### ISSUE TITLE
Community: free to join community requires password input after clicking Join

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10010]
### Description

<img width="1512" alt="Screenshot 2023-03-24 at 11 58 50" src="https://user-images.githubusercontent.com/82375995/227472926-48388011-d258-407d-8b0f-193827542708.png">

1. create open community (free to join)
2. invite a friend there
3. as a person who is invited, click Go to community -> Join community

As result, password prompt is shown

**Comment by jrainville** [comment]
@0x-r4bbit is it ok to not ask for password when we don't need to reveal the address or it would require a big refactor?

**Comment by 0x-r4bbit** [comment]
Oh wow! That should not be there.
Lemme fix this.

**Comment by 0x-r4bbit** [comment]
@anastasiyaig here's a fix https://github.com/status-im/status-desktop/pull/10019
