### ISSUE TITLE
Wrong password error when upgrading from 0.10.0 to 0.11.0

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10027]
### Description

1. i had my main instance of status (0.10.0) installed in Applications folder on Mac
2. i have downloaded https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.11.x/1/
3. i have upgraded to 0.11.0 RC1 (i kept the data folder and replaced the application instance in the Applications)
4. when launching app, i can't login

```
Warning: Display non non-main thread! Deferring to main thread (:0, )
ReEncryptKeyStoreDir error: walk error: unable to re-encrypt key file: decryption error: could not decrypt key with given password, path: /Users/anastasiya/Library/Application Support/Status/data/keystore/0xdee6b86b6801124684a7171368d542ec53a478fde47c789e597e9970612f3d46/UTC--2022-12-05T06-58-02.049541000Z--6c915f5e3806e4220f92a7166039838f27b966a3, name: UTC--2022-12-05T06-58-02.049541000Z--6c915f5e3806e4220f92a7166039838f27b966a3
```

I am convinced i am using correct password

There is some issue with migrations , so upgrading from 0.10.0 to 0.11.0 does not work

**Comment by noeliaSD** [comment]
It happend the same to me.
 
After several minutes waiting on loggin screen, seemed the app was freezed, I quited the app. After that, I tried to login again but the message result was, `Incorrect password`.

**Comment by anastasiyaig** [comment]
thanks for hint @caybro 
we need to post it to release notes for others

**Comment by jrainville** [comment]
Closing as this is a "user error" (it wasn't clear). I opened this to tell users what to do https://github.com/status-im/status-desktop/issues/10039
