### ISSUE TITLE
[Airdrop] Add notification toast in the airdrop process

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10029]
### Description
Review with the design team which should be the messages shown when:
- Aidrop is created correctly.
- Aidrop process failed (determine if there are different failure cases, and if they need to be notified differently to the user).

Once it if defined, add notifications accordingly!

**Comment by noeliaSD** [comment]
Probably duplicated task: https://github.com/status-im/status-desktop/issues/10482

**Comment by endulab** [comment]
Toast messages will be added in #10536.
