### ISSUE TITLE
3-word alias shown on login screen

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10038]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/5377645/227957520-7172fc0b-de0b-4f0d-8d08-cd58644fe8a1.png)

Correct display name configured under Settings/Profile:
![image](https://user-images.githubusercontent.com/5377645/227957773-9e9bee15-2ec9-4f45-972c-a87b8741170e.png)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
> @caybro steps? 
> If you recovered your account following Status old user onboarding path and recover using seed phrase/keycard this should not be the case.
> But if you followed the onboarding path Status new user and then import seed phrase, then this may happen. But in this case you were cheating cause you followed new Status user path, but entered an already user (old) seed phrase. 😆 

I selected "existing user" path and recovered from the seed phrase

**Comment by saledjenic** [comment]
So... you were cheating 😉

**Comment by saledjenic** [comment]
@caybro please, when you have some time, check this PR https://github.com/status-im/status-go/pull/3362 and let me know if the issue is fixed for you (if you build it locally make sure that you deleted status-go lib).

**Comment by caybro** [comment]
> @caybro please, when you have some time, check this PR [status-im/status-go#3362](https://github.com/status-im/status-go/pull/3362) and let me know if the issue is fixed for you (if you build it locally make sure that you deleted status-go lib).

Do I have to reset my account, and restore it from the seed phrase again? Because right now, it didn't fix the problem for me

**Comment by saledjenic** [comment]
Yes, you need to remove your local Status folder, build and run this PR and restore your account using the same seed phrase you faced an issue with.

**Comment by saledjenic** [comment]
We can add a function which will check the state and fix it for you, but I guess that's not needed at this moment, such actions will be mandatory after MVP, for fixing possible issues like this one.

**Comment by caybro** [comment]
OK, let's close it then; I'll reopen if the issue persists after seed phrase restoration

**Comment by alaibe** [comment]
some improvements here: https://github.com/status-im/status-go/pull/3362
