### ISSUE TITLE
Re-encrypt db screen

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#10037]
When re-encryption of the db happens, it may take a lot of time depending on db size, we needs screens for this

Flows when re-encryption happens:
migrate profile to keycard
convert keycard user to regular keycard
change password

@alaibe check if there is a indicator of progress
@John-44 @benjthayer design the screens

**Comment by alaibe** [comment]
As far as I can tell, i don't see anything about getting a progress indicator. However to avoid the infinite spinner, we could do it "Microsoft way". Assume it takes 1 hour and add 1 percentage per minutes
And when it completes, it speed up to the 100%

**Comment by alaibe** [comment]
@jrainville for the release it is a one time migration, but see in the description there is other cases where we re-encrypt the db

**Comment by caybro** [comment]
Any `BusyIndicator` will do

**Comment by jrainville** [comment]
Aaaah, you're right. My bad, I read it all fast

**Comment by iurimatias** [comment]
for the RC this should be something simple, just a message on the UI like "do not turn off the app" etc..

**Comment by alaibe** [comment]
For this one-off, that should not happen, as the re-encryption is before login

**Comment by StateOf-Vlado** [comment]
Note for Automation testing: remove tag @mayfail for:
Scenario: The user can change the password and login with new password
https://github.com/status-im/status-desktop/blob/master/test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/test.feature#L51

**Comment by benjthayer** [comment]
Hey @jrainville kicking this off now as a priority. Should have designs ready in the next day or so, allowing time to review with Sale/John

**Comment by alexandraB99** [comment]
@benjthayer what is the design status here?

**Comment by benjthayer** [comment]
> @benjthayer what is the design status here?

Hi @alexandraB99 designs were started for this but other items were prioritised. 

@John-44 I could loop back to finalise this prior to starting WalletConnect work?

**Comment by benjthayer** [comment]
Re-encryption designs now complete and added into the relevant existing flows @alexandraB99 @jrainville @saledjenic :

**Migrating profile keypair from Keycard to Status**
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15715-371808&mode=design&t=rJ0YF50rEMlafVVb-4

**Migrating profile keypair from Status to Keycard**
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=7258-182696&mode=design&t=rJ0YF50rEMlafVVb-4

**Changing password**
[https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=20164-319037&mode=design&t=rJ0YF50rEMlafVVb-4](https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=20164-311411&mode=design)

**Comment by saledjenic** [comment]
@benjthayer thanks for the update on this. 
@alaibe I am pretty sure this is already implemented, QAs  @anastasiyaig can confirm.

**Comment by anastasiyaig** [comment]
@saledjenic it was implemented partially (only 1 scenario was addressed). Please see the designs - there are some changes we discussed in All hands several weeks ago we need to address.

**Comment by anastasiyaig** [comment]
@saledjenic for example changing password flow in latest master
<img width="1512" alt="Screenshot 2023-10-30 at 15 50 53" src="https://github.com/status-im/status-desktop/assets/82375995/726f874a-33f5-4682-8fe6-1f9a3f5a450c">


<img width="1512" alt="Screenshot 2023-10-30 at 15 50 45" src="https://github.com/status-im/status-desktop/assets/82375995/f8867491-fde8-4236-b61b-0255881dcf74">

**Comment by alexandraB99** [comment]
@benjthayer for Password Change, I see designs here https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=1646-297422&mode=design&t=QiVEMhvhg9eBComJ-4 and here https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=11-106858&mode=design&t=gyA9qpLModHumc5A-4.

Should these be the same thing/flow?

**Comment by benjthayer** [comment]
> @benjthayer for Password Change, I see designs here https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=1646-297422&mode=design&t=QiVEMhvhg9eBComJ-4 and here https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=11-106858&mode=design&t=gyA9qpLModHumc5A-4.
> 
> Should these be the same thing/flow?

Hey @alexandraB99 yes as part of the recent profile work, we have created a new `Password` nav item in settings underneath the `Profile` nav item where change password used to be.

https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=11-109778&mode=design&t=ypGuFyfondGMCsnN-4

This replaces the below designs:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=20164-319037&mode=design&t=rdoz3T7HWGEMUp53-4

cc @saledjenic

**Comment by alexandraB99** [comment]
Biometrics option to be added here: https://github.com/status-im/status-desktop/issues/13302

**Comment by anastasiyaig** [comment]
Test cases created: https://ethstatus.testrail.net/index.php?/suites/view/5308&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=56768
Bugs found during testing in master:
https://github.com/status-im/status-desktop/issues/13748
https://github.com/status-im/status-desktop/issues/13763
https://github.com/status-im/status-desktop/issues/13747
https://github.com/status-im/status-desktop/issues/13783
