### ISSUE TITLE
Can not accept incoming contact request

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10032]
# Bug Report
Freshly restored account, I have a pending incoming contact request which I can't accept:

![image](https://user-images.githubusercontent.com/5377645/227919573-6ee8980e-bf18-49bd-9930-614f40015d59.png)

```
DBG 2023-03-27 12:39:45.661+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=24199 file=core.nim:27 rpc_method=wakuext_acceptLatestContactRequestForContact
ERR 2023-03-27 12:39:45.664+02:00 rpc response error                         topics="rpc" tid=24199 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_acceptLatestContactRequestForContact, code:-32000, message:record not found ]\n"
ERR 2023-03-27 12:39:45.664+02:00 error doing rpc request                    topics="rpc" tid=24199 file=core.nim:40 methodName=wakuext_acceptLatestContactRequestForContact exception="\nstatus-go error [methodName:wakuext_acceptLatestContactRequestForContact, code:-32000, message:record not found ]\n"
ERR 2023-03-27 12:39:45.664+02:00 an error occurred while accepting contact request topics="contacts-service" tid=24199 file=service.nim:442 msg="\nstatus-go error [methodName:wakuext_acceptLatestContactRequestForContact, code:-32000, message:record not found ]\n"
```

## Steps to reproduce

Click on "accept" in either Settings or Profile Dialog (same behavior)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by MishkaRogachev** [comment]
Should be fixed here, i'll double check it after merging: https://github.com/status-im/status-desktop/issues/10032

**Comment by caybro** [comment]
> Should be fixed here, i'll double check it after merging: #10032

Where? :) The link leads to itself

**Comment by MishkaRogachev** [comment]
> status-im/status-go#3327

fixed :)

**Comment by MishkaRogachev** [comment]
> > Should be fixed here, i'll double check it after merging: #10032
> 
> Where? :) The link leads to itself

fixed :)

**Comment by MishkaRogachev** [comment]
Upd: this one is part of https://github.com/status-im/status-desktop/issues/8702 problem
