### ISSUE TITLE
Contacts not restored correctly, effectively blocked out of any 1-1 conversation

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10040]
# Bug Report

This is a peculiar situation:
- on a restored account, existing contacts got into semi-broken state, they all show as "pending":
![image](https://user-images.githubusercontent.com/5377645/227959050-dbd6fd56-4396-4605-947c-a594e08d8583.png)

- now, as we removed the ability to cancel/retract outgoing CRs, I can no longer chat to _anyone_ until/unless _they_'ve sent me a message (I appear as a mutual contact to others); no existing chats:

![image](https://user-images.githubusercontent.com/5377645/227959570-073731da-8d46-43ad-af0e-b74d40a47ac1.png)

- as soon as the other party sends a message, we are mutual contacts again:
![image](https://user-images.githubusercontent.com/5377645/227960301-b829397c-ea71-460c-a0d3-3fe718adff46.png)

The overall situation becomes even _much_ worse with those 2 additional bugs:
- group chat is semi-broken too: https://github.com/status-im/status-desktop/issues/10030
- can not accept _incoming_ contact request: https://github.com/status-im/status-desktop/issues/10032

All in all, this seems like a lonely planet with no one to chat to :)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by osmaczko** [comment]
@caybro, I cannot reproduce this issue on either version 0.11.0 RC2 or the master branch. Can you please attempt to reproduce it on your instance?

https://user-images.githubusercontent.com/33099791/229485182-eb4d6c7f-9ef6-41a4-b52b-4ce402da92c0.mp4

**Comment by osmaczko** [comment]
I spotted a different bug though. I can't chat with correctly restored contacts.

https://user-images.githubusercontent.com/33099791/229492610-e403f907-a1cd-4d44-b086-d3f2eacfdf2c.mp4

**Comment by caybro** [comment]
Interesting... yeah I can always reproduce the reported issue but that might be due to some bad migration? I've never seen your second problem on the other hand

**Comment by caybro** [comment]
> @caybro, I cannot reproduce this issue on either version 0.11.0 RC2 or the master branch. Can you please attempt to reproduce it on your instance?

Just tested, I can no longer reproduce :) Nice job
