### ISSUE TITLE
[Community Mint Collectibles] Implement `Airdrop` footer option

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10047]
### Description
Enable navigation to airdrop section when user clicks on `Airdrop`:

![Screenshot 2023-03-28 at 11 30 19](https://user-images.githubusercontent.com/97019400/228193737-f08103a1-c288-425f-808b-1335006c1bbc.png)

Navigate to `New Airdrop` page with the preselected token data filled --->

![Screenshot 2023-03-28 at 11 30 35](https://user-images.githubusercontent.com/97019400/228193738-8fba1377-a5f4-4fa6-bc62-185f861c941d.png)

**Comment by xAlisher** [comment]
I don't have the slightest idea about this behavior

**Comment by noeliaSD** [comment]
> I don't have the slightest idea about this behavior

Ok. Could you confirm what should happen then when user clicks on this `Airdrop` footer option? Thanks!!

**Comment by John-44** [comment]
> > I don't have the slightest idea about this behavior
> 
> Ok. Could you confirm what should happen then when user clicks on this `Airdrop` footer option? Thanks!!
> 
> Maybe @John-44 you can help with that?!

It should take the user to the 'New Airdrop' screen with the token pre-selected.  

In the future we might want to consider also having 'New Airdrop' live in a dialogue as well as a full screen in the 'Airdrop' section, but for now I think it's fine to just redirect the user to the 'New airdrop' screen in the Airdrop section with the token preselected
