### ISSUE TITLE
[Community Mint Collectibles] Implement Retail footer option 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10049]
### Description
This flow still needs design.

[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=27140%3A520947&t=fYonnwnxGvWlnMms-1)
![Screenshot 2023-03-28 at 11 38 55](https://user-images.githubusercontent.com/97019400/228199198-54badfa4-ca63-442c-b0b0-5086c3d9e543.png)

**Comment by caybro** [comment]
@alexandraB99 perhaps should be postponed for after 0.14 if it doesn't have any design yet? @John-44

**Comment by John-44** [comment]
> @alexandraB99 perhaps should be postponed for after 0.14 if it doesn't have any design yet? @John-44

Oh yes, we shouldn't be adding the Retail option to the footer until we've built the Retail functionality!! ;-)

I'm hoping we will be able to start work on the Retail functionality in either the 0.19 or 0.20 milestone.  But I haven't even created those milestones in github yet, so we can't attach this issue to these milestones.  Humm, close this issue or create a 0.19 milestone??

**Comment by alexandraB99** [comment]
@caybro , @John-44 done.
