### ISSUE TITLE
Activity center: being kicked from community notification looks broken

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10054]
Here's a notification in my notification center that I'm seeing after I've been kicked from a community:

![Screenshot from 2023-03-28 13-26-20](https://user-images.githubusercontent.com/445106/228222044-65534fcb-58e4-46e7-82a3-d56ce42744e4.png)

**Comment by imagiMary** [comment]
Hi @0x-r4bbit @caybro, I've come across this 'Kicked' notification in the context of - when a user leaves a community, the owner of the community receives a blank ‘You were kicked from’ entry in their Activity Centre.

Version: 0.11.0-rc.2
OS: Ubuntu 22.10 

https://user-images.githubusercontent.com/124154641/230054772-a757a306-18f3-4929-8fa3-5821fa6ec52a.mp4

&nbsp; 
Preconditions: Alice is the owner of a community. Bob is a member of Alice's community. 

<ins>Steps to reproduce:</ins>
1. Bob leaves Alice's community.

<ins>What currently incorrectly happens:</ins>

2. Alice receives a ‘You were kicked from’ notification in their activity centre.

<ins>What is supposed to happen:</ins>

2. Alice should not receive a ‘You were kicked from’ notification when a user leaves one of their communities. 

&nbsp;

**Comment by borismelnik** [comment]
@0x-r4bbit @imagiMary its not reproduced for me on `latest master`, but reproduced on `0.11.0`


![Image](https://github.com/status-im/status-desktop/assets/82511785/ff6cbdfa-6357-486a-a818-bf1ef7a1babd)

think we can close it as fixed.
