### ISSUE TITLE
Missing unread message badges on community and channels

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10058]
# Bug Report

## Description

In the 0.11RC1, I opened the app after a night's sleep. I saw that I have 3 AC notifications, 2 of them on the community, but the community didn't have a dot, nor a badge.

If I manually go in the channel, I can see that there are new messages. Some other channels that didn't have mentions for me also had messages and didn't have the unread message dot.

#### Expected behavior

All channels that have unread messages that are not muted should have the dot. If those are mentions or replies, have the badge with the appropriate number.

### Additional Information

- Status desktop version: 0.11RC1

**Comment by caybro** [comment]
Yup, similar erratic behavior in master too; it usually settles (gets back in sync) after using the app for a while. I guess once the channels are in memory?

**Comment by caybro** [comment]
The opposite happens too: a chat category is highlighted even though there's no new messages (or at least they're not visible)

**Comment by caybro** [comment]
This picture illustrates both problems quite visibly; "Core Desktop" category highlighted eventhough there are no new messages; "Core Mobile" and its "mobile-ui" channel has new messages but no badge is displayed in the primary nav

![image](https://user-images.githubusercontent.com/5377645/228279931-4484876a-533d-486e-94bb-048aa093df98.png)
