### ISSUE TITLE
[Community Mint Collectibles] Add new `key` role into `tokensModel`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10053]
### Description

- Add a unique identifier for items in model `tokensModel`.
- Use role `key` for that propose.
- To calculate that unique id, use `contract address` + `chainId` and create a `hash`.

After that, it will be needed an update on qml side to use `key` instead of `index`. 
Related UI task: https://github.com/status-im/status-desktop/issues/10013

**Comment by endulab** [comment]
Added in #10052
