### ISSUE TITLE
group chat: member list empty

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10066]
# Bug Report

Regression (0.11/master): after https://github.com/status-im/status-desktop/pull/10046 got merged, the member list of private chat groups comes up empty:

![image](https://user-images.githubusercontent.com/5377645/228384633-bfbfc3af-323d-41bf-aa87-7644fd76afcd.png)

(community chats seem to be not affected)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by osmaczko** [comment]
I don't really see the correlation with https://github.com/status-im/status-desktop/pull/10046, the only change done there was: 
https://github.com/status-im/status-go/compare/e9482e3974a2f82bd6a23f0c9e861b5bca23f472...6eb39eca7533ba730194cf440d5c617b693bba14#diff-d068c64014b3b3b4240fbb5d0ad5e59923512e4369bd0982363a82a68d4b054f

**Comment by caybro** [comment]
No no, I'm not saying your fix is the culprit here, there have been other changes in status-go that got merged too. Just pointing out approximate time window

**Comment by caybro** [comment]
This seems to be some Schroedinger bug (2 different/subsequent starts, no code changes at all):

![Snímek obrazovky z 2023-03-29 14-47-21](https://user-images.githubusercontent.com/5377645/228540196-bfb7077e-303a-45d0-975e-6d321c05356a.png)
![Snímek obrazovky z 2023-03-29 14-48-03](https://user-images.githubusercontent.com/5377645/228540200-04d2a1fb-b49f-42b1-905c-a50015bac68b.png)

Sigh :/

**Comment by osmaczko** [comment]
> This seems to be some Schroedinger bug (2 different/subsequent starts, no code changes at all):

Those are the best to debug :sweat_smile:
