### ISSUE TITLE
Profile: user picture (avatar) is not saved when changing it getting back from Password screen

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10069]
### Description

1. open status
2. click  I am new to Status
3. click import a seed phrase
4. fill in known seed
5. on the screen Your profile, fill in display name and dont change avatar
6. click Next
7. when being on `Your emojihash and identicon ring` screen, click back button
8. upload any custom pic for your avatar
9. finish onboarding

As result, user custom pic is not applied

```
Warning: qrc:/app/AppLayouts/Profile/stores/ProfileStore.qml:19: ReferenceError: userProfile is not defined (qrc:/app/AppLayouts/Profile/stores/ProfileStore.qml:19, )
Warning: qrc:/app/AppLayouts/Profile/stores/ProfileStore.qml:18: ReferenceError: userProfile is not defined (qrc:/app/AppLayouts/Profile/stores/ProfileStore.qml:18, )
Warning: qrc:/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:12: ReferenceError: mainModule is not defined (qrc:/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:12, )
```

**Comment by iurimatias** [comment]
duplicate (similar?) of https://github.com/status-im/status-desktop/issues/10099
