### ISSUE TITLE
Cannot send mentions in an edit

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10074]
# Bug Report

## Description

If you try to edit a message and mention someone, it will work in the input, but once sent, it will not be considered a mention

## Steps to reproduce

1. Send a normal message
2. Start editing that message
3. add a mention or remove everything to add a mention
4. It works
5. press enter

message is sent and the mention is plain text

**Comment by caybro** [comment]
Editing a message generally screws up any formatting you may have had before
