### ISSUE TITLE
it takes more than 1 minute to run 0.10.0 release on mac m1

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#10079]
https://user-images.githubusercontent.com/11790366/228757001-3f094949-885b-401c-a3c3-d7a5d23dab52.mov

the app just hangs after 10 sec for ~40 seconds

**Comment by iurimatias** [comment]
closing as duplicate of other tasks looking to improve startup time. the situation is also a bit better on apple silicon builds
