### ISSUE TITLE
Message with text and image can not be edit

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#10072]
# Bug Report

## Description

Message with text and image can not be edit
P.S. Simple message with only one image can't be edit too

## Steps to reproduce

1. Send message with the image
2. Check edit pop-up

#### Expected behavior

Edit pop-up is present, and text can be edited

#### Actual behavior

The edit pop-up is absent.
If you'll try to edit you last msg by up arrow, edit view will be open, but msg won't be edited

![image](https://user-images.githubusercontent.com/117639195/228604232-2e958c42-4684-439f-8029-f65e25c680c1.png)

### Additional Information

- Status desktop version: 0.11
- Operating System: macos

**Comment by borismelnik** [comment]
@jrainville are you that we need it for this iteration? In general, we can change the text just for emoji and text messages. 
Current implementation of `EditMessage` involves changes of `ContentType` of original message to `EditMessage` which similar with `Text` only. I can implement a new way to edit image messages, but it mostly `feature` and must be tested as new feature and so on. Also, as a quick fix can add the blocker to input field to avoid changes for image messages.

PS: Previously, we sent image messages with text as several messages where one was a text message.

**Comment by borismelnik** [comment]
let me check, I think I can block it just for `last message content type == image`

**Comment by jrainville** [comment]
Is there a way to modify the text only of the image message? Is it mostly hard to fix because of our QML or because the backend doesn't support that?

**Comment by borismelnik** [comment]
@jrainville I merged [this pr] which helps to avoid open edit popup for image messages.
Basically, we need to add new type of message like `EditedImageMessage` or add a field like `imagePath` to `EditMessage` to understand that message was an `ImageMessage`. As I said before, no backend support editing just `Text` and `Emoji` messages and it change original message type to `EditMessage`.
