### ISSUE TITLE
Prepare pytest+squish concept of tests

### ISSUE THREAD

**Issue by StateOf-Vlado** [status-im/status-desktop#10093]
### Description

Adapt tests from the settings suite to new concept squish+pytest

### Acceptance Criteria

Tests from the Settings suite can be executed in the new framework structure

**Comment by StateOf-Vlado** [comment]
It's good to add a description of the test in TestRail.
Also, we can integrate the Allure test report https://docs.qameta.io/allure/
And Jenkins.

**Comment by iurimatias** [comment]
closing since this task is in the done state
