### ISSUE TITLE
Sync QR code scanning doesn't work from linux AppImage

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10101]
# Bug Report

Tested by @osmaczko 

```
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Warning: Focus mode selection is not supported (:0, )
Warning: Starting camera without viewfinder available (:0, )

(nim_status_client:1354141): GStreamer-CRITICAL **: 17:47:02.331: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed

(nim_status_client:1354141): GStreamer-CRITICAL **: 17:47:02.331: gst_object_unref: assertion 'object != NULL' failed
Warning: CameraBin error: "GStreamer error: negotiation problem." (:0, )
Warning: CameraBin error: "Internal data stream error." (:0, )
```

![image](https://user-images.githubusercontent.com/25482501/229101574-9592c9b5-ca9a-4cd0-bd60-2516dd8f5e0a.png)

**Comment by caybro** [comment]
Looks like an AppImage/desployment problem; we are not bundling:
`/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so`

**Comment by igor-sirotin** [comment]
@caybro can you take a look at this, if it doesn't take much time?
I'm on Mac, don't want to setup linux vm builds just for this 🤦

**Comment by caybro** [comment]
> @caybro can you take a look at this, if it doesn't take much time? I'm on Mac, don't want to setup linux vm builds just for this facepalm

I can try... but the whole AppImage business only works on Ubuntu :/

**Comment by osmaczko** [comment]
> > @caybro can you take a look at this, if it doesn't take much time? I'm on Mac, don't want to setup linux vm builds just for this facepalm
> 
> I can try... but the whole AppImage business only works on Ubuntu :/

I don't have Ubuntu anymore but I can run AppImages just fine on Fedora. @caybro can you please elaborate what you meant by "only works on Ubuntu" before I start to investigate the issue?

**Comment by jrainville** [comment]
I can confirm that the QR scanner worked fine in the sandbox in `7c1c178d37e84c110c0e6f65e914e017b7b006cb`, which is the first time it was introduced in master.

Then, when Igor added it in the onboarding, it stopped working, even in the sandbox `14c264e350f0c21868eaf0e3b4684e0b4ec7690c`. 
He also did  a lot of manipulation on the Makefile, so I'll try to see what's the culprit

**Comment by caybro** [comment]
> In the working commit, the logs are
> 
> ```
> ("qrc:/", "/home/jonathan/dev/status-desktop/ui/StatusQ/build/sandbox", "qrc:/qt-project.org/imports", "/home/jonathan/Qt5.15/5.15.2/gcc_64/qml")
> Focus mode selection is not supported
> needed to resize
> size:  0 , new size:  1843200
> ```
> 
> In the failing commit, the logs are
> 
> ```
> ("qrc:/", "/home/jonathan/dev/status-desktop/ui/StatusQ/build/sandbox", "qrc:/qt-project.org/imports", "/home/jonathan/Qt5.15/5.15.2/gcc_64/qml")
> Focus mode selection is not supported
> Starting camera without viewfinder available
> 
> (Sandbox:317990): GStreamer-CRITICAL **: 16:42:59.641: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed
> 
> (Sandbox:317990): GStreamer-CRITICAL **: 16:42:59.641: gst_object_unref: assertion 'object != NULL' failed
> CameraBin error: "GStreamer error: negotiation problem."
> CameraBin error: "Internal data stream error."
> ```

Most likely some GStreamer plugins missing in the AppImage
