### ISSUE TITLE
Enable Admin role (in addition to Owner role)

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#10114]
Now that we have Community level token permissions working, we need to add the Admin role so that a Community Owner can appoint multiple admins to help them manage the community.  

The differences between the Owner and Admin roles are as follows:

| Ability  | Owner | Owner, using install without community private key | Admin |
| :------------- | :------------- | :------------- | :------------- |
| Ability to access the Community admin area | Yes | Yes | Yes |
| Ability to access Community admin functions outside the Admin area | Yes | Yes | Yes |
| Edit Community (inc. edit tags, logo, banner, request to join required setting, pin setting, etc...) | Yes | Yes | Yes |
|  Create, edit and delete channels or categories | Yes | Yes |  Yes |
|  Reorder channels and categories | Yes | Yes | Yes |
|  Create, edit and delete 'become member' permissions | Yes | Yes |  Yes |
|  Create, edit and delete 'become admin' permissions | Yes | Yes | No |
| Create, edit and delete 'channel' permissions  | Yes | Yes | Yes |
| Receive 'request to join' notifications, and ability to Accept or Reject (see *Note 1* below)  | Yes | Yes | Yes |
| Kick and ban members (see *Note 1* below)  | Yes | Yes | Yes |
| Delete any message in the Community | Yes | Yes  | Yes |
| Pin messages, if 'Any member can pin a message' is switched off | Yes | Yes | Yes |
| View statistics on Overview screen  | Yes | Yes | Yes |
|  Mint Tokens | Yes | Yes | No |
|  Airdrop Tokens | Yes | Yes | No |
| Access Community private key  | Yes | No | No |

*Note 1:* When an Admin accepts a 'request to join', or kicks or bans a member, this command is sent to the Owner Node which then performs the required action. If the Owner Node is not online, the required action will be performed by the Owner Node the next time the Owner Node comes online.

*Note 2:* The "Owner, using install without community private key" abilities are for the scenario where (for example) the Owner has the community private key in their Status Desktop instance running on their Desktop computer, but is accessing their community from a Status Desktop instance running on their laptop that *does not* contain the community private key.

*Note 3:* In the community admin area, the "Mint tokens" and "Airdrop" sections in the secondary nav should be hidden from Admins (e.g. only Owners should see these two sections in the admin area secondary nav).

**Comment by mprakhov** [comment]
Questions for tomorrow's meeting:
1. Is this feature only for the closed community?
2. Will the `Admin` have any specific icon in the members list? (like a crown for an owner)?
3. Can the `Owner` set admin rights not only via permissions settings? If yes, I need a UI workflow (or should it be done in a separate ticket)
4. Can the `Owner` remove `Admin` rights? What if the user is `Admin` by admin permissions?
5. Should the `Owner` approve `Admins` who are joining as admins by permissions? (What if the `Owner` removes `Admin` permissions, the user quit the community and rejoins again)
6. Should `Admins` have any UI telling that ban/kick/request to join is waiting for an `Owner` approval?
7. `Admin` does ban/kick/request to join related to another member - how will it be displayed for the Owner/ 2 Owners?
8. How to become an `Owner` without a community private key (steps... is it Device sync?)
cc @John-44  @jrainville @anastasiyaig

**Comment by mprakhov** [comment]
@John-44 have a question:
Should we hide this option for `admins` or disable it (make inactive)?
1. Transfer ownership btn in view community
![image](https://user-images.githubusercontent.com/117639195/235104368-8b41f386-cce6-41fb-b4a7-dbc8ccf65594.png)

2. Backup option
![image](https://user-images.githubusercontent.com/117639195/235104637-2b8b8d30-6372-4a0a-985b-105a5559f2f1.png)

3. Invite, airdrop, backup in community overwiew
![image](https://user-images.githubusercontent.com/117639195/235105021-6355ebd3-1011-4940-88ab-60f0c80ed9bd.png)

4. Become admin in permission configuration
![image](https://user-images.githubusercontent.com/117639195/235105286-cb6c8023-4311-4662-9352-865c3990c413.png)

5. Admin settings. We can hide/make inactive Edit, duplicate, delete for admin settings or hide the admin settings itself
![image](https://user-images.githubusercontent.com/117639195/235105611-5e3ff672-de8c-4015-a84d-450a811c1bb3.png)

**Comment by mprakhov** [comment]
cc @benjthayer maybe you know the answer too 😄

**Comment by John-44** [comment]
> @John-44 have a question: Should we hide this option for `admins` or disable it (make inactive)?
> 
> 1. Transfer ownership btn in view community
>    ![image](https://user-images.githubusercontent.com/117639195/235104368-8b41f386-cce6-41fb-b4a7-dbc8ccf65594.png)

Hide

> 2. Backup option
>    ![image](https://user-images.githubusercontent.com/117639195/235104637-2b8b8d30-6372-4a0a-985b-105a5559f2f1.png)

Hide

> 3. Invite, airdrop, backup in community overwiew
>    ![image](https://user-images.githubusercontent.com/117639195/235105021-6355ebd3-1011-4940-88ab-60f0c80ed9bd.png)

Hide Airdrop and Backup, but Invite should be shown and remain active

> 4. Become admin in permission configuration
>    ![image](https://user-images.githubusercontent.com/117639195/235105286-cb6c8023-4311-4662-9352-865c3990c413.png)

Show, but in inactive state

> 5. Admin settings. We can hide/make inactive Edit, duplicate, delete for admin settings or hide the admin settings itself
>    ![image](https://user-images.githubusercontent.com/117639195/235105611-5e3ff672-de8c-4015-a84d-450a811c1bb3.png)

Show, but hide the 'Edit', 'Duplicate' and 'Delete' buttons.

**Comment by John-44** [comment]
@mprakhov @jrainville ^

**Comment by mprakhov** [comment]
As per today's discussion with @0x-r4bbit - we can split status-go work and proceed parallel.
What was done on the status-go side:
- added new role CommunityMember_ROLE_ADMIN (could be deleted)
- owner set up admin role based on token permissions
- admin event for "patching" the community via subscription
- admin event verification on the receiver node
- core for unit testing admin changes
- test for testing editing the community by admin
- stub tests (must be implemented)
- methods, which should be used for updating the community based on admin event

What needs to be implemented on the status-go side:
- validating with timeout admin permissions by owner node (we have logic for members)
- test for changing tokenPermissions
- stub tests (stub test means that this scenario is not implemented)
- sending different admin events and applying them to other nodes
- double-check encryption functionality

@0x-r4bbit it would be nice if you can take admin scenarios:
- CommunityAdminEvent_COMMUNITY_MEMBER_TOKEN_PERMISSION_CHANGED
- CommunityAdminEvent_COMMUNITY_MEMBER_TOKEN_PERMISSION_DELETED
- CommunityAdminEvent_COMMUNITY_REQUEST_TO_JOIN_ACCEPTED
- CommunityAdminEvent_COMMUNITY_REQUEST_TO_JOIN_REJECTED
- CommunityAdminEvent_COMMUNITY_MEMBER_KICK
- CommunityAdminEvent_COMMUNITY_MEMBER_BAN
and tasks
- validating with timeout admin permissions by owner node (we have logic for members)
- test for changing tokenPermissions

my current working branch: https://github.com/status-im/status-go/tree/mp/permissions
it can be taken as a root one for working and merging our parts of work

cc @jrainville

**Comment by 0x-r4bbit** [comment]
Thank for the writeup @mprakhov !
I'll look into these

**Comment by 0x-r4bbit** [comment]
Dumping this here so we don't forget about it.
My instance crashed with:

```
/home/rabbit/projects/status-im/status-desktop-2/src/nim_status_client.nim(197) nim_status_client
/home/rabbit/projects/status-im/status-desktop-2/src/nim_status_client.nim(194) mainProc
/home/rabbit/projects/status-im/status-desktop-2/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/home/rabbit/projects/status-im/status-desktop-2/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/home/rabbit/projects/status-im/status-desktop-2/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/home/rabbit/projects/status-im/status-desktop-2/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(559) onSlotCalled
/home/rabbit/projects/status-im/status-desktop-2/src/app_service/service/chat/service.nim(257) onAsyncGetChatsByChannelGroupIdResponse
/home/rabbit/projects/status-im/status-desktop-2/src/app/core/eventemitter.nim(58) emit
/home/rabbit/projects/status-im/status-desktop-2/src/app/modules/main/chat_section/controller.nim(115) :anonymous
/home/rabbit/projects/status-im/status-desktop-2/src/app/modules/main/chat_section/io_interface.nim(37) onChatsLoaded
/home/rabbit/projects/status-im/status-desktop-2/src/app/modules/main/chat_section/module.nim(387) onChatsLoaded
/home/rabbit/projects/status-im/status-desktop-2/src/app/modules/main/chat_section/module.nim(246) buildChatSectionUI
/home/rabbit/projects/status-im/status-desktop-2/src/app/modules/main/chat_section/model.nim(197) setData
/home/rabbit/projects/status-im/status-desktop-2/vendor/nimqml/src/nimqml/private/qabstractitemmodel.nim(236) endResetModel
/home/rabbit/projects/status-im/status-desktop-2/vendor/nimqml/src/nimqml/private/qabstractitemmodel.nim(45) dataCallback
/home/rabbit/projects/status-im/status-desktop-2/vendor/nimqml/src/nimqml/private/qabstractitemmodel.nim(37) data
/home/rabbit/projects/status-im/status-desktop-2/src/app/modules/main/chat_section/model.nim(120) data
/home/rabbit/projects/status-im/status-desktop-2/src/app/modules/main/chat_section/item.nim(156) amIChatAdmin
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:747: run-linux] Segmentation fault (core dumped)
```
