### ISSUE TITLE
Wallet: dot is not considered as delimiter for Send modal

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10125]
### Description

Regardless of user locale, it seems most people are used to using "." as a decimal separator when entering numbers. To prevent confusion / frustration, we should only allow that decimal separator for user input. For displaying numbers, we'll still respect the user's locale.

<img width="1512" alt="Screenshot 2023-04-03 at 13 01 51" src="https://user-images.githubusercontent.com/82375995/229478753-641edf58-755f-4da7-9502-e54839d99170.png">

<img width="1512" alt="Screenshot 2023-04-03 at 13 00 50" src="https://user-images.githubusercontent.com/82375995/229478777-1ae3ecf1-4346-486f-b855-b07cc350c91f.png">

**Comment by caybro** [comment]
@anastasiyaig what locale is your OS using? If you run your OS in Russian, this is totally expected; you should use `,` as a decimal separator

**Comment by caybro** [comment]
Just to clarify, accepting `.` as an addition or fallback could be added

**Comment by alaibe** [comment]
@caybro as this is for input we should support both, entering `1,2` and `1.2`
wdyt?

**Comment by caybro** [comment]
> @caybro as this is for input we should support both, entering `1,2` and `1.2`
> wdyt?

Yeah, I think it makes sense

**Comment by alaibe** [comment]
Latest: we will only support numbers with decimal point for decimal point input

**Comment by dlipicar** [comment]
Updating description according to the latest discussion

**Comment by caybro** [comment]
> Latest: we will only support numbers with decimal point for decimal point input

WHAT? So (at least in my case), the app will correctly display `,` but in some places will require me to use `.`?

**Comment by caybro** [comment]
> @caybro yeah, we just had a chat with John about this. The system locale will be used for displaying, but user input will always use `.` as decimal separator.

SAD PANDA... let's wait for ppl reporting issues with this :/

In the meantime, feel free to re-assign this bug to me, I'll fix it properly in my free time later

**Comment by alaibe** [comment]
@caybro no problem, the rationale is to keep it simple to start with and augment with need

Why decimal point vs locale
=> web being the norm or at least what is the most use, `,` is not allowed in input type number, only `.`

**Comment by dlipicar** [comment]
> @dlipicar I meant really later :)

@caybro haha sorry, got that wrong. I'll take care of it then!
