### ISSUE TITLE
[tests]: Add tests execution for nightly and release

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10121]
### Description

- find out if we execute autotests for master builds and release builds
- set up the execution (jobs) in case we dont

here are the jobs : https://ci.infra.status.im/job/status-desktop/
master and release respectively

What is expected:

- existing autotests are launched for master build on nightly basis
- existing autotests are launched for release build on nightly basis 

Do not run autotests if no commits were done after last tests run

Provide some kind of reporting (or job links) where QA team can review and analyse the results of execution

**Comment by anastasiyaig** [comment]
@glitchminer adding u for transparency

**Comment by anastasiyaig** [comment]
https://github.com/status-im/status-desktop/pull/10305

**Comment by StateOf-Vlado** [comment]
@anastasiyaig  can we run the release build manually when we need it?

**Comment by anastasiyaig** [comment]
> @anastasiyaig can we run the release build manually when we need it?
Manual running prepared: https://ci.infra.status.im/job/status-desktop/job/manual/ and we able to run any branch

I suspect something is incorrect here: I launched the job with `release 11.0.x` branch and it fails. Also it builds the artifacts from the beginning when instead should pick up the already existing ones (recent) @StateOf-Vlado

**Comment by anastasiyaig** [comment]
https://ci.infra.status.im/job/status-desktop/job/manual/

**Comment by StateOf-Vlado** [comment]
@anastasiyaig  test results you can find if follow next steps:

1) Click logs for Linux e2e squish in matrix
![Image](https://user-images.githubusercontent.com/128374224/233553213-529978b7-da86-48e4-b4c8-948f77750556.png)

2) in popup click link: Build status-desktop >> system >> linux >>x86_64 >> test-e2e
![Image](https://user-images.githubusercontent.com/128374224/233553337-93f40ccf-fe79-435f-b359-5f29eb54967a.png)
