### ISSUE TITLE
Messages: editing a leading text for album is not possible

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10123]
### Description

1. send a message with text and some pictures (album) in any chat
2. click edit
3. change the text
4. save

As result, the text is not changed

https://user-images.githubusercontent.com/82375995/229468242-2fafdca3-f7d8-4142-8de5-17de7395a64d.mp4

**Comment by jrainville** [comment]
Duplicate of https://github.com/status-im/status-desktop/issues/10072
