### ISSUE TITLE
Connection toasts take up a lot of CPU time

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#10124]
Need to find a way to reduce this

**Comment by Khushboo-dev-cpp** [comment]
https://user-images.githubusercontent.com/60327365/229512519-d88b376a-f960-44c5-bdaf-b2624b395203.mov

**Comment by Khushboo-dev-cpp** [comment]
For me the performance is not that bad, but we have events coming form go side that cannot be optimised further, because of which we are retrying action every 30 secs causing bad behaviour for sure. We are removing automatic retries after discussion with John and Ben, and giving user  option to update manually by "Retry now" or the app will update all wallet data after 10 mins as per current implementation.

**Comment by caybro** [comment]
> For me the performance is not that bad, but we have events coming form go side that cannot be optimised further, because of which we are retrying action every 30 secs causing bad behaviour for sure. We are removing automatic retries after discussion with John and Ben, and giving user option to update manually by "Retry now" or the app will update all wallet data after 10 mins as per current implementation.

Sounds more sensible; is the 10 minute retry interval always happening, or just in case of previous failure?

**Comment by Khushboo-dev-cpp** [comment]
> > For me the performance is not that bad, but we have events coming form go side that cannot be optimised further, because of which we are retrying action every 30 secs causing bad behaviour for sure. We are removing automatic retries after discussion with John and Ben, and giving user option to update manually by "Retry now" or the app will update all wallet data after 10 mins as per current implementation.
> 
> Sounds more sensible; is the 10 minute retry interval always happening, or just in case of previous failure?

Its a period refresh that we d on the wallet side.
