### ISSUE TITLE
Review StatusImage sourceSize calculation

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#10139]
### Description

Several remarks were done about how the sourceSize was calculated in `StatusRoundedImage`(logic now moved to `StatusImage`). See https://github.com/status-im/status-desktop/pull/10005#discussion_r1147626143

Investigate what we actually wanted to achieve there, and see if there's some underlying issue why that's needed that we can fix.

**Comment by iurimatias** [comment]
moved to 0.13.0

**Comment by alexandraB99** [comment]
Investigating a bit, I found the reason for this was this https://github.com/status-im/status-desktop/pull/5914 task. Apparently these icons are fetched from a remote location and are not rendered as we'd like. Not sure if setting width/height and fillMode: Image.PreserveAspectFit would just do, I haven't tested.

cc @dlipicar
