### ISSUE TITLE
can't send message to newly accepted contact request

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#10164]
# Bug Report

## Description

can't send message to newly accepted contact request

## Steps to reproduce

1. in the activity center accept a contact request
2. click view profile
3. click send message

![Screen Shot 2023-04-04 at 10 17 56 AM](https://user-images.githubusercontent.com/176720/229822178-5eba3746-781d-4c76-9afc-bf4929657d35.png)

#### Expected behavior

should open the 1 on 1 chat with that user

#### Actual behavior

nothing happens

**Comment by caybro** [comment]
Should be fixed by https://github.com/status-im/status-desktop/pull/10138?

**Comment by jrainville** [comment]
Ah, thanks, I was trying to think which issue/PR fixed that
