### ISSUE TITLE
Adapt StatusBaseButton to handle actions when it is disabled

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#10185]
### Description
We should support having a tooltip when a button us enabled to show additional information 
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=11357-181508&t=ms5yB9BaJn7kdaJF-4 this is a design where this is needed currently
In order to do this we would need to-
1. add a new property "interactive" for the StatusBaseButton and let the UI reflect current enabled=false state with interactive= false
2. Add a tooltip that should be shown in case it is defined by user when the greyed out button is hovered

Also remove and remove DisabledTooltipButton.qml once this is implemented.

**Comment by caybro** [comment]
Related Qt bug: https://bugreports.qt.io/browse/QTBUG-30801 (fixed in QT 6.0)
