### ISSUE TITLE
crash on requesting funds to unknown contact

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1018]
the steps were
1. send a message to a user that is not in the contacts (I did for 3esmit)
2. request funds, put a big amount (one can hope!)
3. press preview

result: app quits

**Comment by michaelsbradleyjr** [comment]
Can you rerun using `lldb` and get a backtrace?

**Comment by jrainville** [comment]
I tried reproducing this one, but I couldn't. 
It's possibly the weird bug Michael is mentioning.

I still found one reproducible issue I fixed here: https://github.com/status-im/nim-status-client/pull/1028
It should at least help a little
