### ISSUE TITLE
Windows: App fails to launch

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10206]
# Bug Report

## Description

After installing 0.11.0 RC2 Build 8 the app will not launch on Windows.

## Steps to reproduce

1. At the end of installation of 0.11.0 RC2 Build 8 select option to launch app - app does not launch
Same behaviour found when attempting to open exe directly

2. Trying to launch app as administrator opens UAC dialog. Accepting this also has no result
![image](https://user-images.githubusercontent.com/50769329/230160093-f689c6d5-3d4e-4265-b7db-1a697b399323.png)

3. When trying to launch a local build of master the following error was encountered:

```
Running: bin/nim_status_client.exe
could not import: dos_qabstractitemmodel_beginMoveRows
```

#### Expected behavior

App launches

### Additional Information

- Status desktop version: 0.11.0 RC2 Build 8
- Operating System: Win 11 Pro

**Comment by caybro** [comment]
> could not import: dos_qabstractitemmodel_beginMoveRows

So this is something I have recently added to DOtherSide but for some reason it didn't make it into the package???

**Comment by jrainville** [comment]
@caybro do you have the PR where you did that? It will help me know what needs to be added to the package if needed

**Comment by caybro** [comment]
> @caybro do you have the PR where you did that? It will help me know what needs to be added to the package if needed

Nothing new, it just seems like the static lib didn't get recompiled

**Comment by caybro** [comment]
This PR: https://github.com/status-im/status-desktop/pull/9792

**Comment by jrainville** [comment]
Trying to run the release, I get those errors:
```
Warning: QQmlApplicationEngine failed to load component (:0, )
Warning: qrc:/main.qml:322:9: Type AppMain unavailable (qrc:/main.qml:322, )
Warning: qrc:/app/mainui/AppMain.qml:1:1: module "QtQuick" version 2.15 is not installed (qrc:/app/mainui/AppMain.qml:1, )
INF 2023-04-05 15:00:47.902-04:00 starting application...                    topics="status-app" tid=2992 file=nim_status_client.nim:193
Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
INF 2023-04-05 15:00:47.906-04:00 shutting down...                           topics="status-app" tid=2992 file=nim_status_client.nim:161
```

Didn't we have that error before? I think it was because Qt5.15 wasn't installed on the release machine

I'm gonna try a dev build

**Comment by caybro** [comment]
> Trying to run the release, I get those errors:
> ```
> Warning: QQmlApplicationEngine failed to load component (:0, )
> Warning: qrc:/main.qml:322:9: Type AppMain unavailable (qrc:/main.qml:322, )
> Warning: qrc:/app/mainui/AppMain.qml:1:1: module "QtQuick" version 2.15 is not installed (qrc:/app/mainui/AppMain.qml:1, )
> INF 2023-04-05 15:00:47.902-04:00 starting application...                    topics="status-app" tid=2992 file=nim_status_client.nim:193
> Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
> INF 2023-04-05 15:00:47.906-04:00 shutting down...                           topics="status-app" tid=2992 file=nim_status_client.nim:161
> ```
> 
> Didn't we have that error before? I think it was because Qt5.15 wasn't installed on the release machine
> 
> I'm gonna try a dev build

This means Qt 5.15 isn't bundled into the installation package

**Comment by jrainville** [comment]
I just tested a dev build and it works fine. @glitchminer , you probably forgot to rebuild DotherSide when you tried.

The release build doesn't have an issue. I'll check the install script

**Comment by jrainville** [comment]
The build script seems ok. @jakubgs , could you check if the release Windows machine has Qt 5.15 correctly installed on it? I'm fairly sure we already did it last time, but maybe there are still two versions installed and it randomly used the wrong one?

**Comment by glitchminer** [comment]
@jrainville , thanks for investigating. You are right - I checked again and the issue with the local build was on my side, sorry.

Also, as you mentioned, it looks like it did use 5.14 (going by the log for windows build 2429)

**Comment by jakubgs** [comment]
@jrainville and what exactly does "correctly installed" mean?

All hosts have two versions installed, the one used is decided by env vars:
```
 > a ci-slave-linux -a 'ls -d /opt/qt/5.* | xargs -I{} bash -c "md5deep -rl {} | md5sum -z; echo {}"'  
linux-01.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
b3dc5fade8f41ca1b3509516566a53ac  -/opt/qt/5.14.2
bca768bb98fbbfa9603c4e1545f02985  -/opt/qt/5.15.2
linux-01.he-eu-hel1.ci.release | CHANGED | rc=0 >>
2bfeeb0d3e5e0ec865c9b45ed708ab73  -/opt/qt/5.14.2
528e022aa36c35654c86e18eeb8da51b  -/opt/qt/5.15.2
linux-03.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
2f7dfe455aefb07342de9961a18f3e8a  -/opt/qt/5.14.2
b0ab7d284f2b06aac7d8a88a0944e206  -/opt/qt/5.15.2
linux-05.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
ba546b32bd1c4247bcbe41de1c8b5701  -/opt/qt/5.14.2
d56a31e63719baa044fa793f3a7c2875  -/opt/qt/5.15.2
linux-04.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
8e3f05f427cc986facd92b2c6ca9b331  -/opt/qt/5.14.2
6acead0398296ce4989e28a3cd7094d0  -/opt/qt/5.15.2
linux-06.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
59bb317f1d215c1ccb835fd1c9adbd2f  -/opt/qt/5.14.2
17a3a81cb9a9eb7bbd8e7a31a824079e  -/opt/qt/5.15.2
linux-02.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
aa3adf562dd80dd5ed72ea41fedfc685  -/opt/qt/5.14.2
eff2a21f5be657d608d035f925dee362  -/opt/qt/5.15.2
```
None of the checksums match. Not sure why. Possibly an artifact of how `aqt` installs things.

**Comment by jakubgs** [comment]
Oh wait, if I sort it I get a correct result:
```
 > a ci-slave-linux -a 'ls -d /opt/qt/5.* | xargs -I{} bash -c "md5deep -rl {} | sort -u | md5sum -z; echo {}"' 
linux-01.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
4bf40501db91d29933430a688db05178  -/opt/qt/5.14.2
a1e5d6cc5ba4eb4731e8cd9063b71662  -/opt/qt/5.15.2
linux-02.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
4bf40501db91d29933430a688db05178  -/opt/qt/5.14.2
a1e5d6cc5ba4eb4731e8cd9063b71662  -/opt/qt/5.15.2
linux-03.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
4bf40501db91d29933430a688db05178  -/opt/qt/5.14.2
a1e5d6cc5ba4eb4731e8cd9063b71662  -/opt/qt/5.15.2
linux-04.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
4bf40501db91d29933430a688db05178  -/opt/qt/5.14.2
a1e5d6cc5ba4eb4731e8cd9063b71662  -/opt/qt/5.15.2
linux-05.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
4bf40501db91d29933430a688db05178  -/opt/qt/5.14.2
a1e5d6cc5ba4eb4731e8cd9063b71662  -/opt/qt/5.15.2
linux-06.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
4bf40501db91d29933430a688db05178  -/opt/qt/5.14.2
a1e5d6cc5ba4eb4731e8cd9063b71662  -/opt/qt/5.15.2
```

**Comment by jrainville** [comment]
Fixed

**Comment by jakubgs** [comment]
If we look at the host environment it's clearly using `5.15.2`:

![image](https://user-images.githubusercontent.com/2212681/230638938-9ed6b7de-0052-4674-b4df-eda0da9cff3f.png)

https://ci.status.im/computer/windows-01/systemInfo

We can check the same thing over RDP:

![image](https://user-images.githubusercontent.com/2212681/230639182-f8b7bf6b-257c-45e7-8ab5-d85dc3009d4b.png)

So I really wonder where this usage of `5.14.2` come from. I'd like to see the log this is based on.
