### ISSUE TITLE
[Community Permissions] Review scrolling behavior for holdings dropdown

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#10201]
# Bug Report

## Description

In the base "Select token" view

![Screenshot from 2023-04-05 11-44-46](https://user-images.githubusercontent.com/20650004/230124394-3df3c705-c199-445d-b686-41b31596ad76.png)

the scroll behavior is not fully clear:
- Should search bar and buttons "mint asset" and "import existing asset" be scrollable? Where is the top cut-off edge?
- Should "all listed assets" footer be always visible or scrollable as well? Where is the bottom cut-off edge for scrolling?

In the current implementation scroll bar is not scrollable and top/bottom cut off borders are probably incorrect.
![Screenshot from 2023-04-05 11-17-38](https://user-images.githubusercontent.com/20650004/230123570-50146251-f856-4414-9f10-5c75e4d597d1.png)

**Comment by noeliaSD** [comment]
@benjthayer could you give us your point of view here? It is a `low-priority` task so.. when you have time!

**Comment by benjthayer** [comment]
Hey @noeliaSD @micieslak, thanks for the query - I've added the below scrolling flow to the permissions area to help clarify the intended menu scroll behaviour.

Hope this helps! Anything else just shout :)

<img width="1772" alt="Screenshot 2023-05-11 at 09 46 59" src="https://github.com/status-im/status-desktop/assets/110033914/22f698bf-0996-498a-83c4-2bfe9619ffee">

Figma link
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29708-620637&t=Os6iVseYwCZb4YRQ-4

**Comment by noeliaSD** [comment]
> https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29708-620637&t=Os6iVseYwCZb4YRQ-4

Thanks for the design, @benjthayer !!

**Comment by noeliaSD** [comment]
> Hey @noeliaSD @micieslak, thanks for the query - I've added the below scrolling flow to the permissions area to help clarify the intended menu scroll behaviour.
> 
> Hope this helps! Anything else just shout :)
> 
> <img alt="Screenshot 2023-05-11 at 09 46 59" width="1772" src="https://user-images.githubusercontent.com/110033914/237628385-22f698bf-0996-498a-83c4-2bfe9619ffee.png">
> Figma link https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29708-620637&t=Os6iVseYwCZb4YRQ-4

I'm wondering if it would make sense to move the `All listed assets` (it is a folder), to the top and always pinned?

**Comment by benjthayer** [comment]
cc @xAlisher for your thoughts on @noeliaSD 's suggestion above...
