### ISSUE TITLE
StatusQ modules separation

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10218]
This is a problem I came to in https://github.com/status-im/status-desktop/pull/10207

## Problem

`StatusQ.Core.Theme` (or any other "qml sub-module") is compiled as resources in StatusQ plugin  `libStatusQ.dylib`.
Because of this, to access `StatusQ.Core.Theme` we should first load the plugin resources.

To do this, I currently added `import StatusQ 0.1` in each root QML file of all applications (desktop, sandbox, storybook, qml tests).

## Solution

In fact, `StatusQ`, `StatusQ.Core` and `StatusQ.Core.Theme` are 3 different QML modules.

QML files of `StatusQ.Core.Theme` should be self-contained. If compiled into a plugin, than it should be compiled into a separate `StatusQ/Core/Theme/libStatusQCoreTheme.dylib`. 

This is the key to fix all dependency problems. But it’s quite hard to achieve with pure CMake without [qt_add_qml_module](https://doc.qt.io/qt-6/qt-add-qml-module.html).

## Note

I don't think we should put effort to fix this before switching to Qt6.
The workaround works fine and doesn't hurt.

But I'd leave this task here, because I've left links in the code to this issue.

**Comment by caybro** [comment]
Just got an idea how to fix this workaround: we could compile the resources into an external file (like we do currently in status_desktop) and then from the StatusQ plugin.cpp load it via [QResource::registerResource](https://doc.qt.io/qt-5/qresource.html#registerResource)

**Comment by igor-sirotin** [comment]
I don't think it would work. Or at least it wouldn't work properly.

StatusQ `plugin.cpp` will only be loaded when `import StatusQ` is found. So the `registerResource` would be only called at that point. And just as before, the resources wouldn't be found earlier with `import StatusQ.Core.Theme`. 

As I understand, there's no difference if the resources are in compiled in external file or right with `StatusQ.dll`. 

Or I might be missing something from your point here.

**Comment by igor-sirotin** [comment]
@iurimatias I don't think we are going to implement this in near future, so it might make sense to close this issue.
This is pure refactoring to remove several workarounds made in the code. 

Though this is good reference for C++ implementation modules architecture.

**Comment by jrainville** [comment]
Closing as we won't be doing this before the move to C++

**Comment by stefandunca** [comment]
This limitation made me chase an intermittent unrelated error in tests, now I know better.

```out
file:///Users/stefan/proj/status/status-desktop/storybook/qmlTests/tests/tst_ConnectedDappsButton.qml:15:9: Type ConnectedDappsButton unavailable 
             ConnectedDappsButton { 
             ^
file:///Users/stefan/proj/status/status-desktop/ui/app/AppLayouts/Wallet/controls/ConnectedDappsButton.qml:11:1: Type StatusButton unavailable 
     StatusButton { 
     ^
file:///Users/stefan/proj/status/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusButton.qml:6:1: Type StatusBaseButton unavailable 
     StatusBaseButton { 
     ^
file:///Users/stefan/proj/status/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusBaseButton.qml: Type ModelUtils unavailable
file:///Users/stefan/proj/status/status-desktop/ui/StatusQ/src/StatusQ/Core/Utils/ModelUtils.qml:5:1: module "StatusQ.Internal" is not installed 
     import StatusQ.Internal 0.1 as Internal 
     ^
```

@igor-sirotin thanks for raising the awareness on this issue

**Comment by micieslak** [comment]
Problem fixed by https://github.com/status-im/status-desktop/pull/16497, all workarounds (additional imports) removed.
