### ISSUE TITLE
Remove unreachable communities from community portal

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10213]
### Description

Communities can become unreachable through disuse. While the correct number of placeholders may load, the community portal will not be able to load the details of unreachable communities. This issue is to suggest that they be hidden from the portal.

![image](https://user-images.githubusercontent.com/50769329/230379711-7be384e2-8477-45c2-b164-a64b2af2e861.png)

**Comment by jrainville** [comment]
Closing this as we just updated to use the real contract.
