### ISSUE TITLE
Chat: using @everyone in the middle of sentence resolves it to 0x0001

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10211]
### Description

1. create a group chat
2. type text + `@everyone` + text

<img width="810" alt="Screenshot 2023-04-06 at 14 48 49" src="https://user-images.githubusercontent.com/82375995/230367939-4259fb8c-8308-401c-b41c-3de5a9755c50.png">

**Comment by jrainville** [comment]
@anastasiyaig you say in the ticket to create a group chat, but in the screenshot you say community channel, which one is it?
Also, I cannot reproduce. It works fine in a community and in a group chat, we don't actually support it (it still shows ok, not the hex)

**Comment by caybro** [comment]
Looks like this PR (https://github.com/status-im/status-desktop/pull/10245) fixed it? :)

**Comment by anastasiyaig** [comment]
@caybro i closed the ticket, not sure which PR specifically fixed that since it was not linked

**Comment by jrainville** [comment]
I couldn't reproduce the issue even before doing that PR. Something else fixed it it seems
