### ISSUE TITLE
[Chat][Performance] Improve channels switching time

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#10231]
### Description

Currently switching community channels takes a long time (~15sec when switching to channels with lots of messages).

https://user-images.githubusercontent.com/47811206/230599551-63f5ff77-82fb-45fe-8528-b75193413b13.mov

**Comment by caybro** [comment]
Yes, esp. `#desktop` and `#mobile`

The app gets stuck for a long time on:
```
DBG 2023-04-07 14:00:41.154+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=85805 file=core.nim:27 rpc_method=wakuext_firstUnseenMessageID
DBG 2023-04-07 14:01:33.816+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=85804 file=core.nim:27 rpc_method=wakuext_emojiReactionsByChatID
```

**Comment by alexjba** [comment]
There's the true potential on first load:

https://user-images.githubusercontent.com/47811206/230621092-454d8560-292a-4c1f-aaaa-1417853f3e19.mov

Unfortunately I'm not getting consistent results with this implementation. Probably the db is getting locked sometimes.

**Comment by alexjba** [comment]
Will be closed by https://github.com/status-im/status-go/pull/3442

**Comment by alexjba** [comment]
This issue depends on:

- [ ] #10282
- [ ] #10471

**Comment by alexjba** [comment]
Fixed by latest performance improvements
