### ISSUE TITLE
Can't start release 0.11.0 build #18

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10257]
### Description

Install https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.11.x/18/console which is the latest release build

Application can't be started

```
anastasiya@MacBook-Pro-Anastasiya MacOS % PORT_SHIFT=1 ./nim_status_client
INFO [04-11|16:50:05.819] Status backend initialized               backend=geth version=0.142.5 commit=c84d6fcc3 IpfsGatewayURL=https://ipfs.status.im/
INF 2023-04-11 16:50:06.759+03:00 Version: 0.11.0-rc.3                       topics="status-app" tid=22100468 file=nim_status_client.nim:186
INF 2023-04-11 16:50:06.759+03:00 Commit: 7418ac06a                          topics="status-app" tid=22100468 file=nim_status_client.nim:187
INF 2023-04-11 16:50:06.760+03:00 Current date:                              topics="status-app" tid=22100468 file=nim_status_client.nim:188 currentDateTime=2023-04-11T16:50:06+03:00
INF 2023-04-11 16:50:06.760+03:00 starting application controller...         topics="status-app" tid=22100468 file=nim_status_client.nim:190
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
INF 2023-04-11 16:50:34.253+03:00 starting application...                    topics="status-app" tid=22100468 file=nim_status_client.nim:193
Debug: Network Cache Dir:  "/Users/anastasiya/Library/Application Support/Status/tmp/netcache" (:0, )
```

<img width="274" alt="Screenshot 2023-04-11 at 16 53 05" src="https://user-images.githubusercontent.com/82375995/231185128-0b3618af-3894-4b27-8c15-cc2972c2a525.png">

**Comment by anastasiyaig** [comment]
@iurimatias @jrainville @alexandraB99 @alaibe

**Comment by caybro** [comment]
Just a random idea @anastasiyaig, can you try without `PORT_SHIFT=1`?

**Comment by anastasiyaig** [comment]
@caybro @glitchminer run it without the port shift - same result

**Comment by jrainville** [comment]
I tried the Linux build and it works fine.
I have a feeling this is related to the new ARM build (the 9th build worked and it was probably before).
@jakubgs is there something that needs to be installed on the Release hosts? Also the ARM build just failed.

**Comment by jakubgs** [comment]
@jrainville the build was not failing, release app notarization was failing due to combining of stderr and stdout.
As @anastasiyaig has pointed out that release issue has already been resolved.

As for the app not starting on Macs, I have no idea. That's more of a question to devs.
I can't even debug this properly as I don't use Macs.

**Comment by anastasiyaig** [comment]
i can confirm the release is launching in 21 build https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.11.x/21/
