### ISSUE TITLE
Fetching messages from store nodes that are more than 24 to 48 hours old is broken 

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#10279]
Yesterday afternoon when I tried to update my install from 0.9 to 0.11, the update process borked my installation, forcing me to do a fresh install.

After doing a fresh install and restoring using my seed phrase, when I went to the Status Internal community, in most channels only messages from the last 24 hours had been downloaded, and in a few channels messages from the last 48 hours had been downloaded.  No messages older than 48 hours were downloaded, this includes 1on1 messages, ad-hoc group chat messages, as well as messages in the Status Internal community.

It is now 15 hours after I did the fresh install, and still no messages older then 24 to 48 hours have been downloaded.  I've had between 20 and 30 peers all this time, and I haven't see the "can't connect to store node" banner.

The 0.12 install is supposed to be configured to automatically fetch from store nodes all messages from the last 7 days, so something is definitely broken here.  We we ideally want to raise this limit for 1on1 and ad-hoc group chat messages to 30 days (and it's especially important that the 'automated profile data backup to waku' messages can be retrieved from store nodes for the last 30 days) but of course we need to get message fetching from the last 7 days working first.

To reproduce, either create a fresh account and join the Status Internal community, or do a fresh install in a VM and restore from seedphrase (the backup to waku correctly restores the communities that account was a member of - this might be a quicker way of testing).

@richard-ramos could you take a look at this?    As part of fixing this issue, once fetching the last 7 days worth of messages is working, could we also then raise the limit so that by default Status Desktop fetches the full last 30 days of messages from store nodes automatically (and then test that this works)?

Also cc'ing @cammellos and @jm-clius and @LNSD because the failure could perhaps be happening on the nwaku store node side?

**Comment by jm-clius** [comment]
Can confirm that we can retrieve (with direct query) messages from 30 days ago on all 6 store nodes in `status.prod`. This did not test any specific queries from Status Communities, just that the nwaku store nodes are reachable, have stored 30 days of data and can be queried for that data.

**Comment by John-44** [comment]
![2023-04-13 11_20_22-#nwaku _ Vac - Discord](https://user-images.githubusercontent.com/22846356/231730072-0d486b6f-8bca-4756-bb1c-7512950ccc31.png)

**Comment by churik** [comment]
FYI: there are a bunch of community fetching history issues, that are mentioned here: https://github.com/status-im/status-mobile/issues/14797

**Comment by John-44** [comment]
Thanks @churik, useful to know!

@richard-ramos note that in my case, the issue I'm seeing with messages older then 20 to 48 hours not being fetched from store nodes affects 1on1, ad-hoc group chat and community messages equally.
