### ISSUE TITLE
Switching between two chats shows the loading state even though it is still in memory

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10275]
# Bug Report

## Description

We currently keep 5 channels in memory, but still, when switching from one channel to another and back and forth, the loader still shows.

[loading-sqitch.webm](https://user-images.githubusercontent.com/11926403/231535902-a086077d-46c0-4446-831e-7f2b9afc579c.webm)

## Steps to reproduce

Have a community with big channels.
Switch between 2 of them repeatedly.

#### Expected behavior

The first load/change **should** have the loader while we fetch the messages
Going back to the channel after should be instant, **unless** we go more than 5 channels in memory, then the first one that was loaded is unloaded and should show the loader again.

#### Actual behavior

We see the loader all the time.

### Additional Information

- Status desktop version: 0.11 RC3
- Operating System: Ubuntu 20

**Comment by jrainville** [comment]
@mprakhov @osmaczko which one of you should check this out? I know @mprakhov did the initial work, but I think it might have been a fix by @osmaczko that made it so we show the loader each time.

**Comment by mprakhov** [comment]
That's a regression after https://github.com/status-im/status-desktop/pull/10222
`self.scrollToFirstUnseenMessageWhenLoaded = false` this shouldn't be set to false if we load the data.
I do remember that I left the comment about it in the PR, but I do not see it 😢 
It will be breaking changes to first unread msg's (if we won't provide just another one param)

**Comment by jrainville** [comment]
Yeah I remember your comment. That's why I tagged you both. I think we should/could keep the first unseen message in memory if it's still part of the 5 channels in memory, that way we don't call the function each time we switch. What do you think @osmaczko ?

**Comment by jrainville** [comment]
Found the comment: https://github.com/status-im/status-desktop/pull/10151#discussion_r1157091016

**Comment by mprakhov** [comment]
Exactly.
Each time we click on chat - we reset `self.scrollToFirstUnseenMessageWhenLoaded = false` and this cause to showing a loading page.
Previously `scrollToFirstUnseenMessageWhenLoaded` (it was named another way) was set to `true`, only when we first time opened the chat, and never was set to `false` after what is correct

**Comment by caybro** [comment]
cc @alexjba because his PR might be related too

**Comment by alexjba** [comment]
I've linked the PR. Thanks @caybro

**Comment by jrainville** [comment]
That PR will help the initial load, but doesn't fix the subsequent loads. Thanks for letting me know though.

**Comment by mprakhov** [comment]
> That PR will help the initial load, but doesn't fix the subsequent loads. Thanks for letting me know though.

It should help as we change the conditions for a chat loader view displaying, we do not depend on `firstUnseenMessageLoaded` anymore
