### ISSUE TITLE
[Pinned messages] Clicking URLs in the pinned messages popup does not open the URL externally

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#10274]
### Description

Repro steps:
1. Pin a message containing an URL
2. Open Pinned messages popup
3. Click the URL

Expected:
URL is opened externally

Actual:
The Pinned messages popup is closed

https://user-images.githubusercontent.com/47811206/231475189-9679a30b-16f1-4b61-af35-bdcffe99db82.mov

**Comment by caybro** [comment]
Unfortunately, I have to close this => impossible to fix w/o some major refactorings. TLDR, the `TextEdit` that's used to display the message here eats all mouse events (to be able to catch the clicks on URLs), therefore we can only have either clicking the hyperlinks, or clicking the whole item.
