### ISSUE TITLE
Sync: some data is not synced after getting back from offline on some account

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#10288]
# Bug Report

## Description
In the scope of checking Desktop <-> Mobile sync some data, several issues were noticed when syncing on direction Mobile -> Desktop (desktop client came from offline) 
The issue is not consistent and most visible on multi accounts with a lot of activity/data (not reproducible for me on fresh multi accounts, but constantly bumped onto when using my main account)

This data contains: 
- community request accepting
- changing nickname
- mentions/replies in AC (from time to time)
- sometimes blocking the user

The reason why the issue is in the desktop repo is that it is working better in the direction Desktop -> Mobile.
Moreover, seems that community requests just cannot be accepted from the activity center on the desktop, and it is worth additional reporting/investigating (cc @anastasiyaig ), video is attached.

https://user-images.githubusercontent.com/4557972/231745099-ba2b2fcb-8abb-4f05-8059-e7eb75aef83d.mp4

May be it is better to split that us into several issues, just wanted to let you know that there are definitely issues in terms of syncing data.

## Steps to reproduce
**Prerequisites:** User1 is restored on the desktop and on the mobile client, he is the admin of the community A
1. as User1 (desktop): close the app
2. as User2 (from the third device): send community request
3. as User1 (mobile): accept it, make sure that the user is a member of the community
4. as User1 (mobile): set nickname to any user
5. as User3 (from the third device): mention User1 in the community
5. as User1 (mobile): block any user
6. as User1 (desktop): open the app, log in, and check the data (best to wait for 5-10 mins) 

#### Expected behavior
all data is synced

#### Actual behavior
![Status Desktop 2023-04-13 13-09-57](https://user-images.githubusercontent.com/4557972/231741400-3a952a0e-a8c2-46b1-9c82-25e8ef2882c1.png)
3. AC community request is still there, however, the user is already shown as a member of community
4. Nickname was not synced
5. Blocked users (from time to time) are not synced
6. Mentions/replies sometimes are not fetched (also not reproducible every time) 

### Additional Information

**Desktop app:**
- Status desktop version: RC 8 0.11
- Operating System: Mac OSx Ventura
- Logs: 
[app_20230413_115518.log](https://github.com/status-im/status-desktop/files/11221451/app_20230413_115518.log)
[app_20230413_121133.log](https://github.com/status-im/status-desktop/files/11221452/app_20230413_121133.log)

**Mobile app:**
- Build: 1.22
- OS: IOS 16
- Logs:
[logs (32).zip](https://github.com/status-im/status-desktop/files/11221610/logs.32.zip)

**Comment by igor-sirotin** [comment]
After careful reading, I can say this has nothing to do with Local Pairing.
Not saying that I'm not going to look at it 😄 Just removing the badge.

**Comment by igor-sirotin** [comment]
Ok, after dealing with pairing for some time (it didn't work for me at first), I can say this:
1. ✅ No pending membership requests in community
2. ❌ There's no AC community request at all  (probably should be accepted one)
3. ❌ Nickname didn't change
4. ❌ User is not blocked (actually I added it as a contact during test, on desktop I can only see contact request pending)
5. ❌ Didn't receive mention message
Though I immediately receive all other messages

I can say that everything that syncs syncs immediately. At some point of playing around I also received the nickname update and mentions.

Will investigate further.

**Comment by igor-sirotin** [comment]
Will continue after merging https://github.com/status-im/status-go/pull/3627

**Comment by igor-sirotin** [comment]
Closing this issue. All problems are either logged as separate issues or not reproduced anymore.
- https://github.com/status-im/status-desktop/issues/11160
- https://github.com/status-im/status-desktop/issues/11523
- not reproduced: Community join request visible although user is member
- not reproduced: `@Mention` not received

**Comment by igor-sirotin** [comment]
Just noted that when testing `@mentions` bug, the first message `1` is always lost.
Will try to reproduce this now.
