### ISSUE TITLE
[suite_wallet/tst_wallet and tst_wallet_section_accounts_management] Managing wallet accounts' tests - randomly fail

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#10287]
After tests are written for managing wallet accounts some weird issue appears which causes random test to fail but always because of the same reason. 

After an object is returned by `squish.waitForObject` and after checking `if obj is None` when I try to read `obj.some-property` Squish throws an error `Attempt to access a property of a null object`

An interesting thing is that they are all passing well if I run them section by section in local, but running them all causes that some of them randomly fail, but always because of the issue described above.

I've noticed that sometimes happens for other tests (like saved address tests and others) but they are opening context menu like one or two times, but in case of managing accounts tests each scenario is opening a context menu 4-8 times and there are like ~30 cases for all scenarios, so many times context menu was opened and an option from it was clicked. 

Tests are introduced in this PR https://github.com/status-im/status-desktop/pull/10234

**Comment by StateOf-Vlado** [comment]
on review: https://github.com/status-im/status-desktop/pull/10675
