### ISSUE TITLE
[tests]: configure tests to use custom status data folder

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10293]
Squish tests should operate with different data folder, for example in Status_tests folder, rather than in Status folder which is used to store development accounts.

**Expected result:**

`Status` data folder is not removed / modified when running tests locally. Tests are using their own data folder which can be modified at any point

**Comment by anastasiyaig** [comment]
are u saying it is not possible? @caybro :)

**Comment by anastasiyaig** [comment]
@jrainville @osmaczko do u guys have an idea how to implement this?

**Comment by jrainville** [comment]
I'm pretty confident this is doable. We must configure the data dir path on account creation, so we just need to use an env var or something (we already have one for tests), to change that path to use a test dir. I'll check in a minute to see.
We already have a different path for dev and release, so it's for sure doable in some way

**Comment by jrainville** [comment]
Yeah it's defined in `constants.nim`

```nim
proc defaultDataDir*(): string =
  let homeDir = getHomeDir()
  let parentDir =
    if defined(development):
      parentDir(getAppDir())
    elif homeDir == "":
      getCurrentDir()
    elif IS_MACOS:
      joinPath(homeDir, "Library", "Application Support")
    elif defined(windows):
      let targetDir = getEnv("LOCALAPPDATA").string
      if targetDir == "":
        joinPath(homeDir, "AppData", "Local")
      else:
        targetDir
    else:
      let targetDir = getEnv("XDG_CONFIG_HOME").string
      if targetDir == "":
        joinPath(homeDir, ".config")
      else:
        targetDir
  absolutePath(joinPath(parentDir, "Status"))
```
We just need a new `if` at the top to check for the test env var.

**Comment by StateOf-Vlado** [comment]
if we can add an option in the app running the command we can use it
For example: nim_status_client path_to_user_data

**Comment by StateOf-Vlado** [comment]
Looks like the feature is not resolved.
@anastasiyaig I have to write on nim something here?

**Comment by anastasiyaig** [comment]
@StateOf-Vlado it is up to you, in case u know what to change in Nim files - please, go ahead :)

**Comment by anastasiyaig** [comment]
@jrainville can u please advise?

**Comment by jrainville** [comment]
> I need to build the app to have this possibility

It's possible to make the Nim code read the ENV var on runtime instead of on build time.

> I can not start several clients on one machine

You can start multiple clinets on one machine. One easy way is to use a release version and a dev version. However, you can also use mutliple dev versions at the same time by doing two different clones of the app.

Once the ENV var for the data dir will be implemented, it should even be possible to run from the same clone, but there might be other side effects, so I can't guarantee it.

> Can we add attributes for the application launcher?

What do you mean? Adding them as options when starting? for eg: `make run --datadir="..."`? I guess we can, but the same Nim code will be needed. It just will use that option instead of the ENV var,

**Comment by StateOf-Vlado** [comment]
Oh, sorry, I found:
idrusch@Vladimirs-MBP ~ % /Users/idrusch/Workspace/Status/status-desktop/bin/nim_status_client --help                                                    
Usage: 

nim_status_client [OPTIONS]...

The following options are available:

 -d, --dataDir      Status Desktop data directory [=defaultDataDir()].
     --uri          status-im:// URI to open a chat or other.

**Comment by StateOf-Vlado** [comment]
I will try to use it

**Comment by StateOf-Vlado** [comment]
I tested, It's work well, I will use it
