### ISSUE TITLE
Primary nav sometimes still shows a badge even though all channels in it are read

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10314]
# Bug Report

## Description

As seen here https://github.com/status-im/status-desktop/issues/10264#issuecomment-1508249569

> I don't have any unread private/group messages, yet the primary badge is still showing up

## Steps to reproduce

Unsure.

#### Expected behavior

When all channels in a channel group (section) are read or muted, the main nav item on the left should no longer have the badge.

### Additional Information

- Status desktop version: master

**Comment by caybro** [comment]
I tried manually marking read all the private chats; it was the one from "jakubgs.eth"; it contained nothing but a "fake" message with a contact request. That marked the whole category as read and made the badge disappear.

**Comment by jrainville** [comment]
This should be fixed in latest master and 0.12RC1.
I had made a mistake when trying to fix the badge for communities and the badge would show as soon as any community had a badge,
