### ISSUE TITLE
Repeated channels

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10316]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/33099791/232084555-28b34bd3-8963-4313-8032-2b9cec57ed09.png)

## Steps to reproduce

Hard to tell, it happened after quick switching between chats

### Additional Information

- Status desktop version: 0.11.0 RC6
- Operating System: Ubuntu

**Comment by jrainville** [comment]
Discussing with Mishka, it seems like this can happen when using SortFilterProxy. 
In this PR https://github.com/status-im/status-desktop/pull/10002 (specifically this one https://github.com/status-im/status-desktop/pull/10144), I removed the SortFilterProxy, so once this PR is merged, we need to check if it ever happens again in master.

**Comment by siddarthkay** [comment]
Reproducible on mac M2 as well for me today.

My Status Desktop version is 0.11.0 and I am running the Apple Silicon Build.

![Screenshot 2023-04-24 at 12 31 09 PM](https://user-images.githubusercontent.com/64726664/233941396-3f6519a3-0447-437b-ab06-29dfd9155bee.png)

**Comment by jrainville** [comment]
Closing as this should be fixed with the model change done a few weeks ago
