### ISSUE TITLE
Community / Mint Tokens / Create new collectible - Artwork image field missing cropping tool (backend API)

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#10317]
Version: V0.11.0-rc.6
OS: Ubuntu 22.10

***
Preconditions: User has ‘Community Permissions Setting’ and ‘Community Tokens’ turned on in Settings/Advanced. User is the owner of a community.

<ins>Steps to reproduce:</ins>

1. In the Users community, navigate to ‘Mint Tokens’

2. Click ‘Create new token’

3. Under the Artwork header, add an image

<ins>What currently incorrectly happens:</ins>

4. The image is uploaded immediately into the image field - this is incorrect.  

https://user-images.githubusercontent.com/124154641/232101659-238fbd1d-b586-4436-9e66-cc10525e3022.mp4

&nbsp;

<ins>What is supposed to happen:</ins>

4. When an image is uploaded to the Artwork image field the image cropping tool dialog should immediately open. The User should then be able to crop and save the image. 

The image cropping tool dialog should be the same as the one found in Discover Communities / Create New Community / Create new / Community logo.  

https://user-images.githubusercontent.com/124154641/232101020-ce6b0b83-7bc2-4c20-b089-6120c44ffb10.mp4

&nbsp

**Comment by noeliaSD** [comment]
@imagiMary, one more clarification, please: 

The artwork in this component can be also uploaded by `drag and drop` action. Should this case end up in opening the `cropping tool` too?

Thanks!!

**Comment by imagiMary** [comment]
> @imagiMary, one more clarification, please:
> 
> The artwork in this component can be also uploaded by `drag and drop` action. Should this case end up in opening the `cropping tool` too?
> 
> Thanks!!

Yes please @noeliaSD :) 
 
The `copping tool` should always open when an image is added regardless of how it uploaded e.g. either by `drag + drop` or via the `+` upload  button.

**Comment by noeliaSD** [comment]
> > @imagiMary, one more clarification, please:
> > The artwork in this component can be also uploaded by `drag and drop` action. Should this case end up in opening the `cropping tool` too?
> > Thanks!!
> 
> Yes please @noeliaSD :)
> 
> The `copping tool` should always open when an image is added regardless of how it uploaded e.g. either by `drag + drop` or via the `+` upload button.

Could this screenshot fit the requirements? `Title` and `button` texts?

![Screenshot 2023-05-04 at 11 43 41](https://user-images.githubusercontent.com/97019400/236169664-72132f4c-d326-4150-9637-4c7c095e180c.png)

**Comment by imagiMary** [comment]
Looks good! 
`Title` - "Collectable artwork"
`button` - "Upload collectable artwork"

**Comment by imagiMary** [comment]
@caybro you're right! Thanks for spotting that!!

**Comment by noeliaSD** [comment]
PR created for UI part.

@endulab  It needs some backend works to be completed. Expected flow:
- _UI --> backend_: UI will pass a `json` file with the crop image details and backend will be in charge of cropping it and store it accordingly. 
- _Backend --> UI_: Expected artwork image read from backend: Image already cropped.

**Comment by noeliaSD** [comment]
> PR created for UI part.
> 
> @endulab It needs some backend works to be completed. Expected flow:
> 
> * _UI --> backend_: UI will pass a `json` file with the crop image details and backend will be in charge of cropping it and store it accordingly.
> * _Backend --> UI_: Expected artwork image read from backend: Image already cropped.

PR for UI part already integrated. I will add this task again to the iteration backlog since it needs backend works to be completed!
