### ISSUE TITLE
Send/Bridge max balance functionality not working

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#10320]
Version 0.11, Windows 10

The 'max balance' button functionality (the button in the top right of both the Send and Bridge modals) is incorrect in a few of ways: 

**1) The button is in a red error state when no amount to Send/Bridge has been entered, see screenshot below.**  The button should not be in the red error state, because when the 'amount to send/bridge' is 0.00 it is impossible for this number (zero!) to exceed the available balance of whatever token has been selected.

![2023-04-15 12_22_55-Status Desktop](https://user-images.githubusercontent.com/22846356/232211365-3d440c13-e481-4de8-9ee6-9ebe0e4bcfc0.png)

---

**2) Clicking on the 'max balance' button does nothing.** Clicking on the 'max balance' button is supposed to populate the 'Amount to send/bridge' field with the 100% of the balance of whatever ERC-20 token is selected.  

If ETH (not a ERC-20) is selected, the behaviour should be slightly different:

- if the user's ETH balance is more than 0.1, the 'max balance' button should always display the ETH balance in that account **minus 0.09 ETH**

- if the user's ETH balance is more than 0.06, the 'max balance' button should always display the ETH balance in that account **minus 0.05 ETH**

- if the user's ETH balance is less than 0.06 and more than 0.03 ETH, the  'max balance' button should always display the ETH balance in that account **minus 0.025 ETH**

- if the user's ETH balance is less than 0.03, the 'max balance' button should always display "Max: 0.00 ["ETH" or base currency abbreviation]

The above is to help prevent a user from sending all their ETH, which would be impossible because they wouldn't have any ETH to pay the gas fee, and to help users leave a little bit of ETH in their accounts so the tokens in that account aren't stranded there with no way to transfer be cause there isn't enough ETH to pay for gas.  

A user can always override these guardrails by directly entering an ETH value into the 'Amount to bridge/send' field.  As long as the ETH value the user enters is above the: ETH balance the user has in the account *minus* the estimated 'Max Fees', the "Send" button should be active and the user should be able to proceed with making the transaction.

---

**3) When the user first opens the Send or Bridge modal, the 'max balance' button displays the copy of "No balances active"** (see screenshot below).  This copy should be changed to "No token selected"

![2023-04-15 12_24_27-Status Desktop](https://user-images.githubusercontent.com/22846356/232211680-bf613048-0a89-4852-9227-660168c65818.png)

---

**4) When a user switches between accounts in the Send or Bridge modals, using the tabs above the Send or Bridge modals, the 'max balance' button doesn't update to show the correct max balance for the currently selected account.**

See screenshots below - the 'max balance' button is always showing the max balance of the "Status account", even when "Frist test account" is selected.  Also the "Recent" activity shown under the "Recent" tab is not being updated when a user switches accounts, this also needs to be fixed.

![2023-04-15 12_52_29-Status Desktop](https://user-images.githubusercontent.com/22846356/232217934-77feaca7-2c15-44b4-94af-b9e31d0fc805.png)

![2023-04-15 12_51_58-Status Desktop](https://user-images.githubusercontent.com/22846356/232217960-60d06b3b-feb5-4b9e-b1e7-b16f866b25c0.png)

**Comment by Khushboo-dev-cpp** [comment]
Implemented under https://github.com/status-im/status-desktop/pull/10354
