### ISSUE TITLE
Enhance message context menu with 'mark as unread'

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10329]
### Description

Add 'mark as unread' to message context menu.

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=14632-461976&t=uy7ndkCYvGTyJwQ8-0

![image](https://user-images.githubusercontent.com/33099791/232451306-627e25b8-a40a-40e2-81d1-36d42eb57815.png)

**Comment by kounkou** [comment]
Hi,

Summarizing here some requirements for the task : 

- User marks standard (non-mention) message as unread. 
- Marking a message as unread moves new message marker to above that message. Blue new messages marker missed message number updated.

![Image](https://github.com/status-im/status-desktop/assets/2589171/fbddcc61-82ef-432f-9e97-30366b1e1a20)

**Comment by osmaczko** [comment]
> User marks standard (non-mention) message as unread.

I believe mention can also be marked as unread.

> Marking a message as unread moves new message marker to above that message.

True.

> Blue new messages marker missed message number updated.

Not sure I understand?

**Comment by kounkou** [comment]
Thanks @osmaczko for your comment, 

these requirements are coming from the Figma

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=572-4517&mode=design&t=0EqBoIJnI1VoxRPF-0

Would it make sense to sync up with design team on them ?

for the 

> Blue new messages marker missed message number updated.

This is the line that appears in the chat view to point the unread message. So my understanding is that once the message is marked as unread, that line goes to the unread message, AND the number of unread messages is updated as well.
That number of unread messages should be somewhere in the bottom right of the chatview. 

![Image](https://github.com/status-im/status-desktop/assets/2589171/651b41a0-0373-4680-8519-e444ff1c1510)

Thoughts ?

**Comment by jrainville** [comment]
If I recall correctly, we decided to not implemented the mentions tracker (blue marker), as it's too complex for the good it provides.

The grey one works, I think.

There is also the mention marker on the chat that needs to be updated (on the left side bar, the grey or blue dot). For that, just update the chat's `UnviewedMessagesCount` and `UnviewedMentionsCount` and save it in the DB and put it back in the response/signal that comes back to the app.

In theory, all the changes you listed that are part of the design should happen automatically when the right signals come back from status-go. The UI work needed is mostly to add the new button in the context menu.

The status-go work is probably more complex than I expected, I forgot about changing the last message seen and the count of unread messages, but when you get there, we can give you pointers. However, it's nothing crazy, so feel free to ask questions.

**Comment by kounkou** [comment]
Fantastic! Thank you so much for this notes. I'll keep them in mind when working on the feature.

**Comment by osmaczko** [comment]
> If I recall correctly, we decided to not implemented the mentions tracker (blue marker), as it's too complex for the good it provides.

It was decided to not implement the grey anchor button count number. The blue anchor button was implemented there: https://github.com/status-im/status-desktop/pull/10266

https://user-images.githubusercontent.com/33099791/231292773-181d499a-ed5a-4df8-ab9b-4ce755a19a2b.mp4

> these requirements are coming from the Figma

A bit further in the pipeline there is a case of marking mention as unread, see: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=14689-519109


The only element abandoned from the designs is the grey anchor button **count**, as it had some odd rules and consequently was not self-explanatory to the users.

**Comment by jrainville** [comment]
Ah my bad, I inverted the grey and blue button in my recollection. Follow what Patryk says :smile:

**Comment by kounkou** [comment]
oh Thanks a lot for all the details 😃
