### ISSUE TITLE
Wallet 'Send' and 'Bridge' modals don't vertically resize correctly in response to changing content or changing app window height

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#10323]
Version 0.11, Windows 10

The vertical resizing of the wallet 'Send' and 'Bridge' modals doesn't work correctly.  The modals don't vertically increase in size (up to the margins) or decrease in size, when the height of the content inside the modals increases or decreases.

Also the vertical height of these two modals doesn't correctly increase or decrease when the height of the Status Desktop app window increases or decreases.

These are the issues were demoed via screensharing at the UI team standup on Friday 14th April.  Ping me if more detail is needed.

**Comment by imagiMary** [comment]
@micieslak 
https://user-images.githubusercontent.com/124154641/236262396-e5b93c38-6d2c-41ea-809c-bd9d4c1fff1d.mp4

**Comment by iurimatias** [comment]
not ready for 0.12, moving to 0.13
