### ISSUE TITLE
Sending tokens tokens between the user's own accounts functionality needs fixes and improvements

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#10321]
Version 0.11, Windows 10.

See design below from from [Wallet v2 figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9707%3A107649&t=aZat53N9fCF2n8s7-1):

![2023-04-15 12_36_09-Wallet v2 – Figma](https://user-images.githubusercontent.com/22846356/232214994-e1588367-5ac5-4d29-a0f5-f06605d3e21a.png)

The current implementation is missing the following:

1) In the list of accounts below the "My Accounts" header, the address fragment should be shown before the account balance in base currency

2) When a user selects one of their other accounts, it should be displayed in the "To:" field as shown in the design above (e.g. as shown in the screenshot below)

![2023-04-15 12_44_25-Wallet v2 – Figma](https://user-images.githubusercontent.com/22846356/232216175-520fdc11-aec9-4335-b200-fe5629250f2f.png)

3) When a user goes to send tokens to another account they own, by default *all* networks should be preferred.  Currently, when the user goes to send tokens to another account they own, the send dialogue assumes that Mainnet is the only preferred network, this is incorrect

**Comment by Khushboo-dev-cpp** [comment]
Fixed under https://github.com/status-im/status-desktop/pull/10354
