### ISSUE TITLE
`Storybook` and others don't start because of `module "StatusQ" plugin "StatusQ" not found` on Linux

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#10331]
# Bug Report

## Description

Storybook/Sandbox/SanityChecker don't work out of the box bc of problems with finding StatusQ module. First (but probably no the only one) problem seems to be improper postfix of the lib: `status-desktop/ui/StatusQ/src/StatusQ/libStatusQd.so`.

## Steps to reproduce

Open Storybook in the QtCreater, run the app.

#### Expected behavior
Storybook opens.

#### Actual behavior
Storybook crashes:
```
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
file:///home/michalc/workspace/status-desktop/storybook/main.qml:7:1: module "StatusQ" plugin "StatusQ" not found
12:36:58: /home/michalc/workspace/builds/build-storybook-Desktop_Qt_5_15_2_GCC_64bit-Debug/bin/Storybook crashed.
```
### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by caybro** [comment]
Same behavior here

**Comment by caybro** [comment]
This part is problematic:
```
set_target_properties(StatusQ PROPERTIES 
    ADDITIONAL_CLEAN_FILES bin/StatusQ/qmldir
    DEBUG_POSTFIX "d"
    RUNTIME_OUTPUT_DIRECTORY ${STATUSQ_MODULE_PATH}
    RUNTIME_OUTPUT_DIRECTORY_DEBUG ${STATUSQ_MODULE_PATH}
    RUNTIME_OUTPUT_DIRECTORY_RELEASE ${STATUSQ_MODULE_PATH}
    LIBRARY_OUTPUT_DIRECTORY ${STATUSQ_MODULE_PATH}
)
```

as it messes up the plugin libname in qmldir:
```diff
ltinkl@zephyrus14:~/git/status/status-desktop/ui/StatusQ/src/StatusQ(9838-click-on-the-activity-centre-notification-bell-for-a-second-time-should-close-the-activity-centre-currently-not-working*$|u=)$ git diff qmldir 
diff --git a/ui/StatusQ/src/StatusQ/qmldir b/ui/StatusQ/src/StatusQ/qmldir
index 12303d408..95e1c630d 100644
--- a/ui/StatusQ/src/StatusQ/qmldir
+++ b/ui/StatusQ/src/StatusQ/qmldir
@@ -1,3 +1,3 @@
 module StatusQ
-plugin StatusQ
+plugin StatusQd
 classname StatusQPlugin
```

This "fixes" it but would likely break the release build

**Comment by caybro** [comment]
I still have some objections here: no binary file should be created inside a source tree; we should always do the shadow build to keep the src/build trees separate

**Comment by micieslak** [comment]
so the hotfix for linux is what @caybro wrote or renaming `status-desktop/ui/StatusQ/src/StatusQ/libStatusQd.so` by removing `d`. But yes, lib in source dir looks like a nasty workaround...

**Comment by caybro** [comment]
Changing the `qmldir` file to include the `d` postfix results in status-desktop not starting at all (as I expected):

```
Warning: QQmlApplicationEngine failed to load component (:0, )
Warning: qrc:/main.qml:18:1: module "StatusQ" plugin "StatusQd" not found (qrc:/main.qml:18, )
INF 2023-04-17 13:08:48.184+02:00 starting application...                    topics="status-app" tid=143534 file=nim_status_client.nim:193
Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
INF 2023-04-17 13:08:48.187+02:00 shutting down...                           topics="status-app" tid=143534 file=nim_status_client.nim:161
INF 2023-04-17 13:08:48.187+02:00 logging out...                             topics="app-controller" tid=143534 file=app_controller.nim:278
```

**Comment by igor-sirotin** [comment]
☹️

**Comment by igor-sirotin** [comment]
Sorry for this, guys
Already looking into this.

**Comment by caybro** [comment]
Just linked one more possible defect; for me the app doesn't crash but merely hangs waiting

**Comment by micieslak** [comment]
> @caybro @micieslak
> 
> > no binary file should be created inside a source tree
> 
> > But yes, lib in source dir looks like a nasty workaround...
> 
> But you did approve my PR #10207, which explicitly points out this solution smile
> 
> The thing is that having StatusQ as a QML module, all 3 it's components (qmldir, plugin, qml files) should be in the same directory. It's not going to work any other way. Since sandbox/storrybook wants live-detection of source-file changes, we should be using the source files as part of the QML module. Therefore the plugin just goes to source dir.
> 
> We could find a workaround with copying all QML files to shadow build library on changes, but that would require some separate programming, which I just don't find reasonable here. We only use this feature as developers. And it can be controlled outside StatusQ with given cmake options.

Yeah, I approved, I was also testing that solution and it was working fine then. Something had to change in the meantime probably. I don't see any better solution for now as well frankly speaking. The current approach is fine for me unless it works out of the box :)
