### ISSUE TITLE
Intel version of the app does not launch

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10332]
### Description

Try to launch https://github.com/status-im/status-desktop/releases/download/0.11.0/StatusIm-Desktop-v0.11.0-621f0c-x86_64.dmg (it is latest release 0.11.0 intel build)

```
anastasiya@MacBook-Pro-Anastasiya MacOS % ./nim_status_client             
INFO [04-17|13:40:11.679] Status backend initialized               backend=geth version=0.143.0 commit=1754c2376 IpfsGatewayURL=https://ipfs.status.im/
INF 2023-04-17 13:40:12.550+03:00 Version: 0.11.0                            topics="status-app" tid=2141493 file=nim_status_client.nim:186
INF 2023-04-17 13:40:12.551+03:00 Commit: 621f0c229                          topics="status-app" tid=2141493 file=nim_status_client.nim:187
INF 2023-04-17 13:40:12.551+03:00 Current date:                              topics="status-app" tid=2141493 file=nim_status_client.nim:188 currentDateTime=2023-04-17T13:40:12+03:00
INF 2023-04-17 13:40:12.551+03:00 starting application controller...         topics="status-app" tid=2141493 file=nim_status_client.nim:190
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
Debug: Network Cache Dir:  "/Users/anastasiya/Library/Application Support/Status/tmp/netcache" (:0, )
```
<img width="1552" alt="Screenshot 2023-04-17 at 13 42 44" src="https://user-images.githubusercontent.com/82375995/232461844-b3dd50e6-1fef-4a92-b0cd-af8e1600d024.png">

**Comment by anastasiyaig** [comment]
@jrainville @iurimatias

**Comment by caybro** [comment]
@MishkaRogachev can you `strace` it to see where it hangs (or what file is it trying to open)? I have a suspicion it might be related to https://github.com/status-im/status-desktop/issues/10331

**Comment by jrainville** [comment]
@MishkaRogachev anything in geth.log?

**Comment by MishkaRogachev** [comment]
I faced some problems running `strace/dtrace/dtruss` on Mac, i'll try again tomorrow

> @MishkaRogachev can you `strace` it to see where it hangs (or what file is it trying to open)? I have a suspicion it might be related to #10331

**Comment by igor-sirotin** [comment]
@caybro hmmmm, I don't think this has anything to do with https://github.com/status-im/status-desktop/issues/10331.
If it was about that issue, it would either fail to build on linking stage, or it would crash at runtime with smth like "import StatusQ no found.

**Comment by caybro** [comment]
> @caybro hmmmm, I don't think this has anything to do with #10331. If it was about that issue, it would either fail to build on linking stage, or it would crash at runtime with smth like "import StatusQ no found.

Hmmm maybe, I don't know... for me it doesn't crash either, just hangs with the "import StatusQ not found" error. The thing is that here we're dealing with a release build that might not print any such warning at all

**Comment by MishkaRogachev** [comment]
Current state of investigation:
Tested on M1 release versions:
v0.11.0-rc.4-38d2d4-aarch64 - works
v0.11.0-621f0c-x86_64  - fail
v0.11.0-621f0c-aarch64 - works

Log for x86_64 launch:
```
INF 2023-04-18 21:54:09.979+04:00 Version: 0.11.0                            topics="status-app" tid=1026712 file=nim_status_client.nim:186
INF 2023-04-18 21:54:09.979+04:00 Commit: 621f0c229                          topics="status-app" tid=1026712 file=nim_status_client.nim:187
INF 2023-04-18 21:54:09.980+04:00 Current date:                              topics="status-app" tid=1026712 file=nim_status_client.nim:188 currentDateTime=2023-04-18T21:54:09+04:00
INF 2023-04-18 21:54:09.980+04:00 starting application controller...         topics="status-app" tid=1026712 file=nim_status_client.nim:190
INF 2023-04-18 21:54:28.418+04:00 starting application...                    topics="status-app" tid=1026712 file=nim_status_client.nim:193
```
Next it supposed to be 
```
ERR 2023-04-18 21:50:51.311+04:00 error:                                     topics="accounts-service" tid=1024213 file=service.nim:600 procName=verifyDatabasePassword errDesription="file is not a database"
```

Now trying to re-run pipeline for 0.11.0 branch

**Comment by MishkaRogachev** [comment]
Help wanted!
@jakubgs @jrainville @alexjba I've created a branch from this [PR](https://github.com/status-im/status-desktop/pull/10210) to test x86_64 builds for Mac. And what i've discovered: this version runs fine locally, using `make package` with x86_64 Qt version 5.15.2. And it same time CI x86_64 [package]() for this PR hangs same way as described in ticket. Any ideas?

@anastasiyaig Can i kindly ask you to confirm that [this](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/x86_64/job/package/view/change-requests/job/PR-10383/) package does not work, and locally built package for this [PR](https://github.com/status-im/status-desktop/pull/10383) works fine

**Comment by glitchminer** [comment]
Hi @MishkaRogachev , I can confirm that the package does not work (hangs on launch) and the the the PR, when built locally, does launch for both arm and x86_64.

**Comment by ajayesivan** [comment]
When launching the app it asks for the touch-id, and immediately goes to a not responding state. I'm using an intel mac.

<img src="https://user-images.githubusercontent.com/19279756/233368804-9ad8afeb-8def-42a0-990d-5ae43fdac1eb.png" width="400px"/>

**Comment by glitchminer** [comment]
> Thanks! That makes me fill it somehow related with Qt version? Are you on 5.15.2 or 5.15.8?

My intel version is 5.15.2 and the arm version is 5.15.8

**Comment by MishkaRogachev** [comment]
UPD: Tested also release builds (RELEASE=false VERBOSE=0 make pkg)
@jrainville I have no idea what to do with this task next :(

**Comment by jrainville** [comment]
@jakubgs can you check the Intel Mac hosts? What version of of Qt do they have? Is there a difference between the Intern and ARM hosts?

**Comment by jrainville** [comment]
We need someone with an Intel Mac to try to build locally (with make package), to see if that works. Also, They can easily check if the QT version is the culrpit.

@status-im/desktop anyone still have an Intel Mac?

**Comment by anastasiyaig** [comment]
@qoqobolo can u please assist?

**Comment by qoqobolo** [comment]
> @qoqobolo can u please assist?

Sure. How can I do this?

**Comment by alexjba** [comment]
The renderer thread is crashing :(

Works fine with `QSG_RENDER_LOOP=basic`. We force the renderer thread to threaded from DOtherSide in order for the splash screen not to freeze.
https://github.com/status-im/status-desktop/blob/7757c3b47d518ca7698d09a610b7864065cc38db/vendor/DOtherSide/lib/src/DOtherSide.cpp#L176-L184

**Comment by alexjba** [comment]
Would be interesting to see how it behaves on Intel Macs so that we can update the condition properly. Currently we exclude `arm64` MacOs builds. If it works fine on Intel Macs I guess we can exclude M1 CPUs.

**Comment by caybro** [comment]
Yeah, we should just disable it for Macs
