### ISSUE TITLE
Wallet -> Send: polish Send/Bridge Modals

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#10344]
### Description

- [x] 1. Circular highlight of the tokens list when send modal is launched  Magnify in search should be correct size and joint to  the list
- [x] NO token selected view
- [x] Hovering over token should update token and max on top of the modal
- [x] 0.00 with cursor is missing
- [x] clicking on max should update amount to send 
- [x] Recents account doesn’t correlated with selected account from header
- [x] On switching account the max amount should change
- [x] The my accounts list in the my accounts the list item is different and highlight I slighter
- [x] When own account is elected, the UI in to field is different and all networks are selected by default
- [x] For saved address, with and without prefix -> prefix should show in list in send Modal as well
- [x] Search list and magnify glass in saved addresses
- [x] Paste button missing inside the To field in send modal
- [ ] #10393
- [x] Token selector  combbox, highlight, search icon and placement, and only as long as the tokens list
- [x] Rounded corners for all background rects
- [x] Have padding for list with modal so that no list overflows the modal
- [ ] #10392
- [ ] #10394
- [x] size of input text in bridge is small
- [ ] Length of text too long? when tokens owned is large??
- [x] add loading state to recents in sendModal

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp i made the list to be a chec list for easier understanding what is done if u find it helpful
