### ISSUE TITLE
Count emblems and Activity Centre notifications are being displayed for muted chats/channels 

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#10345]
Version: V0.11.0-rc.6
OS: Ubuntu 22.10

When a user is ‘@’ mentioned in a 1on1 message, ad-hoc group chat or on a community channel _which they have muted_:
- A count emblem is displayed against the message/channel label
- The user receives a notification and the count emblem in incrementally increased in their Activity Centre (ad-hoc group chats / community channels only)

***

## Scenario 1

https://user-images.githubusercontent.com/124154641/232759148-642be2da-8e0a-4169-b6f9-f5487b988ad0.mp4

&nbsp;
Preconditions: Alice mutes Bob’s 1on1 chat

<ins>Steps to reproduce:</ins>

1. Bob messages Alice

_Note: currently Bob needs to ‘@’ mention Alice in their 1on1 chat for Alice to receive a count emblem against Bob’s 1on1 chat, this is incorrect. 1on1 chats should be treated like they are ‘@’ mentions, even if no actual ‘@’ mention is used. A separate issue has been raised - #[10195](https://github.com/status-im/status-desktop/issues/10195)_ 

2. Alice navigates to Messages

<ins>What currently incorrectly happens:</ins>

3. In the Messages secondary nav bar, a count emblem is displayed on Bob’s 1on1 chat label. The mute bell icon overlays Bob’s 1on1 chat count emblem. 

<ins>What is supposed to happen:</ins>
3. In Alice’s Messages secondary nav bar, no count emblem should be displayed on Bob’s 1on1 chat label as Alice has muted the chat. If the mute icon is displayed no count emblem or unread notification should be displayed.   

## Scenario 2

https://user-images.githubusercontent.com/124154641/232759171-b3602e96-5b0a-49aa-ae5c-40353efe2140.mp4

&nbsp;
Preconditions: Alice and Bob are in the same ad-hoc group chat. Alice has muted the group chat. 

<ins>Steps to reproduce:</ins>

1. Bob ‘@’ mentions Alice in the ad-hoc group chat

2. Alice navigates to Messages

<ins>What currently incorrectly happens:</ins>

3. In Alice's account: 

- Primary nav - no dot emblem is displayed against the Message icon, this is correct! 

- Messages secondary nav bar - a count emblem is displayed on the ad-hoc group chat label. 

- Activity Centre -  Alice receives a notification and the Activity Centre count emblem is incrementally increased.

<ins>What is supposed to happen:</ins>

3. As the ad-hoc group chat has been muted, Alice should receive none of the following:

- Messages secondary nav bar - No count emblem should be displayed on the ad-hoc group chat label. 

- Activity Centre - Alice should not receive a notification and the Activity Centre count emblem should not incrementally increase.

<ins>Other information</ins>
Muted Community Channels have the same issue as scenario 2. 

https://user-images.githubusercontent.com/124154641/232759194-b047e34f-71d1-4c3f-a539-facfa81fa107.mp4

&nbsp;

**Comment by John-44** [comment]
@jrainville ^

**Comment by caybro** [comment]
Looks like a visual/UI issue to me
