### ISSUE TITLE
App rebuilds even if there were no Nim file changes

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10349]
# Bug Report

## Description

When you do `make run`, even if there was no file changes, it still builds.

It seems to have started happening since the StatusQ move.

## Steps to reproduce

1. `make run` builds and launches
2. Close the app
3. `make run` again. It builds again!

#### Expected behavior

It should only build once there are Nim file changes

### Additional Information

- Status desktop version: master
- Operating System: Ubuntu

**Comment by caybro** [comment]
In Qt Creator, it's even worse: it compiles twice; once for the `build` phase, once for the `run` phase (even without any file touched at all).

**Comment by caybro** [comment]
Expected: it should still build (and install) the StatusQ module if there are QML file changes; but the _build_ time dependency on status_nim_client -> StatusQ must be removed
