### ISSUE TITLE
[Community Permissions] Update ENS icon in permission pills

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10341]
### Description

[[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=28571-596047&t=sb2ka2Qktrb7zucX-0)]

It is needed to update the ENS icon whenever it is necessary to fit with new design here:
- In permissions creation flow.
- In join community view flow.

![Screenshot 2023-04-18 at 10 14 36](https://user-images.githubusercontent.com/97019400/232715163-d3eea35f-db0c-4b18-b3c6-6acd2594c682.png)

**Comment by iurimatias** [comment]
moved to 0.13.0
