### ISSUE TITLE
Onboarding: Scrolling stuck while channel messages are loading

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10359]
# Bug Report

## Description
Observed that scrolling can get stuck for a few seconds at a time while messages are arriving. These may impact the user after restoring an account for over 20+ minutes as messages load.

https://user-images.githubusercontent.com/50769329/232924100-bf2da5ab-224b-4536-b9bd-db57a989a348.mp4

https://user-images.githubusercontent.com/50769329/232923281-5fda6501-ea93-4124-8e7b-4837400f0ca4.mp4

## Steps to reproduce

Restore account with community that has significant chat history
Attempt to scroll / navigate while the history requests are still loading messages

#### Actual behavior
Scrolling can get stuck as messages arrive or cause flicker

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10292/3/ (found during #10292 )
- Operating System: Mac

**Comment by caybro** [comment]
I think this is no longer an issue? We have the overall "loading" screen and the general scrolling performance got much better in the meantime
