### ISSUE TITLE
Make the re-encryption loading screen appear before the re-encryption starts 

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10352]
## Description

Right now, the re-encryption starts and the loading screen with the message to not shut down the app appears after the re-encryption starts. So on slower machines, the re-encryption freezes the app, and the loading screen never appears. They then close the app, thinking it it broken, not knowing that by doing that, they actually broke it.

The fix here is to make sure the loading screen appear **before** we start the re-encryption.

**Comment by jrainville** [comment]
Seems like there is an actual problem in Windows. It really does fail even before trying to re-encrypt.

I have deja-vu with that error:
```
ReEncryptKeyStoreDir error: unable to rename keyDirPath to backupKeyDirPath: rename C:\Users\sur_e\AppData\Local\Status\data\keystore\0x438551f7a44bcd9e3d32bf8c734fabb19d56dc8cd798a52b0e6d11b52e\ C:\Users\sur_e\AppData\Local\Status\data\keystore\0x438551f7a44bcd9e3d32bf8c734fabb19d56dc8c860435d798a52b0e6d11b52e\-backup: The process cannot access the ecause it is being used by another process
````
@alaibe do you remember?

I confirmed that there is no other process.

**Comment by alaibe** [comment]
@jrainville i don't remember this. I only remember the length of the path being too long but that doesn't seem to be same error

Could it be the app sleeping?

**Comment by jrainville** [comment]
I found the issue. It was a path issue. See how the path has a slash at the end.
Fixed here https://github.com/status-im/status-go/pull/3411

**Comment by jrainville** [comment]
Completed here https://github.com/status-im/status-desktop/pull/10355
