### ISSUE TITLE
Make DB re-encryption fault proof with a back-up

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10353]
### Description

Right, if the Db re-encryption is in progress, if the app is closed by any means, the DB then becomes kaput.

The solution is to first copy the DB, then re-encrypt the new copy. When it's all done, we can rename the DB to the original name, overwriting the first one.

That way, if the app is closed, the original DB is not touched.

**Alternative option**: if that doesn't work because we can only re-encrypt the active DB, we should still create a backup. If the app is closed and the DB is broken, we can then take the backup and use that one instead.
Make sure to delete the backup at the end of any of the successful endings, that way we do not use an old backup by accident.

### Acceptance Criteria

When doing a DB re-encryption by changing the password, it is possible to close the app meanwhile and then reopen. 
The state should then come back to before the re-encryption, with the old password

**Comment by alexjba** [comment]
Wrongfully closed. Should be closed by https://github.com/status-im/status-desktop/pull/11069
