### ISSUE TITLE
Chats bolded without new messages

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10365]
# Bug Report

## Description

Upon opening the app, certain chats appear bolded despite having no unread messages. It happens every time the app is opened.

https://user-images.githubusercontent.com/33099791/233069539-e70845f1-57c9-4d09-ad20-d9d172018077.mp4

## Steps to reproduce

unknown

### Additional Information

- Status desktop version: master (a362cdad16ba75e634c568fe6a0122ca62aadeef)
- Operating System: Ubuntu

**Comment by fryorcraken** [comment]
I have a similar issue with 0.11.0 on Linux Fedora.

I have one 1:1 chat and one private group chat where the only message in each chat is a message sent by me.

However, everytime I re-open the app, they both show in bold.

**Comment by jrainville** [comment]
Closing as this should have been fixed in https://github.com/status-im/status-desktop/pull/10488
