### ISSUE TITLE
Overlapping message in ad-hoc group chat 

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#10364]
## Description
Version: 0.11
OS: Windows 10

***

![04 19 Overlapping text](https://user-images.githubusercontent.com/124154641/233052603-4ac7f66e-0c6d-421a-b53d-31b5e548f854.png)

&nbsp;
The overlapping message occurred immediately after the message was posted. When switching back to the ad-hoc group chat the issue was resolved. 

&nbsp;

**Comment by alexandraB99** [comment]
@imagiMary can't reproduce on neither master nor 0.11, could you please check again

Master:
https://user-images.githubusercontent.com/31625338/234330923-46a23463-3234-48d5-9c6d-50811d89a32c.mov


0.11
https://user-images.githubusercontent.com/31625338/234330959-e8a0a068-63bd-42d4-aeeb-344f8572d437.mov
