### ISSUE TITLE
Community owner able to move channel names out of secondary nav

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#10371]
Version: 0.11.0-rc.6 / 0.11
OS: Ubuntu 22.10 / Windows 10

***

https://user-images.githubusercontent.com/124154641/233097168-8b287727-0539-4d56-8620-abf8ca7bbf01.mp4

Precondition: The user is the owner of a community with multiple channels.

<ins>Steps to reproduce:</ins>

1. The user goes into their community and rearranges multiple channels.

<ins>What currently incorrectly happens:</ins>

3. After some rearranging (I am not sure at what triggers it), the copy of a channel name that the user has been rearranging becomes lighter and at that point the user is able to move the channel name out of the secondary nav bar. 
- Once the user has moved the channel name it stays where it was placed. 
- The channel name does not move or disappear when the user navigates to other screens within the app.   
- Upon restarting the app the channel names return to their original state within the Communities secondary nav. 

<ins>What is supposed to happen:</ins>

3. A user should not be able to move channel names out of a Communities secondary nav.  

<ins>Other information</ins>
In the screencast it is always the top channel in the Communities secondary nav that goes into this funny state but any channel in any position within the secondary nav can go into this state.  
&nbsp;

**Comment by alexandraB99** [comment]
@imagiMary can't reproduce this on current master, could you please check and close, thanks!
