### ISSUE TITLE
Discord import tool disabled by default, yet downloads archives

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10372]
# Bug Report

## Description

On a fresh installation, under `Settings/Advanced`, the `Discord import tool` is disabled by default. Eventhough I haven't enabled it explicitely, it starts downloading the Discord archives.

Not sure if it's a UI issue (the advanced toggle should not be there at all if it's meant to be always enabled), or an actual bug in the import tool itself (it should not start the import when disabled)

Settings:
![image](https://user-images.githubusercontent.com/5377645/233103913-ba9e36a9-64cc-4089-b9bb-1004023e4e7c.png)

Messages:
![image](https://user-images.githubusercontent.com/5377645/233104030-9a4acc5f-34ad-40f8-988b-f9af707f7786.png)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
CC @0x-r4bbit when you come back :)

**Comment by caybro** [comment]
Got it, looks like it's a dupe of https://github.com/status-im/status-desktop/issues/10115 then, closing this one

**Comment by 0x-r4bbit** [comment]
> On a fresh installation, under Settings/Advanced, the Discord import tool is disabled by default. Eventhough I haven't enabled it explicitely, it starts downloading the Discord archives.

Just to clarify things here: 

This toggle for "Discord Import Tool" control whether or not you'll get the UI for importing discord messages and creating a community from it. This is not controlling whether or not your node will download message archives.

History archives will always be downlaoded, this is enabled by default for community members.
