### ISSUE TITLE
Make use of Infura API Key Secret for all requests

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#10375]
### Description

Infura's NFT endpoint requires usage of the API Key Secret on top of the plain API Key. This is supposedly more secure.
You can optionally enable this for all other endpoints. 
![image](https://user-images.githubusercontent.com/11161531/233124599-34471eea-5f7a-4fd7-b996-2c210bd64064.png)
![image](https://user-images.githubusercontent.com/11161531/233124634-1b5ae34f-bb46-4e51-89b1-626f1f686308.png)
Make sure the API Key Secret is used in all requests.

**Comment by anastasiyaig** [comment]
@alaibe please fit it somewhere in any iteration :)

**Comment by alaibe** [comment]
We took another approach with the proxy
