### ISSUE TITLE
App freezes intermittently if wallet has too many watch-only accounts

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#10373]
# Bug Report

## Description

The whole app will freeze for several seconds every few minutes if the wallet has several watch-only accounts. Not sure which module is responsible and what the root cause is, but it looks like the Wallet section is to blame.

I think it might be related to the number of async tasks created when`EventWalletTickReload` occurs. 

## Steps to reproduce

Add a bunch (8+) of watch-only accounts (better if they have lots of activity, collectibles, different tokens)
Try to use the app, for example to chat with somebody. The app becomes very sluggish and will freeze whenever you try to send a message.

**Comment by caybro** [comment]
Yup, been observing the same situation recently; what's worse, the app CPU usage hovers anywhere between 20-100%, even when fully idle

**Comment by alaibe** [comment]
@dlipicar @caybro is the app always busy or only every X minutes (X is probably 10)

**Comment by caybro** [comment]
> @dlipicar @caybro is the app always busy or only every X minutes (X is probably 10)
> 
> I did add 10 watch only account, all have 100+ transaction and while idle CPU is around 5% When not idle, CPU is around 7%

It's gotten much better recently after all those DB improvements... can't really reproduce now

**Comment by alaibe** [comment]
That makes sense as I think what was causing this was the write we do to the db when fetching transaction
