### ISSUE TITLE
Communities: Flickering while hovering over add channel to category button

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10380]
# Bug Report

## Description

As found during testing on the arm build of #10002, hovering over the category and especially the add channel to category button results in flickering (intel build was ok). Priority seems low but there is a usability impact in that it is a little harder to select the button.

https://user-images.githubusercontent.com/50769329/232853393-273cdb9e-f0f9-453c-a791-4592425b51f0.mp4

## Steps to reproduce

Launch MacOS arm build. Add a category and hover over the buttons.

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10002/3/ (since merged to master)
- Operating System: MacOS

**Comment by caybro** [comment]
Most likely some overlapping MouseAreas there; the difference here being a different Qt version: I'm using linux + Qt 5.15.9 and can not reproduce at all

**Comment by caybro** [comment]
I can reproduce now too on Linux :/
