### ISSUE TITLE
Communities: Newly created channels cannot be deleted until after restart

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10382]
# Bug Report

## Description

Found during testing of #10002 

Newly created channels cannot be deleted until after restart. The delete channel option is missing from the menu.

https://user-images.githubusercontent.com/50769329/233081201-e13d8520-776c-4a4a-96f8-30a2ca7152dd.mp4

## Steps to reproduce

Create a new channel in a community
Note that the right click menu is missing the delete option for all newly created channels

### Additional Information

- Status desktop version: Master
- Operating System: MacOS

**Comment by iurimatias** [comment]
moved to 0.13.0
