### ISSUE TITLE
Communities: Cannot join using the invitation link if the community data is not loaded yet

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#10422]
edit: see comment here for the way to fix it https://github.com/status-im/status-desktop/issues/10422#issuecomment-1522074156

# Bug Report

## Steps to reproduce

Click CC community invitation link.
Error is displayed and joining fails.

After some time it joined the channel.

#### Expected behavior

I am able to join the community using invitation link

#### Actual behavior

Error is showed
![image](https://user-images.githubusercontent.com/11396062/234266866-0a5802c5-fe09-4e0f-a589-06d03e67e0d6.png)

### Additional Information

- Status desktop version: 0.11.0
- Operating System: Windows

**Comment by Cuteivist** [comment]
@jrainville 
![image](https://user-images.githubusercontent.com/11396062/234308020-63911ab1-00a5-46ae-8bfe-4f30b91ef05a.png)

**Comment by jrainville** [comment]
@Cuteivist does the button work now or it still fails?

**Comment by Cuteivist** [comment]
@jrainville After it added community then it was always opening correct community tab.
Before joining I tried clicking multiple times and every time it would give me same error.
It added me to the community without app restart.

**Comment by jrainville** [comment]
> Before joining I tried clicking multiple times and every time it would give me same error.

You were clicking on the link or on the button?

**Comment by Cuteivist** [comment]
@jrainville I was clicking only the link.

**Comment by jrainville** [comment]
@borismelnik I would improve the behavior to make sure it's clear to users. So adding a loading text next to the link or a fake unfurled community box with Loading in it. And if someone clicks on the link, we should the ephemeral notification that we are loading the community data. See this comment: https://github.com/status-im/status-desktop/issues/10422#issuecomment-1522074156

**Comment by borismelnik** [comment]
Now I got it :)
