### ISSUE TITLE
MessageContextMenuView consumes a lot of memory

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10437]
`MessageContextMenuView` consumes a lot of memory, see the following:

2.3 GB is the starting usage.
|condition|memory [GB]|memory delta [GB]|
|-|-|-|
|removed ChatContentView::contextmenu|1.6|0.7|

_Originally posted by @osmaczko in https://github.com/status-im/status-desktop/issues/10343#issuecomment-1515103756_

workaround: https://github.com/status-im/status-desktop/pull/10379#issuecomment-1515218331

**Comment by igor-sirotin** [comment]
After first look, here's the plan:

1. Check the component for unused items
2. Try to use `Loader` for `StatusMenu.delegate`. 
This should improve performance significantly, because we usually only see 20-30% of all possible actions.
3. Move `deleteMessageConfirmationDialogComponent` to `Popups`
4. Move `FileDialog` to `Popups`
According to profiler, this one seems to be one of the heaviest parts.
5. Create a single instance of `Menu` for the app.
Add `messageStore` property and access the menu through `Global`
6. Remove `Utils.getContactDetailsAsJson`. 
This data is probably already available at component creation.
Also check for any other "backend" access.

**Comment by caybro** [comment]
> * Move `deleteMessageConfirmationDialogComponent` to `Popups`
> * Move `FileDialog` to `Popups`
>   According to profiler, this one seems to be one of the heaviest parts.

Good plan, this ^^ is where I'd start :)

**Comment by igor-sirotin** [comment]
Logging this here for comparison after fixes.

For me `MessageContextMenuView` loads in ~22ms.
* `ProfileHeader`  - 5ms (btw, it has another `StatusMenu` inside 👀, which takes 80% of loading time) 
* `FileDialog` - 6ms
* 19x `MenuItem`, each 1ms

<img width="1142" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/844a3665-3b8b-4c8d-acb6-7bf1884364b8">

**Comment by igor-sirotin** [comment]
Some WIP beautiful images:

<img width="1118" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/7d672974-2383-40fb-aab4-41766fc18c61">

<img width="1061" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/f395b661-38ce-454a-9c08-8fd69210ca26">

**Comment by osmaczko** [comment]
> @osmaczko , I've set this ready to merge after testing but have only checked functional points of the PR, not addressing this performance issue specifically. Please can you retry with the same method?

Sure, I will give it a try, have it on my todo list. @igor-sirotin, I'm curious to know if you had a chance to look at the memory footprint after your recent adjustments?

**Comment by igor-sirotin** [comment]
@osmaczko good point actually 😄 

I did test the memory consumption, but actually didn't get any big values even before the changes. So I just went with "obviously required" improvements and focus on dynamic creation/destruction, using QML creation time as measurement.

It was `~580 Mb` of RAM (with the workaround applied), and `~540 Mb` with the fixes.

Though now I think that I could have test it with the "big testing account". Will do that first thing tomorrow 👌

**Comment by igor-sirotin** [comment]
Testing with big shared account:

| Test stage | 9cc7d10854e0d4718970e280691d2d19fc65fce9 Memory, Gb | 5ff4b5a4351453d95cc501ef005f289e71a9ab7e Memory, Gb |
|---------|---------------|---------------|
| Launch & login | 0.95 | 0.64 |
| + opened Status Community | 1.65 | 0.82 |
| + opened shared-test-community | 1.81 | 0.88 |

@osmaczko These numbers correlate quite well with posted by you originally. 
So unless you tested it in some other way, I suppose this test is enough 🙂

**Comment by osmaczko** [comment]
> @osmaczko These numbers correlate quite well with posted by you originally.
> So unless you tested it in some other way, I suppose this test is enough

Niice!! 

> but I removed the Loader-hotfix for StatusMessageContetMenuView

I think we can revert this change for good then :muscle:

**Comment by igor-sirotin** [comment]
> I think we can revert this change for good then 💪

Sure, it's already dropped 🙂
