### ISSUE TITLE
Missing a back button when onboarding with keycard and user inserts wrong keycard

### ISSUE THREAD

**Issue by guylouis** [status-im/status-desktop#10433]
When user onboards one of his status accounts:
- this account is using a keycard
- and if the user inserts a wrong keycard 
Then the user is stuck on the screen that tells him he inserted a wrong keycard. He's stuck there and can't go back one step before to insert a new card. 

![image](https://user-images.githubusercontent.com/11461437/234525771-2fec9673-986c-44a8-ba53-4d6b303e8e43.png)

Rem: the user could actually click on the list of accounts and select another account, and select this account again, bit it is not super intuitive 

Solution: add a back button to the screen when the user has inserted a wrong keycard

**Comment by saledjenic** [comment]
@benjthayer I've assigned it to you, once you add this please assign it to me to implement that functionality.

**Comment by benjthayer** [comment]
Hi @saledjenic @guylouis I think adding a retry button in this instance might be the best route as there technically isn't a distinct previous step to go back to (the user has made a profile selection and inserted their reader/keycard which is all executed/executable from the same screen). The user just needs to be instructed on the validation screen to insert the correct card for the profile and try again. 

What do you think of handling this via some micro-copy instructing the user to insert the correct keycard for the profile with a `Try again` button like this:

<img width="1232" alt="Login" src="https://user-images.githubusercontent.com/110033914/237019680-c975b228-985a-4bee-968a-89df3c798c14.png">

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=29528-587317&t=whZ2rX5GbHFff1gY-4

cc @John-44

**Comment by saledjenic** [comment]
> I think adding a retry button in this instance might be the best route as there technically isn't a distinct previous step to go back to

@benjthayer exactly, that's what we needed. We inform user that the inserted keycard is wrong and offer a button to try again after the correct keycard is inserted. Thanks! 

Assigning this to myself now, cause I will need to implement that.

**Comment by John-44** [comment]
> Hi @saledjenic @guylouis I think adding a retry button in this instance might be the best route as there technically isn't a distinct previous step to go back to (the user has made a profile selection and inserted their reader/keycard which is all executed/executable from the same screen). The user just needs to be instructed on the validation screen to insert the correct card for the profile and try again.
> 
> What do you think of handling this via some micro-copy instructing the user to insert the correct keycard for the profile with a `Try again` button like this:
> 
> <img alt="Login" width="1232" src="https://user-images.githubusercontent.com/110033914/237019680-c975b228-985a-4bee-968a-89df3c798c14.png">
> 
> https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=29528-587317&t=whZ2rX5GbHFff1gY-4
> 
> cc @John-44

+1 from me on this change
