### ISSUE TITLE
Settings -> Change password: application is stuck when changing password in settings

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10457]
### Description

1. сreate an account
2. open profile
3. click Change password button
4. fill in the form and click confirmation button

**As result:**
- app is not responding
- no SignOut and Quit button shown

<img width="1519" alt="Screenshot 2023-04-27 at 13 46 20" src="https://user-images.githubusercontent.com/82375995/234840577-f3b107f0-a10d-4261-95d0-7a142b9b543b.png">

<img width="274" alt="Screenshot 2023-04-27 at 13 46 59" src="https://user-images.githubusercontent.com/82375995/234840673-9887fc80-fe64-45ae-8d8c-9aa658e1926a.png">

**Comment by StateOf-Vlado** [comment]
Scenario: The user can change the password and login with new password
https://github.com/status-im/status-desktop/blob/master/test/ui-test/testSuites/suite_settings/tst_mainSettingsSection/test.feature#L51

**Comment by caybro** [comment]
@anastasiyaig I _think_ it re-encrypts the whole database with the new password... and it gets stuck for dozens of minutes, @alaibe ?

**Comment by anastasiyaig** [comment]
ah right we have this screen to be implemented https://github.com/status-im/status-desktop/issues/10037 in this case (for 0.13.0 ) :(

**Comment by alaibe** [comment]
Exactly it does a full re-encryption. If you have a big db, that will take around 20minutes. If you have a small one it will be immediate. I believe there is an issue related to that but i cannot find it

**Comment by alaibe** [comment]
@anastasiyaig yes that screen

**Comment by anastasiyaig** [comment]
okay!
