### ISSUE TITLE
[StatusChatInput] The chat input is disabled for all 1to1 chats

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#10463]
### Description

The user cannot send messages in the 1to1 chats because the input is disabled.
It looks like the recipient is not a contact and the chat is disabled (input and message context menu)

See this video for better understanding:

https://user-images.githubusercontent.com/47811206/234887670-0ad0d2a0-ccef-4060-b486-b896e4c70d9a.mov

**Comment by caybro** [comment]
https://github.com/status-im/status-desktop/pull/10465
