### ISSUE TITLE
App is unresponsive/slow after extended offline period

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10471]
# Bug Report

## Description

When the app is opened after an extended offline period, it initially becomes unresponsive. Once it unblocks, loading channel content is extremely slow. However, when the app is run without an internet connection, it operates smoothly, and switching channels is almost instantaneous.

#### App getting online after extended offline period

https://user-images.githubusercontent.com/33099791/235098895-e7431f63-6fb3-4da2-944a-eb2accbfbd33.mp4

#### App in offline mode

https://user-images.githubusercontent.com/33099791/235099013-9c838138-8365-4659-a050-9f161f53d5b0.mp4

## Steps to reproduce

1. Download fresh shared-desktop-data (aka shared-dev-account)
2. `cd status-desktop-repo && rm -rf Status/data && mv shared-desktop-data/data-final Status/data`
3. Ensure internet connection
4. Open the app

#### Expected behavior

App is responsive/fast

#### Actual behavior

App is unresponsive/slow

### Additional Information

- Status desktop version: master(28374eb83646f322a974788102a572d3c235d946)
- Operating System: Ubuntu 22

**Comment by osmaczko** [comment]
It seems the problem might be related to database locks. Write operations, such as saving messages, acquire locks, causing read operations to wait. The issue is more noticeable when the app is opened after a long period of inactivity and needs to process a backlog of messages, making the app unresponsive.

cc: @cammellos @alexjba

**Comment by jrainville** [comment]
I'm moving this to 0.13 as there is no way to get it fixed, tested and merged in time for 0.12, but this is a very important issue to fix at the start of 0.13

**Comment by osmaczko** [comment]
Has been fixed on the way of https://github.com/status-im/status-desktop/issues/10558.
