### ISSUE TITLE
Pinning a message makes the app crash when receiving the signal

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10485]
# Bug Report

## Description

When one person pins a message in a community (in my case it was an admin), it makes the app crash for others when they receive that signal.

## Steps to reproduce

0. Have two accounts opened with a shared community
1. Pin a message with the admin account
2. receive the signal

Result: the app crashes for the other user

Nothing special in the logs:
```
INF 2023-04-28 13:21:48.897-04:00 received                                   topics="signals-manager" tid=41257 file=messages.nim:63 signal=messages.new messageID=2fa4373497d7fd4cb1295f4cac1f343abe2ce8f4f7680fa2e1b5e25cc17f686e
INF 2023-04-28 13:21:48.897-04:00 received                                   topics="signals-manager" tid=41257 file=messages.nim:63 signal=messages.new messageID=0x6c16ef109cbf42474f85ab7fcea42658545a91a1e4cc7da0697c25289c700766
INF 2023-04-28 13:21:48.899-04:00 shutting down...                           topics="status-app" tid=41257 file=nim_status_client.nim:161
INF 2023-04-28 13:21:48.899-04:00 logging out...                             topics="app-controller" tid=41257 file=app_controller.nim:278
Traceback (most recent call last)
/home/jonathan/dev/status-desktop/src/nim_status_client.nim(197) nim_status_client
/home/jonathan/dev/status-desktop/src/nim_status_client.nim(171) mainProc
/home/jonathan/dev/status-desktop/src/app/core/main.nim(29) delete
/home/jonathan/dev/status-desktop/src/app/core/signals/signals_manager.nim(23) delete
/home/jonathan/dev/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(64) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:747: run-linux] Segmentation fault (core dumped)
```

#### Expected behavior

Doesn't crash and the message is pinned correctly

### Additional Information

The admin account in my case was using an older version (`c3d1133dfd36d3fa487d71f8510150ac22577ae4`), but it shouldn't change anything, since it's the receiver that crashes

- Status desktop version: master `5615a534eab24ad6c2d36129080098da990dae70
- Operating System: Ubuntu 20

**Comment by igor-sirotin** [comment]
Nice bug. I can't event start the app after crash 😄

**Comment by jrainville** [comment]
lol yea, I forgot to tell. Just receiving the signal from status-go or store nodes makes it crash so the app become sunesable until we fix the bug
