### ISSUE TITLE
[Community Airdrops]: Toast messages reporting airdrop progress/completion

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#10482]
## Description

Airdrop state should be notified with etherscan links according to the design.

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=29151-559044&t=adomteD0khOvPuT1-0

![Screenshot from 2023-04-28 17-21-40](https://user-images.githubusercontent.com/20650004/235188166-9184eb43-546e-4a49-8420-c7794027e6af.png)

**Comment by jrainville** [comment]
This was already implemented by @endulab . I just tested it and it works.
