### ISSUE TITLE
[Community Airdrops]: Summary popup with fees specified per chain

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#10484]
## Description

For Airdrop, multiple chains can be involved. Fee needs to be calculated and presented separately for every chain used.

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=30691-633696&t=lALfynOe3I3770Xg-0

![Screenshot from 2023-06-05 17-42-53](https://github.com/status-im/status-desktop/assets/20650004/122b6746-3f01-40e8-812e-0267ec5d589e)

**Comment by noeliaSD** [comment]
Here it is also needed an associated backend task. @endulab could you create it? Thanks

**Comment by endulab** [comment]
@noeliaSD I have one package task. I will do it in one round.
https://github.com/status-im/status-desktop/issues/10536

**Comment by noeliaSD** [comment]
> 

Perfect!! Thank you!

**Comment by noeliaSD** [comment]
> @noeliaSD I have one package task. I will do it in one round. #10536

Perfect! Thank you!

**Comment by micieslak** [comment]
Figma link and screenshot updated to reflect recent changes.
