### ISSUE TITLE
Contacts: No toast is displayed after removing a contact

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10497]
# Bug Report

## Description

Split from and dependant on https://github.com/status-im/status-desktop/pull/10336

After removing a contact, an in app toast notification is expected but not currently displayed

## Steps to reproduce

Remove a contact via the contact's profile
Observe that no toast is displayed

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10336/20/ 
- Operating System: Mac

**Comment by John-44** [comment]
@benjthayer see my comment on issue https://github.com/status-im/status-desktop/issues/10498

Same question as that other issue really, and would like to get your thoughts on this question.
