### ISSUE TITLE
Contacts: Read only mode remains set after being unblocked

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10501]
# Bug Report

## Description

Split from and dependant on https://github.com/status-im/status-desktop/pull/10336

After Alice blocks Bob, Bob is shown a send contact request button (essentially being notified that they are blocked). It is not clear if this is the expected behaviour. [Update: It is the expected behaviour: https://github.com/status-im/status-desktop/issues/10501#issuecomment-1540079082]

If the button is used, this can result in Bob having a pending request without Alice being notified (causing issues after unblocking). After clicking unblock it appears that the users are contacts again, but the previously blocked user is still in read only view with the button to send a request.

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10336/20/
- Operating System: Mac

**Comment by John-44** [comment]
> After Alice blocks Bob, Bob is shown a send contact request button (essentially being notified that they are blocked). It is not clear if this is the expected behaviour.

This is desired behaviour.  It doesn't notify Bob that Bob has been blocked (we don't want Bob to know that Alice has blocked them), what it does do is notify Bob that Alice has removed Bob as a mutual contact (it's ok for Bob to know this).

> If the button is used, this can result in Bob having a pending request without Alice being notified (causing issues after unblocking).

We have to continue to display the 'Send contact request' button for Alice in Bob's UI, so that Bob doesn't know that Alice has blocked him.  

> If the button is used, this can result in Bob having a pending request without Alice being notified

This is desired behaviour, because Alice has blocked Bob.

**Comment by John-44** [comment]
Related issue: https://github.com/status-im/status-desktop/issues/9935

**Comment by glitchminer** [comment]
Thanks for the clarification @John-44. As it's the expected behaviour, would it be worth updating this message to clarify that it will appear to the blocked user as if they have been removed as a contact?

![image](https://github.com/status-im/status-desktop/assets/50769329/076d51c1-f430-4aee-8464-e2009c1358ae)

Just to note, this bug will still be relevant and can stay open cover the behaviour when unblocking - after clicking unblock it appears that the users are contacts again, but the previously blocked user is still in read only view with the button to send a request.
