### ISSUE TITLE
Wallet: implement toast messages (confirmations) when adding account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10510]
### Description

<img width="586" alt="Screenshot 2023-05-02 at 15 13 47" src="https://user-images.githubusercontent.com/82375995/235665966-f8b82a1d-4e4d-4513-b7dd-4aac6a539db0.png">

When adding account, the confirmation toast should be displayed indicating the successful action to the user. Should be applicable when adding:

- W/O account
- Importing using private key
- Importing via seed phrase
- Deriving a new address from default Status keypair
- Generation of new master key
- Accounts created via keycard

**Figma:** https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=13927-396344&t=QIlxb9Ht7sPwTp3S-4

**Comment by anastasiyaig** [comment]
@alaibe please estimate this and add a milestone

@John-44 @benjthayer please confirm we still want this (if yes - then do we need this for all account types or not)

**Comment by benjthayer** [comment]
Hey @anastasiyaig yes, the plan is to have the notification toast to confirm the addition of any account type :)

These include:
- W/O account
- Importing using private key
- Importing via seed phrase
- Deriving a new address from default Status keypair
- Generation of new master key
- Accounts created via keycard
