### ISSUE TITLE
[Community Permissions] Figure out how to handle admin edits without the community private key

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10519]
## Description

While working on https://github.com/status-im/status-desktop/issues/10114, @mprakhov realized that admins cannot actually modify the community description, because they do not have the community's private key, only the owner does.

So we need a way to give them the right to edit the description, kick/ban members, update permissions and all that is in the list, without them having the private key.

---

### First option: Have the change requests always hit the Owner node

 As we have it right now, the owner node is already the single source of truth, so using that same mechanism, we could have the admin send any community description change to the owner node directly, ie not processed by users, and then the owner validates that the sender is indeed an admin.
If they are an admin, update the description and send a "normal" community description edit signal that all users will recognize, because it is signed by the community key
If they are not an admin, the owner just ignores it.

#### Pros:
- Uses the same "single point of truth" mechanism already in place
- Users don't have anything different to do, they still only listen to owner changes only
- More secure as only community descriptions signed by the owner are valid

#### Cons:
- The admin node has even more responsibility
- The admin are reliant on the owner node being up
  - if the owner is not up, we need to either show a "waiting" message or optimistically update, but then have a rollback or something if the change doesn't come in
  - changes can become more unpredictable since two admins can then send similar edits at the same time, but since they are waiting on the owner, they wouldn't know it.

---

### Second option: Have change requests be validated by each individual nodes

We would update the community description to contain the list of admins. That list would be signed by the community key, so it would be known to be valid.

Then, when an admin edits a community, they send a new message type that would be something like `community-description-by-admin-updated`.
Those would be accepted by all members of the community (including admins and the owner). They will check if the person that signed the message is part of the admin list of the community.
If yes, process the update as if it was a normal community description edit from the owner.
If no, ignore.

#### Pros:
- Not reliant on the owner being up, so edits would be "instant"
- No need for a "waiting" UI

### Cons:
- All users need to do checks on signatures (new code)
- Might be an attack vector, since we now accept description changes that are not signed by the community key

---

### Conclusion

Personally, I prefer option 2, since it's gonna feel better for users and admins alike.
The attack vector should be mitigated by the admin list being signed by the community key, but we need to think it through to be sure.

There are probably other options. Feel free to add them below and to discuss the options I proposed.

cc @mprakhov @0x-r4bbit @John-44 @cammellos @iurimatias

**Comment by 0x-r4bbit** [comment]
Some additional thoughts:

**First Option**:

Another downside is that this doubles the amount of messages being sent. Even though admin nodes send a message with a community update that are only processed by the owner, other nodes in the network will still receive the message (and relay it).

**Second option**:

> Might be an attack vector, since we now accept description changes that are not signed by the community key

One "attack vector" I could think of here is that, when someone was removed from the admin list, but that update hasn't made it yet to a member node, and then the member node receives a community description update that is signed by the account that **used to be** an admin. 

The member node will still process the message as it has an outdated admin list...

Not sure how to get around that.

**Option 3**:

This is just a variation of Option 2, but I think it's worth mentioning (and I believe @osmaczko brought it up as well)

Instead of having the CommunityDescription message with an admin list  combined with a new message type signed by an admin key, we could also have a new "CommunityAdminList" message and have admins still send normal CommunityDescriptoin messages.

Member nodes would then use the adminlist signal to update their knowledge of admins and simply check communityDescription on multiple signatures (if necessary).

**Comment by cammellos** [comment]
The way that I thought original is a mixture of 1 & 2,

owners sets admin permissions, admins are able to add "addendums" (edits), which are processed by clients optimistically (the assumption is that the admin is still an admin, as @0x-r4bbit correctly points out, that might not be the case, but that's a risk the owner has to take).

The owner periodically collates those changes and incorporates them in the community description.

Something like:

```
message CommunityEdit {

CommunityDescription description = 1; // This is the latest signed by owner community description
repeated CommunityDescriptionEdit edits = 2; // This is a list of community description edits signed by the admins
}
```

This is propagated from clients directly to community members, community members will validate the community description, and validate the edits against the latest commuintydescription signed by the owner that they have.
If they pass, they will apply the edits.


The admin will periodically incorporate those changes and publish a CommunityDescription incorporating those changes.

Something on those lines it's what I initially thought, so it's a mixture of the private group chats that are completely event based, and communities that are instead always the full projection.

There some corner cases and timing issue to address of course, but that's what instinctively I would go for.

**Comment by jrainville** [comment]
Ok good, that fits with what I had in mind with my preference for option 2, but with the added bonus of the Owner doing a more valid version and passing it to the users.

If I understood correctly, the Owner would also receive the admin edits, then accumulate them, and after a time, send the "new final" version of the community to users?

I just had an idea, but maybe it can be a spam vector (see below after reading the idea). What if we do normal Option 2 of admins sending edits to users and users compare to their own community description, but then, the Owner, when they receive the edit, if **their** description doesn't accept that edit because the admin is no longer admin, then they send a new signal with the "rolled back" or "real" description (without the admin of course).
I see if as a "drop of the hammer". The Owner only sends signals if they detect a bad actor trying to send a fake edit.

Now that I think of it though, it might be a spam vector? If the fake admin knows that sending those signals makes the Owner send their own signal, then I can see it being bad.

Ok, so now I get why it should be a "collage" of edits like you said. The Owner only needs to send the true version after X time **if** they received edits.

One other option for my proposition would be then that we only send those final versions if we detected a bad edit. So if we only see good edits by real admins, the owner doesn't really need to send their own version?

(sorry for the rambling, I was kinda doing a bit of a brainstorm here haha)

**Comment by jrainville** [comment]
Closing this as we've come to a conclusion
