### ISSUE TITLE
[Community Airdrops]: Dynamic fee calculation

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#10547]
## Description

Network fee should be calculated dynamically when the user fills the "New Airdrop" form.

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22647-499102&t=pLPGuYpsAYDmvgWi-0

![Screenshot from 2023-05-04 13-26-15](https://user-images.githubusercontent.com/20650004/236191312-61296a05-2169-45a3-86dc-c55c150c8b97.png)

**Comment by micieslak** [comment]
It also needs some associated backend task. @endulab is it already defined?

**Comment by noeliaSD** [comment]
Related task: https://github.com/status-im/status-desktop/issues/10484

**Comment by noeliaSD** [comment]
> It also needs some associated backend task. @endulab is it already defined?

Probably this will be the backend task: https://github.com/status-im/status-desktop/issues/10536

**Comment by endulab** [comment]
> > It also needs some associated backend task. @endulab is it already defined?
> 
> Probably this will be the backend task: #10536

Yes.
