### ISSUE TITLE
Imported archive messages should not trigger mentions/notifications

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10544]
We have reports of users that start with a fresh account, download the history archives for a community, then after importing into the database, they see a bunch mention indicators in chat items.

Most of the downloaded history is discord messages which are unable to mention Status accounts, so it's likely that these mention originates from normal Status messages that were retrieved via the history archive.

Because importing archive messages is a similar process to handling just-in-time messages, chances are the mentions count handling isn't taken into account.

**This is a good issue for someone else to learn about the archive protocol**

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone

**Comment by iurimatias** [comment]
descoped for now
