### ISSUE TITLE
[SPIKE] Status-go Database performance investigation

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10558]
### Description

We need to figure out what are the actual main causes of the status-go database slow downs/locks.

We have a couple of ideas. We need to test them out.

Notion document to document the ideas and findings: https://www.notion.so/Database-related-performance-1dbaa7ea894c461d885e55676683be07

- [x] https://github.com/status-im/status-desktop/issues/10572
- [x] https://github.com/status-im/status-desktop/issues/10611
- [x] https://github.com/status-im/status-desktop/issues/10559
- [x] https://github.com/status-im/status-desktop/issues/10726
- [x] https://github.com/status-im/status-desktop/issues/10723
- [ ] https://github.com/status-im/status-desktop/issues/10753
- [x] https://github.com/status-im/status-desktop/issues/10588
- [x] #10767
- [x] #10815
- [ ] #10937

**Comment by caybro** [comment]
Coincidentally, I was also looking into this today and so I fired the excellent [hotspot](https://github.com/KDAB/hotspot) tool and here's a couple of findings from running the app for about 2-3 minutes (usual "messenger" session): 

36% of _all_ CPU cycles is spent inside `sha1_compress`:
![Snímek obrazovky z 2023-05-04 13-47-38](https://user-images.githubusercontent.com/5377645/236273508-da724b0b-1575-4d9f-b577-5a486f6547c9.png)

The same, using top-down breakdown:
![Snímek obrazovky z 2023-05-04 13-49-22](https://user-images.githubusercontent.com/5377645/236273840-79412f24-eff5-4ee1-994b-0f942593bbdf.png)

Going into even more detail, 27% of _all_ CPU cycles is spent on this single line, still inside `sha1_compress`:
(https://github.com/mutecomm/go-sqlcipher/blob/25f68adb9fb3bc95229bee7e3498a6ca2f3e752d/sha1.c#L61)
![Snímek obrazovky z 2023-05-04 13-57-40](https://user-images.githubusercontent.com/5377645/236274008-d6efc8b3-6582-4244-8fa4-632484677a88.png)

**Comment by caybro** [comment]
(I can upload the raw `perf.data` file, if anyone's interested in inspecting and visualizing this on Linux)

**Comment by John-44** [comment]
> I hope it gives at least some insight where (and what) to start looking in first :) The `sha1` looks like an ideal candidate for some vectorization (OpenSSL uses MMX/AVX512 or even SHA extensions found in recent Intel/AMD CPUs), I assume that implementation must be orders of magnitudes faster

Do you want to talk a look at the specific issue you've identified here (optimise sha1_compress)? ;-)

I think (but somebody correct me if I'm wrong) that looking into optimisation of sha1_compress is complementary with everything else discussed today.  If you do want to take a stab at this, I would recommend creating a seperate issue for just this task.

**Comment by caybro** [comment]
> > I hope it gives at least some insight where (and what) to start looking in first :) The `sha1` looks like an ideal candidate for some vectorization (OpenSSL uses MMX/AVX512 or even SHA extensions found in recent Intel/AMD CPUs), I assume that implementation must be orders of magnitudes faster
> 
> Do you want to talk a look at the specific issue you've identified here (optimise sha1_compress)? ;-)
> 
> I think (but somebody correct me if I'm wrong) that looking into optimisation of sha1_compress is complementary with everything else discussed today. If you do want to take a stab at this, I would recommend creating a seperate issue for just this task.

Deal ;)

**Comment by alexjba** [comment]
- [ ] https://github.com/status-im/status-desktop/issues/10572
