### ISSUE TITLE
[Community Permissions / Airdrop] Holdings dropdown searcher locked

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10561]
### Description

In holdings dropdown, searcher sometimes is broken. It seems to be disabled. It can be reproduced entering in `CommunityPermissionsSettings` and also in `airdrop` related components, but it is not reproducible always.

Here it is a video where it is reproduced (first 2 seconds, several clicks are done on the searcher and trying to input something, but no response after clicking neither after keypress)

No clear steps to follow to reproduce it. It could be something with the focus since the times it was reproduced where first times accessing to the component via `storybook`.

https://user-images.githubusercontent.com/97019400/236255041-863525ca-0941-431f-a130-3014db2ded9e.mov

First time seeing the issue was in the following PR: _Originally posted by @noeliaSD in https://github.com/status-im/status-desktop/issues/10434#issuecomment-1534998573_

**Aditional info:** macOS Monterey / v-12.3.1

**Comment by caybro** [comment]
I was able to reproduce: you can accidentally reproduce this when hitting "Shift+Tab" while the searchbox is focused; the focus is then shifted (invisibly) to the tab bar above (Assets/Collectibles/ENS). Eventhough it looks disabled, you can still type there when you manually refocus the search box by clicking on it.

**Comment by caybro** [comment]
![image](https://github.com/status-im/status-desktop/assets/5377645/ddfe5169-b0e0-41cd-bdd1-9c717f2b2a1a)
