### ISSUE TITLE
Clean-up and enhancments made to mint collectibles and assets flows

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#10591]
While brining minting assets back into scope, the overall token minting flows (for both assets and collectibles have been tidied and duplicate flows have been removed to avoid confusion.

A number of enhancements have been made in the process (the following give a top-level summary but is not an exhaustive list):

- Reintroduction of tabs to switch between minting an asset and collectible
- Clarification on how a user adds and edits token icon/artwork (file browse and drag and drop)
- Addition of description to asset minting flow
- Re-ordering of asset minting form to align with that of collectibles
- Inclusion of character limits for token name, description and symbol including validation states for all form elements
- `Total finite supply` field introduced when `Unlimited supply` is turned off
- Minting fail states
- Empty state for table that shows token holders when the token is minted but there are not any holders yet
- Burn flows
- Enhancements to remote destruct flows

Please reach out to @benjthayer to chat through the new flows before kicking off development :)

New flows Figma link:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=29373-560281&t=whZ2rX5GbHFff1gY-4

Archived flows that these new designs replace:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=29528-591554

cc @John-44 @noeliaSD

**Comment by noeliaSD** [comment]
Created / updated **UI tasks** to work on the new designs related to `mint collectibles`:

- https://github.com/status-im/status-desktop/issues/10596
- https://github.com/status-im/status-desktop/issues/10597
- https://github.com/status-im/status-desktop/issues/10601
- https://github.com/status-im/status-desktop/issues/10050
- https://github.com/status-im/status-desktop/issues/10602
- https://github.com/status-im/status-desktop/issues/10603
- TODO: [Token holders list update](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29468-617598&t=WrWw1XSn226Wpfo0-0)
- TODO: [Artwork drag/drop selection and cropping tool](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29528%3A590023&t=WrWw1XSn226Wpfo0-1)
- TODO: [Collectible component updates](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29468%3A614842&t=WrWw1XSn226Wpfo0-1). 
- TODO: [Mint process failed flow](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29528%3A590685&t=WrWw1XSn226Wpfo0-1)

**TODO: Assets flow**

**Comment by noeliaSD** [comment]
@endulab ^^

**Comment by noeliaSD** [comment]
All subtasks have been integrated so it can be closed!
