### ISSUE TITLE
Timestamp stripping year part

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#10615]
# Bug Report

## Description

In `ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml` function `formatRelativeTimestamp` strips year part for timestamp containing current year, but sometimes date formats can contain separators (like ".", " ", "/", etc).

There are also specific date format like Swedish 'yyyy-MM-dd", so removal of "yyyy" will leave "-MM-dd" format.

Example:
`dd.MM.yyyy HH:mm` changed to `dd.MM. HH:mm`

![image](https://github.com/status-im/status-desktop/assets/11396062/c1617bdd-4bac-4448-83a6-7da7d9edbaa9)

## Steps to reproduce

Use locale where dates contains separators, like Swedish (yyyy-mm-dd) or Finnish (dd.mm.yyyy)

#### Expected behavior

For dates with current year, year part in timestamp format should be removed with all separators.

#### Actual behavior

For dates with current year, only "yy" or "yyyy" is removed from timestamp format leaving any separators.

### Additional Information

- Status desktop version: 0.11.0
- Operating System: All (depends on locale)
- In #10580  https://github.com/status-im/status-desktop/pull/10580/files#diff-2c8f8d3f414b86095699323cdc038ee52271706708b1a1bc0c64f905fb6ff4b6R307 I proposed temporary fix for format with dot and spaces.

**Comment by John-44** [comment]
@caybro before working on this one, @benjthayer should take a look at this because there is a list of date behaviour somewhere that should be referenced (e.g. 'Today', 'Yesterday', etc, etc.... that works backwards in time), and we should be consistent in using this defined behaviour everywhere.

**Comment by caybro** [comment]
> @caybro before working on this one, @benjthayer should take a look at this because there is a list of date behaviour somewhere that should be referenced (e.g. 'Today', 'Yesterday', etc, etc.... that works backwards in time), and we should be consistent in using this defined behaviour everywhere. 

Got it; we already have this relative date/time stamps implemented btw

**Comment by caybro** [comment]
It already works that way in chats; not sure about the Activity Center

**Comment by caybro** [comment]
The current solution isn't ideal either, it incorrectly strips the separator (`.`) after the month (leaving it at `29.06` while it should be `29.06.`)

![Snímek obrazovky z 2023-08-28 18-58-42](https://github.com/status-im/status-desktop/assets/5377645/a7cfc8e4-7ee1-40d1-aa13-dd0e809acdef)

**Comment by caybro** [comment]
I'm afraid there's no "good" solution at the moment as we lack the support for partial date/time formatting (with selecting parts to display at the output, something that JS [IntlFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) supports but QML doesn't)
