### ISSUE TITLE
"Error handling community updates message" logs communities full info

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10628]
All communities info including chats and members with text-ecnoded images. 
A single error message is about `1'000'000` characters. 🥲

Which is quite bad for performance. 

NOTE: I won't attach the actual log message here, as it's hard to check for any sensitive data.

```
ERR 2023-05-09 13:32:05.654+03:00 Error handling community updates           topics="community-service" tid=9154151 file=service.nim:602 msg="key not found:........" communities=".........."
```

**Comment by jrainville** [comment]
https://github.com/status-im/status-desktop/issues/10641, https://github.com/status-im/status-desktop/issues/10646 and https://github.com/status-im/status-desktop/issues/10628 are all interconnected.

Something really wrong is happening in that function now. Something is not handled correctly and we need to fix that.
Also, remove the objects from the logs.
