### ISSUE TITLE
Unable to login due to sql error

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#10649]
# Bug Report

## Description

![image](https://github.com/status-im/status-desktop/assets/117639195/78e397ff-aa6e-48e2-bd61-5554878decfb)

### Additional Information

- Status desktop version: 0.12.0-rc1
- Operating System: macos

**Comment by caybro** [comment]
and I hit this on Linux too :/

![image](https://github.com/status-im/status-desktop/assets/5377645/37efce34-dfd4-414a-b880-ccc48b4e8dcd)
