### ISSUE TITLE
keycard accounts do not display a keycard icon in the wallet list of accounts

### ISSUE THREAD

**Issue by guylouis** [status-im/status-desktop#10643]
using 0.11.1 (but was the same with 0.11.0 - this is not a regression) on a ARM M1 Macosx computer. 

Our designs planned to have a keycard icon in front of keycard accounts. This is not the case in both case: 
- on a keycard profile: main accounts, derived accounts 
- on a normal (non keycard) profile: when importing a keycard account

Correct design:
<img width="867" alt="image" src="https://github.com/status-im/status-desktop/assets/11461437/b5472343-e892-4a79-b601-4c4a13ac740c">

Implementation (this is a keycard based account):
<img width="1308" alt="image" src="https://github.com/status-im/status-desktop/assets/11461437/9d8af008-61f6-441f-ae2a-d50c96e004e2">

**Comment by saledjenic** [comment]
I've checked this in the latest master and don't see any issues (or I'm missing something?). As I see all accounts display their emoji in each place they are displayed. @anastasiyaig could you check and if so, feel free to close it?


![Image](https://github.com/status-im/status-desktop/assets/86303051/9eccafc0-887c-4340-b15f-7aff47d3dfef)


![Image](https://github.com/status-im/status-desktop/assets/86303051/83c578f4-1b38-46b9-bc0f-b38b8e4091b4)


![Image](https://github.com/status-im/status-desktop/assets/86303051/8d84f20a-f2c6-4076-b30e-a3305d0a5315)

**Comment by guylouis** [comment]
<img width="867" alt="237689650-b5472343-e892-4a79-b601-4c4a13ac740c" src="https://github.com/status-im/status-desktop/assets/11461437/0c88009e-f16a-4870-b44f-7542c9fc3cad">

**Comment by saledjenic** [comment]
I see, thanks, will be handled after we merge this PR https://github.com/status-im/status-go/pull/3475 (these days hopefully).

**Comment by saledjenic** [comment]
@benjthayer thinking now about this issue, so...
- any keypair may be a regular (not migrated) or keycard (migrated to a keycard) keypair 
- if it is a keycard keypair it may have accounts which are on a keycard for real and also user can add accounts for that keypair which are not on a keycard (accounts which derivation path is out of the default Status' derivation path)

Questions:
- Do we want to mark such accounts somehow differently? (Accounts which are on a keycard has grey keycard icon on the right in the list. Maybe we can mark accounts which are derived from the keypair which is migrated to a Keycard, but for which a derivation path is out of the default Status' derivation path with the same keycard icon but in orange color, wdyt?)
- Also how do we sign a transaction for such account using a keycard or password? (My opinion is that  we need to use a Keycard cause at the end that account relates to a keypair which is migrated to a Keycard.)

**Comment by John-44** [comment]
@saledjenic @benjthayer If a user has a master keypair stored on their device, and they have derived addresses from this keypair using derivation paths that are not compatible with keycard, the user should be blocked from transferring this master keypair to a Keycard.

If a user has a master keypair stored on a Keycard, they should be blocked from deriving paths from that master keypair that use derivation paths that aren't compatible with Keycard.

----

Then given the above, if a user wishes to derive a path that's not compatible with Keycard, they have the following choices:

- if the master keypair is stored on the device, the user can use all derivation paths supported by our UI, but if they use a non-keycard compatible derivation path they have to accept that they won't be able to move that master keypair to a Keycard at a later date (unless they remove the account(s) derived from the non-keycard compatible derivation paths first)

- if the master keypair is already stored on a Keycard, the user has to accept that they can only use derivation paths that are supported by Keycard (in this case creating a derivation path that's not compatible with Keycard should simply be unavailable in the UI).  If the user does want to use a derivation path with that master keypar that's not supported by Keycard, the user will need to move the master keypair off the Keycard and back on to their device first.

**Comment by saledjenic** [comment]
That's the case we haven't handled yet and that's confused me. Because at the moment user is able to add a new account for a non-keycard compatible derivation path for a master keypair which is migrated to a Keycard and **that should not be possible**. 

That's a limitation which we will add within this issue. 

@John-44 thanks for the explanation, all clear now.

**Comment by John-44** [comment]
> That's the case we haven't handled yet and that confused me. Because at the moment user is able to add a new account for a non-keycard compatible derivation path for a master keypair which is migrated to a Keycard and **that should not be possible**.
> 
> That's a limitation which we will add within this issue.
> 
> @John-44 thanks for the explanation, all clear now.

Yes, this **should not be possible for the user to do in the UI** :-)  Well spotted, thanks for picking this up.   

@benjthayer, could you add designs for what a user should see when

1) creating (well, driving) a new account from a master key pair *stored on a keycard*.  tldr, all the options for creating a derivation path that's not keycard compatible should be removed

2) the error a user should see if they attempt to move a master keypair which has non-keycard compatible derived accounts to a keycard ( either an error message should block the user for doing this, or the user shouldn't even have this option??)

Thx!

**Comment by benjthayer** [comment]
Sounds good, thanks @John-44 @saledjenic ! I'll look into this today :)
