### ISSUE TITLE
Communities -> Minting: Transferrable flag is not applied (always False)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10648]
### Description

1. mint a token with Transferrable setting
2. open token details

As result, the token is non transferable

https://github.com/status-im/status-desktop/assets/82375995/c01a5ee0-808d-4a29-9518-468b768c8266

**Comment by mprakhov** [comment]
@anastasiyaig was not able to reproduce on 0.13.0-rc5
Could you please retest this bug on 0.13.0-rc5?

**Comment by anastasiyaig** [comment]
yes, it is quite old one, it is fixed now, thanks @mprakhov
