### ISSUE TITLE
Use setWatchedContracts

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#10658]
The `collectible` service provides function `proc setWatchedContracts*(self: Service, chainId: int, address: string, contractAddresses: seq[string])` which:
- Ensures owned collectibles for such contracts are fetched first and auto-refreshed.
- Puts collectibles from such contracts at the top of the list in the wallet's `Collectibles` tab 

Whenever a user joins (attempts to join?) a token-gated community, the corresponding contract address(es) should be added to the Watched Contracts list for that account.

Blocked by https://github.com/status-im/status-desktop/issues/10728

**Comment by anastasiyaig** [comment]
@endulab is it indeed a bug?

**Comment by endulab** [comment]
@anastasiyaig it is not a bug and not a feature - enhancement/improvement is a good word. Does "feature" suit better ?

**Comment by dlipicar** [comment]
We're now fetching the full list of collectibles in the background instead of sequentially as the user scrolls, so we need to re-define this task if there's any special requirement. If not, just close.
