### ISSUE TITLE
Add a Confirmation popup before "Clearing history" from a channel

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10651]
### Description

Twice now I have clicked on "Clear history" instead of "Mark as read" because I went too fast, and poof, there goes my history.

There should be a confirmation dialog like when we delete a message before actually Clearing the history.

### Acceptance Criteria

There is a popup shown before the history is actually cleared saying something like "Are you sure you want to clear the history from this channel" -> Yes or Cancel

**Comment by shinnok** [comment]
May I suggest we also move the **Clear History** menu item to the third vertical section, along with **Delete Chat**, and maybe, also in **red** 🛑? if it doesn't burn on the eye too much (having 2 red labels so close to each other).
This would also provide a clear separation between the two types of actions, distructive vs. non-distructive.

PS: I'm not sure this is the place to suggest such a change, please advise.

**Comment by jrainville** [comment]
> May I suggest we also move the **Clear History** menu item to the third vertical section, along with **Delete Chat**, and maybe, also in **red** stop_sign? if it doesn't burn on the eye too much (having 2 red labels so close to each other). This would also provide a clear separation between the two types of actions, distructive vs. non-distructive.
> 
> PS: I'm not sure this is the place to suggest such a change, please advise.

Yeah I think that's a good idea. Go ahead with it. Most designers are on vacation for now, but that design is old so I feel safe changing it in such a small way, but that will make it clearer.
