### ISSUE TITLE
Communities -> Minting: Token holders list is empty until restart

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10650]
### Description

Before restart:

<img width="1552" alt="Screenshot 2023-05-11 at 17 01 53" src="https://github.com/status-im/status-desktop/assets/82375995/45e511ef-b439-47b7-9734-4b621062f86f">

After restart:

<img width="1471" alt="Screenshot 2023-05-11 at 17 05 28" src="https://github.com/status-im/status-desktop/assets/82375995/5fead587-b6d1-4e94-8847-16d1d9784673">

Token details: https://goerli-optimism.etherscan.io/token/0xa78072e952c6858acadd5070433f2a7632f67638?a=0x31b4a5ef81c3bb3b8caa8a9c644629e304ce24ff

**Comment by endulab** [comment]
I have not seen it for a while. I will have an eye on this.

**Comment by anastasiyaig** [comment]
I was able to reproduce it yesterday in 0.13 rc, i guess the problem is that token status is always `in progress` maybe? I am not sure. but until I restart the app, i dont see any new token holders in the list after airdrop. What is the logic when we display the list. what are the conditions @endulab ?

**Comment by anastasiyaig** [comment]
```
Warning: qrc:/app/AppLayouts/Chat/panels/communities/SortableTokenHoldersPanel.qml:47:9: Unable to assign [undefined] to QAbstractItemModel* (qrc:/app/AppLayouts/Chat/panels/communities/SortableTokenHoldersPanel.qml:47, )
```
that what i found it the logs meanwhile (perhaps its useless)

**Comment by caybro** [comment]
> ```
> Warning: qrc:/app/AppLayouts/Chat/panels/communities/SortableTokenHoldersPanel.qml:47:9: Unable to assign [undefined] to QAbstractItemModel* (qrc:/app/AppLayouts/Chat/panels/communities/SortableTokenHoldersPanel.qml:47, )
> ```
> 
> that what i found it the logs meanwhile (perhaps its useless)

That's actually a really good catch, cc @micieslak any idea?

**Comment by 0x-r4bbit** [comment]
Closing as not reproducible as of latest `master`
