### ISSUE TITLE
Change Testnet banner color

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10667]
Currently we highlight `Testnet mode is enabled` with red colour. 
But using testnet is not actually an error. 🤔 

So maybe would be a good idea to choose a different colour (not error/success/warning).
Also, an error next to `testnet banner` doesn't take enough attention.

<img width="1312" alt="Screenshot 2023-05-12 at 16 41 26" src="https://github.com/status-im/status-desktop/assets/25482501/c774c306-bfce-41d9-9d48-cb5857a40fca">

I suppose we could use Discord Nitro banner as a reference.

<img width="1186" alt="Screenshot 2023-05-12 at 10 32 32 2" src="https://github.com/status-im/status-desktop/assets/25482501/a612d59a-d596-49d0-a0c1-ac1624c23d07">

**Comment by caybro** [comment]
Use the "orange" one (aka warning)?

**Comment by igor-sirotin** [comment]
I don't think it's a warning either. It's more like a "mode" of application to me.
I think it should be different from all colours that we have now, not to conflict with error/warning/success.

It should be smth different, so that you don't see red/orange/success permanently. Because that you get used to this colour. And when a real error/warning/success appears you might just skip it.

**Comment by caybro** [comment]
> I don't think it's a warning either. It's more like a "mode" of application to me. I think it should be different from all colours that we have now, not to conflict with error/warning/success.
> 
> It should be smth different, so that you don't see red/orange/success permanently. Because that you get used to this colour. And when a real error/warning/success appears you might just skip it.

Fully agree, I just don't like the red color as it's not an error :)

**Comment by benjthayer** [comment]
Hey @caybro @anastasiyaig @igor-sirotin - thanks for looping me in :)

We recently finished redesigning Wallet settings, and with it the flows around testnet activation/deactivation. 

As you'll see from the flows below, we've gone with the amber semantic colour for the new banner design given it is not an error as such as you say (so red is not appropriate) but there is a relevant warning attached to that mode: `In this mode, all blockchain data displayed will come from testnets and all blockchain interactions will be with testnets` which is something very important to remind the user and something for which the other semantic colours wouldnt be suitable for. 

A blue banner would feel a little too informational / passive and green also doesn't feel semantically appropriate.

We could consider another colour but other options like purple for example which are distinct from the semantic palette don't feel quite right. 

Perhaps have a quick look and let me know what you think - happy to take suggestions :)

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=15248-319698&t=iprWQUK3VKWNyrls-4

cc @John-44

**Comment by igor-sirotin** [comment]
@benjthayer thanks for your quick response!

I didn't know we were doing designs on this. Great that we came with same thoughts!
I agree with your points, `amber` looks good 👍  
And I also think that we could use purple for other great needs in the future. Like Status Nitro 😄

**Comment by igor-sirotin** [comment]
I suppose it's fine to close this issue, as it will be implemented with Wallet design updates.
