### ISSUE TITLE
Click'n'dragging doesn't scroll channels or private chats list

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#10696]
# Bug Report

## Description

Click and dragging used to work to scroll up/down the channels list or the private chats list, but now it doesn't. It still works in the chat view though. And scrolling with the touchpad still works fine everywhere.

https://github.com/status-im/status-desktop/assets/11161531/3fa3cf3c-1f67-45dc-a1d2-301a2c469776

### Additional Information

- Status desktop version: 0.12 RC1 M1 build
- Operating System: macOS 13.3.1

**Comment by dlipicar** [comment]
@jrainville is this valid? Not sure if it's desired behavior or not. Anyway, we should either close this or assing it to some Epic

**Comment by jrainville** [comment]
I think this is because we made the channel list draggable for admins in communities.
I don't know if we want it. @alexandraB99 ?

**Comment by igor-sirotin** [comment]
I believe that it shouldn't be draggable _with a mouse_. That's how in Discord. And that's default behaviour of Qt's ScrollView.
