### ISSUE TITLE
[messenger] Add reaction contains "Remove Contact" menu entry

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10695]
# Bug Report

The emoji row suddenly contains this extra item:

![image](https://github.com/status-im/status-desktop/assets/5377645/e22764d4-045e-4b42-96fa-dbf2ac3a626d)

## Description

Should be only in the full context menu

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
`1f3a595116 ui/imports/shared/views/chat/MessageContextMenuView.qml   (Alexandra Betouni  2023-05-10 15:22:26 +0300)         text: qsTr("Remove Contact")`

**Comment by igor-sirotin** [comment]
`Remove contact` option also appears for message context menu. 
Fixed that in #10729, now it only appears in `ProfileContextMenu`.

`MessageContextMenuView` had to much property-driven behaviour inside, it was easy to make such a mistake
