### ISSUE TITLE
Crash when bringing app to the front

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#10692]
# Bug Report

## Description

0.12RC1 aarch64 build on a MacBook with an M1 chip.

I wasn't doing anything special with the app. It was open in the background showing Group Chat. I clicked the bar icon to bring it to the front and it crashed. Attaching the crash log.

[CrashReport.txt](https://github.com/status-im/status-desktop/files/11477859/CrashReport.txt)

**Comment by jrainville** [comment]
I know @mprakhov experiences a hang often when maximizing the app too, so maybe it's related.

We need to investigate what is done when refocusing the app to see if something heavy is happening.

**Comment by caybro** [comment]
Not an expert in decoding macOS related backtraces but this looks like crashing on trying to play some video (GIF perhaps?)

**Comment by jrainville** [comment]
@dlipicar do you still experience this crash?

**Comment by dlipicar** [comment]
> @dlipicar do you still experience this crash?

nope, never seen it again

**Comment by jrainville** [comment]
Cool, I assume @alexjba fixed it when he fixed all the crashes. Closing
