### ISSUE TITLE
Enter Seed phrase: Wrong incorrect suggestion input 

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#10708]
# Bug Report

## Description

Suggestions list paste wrong value into input

## Steps to reproduce

1. Remove `Status` dir
2. Go to Enter the seed phrase
3. Try to input words by suggestions when suggestions more than 2

#### Expected behavior

Selected word should be pasted

#### Actual behavior

Pasted another word from suggestion list

### Additional Information

- Status desktop version: `lates master` `0.11.0`
- Operating System: `macOS`

https://github.com/status-im/status-desktop/assets/82511785/747a30cb-6c27-4856-9853-4fc3909a60ca

**Comment by anastasiyaig** [comment]
thank u for great issue description @borismelnik :+1:

**Comment by caybro** [comment]
@borismelnik how are you selecting the word from popup, keyboard or mouse? If by keyboard, which key?

**Comment by borismelnik** [comment]
> @borismelnik how are you selecting the word from popup, keyboard or mouse? If by keyboard, which key?

@caybro by keyboard, classic: Up/Down arrows and `Enter` :) Which variants I have?

**Comment by borismelnik** [comment]
I test it - `space` doesn't works it just add a space :)

**Comment by kounkou** [comment]
Hi there, 
Managed to reproduce the problem using Keyboard only. I used `Up/Down` to select the word then when I hit `Return` I can indeed see another word used in the input.
Looking into a solution to the problem
