### ISSUE TITLE
Message reactions popup shouldn't revoke reactions

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10703]
# Bug Report

## Description

When a user has already reacted to a message, context menu with more reactions doesn't highlight added reactions. And will remove them on click.

## Steps to reproduce

1. React to a message with 👍 
2. Click `Add reaction` (or open message context menu)
3. Note 👍 is not highlighted in the popup

<img width="534" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/364837a8-f6ee-4805-8a48-da5f10af97ce">

#### Expected behavior

This is a good question.

1. Currently this `Add reaction` toggles the reaction, despite the name of the button. If the reactions has already been added, it will be removed. E.g. Discord does always Add the reaction, never removes it from this menu.

1. I don't know if we have designs on this, but from code I can see that at some point of developing it was intended to highlight added reactions.

**Comment by igor-sirotin** [comment]
I know this is a minor bug, but I can simply fix this while working on https://github.com/status-im/status-desktop/issues/10437.

And anyway, please, postpone it until https://github.com/status-im/status-desktop/issues/10437 is done.

**Comment by benjthayer** [comment]
@igor-sirotin as discussed offline, it feels like the `Add reaction` emoji menu should not be a route for removing a user's existing reaction to a post - given as you say the icon and tooltip clarifying the action pertain to **adding** emoji reactions only, not removing them. 

Aligning with Discord, clicking on the emoji you have reacted with again via the emoji menu should not remove your emoji reaction. The user should only be able to remove their emoji by clicking on it underneath the message. 

One enhancement we discussed for the emoji menu was to subtly highlight (eg tick a tick or some form of wash) the emoji/s you have already reacted with so it makes it optimally clear that a) you have already reacted (especially useful for posts which have a lot of emoji reactions) and b) if so, which emoji/s you have used on the post. It is a minor annoyance for me in Discord that I don't have any feedback as to what emoji if any I have already used on a post - especially if I open the emoji menu, hit the same emoji as I used before and nothing happens except for the menu closing.

@John-44 it would be great to get your thoughts on the above and confirmation of whether the enhancement mentioned should be in scope for MVP or come later.

**Comment by igor-sirotin** [comment]
@benjthayer, by the way, GitHub seems to implement what you're proposing 🙂 
Though this highlighted reaction DOES pull it off.

<img width="386" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/30f4d4ff-6165-4749-ac86-64592c231c86">

**Comment by caybro** [comment]
Just to add some more info to this, in our current implementation, the text formatting toolbar (bold, italic, ...) also behaves the same way, ie. it toggles

**Comment by John-44** [comment]
@benjthayer our behaviour here should be exactly the same as Discord.  As long as what is being proposed makes the behaviour the same as Discord, I'm +1 :-)

**Comment by igor-sirotin** [comment]
@caybro actually already fixed that in #10729 🙂

**Comment by kounkou** [comment]
Hi,

cc @jrainville 

I went through this very interesting conversation. Summarizing what is expected.

When a user has already added a reaction `R1` on a message : 

1- Adding a reaction by going in `add reaction` and clicking R1 should have no effect (Currently the reaction R1 is removed which is not expected)
2- Clicking on the R1 directly on the message should remove the reaction (I checked and this already works)

If no objections, I will be working on the PR to fix 1-

**Comment by jrainville** [comment]
@kounkou yes you are correct. Also, could you put a visual indicator in the `add reaction` popup about which emoji is already selected? You can reuse the hover effect for now if you want, or make it blue.

**Comment by kounkou** [comment]
sure, excellent.

To complete the above : 

3- Add a visual indicator in the `add reaction` popup on which emoji is already selected

**Comment by kounkou** [comment]
### Task

cc @jrainville @igor-sirotin 

> 1- Adding a reaction by going in add reaction and clicking R1 should have no effect (Currently the reaction R1 is removed which is not expected)
2- Clicking on the R1 directly on the message should remove the reaction (I checked and this already works)
3- Add a visual indicator in the add reaction popup on which emoji is already selected

### Context 
As I went through the code for finding a way to implement a solution for the ticket, I gathered information about what is the current state along with what is needed. Please follow along.

### Current state 
Today, we maintain 2 models around the reactions on a message

- rootStore.emojiReactionsModel
- reactionsModel 

The first model contains all possible reactions (6 total as of today), and the second one is contextual to the message and contains the reactions reacted by the user.

### Problem statement
To accomplish the task of putting a visual indicator in the add reaction popup on which emoji is already selected requires, from all possible reactions (model rootStore.emojiReactionsModel), to get the reacted status by the user of the reaction (model reactionsModel). However this is cumbersome. Example problems just to list one would require doing a merge of models on the fly for each messages, etc.

### Proposal solution
I found out that a model that is a combination of some properties of each models, and that has reactions enhanced with  the `didIReactWithThisEmoji` for each reaction should be enough to solve this ticket. And this involves adding the new model in Nim for durability.

### What if we don't actually do the above :

The mere fact of iterating through the different models will be sub-optimal in complexity, which means that performance might get hit only for performing the reaction feature 😨 
Assessment of Time complexity : 

```
O(R * U * M) Time complexity

where 

R : number of reactions, R currently 6
U : number of user reacted reactions U <= R
M : number of messages
```

As you can see, this is not optimal.

### Links references, acknowledgment

- [extends number of reactions](https://status-desktop.featureupvote.com/suggestions/345525/extend-emoji-reactions)

Thanks to @igor-sirotin for answering my pointy questions 💉 😄

**Comment by jrainville** [comment]
Great report!

Like discussed offline, the new Nim model sounds like a good solution, but since you're still new to the Nim world, let's push back the implementation of it until you have more experience.
