### ISSUE TITLE
System message "user pinned message" is not visible immediately after pinning for the current user

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10702]
When a user pins a message, system message `user pinned a message` should be visible.

It is visible for the other user though.
And it's also there after app restart.

<img width="1756" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/595062d5-608a-46ee-ab75-9d9c6b6c48fe">

### Reproduce steps

1. User AAA: Send a message
1. User AAA: Pin a message
1. User B: Note system message `AAA pinned a message`
1. User AAA: Note no system message `AAA pinned a message`
1. User AAA: Restart, note system message `AAAA pinned a message`

**Comment by friofry** [comment]
fixed in https://github.com/status-im/status-desktop/pull/14146
