### ISSUE TITLE
Make sending community requests async

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10719]
Currently, when requesting access to a community, we perform a synchronous call on status-go `requestToJoinCommunity`.
This has slowly becoming an issue because we're now doing a bit more work when sending membership requests to a community.

Namely, a users node now fetches and checks balances of ERC20 and ERC721 token that live in the user's wallet (can be 1 can be many).

This fetching of data takes time, which slightly blocks the UI when sending a request to join community.

To account for that we should:

- Introduce a new async task in desktop that performs the request to join
- Have the "Request to join" button change to loading state while the async task is pending
- Once the request has been sent, change button state back to not-loading (which should then render the "membership request pending" message

/cc @jrainville this is a great task for someone new to get their feet with async tasks and the join community flow

**Comment by 0x-r4bbit** [comment]
I'm reopening this to ensure we apply the same UI changes to the request-to-join case in a token permissioned, spectated community as well

**Comment by jrainville** [comment]
I can confirm that we only support the async flow now
