### ISSUE TITLE
Communities -> Minting: Minted collectibles are not shown when minting new ones

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10727]
### Description

1. mint a token
2. make sure the token is shown on Mint tokens screen and Airdrops screen
3. mint another token (for example on Goerli) on other day
4. check Mint tokens screen

As result, there is no presence of previously successfully minted token, only tokens that i have minted today. Address to verify `0xF38D2CD3C6Ad02dD6f8B68E0A7b2f959819954b6` (minted tokens for goerli, goerli opt and goerli arb last week sucessfully but now they are not there)

<img width="1408" alt="Screenshot 2023-05-17 at 14 15 18" src="https://github.com/status-im/status-desktop/assets/82375995/791765ee-4465-496c-ba26-48809a41532c">

**Comment by 0x-r4bbit** [comment]
@anastasiyaig as discussed on Status, I've ran into a few issues with deploying NFTs through Status, but ultimately, I've deployed two and they both show up in the UI correctly.

Is there anything else I'd need to do to reproduce this?

**Comment by anastasiyaig** [comment]
ya as i suspected, i guess it is fixed already and can be closed.
