### ISSUE TITLE
Image message context menu is not available

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10737]
## Description

Right-click on an Image message should open standard message context menu.
Just `Edit` action shouldn't be available.

**Comment by caybro** [comment]
I hope we're also keeping this menu (entries): 

![image](https://github.com/status-im/status-desktop/assets/5377645/5b254b43-e278-417d-9a0f-392f9e5d4af5)

**Comment by igor-sirotin** [comment]
> I hope we're also keeping this menu (entries): 


Sure, it's still there :)
