### ISSUE TITLE
Pinned messages popup doesn't show message Images and Stickers

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10731]
# Bug report

### Messages in chat:

<img width="859" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/26a9cfee-3a9d-45b6-900b-aae90a8a1f81">

### Same messages in pinned messages popup:

<img width="829" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/c2ba736e-2e92-4ec7-8af5-837a770ce0ca">

# Steps to reproduce

1. Send a message with image
2. Send a message with sticker
3. Pin both messages
4. Open Pinned messages popup
5. Note not image or sticker displayed

**Comment by alexandraB99** [comment]
@jrainville it seems that both the image and sticker properties are empty strings coming from the model.
