### ISSUE TITLE
Chat: New chat showing fetch more before 1970

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10735]
# Bug Report

## Description

After adding a new contact and starting a chat the fetch button is labelled with Fetch more message before 1 January 1970.

![image](https://github.com/status-im/status-desktop/assets/50769329/953da3f4-e31f-4617-9697-b6c9921c78fe)

### Additional Information

- Status desktop version: 0.12.0 RC2
- Operating System: Mac

**Comment by jrainville** [comment]
It seems already fixed
