### ISSUE TITLE
Wallet -> Sending a transaction in certain locations may cause crashes because of blocked / limited requests by provider (Infura / POKT)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10730]
### Description

**UPD:** it seems that transactions performed in a location that could be blocked / banned by web3 provider (infura or pokt) are causing crashes, we need to add a guard for this

**NOTE:** this is a recovery flow as follows:

1. open status with no previous data (clean install)
2. click I already use Status
3. click I dont have other device
4. click Enter a seed phrase
5. enter a seed for account (reach out to me if u want to test on the specific account i am using)
6. log in and do not enable biometric login (use password)
7. open wallet. **NOTE:** all previously added accounts are there (even watch only accounts)

<img width="1508" alt="Screenshot 2023-05-18 at 18 29 47" src="https://github.com/status-im/status-desktop/assets/82375995/5e71df51-9395-440a-ac63-17fd887474c4">

8. click plus button
9. enter account name
10. click Edit and enter password. App crashes

```
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x1064183ca?, 0x14000102480?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x1400005a790 sp=0x1400005a760 pc=0x1062dd5c0
runtime.sigNotOnStack(0x10)
	/usr/local/go/src/runtime/signal_unix.go:1029 +0x5c fp=0x1400005a7b0 sp=0x1400005a790 pc=0x1062f38ec
runtime.adjustSignalStack(0x10, 0x1400004c000, 0x1400005a858)
	/usr/local/go/src/runtime/signal_unix.go:581 +0x250 fp=0x1400005a820 sp=0x1400005a7b0 pc=0x1062f2c20
runtime.sigtrampgo(0x10, 0x1400005a9c0, 0x1400005aa28)
	/usr/local/go/src/runtime/signal_unix.go:469 +0x170 fp=0x1400005a8a0 sp=0x1400005a820 pc=0x1062f2870
runtime.sigtrampgo(0x10, 0x1400005a9c0, 0x1400005aa28)
	<autogenerated>:1 +0x1c fp=0x1400005a8d0 sp=0x1400005a8a0 pc=0x10630eb7c
runtime.sigtramp()
	/usr/local/go/src/runtime/sys_darwin_arm64.s:227 +0x4c fp=0x1400005a990 sp=0x1400005a8d0 pc=0x10630dd5c

goroutine 34 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000056fe0 sp=0x14000056fe0 pc=0x10630cca4

goroutine 17 [running, locked to thread]:
	goroutine running on other thread; stack unavailable

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000048fa0 sp=0x14000048f80 pc=0x1062dff90
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0x14000048fd0 sp=0x14000048fa0 pc=0x1062dfde0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000048fd0 sp=0x14000048fd0 pc=0x10630cca4
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000049760 sp=0x14000049740 pc=0x1062dff90
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x98 fp=0x140000497b0 sp=0x14000049760 pc=0x1062cdae8
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x140000497d0 sp=0x140000497b0 pc=0x1062c2b48
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000497d0 sp=0x140000497d0 pc=0x10630cca4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x14000070000?, 0x10645c398?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000049f50 sp=0x14000049f30 pc=0x1062dff90
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1065ad800)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x5c fp=0x14000049f80 sp=0x14000049f50 pc=0x1062cba1c
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:628 +0x44 fp=0x14000049fb0 sp=0x14000049f80 pc=0x1062cbf74
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x14000049fd0 sp=0x14000049fb0 pc=0x1062c2ae8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000049fd0 sp=0x14000049fd0 pc=0x10630cca4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xac

goroutine 18 [finalizer wait]:
runtime.gopark(0x140000485a8?, 0x1062b7f30?, 0x40?, 0x30?, 0x103e08a90?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000048580 sp=0x14000048560 pc=0x1062dff90
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x100 fp=0x140000487d0 sp=0x14000048580 pc=0x1062c1c10
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000487d0 sp=0x140000487d0 pc=0x10630cca4
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x80
Traceback (most recent call last)
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(197) nim_status_client
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(194) mainProc
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(559) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app_service/service/keychain/service.nim(67) onKeychainManagerSuccess
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/eventemitter.nim(58) emit
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/controller.nim(147) :anonymous
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/io_interface.nim(187) keychainObtainedDataSuccess
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/module.nim(624) keychainObtainedDataSuccess
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/controller.nim(575) terminateCurrentFlow
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/controller.nim(447) cancelCurrentFlow
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app_service/service/keycard/service.nim(146) cancelCurrentFlow
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nim-keycard-go/keycard_go.nim(21) keycardCancelFlow
SIGABRT: Abnormal termination.
```

**Comment by anastasiyaig** [comment]
@alaibe @Khushboo-dev-cpp @dlipicar i finally figured it out (how to reproduce). Ping me if u need USDC, i have a lot

**Comment by Khushboo-dev-cpp** [comment]
I feel like @alaibe recently fixed this, there was a function missing or something like that.

**Comment by Khushboo-dev-cpp** [comment]
crash stack for me when sending USDC on testnet /home/khushboo/status/status-desktop/src/nim_status_client.nim(197) nim_status_client
/home/khushboo/status/status-desktop/src/nim_status_client.nim(194) mainProc
/home/khushboo/status/status-desktop/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/home/khushboo/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/home/khushboo/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/home/khushboo/status/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(565) onSlotCalled
/home/khushboo/status/status-desktop/src/app/modules/shared_modules/keycard_popup/view.nim(107) onPrimaryActionClicked
/home/khushboo/status/status-desktop/src/app/modules/shared_modules/keycard_popup/io_interface.nim(103) onPrimaryActionClicked
/home/khushboo/status/status-desktop/src/app/modules/shared_modules/keycard_popup/module.nim(337) onPrimaryActionClicked
/home/khushboo/status/status-desktop/src/app/modules/shared_modules/keycard_popup/internal/state.nim(155) executePrePrimaryStateCommand
/home/khushboo/status/status-desktop/src/app/modules/shared_modules/keycard_popup/internal/enter_password_state.nim(18) executePrePrimaryStateCommand
/home/khushboo/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(605) terminateCurrentFlow
/home/khushboo/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(571) finishFlowTermination
/home/khushboo/status/status-desktop/src/app/core/eventemitter.nim(58) emit
/home/khushboo/status/status-desktop/src/app/modules/main/controller.nim(382) :anonymous
/home/khushboo/status/status-desktop/src/app/core/eventemitter.nim(58) emit
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/send/controller.nim(53) :anonymous
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/send/io_interface.nim(42) onUserAuthenticated
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/send/module.nim(177) onUserAuthenticated
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/send/controller.nim(99) transfer
/home/khushboo/status/status-desktop/src/app_service/service/transaction/service.nim(488) transfer
/home/khushboo/status/status-desktop/src/app_service/service/transaction/service.nim(456) transferToken
/home/khushboo/status/status-desktop/src/app/core/eventemitter.nim(58) emit
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/transactions/controller.nim(47) :anonymous
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/transactions/io_interface.nim(43) transactionWasSent
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/transactions/module.nim(155) transactionWasSent
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/transactions/view.nim(152) setPendingTx
/home/khushboo/status/status-desktop/src/app/modules/main/wallet_section/transactions/model.nim(251) addNewTransactions
/home/khushboo/status/status-desktop/vendor/nimqml/src/nimqml/private/qabstractitemmodel.nim(186) endInsertRows
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:747: run-linux] Segmentation fault (core dumped)

**Comment by anastasiyaig** [comment]
I removed it from 0.12.0 because it is very edge case but it is still good to have it fixed (add guard)

**Comment by saledjenic** [comment]
> Yeah a dejavu!!! the stack trace however says something about keycard. @saledjenic could it be related?

Yes, it is related. We already have a few crash issues logged, but in general all of them refer to the same issue - keycard lib issue (one we thought was fixed by changing Go version).

**Comment by anastasiyaig** [comment]
closing this one in favor of https://github.com/status-im/status-desktop/issues/10743
