### ISSUE TITLE
Community -> Can't accept a member to community with permission set on mainnet

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10736]
### Description

1. app is not showing the prompt to accept incoming request without restart
2. when the membership request appears after restart, then accepting it crashes app

Steps to reproduce:

1. create community on mainnet with membership approval required flag
2. add permission rule that user has to have 10 SNT and 0.01 ETH to join the community
3. add a person to contacts
4. send invitation to the community
5. as a person who was invited, reveal your address and send a request to join
6. as community owner, check the pending requests -> as result there is no any of them
7. restart the app -> observe the incoming membership request appears -> accept it

As result the app crashes

```
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(197) nim_status_client
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(194) mainProc
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(560) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app_service/service/community/service.nim(1395) onAsyncAcceptRequestToJoinCommunityDone
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/eventemitter.nim(58) emit
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/main/controller.nim(355) :anonymous
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(54) sysFatal
Error: unhandled exception: invalid object conversion [ObjectConversionDefect]
```

**Comment by borismelnik** [comment]
@jrainville @0x-r4bbit I fix the crash but I still see an error from status go `no opensea client`. Should I fix it in current PR or should create another issue?

**Comment by 0x-r4bbit** [comment]
@borismelnik did you set up the opensea API key?
