### ISSUE TITLE
Chat: Context menu for gif downloads/copies a png file

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10747]
# Bug Report

## Description

Instead of copying or downloading a gif file from a message the context menu options are copying/downloading a frame of the gif as a png.

![image](https://github.com/status-im/status-desktop/assets/50769329/ec8b0d8f-238d-44dc-9385-f613e9562193)

### Additional Information

- Status desktop version: 0.12.0 RC2
- Operating System: Mac

**Comment by caybro** [comment]
This also ignores the selected target folder and always saves to `~/Pictures` (at least here on Linux)

**Comment by caybro** [comment]
The reason why the GIF is not saved properly: https://doc.qt.io/qt-5/qimage.html#reading-and-writing-image-files

GIF is supported only for reading

Will use a generic [QSaveFile](https://doc.qt.io/qt-5/qsavefile.html) with MIME type (auto extension) detection support
