### ISSUE TITLE
Community: new user is mentioned by past messages

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10745]
### Description

<img width="274" alt="Screenshot 2023-05-19 at 11 34 47" src="https://github.com/status-im/status-desktop/assets/82375995/9f4252a5-b99c-4487-8820-f18c5e3269dd">

1. create community
2. in several chats send `@everyone` mentioning
3. create new user and add it to the community
4. allow this user to fetch messages

As the result, user is receiving mentions from the past messages when he was not a part of community yet

**Comment by jrainville** [comment]
Could you also see the messages in the community, or just the AC notif?

Anyway, maybe we should change it so that only the direct mentions from the past work?
