### ISSUE TITLE
[Performance] Test different DB configurations (4096+ page size, new SQLCipher and SQLite versions)

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#10753]
### Description

See https://www.notion.so/Database-related-performance-1dbaa7ea894c461d885e55676683be07?pvs=4#65a0277e8fc243648355ab4478794cb6

Would the page size improve performance? We currently use 1024, but based on docs it was a good choice for 2003 systems. https://www.sqlite.org/pgszchng2016.html 

The page size configuration is one of the breaking changes in newer SQLCipher Versions. Increasing the page size to 4096 would allow us to use SQLCipher 4 with latest SQLite https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/.

The goal of this task is to answer the following questions:

- [ ] What are the implications of migrating to latest SQLCipher 4? If migrating the DB to latest SQLCipher is not an option, how about migrating the lib to latest SQLCipher and open the DB in compatibility mode? See https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_compatibility
- [ ] Quantify the performance improvement on different scenarios: increased page size, upgraded SQLCipher/SQLite versions, Migrate the DB to latest SQLCipher

**Comment by caybro** [comment]
If upgrading, are we talking about this https://github.com/xeodou/go-sqlcipher?

It doesn't use the bundled tomcrypt any longer, instead relies on system supplied openSSL

**Comment by alexjba** [comment]
> If upgrading, are we talking about this https://github.com/xeodou/go-sqlcipher?
> 
> It doesn't use the bundled tomcrypt any longer, instead relies on system supplied openSSL

Not necessarily, but looks like a nice implementation. I was thinking first to test the latest mutecomm sqlcipher + latest improvements.

**Comment by alexjba** [comment]
Based on benchmarking the best performance we can get is using the latest `sqlcipher` with our improved crypto implementation and increase the page size.

<img width="1003" alt="Screenshot 2023-05-26 at 15 46 46" src="https://github.com/status-im/status-desktop/assets/47811206/9b0b9e57-8d55-4c03-bfff-83be6f454456">
