### ISSUE TITLE
addresses should display first 4 characters 0x1234 instead of 0x123

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1077]
![qSUoiPQ.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/988d6fb2-5430-4a2e-9f48-3024fd914827)

**Comment by PascalPrecht** [comment]
Quick note on this one. I moved it to icebox because this is very likely fixed. Couldn't find a single spot in the application where addresses render less than 4 characters after `0x`
