### ISSUE TITLE
Wallet Footer for watch only accounts should show only "Receive" as an option

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#10786]
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12973-388819&t=vJHpfHQMhv8pSSPN-4

**Comment by John-44** [comment]
@Khushboo-dev-cpp @benjthayer shouldn't "Buy" be an option for 'watch only' accounts as well?

Sorry, only just noticed this.
