### ISSUE TITLE
Update community description validation

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10782]
### Description
 Nowadays we are not allowing periods/dots in a community description. 
![image](https://github.com/status-im/status-desktop/assets/97019400/7880721a-690b-467b-8874-f3a13fb5f335)

According to new design decision: Amend the validation parameters to ensure periods/fullstops are allowed: `[A-Za-z0-9_-.\u0020]`

**Comment by caybro** [comment]
Dupe of https://github.com/status-im/status-desktop/issues/11307 (which has more info)
