### ISSUE TITLE
Extend Bridge Tx detection support

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#10791]
We currently only support ETH bridge Tx detection (L1->L2, L2->L1, L2->L2) done through Hop.

- [ ] Detect Hop ERC20 bridge Txs 
https://docs.hop.exchange/v/developer-docs/smart-contracts/integration
- [ ] Detect Celer Bridge ETH bridge Txs
https://cbridge-docs.celer.network/
- [ ] Detect Celer Bridge ERC20 bridge Txs
https://cbridge-docs.celer.network/
- [ ] Detect Standard Bridge bridge Txs
https://community.optimism.io/docs/developers/bridge/standard-bridge/

**Comment by saledjenic** [comment]
@dlipicar what's the state of this one?

**Comment by dlipicar** [comment]
@saledjenic 0 work has been done for this, but it's still desired I believe. No idea about the priority.

**Comment by saledjenic** [comment]
In a private discussion, Dario suggested:

Since we've got some logic implemented to detect Bridge transactions based on the Event Logs in services/wallet/transfer/bridge_identifier.go, used by
```
func (c *transfersCommand) checkAndProcessBridgeMultiTx(ctx context.Context, tx Transaction) (bool, error) {
    for _, subTx := range tx {
        switch subTx.Type {
        // If the Tx contains any hopBridge subTx, create/update Bridge multiTx
        case w_common.HopBridgeFrom, w_common.HopBridgeTo:
            multiTransaction, err := buildHopBridgeMultitransaction(ctx, c.chainClient, c.transactionManager, c.tokenManager, subTx)
            if err != nil {
                return false, err
            }

            if multiTransaction != nil {
                setMultiTxID(tx, multiTransaction.ID)
                c.markMultiTxTokensAsPreviouslyOwned(ctx, multiTransaction, subTx.Address)
                return true, nil
            }
        }
    }

    return false, nil
}
```
the current implementation is limited to
-) Only Hop (no other providers)
-) Only ETH bridges (no ERC20 bridges)
and we need to extend it.

We need to check this and see what we need to do.
