### ISSUE TITLE
Add zooming funcionality in EditCroppedImagePanel

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#10802]
### Description
[Cropping tool window](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29656%3A618763&t=2d7jz2hsUN6PVeZ3-1) minimum heigh or width should be set by default fitting the minimum heigh or width of the selected image. Figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=389-95124

Updated Figma: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=29631-694670&mode=design&t=pXVNdgAoAmvgl7co-4

eg Use Cases:
[For collectibles](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29468%3A611074&t=hPIthm2iHjUAucFk-1)
https://user-images.githubusercontent.com/97019400/237324630-c313ec39-5b47-409e-8f1a-e8c6c2dc39f3.png

[For assets](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29384%3A563130&t=hPIthm2iHjUAucFk-1)
https://user-images.githubusercontent.com/97019400/237324807-f6a1ba51-e0aa-4bb9-9a4f-8f294755b870.png

**Comment by noeliaSD** [comment]
We've agreed with @benjthayer to extend it to the whole app where an image can be cropped. I.e: `BannerPicker`, `LogoPicker`, `user profile` selector and `mint collectible / asset`. Should be needed to check if there are other places in the app where the cropping tool is also used, and apply this image / zoom / window initialization too.

**Comment by caybro** [comment]
Image in a group chat channel?

**Comment by noeliaSD** [comment]
> Image in a group chat channel?

Yes! It also can be cropped! Good point!

**Comment by caybro** [comment]
So this is already implemented in all the places that I checked: community logo and banner pickers, user profile image and also the mint token.
