### ISSUE TITLE
Keycard: Preventing a user from migrating a master keypair to Keycard when it contains an account with a derivation path that is incompatible with Keycard

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#10808]
A variant dialog has been created for the following Keycard settings flows to prevent a user from migrating a keypair to a Keycard when it features one or more account that has a non-Ethereum (Keycard incompatible) derivation path:

`Setup a new Keycard with an existing account`
`Migrate an existing account from Status Desktop to Keycard` 

Essentially, any master keypair that contains such an account does not feature the radio button control and therefore cannot be selected and thus migrated to Keycard. 

To clarify to the user why the radio button is missing from this master keypair, we add the following info copy:

`Contains accounts with Keycard incompatible derivation paths`

This copy should be adjusted depending on the number of Keycard incompatible accounts there are related to the master keypair:

Key contains 1 account that is incompatible: 
`Contains an account with Keycard incompatible derivation path`

Key contains >1 account that is incompatible:
`Contains accounts with Keycard incompatible derivation paths`

<img width="640" alt="Keycard-incompatible account" src="https://github.com/status-im/status-desktop/assets/110033914/8225f58b-6c28-4fa2-892b-5dec25e20d50">

Figma:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15881-367173&t=qv5HfQoo3Dwq7lOs-4

cc @John-44 @saledjenic

**Comment by saledjenic** [comment]
@benjthayer thanks for the updated, this was already implemented, the only what was missing is that info note which you added. That's implemented in this PR https://github.com/status-im/status-desktop/pull/10813 now.
