### ISSUE TITLE
Onboarding: wrong screen when logging in with incorrect password

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10819]
### Description

1. create basic account with password
2. login
3. logout
4. try to login with wrong password

<img width="1482" alt="Screenshot 2023-05-26 at 12 05 31" src="https://github.com/status-im/status-desktop/assets/82375995/b4679f74-694d-472e-b22a-02c2449b6795">

**Comment by caybro** [comment]
Now this might be due to the DB pool changes, CC @alexjba

**Comment by caybro** [comment]
@anastasiyaig do you have (or have you used) the keycard when logging in?

**Comment by anastasiyaig** [comment]
@caybro it is basic account (regular non-keycard account) created with password without any stored user data (data folder is clean)

**Comment by caybro** [comment]
After this fix, we still get the wrong error message @osmaczko @alexjba:

![image](https://github.com/status-im/status-desktop/assets/5377645/4fcf9838-d632-4be8-b926-2740150f132e)

**Comment by saledjenic** [comment]
> After this fix, we still get the wrong error message @osmaczko @alexjba:

It was like that before I guess? I mean maybe not the same error, but also it was some db error displayed.

**Comment by alexjba** [comment]
> After this fix, we still get the wrong error message @osmaczko @alexjba:
> 
> ![image](https://user-images.githubusercontent.com/5377645/241180498-4fcf9838-d632-4be8-b926-2740150f132e.png)

<img width="1422" alt="Screenshot 2023-05-26 at 13 20 20" src="https://github.com/status-im/status-desktop/assets/47811206/48dc6484-1f7b-45b9-ae62-6fd70bc715d8">

^This is what we've had before. 

We have new error messages now since the DB pool implementation. Looks like we're expecting this specific error in order to show the appropriate wrong password message in the UI:
```
if (error === "file is not a database") {
```

**Comment by osmaczko** [comment]
> Looks like we're expecting this specific error in order to show the appropriate wrong password message in the UI:

```
if (error === "file is not a database") {
```

:man_facepalming: principle of least surprise, you change the error string and then feature stops working. I will fix.

**Comment by caybro** [comment]
> > Looks like we're expecting this specific error in order to show the appropriate wrong password message in the UI:
> 
> ```
> if (error === "file is not a database") {
> ```
> 
> man_facepalming principle of least surprise, you change the error string and then feature stops working. I will fix.

Well we now have several different error strings :)
