### ISSUE TITLE
Deriving a new account from a Keycard-stored master keypair: Prevent use of non-Ethereum derivation path

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#10810]
When a user has a master keypair stored on a Keycard, it should not be possible for them to derive a new address from that keypair by using a derivation path that is not compatible with Keycard.

To prevent the user from getting into this state, we can simply remove the combo box functionality from the derivation path field in the add new account flow for accounts being derived from a master keypair stored on Keycard. This means the user can only ever edit the address index and will therefore always use a standard Ethereum derivation path which will always be compatible with Keycard.

<img width="480" alt="Add Account --_ Derivation path in edit mode" src="https://github.com/status-im/status-desktop/assets/110033914/c4dd7bec-de73-4247-afd7-9a3382db90b5">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12272-278364&t=Cp7fl6Y22OdzOSlq-4

cc @saledjenic @John-44

**Comment by saledjenic** [comment]
Closing this issue cause this is already implemented in commit `36ca4cd8f925677b204c649d67953e52569f4348`.
