### ISSUE TITLE
NavBar: Right clicking on `Wallet`, `Community Portal` and `Settings` highlight them

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#10824]
# Bug Report

## Description

Right click on these items trying to open some popup and failed:
```
Warning: qrc:/StatusQ/Controls/StatusNavBarTabButton.qml:49: TypeError: Cannot read property 'popup' of null (qrc:/StatusQ/Controls/StatusNavBarTabButton.qml:49, )
```

As side effect this action highlights the items:

![Снимок экрана 2023-05-26 в 14 58 56](https://github.com/status-im/status-desktop/assets/82511785/3e83b09b-ae2d-45bd-848c-2e9e1f5d109a)

## Steps to reproduce

1. Login to the app
2. Click on `Settings` or `Wallet` or `Community Portal` by right mouse button

#### Expected behavior

This action do nothing (I guess)

#### Actual behavior

Emit the warning and highlight the items until reloading the app

### Additional Information

- Status desktop version: `latest master`
- Operating System: `macOS`

**Comment by caybro** [comment]
I can't reproduce in today's master but I believe you, it used to happen some time ago :)

**Comment by caybro** [comment]
> > I can't reproduce in today's master but I believe you, it used to happen some time ago :)
> 
> Do you test it on macOS? :)

Nope, on Linux
