### ISSUE TITLE
Wrong error message on incorrect password

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10830]
After this fix, we still get the wrong error message @osmaczko @alexjba:

![image](https://github.com/status-im/status-desktop/assets/5377645/4fcf9838-d632-4be8-b926-2740150f132e)

_Originally posted by @caybro in https://github.com/status-im/status-desktop/issues/10819#issuecomment-1564102252_

**Comment by anastasiyaig** [comment]
@jrainville just so u know, we need to fix it in 0.13.0
