### ISSUE TITLE
Create GenerateShareURL functions in status-go

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10851]
### Description

The Web team came up with a new format for the share links.
We need to create a new status-go function/API to generate those.
We also need the function/API to "decrypt" them when we see them in a message.

The reason for it to be in status-go is so mobile can take advantage of them as well.

You can find the spec here: https://github.com/vacp2p/rfc/pull/600

Discussion here: https://github.com/status-im/status-web/issues/327

### Acceptance Criteria

- The status-go backend has one or multiple functions that can generate a "share url" for:
  - community `/c/` (to open the community)
  - community channel `/cc/` (to open a community channel in the community) 
  - user `/u/` (to open the 1-1 chat)
- The status-go backend has a function to "decrypt" those URLs. 2 options:
  - Basic API that we pass the URL to and it gives us the link data as JSON
  - Better but more complex approach: detect those links in the messages when we handle the message and add the link data to the message object itself.
- There is one or more tests in status-go for that API

Does **not** include any UI work or linking yet.

**Comment by MishkaRogachev** [comment]
A few tails:
https://github.com/status-im/status-desktop/issues/11403
https://github.com/status-im/status-go/issues/3713
