### ISSUE TITLE
Update UI to use the new CreateShareURL api

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10852]
### Description

Dependent on https://github.com/status-im/status-desktop/issues/10851

Anywhere we still use direct uses of `status.app/`, replace by using the status-go function and its return.

Also update the MessageLinkComponent to unfurl on those new link formats.
This will need to use the new API to "decrypt" the URL or the new message properties if the URL is decrypted "automatically" when handling messages.

### Acceptance Criteria

- All the places where we show share URLs now show the new format:
  - community links in the community popup and invite popup
  - user links in the profile popup and settings
  - any other place where share links are used
- The new share URLs are unfurled correctly in the chats (as before, but with the new format)
  - the old format does **not** need to be supported still

**Comment by felicio** [comment]
Please,

> The new share URLs are unfurled correctly in the chats (as before, but with the new format)

Is this referring to normal OG images or custom possibly dynamic cards like the one below

<img width="466" alt="image" src="https://github.com/status-im/status-desktop/assets/13265126/6dc2dc67-0a5a-49fd-994b-f38343ff243f">

Also, would you say it's fair/expected to add the following point(s) too?

- using[/unfurling] when previewing in app too (not og images) (e.g. when navigating from website or QR to app to preview a community that you're not a member of, or to a profile you don't have in contacts)

**Comment by jrainville** [comment]
> Is this referring to normal OG images or custom possibly dynamic cards like the one below?

Normal OG images. The new dynamic card will be done in this task https://github.com/status-im/status-desktop/issues/10585 which will be done by the UI team instead.

> using[/unfurling] when previewing in app too (not og images) (e.g. when navigating from website or QR to app to preview a community that you're not a member of, or to a profile you don't have in contacts)

Just to be sure I understand your point/question, you're saying that when using a link outside the app (website or QR), if it's a community that you're not member of, it will open the community in spectate mode. If it's a chat key of a non-contact, it will open the profile?

If that's so, then point 1 about community is already done and included. I guess I could add a point to make sure it still works.

The second point about opening the profile, I'm not sure. I don't think I tested it, but it should be simple enough to do.

Anyway, I don't think it's worth adding to this particular issue. This issue is for adapting to the status-go backend that will be done in https://github.com/status-im/status-desktop/issues/10851
So it's more a refactor than a new feature.

If anything, most new features will come with the UI issue https://github.com/status-im/status-desktop/issues/10585 

I'll still add an issue for opening the profile of a non-contact when using a link. If it's already done, then nothing lost, otherwise, we'll implement it. Like I said, it shouldn't be too hard since all the pieces are already there.

**Comment by felicio** [comment]
@jrainville 

> If that's so, then point 1 about community is already done and included.

Correct.

>  I guess I could add a point to make sure it still works.

Perfect, I think it makes sense to ensure these https://github.com/vacp2p/rfc/pull/602#discussion_r1213035855 formats would be handled.

> I'll still add an issue for opening the profile of a non-contact when using a link.

Nice, thank you.

So far none of these work for me,

> note: new scheme will be `https://` and `status-app://`

> note: GitHub does not display custom schemes as links, so copy paste it to your browser's address bar and enter, for example

Community:

- status-im://c#zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11
- status-im://c/iyKACkQKB0Rvb2RsZXMSJ0NvbG9yaW5nIHRoZSB3b3JsZCB3aXRoIGpveSDigKIg4bSXIOKAohiYohsiByMxMzFEMkYqAwEhMwM=#QnO2hw5tVAE-MD5i8Mq4s_oGWd0rRFmlObgRUNQXtUNwP1ixFw914Y4-BQpF08KOqpaULCh7UCtlWR-O0YP8MwA=

Channel:

- status-im://cc/003cdcd5-e065-48f9-b166-b1a94ac75a11#zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11
- status-im://cc/G54AAKwObLdpiGjXnckYzRcOSq0QQAS_CURGfqVU42ceGHCObstUIknTTZDOKF3E8y2MSicncpO7fTskXnoACiPKeejvjtLTGWNxUhlT7fyQS7Jrr33UVHluxv_PLjV2ePGw5GQ33innzeK34pInIgUGs5RjdQifMVmURalxxQKwiuoY5zwIjixWWRHqjHM=#7aeB-M6pIbvpSVGM4TeJkKWPya4YRAHbq4amL0cHlSBpRKn7_lyR4kxEDo2hC4koqPWYe_ak2R9cSVKSiV_nNAA=

User:

- status-im://u/jakubgs.eth
- status-im://u#zQ3shrdY7cMv1vQKs6g73kqsPGFfyMdoKLZRCQeAP5o1dePKj
- status-im://u/G10A4B0JdgwyRww90WXtnP1oNH1ZLQNM0yX0Ja9YyAMjrqSZIYINOHCbFhrnKRAcPGStPxCMJDSZlGCKzmZrJcimHY8BbcXlORrElv_BbQEegnMDPx1g9C5VVNl0fE4y#LbQUdJDHCKoi8DzoYyX89bpKrTjVV3ShqH3E64bDifJB2GkedtLBfVKA02RbUfX074pb9i3owGwRdS6x_ntxrQA=

**Comment by jrainville** [comment]
> So far none of these work for me,

Yeah, that's gonna be so until we we do the https://github.com/status-im/status-desktop/issues/10851

Though we could support the ENS name as part of an other issue.

**Comment by felicio** [comment]
> Yeah, that's gonna be so until we we do the https://github.com/status-im/status-desktop/issues/10851

I understand why the encoded ones aren't working, but I'm surprised even the plain ones like the following don't.

- status-im://c/zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11
- status-im://cc/003cdcd5-e065-48f9-b166-b1a94ac75a11/zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11
- status-im://u/zQ3shrdY7cMv1vQKs6g73kqsPGFfyMdoKLZRCQeAP5o1dePKj

**Comment by felicio** [comment]
> but in the spec, it's /u#<ens_name> (with hash tag)

Right, edited the comment.

**Comment by jrainville** [comment]
Issue for the ENS https://github.com/status-im/status-desktop/issues/10907

**Comment by jrainville** [comment]
> I understand why the encoded ones aren't working, but I'm surprised even the plain ones like the following don't.

I tested the community and user one on Windows one or two weeks ago when I changed the prefix to status-app and they worked.

Which OS are you on? Deep links don't work on Linux yet. Mac, I'm not sure. I heard that they might be broken. @borismelnik is gonna fix if that,s the case as part of the task to change to status-app as well

**Comment by felicio** [comment]
> > Yeah, that's gonna be so until we we do the #10851
> 
> I understand why the encoded ones aren't working, but I'm surprised even the plain ones like the following don't.
> 
> * status-im://c/zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11
> * status-im://cc/003cdcd5-e065-48f9-b166-b1a94ac75a11/zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11
> * status-im://u/zQ3shrdY7cMv1vQKs6g73kqsPGFfyMdoKLZRCQeAP5o1dePKj
> 
> Since I thought you said they would. Note, that these are just for demo of current implementation (not) working.

Might be due to PK serialization 🤔.

**Comment by felicio** [comment]
> I tested the community and user one on Windows 

Cool.

> Which OS are you on?

macOS.

> is gonna fix if that

Nice.
