### ISSUE TITLE
Change community join flow to always ask for sharing addresses

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10853]
### Description

As discovered when working on the community airdrop feature, to airdrop tokens to users in a community, we need their wallet address.

However, currently, users only share their addresses when the community already has a permission. In the airdrop use case, most of the time, the community will start with no permission and then the permission will be created for certain channels or for admins, using the airdrop feature.

Therefore, the temporary solution is to **always** ask users to share their wallet address when joining any community.

The flow is already there for permissioned communities, we just need to expand it to those without permissions as well.

In the case of a community with no permission, the spectate screen stays the same, but when the user clicks on the "Join the community" button, they will instead see the popup that asks for them to share their address, regardless of it being on request or not.
Figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=2244-260547&t=FFyigg7zVGKkn0sX-0
(ignore the captcha)
It's possible that this popup is already implemented and can be reused from the permissioned community flow.

**Additional info**
We now use a new mechanism for sharing the address that adds the needed chainIDs to check the tokens for the owner, but since there is no permission yet, ie no balance to check, you can make it so it shares no chainID for now.

Then, if the owner adds a permission, it would be the owner's responsibility to check all of Status' known chains and create the chainID array to fulfill the new permissions.
@0x-r4bbit can you confirm if the mechanism is already working like this where the control node will check all chains if the user has no chainID set yet? 

### Acceptance Criteria

- All communities ask to reveal addresses
- The control node aggregates those addresses, same as for a permissioned community 
- If a community becomes permissioned after that, the user's address is able to be checked. The is kicked or kept depending on whether they possess the tokens
- Stays backwards compatible with old communities
  - For example, the Status CC community should not encounter any problem even if the users didn't share their address
  - ie even if we ask new communities to share address all the time, old communities with no addresses should still work as intended.

**Comment by 0x-r4bbit** [comment]
@MishkaRogachev depends if it's a community that has the "Request to join required" flag set or not.
If yes, then the admin has to manually approve all incoming requests (this has nothing to do with token permissions btw)
