### ISSUE TITLE
Desktop v0.12.0 Mac Terms Acceptance Dialog Checkboxes not very Visible

### ISSUE THREAD

**Issue by easye** [status-im/status-desktop#10859]
After installing the Status Desktop v0.12 Beta for macOS/M1 <https://status-im-files.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-v0.12.0-85bbd3-aarch64.dmg>, the checkboxes on the "Before you get started…" modal are not very visible under.  They "work" if pressed, so this is not a bug per se, but probably slightly confusing for new users.

![image](https://github.com/status-im/status-desktop/assets/864261/b4b5c3ed-69cd-4298-925e-376001ad9a88)

**Comment by caybro** [comment]
This had been fixed in master (the area is scrollable now)
