### ISSUE TITLE
[StatusChatInput] replied multiline code message looks bad

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#10855]
# Bug Report

Replying to a single line of code looks fine 👌 
<img width="570" alt="Screenshot 2023-05-30 at 10 38 21" src="https://github.com/status-im/status-desktop/assets/25482501/94c43c2b-88f4-4124-946a-bcd3adc85097">

But replying to a multilne code message looks like this 🙁 
The background color of code style is the same as `StatusChatInput` background color. And there's no margin between:
<img width="562" alt="Screenshot 2023-05-30 at 10 40 57" src="https://github.com/status-im/status-desktop/assets/25482501/770c5bf6-a251-4529-a4ac-44e003fb0bdf">

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
