### ISSUE TITLE
New date range picker for Status desktop

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#10862]
As part of the rework of wallet activity, a new date range picker design was created allowing the user to filter their activity according to specific date parameters.

Eventually, it would be ideal to use the same date picker design / component throughout the app to ensure consistent user experience (eg including date picker featured as part of the Discord Import flow).

NB This date picker is planned as post-MVP work for the wallet but logging as per @caybro's request :) 

Figma designs:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12651-321990&t=uGwQJyFaAx4MXuaO-4

<img width="1529" alt="Screenshot 2023-05-30 at 15 11 33" src="https://github.com/status-im/status-desktop/assets/110033914/7ba6e845-8c2f-4b17-8aa6-70c8b0cff3c2">

**Comment by caybro** [comment]
FYI, integrating the changes done here in this issue will also fix the defunct date range picker for Wallet
