### ISSUE TITLE
Add new unfurling setting to change if senders want to fetch Link data when sending messages

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10866]
### Description

Related to https://github.com/status-im/status-desktop/issues/10863

Currently, it's the receivers that fetch the data from links, but with the new feature added with the issue above, it's the sender that will fetch the data and send it with the message.

This issue is to add a setting in the Messaging section. Above `Display Message Link Previews`, add a setting to enable or disable that fetch.

Feel free to find a name for it or ask designers for one.

There might already be a setting in status-go for that. You can ask @ilmotta for it.
If there is not, then you can just use a QT setting instead for simplicity

This issue is gonna be easier to implement once https://github.com/status-im/status-desktop/issues/10863 is done, but it can be implemented parallel or before, especially if the setting is already in status-go.
It's also possible that #10863 depends on that setting, but we can hardcode it when working on it, so it's not 100% necessary to have it.

### Acceptance Criteria

- There is a new switch setting in the Messaging section that enables and disables the fetching and sending of data from links
- When the setting is ON, the feature to fetch and send link data with messages is activated.
- When the setting is OFF, that feature is deactivated, meaning there is NO fetch (no call to status-go and the web when typing a link) and no additional data sent with the message; ie the link is sent bare and the receiver will NOT have an unfurl, at least after https://github.com/status-im/status-desktop/issues/10863 is implemented

**Comment by felicio** [comment]
> There might already be a setting in status-go for that. You can ask @felicio for it.

Nope, I got no such thing.

Also, and at first glance, I wouldn't say that URL unfurling to display an OG image/preview is same as decoding an encoded URL as per https://github.com/vacp2p/rfc/pull/602 and using its metadata/description or the public key to fetch the latest data.

**Comment by jrainville** [comment]
@felicio my bad, I mentioned the wrong person haha. Too many URL issues today got me confused :face_with_spiral_eyes:

**Comment by igor-sirotin** [comment]
backend task: https://github.com/status-im/status-go/issues/4130
