### ISSUE TITLE
`Community Settings` options look like highlighted although they are not the selected and current option

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10873]
# Bug Report

## Description

`Community Settings` options look like highlighted although they are not the selected and current option

## Steps to reproduce

1. Go to manage community
2. Start selecting options

#### Expected behavior
When a new option is selected, the previous one is not highlighted.

#### Actual behavior
When a new option is selected, the previous one keeps the look of highlighted.

### Additional Information

https://github.com/status-im/status-desktop/assets/97019400/0debf50c-27f9-40c0-ad01-d6bbb53cf0c1

- Status desktop version: master `367640af6c6baebe84d85607172a29f19284e9bc`
- Operating System: macos

**Comment by alexjba** [comment]
Can't reproduce it on latest master

**Comment by jrainville** [comment]
I can't reproduce either. I'll close. Reopen if you can reproduce.
