### ISSUE TITLE
Clear balance and nonce cache in status-go when transfers are loaded

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#10888]
### Description

Currently we never clear balance and nonce cache in status-go, after fetching blocks is done during transfers fetching. But in case of many transfers, that could significantly increase memory usage. For my case it was ~800Mb difference for an account that has ~3500 transfers (not sure if that whole amount is all cache related).

A simple approach would be to clear cache after we have found all ETH transfers and reached the beginning of account history (saved `start_blk` to `blocks_sequential_ranges` table).
A more complex solution would be to partially clear cache for blocks that are already loaded and there will be no more cache hit for them.

This cache is never used (AFAIK) after history transfers fetching is complete.

**Comment by anastasiyaig** [comment]
@IvanBelyakoff please link to a PR
