### ISSUE TITLE
Headline color in wallet view looks off (dark mode)

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10898]
This is what it looks like in light mode (which is fine)

![Screenshot from 2023-06-02 13-30-31](https://github.com/status-im/status-desktop/assets/445106/4866d6e2-a437-4d0d-8e45-1559b6fd57c3)

This is what it looks like in darkmode (which doesn't seem fine)
![Screenshot from 2023-06-02 13-30-24](https://github.com/status-im/status-desktop/assets/445106/9c6666ea-c447-4573-a3d1-ced8a6fa2415)

**Comment by caybro** [comment]
Should be fixed by https://github.com/status-im/status-desktop/pull/10764
