### ISSUE TITLE
Join community view looks off since ScrollView refactor

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10905]
This is what it currently looks like:

![Screenshot from 2023-06-02 15-07-24](https://github.com/status-im/status-desktop/assets/445106/c528cd4b-b3c1-4327-bcd8-e805c2eff01e)

Notice how the community token permissions are centered over the entire window.
This is not how it should be.

The token permissions were centered in the right "pane" of the view.

Talked to @noeliaSD about this.
She has suspicions that it's related to some ScrollView refactor (not sure what happened there).

**Comment by caybro** [comment]
Also some top margin missing above the bio in the Profile popup:
![image](https://github.com/status-im/status-desktop/assets/5377645/ba5471d6-149b-4998-b6db-2d57c8fe0992)
