### ISSUE TITLE
Community section boxes are "glued" to the bottom of the window

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10901]
The three boxes for "Invite people", "airdrop tokens", "backup" seem to miss a padding, so they end up at the very bottom of the app window:

![Screenshot from 2023-06-02 14-09-15](https://github.com/status-im/status-desktop/assets/445106/08c86260-c203-496b-9acd-18c6b0a9c963)

I thought it was related to my window being very small, but even increasing its size doesn't fix it. Plus, **decreasing** the size makes them stick to the bottom as well.

**Comment by caybro** [comment]
Plus the right edge get cut off if you decrease the window size

**Comment by caybro** [comment]
Fixed in master:

![image](https://github.com/status-im/status-desktop/assets/5377645/25549555-c897-47e0-b697-90cbc41d38eb)
