### ISSUE TITLE
"Enter your password" modal seems broken

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10906]
Here's what it looks like:

![Screenshot from 2023-06-02 15-31-45](https://github.com/status-im/status-desktop/assets/445106/030ae095-1f07-472a-96fc-961da74bf49d)

Steps to reproduce:

1. Enter community view of a community that has token permissions
2. Hit "Reveal addresses" button
3. Modal opens and looks like this

**Comment by caybro** [comment]
I'd say the ScrollView again? CC @igor-sirotin
