### ISSUE TITLE
Update StatusBaseButton content item layout

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#10903]
### Description

StatusBaseButton is using `RowLayout` to handle content items.
This create specific problem when button needs to be stretched.

![image](https://github.com/status-im/status-desktop/assets/11396062/be49cfb3-7a24-4434-8087-638a9e4a65f7)

Icon and text cannot be aligned together and cantered in the button.

**Comment by caybro** [comment]
There are some props like:
```qml
    property int textAlignment: Qt.AlignVCenter | Qt.AlignHCenter
    property bool textFillWidth: false
```
that you can experiment with but in general I agree, this needs some second thought/cleanup

**Comment by caybro** [comment]
Need to clean this up; will also create the corresponding storybook page to be able to play with all the params/variations of the component
