### ISSUE TITLE
Wallet -> Add account: Edit account modal positioning is wrong

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10913]
### Description

1. open wallet 
2. generate account
3. edit account

```
Warning: qrc:/StatusQ/Popups/Dialog/StatusDialog.qml:119: Error: Invalid attempt to destroy() an indestructible object (qrc:/StatusQ/Popups/Dialog/StatusDialog.qml:119, )
```

![image](https://github.com/status-im/status-desktop/assets/82375995/edd23bec-4947-4b0f-b8cf-0f22975ef2bc)

**Version:** latest develop . Introduced in https://github.com/status-im/status-desktop/pull/10668

**Comment by caybro** [comment]
CC @alexandraB99

**Comment by caybro** [comment]
Also remove account is broken:
![image](https://github.com/status-im/status-desktop/assets/5377645/8a093496-3f26-4b6b-9bbd-70ae6ea6d5dc)
