### ISSUE TITLE
Wallet: Authentication popup is broken

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10915]
### Description

<img width="1512" alt="Screenshot 2023-06-05 at 11 24 38" src="https://github.com/status-im/status-desktop/assets/82375995/c2774b3a-cbde-4beb-9a6b-680836816b8a">

Commit: `dc9193424fba4932c46f3580f1541c3c81ffffad` master build

**Comment by caybro** [comment]
CC @igor-sirotin
