### ISSUE TITLE
memory usage grows when switching chats

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#1092]
On mac just switching between chats you can see how memory usage grows and isn't  cleared

![image](https://user-images.githubusercontent.com/11790366/94887725-5b0b0400-0477-11eb-9f85-7c6246412369.png)

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/94929536-83215400-04c5-11eb-987a-8fffa9dcb73b.png)

**Comment by iurimatias** [comment]
so not to say it's perfect but since this we have done a lot of of fixes and improvements that essentially solve this, sometimes the memory usage will go up but will come down once the gc kicks in
