### ISSUE TITLE
Asset charts should never show a date earlier than the asset genesis date

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#10927]
When the `ALL` time period is selected, all asset charts start from the same month and year: `JUL 2010`. However, the first month and year shown when `ALL` is selected should relate to the genesis date of the asset. This avoids there being a large period of time where the asset prices is 0.00 prior to its genesis date as can be seen on Dai's chart below.

<img width="937" alt="Screenshot 2023-06-05 at 14 30 34" src="https://github.com/status-im/status-desktop/assets/110033914/4bbd6b28-6f6b-4f6a-852a-7f0e7a88e598">
cc @John-44

**Comment by alaibe** [comment]
Will be work part as new chart feature
