### ISSUE TITLE
Keycard -> Factory reset: factory reset button does not launch the factory reset flow from onboarding

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10925]
### Description

1. open status
2. click Add new user
3. click Generate keys for a new Keycard
4. click Factory reset

https://github.com/status-im/status-desktop/assets/82375995/c1f1a90e-a884-4037-9dea-2e3ec836219f

**Comment by caybro** [comment]
Is this supposed to open a new modal?

**Comment by anastasiyaig** [comment]
i assume yes, it is either modal or pop up

**Comment by anastasiyaig** [comment]
i cant reproduce it in master commit 63eacf0817381bd6b8214f84d32d47bb805de9ac (sep-11-2023)
