### ISSUE TITLE
Block Admins from Kicking or Banning other Admins

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10936]
### Description

Needs https://github.com/status-im/status-desktop/issues/10114

Right now, an admin can kick/ban everyone, except the owner (duh).

However, we do not want to enable admins to kick each other, so we need to block that behaviour.

### Acceptance Criteria

- There is no button in the UI for the Admin to kick another admin (possible to just disable it and put a tooltip saying you can't kick or ban another admin)
  - also double check that there is no button to kick the owner
- More important even: block in status-go the sending and the reception of admin on admin violence.

**Comment by mprakhov** [comment]
1. status-go:
- for ban and kick API check that the admin can't ban another admin
- in `PatchCommunityDescriptionByAdminEvent` verify that the admin is not trying to kick/ban another admin
- do a fix on status-desktop side to disable kick/ban admins by another admin

**Comment by 0x-r4bbit** [comment]
status-go PR for this: https://github.com/status-im/status-go/pull/3666
