### ISSUE TITLE
Onboarding -> Recover from seed: Fetching data screen is not scrollable

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10939]
### Description

1. open status
2. click I dont have other device and import a seed phrase
3. when being on the Fetching data screen, resize it a bit (or open on small laptop like mine, 13 inch)
4. try to scroll to the Continue button

**Actual result:** 

1. continue button is overlapped with fetching data details
2. scrolling to the button is not possbile
3. the screen is not autoresizing components to adjust different screen sizes

<img width="1552" alt="Screenshot 2023-06-06 at 10 17 12" src="https://github.com/status-im/status-desktop/assets/82375995/5af40621-6350-42b3-a8d2-da7305e4d5fe">

**Comment by caybro** [comment]
ScrollView bug most probably, CC @igor-sirotin

**Comment by igor-sirotin** [comment]
Will check 👌🏻

**Comment by stefandunca** [comment]
I'm using this issue to report another minor glitch I encounter. 
The countdown is elided right for some values:
![image](https://github.com/status-im/status-desktop/assets/47554641/db0ae782-35fc-4b96-a3c4-7892fcbc0a0d)

**Comment by caybro** [comment]
The text is also definitely too dark :)

**Comment by caybro** [comment]
Related: https://github.com/status-im/status-desktop/issues/10947

**Comment by caybro** [comment]
Related: https://github.com/status-im/status-desktop/issues/11163

**Comment by iurimatias** [comment]
this should be fixed already, we need to verify and then close this

**Comment by anastasiyaig** [comment]
@iurimatias i was able to reproduce it the way it is described. So if u resize the app window - there is no chance u can reach the Continue button, which looks now normal btw

We might still want to look into this, but it is not a super priority

<img width="1363" alt="Screenshot 2023-09-19 at 12 28 10" src="https://github.com/status-im/status-desktop/assets/82375995/723f6b0a-0791-446b-8bac-29888d33368f">


https://github.com/status-im/status-desktop/assets/82375995/fb304cb6-6a23-4108-a7bc-8280705c1cda
