### ISSUE TITLE
Wallet: Received gEth showing as Sent in activity

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10945]
# Bug Report

## Description

Transaction sending 0.00001 gEth to wallet is shown as an outgoing (Send) transaction in recipients activity.

## Steps to reproduce

Account A sends 0.0001 gEth to new Status account (B)
https://goerli.etherscan.io/tx/0x43d7db667acfcddcb1ecd48120a279149ce15a6660408667233b054817d2c58b

Account B returns 0.00001 gEth to account A
https://goerli.etherscan.io/tx/0x4625464e813ccce56eefe7c7375af382c92f931ecd1991e6d87f5dc6504f9d51

In account A (running 0.12.0) both transactions are outgoing.
![image](https://github.com/status-im/status-desktop/assets/50769329/30550fdb-a209-41e3-81be-ef7a78e048d6)

### Additional Information

- Status desktop version: 0.12.0
- Operating System: Mac

**Comment by Cuteivist** [comment]
@glitchminer It is fixed on current master 

![image](https://github.com/status-im/status-desktop/assets/11396062/be31c531-bd4f-4797-8376-446c9ccf2053)

**Comment by glitchminer** [comment]
Thanks @Cuteivist , retested on master and could not reproduce. Closing.
