### ISSUE TITLE
Chat: Quoted message in a reply is not clickable

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10950]
# Bug Report

## Description

The quoted message in a reply should be clickable and take the user to the original message. This is not currently possible - only the username/header is clickable.

![image](https://github.com/status-im/status-desktop/assets/50769329/ca6d4d51-8771-4758-a310-426141fe57be)

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by caybro** [comment]
It is still clickable but only in the empty space right of the username

**Comment by caybro** [comment]
Raising prio as this is a regression against an already released version
