### ISSUE TITLE
Album of images disappears from reply after reloading the app

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#10986]
# Bug Report

## Description

Album of images disappeared form reply after reloading the app

## Steps to reproduce

1. Send several images as an album with text
2. Reply on the message with album - images displayed in reply message
3. Reload the app - images not displayed anymore

#### Expected behavior

Album of images and text must be displayed in reply till original message exists 

#### Actual behavior

Album of images disappeared from reply, user can see just text message

### Additional Information

- Status desktop version: `latest master`
- Operating System: `all`

![Снимок экрана 2023-06-08 в 13 02 48](https://github.com/status-im/status-desktop/assets/82511785/8d259235-0dd0-4c75-95a8-da8a0206b795)

**Comment by kounkou** [comment]
Hi,
I could reproduce the issue easily by following the same actions stated in the Description.
Looking into why this issue happens

**Comment by kounkou** [comment]
Currently, I fixed the display of the images 
Next step is to fix the images that are actually display to be the correct ones.
I have also noticed that the problem is only related to the first quoted message, the rest of the messages do not have the specified problem.

Attaching screenshots for visibility

![Image](https://github.com/status-im/status-desktop/assets/2589171/3ba75323-aef8-43c2-b650-2a14af0dabb0)

**Comment by kounkou** [comment]
Based on my analysis of possible solutions, there could be 2 ways of solving this issue 

1- [preferred] Add new properties in nim and do a binding with Qml
Here I will need 2 properties : images of an album, and the actual number of images in the album. Please note that these images I need are quoted images, similar to already existing quotedMessage Text.

2- [slow] Call a function to retrieve the images for a specific message id
This option is slow and probably asynchronous

I am currently working on implementing solution 1-

**Comment by jrainville** [comment]
I wonder now if it's not a problem in status-go. We do see the images when we first receive the reply, that means that the model supports showing them correctly and also that we get all the wanted data from the backend when we receive it through the signal (event from status-go).

However, on app reload, we do not use the signal, we use a function to get messages in pages (like 20 messages), and probably that function doesn't return the album of messages as part of the message.

One way to check what you receive from status-go would be to `echo jsonSignal` in `signals_manager.nim`. That will show you all the signals received from status-go.
You can then identify what you get when you receive a reply with an album.

Then, you can compare with what we get on app start by doing `echo msgsResponse` in `asyncFetchChatMessagesTask`in `message/async_tasks.nim`.

If you see that the returned message in the latter is missing info compared to the one in the former, that means we are missing something in sttaus-go.

In that case, @borismelnik can help you identify how he passed the album to the message reply.

**Comment by kounkou** [comment]
Thank you @jrainville, this is gold!
I captured some logs. I will analyze them more in a few. I can see that the image are indeed returned in status, so this might explain why whatever I did in nim, I still saw unexpected results 😅
I had a conversation with @borismelnik  on the nim part. The status go seem to be the right place to check now. I'll shift to status go

**Comment by kounkou** [comment]
I have added some `echo` lines as recommended above, here are the observations : 

### Before the reboot
I added some logs lines to to print the signal received. It's just a signal here, I seems logical to me that I don't see the actual payload. So here I am missing finding the actual place where the payload is sent from `nim` to `status-go`
I am also not able to observe any communication on the way `status-go` to `nim`, by observing on the status-go side.


### After reboot
After reboot, I have much more info that I can analyze after pretifying the json.  What I can see is : The quoted message which I am interested with comes with a matching text and image from the `asyncFetchChatMessagesTaskin` perspective.
For my particular test however, while I was expecting 2 images, only actually 1 image repeated in messages. While the albumImage count is correct.

So based on above observations, there is something not working correctly when loading the messages from status-go. So as action : 

- I need to confirm what is actually sent before reboot (I need better way to observe the message sent from nim to status-go)
- Once I know above, I can either have to fix status-go or making sure the code retrieve the info and displays them correctly.


```
[
  {
    "id": "0x5a02b81d98a2abc6879f02a6e82a6416ff083f76347da7d589905727d87dd6cc",
    "whisperTimestamp": 1700209257936,
    "from": "0x049563f3dae3c4dc1f1ff72463ab2f7ffa5011bf0f938c0dd87db8955d61ad70ff49393ad1c1dc53890df4e091af1b3d64724017ad9b0fdce6236f8965c4489278",
    "alias": "",
    "identicon": "",
    "seen": true,
    "outgoingStatus": "delivered",
    "quotedMessage": {
      "id": "0xd9c8ae3adf49fe4f5c8fe18327f015652ad204c17fd377a5828b0b3f168ba258",
      "contentType": 7,
      "from": "0x049563f3dae3c4dc1f1ff72463ab2f7ffa5011bf0f938c0dd87db8955d61ad70ff49393ad1c1dc53890df4e091af1b3d64724017ad9b0fdce6236f8965c4489278",
      "text": "Sender message 1",
      "parsedText": [
        {
          "type": "paragraph",
          "children": [
            {
              "literal": "Sender message 1"
            }
          ]
        }
      ],
      "albumImagesCount": 2,
      "image": "https://Localhost:39325/messages/images?messageId=0xd9c8ae3adf49fe4f5c8fe18327f015652ad204c17fd377a5828b0b3f168ba258"
    },
    "rtl": false,
    "parsedText": [
      {
        "type": "paragraph",
        "children": [
          {
            "literal": "Receiver message 1"
          }
        ]
      }
    ],
    "lineCount": 0,
    "text": "Receiver message 1",
    "chatId": "0x04c429330e366166687319c372775b39a917352e1af7f1510bf0a7a7805f7a2597030753529f3ff5e55b5a27c1d0be154312fa924532ac2ad005ed403223a43e9b",
    "localChatId": "0x04c429330e366166687319c372775b39a917352e1af7f1510bf0a7a7805f7a2597030753529f3ff5e55b5a27c1d0be154312fa924532ac2ad005ed403223a43e9b",
    "clock": 1700209257936,
    "replace": "",
    "responseTo": "0xd9c8ae3adf49fe4f5c8fe18327f015652ad204c17fd377a5828b0b3f168ba258",
    "ensName": "",
    "displayName": "",
    "image": "https://Localhost:39325/messages/images?messageId=0x5a02b81d98a2abc6879f02a6e82a6416ff083f76347da7d589905727d87dd6cc",
    "albumId": "371a1c7d-26a4-4caa-8abc-d70ee3dba7b4",
    "albumImagesCount": 3,
    "gapParameters": {},
    "timestamp": 1700209257936,
    "contentType": 7,
    "messageType": 1,
    "compressedKey": "zQ3shXTwuHEukauQdkJhELxj9Bk575cRrAqzjuZfJzbabVfGa",
    "emojiHash": [
      "👨🏿‍🎨",
      "😩",
      "🐱",
      "👊🏿",
      "👩🏾‍🚒",
      "🚣‍♂️",
      "👩🏼‍🦰",
      "🌰",
      "🔔",
      "🅿️",
      "🙆🏼‍♂️",
      "🤽🏿",
      "🤹🏾",
      "📽️"
    ]
  }
  ...
  ]
  
````

**Comment by jrainville** [comment]
> For my particular test however, while I was expecting 2 images, only actually 1 image repeated in messages. While the albumImage count is correct.

I think the image there is actually the user's image, to easily display the user info from the message.

The actual images would come in an album property.

> I am also not able to observe any communication on the way status-go to nim, by observing on the status-go side.

It would look something like `{"type": "message-new", ...}`  with a big payload. 

Now that I rethink about it, the album feature can be a little complex, because the images can come in multiple different messages from waku. So sometimes the album has 3 images, but you might receive only 2 at first. Then we show a loading until we receive the final image.

So I think the issue here is that when we generate/populate the `quotedMessage` in status-go, we probably don't have the same code to recreate the album?

**Comment by kounkou** [comment]
Hey, thanks for following along 🙌🏾,

> I think the image there is actually the user's image, to easily display the user info from the message.

For the image I have checked it myself. It's served by the localhost when Status in running. So I opened it on a browser (magic!), and it's one of the original message to which I replied.

> The actual images would come in an album property.

what you mentioned below matched my observation. A message can be split into multiple message, I thought there is no such thing as album in quotedMessage structure. Those images can be grouped in album later on. 

> It would look something like `{"type": "message-new", ...}`  with a big payload.

Right... There must something else that I am missing here cause I saw similar messages type message-new but no payload. I'll post the code here in a few.

> Now that I rethink about it, the album feature can be a little complex, because the images can come in multiple different messages from waku. So sometimes the album has 3 images, but you might receive only 2 at first. Then we show a loading until we receive the final image.

Indeed thanks for sharing 👍🏾

> So I think the issue here is that when we generate/populate the `quotedMessage` in status-go, we probably don't have the same code to recreate the album?

Right, I'll check the nim module again today

**Comment by kounkou** [comment]
Hi,

The reason why the before reload everything works perfectly is because inside MessageView.qml

https://github.com/status-im/status-desktop/blob/78303105915e17c4e8ff4d176f8b46e3b8381dae/ui/imports/shared/views/chat/MessageView.qml#L669

On `onResponseMessageChanged` signal, we call the `messageStore.getMessageByIdAsJson(responseToMessageWithId)` to obtain the images of the quotedMessage. 

But the model is not made aware of this change at any time. Therefore, when reloading the application, the message doesn't contain the necessary quoted Images to be displayed.
However, the quotedMessage text already exists in the model.

I am currently exploring a solution where I gather the images from the message module in nim.

Currently, I am able to retrieve one image per quotedMessage. Once all the images retrieved, I will expose a quotedMessageAlbumCount and quotedMessageAlbumImages to be used in the MessageView component for any replies.
