### ISSUE TITLE
UI updated for recovering from Waku onboarding flow

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#10984]
We need to slightly update UI for recovering from Waku onboarding flow to meet the new Figma design:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=31281-626206&t=IIt7pohtmgc4Y7G6-4

**Comment by saledjenic** [comment]
Under this issue we should handle this case:

![a1](https://github.com/status-im/status-desktop/assets/86303051/95d402bb-d3d8-4936-86dd-b5be5f8cbfb8)

![a2](https://github.com/status-im/status-desktop/assets/86303051/af0c10e0-7bf3-45b9-af9e-4d253453b7e5)

If the app height is set to its minimum height, some progress bars as well as the "Continue" button are invisible. I guess we can do the list of progress bars scrollable, @benjthayer?

**Comment by caybro** [comment]
> Under this issue we should handle this case:
> 
> ![a1](https://user-images.githubusercontent.com/86303051/249130034-95d402bb-d3d8-4936-86dd-b5be5f8cbfb8.png)
> 
> ![a2](https://user-images.githubusercontent.com/86303051/249130043-af0c10e0-7bf3-45b9-af9e-4d253453b7e5.png)
> 
> If the app height is set to its minimum height, some progress bars as well as the "Continue" button are invisible. I guess we can do the list of progress bars scrollable, @benjthayer?

I guess this is already handled by @alexjba in some other PR/issue?

**Comment by benjthayer** [comment]
I think it would be best to modify the design to accommodate the min 680px height scenario as opposed to scrolling the progress bars (sometimes the cutoff of content is in a place where there is no affordance for scrolling - i.e. no content is cut through - so the user might not see that some data has not been fetched if below the scroll point).

We have 2 options for accommodating the 680px size:
1) We rejig the design so it is slightly more condensed - we use this more condensed design irrespective of app window height (it works for all window heights)
2) We responsively scale the data fetch animation - as the user reduces the window height, we scale down the animation size.

It might come down to which is more straightforward from an implementation perspective?

**Comment by saledjenic** [comment]
@benjthayer I agree about this "We responsively scale the data fetch animation", also not sure why do we need that much empty space above the animation.

Another point here is that we are fetching a lot of things, more than it's on that screenshot, but maybe we can group some items and have 4 groups to display to a user, for example everything what we're fetching may be grouped in these 4 groups:
- profile (profile details and contacts belong here, cause contacts are related to the profile)
- wallet (keypairs and watch only accounts belong here)
- community (all communities related details)
- settings (all app settings)

**Comment by benjthayer** [comment]
@saledjenic that's a good point - reducing the number of categories will help with space for sure. The only thing we risk doing by grouping the data to more abstract categories is reducing the granularity of feedback to the user when types of data fail to fetch. The more detailed we can be on what couldn't be fetched, the more informed the user is on whether they wish to proceed without the missing data. 

For the Wallet category for example, I'd be ok with losing my watch-only accounts but not my keypairs. So we would need some form of descriptive feedback anyway stipulating what has failed to be fetched within the broader category which in itself would take up room.
