### ISSUE TITLE
Fees dialog shows only first time

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#10989]
Fee dialog is shown only once. When I click the button one more time nothing happens.
It can be reproduced during self-destruct and burning.

![image](https://github.com/status-im/status-desktop/assets/61889657/5e83549e-c304-4028-967a-bc982200e45b)

**Comment by caybro** [comment]
Will be fixed with my PR here: https://github.com/status-im/status-desktop/pull/10958
