### ISSUE TITLE
Implement channel permission lock screen as per design

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10996]
### Description

Part of Epic https://github.com/status-im/status-desktop/issues/10598

When a channel has a permission that is not fulfilled, we need to show the locked screen as per design below:

Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=2578-354261&t=czRGLCFONxOmFeu8-0

There should be a component already for that. Feel free to ask Noelia

We list the permissions needed for both types "View and post" and "View only".

Of course, if any of the permission is met, we do not show the locked screen, we show the channel in the right mode.

Ignore hidden permissions for now.

### Acceptance Criteria

- When a channel has permissions and none of them are met, we show the locked screen as per design
- If one of the permission is met, we show the channel is the right mode

**Comment by 0x-r4bbit** [comment]
Desktop PR: https://github.com/status-im/status-desktop/pull/11134
