### ISSUE TITLE
Implement "View only" permission for channels

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10995]
### Description

Part of Epic #10598

Depends on https://github.com/status-im/status-desktop/issues/10993

Implement the "View only" permission for channels. Make it possible to create, edit and delete those permissions.
Only owners can create this permission.

Figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22721-500627&t=czRGLCFONxOmFeu8-0

There should be a placeholder "view only" state for the Input implemented by Alexandra. Ask her for the details

When there is no permission on a channel, everyone and read and write to it, but once **one** "View only" permission is added to a channel, only those that fulfill that permission can read from that channel. The channel still appears in the list, but it will be locked for those not fulfilling the permission.

Do note the "switch" in the top right of the "Who holds" section. Unchecking that means that there is not token requirement, so "anyone" (everyone) fulfills the requirement. So making a channel permission when "anyone is allowed to View only in #channel" means that #channel becomes read-only for everyone, except admins and owners. That is essentially how announcements channels would be done.

An example of a  channel that has a "View only" permission with tokens, would be a vip-announcement channel, where only a subset of members can see that channel and admins and owners are still the only one being able to write.

It's also possible to mix "View and post" and "View only", meaning that only a subset would be able to write, then another subset would be able to read, of both use a token requirement, then some members will not be able to view the content of that channel. 

**Small details**:

- **no** encryption for now. Just client handling
- ignore the hidden permission setting for now
- use a placeholder screen for the locked state (blurred screen). So we still show the channel, but it can be just a white Rectangle with placeholder text for now
- reminder than admins and owners can ALWAYS read and write to all channels

### Acceptance Criteria

- Owners can create, edit and delete channel permissions for "View only" in the Permissions screen of the community management area
- Unchecking the "who holds" switch makes the permission apply to everyone, making a channel read-only to everyone (except admins and owners) 
- Other users receive that permission and 
  - if they do **not** meet the requirement, a placeholder screen is shown when clicking the channel saying that they do not have access
  - if they do meet the requirements, they can see the channel's content, but still can't write
- Admins and owners can still see and post as normal as well, even if they do not meet the requirements

**Comment by 0x-r4bbit** [comment]
Desktop PR: https://github.com/status-im/status-desktop/pull/11134
