### ISSUE TITLE
Implement hidden permission (for community and channels)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10997]
### Description

Part of Epic https://github.com/status-im/status-desktop/issues/10598

Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22734-502803&t=czRGLCFONxOmFeu8-0

In the design, there is a "Hide permission" switch. When it is switched on, that means that if the person does **not** meet the requirement, they do **not** see the missing requirement.

For example, in this screen: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=2367-280302&t=xZGiwDNEtqkJZ3fR-0

if both requirements are hidden, if the user only fulfills the 15 UNI permission, then only that one will be shown and not the other one. The user would still be able to Request to join.

If the user does **not** meet any of the requirements, then they would **only** see  "Membership requirements not met" and be denied entry to the community.

Same principle for channel permissions, except that channels never have a button. If the permission is fulfilled, we show the channel directly in the right mode.
Reminder that admins and owners can always read and post in all channels, even if they do not fulfill the requirement.

### Acceptance Criteria

- If a permission is marked as hidden by the owner, when a user does not fulfill the requirement, the permission is not shown to them
- If they meet it, they will see it + the button will be enabled
- Same thing for channels, but there is no button

**Comment by 0x-r4bbit** [comment]
This will land in https://github.com/status-im/status-desktop/pull/11134

**Comment by 0x-r4bbit** [comment]
This has landed with #11134
