### ISSUE TITLE
Implement "View and post" permission for channels

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10993]
### Description

Part of Epic #10598

Implement the "View and post" permission for channels. Make it possible to create, edit and delete those permissions.
Only owners can create this permission.

Figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22721-500591&t=czRGLCFONxOmFeu8-0

**Small details**:

- **no** encryption for now. Just client handling
- ignore the hidden permission setting for now
- use a placeholder screen for the locked state (blurred screen). So we still show the channel, but it can be just a white Rectangle with placeholder text for now
- reminder than admins and owners can ALWAYS read and write to all channels

### Acceptance Criteria

- Owners can create, edit and delete channel permissions for "View and post" in the Permissions screen of the community management area
- Other users receive that permission and 
  - if they do **not** meet the requirement, a placeholder screen is shown when clicking the channel saying that they do not have access
  - if they do meet the requirements, they can see the and write in the channel as normal
- Admins and owners can still see and post as normal as well, even if they do not meet the requirements

**Comment by 0x-r4bbit** [comment]
Backend implementation landing here: https://github.com/status-im/status-go/pull/3605/files

**Comment by 0x-r4bbit** [comment]
Desktop PR: https://github.com/status-im/status-desktop/pull/11134

**Comment by 0x-r4bbit** [comment]
This has landed via #11134
