### ISSUE TITLE
Settings -> About: clicking Check for updates always results in green confirmation bar Your version is up to date

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#10990]
## Description

**Steps:**

1. install 0.11.1
2. create account
3. open settings
4. click about
5. click check for updates

As results, the app says there is no update, but we do have 0.12 released.

Version: 0.11

When using Status Desktop 0.11 _after_ Status Desktop 0.12 has been released, the green loading bar tells users that their "version of Status desktop is up to date" when in fact it isn't and there is a new release available. 

<img width="1684" alt="Green loading bar" src="https://github.com/status-im/status-desktop/assets/124154641/7a8d4f2b-94c5-4996-9f8f-838f50b4b6d9">

**Comment by John-44** [comment]
@anastasiyaig as this is a bug with 0.11, not sure it's it's already been fixed in 0.12 ?

**Comment by anastasiyaig** [comment]
@John-44 so when using 0.11.0 the app says that there is no new version available , right? I will double check that, i think this functionality is kinda off right now

**Comment by anastasiyaig** [comment]
Okay, i updated the ticket a bit. Also, i guess we need some design here (in case we have newer version - what to show and how we want the user to proceed)

There is no any mechanism for automatic update I believe.

cc @jrainville @iurimatias

**Comment by jrainville** [comment]
The current way of checking version is very annoying. I think it uses a contract and IPFS, which makes it hard to update. 

That's why we forget/don't want to update the version each time.

I think Iuri is planning to redo the feature in a later milestone

**Comment by anastasiyaig** [comment]
@jrainville @John-44 maybe we can hide the button then? In about section :) and dont show this banner

**Comment by John-44** [comment]
@jrainville @anastasiyaig @iurimatias how about we hide this feature in 0.13, and then bring it back when we do the work to properly implement opt-in auto updates (in the 0.16 or 0.17 release cycle probably)?
