### ISSUE TITLE
[Deep Links] Fetch and show community in spectate mode when activating a link to an unknown community

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11002]
### Description

If you activate a link for a community that you do not know, we should start fetching its info, similarly to when a link is posted in the chat.

It also needs an Ephemeral notification that says that we are loading the data. You can reuse the one we have for the links.

Once the data is loaded, we should open the community in Spectate mode.

There should be an error ephemeral notification if we can't find the data.

Finally, if we do know the community, but we are not spectating, it should just open it in spectate mode.

### Acceptance Criteria

- Activating a community deep link should:
  - show the community if we already have it in the left bar
  - add it and show it in spectate mode if we have it in our DB but no longer spectating
  - fetch its data and then add it and show it in spectate mode when the data is fetched
    - show a loading ephemeral notification at the start of the fetch
    - show an error ephemeral notification if the data fetch fails or doesn't return anything
    - if the fetch succeeds, add the community to the left bar and open it in spectate mode

**Comment by jrainville** [comment]
> I think we should add requested community to the panel (as spectated or joined) till we fetching the data

We can, but I don't think we have a design for that. Maybe we can just add a community on the left bar with a loading indicator. It wouldn't be clickable until the data is loaded. What do you think? (we need to keep it simple for now)

**Comment by borismelnik** [comment]
@jrainville John put it to designers backlog so we can close it as done (cos it works in master) and open new issue about to display requested communities or move back till design will be done.
