### ISSUE TITLE
[chat] @mentions no longer working

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#11005]
# Bug Report

Somewhen during last week in master, @mentions stopped working:

![image](https://github.com/status-im/status-desktop/assets/5377645/1fbab795-f5e9-4a77-b6b4-f3021a149125)

There have been a couple of potential culprits:
- https://github.com/status-im/status-desktop/pull/10928
- https://github.com/status-im/status-desktop/pull/10668

Or maybe something completely different

The only thing that actually gets suggested is `@everyone`

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by jrainville** [comment]
My guess is that since the refactor done in https://github.com/status-im/status-desktop/pull/10928, we do not pass the usersModel correctly.
