### ISSUE TITLE
Wallet -> Send: cant bypass Authenticate flow, clicking this button hangs the app (on Mac M1)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11010]
### Description

<img width="1512" alt="Screenshot 2023-06-09 at 11 56 41" src="https://github.com/status-im/status-desktop/assets/82375995/813cbb2c-8492-4b90-9807-3eb657cea204">

**Comment by alexjba** [comment]
Logs before crashing:
```
BG 2023-06-09 13:22:44.304+03:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=10341865 file=threadpool.nim:54 messageType=FetchDerivedAddressesTaskArg:ObjectType threadid=10341865 task="{\"$type\":\"FetchDerivedAddressesTaskArg:ObjectType\",\"password\":\"0xc21f6381f45922704ecb6614b23d65be7b63d205355218dc71cabdc3a3001ce3\",\"derivedFrom\":\"\",\"paths\":[\"m/44\'/60\'/0\'/0/2\"],\"vptr\":105553143374368,\"slot\":\"onDerivedAddressesFetched\",\"tptr\":4306675612}"
DBG 2023-06-09 13:22:44.305+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10341865 file=core.nim:27 rpc_method=wallet_getDerivedAddresses
ERR 2023-06-09 13:22:44.305+03:00 rpc response error                         topics="rpc" tid=10341865 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getDerivedAddresses, code:-32000, message:cannot retrieve a valid account for a given address ]\n"
ERR 2023-06-09 13:22:44.305+03:00 error doing rpc request                    topics="rpc" tid=10341865 file=core.nim:40 methodName=wallet_getDerivedAddresses exception="\nstatus-go error [methodName:wallet_getDerivedAddresses, code:-32000, message:cannot retrieve a valid account for a given address ]\n"
INF 2023-06-09 13:22:44.305+03:00 shutting down...                           topics="status-app" tid=10341846 file=nim_status_client.nim:161
INF 2023-06-09 13:22:44.306+03:00 logging out...                             topics="app-controller" tid=10341846 file=app_controller.nim:284
```

**Comment by anastasiyaig** [comment]
@Cuteivist u were able to Authenticate on Windows right?

**Comment by Cuteivist** [comment]
@anastasiyaig  On Windows it shows error popup.

![image](https://github.com/status-im/status-desktop/assets/11396062/6a8474c0-cfc0-4a43-9707-de6dc54bdad7)


On Mac it freezes in a moment where it should show such message. Last log indicate call to same method as in error popup.
So in my opinion both platforms have same issue it just on Mac it freezes app and on WIndows it popups error message and I can continue using app.

**Comment by alaibe** [comment]
ToAmount is null I believe in multi tx

**Comment by alaibe** [comment]
Pretty sure this PR is the reason why it fails: https://github.com/status-im/status-go/pull/3522

**Comment by anastasiyaig** [comment]
@dlipicar @alaibe i can reproduce it in master commit 125593369fe08321818336440675e53ea65eabdc as well as @IvanBelyakoff

**Comment by alexjba** [comment]
@anastasiyaig Can you reproduce this on `Add new wallet account` flow, on https://github.com/status-im/status-desktop/tree/release/0.13.x?

**Comment by anastasiyaig** [comment]
@alexjba seems to be okay in release 0.13
