### ISSUE TITLE
Chat input suggestion popup in ad-hoc group chats doesn't suggest "@everyone"

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#11029]
Something I've noticed in the latest 0.12.0 release.
`@everyone` is no longer suggested.

![Screenshot from 2023-06-12 13-10-08](https://github.com/status-im/status-desktop/assets/445106/0fc270e9-4007-472a-8fde-077c13849780)

There's this issue: https://github.com/status-im/status-desktop/issues/11005 which touches on similar things, however it reports the exact opposite behaviour:

> The only thing that actually gets suggested is @everyone

@caybro feel free to close this if you're certain this was fixed as part of #11005 but judging by its description it does not.

**Comment by jrainville** [comment]
In communities, `@everyone` works in 0.12. You were trying in a group.

By design we didn't support it (or at least as per the code), but IMO, it makes sense to also support `@everyone` in a group. 

What do you think @John-44

**Comment by John-44** [comment]
I've edited the issue title to reflect that this is only about ad-hoc group chats, @caybro @jrainville could you re-open this issue?
