### ISSUE TITLE
StatusQ: Dynamic width calculation for StatusMenu

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11028]
# Bug Report

## Description

Currently the width of StatusMenu is fixed what is problematic when content is dynamic and also for translations:

![Screenshot from 2023-06-12 12-38-03](https://github.com/status-im/status-desktop/assets/20650004/a5126c9f-b5a2-4cb3-ade9-6cd3bb7abaec)

While having it fixed, `SortableTokenHoldersPanel.qml` can be adjusted according to the design: 
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29473-626171&t=Rw4edL9LegNa9ez6-0
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29456-601850&t=Rw4edL9LegNa9ez6-0

## Steps to reproduce
Use `StatusMenu` with long item text.

#### Expected behavior
`StatusMenu` width should adapt to the width of items

#### Actual behavior
`StatusMenu` width is fixed, leading to elision for longer texts.

**Comment by micieslak** [comment]
This blog post may be useful for this task: https://martin.rpdev.net/2018/03/13/qt-quick-controls-2-automatically-set-the-width-of-menus.html

**Comment by alexjba** [comment]
> This blog post may be useful for this task: https://martin.rpdev.net/2018/03/13/qt-quick-controls-2-automatically-set-the-width-of-menus.html

Works like a charm! Thanks!
