### ISSUE TITLE
Token minting: Integrate token holder's list menu actions

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11033]
# Bug Report

## Description

Community settings -> Tokens -> Hodlers list. Integrate actions visible when hodler is a contact (View Profile, View Messages, Kick and Ban).

![Screenshot from 2023-06-12 13-45-13](https://github.com/status-im/status-desktop/assets/20650004/553ac16e-4e75-45f5-8c47-0fa0757c1228)

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29673-619998&t=Rw4edL9LegNa9ez6-0

**Comment by alexjba** [comment]
Needs backend support for token holders.

**Comment by noeliaSD** [comment]
Somehow related: https://github.com/status-im/status-desktop/issues/11471

There are some options covered in task #11471. Other options like `profile dialog` or `airdrop` should be done here. `Messages view` needs to be checked since maybe it's for post MVP

**Comment by noeliaSD** [comment]
Blocked by https://github.com/status-im/status-desktop/issues/11143

**Comment by micieslak** [comment]
> Somehow related: #11471
> 
> There are some options covered in task #11471. Other options like `profile dialog` or `airdrop` should be done here. `Messages view` needs to be checked since maybe it's for post MVP

#11471 is outdated now. It's related to 

https://github.com/status-im/status-desktop/issues/11622
https://github.com/status-im/status-desktop/issues/11625

but only for TokenMaster token. For regular tokens actions are different (links in figma lead to proper screens).

**Comment by micieslak** [comment]
Blocked by https://github.com/status-im/status-desktop/issues/12027
