### ISSUE TITLE
Unread message count on the community badge is including muted channels

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#11040]
When the user gets mentioned in a muted and unmuted channel the unread message badge on the community icon is including both of them.

## Steps to reproduce

1. Open the app
2. Mute a channel in a community
3. Get mentioned in the muted channel
4. Get mentioned in the unmuted channel

#### Expected behavior
Unread message badge on the community icon should show 1 unread message.

#### Actual behavior
Unread message badge on the community icon should shows 2 unread messages, including the one from the muted channel.

### Additional Information

- Status desktop version: PR 10968
- Operating System: Windows 11 22H2

https://github.com/status-im/status-desktop/assets/52439419/45668db3-82fc-4f48-bbd8-d21f1d80fe5c

**Comment by jrainville** [comment]
IMO, it's ok to up the community badge when there is a notification on a muted channel. Otherwise you will not know you were notified. That's also how Discord works.

Up to designers though cc @John-44

**Comment by jrainville** [comment]
I'll close this as I consider this the expected behaviour
