### ISSUE TITLE
New Beta dialog design - to be presented every time user launches Status in Beta

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11044]
A new Beta dialog design has been created with more extensive disclaimer copy highlighting areas of the app which may not be performant, stable or reliable. The dialog should be presented to users every time the app is launched. The dialog does not feature a close `X` top right so the only way for the user to proceed is to check the acknowledgements.

<img width="1440" alt="Beta-dialog" src="https://github.com/status-im/status-desktop/assets/110033914/229e22e0-cd0c-4863-b056-45dd3bfd35d4">

<img width="1440" alt="Beta-Acknowledged" src="https://github.com/status-im/status-desktop/assets/110033914/3f1ec56b-19ec-481c-bbd8-f59b276a3d16">

Designs:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=31450-560694&t=bO2xh3Cg3mbrnUey-4

cc @John-44

**Comment by alexjba** [comment]
@benjthayer I'm sharing here a feedback from other Status contributors.

This dialog looks like this on a minimised app:

<img width="1397" alt="Screenshot 2023-10-10 at 13 58 35" src="https://github.com/status-im/status-desktop/assets/47811206/63195dd8-e8d3-4630-ae62-7f9d0b623b3c">

It's not clear the dialog is scrollable and the user is stuck because the `I'm ready to use Status` button is disabled.

**Comment by John-44** [comment]
> @benjthayer I'm sharing here a feedback from other Status contributors.
> 
> This dialog looks like this on a minimised app:
> 
> <img alt="Screenshot 2023-10-10 at 13 58 35" width="1397" src="https://user-images.githubusercontent.com/47811206/273879241-63195dd8-e8d3-4630-ae62-7f9d0b623b3c.png">
> It's not clear the dialog is scrollable and the user is stuck because the `I'm ready to use Status` button is disabled.

@benjthayer perhaps an easy fix would be to remove the Status logo at the top?

**Comment by benjthayer** [comment]
Thanks @John-44 @alexjba  - agree - here's a couple of options:

1) Removing the logo and reducing the spacing between paragraphs ensures we can show at least 1 of the checkboxes in min app height
- If we tweaked the copy, we might be able to get both checkboxes visible
- OR we could remove the second checkbox `I’m ready to use Status Desktop Beta` which feels less critical

2) Make the checkboxes sticky along with the lower action bar with the copy scrolling underneath 

<img width="1322" alt="Screenshot 2023-10-10 at 12 48 56" src="https://github.com/status-im/status-desktop/assets/110033914/e1425115-3402-42a2-a442-7fda4f5cf48c">

**Comment by John-44** [comment]
> Thanks @John-44 @alexjba - agree - here's a couple of options:
> 
> 1. Removing the logo and reducing the spacing between paragraphs ensures we can show at least 1 of the checkboxes in min app height
> 
> * If we tweaked the copy, we might be able to get both checkboxes visible
> * OR we could remove the second checkbox `I’m ready to use Status Desktop Beta` which feels less critical
> 
> 2. Make the checkboxes sticky along with the lower action bar with the copy scrolling underneath
> 
> <img alt="Screenshot 2023-10-10 at 12 48 56" width="1322" src="https://user-images.githubusercontent.com/110033914/273889750-e1425115-3402-42a2-a442-7fda4f5cf48c.png">

@benjthayer I lean towards going with the version on the left, with the following additional amendment - remove the "I confirm that..." text (saves another line, and perhaps also remove the line break?

**Comment by alexjba** [comment]
> Thanks @John-44 @alexjba - agree - here's a couple of options:
> 
> 1. Removing the logo and reducing the spacing between paragraphs ensures we can show at least 1 of the checkboxes in min app height
> 
> * If we tweaked the copy, we might be able to get both checkboxes visible
> * OR we could remove the second checkbox `I’m ready to use Status Desktop Beta` which feels less critical
> 
> 2. Make the checkboxes sticky along with the lower action bar with the copy scrolling underneath
> 
> <img alt="Screenshot 2023-10-10 at 12 48 56" width="1322" src="https://user-images.githubusercontent.com/110033914/273889750-e1425115-3402-42a2-a442-7fda4f5cf48c.png">

One other option I see is to always show the scrollbar.

**Comment by benjthayer** [comment]
> @benjthayer I lean towards going with the version on the left, with the following additional amendment - remove the "I confirm that..." text (saves another line, and perhaps also remove the line break?

With 12px to spare @John-44

<img width="858" alt="Screenshot 2023-10-10 at 13 06 25" src="https://github.com/status-im/status-desktop/assets/110033914/c7298d31-b1ba-4444-b7e9-686547546ae8">

**Comment by benjthayer** [comment]
> Looks good to me, thanks @benjthayer ! :-)

Excellent! Designs updated here @alexjba 👍
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=31450-560694&mode=design&t=tjD5js8UqBrXPBp2-4
