### ISSUE TITLE
Unread message badge is not removed in muted channel

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#11041]
When the user opens a muted channel they were mentioned in the unread message badge does not go away.

## Steps to reproduce

1. Open the app
2. Mute a channel in a community
3. Get mentioned in the muted channel
4. Open the muted channel

#### Expected behavior
Unread message badge is removed.

#### Actual behavior
Unread message badge is not removed.

### Additional Information

- Status desktop version: PR 10968
- Operating System: Windows 11 22H2

https://github.com/status-im/status-desktop/assets/52439419/ad15d397-2aff-413f-b244-99b6c01d0d86

**Comment by anastasiyaig** [comment]
@jrainville badges! :D
