### ISSUE TITLE
Invalid width for items chat list

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#11047]
# Bug Report

<img width="1312" alt="Screenshot 2023-06-09 at 16 06 16" src="https://github.com/status-im/status-desktop/assets/25482501/8d3f2101-c521-4ce3-8479-b9d641b20fdd">

## Description

I tried to quick-fix this, but there's a problem here:

https://github.com/status-im/status-desktop/blob/43c7258328a0df542318872624d73899a049ddff/ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml#L124-L130
https://github.com/status-im/status-desktop/blob/43c7258328a0df542318872624d73899a049ddff/ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml#L304-L308

This could be fixed settings `Layout.fillWidth: true` to actions, like usage docs says
https://github.com/status-im/status-desktop/blob/43c7258328a0df542318872624d73899a049ddff/ui/StatusQ/src/StatusQ/Components/StatusDraggableListItem.qml#L77
, but such QML doesn't load at all.

As I understand, you can't reparent to a Layout.

NOTE: Can be simply tested with Storybook with `StatusChatListAndCategoriesPage.qml` page.

**Comment by caybro** [comment]
> cc @caybro Though this is definitely not urgent slightly_smiling_face

Well I'd say yes - it cuts out the notifications' badge :/

**Comment by caybro** [comment]
FTR, I was able to repro in Storybook too:

![Snímek obrazovky z 2023-06-13 12-17-41](https://github.com/status-im/status-desktop/assets/5377645/5fcc6c9c-74ef-4376-aad7-a5821648702c)

**Comment by caybro** [comment]
Fixed:
![Snímek obrazovky z 2023-06-13 12-22-08](https://github.com/status-im/status-desktop/assets/5377645/67ed847b-2801-428c-b610-bc623721da11)
