### ISSUE TITLE
Syncing: new device notification

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#11078]
### Description

@John-44:
> If a user already has devices  '1 -> 2' paired, when the user then later pairs devices '2 -> 3' , then a notification should appear on device '1' informing the user that a device '3' has appeared, and do they want pair devices '1' and '3'.  If user taps "Accept" then devices '1' and '3' should become paired, I'll post the designs for this below (and like all notifications, this notification should appear as both a bubble notification and an entry in the Notification Centre).

Mobile design:
https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=4537-515917&t=Ictm44ypvb3xKiPZ-4

<img width="1060" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/b58b3e2d-5fad-4212-8e41-d97f74bc944b">

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone, however this could be done in the stabilization period with other refactors if there is room
