### ISSUE TITLE
Profile showcase backend

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#11081]
### Description

The UI for this feature is ready but we need to implement the backend part

**Comment by MishkaRogachev** [comment]
Figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=725-11513&mode=design&t=YIdxDhrwIgr2G8tY-0

**Comment by MishkaRogachev** [comment]
Also needs this: https://github.com/status-im/status-desktop/pull/12594
