### ISSUE TITLE
Community: Admin could not accept user after rejecting a join request

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11094]
# Bug Report

## Description

Found during #10909 

## Steps to reproduce

1. Reject a join request as an Admin
2. Attempt to accept the request from the rejected screen

![image](https://github.com/status-im/status-desktop/assets/50769329/82f9b102-f611-4b11-8fd4-d885004d338e)

### Additional Information

- Status desktop version: Mac
- Operating System: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10909/25/

**Comment by jrainville** [comment]
Closing this as it has been fixed a while ago
