### ISSUE TITLE
Banned user was not moved to ban list on the Admin instance

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11096]
# Bug Report

## Description

Found during #10909 

## Steps to reproduce

1. Edit members on Admin account
2. Ban a member
3. Member was banned but not moved to ban list - could not unban
4. Member could only be unbanned by owner

### Additional Information

- Status desktop version: Mac
- Operating System: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10909/25/

**Comment by iurimatias** [comment]
note, issue is not just the unban part but that the user still shows in the member list for some users even though the user is banned

**Comment by iurimatias** [comment]
note: I believe this has been fixed

**Comment by glitchminer** [comment]
Retested and it's no longer reproducible. Setting to closed.
