### ISSUE TITLE
Community: Join request appeared in Owner nodes's pending requests twice

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11095]
# Bug Report

## Description

Found during #10909 

![image](https://github.com/status-im/status-desktop/assets/50769329/c058c989-c458-4fca-871c-fe8d97f9d7e7)

## Steps to reproduce

1. Send join request for community
2. Reject join request as admin
3. Observe on Owner node that there are 2 requests for the same user

### Additional Information

- Status desktop version: Mac
- Operating System: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10909/25/

**Comment by jrainville** [comment]
I'll close this as we've made improvements to this lately and I haven't seen it so far.
