### ISSUE TITLE
Wallet - > Saved addresses: Network selector is not active when adding address as ENS name

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11090]
### Description

<img width="1427" alt="Screenshot 2023-06-14 at 22 18 20" src="https://github.com/status-im/status-desktop/assets/82375995/e21ece3a-b056-4e93-8d2a-526167fc3fd3">

**Comment by anastasiyaig** [comment]
@IvanBelyakoff @alaibe @benjthayer is that a bug? It seems like yes but please confirm we want network selection available for ens name input too

**Comment by benjthayer** [comment]
@anastasiyaig thanks - I don't think the addition of an ENS into the address field was defined in the designs. @John-44 I assume this information isn't pulled from the ENS data added by the user given the multichain address concept is new and being driven by us? In that case, should we enable the addition of network preferences, and if so, should the network short IDs be prepended to the ENS name in the same way they are for addresses? 

<img width="506" alt="Screenshot 2023-06-15 at 07 43 08" src="https://github.com/status-im/status-desktop/assets/110033914/2f2f75ec-55c7-4b7f-87c9-1363f5dc011e">

**Comment by benjthayer** [comment]
> @benjthayer @anastasiyaig This is by design, I remember discussing it with @John-44. Network selection should not be active for ENS names, because ENS names can point to multiple addresses on multiple chains (forgive me if I am not quite correct, I forgot the correct ERC for this), so there is a standard way of working ENS names and chains and our networks prefixes are redundant. I think we should close this issue.

That makes sense, thanks for clarifying Ivan. :)

**Comment by anastasiyaig** [comment]
would it be a super picky to hide this selector in case i put an ENS name as an address? @IvanBelyakoff how painful is that? If it requires too much logic behind, then lets give up :D

**Comment by anastasiyaig** [comment]
closing then, i will fix the test to check this as well
