### ISSUE TITLE
Community: Admin and Member instances crashed after changing permissions via owner node

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11097]
# Bug Report

## Description

Found during #10909 

## Steps to reproduce

Have not been able to consistently reproduce this but it has occurred multiple times now. 

1. Have owner, admin and member instances open
2. Change community permissions on owner node (delete some / add some)

### Additional Information

- Status desktop version: Mac
- Operating System: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10909/25/

**Comment by 0x-r4bbit** [comment]
@glitchminer I've tried reproducing this but was unable to. Are you still able to reproduce this on latest master?

**Comment by glitchminer** [comment]
Hey @0x-r4bbit , I think there has been further work done on the permissions since this was raised. It's not reproducible on master now. Closing.
