### ISSUE TITLE
[Check #14639] Communtiy Airdrops: Fees calculation - support "exceeding the per block gas limit" error

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11104]
# Bug Report

## Description

Currently we have following error codes for fees calculation:

```
    enum ComputeFeeErrorCode {
        Success,
        Infura,
        Balance,
        Other
    }
```
There is no custom error code for exceeding the per block gas limit.

![image](https://github.com/status-im/status-desktop/assets/20650004/50db0b90-0f49-4488-b90e-45341056ad44)

**Comment by micieslak** [comment]
@John-44 - me and @endulab had a small discussion about that task. It turns out that it may be problematic to detect particular types of errors bc they all comes as strings with some sentences describing the problem. What we can do is to parse that and categorize by using some heuristics. However when underlying text is changed, it gets broken easily. One option, proposed by @endulab is to present original message (e.g. in some tooltip) when user wants to know details related to the error. The drawback is that it would be always English.

**Comment by saledjenic** [comment]
This is fixed in this PR https://github.com/status-im/status-go/pull/5377
