### ISSUE TITLE
Contact request message is not shown in chat for the receiver

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#11113]
# Bug Report

## Description

![image](https://github.com/status-im/status-desktop/assets/25482501/973d7538-3f38-498d-bf0b-3ef7b08b60ed)

## Steps to reproduce

1. User 1: send contact request with message `1`
2. User 2: accept contact request
3. User 2: note chat opened, no message `1` ⬅️ 
4. User 2: send message `2`
5. User 1: note both `1` and `2` messages
6. User 2: note still no message `1`⬅️ 

"Fetch more messages" doesn't help.

Tested on 407179cd104c677c9ae693ba0f35e91f06073720

**Comment by igor-sirotin** [comment]
cc @MishkaRogachev, I think you was working with contact requests recently

**Comment by MishkaRogachev** [comment]
Should be fixed here: https://github.com/status-im/status-desktop/pull/11178
