### ISSUE TITLE
Version 0.13.0-rc2 fails execution

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#11128]
Tried running 0.13.0-rc2 today, noticed that the app image isn't starting.
Checked the logs, then found:

```
Warning: QQmlApplicationEngine failed to load component (:0, )

Warning: qrc:/main.qml:18:1: plugin cannot be loaded for module "StatusQ": Cannot load library /tmp/.mount_StatusNzRL1R/usr/bin/StatusQ/libStatusQ.so: (/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_StatusNzRL1R/usr/bin/StatusQ/libStatusQ.so)) (qrc:/main.qml:18, )

INF 2023-06-19 09:49:15.230+02:00 starting application...                    topics="status-app" tid=255328 file=nim_status_client.nim:189

WRN 2023-06-19 09:49:15.233+02:00 Error decoding signal                      topics="signals-manager" tid=255328 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"

Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )

INF 2023-06-19 09:49:15.233+02:00 shutting down...                           topics="status-app" tid=255328 file=nim_status_client.nim:157

INF 2023-06-19 09:49:15.233+02:00 logging out...                             topics="app-controller" tid=255328 file=app_controller.nim:284

Traceback (most recent call last)

/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(193) nim_status_client

/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(166) mainProc

/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/app/boot/app_controller.nim(285) delete

/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/app_service/service/general/service.nim(43) logout

/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/backend/general.nim(27) logout

/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nim-status-go/status_go.nim(143) logout

SIGSEGV: Illegal storage access. (Attempt to read from nil?)

Segmentation fault (core dumped)
```

According to @osmaczko 

> https://docs.appimage.org/reference/best-practices.html?highlight=glibc#binaries-compiled-on-old-enough-base-system
> As a general rule of thumb, please use no libstdc++.so.6 newer than the one that comes with the oldest distribution that you still want to support, i.e., the oldest still-supported LTS version of Ubuntu. seems this rule has been broken

- Operating System: Ubuntu 20.04.6 LTS

**Comment by anastasiyaig** [comment]
@jakubgs please take a look

**Comment by jakubgs** [comment]
I haven't even fixed Linux builds in:

* https://github.com/status-im/infra-ci/issues/88

**Comment by jakubgs** [comment]
Also, this looks like a job for devs, if the runtime crashes.

**Comment by jrainville** [comment]
For what it's worth, last week (or maybe it was the one before), I packaged the app locally using the Docker image and that build worked fine, so the issue seems in the CI or the jenkinsfile?

**Comment by osmaczko** [comment]
> For what it's worth, last week (or maybe it was the one before), I packaged the app locally using the Docker image and that build worked fine, so the issue seems in the CI or the jenkinsfile?

What version of Ubuntu are you on?

**Comment by jrainville** [comment]
Ubuntu 20.04.3 LTS

**Comment by jakubgs** [comment]
Our Docker image for Linux builds is still on `18.04` due to Glibc limitation:
https://github.com/status-im/status-desktop/blob/54ae6a31546b75d36e6f21447a5f6a1af124e922/ci/Dockerfile#L4

That has not changed in more than 2 years.

**Comment by jakubgs** [comment]
I doubt it's the GCC upgrade, as we've been using GCC 11 for E2E linux builds for a long while without any issues.

But one check we could do is see if this build also crashes: [`StatusIm-Desktop-230614-093117-38d3b3-pr11065-x86_64.tar.gz`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-230614-093117-38d3b3-pr11065-x86_64.tar.gz)

* https://github.com/status-im/status-desktop/pull/11065

**Comment by jrainville** [comment]
Latest master worked fine when packaged using `build-linux.sh` on my machine.

**Comment by jrainville** [comment]
Welp, not the greatest test actually, because I tried `0.13.0.rc2` and it actually works on my machine...

I doubt the Ubuntu version difference between Pascal and I is the difference

**Comment by jakubgs** [comment]
I have checked the PR linux build from https://github.com/status-im/status-desktop/pull/11065 and it works fine on my machine.

**Comment by jakubgs** [comment]
But I have also tried the [`0.13.0-rc.2`](https://github.com/status-im/status-desktop/releases/tag/untagged-2e2e1217d2853d4221e7) AppImage and it worked as well. So that doesn't tell us much.

@0x-r4bbit does the build from https://github.com/status-im/status-desktop/pull/11065 also explode like that for you?

**Comment by 0x-r4bbit** [comment]
@jakubgs unfortunately it does not work either.

**Comment by 0x-r4bbit** [comment]
@jakubgs That one works!

**Comment by jakubgs** [comment]
@0x-r4bbit can you also test the new `master` build?
https://ci.infra.status.im/job/status-desktop/job/master/2547/

**Comment by 0x-r4bbit** [comment]
@jakubgs that one works for me as well.
