### ISSUE TITLE
Mutual contacts - System message should be above the message that comes in the contact request

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#11120]
When a user *who used to be a mutual contact, but isn't a mutual contact any more* send a new contact request, the 'system message' should be above the message that's included in the mutual contact request, not below as is shown in this screenshot

![Screenshot_2023-06-16_at_11](https://github.com/status-im/status-desktop/assets/22846356/1a2a8fa4-1bc3-4a70-8e16-8fdb54cf3ae9)

In this screenshot:

1.  "@ios parallax sent you a contact request" should be first
2. Then the "Please add me to your contacts" message from 'ios parallax' should be second
3. Then the two action buttons should be third

**Comment by MishkaRogachev** [comment]
Should be fixed here: https://github.com/status-im/status-desktop/pull/11178
