### ISSUE TITLE
Token minting: mint form is needlessly scrollable horizontally

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11123]
# Bug Report

## Description

The form has scrollable blank space on the right. It's also possible to trigger horizontal scrolling when using right arrow in the input fields.

[Screencast from 16.06.2023 13:55:34.webm](https://github.com/status-im/status-desktop/assets/20650004/9553aef2-f7c3-4962-87d1-888b6aed078e)

[Screencast from 16.06.2023 13:01:14.webm](https://github.com/status-im/status-desktop/assets/20650004/247191a9-dcad-47e7-8ae1-e4cd20baac45)

## Steps to reproduce

1. Create community
2. Go to community settings, section `Mint Tokens`
3. Disable `Unlimited supply` option
4. Clear `Total finite supply` text input

#### Expected behavior
No horizontal scrolling at all.

#### Actual behavior
There is horizontal scrolling bc of the blank space on the right.

**Comment by noeliaSD** [comment]
It can be related to recent `StatusScrollView` refactor
