### ISSUE TITLE
Scheduler to transform pending transaction to transaction

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#11139]
### Goals
- Move watching pending transactions to status-go
- Handle restart of watching pending transactions on app restart
- Integrate pending transactions manager with transfers scheduler to properly transform pending transaction to transaction (pending transaction must be deleted immediately once corresponding transaction is saved to `transfers `table for wallet transactions or confirmed for non-wallet transactions)

**Comment by stefandunca** [comment]
Finished with the fix https://github.com/status-im/status-desktop/pull/12055
