### ISSUE TITLE
[Community] New design flows to integrate `Revealing addresses when joining Community` functionality

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11138]
### Description

This is a task related to new design flows to integrate which addresses to reveal when joining a community

[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=31461-597356&t=rp8aS5G1lydW9Rsb-0)

The work is UI only, no backend will be done as part of this task

## Overview
![image](https://github.com/status-im/status-desktop/assets/5377645/0af884af-9eab-4df9-9359-d1ee536aba34)

The dialog has 2 modes (when joining, with a back button, and a plain one, when editing) and basically consists of a 3 vertical parts:
- (optional) warning red banner
- addresses section (all selected by default, ordered by balance of relevant tokens)
  - primary: `icon` / `name`
  - secondary: `tokens` below 
  - right side actions:
    - `airdrop` radio button (which addresses to perform the airdrop on); default first in the list, requires auth
    - `select checkbox` (which addresses to share with the community); 1+ multi-select
- (optional) permissions section (only for token gated community and/or channels)
  - `join` community permission
  - `channel` related permissions (`view only`, `view and post`)
  - `become admin` permission (hidden when criteria not met)

Both sections (addresses/permissions) accommodate in height with up to 50% (half split), and are individually scrollable.

## Permissions
Detailed join community permission types:
![image](https://github.com/status-im/status-desktop/assets/5377645/7bba0ac3-1926-4b8e-9be2-ab40c1a32fe4)

Complex channel related permissions:
![image](https://github.com/status-im/status-desktop/assets/5377645/ed2beab4-ff1d-458a-bb6e-d118773545af)

Related backend PRs/issues: 
- [x] https://github.com/status-im/status-desktop/pull/11224
- [x] https://github.com/status-im/status-desktop/pull/11530
- [ ] https://github.com/status-im/status-desktop/pull/11557
- [ ] https://github.com/status-im/status-desktop/issues/11480
- [ ] https://github.com/status-im/status-desktop/issues/11481
- [ ] https://github.com/status-im/status-desktop/issues/11532

**Comment by caybro** [comment]
PR https://github.com/status-im/status-desktop/pull/11214 will add a new signal:

```qml
Global.openEditSharedAddressesFlow(string communityId)
```

that will be used to hook into the flow (does nothing at the moment of this writing).
