### ISSUE TITLE
Community -> Manage permissions: deleting permission redirects to Overview page

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11146]
### Description

1. create a permission for community
2. delete it
3. note that user is redirected to Overview page

**Expected**: stay on Permissions page after editing / deleting permissions

https://github.com/status-im/status-desktop/assets/82375995/501861dd-d949-4314-b554-23c48b8e88d6

**Comment by noeliaSD** [comment]
It also happens when you mint!

**Comment by anastasiyaig** [comment]
@alexandraB99 is it something quick we can fix in 0.13?

**Comment by noeliaSD** [comment]
I've taken a quick look and seems this was introduced in this commit: https://github.com/status-im/status-desktop/commit/82a1ed2f7aa46750fb5ab891e2ce40f61287eccb

With the addition of these 2 bindings with `root.community.memberRole` in `CommunitySettingsView` in some point it causes the `onSettingsMenuModelChanged` trigger that modifies the stacklayout current item to 0 (overview) :
```
        {id: Constants.CommunitySettingsSections.MintTokens, name: qsTr("Mint Tokens"), icon: "token", enabled: root.community.memberRole === Constants.memberRole.owner},
        {id: Constants.CommunitySettingsSections.Airdrops, name: qsTr("Airdrops"), icon: "airdrop", enabled: root.community.memberRole === Constants.memberRole.owner}]
```
@mprakhov maybe it is easy for you to solve it. Could you take a look?

**Comment by mprakhov** [comment]
I can take a look, but after finishing my current task

**Comment by jrainville** [comment]
I put it as 0.14. I think the bug is a small enough inconvenience that it doesn't deserve a patch on the RC

**Comment by jrainville** [comment]
@mprakhov FYI I assigned to @0x-r4bbit
