### ISSUE TITLE
Inconsistency in localization in seed phrase restoring screen

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-desktop#11155]
# Bug Report

## Description
![image](https://github.com/status-im/status-desktop/assets/33176106/dad04b76-bbac-4539-a8ef-320360803131)

Inconsistency between time remaining to finish syncing locale and other text on the screen

## Steps to reproduce
Restore account with seed phrase.

#### Expected behavior
Should have the same locale (e.g. If the user uses an Arabic locale on his OS then all text should be Arabic)
#### Actual behavior
Inconsistent localization in text

**Comment by caybro** [comment]
Kinda expected... the translations are simply not completely done (yet) in this part

**Comment by jrainville** [comment]
Closing as we haven't translated the app fully yet.
