### ISSUE TITLE
Consider doing channel permission checks while handling community updates

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#11157]
As discussed in #11156, we might want to consider performing channel permission checks right when we receive and handle community description updates.

The idea would be to check the new incoming `CommunityDescription` for changes in its `TokenPermissions`. 
If there are any, perform the necessary channel checks.

The channel checks will create a `CheckChannelPermissionResponse` for each channel, that can then be attached to the `MessengerResponse`.

Clients that receive the new community description will then also have the information of which channel permissions were satisfied.

One thing to consider though, is that it can lead to slower processing of community descriptions as clients have to wait until the channel checks are done. 

The same mechanism can be done for permissions to join as well.

**Comment by 0x-r4bbit** [comment]
Maybe @cammellos has some additional input here on why this should **not** be done (or maybe only in a particular way)

**Comment by cammellos** [comment]
@0x-r4bbit it's probably ok, but it should not be synchronous, so it should be put on a queue or done periodically

**Comment by 0x-r4bbit** [comment]
If we don't do it synchronously (within handling incoming messages, which is asynchronous), then we won't get the channel permissions responses as part of the messenger response. 

Then we might as well not do it.

**Comment by cammellos** [comment]
> If we don't do it synchronously (within handling incoming messages, which is asynchronous), then we won't get the channel permissions responses as part of the messenger response.
> 
> Then we might as well not do it.

you would signal it

**Comment by 0x-r4bbit** [comment]
> you would signal it

That's essentially what's already happening when clients call the API explicitly after receiving a token permission update, and it's what leads to the "flash of unsatisfied permissions", which we're trying to fix.

**Comment by cammellos** [comment]
sorry, didn't read the original issue:) 
you can notify the client that permissions are being checked, until permissions are checked,at that point you can show the user the banner?

**Comment by 0x-r4bbit** [comment]
Right, if we show some loading indicator, then we can indeed just stick with what's already there.
Will discuss this with John

**Comment by 0x-r4bbit** [comment]
Waiting for @benjthayer to create some loading indicator with his design magic

**Comment by caybro** [comment]
> Waiting for @benjthayer to create some loading indicator with his design magic

StatusDotsLoadingIndicator would fit this imo

**Comment by benjthayer** [comment]
Designs incoming! Just focused on wallet charting atm. If this becomes a blocker just ping me and I'll expedite :)

**Comment by osmaczko** [comment]
> Designs incoming! Just focused on wallet charting atm. If this becomes a blocker just ping me and I'll expedite :)

@benjthayer temporarily, before the designs are ready, I've implemented it as follows:

https://github.com/status-im/status-desktop/assets/33099791/5e22c5ac-64dc-457c-9edd-f146a490e244

Once the designs are finalized, please notify me. I'll then create an issue and delegate it to the UI team.
