### ISSUE TITLE
Messaging -> Reply: reply box is not gone when switching channels if the very last message was a reply message

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11167]
### Description

1. open any chat
2. send a message
3. reply to it
4. switch to another chat
5. get back to previous chat

**As result** - there is a reply box shown still in input area

https://github.com/status-im/status-desktop/assets/82375995/5f91e2a7-5457-4da0-b20a-196a67542ae2

**Comment by anastasiyaig** [comment]
@jrainville can that be for 0.14?

**Comment by jrainville** [comment]
> @jrainville can that be for 0.14?

Easily for 0.14. Do you reckon we should put it in 0.13? It's quite annoying and is a regression

**Comment by anastasiyaig** [comment]
i would love to see it fixed in 0.13 however it is not really a blocker @jrainville so it is up to us to decide i think. And depends on how destructive the fix could be :D

**Comment by jrainville** [comment]
> i would love to see it fixed in 0.13 however it is not really a blocker @jrainville so it is up to us to decide i think. And depends on how destructive the fix could be :D

Good point. @igor-sirotin do you think you can fix this fast and is it a one liner? If it's a fast and small fix, let's put it in 0.13, if not, just 0.14 (master)

**Comment by igor-sirotin** [comment]
@jrainville Will take a look today 👌

**Comment by igor-sirotin** [comment]
The fix is here: https://github.com/status-im/status-desktop/pull/11195

Also faced a bug that the text wasn't preserved when switching to a chat with Blocked contact. Fixed that as well.
_____

> Same happens if you're uploading an image fwiw

@caybro, couldn't reproduce the bug with images.
