### ISSUE TITLE
Account recovery shouldn't show loading state when state is complete

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#11163]
After recovering an account from seed, I ended up seeing this:

![Screenshot from 2023-06-20 11-15-30](https://github.com/status-im/status-desktop/assets/445106/2302f64c-f48f-45c3-afd9-1ab80f730b28)

Notice that all items seem to be complete, yet I have to wait another 1.5 minutes for the app to continue.
I think we should stop the timer if we know all necessary items were loaded.

**Comment by caybro** [comment]
CC @alexjba

**Comment by noeliaSD** [comment]
I also noticed that the timer switches from `...` to a real time like this:

![Screenshot 2023-06-20 at 16 43 25](https://github.com/status-im/status-desktop/assets/97019400/57e8dcc7-3274-418e-a234-f88ee36f2656)

**Comment by caybro** [comment]
> I also noticed that the timer switches from `...` to a real time like this:
> 
> ![Screenshot 2023-06-20 at 16 43 25](https://user-images.githubusercontent.com/97019400/247152268-57e8dcc7-3274-418e-a234-f88ee36f2656.png)

Looks like an `elide` for text too long

**Comment by caybro** [comment]
Default window size occludes the last item + button:

![image](https://github.com/status-im/status-desktop/assets/5377645/4b010232-1bb5-417a-b6a6-0f209ce5a978)

**Comment by 0x-r4bbit** [comment]
@caybro that's already raised in https://github.com/status-im/status-desktop/issues/10947

**Comment by alexjba** [comment]
> @caybro that's already raised in #10947

Would make sense to group them into 1 bug? All of them are small tweaks we need to do in the UI.

**Comment by caybro** [comment]
Moving to 2.31 as this issue depends on/ is blocked by https://github.com/status-im/status-go/issues/5022

**Comment by caybro** [comment]
This will be covered by the new Onboarding EPIC (https://github.com/status-im/status-desktop/issues/16712), more specifically by https://github.com/status-im/status-desktop/issues/16799
