### ISSUE TITLE
Windows - App keeps crashing after logging in

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#11176]
App keeps crashing a couple of minutes after loggin in. The account that is logged in was used to mint tokens before the crash started occuring.

I've checked the same account on macos and it works fine there.

### Additional Information
**Error showing up after login:**
![error](https://github.com/status-im/status-desktop/assets/52439419/515d3b94-e2b3-4279-8d2e-3d7e208320a9)
**Logs:**
[app_20230620_125404.log](https://github.com/status-im/status-desktop/files/11799412/app_20230620_125404.log)

- Status desktop version: v0.13.0-rc.2
- Operating System: Windows 11 22H2

**Comment by alexjba** [comment]
I can reproduce this on MacOS:
Repro steps:
1. Mint a token using testNet (I've used Optimism Goerli)
2. Log out
3. Log in

**Comment by noeliaSD** [comment]
I'm not experiencing crashes, but my app freezes after logging in. I had an old account with some minted tokens... this couldn't be used anymore. Then I created a new one yesterday and today I minted a token, after that (maybe not immediately) it behaves the same way again... after login it freezes.

**Comment by anastasiyaig** [comment]
its very odd that I was not able to reproduce. lets test this in PR :)

**Comment by noeliaSD** [comment]
> 

Do you have an account with minted tokens? Mine also has a token already airdroped, so 1 collectible in the wallet account.. 

Attached log: [Process 99671 stopped.zip](https://github.com/status-im/status-desktop/files/11815972/Process.99671.stopped.zip)

**Comment by alexjba** [comment]
> Do you have an account with minted tokens @anastasiyaig ? Mine also has a token already airdroped, so 1 collectible in the wallet account..
> 
> Attached log: [Process 99671 stopped.zip](https://github.com/status-im/status-desktop/files/11815972/Process.99671.stopped.zip)

@jrainville WDYT, should be a different issue? The crash reported by Noelia seems to be triggered by this call stack when there is one airdropped token in the wallet:
```
* thread #56, stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x000000010ac9b790 libstatus.dylib`github.com/status-im/status-go/services/ext.(*Service).FetchNFTMetadata + 32
    frame #1: 0x000000010ab539c8 libstatus.dylib`github.com/status-im/status-go/services/wallet/collectibles.(*Manager).processAssets + 760
    frame #2: 0x000000010ab539c8 libstatus.dylib`github.com/status-im/status-go/services/wallet/collectibles.(*Manager).processAssets + 760
    frame #3: 0x000000010ab52f08 libstatus.dylib`github.com/status-im/status-go/services/wallet/collectibles.(*Manager).FetchAllAssetsByOwner + 152
    frame #4: 0x000000010cd2e360 libstatus.dylib`golang.org/x/text/encoding/korean.encode5 + 544
```

**Comment by jrainville** [comment]
> WDYT, should be a different issue?

Good catch. Maybe it's all the same root, but the crash seems to happen in a very different place, so maybe it's not fully related

**Comment by caybro** [comment]
> frame #4: 0x000000010cd2e360 libstatus.dylib`golang.org/x/text/encoding/korean.encode5 + 544

Really some Korean text encoding? :o

**Comment by noeliaSD** [comment]
Just to confirm, I can reproduce it more or less consistenly on MacOS:

1. Create new account.
2. Mint token --> Process ends correctly
3. Airdrop token --> Process ends correctly.
4. If you don't restart the application seems the application works correctly (Just tested for 3 / 4 minutes.. maybe if you use it more time, it also becomes frozen).
5. If you restart the application, first time you can do some actions, like screen navigations, until maybe in 2 / 3 minuts it becomes frozen.
6. If you restart the application, maybe second / third time, it just becomes frozen after loggin.

I tried without airdropping, just only minting, and the application works fine after some minutes of usage.

**NOTE:** Tried 4 times, with 4 different new accounts, and same behavior found.

**Comment by anastasiyaig** [comment]
@noeliaSD there is a PR linked, did u try there?

**Comment by noeliaSD** [comment]
> 

Not yet, will try!! Thanks!

**Comment by noeliaSD** [comment]
@anastasiyaig @jrainville I can confirm I can reproduce the same way as described above using the [PR](https://github.com/status-im/status-desktop/pull/11196) branch.

**Comment by anastasiyaig** [comment]
oh no , thanks for trying @noeliaSD

**Comment by alexjba** [comment]
@anastasiyaig I found some specific repro steps. Might be crashing on other flows with the same root cause, but this is the fast way of crashing the app:
1. Go to Minted tokens, open a token
2. Go to community and reorder channels

https://github.com/status-im/status-desktop/assets/47811206/80f63edd-16b9-46bc-a0f5-63d7445ceb56
