### ISSUE TITLE
Community settings: Overview page doesn't fit narrow window width

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11183]
# Bug Report

## Description

The layout becomes trimmed when window width is reduced to minimum

## Steps to reproduce

https://github.com/status-im/status-desktop/assets/20650004/e827747f-ad26-48f9-8385-b72f7506fac5

**Comment by alexjba** [comment]
The footer is blocking the layout to a minimum width that's larger than the view width. Should be fixed by https://github.com/status-im/status-desktop/issues/11321

**Comment by caybro** [comment]
Fixed with https://github.com/status-im/status-desktop/pull/11430
