### ISSUE TITLE
[Mint Token] Sanitize description validation field 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11185]
### Description

The user can write description with repeating white spaces like spaces, tabs and new lines. As a result user can set a description containing e.g. 280 new lines, what is later presented to other users as a long blank scrollable area.

Before presenting in the "Preview" and sending to the network, the description should be sanitized by removing extra white characters.

![Screenshot from 2023-06-20 14-39-43](https://github.com/status-im/status-desktop/assets/20650004/c8889b99-c60b-4855-b287-1dd3b449af3b)

![Screenshot from 2023-06-20 14-39-51](https://github.com/status-im/status-desktop/assets/20650004/a80c7d29-f406-4791-aec4-c79aac5f4270)

**Comment by alexandraB99** [comment]
Will be done here https://github.com/status-im/status-desktop/issues/11307
