### ISSUE TITLE
"Please add me to your contacts" randomly added to 1-1 chat

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11191]
# Bug Report

## Description

![image](https://github.com/status-im/status-desktop/assets/11926403/41b57ca1-67ec-40d6-a996-93728d48cee2)

Out of nowhere, my contact request message from a while ago was shown in the 1-1 chat I had with @0x-r4bbit .

The date on it doesn't make sense either, so I assume the timestamp is 0, because the date is 1969.

## Steps to reproduce

No idea. I just opened the app and the message was there under new messages from @0x-r4bbit .

@0x-r4bbit did you by any chance re-send me a request or something?

Restarting the app doesn't affect it. The message stays.

#### Expected behavior

No repeat contact request message, especially not with the wrong date.

#### Actual behavior

Random contact request message

### Additional Information

- Status desktop version: 0.13.rc2
- Operating System: Ubuntu 20

**Comment by 0x-r4bbit** [comment]
> @0x-r4bbit did you by any chance re-send me a request or something?

Nothing alike. I just updated my desktop version to 0.13.0 with the ubuntu fixes

**Comment by jrainville** [comment]
Ok, so that means that there is just a small bug somewhere

**Comment by jrainville** [comment]
I think this was fixed by @MishkaRogachev in his fix for SpiffWorkflow
