### ISSUE TITLE
Wallet -> Watch only accounts recovered with seed are missing titles

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11193]
### Description

1. title is missing
2. icon is always the same black one

**Steps:**

having account u know a seed for, add some watch only accounts there and recover it

![image](https://github.com/status-im/status-desktop/assets/82375995/faa0e704-0876-490b-b1d9-f3143a86fb9f)

**Comment by anastasiyaig** [comment]
@alaibe do we want to fix that in RC? not a blocker though

**Comment by caybro** [comment]
I just recovered from seed phrase today on master and all was fine

**Comment by anastasiyaig** [comment]
just checked in master for my seed: several watch only accounts are missing titles

<img width="1552" alt="Screenshot 2023-06-21 at 17 48 11" src="https://github.com/status-im/status-desktop/assets/82375995/7b83e652-c5c7-4954-b67c-a7f46a9b0024">

**Comment by anastasiyaig** [comment]
alright i will check
