### ISSUE TITLE
Login fails: No such column C.MUTED_TILL

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11202]
# Bug Report
Failed to login on latest master due to `No such column: C.MUTED_TILL` error.

![Screenshot_2023-06-21_at_09 38 38](https://github.com/status-im/status-desktop/assets/47811206/44825140-bbcd-442a-b668-cee6b19f940c)

#### Expected behavior
Login successful
#### Actual behavior
Login error
### Additional Information

- Operating System: MacOS

**Comment by alexjba** [comment]
Might be related to https://github.com/status-im/status-go/pull/3549

CC @borismelnik

**Comment by alexjba** [comment]
@noeliaSD @caybro Please feel free to update the description if you have more meaningful info on repro steps

**Comment by caybro** [comment]
That's about it, just got an update for status-go

**Comment by borismelnik** [comment]
Will fix it today, sorry.

**Comment by jrainville** [comment]
Fixed here https://github.com/status-im/status-desktop/pull/10968
