### ISSUE TITLE
Community -> Minting: 0/1 remaining label shown for a token with infinite supply

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11208]
### Description

<img width="541" alt="Screenshot 2023-06-21 at 17 07 38" src="https://github.com/status-im/status-desktop/assets/82375995/0d55f06f-8d2b-42e0-84e8-7329dbc86016">

<img width="1834" alt="Screenshot 2023-06-21 at 17 25 06" src="https://github.com/status-im/status-desktop/assets/82375995/ec4a5255-18ba-4a6f-a124-fca534f6ff56">

We dont have designs for this case i guess (or I failed to find them)

**Comment by noeliaSD** [comment]
@benjthayer could you confirm that this is the expected behavior when the token minted is set as `infiniteSupply = true`?
![Screenshot 2023-06-22 at 07 23 36](https://github.com/status-im/status-desktop/assets/97019400/4f81d598-0c97-4707-9706-6c400a9117a9)

**Comment by benjthayer** [comment]
> @benjthayer could you confirm that this is the expected behavior when the token minted is set as `infiniteSupply = true`? ![Screenshot 2023-06-22 at 07 23 36](https://user-images.githubusercontent.com/97019400/247831233-4f81d598-0c97-4707-9706-6c400a9117a9.png)

This looks great but I think in the instance of infinite supply, we can simplify slightly to `[infinite icon] remaining`

Thanks for spotting - this was missing from the designs :)

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=33754-590474&t=sFcor9E4Na4hv7iM-4

<img width="1440" alt="Infinite-Remaining" src="https://github.com/status-im/status-desktop/assets/110033914/812b19de-b5e9-45df-ad71-b96a348c97ea">

**Comment by noeliaSD** [comment]
> > @benjthayer could you confirm that this is the expected behavior when the token minted is set as `infiniteSupply = true`? ![Screenshot 2023-06-22 at 07 23 36](https://user-images.githubusercontent.com/97019400/247831233-4f81d598-0c97-4707-9706-6c400a9117a9.png)
> 
> This looks great but I think in the instance of infinite supply, we can simplify slightly to `[infinite icon] remaining`
> 
> Thanks for spotting - this was missing from the designs :)
> 
> https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=33754-590474&t=sFcor9E4Na4hv7iM-4
> 
> <img alt="Infinite-Remaining" width="1440" src="https://user-images.githubusercontent.com/110033914/247874410-812b19de-b5e9-45df-ad71-b96a348c97ea.png">

Ok. I'll update it in the existing PR! Thankss
