### ISSUE TITLE
Received unexpected contact request notifications on upgrade to 0.13 RC2

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11206]
# Bug Report

## Description

Notifications were displayed in the activity centre for contact requests after upgrading to 0.13RC2, while keeping existing database. These were not expected as they had been handled some time ago. It's unclear whether they somehow came from the storenode despite being well over 30 days, or if it's the result of a database issue.

The contact requests did not appear in the pending requests of contact settings.

![image](https://github.com/status-im/status-desktop/assets/50769329/576d8591-c6e9-40b4-87b3-00546fd3a17f)

### Additional Information

- Status desktop version: Mac
- Operating System: 0.13 RC2

**Comment by lukaszso** [comment]
Had the same happen to me on Windows, this contact request was accepted last week
![cont](https://github.com/status-im/status-desktop/assets/52439419/71153b8e-4473-4ec3-a356-50625cc9d6eb)

**Comment by iurimatias** [comment]
possibly already fixed
