### ISSUE TITLE
[StatusChatInput] Clean up StatusChatInput conditions in ChatColumnView.qml

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#11203]
### Description
Maybe introduce states setting properties like `enabled`, and `textInput.placeholderText` in order for the code to not grow bigger.

**Comment by alexjba** [comment]
Currently the logic is split between `RootStore` (using `isUserAllowedToSendMessage` and `chatInputPlaceHolderText`) and inline, directly in `ChatColumnView.qml` bindings. In RootStore we handle One-to-one chats and group chats and community/channels and others seems to be handled inline, in property bindings.

The RootStore properties are also used in multiple places to enable/disable other features if the user is not allowed to send messages. This might bring inconsistencies when the chat input is disabled for reasons handled elsewhere.

I think we should also review all the flows where the user is currently not allowed to send messages to determine if we need to enable/disable other features like `Delete his own messages`, `View messages received before being blocked from chat`.
After this step we can proceed on refactoring the `enabled` and `textInput.placeholderText`.

Would be nice if the refactoring brings in these improvements:
1. Aggregate the business logic to be clear on which conditions the chat is disabled (probably a state based mechanism would be nice here as @alexandraB99 mentioned) and what placeholder text should be used for each case.
2. Make it clear what are the conditions where other features should be enabled/disabled (Eg. `Delete his own messages`, `View messages received before being blocked from chat`)

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
