### ISSUE TITLE
[Minting] Account name is empty during deployment

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#11219]
When the item is created in the model, the contract does not exist yet and the contract owner is empty.

![image](https://github.com/status-im/status-desktop/assets/61889657/584dcd27-098d-407b-8d61-bdb73f68a89e)

**How to reproduce:**
1. Mint token
2. Go to minted token list
3. Check Account field - this is empty.
4. The field is filled correctly after restart when the token is minted.

**Possible solution:**
Add to CommunityTokenDeployedArgs field with owner. Owner will be addressFrom in deployContract() function in community_tokens service.
Use this field in main module in onCommunityTokenDeployed function when creating new token item.

**Comment by anastasiyaig** [comment]
<img width="1505" alt="Screenshot 2023-06-26 at 11 37 49" src="https://github.com/status-im/status-desktop/assets/82375995/4028b3d9-cd82-4ca1-988f-85805ca2967e">

**Comment by endulab** [comment]
@MishkaRogachev, there is some logic change and I am going to add a deployer address to database and token item directly after deployment. This means that we do not want this ticket. The account name will be displayed correctly. It will be done in ticket #11250. You can close this ticket as a duplicate.

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev, there is some logic change and I am going to add a deployer address to database and token item directly after deployment. This means that we do not want this ticket. The account name will be displayed correctly. It will be done in ticket #11250. You can close this ticket as a duplicate.

Thanks!
