### ISSUE TITLE
Communities - Missing animation when token is being minted

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#11213]
The three dots next to the minting status are static while they should be animated

## Steps to reproduce

1. Start minting tokens
2. When minting is in progress click on the token to see the details
3. Observe the three dots in the top left corner

#### Expected behavior
Dots should animate

#### Actual behavior
Dots are static

https://github.com/status-im/status-desktop/assets/52439419/d169cb2a-a358-4017-af84-b0259e70d102

- Status desktop version: 0.13 rc2
- Operating System: Windows 11 22H2

**Comment by caybro** [comment]
It only appears frozen because the whole app is frozen due to some blocking call (I assume the "mintToken" backend call).  UI-wise this is using the correct component:

```qml
StatusDotsLoadingIndicator { visible: (root.deployState === Constants.ContractTransactionStatus.InProgress) }
```

**Comment by endulab** [comment]
@caybro the app is not blocked during the minting process. The system is listening to blockchain in the async manner and we receive a signal when the minting is done. Then the deployState is changed into "Completed".

**Comment by caybro** [comment]
Ok then there doesn't seem to be any reason for the loading indicator not to animate. @lukaszso can you pls check again on master when you get a spare cycle?

**Comment by iurimatias** [comment]
@lukaszso @anastasiyaig could you please check if this is still happening

**Comment by lukaszso** [comment]
@iurimatias checked latest master and the issue is gone. The loading animation is there, closing
