### ISSUE TITLE
[Wallet] Using empty wallet name creates confusing UX in minting view

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11218]
The user is allowed to edit the wallet name and use an empty string as name. It gets confusing when an empty wallet name is used in Minting accounts dropdown (probably the same for other views).

See this video and the linked comment for better understanding:

https://github.com/status-im/status-desktop/assets/47811206/d6d79cd0-f095-4e2a-9dcd-ee65c29e675e

_Originally posted by @noeliaSD in https://github.com/status-im/status-desktop/pull/11168#pullrequestreview-1490856758_

**Comment by alexjba** [comment]
@benjthayer WDYT about using wallets with empty names?

In the linked PR 2 options have been proposed:
1. Do not allow empty wallet name by validating the wallet name edit field
2. Display some placeholder text in the Minting wallet accounts dropdown when the name is empty.

These 2 options could work well together to fix current accounts with empty wallet names and also prevent empty wallet names from now on.

**Comment by benjthayer** [comment]
> @benjthayer WDYT about using wallets with empty names?
> 
> In the linked PR 2 options have been proposed:
> 
> 1. Do not allow empty wallet name by validating the wallet name edit field
> 2. Display some placeholder text in the Minting wallet accounts dropdown when the name is empty.
> 
> These 2 options could work well together to fix current accounts with empty wallet names and also prevent empty wallet names from now on.

Hi @alexjba I would think route 1 would be best - validating against an empty name both at the point of account creation and when editing the name- this will avoid missing wallet names altogether. 

While it's nice to give the user as much creative freedom as possible, there is little utility in an empty name and allowing them to do this would lead to a few UX issues later down the line as you rightly pointed out. 

If the user doesn't want to name their account, they can always stick with the automatically generated name `Account [number of account]` that is populated into the name field when the user is creating the account.

https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=15742-499323&t=kvNFpKtgHWy8Twvp-4

cc @John-44

**Comment by alexjba** [comment]
Cannot reproduce anymore! A valid account name is required
