### ISSUE TITLE
Community -> New community (and Edit community): make community banner, logo and description mandatory 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11234]
### Description

It is a feature change, per changes needed on mobile side, please make the community banner and community logo both required to proceed with new community creation

<img width="1312" alt="Screenshot 2023-06-23 at 15 51 32" src="https://github.com/status-im/status-desktop/assets/82375995/0384807b-9ede-4d6b-9a03-01eb204672c3">

**NOTE:** could be affecting community import, as there is no guarantee that imported community has this banner, worth taking into consideration this case as well

**Comment by anastasiyaig** [comment]
@churik @benjthayer @jrainville please check this out, per mobile team we need this change, but I dont know when so:
- confirm it is required change
- assign to a proper milestone based on urgency

**Comment by ilmotta** [comment]
Thanks for creating the issue @anastasiyaig. Based on a discussion with @John-44 over Discord, the agreement was that banners should be mandatory and that designs should not cater for a fallback. In the mobile app at the moment, missing banners look like a UI bug, and that was the motivation for the discussion.

I can't speak for the urgency, but it's worth noting status-mobile doesn't require any code changes because it's a data inconsistency issue.

**Comment by caybro** [comment]
Just a Q: what about the logo? That one is not mandatory either at the moment (on desktop)

**Comment by benjthayer** [comment]
It feels sensible to me to make Community name, description, logo and banner mandatory. This would simply be a case of disabling the `Next` button in the Community creation flow until those fields are complete/filled. Name, description, logo and banner are required for the directory both for indexing for user search and for optimal presentation of the Community card. Regarding the logo, I would have definitely thought we want to avoid empty/placeholder Community logos in the side bar as this will make it very hard for a user to navigate between Communities. cc @John-44

**Comment by John-44** [comment]
> Just a Q: what about the logo? That one is not mandatory either at the moment (on desktop)

@caybro well spotted, logo should be mandatory as well

**Comment by anastasiyaig** [comment]
i've asked that before , @churik said they dont logo

**Comment by churik** [comment]
What do you mean? It would be awesome if both fields are mandatory - fewer possibilities to get completely empty community details and fewer reasons to have a fallback for these cases(but we still need it for mobile)

**Comment by anastasiyaig** [comment]
ya sure lets make them both mandatory

**Comment by caybro** [comment]
Yup, on it :) PR in a few

**Comment by caybro** [comment]
Something I spotted along the way:

![image](https://github.com/status-im/status-desktop/assets/5377645/72ee1666-0f6d-4f5d-bdef-154ac3ae0fd4)

Is it intentional we don't allow _any_ punctuation in the description field? @benjthayer @John-44

**Comment by caybro** [comment]
Also... it's not 1980 and se should _not_ force international communities to use English only in field names and descriptions:

![image](https://github.com/status-im/status-desktop/assets/5377645/d94ed3ee-49fb-4126-9cd7-b5facfe3bf52)

**Comment by anastasiyaig** [comment]
@caybro there was a discussion happening somewhere, i _think_ we apply here requirements that match the display name requirements

https://github.com/status-im/status-desktop/issues/10120#issuecomment-1494633556

> we only support A-Z, a-Z, 0-9, -, _, and spaces between words in usernames. We utilize this to achieve a better compression ratio in our new URL format, and it's safer from a security prospective because if we allowed the full UTF-8 set then many characters can be used to impersonate other characters.

**Comment by caybro** [comment]
> @caybro there was a discussion happening somewhere, i _think_ we apply here requirements that match the display name requirements
> 
> [#10120 (comment)](https://github.com/status-im/status-desktop/issues/10120#issuecomment-1494633556)
> 
> > we only support A-Z, a-Z, 0-9, -, _, and spaces between words in usernames. We utilize this to achieve a better compression ratio in our new URL format, and it's safer from a security prospective because if we allowed the full UTF-8 set then many characters can be used to impersonate other characters.

Yeah it kinda makes sense for unique stuff (like display, community or token name); any description should be a free form text imo. No restrictions beside the total length

**Comment by anastasiyaig** [comment]
@benjthayer please help :D

**Comment by benjthayer** [comment]
> Also... it's not 1980 and we should _not_ force international communities to use English only in field names and descriptions:
> 
> ![image](https://user-images.githubusercontent.com/5377645/249456532-d94ed3ee-49fb-4126-9cd7-b5facfe3bf52.png)
> 
> This will seriously damage the outreach...

@John-44 might need some input here from a technical perspective - particularly regarding how the available characters for Community descriptions is tied in with URL compression considerations
