### ISSUE TITLE
[Wallet] Crash on login while processing NFT metadata (FetchNFTMetadata)

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11244]
# Bug Report
## Description

The app is crashing on login when the user holds community airdropped tokens.

Here is a test DB with all the setup:
https://drive.google.com/drive/folders/1QdAQOUhDGcjzAzWh0UlDL-apEQspsqaE?usp=sharing
Password: aaaaaaaaaa

Full stack trace: https://drive.google.com/file/d/1FjO03JdY-v_KosNq2fxn_Cx54L0IjdNu/view?usp=sharing
```
* thread #56, stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x000000010ac9b790 libstatus.dylib`github.com/status-im/status-go/services/ext.(*Service).FetchNFTMetadata + 32
    frame #1: 0x000000010ab539c8 libstatus.dylib`github.com/status-im/status-go/services/wallet/collectibles.(*Manager).processAssets + 760
    frame #2: 0x000000010ab539c8 libstatus.dylib`github.com/status-im/status-go/services/wallet/collectibles.(*Manager).processAssets + 760
    frame #3: 0x000000010ab52f08 libstatus.dylib`github.com/status-im/status-go/services/wallet/collectibles.(*Manager).FetchAllAssetsByOwner + 152
    frame #4: 0x000000010cd2e360 libstatus.dylib`golang.org/x/text/encoding/korean.encode5 + 544
```

## Steps to reproduce
1. Create a community
2. Mint a token and airdrop it to a member
3. Open the app and login with the member account

#### Expected behavior
App doesn't crash
#### Actual behavior
App is crashing
### Additional Information

- Status desktop version: Master:
c47140a4064c9a6837df6ff2a4a56b54cf812003 [c47140a40]
- Operating System: MacOS

**Comment by dlipicar** [comment]
ugh not again... will check it out

**Comment by dlipicar** [comment]
PR with fix up. Thanks @alexjba for the detailed report and the resources! Made fixing this much easier.
