### ISSUE TITLE
Keycard -> Migrate account from Keycard to Status: keycard modal can't be closed

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11260]
### Description

1. create account with keycard
2. open settings
3. open keycard
4. click Migrate account from Keycard to Status
5. click View wallet

As result, the keycard modal is blocking main window because it can't be closed

<img width="1424" alt="Screenshot 2023-06-27 at 11 31 30" src="https://github.com/status-im/status-desktop/assets/82375995/603b84ee-a33d-4d2d-9dee-4d29899cb4ba">

https://github.com/status-im/status-desktop/assets/82375995/01aa9774-c256-45ac-adcb-799233aad1ab

**Comment by alaibe** [comment]
@anastasiyaig Can you confirm it is still happening? We cannot reproduce

**Comment by anastasiyaig** [comment]
i will check @alaibe , thanks for heads up
