### ISSUE TITLE
Biometrics prompt is shown after restarting the app even it was not enabled

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11261]
### Description

1. create new account (on mac)
2. do not enable biometrics (use password)
3. log in
4. restart the app

As result, the prompt for biometrics is shown

<img width="1440" alt="Screenshot 2023-06-27 at 11 45 18" src="https://github.com/status-im/status-desktop/assets/82375995/65fee62e-36ab-4bf2-b16b-ee4c749ad1d0">

**Comment by anastasiyaig** [comment]
@jrainville it is not a blocker at all, but really annoying , so would be nice to fix it some day soon

**Comment by anastasiyaig** [comment]
@jrainville can we put some effort in it? We moved further with autotests and they are failing because of this prompt showing up here and there

**Comment by anastasiyaig** [comment]
@Valentina1133 @StateOf-Vlado for your reference

**Comment by anastasiyaig** [comment]
yes, all the time

**Comment by MishkaRogachev** [comment]
@anastasiyaig this is the case, right?

https://github.com/status-im/status-desktop/assets/2522130/9099719c-0acb-42c6-b66a-f0472a953802

It happens after restore, if even biometrics login is disabled. But it happens after the login, what is superweird

**Comment by anastasiyaig** [comment]
yes exactly
