### ISSUE TITLE
DB migration has bigger priority than incorrect password

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#11274]
# Bug Report

## Steps to reproduce

* Have v3 database, run on code that migrates to v4. 
* Try to login with incorrect passowrd

#### Expected behavior

Error message that migration from v3 to v4 failed

#### Actual behavior

Wrong password error is displayed.

### Additional Information

- Status desktop version: master
- Operating System: Mac

**Comment by caybro** [comment]
CC @alexjba
