### ISSUE TITLE
[Community Overview] Analyse community overview requirements

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11278]
### Description

[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?type=design&node-id=31171-627948&mode=design&t=KdZvsHyI2jrla6nn-0)

Analyse the new community overview requirements and create the needed tasks.

**Comment by caybro** [comment]
@alexjba see https://github.com/status-im/status-desktop/issues/11152

**Comment by alexjba** [comment]
This is the Epic for Community Overview:
https://github.com/status-im/status-desktop/issues/11319
