### ISSUE TITLE
Desktop app crashes randomly on Mac M2

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-desktop#11282]
# Bug Report
Status desktop app is crashing randomly on my Macbook Pro M2. 

## Description

The crash occured multiple times now, 3-4 times in last 2 days. I cannot pinpoint a specific action that is triggering it. 
Sometimes, when i am scrolling through messages in channel, or sometimes when it is just in the background.

## Steps to reproduce

Sometimes, when i am scrolling through messages in channel, or sometimes when it is just in the background.

#### Expected behavior
Desktop app should not crash. 

#### Actual behavior
Crashes randomly.
### Additional Information
Attaching crash report as shown my MacOS for reference. 
[status-desktop-crash-mac-M2.txt](https://github.com/status-im/status-desktop/files/11888528/status-desktop-crash-mac-M2.txt)

- Status desktop version:  0.12.0
- Operating System: MacOS Ventura 13.4 (22F66)

**Comment by iurimatias** [comment]
closed as old, likely ok now as far as we can tell
