### ISSUE TITLE
UX: Can't scroll view in app unless cursor is scrollable area

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#11285]
The title of this issue sounds like a non-issue and I apologize as I couldn't come up with a better one.
The issue is rather that the scrollable area is way smaller in width than what one would expect.

Here's what I'm referring to:

Look at the screenshot below and notice how there's most likely more UI component in the view so the form can be completed (I've assumed that because there was no visible submit button anywhere).

![Screenshot from 2023-06-28 11-06-41](https://github.com/status-im/status-desktop/assets/445106/53364d46-4d8f-4093-ba24-b25a2a018bc7)

What you can't see on the screenshot, is that I was trying to scroll down with my mouse but nothing was happening.
First I thought it was a layout issue, but then I noticed, as soon as I move the mouse further left somewhere below the tab buttons, scrolling works.

What's happening here is that the scrollable area is only as wide as the tabbed content, resulting in bad UX where users are unable to scroll in the app unless they are explicitly putting the cursor into that much smaller scroll area.

I suggest we either make the scrollable area as wide as the right panel, or somehow register a scroll handler on that right panel.
Whatever works, so that the outcome is:

**No matter where the cursor is in that right main panel, scrolling should work if there's more content that didn't fit into the viewport.**

Part of this issue should also to check other places in the app where this happens. This is most likely not only happening on the screen shown in the screenshot.

**Comment by caybro** [comment]
Yeah, I've done that for the Settings already; might as well do it here. The whole community settings panel(s) will undergo some changes and refactorings so definitely something to keep in mind. That said, there's still (and will be) one major annoyance: scrolling while inside a multiline text field (or anything that includes a `Flickable`) is simply never going to work - that is a Qt bug

**Comment by micieslak** [comment]
Will be done along with https://github.com/status-im/status-desktop/issues/11177
