### ISSUE TITLE
Airdrop section of deployed NFT doesn't seem to apply darkmode

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#11289]
After trying to deploy an NFT and viewing it in Desktop, I've noticed the "Airdrop" section doesn't seem to look well in darkmode:

![Screenshot from 2023-06-28 11-50-39](https://github.com/status-im/status-desktop/assets/445106/c6bf7a39-76c5-4745-9876-94c556455f21)

Also, when clicking that "Airdrop" button, I see a green that look slike this:

![Screenshot from 2023-06-28 11-51-02](https://github.com/status-im/status-desktop/assets/445106/15eb2699-4718-4c01-bd21-d1bf40f5cd98)

That "fee" section looks a bit too black to my eyes, so looks like this is not using the correct color either.

**Comment by caybro** [comment]
Doesn't even load in storybook:

```
file:///home/ltinkl/git/status/status-desktop/ui/app/AppLayouts/Chat/views/communities/CommunityNewAirdropView.qml:26:5: Required property communityDetails was not initialized
```

**Comment by caybro** [comment]
OK, after a small fix:

![image](https://github.com/status-im/status-desktop/assets/5377645/8371d5e1-7ec8-4219-8e38-7181c1eda804)


Things get definitely a bit too dark here :)
