### ISSUE TITLE
Revisit character set usage (ASCII/Latin1/UTF-8) in description fields

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#11307]
# Bug Report

For various reasons (safety/security/length) we limit our users in what kind of characters they are able to enter in description fields throughout the app (community, group chat, tokens, etc.). We have several regexes for this purpose at the moment:

```qml
    readonly property QtObject regularExpressions: QtObject {
        readonly property var alphanumerical: /^$|^[a-zA-Z0-9]+$/
        readonly property var alphanumericalExpanded: /^$|^[a-zA-Z0-9\-_ ]+$/
        readonly property var alphanumericalWithSpace: /^$|^[a-zA-Z0-9\s]+$/
        readonly property var asciiPrintable:         /^$|^[!-~]+$/
        readonly property var ascii:                  /^$|^[\x00-\x7F]+$/
        readonly property var capitalOnly: /^$|^[A-Z]+$/
        readonly property var numerical: /^$|^[0-9]+$/
    }
```

Clarify/review their usage and possibly be less restrictive for the said "description" fields. The goal is to allow `ascii`, that is 7-bit plain text, w/o control characters (cf https://www.rapidtables.com/code/text/ascii-table.html). Currently is it impossible to enter e.g. any punctuation:

![image](https://github.com/status-im/status-desktop/assets/5377645/2d2407c6-a79d-4c47-8974-75b102113563)

**Comment by alexandraB99** [comment]
following

**Comment by felicio** [comment]
> Any comments or amendments to this @John-44 @felicio ?

The latest info that I got is for the allowed character class to be exactly `[A-Za-z0-9_-.\u0020]`, and that's **both in display names and description**.

I also remember asking for an issue to track implementation of this limitation in https://github.com/status-im/status-desktop/issues/6032#issuecomment-1406614163. Please, can I track this then for that reason?

**Comment by felicio** [comment]
Hi @caybro, I just had a look at the commit closing this issue and wanted to note that while the above mentioned character class was complete, I think it should vary per "use case". Maybe listing it could help:

- Profile display name
    - Chars: [A-Za-z0-9_-.\u0020]
    - Exception: The dot only in .eth and if verified
    - Correct: devnull.eth; Dev null; dev-null; etc.
    - Incorrect: devnull.com
- Profile bio
    - Chars: [A-Za-z0-9_-.\u0020]
    - Correct: This is Dev Null
    - Incorrect: This is @devnull
- Profile nickname
    - Chars: [A-Za-z0-9_-\u0020]
    - Correct: Var Log
    - Incorrect var.log
- Community name
    - Chars: [A-Za-z0-9_-\u0020]
    - Correct: My community; My-community_
    - Incorrect: community.eth
- Community description
    - Chars: [A-Za-z0-9_-.\u0020]
    - Correct: This is my community.
    - Incorrect: This, is my community
- Channel category name 
    - Chars: [A-Za-z0-9\u0020]
    - Correct: General
    - Incorrect General-1; General.eth
- Channel name
    - Chars: [a-z0-9-]
    - Correct: foo-bar
    - Incorrect: Foo-bar
- Channel description
    - Chars: [A-Za-z0-9_-.\u0020]
    - Correct: About this
    - Incorrect: Rules: mention @ here

Also, after seeing some more designs:

- Group chat name
    - Chars: [A-Za-z0-9_-,'\u0020]
    - Designs
        - https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1801-408488&mode=design&t=To1Af31sPAKyNW5N-4
        - https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=7026-529039&mode=design&t=To1Af31sPAKyNW5N-4
    - Correct: Dev's meeting; Dev, Null, Var and log
    - Incorrect: Dev+Null

Finally, the "Only letters, numbers, underscores, whitespaces and hyphens allowed" error message would be outdated too.

Cc @John-44 for approval

**Comment by caybro** [comment]
> 



> Hi @caybro, I just had a look at the commit closing this issue and wanted to note that while the above mentioned character class was complete, I think it should vary per "use case". Maybe listing it could help:
> 
> * Profile display name
>   
>   * Chars: [A-Za-z0-9_-.\u0020]
>   * Exception: The dot only in .eth and if verified
>   * Correct: devnull.eth; Dev null; dev-null; etc.
>   * Incorrect: devnull.com
> * Profile bio
>   
>   * Chars: [A-Za-z0-9_-.\u0020]
>   * Correct: This is Dev Null
>   * Incorrect: This is @devnull
> * Profile nickname
>   
>   * Chars: [A-Za-z0-9_-\u0020]
>   * Correct: Var Log
>   * Incorrect var.log
> * Community name
>   
>   * Chars: [A-Za-z0-9_-\u0020]
>   * Correct: My community; My-community_
>   * Incorrect: community.eth
> * Community description
>   
>   * Chars: [A-Za-z0-9_-.\u0020]
>   * Correct: This is my community.
>   * Incorrect: This, is my community
> * Channel category name
>   
>   * Chars: [A-Za-z0-9\u0020]
>   * Correct: General
>   * Incorrect General-1; General.eth
> * Channel name
>   
>   * Chars: [a-z0-9-]
>   * Correct: foo-bar
>   * Incorrect: Foo-bar
> * Channel description
>   
>   * Chars: [A-Za-z0-9_-.\u0020]
>   * Correct: About this
>   * Incorrect: Rules: mention @ here
> 
> Also, after seeing some more designs:
> 
> * Group chat name
>   
>   * Chars: [A-Za-z0-9_-,'\u0020]
>   * Designs
>     
>     * https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1801-408488&mode=design&t=To1Af31sPAKyNW5N-4
>     * https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=7026-529039&mode=design&t=To1Af31sPAKyNW5N-4
>   * Correct: Dev's meeting; Dev, Null, Var and log
>   * Incorrect: Dev+Null
> 
> Finally, the "Only letters, numbers, underscores, whitespaces and hyphens allowed" error message would be outdated too.
> 
> Cc @John-44 for approval

Great, thanks for the writeup and complete specs :) While we have some additional validators in place already (like for the profile display name not containing `.eth`), many are definitely missing and needs a second round of fixes.

I'll reopen the issue and will have a second look when @John-44 approves

One thing I find odd is that there are different rules for a `channel name` and a `group chat name` (they are effectively the same thing in the UI)

**Comment by caybro** [comment]
Or that "profile bio" cannot contain e.g. a semicolon (`;`) or a slash (`/`) for citing a website URL?

**Comment by felicio** [comment]
> I find odd is that there are different rules

Afaik, there aren't any this comprehensive 🙂. The list above was just my shot at it based on what I've seen, heard or found sensible.

**Comment by caybro** [comment]
I guess we can move this for after 0.15 if needed

**Comment by alexandraB99** [comment]
@John-44 can we close this task - is what we have good enough for now? please let us know if there is anything else needed here. cc @caybro

**Comment by John-44** [comment]
> @John-44 can we close this task - is what we have good enough for now? please let us know if there is anything else needed here. cc @caybro

If nobody thinks anything else is required then we can close this task
