### ISSUE TITLE
App crashes when `collectible` tab is selected in airdrop view of a community with already minted collectibles

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11309]
# Bug Report

## Description

App crashes when `collectible` tab is selected in airdrop view of a community with some minted collectibles.

## Steps to reproduce
- Go to `airdrop` section of a community with some tokens already minted.
- New airdrop / select `collectibles` tab.

#### Expected behavior
Collectibles tab is selected and user can choose one of the community minted tokens.

#### Actual behavior
Crash:

https://github.com/status-im/status-desktop/assets/97019400/06d43d37-c9e1-4cf1-8142-3ff6601c8411

### Additional Information

- Status desktop version: master 67929c8e0314bd9e9081fefbbe15c5ca8210fb79
- Operating System: macOS Monterey 12.3.1

**Comment by caybro** [comment]
I think this has been fixed already in master?

**Comment by noeliaSD** [comment]
> I think this has been fixed already in master?

It seems yes, I tried with the last master we have right now and it's reproducible 100%. @alexjba could also reproduce it.
