### ISSUE TITLE
[Community Overview] Implement Community Overview Heading

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11320]
[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?node-id=31229%3A627222&mode=dev)

- [ ] Remove Community logo
- [ ] Align the `Edit Community` button
- [ ] 64px paddings L/R of content (this is for the entire screen)

￼
<img width="695" alt="Pasted Graphic 2" src="https://github.com/status-im/status-desktop/assets/47811206/e7daf4ec-4fa1-4993-a98d-f2be2e9ce001">

**Comment by anastasiyaig** [comment]
same here, please add milestone so the task wont be forgotten @alexjba @alexandraB99 @iurimatias
