### ISSUE TITLE
[Community Overview] Update Edit Community based on the new design

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11323]
[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?node-id=3132%3A383870&mode=dev)

### Design changes
- Align title and subtitles to the left

- ~Change Pencil icon to Plus icon on Community logo  ￼~
<img width="65" alt="image" src="https://github.com/status-im/status-desktop/assets/47811206/90b55404-bf00-434f-be5e-1a4db4754ab3">

- Add max size info of the community banner
<img width="563" alt="Screenshot 2023-06-29 at 11 30 13" src="https://github.com/status-im/status-desktop/assets/47811206/a78491d3-e0fb-4621-873b-db365ec1001d">

- Align tags to the left
<img width="265" alt="image" src="https://github.com/status-im/status-desktop/assets/47811206/1cfae363-1a99-4e69-8120-2ff6dd40ea34">

- Increase height of Dialog for new members to 482
- Update paddings according to design
- 
### Text changes
- Name your community -> Community name
- Give it a short description -> Description
- Wide aspect ratio is optimal -> Optimal aspect ratio 16:9
- Community introduction and rules -> Dialog for new members

### Review page to pixel-perfect items alignment and size

**Comment by alexjba** [comment]
@benjthayer Should we also update the design of `Create community popup`? It's almost identical to Edit community.

<img width="1725" alt="Screenshot 2023-06-29 at 13 44 22" src="https://github.com/status-im/status-desktop/assets/47811206/4ffbd79d-baa6-4205-be67-ac2648cf72a9">

**Comment by anastasiyaig** [comment]
@alexjba @alexandraB99 is it for 0.14? please add a milestone , this task is not propagating to any board because of missing milestone

**Comment by alexjba** [comment]
@anastasiyaig WDYM?
It's added 🤔 
@[alexjba](https://github.com/alexjba) alexjba added this to the [0.14](https://github.com/status-im/status-desktop/milestone/57) milestone [2 days ago](https://github.com/status-im/status-desktop/issues/11323#event-9674221535)

**Comment by anastasiyaig** [comment]
@alexjba did not show up to me for some reason, sorey!

**Comment by John-44** [comment]
@alexjba “max size” should **be removed**, not added above the community banner

**Comment by John-44** [comment]
@alexjba but while we are touching this (create community and edit community) we should reduce the max number of community tags from 4 to 3. I think this *might* be tracked in a separate issue somewhere

**Comment by anastasiyaig** [comment]
logged there @John-44 @alexjba https://github.com/status-im/status-desktop/issues/11417
