### ISSUE TITLE
Wallet -> Can't send from L2 to L1: Fail with error 'L2_AMM_W: Bonder fee cannot exceed amount'

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11328]
### Description

```
Fail with error 'L2_AMM_W: Bonder fee cannot exceed amount'
```

https://goerli.arbiscan.io//tx//0xfd23b7ed6e2ecfa38edfc292002402c35db2df722bbe9af185af2859dabe2ac4
https://goerli-optimism.etherscan.io/tx/0x7988b920ed26fe242017ec3b244539ef927dc950d8f465c5f1e6deaef7ae1111

<img width="1312" alt="Screenshot 2023-06-29 at 14 35 13" src="https://github.com/status-im/status-desktop/assets/82375995/c2b95873-b0a2-486b-b544-acb5598f9242">

<img width="1312" alt="Screenshot 2023-06-29 at 14 30 18" src="https://github.com/status-im/status-desktop/assets/82375995/a504170e-84c1-4449-9fe4-d5e209f0ba80">

**Comment by alaibe** [comment]
@anastasiyaig I will prevent to load that route but the reason is that you send a lower amount than the bonder fees
