### ISSUE TITLE
[Community Overview] Edit Community - Add "Block users with duplicate usernames"option

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11324]
[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?node-id=3132%3A384437&mode=dev)

- Add “Block users with duplicate usernames” checkbox 
<img width="282" alt="Screenshot 2023-06-29 at 11 31 57" src="https://github.com/status-im/status-desktop/assets/47811206/30e10761-078d-4920-9c5b-62339f9784ff">

**Comment by alexjba** [comment]
@jrainville Do we have backend support for this community settings?

**Comment by alexjba** [comment]
@John-44 is this for 0.14?

**Comment by John-44** [comment]
> @John-44 is this for 0.14?

Well spotted, no it isn’t it should have its milestones tag removed and tagged as low priority. We won’t want to work around n this until next year, if ever. cc’ing @jrainville @iurimatias

**Comment by John-44** [comment]
we might entirely remove this from the designs

**Comment by alexandraB99** [comment]
> we might entirely remove this from the designs

@John-44 can you confirm this? cc @benjthayer

**Comment by John-44** [comment]
> > we might entirely remove this from the designs
> 
> @John-44 can you confirm this? cc @benjthayer

Yes, this functionality has been removed, so no need to implement and this issue should be closed
