### ISSUE TITLE
Minting - User not informed of failure to mint on Arbitrum Goerli

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11338]
# Bug Report

## Description

During minting, after signing the transaction in the final step the process failed. The Pokt error banner was displayed but the user was not informed that the minting did not take place. They were returned to the minting welcome screen with no other info or toast.

## Steps to reproduce

Attempt to mint a token on using Arb testnet.
Sign transaction
User is returned to the minting welcome screen, the pokt error banner is displayed temporarily, no toast or other information is provided.

Console

```

ERR 2023-06-29 16:59:02.613+01:00 Error deploying collectibles               topics="community-tokens-service" tid=5732788 file=service.nim:336 message="\nstatus-go error [methodName:collectibles_deploy, code:-32000, 
message:fallback failed with \'intrinsic gas too low\'. run error was \'intrinsic gas too low\' ]\n"
```

#### Expected behavior
Minting screen with error state for the collectible and toast.

### Additional Information

- Status desktop version: 0.13RC5
- Operating System: Mac

**Comment by jrainville** [comment]
> @iurimatias @jrainville it is somethng that we forgot to implement? can we handle it in 0.14?

Sounds like a bug about gas. I'll get this fixed in 0.14
