### ISSUE TITLE
Keycard: UI of popups opened from Keycard settings is too narrow

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11335]
# Bug Report

## Description

Within the "Create a new Keycard account with a new seed phrase" flow and other similar flows within Keycard settings the popup UI is not wide enough for the components.

![image](https://github.com/status-im/status-desktop/assets/50769329/8ae67448-dce8-4461-8386-105199564842)
![image](https://github.com/status-im/status-desktop/assets/50769329/1197ff46-e20b-4699-871b-07223cbfc6f0)

### Additional Information

- Status desktop version: 0.13RC5
- Operating System: Mac

**Comment by caybro** [comment]
Looks more like: double margin on the left, none on the right side

**Comment by caybro** [comment]
@alexjba same popup here? https://github.com/status-im/status-desktop/issues/11420
