### ISSUE TITLE
Remove old transaction module

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#11380]
Started by @dlipicar here https://github.com/status-im/status-desktop/pull/11339

**Comment by stefandunca** [comment]
@anastasiyaig, the following change removes the old history fetching that was still used in Send popup. This impacts the implementation of the activity filtering and recent activity in send: https://github.com/status-im/status-desktop/pull/11339
Please help and take a look that things are as expected and nothing has changed in behaviour from master.
