### ISSUE TITLE
Community -> Download a picture in channel: "Open" native dialog opens instead of "Save"

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11391]
### Description

1. send a picture in a channel of community
2. open this picture
3. click Download

As result, the dialog opened is "Open" dialog, but should be "Save" instead

**Version:** Status Master build 2603, https://ci.infra.status.im/job/status-desktop/job/master/2603/, commit `e5e5229e6`

https://github.com/status-im/status-desktop/assets/82375995/90a671ff-62a2-4839-9b1f-365382b45b83

**Comment by isbees** [comment]
Hi, I would like to help with this task. I assume I just download the app and try to send any picture, correct?

**Comment by anastasiyaig** [comment]
yes, create dummy community and send any picture to any channel, then right click it and select download

**Comment by caybro** [comment]
@anastasiyaig this is actually correct and looks like an OS dependent glitch; in fact the button should read "Select directory" but for some reason, the macOS dialog uses "Open". We have no way to control that
