### ISSUE TITLE
Overview balance incorrect

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#11397]
![image](https://github.com/status-im/status-desktop/assets/491074/615035f1-028b-4b5a-bdfd-d11127c2d181)

It should be 999,90B

**Comment by anastasiyaig** [comment]
@alaibe can it be because the last one is watch only (and we miss the icon)? And `show watch only` is off?

**Comment by alaibe** [comment]
Still have a big balance in non watch only account, it should still shows the B no?

**Comment by anastasiyaig** [comment]
yes, it should in this case :(
