### ISSUE TITLE
Communities: Intro/outro msg can be removed via community edit form

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11416]
# Bug Report

## Description

When creating community, intro/outro messages are required. But later when editing community changes can be saved after removing intro/outro messages.

https://github.com/status-im/status-desktop/assets/20650004/b9eac129-d47b-4db2-900f-3c19abdff1c1

## Steps to reproduce

Go to community settings, overview, edit community, remove intro/outro messags, save changes

#### Expected behavior

It shouldn't be possible to save changes when no intro/outro messages

#### Actual behavior

Edit form can be removed when no intro/outro messages

**Comment by shinnok** [comment]
Any idea why the screencast video is not playable here?

**Comment by jrainville** [comment]
> Any idea why the screencast video is not playable here?

It works for me.

It shows someone editing a community and leaving the community bio empty.

**Comment by caybro** [comment]
> Any idea why the screencast video is not playable here?

You likely don't have the required video codec installed

**Comment by shinnok** [comment]
@micieslak I cannot reproduce the behavior on current **master**:b3c74de23, with an existing or a new community and even trying to fiddle with the other fields, after editing "Dialog for new members", the **Save Changes** button behaves correctly for me.

This rule, _should_ enforce at least 1 character in the editor:

https://github.com/status-im/status-desktop/blob/95f6350e8ff6a1d66f6acbfcd47c193389a4771d/ui/app/AppLayouts/Communities/controls/IntroMessageInput.qml#L23-L25

Could you kindly trying to reproduce on your end and see if you can remember the precise leading steps you took?

https://github.com/status-im/status-desktop/assets/544446/1701302f-e22b-4f69-9a96-442d2616404d

**Comment by jrainville** [comment]
No longer reproducible
