### ISSUE TITLE
For dev builds the QtWebEngine directory should be inside the data directory.

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/status-desktop#1141]
The reason for doing this is that we don't really want dev builds to crossover in usage of caches, cookies, etc. that are created by a packaged build in the platform-specific path in the user's home directory, e.g. `~/Library/Application Support/Status` on macOS.

We can detect that env var `NIM_STATUS_CLIENT_DEV` is not empty, as we do for other purposes, and when it's not empty the path-related setters [documented here](https://doc.qt.io/qt-5/qwebengineprofile.html#details) can be used to specify that the persistent storage and cache paths are inside the untracked `data` directory at the top-level of the repo.

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5747
