### ISSUE TITLE
Community overview: limit the number of tags to 3

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11417]
### Description

https://github.com/status-im/status-desktop/issues/11323#issuecomment-1621307206

![image](https://github.com/status-im/status-desktop/assets/82375995/4d6de703-53d6-49e1-8f96-44a22b0de7ef)

**Comment by anastasiyaig** [comment]
@alexjba @alexandraB99 i added this task based on https://github.com/status-im/status-desktop/issues/11323#issuecomment-1621307206

**Comment by alexjba** [comment]
fixed by https://github.com/status-im/status-desktop/pull/11341
