### ISSUE TITLE
Add status-go version to About screen

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11424]
### Description

So QAs and users can tell which version is used in case of incompatibilities. @anastasiyaig asked for it.

### Acceptance Criteria

- status-go version (commit version works but tag is better as it's what mobile uses) is shown in the about page

**Comment by caybro** [comment]
Tentative WIP screenshot (working, actual version displayed):
![image](https://github.com/status-im/status-desktop/assets/5377645/23834beb-4cf6-4847-9f71-e7bc006dc21e)

**Comment by anastasiyaig** [comment]
thanks @caybro :) ❤️
