### ISSUE TITLE
[Community Permissions] Extend collectibles model with supply amount

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11437]
### Description
We need to identify the unique collectibles in Community permissions (holdings dropdown) and the current model does not provide this info.
Please see the discussion here: https://github.com/status-im/status-desktop/issues/10546

The purpose of this task is to extend the current model with `supply` amount.

**Comment by alexjba** [comment]
@endulab I've created this task based on our discussions. 
Do you think it's doable for 0.14?

**Comment by jrainville** [comment]
@endulab is this already done? I feel like your latest PR does something similar
