### ISSUE TITLE
Fix missing message header (timestamp + user name) in the case of a bot send

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11444]
# Bug Report

## Description

Issue reported originally here: https://www.notion.so/Timestamp-StatusApp-notifications-37d053850ea949f3bd8e098461985a52

It happens to the people at Spiffworkflow.

The messages don't have the message header even if they are send with more than 15 minutes interval.

Their frontend code to send messages is here: https://github.com/status-im/spiffworkflow-connector/blob/master/connectors/connector-waku/connector_waku/commands/sendMessage.py

They use a Dockerfile wrapping status-go for the backend: https://github.com/status-im/spiffworkflow-connector/blob/master/connectors/connector-waku/Dockerfile

## Steps to reproduce

Use the code above to send a message in a group chat (that's where they sent their messages, but a community probably works too)
See that there is not message header

#### Expected behavior

Shows the message header with timestamp and username with usual rules (no repeat if less than X minutes)

#### Actual behavior

Missing message header.

**Comment by harmeet-status** [comment]
This issue was experienced with version 0.12

**Comment by jrainville** [comment]
@harmeet-status I see in the screenshot of this issue https://github.com/status-im/status-desktop/issues/11483  that the timestamp and other message header elements are there, so maybe it's fixed in 0.13?

**Comment by jrainville** [comment]
Seems like it's fixed in 0.13. Feel free to reopen if it still happens

**Comment by harmeet-status** [comment]
@jrainville this was fixed by @MishkaRogachev
