### ISSUE TITLE
Communities: Channel/Category regression

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#11452]
Version: 0.13.0-rc.6
OS: Windows 10

***
Preconditions: Download 0.13 - rc.6 and restore Status account from seed phrase 

<ins>Steps to reproduce:</ins>

1. Navigate to the internal Status community

<ins>What currently incorrectly happens:</ins>

2. The Status channels are not categorised and are in seemingly a random order. The categories still exist but are sitting at the bottom of the secondary nav and have no channels. 

<ins>What is supposed to happen:</ins>

2. Channels should be categorised :)    

<ins>Other information</ins>

https://github.com/status-im/status-desktop/assets/124154641/b5bdfe9f-bced-4fe5-95ea-72533f85b120

**Comment by jrainville** [comment]
I just tried to reproduce twice with the shared account that is part of the Status community and I couldn't reproduce.

I know it ended up fixing itself for you, so maybe it's was just a random UI issue.

Is there still a bug with SortFilterProxy where some weird stuff can happen sometimes? cc @alexandraB99 @alexjba @caybro

**Comment by caybro** [comment]
> I just tried to reproduce twice with the shared account that is part of the Status community and I couldn't reproduce.
> 
> I know it ended up fixing itself for you, so maybe it's was just a random UI issue.
> 
> Is there still a bug with SortFilterProxy where some weird stuff can happen sometimes? cc @alexandraB99 @alexjba @caybro

No idea, I really can't reproduce this one (and I've restored from seed phrase twice recently)

**Comment by lukaszso** [comment]
Cannot reproduce. Tried multiple times on Windows and the categories are displayed correctly.
