### ISSUE TITLE
Community regression: Channels stay highlighted when they are not selected 

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#11459]
Version: 0.13.0-rc.6
OS: Windows 10

***
Preconditions: Download 0.13 - rc.6 and restore Status account from seed phrase. Navigate to a community the user is the owner of. 

<ins>Steps to reproduce:</ins>

1. Click on a channel and move it up a little bit without changing the channel position. 

<ins>What currently incorrectly happens:</ins>

2. The channel above the channel that was selected and moved becomes highlighted.  
The channel that was highlighted remains highlighted when a mouse is not hovering over it and after it is no longer selected. You can do this to multiple channels. 
When a user clicks and drags a channel across the previously selected and highlighted channel(s), the highlight disappears. 

<ins>What is supposed to happen:</ins>

2. Channels should only be highlighted when:
- a mouse is hovering over it (light grey)
- the channel has been selected (slightly darker grey)

<ins>Other information</ins>
This screencast better demonstrates the bug -  

https://github.com/status-im/status-desktop/assets/124154641/b9bbe5b9-2567-412f-8802-7e1982d0136e

&nbsp;

**Comment by jrainville** [comment]
@caybro you put the messenger-team label, but I'm not sure if that's correct. This seems like a UI issue. The dragged state probably doesn't remove itself correctly or something?
