### ISSUE TITLE
Replace Mainnet with Optimism as default network selection 

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11467]
Given the generally cheaper fees, Optimism should be presented as the default network in dropdowns where the user can make a network selection. For example, when the user goes to mint the Owner and TokenMaster tokens and when they proceed to mint any Community collectible or asset, Optimism should be automatically shown in the network selector dropdown.

Currently the default shown is Mainnet (so this should be replaced with Optimism).

<img width="1087" alt="Screenshot 2023-07-10 at 11 04 56" src="https://github.com/status-im/status-desktop/assets/110033914/73f3aa74-79c8-4bfd-8806-6aa12d9be068">

cc @John-44 @jrainville

**Comment by caybro** [comment]
CC @noeliaSD @micieslak here too, I guess

**Comment by John-44** [comment]
Optimism should be the default network selection for all token functionality that contains a network selector in the Community Admin area
