### ISSUE TITLE
Disabling Community token related functionality while in Testnet mode

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11468]
While in Testnet mode, the user should not be able to access the Community admin area. This helps prevent the user from deploying and interacting with Community smart contracts while in this mode.

Designs have been created showing what the Community founder, Owner (if Owner token minted), TokenMaster (if TokenMaster token minted and airdropped) and admin should see when they launch the Community admin area.

- The entire community admin nav is disabled
- The body area is taken over with a panel explaining that the admin area is disabled with a CTA to turn off Testnet mode
- Testnet mode can be turned off either via the above CTA or the omnipresent orange Testnet banner
- If Testnet is turned off while in this view, the UI will refresh and show the user their last visited admin area location with the orange Testnet banner removed

Figma designs:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=34976-596521&mode=design&t=7HSjl1pkHU0oNfhu-4

<img width="1440" alt="Testnet1" src="https://github.com/status-im/status-desktop/assets/110033914/073a60f5-7e48-43ef-afef-e0c38d9f26a5">

<img width="1440" alt="Testnet2" src="https://github.com/status-im/status-desktop/assets/110033914/3529c6d0-f512-42d4-82d9-527a8e0b6750">

<img width="1440" alt="Testnet3" src="https://github.com/status-im/status-desktop/assets/110033914/9bb7f2d3-bbcf-4906-81a2-f6ce8849547b">

**Comment by caybro** [comment]
This is one most probably going to either @noeliaSD or @micieslak

**Comment by benjthayer** [comment]
@caybro @John-44 @noeliaSD @jrainville apologies, please hold off on this issue for now. After a recent discussion with Patryk and John, we are going to simplify this somewhat by disabling the entire Community admin area when the Owner, TokenMaster or Admin is in testnet mode. New designs incoming...
