### ISSUE TITLE
UI elements relating to the airdropping of the Owner token added to mint Owner token flows

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11473]
When the Community Owner token is minted, the smart contract also airdrops the Owner token to the Community founder. 

A couple of additional states have been added to the mint Owner token flows to represent the toasts and activity items that should be shown for the airdrop of the Owner token at various points in this process (as broken down below):

1) While airdrop Tx is in progress, the Community founder should see a toast reading `Airdropping [Community name] Owner token to you` with a link to view on the relevant chain explorer.

Figma link:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=34794-590400&mode=design&t=H9WXPVH15Vuk0mSS-4

<img width="1440" alt="1" src="https://github.com/status-im/status-desktop/assets/110033914/49e9cc6c-553e-4805-ae41-d65caaaf7218">

-

2) When the airdrop is successful, we should update the toast (or show a new toast if the in progress toast has been dismissed already) saying `[Community name] Owner token airdropped to you`

Figma link:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=34794-590597&mode=design&t=H9WXPVH15Vuk0mSS-4

<img width="1440" alt="2" src="https://github.com/status-im/status-desktop/assets/110033914/932a361e-e23b-4b39-a36e-17fa2d356ea6">

-

3) When the airdrop is successful, the user's designated account for the airdrop should show a `Received` collectible activity item.

Figma link:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=34794-591315&mode=design&t=H9WXPVH15Vuk0mSS-4

<img width="1188" alt="3" src="https://github.com/status-im/status-desktop/assets/110033914/8c2b1afa-6b0c-41fc-acc4-6ccd0f62d735">

cc @noeliaSD

**Comment by endulab** [comment]
Points 1. and 2. are already done in pr https://github.com/status-im/status-desktop/pull/11857
Point 3. - this is a question to wallet team. Ping @dlipicar

**Comment by jrainville** [comment]
Closing as this was fixed in https://github.com/status-im/status-desktop/pull/11857 and the remaining part is in another issue https://github.com/status-im/status-desktop/issues/11889
