### ISSUE TITLE
Make the owner without the community private key behave like an owner (ownership transfer) 

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11478]
### Description

Second step of Owners without private key. Follow up of https://github.com/status-im/status-desktop/issues/11477

We want to support the flow where a user creates a community on a computer, then imports the same account on another computer with the same community (imports the community key), then forgets the key in the main computer.

That would make it so that the main computer remains an owner node, but not a control node.

In the previous issue, we made it so that the owner still has admin rights. In this one, we want owners to still have owner rights. That means expanding the admin events to also have owner events. So it would use the same event mechanism, but adding new events that only the node marked as owner in the member list can do.

Obviously, if the node is marked as owner, but has the community key, use the normal control node flow of using the key instead.

### Acceptance Criteria

- When an owner is no longer a control node, they should still have owner rights as per this list https://github.com/status-im/status-desktop/issues/10114

**Comment by mprakhov** [comment]
MR was merged, closing as done
