### ISSUE TITLE
bug: syncing devices with mobile does not sync chats nor contacts

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1147]
**Repro**
Advertise then sync devices with mobile. 

**Expected**
Public chats and 1-1s (maybe?) should appear as they are in mobile. Contacts should sync.

**Actual**
Public chats and 1-1s are not synced. Sometimes only one channel is synced. Contacts are not synced

**Comment by iurimatias** [comment]
can't replicate
