### ISSUE TITLE
Remotely destructing TokenMaster token - Remotely destruct, kick and ban dialogs now all feature account selection dropdown (which account to pay fees on)

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11471]
When a Community Owner kicks or bans a TokenMaster, there is a required Tx to remotely destruct that TokenMaster's TokenMaster token as well. In previous designs, the account selection dropdown for the Owner to select which account to use for the Tx (and therefore which to pay fees from) was inside of the sign Tx dialog. This dropdown (and associated error state when there are insufficient funds for the Tx) has now been moved inside the Kick / Ban dialog as shown below. This is also the case for the remotely destruct TokenMaster token dialog if the Owner's goal is to destruct the TokenMaster token without kicking/banning the TokenMaster from the Community.

Figma designs:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=34794-595580&mode=design&t=H9WXPVH15Vuk0mSS-4

<img width="600" alt="Remotely destruct" src="https://github.com/status-im/status-desktop/assets/110033914/6aa93386-dd3b-4aee-bc05-113efd61879f">

<img width="600" alt="Kick dialog" src="https://github.com/status-im/status-desktop/assets/110033914/55f2d020-8d48-46e1-86b9-9b3dbcf5d7b7">

<img width="600" alt="Ban dialog" src="https://github.com/status-im/status-desktop/assets/110033914/d243e3c9-1e09-4443-970c-032a2fa8e6c5">

<img width="600" alt="Ban dialog - insufficient funds" src="https://github.com/status-im/status-desktop/assets/110033914/0217c149-548d-409b-a614-846a76f63922">

@noeliaSD

**Comment by micieslak** [comment]
After last design changes description, figma link and screens are outdated, redefined in https://github.com/status-im/status-desktop/issues/11622
