### ISSUE TITLE
Add API to forget/remove the community private key (ownership transfer)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11475]
### Description

Add an API in status-go and Nim functions that call that API so that an owner can forget/remove the private key from their DB.

This is part of the flow where an owner would transfer ownership to someone else or to another PC. This is to make sure there is never 2 control nodes at the same time.

Just before deleting the private key, the node should update the description and remove itself as owner and send it to members. Then it deletes the key.

When another node imports the community private key, the invert happens, it imports, then updates the description, marking itself as owner (it might be already happening, but double-check).

There is one edge case where you import the key in the same account on another machine, then you have two control nodes. After that, you remove the key from one of the machine, removing yourself as owner. Then for a short while, the community would appear to have no owners. Either make it that the new control node corrects the record straight away by sending a new description with it as the owner or when the next periodic community description is published, make sure the record is set straight (that account is still the owner).

### Acceptance Criteria

- There is a status-go function and API to remove the private key, plus tests
  - by doing so, the node updates the community description and removed itself
- The new control node advertises itself as the control node
- There is Nim code to call that status-go API from the QML

**Comment by MishkaRogachev** [comment]
@jrainville want is decision about https://github.com/status-im/status-desktop/issues/11572? Should i add nim code for `removePrivateKey` call?

**Comment by jrainville** [comment]
> @jrainville want is decision about #11572? Should i add nim code for `removePrivateKey` call?

I'm not sure yet if the automatic control node switch is gonna be doable in 0.14, so you can finish the Nim part for now. It shouldn't be very long, so it can be removed later if we no longer needed it
