### ISSUE TITLE
Please add me to your contact request appears each time for a msg

### ISSUE THREAD

**Issue by harmeet-status** [status-im/status-desktop#11483]
# Bug Report

## Description

In 0.12 this issue was fixed. It would suppress contact requests for those people who are already contacts with you. However this issue is back in 0.13

FYI - we are sending a contact request each time we send a msg from SpiffWorkflow. This is just how it need to happen as we cannot keep track of if you accepted the contact request or not in Spiff, so we simplified it and said we will just send a contact request followed by a msg each time. I was told by John this would be ok, since the app should suppress contact requests if you have already added them.

Btw, we are using a Waku node to send this from SpiffWorkflow.

## Steps to reproduce

1. Login to Spiff and navigate to Set up Status App (Desktop) notifications process. This is simply a process which will send you a test notification in the Status Desktop App.
2. You will see each msg with request for contact (see photo attached)

#### Expected behaviour
Don't show the contact request, if you have already added them as a contact

#### Actual behaviour
Please add me to your contacts appears each time

### Additional Information

- Status desktop version: 0.13
- Operating System: Windows
![image](https://github.com/status-im/status-desktop/assets/104047049/82b8824c-b53d-4f3b-ba0b-0e1e4f604861)

**Comment by MishkaRogachev** [comment]
Closed with https://github.com/status-im/status-go/pull/3754
But this fix will only work for clients with updated status-go

**Comment by MishkaRogachev** [comment]
@jrainville can we close it now?
