### ISSUE TITLE
Add channel name to the token_permission_chat_list_model

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11481]
### Description

Needed for this design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=31461%3A564305&mode=dev

We need to add the channel name to the token_permission_chat_list_model. Currently, it only has the chat key.

Also check how the QML currently uses that model. I find it weird that it only has the chat key. If the QML uses a JSON function to get the channel data, then it's better to change it to actually use the channel data in the model, as using JSON is slow and also doesn't update correctly on updates.

### Acceptance Criteria

- The channel name is now part of the token_permission_chat_list_model
- The name updates if there a change

**Comment by caybro** [comment]
> If the QML uses a JSON function to get the channel data, then it's better to change it to actually use the channel data in the model, as using JSON is slow and also doesn't update correctly on updates.

@borismelnik we don't actually show it anywhere imho (yet); all we need is this `channelName` next to the key in that model (ie one more data role):
```nim
  method roleNames(self: TokenPermissionChatListModel): Table[int, string] =
    {
      ModelRole.Key.int:"key",
    }.toTable
```
