### ISSUE TITLE
Blurry icon presentation on 0.13.0-rc.6

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11485]
The marked icons in the below screenshot of the 0.13.0-rc.6 version of the app are quite blurry - looks like pixel interpolation from using PNGs perhaps. Viewed on Apple Studio Display (5120 x 2880)

<img width="1407" alt="Screenshot 2023-07-11 at 10 24 41" src="https://github.com/status-im/status-desktop/assets/110033914/5010f98a-ba22-4c36-a8b2-830cd216ab17">

**Comment by benjthayer** [comment]
On closer inspection, the following also appear blurred:

- The channel icon in the top banner (see the hash icon prefixed to `desktop` in above screenshot)
- The pinned messages icon in the top banner
- Some of the contact icons in the members pane are also blurred, while others are not

**Comment by caybro** [comment]
Most likely a redraw artifact/glitch; can you reproduce this on a fresh start of the app @benjthayer ?

**Comment by benjthayer** [comment]
Very odd! Seems to be fine after a restart! Thanks @caybro I'll keep an eye out to see if it happens again and if so log any steps to reproduce
