### ISSUE TITLE
Small change to order of account information in Wallet Settings

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11493]
Mobile designs for wallet settings are currently underway. As part of this work Alisher and John have agreed to a slight re-ordering of the account information which has now been reflected in the desktop designs also.

**The new order of account information is as follows:**

For accounts where the derivation path is known (excludes watch-only accounts and accounts imported via private key):
- Balance
- Address
- Key
- Origin
- Derivation path
- Stored

Figma example:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15410-339830&mode=design&t=H9iCBrqCjKgo29g0-4

<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/110033914/3bde7c46-1030-49e6-9bad-3b2711b62dfe">

For accounts where the derivation path is not known:
- Balance
- Address
- Key
- Origin
- Stored

Figma example:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15479-316147&mode=design&t=H9iCBrqCjKgo29g0-4

<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/110033914/f2e26a62-0873-4451-841f-5760fba9c3b0">

(NB these updates have been made in a few areas of the Wallet settings designs as a few of the different flows features the account details pages).

cc @saledjenic

**Comment by anastasiyaig** [comment]
@alaibe changing wallet settings is fun! :)

**Comment by Khushboo-dev-cpp** [comment]
Completed under https://github.com/status-im/status-desktop/pull/11562
