### ISSUE TITLE
Cannot change channels in one of my communities

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#11490]
# Bug Report

## Description

Using v0.13.0-rc.7 on macOS Ventura 13.4.

In one of the channels I've recently joined, clicking on the different channels does nothing. The channel doesn't change, no line appears in the logs, it's as if I had never clicked.

In the other community, everything works fine.

Restarting the app the first time didn't help, but the issue disappeared the second time "-.-

Upon restart, I also got a notification from a several hours old message in a new channel (`spiffworkflow`) in the Status CC community. Just a hunch, but I think there was some blocking condition there.

https://github.com/status-im/status-desktop/assets/11161531/bc17e767-0428-4919-a789-bb8e3587b450

Logs:
[app_20230711_100500.log](https://github.com/status-im/status-desktop/files/12015036/app_20230711_100500.log)

[geth.log.zip](https://github.com/status-im/status-desktop/files/12015040/geth.log.zip)

**Comment by caybro** [comment]
I believe this is fixed @igor-sirotin ?

**Comment by igor-sirotin** [comment]
What was fixed is this: https://github.com/status-im/status-desktop/issues/11616
Doesn't look related to the issue.

**Comment by dlipicar** [comment]
I haven't seen this happen again, could've been an ultra-rare corner case or something that got fixed along the way

**Comment by jrainville** [comment]
Have you been able to reproduce this @dlipicar ?

**Comment by dlipicar** [comment]
Nope, I'd close this
