### ISSUE TITLE
Minted asset hodler list remains empty after airdrop and restart

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11497]
# Bug Report

## Description
Found during https://github.com/status-im/status-desktop/pull/11353

Minted asset hodler list remains empty after airdrop and restart
![image](https://github.com/status-im/status-desktop/assets/50769329/3ab4e7fd-58af-4c80-80c5-edbde9328daf)

https://goerli.etherscan.io/token/0x8a5ec70974c88493bd2511e185b2d180ca185ac3

#### Expected behavior

List is populated with holders of the token that has been airdropped.

#### Actual behavior

List is empty.

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/11353
- Operating System: Mac

### NOTE
There is a technical limitation when displaying asset holders. We do not have a function similar to Collectibles.
Also there is no function in smart contract to iterate through owners. What we can do is to display holders from our community - for every community member we can get revealed address and check balance for this address (this idea was discussed with @John-44)
Related task: https://github.com/status-im/status-desktop/issues/11143

**Comment by noeliaSD** [comment]
@endulab did you say in the attached PR that there is already a task for this??

**Comment by endulab** [comment]
@noeliaSD I was thinking that I had a task for this, but it seems that I did not create it. Let's use this one.

**Comment by jrainville** [comment]
I changed the assignee to @MishkaRogachev because it's basically the same task as https://github.com/status-im/status-desktop/issues/11143

**Comment by MishkaRogachev** [comment]
https://github.com/status-im/status-desktop/pull/11787

**Comment by jrainville** [comment]
Fixed in #11787
