### ISSUE TITLE
Minting - Burn and self destruct pop-ups are not closed after signing

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11498]
# Bug Report

## Description

Found in https://github.com/status-im/status-desktop/pull/11353

Burn and destruct pop-ups do not close after signing transaction
This makes it difficult to click on toast link before it closes.

![image](https://github.com/status-im/status-desktop/assets/50769329/86f4ce6b-212c-464b-acf9-e3baf2af7f08)

## Steps to reproduce

Burn or destruct assets/collectible
Sign transaction
Pop-up remained open

#### Expected behavior
Pop up closes

### Additional Information

- Status desktop version:  https://github.com/status-im/status-desktop/pull/11353
- Operating System: Mac

**Comment by noeliaSD** [comment]
@alexandraB99 any of the `ui-team` members can take this!!
