### ISSUE TITLE
Chat activation issues while blocking/unblocking user

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#11505]
# Bug Report

## Description

Currently, not all required events occur during locking and unlocking a contact. The logic should already be implemented in status-go, but chat deactivation signals are not always handled correctly by the desktop app

#### Expected behavior

- When a user blocks a contact, the chat should immediately deactivate and close on ui
- All chat history should be deleted for the blocked contact
- Sending a contact request should be disabled for a blocked contact 
- When the user unblocks the contact, chat should not be activated
- After the contact is unblocked, the ability to send a contact request should be enabled
- Chat should be activated after a contact accepts a contact request

**Comment by anastasiyaig** [comment]
@MishkaRogachev there is a task in 0.15 to align block user functionality with mobile and designs, did u see it? https://github.com/status-im/status-desktop/issues/8805

**Comment by jrainville** [comment]
I'm going to close in favour of https://github.com/status-im/status-desktop/issues/8805 to not duplicate the work
