### ISSUE TITLE
bug: Crash when creating ENS from desktop

### ISSUE THREAD

**Issue by mratsim** [status-im/status-desktop#1150]
On Linux using beta.2, when trying to create a ENS from Status-Desktop

Clicking on the arrow on the right reliably crashes
![image](https://user-images.githubusercontent.com/22738317/95442485-bb101780-095b-11eb-99d5-972c1e7538a0.png)

**Comment by richard-ramos** [comment]
This has been fixed already. Please reopen if the issue still persist
