### ISSUE TITLE
App crashes when attempting to block user in Settings

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#11506]
# Bug Report

## Description

Go to Settings->Messaging->Contacts, requests & blocked users -> Click `...` on any user -> Block user

#### Expected behavior
- User is blocked
#### Actual behavior
- Crash
- User seems blocked on app restart

### Additional Information

- Status desktop version: 0.13-rc6
- Operating System: Ubuntu 20.04

**Comment by anastasiyaig** [comment]
i checked in master - there is a significant difference in performance compared to 0.13 (master is way faster). also was not able to see the crash. We also have a task to revisit block user fucntionality in 0.15 worth checking after implementation
