### ISSUE TITLE
[StatusChatInput] Various enhancements to cursor animation and behaviour in message input

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11519]
There are a series of small enhancements we can make to the message input behaviour to make it a little more standardised to other platforms to better meet user expectation. The following refer to a filled message input (filled but not yet sent).

**Enhancement 1**
When the user taps or holds the arrow key to change the caret position (the vertical line marking where text will be written from), the blinking animation (where the caret fades in and out) should be paused. While the user is tapping or holding the arrow key, the caret should not fade out - it should be constantly visible. 

**Enhancement 2**
When the user taps the arrow key to navigate the caret down to the bottom line of a message, one more tap should take the caret to after the last character typed into the message input.

**Enhancement 3**
The blinking animation of the cart should also stop when the user is typing and instead be constantly visible

**Enhancement 4**
It is also more standard for the caret to disappear when the user is highlighting text, showing only the highlight wash.

**Comment by iurimatias** [comment]
moving to 2.31 as it's a goal there

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
