### ISSUE TITLE
[Airdrop] Integrate functionality of airdropping to members with the shared address

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11532]
### Description

Current state of `airdropping to members` functionality is the following:
- In `EditAirdropView.qml`, UI displays the list of community members but selecting a member and proceeding with the airdrop action does nothing, since at the point this was implemented we didn't have the concept introduced [here](https://github.com/status-im/status-desktop/pull/11530) about the `airdropAddress` shared.

This task should integrate the `airdropAddress` concept in the `airdrop to members` flow, so the user will be able to airdrop tokens to any of their community members.

**NOTE**: [Figma flow](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22647-497754&mode=design&t=5oXrrddTCZni63iZ-0)

![Screenshot 2023-07-14 at 11 50 59](https://github.com/status-im/status-desktop/assets/97019400/07d12b9e-6b8e-47fe-8128-c2e7d8010d09)

**Comment by noeliaSD** [comment]
@jrainville, not sure if this has already been considered but, maybe it would be useful to add a new property into the `members` model to directly access to each member `sharedAddress`.

**Comment by jrainville** [comment]
> @jrainville, not sure if this has already been considered but, maybe it would be useful to add a new property into the `members` model to directly access to each member `sharedAddress`.

Yes good point. I added in a recent PR to status-go the `airdropAddress` of the user. We just need to add it to the Nim model. I'll add an issue.

**Comment by jrainville** [comment]
Opened here https://github.com/status-im/status-desktop/issues/11540
