### ISSUE TITLE
Communities to have a min of 1 tag

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11538]
Currently, it is not mandatory for a Community founder to add any tags for their Community. 

Speaking with @John-44 having a min of 1 tag should be a mandatory requirement for all new Communities. They should not be able to proceed with creating the Community until at least 1 tag has been added, in the same way we are making Community names, descriptions, logos and banners mandatory. 

When editing the Community, the user should also not be able to remove the final tag or at least should not be allowed to confirm Community edits until 1 tag has been re-added.

This may require some design work to clarify how we want to guide the user into meeting this new mandatory condition so if development could please reach out to myself to discuss ahead of implementation of the behaviour. Thanks!

---

requirements:
- when creating a community, a min of 1 tag is required
- when editing a community, the user cannot remove a tag if it's the only left

**Comment by iurimatias** [comment]
added to milestone but we'll need to estimate

**Comment by jrainville** [comment]
Closing this one as it's been superseded by https://github.com/status-im/status-desktop/issues/13966
