### ISSUE TITLE
Can't change networks to testnets on Minting screen

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11539]
### Description

Networks list is always Mainnet

![image](https://github.com/status-im/status-desktop/assets/82375995/cdbf9547-c3bc-4d97-93b4-6f6d8ad8bb21)

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp could be a regression from new networks settings screen , can u please take a look? or @alaibe

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig actually the thing is that the networks in testnet and mainnet looks the same, with same name and icon. @benjthayer  is working on creating icons for etstnet modes but for now I have kept same for both of them. We have a warning on top saying we are on testnet mode though, so this is not a bug but a feature :D

**Comment by anastasiyaig** [comment]
oh thanks @Khushboo-dev-cpp 

@glitchminer ^^ 
@endulab ^^
