### ISSUE TITLE
[Check #14639] Wallet -> Send: add a guard to check that maxFeePerGas is always > baseFee

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11536]
### Description

```
ERR 2023-07-14 15:05:22.674+03:00 rpc response error                         topics="rpc" tid=4586181 file=core.nim:36 err="\nstatus-go error [methodName:wallet_createMultiTransaction, code:-32000, message:fallback failed with \'max fee per gas less than block base fee: address 0xF38D2CD3C6Ad02dD6f8B68E0A7b2f959819954b6, maxFeePerGas: 1348900000 baseFee: 1435850000\'. run error was \'max fee per gas less than block base fee: address 0xF38D2CD3C6Ad02dD6f8B68E0A7b2f959819954b6, maxFeePerGas: 1348900000 baseFee: 1435850000\' ]\n"
```

<img width="1061" alt="Screenshot 2023-07-14 at 15 05 34" src="https://github.com/status-im/status-desktop/assets/82375995/4913b055-331a-4bac-8512-0e7480fc8708">

**Comment by alaibe** [comment]
@benjthayer this is not something we can prevent with a 100% guarantee, do you think you could design something for this?

**Comment by alaibe** [comment]
Here, the best would be to change our strategy fees. We already have this guard in golang, but we are sometimes to close to it

**Comment by saledjenic** [comment]
This is fixed in this PR https://github.com/status-im/status-go/pull/5377

**Comment by benjthayer** [comment]
Hey @alaibe just getting to this - is there anything still required from design on this? If so, perhaps we can sync up so I can better understand what is required.

**Comment by alaibe** [comment]
@benjthayer we should have fixed it by changing fees structure. Not needed anymore ;)
