### ISSUE TITLE
Updated fees panel and transaction summary dialog for airdropping, minting, burning, remotely destructing

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11550]
With the advent of the Owner token and TokenMaster token, the way fees are taken through contract interactions has changed. 

Instead of the token being bound to the address that is selected in the minting form, the Owner and TokenMaster instead select the account from which to pay gas fees for contract interactions with the token. 

The latest fee panels and transaction summary dialogs have been rolled out into the following flows:
- Airdrop
- Mint (Owner token and normal token mint)
- Remote destruction
- Burn

The **fees** panel has been made into a component to make it easier to see the variants used throughout these flows:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=35302-601554&mode=design&t=izrFg3DNSH3R21mU-4

<img width="1246" alt="Screenshot 2023-07-17 at 11 20 49" src="https://github.com/status-im/status-desktop/assets/110033914/84b46c9d-efde-4e10-b555-2859ed2aa611">

States:
- Placeholder (use if the fee cannot be fetched until the user has input some value - e.g. number of tokens to burn)
- Single fee line item - price being fetched/calculated
- Single fee line item default - showing fee and account selector
- Single fee line item validated - user doesn't have enough funds in select account on requisite network
- Single fee line item - price being updated after user interaction with dialog (e.g. changes burn amount)
- Single fee line item validated - fee exceeds block gas limit
- Multi line fee item - all of the above states + differentiated validation per network for insufficient funds on selected account and fee exceeding block gas limit

The fetch (skeleton load) state should only be used if the fee fetch/update is not instantaneous.
While the dialog is in view, the fees should update according to the block time which will be different depending on the network being used for the transaction. Again, the loading state should only be used if the refresh of the fee is not instantaneous. 

A flow showing how the fee panel should look under the various conditions is shown here (in the context of airdrop):
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=35302-602386&mode=design&t=izrFg3DNSH3R21mU-4

--

The same with the **Tx summary transaction dialog**:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=35333-606277&mode=design&t=izrFg3DNSH3R21mU-4
<img width="1254" alt="Screenshot 2023-07-17 at 11 01 14" src="https://github.com/status-im/status-desktop/assets/110033914/7bab7ec9-3c4c-4061-981f-4a45698f4f53">

--

**Flows updated with the above:**

**Airdrop**
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22602-495365&mode=design&t=izrFg3DNSH3R21mU-4

**Mint, airdrop and remotely destruct Owner / TokenMaster tokens**
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=34794-589770&mode=design&t=izrFg3DNSH3R21mU-4
- Note that during the minting of the Owner token, the Community founder no longer selects the address to be used for all future interactions with the token - they simply select the account to be used to pay the gas fees and to have the Owner token airdropped to them on. The Owner token mint form is the only exception to the fee panel where the account selector is not included in the fees panel. This is because the Community founder is selecting the account to use for both the fees and the airdrop - so it is not solely relevant to fees.

**Mint, airdrop and remotely destruct collectibles and assets** 
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29373-560281&mode=design&t=izrFg3DNSH3R21mU-4
- Note that during the minting of a token, the Owner/TokenMaster no longer selects the address to be used for all future interactions with the token - they simply select the account to be used to pay the gas fees and to have the Owner token airdropped to them on. The mint form for the Owner and TokenMaster are therefore identical.

For the remote destruction of a token, note that the dialog has been changed significantly to allow the fees panel to stay in view. All views and interactions for this dialog have been documented here:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29468-618133&mode=design&t=izrFg3DNSH3R21mU-4

<img width="594" alt="Screenshot 2023-07-17 at 11 14 59" src="https://github.com/status-im/status-desktop/assets/110033914/322bd5ea-6068-400e-b740-ea089955938b">

cc @micieslak @John-44 @noeliaSD

**Comment by alexjba** [comment]
Already implemented

### Owner token:

![Image](https://github.com/status-im/status-desktop/assets/47811206/6956e1cd-73a8-4fdc-8ae9-ffce062a93b9)


### Minting


![Image](https://github.com/status-im/status-desktop/assets/47811206/048a456e-2155-4100-a8d3-c4cd6142fc75)


![Image](https://github.com/status-im/status-desktop/assets/47811206/8930fe65-aa38-4a9a-848b-f243b0907909)

### Airdrop


![Image](https://github.com/status-im/status-desktop/assets/47811206/08691712-a203-4d0a-9ab0-2be69f6f6264)
