### ISSUE TITLE
Members should NOT have access to other members' revealed accounts

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11573]
# Description

Right now, the members' shared addresses are inside the community description. They should not, as that means that all members see them.

Only the control node should have access to those addresses (and later Token Masters and owners without the community private key)

# Acceptance criteria

Here is the list of things to change/do (kindof ordered):

1. Remove revealed accounts from the community description (member chat key is still needed)
2. Add a new SQL table for the control node to store the revealed accounts
3. Back up that table's content to waku, using the community key (can only be decrypted by control nodes)  in case the control node is lost
4. Change the way Admins receive and process requests to join
    - Members no longer send the full request to join to admins, they only send the abridged version that contains the chat key and other necessary params (without any address)
    - When an admin makes a decision about that request to join, it does **not** get propagated to users yet, it goes to the control node and other admins
    - The request is shown as "pending" for the admin afterwards (eg "Rejection pending...") @benjthayer will have designs later, but use a placeholder for now
    - Other admins receive that signal and display the same pending message as above. They cannot change the decision
    - The control node receives the decision and does normal control node stuff; it checks the permissions if needed, updates the description and sends it
    - The human owner doesn't have do do anything, this is automatic by the control node
    - When admins receive the new description, they can get rid of the pending request
5. All other admin actions that touch permissions or members use that same flow
    - They go in pending state until the control node executes the action

**Comment by jrainville** [comment]
@John-44 just to be 100% sure, we do not want normal members to have access to others' revealed accounts right?

**Comment by John-44** [comment]
> @John-44 just to be 100% sure, we do not want normal members to have access to others' revealed accounts right?

@jrainville if you are referring to wallet accounts (I assume you are) then members **definitely** shouldn’t just be able to see (or be able to find out in any way) the wallet addresses of other members.

Only mechanism by which users can choose to share their addresses with other users is use the Profile Shocase and opt-in (which is nothing to do with communities)

**Comment by John-44** [comment]
@jrainville really, only the Control Node should have visibility of addresses.

**Comment by jrainville** [comment]
I updated the description to fit the requirements we discussed in the call

**Comment by jrainville** [comment]
Updated design flows and documented here: https://github.com/status-im/status-desktop/issues/11649

**Comment by 0x-r4bbit** [comment]
Started working on this, and keeping a list of things left to be done here:

- [ ] ensure we users don't send requests to admins if the community is configured to be auto-accept
- [ ] ensure admin node drop/ignore requests if the community is configured to be auto-accept
- [ ] Removed revealed accounts from requests sent to admins
- [ ] Adjust `HandleCommunityRequestToJoin`, `AcceptCommunityRequestToJoin` and `DeclineRequestToJoin` for admin nodes
  - Introduce new `RequestStateAcceptedPending` and `RequestStateDecliendPending` states
  - ensure admins don't perform token permission checks
  - mark requests as accepted/pending when manually accepted and forward community event to owner node
  - mark requests as declined/pending when manually declined and forward community event to owner node
  - broadcast (pending) decision to other admins
- [ ] Adjust community descriptoin handling for admins
  - Ensure admins update their description based on other admins events, if not already done
- [ ] Adjust handling admin events as owner nodes such that
  - If admin accepted request, perform token checks, then auto accept request
  - If admin declined request, perform token checks then... auto decline(?)
- [ ] when receiving requests to join directly from other users, check if admins have already responded in the meantime and act accordingly
- [ ] Update UI
  - Introduce accepted/declined pending in activity center notification
  - Update pending requests UI according to accepted/declined state

**Comment by jrainville** [comment]
> Adjust handling admin events as owner nodes such that
If admin declined request, perform token checks then... auto decline(?)

If an admin declined a request, it's not necessary for the control node to do anything about it. It can just drop the request.

**Comment by 0x-r4bbit** [comment]
PR for most of the stuff is here: https://github.com/status-im/status-go/pull/3843

Gonna add the final touches for removing revealed addresses on top of that
