### ISSUE TITLE
Permissions values are not being applied as specified by user

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11588]
# Bug Report

## Description

When a user specifies an amount in a permission is is being applied with a figure including several more decimal places. For example, 0.1 is being set as per the image below. This results in a larger amount than intended being required to meet the permission criteria.

![image](https://github.com/status-im/status-desktop/assets/50769329/8e93065d-12ed-4e02-9696-b51f25507b5e)

## Steps to reproduce

Create a permission requiring 0.1 Eth

#### Expected behavior

Permission to be set with value entered by user.

#### Actual behavior

An amount larger than the value input by the user is being set.

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by anastasiyaig** [comment]
<img width="1728" alt="Screenshot 2023-07-19 at 17 57 44" src="https://github.com/status-im/status-desktop/assets/82375995/68e9d4ec-09c2-49ce-a802-2e3ca50fe8d7">
<img width="565" alt="Screenshot 2023-07-19 at 17 57 51" src="https://github.com/status-im/status-desktop/assets/82375995/33979fd3-c9c3-4579-9567-ec212f826491">

perhaps this is a reason i am not able to join the community from mobile

**Comment by caybro** [comment]
I think @micieslak is tracking this :)

**Comment by jrainville** [comment]
I know it's been happening for a long time. I know it's a problem with floats. Is it an issue in QML or Nim or both?
