### ISSUE TITLE
[Mint/Airdrop] Remove TEMP mint and airdrop buttons when Owner and TMaster token backend is ready

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11612]
### Description

On the following [PR](https://github.com/status-im/status-desktop/pull/11614) there have been added `TEMP` buttons to keep available the exisiting minting and airdrop flows while `Owner and TMaster token` backend is not ready.

<img width="1194" alt="Screenshot 2023-07-20 at 18 12 31" src="https://github.com/status-im/status-desktop/assets/97019400/eb21555b-8bc4-4957-ac16-4675b0be4da9">

Here the code to remove:
- `ui/app/AppLayouts/Communities/panels/MintTokensSettingsPanel.qml` --> Look for `text: qsTr("TEMP Mint token")`
- `ui/app/AppLayouts/Communities/panels/AirdropsSettingsPanel.qml` --> Look for `text: qsTr("TEMP Airdrop")`

**Comment by noeliaSD** [comment]
@endulab this task needs to be done after the complete functionality works so there's no need to have a backup button to do a minting! Please let me know when the button can be removed!

**Comment by jrainville** [comment]
@endulab might be doing this task as part of his PR. Please sync together @micieslak

**Comment by endulab** [comment]
@micieslak I removed button in https://github.com/status-im/status-desktop/pull/11857. You can close this task.
