### ISSUE TITLE
Community: Some Channels are not loading in the Status Internal community 

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#11616]
Version: 0.13.1
OS: Windows 10

***
Preconditions: Install 0.13.1

<ins>Steps to reproduce:</ins>

1. Navigate to the internal Status community 

2.  Click on a channel that has an unread messages 

<ins>What currently incorrectly happens:</ins>

3. The channel messages aren't loading

https://github.com/status-im/status-desktop/assets/124154641/5cab019e-5b89-4a61-8ee2-73a03fc48da4

<ins>What is supposed to happen:</ins>

3. The messages in the channel should load

<ins>Other information</ins>
Log: 
INF 2023-07-20 17:57:44.584+01:00 received                                   topics="signals-manager" tid=6288 file=messages.nim:71 signal=messages.new messageID=0xdf695491137125383b7237605b2ea350e2f0a9debc6aaeda18e534ecd567cdc1
ERR 2023-07-20 17:57:44.800+01:00 requested community doesn't exists         topics="community-service" tid=6288 file=service.nim:700 communityId=0x04ed918fd54d89037a1affd673f55e9a9e613478de1c03ef3a94cad37f91026c55a8739d64cbfc23a9f9d934323012f54c264eb4d6667638c6cb2926c220bb465a
INF 2023-07-20 17:58:05.583+01:00 received                                   topics="signals-manager" tid=6288 file=messages.nim:71 signal=messages.new messageID=0x5fc77ee49c744d7e7be30e026ffaabcb507b5eb818bc331f514da9c13a4820b1
ERR 2023-07-20 17:58:05.798+01:00 requested community doesn't exists         topics="community-service" tid=6288 file=service.nim:700 communityId=0x04ed918fd54d89037a1affd673f55e9a9e613478de1c03ef3a94cad37f91026c55a8739d64cbfc23a9f9d934323012f54c264eb4d6667638c6cb2926c220bb465a

&nbsp;

**Comment by osmaczko** [comment]
@igor-sirotin I would start with checking first unseen message. I assume, for some reason, this message can't be loaded when fetching messages.

**Comment by igor-sirotin** [comment]
Reproducible with clicking on a message in AC. After this the channel never opens, even if it was opening before.

**Comment by jrainville** [comment]
Reopening just to track that we want it in 0.13.2

**Comment by igor-sirotin** [comment]
Cherry-picked in https://github.com/status-im/status-desktop/pull/11655

**Comment by igor-sirotin** [comment]
Closing in favor of https://github.com/status-im/status-desktop/issues/11759
