### ISSUE TITLE
Wallet accounts scroll bar is showing above footer

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#11626]
# Bug Report

## Description

Scroll bar used in wallet accounts scrolls above the footer.
It should scroll to the footer instead.

I checked and simply changing `size` and `position` isn't possible to assigned ScrollBar. Only solution is to create ScrollBar anchored to view then calculate and rescale size and position manually.

## Steps to reproduce

* add multiple accounts
* Resize the app so the wallet accounts can be scrolled
* Scroll to the last position

#### Expected behavior

![image](https://github.com/status-im/status-desktop/assets/11396062/ea7efc5d-8877-4f13-8485-579aec6352b2)

#### Actual behavior

![image](https://github.com/status-im/status-desktop/assets/11396062/06bee11f-f3ea-4ab6-9c07-e331ce5ac2cc)

### Additional Information

- Status desktop version: master
- Operating System: Windows

**Comment by caybro** [comment]
What about removing the footer from the list view completely? And have a column of ListView + static list item delegate below?
