### ISSUE TITLE
Communities: Implement `Remote destruct` popups for `TokenMaster` token

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11625]
## Description

The remote destruct popups for TokenMaster tokens differ from remote destruct popups for regular tokens (https://github.com/status-im/status-desktop/issues/11624).

After the latest design update, popups contain both account selector and fee preview to inform the user about costs up front.

This task is based on outdated https://github.com/status-im/status-desktop/issues/11471

Relates to: https://github.com/status-im/status-desktop/issues/11624

**DEPENDS ON BACKEND TASK** https://github.com/status-im/status-desktop/issues/11276

Figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=35031-611336&mode=design&t=fl3tGGEKnLeeqOQY-0

<img width="600" alt="Remotely destruct (1)" src="https://github.com/status-im/status-desktop/assets/20650004/b82867ac-af8c-4dbb-9663-08d85660d2a0">

![Mint Token (2)](https://github.com/status-im/status-desktop/assets/20650004/07b620af-255a-4e38-b2b9-e2ad69ed6f74)

**Comment by noeliaSD** [comment]
Related to https://github.com/status-im/status-desktop/pull/11441

**Comment by endulab** [comment]
UI can use the same API which is used for collectibles.
The check whether it is master token or not will happen in the lowest level in status-go.
We need only disallow non-owners to make master token operations.

**Comment by alexjba** [comment]
Closing in favour of #12067 and #12066

Fees are implemented #11865
