### ISSUE TITLE
Syncing: Status app should ask for permissions to have access to camera

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11643]
### Description

**Info:** `MacOS Ventura 13.4.1,  Status version 0.13.1`

precondition: no permissions are granted to status app to use Camera (mac)

1. open app and proceed to syncing flow
2. select Scan QR code option

<img width="1728" alt="Screenshot 2023-07-21 at 17 04 24" src="https://github.com/status-im/status-desktop/assets/82375995/d9e96515-04c2-4927-b844-e12800b8f0a6">

**Comment by anastasiyaig** [comment]
@igor-sirotin please check this out, i was on 0.13.1

**Comment by churik** [comment]
Reproduced to me on Ventura 13.2.1 (22D68), MacBook Pro, release 0.13.1

**Comment by jrainville** [comment]
Maybe it's related to my change I did a while ago to fix the Linux camera, but Igor did test on Mac, so maybe not. https://github.com/status-im/status-desktop/pull/11021

**Comment by igor-sirotin** [comment]
Just to keep updated.
The dev version does ask for camera permissions.
It's only the Release build that doesn't. This makes the investigation a bit harder 🙂

**Comment by jrainville** [comment]
Ouch, those are the worst issues.

I don't get why running form the terminal vs directly would make a difference though. 

Just from the first part, I would have assumed that the release build was missing a package, but if it works from the terminal, I'm at a loss for ideas.

Hopefully other people ran into that before.

**Comment by igor-sirotin** [comment]
Actually there're some things that only affect AppBundle.
e.g. `info.plist` file, which should contain `NSCameraUsageDescription`. But we have that already.
Will keep looking in this direction.
