### ISSUE TITLE
profile: impossible to copy one's chat key

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#11665]
# Bug Report

With the SpiffWorkflow now in place... we have to solve one issue: currently it's impossible to get/copy anyone's chat key in any way. Bamboo profile requires this key to be filled in in order for the interconnect to work

Bamboo/Spiff expects the compressed key:
<img width="938" alt="Screen Shot 2023-07-11 at 6 21 48 pm" src="https://github.com/status-im/status-desktop/assets/5377645/1de48a4c-52a7-4fe9-b822-bb259736de59">

### Additional Information

- Status desktop version: master
- Operating System: Linux (F37)

**Comment by John-44** [comment]
We shouldn't be letting users copy *only* their compressed chat key, users should always copy their chat key wrapped in a URL.  This way, by making the chat key and the 'share URL' one and the same thing, the chat key always becomes an artefact anyone can click on.

Status Desktop shouldn't change anything here - bamboo and Splif Workflow need to be updated to accept chat keys wrapped in URLs

**Comment by caybro** [comment]
> We shouldn't be letting users copy _only_ their compressed chat key, users should always copy their chat key wrapped in a URL. This way, by making the chat key and the 'share URL' one and the same thing, the chat key always becomes an artefact anyone can click on.
> 
> Status Desktop shouldn't change anything here - bamboo and Splif Workflow need to be updated to accept chat keys wrapped in URLs

Got it; it exists in master only so as soon as Bamboo/Spiff adjusts to the URL format, we can always drop this feature
