### ISSUE TITLE
Wallet -> Activity view: double scrolling for filtering by token type

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11670]
### Description

so on the first screenshot, Assets and Collectibles buttons are cut but  because of that i can reach the end of the token list
on the second screenshot - buttons are nice but i cant get to the token at the bottom

To reproduce:

1. add 0x60057786842aff287ebb0bbf96e082733a4a667f as w/o on mainnet
2. open activity tab
3. filter by token
4. scroll to the end of the list

<img width="293" alt="Screenshot 2023-07-25 at 17 33 30" src="https://github.com/status-im/status-desktop/assets/82375995/1c4331ad-3f0e-46ac-896d-9d7f7d489f8f">

<img width="293" alt="Screenshot 2023-07-25 at 17 33 38" src="https://github.com/status-im/status-desktop/assets/82375995/4a26c568-4c35-4373-8946-31aa4d7edbbc">

**Comment by caybro** [comment]
I think I've seen this bug before, @micieslak ?

**Comment by Khushboo-dev-cpp** [comment]
https://github.com/status-im/status-desktop/assets/60327365/3f5bd274-3d3d-4951-bc98-cf8f0f86da40

not reproducible on latest master @anastasiyaig assigning back to you

**Comment by anastasiyaig** [comment]
lets close that
