### ISSUE TITLE
Wallet settings - various small enhancements identified via mobile wallet settings work

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11675]
The design of the wallet settings area for the mobile app has uncovered a number of small enhancements we can also bring to desktop for alignment. I've done my best to be as detailed on those changes below. 

**Wallet settings designs Figma**
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15264-338833&mode=design&t=iftwPJwVkmFPNGIT-4

--

1. Consistency in terminology: Any reference to `Keys` or `Master keys` or `Master keypairs` are now all replaced with `Keypairs` for consistency. This change impacts many of the menu, screens and dialogs in the wallet settings area including CTAs and validation. E.g:

<img width="661" alt="Screenshot 2023-07-25 at 15 55 56" src="https://github.com/status-im/status-desktop/assets/110033914/d063af61-c3a8-4a4d-be72-255301e346fc">

<img width="452" alt="Screenshot 2023-07-25 at 15 56 30" src="https://github.com/status-im/status-desktop/assets/110033914/94c5cd42-ac80-47d8-94d6-d92875c10a84">

--

2. Change in terminology: Any reference to `Watch-only` or `Watch-only accounts` has been changed to `Watched address` or `Watched addresses` (if plural).

<img width="784" alt="Screenshot 2023-07-25 at 15 37 21" src="https://github.com/status-im/status-desktop/assets/110033914/f4004370-7aa5-456f-a352-2ce88edab8d0">

<img width="1154" alt="Screenshot 2023-07-25 at 15 37 52" src="https://github.com/status-im/status-desktop/assets/110033914/b5fd074b-3126-4a43-8d27-725f3c6defc3">

--

3. Change in terminology: Instead of referring to synced keys, we refer to `added` keypairs which require import. This change is made mainly in the following flows:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15777-377915&mode=design&t=iftwPJwVkmFPNGIT-4

Specifically:

--

a) Copy change in the `Key syncing` panel (which is dynamically shown on the device which has added new keypairs and accounts to enable the user to add those keypairs/accounts to their synced devices via the QR button).

Old copy: `Key syncing`
New copy: `Import keypairs from this device to your other synced devices` 

New design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=17597-392050&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/110033914/1c125b42-926e-44e5-b251-fd8d931cd4b1">

Old design:
<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/110033914/17368467-663b-4ba2-80e2-92c44c2be024">

--

b) On the counterparty device - the one where the new keypair needs to be added, there is a copy change in the `Import` panel:

Old copy: `Key syncing`
Old CTA: `Import missing keys to this device` (button also now orange)

New copy: 
- If 1 keypair requires import: `1 keypair requires import to use on this device`
- If >1 keypair requires import: `2 keypairs require import to use on this device`
New CTA: 
- If 1 keypair requires import: `Import missing keypair` 
- If >1 keypair requires import: `Import 2 missing keypairs`

New design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15777-377334&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/110033914/1d7fa28e-51b7-41b5-a793-7b56dc8cd36c">

Old design:
<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/110033914/053b349d-2be9-4175-9989-194759caa88d">

Note: the orange text below the keypair name of the keypair that requires import has also changed format to specify the date the keypair was originally added.
Old copy format: `Synced from [device name] - finalise import to use accounts`
New copy format: `Added to [device name] - [date added to device]` -- IGNORE!

--

c) Copy change to finalise import dialog header:
Old dialog title: `Finalise import of synced keys`
New dialog title: `Import missing keypairs`

Old dialog copy: `[n] public keys have been synced from [n] devices. To use the associated accounts on this device, you will also need to import the keypairs.`
New dialog copy: `To use the associated accounts on this device, you need to import their keypairs.`
NB - each list item was also previously formatted: `Import [n] keypair from [device name]`, now it is written: `From [device name]` as the list item reads on from the title, i.e. `Import missing keypairs... from [device name]`. There is also an additional label within the device grouping at the top right clarifying how many keypairs will be imported: `Import [n] keypairs`. Finally, there is a slight design change to the layout of the keypair list items within the device grouping - note the slight separation / padding between the keypairs in the new design.

New design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15778-380982&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="480" alt="Finalise import5" src="https://github.com/status-im/status-desktop/assets/110033914/69f0bd33-4eb6-4336-99f8-2589a06acde3">

Old design:
<img width="480" alt="Finalise import2" src="https://github.com/status-im/status-desktop/assets/110033914/f193d6f5-a45a-4301-a241-25e68380fd25">

--

d) Title changed on dialog where user selects import method.
Old dialog title: `Import [keypair name] keypair from [device name]`
New dialog title: `Import [keypair name]`

New design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15778-381242&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="480" alt="Finalise import3" src="https://github.com/status-im/status-desktop/assets/110033914/63c81a7a-818c-4a0f-b56d-2be0fc9fbae8">

Old design:
<img width="480" alt="Finalise import4" src="https://github.com/status-im/status-desktop/assets/110033914/da8b8d0e-f8cb-447d-ac37-495ea7b31f77">

--

e) Copy change on toast messages:
Use `keypair` instead of the other variants of this term described above

Eg:
Design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15814-383391&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="428" alt="Screenshot 2023-07-25 at 16 54 10" src="https://github.com/status-im/status-desktop/assets/110033914/3cde6010-f41b-4abf-a6f5-9e3721393a00">

--

f) Copy change on CTA for Import via seed phrase and private key dialogs:
Old CTA copy: `Import [keypair name] key`
New dialog title: `Import [keypair name] keypair`

Private key:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15778-384761&mode=design&t=iftwPJwVkmFPNGIT-4

Seed phrase:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15778-384802&mode=design&t=iftwPJwVkmFPNGIT-4

--

f) Copy and CTA change on account page in wallet settings (keypair requires import)

New design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15778-386239&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="1440" alt="Finalise import6" src="https://github.com/status-im/status-desktop/assets/110033914/76b48149-ff52-4337-9e1b-c1cdff32c765">

Old design:
<img width="1440" alt="Finalise import7" src="https://github.com/status-im/status-desktop/assets/110033914/9751aa2b-f379-4aff-9f03-a634ac497f10">

--

g) Copy and CTA change on account in wallet (keypair requires import)

New design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15778-386172&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="1188" alt="Account" src="https://github.com/status-im/status-desktop/assets/110033914/4163fe25-b949-466d-8b4c-67deb9452b0b">

Old design:

<img width="1188" alt="Account2" src="https://github.com/status-im/status-desktop/assets/110033914/4ab17f80-180b-4e5f-89a3-a7ea69658a5c">

--

h) Copy change on QR generation dialog instructions (to reference new import button labelling):

Old copy: `On your other device, navigate to the Wallet screen
and select ‘Finalise import of synced keypairs’. For security reasons, do not save this code anywhere.`

New copy: `On your other device, navigate to the Wallet screen
and select ‘Import missing keypairs’. For security reasons, do not save this code anywhere.`

New design:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15779-389854&mode=design&t=iftwPJwVkmFPNGIT-4

<img width="480" alt="Show QR" src="https://github.com/status-im/status-desktop/assets/110033914/6cd298d7-c268-4fcc-a70b-e256fd90a019">

--

There are also some changes incoming in relation to how we signpost and allow users to import keypairs from Waku backup. The intention is that the signposting, copy and flows will be the same for the user irrespective of if the missing keypair is a result of  a waku backup or if the keypair has been added to a synced device and not yet imported. I will create a separate issue for that once the mobile designs are finalised and ready to be rolled out to desktop.

cc. @John-44 @xAlisher @saledjenic

**Comment by Khushboo-dev-cpp** [comment]
Ive addressed point 2 here https://github.com/status-im/status-desktop/pull/12341. The 1 and 3rd point are unclear to me as I am not sure if I'll mix things up. Hence, assigning it to Sale who will be the best person to do it

**Comment by saledjenic** [comment]
@Khushboo-dev-cpp thanks, I guess if not all many of these small things are already in place, but will go through this issue and check each point and update the code if needed.

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp thanks, I guess if not all many of these small things are already in place, but will go through this issue and check each point and update the code if needed.

@saledjenic I have to scratch that comment I made. I used your mock lib and have tested the flows mentioned here and made the necessary changes, no need to recheck :)

**Comment by saledjenic** [comment]
Ahh nice then, since this will be closed as soon as your PR gets merged I'm removing myself from the assignees.
