### ISSUE TITLE
Wallet -> Assets: missing icons for tokens on Mainnet 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11671]
### Description

We have a lot of icons missing for tokens, example is on the screenshot below. The task is to add the icons from design POV and then add them to the app

<img width="2025" alt="Screenshot 2023-07-25 at 18 13 23" src="https://github.com/status-im/status-desktop/assets/82375995/4781bc59-6a20-41ee-abc7-00643c829990">

**Comment by saledjenic** [comment]
Not relevant anymore.
