### ISSUE TITLE
[Community Settings] CommunitySettingsView is needlessly loaded for each loaded community

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11688]
### Description

CommunitySettingsView is needlessly loaded for every loaded community even if the user doesn't have the rights to open the settings view, or doesn't need this view in the current session.

One proposal is to load the CommunitySettingsView on demand, when the user needs it, and to keep it loaded to preserve the state.

**Comment by caybro** [comment]
To expand: I think we should _never_ load it unless the user is an admin/owner. Also, I think the state should be kept outside and we should unload this settings view from memory when not active

**Comment by alexjba** [comment]
> I think the state should be kept outside

The general state is easy to save, but the complexity is raising fast when starting to consider the inner components (E.g. some user typed token description in minting view, or the amount currently typed in the holdings dropdown.). One question here would be: Is it worth the effort to move the state outside of settings view?

The other options I see here are:
1. to preserve the view once it's been loaded.
2. A hybrid approach - Save the general state and unload the view **if** it's not dirty. Otherwise preserve the entire view.

IMO would be nice to have the entire UI state saved when switching views because I personally find it a bad UX to discard the work in progress without notification.
