### ISSUE TITLE
Wallet -> Send: receiving fees hangs the app on Mac and crashes on Windows

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11711]
### Description

<img width="1626" alt="Screenshot 2023-07-28 at 17 43 55" src="https://github.com/status-im/status-desktop/assets/82375995/05d37866-3d73-47de-ba88-9b535c8ba7cd">

https://github.com/status-im/status-desktop/assets/82375995/72aeeeee-a296-4771-980e-0c410492af98

**Comment by anastasiyaig** [comment]
per @Khushboo-dev-cpp , yes

**Comment by alaibe** [comment]
Quite unexpected, there is no "specific" logic per platform, I really suspect something around not being able to reach out the chain

**Comment by anastasiyaig** [comment]
i agree, i also tested that in latest master just now and it happens when all networks are enabled. When i was on ETH goerli, i was able to send
