### ISSUE TITLE
Chat -> GIFs are not resolved

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11714]
### Description

**Version:** `Master build [2738](https://ci.infra.status.im/job/status-desktop/job/master/2738/) from 28.07.2023, MacOS Ventura 13.5`

1. open community
2. open any channel
3. send a gif

<img width="1840" alt="Screenshot 2023-07-31 at 10 58 59" src="https://github.com/status-im/status-desktop/assets/82375995/2738a8e2-703d-4906-89e2-7dbae2cdfc8b">

**Comment by caybro** [comment]
I guess it's due to the unfurl changes that are not yet finished

**Comment by jrainville** [comment]
Yeah I think so too cc @igor-sirotin

**Comment by igor-sirotin** [comment]
Indeed, just not finished with new unfirling yet.
Here's the issue: https://github.com/status-im/status-desktop/issues/11634
