### ISSUE TITLE
Display name / image problems with CR dialog

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#11726]
# Bug Report

There are several issues with the `SendContactRequestModal` popup, especially with the way the user name and image are displayed:

1. Sending a contact request (CR) results in missing profile image:
![image](https://github.com/status-im/status-desktop/assets/5377645/8a59c803-d399-4b9b-be4f-761fa956b29c)

2. Display name is wrong for a user with an ENS name (image missing too, see above):
![Snímek obrazovky z 2023-07-31 18-18-42](https://github.com/status-im/status-desktop/assets/5377645/d8026d3b-7c00-4724-8001-70d8dca6e8f5)

3. Sending an ID verification request ignores the local nickname:
![Snímek obrazovky z 2023-07-31 18-19-32](https://github.com/status-im/status-desktop/assets/5377645/3a9f10b0-c3b5-4529-b490-d6756b3759de)

4. "Unknown" user with just an `alias`:
![image](https://github.com/status-im/status-desktop/assets/5377645/acef6262-78ce-4de0-a359-21e032ba9574)
(this one totally loses any previous known information, even after fetching the info from mailserver)

### Additional Information

- Status desktop version: master (5eaabe8ea6fa3f9ba2b167ffee2e622423ea6757)
- Operating System: Linux (F37)

**Comment by caybro** [comment]
@jrainville @alexandraB99 hope it's ok to target 0.14, local fixes "almost" done anyway

**Comment by caybro** [comment]
Just couldn't find any even remotely matching epic

**Comment by jrainville** [comment]
> Sending an ID verification request ignores the local nickname:

The ID verification is still a  bit bugged and planned to be fixed later iirc.

> hope it's ok to target 0.14, local fixes "almost" done anyway

fine with me

**Comment by caybro** [comment]
> > Sending an ID verification request ignores the local nickname:
> 
> The ID verification is still a  bit bugged and planned to be fixed later iirc.
> 

It's the same dialog, similar prob
