### ISSUE TITLE
Account Interaction - Migrate to keycard / stop using keycard

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#11737]
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=15235%3A285624&mode=dev

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=15285%3A324706&mode=dev

Covers migrating profile or seed phrase related keypair to a Keycard from the Settings/Wallet, as well as migrating them from a keycard to the app.

Corresponding options for those keyapairs:
- `Move keypair to Keycard`
- `Stop using Keycard`

**Comment by saledjenic** [comment]
@benjthayer I was about to start developing this feature, then I've found these two flows here:
- https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15700-370222&mode=design&t=q7dxa9km9KQvcPW9-0
- https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15715-368814&mode=design&t=q7dxa9km9KQvcPW9-0

which are still WIP, but just want to share here how I see those 2 flows:
- migrating **profile keypair** from keycard to desktop:
  1. user needs to provide the correct keycard (one associated with the profile)
  2. user needs to provide the correct seed phrase to confirm the he is the owner of the profile keypair and that we can build necessary master keystore file
  3. user needs to provide a desired password he wants to use to login the app
  4. once we have collected all those details, we can do the migration
  5. the last step of migration will be app restart (cause in that case we re-encrypted db and keystore files)
- migrating **regular keypair** from keycard to desktop (this is much simpler case and we have 2 options here and need to decide which one we want to apply):
  - **option A**:
  1. user doesn't need to provide a keycard in this case at all, the app already knows all necessary details to migrate a regular keypair to the app
  2. we just need to remove associated keycards' details for this keypair and mark it as a non operable keypair and add it to the list of keypairs which require import to use on this device (this list: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15777-376966&mode=design&t=qQrvQwnv1rtcqwow-0)
  - **option B**:
  1. user doesn't need to provide a keycard in this case as well, the app already knows all necessary details to migrate a regular keypair to the app
  2. user needs to provide the correct seed phrase for this keypair
  3. user needs to authenticate this action
  4. once we have collected all those details, we can do the migration

**Comment by benjthayer** [comment]
Hey @saledjenic `Stop using Keycard` flows for both profile and non-profile keypairs are now ready for development.

Designs:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15700-371329&mode=design&t=UKrt1bYDMRRAmONG-4

Thanks! :)

**Comment by saledjenic** [comment]
The first part of this issue which handles migrating to a keycard option is developed under the PR: https://github.com/status-im/status-desktop/pull/12010
