### ISSUE TITLE
Community -> Members list: members list is not updated when leaving community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11735]
### Description

1. create a community on desktop app
2. create an account on mobile device
3. add the mobile device account to friends list and invite to community
4. as mobile account, accept and join
5. as mobile account, leave the community

As result, status desktop app still shows mobile account as community member

<img width="1728" alt="Screenshot 2023-08-01 at 13 57 26" src="https://github.com/status-im/status-desktop/assets/82375995/3daa893d-a66c-4d0e-a9c1-9a6c7ac5eab4">

**Version:** 
`Status Desktop Master commit 6c5c36584a664ba79bab05effdccdb1389a9d47c, status mobile develop commit cf11743f87dae4ba4954b86107d8fbc18414e816`

**Comment by kounkou** [comment]
Hi,

### Attempt to reproduce the issue : 

Testing on mobile apk : 
https://github.com/status-im/status-mobile/releases/download/1.20.4/StatusIm-Mobile-v1.20.4-c85856-universal.apk

I am currently experiencing : 

- crash of the status-mobile when installing on a real mobile phone. The phone has Android 14 and Kernel version 5.10.168-android12-9-27760517-abS901WVLS3SWK7 from 1 Thu Nov 30
- an error stating : `Error java.lang.UnsatisfiedLinkError: dlopen failed: library "libgokni.so` not found on Android Studio Hedgehog | 2023.1.1 Patch 2, Build #AI-231.9392.1.2311.11330709

### Next steps

I guess I need to actually test on non-released version from master.

**Comment by anastasiyaig** [comment]
I tested that today with:

desktop as master commit ae16bd8b675b60bfaa58737e721d1cdb105552ed
mobile as develop from 6 feb (nightly) https://ci.infra.status.im/job/status-mobile/job/nightly/3011/

I was able to join community, leave and and see the members list reflects the changes correctly.
