### ISSUE TITLE
Wallet Setting: New designs for edit network settings 

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#11751]
### Description
 I see new designs for edit network that we havent already handled-

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15248-327743&mode=dev
 
 @benjthayer please let us know if the designs are ready for implementation.

**Comment by benjthayer** [comment]
> ### Description
> I see new designs for edit network that we havent already handled-
> 
> https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15248-327743&mode=dev
> 
> @benjthayer please let us know if the designs are ready for implementation.

Hey Khushboo, sorry I missed this one for some reason. Yes, the designs for network settings are stable and ready to be developed.
