### ISSUE TITLE
[StatusChatInput] Do not truncate large messages

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#11767]
### Description

_opening in repo as not sure if bug or missing feature_

When pasting  large message to send. The message gets truncated with no feedback to the user.
Meaning that one can send a truncated message without realising it.

A better UX (in my opinion) is to let the full message being pasted in the box but have the character counter display a negative value and disable the ability to send until the character counter value hits zero.

Version: 0.13.2

**Comment by iurimatias** [comment]
@benjthayer could you add this to you backlog please

**Comment by benjthayer** [comment]
> @shinnok has already been in contact with Ben.

Yep already been in discussions with @shinnok about this. @shinnok just shout if any further input needed.

**Comment by shinnok** [comment]
> Yep already been in discussions with @shinnok about this. @shinnok just shout if any further input needed.

I believe I managed to implement most of what we discussed for this, including doubling the max height that the input edit extends to when necessary. You can see the end result in the **third iteration video** here:

https://github.com/status-im/status-desktop/pull/12082#third-iteration
