### ISSUE TITLE
Intel and m1 mac build does not launch

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11762]
### Description

https://ci.infra.status.im/job/status-desktop/job/master/2757/

Launching intel mac build from this job does not work to me

<img width="372" alt="Screenshot 2023-08-02 at 17 46 15" src="https://github.com/status-im/status-desktop/assets/82375995/39340d8c-6673-42f4-8038-0282df2e9a7a">

<img width="328" alt="Screenshot 2023-08-02 at 17 46 19" src="https://github.com/status-im/status-desktop/assets/82375995/37ec493b-63b7-4602-8577-6c7248b76b88">

**Comment by anastasiyaig** [comment]
@iurimatias was able to reproduce as well and provided this:

```
1]    5875 killed     ./nim_status_client
(base) ➜  MacOS du -sh *
 30M    StatusQ
 13M    nim_status_client
(base) ➜  MacOS cd /Applications/Status.app/Contents/MacOS/
(base) ➜  MacOS du -sh *
 30M    StatusQ
 18M    nim_status_client
```

cc @jrainville 

@jakubgs is it something u can check?  The package is wrong size it seems

**Comment by jakubgs** [comment]
Is it perhaps only the `x86_64` build only? Because it appears to be built as release without any good reason:

![image](https://github.com/status-im/status-desktop/assets/2212681/d775201e-cd19-43ca-8fa5-aa4f76aa04ba)

**Comment by anastasiyaig** [comment]
yes, i pointed on that earlier this week

**Comment by jakubgs** [comment]
Looks like the release type issue was a red herring and this PR has not fixed the issue:

* https://github.com/status-im/status-desktop/pull/11766

While I was out no changes to CI have been made, so I don't think this is an infra issue, but a codebase issue.

**Comment by anastasiyaig** [comment]
@alexjba maybe u can check on that?

**Comment by anastasiyaig** [comment]
@igor-sirotin perhaps this change causes this https://github.com/status-im/status-desktop/pull/11748

can u please check?

**Comment by igor-sirotin** [comment]
I can confirm this happens. Checking now.

**Comment by igor-sirotin** [comment]
Probably I added the `com.apple.developer.associated-domains` entitlement to early.
https://github.com/status-im/status-desktop/blob/ce87d3a7a2424390870fa441e3461376ce89ac77/Entitlements.plist#L7-L10

The app launch is blocked with `Disallowing im.Status.NimStatusClient because no eligible provisioning profiles found` message in system logs.
