### ISSUE TITLE
Simplifly Loading Items mechanism in the model

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#11802]
We could have a proxy model that conditionally appends "loading items" to the end of the list, since it seems to be a common requirement for lists of items we show in the app.

- UPDATE -
We have a proxy model now, use it and remove all the loading items logic from the collectibles model.

**Comment by Michal-Status** [comment]
Tested and it does not work. Issue reported here - https://github.com/status-im/status-desktop/issues/11802
