### ISSUE TITLE
Updating a community makes the control node freeze for a few seconds

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11808]
# Bug Report

## Description

If as an owner, you update the community, or even if an admin updates the community, even just the name, it makes the control node freeze for a few seconds.

It doesn't feel good and also in most cases, it's probably useless. 

I think it's because it redoes the channel permission checks, but if you don't touch the permissions, it doesn't need to do that.

Anyway, if it does have to do the permission checks, it would be better to do them async afterwards.

## Steps to reproduce

0. Have a community with community permissions (mine has 3 minted collectibles, a permission to join and one to admin)
1. Edit the community name as the owner
-> control node freezes
2. Edit the community as an admin
-> control node also freezes

[slow.webm](https://github.com/status-im/status-desktop/assets/11926403/05827740-464f-4eb8-93d4-8c3a874c962a)

#### Expected behavior

App stays responsive after an edit.

If the edit doesn't touch the permissions, no permission check is done.

If there are permission edits, the permission checks are done async

#### Actual behavior

The app freezes on the control node when any edit is made, by the owner or by an admin

### Additional Information

- Status desktop version: master `20790a4c2a22a07c1c43e19e80b6f8873f3c8408`
- Operating System: Ubuntu 20

**Comment by borismelnik** [comment]
![Image](https://github.com/status-im/status-desktop/assets/82511785/057f7ca0-9c7c-4799-bb87-65a423db4b28)

Unfortunately :( @jrainville

**Comment by jrainville** [comment]
@borismelnik which version of desktop and status-go did you use? In theory master should work, but worst case, `release/0.14.x` should be safe too
