### ISSUE TITLE
[community chat] user list missing

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#11813]
# Bug Report

Since 354bd3e923b6f8925aab5e145771f3a11da2aba2, the user list panel in community chats is empty:
![image](https://github.com/status-im/status-desktop/assets/5377645/7dd35046-21a8-421a-b8de-9a9c5d418919)

Group chat is still fine:
![image](https://github.com/status-im/status-desktop/assets/5377645/f7256881-2e27-49ca-ae27-0d187f489204)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by jrainville** [comment]
Should we default to showing the whole community list for now, or it would require monkey patching and is no worth it?

**Comment by osmaczko** [comment]
@caybro is using latest master if I am not mistaken. IMO it is not worth the effort to cover the case of not yet updated control node. I am not sure if that's even doable, we would need to do the migration of `CommunityDescription` on clients. The issue with that is:
1)  `CommunityDescription` is saved as binary blob: protocol message with `CommunityDescription`,
2) This description is signed by control node, so can't be modified by clients freely

**Comment by jrainville** [comment]
I was more talking about doing a small patch on Nim to cover the case where the control node isn't updated.

If it's more than a few lines, I don't think it's worth it though, since just updating the control node will fix it

**Comment by osmaczko** [comment]
> I was more talking about doing a small patch on Nim to cover the case where the control node isn't updated.

How would you recognize that control node isn't updated?

**Comment by jrainville** [comment]
> How would you recognize that control node isn't updated?

If the member list from the chat is empty I guess?

**Comment by osmaczko** [comment]
> If the member list from the chat is empty I guess?

If the control node undergoes an update and no one fulfills the channel's criteria, then the member list will also be empty.

> If it's more than a few lines, I don't think it's worth it though, since just updating the control node will fix it

I think the same.

**Comment by caybro** [comment]
If it's just a transitional issue that will correct itself over time, I guess it's fine

**Comment by jrainville** [comment]
Closing for now since it seems like only a matter of the control node not being updated
