### ISSUE TITLE
Failed to change password for account, error "invalid cross-device link"

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#11811]
# Bug Report

## Description

Change password from Profile view. After new password is entered and confirm button is clicked, after some time operation silently fails with the error in the log:
```
error:   topics="privacy-service" tid=62524 file=service.nim:99 procName=changePassword errDesription="rename /tmp/1429909632-v4.db /home/user/work/projects/Status/status-desktop/Status/data/0x8e5b0d6c8c8bbb112889c5932549cad6ce15dfbf09c493ceb933fe0b5b176da9-v4.db: invalid cross-device link"
```

## Steps to reproduce

Settings->Profile->Change password-> Enter new password -> Change password and restart status

#### Expected behavior
Password changed successfully
#### Actual behavior
Silent error in the log
### Additional Information
I have `/tmp` and `/home` directories on different partitions.

- Status desktop version: 0.13.1-rc.1; another setup is commits status-desktop 2e1b60ab067f3b77a4da2ae03cf607c69c7c488f with status-go d5203c5e539846fb090bf3583ee536ec88f8b7a4
- Operating System: Ubuntu 20.04.6

**Comment by caybro** [comment]
@IvanBelyakoff I assume your `/tmp` and `/home` mount points are not the same partition? :)

CC @alexjba 

Not quite sure in detail how the DB migration is done but it looks like it's processed in a temp file and them overwritten when succeeded. It seems there's some sort of hard link involved and this wouldn't work if the 2 files are not in the same partition, needs to be a symlink

**Comment by caybro** [comment]
> @IvanBelyakoff I assume your `/tmp` and `/home` mount points are not the same partition? :)
> 

Ah, you wrote it there already in the description, sorry 😐

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-go/pull/3793
