### ISSUE TITLE
[Community Settings] Add `SFPM` for wallet accounts model in a single place

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11829]
### Description

We are using an `SFPM` for `colors` and filtering by `walletType` in many places for working with **wallet accounts model** in different token related  / community settings views:
- `MintTokensSettingsPanel.qml`
- `BurnTokensPopup.qml`
- `CommunitySettingsView.qml`
- `CommunityTokenView.qml`
- `EditCommunityTokenView.qml`
- `EditOwnerTokenView.qml`

This task should do a small refactor to have that proxy only in a single place, like `CommunitySettingsView.qml` and pass the tuned model through the rest of views.

_Originally posted by @micieslak in https://github.com/status-im/status-desktop/pull/11816#discussion_r1286719411_

**Comment by caybro** [comment]
We are also filtering (I think in all of these places) on this condition as well:
```qml
filters: [
    ValueFilter {
        roleName: "walletType"
        value: Constants.watchWalletType
        inverted: true
    }
]
```
