### ISSUE TITLE
[Minted Assets and Permissions] Minted assets are not displayed in the correct permissions list

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11843]
### Description

Here there are 3 different issues that may worth it to split in different ones:
1. When user mints a community asset, after it is correctly displayed as deployed in the community settings token view, if user navigates to the permissions list, this asset is not there until the app restarts.
2. When a new asset is minted, instead of being part of the assets list in permissions, it is shown in collectibles tab.
3. In general, it seems that assets list doesn't set up the `category` role correctly since, no category is displayed and they should be under `Community assets`, `Your assets` or `All listed assets` following the current design.

Here a video that reproduces all these issues:

https://github.com/status-im/status-desktop/assets/97019400/a98be099-5637-4ce6-8325-ec2eea98d9e9

**Comment by MishkaRogachev** [comment]
figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29468-609606&mode=design&t=h4ugpDD6UAU47SHt-0
