### ISSUE TITLE
[Mint token] Network selector not shown properly

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11846]
# Bug Report

## Description

Network selector is not displayed correctly in `Mint token flows`:

![Screenshot 2023-08-09 at 14 25 45](https://github.com/status-im/status-desktop/assets/97019400/8e83fec0-442c-49fd-9e0e-a555176aa629)

### Additional Information

- Status desktop version: master 11820d040043a62d03eec115deeabc269096cb30
- Operating System: _macOS Monterey 12.3.1_

**Comment by caybro** [comment]
This is reproducible in both storybook (when you uncheck `Multi Selection`):
![Snímek obrazovky z 2023-08-11 17-11-11](https://github.com/status-im/status-desktop/assets/5377645/6157e266-e7f9-4011-99b1-8bbaaa6ee30f)

and also in the app (with testnet mode enabled)
