### ISSUE TITLE
Keycard -> Check whats on keycard: nan$ shown

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11841]
### Description

1. create status account
2. migrate it to keycard
3. generate account under satus keypair so it is migrated to keycard as well
4. remove data folder
5. install app
6. create new account (normal one)
7. open Keycard -> Whats on keycard and insert the card with migrated accounts

As result, both status and generated accounts are showing nan$ balance. Expecting 0 

<img width="1312" alt="Screenshot 2023-08-09 at 12 42 06" src="https://github.com/status-im/status-desktop/assets/82375995/c0a31360-26b6-4680-97d9-a8f3743a63c7">

**Comment by anastasiyaig** [comment]
@alaibe i dont see any suitable epic for keycard tasks / issues , can we please have one?

**Comment by alaibe** [comment]
@anastasiyaig Keycard tasks are all over, I will create an epic for keycard bugs after initial development
