### ISSUE TITLE
Communities: Refactor community permissions to handle amounts as big integers instead of floats

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11863]
# Bug Report

## Description

As described in https://github.com/status-im/status-desktop/issues/11376 passing amounts between ui and backend is unreliable and may lead to distortions. In https://github.com/status-im/status-desktop/issues/11491 it's refactored for minting, airdropping and burning. Similar refactor should be done for permissions.

It should also fix current problems with displaying decimal fractions provided by the user:

![Screenshot from 2023-08-10 16-06-30](https://github.com/status-im/status-desktop/assets/20650004/38390d56-b818-449e-8221-78d45d7a3015)

![Screenshot from 2023-08-10 16-06-50](https://github.com/status-im/status-desktop/assets/20650004/08f296cb-249e-498d-95bd-b48e368f28d8)

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone

**Comment by endulab** [comment]
Yes @jrainville https://github.com/status-im/status-desktop/issues/11588

**Comment by jrainville** [comment]
Cool. I linked this issue to the PR then. Make sure to get it merged when you can
