### ISSUE TITLE
Communities: Requesting to join community crashes the app

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#11890]
# Bug Report

Request to join the community

![image](https://github.com/status-im/status-desktop/assets/11396062/3a0ef93c-06af-4641-8af0-16d0911b90f8)

### Additional Information

- Status desktop version: 0.13.3
- Operating System: Windows

**Comment by jrainville** [comment]
I think this was already fixed, it rings a bell.

Also, we've been improving the requestToJoin flow for a while, so we probably would have experienced the crash if it still happened.

I'll still try to test Windows on master in a few to be sure it doesn't happen again

**Comment by endulab** [comment]
I made a few tests: tried to send a request a few times in a row and cancelled it on both sides (sender and receiver). I tried for both: normal and token-gated community. Functionality works as expected. No crash.
Also we have a new flow now: we need to share wallet addresses before sending request.
Tested on Mac.
Maybe we can confirm with QA team @anastasiyaig @lukaszso

**Comment by anastasiyaig** [comment]
checking on windows

**Comment by anastasiyaig** [comment]
i tested it with nightly build https://ci.status.im/job/status-desktop/job/nightly/168/ on windows and mac. On mac i created community, and invited account from Windows machine. I was able to see the invitation, notifications, click the community invite, prove ownership and share addresses, requested to join community and got approved.
