### ISSUE TITLE
[Communities]: Airdrop amount is strictly limited to 10 digits

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#11918]
# Bug Report

## Description
As noted here: https://github.com/status-im/status-desktop/pull/11862#issuecomment-1677585550 in some cases amount is considered invalid bc of strict limit even thought it's correct amount when taking into consideration defined supply and decimal places.

## Steps to reproduce
1. Mint token with high supply and many decimal places, e.g.:
![image](https://github.com/status-im/status-desktop/assets/20650004/300049b4-0a65-4816-9cc0-3b4089c13255)
2. Try to define airdrop of high amount, using also decimal places:
![image](https://github.com/status-im/status-desktop/assets/20650004/09426339-8c4f-4e0a-85b3-e6b2419130b9)

#### Expected behavior
Total supply and also decimal places should be taken into account when validating amount.

#### Actual behavior
Strict limit of 10 characters is used.

**Comment by friofry** [comment]
I'm going reimplement this
