### ISSUE TITLE
[chat] Download/invite popup small issues

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#11926]
# Bug Report

![image](https://github.com/status-im/status-desktop/assets/5377645/7b2fd076-8556-498e-b948-1355a06502b7)

- the popup is not centered
- the link (status.im) is wrong and should be probably clickable

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
@benjthayer do we have designs for this? :)

**Comment by benjthayer** [comment]
@caybro I've not seen this before and not seen it in the designs. Where does the user invoke this dialog from?

**Comment by caybro** [comment]
> @caybro I've not seen this before and not seen it in the designs. Where does the user invoke this dialog from?

By clicking on the `invite` blue text/link (below the popup)

**Comment by caybro** [comment]
@benjthayer oh and here as well:

![image](https://github.com/status-im/status-desktop/assets/5377645/d57aa01b-0c11-4100-b7a4-1b6cfe7f00a8)

**Comment by benjthayer** [comment]
The only reference to it I can find is here:
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=855-243&mode=design&t=RHiVfs6MkX9PMxaI-4

I'm sure we can make this a lot nicer!
