### ISSUE TITLE
[Community membership] The owner cannot accept rejected members

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#11928]
# Bug Report

## Description

The owner cannot accept a community membership request that was previously rejected.

## Steps to reproduce

1. Send a community membership request for a community with request to join required (Can be changed in Community settings - Edit community)
2. Login to community admin/owner account
3. Reject the request from step 1 (Community settings - Members -> All members)
4. Go to the Rejected tab. The membership request should be in the list
5. Hit Accept

#### Expected behavior
The membership request is accepted
#### Actual behavior
The membership request state is not changing
### Additional Information

Logs:
```
ERR 2023-08-17 16:35:39.198+03:00 Error accepting request to join community  topics="community-service" tid=441179 file=service.nim:1518 msg="Community request not found: 0x02530b0712f304a145bc1454379deced2397abbf90d21841dc046c0df50ed43f"
```

https://github.com/status-im/status-desktop/assets/47811206/a56a4303-eb0a-4254-9512-0180458f80ef

- Status desktop version: 2c500042759ef9ad8c19729d53b8ea198241e834
- Operating System: MacOs

**Comment by jrainville** [comment]
Ah I found this issue as well when Hooking the pending request state. So in this PR, this issue should be fixed https://github.com/status-im/status-desktop/pull/11914
