### ISSUE TITLE
Community: mint Owner Token prompt is still present even the device is Control node (recovered community)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11936]
### Description

1. create community
2. mint owner token and token master token 
3. back up seed and community private key
4. remove your data folder and recover the account
5. import the community private key to make current device being control node again
6. open airdrop screen

**As result:**
1. owner token and master token are present on the tokens screen
2. can't mint token , button is disabled
3. mint owner token prompt is present

<img width="1643" alt="Screenshot 2023-08-17 at 18 16 11" src="https://github.com/status-im/status-desktop/assets/82375995/4d1330a9-34dc-40b3-8ffe-b4e7ea3f6580">

<img width="1643" alt="Screenshot 2023-08-17 at 18 16 17" src="https://github.com/status-im/status-desktop/assets/82375995/0bfdc1ae-fa39-4539-9b3c-5e90d07ac973">

NOTE: 

### on Linux :
backup the ~/.config/Status directory if you need it, then delete it

**Comment by anastasiyaig** [comment]
@jrainville maybe @endulab can double check on that?

**Comment by endulab** [comment]
I have a suspicion that there is a problem with rehydrating database. I added a new column with Privileged type and probably it is wrong and has impact on enabling buttons.

**Comment by kounkou** [comment]
This requires minting the owner token, and I am currently in the process of minting token.

**Comment by kounkou** [comment]
Hi, 
I have tried to reproduce this issue, by following the provided steps in description.
However, I couldn't see any issue comparing to the given screenshots in description

As result:

-[x] owner token and master token are present on the tokens screen
-[x] I CAN mint token , button is disabled
-[x] mint owner token prompt is NOT present

![Screenshot from 2024-02-13 09-47-52](https://github.com/status-im/status-desktop/assets/2589171/11d231a3-10b5-4d4a-bdd5-28200567b72b)

**Comment by anastasiyaig** [comment]
@kounkou i tested today in last master commit i pulled and it seem to be alright now!
