### ISSUE TITLE
Permissions are not evaluating community minted ERC20 tokens

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11934]
# Bug Report

## Description

1. Mint and airdrop a community asset, ERC20 token
2. Configure a permission the depends on the token. For example, join community
3. Attempt to join the community but find that the token is not being considered as held by the user

#### Expected behavior

Minted ERC20 tokens are evaluated and can be used in permissions.

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-11803/8/ 
- Operating System: Mac

**Comment by jrainville** [comment]
My guess as to what is happening here is that the token is not being added to the user's wallet. Though the permission check function should know to check the right contract for the balance, so maybe that's not it?

**Comment by jrainville** [comment]
@endulab any chance that this is caused just because of the ERC20 contract not being hooked with the Owner token contract?

**Comment by endulab** [comment]
@jrainville I do not think so. This is rather the problem of the code which checks wallet balance. @glitchminer you can ensure that the wallet contain the token by checking etherscan. If it does contain then we have a problem with checking balance.

**Comment by glitchminer** [comment]
@endulab , the transaction was successful: https://goerli-optimism.etherscan.io/token/0x08bbbf4091669919ed307139f572c1547fabf88a?a=0x9a500ea28e968e6e9f7a15e0f6b25d13ca89d0a7

It appears that this is being shown as ETH in the wallet
![image](https://github.com/status-im/status-desktop/assets/50769329/09f350db-b82c-460b-b4e6-83a168788589)

**Comment by endulab** [comment]
After some investigations, it turned out that permissions are created with wrong type, because ERC20 token is on the ERC721 list. This will be fixed in https://github.com/status-im/status-desktop/issues/11843.
FYI @glitchminer @jrainville

**Comment by endulab** [comment]
Also I was investigating "no such table: collectible_data_cache" error which shows up sometimes when parsing permissions.
It will be fixed here: https://github.com/status-im/status-go/pull/3926
