### ISSUE TITLE
Set Keycard's metadata if they are not present

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#11933]
If a Keycard without metadata is used (which should be the case only if an old Keycard is being used) then we need to set metadata for that Keycard based on the app state for the key stored on that Keycard.

We should do that silently when a user provides a PIN for a Keycard for any reason.

Also at this moment, some flows require a Keycard that contains metadata, thus we need to check all flows we have and let the user run any of them regardless if a Keycard contains metadata or not, but in case it doesn't contain them we need to set them firstly before we continue with the flow.

**Comment by guylouis** [comment]
it seems to me there are mostly two cases where this can happen and we have to tackle them both:
**1/** user wants to imports accounts from a keycard (either when creating a status account, or importing accounts on desktop that come from an existing keycard) and this card has no metadata
**2/** the user has a card in status desktop with metadata well set up, and for some reasons he uses a copy of this same card (same root key) but with no metadata. It's actually probably a rare case.

With more details
**1/** we're importing accounts from a keycard 
       - either before sign-in when the user creates a status account, in this case we ask which name we give to the card. There's no need to give name to accounts I guess since it's the creation of a new status account, and in this case we don't ask for the default account.
       - or when signed-in, when importing an account from a keycard, if there is no metadata then we need to decide what we do ... because this feature, when it's using a card with metadata, is importing all the accounts that are present in the metadata list. Actually when there is no metadata, we should let the user decide which path(s) of the card he wants to import ....
      
**2/** that's what @saledjenic describes above I guess, there is some metadata stored about this card in desktop, and we can silently update the second card with them.

**Comment by saledjenic** [comment]
@xAlisher this is an issue we have for the desktop app that is not implemented and this is also the flow we've discussed that you're designing for mobile app. Once you do it, please speak to @benjthayer to create the same for the desktop app and please post the link to that flow here, so that I can implement it.
