### ISSUE TITLE
[Community Ownership] Add check that owner contains OwnerToken 

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#11945]
### Description

All members share their addresses during requests to join the owner. This address is saved to a separate DB.
The owner himself does not reveal his address during creating the community and joining it. 

We need to figure out which address must use OwnerToken and update `ReevaluateMembers` fn to use this address in order to check if Owner owns OwnerToken

**Comment by jrainville** [comment]
I guess an option would be for the owner to add their own address to the SharedAddress table. We can automatically do that when the OwnerToken is minted, because then, we need to use only that address

**Comment by jrainville** [comment]
This issue might be done by another issue in the meantime, but it is simpler now, since we'll be using a Deployer contract that contains a map of communityId -> OwnerToken

**Comment by mprakhov** [comment]
discussed with @osmaczko and agreed that with the current implementation it is not needed any more
closing as obsolete
