### ISSUE TITLE
New/Edit channel: New option to hide channel from members who don't have view permissions

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11948]
The create channel and edit channel flows have been updated to include a new checkbox:

`[ ] Hide channel from members who don’t have permissions to view the channel`

The new checkbox is positioned directly above the permissions section of the `New Channel` and `Edit [channel name]` dialogs.

It should be deselected by default.

When selected, users that do not hold the requisite tokens to view the channel will not see the channel in the channels list for that Community. 

New channel dialog design:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=36915-686731&mode=design&t=NTLT8Ifpzgewt89p-4

<img width="640" alt="New channel" src="https://github.com/status-im/status-desktop/assets/110033914/deb77988-b902-416f-a4cd-22d522127458">

--

Edit channel dialog design:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=3064-356164&mode=design&t=NTLT8Ifpzgewt89p-4

<img width="640" alt="Edit channel" src="https://github.com/status-im/status-desktop/assets/110033914/54f49962-e13b-45c4-8e5c-1293fd696216">

cc @John-44

**Comment by alexandraB99** [comment]
Fixed in https://github.com/status-im/status-desktop/pull/12160

**Comment by iurimatias** [comment]
is done, but needs backend

**Comment by jrainville** [comment]
Backend issue here: https://github.com/status-im/status-desktop/issues/13291

**Comment by benjthayer** [comment]
Additional requirement:
If all channels in a category are 'hidden' for a user, the Category should be hidden from that user as well

cc @John-44

**Comment by alexjba** [comment]
covered by https://github.com/status-im/status-desktop/issues/13291
