### ISSUE TITLE
[Community Ownership] enable community updates to be signed by owner

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11958]
As of today, each community update is signed by the community's private key. With tokenized ownership, community updates will be signed either by the community's private key or by the signer's private key specified in the Owner Token contract.

This task is to make the clients rely on the arbitrary `signer` property rather than expecting the updates to be signed by the community's private key only.

The SPIKE on this has already been done here: https://github.com/status-im/status-desktop/issues/11371

### Acceptance criteria:
- [x] Sign community messages with control node's private key ([example](https://github.com/status-im/status-go/blob/e3788163c96aea35376cf25aea7b5bcf9b7974cc/protocol/communities_messenger_signers_test.go#L131C1-L136))
- [x] Use `community.signer` to validate control node messages (community description, request to join response, etc.). If no owner token has been deployed, then the signer should be the community's pubkey
- [x] Extend the community's protobufs with community id and stop inferring community id from the message's signer ([details](https://github.com/status-im/status-desktop/issues/11371#issuecomment-1624206189))

**Comment by cammellos** [comment]
I'll pick this up from Monday

**Comment by jrainville** [comment]
@cammellos what's the status on this? Patryk is back and can give a hand if needed

**Comment by cammellos** [comment]
@jrainville I spoke to Patryk and MIchal this morning, there's a few things that need to be implemented in this PR and to clarify, though the contracts are not ready yet, I can make it work so that it's working, but once contracts are finalized, we need to patch things up

**Comment by jrainville** [comment]
Great, thanks!
Is there a PR already? I don't see it linked to this issue

**Comment by cammellos** [comment]
@jrainville oh no, it's just a pile of mess on my local machine :) I can push something tomorrow

**Comment by osmaczko** [comment]
Done: https://github.com/status-im/status-go/pull/4108
