### ISSUE TITLE
[Community Ownership] hydrate community signer

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11956]
Get the owner token contract address by fetching it from `ContractOwnerTokenRegistry`, see: https://github.com/status-im/status-desktop/issues/11954#issuecomment-1709964605

### Acceptance criteria:
- [x] Add a method that will obtain Owner Token address for given community
- [ ] Once address is determined, save it in local database
- [ ] Extend `Community` struct with local only `signer` field and populate it with [ownerToken.signerPublicKey](https://github.com/status-im/communities-contracts/blob/8d3f185bf4d382d522815cff7cb2b70902cfffa8/contracts/mvp/OwnerToken.sol#L10)
- [x] Add a loop that will poll `ownerToken.signerPublicKey` ([details](https://github.com/status-im/status-go/pull/3727#discussion_r1266522527))

**Comment by jrainville** [comment]
Closing in favour of https://github.com/status-im/status-desktop/issues/11945

**Comment by osmaczko** [comment]
Done: https://github.com/status-im/status-go/pull/4108
