### ISSUE TITLE
[Community Ownership] validate Owner Token contract against known bytecode

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11957]
Once the Owner Token [contract address is obtained](https://github.com/status-im/status-desktop/issues/11956), the contract itself should be validated against know contract bytecode. This is to prevent owners from deploying malicious Onwer Token contracts.

### Acceptance criteria:
- [ ] Once Owner Token address is determined, the contract should be validated against know contract bytecode

**Comment by endulab** [comment]
Considering that we have a deployer contract which deploys owner token and also keeps the global registry of owner tokens, we do not need to verify the owner token contract. FYI @jrainville

**Comment by jrainville** [comment]
Yeah I agree. Once we're 100% sure to go with the Deployer contract solution, I'll close this issue

**Comment by jrainville** [comment]
Closing as we use the Deployer contract now
