### ISSUE TITLE
Copy and iconography tweaks to password creation flow

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11965]
**A couple of fine tuning items for the password creation flow:**

1a) The description copy underneath the `Create a password` title has been adjusted slightly so it fits more neatly on 2 lines (previously 3 lines). This avoids the red alert text needing to be split over 2 lines. Given that change, the form should be moved up, ensuring the padding between the description and the first input is retained to match the padding we have in place now

1b) The confirm password input should also house the `show` (eye) icon once the user has entered at least 1 character.

<img width="1232" alt="Create a password" src="https://github.com/status-im/status-desktop/assets/110033914/9a5b28a1-fced-451c-bf2d-9578eb2d0832">

2a) The additional confirmation step should have the `Confirm your password (again)` input auto-focused

<img width="1232" alt="Confirm password 1" src="https://github.com/status-im/status-desktop/assets/110033914/590506ee-42aa-48f4-bf7c-e04edac5b319">

2b) This input should also show the eye icon once the user has entered at least 1 character. 

<img width="1232" alt="Confirm password 2" src="https://github.com/status-im/status-desktop/assets/110033914/a84720da-a6ec-494a-b136-ed7840209c0f">

**Comment by kounkou** [comment]
Hi @benjthayer 

cc @jrainville 

> 1a) The description copy underneath the Create a password title has been adjusted slightly so it fits more neatly on 2 lines (previously 3 lines). This avoids the red alert text needing to be split over 2 lines

For the change in 1a to be effective, would it make sense to consider not only the English language but also every other single supported language?
A good benchmark for translation length could be German or French for instance. 
I would like to understand if having 2 lines for the description underneath the `Create a password` is a hard constraint, knowing that in other languages this constraint might not be fulfilled.

Please let me know your thoughts

Here are some screenshots with the new description sentence : 

once at least 1 letter is added, the icon in right is displayed as expected

![Image](https://github.com/status-im/status-desktop/assets/2589171/4a35d6c0-a5ea-4eb0-b64b-cc11352b4e9f)

once at least 1 letter is added, the icon in right is displayed as expected

![Image](https://github.com/status-im/status-desktop/assets/2589171/ee2637d6-089f-4dc9-be34-a7e2a0a11394)

There is strong focus and once at least 1 letter is added, the icon in right is displayed

![Image](https://github.com/status-im/status-desktop/assets/2589171/7f8656f5-1c9e-4acb-b434-1d7d8d37b37a)



For : 

> 1b) The confirm password input should also house the show (eye) icon once the user has entered at least 1 character.
> 2a) The additional confirmation step should have the Confirm your password (again) input auto-focused
> 2b) This input should also show the eye icon once the user has entered at least 1 character.

This is now solved in https://github.com/status-im/status-desktop/commit/defce32b37a11233d4772d7ea954d325b8d5c4e8

**Comment by jrainville** [comment]
> I would like to understand if having 2 lines for the description underneath the Create a password is a hard constraint, knowing that in other languages this constraint might not be fulfilled.

Good question. I'm not the designer, but I assume that two lines is what we aim for yes, so if it's possible to easily adjust the width so that it always fits on two lines, it would be nice.

If it's not easy to do programatically, you can try to use English, French and German and see what is the optimal width that is needed for all three languages to fit on two lines.

**Comment by kounkou** [comment]
Thanks. Working on a commit with assumption that two lines is what we aim for.

**Comment by benjthayer** [comment]
Hey @kounkou @jrainville thanks for looping me in :) It's hard to know what the design intent was for the text areas of these screens (I personally didn't design them) given there seems to be a variation in approach - some wrap more tightly, others use carriage returns for each sentence. 

The ideal from my perspective would be to have the text width match the input / form width below. However, given this paradigm is broken by the screens to the left and right of this screen in the flow, and the consideration around different languages, we might be safer allowing the text go as wide as required and implementing a carriage return between the 2 lines. That way, when we have a variation in the length of the text due to the translation into different languages, we can ensure there will only ever be 2 lines for the copy.

So instead of this:

<img width="1107" alt="Screenshot 2023-11-03 at 11 55 21 AM" src="https://github.com/status-im/status-desktop/assets/110033914/b9071dab-89c6-4548-9fba-50f0b40db876">

We do this:
<img width="1096" alt="Screenshot 2023-11-03 at 12 11 37 PM" src="https://github.com/status-im/status-desktop/assets/110033914/588ed4f5-feae-4fb8-9b08-d5a5abd104b7">

WDYT?
