### ISSUE TITLE
Wallet Settings: Tweaked import keypair flows to work around current inability to know which keypairs are fully imported on which synced device

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#11968]
Modifications have been made to the keypair import flows (in the `Wallet` page of the `Settings | Desktop` file). 

**Why?**
The previous iteration of the keypair import flows relied on us being able to know and communicate to the user which devices have which keypairs imported. This presumption in the previous design iteration allowed us to direct the user to a specific device depending on what keypair they wanted to import. If a keypair the user wanted to import was currently imported and fully functional on device B, instructions could be provided on device A to head to device B in order to generate the encrypted keypair QR. Given this information isn't currently known, the flows have been updated and generalised in various ways to avoid reliance on this information.

The previously designed flows can be found in the `Archive` pages of the `Settings | Desktop` file for comparison:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-606636&mode=design&t=kDsJy0gwUXRt62bH-4

The new designs can be found in their place in the `Wallet` page of the `Settings | Desktop` file:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-535102&mode=design&t=x4R2VWW5FQXxodXP-4

**Detailed list of changes:**

**1) Notification centre item relating to import of keypair to another of the user's synced devices:**

New copy: `Rainbow keypair was added to one of your synced devices`
Old copy: `Rainbow keypair was added to: [device name]`

<img width="1081" alt="Screenshot 2023-08-21 at 16 23 23" src="https://github.com/status-im/status-desktop/assets/110033914/d3ce3d1e-3716-471d-9230-492f539c0bab">

--

**2) Orange alert message on non-imported keypair** 

New copy: `Import keypair to use derived accounts`
Old copy: `Added to [device name] - [date imported DD MMM YYYY]`

<img width="1404" alt="Screenshot 2023-08-21 at 16 26 06" src="https://github.com/status-im/status-desktop/assets/110033914/3a602d68-430d-4160-8c75-a8da06cbbf51">

--

**3) Import missing keypairs dialog**

Previously, this dialog would group missing keypairs by the device they can be imported from. The dialog has been reformatted to avoid referencing devices. Instead of device groupings, the user is presented with 2 groups of options. 
- First, they can 'Import via scanning encrypted QR` - this brings up the QR scanner dialog and the user can scan whichever device they wish (the user is relied on to determine which device they scan based on their knowledge of where the required keypairs are fully imported).
- Secondly, they can select individual keypairs to import via seed phrase / private key (depending on how the keypair was originally imported) or QR

- Additionally, we've removed any of the sub-flows that showed differences in the user's flow depending on if keypair they wanted to import was on just one or multiple devices (we no longer need the ability for the user to select which device to import from in the event the keypair they want to import is imported on multiple of their synced devices).

<img width="809" alt="Screenshot 2023-08-21 at 16 30 19" src="https://github.com/status-im/status-desktop/assets/110033914/2502fd12-326c-4ef5-a2a7-891b94066106">

--

**4) QR dialog**

Given we no longer know which device to direct the user to in order to import specific keypairs, the QR dialog title now omits the device name:

New copy: `Scan encrypted keypair QR code`
Old copy: `Scan encrypted QR from [device name]`

In addition, we've taken the opportunity to make the CTA on how to generate the QR on the other device more descriptive:

New copy: `How to display the QR code on your other device`
Old copy: `How to generate the QR`

(This may also need to be rolled out to other sync/QR flows for consistency)

<img width="812" alt="Screenshot 2023-08-21 at 16 34 46" src="https://github.com/status-im/status-desktop/assets/110033914/ba218d3c-66f2-493c-b14c-34cc53228d4c">

--

**5) QR dialog - how to generate the QR on the other synced device instructions**

Given we no longer know which device to direct the user to in order to import specific keypairs, the QR dialog instructions on how to generate the QR on the other device now avoids directing the user to specific devices:

New copy: `1. Open Status on the device you want to import from`
Old copy: `Open Status on [mobile/desktop device name]`

Tabs have also been added to allow the user to select whether they want to import via QR from a desktop or a mobile device

<img width="810" alt="Screenshot 2023-08-21 at 16 39 32" src="https://github.com/status-im/status-desktop/assets/110033914/8f8931d5-13fd-4958-bd9b-7e61e7f8461f">

--

**6) Keypair import confirmation toasts **

These have been amended to avoid specifying the device name (which is largely redundant anyway considering the user will be mindful of which device they have just imported from via the QR route as they will have that device to hand to generate the QR on and scan from).

<img width="814" alt="Screenshot 2023-08-21 at 16 46 49" src="https://github.com/status-im/status-desktop/assets/110033914/80368309-354b-408b-bae7-02cfc4187d7c">

--

**7) Importing keypairs via the keypair context menu**

Related to point 3, the previous flows enabled the user to select which device they wanted to scan the QR from if the keypair they want to import was imported on more than one of their synced devices. Again, this option and associated dialog states have been removed.

<img width="843" alt="Screenshot 2023-08-21 at 16 53 11" src="https://github.com/status-im/status-desktop/assets/110033914/5b29ef03-273c-4da6-97ce-af640379c1a3">

--

**8) Importing keypairs at the account level (Navigating into an account page in Wallet settings)** 

'Import keypair to use account' : The description directly beneath this title has been modified to remove reference to a specific device:

New copy: `This account was added to one of your synced devices. To begin using this account you will first need import the associated keypair to this device. Click “Import missing keypair” above.`

Old copy: `This account was added to [device name]. To begin using this account you will first need import the associated keypair to this device. Click “Import missing keypair” above.`

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-539781&mode=design&t=x4R2VWW5FQXxodXP-4

<img width="1022" alt="Screenshot 2023-08-21 at 17 01 27" src="https://github.com/status-im/status-desktop/assets/110033914/16caaee9-a9e6-48f5-9804-c73a51d1e29f">

--

**9) Importing keypairs at the account level (Navigating into an account page in Wallet)**

Similar to 8, reference to the device name has been removed in the `Import keypair to use this account` panel at the top of the page:

New copy: `This account was added to one of your synced devices. To begin using this account you will first need import the associated keypair to this device.`

Old copy: `This account was added to [device name]. To begin using this account you will first need import the associated keypair to this device.`

<img width="1256" alt="Screenshot 2023-08-21 at 17 05 13" src="https://github.com/status-im/status-desktop/assets/110033914/550c661c-8568-499a-b6b9-4e578c500ae7">

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-539713&mode=design&t=x4R2VWW5FQXxodXP-4

- The flows here align with those discussed earlier in removing the device name from the dialog copy and removing the option to select which device to import from. The copy has been shortened slightly in addition:

<img width="826" alt="Screenshot 2023-08-21 at 17 10 02" src="https://github.com/status-im/status-desktop/assets/110033914/b86f2708-64a3-4a0b-a294-d6f1b6bda933">

--

**9) Importing keypairs after Waku backup**

A couple of amends to align with above copy/logic and fixes:

Amber warning copy:
New copy: `Restored from backup. Import keypair to use derived accounts.`
Old copy: `Restored from backup. Re-enter private key to use.`

Menu items: removal of `Import keypair from device via encrypted QR`

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-538750&mode=design&t=x4R2VWW5FQXxodXP-4

<img width="1289" alt="Screenshot 2023-08-21 at 17 12 31" src="https://github.com/status-im/status-desktop/assets/110033914/84b86b14-8bcc-4fc5-87f2-919feccc0f81">

--

As a final point, when talking about `associated accounts` in relation to accounts that are derived from a keypair, we are now changing this language to `derived accounts` as this is more accurate and allows us to familiarise users with this language which is used elsewhere in the app (eg choosing a derivation path when creating an account). We should use `derived accounts` anywhere we previously used `associated accounts` eg in the keypair context menu: `Remove keypair and associated accounts` becomes `Remove keypair and derived accounts`. I can create a separate issue for which screens/components this impacts if needed.

@saledjenic @John-44 @xAlisher @mariocnovoa

**Comment by saledjenic** [comment]
@benjthayer I've addressed all the points you raised above, here is a PR for it:
https://github.com/status-im/status-desktop/pull/11994

There is an attached video, in that PR, displaying the functionality of point 1. 
I've added a notification to meet the Figma request but also noticed that in the app other notification types have no CTA component on the right side as displayed here https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=18442%3A531561&mode=dev but they display checkmark button marking a certain notification read/unread, that's something we need to work on align.

**Comment by benjthayer** [comment]
> @benjthayer I've addressed all the points you raised above, here is a PR for it: #11994
> 
> There is an attached video, in that PR, displaying the functionality of point 1. I've added a notification to meet the Figma request but also noticed that in the app other notification types have no CTA component on the right side as displayed here https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=18442%3A531561&mode=dev but they display checkmark button marking a certain notification read/unread, that's something we need to work on and align app with the Figma.

Thanks @saledjenic yeah as discussed offline, it feels like there is a body of work needed to look holistically at the notifications centre, ensuring we have a designed system for handling all notification centre list item variants so they are capable of comfortably displaying a title, description, link/CTAs and read/unread marker. Likely this will be a later enhancement but will make a note of it and we can loop back when there is more time.
