### ISSUE TITLE
[Community Ownership] enable ownership change

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11964]
Once the Owner Token is transferred, the new owner needs to set the signer (control node).

### Acceptance criteria:
- [ ] Add `setupControlNode(communityID)` endpoint in messenger that will:
    - update community's Owner Token contract with new signer -> [setSignerPublicKey](https://github.com/status-im/communities-contracts/blob/8d3f185bf4d382d522815cff7cb2b70902cfffa8/contracts/mvp/OwnerToken.sol#L42)(identity.Public())
    - distribute CommunityDescription signed by new control node 
    - notify other devices about this device being the control node (this should be done in scope of https://github.com/status-im/status-desktop/issues/11962)
    - create and distribute encryption keys (this should be done in scope of https://github.com/status-im/status-desktop/issues/11963)

**Comment by endulab** [comment]
Some of the scope is already done by @cammellos.
I am going to work on the nim logic for setting signer public key, which is:
- presenting transaction fees;
- executing smart contract after authentication.

**Comment by dlipicar** [comment]
FYI https://github.com/status-im/status-desktop/issues/12403
