### ISSUE TITLE
Community direct invite doesn't show up sometimes 

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11967]
# Bug Report

## Description

Discovered using the Status Wallet team community.

Anthony, who's an admin, tried to invite me using a direct invite (using the modal), and I don,t see it appearing in the chat list.

I see those logs:
```
INF 2023-08-21 09:56:52.272-04:00 received                                   topics="signals-manager" tid=31513 file=messages.nim:70 signal=messages.new messageID=0x14a5194839afdaeb92a3e0f17e0217e6cc97b1cc75656584d14a76c0653eb37b
ERR 2023-08-21 09:56:52.274-04:00 requested community doesn't exists         topics="community-service" tid=31513 file=service.nim:715 communityId=0x04cfd95ab9ba683134943979e5fbecd1713298e2db9b81e46e9775d73bb3e4fe511d0774f5fd0d19d60ca252469baa4d21855a908edc3db47847fa2d6303ff
```

## Steps to reproduce

Unsure, but maybe it needs a community with an admin permission

Send the invite from the admin to a non-member.

Result: nothing shows in the chat

#### Expected behavior

The invite shows up

### Additional Information

- Status desktop version: master `3e8f710560149022d38aeb27227e8fa482de2d86` 
- Operating System: Ubuntu 20

**Comment by jrainville** [comment]
I've found the issue here.

It's that when an admin sends a direct invite (or shares the community), they use the encrypted community they already have in their DB, because they can't encrypt it themselves.

However, it then doesn't have the signature, so in `HandleWrappedCommunityDescriptionMessage`, `applicationMetadataMessage.RecoverKey()` returns empty (no signer). That then throws an error in the `HandleCommunityDescriptionMessage`.

I'm trying to figure out if it's better to just handle that on the receiver side and accept the description from the admin as is. Then I just need to figure out how to add the CommunityID to the message properly so that I can save it (the description doesn't have the ID).

Another option is to fix on the sender side, but that would require saving the control node's signature and sending it as part of the message. I'm not sure if that's even doable.

@mprakhov have you experienced that type of scenario when doing the Admin work? What do you recommend?

**Comment by mprakhov** [comment]
@jrainville I think I missed this scenario (admin invite)
Question - if the admin invites the user - can he send `CommunityDescriptionProtocolMessage`? This msg contains control node signature

**Comment by osmaczko** [comment]
> I've found the issue here.
> 
> It's that when an admin sends a direct invite (or shares the community), they use the encrypted community they already have in their DB, because they can't encrypt it themselves.
> 
> However, it then doesn't have the signature, so in `HandleWrappedCommunityDescriptionMessage`, `applicationMetadataMessage.RecoverKey()` returns empty (no signer). That then throws an error in the `HandleCommunityDescriptionMessage`.
> 
> I'm trying to figure out if it's better to just handle that on the receiver side and accept the description from the admin as is. Then I just need to figure out how to add the CommunityID to the message properly so that I can save it (the description doesn't have the ID).
> 
> Another option is to fix on the sender side, but that would require saving the control node's signature and sending it as part of the message. I'm not sure if that's even doable.
> 
> @mprakhov have you experienced that type of scenario when doing the Admin work? What do you recommend?

See: https://github.com/status-im/status-desktop/issues/11859. It was resolved already, `CommunityDescription` stored in database should be signed by control node, so that we can share it with others.

**Comment by jrainville** [comment]
> Question - if the admin invites the user - can he send CommunityDescriptionProtocolMessage? This msg contains control node signature

That's what is getting sent :thinking: Maybe something is wrong. I'll try to force a new description to get to my admin.

**Comment by jrainville** [comment]
The PR was merged two weeks ago. I'm pretty sure I used the owner + admin at the same time more recently than that. 

Is there a chance that we can still save the unsigned description by accident?

**Comment by mprakhov** [comment]
In rc14 - it is not possible, only if you had somewhere in the backup old non-signed CommunityDescription
Check `toProtocolMessageBytes()` fn - it is called on saving commuity to the DB, and it uses CommunityDescriptionProtocolMessage can be signed only by an ControlNode
