### ISSUE TITLE
If a user is asked by the owner for their shared addresses and they have none set up, we should prompt the user

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11974]
### Description

Dependent on https://github.com/status-im/status-desktop/issues/11969

In the above issue, the owner node will ask the users' nodes what their shared addresses are (all in the background). It,s possible however that the user never shared them (very old account), or more probable, they lost their account and re-imported.

If that's the case, when the user's node gets the signal to get the shared addresses, the app should add a notification of some sort asking to select the shared addresses.

I propose a notification in the activity center, but I'll leave it up to designers.

Once that prompt/notification is clicked by the user, it should make them go to the "edit shared addresses" modal, which will send the shared addresses correctly to the owner

### Acceptance Criteria

- There is a prompt/notification that is shown to users that have no shared addresses in their DB for a specific community when asked by the owner
- When clicked, that prompt goes to the edit shared addresses modal

**Comment by jrainville** [comment]
> Do we have a design for this?
> 
> cc: @jrainville @John-44 @benjthayer

No, this is something I "invited" we could say :laughing: 

I think just adding an AC notification that tells the user to send their shared addresses should be good. Clicking on it can open the "edit shared" addresses modal or the "join community" modal depending on the state.

**Comment by mprakhov** [comment]
was auto closed after status-go part merge, status-desktop still not merged due to e2e error

**Comment by John-44** [comment]
I don't think we need to fix this issue, it's one of the bits of scope we removed because all community members are required to share at least one address.

0.15 waku changes completely break backwards compatibility anyhow, and the statement that 'all community members have shared at least one address' will be true for all users of 0.15 and newer, so this issue has gone away
