### ISSUE TITLE
Closed communities shouldn't give access to the channel list

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11971]
### Description

Closed communities, ie communities with a permission to join, are encrypted. However, the channel list is part of the community description, so it is not. That means that anyone seeing the community can see what are the channels in the community, even if they are not joined.

We need to change this so that the channel list is apart from the shared community description. 

This requires a big change, so we need to discuss it thoroughly before implementing.

### Acceptance criteria

- The channel list isn't available to someone who has not joined a closed community
- Everything is normal for someone who is joined

**Comment by osmaczko** [comment]
Duplication of https://github.com/status-im/status-desktop/issues/12850 (already implemented).
