### ISSUE TITLE
Implement handling protocol external links

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#11982]
### Problem

When a user receives a transaction they don't know what provider it comes in most of the cases. Example are Paraswap, Uniswap and Hop.

### Desired Solution

**Use case: User receives a transaction from paraswap or some swap utility**

context: user is in the wallet activity tab
1. User receives a transaction using an tool such as paraswap
2. User views transaction
3. User clicks "Go to external"
4. Browser opens to go paraswap for that transaction

![image](https://github.com/status-im/status-desktop/assets/11396062/e9fb07d4-1f00-427e-803a-e128a1201b2f)

### Challenges & considerations

Currently there is no easy way or perhaps not way at all to figure out if an implementation comes from a specific protocol.

**Comment by glitchminer** [comment]
### **Proposed criteria**

### Story
> [!IMPORTANT]
> As a recipient of a transaction from a swap utility
> I want to know what swap utility was used
> So that I can view the provider and transaction details

### Scenario: Viewing transaction details involving a swap provider
```gherkin
Scenario: Viewing transaction details involving a swap provider
Given the user has a transaction from the compatible swap utility <compatible-utility>
When the user opens the transaction details
Then a section titled “Using” should be displayed
And the swap utility name and icon should be shown
And a “Go to external” button link should be shown

Examples:
| compatible-utility |
| ???                |
```

### Scenario: Visit website of swap utility
```gherkin
Scenario: Visit website of swap utility
Given the details of a transaction from the swap utility <compatible-utility> are open
When the “Go to external” button is clicked for the provider
Then the website of the provider detailing the transaction should open

Examples:
| compatible-utility |
| ???                |
```

### Scenario: Cannot determine swap provider
```gherkin
Scenario: Cannot determine swap provider
Given the swap utility cannot be determined
Then the “Using” section within the transaction details screen is not shown
```

### Scenario: Transaction was not from a swap provider
```gherkin
Scenario: Transaction was not from a swap provider
Given the details of a transaction not involving a swap utility are open
Then the “Using” section within the transaction details screen is not shown
```
