### ISSUE TITLE
Message is truncated when typing a hypen (-)

### ISSUE THREAD

**Issue by shinnok** [status-im/status-desktop#12007]
# Bug Report

## Description

Typing a single (or multiple) hyphen on a new line, in the chat input, truncates the text before it when sending the message.

## Steps to reproduce

See attached video:

https://github.com/status-im/status-desktop/assets/544446/0cc84475-d118-4aa7-8104-903a160b1b43

- Status desktop version: on current master:5fb057f61
- Operating System: macOS Ventura

**Comment by shinnok** [comment]
In the meantime I found out that several characters trigger this behavior as long as they stand on a single line, including `-` (hyphen), `=` (equal) and `\` (backslash).

Briefly trying to disable a several special input handlers such as for mentions and emojis in `StatusChatInput` did not change the behavior.

**Comment by caybro** [comment]
I believe this bug is not in StatusChatInput (or QML), it happens _after_ having been sent, so either NIM or status-go processing of the message

**Comment by noeliaSD** [comment]
> I believe this bug is not in StatusChatInput (or QML), it happens _after_ having been sent, so either NIM or status-go processing of the message

@mprakhov did you find it's just a ui isse then?

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
