### ISSUE TITLE
After accepting a contact request , the notification and the count doesn't clear-out

### ISSUE THREAD

**Issue by madhurrya** [status-im/status-desktop#12000]
### Description
Version 0.13.2
I have accepted a new contact request I got. But the notification related to that and the notification count for that doesn't automatically clear-out. 
![image](https://github.com/status-im/status-desktop/assets/110527567/80ebc4bb-1b21-4215-92da-d78640ebf85d)

**Comment by kounkou** [comment]
I tested that today with:

desktop as master commit https://github.com/status-im/status-desktop/commit/c995ff20b02a85142b8eddc23fc94cfe9c7926bf as of Wed Jan 31 20:22:27 2024

I was able to send a request, and accept on another instance of the application and the notification disappeared as expected.

[Screencast from 2024-02-06 10:24:05 AM.webm](https://github.com/status-im/status-desktop/assets/2589171/a420fd8a-5e38-43c7-a131-9852f4d23e9a)
