### ISSUE TITLE
Clickling UP arrow opens edit view for a message with image

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#12019]
# Problem

AFAIK, it's not possible to edit a message with an image. At least right-click doesn't provide such an option.
But we have a feature clicking UP arrow with active focus focus at `ChatInput` starts editing the last message. This also works for messages with image. 

Probably should be tested for other non-editable messages too.

**Comment by kounkou** [comment]
Reproduced it easily by sending a message with image and then trying a right click to edit
Working on a fix

![Image](https://github.com/status-im/status-desktop/assets/2589171/81e76486-d795-492d-a2b3-25c998e9c89c)
