### ISSUE TITLE
Transaction request bubble shows wrong title on state change

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#1201]
When a transaction request bubble changes its state to `declined`, it changes its title to `outgoing transaction` for the sender and the receiver, while it should still just say `Transaction request`.

<img width="263" alt="Screenshot 2020-10-19 at 18 42 26" src="https://user-images.githubusercontent.com/445106/96480665-d7089880-123a-11eb-98c2-dd558bf7234e.png">

**Comment by PascalPrecht** [comment]
Looks like this needs to be solved on a protocol level. /cc'ing @cammellos 
Whether or not a transaction is considered a "request" depends on its `commandState`. When a transaction is declined, it changes its state so we no longer know whether it originates from a request or not.

@cammellos do you think we could put that information into tx data coming from status?

**Comment by iurimatias** [comment]
closed in favour of issue #2915 and PR #2914
