### ISSUE TITLE
Update `requestCommunityInfoFromMailserver` to use shard info

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12015]
### Description

Needs https://github.com/status-im/status-go/pull/3944

With the new community shards, we need to update the `requestCommunityInfoFromMailserver` function to accept the shard info params, ie  `shard_cluster` and `shard_index`

### Acceptance Criteria

- Receiving an unknown community link, whether it has sharding on or off, should still fetch the info from mailsever and show the right data

**Comment by richard-ramos** [comment]
In this status-go PR, the API for requestCommunityInfoFromMailserver changes to receive an optional cluster and index:
https://github.com/status-im/status-go/pull/3944/files#diff-a594611e93b4c54ab50482007b066651b63e421f41b0e375e2949c8afa5e9d30R1173-R1178

**Comment by jrainville** [comment]
> In this status-go PR, the API for requestCommunityInfoFromMailserver changes to receive an optional cluster and index: https://github.com/status-im/status-go/pull/3944/files#diff-a594611e93b4c54ab50482007b066651b63e421f41b0e375e2949c8afa5e9d30R1173-R1178

Good to know, we just need to update our functions to call it with the right params then.

It seems like a breaking change right? Or does it work with empty values?

**Comment by richard-ramos** [comment]
We should set `nil` for those parameters
