### ISSUE TITLE
Status-desktop is hanging up when new request for join community is received from mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#12020]
# Bug Report
Follow up on https://github.com/status-im/status-mobile/pull/17091, reproduced during testing between status desktop master 25/08/23

## Steps to reproduce
1) Create a community with `Request to join`
20 Send a request from the mobile

#### Expected behavior
The request has arrived, can accept it

#### The actual behavior
app is hanging

https://github.com/status-im/status-desktop/assets/4557972/1ec7fe28-4f78-443c-8700-1df341b74f21

### Additional Information

- Status desktop version: master 25/08/23 (based on [0.164 go version ](https://github.com/status-im/status-go/tree/v0.164.0))
- Operating System: Mac OS
Console log: 
[message.txt](https://github.com/status-im/status-desktop/files/12456295/message.txt)
Geth.log: 
[geth (1).log](https://github.com/status-im/status-desktop/files/12456296/geth.1.log)

**Comment by jrainville** [comment]
Maybe it's related to this one? https://github.com/status-im/status-desktop/issues/11808
Anything that modifies the control node's community seems to make it freeze for me.

@churik or it's an actual hang in your case that never ends and is only triggered by mobile to desktop?

**Comment by churik** [comment]
hello @jrainville 
it's an actual hang that never ends - app is not responding anymore, I need to restart it.

Desktop > desktop has not been checked.

**Comment by jrainville** [comment]
Might be related to https://github.com/status-im/status-desktop/issues/12027 cc @endulab @MishkaRogachev

**Comment by MishkaRogachev** [comment]
It may be related with this [PR](https://github.com/status-im/status-go/pull/3674). @cammellos @ilmotta can I ask if the mobile client provide wallet addresses when sending request to join?

**Comment by endulab** [comment]
> Might be related to #12027 cc @endulab @MishkaRogachev

Unfortunately #12027 was tested today (by me and @micieslak) for both 0.14.x and master and seems to be ok. I am waiting for a feedback from @glitchminer. So, probably, we have a different issue here.

**Comment by ilmotta** [comment]
> It may be related with this [PR](https://github.com/status-im/status-go/pull/3674). @cammellos @ilmotta can I ask if the mobile client provide wallet addresses when sending request to join?

@MishkaRogachev, AFAIK the mobile client is not sending the addresses when calling the endpoint `RequestToJoinCommunity`.

**Comment by cammellos** [comment]
@MishkaRogachev @ilmotta I think it does now, as far as I can see, in develop, if we don't send any addresses, it will send all of them, but that's to double check

**Comment by ilmotta** [comment]
> @MishkaRogachev @ilmotta I think it does now, as far as I can see, in develop, if we don't send any addresses, it will send all of them, but that's to double check

@cammellos, I checked `develop`, but I never see us sending `addressesToReveal` to status-go. Maybe I'm looking at the wrong place. I checked:

- https://github.com/status-im/status-mobile/blob/b24dbe585bd4b97dee97fa63e4e29f5622ed6561/src/status_im/communities/core.cljs#L228
- https://github.com/status-im/status-mobile/blob/b24dbe585bd4b97dee97fa63e4e29f5622ed6561/src/status_im/communities/core.cljs#L242

**Comment by cammellos** [comment]
mmh,
we used to do that in status-go here https://github.com/status-im/status-go/blame/3e7d1a5f34183ea9f2ebf3b3d6a8143c98674d62/protocol/messenger_communities.go#L652 

but I think we still do that here:

https://github.com/status-im/status-go/blame/2b8543dfaec8708af2d2e328d948b3a0f2a17906/protocol/messenger_communities.go#L864


Basically if we specify `RevealedAddresses` it will only send those, if we don't it will send all of them, unless I am mistaken, but reading the code seems to do that. 
It would be easy to verify I guess, to check if addresses are sent

**Comment by churik** [comment]
Reproduced with a latest master (status-go v.0.166)

**Comment by jrainville** [comment]
Closing as completed, as develop already has this fix
