### ISSUE TITLE
Cannot join community

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12027]
# Bug Report

## Description

There is no way to join community. It does not work for both open communities and those secured with permissions.

![Screenshot from 2023-08-29 11-23-48](https://github.com/status-im/status-desktop/assets/20650004/2c25c7e2-0703-467f-85dc-e2ef05472ea0)

![Screenshot from 2023-08-29 10-45-29](https://github.com/status-im/status-desktop/assets/20650004/a12fd762-5aeb-4564-81aa-4a6aefffd324)

## Steps to reproduce

1. Create community
2. (Optionally) Create permission for becoming member
3. Send invitation to a contact
4. Send join request on the other end

#### Expected behavior
Community creator should see join request.

#### Actual behavior
Community creator see no pending request

### Additional Information

- Status desktop version: Master
- Operating System: Mac, Linux

**Comment by endulab** [comment]
Branch: release/0.14.x
- no request to join - OK
- request to join - OK
Branch: master
- no request to join - ?
- request to join - ?

**Comment by glitchminer** [comment]
Closing as no longer reproducible. 

In the latest version of 0.14 (RC3) this seems to have reverted to the previous behaviour of taking up to around 5 seconds for the "membership request pending" message to clear and the user to become a member of the community.
