### ISSUE TITLE
Mint button is disabled when owner token exists

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12044]
# Bug Report

## Description

The mint token button is disabled even though the owner and TM tokens already exist

![image](https://github.com/status-im/status-desktop/assets/50769329/5fe03780-4309-4b4a-ab0f-bb2df44cffc1)

## Steps to reproduce

Launch 0.14 RC3
Navigate to token settings
Find that mint is disabled

#### Expected behavior

Mint should be enabled when the owner and TM tokens exist already.

#### Actual behavior

Mint is disabled

### Additional Information

- Status desktop version: 0.14.0 RC3
- Operating System: Mac

**Comment by iurimatias** [comment]
the fix for this is included now
