### ISSUE TITLE
Community Settings - no action buttons in members list

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12042]
# Bug Report

## Description

Actions like kick or ban should be available from the community member's list.

Related figma: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=3707-375018&mode=design&t=7VupdnfQoNWbGRzC-0

![Screenshot from 2023-08-30 14-29-16](https://github.com/status-im/status-desktop/assets/20650004/2a5a326f-c246-4c35-8051-699b615f6f95)

## Steps to reproduce

1. Create community
2. Invite somebody
3. Go to community settings, members

#### Expected behavior
There are actions available on hover

#### Actual behavior
There is no action available

### Additional Information

- Status desktop version: Master
- Operating System: Linux

**Comment by jrainville** [comment]
This might be my fault. I made it so that an admin can't kick/ban another admin or TokenMaster, but maybe I messed it up for normal users.

Let me know if you have questions.
