### ISSUE TITLE
Community image and banner should be mandatory

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12045]
# Bug Report

## Description

When creating a community setting a logo and banner should be mandatory. This is not currently the case.
Previously fixed here but may not have been included in release https://github.com/status-im/status-desktop/issues/11234

![image](https://github.com/status-im/status-desktop/assets/50769329/79ec131b-ff32-451c-a3c8-69ceefea01ec)

## Steps to reproduce

Start the process to create a community

#### Expected behavior

Next button is not enabled until banner and logo are set.

#### Actual behavior

Only name and description are mandatory

### Additional Information

- Status desktop version: 0.14 RC3
- Operating System: Mac

**Comment by caybro** [comment]
It is mandatory in release builds only

**Comment by glitchminer** [comment]
> It is mandatory in release builds only

Thanks @caybro, do you know if we have a list somewhere of these differences from release? It feels like the number of them is increasing.

**Comment by glitchminer** [comment]
Closing. Behaviour is expected in local build and is OK in release build.
