### ISSUE TITLE
Transaction bubbles don't update their state to pending/completed

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#1205]
These cases don't seem to be handled at the moment. When signing and sending a transaction, the transaction bubble is not udpated to `pending` or `completed` for both, sender and receiver.

**Comment by PascalPrecht** [comment]
This might not be an issue and needs to be verified again. The reason we didn't get any state updates was because we aren't receiving any blocks at the moment from infura.

**Comment by iurimatias** [comment]
note: possible that PRs #2315 and #2321 fix or help with this

**Comment by PascalPrecht** [comment]
Seems like there have been more changes in the messages. The transaction bubbles don't seem to work as intended anymore. When trying to send a transaction and the address is being requested, the **receiver** gets the "Sign and send" button which is backwards. This needs fixing. Created https://github.com/status-im/status-desktop/issues/2413 accordingly

**Comment by jrainville** [comment]
@saledjenic  You are already working on the chat transactions. Do you think you already cover this issue with your work?

**Comment by saledjenic** [comment]
@jrainville yes seems this is similar to [this issue](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/2720) which is assigned to me. I haven't started yet with that part, but yes, I will fix that.

**Comment by jrainville** [comment]
Ok cool, I won't start working on my issues until you have something so that I can check if you fixed those issues as well

**Comment by iurimatias** [comment]
closed in favour of issue #2915 and PR #2914
