### ISSUE TITLE
[Discord history import] Translate error messages into user friendly messages

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12098]
We need to translate these messages into user friendly errors:

Incorrect format:
<img width="1840" alt="Screenshot 2023-09-06 at 10 53 34" src="https://github.com/status-im/status-desktop/assets/47811206/b3ec6cad-1b50-4443-9bf5-44a191a9123f">

Missing file:
<img width="1840" alt="Screenshot 2023-09-06 at 10 56 06" src="https://github.com/status-im/status-desktop/assets/47811206/82a4edcd-fcb6-47af-84ef-a8d70aabe01c">

Empty file:
<img width="1840" alt="Screenshot 2023-09-06 at 11 06 25" src="https://github.com/status-im/status-desktop/assets/47811206/ca932c24-7101-444f-8204-bafd0d70ce3e">

_Originally posted by @alexjba in https://github.com/status-im/status-desktop/pull/12060#discussion_r1316900351_

Please see the discussion above for more context. The error messages can't be translated because the UI is receiving a string error messages instead of an error code. This error message could be confusing for the user.
Figma design for error messages: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?type=design&node-id=37281-294595&mode=design&t=rpapF1XibwDiSUVT-0

**Comment by iurimatias** [comment]
descoped for now
