### ISSUE TITLE
Discord channel import: move category selection to UI by using ItemSelectionModel

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12099]
# Bug Report

## Description

Originally raised in: https://github.com/status-im/status-desktop/pull/12060#discussion_r1315660210

This approach should give better separation of concerns and possibility to instantiate functional ui component without reimplementing selection logic.

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone

**Comment by noeliaSD** [comment]
Moved to next milestone due to team capacity and priorities.

**Comment by noeliaSD** [comment]
Candidate for stabilization phases

**Comment by iurimatias** [comment]
descoped for now
