### ISSUE TITLE
community link keeps unfurling even though community is already known

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#12100]
# Bug Report

## Steps to reproduce

1. copy the invite link
2. paste in the chat

result: unfurling keeps loading forever, even though I already have the community info since i'm the owner...

![Screen Shot 2023-09-07 at 9 09 02 AM](https://github.com/status-im/status-desktop/assets/176720/c05bd226-fa02-46ee-8661-eba2aadaf868)

**Comment by iurimatias** [comment]
this happen when pasting the link

**Comment by jrainville** [comment]
This is because this is an old link format. IMO, we should close this issue as that link format is not available anymore.
