### ISSUE TITLE
Wallet: Community token logo and amount improperly displayed in wallet

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12110]
# Bug Report

## Description

In the mint asset form we define `Decimals (DP`:

![image](https://github.com/status-im/status-desktop/assets/20650004/95db39fa-8edb-4eff-8e20-8d3d775680a4)

This `DP` value is intended to be used only on the UI side to control how many decimal places user should see and use when providing amount. Under the hood every unit is divisible in the same way as `ETH`. 1 unit is 10^18 base units.

Let's take a look how asset look in `Tokens` section in community settings:

![Screenshot from 2023-09-08 11-46-33](https://github.com/status-im/status-desktop/assets/20650004/68c7f912-f47a-400b-93c0-41d429339c94)

The total supply is `9,000000001`, `DP` is 10.

In the wallet the asset is presented as follows:

![Screenshot from 2023-09-07 14-21-41](https://github.com/status-im/status-desktop/assets/20650004/152b1c56-8df0-4520-afb3-66395d9e5ed1)

The balance is displayed as `900 000 000` what is `9*10^8` or `9*10^(18-10)`. The `DP` value is improperly taken into account to present the balance. The actual amount in base units should be divided by 10^18 (that value is used consistently for all community assets). `DP` should be used only to control how many decimal places we show.

The other question is if the wallet should present the total supply. Is it equal to owner's balance for that token?

## Steps to reproduce
1. Create community
2. Mint owner token and token master
3. Mint community asset, define some finite amount and DP
4. Go to wallet

#### Expected behavior
Asset should be visible with proper artwork and balance

#### Actual behavior
There is no artwork visible, balance is incorrect

### Additional Information

- Status desktop version:
- Operating System:

**Comment by alaibe** [comment]
@micieslak regarding the balance, is the decimals correctly set in the contract?

Could you link the contract so that I can verify that?

Regarding the artwork. This is something that hasn't been worked on yet.

`The other question is if the wallet should present the total supply.`
Design is not final here yet. but i doubt we will make a special case for community token

**Comment by micieslak** [comment]
> @micieslak regarding the balance, is the decimals correctly set in the contract?

From what I know it's fixed to be divisible as ETH, 1 unit is 10^18 base units. Decimals specified in the form are only for UI.

> Could you link the contract so that I can verify that?

I don't know the contract. @endulab would know for sure (he's off currently).

> Regarding the artwork. This is something that hasn't been worked on yet.

Ok, its minor thing.

> `The other question is if the wallet should present the total supply.` Design is not final here yet. but i doubt we will make a special case for community token

So the currently presented value seems to be incorrect, right?
