### ISSUE TITLE
Community channels member list issue 

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#12114]
# Bug Report

## Description

<img width="1325" alt="Screenshot 2023-09-11 at 12 52 29" src="https://github.com/status-im/status-desktop/assets/2522130/890f78f7-4b23-452f-83d5-569624e41cc1">

The problem is reproduced periodically in the `Status CCs` community when performing the following actions on the control node:
- Adding new community members
- Kicking/Banning community members

Instead of displaying all members of the community in the channel, only some (last?) members of the community appear there. All channels break at once.

The problem was found while working on https://github.com/status-im/status-desktop/issues/12046, but it was found that when the control node is updated to 0.14, the list of community members is restored normally. See comment [here](https://github.com/status-im/status-go/pull/3996#issuecomment-1708908041).

Adding a new community member sometimes restores the correct list of community channel members, but after a while the problem may reappear.

Also note: 
- The community member sheet looks normal, only the channel member list is broken
- I did not succeed to reproduce this issue with status-go tests and fresh communities. It's most likely that this only appears in older communities

**Comment by iurimatias** [comment]
This happened just now, I invited someoen to the CC community, and upon approval the member list shows up again, while before this it was just 4 members. However later it's quite possible it will revert back to 4 members since that what has happened before. so to summarize:

- Member list on the sidebar eventually shows up just a few members, and these are all members that have been accepted recently, since the update, so ti seems the two are related
- After accepting a new member, the sidebar shows the correct member list again, but reverting again.

**Comment by caybro** [comment]
> This happened just now, I invited someoen to the CC community, and upon approval the member list shows up again, while before this it was just 4 members. However later it's quite possible it will revert back to 4 members since that what has happened before. so to summarize:
> 
> * Member list on the sidebar eventually shows up just a few members, and these are all members that have been accepted recently, since the update, so ti seems the two are related
> * After accepting a new member, the sidebar shows the correct member list again, but reverting again.

Yup, I can see the full member list at this very moment; will report back what happens later/tomorrow when I've restarted the app :)

**Comment by iurimatias** [comment]
After restarting just now, it's back to only a few members

**Comment by MishkaRogachev** [comment]
Short update: At the moment, the community channel members list still shows the same members, but there is an interesting point:

<img width="1308" alt="Screenshot 2023-09-13 at 01 32 48" src="https://github.com/status-im/status-desktop/assets/2522130/794215c5-2037-4c2a-84bc-ce61d5634561">


Since the latest status-desktop releases of 0.14 use the develop status-go branch, [Patrick's fix](https://github.com/status-im/status-go/pull/3942) was not present in them. And now there is no way to revert status-desktop the status-go branch 0.14, since we don't have downward migrations.

So I made a [PR](https://github.com/status-im/status-go/pull/4019) with this fix and additional logs here. @iurimatias built it yesterday and ran it on the Status CCs community control node. The list of community channel members is working and the logs show the correct number of users when adding and removing community members, but now the clients don't get this information: I can see old number of community members (200) and only a few members in the community channel members list.

Using the same version with logs, I can observe that I do NOT get the message (do not see logs) in handleCommunityDescription, although in previous versions I definitely saw this message with the wrong number of channel members but the correct number of community members

**Comment by jrainville** [comment]
> Since the latest status-desktop releases of 0.14 use the develop status-go branch, https://github.com/status-im/status-go/pull/3942 was not present in them. And now there is no way to revert status-desktop the status-go branch 0.14, since we don't have downward migrations.

The goal was for that fix to be cherry-picked in the release branch once Iuri updated the control node. Have you done that? Maybe it fixes the issue?

**Comment by MishkaRogachev** [comment]
> The goal was for that fix to be cherry-picked in the release branch once Iuri updated the control node. Have you done that? Maybe it fixes the issue?

I want to believe it is, but until we fix the CommunityDescription, it can't be confirmed.

**Comment by MishkaRogachev** [comment]
Most likely hypothesis:
The size of CommunityDescription is too large and is discarded at the protocol level, in each such message a list of channels is included, and each channel contains all members of the community, i.e. about 200 for Status CCs

**Comment by MishkaRogachev** [comment]
> Most likely hypothesis: The size of CommunityDescription is too large it may be discarded on the waku level. I in each such message a list of channels is included, and each channel contains all the members of the community, i.e. about 200 for Status CCs

Confirmed!
```
t=2023-09-15T10:27:50-0400 lvl=info msg="publishing message via relay" messageSizeInBytes=2,253,383 envelopeHash=0x941d2f25411b878558df213d496bb3a3fcea07c496476b1e29eb55dad9c64a3a pubsubTopic=/waku/2/default-waku/proto contentTopic=/waku/1/0xee3a5ba0/rfc26 timestamp=1,694,788,070,916,532,000
t=2023-09-15T10:27:50-0400 lvl=dbug msg="validation done; took 295.042µs"
t=2023-09-15T10:27:50-0400 lvl=dbug msg="dropping message to peer 16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D: unable to fragment RPC: message with len=2253416 exceeds limit 1048576"
t=2023-09-15T10:27:50-0400 lvl=dbug msg="dropping message to peer 16Uiu2HAmFy8BrJhCEmCYrUfBdSNkrPw6VHExtv4rRp1DSBnCPgx8: unable to fragment RPC: message with len=2253416 exceeds limit 1048576"
t=2023-09-15T10:27:50-0400 lvl=dbug msg="dropping message to peer 16Uiu2HAmDcjweJCSRgtFWoBzzZyBtsB9HgHJnRhShEEfmQhFBkw9: unable to fragment RPC: message with len=2253416 exceeds limit 1048576"
t=2023-09-15T10:27:50-0400 lvl=dbug msg="dropping message to peer 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD: unable to fragment RPC: message with len=2253416 exceeds limit 1048576"
```

**Comment by MishkaRogachev** [comment]
Some good news:

https://github.com/status-im/status-desktop/assets/2522130/a94dcd26-5262-43f4-abd4-5f81a025f7ee

**Comment by anastasiyaig** [comment]
There is still some work to be done to fix the description in other places, still in progress

**Comment by MishkaRogachev** [comment]
Small update on [this](https://github.com/status-im/status-go/pull/4054) PR:
* Fixed channels without permissions work fine
* Broke channels with permissions (hope not )
