### ISSUE TITLE
Crash when pinning message

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#12125]
# Bug Report

## Description

As the title

## Steps to reproduce

* Open chat
* Right click menu
* Pin message

#### Expected behavior

No crash

#### Actual behavior

![image](https://github.com/status-im/status-desktop/assets/11396062/79cc2212-08d3-4cef-8f42-6b4034d99b91)

Note that message is pinned on the receiver side

![image](https://github.com/status-im/status-desktop/assets/11396062/94b09533-93dc-47f1-a7d0-e62ceef4d43d)

### Additional Information

- Status desktop version: master
- Operating System: Windows

**Comment by jrainville** [comment]
Fixed here https://github.com/status-im/status-desktop/pull/12204
