### ISSUE TITLE
Local pairing: failed when scanning a QR code by desktop app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12126]
### Description

1. install the build on mobile app and create new account there
2. install the build on desktop app and select - I already use status -> Scan Sync code. Enable the camera access on your laptop and scan the QR displayed on mobile phone

![image](https://github.com/status-im/status-desktop/assets/82375995/6224b7da-059b-4a9d-a859-cc34461920ea)

![image](https://github.com/status-im/status-desktop/assets/82375995/10a1e4bb-e1f5-4372-a893-093843debbd3)

```
Experimental support for Apple Silicon
INFO [09-11|13:18:10.960] Status backend initialized               backend=geth version=0.166.8 commit=46c0063be IpfsGatewayURL=https://ipfs.status.im/
INF 2023-09-11 13:18:11.285+03:00 Version: 0.9.90                            topics="status-app" tid=13320404 file=nim_status_client.nim:189
INF 2023-09-11 13:18:11.285+03:00 Commit: 2d84e2a13                          topics="status-app" tid=13320404 file=nim_status_client.nim:190
INF 2023-09-11 13:18:11.285+03:00 Current date:                              topics="status-app" tid=13320404 file=nim_status_client.nim:191 currentDateTime=2023-09-11T13:18:11+03:00
INF 2023-09-11 13:18:11.285+03:00 starting application controller...         topics="status-app" tid=13320404 file=nim_status_client.nim:193
INF 2023-09-11 13:18:11.853+03:00 starting application...                    topics="status-app" tid=13320404 file=nim_status_client.nim:196
WRN 2023-09-11 13:18:11.857+03:00 Error decoding signal                      topics="signals-manager" tid=13320404 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
Debug: StatusApplicationDelegate::applicationDidFinishLaunching (:0, )
Debug: needed to resize (:0, )
Debug: size:  0 , new size:  8294400 (:0, )
WARN [09-11|13:20:51.641] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. connecting to 'https://10.77.128.175:51086' failed: dial tcp 10.77.128.175:51086: connect: operation timed out; "
WARN [09-11|13:22:07.646] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. connecting to 'https://10.77.128.175:51086' failed: dial tcp 10.77.128.175:51086: connect: operation timed out; "
```

**Comment by anastasiyaig** [comment]
@igor-sirotin please check this out when u can

**Comment by igor-sirotin** [comment]
@anastasiyaig hmm, this is interesting. 

Could you please give some more information:
1. Was this a real mobile device or a simulator?
2. Was the mobile iOS or Android?
3. Does `desktop -> mobile` pairing work with the same mobile/desktop configuration?
4. Are the devices in same local network?

**Comment by anastasiyaig** [comment]
1. real device
2. iOS, iPhone 14 Pro
3. yes, it works now , there were some issues, but now it should work (in latest master i hope)
4. yes, it is the same WIFI network i am on at home

Were not you able to reproduce it @igor-sirotin ? works for you?

**Comment by igor-sirotin** [comment]
@anastasiyaig Wanted to get the answer to the first 2 questions before testing 🙂  Will check this now

**Comment by igor-sirotin** [comment]
@anastasiyaig and the versions are like this, right?
- desktop: https://github.com/status-im/status-desktop/pull/12117
- mobile: `1.25.0`

**Comment by anastasiyaig** [comment]
should be like that, correct @igor-sirotin . Also, i remember that functionality  working to me some time ago...

**Comment by anastasiyaig** [comment]
@igor-sirotin so i did the following today:

1. i installed these builds for mobile (recent nightly) https://i.diawi.com/pWa4Av
and for desktop PR 12117 https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/view/change-requests/job/PR-12117/7/artifact/pkg/StatusIm-Desktop-230915-073952-f42899-pr12117-aarch64.dmg
2. i created new acc on mobile , went to syncing - click plus - reveal syncing code (which is looking as follows `cs3:35ejbpFgFufBpzkeX2JXY9NSEaUDVZL4JKygmqssNAquF2KZcujaLTMdRKZshKBz6TaC96VKUndn4E8Unu95YyxcmxzqwdYmAp2xWxQ18W5Z9yrTjbC13B4JfDWYQMjwYAUEGoGxfzgpd6z9BPFwevxfb61VfJZQ5:J8R:y938KF8CTZs67p7Fcuexsm9qRpdbPRTBitR1epubmddd:HP2pxjLtGQJXcYsdUejKifsNvu3CEYYDASba8bTj5cnc`)
3. on desktop app i selected I already use status - i have a sync code - enabled camera access - scanned the code from mobile device

As result desktop app was stuck for a while and then crashed with:
```
Traceback (most recent call last)
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/vendor/nim-taskpools/taskpools/taskpools.nim(171) workerEntryFn
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/vendor/nim-taskpools/taskpools/taskpools.nim(242) eventLoop
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/vendor/nim-taskpools/taskpools/taskpools.nim(193) runTask
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/vendor/nimbus-build-system/vendor/Nim/lib/std/tasks.nim(79) invoke
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/vendor/nimbus-build-system/vendor/Nim/lib/std/tasks.nim(121) runTask
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/src/app/core/tasks/threadpool.nim(60) runTask
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/src/app_service/service/devices/async_tasks.nim(19) :anonymous
/Users/jenkins/workspace/s_macos_aarch64_package_PR-12117/vendor/nim-status-go/status_go.nim(384) inputConnectionStringForBootstrapping
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by igor-sirotin** [comment]
@anastasiyaig, went with the same reproduce steps, worked for me 🤔 

<img width="1512" alt="Screenshot 2023-09-15 at 11 33 10" src="https://github.com/status-im/status-desktop/assets/25482501/ede53f04-0384-4b17-98d2-0e384dc231ea">

The only difference I see is that my connection string is much simpler (i.e. much less network interfaces on mobile):
`cs3:scrDLv3:GZS:eGg9mf9cwQdiLSXPXaWpiSH2tYytTSWUE94rpqYrmSHR:xrL3zvKWRtVyj9cXUftzX9HSn8BvBsh2Ryk5tcnQG2j`

Will DM you for further investigation.

**Comment by anastasiyaig** [comment]
i asked @VolodLytvynenko to reproduce the issue and he was not able to. It works for him. I am stuck with ideas :) 
i am on `Ventura 13.5.2 (22G91)` and ios `16.6.1` in case that matters. 
@Samyoul do u have any idea what can cause connection timeouts?

```
WARN [09-18|10:17:37.738] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. connecting to 'https://10.47.196.219:55918' failed: dial tcp 10.47.196.219:55918: connect: operation timed out; "
WARN [09-18|10:18:53.742] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. connecting to 'https://10.47.196.219:55918' failed: dial tcp 10.47.196.219:55918: connect: operation timed out; "
WARN [09-18|10:20:09.746] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. connecting to 'https://10.47.196.219:55918' failed: dial tcp 10.47.196.219:55918: connect: operation timed out; "
failed to connect to any of given addresses. failed to connect to any of given addresses. connecting to 'https://10.47.196.219:55918' failed: dial tcp 10.47.196.219:55918: connect: operation timed out; 
ERR 2023-09-18 10:20:09.750+03:00 failed to start bootstrapping device       topics="devices-service" tid=3368398 file=service.nim:191 errorDescription="failed to connect to any of given addresses. failed to connect to any of given addresses. connecting to 'https://10.47.196.219:55918' failed: dial tcp 10.47.196.219:55918: connect: operation timed out; "
```

**Comment by anastasiyaig** [comment]
after i restarted my devices , i am receiving this

```
WARN [09-18|11:07:37.873] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. %!w(<nil>)"
WARN [09-18|11:07:38.875] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. %!w(<nil>)"
WARN [09-18|11:07:39.877] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. %!w(<nil>)"
failed to connect to any of given addresses. failed to connect to any of given addresses. %!w(<nil>)
ERR 2023-09-18 11:07:39.885+03:00 failed to start bootstrapping device       topics="devices-service" tid=28013 file=service.nim:191 errorDescription="failed to connect to any of given addresses. failed to connect to any of given addresses. %!w(<nil>)"
```

**Comment by igor-sirotin** [comment]
## Input

Here're 2 connection strings I received from @anastasiyaig:

- desktop-generated connection string:
`cs3:scrCnsq:HU5:nERcW1qYamkXhvZyTgM9YPvNojA9bQwM3YnrsyraQZiK:5ouXLuUhuR95VDMBGk5zQ8bn1gZUav34qMQP6vsqjsyL`

Which contains:
```
netIPs = {[]net.IP} len:1, cap:1
 0 = {net.IP} 192.168.0.8
```

- mobile-generated connection string:
`cs3:35dFgoskQgRLN2ve6qhdNRDuLYxWGV41R4fRGbq4SEFi4RbtRHdqryuoCvXfokr8RopC7qn8E532fm84D1bKxCece1zmVMZd92Bfoaq3BSpdPeA6iRsDJAvPvRUjGiZgGS9N9AqmqKXzz5vuipB1wcGSgtw8J5eeV:Hdc:egLMxbFsX8jcP9TrGkiTAojEAAJR4TEykKnq4ekcVapy:3avyYaXYf4ALMWrkfBwteAKRZxkobXM25QuybXjj7awS`

which is:
```
netIPs = {[]net.IP} len:11, cap:16
 0 = {net.IP} 10.47.196.219
 1 = {net.IP} 10.118.57.100
 2 = {net.IP} 192.168.0.196
 3 = {net.IP} 10.47.196.219
 4 = {net.IP} 10.47.196.219
 5 = {net.IP} fd74:6572:6d6e:7573:d:80fd:8a7b:bac2
 6 = {net.IP} fd74:6572:6d6e:7573:c:80fd:8a7b:bac2
 7 = {net.IP} fd74:6572:6d6e:7573:d:80fd:8a7b:bac2
 8 = {net.IP} fd74:6572:6d6e:7573:c:80fd:8a7b:bac2
 9 = {net.IP} fd74:6572:6d6e:7573:d:80fd:8a7b:bac2
 10 = {net.IP} fd74:6572:6d6e:7573:c:80fd:8a7b:bac2
```

- The error says:
`failed to connect to any of given addresses. connecting to 'https://10.47.196.219:55918' failed: dial tcp 10.47.196.219:55918: connect: operation timed out`

## Conclusions

1. Obviously, mobile shows several IP duplications

2. Desktop tries to reach mobile only by `10.47.196.219`, which doesn't seem correct.
- I will check desktop configuration, if it even should try `10.47.196.219`
- I will check why desktop doesn't try `192.168.0.196`

**Comment by igor-sirotin** [comment]
Closed in https://github.com/status-im/status-desktop/pull/12191
