### ISSUE TITLE
Chats are always unread after startup

### ISSUE THREAD

**Issue by yakimant** [status-im/status-desktop#12133]
# Bug Report

## Description

I have 2 chats, which are always marked as 'unread' on startup.
See the screenshots:

---
![Screenshot 2023-09-12 at 11 37 01](https://github.com/status-im/status-desktop/assets/1529006/09696861-7d06-4cbd-9420-21c7c4fb4376)
---
![Screenshot 2023-09-12 at 11 37 15](https://github.com/status-im/status-desktop/assets/1529006/4717f379-e712-42b0-b66b-2c0c02e1362f)
---
![Screenshot 2023-09-12 at 11 37 20](https://github.com/status-im/status-desktop/assets/1529006/f8b87fce-b1e6-4ccf-804b-495f60de947f)
---

After reading them and restart - they are 'unread' again.

### Additional Information

- Status desktop version: macOS 13.4.1
- Operating System: 0.13.3

**Comment by iurimatias** [comment]
should be fixed

**Comment by igor-sirotin** [comment]
Already fixed I believe.

**Comment by yakimant** [comment]
Yes, It's not there in 0.15.0 anymore. Thanks!
