### ISSUE TITLE
[Communities] Add permissions related content in create/edit channel popup

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#12142]
### Description
Figma:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=2975-488707&mode=design&t=7bhUfNQmmUXSOz0g-4

<img width="538" alt="pp" src="https://github.com/status-im/status-desktop/assets/31625338/8dd42c1b-9c63-4a8f-b35c-4dc0be1d2092">

**Comment by noeliaSD** [comment]
This is marked as a "bug", but it is, indeed, a "feature" that allows a second alternative/flow for the "create channel permissions" functionality. In the current app, the user can already create "channel permissions", so there is no missing functionality, just a secondary way of doing it missing.

Following priorities of milestone `0.15.5` and team workload, this one is moved to the next iteration.
