### ISSUE TITLE
[Community Ownership] Expose needed community collectible properties to the UI

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#12155]
### Description
The following information is required to be shown from wallet collectibles view for community minted tokens: `Symbol`, `Total`, `Available`, `Transferible` and `Destructable` apart from the collectible `name`, `image`, `privilegesLevel` (meaning Owner, TMaster or just community token) and  `community color`.

[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=37206%3A87148&mode=design&t=sk06NxQNBlbYP6TV-1)

![Screenshot 2023-09-14 at 14 41 05](https://github.com/status-im/status-desktop/assets/97019400/a70d2691-11bf-4951-84d3-07a43b7d8ef9)

This task should be used to expose the needed `traits`to the UI.

**Comment by dlipicar** [comment]
For reference:

```
func TokenPermissionsByType(permissions map[string]*CommunityTokenPermission, permissionType protobuf.CommunityTokenPermission_Type) []*CommunityTokenPermission {
    result := make([]*CommunityTokenPermission, 0)
    for _, tokenPermission := range permissions {
        if tokenPermission.Type == permissionType {
            result = append(result, tokenPermission)
        }
    }
    return result
}


    CommunityTokenPermission_BECOME_TOKEN_MASTER       CommunityTokenPermission_Type = 5
    CommunityTokenPermission_BECOME_TOKEN_OWNER        CommunityTokenPermission_Type = 6
```
