### ISSUE TITLE
(shared addresses) wallet address selection broken

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#12152]
# Bug Report
A couple of things got broken in recent master (more specifically in the account selector, the upper part):
- nothing's preselected by default (_everything_ should be)
- the airdrop (auto) selection doesn't jump to next free address
- user should not be able to unselect all addresses
- addresses are duplicated on closing

![image](https://github.com/status-im/status-desktop/assets/5377645/fd7304b3-5f8f-4033-bd18-aa6b62054249)

- when the user makes a manual selection, the addresses get duplicated but without airdrop address :
![image](https://github.com/status-im/status-desktop/assets/5377645/6547b22c-2ee4-42f2-afda-61d22d76d464)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
CC @jrainville

**Comment by caybro** [comment]
Found the culprit (address vs ADDRESS, ie a string lower/uppercase problem), fixing :)

**Comment by John-44** [comment]
@caybro one account should *always* be marked as the airdrop account (it should be impossible for the user not to have any account selected as the airdrop account).

Also it should be impossible for the user to select zero accounts.

How to do both of these things is shown in @benjthayer designs

**Comment by caybro** [comment]
> @caybro one account should _always_ be marked as the airdrop account (it should be impossible for the user not to have any account selected as the airdrop account).
> 
> Also it should be impossible for the user to select zero accounts.
> 
> How to do both of these things is shown in @benjthayer designs

Yup, that's how I initially implemented but it got broken recently; PR incoming
