### ISSUE TITLE
Add Copy/Open Link as context menu actions on GIF message previews

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12183]
`Copy link` and `Open link` context menu actions are missing from GIFs messages in chat history.

These actions have been added for images by this task: #11941. GIF messages need to be aligned.

[Design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?type=design&node-id=21366-548550&mode=design&t=VLcRo32rlBbrVG8v-0)

<img width="1017" alt="Screenshot_2023-09-15_at_14 02 25" src="https://github.com/status-im/status-desktop/assets/47811206/a5bfab5f-cd71-4c11-910c-e238f4622fc6">

**Comment by caybro** [comment]
Note: regular unfurled image previews are completely missing the context menu:

![Snímek obrazovky z 2023-09-29 15-21-49](https://github.com/status-im/status-desktop/assets/5377645/46712228-b86b-42ec-a8ba-e4382bfa7618)
