### ISSUE TITLE
Adding Software Privacy Statement and Terms of Use into About section of Settings

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#12192]
Designs have been done for bringing the Status Software Privacy Statement and Terms of Use copy into the About section of Settings. 

Some small tweaks have been made to the `About` page menu, clarifying which items are embedded in the app vs linked externally.
<img width="1440" alt="About" src="https://github.com/status-im/status-desktop/assets/110033914/178bf427-0d41-4f9c-a6b5-28c1aa3bdb65">

Status Software Privacy Statement and Terms of Use inside the application. NB as noted in the Figma, the Status Software Privacy Statement and Terms of Use page designs are representative to clarify formatting. They should not be used as a reference for the final copy for these pages. The final copy should be taken from the docs linked in the relevant place inside the Figma. 

<img width="1906" alt="Screenshot 2023-09-18 at 14 06 41" src="https://github.com/status-im/status-desktop/assets/110033914/07947b62-8012-484e-81f5-4a83c16784eb">

Figma designs:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18977-144942&mode=design&t=iRaNpFuK2LYieyvN-4

**Comment by caybro** [comment]
@John-44 @benjthayer those two bundled docs (terms of use & privacy), should they be made translatable, or we just ship them as-is?

**Comment by caybro** [comment]
@John-44 can we please have the documents in Markdown? :) Loading from a MS Word doc is kinda hard in QML :D

**Comment by John-44** [comment]
> @John-44 can we please have the documents in Markdown? :) Loading from a MS Word doc is kinda hard in QML :D

[@ericnguyen101](https://github.com/@ericnguyen101) also wanted to make a few final adjustments to the copy, so I've just pinged [@ericnguyen101](https://github.com/@ericnguyen101) to let him know he has an opportunity to make these adjustments and I've requested that he then attaches an updated version in markdown format to this issue.
