### ISSUE TITLE
[Community sharding] UI for community owner to enable manual Waku static sharding for their community

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12197]
####  ✨ Enabling and creating sharded communities.

The manual community sharding is a feature that will only be used internally, by Status contributors. The community owner can enable this feature from Advanced settings. When it's enabled, the community sharding can be configured from the Edit community view. 

The community sharding popup will receive a shard number as input and will display the generated Pub/Sub topic based on the input. The Pub/Sub topic will be copied and sent to Jakubs to enable the community sharding. Once the community sharding has been enabled, the user will be notified through a toast message. Once the community sharding is enabled, the Edit community view will present this information and the `Modify` button is enabled. It opens the `Manage community sharding` popup where the user can disable sharding or edit the sharding configuration.

[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?type=design&node-id=37242-228672&mode=design&t=usJ5k36v95dGjmIR-0)

**Comment by caybro** [comment]
I believe @richard-ramos has some backend code for this?

**Comment by caybro** [comment]
FYI the respective backend work: https://github.com/status-im/status-desktop/pull/12033 and https://github.com/status-im/status-go/pull/3944
