### ISSUE TITLE
Random crashes on 0.14RC9

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#12195]
# Bug Report

## Description

After the findings from https://github.com/status-im/status-desktop/issues/11996 , RC5 worked fine for a while and I didn't get any more crashes. I upgraded to RC9 (StatusIm-Desktop-v0.14.0-rc.9-0e29a6-aarch64) last Friday and Status started crashing again today, very similarly to how it did before.

First a couple of random crashes, then insta-crashing on login.
I deleted my data folder, restored my acount from seed phrase, and now it lets me log in, but it crashes every couple of minutes without a clear reason. 

Attaching info from the latest crashes.

[nim_status_client-2023-09-18-152149.txt](https://github.com/status-im/status-desktop/files/12652121/nim_status_client-2023-09-18-152149.txt)
[app_20230918_150848.log](https://github.com/status-im/status-desktop/files/12652127/app_20230918_150848.log)

[nim_status_client-2023-09-18-152738.txt](https://github.com/status-im/status-desktop/files/12652120/nim_status_client-2023-09-18-152738.txt)
[app_20230918_152152.log](https://github.com/status-im/status-desktop/files/12652129/app_20230918_152152.log)

[geth.log.zip](https://github.com/status-im/status-desktop/files/12652133/geth.log.zip)

**Comment by alexjba** [comment]
Same here. I've been using it for about 1 week without any issues and today started crashing. I'm not a member of Status community and the account is quite light. I've noticed it started crashing when I've started to use pinned messages. It's definitely crashing when pinning a message. But it's also crashing randomly when I use an 1-1 chat that has pinned messages.

@dlipicar Do you think we're experiencing the same issue?

What I've noticed so far:
 - 1 chat opened: Account A and B
 - Account A pinned a message - Account A crashes
 - Account A reopens the app - Account B crashes
 
 When I've stopped playing with the pinned messages it became more stable.

**Comment by dlipicar** [comment]
@alexjba Your case sounds similar, though you might wanna check the backtrace to see if it's the same bug. Mine looked the same every time it crashed.

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   nim_status_client                        0x104574c1c 0x1044f8000 + 511004
1   nim_status_client                        0x10475855c 0x1044f8000 + 2491740
2   nim_status_client                        0x10484d714 0x1044f8000 + 3495700
3   nim_status_client                        0x1049cd56c 0x1044f8000 + 5068140
4   nim_status_client                        0x104672064 0x1044f8000 + 1548388
5   nim_status_client                        0x104850a44 0x1044f8000 + 3508804
6   nim_status_client                        0x104850ee8 0x1044f8000 + 3509992
7   nim_status_client                        0x104672064 0x1044f8000 + 1548388
8   nim_status_client                        0x104776f4c 0x1044f8000 + 2617164
9   nim_status_client                        0x1045e3210 0x1044f8000 + 963088
10  nim_status_client                        0x104d96f7c DOS::DosQObjectImpl::executeSlot(QString const&, std::__1::vector<QVariant, std::__1::allocator<QVariant>> const&) + 532
11  nim_status_client                        0x104d96b30 DOS::DosQObjectImpl::executeSlot(QMetaMethod const&, void**, int) + 364
12  nim_status_client                        0x104d96404 DOS::DosQObjectImpl::executeSlot(int, void**) + 100
13  nim_status_client                        0x104d96334 DOS::DosQObjectImpl::qt_metacall(QMetaObject::Call, int, void**) + 116
14  QtCore                                   0x107001bb0 QObject::event(QEvent*) + 596
15  QtCore                                   0x106fda7b8 QCoreApplicationPrivate::notify_helper(QObject*, QEvent*) + 124
16  QtCore                                   0x106fda410 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 292
17  QtCore                                   0x106fdb524 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 464
```

**Comment by jrainville** [comment]
I can confirm that pinning a message crashes the app on RC9.
I'm on it.

It's quite possible that it's the same thing you experienced @dlipicar if the pin signal is what crashes the app and you are importing the archive messages (you'd receive pinned messages)
