### ISSUE TITLE
When sending eth max value is not realistic

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#12215]
If I want send eth and click on max, there will be not enough eth for gas. Shall we in that case decrease the max value?

Note that if u are multichain, this is even more complex as we need to decrease the value for each chain.

Problem: at that stage router didn't run yet and we don't know what's the max value can be as it can change based on the routing

@John-44 @benjthayer any idea here?

**Comment by micieslak** [comment]
The related problem is defined here: https://github.com/status-im/status-desktop/issues/12146

**Comment by John-44** [comment]
@alaibe @micieslak I remember that somewhere in the designs or in a github issue (but I can't remember where, might be in and old design or old issue) it specifies that in the case of sending ETH, if a user clicks Max it doesn't actually populate the send field with Max, it populates the Send field with "Max - X amount".

I've had a hunt through both figmas and old issues trying to find the description of how this was supposed to work.  I can't find it, but I remember the idea so I'll rewrite here.

The logic below applies *per chain* (not per send transaction) so if a user is (for example) sending ETH to a recipient in a compound transaction on both Optimism and Mainnet, then this logic would apply to the user's balances for that account on Optimism and Mainnet.  e.g if the user has 1.5 ETH on Mainnet then 0.1 ETH would be left on Mainnet and if the user had 0.1 ETH on Optimism then 0.01 ETH would be left on Optimism.

- If user has > 1 ETH, then when user presses Max populate send field with "Max minus 0.1 ETH"
- If user has < 1 ETH but > 0.5 ETH, then when user presses Max populate send field with "Max minus 0.05 ETH"
- If user has < 0.5 ETH but > 0.1 ETH, then when user presses Max populate send field with "Max minus 0.025 ETH"
- If user has < 0.1 ETH but > 0.025 ETH, then when user presses Max populate send field with "Max minus 0.01 ETH"
- If user has < 0.025 ETH but > 0.005 ETH, then when user presses Max populate send field with "Max minus 0.002 ETH"
- If a user has < 0.005 ETH then the 'Max' button should be grayed out and inactive.

@alaibe @micieslak does that make sense?  Might be worth discussing on a quick call.  CC'ing @benjthayer

**Comment by alaibe** [comment]
@John-44 Alright, i missed or totally forgot that point. I get the general idea and it makes sense reduce Max - X amount
Now, something to consider, the user may click max before we know which chain is going to be used.

e.g: I have 5 eth, but this 5 eth are dispatch as followed:
3 eth on mainnet
1 eth on optimism
1 eth on arbitrum
That would mean according to your logic that max would fill in: 3-0.1 + 1-0.01 +1-0.01 is that right?

Now what I don't understand is the second part of the logic:
if user has > but < ....
gas is not dependent of the amount of eth that u send?
