### ISSUE TITLE
Discord import channel: implementation of method for importing single channel 

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#12238]
Part of: #12018 

### Description

The backend part of importing single community channel

### Acceptance Criteria

- Should create new channel in specified community
- ~~Should have possibilities to cancel the import~~
- Should have the way to inform the UI about the progress

**Comment by jrainville** [comment]
@anastasiyaig this one is ready for QA. Do note that the cancellation part has been moved to another issue, since it seems like it didn't work for communities either.

**Comment by anastasiyaig** [comment]
@lukaszso please take care of it
