### ISSUE TITLE
Wallet: Manual refresh option

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#12240]
@benjthayer @alaibe creating this to follow up on this feature we discussed to allow user to refresh assets/collectibles list manually.

Currently we update the list on startup and every 10 mins.

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

**Comment by Khushboo-dev-cpp** [comment]
@alaibe we do not have designs for this yet, do we move it to next cycle ?

**Comment by alaibe** [comment]
Let s keep it for now, in case it arrives during this cycle

**Comment by alaibe** [comment]
Closing as duplicated
