### ISSUE TITLE
Netwok prefixes included in copied wallet address

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#12248]
Click on the copy address button of an address popup should copy the address only, without network prefixes.

Improvement:
- that popup could have links based on selected networks like "View on Etherscan", "View on Arbiscan"...

![__1](https://github.com/status-im/status-desktop/assets/86303051/93ea0f06-457d-4023-9ade-e77873673b02)

**Comment by alaibe** [comment]
This is per design

**Comment by saledjenic** [comment]
@benjthayer wdyt about I suggested in the description of this issue?

**Comment by benjthayer** [comment]
> @benjthayer wdyt about what I suggested in the description of this issue?

WRT copying the link, I think the user would expect for it to be the entire string that is presented to be copied. So in the scenario where the user clicks copy on the multichain view, then I would expect the chain prefixed to be copied also. The user can always manually remove the network prefixes from the string before sending if they wish or go to the legacy format and copy the address from there if they don't want the prefixes. 

I like the idea of linking out to the relevant network explorers - I wonder if this functionality would be better housed in the account detail view in settings so we keep the dialog focused on sharing via QR/copying the address? WDYT?

cc @John-44

**Comment by alaibe** [comment]
Yes, regarding the copy, we agree.

The opening question is about link to explorer

**Comment by saledjenic** [comment]
I cannot agree with copying networks together with the account address, though that's my personal opinion. 🙂 

Reasons:
- What are the cases where we would need to use addresses with networks? (as far as I know, there is no such place in the app, usually users want to copy the address to share it or whatever)
- Based on the statistics, if one needs network prefixes he can add them, but in the majority of usages user will need to remove them (maybe in 100% of cases) I do agree that we have "Legacy" tab, but that's one click more, have to switch to it cause the default one is "Multichain" tab.

All this is just about UX from my point of view, classified as a minor thing.

**Comment by John-44** [comment]
> This is per design that the prefix are being copied

Yes correct, this is per design.

If the user has the "Legacy" tab selected, copying the address copies just the address without the multi-chain prefixes.

If the user has "Multichain" tab selected, copying the address copies the multichain address e.g. the address including the multichain prefixes.

I'm not clear what the issue is here, as we have the "Legacy" and "Multichain" tabs for exactly this purpose (what address format the user wishes to display a QR code for or copy)
