### ISSUE TITLE
Send popup, simple/advanced view do not show the same networks

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#12257]
![__1](https://github.com/status-im/status-desktop/assets/86303051/bcedc2c4-cf37-4ef3-8c1b-4f659b600ce6)

![__2](https://github.com/status-im/status-desktop/assets/86303051/ddfc7950-c433-4435-aa6f-a26a0e09e324)

**Comment by Khushboo-dev-cpp** [comment]
will be fixed under https://github.com/status-im/status-desktop/pull/12246
