### ISSUE TITLE
Tweak to local pairing messaging to clarify both devices should be on the same network

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#12261]
Small design tweaks to clarify both devices should be on the same network when syncing two devices:

1. `How to get sync code on...` added initial step of `1. Ensure both devices are on the same network` to both desktop and mobile views:

<img width="1440" alt="Syncing - 2 devices, not synced" src="https://github.com/status-im/status-desktop/assets/110033914/476c04bb-7d99-432b-9fcd-79abde8195a4">

<img width="1440" alt="Syncing - 2 devices, not synced-1" src="https://github.com/status-im/status-desktop/assets/110033914/3160a846-c54e-4354-89fb-cdaf1514d948">

Figma link:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=13665-208079&mode=design&t=lf4ZFh5LxxJDDJzo-4

--

2. Beneath QR code viewing area: Copy changed from `Ensure that the QR code is in focus to scan` to `Ensure both devices are on the same network`

<img width="480" alt="QR Scan2" src="https://github.com/status-im/status-desktop/assets/110033914/128905c9-3218-487a-948a-030f90568380">

<img width="480" alt="QR Scan" src="https://github.com/status-im/status-desktop/assets/110033914/527779cb-b9d9-4dff-afaa-db1f315d6faf">

Figma link:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=1930-136137&mode=design&t=lf4ZFh5LxxJDDJzo-4

--

4. Beneath `Paste sync code` input: New copy `Ensure both devices are on the same network`

<img width="480" alt="Enter Sync Code" src="https://github.com/status-im/status-desktop/assets/110033914/e9dd9622-1bc4-4192-875a-1e05f519d474">

Figma link:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=13578-276069&mode=design&t=lf4ZFh5LxxJDDJzo-4

cc @John-44 @igor-sirotin

**Comment by igor-sirotin** [comment]
There's a dashed rectangle design which I skipped to implement in the beginning.
There's a `ShareRectangle` component now which could be reused. Maybe do it in this issue?

**Comment by caybro** [comment]
> There's a dashed rectangle design which I skipped to implement in the beginning. There's a `ShareRectangle` component now which could be reused. Maybe do it in this issue?

Are you working on this? If not, I can take it, backlog empty mostly

**Comment by igor-sirotin** [comment]
@caybro  nope, I'm on another task 🙂

**Comment by igor-sirotin** [comment]
> backlog empty mostly
good job 💪
