### ISSUE TITLE
Not possible to select a link in the message

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#12266]
# Bug Report

I'd like to copy a link from the message. I'm selecting the link, but the selection is dropped as soon as the mouse is released.
Actually, any selection that **ends inside a link** is dropped. 

https://github.com/status-im/status-desktop/assets/25482501/20fd377a-27be-4604-a5af-d17710536f99

## Steps to reproduce

1. Send a message with link `Test message with a link https://github.com/. Try to copy the link!`
2. Any selection that **ends inside the link** will immediately disappear after releasing the mouse

**Comment by caybro** [comment]
CC @alexjba

**Comment by igor-sirotin** [comment]
Also, `Copy message` action in context menu doesn't work at all :(
Not sure if it makes sense to open a separate ticket.

cc @alexjba @caybro

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone
