### ISSUE TITLE
Fee estimation error during owner token minting

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12270]
# Bug Report

## Description

```
ERR 2023-09-27 11:43:58.397+01:00 rpc response error                         topics="rpc" tid=61513248 file=core.nim:36 err="\nstatus-go error [methodName:collectibles_deployOwnerTokenEstimate, code:-32601, message:the method collectibles_deployOwnerTokenEstimate does not exist/is not available ]\n"
ERR 2023-09-27 11:43:58.397+01:00 error doing rpc request                    topics="rpc" tid=61513248 file=core.nim:40 methodName=collectibles_deployOwnerTokenEstimate exception="\nstatus-go error [methodName:collectibles_deployOwnerTokenEstimate, code:-32601, message:the method collectibles_deployOwnerTokenEstimate does not exist/is not available ]\n"
```

![image](https://github.com/status-im/status-desktop/assets/50769329/84a6a050-3439-4591-a0ed-55024eaf4712)

## Steps to reproduce

Create a community
Attempt to mint owner token on mainnet
Observe unknown error with main account selected

### Additional Information

- Status desktop version: 0.14 RC 11
- Operating System: Mac

**Comment by endulab** [comment]
The name "collectibles_deployOwnerTokenEstimate" is wrong. It should be "communitytokens_deployOwnerTokenEstimate" (in src/backend/community_tokens.nim). I do not see anywhere "collectibles_deployOwnerTokenEstimate" in master.

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/status-desktop/pull/12283
