### ISSUE TITLE
Crash on leaving group chat

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12297]
# Bug Report

## Description

The app crashes when leaving a group chat.

1. Right click on chat
2. Select leave group

![image](https://github.com/status-im/status-desktop/assets/50769329/a5117f58-dcb5-4aca-ac61-3af96830c51a)

Console shows only limited info
`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

### Additional Information

- Status desktop version: 0.14 RC12
- Operating System: Mac

**Comment by caybro** [comment]
FWIW, can not reproduce on `master`

**Comment by jrainville** [comment]
Indeed, I only could reproduce on 0.14, but not on master

**Comment by jrainville** [comment]
Closing as it's fixed in master
