### ISSUE TITLE
Wallet -> Buying ENS results in error on Testnet

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12327]
### Description

Try to buy ENS name on Goerli, u need to have some STT:

1. open settings
2. open ENS
3. proceed with getting a name and sign a transaction

https://goerli.etherscan.io/tx/0x3d230b7fe6c049993f7a8a1a0f77e1776a4c0277fbc4bc5847d9e6d7dc602c5a

<img width="1061" alt="Screenshot 2023-10-03 at 17 27 56" src="https://github.com/status-im/status-desktop/assets/82375995/894ceea5-e42e-4dd6-bbaa-8c92129d7f3c">

**Comment by Khushboo-dev-cpp** [comment]
its weird cause for tx was unsuccessful but ens name was added



![Image](https://github.com/status-im/status-desktop/assets/60327365/bb362828-c7ee-4886-bf8b-7037335aab6b)
![Image](https://github.com/status-im/status-desktop/assets/60327365/4bfb3764-0eda-41ef-a0b1-a6f199ba24a6)

Nothing wrong from data going from UI to go-side, I am not the right person to explore further.
