### ISSUE TITLE
[Edit message] Crash when sending an edited message where the link preview was removed

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12323]
# Bug Report

## Description

The app is crashing after sending an edited message where a link preview was removed.
It seems the crash happens in `status-go`
NOTE: The receiver will also crash when receiving the edited message

## Steps to reproduce
1. Send a message containing one link preview
2. Go to message history and click edit on the previously sent message
3. Replace the url with any text
4. Hit Enter to send the message

#### Expected behavior
Message is edited and sent, no crash
#### Actual behavior
Message is edited and sent, app crashes
### Additional Information

- Status desktop version: Tested on 0.14RC12 and master https://github.com/status-im/status-desktop/commit/2d4e20585
- Operating System: MacOS

**Comment by kounkou** [comment]
As a conclusion to above analysis, we can conclude that the bug cannot not be reproduced on later version. And will therefore move the ticket accordingly if no more comments.
