### ISSUE TITLE
Wallet shows wrong balances per chain

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#12347]
I have assets only in Mainnet and Optimism, but the wallet shows me that I have assets on Arbitrum:

![image](https://github.com/status-im/status-desktop/assets/61889657/83419256-9ee4-41a6-a615-91b0b97a8740)

**Comment by alaibe** [comment]
@endulab can you share your address pls?

**Comment by stefandunca** [comment]
The issue of reporting `<nil>` as `rawBalance`, [fixed here](https://github.com/status-im/status-desktop/issues/12330), might be a side effect of the root cause for this issue.

**Comment by alaibe** [comment]
0x77b48394c650520012795a1a25696d7eb542d110

**Comment by anastasiyaig** [comment]
i can reproduce as well 
https://goerli.etherscan.io/address/0xf38d2cd3c6ad02dd6f8b68e0a7b2f959819954b6

https://github.com/status-im/status-desktop/assets/82375995/8179a2fd-7603-4cdb-94f6-e84060446358
