### ISSUE TITLE
Shared URLs data should never be used

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#12356]
### Description

As of yesterday, there was a decision not to use the shared URLs data in desktop and mobile apps. This is for status-web only.

> correct, other than generating the metadata that's encoded in these links, the metadata in these links should not be used anywhere in the app.
The app should always first look for the data in it's local DB, and if it's not there then fetch the data from waku
The only place that should use the metadata in these links is the 'web preview pages' (that are outside the scope of the mobile and desktop apps)

Currently we use it in a bunch of places:
- Send contact request popup
- Import community popup
- ... probably more places

cc @jrainville @borismelnik @MishkaRogachev

**Comment by jrainville** [comment]
Just to be sure, we still generate the URLs with all the data, we just do not want to use teh data in Desktop, right?

In other words, when sharing a profile or community, it will have the encoded data in the URL, but once pasted in the chat and unfurled, it should **not** use that data, and instead use the data in the DB or from waku?

**Comment by jrainville** [comment]
> And it's not only about chat link unfurling, but everywhere in the app.
E.g. this is how your profile link looks like in send contact request. The popup uses the URL-encoded data. Shouldn't be this way.

Good point. We should still support the "new" URLs in the ad hoc "New Chat" input, but not use that data. 

> And I think this should be fixed in 0.15

Yeah I'll try to schedule it for then, but if it's done in 15.5, it's ok as well I gues.
