### ISSUE TITLE
Client doesn't recognize that user is still member of a community after re-import from seed

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12368]
# Bug Report

## Description

Experienced by Jakub.

He re-imported his account from seed phrase on 0.14.0 and even though he still appears in the member list for the Status CC community, he cannot post and has to request access again.

## Steps to reproduce

0. Be part of a community
1. Import that account in another instance using seed phrase
2. Import the community or have it shared with you
3. See that you are part of the member's list but still can't post

#### Expected behavior

You get access to the community without having to request access again

#### Actual behavior

You need to request to join again

### Additional Information

- Status desktop version: 0.14.0
- Operating System: NixOS

**Comment by caybro** [comment]
Same happened to me in the past too
