### ISSUE TITLE
Support 125% UI scaling

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12360]
### Description

The 150% UI scaling is a bit too zoomed in for most and the 100% + Font scaling makes the chat look ok, but the rest of the UI is  a bit small.

Having a 125% UI scaling would be a good step in the middle.

### Acceptance Criteria

- There is a setting to put the UI zoom at 125%

**Comment by noeliaSD** [comment]
@jrainville this is considered as `bug` but I could see it as a new `feature`. Please, could you confirm which is the priority and if so, move it to the next iteration?

**Comment by jakubgs** [comment]
I'd call it a bug, but that's just me. Honestly, I like how Discord does it, where I can just `ctrl`+`-`/`+` to scale the UI at runtime.

But I assume that would be hard with QT.

**Comment by noeliaSD** [comment]
Following current priorities and team workload, it's been moved to the next interation.

**Comment by noeliaSD** [comment]
Following current priorities and team workload, it's been moved to the next interation.
