### ISSUE TITLE
[Wallet - Token management] Manage token entry in wallet settings

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#12376]
### Description

[Design](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=18139%3A133756&mode=design&t=dZJyXy1XapMmRQNJ-1)

![Screenshot 2023-10-06 at 21 16 50](https://github.com/status-im/status-desktop/assets/97019400/482eeb2c-91a0-4b5b-b861-85b5105045f1)

Just create the new `Manage tokens` entry in **wallet settings** and a new page for doing the development of the 3 differents tabs `Assets / Collectibles / Token lists`.

In the new page just add the tab bar with all the needed options.

**Comment by noeliaSD** [comment]
@caybro I'm working on https://github.com/status-im/status-desktop/issues/12374 so I also need to add this option in wallet settings. I'll do it too and will deal with conflicts / merge issues once we integrate, ok?

**Comment by caybro** [comment]
> @caybro I'm working on https://github.com/status-im/status-desktop/issues/12374 so I also need to add this option in wallet settings. I'll do it too and will deal with conflicts / merge issues once we integrate, ok?

Yeah sure, go ahead and take this issue
