### ISSUE TITLE
Add URL trust options when the user clicks on a link preview

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12388]
[Design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?type=design&node-id=23648-94932&mode=design&t=7IZmhnse7ELoQRHu-0)

When the user clicks a link preview a popup should be opened allowing the user to see the actual URL being opened. The user can also add the domain to the `trusted` domains so that this popup to never show up for the specified domain.

<img width="559" alt="Screenshot 2023-10-09 at 16 00 14" src="https://github.com/status-im/status-desktop/assets/47811206/de91e551-60f7-41e6-8002-4eef1ffb87c1">

**Comment by igor-sirotin** [comment]
backend task: https://github.com/status-im/status-go/issues/4132
