### ISSUE TITLE
Organization channels

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1238]
https://github.com/status-im/status/issues/3

needs designs specific to desktop (cc: @simonricoo ) but we can go forward with some frontend implementation given the designs for mobile, in particular to implement the end to end functionality.

WIP status-go PR https://github.com/status-im/status-go/pull/2046

**Comment by jrainville** [comment]
List of features to be implemented: https://docs.google.com/spreadsheets/d/1HIrp1xTO0obt9T-DgR0Kpv5U5pc9twloHGEcOo70lmw/edit#gid=0

**Comment by iurimatias** [comment]
closing as this is not an epic anymore as phase 1 is done, or we should create an epic for phase 2
