### ISSUE TITLE
[StatusChatInput] Left/Right keys wrongfully inserts or deletes mention

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12394]
# Bug Report

## Description

Trying to edit and navigate a text containing mention can trigger an unexpected mention or altering the mention.

### Steps to reproduce

1. Open a new chat with contact JohnDoe
2. Type `Hello @JohnDoe!`
3. Mention is inserted and the text looks like this `Hello @JohnDoe !`
4. Hit backspace twice to delete ` !`
5. Mentions suggestions is opened
6. Hit Left key

#### Expected behavior
Cursor moves before the mention
#### Actual behavior
A new mention is inserted to the right
### Steps to reproduce

1. Open a new chat with contact `JohnDoe1` and `JohnDoe2`
2. Type `Hello @JohnDoe1@JohnDoe2!`
3. Mention is inserted and the text looks like this `Hello @JohnDoe1 @JohnDoe2 !`
4. Delete the space between mentions
5. Mentions suggestions is opened
6. Hit Right key

#### Expected behavior
Cursor moves after the second mention
#### Actual behavior
The mention to the right is deleted

**Comment by iurimatias** [comment]
moving to 2.31 due to lack of space in this milestone, also tasks for chat input are in 2.31 currently

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
