### ISSUE TITLE
Deploy the Deployer contract to the Sepolia chain and add the address to status-go

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12404]
### Description

The Community Owner Token Deployer contract needs to be deployed to the Sepolia chain for us to work and test Community permissions on Sepolia.

After that, add the address to the status-go list

**Comment by jrainville** [comment]
cc @alaibe @0x-r4bbit @endulab

**Comment by 0x-r4bbit** [comment]
Deployed a version here: https://github.com/status-im/communities-contracts/pull/20

**Comment by 0x-r4bbit** [comment]
@jrainville Do we want this to be deployed on an L2 and/or L1 mainnet as well?

**Comment by jrainville** [comment]
> @jrainville Do we want this to be deployed on an L2 and/or L1 mainnet as well?

@0x-r4bbit thanks for asking. We do want it on Arbitrum and Optimism. We want it on Goerli and Sepolia too, but I think those last ones are already done. Obvsiouly, we want it on L1 mainnet too, but that should be already done too.

**Comment by alaibe** [comment]
Regarding Goerli/Sepolia we shouldn't forget the 4 L2 chains that goes with them

**Comment by 0x-r4bbit** [comment]
> Obvsiouly, we want it on L1 mainnet too, but that should be already done too.

This is not yet deployed on mainnet.
