### ISSUE TITLE
Wallet - Settings - Edit network: clicking revert to default closes the form

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12416]
### Description

https://github.com/status-im/status-desktop/assets/82375995/38cb2d6d-9c1d-43a1-87f1-b88ced8315b3

**Comment by anastasiyaig** [comment]
@alaibe it used to stay on the screen before (so when clicking Revert, u were able to stay on the form and check that values are reverted and RPC connection successful messages appear). Is it now expected (as on the video)?

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp can u please check on that? seems to be a quick UI fix :)

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig this is actually as per the new design https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-530358&mode=dev here :)

**Comment by anastasiyaig** [comment]
oh, thank you for clarification, however it is really annoying :D

**Comment by Khushboo-dev-cpp** [comment]
> oh, thank you for clarification, however it is really annoying :D

I guess in case you simply wanted to continue editing, I guess it could be. Want to discuss it with Ben?

**Comment by anastasiyaig** [comment]
Thats okay, can you please gimme a link with a ticket to implement a notification for successful revert? Or epic , sorry i got lost completely :D

**Comment by Khushboo-dev-cpp** [comment]
> Thats okay, can you please gimme a link with a ticket to implement a notification for successful revert? Or epic , sorry i got lost completely :D

That was done on my PR, wonder why it did not work for you :( 

https://github.com/status-im/status-desktop/pull/12367

**Comment by anastasiyaig** [comment]
i just missed that :D thank you!
