### ISSUE TITLE
Request to join pending list doesn't update itself correctly when control node goes back online

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12414]
# Bug Report

## Description

Experienced by @iurimatias (control node) and @alaibe (admin).

They both have pending request to join list that are different and don't properly reflect the state of the app.

For example, they still see some people in the pending list even though they are members.

## Steps to reproduce

I'm not sure. It probably has something to do with the admin approving the members while the control node is down.

#### Expected behavior

The pending members list in a community reflects the state. If someone is approved, they are in the members list only, if they are denied, they are in the "rejected" list. If they have not been touched yet, then they are in the "pending requests" list, same if they were approved by an admin with the control node not online.

#### Actual behavior

The pending requests list contains members that have already been approved.

### Additional Information

- Status desktop version: 0.14.0

**Comment by jrainville** [comment]
@mprakhov FYI, I fixed a problem here https://github.com/status-im/status-go/pull/4144
it's possible that it fixed this issue too or at least helped.

**Comment by mprakhov** [comment]
closing as done, all related issues resolved in the latest master
