### ISSUE TITLE
(shared addresses) broken icon background color

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#12427]
# Bug Report

![image](https://github.com/status-im/status-desktop/assets/5377645/9bf8ed37-f8aa-40d9-ad08-f4c39be0c614)

The error is quite obvious from the logs and source code:
```
Warning: qrc:/app/AppLayouts/Wallet/stores/RootStore.qml:55: TypeError: Property 'getColorForId' of object Utils_QMLTYPE_143(0x7de1d60) is not a function 
                         return Utils.getColorForId(colorId) (:0, )
```

and the respective source snippet:
```
d47ac2d5f7 (Khushboo Mehta        2022-02-21 18:07:16 +0100) import utils 1.0
e805a9bf26 (Stefan                2023-09-27 16:41:55 +0300) import StatusQ.Core.Utils 0.1
```

Meaning that now we have 2 imported modules going by the same name, `Utils`

### Additional Information

- Status desktop version: master (629d8b62b15a149aac3159fcbac6c2a739c55694)
- Operating System: linux

**Comment by caybro** [comment]
@stefandunca when you get a spare cycle pls :)

**Comment by stefandunca** [comment]
> @stefandunca when you get a spare cycle pls :)

Will do, thanks for the heads up
