### ISSUE TITLE
[StatusChatInput] Undo/Redo stack doesn't keep the cursor position

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12446]
### Description

This [task](https://github.com/status-im/status-desktop/issues/12181 ) implemented a custom Undo/Redo stack for `StatusChatInput` that keeps the undo stack even after manually updating the HTML in the input.
There is one regression where the `Undo` or `Redo` moves the cursor at the end of text instead of preserving the position.

Actual:
The custom stack is missing the cursor position and the cursor is always moved to the end of line on text Undo or Redo.

Expected:
The undo stack will keep the previous cursor position and properly restores it.

See this comment for more details:
https://github.com/status-im/status-desktop/pull/12262#issuecomment-1759241935

**Comment by caybro** [comment]
Also expected: there's a new test that verifies this :D
