### ISSUE TITLE
Update status/community/channel link previews on reception

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#12459]
# Description

Initially received `StatusLinkPreviews` are made to be instantly shown in the chat.
This information should be replaced with up-to-date verified data, because:
- the contact/community/channel info could have changed since sending the link preview
- the data might be malformed

So, as soon as we _see_\* a status link preview in chat, we should:
1. subscribe to corresponding contact/community/channel updates
2. as soon as the corresponding contact/community/channel is found in the database, replace the received link preview data with local data
3. when fresh information is received (becomes locally available), the corresponding card should automatically update

Also, for contacts we should _probably_\*\*:
- consider `localNickname`. It would make sense to see it in the everywhere in the app
- if the display name looks like an ENS name, verify it (and hide the identicon ring in the card if verified)

_\* we could do that automatically with the reception of the message, but we want to avoid instant massive requests of same data from many users, e.g. when a community link is posted to a channel with lots of users._

_\*\* This is my understanding, discuss with the team first._

# Implementation details

It would be great to implement this in status-go as much as possible, to make it simpler to test and maintain in both desktop and mobile. But this definitely requires the app to signal "hey, now I see the message, let's start 'the update procedure'".

# Acceptance Criteria

1. When a status link preview is received, it's shown in the chat (this is already done, just don't break this behaviour)
2. For status links, all UI card information should be "live" and updated with the latest information from Waku

**Comment by igor-sirotin** [comment]
cc @jrainville 
Letting you know that we have such a request, which seems quite important.
I've put it for 0.15.5 for now, because it doesn't look like we'll be in time to get this in 0.15. But we'll see how it's going, I'll do my best to take it to 0.15.

**Comment by jrainville** [comment]
Do we want to use the data in a Share URL? We discussed before that we don,t anymore, but this issue makes it seem like we do?

Anyway, whether we use it or not, the goal was always to subscribe to that topic and update with the latest info as soon as we get it, so that doesn't change at least.

+1 to do it in status-go. We have the annoying problem that we used to do it in QML and that caused us to request the same info multiple times by accident.

**Comment by igor-sirotin** [comment]
> Do we want to use the data in a Share URL? We discussed before that we don,t anymore, but this issue makes it seem like we do?

@jrainville hmmm, I don't see how it's related.
We still don't want to show any data from a Shared URL, except for ids and community shard.

**Comment by igor-sirotin** [comment]
> I guess I got confused by those lines:
> 
> > Initially received StatusLinkPreviews are made to be instantly shown in the chat.
> > This information should be replaced with up-to-date verified data, because:
> 
> I thought it meant "we want to first use the share URL data, then replace it with the data fetched from the store nodes", but I guess what you meant is more "in master, we currently display the Link Preview using the Data, but it should be replaced"?
> 
> Or maybe it's something else completely and you're talking about the Sender side Link Previews?

lol, it's not what I meant, sorry for that 😄 

"Shared URLs data" and "LinkPreview data" are different.
1. On the sender side, we fill the LinkPreview with information NOT from the shared URL
2. On receiver side, LinkPreview is a separate bunch of data for the given Shared URL.
Receiver gets BOTH shared URL and a LinkPreview for it.

So, what this issue is about:
1. First of all, when a message is received, receiver should take the LinkPreveiw data and show it.
2. Then subscribe to corresponding user/community/channel changes
3. Replace the received LinkPreview data with the local available one (as soon as it's avalable)

All these operations have nothing to do with Shared URLs 🙂 

@jrainville does this makes sense?

**Comment by jrainville** [comment]
Ok yeah it makes sense! Thanks.

> Then subscribe to corresponding user/community/channel changes
Replace the received LinkPreview data with the local available one (as soon as it's avalable)

At least we both agreed on this part :smile:
