### ISSUE TITLE
The Community channel list is sometimes empty

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12456]
# Bug Report

## Description

This issue is pretty random. It happens only sometimes and not always in the same channel.

Empty list
![image](https://github.com/status-im/status-desktop/assets/11926403/29e9630d-4ea9-4c73-a534-dc92d9c5fd94)

Same community, different channel
![image](https://github.com/status-im/status-desktop/assets/11926403/d06b72e0-8a19-43c6-8069-c77ab3a2bc90)

This community has a channel permission to view and post in `#dasfd`, so  that's probably the reason, though the owner should be in the member list at leats.

The issue also happens in communities with no permissions.

## Steps to reproduce

Unsure. Restarting the app often "fixes" the issue for the affected channel.

#### Expected behavior

The member list always appears

#### Actual behavior

The member list is sometimes empty

### Additional Information

- Status desktop version: 0.14.1
- Operating System: Ubuntu 20

**Comment by caybro** [comment]
Yeah, same here on master; same channels (within the same community) just lack the member list; restarting usually helps
