### ISSUE TITLE
"Welcome to Status Desktop Beta" popup appears on each start

### ISSUE THREAD

**Issue by yakimant** [status-im/status-desktop#12450]
# Bug Report

## Description
Even if I confirm, that I'm ready to use - it is appearing on every run:

![Screenshot 2023-10-16 at 11 31 57](https://github.com/status-im/status-desktop/assets/1529006/004e4198-7d2c-40f3-a4c8-5f8c4dbe8bc8)

**Comment by caybro** [comment]
This is by design, right? @benjthayer @John-44

**Comment by John-44** [comment]
> This is by design, right? @benjthayer @John-44

Yes correct
