### ISSUE TITLE
Empty community view after loosing privileged member permissions

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#12468]
# Bug Report

## Description

If I was a token master or admin in the community and had opened community settings after losing privileged permissions, the community became blank (white) and it is not possible to navigate there until restart

## Steps to reproduce

1. Create an Owner token and token master token
2. Send token master token to user1
3. user1 open community settings
4. control node destruct token master token for user1

#### Expected behavior

Return from community settings page to community navigation page

#### Actual behavior

We see blank community page

https://github.com/status-im/status-desktop/assets/117639195/0b87852f-8fb6-4a9a-9163-8ccdcdb0999a

### Additional Information

- Status desktop version: latest master
- Operating System: macos

**Comment by jrainville** [comment]
Fixed here https://github.com/status-im/status-desktop/pull/12830
