### ISSUE TITLE
Wallet - Settings: Testnet banner is not showing up

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12464]
### Description

https://github.com/status-im/status-desktop/assets/82375995/29ae71bf-f6ba-4374-a922-c885a0fcd3e6

**Comment by anastasiyaig** [comment]
alright, so the issue appears when `STATUS_RUNTIME_TEST_MODE` env variable is set to true. Perhaps there is something odd with this env variable config somewhere on backend

**Comment by jrainville** [comment]
> alright, so the issue appears when `STATUS_RUNTIME_TEST_MODE` env variable is set to true. Perhaps there is something odd with this env variable config somewhere on backend

Yeah I made it so that if the `STATUS_RUNTIME_TEST_MODE` is set, we disable all banners, because they were making the squish tests flaky. The reason is that the banners have animations that move the whole app, so some clicks would miss their target
