### ISSUE TITLE
[Link previews] Missing displayName for own profile 

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12477]
# Bug Report

## Description

Sharing my own contact doesn't load the display name.

https://github.com/status-im/status-desktop/assets/47811206/e4784633-9aea-4085-8953-97363d713c22

## Steps to reproduce
1. Copy your own profile url
2. Paste in chat input
3. Send the message

#### Expected behavior
1. The `displayName` is available in chat input link preview
2. The `displayName` is available in the message view
#### Actual behavior
The `displayName` is not available

**Comment by alexjba** [comment]
@igor-sirotin FYI

**Comment by igor-sirotin** [comment]
Yeap, I'm aware of that, the fix is on the way: https://github.com/status-im/status-go/pull/4169
