### ISSUE TITLE
Community description no longer updates properly when the Owner Token is minted

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12473]
# Bug Report

## Description

Found by @mprakhov . Feel free to edit this description to give more info.

Once a community mints the Owner Token, the community stops behaving correctly, because the description no longer updates correctly. It has something to do with the verification queue.

Additionally it won't be able to invite new members to the community and accept their requests to join

## Steps to reproduce

1. Have a community
2. Mint the Owner token
3. Update the community (edit name for example)
4. See that it doesn't update correctly for other members

#### Expected behavior

Community continues working properly and updating

#### Actual behavior

Community stops updating after minting

### Additional Information

- Status desktop version: master `1f8b44fbfbe71bcbe0140804ef273cb47d040d6d`

**Comment by anastasiyaig** [comment]
@mprakhov @jrainville shall we update the go version in master to reflect the change?

**Comment by mprakhov** [comment]
@anastasiyaig Yes, I can do it, but there is an issue with joining to the community with the minted owner token. I'll create a separate ticket for this as fix require discussion

**Comment by mprakhov** [comment]
ticket related to the invite
https://github.com/status-im/status-desktop/issues/12481
