### ISSUE TITLE
[Link preview] Missing title in image link previews

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12479]
# Bug Report

## Description
The file name should be presented as the title for image link previews. This is currently missing from the link preview model.

<img width="1692" alt="Screenshot 2023-10-19 at 13 13 41" src="https://github.com/status-im/status-desktop/assets/47811206/ab14a0ed-13b2-40df-9910-459e77667bb8">

## Steps to reproduce
1. Paste an image URL in the chat input (E.g https://png.pngtree.com/element_our/png/20180928/beautiful-hologram-water-color-frame-png_119551.jpg)
2. Allow the link preview to be loaded
3. Send the message

#### Expected behavior
When the link preview is loaded in the chat input, the file name is presented in the title
After sending the message a link preview is loaded in the message view and the file name is presented in the title
#### Actual behavior
When the link preview is loaded in the chat input, the preview title is empty
After sending the message a link preview is loaded in the message view. The preview title is empty

**Comment by alexjba** [comment]
@igor-sirotin I see two options for this:
1. Load the filename in status-go (I think this is the proper solution)
2. Parse the url at application level and get the filename.

IMO the filename should be loaded from status-go. This is why I've labeled this for messenger-team.

**Comment by igor-sirotin** [comment]
Thanks for spotting!
It should definitely be done in status-go. I'll probably even move the issue there 🙂
