### ISSUE TITLE
[StatusChatInput] Editing a link preview using mouse selection will delete the entire URL

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12478]
# Bug Report

## Description
When editing the hyperlink in status chat input after moving the cursor using the mouse will delete the hyperlink. It works fine when editing after the cursor has been moved using left/right keys.

https://github.com/status-im/status-desktop/assets/47811206/e132200c-737e-4757-8202-fa81ac7c848d

## Steps to reproduce
1. Insert an URL in statusChatInput
2. Move the cursor inside the url
3. Edit the URL

#### Expected behavior
The URL is edited
#### Actual behavior
The URL is deleted

**Comment by alexjba** [comment]
I tend to think it's not fixable with the current approach. The html anchors are buggy in qt TextEdit and I couldn't find any workaround. I've been looking for a workaround to replace the html anchors with other tags and add styling to the text, but the qt rich text processor is formatting the text in unexpected ways and the input tags are altered in such a way that the hyperlink cannot be properly identified.

E.g. One approach I've tried was to add styling to the hyperlink text using `style` and mark the hyperlink with anchors. It was promising, but the hyperlink is split after the first letter by the rich text processor `<span..>h</span><span ...>ttp://www.etc.ro</span>`

What we need in order to fix this is to find a way to style the urls and check all these requirements:
1. Add styling to substrings (this is easy and fully supported with `style`)
2. Identify each url that has been styled (there are changes that needs to be applied so that we can remove the styling. Sometimes a substring will remain when the url is invalidated and the styling needs to be removed). Something like html `class`, `id`, or any other way to preserve some unique metadata in the html tag. @caybro @micieslak @noeliaSD @alexandraB99 Any ideas on this? The ones already mentioned are not working.
3. Identify identical urls so that we can highlight them (add background color)
4. Move all white spaces outside of the url styling tag

**Comment by caybro** [comment]
@alexjba good news, I cannot reproduce here

[Záznam obrazovky z 2023-11-01 17-00-50.webm](https://github.com/status-im/status-desktop/assets/5377645/e579c6ed-0c82-49bd-803f-ebb02a78f587)

```
ltinkl@zephyrus14:~$ qmake -version
Using Qt version 5.15.10 in /usr/lib64
```

**Comment by caybro** [comment]
> @alexjba good news, I cannot reproduce here
> 
>  Zaznam.obrazovky.z.2023-11-01.17-00-50.webm 
> If I press left/right after having clicked on that link, the cursor jumps to start/end of the link
> 
> ```
> ltinkl@zephyrus14:~$ qmake -version
> Using Qt version 5.15.10 in /usr/lib64
> ```

Right... if you edit, the link gets erased :/

**Comment by alexjba** [comment]
@benjthayer One workaround I can think of is to select the hyperlink on click (the same way we're doing for mentions). WDYT of this workaround?

**Comment by benjthayer** [comment]
> @benjthayer One workaround I can think of is to select the hyperlink on click (the same way we're doing for mentions). WDYT of this workaround?

Thanks @alexjba , I think the priority here is to retain optimal usability for the editing of the URL. The user doesn't need to be able to click and visit the link from the composer given they have already copied it so it is in their clipboard or browser if they want to use/view the link. So even when the link is in the blue treatment indicating that the string is a URL, we can retain the type (I-beam cursor) when the user hovers the string as opposed to the pointer cursor. Much like Discord does... 

https://github.com/status-im/status-desktop/assets/110033914/746cb39c-fce8-41ef-b62e-a3a9644acf06

One thing to note is that we should also retain the double-click and triple-click functionality that we have in the app today.  eg if I double-click `currencies` or `status` in the following string, just that section should be highlighted so I can edit that segment: https://coinmarketcap.com/currencies/status/. 
(Triple-click should highlight the entire row of type in the composer)
