### ISSUE TITLE
Sending community invite is not working for the community with minted owner token

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#12481]
# Bug Report

## Description

If you try to invite the member to the community with a minted token owner - the receiver will not receive this msg

## Steps to reproduce

1. Mint owner token
2. Send an invite to the community to the user

Notes:
Invite members does not work due to `handleWrappedCommunityDescriptionMessage` https://github.com/status-im/status-go/blob/74c13fd3639079ed4534ea552b35d580f0e4bd87/protocol/messenger_handler.go#L2292-L2309
which will return null, because all communitiesDescriptions are going to the runOwnerVerificationLoop if owner token was deployed

If just skip this data (do not do an early return on `communityResponse == nil`), we'll get corrupted UI and this won't work too
![image](https://github.com/status-im/status-desktop/assets/117639195/365489ea-d044-4791-a094-09aa19d3df01)

If send a community link directly (https://status.app/c/CwuAChUKAzIyMhIDMjIyGAEiByM0MzYwREYD#zQ3shNbuVmNhcDGXEWiXzWyGV31uie7mwD3pZkjpjyMNRWyYT), the client gets an error

```
DBG 2023-10-19 14:07:20.852+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=65637631 file=core.nim:27 rpc_method=wakuext_requestCommunityInfoFromMailserver
DBG 2023-10-19 14:07:22.691+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=65637419 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
WRN 2023-10-19 14:07:26.792+02:00 Error decoding signal                      topics="signals-manager" tid=65637419 file=signals_manager.nim:43 err="Unknown signal received: backup.performed"
ERR 2023-10-19 14:07:35.960+02:00 rpc response error                         topics="rpc" tid=65637631 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_requestCommunityInfoFromMailserver, code:-32000, message:failed to request community info for id \'0x0211b4b265d0c6ce95c2fcf81e7608ab520a91154d880becc35d3186289f357628\' from mailserver: context deadline exceeded ]\n"
ERR 2023-10-19 14:07:35.962+02:00 error doing rpc request                    topics="rpc" tid=65637631 file=core.nim:40 methodName=wakuext_requestCommunityInfoFromMailserver exception="\nstatus-go error [methodName:wakuext_requestCommunityInfoFromMailserver, code:-32000, message:failed to request community info for id \'0x0211b4b265d0c6ce95c2fcf81e7608ab520a91154d880becc35d3186289f357628\' from mailserver: context deadline exceeded ]\n"
```

**Comment by mprakhov** [comment]
cc @jrainville , @igor-sirotin , @osmaczko 
Can we have some brainstorming on how we can fix that issue?

**Comment by osmaczko** [comment]
One of the solutions would be to mimic the same mechanism as with communities shared through links. When we receive the link, we display the card in a loading state and request community info from the mailserver. We could approach this in a similar way, displaying the loading state until we get the community response from the loop.

**Comment by mprakhov** [comment]
option 2: @igor-sirotin told, that we are planning to reject from `invite member` msg and send the community link directly, but in my case, it is also not working on the latest master
P.S. The problem with option 2 is : `invite member` msg can be still used on the mobile

**Comment by jrainville** [comment]
If we do have confirmation that we don't want to use the old invite api, where we send the community description in the message, then just sending the Community link and using the Unfurl mechanism is fine.

The advantage of using the `inviteToCommunity` flow though is that it doesn't rely on the store nodes. The description is already part of the message, so it's faster to share a community with someone. The tests also rely a lot on it (`advertiseCommunityTo` uses it).

So in the case where we want to continue using that mechanism, Patryk's idea is good. We use the same process as with links:
1. Check DB (or service cache in our case) if we know this community
   - if yes, display what we have
   - if no, show a loading state
3. In the meantime, subscribe to the community topic
4. Also in the meantime, unwrap the community description and validate that it is legit
5. If we get a more up to date description from the store nodes or the unwrapped description, we send a signal to the client and update the unfurl with the up to date data

In theory, this should be the same behaviour we have/we want when unfurling a community link

**Comment by jrainville** [comment]
> I'm not sure where and when, but I remember hearing from someone that we planned not to use this way of community invites in favour of sharing URLs. But I might be wrong 🙂

Let's ask John and the other from the Desktop team tomorrow to see if that's indeed the case.
