### ISSUE TITLE
Activity in "Loading" state forever

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#12496]
# Bug Report

## Description

Had some activity previously. Now I sent an NFT to Sale, checked out the pending transaction (which didn't seem to be recognized as an ERC721 send), clicked "new transactions"and now it's forever stuck there 
![image](https://github.com/status-im/status-desktop/assets/11161531/6c27dfa5-b074-4786-b118-390a1b4fefd4)

Had to restart Status to recover from this.

After restarting, pressed "new transactions" again, and it got stuck again...

This seems to affect other parts of the wallet. For example, Collectibles Details are not shown in this state.

@alaibe reported that changing chains several times also triggers this state

https://opensea.io/Maxstealth/collected
0x208b82B04449Cd51803fAE4B1561450ba13d9510

**Comment by alaibe** [comment]
![image](https://github.com/status-im/status-desktop/assets/491074/e78c3cca-1076-4393-9348-881a5dbe2af3)

Confirmed here

**Comment by anastasiyaig** [comment]
@Cuteivist i think we can close it for now

**Comment by anastasiyaig** [comment]
that might be something specific as i was not able to reproduce.. @dlipicar pls share some details if u can

**Comment by dlipicar** [comment]
@anastasiyaig Seems to be related to a combination of factors:
- Possibly a slow connection
- Account with lots of collectibles (for example, `0x1` or `sonnyf.eth`)
- Fetch using Opensea client (which has the longest required wait between API calls)

It's a different issue than the one originally reported, but the effect is similar. I think I know which improvements are needed, working on them right now.

**Comment by anastasiyaig** [comment]
Perfect , i will add a test for that specifically using these accounts in e2e, thank u

**Comment by anastasiyaig** [comment]
> @anastasiyaig Seems to be related to a combination of factors:
> 
> * Possibly a slow connection
> * Account with lots of collectibles (for example, `0x1` or `sonnyf.eth`)
> * Fetch using Opensea client (which has the longest required wait between API calls)
> 
> It's a different issue than the one originally reported, but the effect is similar. I think I know which improvements are needed, working on them right now.

@dlipicar any news on that one?

**Comment by dlipicar** [comment]
@anastasiyaig I have seen it get stuck for a while, but not "forever" anymore. However, it should never get stuck in the loading state for a noticeable time (there should be a couple SQL queries and that's it), so I'm still trying to figure out where this is coming from...

**Comment by anastasiyaig** [comment]
i am just wondering if the issue should be moved to 0.16 or whatever . I assume yes, because in general it happens on (lets say) certain known huge accounts right? @dlipicar

**Comment by anastasiyaig** [comment]
i moved that to 0.15.5

**Comment by Khushboo-dev-cpp** [comment]
https://github.com/status-im/status-desktop/assets/60327365/d4c5ce11-ad10-4303-99a4-b5d6b1ee8e49

Not reproducible on latest master with my account

**Comment by Khushboo-dev-cpp** [comment]
Used the 0x address and not reproducible still.

https://github.com/status-im/status-desktop/assets/60327365/9e160100-1b6b-43a7-9046-ddde5a88330d

hence closing this bug
