### ISSUE TITLE
Wallet: negative transaction fees

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#12499]
## Found in the first wallet dogfooding session

Sending `0.1` ETH looks like the recipient will receive more than sending `0.10059` ETH.
Max fees are negative (this might be related to the root cause)

<img src="https://github.com/status-im/status-desktop/assets/47554641/b8273cd2-10c8-442d-9de4-b78390c506ab" width="300"></img>

**Comment by alaibe** [comment]
Could you share advance network, it is possible on testnet

**Comment by stefandunca** [comment]
> Could you share advance network, it is possible on testnet

Here it is

![image](https://github.com/status-im/status-desktop/assets/47554641/fd310cd4-913c-4a27-a76b-3318e58119b3)

**Comment by alaibe** [comment]
As this is is a bridge tx and you receive more than you send, this is "expected" Don't expect to receive more in prod network
