### ISSUE TITLE
Explore creating a `QObject event emitter` in nim to pass events from the `controller` to the `model` via the `module`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#12511]
### Description

The goal of this task is exploring the idea of creating a `QObject event emitter` to register specific events in a `model` comming from it's source of truth (service events) via the `controller - module - view` layered architecture. 

Nowadays there is the `EventEmitter` global object that can be used for that propose but here the idea is to explore if it's possible to make it more **context oriented** and just use a specific event emiter object to deal with specific context events.

**Comment by Khushboo-dev-cpp** [comment]
Weve decided to not use event emitter in the model but instead using the module to inform the model (via view) hence closing this task
