### ISSUE TITLE
Explore if it's possible and it's worth it to make a module implement multiple interfaces

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#12512]
### Description

@Khushboo-dev-cpp to detail it better

**Comment by micieslak** [comment]
After a small research I've found this article: https://www.openmymind.net/Interfaces-In-Nim/ It seems to easily usable in our case.

**Comment by Khushboo-dev-cpp** [comment]
Closing this as if now as we have used the approach suggested by Michal.
