### ISSUE TITLE
segmentation fault when joining test community

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#12535]
# Bug Report

## Description

Segmentation fault when joining the test community displayed in Status

## Steps to reproduce

1. deleted `~/.config/Status`
2. reimport old profile (not using sync)
3. Click on "join" on the test community

#### Actual behavior

segmentation fault

### Additional Information

- Status desktop version: 0.14.1
- Operating System: Fedora

[0.14.1_segfault.txt](https://github.com/status-im/status-desktop/files/13113774/0.14.1_segfault.txt)

**Comment by jrainville** [comment]
I don't thin anyone reproduced it on master or 0.15 since then. Also, `requestCommunityInfoFromMailserver`, the possible culprit from the logs has been improved and fixed since then.

Feel free to reopen if you get this issue again
