### ISSUE TITLE
Wallet - Settings -> Account removal popup needs redesign

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12538]
### Description

**Current:**

<img width="1431" alt="Screenshot 2023-10-24 at 17 31 24" src="https://github.com/status-im/status-desktop/assets/82375995/ffda0a4b-8c5f-439c-b944-d4929734a411">

**Expected:**

![image](https://github.com/status-im/status-desktop/assets/82375995/0332f751-e869-4355-bcae-69a0480e4475)

**Figma flows:** 
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=18442-541620&mode=design&t=uvDadnnA4VTyUsus-4

**Comment by anastasiyaig** [comment]
@alaibe please add a milestone
@John-44 how urgent we need this?

**Comment by John-44** [comment]
> @alaibe please add a milestone @John-44 how urgent we need this?

this should probably be added to 0.15.5

**Comment by alaibe** [comment]
Agree for 0.15.5 that's a miss.
