### ISSUE TITLE
Chats are not loading if user was kicked and restarted the app

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#12558]
# Bug Report

## Description

Chats are not loading if the user was kicked and restarted the app

## Steps to reproduce

https://github.com/status-im/status-desktop/assets/117639195/4358472b-ee16-4326-8238-4d16dd355c43

Can be healed by reopening community invite

- Status desktop version: latest master
- Operating System: macOS

**Comment by jrainville** [comment]
Ah I know what's going on. It tries to go back to the last community it had opened, but it isn't there anymore.

IMO, we should still be spectating the community. It's probably a small bug on status-go's side. When we get kicked, we lose `joined`, but we should put `spectacted` instead.

**Comment by mprakhov** [comment]
I also observe that `joined` status is set to true, even if I was kicked (`getAmIMember`)
