### ISSUE TITLE
Failures during login

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12566]
# Bug Report

## Description

Currently getting a variety of errors when attempting to log in with an existing account. Using a fresh Status db does work. Troubleshooting done so far suggests it may be related to this change: https://github.com/status-im/status-go/pull/4182/files#diff-47ca94cb01ad5f1c83b007b21d3ade014ad6cf2d2ace4c26800e2015f94c60e4

![image](https://github.com/status-im/status-desktop/assets/50769329/9c52bc44-39ca-48b8-a889-627bd1d6ecd2)
![image](https://github.com/status-im/status-desktop/assets/50769329/f9a7edfb-bcc8-4561-9931-9b9b2c698acf)
![image](https://github.com/status-im/status-desktop/assets/50769329/a67dd695-4d80-48cb-b55f-d76f5d253a38)
![image](https://github.com/status-im/status-desktop/assets/50769329/6637f1d2-6e3f-4f53-a8d7-82704dfc8af5)
(password incorrect showing even when password is typed correctly)

### Additional Information

- Status desktop version: master (found in https://github.com/status-im/status-desktop/pull/12458 after rebase)
- Operating System: Mac

cc: @borismelnik

**Comment by jrainville** [comment]
@cammellos can you look at it. I think it's something that got introduced with your fix for ratchet keys.

**Comment by cammellos** [comment]
@jrainville looking into it, thanks

**Comment by cammellos** [comment]
@jrainville @glitchminer could you test using this status-go version please?

**Comment by cammellos** [comment]
https://github.com/status-im/status-go/pull/4223

**Comment by jrainville** [comment]
@cammellos it works for me with that PR!
