### ISSUE TITLE
Community token permission counts incorrectly the available amount of ETH

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#12565]
# Bug Report

## Description

I have 0.77 ETH on the balance, but I was able to join closed community which had a requirement of 1 ETH

P.S. During the available amount calculation, it can take Arbitrum and Optimism into account

## Steps to reproduce

1. Create a closed community
2. Add as a limit your amount of ETH + Arbitrum and Optimism

https://github.com/status-im/status-desktop/assets/117639195/ae1c6540-d796-4a8a-8b2f-054e437a7a20

- Status desktop version: latest master
- Operating System: macOS

**Comment by MishkaRogachev** [comment]
Confirm working as expected
<img width="555" alt="Screenshot 2023-12-13 at 18 38 33" src="https://github.com/status-im/status-desktop/assets/2522130/47d7e471-08a3-41b8-a154-98e3c9d44737">
