### ISSUE TITLE
Wallet -> Watched addresses: expand the right click context menu to fit new item

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12579]
### Description

Expected: `Exclude from total balance` option is fully visible in context menu

<img width="1512" alt="Screenshot 2023-10-30 at 15 43 38" src="https://github.com/status-im/status-desktop/assets/82375995/36074957-7dc0-48e0-b987-678cc91f1c56">

**Comment by anastasiyaig** [comment]
cc @Khushboo-dev-cpp @alaibe i put it to 0.16, but feel free to move

**Comment by caybro** [comment]
Most likely the `StatusMenu` is using some hardcoded width; otherwise it can adjust automatically to the longest item

**Comment by anastasiyaig** [comment]
@caybro but it is fixable, right? Or we keep certain width on purpose?

**Comment by caybro** [comment]
> @caybro but it is fixable, right? Or we keep certain width on purpose?

Yup right here:

https://github.com/status-im/status-desktop/blob/0f1b16006e0dd6674ca1471a04c9e7d00693cf54/ui/app/AppLayouts/Wallet/views/AccountContextMenu.qml#L21

Easy to fix, just remove it :)
