### ISSUE TITLE
API to retrieve a list of collectible headers by tokenID

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#12578]
### Description

As part of the profile showcase feature, you get a list of collectibles associated with an account through Waku.
@MishkaRogachev requested an API that will let him, given a list of collectible tokenIDs, fetch the list of CollectibleHeaders to be able to display them in a gallery.

**Comment by MishkaRogachev** [comment]
@dlipicar, thanks for opening this ticket! This api needed both for [12594](https://github.com/status-im/status-desktop/pull/12594) and [12510](https://github.com/status-im/status-desktop/pull/12510) PRs.

Use case: https://github.com/status-im/status-desktop/pull/12510/files#diff-11b7aeea25646fee77baaa252e3efdaa32306f130972fdc8d03603052050c68cR139

**Comment by dlipicar** [comment]
This is done!
