### ISSUE TITLE
Wallet -> Watched addresses: Stored section is empty for watched address

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12582]
### Description

**Expected:**

<img width="725" alt="Screenshot 2023-10-30 at 17 27 55" src="https://github.com/status-im/status-desktop/assets/82375995/9d7bd696-2c7e-467e-ba04-386fab3bafc7">

**Current:**

<img width="1512" alt="Screenshot 2023-10-30 at 17 29 09" src="https://github.com/status-im/status-desktop/assets/82375995/5da55be3-d368-470f-8226-8671aacb1575">

**Comment by alaibe** [comment]
I'd suggest to not display stored in case of watch only, as nothing is being stored

**Comment by anastasiyaig** [comment]
Perfect, @benjthayer @John-44 would that be ok? I was guided by designs however @alaibe has a valid point I cant argue with
