### ISSUE TITLE
Move Permission logic from the Create/EditChatPopup to the Nim model

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12609]
### Description

As implemented in https://github.com/status-im/status-desktop/pull/12160, the [new design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=2975-488707&mode=design&t=7bhUfNQmmUXSOz0g-4) was implemented to make it possible to create, edit and delete permissions inside the Create/EditChatPopup.

For added info, the permissions changes must not be confirmed (sent to status-go) until the user presses the `Create/Edit channel` button, so we need to keep a temporary state.

The problem is that the PR added a lot of logic to the QML part, because the PermisisonsModel was never meant to be used for that temporary context.

We need to improve the model to support it. Here is my idea:

> Maybe we add an enum in the permisisons model called `temporaryState`. That enum it can be `default/normal`, `created`, `edited` or `deleted`.
> With that, the UI can now  call Nim each time the user makes changes, but with a temporary flag.
> 
> Then, when the user clicks Next, the Nim code can check those that are not `default/normal` and apply the change to them (create them, edit them, etc).
> 
> If the user clicks cancel, instead we just undo everything.
> For created, it's easy we just remove it from the model.
> For deleted, it's also simple, we go back to normal.
> 
> The complex one is edited, because we need to go back to the previous data and I'm not sure where we can keep that data. Maybe we can just get that permission back from the cache.

With all these changes in place, the code will be much cleaner in QML.

**Comment by micieslak** [comment]
Hey, currently there is a logic for handling temporary state in QML, we have some reusable components like e.g. `ModelComparator` to track quite easily the dirty state. It works for previous views in settings. But it may not fit perfectly in the new use-cases, that's true.

But moving it to nim sounds also sub-optimal bc we increase complexity of nim part, which is intended to be dropped in the future. And it would be specific solution for that case, not reusable component. Because of that I would opt for handle it on UI side by custom c++ model or, ideally, by some generic models, especially https://github.com/status-im/status-desktop/issues/12690 seems to be useful here (maybe in combination with some other proxies - https://github.com/status-im/status-desktop/issues/12681).

**Comment by noeliaSD** [comment]
> Hey, currently there is a logic for handling temporary state in QML, we have some reusable components like e.g. `ModelComparator` to track quite easily the dirty state. It works for previous views in settings. But it may not fit perfectly in the new use-cases, that's true.
> 
> But moving it to nim sounds also sub-optimal bc we increase complexity of nim part, which is intended to be dropped in the future. And it would be specific solution for that case, not reusable component. Because of that I would opt for handle it on UI side by custom c++ model or, ideally, by some generic models, especially #12690 seems to be useful here (maybe in combination with some other proxies - #12681).

I think that in the measure of possible we should keep the nim side / backend just as a `UI data provider` and, again, if possible, try to manage user interaction in UI. However, I didn't go deep into this specific use case and could be wrong!

What @micieslak suggests makes sense to me and the `temporal model state` editing forms seems to be something very generic / usual in our app so we can think on, if with the existing utils it's not enough, creating a generic proxy or, a specific for this use case c++ model that helps on it.

**Comment by noeliaSD** [comment]
Following same reasoning than in here: https://github.com/status-im/status-desktop/issues/12142 this is moved to the next iteration.
