### ISSUE TITLE
SPIKE: investigate what is needed to bridge communities to Discord

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12610]
### Description

We used to have bridge between Status and Discord. The code is here: https://github.com/status-im/matterbridge/blob/d0c6e9d614d7a465eba20138b84ee7a3785795c3/bridge/status/status.go

The problem is it used to work with Waku V1, and also with public channels, which are not encrypted.

So this spike is to spend 1-2 days looking into this and our status-go code to make the bridge work with communities, and also with communities that are token gated, aka private communities (encrypted).

**Comment by endulab** [comment]
In the task I focused first on running a minimal status node and messenger with waku2.
I based on the old code (waku v1) but also looked at cmd/statusd to check how cli node can be run.
The most problematic was using correct imports and also use correct configuration settings.
The bridge now does: 
1. runs node
2. runs messenger
3. runs retrieve messages loop
4. receives messages from 1:1 chat

![image](https://github.com/status-im/status-desktop/assets/61889657/90fbc9d8-82ae-400c-8f6a-0b0ec0e20e43)

If we want to continue with the task, the next step will be to join and receive messages from communities.

FYI @jrainville @iurimatias 

Corresponding branch: https://github.com/status-im/matterbridge/tree/waku2

**Comment by jrainville** [comment]
Spike complete. The work shall continue in https://github.com/status-im/status-desktop/issues/12710
