### ISSUE TITLE
[Wallet - Token management] Add `Advanced settings` in new `Advanced Tab`

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#12611]
[Design](https://www.figma.com/file/eM26pyHZUeAwMLviaS1KJn/%E2%9A%99%EF%B8%8F-Wallet-Settings%3A-Manage-Tokens?type=design&node-id=305%3A139866&mode=design&t=HBhmgzvmu47bpf8o-1):

<img width="856" alt="Screenshot 2023-12-19 at 14 33 55" src="https://github.com/status-im/status-desktop/assets/97019400/3e81dd58-fde3-4c6e-9504-c80b15dfb50c">

**Comment by noeliaSD** [comment]
This task has lower priority than other tasks from the same EPIC. So potential task to be moved to the next iteration.

**Comment by noeliaSD** [comment]
Hey `UI team`. This is a potential task to be picked up without need of `Tokens Management` context. 
cc: @caybro, @alexandraB99, @alexjba, @micieslak

**Comment by noeliaSD** [comment]
Related: https://github.com/status-im/status-desktop/issues/13040
