### ISSUE TITLE
Wallet -> Watched addresses: wrong label for editing watched address button

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12623]
### Description

Current is `Edit account`:

<img width="1512" alt="Screenshot 2023-11-02 at 19 14 45" src="https://github.com/status-im/status-desktop/assets/82375995/f44a2c3c-4968-402b-a409-a731854c1551">

Designs show `Edit watched address`:

<img width="760" alt="Screenshot 2023-11-02 at 19 14 58" src="https://github.com/status-im/status-desktop/assets/82375995/1d57f67b-2ff9-4319-a4eb-d110158f038d">

**Comment by anastasiyaig** [comment]
@alaibe @benjthayer do we need different button labels for different accounts indeed? asking because it is shown like that in figma

**Comment by benjthayer** [comment]
> @alaibe @benjthayer do we need different button labels for different accounts indeed? asking because it is shown like that in figma

Thanks for flagging @anastasiyaig we did purposefully differentiate the terminology in the designs given the watched address is not technically an account in the full sense - watched addresses obviously have less functionality available so we decided not to use the word `account` in relation to `watched addresses`. The alternative would be to use `Remove` or `Edit` without specifying the type of address/account but that feels a little too abstracted to me perhaps.

**Comment by anastasiyaig** [comment]
perfect, thanks for clarifying!
