### ISSUE TITLE
[Message history] Replying to a message with emoji will show the emoji in html format

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12622]
### Description

The reply to a message containing emoji shows the emoji html instead of the emoji.

<img width="1015" alt="Screenshot 2023-11-02 at 17 24 48" src="https://github.com/status-im/status-desktop/assets/47811206/a4b5d099-e552-4e7a-aa61-4be026e8bcee">

Repro steps:
1. Send a message containing emoji ("I've used :D as emoji")
2. Reply to the message containing emoji

Expected behaviour:
The reply message contains the quoted message without html tags, showing the emoji

Actual behaviour:
The reply message contains the quoted message with html tags. The emoji is now displayed

**Comment by jrainville** [comment]
I feel like we're fixing this issue every 3 months :joy: :sweat_smile:

**Comment by alexjba** [comment]
> I feel like we're fixing this issue every 3 months 😂 😅

In this case I guess it's time for some tests along with the fix. 😄

**Comment by caybro** [comment]
Fixed with https://github.com/status-im/status-desktop/pull/12867
