### ISSUE TITLE
LinkPreviews mini cards in chat input should contain local nickname for contact links

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#12624]
> hmmm, there's something I might have missed. These sender mini cards should probably also contain "real" data, e.g. local nickname should be applied to contacts 🤔
> <img alt="image" width="349" src="https://user-images.githubusercontent.com/25482501/280111026-0172463e-fdcf-4769-aee9-a06c2f94f98f.png">

though @alexjba mentions this:
> Good finding. But IMO the link preview shouldn't contain any local data (E.g. sender side local nickname) 🤔
Wouldn't it introduce some inconsistencies between what the sender think he's sending and what the receiver is actually seeing? 🤔 I think it should be transparent.
IMO the only place where it's ok to use local nicknames is on receiver side.

_Originally posted by @igor-sirotin in https://github.com/status-im/status-desktop/issues/12613#issuecomment-1791498268_

**Comment by igor-sirotin** [comment]
@alexjba let's discuss this tomorrow on the call with John

**Comment by igor-sirotin** [comment]
@John-44 @benjthayer 

I don't remember us discussing this. Please correct me if I just forgot something.

Consider this case:
1. Alice, Charle: add `Bob` as a contact
2. Alice: rename `Bob` to `Bobby` (local nickname)
3. Charlie: rename `Bob` to `Bobo` (local nickname)
4. Alice: pastes Bob's profile link to a chat with Charle
❓ should Alice see `Bob` or `Bobby` in the link preview card in message composer?
5. Alice: sends link to Charlie
The link preview attached to the message will contain `Bob`, not `Bobby`, as local nicknames are ignored here.
6. ✅  Charlie: shows a received card with `Bobo`, as per local nickname (this is agreed and implemented).


On one side, the user should always see the local nickname, where ever it's shown
On the other side, as Alex pointed out, it creates an inconsistency between what Alice sees in UI (`Bobby`) and what's actually being sent (`Bob`).

What do you think of this?

**Comment by John-44** [comment]
@igor-sirotin good question, to answer:

> 1. Alice, Charle: add `Bob` as a contact
> 2. Alice: rename `Bob` to `Bobby` (local nickname)
> 3. Charlie: rename `Bob` to `Bobo` (local nickname)
> 4. Alice: pastes Bob's profile link to a chat with Charle
>    ❓ should Alice see `Bob` or `Bobby` in the link preview card in message composer?

A: I think Alice should see `Bobby` in the link preview card in message composer.  But let me know if you think otherwise, I'm not totally sure on this question.

> 5. Alice: sends link to Charlie
>    The link preview attached to the message will contain `Bob`, not `Bobby`, as local nicknames are ignored here.

This is fine

> 6. ✅  Charlie: shows a received card with `Bobo`, as per local nickname (this is agreed and implemented).

This is correct :-)

> On one side, the user should always see the local nickname, where ever it's shown On the other side, as Alex pointed out, it creates an inconsistency between what Alice sees in UI (`Bobby`) and what's actually being sent (`Bob`).
> 
> What do you think of this?

I think this is fine, because it's consistent behaviour.  User's are free to rename other users to anything they want, that's how they should see the other person's name, and it's only local to the user.

**Comment by igor-sirotin** [comment]
@John-44 thanks for you reply!

> A: I think Alice should see Bobby in the link preview card in message composer. 

I agree with this, I was tending to this desicion as well 🙂
