### ISSUE TITLE
Can't access community admin settings when received ownership.

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#12642]
When the transfer of community ownership finishes successfully (provided by https://github.com/status-im/status-desktop/pull/12532), the new owner can't access community admin settings, even after restart. Probably roles are not updated correctly.

![image](https://github.com/status-im/status-desktop/assets/61889657/86afa992-2672-435d-9c15-e3fea945f244)

**Comment by jrainville** [comment]
Fixed in status-go
