### ISSUE TITLE
Intercept and handle WalletConnect deep links

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#12641]
TODO:
- [x] Add a Status custom wallet to `Web3Modal` for testing deep linking as per [recommendation](https://github.com/orgs/WalletConnect/discussions/3978#discussioncomment-7676687)
- Configure explorer
  - [x] ~~(`status-app://wc:.....`) ![image](https://github.com/status-im/status-desktop/assets/47554641/306a0146-02be-4b87-809c-0f6ed72a88d3)~~
    - Requires implementation to be finalized and a release to be available for testing by the wallet connect team
  - [x] ~~Chains~~
  ![image](https://github.com/status-im/status-desktop/assets/47554641/29f88a49-73c7-463d-8cfb-2c7845bd963a)

**Comment by jakubgs** [comment]
I don't think WalletConnect will be able to accept our submission of changes without being able to test it:

![image](https://github.com/status-im/status-desktop/assets/2212681/5db14f7f-fa21-44b0-8c31-32811c16a110)
