### ISSUE TITLE
Performance issues when using ExpressionRole

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#12650]
### Description

While working with ExpressionRoles in a qml store we noticed that the performace is added in some cases.

```
     ExpressionRole {
                name: "jsArraySources"
                expression: model.sources.split(";")
            }
```

We also noticed that the startup time can be affected by this in case some uses it in a more complex scenario like the one mentioned above.

**Comment by caybro** [comment]
Not only in a store, any usage/introduction of an `ExpressionRole` inside a SFPM hampers the performance quite a lot

**Comment by micieslak** [comment]
Fixed by https://github.com/status-im/status-desktop/issues/13047
