### ISSUE TITLE
Crash when try to install uninstalled stickers pack

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#12664]
**1. Crash:**

Steps to reproduce:
- buy a new stickers
- uninstall it
- try to install it again
- app crash

<img width="428" alt="2" src="https://github.com/status-im/status-desktop/assets/86303051/ecdf3ddb-7de7-49fe-bf3b-26ff84cfa74c">

**2. Issue:**

Steps to reproduce:
- buy a new stickers
- use some stickers from the bought stickers pack
- uninstall stickers
- there are uninstalled stickers in the recently used stickers section, but there should not be any sticker that doesn't belong to the installed stickers displayed in that section

<img width="416" alt="3" src="https://github.com/status-im/status-desktop/assets/86303051/1503822e-f23e-480c-8cd2-49eef864e5c4">

**Comment by anastasiyaig** [comment]
@jrainville please fit it into any of milestones

**Comment by jrainville** [comment]
I'm putting it in 0.15 because we need to fix it before the full release, but I'm planning to move it to 0.15RC once the milestone is created.
The crash really needs to be addresses at least.

**Comment by anastasiyaig** [comment]
@jrainville ya there were several issues with transactions for stickers/ens, it was a paid package most likely

**Comment by jrainville** [comment]
I just tried with a bought pack and it didn't crash for me. It did have another issue though. When the pack is bought, if I uninstall, it goes back to the state where I can buy it. It doesn't realize I had already bought it. I had to restart the app. Then I could re-install without a problem. I'll fix that

**Comment by jrainville** [comment]
Ok, I was able to reproduce once. It seems very random, because it worked all the other times I tried.
The stack trace isn't that helpful either:
```
DBG 2023-11-09 14:42:59.115-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=408258 file=core.nim:27 rpc_method=stickers_uninstall
DBG 2023-11-09 14:42:59.118-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=408258 file=core.nim:27 rpc_method=stickers_installed
DBG 2023-11-09 14:42:59.120-05:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=408276 file=threadpool.nim:54 messageType=AsyncGetRecentStickersTaskArg:ObjectType threadid=408276 task="{\"$type\":\"AsyncGetRecentStickersTaskArg:ObjectType\",\"vptr\":94046774418944,\"slot\":\"onAsyncGetRecentStickersDone\",\"tptr\":94046718839904}"
DBG 2023-11-09 14:42:59.120-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=408276 file=core.nim:27 rpc_method=stickers_recent
DBG 2023-11-09 14:42:59.974-05:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=408275 file=threadpool.nim:54 messageType=InstallStickerPackTaskArg:ObjectType threadid=408275 task="{\"$type\":\"InstallStickerPackTaskArg:ObjectType\",\"packId\":\"0\",\"chainId\":1,\"hasKey\":false,\"vptr\":94046774418944,\"slot\":\"onStickerPackInstalled\",\"tptr\":94046718815248}"
INF 2023-11-09 14:42:59.975-05:00 shutting down...                           topics="status-app" tid=408258 file=nim_status_client.nim:173
INF 2023-11-09 14:42:59.975-05:00 logging out...                             topics="app-controller" tid=408258 file=app_controller.nim:287
Traceback (most recent call last)
/home/jonathan/dev/status-desktop/src/nim_status_client.nim(208) nim_status_client
/home/jonathan/dev/status-desktop/src/nim_status_client.nim(181) mainProc
/home/jonathan/dev/status-desktop/src/app/boot/app_controller.nim(324) delete
/home/jonathan/dev/status-desktop/src/app_service/service/stickers/service.nim(96) delete
/home/jonathan/dev/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(67) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:866: run-linux] Segmentation fault (core dumped)
```

**Comment by jrainville** [comment]
The crash is fixed here: https://github.com/status-im/status-desktop/pull/12675

I opened a new issue for the second problem since it's more minor: https://github.com/status-im/status-desktop/issues/12677

**Comment by saledjenic** [comment]
> @saledjenic I tried with a free pack and it doesn't reproduce, so just to be sure, in your case, it was a paid pack?

I've just tried with the latest master and yes, no crashes anymore, it might be some fixed by PRs merged in the meantime.

**Comment by jrainville** [comment]
> > @saledjenic I tried with a free pack and it doesn't reproduce, so just to be sure, in your case, it was a paid pack?
> 
> Yes, was a paid one. I've just tried with the latest master and yes, no crashes anymore, it might be some fixed by PRs merged in the meantime.

I think it's just that it's a very random crash. It was very hard to reproduce, but my PR makes sure it doesn't happen again
