### ISSUE TITLE
Unable to join token gated community

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12678]
# Bug Report

## Description

- Testnet
- Configure community to need 0.1 Eth to become a member
- Attempt to join the community
- User is not asked to authenticate to prove ownership of accounts being shared

![image](https://github.com/status-im/status-desktop/assets/50769329/7188eb1e-0116-4f1e-a762-12fa262f3ce7)

- Clicking on reveal account and request to join does nothing in app

Console
```
ERR 2023-11-09 20:48:55.172+00:00 communities:                               
tid=833901 file=module.nim:344 
err="unexpected call to join community function before all addresses are signed"
```

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by jrainville** [comment]
@alexandraB99 this seems like a UI issue. Can you have someone check it out? If it's on the backend, I can pick it back.
