### ISSUE TITLE
StatusQ: Create generic proxy model `GroupByModel`

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12683]
# Description

Proxy allowing grouping rows according to provided criteria. Grouped items are exposed by additional role holding submodel.

How the usage could look like:
```
    ListModel {
        id: srcModel

        ListElement {
            color: "purple"
            color2: "purple2"
            name: "a"
            extendedName: "abc"
        }
        ListElement {
            color: "red"
            color2: "red2"
            name: "b"
            extendedName: "abc2"
        }
        ListElement {
            color: "purple"
            color2: "purple2"
            name: "c"
            extendedName: "abc4"
        }
        ListElement {
            color: "purple"
            color2: "purple2"
            name: "d"
            extendedName: "abc2"
        }
        ListElement {
            color: "green"
            color2: "green2"
            name: "e"
            extendedName: "abc9"
        }
        ListElement {
            color: "green"
            color2: "green2"
            name: "f"
            extendedName: "abc9"
        }
    }

    GroupModel {
        id: groupModel

        sourceMode: srcModel
        submodelRoleName: "submodel"

        groupBy: "color"


        bypassRoles: ["color2"]
    }
```

The output model in intended to contain number of rows equal to number of unique values of role indicated via `groupBy` property.
Submodel is intended to be available via role name specified via `submodelRoleName` property.

By default output model contains two roles on top-level - the one specified in `groupBy` and the one containing model specified in `submodelRoleName`. However additional roles can be exposed in top-level model using `bypassRoles` property. The value comes from an arbitrary entry in the submodel so should be used whenever the role value is the same for all entries in submodel.

The output model then would be equivalent to model depicted below:
```
ListModel {
    id: groupped
    
    ListElement {
        color: "purple"
        color2: "purple2"

        submodel: [
            ListElement {
                color: "purple"
                color2: "purple2"
                name: "a"
                extendedName: "abc"
            },
            ListElement {
                color: "purple"
                color2: "purple2"
                name: "c"
                extendedName: "abc4"
            },
            ListElement {
                color: "purple"
                color2: "purple2"
                name: "d"
                extendedName: "abc2"
            }
        ]
    }
    
    ListElement {
        color: "red"
        color2: "red2"
        submodel: [
            ListElement {
                color: "red"
                color2: "red2"
                name: "b"
                extendedName: "abc2"
            }
        ]
    }
    
    ListElement {
        color: "green"
        color2: "green2"
        submodel: [
            ListElement {
                color: "green"
                color2: "green2"
                name: "e"
                extendedName: "abc9"
            },
            ListElement {
                color: "green"
                color2: "green2"
                name: "f"
                extendedName: "abc9"
            }
        ]
    }
}
```

**Comment by micieslak** [comment]
@iurimatias @alexandraB99 I think that it would be beneficial to finish this task. It has a big potential to improve performance and simplify UI code in various places, especially related to Wallet. The estimation here (3 points) its incorrect - it's big tasks, thousands line of code, component and tests. But it's like 80% done some time ago. So maybe we could reconsider finishing it in 2.29.0 to have ready for offsite and discuss it with a Wallet team.

**Comment by noeliaSD** [comment]
First, to complete this task: https://github.com/status-im/status-desktop/issues/14370 and after conclusions, if necessary, this task can be taken.
