### ISSUE TITLE
Naming of first and subsequent Wallet accounts 

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#12693]
Currently in development, the user's first Wallet account is auto-named `Status account`. This placeholder name should be changed to `Account 1` in order to align with mobile.

When the user subsequently creates a new account, that account should be named `Account 2`, with the number iteratively increasing by 1 for each new account thereafter.

If a user removes an account, this should not be taken into account in the generation of the placeholder name. I.e. if I create `Account 8` and then remove it, and then create a new account, this new account should have a placeholder name of `Account 9` not `Account 8`.

cc @pedro-et @Khushboo-dev-cpp @saledjenic

**Comment by saledjenic** [comment]
@benjthayer except for the default account, one that is created along with the Status account creation, there is no way to create an account without providing a name for it. So wondering what is a use case where the user can generate accounts one after another without providing an account name that the app needs to auto-generate names for them?

**Comment by benjthayer** [comment]
> @benjthayer except for the default account, one that is created along with the Status account creation, there is no way to create an account without providing a name for it. So wondering what is a use case where the user can generate accounts one after another without providing an account name that the app needs to auto-generate names for them?

Thanks @saledjenic , it's just a way of populating the name field so the user can progress without being blocked in the account creation flow. The user might want to add multiple accounts just to see how they all look in the UI when they first join Status and then go back to edit the names when they know what they want to do with those accounts later. Naming them `Account 1, 2, 3` etc is just a simple and common convention for this but open to other ideas of course :)

**Comment by saledjenic** [comment]
@benjthayer I agree, but do we have a design for that? That's not what we have in the app at this moment.
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12272-269323&mode=design&t=5oJ6UPHfZDHWYaet-0

**Comment by alaibe** [comment]
I believe we can prefill the account name input with the generation function?

**Comment by anastasiyaig** [comment]
Test run: https://ethstatus.testrail.net/index.php?/runs/view/15324&group_by=cases:section_id&group_order=asc&group_id=51467
Updated automated tests as well in https://github.com/status-im/desktop-qa-automation/pull/560
