### ISSUE TITLE
Unable to update to 0.15 RC 1 using existing db

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12694]
# Bug Report

## Description

- DB previously used with nightly build for 09 Nov.
- After submitting password on 0.15 RC1 observed a CPU spike to 519%

![image](https://github.com/status-im/status-desktop/assets/50769329/7a809b7f-df9d-459e-89bf-cadafc3b4cdd)

- Application then becomes unresponsive and sticks around 100% CPU while on the loading screen

### Additional Information

- Status desktop version: 0.15 RC1
- Operating System: Mac

for info, @jrainville

**Comment by endulab** [comment]
Related prs:
https://github.com/status-im/status-desktop/pull/12739
https://github.com/status-im/status-desktop/pull/12714

**Comment by jrainville** [comment]
@noeliaSD @endulab this issue was closed when the PR was closed, is that intended? The issue is fixed with those PRs?

**Comment by noeliaSD** [comment]
I don't know about this task but if the issue is solved by my previously closed pr, at least, [this one](https://github.com/status-im/status-desktop/pull/12739) should be integrated as well.

**Comment by endulab** [comment]
@jrainville @noeliaSD the pr from Noelia was checked by @glitchminer and it seems that the issue is fixed.
This is why I connected Noelia's pr with this issue. We agreed with Magnus that we can close this issue for now.
