### ISSUE TITLE
StatusQ: Create generic proxy model `WritableModel`

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12690]
# Description

Proxy decorating source mode with additional method(s) allowing to overwrite value of any property from the model. The temporary (dirty) state would be kept by the proxy, leaving source model unmodified.

Probably that kind of functionality could be done within single proxy with https://github.com/status-im/status-desktop/issues/12686 to have wide spectrum of operations not affecting source:
- reordering rows
- deleting rows
- changing existing values
- adding new rows (in-line with existing role names)

**Comment by noeliaSD** [comment]
First application for this proxy will be for this task: https://github.com/status-im/status-desktop/issues/12142
The consumer task has been moved to the next iteration.

Following priorities of milestone 0.15.5 and team workload, this one is moved to the next iteration too.

**Comment by alexjba** [comment]
It will be partially implemented in the first phase without the possibility to move rows. I can be extended afterwards to add move support.

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-desktop/pull/12838
