### ISSUE TITLE
[Bridge] Bridge status communities to Discord

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12710]
### Description

Continue the work started in the spike https://github.com/status-im/status-desktop/issues/12610

### Acceptance Criteria

- Messages sent to a Status community channel are bridged to a Discord community channel and vice-versa

**Comment by endulab** [comment]
TODO:
- use new shard settings
- test token-gated community

**Comment by endulab** [comment]
Normal communities works ok.
I could not check token-gated communities because of problems with FetchCommunity - https://github.com/status-im/status-go/issues/4496

**Comment by endulab** [comment]
After some adjustments I was able to connect to token-gated community
