### ISSUE TITLE
Allow running own nodes for IPFS and Swarm 

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#1271]
Requested by @3esmit.
This applies for browsing addresses using ENS, as well as downloading stickers
Will probably require modifying status-go settings to include the IPFS/Swarm node configuration in `settings_getSettings`
Could be part of the node module?

**Comment by iurimatias** [comment]
we're unlikely to run these type of nodes directly due to all sorts of potential complications, but with #2525 a user can simply point it to a local node
