### ISSUE TITLE
[Check #14639] Wallet - Send: suggestion on Simple screen does not match the Advanced screen

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12747]
### Description

1. open wallet
2. switch to test net
3. select eth and click send
4. select any account to send to
5. wait for the route on simple tab to build -> shows as mainnet
6. open advanced tab -> arbitrum is suggested
7. when confirming transaction , it indeed sends in Arbitrum

https://github.com/status-im/status-desktop/assets/82375995/67774f1f-b260-4f9d-bb68-564c247c6977

**Comment by anastasiyaig** [comment]
@benjthayer i find this confusing. the simple screen says that the network to use is mainnet
if i don't click on advance i will never know that it is not mainnet
when i am on Simple screen right, there is send button
i could never open Advanced, and send as it is
and then it would be sent on the network i am not expecting it to be
maybe on simple screen show the route label (like from - to )?

@John-44 wdyt

**Comment by John-44** [comment]
> @benjthayer i find this confusing. the simple screen says that the network to use is mainnet if i don't click on advance i will never know that it is not mainnet when i am on Simple screen right, there is send button i could never open Advanced, and send as it is and then it would be sent on the network i am not expecting it to be maybe on simple screen show the route label (like from - to )?
> 
> @John-44 wdyt

@anastasiyaig there is a bug here, because the routing solution should always be the same, irrespective of if the user is on the Simple, Advanced or Custom tab.

These tabs are just different views of *exactly the same thing*.  The routing solution should not change when the user moves from Simple to Advanced.

Definitely a bug!  Well spotted :-)

**Comment by John-44** [comment]
> @benjthayer i find this confusing. the simple screen says that the network to use is mainnet if i don't click on advance i will never know that it is not mainnet when i am on Simple screen right, there is send button i could never open Advanced, and send as it is and then it would be sent on the network i am not expecting it to be maybe on simple screen show the route label (like from - to )?
> 
> @John-44 wdyt

@anastasiyaig In the **Simple** view, it's only showing the networks the receiver will receive funds on, not the networks the sender is sending funds from.  So the information displayed in the screencast is technically correct.

However I agree that in this case it looks a bit confusing.  Not sure if there is a design quick fix here or not though.  Perhaps something @benjthayer could take a look quick look at *after* the work on profile and WalletConnect has been completed?  Profile and WalletConnect have to take design priority over this item.

**Comment by saledjenic** [comment]
This is not the case anymore, tested it in the router v2 integration build, this PR https://github.com/status-im/status-go/pull/5426, seems it was fixed by some of the router related improvements we did in the last few weeks.
