### ISSUE TITLE
Community: cant mint owner token on goerli / arb goerli

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12748]
### Description

<img width="1512" alt="Screenshot 2023-11-15 at 17 08 19" src="https://github.com/status-im/status-desktop/assets/82375995/48bca9b0-9cd4-40c0-9e74-6dc7b698835b">

```
ERR 2023-11-15 17:08:20.297+03:00 error doing rpc request                    topics="rpc" tid=3393790 file=core.nim:40 methodName=wakuext_createCommunityTokenDeploymentSignature exception="\nstatus-go error [methodName:wakuext_createCommunityTokenDeploymentSignature, code:-32000, message:deployer contract not available for chainID ]\n"
```

**Comment by anastasiyaig** [comment]
@jrainville i bet we had the deployer on goerli, where did it go? Perhaps on purpose?

**Comment by jrainville** [comment]
cc @endulab @0x-r4bbit is the contract deployed on the chains Nastya is asking about?

**Comment by endulab** [comment]
Contracts are deployed on Sepolia and Optimism Goerli.

**Comment by anastasiyaig** [comment]
@endulab thanks ! I will verify in a few and close the task

**Comment by 0x-r4bbit** [comment]
Correct, the contracts are on Goerli and Sepolia. The addresses can be found here: https://github.com/status-im/communities-contracts#deployments

Only thing to keep in mind is that the version on `Goerli` does not include the custom `StatusMint` events.

**Comment by 0x-r4bbit** [comment]
> Now i can mint only on Optimism

@anastasiyaig they are not deployed on optimism goerli (or mainnet), so I'm surprised this is the case.

**Comment by anastasiyaig** [comment]
@0x-r4bbit okay i am confused. What i want to clarify: which networks i should be able to mint tokens on (i assumed L1 + L2 for ethereum, which are goerl + opt goerli + arb goerli). I think it was like that before. What should i expect now?

**Comment by 0x-r4bbit** [comment]
@anastasiyaig sorry for the confusion:

I misread my own changes. So the contracts **are** deployed on optimism goerli and ethereum sepolia.
Check link in my comment

**Comment by 0x-r4bbit** [comment]
>  What should i expect now?

Ah, I wasn't aware there was already support for Arbitrum on desktop. So since we moved to making deployment of these tokens via `CommunityTokenDeployer` contract, it's mandatory for that one to be deployed on these chains. It's not deployed on arbitrum yet.

**Comment by anastasiyaig** [comment]
okay i am still confused. I opened latest master. I tried to mint on **testnet goerli** and got an error
```
unityTokenDeploymentSignature, code:-32000, message:deployer contract not available for chainID ]\n"
ERR 2023-11-20 15:54:15.181+03:00 error doing rpc request                    topics="rpc" tid=6256674 file=core.nim:40 methodName=wakuext_createCommunityTokenDeploymentSignature exception="\nstatus-go error [methodName:wakuext_createCommunityTokenDeploymentSignature, code:-32000, message:deployer contract not available for chainID ]\n
```

**The same happens for goerli arbitrum**. This is initial problem i opened issue for. Is it not an issue , or an issue we need to do something with the app to resolve? I am losing track

<img width="1542" alt="Screenshot 2023-11-20 at 15 56 00" src="https://github.com/status-im/status-desktop/assets/82375995/361e5a2f-fe9d-4bd1-b694-494d98197fed">

@0x-r4bbit

**Comment by 0x-r4bbit** [comment]
@anastasiyaig this seems to match what I'd expect. Below you see that the contracts necessary to deploy owner and master tokens are deployed on **Sepolia** and **Optimism Goerli**

<img width="775" alt="Screenshot 2023-11-20 at 14 26 06" src="https://github.com/status-im/status-desktop/assets/445106/c1f92853-9c7e-4ec2-8fe0-ccc62d4b912f">

They are not yet deployed on: **Goerli**, **Arbitrum Goerli**, **Arbitrum Sepolia**, **Optimism Sepolia** and **Mainnet**

I am working on deploying them on Goerli and Arbitrum Goerli now and then I'll work on Arbitrum Sepolia.

**Comment by anastasiyaig** [comment]
perfect now i am clear, sorry for being slow @0x-r4bbit

**Comment by 0x-r4bbit** [comment]
Contracts are now also deployed on **Arbitrum Goerli** and **Arbitrum Sepolia**

**Comment by jrainville** [comment]
@endulab can you update status-go to point to those addresses, thank you.
