### ISSUE TITLE
Version links on About screen lead to unavailable Github pages

### ISSUE THREAD

**Issue by s-tikhomirov** [status-im/status-desktop#12742]
# Bug Report

## Description

The "About" screen displays the version (two versions, actually). Each version is a link to a Github page. The "Release Notes" button below is also a link. All of them lead to Github's 404 page.

## Steps to reproduce

1. Open "About" page.
2. Click on the version number of on the "Release notes" link

#### Expected behavior

A release page on Github opens.

#### Actual behavior

A Gihub's 404 page opens.

### Additional Information

- Status desktop version: Current version 0.9.90, Status Go version 0.171.12
- Operating System: Ubuntu 20.04.6 LTS

**Comment by caybro** [comment]
It happens because we read the status-go version from the `VERSION` file but sometimes the devs forget to make a git tag when publishing their release, leading to the 404

**Comment by jrainville** [comment]
Fixed for RC3. The tags were indeed not created.
