### ISSUE TITLE
Wallet TEST_MODE: account ordering is buggy when in test mode

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12777]
### Description

Run the app with env var `STATUS_RUNTIME_TEST_MODE=1`

1. add several accounts
2. open accounts settings
3. open account order -> accounts color is off
4. do some reordering and open main wallet
5. All accounts overlap accounts list

<img width="1652" alt="Screenshot 2023-11-17 at 13 12 54" src="https://github.com/status-im/status-desktop/assets/82375995/f51d0161-ba50-498e-955d-2a3301869ed0">

<img width="1312" alt="Screenshot 2023-11-17 at 13 35 59" src="https://github.com/status-im/status-desktop/assets/82375995/8d296bcd-0262-492a-970d-51289f500f01">

**Comment by iurimatias** [comment]
moving to 0.15.5 since this is done
