### ISSUE TITLE
[Owner token transfer] CTAs for pending members missing after ownership change

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#12776]
## Steps to reproduce
1. Perform ownership transfer
2. As a new owner try to accept/decline any pending membership requests

#### Expected behavior
There are CTAs to Accept/Decline the request
#### Actual behavior
The CTAs are missing.
### Additional Information

- Status desktop version: v0.15.0-rc.2-4d1fd3
- Operating System: macOS Sonoma 14.0

**Comment by mprakhov** [comment]
@lukaszso needs small clarification: 
Pending requests that you see - is it a request from the ex-member that was kicked after the ownership transfer or it is a new member, who decided to join after the ownership was changed?

**Comment by lukaszso** [comment]
@mprakhov in this case it was an ex-member

**Comment by mprakhov** [comment]
@jrainville taking into account that it was ex-member - should we move it into 0.15.5 and fix it in the scope of https://github.com/status-im/status-desktop/issues/12577 ticket?

**Comment by jrainville** [comment]
> @jrainville taking into account that it was ex-member - should we move it into 0.15.5 and fix it in the scope of #12577 ticket?

Yeah. In a way, we could close this issue in favour of the other feature, but I'll leave open for now to make sure we fix it.

**Comment by mprakhov** [comment]
closed in https://github.com/status-im/status-desktop/pull/12928
