### ISSUE TITLE
[Owner token transfer] Membership request sent after ownership change are not delivered to the new owner

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#12795]
New community owner does not receive any notifications about new users wanting to join, there are also no pending requests in community management.

## Steps to reproduce
Prerequisite: User received a community owner token and finalised the ownership transfer
1. A new membership request is sent
2. User checks the notification center and pending requests

#### Expected behavior
User should see a notification and a pending request in community management

#### Actual behavior
No information about new membership requests are delivered.

### Additional Information

- Status desktop version: 0.15 RC2
- Operating System: macOS

**Comment by mprakhov** [comment]
there is some error on the transport layer... here what I found in status-go logs

```
INFO [11-20|20:04:01.343|github.com/status-im/status-go/wakuv2/waku.go:1008]                                         publishing message via relay             envelopeHash=0x3e07686e99639c1863552066da43b5481323ef110f462763ee9ea42ed15bcb9b pubsubTopic=/waku/2/default-waku/proto contentTopic=/waku/1/0x21bec532/rfc26 timestamp=1,700,517,841,342,513,148
ERROR[11-20|20:04:01.343|github.com/status-im/status-go/wakuv2/common/message.go:233]                                failed to decode message                 err="couldn't decrypt using symmetric key: cipher: message authentication failed"
DEBUG[11-20|20:04:01.343|github.com/status-im/status-go/wakuv2/common/filter.go:230]                                 processing message: failed to open       message=0x3e07686e99639c1863552066da43b5481323ef110f462763ee9ea42ed15bcb9b filter=71b87dd00110d517a1cae8cb1cb3d5fd25d01ead8b4f7897fc09237c5839c777
```

**Comment by jrainville** [comment]
Are new users sending the requests encrypted with the wrong key? Maybe they still use the old owner's public key or the community key?

**Comment by mprakhov** [comment]
@jrainville root cause found and fixed (checked), I'm trying to prepare a unit test for this scenario, but in unit test msg is not delivered for some reason
