### ISSUE TITLE
Desktop and Mobile version cannot chat

### ISSUE THREAD

**Issue by Ely5ia** [status-im/status-desktop#12793]
Are the accounts on the desktop and mobile versions of Status completely separate at present? I can't add friends to communicate between desktop and mobile.
The mobile version uses an uncompressed key format, while the desktop version uses a compressed key format. The protocol on the desktop version may be newer, but this makes Status unable to chat across platforms. Users very much hope to be able to chat on different devices.

The following is my specific usage. The software versions are all the latest.
I tried to recover my mobile account on desktop but it wouldn't recover. After I use the recovery key, I will get a brand new account, which does not contain the mobile account information. But their 3-word usernames are the same. Therefore, I plan to run the Android x86 virtual machine on Linux to use the Status mobile version, but you have not built an apk for the x86_64 architecture, and I still cannot run it normally using the Arm compatible library. Because of these things, I don't know how to promote Status to my privacy-conscious friends.

Finally, I still think that if Status can chat with each other on multiple platforms, it will be more anonymous than Signal. So I really hope it happens sooner.

Thanks.

Status-Mobile version:latest
System:Archlinux (Kernel 6.3)

**Comment by John-44** [comment]
@Ely5ia are you using the old legacy Mobile app (the one that's currently in the app stores) or the latest pre-Alpha mobile app builds from github?

The old legacy Mobile app uses Waku v1 which isn't compatible with Waku v2 that's used by the new Mobile and Desktop apps.

The latest pre-Alpha mobile app builds work with Status Desktop as they both use Waku v2
