### ISSUE TITLE
[Owner token transfer] Blank page displayed instead of community ofter ownership transfer

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#12805]
After a community owner transfer the owner token, they are kicked from the community. As a result, the community is shown as a blank page.

https://github.com/status-im/status-desktop/assets/52439419/781acac3-e096-4d11-9226-2687fbead85e

## Steps to reproduce

1. Community owner sends the owner token to another user
2. The other user finalises the ownership transfer and becomes the owner of the community
3. Previous owner receives the kick notification and then clicks on the community icon on the left panel 

#### Expected behavior
"Be right back message" is shown

#### Actual behavior
Blank page is displayed.

### Additional Information

- Status desktop version: 0.15 RC2
- Operating System: macOS

Logs from the session: 
[app_20231120_232121.log](https://github.com/status-im/status-desktop/files/13420072/app_20231120_232121.log)

**Comment by mprakhov** [comment]
known issue, the same as 
https://github.com/status-im/status-desktop/issues/12468

**Comment by jrainville** [comment]
> known issue, the same as #12468

Right, I did remember that other issue, but that other issue said it happened only when in the settings page.

If it happens for whatever the state of the community, then it's more of a problem and should be fixed in the RC. It should at least show the community spectated mode.

**Comment by mprakhov** [comment]
@lukaszso - do you remember if the ex-owner was in a community setting during this bug?

**Comment by lukaszso** [comment]
@mprakhov yes, the ex-owner was in the settings page of the community.
