### ISSUE TITLE
Create new / edit community flow: Warning text on "Request to join required" option

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#12809]
A small tweak has been made to the `Request to join required` checkbox list item featured in the `Create New Community` and `Edit Community` flows.

Changes made:

1) `Request to join required` option moved to base of checkbox list
2) When the checkbox for this item is selected, a warning in orange text is shown reading:
`Warning: Only token gated communities (or token gated channels inside non-token gated community) are encrypted` 

NB this text is only shown when the checkbox is in the selected state. The rest of the UI should push down as required to accommodate this text as the checkbox is selected.

**Change to Create New Community flow:**
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=2636-359221&mode=design&t=3AguBBoHdwrIIKGc-4

<img width="1806" alt="Screenshot 2023-11-21 at 11 17 26 AM" src="https://github.com/status-im/status-desktop/assets/110033914/a6a01828-4bac-4b31-92e2-027ffef53651">

**Change to Edit Community flow:**
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=45510-224401&mode=design&t=3AguBBoHdwrIIKGc-4

Original:
<img width="930" alt="Screenshot 2023-11-21 at 11 18 21 AM" src="https://github.com/status-im/status-desktop/assets/110033914/a1b2110d-c8f1-4fa1-bf79-1ac9c99252c2">

New:
<img width="1839" alt="Screenshot 2023-11-21 at 11 19 06 AM" src="https://github.com/status-im/status-desktop/assets/110033914/a1b4f4be-e9dd-4395-b1a9-7c7790102fcb">

cc @John-44

**Comment by noeliaSD** [comment]
Following priorities of milestone `0.15.5` and team workload, this one is moved to the next iteration.

**Comment by noeliaSD** [comment]
Following priorities of milestone `0.16` and team workload, this one is moved to the next iteration.
