### ISSUE TITLE
[Owner token transfer] No toast shown after finalising or declining ownership transfer

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#12808]
There is no toast shows after the receiver of the owner token finalises the transfer or declines it.

## Steps to reproduce

Scenario 1:
1. Receive an owner token for a community
2. Go through the Finalise ownership flow and sign the transaction

#### Expected behavior
Toast with a link to relevant explorer is shown to the user.
#### Actual behavior
No toast shown.

Scenario 2:
1. Receive an owner token for a community
2. Go through the decline ownership flow and confirm the decision

#### Expected behavior
Toast is shown.
#### Actual behavior
No toast shown.
### Additional Information

- Status desktop version: 0.15 RC2
- Operating System: macOS

**Comment by jrainville** [comment]
I think this is covered by https://github.com/status-im/status-desktop/issues/12656
cc @endulab

**Comment by jrainville** [comment]
Assigning @endulab . Feel free to close as duplicate if it is the case

**Comment by endulab** [comment]
I am closing it as a duplicate of https://github.com/status-im/status-desktop/issues/12175
FYI @noeliaSD
