### ISSUE TITLE
Retrieve images from Status-go to generate thumbnail images in reply

### ISSUE THREAD

**Issue by kounkou** [status-im/status-desktop#12821]
### Description

linked to https://github.com/status-im/status-go/pull/4516

From PR : https://github.com/status-im/status-desktop/pull/12806
Issue   : #10986 
 
> I think using only the messages received here might not generate a good map, because newMessagesLoaded only contains ~20 messages. In most cases, it should be ok, but if someone replied to an old message, then the album of messages wouldn't be part of the messages seq, so we'd also not find the images.

jrainville

In the code creates a map that solely relies on the received messages. The received message having a limit of ~20 messages, reply on an image for older messages, the code will not be able to obtain the images for that older message.
A solution would be to have access to the DB from status-go to fetch the corresponding message images and populate the Qml properties accordingly.

### Steps to reproduce

1- Find very old message with album images (more than 20 message earlier)
2- Reply to the message with album images

#### Expected behavior

- The old message images are not rendered in the reply thumbnails

#### Actual behavior

- The old message images should be rendered in the reply thumbnails

### Additional information

- https://github.com/status-im/status-desktop/issues/10986
- https://github.com/status-im/status-desktop/pull/12806

**Comment by jrainville** [comment]
For whoever works on this in the future, I think the optimal solution would be to improve the Message object in status-go itself so that any time we get the Quoted message, it also returns the album of images as part of it.

Obviously, this would only be local when retrieving messages from the DB, as we do not want to pass the full album of images when sending the images on the network.

So with luck, only modifying the persistence layer by improving the query would be enough! :crossed_fingers:

**Comment by kounkou** [comment]
From my analysis, this ticket requires to add a new column in the sqlite database for the quoted album Images. then follow a process for making the databse migration (I am not aware of this process, I saw couple of PR with similar changes, but it’s quite cryptic how the migrations are done. Example : https://github.com/status-im/status-go/pull/2869) So I need to ask around. @Igor Sirotin any idea if there’s a documented process to follow when adding a new field in our message_persistence in status-go.

**Comment by kounkou** [comment]
Here are steps I set myself to be able to deliver this ticket : 

    - Step 1 : Setup the code for being able to do DB migration — Complete
    - Step 2 : Update unittest in status-go to have reception of the message with QuotedMessage images and return QuotedMessage images persisted in DB — **in progress
    - Step 3 : Send PR with :SQL script for altering the user_messages table, and the migration files — in progress
    - Step 4 : Perform changes on the status-desktop to use status-go new changes — waiting to start
    - Step 5 : Send PR with status-desktop changes in the view — waiting to start
