### ISSUE TITLE
Community portal is not displaying featured community

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12827]
# Bug Report

## Description

The dapp is showing 1 featured community: https://community-dapp-git-review-status-im-web.vercel.app/featured 

The desktop app is not rendering this:

![image](https://github.com/status-im/status-desktop/assets/50769329/0101c918-624f-4129-9212-147e93b9b0a9)

### Additional Information

- Status desktop version: 0.15 RC3
- Operating System: Mac

**Comment by jrainville** [comment]
@osmaczko is this just an issue of fetching the data from store nodes? cc @igor-sirotin

**Comment by osmaczko** [comment]
> @osmaczko is this just an issue of fetching the data from store nodes? cc @igor-sirotin

Yes, it is. It is fetched by the DApp correctly though..

**Comment by igor-sirotin** [comment]
Not sure if `0.15-rc3` is affected by this, but there's a fix for this in status-go: 
https://github.com/status-im/status-go/pull/4360

**Comment by jrainville** [comment]
> Not sure if `0.15-rc3` is affected by this, but there's a fix for this in status-go: [status-im/status-go#4360](https://github.com/status-im/status-go/pull/4360)

We probably want that in the release branch if it fixes fetching data

**Comment by John-44** [comment]
I can't see any Communities in the portal at all, and as there are no communities in the portal there can't be any featured communities.

https://curate.status.app/directory is the URL of the production Community Directory Curation dApp (aka 'portal') that we should validate as working end to end with the app

**Comment by osmaczko** [comment]
> I can't see any Communities in the portal at all, and as there are no communities in the portal there can't be any featured communities.
> 
> https://curate.status.app/directory is the URL of the production Community Directory Curation dApp (aka 'portal') that we should validate as working end to end with the app

@John-44 this issue is about the app in testnet mode. status-desktop will reflect the state of the:
- https://curate.status.app/directory - in normal case
- https://community-dapp-git-review-status-im-web.vercel.app/directory - if testnet (and test fleet) is enabled


https://community-dapp-git-review-status-im-web.vercel.app/directory operates on optimism goerli testnet

**Comment by iurimatias** [comment]
discussed with the team, closing as it's happening due to several reasons such as community not supported, history being old etc..
