### ISSUE TITLE
Shared URLs to community without tags are invalid

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#12822]
# Bug Report

## Description

Try to to open this link in browser:
https://status.app/c/CxCACh8KBFBJR1MSDHdlIGxvdmUgcGlncxgBIgcjRDM0NEM1Aw==#zQ3shZp9gY1FXfYkcd3CMrFLHriHQfrXvpF9XbZMwJhTcZsq8

<img width="1012" alt="Screenshot 2023-11-22 at 08 43 35" src="https://github.com/status-im/status-desktop/assets/25482501/ec9d6807-6a36-4e16-910d-90d844b91b42">

And this link, which was created after adding some tags to the community:
https://status.app/c/CxKACiMKBFBJR1MSDHdlIGxvdmUgcGlncxgBIgcjRDM0NEM1KgIjHgM=#zQ3shZp9gY1FXfYkcd3CMrFLHriHQfrXvpF9XbZMwJhTcZsq8

<img width="1012" alt="Screenshot 2023-11-22 at 08 43 27" src="https://github.com/status-im/status-desktop/assets/25482501/aeb83411-cc11-4d57-805b-eb0ef5f3259a">

The first URL is invalid. It's failing to open both in browser and desktop.

**Comment by MishkaRogachev** [comment]
@igor-sirotin i tried your urls. Both urls work in status web and status-go... The only weird thing i've noticed is that tags can be presented both as zero-length slice and nil. Here is fix for that: https://github.com/status-im/status-go/pull/4420

**Comment by MishkaRogachev** [comment]
<img width="1012" alt="Screenshot 2023-12-05 at 18 00 31" src="https://github.com/status-im/status-desktop/assets/2522130/0f306662-4468-4ff6-900d-9c1210fb4981">
both urls work in status-desktop

**Comment by igor-sirotin** [comment]
Don't know what was wrong previously. Both links work now indeed. 
Anyway, your fix makes sense, thank you! 👍
