### ISSUE TITLE
Supported image formats are case sensitive

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12835]
# Bug Report

## Description

When sending an image, formats with uppercase file extensions are shown as invalid formats.

## Steps to reproduce

- Image is valid when file name is .jpg, .png, etc.
- Image is invalid when file name is .JPG or .PNG, etc.

![image](https://github.com/status-im/status-desktop/assets/50769329/85bd491b-b24d-49ca-b0de-48f391bbe1b9)

#### Expected behavior

File extensions are not case sensitive

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by caybro** [comment]
Probably needs this simple fix:

```diff
--- ui/StatusQ/src/QClipboardProxy.cpp
+++ ui/StatusQ/src/QClipboardProxy.cpp
@@ -76,7 +76,7 @@ bool QClipboardProxy::isValidImageUrl(const QUrl& url, const QStringList& accept
 {
     const auto strippedUrl = url.url(QUrl::RemoveAuthority | QUrl::RemoveFragment | QUrl::RemoveQuery);
     return std::any_of(acceptedExtensions.constBegin(), acceptedExtensions.constEnd(), [strippedUrl](const auto & ext) {
-        return strippedUrl.endsWith(ext);
+        return strippedUrl.endsWith(ext, Qt::CaseInsensitive);
     });
 }
 ```

But I'll have to check :)
