### ISSUE TITLE
Communties: network selector is missing for minting assets, fees are not calculated

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12844]
### Description

1. cant select any network to mint asset other than optimism
2. cant fetch fees even for optimism

```
ERR 2023-11-23 15:46:20.851+03:00 rpc response error                         topics="rpc" tid=8949608 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getSuggestedFees, code:-32000, message:could not find network: 0 ]\n"
ERR 2023-11-23 15:46:20.851+03:00 error doing rpc request                    topics="rpc" tid=8949608 file=core.nim:40 methodName=wallet_getSuggestedFees exception="\nstatus-go error [methodName:wallet_getSuggestedFees, code:-32000, message:could not find network: 0 ]\n"
```

<img width="1596" alt="Screenshot 2023-11-23 at 15 46 33" src="https://github.com/status-im/status-desktop/assets/82375995/50d32c95-6416-47fc-8c00-76b988153a4a">

**Comment by anastasiyaig** [comment]
@endulab can u please look into that?

**Comment by glitchminer** [comment]
I'm also getting a crash when attempting to airdrop a community token

```
ERR 2023-11-23 15:08:07.170+00:00 error doing rpc request                    topics="rpc" tid=4598942 file=core.nim:40 methodName=communitytokens_estimateMintTokens exception="\nstatus-go error [methodName:communitytokens_estimateMintTokens, code:3, message:execution reverted: ERC721: mint to the zero address ]\n"
ERR 2023-11-23 15:08:34.921+00:00 Error computing airdrop fees               topics="community-tokens-service" tid=4598925 file=service.nim:1183 msg="key not found: 5"
```

**Comment by endulab** [comment]
Ok, I will check this.

**Comment by endulab** [comment]
"cant select any network to mint asset other than optimism" -> the chain of owner token determines the chain of community tokens. If it is Optimism then all tokens must be on Optimism.
"cant fetch fees even for optimism" -> Quite probably the same as https://github.com/status-im/status-desktop/issues/12847. 
We suspect that the reason can unexpected change of testnet mode. I had the same results when I turned off the testnet and tried to do anything with tokens. In such a case chain id is unknown.

**Comment by anastasiyaig** [comment]
yes, 100%. i forgot about that. Sorry

**Comment by jrainville** [comment]
Completed in https://github.com/status-im/status-desktop/pull/12874
