### ISSUE TITLE
Communities: airdropping NFT fails on calculating fees

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12847]
### Description

```
ERR 2023-11-23 17:04:05.833+03:00 Error computing airdrop fees               topics="community-tokens-service" tid=8949586 file=service.nim:1183 msg="key not found: 5"
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

https://github.com/status-im/status-desktop/assets/82375995/ea816ccd-c578-4666-88cd-8029bd47e713

**Comment by anastasiyaig** [comment]
@jrainville it might be beacuse of test net but on mainnet i cant really check. Can we find someone to investigate?

**Comment by endulab** [comment]
I do not see the testnet banner so I guess that mainnet is switched on. But contracts are minted on testnet.
Maybe there is some mismatch. 
key not found: 5 - I guess it's about Goerli.

**Comment by anastasiyaig** [comment]
@endulab it was goerli

**Comment by anastasiyaig** [comment]
at some point banner went away 😂
