### ISSUE TITLE
No msg, that the control node is offline after the ownership change during the auto-rejoin after

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#12868]
# Bug Report

## Description

No msg, that the control node is offline after the ownership change during the auto-rejoin after

The code for creating this widget was accidentally removed during rebase

![image](https://github.com/status-im/status-desktop/assets/117639195/979f7187-cb0c-407d-9ba9-4c280745b487)

**Comment by caybro** [comment]
Used to be here https://github.com/status-im/status-desktop/commit/f1d4462f69b1ce29c0ba4067a22a0fa694f777a4#diff-a890b091a81c50d7b02e860563a2deb16aae3477bc945181f5e37a0e81b9190cL362-L379
