### ISSUE TITLE
Status desktop copy update

### ISSUE THREAD

**Issue by cheny0** [status-im/status-desktop#12864]
Hi team, here are some updates for the desktop app copy.

## General and messaging

|ID |Scope |Type  |Original                                                                                                        |Update to                                                                                                                                                                |Directions                                                                          |Docs update|
|---|------|------|----------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------|
|1  |General and messaging|Tooltip|Start chat                                                                                                      |New chat                                                                                                                                                                 |Hover over the icon next to the Messages label                                      |Y          |
|2  |General and messaging|Tooltip|More                                                                                                            |More options                                                                                                                                                             |This refers to the three dots button tooltip                                        |Y          |
|3  |General and messaging|Copy  |Fetch more messages                                                                                             |Load previous messages                                                                                                                                                   |                                                                                    |N          |
|4  |General and messaging|Copy  |Any messages you send here are encrypted and can only be read by you and xxx.                                   |All messages you send here are encrypted, only you and xxx can read them.                                                                                                |In the chat window, under the contact’s profile picture                             |N          |
|5  |General and messaging|Label |View Profile                                                                                                    |View profile                                                                                                                                                             |Messages -> Select a contact -> More (the three dots icon)                          |Y          |
|6  |General and messaging|Label |Mute Chat                                                                                                       |Mute chat                                                                                                                                                                |Messages -> More (the three dots icon)                                              |Y          |
|7  |General and messaging|Label |Mark as Read                                                                                                    |Mark as read                                                                                                                                                             |Messages -> More (the three dots icon)                                              |Y          |
|8  |General and messaging|Label |Clear History                                                                                                   |Clear history                                                                                                                                                            |Messages -> More (the three dots icon)                                              |Y          |
|9  |General and messaging|Label |Delete Chat                                                                                                     |Delete chat                                                                                                                                                              |Messages -> More (the three dots icon)                                              |Y          |
|10 |General and messaging|Label |Add / remove from group                                                                                         |Add / remove members                                                                                                                                                     |Messages -> Select a group chat -> More (the three dots icon)                       |Y          |
|11 |General and messaging|Label |Mute Chat                                                                                                       |Mute chat                                                                                                                                                                |Messages -> Select a group chat -> More (the three dots icon)                       |Y          |
|12 |General and messaging|Label |Mark as Read                                                                                                    |Mark as read                                                                                                                                                             |Messages -> Select a group chat -> More (the three dots icon)                       |Y          |
|13 |General and messaging|Label |Clear History                                                                                                   |Clear history                                                                                                                                                            |Messages -> Select a group chat -> More (the three dots icon)                       |Y          |
|14 |General and messaging|Label |Standard colours                                                                                                |Highlight colour                                                                                                                                                         |Messages -> Select a group chat -> More (the three dots icon) -> Edit name and image|           |

## Communities

|ID |Scope |Type  |Original                                                                                                        |Update to                                                                                                                                                                |Directions                                                                          |Docs update|
|---|------|------|----------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------|
|1  |Communities|Label |Mute Channel                                                                                                    |Mute channel                                                                                                                                                             |Select a community from the navigation sidebar -> More (three dots icon)            |Y          |
|2  |Communities|Label |Mark as Read                                                                                                    |Mark as read                                                                                                                                                             |Select a community from the navigation sidebar -> More (three dots icon)            |Y          |
|3  |Communities|Label |Clear History                                                                                                   |Clear history                                                                                                                                                            |Select a community from the navigation sidebar -> More (three dots icon)            |Y          |
|4  |Communities|Tooltip|Discover communities                                                                                            |Communities                                                                                                                                                              |Hover over the Communities icon on the navigation sidebar                           |Y          |
|5  |Communities|Label |Discover communities                                                                                            |Communities                                                                                                                                                              |Click the Communities icon on the navigation sidebar                                |Y          |
|6  |Communities|Button|Create New Community                                                                                            |Create community                                                                                                                                                         |Click the Communities icon on the navigation sidebar                                |Y          |
|7  |Communities|Label |Create New Community                                                                                            |Create community                                                                                                                                                         |Click the Communities icon on the navigation sidebar -> Click Create New Community button -> The label on the top left|Y          |
|8  |Communities|Label |Request to join required                                                                                        |Send request to join the community                                                                                                                                       |Click the Communities icon on the navigation sidebar -> Click Create New Community button|Y          |

## Wallet
|ID |Scope |Type  |Original                                                                                                        |Update to                                                                                                                                                                |Directions                                                                          |Docs update|
|---|------|------|----------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------|
|1  |Wallet|Copy  |This is your signing phase  <br>You should see 3 these words before signing each transaction  <br> If you see a different combination, cancel the transaction and sign out. |Your signing phrase    <br>A signing phrase helps you avoid sending funds to fraudulent recipients.  <br> I If the three words don’t appear as provided, don’t confirm the transaction.|On the popup appearing when a user first clicks on Wallet on the navigation sidebar.|N          |
|2  |Wallet|Button|Ok, got it                                                                                                      |OK                                                                                                                                                                       |On the popup appearing when a user first clicks on Wallet on the navigation sidebar.|Y          |
|3  |Wallet|Label |All accounts                                                                                                    |Total balance                                                                                                                                                            |On the Wallet sidebar, in the grey card                                             |Y          |
|4  |Wallet|Label |All Accounts                                                                                                    |Accounts                                                                                                                                                                 |In the Wallet content area                                                          |Y          |

## Settings

|ID |Scope |Type  |Original                                                                                                        |Update to                                                                                                                                                                |Directions                                                                          |Docs update|
|---|------|------|----------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------|
|1  |Settings|Button|Change Password                                                                                                 |Change password                                                                                                                                                          |Settings -> Profile -> The button on the top right                                  |Y          |
|2  |Settings|Label |Profile Picture                                                                                                 |Change avatar                                                                                                                                                            |Settings → Profile, then click the Edit icon next to your profile picture. Click Upload avatar (Upload a file) and select an image from your computer. A window with this title will appear.|Y          |
|3  |Settings|Label |Make this my Profile Pic                                                                                        |Change avatar                                                                                                                                                            |Settings → Profile, then click the Edit icon next to your profile picture. Click Upload avatar (Upload a file) and select an image from your computer. A window with this title will appear.|Y          |
|4  |Settings|Label |Display name                                                                                                    |Name  (Mobile app copy)                                                                                                                                                  |Settings -> Profile                                                                 |Y          |
|5  |Settings|Copy  |Display name                                                                                                    |Profile name (Mobile app copy)                                                                                                                                           |Settings -> Profile -> The text in the input filed                                  |Y          |
|6  |Settings|Copy  |Tell us about yourself                                                                                          |Something about you  (Mobile app copy)                                                                                                                                   |Settings -> Profile -> The text in the input filed                                  |N          |
|7  |Settings|Label |Twitter                                                                                                         |X                                                                                                                                                                        |Settings -> Profile -> Links -> Click Add a link                                    |           |
|8  |Settings|Label |Twitter username                                                                                                |X username                                                                                                                                                               |Settings -> Profile -> Links -> Click Add a link -> Click Twitter                   |           |
|9  |Settings|Button|Edit Profile                                                                                                    |Edit profile                                                                                                                                                             |Settings -> Profile → Preview, the button is to the right of your avatar, name and emoji hash.|Y          |
|10 |Settings|Label |Link to Profile                                                                                                 |Link to profile                                                                                                                                                          |Settings → Profile → Preview                                                        |           |
|11 |Settings|Label |Emoji Hash                                                                                                      |Emoji hash                                                                                                                                                               |Settings → Profile → Preview                                                        |           |
|12 |Settings|Copy  |Sync a New Device    <br> You own your data. Sync it among your devices.  <br> 1. Verify your login with password or Keycard <br> 2. Reveal a temporary QR code and Sync code<br> * 3. Share that information with your new device<br>  Setup Syncing  <br>*This is best done in private. The code will grant access to your profile.|Sync a new device <br> 1. Log into your profile on your other device <br>2. Reveal a sync code by clicking “Start Syncing”. Don’t share the code with others. <br>3. Enter the sync code or scan the sync code on your other device. Your devices are in sync automatically <br> Start Syncing (The sentence under the button is removed because the info has been included in step 2.)|Settings -> Syncing                                                                 |N          |
|13 |Settings|Label |Open Message Links With                                                                                         |Open links from messages with                                                                                                                                            |Settings -> Messaging                                                               |Y          |
|14 |Settings|Label |System Default Browser                                                                                          |System default browser                                                                                                                                                   |Settings -> Messaging                                                               |Y          |
|15 |Settings|Label |Contacts, Requests and Blocked Users                                                                            |Contacts, requests and blocked users                                                                                                                                     |Settings -> Messaging                                                               |Y          |
|16 |Settings|Button|Send contact request to chat key                                                                                |Send contact request                                                                                                                                                     |Settings -> Messaging -> Contacts, Requests and Blocked Users                       |Y          |
|17 |Settings|Label |Send Contact Request to chat key                                                                                |Send contact request                                                                                                                                                     |Settings -> Messaging -> Contacts, Requests and Blocked Users -> Send contact request to chat key|Y          |
|18 |Settings|Copy  |Enter chat key here                                                                                             |Enter the user’s chat key                                                                                                                                                |Settings -> Messaging -> Contacts, Requests and Blocked Users -> Send contact request to chat key|N          |
|19 |Settings|Button|Send Contact Request                                                                                            |Send contact request                                                                                                                                                     |Settings -> Messaging -> Contacts, Requests and Blocked Users -> Send contact request to chat key|Y          |
|20 |Settings|Copy  |Search by a display name or chat key                                                                            |Search by the user’s name or chat key                                                                                                                                    |Settings -> Messaging -> Contacts, Requests and Blocked Users                       |N          |
|21 |Settings|Label |Pending Requests                                                                                                |Pending requests                                                                                                                                                         |Settings -> Messaging -> Contacts, Requests and Blocked Users                       |Y          |
|22 |Settings|Label |View Profile                                                                                                    |View profile                                                                                                                                                             |Settings -> Messaging -> Contacts, Requests and Blocked Users -> three dots next to a contact’s name|Y          |
|23 |Settings|Label |Send Message                                                                                                    |Send message                                                                                                                                                             |Settings -> Messaging -> Contacts, Requests and Blocked Users -> three dots next to a contact’s name|Y          |
|24 |Settings|Label |Verify Identity                                                                                                 |Verify identity                                                                                                                                                          |Settings -> Messaging -> Contacts, Requests and Blocked Users -> three dots next to a contact’s name|Y          |
|25 |Settings|Label |Mark as Untrustworthy                                                                                           |Mark as untrusted                                                                                                                                                        |Settings -> Messaging -> Contacts, Requests and Blocked Users -> three dots next to a contact’s name|Y          |
|26 |Settings|Label |Remove Contact                                                                                                  |Remove contact                                                                                                                                                           |Settings -> Messaging -> Contacts, Requests and Blocked Users -> three dots next to a contact’s name|Y          |
|27 |Settings|Label |Block User                                                                                                      |Block user                                                                                                                                                               |Settings -> Messaging -> Contacts, Requests and Blocked Users -> three dots next to a contact’s name|Y          |
|28 |Settings|Label |Display Message Link Previews                                                                                   |Preview links in messages                                                                                                                                                |Settings -> Messaging                                                               |Y          |
|29 |Settings|Copy  |Fine tune which sites to allow link previews                                                                    |Specify by website                                                                                                                                                       |Settings -> Messaging -> Enable “Display Message Link”                              |N          |
|30 |Settings|Label |Member                                                                                                          |Joined  (Mobile app copy)                                                                                                                                                |Settings -> Communities                                                             |Y          |
|31 |Settings|Label |Mute Community                                                                                                  |Mute community                                                                                                                                                           |Settings -> Communities -> Member -> three dots next to a community’s name          |Y          |
|32 |Settings|Label |Invite People                                                                                                   |Invite people                                                                                                                                                            |Settings -> Communities -> Member -> three dots next to a community’s name          |Y          |
|33 |Settings|Label |Edit Shared Addresses                                                                                           |Edit shared addresses                                                                                                                                                    |Settings -> Communities -> Member -> three dots next to a community’s name          |Y          |
|34 |Settings|Label |Leave Community                                                                                                 |Leave community                                                                                                                                                          |Settings -> Communities -> Member -> three dots next to a community’s name          |Y          |
|35 |Settings|Button|View & Join Community                                                                                           |Join community                                                                                                                                                           |Settings -> Communities -> Pending -> the button next to a community’s name         |Y          |
|36 |Settings|Label |Mute Community                                                                                                  |Mute community                                                                                                                                                           |Settings -> Communities -> Pending -> three dots next to a community’s name         |Y          |
|37 |Settings|Label |Invite People                                                                                                   |Invite people                                                                                                                                                            |Settings -> Communities -> Pending -> three dots next to a community’s name         |Y          |
|38 |Settings|Label |Close Community                                                                                                 |Close community                                                                                                                                                          |Settings -> Communities -> Pending -> three dots next to a community’s name         |Y          |
|39 |Settings|Label |Notifications & Sounds                                                                                          |Notifications and sounds                                                                                                                                                 |On the settings side bar                                                            |Y          |
|40 |Settings|Copy  |Enable Notifications in macOS Settings                                                                          |Enable notifications in macOS settings                                                                                                                                   |Settings -> Notifications & Sounds                                                  |N          |
|41 |Settings|Label |Allow Notification Bubbles                                                                                      |Allow notification bubbles                                                                                                                                               |Settings -> Notifications & Sounds                                                  |Y          |
|42 |Settings|Label |1:1 Chats                                                                                                       |Direct messages                                                                                                                                                          |Settings -> Notifications & Sounds -> Messages                                      |           |
|43 |Settings|Label |Group Chats                                                                                                     |Group chats                                                                                                                                                              |Settings -> Notifications & Sounds -> Messages                                      |Y          |
|44 |Settings|Label |Personal @ Mentions                                                                                             |Personal @ mentions                                                                                                                                                      |Settings -> Notifications & Sounds -> Messages                                      |Y          |
|45 |Settings|Label |Global @ Mentions                                                                                               |Global @ mentions                                                                                                                                                        |Settings -> Notifications & Sounds -> Messages                                      |Y          |
|46 |Settings|Label |All Messages                                                                                                    |All messages                                                                                                                                                             |Settings -> Notifications & Sounds -> Messages                                      |Y          |
|47 |Settings|Label |Contact Requests                                                                                                |Contact requests                                                                                                                                                         |Settings -> Notifications & Sounds -> Others                                        |Y          |
|48 |Settings|Label |Identity Verification Requests                                                                                  |Identity verification requests                                                                                                                                           |Settings -> Notifications & Sounds -> Others                                        |Y          |
|49 |Settings|Button|Send Alerts                                                                                                     |Send alerts                                                                                                                                                              |Settings -> Notifications & Sounds -> Buttons next to the labels                    |Y          |
|50 |Settings|Button|Deliver Quietly                                                                                                 |Deliver quietly                                                                                                                                                          |Settings -> Notifications & Sounds -> Buttons next to the labels                    |Y          |
|51 |Settings|Button|Turn Off                                                                                                        |Turn off                                                                                                                                                                 |Settings -> Notifications & Sounds -> Buttons next to the labels                    |Y          |
|52 |Settings|Label |Notification Content                                                                                            |Notification details                                                                                                                                                     |Settings -> Notifications & Sounds -> Others                                        |Y          |
|53 |Settings|Label |Show Name and Message                                                                                           |Show contact and message                                                                                                                                                 |Settings -> Notifications & Sounds -> Notification content                          |Y          |
|54 |Settings|Label |Name Only                                                                                                       |Show contact                                                                                                                                                             |Settings -> Notifications & Sounds -> Notification content                          |Y          |
|55 |Settings|Label |Anonymous                                                                                                       |Hide content                                                                                                                                                             |Settings -> Notifications & Sounds -> Notification content                          |Y          |
|56 |Settings|Label |Play a Sound when Receiving a Notification                                                                      |Notification sound                                                                                                                                                       |Settings -> Notifications & Sounds -> Notification content                          |Y          |
|57 |Settings|Button|Send a Test Notification                                                                                        |Send a test notification                                                                                                                                                 |Settings -> Notifications & Sounds -> Notification content                          |Y          |
|58 |Settings|Label |Exemptions                                                                                                      |Exceptions                                                                                                                                                               |Settings -> Notifications & Sounds -> Exemptions                                    |Y          |
|59 |Settings|Label |Personal @ Mentions                                                                                             |Personal @ mentions                                                                                                                                                      |Settings -> Notifications & Sounds -> Exemptions -> Most recent -> Click the plus sysmbol|Y          |
|60 |Settings|Label |Global @ Mentions                                                                                               |Global @ mentions                                                                                                                                                        |Settings -> Notifications & Sounds -> Exemptions -> Most recent -> Click the plus sysmbol|Y          |
|61 |Settings|Label |Other Messages                                                                                                  |Other messages                                                                                                                                                           |Settings -> Notifications & Sounds -> Exemptions -> Most recent -> Click the plus sysmbol|Y          |
|62 |Settings|Button|Send Alerts                                                                                                     |Send alerts                                                                                                                                                              |Settings -> Notifications & Sounds -> Exemptions -> Most recent -> Click the plus sysmbol|Y          |
|63 |Settings|Button|Deliver Quietly                                                                                                 |Deliver quietly                                                                                                                                                          |Settings -> Notifications & Sounds -> Exemptions -> Most recent -> Click the plus sysmbol|Y          |
|64 |Settings|Button|Turn Off                                                                                                        |Turn off                                                                                                                                                                 |Settings -> Notifications & Sounds -> Exemptions -> Most recent -> Click the plus sysmbol|Y          |
|65 |Settings|Button|Clear Exemptions                                                                                                |Reset                                                                                                                                                                    |Settings -> Notifications & Sounds -> Exemptions -> Most recent -> Click the plus sysmbol|Y          |
|66 |Settings|Label |Language & Currency                                                                                             |Language and currency                                                                                                                                                    |On the settings side bar                                                            |Y          |
|67 |Settings|Label |Set Display Currency                                                                                            |Set display currency                                                                                                                                                     |Settings -> Language & Currency                                                     |Y          |
|68 |Settings|Label |US Dollars                                                                                                      |US dollar                                                                                                                                                                |Settings -> Language & Currency -> Click the button next to Set Display Currency    |N          |
|69 |Settings|Label |British Pound                                                                                                   |British pound                                                                                                                                                            |Settings -> Language & Currency -> Click the button next to Set Display Currency    |N          |
|70 |Settings|Label |Euros                                                                                                           |Euro                                                                                                                                                                     |Settings -> Language & Currency -> Click the button next to Set Display Currency    |N          |
|71 |Settings|Label |Time Format                                                                                                     |Time format                                                                                                                                                              |Settings -> Language & Currency                                                     |Y          |
|72 |Settings|Label |Use System Settings                                                                                             |Follow system settings                                                                                                                                                   |Settings -> Language & Currency                                                     |Y          |
|73 |Settings|Label |Use 24-Hour Time                                                                                                |Use 24-hour time                                                                                                                                                         |Settings -> Language & Currency                                                     |Y          |
|74 |Settings|Label |Application Logs                                                                                                |Application logs                                                                                                                                                         |Settings -> Advanced                                                                |N          |
|75 |Settings|Label |Experimental Features                                                                                           |Experimental features                                                                                                                                                    |Settings -> Advanced                                                                |Y          |
|76 |Settings|Label |Dapp Browser                                                                                                    |dApp browser                                                                                                                                                             |Settings -> Advanced                                                                |Y          |
|77 |Settings|Label |Node Management                                                                                                 |Node management                                                                                                                                                          |Settings -> Advanced                                                                |Y          |
|78 |Settings|Label |WakuV2 Store                                                                                                    |WakuV2 store                                                                                                                                                             |Settings -> Advanced                                                                |Y          |
|79 |Settings|Label |Waku Nodes                                                                                                      |Waku nodes                                                                                                                                                               |Settings -> Advanced                                                                |Y          |
|80 |Settings|Label |About & Help                                                                                                    |Info                                                                                                                                                                     |On the settings side bar                                                            |Y          |
|81 |Settings|Copy  |Current Version                                                                                                 |Current version                                                                                                                                                          |Settings -> About                                                                   |N          |
|82 |Settings|Copy  |Status Go Version                                                                                               |Status Go version                                                                                                                                                        |Settings -> About                                                                   |N          |
|83 |Settings|Button|Release Notes                                                                                                   |Release notes                                                                                                                                                            |Settings -> About                                                                   |N          |
|84 |Settings|Label |Our Principles                                                                                                  |Our principles                                                                                                                                                           |Settings -> About                                                                   |N          |
|85 |Settings|Label |Status desktop’s GitHub Repositories                                                                            |Status desktop’s GitHub repositories                                                                                                                                     |Settings -> About                                                                   |N          |
|86 |Settings|Label |Status Desktop                                                                                                  |Status desktop                                                                                                                                                           |Settings -> About                                                                   |N          |
|87 |Settings|Label |Legal & Privacy Documents                                                                                       |Legal and privacy documents                                                                                                                                              |Settings -> About                                                                   |N          |
|88 |Settings|Label |Terms of Use                                                                                                    |Terms of use                                                                                                                                                             |Settings -> About                                                                   |N          |
|89 |Settings|Label |Privacy Policy                                                                                                  |Privacy policy                                                                                                                                                           |Settings -> About                                                                   |N          |
|90 |Settings|Label |Software License                                                                                                |Software license                                                                                                                                                         |Settings -> About                                                                   |N          |
|91 |Settings|Label |Sign out & Quit                                                                                                 |Log out  (Mobile app copy)                                                                                                                                               |On the settings side bar                                                            |Y          |
|92 |Settings|Label |Sign out                                                                                                        |Log out (Mobile app copy)                                                                                                                                                |Settings -> Sign out & Quit -> The text on the top left                             |Y          |
|93 |Settings|Copy  |Make sure you have your account password and seed phrase stored. Without them you can lock yourself out and lose funds.|Make sure you have backed up your password and recovery phrase. If you forget them, you may lose access to your Status profile and wallet funds.                         |Settings -> Sign out & Quit                                                         |Y          |
|94 |Settings|Button|Sign out & Quit                                                                                                 |Log out (Mobile app copy)                                                                                                                                                |Settings -> Sign out & Quit -> The button                                           |Y          |

## Error messages
|ID |Scope |Type  |Original                                                                                                        |Update to                                                                                                                                                                |Directions                                                                          |Docs update|
|---|------|------|----------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|-----------|
|1  |Error messages|Copy  |CryptoCompare and CoinGecko down. Market values are as of October 23, 2023 13:26:02 CST                         |Unable to get data from CryptoCompare and CoinGecko. Market values were last updated on October 23, 2023 13:26:02 CST.                                                   |Appear on the top of the app                                                        |N          |
|2  |Error messages|Copy  |CryptoCompare and CoinGecko connection successful                                                               |Connected to CryptoCompare and CoinGecko                                                                                                                                 |Appear on the top of the app                                                        |N          |
|3  |Error messages|Copy  |Can not connect to store node. Retrying automatically                                                           |Unable to connect to the store node. We're trying again for you.                                                                                                         |Appear on the top of the app                                                        |N          |
|4  |Error messages|Copy  |Downloading message history archives, DO NOT CLOSE THE APP until this banner disappears.                        |Downloading historical messages. Please keep the app open until this message disappears.                                                                                 |Appear on the top of the app                                                        |N          |

**Comment by caybro** [comment]
Just a reminder to whoever will be working on this task: after the string changes, run the `scripts/translationScripts/update-en-ts.py` script to regenerate the translation files

**Comment by John-44** [comment]
This bug should be closed as won't fix, as per discussions earlier today.  This info will be passed to the design team, and design will consider this change request.
