### ISSUE TITLE
No AC to finalize ownership if owner token receiver is not a community member

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#12876]
# Bug Report

## Description

No AC to finalize ownership if owner token receiver is not a community member

## Steps to reproduce

1. Create a community and mint owner token
2. Send owner token to the user, who is not a community member and not in spectated mode

#### Expected behavior

AC to finalize ownership received

#### Actual behavior

No AC to finalize ownership

### Additional Information

- Status desktop version: 0.15.x
- Operating System: macos

**Comment by endulab** [comment]
The AC message shows up when there is a signal from a wallet.
The signal from a wallet is emitted when the wallet receives the owner token.
If there is no AC message it means that the wallet did not emit the signal.
