### ISSUE TITLE
Crash when recovering seed phrase

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12872]
### Description

1. installed 0.15 rc 5
2. i had clean db
3. i imported seed  with the flow `I already use Status`
4. app crashed

```
WRN 2023-11-24 16:30:58.766+03:00 Error decoding signal                      topics="signals-manager" tid=9904104 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
WRN 2023-11-24 16:30:59.306+03:00 Error decoding signal                      topics="signals-manager" tid=9904104 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
2023-11-24T16:31:01.709+0300	INFO	communities/manager.go:308	initializing history archive tasks
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
zsh: segmentation fault  ./nim_status_client -d:~/data/RC --LOG_LEVEL=DEBUG
```

5. i restarted the app: it shows 3 words name (like i have 0 data on waku, but i use the acc daily, and at least i must have display name)

<img width="1512" alt="Screenshot 2023-11-24 at 16 33 25" src="https://github.com/status-im/status-desktop/assets/82375995/7ef1e8dd-9385-4d1b-bbe1-8b0b8e46b5b8">

6. i logged in and set display name in profile as profile was showing empty field as display name
7. i cleaned the data folder and imported the same acc again 
8. it crashed again on importing and 3 words name shown on login
9. i logged in and checked profile -> recently set display name is there
<img width="1512" alt="Screenshot 2023-11-24 at 16 36 15" src="https://github.com/status-im/status-desktop/assets/82375995/64939d26-2193-4e9a-9a44-d9de50e9a3c2">

**My guess:** when having only display name set for a seed, waku back up somewhat loses it and within next 8h after , when recovering account, there is NULL reference that causes the crash and then - 3 words name appearance

**Comment by anastasiyaig** [comment]
@glitchminer

**Comment by igor-sirotin** [comment]
Meanwhile I can confirm the bug. And it's not reproducible on master.

**Comment by jrainville** [comment]
> Meanwhile I can confirm the bug. And it's not reproducible on master.

So it only happens in the release branch?

**Comment by igor-sirotin** [comment]
Ok it turned out I was dumb enough not to `make status-go-clean` before the run, that's why it was crashing for me. 
Right now I'm not able to reproduce it, investigating.

**Comment by jrainville** [comment]
I think it has to do with the particular account Nastya was using. It synced partial data or something, so when we fetch it, it crashes it seems? Maybe @anastasiyaig can share the seed phrase? If not, maybe you guys can pair or just exchange logs

**Comment by anastasiyaig** [comment]
sure @jrainville , just shared with @igor-sirotin
