### ISSUE TITLE
Segfault on accepting a contact request

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#12889]
# Bug Report

Application started to crash when receiving contact and community request

## Steps to reproduce

1. Create a new acc
2. Receive a CR
3. Accept it

#### Expected behavior

no segmentation fault

#### Actual behavior

Segmentation fault

### Additional Information

- Status desktop version: latest master
- Operating System: macos

**Comment by MishkaRogachev** [comment]
works on: 78303105915e17c4e8ff4d176f8b46e3b8381dae

**Comment by MishkaRogachev** [comment]
works on 26d867a63ae660bdc2b8659d6d16d36309726f61

**Comment by MishkaRogachev** [comment]
fails on 9a714cfec02617933556aa471c08d4a8a7ae13d6

**Comment by caybro** [comment]
I was able to reproduce on master too; this time even without accepting anything. I assume somebody sent me a CR

**Comment by MishkaRogachev** [comment]
Lol, I broke it - I fixed it :)

**Comment by anastasiyaig** [comment]
wow thats the spirit!
