### ISSUE TITLE
Communities: channels are duplicated when joining community by clicking the Go to community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12883]
### Description

1. create community that requires approval to join
2. enable all checkboxes (everyone is able to pin message, etc), add tags
3. add 2 more channels to this community
4. create a community category and assign 1 channel to it
5. add 2 contacts
6. send invitation to join this community to your 2 contacts at the same time

**As result:**

- receiver of that invitation see the toast that `community was imported`
- receiver of that inviation clicks Go to community and as result, the channels are duplicated

- community owner gets a notification about permission added when no permissions are yet created
<img width="414" alt="Screenshot 2023-11-28 at 11 56 36" src="https://github.com/status-im/status-desktop/assets/82375995/cab2ed65-85fc-4115-81a1-a7f95c0986f2">

<img width="1474" alt="Screenshot 2023-11-28 at 11 52 17" src="https://github.com/status-im/status-desktop/assets/82375995/a616c57c-ba30-460a-a57f-154f5c8930e0">

<img width="1312" alt="Screenshot 2023-11-28 at 11 52 11" src="https://github.com/status-im/status-desktop/assets/82375995/67555387-5267-4187-b01d-cb438c78a6c9">

**Comment by anastasiyaig** [comment]
@mprakhov @igor-sirotin can u guys check on this please? Or someone else who is more free (dont know whom to ask)

**Comment by mprakhov** [comment]
I was able to repro this issue when the owner token was minted, without additional setups (aka selecting checkboxes, setting tags etc). After app restart - everything is ok, so the issue somewhere on the status-desktop side

**Comment by mprakhov** [comment]
one more issue - if I mint an owner token and send an invite via `Invite member`, when the invite is delivered and parsed, the community automatically appear in the community section (without clicking on the invite)

![image](https://github.com/status-im/status-desktop/assets/117639195/bc7cc43f-0676-4dc0-9ca2-391a787c0a0d)
