### ISSUE TITLE
Communties: Sharing my address shows fantom permissions which are not met

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12884]
### Description

I have permission free community (the only condition is that it requires approval to join). As a member of that community, when clicking Request to join, there is a Select addresses to share flow which says that I dont have needed tokens. But so far none is required

<img width="1920" alt="Screenshot 2023-11-28 at 12 10 09" src="https://github.com/status-im/status-desktop/assets/82375995/9132651d-eb02-4ffd-b7c7-3f548c37f37a">
<img width="1312" alt="Screenshot 2023-11-28 at 12 10 45" src="https://github.com/status-im/status-desktop/assets/82375995/51a9172f-4d0d-40f8-b78b-218031d9d9ec">

https://github.com/status-im/status-desktop/assets/82375995/03922f26-1196-4d3d-8452-bcf3e3a90972

upd: **EXPECTED UI in this case**

![image](https://github.com/status-im/status-desktop/assets/82375995/36366fdc-4cb2-47b5-97d4-bb92f06a64d0)

**Comment by anastasiyaig** [comment]
maybe @mprakhov u can help?

**Comment by mprakhov** [comment]
Hi @anastasiyaig , I'm full of tasks, but if there is no volunteers, I'll take a look

**Comment by anastasiyaig** [comment]
🙏 sorey about that

**Comment by anastasiyaig** [comment]
@benjthayer sorry for bothering u, i just cant find any designs about that, maybe u can point to them for me? How it overall should look like

**Comment by benjthayer** [comment]
Hey @anastasiyaig the share addresses flows upon joining a community are here:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=31461-563897&mode=design&t=96pXLjzPIRbq8VSQ-4

Just shout if you need any further clarifications! Thanks

**Comment by anastasiyaig** [comment]
thanks @benjthayer , i overlooked it even looking in this exact file :D 

so this is a bug. This community is token gated (we have Owner token minted already). Then it should be `1 account, no channel permissions` flow:

<img width="1010" alt="Screenshot 2023-11-28 at 15 14 09" src="https://github.com/status-im/status-desktop/assets/82375995/85853572-3180-4a55-8fce-b1d5e1997385">

**Comment by benjthayer** [comment]
Just to clarify the design intent here @anastasiyaig :

By default when the owner mints the Owner and TokenMaster tokens, these are the permissions that are automatically created:

<img width="930" alt="Screenshot 2023-11-28 at 12 32 49 PM" src="https://github.com/status-im/status-desktop/assets/110033914/3f3434db-83c5-4a22-8d9e-2c2bef758462">
[https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?type=design&node-id=36893-640505&mode=design&t=96pXLjzPIRbq8VSQ-4](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=36893-640505&mode=design&t=96pXLjzPIRbq8VSQ-4)

These auto-generated permissions pertain only to the Owner and TokenMaster. So by default, unless the user establishes an explicit token gating rule for the community, there is no token gating applied to the community at this point.

If I then go and join that same community - as a different person (i.e. not the owner) - given the community is still not token gated, I should see this variant of the share addresses dialog (depending on how many addresses I have):

<img width="1076" alt="Screenshot 2023-11-28 at 12 34 48 PM" src="https://github.com/status-im/status-desktop/assets/110033914/b5548e67-e64b-40b1-a863-67d066262a54">

[https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?type=design&node-id=31461-579225&mode=design&t=96pXLjzPIRbq8VSQ-4](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=31461-579225&mode=design&t=96pXLjzPIRbq8VSQ-4)

One thing I see in the video is a new body of work I have been doing with Sale which is the requirement to prove ownership of any addresses you share - if all addresses that the user wants to share are stored in the same place the user will see an authentication icon in the Share selected addresses to join. If the keypairs of the accounts being shared are in different storage locations - ie 2 on device, 2 on different keycards, they will be taken to an authentication wiki like this where they authenticate each keypair as required:
[https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?type=design&node-id=45088-305547&mode=design&t=96pXLjzPIRbq8VSQ-4](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=45088-305547&mode=design&t=96pXLjzPIRbq8VSQ-4)

Hope that helps! :)

**Comment by noeliaSD** [comment]
@caybro if I'm not wrogn, you implemented that feature. Could you confirm that probably, the work needed here is, the UI should evaluate which type of permissions are in the model and if there are only the 2 specific for the TMaster and Owner, the `Permissions` section shoud be hidden?

**Comment by mprakhov** [comment]
What should we show if:
1. the user owns TokenMaster token and wants to join the community.
2. community has admin permissions and the user has an admin token (or necessary balance) to join this community as an admin

**Comment by benjthayer** [comment]
> What should we show if:
> 
> 1. the user owns TokenMaster token and wants to join the community.
> 2. community has admin permissions and the user has an admin token (or necessary balance) to join this community as an admin

Hey @mprakhov the designs for that are here:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=31461-567344&mode=design&t=yvgpLaFvkh9IS0K9-4

The permissions for TokenMaster and admin are hidden unless the user has the requisite tokens in/across their accounts. They can choose to join as a member even if they have the tokens for joining as an admin/TM by deselecting the relevant accounts that are currently holding those tokens.

**Comment by alexandraB99** [comment]
this doesn't seem like a new ui or new ui component is need here, is just a matter of adding the feature, re-assigning to messenger team

**Comment by endulab** [comment]
Reopening, since requires more work.
