### ISSUE TITLE
Communities: Token hodlers list is empty even all members are owning a token

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12888]
### Description

1. i created community
2. i generated a token there
3. i added 2 members to this community and approved them
4. i aidropped erc20 to this members
5. i airdropped this token to myself

As result, the list is still empty.

addresses to check:
`0xf525012c2b01f2b2d61499fe18bc98ba1411270b` (community owner)
`0xeea8a4b6377266f90fb3e17a0ddb0bc8ca950723` community member with token on generated account
`0xafca2efc364ca0867ab5c3310b90bacd6aa5226c` community member with token on Status account

<img width="1390" alt="Screenshot 2023-11-28 at 14 32 14" src="https://github.com/status-im/status-desktop/assets/82375995/f1315108-4927-43bf-b5b2-19b583612a31">

<img width="1338" alt="Screenshot 2023-11-28 at 14 33 24" src="https://github.com/status-im/status-desktop/assets/82375995/a0dd7380-559a-48de-826d-a326979f6cbc">

**Comment by anastasiyaig** [comment]
@MishkaRogachev do u know what could happen there? I am on 0.15 rc 5

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev do u know what could happen there? I am on 0.15 rc 5

I did not touch this list since last release. Can you see those tokens in wallet?

**Comment by anastasiyaig** [comment]
yes! :)

**Comment by anastasiyaig** [comment]
closing in favor of https://github.com/status-im/status-desktop/issues/12062
