### ISSUE TITLE
TokenMaster is marked as holding the Owner token yet not holding the TM token

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12905]
# Bug Report

## Description

In the Tokens tab of the community admin panel, the TokenMaster can see `you hodl` under the Owner token, instead of under the TMaster token.

![image](https://github.com/status-im/status-desktop/assets/11926403/f6e2ac05-35b3-475f-9f91-9c6ef775912a)

Similarly, when clicking on the Owner token, it says the TM can transfer the token.

![image](https://github.com/status-im/status-desktop/assets/11926403/01636916-d421-449b-aa33-01298bf0afb3)

## Steps to reproduce

1. Create an on request community in Account A
2. Invite Account B to community
3. Join using Account B and approve using A
4. A mints the Owner token and airdrops a TM token to B
5. B is now a TM
6. B checks the Tokens tab

#### Expected behavior

TokenMaster is marked as hodling the TokenMaster token, not the Owner token. TM cannot send the Owner token to anyone

### Additional Information

Tested on testnet mode

- Status desktop version: 0.15.0 RC5
- Operating System: Ubuntu 20

**Comment by jrainville** [comment]
@noeliaSD FYI I created this issue

**Comment by noeliaSD** [comment]
- The footer issue is solved in here: https://github.com/status-im/status-desktop/issues/12911
- The `text` under the owner token item is in review with the design team

**Comment by noeliaSD** [comment]
Agreed with @benjthayer that in case of `tmaster` or `admin` user profiles, text under `TOwner item` will be just `1 of 1`
