### ISSUE TITLE
TokenMaster can still see people in Pending requests after they were accepted by the Owner

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12904]
# Bug Report

## Description

As a TokenMaster, I can see pending requests to join. Once they were accepted by the Onwer, I can see the new members in the `All members` tab, but some of them still appear in the `Pending Requests` tab.

This **might** be because I tried to accept them and it failed. See https://github.com/status-im/status-desktop/issues/12902
The person still in the list is the one I tried to approve and it failed.

However, I also see myself in the Pending Requests, which makes no sense.

Pending tab:
![image](https://github.com/status-im/status-desktop/assets/11926403/40042fa6-a234-4438-9a4d-d38b3e0e18b1)

Members tab (see that the two above are also in the members):
![image](https://github.com/status-im/status-desktop/assets/11926403/8163f247-3db9-4ab4-b4e9-e7ef8b187e0e)

## Steps to reproduce

1. Create an on request community in Account A
2. Invite Account B to community
3. Join using Account B and approve using A
5. A mints the Owner token and airdrops a TM token to B
6. B is now a TM
7. B can see himself in the Pending Requests :exclamation: 
8. C sends a request to join the community
9. B sees the request. Optional step: B tries to accept and it fails
10. A approves the request
11. C is now a member of the community, but the request is still in the pending list :exclamation: 

#### Expected behavior

Once a member is accepted or rejected, he is no longer part of the pending list
We can never see ourselves in the pending list

#### Actual behavior

Sometimes members stays in pending when approved and I could see myself in pending

### Additional Information

Tested in testnet mode

- Status desktop version: 0.15.0 RC5
- Operating System: Ubuntu 20

**Comment by mprakhov** [comment]
assigning this ticket to myself, as I've been investigating almost a similar problem
