### ISSUE TITLE
Version Updating (Temporary solution)

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1290]
Based on the conversation from the last week I made this proposal for the version updating @jrainville @michaelsbradleyjr @iurimatias @hesterbruikman 

Something we haven't discussed is that we need to show a "Make sure you have your account password and seed phrase stored." before downloading as it may cause loosing funds and the account access. On MacOS it works fine  when you hit "Replace" when you are dropping the new dmg into the application folder (It remembers the seed credentials on the start). But I assume users will also uninstall first so credentials are lost or just it works differently on Linux / Windows or some error occurred during the installation or something else, thats why I would suggest to show this modal on all platforms.

Figma: https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1847%3A12524

<img width="990" alt="Screenshot 2020-11-11 at 10 57 28" src="https://user-images.githubusercontent.com/52249767/98797467-e54a6e80-240c-11eb-9285-d172bd98658f.png">

<img width="657" alt="Screenshot 2020-11-11 at 11 01 15" src="https://user-images.githubusercontent.com/52249767/98797924-889b8380-240d-11eb-8322-07262a0ceaa6.png">

<img width="475" alt="Screenshot 2020-11-11 at 11 03 36" src="https://user-images.githubusercontent.com/52249767/98797939-8d603780-240d-11eb-8650-eb84ff830d70.png">

**Comment by hesterbruikman** [comment]
Good catch @simonricoo! So you mean tapping Download in the snackbar at the top prompts this modal first, if you tap Download on the modal, you actually download the file, correct?

I like the inclusion of the native mac Menu bar in the design. @iurimatias are native menu bars planned for? I see QML has a type available at least for Mac and Linux: https://doc-snapshots.qt.io/qt5-5.9/qml-qt-labs-platform-menubar.html
