### ISSUE TITLE
Disable random selection of flag emojis for the wallet account and community channels 

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12907]
### Description

When creating a new wallet account or community channel, a random emoji is selected, but that emoji can be a random flag and it can become awkward, so it's better to disable that.

Flags can later still be manually selected by the user of course.

**Comment by alexandraB99** [comment]
Create/edit channel popup logic is already there:

https://github.com/status-im/status-desktop/assets/31625338/10ce5a27-9be2-496a-b842-8f52a4c8af77
