### ISSUE TITLE
Asset minted by the Owner doesn't appear in the Airdrop list until an app reload

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12906]
# Bug Report

## Description

The Owner of a community minted a new Asset token as a community token.
That Asset didn't appear in the list to Airdrop until the Owner reloaded the app.
Same thing for the TokenMaster, they couldn't see the Asset until an app restart.
Collectibles worked right away however.

## Steps to reproduce

1. Create an on request community in Account A
2. Invite Account B to community
3. Join using Account B and approve using A
4. A mints the Owner token and airdrops a TM token to B
5. B is now a TM
6. A mints a new Asset token for the community
7. Transaction works
8. Both of them check the Airdrop panel and the Asset list -> cannot see the Asset :exclamation: 
9. Reload the app
10. Both go check again and it is there :heavy_check_mark: 

#### Expected behavior

Minted Community Assets are visible in the Airdrop list as soon as the transaction is successful

#### Actual behavior

App restart needed before the Asset is visible

### Additional Information

Tested on testnet mode

- Status desktop version: 0.15.0 RC5

**Comment by MishkaRogachev** [comment]
I've reproduced the steps and on step 8 i see asset on both accounts without restarting the app (or even refreshing the community page):

<img width="633" alt="Screenshot 2023-12-12 at 21 35 12" src="https://github.com/status-im/status-desktop/assets/2522130/b7769d5f-6015-4f00-9f32-e42eba46e547">
<img width="633" alt="Screenshot 2023-12-12 at 21 35 07" src="https://github.com/status-im/status-desktop/assets/2522130/b753e837-fed1-4853-9481-30b96a5473ec">
<img width="633" alt="Screenshot 2023-12-12 at 21 31 51" src="https://github.com/status-im/status-desktop/assets/2522130/a4d350a3-9c71-4751-b212-fe70ad0b85e7">
<img width="633" alt="Screenshot 2023-12-12 at 21 31 41" src="https://github.com/status-im/status-desktop/assets/2522130/ceb41eb9-4587-4b9c-982d-843cc30c05b4">

**Comment by MishkaRogachev** [comment]
Collectibles also work (second app screenshots):

<img width="633" alt="Screenshot 2023-12-12 at 21 48 29" src="https://github.com/status-im/status-desktop/assets/2522130/86d866f0-3ab5-49f7-86f5-3b10224368f2">
<img width="633" alt="Screenshot 2023-12-12 at 21 48 19" src="https://github.com/status-im/status-desktop/assets/2522130/a79077bc-a95f-4e2a-aeb0-0a1e85e1a162">

**Comment by MishkaRogachev** [comment]
https://github.com/status-im/status-desktop/assets/2522130/21ce2e6c-a892-4f51-a535-f0460075e7df

**Comment by MishkaRogachev** [comment]
there is a similar task, but it is a different component: https://github.com/status-im/status-desktop/issues/12062
