### ISSUE TITLE
Do not modify the node configuration directly

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#12918]
### Description

In desktop we use in a couple of places the function `saveConfiguration` https://github.com/status-im/status-desktop/blob/master/src/app_service/service/node_configuration/service.nim#L82 to update values in the node config, like the log level, waku mode, waku version, etc. This can lead to errors in which the node configuration being saved does not have correct values in case it was modified by status-go by some other function, and we might end up overriding some value we didnt intend to.

Solving this will require status-go work to implement new API methods to replace the invocations to saveConfiguration. The flow for these functions should be:

1. Load the current NodeConfig
2. Modify the NodeConfig setting... (i.e. if we want to switch the log level,  we'd set `config.LogLevel = value`
3. Save the NodeConfig
4. Return the updated node config so status-desktop can update its own state (not sure about this step).

**Comment by igor-sirotin** [comment]
As for `setFleet`, it's currently done like this:
https://github.com/status-im/status-desktop/blob/0a94af6fc75ca860197843fafaabac3747deb0c2/src/app_service/service/node_configuration/service.nim#L146-L186

We should instead just call `SaveSetting` and restart the app. And `LoginAccount` will do the job of loading the value from settings. Probably same approach should be taken for some other values.

related: https://github.com/status-im/status-go/pull/4785

**Comment by richard-ramos** [comment]
That sounds good!
The less the clients have to touch the node config the better. Status-go already has the node configuration for the user so it does not make sense for us to modify the node config ourselves, when status-go can just receive the new values to modify and do the update itself!

**Comment by igor-sirotin** [comment]
@jrainville this task is related to https://github.com/status-im/status-desktop/issues/12977.
Would make sense to work on them in a row.
