### ISSUE TITLE
Runtime log level control doesn't work

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#12919]
## Bug description

It should be possible to set the run-time log level in 2 ways:
- `--log-level` CLI option
- `STATUS_RUNTIME_LOG_LEVEL` environment variable

The switch kinda works, but with limitations.
- In debug build: I'm not getting TRACE logs.
- In release build: I'm not getting DEBUG and TRACE logs.

All other settings like ERROR, WARN, INFO always work.

Even though I can see that the log level is set to correct value here:
https://github.com/status-im/status-desktop/blob/34d0719b397efba9e7b2ffbea541d5e748fcb67d/src/nim_status_client.nim#L63

I still don't see desired log messages in the terminal.

## `TRACE` level and status-go

Actually, if you try to set log level to `TRACE`, you won't be able to login to the account, because we pass this value to status-go, which doesn't support `TRACE` value. This should also be fixed, it's kinda related.

## Possible reason

There're 2 places where we check if `LOG_LEVEL` env variable is set:
https://github.com/status-im/status-desktop/blob/34d0719b397efba9e7b2ffbea541d5e748fcb67d/src/app/boot/app_controller.nim#L441

https://github.com/status-im/status-desktop/blob/34d0719b397efba9e7b2ffbea541d5e748fcb67d/src/app/boot/app_controller.nim#L136

This is definitely wrong, at least because the env variable name is now `STATUS_RUNTIME_LOG_LEVEL`.
Also, we should check is `--log-level` CLI option was set.

I tried to fix it, but it still didn't work for me 🙁 

## My attempts

I tried to fix it, you can find my attempts in `temp/runtime-log-level-fix-attempt` branch.

**Comment by igor-sirotin** [comment]
cc @saledjenic

**Comment by saledjenic** [comment]
@igor-sirotin will take a look just to find some time.
