### ISSUE TITLE
Linux: clicking cross button closes app Window but does not kill the process when not logged in

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12920]
### Description

1. open app on linux
2. do NOT login, stay on the welcome screen
3. click cross button to close the app
4. check processes running

![image](https://github.com/status-im/status-desktop/assets/82375995/e75a59f6-ea87-41ec-8c92-272c1f325690)

**Comment by anastasiyaig** [comment]
Nope to both

**Comment by anastasiyaig** [comment]
thanks @caybro ! can u handle this? It is also a reason for my non smart tests being failed

**Comment by caybro** [comment]
> thanks @caybro ! can u handle this? It is also a reason for my non smart tests being failed

Yeah, I'm having a look

**Comment by caybro** [comment]
@anastasiyaig if you start with a fresh account, is the settings "Minimize on close" on or off for you by default?

**Comment by caybro** [comment]
Asking because for me, it's `true`, meaning that we default to "hide into tray" instead of quitting the app. In that sense, the behavior you describe in this issue is actually correct: the app doesn't quit, the window is hidden and the app is kept running in the background.

**Comment by caybro** [comment]
I can't reproduce even the second case; that is, for me, the app correctly quits if we are on the login screen

**Comment by jakubgs** [comment]
Yes, it works correctly on the login screen, but not once you've logged in.

**Comment by caybro** [comment]
I can't reproduce in current, neither before or after login
