### ISSUE TITLE
Use shard.test as default prod and remove references to status.prod and status.test

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#12968]
### Description

- [x] set shard.test as prod default
- [x] remove all references to status.prod and status.test
- [x] remove all references to waku v1 fleets

related: https://github.com/status-im/status-go/pull/4161/

### QA Test Scenario Description
Scenario 1
1. 
2. 
Scenario 2
1. 
2.

**Comment by chair28980** [comment]
Implemented in:

- https://github.com/status-im/status-go/pull/4434
- https://github.com/status-im/status-go/pull/4435
- https://github.com/status-im/status-desktop/pull/12963
