### ISSUE TITLE
Implement Sign API - WalletConnect (stub UI)

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#12960]
https://docs.walletconnect.com/api/sign/wallet-usage

**Comment by saledjenic** [comment]
Not entirely sure what to do with this one, cause the used `SignClient` on the page (https://docs.walletconnect.com/api/sign/wallet-usage) from their documentation refers to the module coming from `"@walletconnect/sign-client"`, but we already achieved the same using `Web3Wallet` which is coming from `"@walletconnect/web3wallet"`, as stated on another page (https://docs.walletconnect.com/web3wallet/wallet-usage) in their documentation as well.

What do you think?

**Comment by stefandunca** [comment]
I agree not to implement that API specifically, it looks like might be older than the web3sdk and delivers the same API for wallets;
