### ISSUE TITLE
Wallet: Market data is not fetched sometimes

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12987]
### Description

Usually being found by autotest

**Env:** `Ubuntu 22.04, master`

Steps:

1. create fresh account
2. check the balance is 0
3. add w/o account in settings
4. enable the `Include in total balance` toggle for that account
5. check balance in main wallet screen

As result, sometimes All accounts is showing 0 and market data is 0. the test has timeout of 10 seconds to fetch the data

https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/120/allure/#suites/4516d92a77da5a21d6cc36335b5a380f/fb458b95cfb8b1ba/?attachment=2de1b38e5fe85145

![image](https://github.com/status-im/status-desktop/assets/82375995/9c7c0cef-e64c-4185-84ab-dc440435f2d2)

**Comment by anastasiyaig** [comment]
We depend on cryprocompare API to fetch the prices https://min-api.cryptocompare.com/pricing

**Comment by alaibe** [comment]
Goal is to create a mock market data that we can return when doing test

**Comment by anastasiyaig** [comment]
i will close that with the hope we can use fork in autotests ( https://github.com/status-im/desktop-qa-automation/issues/385)
