### ISSUE TITLE
Fetch community metadata for community tokens

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#12985]
Fetch community metadata (name and image) for community tokens

Collectibles have already system in place. Currently @dlipicar is doing adjustments to fetching logic, so this task will be split into two parts
* [x] Fill data from community cache. Implement CommunityManager for wallet so common code for tokens and collectibles can be placed there
* [x] Add fetching community metadata for tokens. Lazy loading will be called when re-fetching assets for wallet.
* [x] Add event handling of fetched community data event on status-desktop side

**Comment by Khushboo-dev-cpp** [comment]
Please check WalletAssetsStore.qml and check if which approach of joining with community model is enough for this.

**Comment by caybro** [comment]
@Cuteivist I assume this issue/epic can be closed?
