### ISSUE TITLE
New issues with contact requests

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#13019]
# Bug Report
<img width="1000" alt="Screenshot 2023-12-15 at 14 00 12" src="https://github.com/status-im/status-desktop/assets/2522130/c501cb4f-f158-4e3e-9400-37be75a8e13d">

![image](https://github.com/status-im/status-desktop/assets/2522130/4ede7f27-ff0b-4999-8a67-82d49efa20f3)

## Description

I've recently noticed 2 new contact request issues, both reproduced with moderate frequency:

1) The receiver doesn't get the contact request , it looks like it gets lost in the network. But normal messages don't get lost, at least that often.
2) The sending party sometimes receives an additional message that the contact request is accepted, although the sending party does not perform any additional manipulations. May be related to https://github.com/status-im/status-go/issues/3803

## Steps to reproduce

1. Create a new account
2. Send a contact request to a user
3. Goto 1 until one of the problems is reproduced.

#### Expected behavior

1. Receiver gets a contact request
2. Sender sees 3 messages:

<img width="1000" alt="Screenshot 2023-12-15 at 14 09 41" src="https://github.com/status-im/status-desktop/assets/2522130/8d1795df-0462-41c0-b0aa-48bd6db7dd02">

#### Actual behavior

Sometimes happens (1) or (2) problem

**Comment by MishkaRogachev** [comment]
Contact flows seem to be fully-working in the current master: 
<img width="1016" alt="Screenshot 2023-12-18 at 18 04 48" src="https://github.com/status-im/status-desktop/assets/2522130/5741c2cf-03bd-49be-9f73-5104ec6082c1">
However, if `acceptContactRequest` gets lost in the network and a user receives an other message from a contact-requested contact, it may spam extra `acceptedContactRequest` message. I am investigating, is it possible to reproduce such behaviour in status-go test

**Comment by anastasiyaig** [comment]
@MishkaRogachev pls ping me in case u submit a PR with a fix, we have an autotest that was seeing this (perhaps this one) issue as well, i wanna try it

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev pls ping me in case u submit a PR with a fix, we have an autotest that was seeing this (perhaps this one) issue as well, i wanna try it

Sure! i'm working on the status-go pr right now

**Comment by MishkaRogachev** [comment]
@anastasiyaig issue with extra mutual messages should be resolved by https://github.com/status-im/status-go/pull/4488
