### ISSUE TITLE
Read the Nonce from the network instead from the local cache

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#13033]
Reading the Nonce from the local cache may be incorrect if the tx is made out of the Status app or if Status app sends a tx prepared by the dapp (via WalletConnect). A submitted tx with a wrong Nonce results in a failing tx, that's why we need to read the Nonce from the network.

**Comment by saledjenic** [comment]
Implemented in this PR https://github.com/status-im/status-go/pull/4489

**Comment by iurimatias** [comment]
closing since this is marked as done and PRs are merged
