### ISSUE TITLE
Login error is not visible when authenticating with TouchID

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#13046]
# Bug Report

## Description

If biometric authentication is enabled (TouchID on MacOS) and an error occurs during login, the error is not visible.
Clicking `use password instead` make the error visible.

## Steps to reproduce

I have some problems with 0.15.0-RC on my account.
But probably this can be reproduced by replacing a password in keychain with a wrong one.

### Info

status-desktop version: 0.15.0-rc9

**Comment by igor-sirotin** [comment]
I'm able to reproduce this on 0.15 with my issue here: https://github.com/status-im/status-desktop/issues/13048

https://github.com/status-im/status-desktop/assets/25482501/d2748023-e2db-4cb7-b584-a6edf2c600b6

**Comment by igor-sirotin** [comment]
not sure if it's reproducible on master.

**Comment by igor-sirotin** [comment]
I can confirm the issue is reproducible on latest master nightly build: 

<img width="1312" alt="Screenshot 2024-01-24 at 13 39 45" src="https://github.com/status-im/status-desktop/assets/25482501/952bc9e4-b03e-446a-a75d-82fefb7ba8fd">
<img width="1312" alt="Screenshot 2024-01-24 at 13 39 50" src="https://github.com/status-im/status-desktop/assets/25482501/f0b4ab01-7454-4d08-9b09-b6b43f462ff9">

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one
