### ISSUE TITLE
StatusQ: Add optimized version of ExpressionRole for SFPM

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#13047]
# Bug Report

## Description

`SortFilterProxyRole`'s `ExpressionRole` has performance issue because internally adds to expression's context values of all other roles, also recursively when multiple expression roles are used. The idea is to allow to define explicitly which roles should be provided to the script.

**Comment by caybro** [comment]
`ExpressionSorter/Filter` suffer from the same issue
