### ISSUE TITLE
[Second iteration - Token management] `Assets` in main `Wallet Layout`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13044]
This tasks pretends to cover all needed refactors in `Assets View` regarding how data is taken from backend and managed on the UI after the agreements decided by the team in https://github.com/status-im/status-desktop/issues/12766.

**NOTE:** Here it's needed to deal, as well, with some potential performance issues if they exist.

We pretend to use just one `ListView` with 2 different sections.

**Comment by noeliaSD** [comment]
Depends on https://github.com/status-im/status-desktop/issues/12766

**Comment by noeliaSD** [comment]
We need to clarify if in Assets page there's also the expandable layout

**Comment by noeliaSD** [comment]
If not, first iteration coverd everything!

**Comment by alexandraB99** [comment]
Done [here](https://github.com/status-im/status-desktop/commit/1bd23b027d1da18243ae9219e7650c7e626209e2)
