### ISSUE TITLE
Migration errors when opening app from deep link

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#13053]
# Bug Report

![0 15_a_new_start](https://github.com/status-im/status-desktop/assets/47554641/ecbbdc4c-43bb-4334-9179-ce522e79957a)

## Description

Opening status from a `status.app` profile page doesn't work

![image](https://github.com/status-im/status-desktop/assets/47554641/cc30190c-0fd1-4876-8991-ba0d0e56d69b)

## Steps to reproduce

1. Created a new account
2. Tried to open the profile using the "Open profile in Status" option from the profile page (see picture above)
3. The app was highlighted, but nothing happened
4. I closed the app
5. Clicked again on the "Open profile in Status"
6. Application opened showing migration error from the screenshot on login

#### Expected behavior

After login app opens and give the chance to connect with the contact from the profile link

#### Actual behavior

I got stuck and the user DB got corrupted.

### Additional Information

- Status desktop version: StatusIm-Desktop-v0.15.0-rc.9-6dc10b-aarch64.dmg
- Operating System: MacOS 14.1.1

**Comment by anastasiyaig** [comment]
@stefandunca i guess this is the same as https://github.com/status-im/status-desktop/issues/13048
