### ISSUE TITLE
User is blocked in modal when using biometrics to share addresses when joining a community

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#13051]
# Bug Report

![blocked_after_authenticating](https://github.com/status-im/status-desktop/assets/47554641/8c3a8a14-8456-41fe-bca5-817fd81a4e2e)

## Steps to reproduce

1. I recovered the account from the seed phrase
2. Joined a community
3. Chose "use biometrics instead"
4. I used the biometrics
5. The app was still stuck in the authenticate dialog as in the screenshot
6. I also tried to insert the password manually but none of the buttons were enabled

#### Expected behavior

After using biometrics I can move forward

#### Actual behavior

I got blocked in Modal

### Additional Information

- Status desktop version: StatusIm-Desktop-v0.15.0-rc.9-6dc10b-aarch64.dmg
- Operating System: MacOS 14.1.1

**Comment by kounkou** [comment]
I have managed to reproduce the problem following the steps provided in description. My observations are that once we click on the `Use biometrics instead` the UI disables the 3 buttons : `Cancel` `Use biometrics instead` and `Authenticate`, as we fill the biometrics, but those button are never enabled again once the popups for inputing the biometrics are closed. Investigating why we have this problem.
