### ISSUE TITLE
Reply to a message with an emoji shows a bunch of HTML code

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#13067]
# Bug Report

## Description

![image](https://github.com/status-im/status-desktop/assets/11161531/07b918ef-b82c-42ae-bcdd-e6d375459b81)

1) Reply to a message ending in an emoji in some Community's channel
2) Quoted message shows up with a bunch of HTML code at the end

### Additional Information

- Status desktop version: 0.15.5RC9
- Operating System: macOS Sonoma

**Comment by igor-sirotin** [comment]
I think it's fixed in master already: https://github.com/status-im/status-desktop/issues/12786

**Comment by caybro** [comment]
Yup, fixed here: https://github.com/status-im/status-desktop/pull/12867
