### ISSUE TITLE
Messages are not sent when Light Mode is enabled

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13064]
# Bug Report

## Description

After switching to Light Mode no messages are sent or received at all.

## Steps to reproduce
1. Launch the app
2. Switch to Light Mode and restart the app
3. Send a message to one of the contacts

#### Expected behavior
Message is delivered to the recipient.

#### Actual behavior
Message is not sent.
### Additional Information
From the geth.log -> `ERROR[12-20|11:15:54.527|github.com/status-im/status-go/wakuv2/filter_manager.go:355]                        filter resubscribe findPeer error        error="filter could not select a suitable peer"`
Note: After switching back to relay mode all the unsent messages are delivered correctly.
- Status desktop version: StatusIm-Desktop-v0.15.0-rc.9-6dc10b
- Operating System: macOS Sonoma 14.0

**Comment by endulab** [comment]
@lukaszso I tried to reproduce the issue , but it worked correctly. I used master branch.

![image](https://github.com/status-im/status-desktop/assets/61889657/2d192397-5520-4342-8f5f-32ddf97ca1e1)

**Comment by lukaszso** [comment]
Tried with latest master and also could not reproduce this issue. Let's close it.
