### ISSUE TITLE
Profile: uploading .heif and .tiff images does not make any effect (picture is not set)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13077]
### Description

1. open app
2. during onboarding set `.heif` picture
3. apply

As result, picture is not saved. Based on Constants.qml, it should work:

```
readonly property var acceptedDragNDropImageExtensions: [".png", ".jpg", ".jpeg", ".heif", ".tif", ".tiff"]
```

```
ERR 2023-12-21 12:58:06.746+03:00 error:                                     topics="general-app-service" tid=4017575 file=service.nim:61 procName=generateImages errDesription="response is not an array"
```

https://github.com/status-im/status-desktop/assets/82375995/4ced56a8-1078-4809-aaff-0bc56ef74390

**Comment by anastasiyaig** [comment]
@caybro maybe we can address it within profile showcase changes?

**Comment by caybro** [comment]
> @caybro maybe we can address it within profile showcase changes?

I doubt it; the error comes from `status-go` which I think means it can't really convert the HEIF to JPG (which is what we do for all images)

**Comment by caybro** [comment]
@jrainville @borismelnik @igor-sirotin any idea if we really support HEIF everywhere? If not, I'd remove it from the supported image formats

**Comment by anastasiyaig** [comment]
@caybro `heif` and `tiff` then, both are not working

**Comment by borismelnik** [comment]
> @jrainville @borismelnik @igor-sirotin any idea if we really support HEIF everywhere? If not, I'd remove it from the supported image formats

I know that for HEIF we can add a plugin, but im not sure that we need to support this. I never met the app which support this format. I think we should just remove it from supported images formats

**Comment by igor-sirotin** [comment]
@caybro I have no idea 🙂

**Comment by caybro** [comment]
> > @jrainville @borismelnik @igor-sirotin any idea if we really support HEIF everywhere? If not, I'd remove it from the supported image formats
> 
> I know that for HEIF we can add a plugin, but im not sure that we need to support this. I never met the app which support this format. I think we should just remove it from supported images formats

On the Qt side, yes and it works on macOs only :) Question is whether `status-go` supports it. But yeah, I'd remove it as it doesn't work everywhere even in the app itself
