### ISSUE TITLE
"This is your signing phrase" popup shows during loading screen

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#13071]
If "Wallet" section was the last section opened, then during next app startup the "This is your signing phrase" popup appears during the loading screen:

<img width="1312" alt="Screenshot 2023-12-20 at 16 17 53" src="https://github.com/status-im/status-desktop/assets/25482501/d4326d55-0ba2-4c6f-be89-ff488eada719">

**Comment by anastasiyaig** [comment]
@caybro @alaibe any ideas which team should address that?

**Comment by caybro** [comment]
> @caybro @alaibe any ideas which team should address that?

Hard to say... :) Maybe @alexjba has an idea?

**Comment by alaibe** [comment]
Happy to take that on
