### ISSUE TITLE
[Profile Showcase backend] Improvements for profile showcase communities

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#13076]
## Design 

https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=725-11513&mode=design&t=pqb7Pg4MWmokTsr4-0

<img width="748" alt="Screenshot 2023-12-21 at 16 43 08" src="https://github.com/status-im/status-desktop/assets/2522130/4bb21f6b-2e72-4969-85ff-5f7ee43c3664">

## Requirements (backend only):
- If a user leaves the community which is being presented in the profile, the corresponding community entry should be removed and the profile change should be dispatched.
- Prefetch communities when receiving profile showcase for a contact

**Comment by igor-sirotin** [comment]
> Prefetch communities 

This is wrong to do. **We shouldn't make more network requests as a reaction to network events.**
Therefore we should start fetching communities/contacts/whatever from UI events.

Basically we implemented just the same thing with link previews here: https://github.com/status-im/status-desktop/pull/12613. 
If we would start fetching the community for link preview automatically on message reception, then it's easy to spam Waku. Consider example: 
1. Imagine a 10k users community
2. you send a link to community 
3. every online user will start fetching the community from Waku <--- bad, right?

As we want to update the community at some point. Consider example:
1. we open someone's profile showcase 
4. 1 year passes
5. One of profile showcase's community name changes
6. We open profile showcase again
7. We want to fetch the community again.

That means we want to fetch the community every time we open the profile showcase. To prevent fetching it too frequently, in desktop `requestCommunityInfo` is extended with `requiredTimeSinceLastRequest` argument.

**Comment by jrainville** [comment]
Fixed by https://github.com/status-im/status-go/pull/4686
