### ISSUE TITLE
Add save receiver address to the context menu in tx details view

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#13095]
Related Figma:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=21991%3A258883&mode=dev

Note:
- All activity in the wallet relating to this address are updated to show the saved address name

**Comment by lukaszso** [comment]
I can confirm that saving receiver address from the transaction details works fine.
