### ISSUE TITLE
Preferred chains maintained in two places

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#13109]
We're maintaining 2 preferred chains for the same address in some cases (when the user saves a wallet account).

Primarily we're maintaining preferred chains in the `keypairs_accounts` table, for all wallet accounts and also we're maintaining preferred chains in the `saved_addresses` table as well for all saved addresses.

The trick is that the wallet address can be added to the saved addresses as well. In this case we have 2 preferred chains for the same address that are not synced.

_Some of the solutions:_

1. disable adding wallet addresses to the saved addresses list

2. syncing the change, when changing referred chains for the wallet address, to check if it exists in the saved addresses and update preferred chains there as well, and vice versa, when changing preferred chains for the wallet address to check if it exists in the keypairs_accounts table and update chains there

3. merging `saved_addresses` into `keypairs_accounts` table, adding some new flags `saved` (to mark if the address is added to the saved addresses or not), `saved_removed` (to mark if the address is removed from the saved addresses list or not) and `saved_clock` (to set the clock of the last change made over saved address), that way we can have a single source of truth and also if keypair/account is deleted (we're doing a soft delete, just setting a flag, not delete it for real), we will still have it in the list of saved addresses till the moment `saved_removed` flag is set to `true`. 
 

I'm maybe more for solution 3.  but we can discuss it.

**Comment by benjthayer** [comment]
Thanks @saledjenic from a UX perspective, I don't think there's really any benefit in the user adding one of their accounts as a saved address so IMO we could go for route 1 (validating the address field when the user attempts to add one of their own accounts to their saved addresses). It feels like it would be beneficial to safeguard the mental schema that `saved addresses` are primarily for managing and accessing counterparties. 

We do permit the user to add existing contacts into the saved addresses list even though that causes similar duplicity in the UI (the address would then be visible in the send dialog under both the contacts and saved addresses tabs). But in that case, the concept of saved addresses being the method to manage and access external counterparties is still retained. 

If we did block the user from adding one of their own accounts as a saved address, would we also need to consider the edge case of a user adding a saved address and then trying to import that same address as their own account?

Just my initial thoughts, WDYT @John-44 ?

**Comment by John-44** [comment]
> Thanks @saledjenic from a UX perspective, I don't think there's really any benefit in the user adding one of their accounts as a saved address so IMO we could go for route 1 (validating the address field when the user attempts to add one of their own accounts to their saved addresses). It feels like it would be beneficial to safeguard the mental schema that `saved addresses` are primarily for managing and accessing counterparties.
> 
> We do permit the user to add existing contacts into the saved addresses list even though that causes similar duplicity in the UI (the address would then be visible in the send dialog under both the contacts and saved addresses tabs). But in that case, the concept of saved addresses being the method to manage and access external counterparties is still retained.
> 
> If we did block the user from adding one of their own accounts as a saved address, would we also need to consider the edge case of a user adding a saved address and then trying to import that same address as their own account?
> 
> Just my initial thoughts, WDYT @John-44 ?

@benjthayer @saledjenic I would be in favour of blocking the user from saving one of their own addresses as a saved address, as this doesn't serve any purpose, could be confusing, and leads to the corner cases @saledjenic described.  Handling "the edge case of a user adding a saved address and then trying to import that same address as their own account" seems like it would be easier to handle.  We could do something as simple as pop up a dialogue letting them know that the saved address will be deleted as a result of added an account with the same address, or something like that.

**Comment by saledjenic** [comment]
Following what's discussed above we now have the following handling:
- if the user tries to save an address, that is already added to the Wallet, we display the "This address is already added to Wallet" error when validating the address input field
- if the user tries to add an account to the Wallet section, that is already saved, we display a Yes/No prompt to the user letting him know if he wants to proceed with adding an account to the Wallet section the related saved address will be removed.

@benjthayer in the description of https://github.com/status-im/status-desktop/pull/13265 you can see a video of this functionality. If you have any comments on the wording, let me know (cause that prompt and error are not in the current design).

**Comment by benjthayer** [comment]
> Following what's discussed above we now have the following handling:
> 
> * if the user tries to save an address, that is already added to the Wallet, we display the "This address is already added to Wallet" error when validating the address input field
> * if the user tries to add an account to the Wallet section, that is already saved, we display a Yes/No prompt to the user letting him know if he wants to proceed with adding an account to the Wallet section the related saved address will be removed.
> 
> @benjthayer in the description of #13265 you can see a video of this functionality. If you have any comments on the wording, let me know (cause that prompt and error are not in the current design).

Thanks @saledjenic, I've done the design for the first scenario and added it to the main flows - the main enhancement to what you have in the video you referenced is that we show the account card as part of the validation so the user can clearly see which account they are trying to add as a saved address:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=22366-83911&mode=design&t=ARBs7CNm2wuG00wF-4

<img width="546" alt="Screenshot 2024-01-23 at 9 25 50 AM" src="https://github.com/status-im/status-desktop/assets/110033914/c291879a-17a2-4d38-bea8-6a0a902db1d2">

This is very similar to what we show if the user enters the address of a contact:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=21991-256460&mode=design&t=ARBs7CNm2wuG00wF-4

<img width="554" alt="Screenshot 2024-01-23 at 9 28 09 AM" src="https://github.com/status-im/status-desktop/assets/110033914/b60d6ad4-b896-49cd-b411-b8e0424d9f7d">

I've not yet designed the scenario where the user attempts to import an address which is already in their saved addresses. I'll let you know here when that's done, but thanks for implementing what you have - I don't imagine it will be drastically different to that :)

**Comment by saledjenic** [comment]
Ahhh I didn't know that even for a contact, I guess it was added recently (after I developed add/edit saved address). 
Ok, thanks for the heads-up, will add that to that PR.

**Comment by benjthayer** [comment]
> Ahhh I didn't know that even for a contact, I guess it was added recently (after I developed add/edit saved address). Ok, thanks for the heads-up, will add that to that PR.

Yeah sorry @saledjenic  this one is recent - I was going to add an issue for it. 

The difference to note between adding a contact to saved addresses and adding your own account is that adding a contact is allowed - it isn't a blocking validation just a warning so the user can continue on and add the contact as a saved address. However, in the case of adding your own account as a saved address it is a blocking validation (red) - the user cannot proceed as the primary CTA is disabled.

**Comment by saledjenic** [comment]
@benjthayer want to let you know those 3 types of cards (wallet account/saved address/contact) will be handled in this issue https://github.com/status-im/status-desktop/issues/13280
