### ISSUE TITLE
Synchronization issues between mobile and desktop

### ISSUE THREAD

**Issue by Ely5ia** [status-im/status-desktop#13114]
I use the mobile client that supports waku2 and the latest release version of the desktop version, but I use another account on the desktop to send a chat request to the main account, and the mobile version cannot accept it. And it seems that the chat records of the two clients cannot be synchronized.
In other words, mobile and desktop still cannot communicate at the same time. Is there any solution? If it is because the function implementation is not yet complete, then I will wait for the update.

Mobile version: 1.25
Desktop version: 0.15-rc.9

**Comment by iurimatias** [comment]
this is expected somewhat as 0.15 is using sharding and is working on a different p2p network
