### ISSUE TITLE
Onboarding: Login failed on user creation

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13112]
### Description

This was found by autotest https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-423/1/allure/#suites/804b25da7c0d1c4c7f8a050c6a89e043/3889c7166d2c5707/

I cant replicate manually yet. Unfortunately i dont have geth logs stored , but this is an application log 
[login_failed.log](https://github.com/status-im/status-desktop/files/13793042/login_failed.log)

Autotests use debug flag `'--LOG_LEVEL=DEBUG'` when starting the app itself, perhaps this is a reason? I remember a problem with TRACE (https://github.com/status-im/status-desktop/issues/12919)

Values used by autotests: `name='squisher', password='0000000000'`

![image](https://github.com/status-im/status-desktop/assets/82375995/80be6330-773f-4d42-8d0c-c31c8bc68250)

**Comment by mprakhov** [comment]
this test is enabled, we haven't observe this issue in the test for the last month... closing as non-reproducible
