### ISSUE TITLE
`BACKEND`: Add sorting criteria to `GetOwnedCollectiblesAsync`

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#13120]

**Comment by caybro** [comment]
Won't be probably needed with the new approach of getting _all_ data, and (still) sorting/filtering in QML (using SFPM); all we need for the backend is to store the currently selected sort/filter criteria (role name)

**Comment by dlipicar** [comment]
> Won't be probably needed with the new approach of getting _all_ data, and (still) sorting/filtering in QML (using SFPM); all we need for the backend is to store the currently selected sort/filter criteria (role name)

Yeap, this is not needed anymore
