### ISSUE TITLE
Settings -> Assets don't show correctly

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13150]
![image](https://github.com/status-im/status-desktop/assets/491074/80f732d8-65d6-44ec-ba32-131ac0027fac)

**Comment by alaibe** [comment]
Yes that should be a supported scenario

**Comment by alaibe** [comment]
FYI: same error on prod mode

**Comment by caybro** [comment]
> FYI: same error on prod mode

Yeah, it's because one of the services is down and the backend puts it to the "loading" state
