### ISSUE TITLE
Community order has expanded address covering the title

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13158]
![image](https://github.com/status-im/status-desktop/assets/491074/06c3cfe5-b98f-4795-80b9-467ef5c6a5ae)

**Comment by Khushboo-dev-cpp** [comment]
I could not reproduce this on latest master.

**Comment by caybro** [comment]
Yeah I remember fixing this already some time ago

**Comment by alaibe** [comment]
Here issue is that the community name is not being fetched, let me reopen as there is a new design coming

**Comment by benjthayer** [comment]
Hey @alaibe I've added designs to the relevant flows to cover if the community name could not be fetched:

**Community tag inside collectible detail page:** 
NB the collectible detail page linked features the tweaked collectible detail page design as covered in [this GH issue](https://github.com/status-im/status-desktop/issues/13399)

<img width="1622" alt="Screenshot 2024-02-06 at 9 06 26 AM" src="https://github.com/status-im/status-desktop/assets/110033914/c8f4ff55-e700-4ab3-8d6e-8de7aa72c86a">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21257-30930&mode=design&t=VjUau4UutkmCghHr-4

--

**Community tag inside Assets detail page:** 

<img width="1025" alt="Screenshot 2024-02-06 at 9 13 41 AM" src="https://github.com/status-im/status-desktop/assets/110033914/6d2772f3-26f3-40f2-a09d-6f6f9003d27a">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21337-308555&mode=design&t=VjUau4UutkmCghHr-4

--

**Community tag inside Asset list item:** 

<img width="1119" alt="Screenshot 2024-02-06 at 9 15 28 AM" src="https://github.com/status-im/status-desktop/assets/110033914/56746ac5-79ad-4fcc-ae8f-6703e2cbc036">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21330-195031&mode=design&t=VjUau4UutkmCghHr-4

--

**Community tag inside Collectible list item:** 

<img width="1145" alt="Screenshot 2024-02-06 at 9 16 05 AM" src="https://github.com/status-im/status-desktop/assets/110033914/418eab37-826d-449e-9589-5f7552818900">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21292-169137&mode=design&t=VjUau4UutkmCghHr-4

--

**Community tag inside send dialog:** 
NB the send dialogs linked feature a slight tweak to the layout of the collectibles list to accommodate the `Community minted` and `Other` section headers as well as clarifying how the user drills into a community folder to select a collectible. A new issue will be created to summarise these changes.

In the Send dialog we append the first few characters of the community ID to differentiate between multiple communities whose name could not be fetched.

<img width="1049" alt="Screenshot 2024-02-06 at 9 07 23 AM" src="https://github.com/status-im/status-desktop/assets/110033914/9dd8a17b-c195-4318-9b77-1b4e8bbbaf82">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21292-149842&mode=design&t=VjUau4UutkmCghHr-4

--

**Community tag inside Manage tokens:** 

<img width="1651" alt="Screenshot 2024-02-06 at 9 08 23 AM" src="https://github.com/status-im/status-desktop/assets/110033914/7bbe8b49-0ca8-4434-a0db-688c3db158e6">

Figma:
https://www.figma.com/file/eM26pyHZUeAwMLviaS1KJn/%E2%9A%99%EF%B8%8F-Wallet-Settings%3A-Manage-Tokens?type=design&node-id=1583-105708&mode=design&t=wRfkGGO8V1dEvvU2-4

**Comment by benjthayer** [comment]
@alaibe  - I've updated the final designs for what we show and what interactions are available for when the community name cannot be fetched. After speaking with Pascal, it seems there isn't any information in the smart contract relating back to the community so the best we can do I feel in this situation is to show `Unknown community` and the community address on hover with the ability to click to copy the address incase the user wants to investigate further.
