### ISSUE TITLE
[Wallet] Memory usage skyrockets when loading collectibles tab with a few hundred collectibles

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13165]
# Bug Report

## Description

The memory usage skyrockets when loading the collectibles tab in the main wallet view for accounts with a few hundred items.

<img width="693" alt="Screenshot 2024-01-09 at 15 43 42" src="https://github.com/status-im/status-desktop/assets/47811206/3b60f784-213b-47b4-aa66-b70b7630aa13">

## Steps to reproduce

1. Add a watch account with lots of collectibles. I've used this address `0xcc9d3dd3f433de6c14e8881b13d4bcfe1a3e59f5`
2. Go to the new account and select `Collectibles` tab
3. Give it some time for the collectibles to load (In my case lots of items were visible only after a restart)

#### Expected behavior
The memory usage is decent
#### Actual behavior
The memory usage goes to ~25GB RAM and ~400GB virtual memory
### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/56493fa5e16196ab56747342f5a4af4f492a3529
- Operating System: MacOS

**Comment by caybro** [comment]
Just to be sure, can you try with this PR: https://github.com/status-im/status-desktop/pull/13129 (I added the usage of `FastExpressionFoo` for the collectibles' views as well)

**Comment by alexjba** [comment]
> Just to be sure, can you try with this PR: #13129 (I added the usage of `FastExpressionFoo` for the collectibles' views as well)

It's the same..

**Comment by alexjba** [comment]
Should be fixed by https://github.com/status-im/status-desktop/issues/13045

The memory usage increases really high because the GridView is unrolled and we're loading all the collectible assets in the memory at the same time.

To be tested and closed once #13045 is merged

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-desktop/pull/13283
