### ISSUE TITLE
Add existing ENS name causes app to crash

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1316]
1. Obtain ENS name on mobile.
2. Start Status Desktop with fresh data folder
3. Settings > ENS > Type ENS name, then click continue
4. Expected: see message saying ENS is connected
5. Actual: see message for a second, then app crashes.

**Comment by richard-ramos** [comment]
Is this still happening? I can't reproduce this issue

**Comment by iurimatias** [comment]
can't replicate
