### ISSUE TITLE
[Token Management] Integrate the Advanced settings with backend

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13178]
Integration to be done in `ManageTokensView.qml`

UI PR: https://github.com/status-im/status-desktop/pull/13129
Backend PR: https://github.com/status-im/status-desktop/pull/13128

Additionally we need to enforce these settings:
- in the main wallet (Assets) view
- in Send modal

![image](https://github.com/status-im/status-desktop/assets/5377645/a70e9203-4ee4-48ff-8b02-7ea65ee538cd)

**Comment by caybro** [comment]
@iurimatias question here is: we have a UI in place already which practically does nothing atm; what to do with it? Hide it temporarily for this milestone?

**Comment by Khushboo-dev-cpp** [comment]
@Cuteivist https://github.com/status-im/status-desktop/pull/13358/files#:~:text=//%20TODO%3A%3A%20Need%20to%20connect%20with%20backend%20here%20https%3A//github.com/status%2Dim/status%2Ddesktop/issues/13178

for the send modal you would simply have to plugin the backend values here

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp @caybro You can access it in QML right now. For example in TokensStore you could access it:
> 
> * `root._allTokensModule.showCommunityAssetWhenSendingTokens`
> * `root._allTokensModule.displayAssetsBelowBalance`
> * `root._allTokensModule.displayAssetsBelowBalanceThreshold`

Ive added these in TokensStore, please do test once you work on this integration task though.
