### ISSUE TITLE
[Second Iteration - Token Management] Create the hidden tab (to host both assets and collectibles)

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13188]
Design: https://www.figma.com/file/eM26pyHZUeAwMLviaS1KJn/%E2%9A%99%EF%B8%8F-Wallet-Settings%3A-Manage-Tokens?type=design&node-id=0-1&mode=design&t=J3O9jm3MG1fMTGF0-0

- refactor a bit the placement of the controller(s); need to share them partially across the panels
- emit a notification when something is unhidden

Empty state:
![image](https://github.com/status-im/status-desktop/assets/5377645/0eafd02c-78c7-4563-ada4-528763cf7978)

Hidden tokens:
![image](https://github.com/status-im/status-desktop/assets/5377645/1f5c765a-e53d-447b-9885-c8a126dffdc3)

**Comment by noeliaSD** [comment]
**Requirements from design:**
- The hidden lists can contain 2 different type of elements being them **INDIVIDUAL** tokens OR **GROUPS** (by group --> _collection_ or _community_ depending on the case).
- Whenever a user hides a complete group, this action **prevails above individual items**, meaning that, in case there's already an individual token from community A hidden, if user hides the group corresponding with the community A, all previously individual tokens hidden from A will be "removed" from the hidden view and they will be treated as a hidden group insted.
- Following with the same use case where the user hides a group, any new token received in the list will be automatically hidden.
- In the case of individual token hides, if the user manually hides all tokens in a community, one by one, this WILL NOT be considered a hidden group, so all tokens in this community will be hidden but displayed in the corresponding hidden list as INDIVIDUAL elements.
- Following with the same use case where the user hides all tokens from a group (community or collection), but one by one, if a new token is added in the list, this token will not be hidden. It will be added in the visible tokens list.
- For MVP, there's no posibility to expand groups to display the elements inside. The groups delegate will just contain a count of the elements in the group.

Please, @benjthayer confirm that all these use cases are correct and if there's something missing, please share it!

**Comment by benjthayer** [comment]
> Please, @benjthayer confirm that all these use cases are correct and if there's something missing, please share it!

Perfectly summarised, thank you @noeliaSD ! Also to note, that for the context menu for hidden items:
If a user has hidden more than one token from a collection or community in an iterative fashion, the context menu for each of those hidden individual items should feature the option to `Show all collectibles from this community/collection`. This allows the user to quickly batch unhide items from a collection/community should they wish to do so.

**Comment by noeliaSD** [comment]
Here some agreements the `UI team` has decided to approach the implementation of this task:
- Since both hidden lists need to display 2 different types of delegates, and also the sources will be 2 different models, the `Concat Model` utility can be used to mix model with INDIVIDUAL elements and model with GROUP elements. Then the list delegate needs to distinguish between the element type to display the different delegate design.
- Since after last discussion with backend, the UI will work with the complete individual elements data, the UI is able to build the hidden groups model by its own.
- In case of hidden group action is made, the UI is the responsable of checking if in the existing hidden lists, there are some individual items from this group and updates the list accordingly.

**Here a point to discuss:**
- Whenever the hide group action is triggered all new elements added in the user lists must be considered as hidden so, there are 2 options here:
1. The UI communicates to the backend that this specific group needs to be hidden so, the backend internally modifies ALL individual items from this group to `visible = false` and whenever a new element is added in the list, the backend knows this token needs to be directly hidden.
 2. Whenever the UI receives a model update from the backend, it needs to check if there's a new element belonging to some of the hidden groups to directly change it's visible property.
@caybro @micieslak @alexjba which option do you think is more appropriate?

**Comment by noeliaSD** [comment]
> Here some agreements the `UI team` has decided to approach the implementation of this task:
> 
> * Since both hidden lists need to display 2 different types of delegates, and also the sources will be 2 different models, the `Concat Model` utility can be used to mix model with INDIVIDUAL elements and model with GROUP elements. Then the list delegate needs to distinguish between the element type to display the different delegate design.
> * Since after last discussion with backend, the UI will work with the complete individual elements data, the UI is able to build the hidden groups model by its own.
> * In case of hidden group action is made, the UI is the responsable of checking if in the existing hidden lists, there are some individual items from this group and updates the list accordingly.
> 

This will be the first try but if we see it will take more time than the one we have now available, a first step can be considered by only adding individual items in all lists and postpone the group elements to a next iteration.

**Comment by caybro** [comment]
The approach I'll take is that we have to track (separately) whether a group is hidden or not, in addition to do the same at the individual token level. Ultimately, if both of those conditions are true, we hide (don't display) the individual token in the Hidden section.

**Comment by noeliaSD** [comment]
> The approach I'll take is that we have to track (separately) whether a group is hidden or not, in addition to do the same at the individual token level. Ultimately, if both of those conditions are true, we hide (don't display) the individual token in the Hidden section.

Yeah, but the decision comes when there's a new token added into the list since, as the user has triggered the group hidden option, the individual element "by default" will be hidden, so we could transmit to the backend this "group hidden" action and then the new elements added could come from the backend with the hidden flag set up.

**Comment by noeliaSD** [comment]
Here is the pseudocode we have been discussing:

- token.visible = false && group.visible = true --> individual hide
- token.visible = true && group.visible = true --> visible
- token.visible = false && group.visible = false --> group hide
- token.visible = true && group.visible = false --> group hide AND token.visible will become false
- AND whenever we are in group.visible = false ALL new entries by default will be token.visible = false

**Comment by micieslak** [comment]
> * token.visible = true && group.visible = false --> group hide AND token.visible will become false

Basically, when `group.visible = false` we can just ignore `token.visible`.

But when we switch from `group.visible = false` to `group.visible = true` we need to ensure that all tokens belonging to that group are set to `token.visible = true`.

**Comment by noeliaSD** [comment]
More clarifications here.

**Hidden lists order** should be like this (@benjthayer answer):

> The entity most recently hidden (whether that is a group or individual item) should go on top. This is mainly to ensure, when a user has hidden an item, if they have done so in error, they can easily spot it at the top of the list and unhide if they want to
So if I hide collectible A, THEN a community X, THEN collectible B, the order in the hidden list should be:
> 1) Collectible B (most recently hidden)
> 2) Community X
> 3) Collectible A

> Obviously if I hide a group and I have already hidden items that are part of that group, as discussed, those items would be folded into the group and the group added to the top of the list given it is the most recently hidden entity

**NOTE**: To approach that probably we will need to add a new role `timestamp` for both models, the individual and the groups one.

**Comment by caybro** [comment]
> One more technical note. On the top level we have two sections, "assets" and "collectibles"
> 
> ![image](https://private-user-images.githubusercontent.com/20650004/296233177-87b6efa1-3807-4abe-af64-f135165354d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjIyNDAsIm5iZiI6MTcwNTA2MTk0MCwicGF0aCI6Ii8yMDY1MDAwNC8yOTYyMzMxNzctODdiNmVmYTEtMzgwNy00YWJlLWFmNjQtZjEzNTE2NTM1NGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEyMTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjYxNGRlYzRlODQ4NDQwMDk2ODk3OGFhZWQ4YTU5ZjYxMDZjYWJlNTYyZWNhOTBjMWY5MmM4MTc2YjA2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LyD4RkFf-0bUpyGOgk1sqxfL-FsNGsO0IZff0WtYZ4g)
> 
> We can use also ConcatModel to have it in a single listview and easily avoid lists unrolling and instantiating all delegates up front.
> 
> The "assets" header can be done using ListView's header. The "collectibles" is a bit more tricky because it can be done as a section but it wont work out of the box for empty list here. The workaround is to move it to a footer then or keep "fake" element in a model.

I'll go with a single ListView (with ConcatModel) as a start, w/o any decoration or section headers

**Comment by noeliaSD** [comment]
> > One more technical note. On the top level we have two sections, "assets" and "collectibles"
> > ![image](https://private-user-images.githubusercontent.com/20650004/296233177-87b6efa1-3807-4abe-af64-f135165354d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjIyNDAsIm5iZiI6MTcwNTA2MTk0MCwicGF0aCI6Ii8yMDY1MDAwNC8yOTYyMzMxNzctODdiNmVmYTEtMzgwNy00YWJlLWFmNjQtZjEzNTE2NTM1NGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEyMTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjYxNGRlYzRlODQ4NDQwMDk2ODk3OGFhZWQ4YTU5ZjYxMDZjYWJlNTYyZWNhOTBjMWY5MmM4MTc2YjA2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LyD4RkFf-0bUpyGOgk1sqxfL-FsNGsO0IZff0WtYZ4g)
> > We can use also ConcatModel to have it in a single listview and easily avoid lists unrolling and instantiating all delegates up front.
> > The "assets" header can be done using ListView's header. The "collectibles" is a bit more tricky because it can be done as a section but it wont work out of the box for empty list here. The workaround is to move it to a footer then or keep "fake" element in a model.
> 
> I'll go with a single ListView (with ConcatModel) as a start, w/o any decoration or section headers

Just to clarify: These section decorations and behavior are not the same than for the other setting pages, so you can work on them directly in this task since there are no dependecies with this task: (https://github.com/status-im/status-desktop/issues/13026).
