### ISSUE TITLE
Receiver doesn't get a contact request

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#13199]
# Bug Report

## Description

No contact requests in pending requests for receiver

## Steps to reproduce
1. Send contact request from one user to another
2. Open the instance for receiver
3. Go to Contacts/ Pending requests

#### Expected behavior

Receiver gets a contact request from the first user

#### Actual behavior

Button Pending requests is disabled, no contact requests received
### Additional Information

- We found the issue in the latest autotests nightly
- Status desktop version: latest master build
- Operating System: macOS Ventura 13.5

**Comment by anastasiyaig** [comment]
@igor-sirotin @borismelnik pls check that out

**Comment by igor-sirotin** [comment]
hmm, was doing this just yesterday on latest master, was fine for me 🤔

**Comment by anastasiyaig** [comment]
it was working yesterday but today - seems not @igor-sirotin

**Comment by osmaczko** [comment]
Can't reproduce (see the video). @Valentina1133 could you please check if the issue still exits on the latest nightly?

https://github.com/status-im/status-desktop/assets/33099791/3a7b9bb8-0bad-4d79-abf2-7cb10c17b753

**Comment by Valentina1133** [comment]
@osmaczko I checked. There is no issue with contact requests anymore
