### ISSUE TITLE
Uploaded image preview is too small

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1319]
1. Upload an image to a group chat
2. Send the message
3. Click the image in the message bubble to show the preview.
4. Expected: image preview should fit to the preview modal
5. Actual: image preview is tiny

![Imgur](https://imgur.com/UIMOH19.png)

**Comment by jrainville** [comment]
I think @PascalPrecht fixed that in another PR

**Comment by PascalPrecht** [comment]
@emizzle can you try this on latest `master`?

**Comment by jrainville** [comment]
BTW, I also improved it in my AnimatedImage PR. There was a problem where if the image was not loaded when we opened the popup,. the sourceSize would not be set, making a 0x0 popup.

**Comment by iurimatias** [comment]
can't replicate, seems to have been fixed
