### ISSUE TITLE
Don't display number of members for token-gated communities on previews

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#13192]
### Description

Currently, community preview cards display the number of members (and active members). This data is encrypted for token-gated communities, resulting in a display of 0 for non-members (peers who can't decrypt the data). In such cases, these stats should be hidden.

Acceptance criteria:
- [ ] Hide the numbers of members and active members in community previews for token-gated communities if the user is not a member of that community.

**Comment by alexjba** [comment]
I've handled here the community previews in the link previews and curated community cards. But looks like we need the same approach in every place where the community members are shown. Will create a new task for this. I think we'll first need an analysis to spot all these places.



![Image](https://github.com/status-im/status-desktop/assets/47811206/0b60a588-40b1-4ec0-9dae-95e4fb3f21f7)
![Image](https://github.com/status-im/status-desktop/assets/47811206/a2365f93-bd94-4b09-bde2-c5d63e315c94)
![Image](https://github.com/status-im/status-desktop/assets/47811206/0a4c6ee4-2380-4add-9b1f-c164b40b9d22)
