### ISSUE TITLE
[PR done, awaiting status-go merge] Add Desktop Toggle for Mainnet Transaction Validation using Nimbus in Settings/Advanced

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#13204]
### Description

Add a toggle in the Settings/Advanced section. This toggle should be labeled "Validate Mainnet tx using Nimbus Light Client". By default, this toggle should be set to 'off'. This feature aims to enhance user control over transaction validation using the Nimbus Light Client.

**Comment by kounkou** [comment]
Hi, based on discussion with Vitaly,
the goal is 

> The goal is this: when we start using the verification proxy, it can provide us with an additional layer of security, as calls to possibly untrusted eth providers like Infura can be verified with the verification proxy

The goal would be to add a toggle to be able to start configure the starting of the nimbus after a restart to account for RPC client configuration.
I'll start with setting up the environment to be able to catch up on Vitaly's code and start the implemenation.

**Comment by corpetty** [comment]
is the goal of making the default "off" just for testing purposes. Imo, the default should be "on" once we're comfortable with the stability of the feature.

**Comment by kounkou** [comment]
> is the goal of making the default "off" just for testing purposes? Imo, the default should be "on" once we're comfortable with the stability of the feature.

I can understand that perspective. Nevertheless, this matter is not within the scope of this pull request. Instead, this comment aligns more logically with the backend perspective, considering that the parameters are retrieved from the backend.
