### ISSUE TITLE
Feature request: auto sync contact, channel list, and previous chat messages

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1321]
Same as other chat clients like WhatsApp and Telegram, users expect their contacts, recent channel list, and previous chat messages to be synced automatically across devices. It would help users who run a desktop instance coming from mobile to automatically sync contacts, recent channel lists, and previous chat messages. Maybe this can be done by some kind of behind-the-scenes message sent to mobile to allow it happen ("Would you like to sync your contact, recent channel list, and previous chat messages with DEVICE-ID"?).

**Comment by iurimatias** [comment]
This is the sync feature right? i.e in profile -> Device Settings
