### ISSUE TITLE
Community: removing a shard from community blocks messaging

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13217]
### Description

1. create community in 0.15 release and make it encrypted
2. add some members here
3. send some messages in some channels
4. click Edit community and assign community to shard 123
5. try to send some messages again 

In my case I received this: 
```
ERROR[01-16|09:34:13.828|github.com/status-im/status-go/wakuv2/waku.go:1060]                                 could not send message                   envelopeHash=0x71af99bdf132f0127d7f06852de23989d260b24023a075939afcf13342ef5a93 pubsubTopic=/waku/2/rs/16/123 contentTopic=/waku/1/0x7dccd139/rfc26 timestamp=1,705,386,854,118,873,907 error="not enough peers to publish"
```

I talked to Richard and he said it might be okay because I am not connected to any peer that supports shard 16/123 

6. then i go to community and removed the shard from it within UI (edit community - stop sharding)
7. then i asked Valentina to restart the app and try message again and there is an error shown for her blocking her from login

![image](https://github.com/status-im/status-desktop/assets/82375995/d71543cd-5023-4b8e-ac10-c9910e198dc6)

I asked for geth log on her side and found this:
```
ERROR[01-16|13:39:46.276|github.com/waku-org/go-waku/waku/v2/protocol/metadata/waku_metadata.go:219]  disconnecting from peer                  peerID=16Uiu2HAkukebeXjTQ9QDBeNDWuGfbaSg79wkkhK4vPocLgR6QFDf error="invalid shard count"
ERROR[01-16|13:39:46.277|github.com/waku-org/go-waku/waku/v2/protocol/metadata/waku_metadata.go:219]  disconnecting from peer                  peerID=16Uiu2HAkukebeXjTQ9QDBeNDWuGfbaSg79wkkhK4vPocLgR6QFDf error="invalid shard count"
```

[geth.log.zip](https://github.com/status-im/status-desktop/files/13946459/geth.log.zip)

Need some help investigating if removing a shard from community could lead to this

**Comment by anastasiyaig** [comment]
cc @Valentina1133 

@richard-ramos @igor-sirotin @osmaczko  can we please check on that somehow? i am pretty sure the flow of assigning a shard is kinda done incorrectly by me , but i think it should not lead to inability to use the app

**Comment by richard-ramos** [comment]
This error on login is not related to the sharding functionality but to something going wrong with the migrations. The errors found in the log should not stop the app from being used, but be limited to not being able to not broadcast messages on the community with wrong shard assigned.

**Comment by anastasiyaig** [comment]
ya but i wonder where are the migrations coming from, because before this move of removing shard - the app was launched normally, @Valentina1133 was able to login just fine. Then i removed the shard, she restarted the app and then no chance to login

**Comment by richard-ramos** [comment]
@Valentina1133 , is the account you used for this test a new account?

**Comment by osmaczko** [comment]
This issue will be resolved with https://github.com/status-im/status-desktop/pull/13321. It includes https://github.com/status-im/status-go/pull/4627 and https://github.com/status-im/status-go/pull/4638, which are both required for the fix.

Disabling community sharding works as follows:

https://github.com/status-im/status-desktop/assets/33099791/281fa3ca-a52a-409d-a693-4d5d8540220b

> I talked to Richard and he said it might be okay because I am not connected to any peer that supports shard 16/123

Indeed, this is the case. When I manually connect two peers operating on the same shard, messaging works fine:

https://github.com/status-im/status-desktop/assets/33099791/02d45972-a6e6-4068-ac81-1995f593dc87

> This error on login is not related to the sharding functionality but to something going wrong with the migrations.

I can confirm. Running the same account after a shard change is fine. I assume @Valentina1133 ran a newer version of Status with the same account and then reverted to the old version, which resulted in broken migrations.

**Comment by anastasiyaig** [comment]
thanks @osmaczko !
