### ISSUE TITLE
Clean up and remove this repo's “Discussion” tab

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#13229]
### Description

The “Discussions” section of this repo hasn't been used for a year and a half. I suggest closing any pending discussion and removing this tab from the repository configuration. As it is right now, it may one think this project is stale and not being actively developed.

![Screenshot 2024-01-17 at 10  28 06@2x](https://github.com/status-im/status-desktop/assets/62282406/18f8f72c-16b2-4ed5-83d9-c3a7b1c62f03)

**Comment by iurimatias** [comment]
done
