### ISSUE TITLE
Token UI is corrupted in the Community->Tokens settings

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#13220]
# Bug Report

## Description

Collectibles UI is corrupted in the Community->Tokens settings

## Steps to reproduce

1. Create the community and mint owner token
2. Check the owner token and token master token UI. There is black bubble at the bottom

![Screenshot 2024-01-16 at 11 35 50 1](https://github.com/status-im/status-desktop/assets/117639195/c243125c-3828-4c3c-854f-d1ca7ffce58f)

- Status desktop version: latest master
- Operating System: macos

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one
