### ISSUE TITLE
Fix: scrolling up fast keeps jumping down to a lower point in the chat

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1323]
When in a public chat, scrolling up quickly to find a previous message causes the chat to jump back down to a much more previous message. It is possible that it does while all the messages are loading and being rendered, as it does not seem to happen after they have all already been rendered. IOW, after the initial skipping while scrolling, it does not seem to be replicatable.

**Comment by iurimatias** [comment]
can't replicate anymore but I recall experiencing this issue at one point
