### ISSUE TITLE
[Wallet] Add last navigation to the specific transactions details page from toast link displayed when a community token has been received

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13249]
### Description
The task https://github.com/status-im/status-desktop/issues/13039 introduced toasts for:

1. Any other community [asset](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=20765%3A399010&mode=design&t=6wvg1f2sJZXpvKwo-1) received (after first one):
![Screenshot 2024-01-19 at 12 11 46](https://github.com/status-im/status-desktop/assets/97019400/aa5f2459-ae67-40fd-9bf9-c00dc8bc55a3)

2. Any other community [collectible](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=20787%3A74778&mode=design&t=HHZUwq2iA18xbNuF-1) received (after first one):
![Screenshot 2024-01-19 at 12 11 57](https://github.com/status-im/status-desktop/assets/97019400/51216368-bf01-49e6-8e3a-3f00ac0dd0aa)

Whenever the user clicks on the `View transaction details` link, it should navigate to the specific transaction details page, like this:
![Screenshot 2024-01-19 at 14 22 26](https://github.com/status-im/status-desktop/assets/97019400/18b884a0-ad91-41b5-bc82-961d5e446264)

Currently it only navigates to the main activity page here:
![Screenshot 2024-01-19 at 14 22 32](https://github.com/status-im/status-desktop/assets/97019400/df2bbdaf-ee79-4e4b-bbc1-32f934f43d0d)

So, the purpose of this task is to complete the navigation to the specific transaction details page.

**NOTE:** The following case is the one to be completed: `ToastsManager.qml` --> case `ToastsManager.ActionType.ViewTransactionDetails`

**Comment by noeliaSD** [comment]
Related task: https://github.com/status-im/status-desktop/issues/13039

**Comment by saledjenic** [comment]
@caybro I guess you meant this (I added that recently for saved addresses, to jump to its activity page and set it to filter):
https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Wallet/controls/SavedAddressesDelegate.qml#L187-L190

I deliberately set `data` as an object param to `changeAppSectionBySectionType` so that other props can be added for specific use.
