### ISSUE TITLE
Keycard: Unable to continue keycard flow if it's started without reader/card connected

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13244]
# Bug Report

## Description

There is an issue with keycard/reader detection. If the user starts any keycard flow with A) reader disconnected or B? Reader connected but with no card inside it impossible to continue the flow until it is restarted with the reader and card ready.

## Steps to reproduce

1. Launch the app
2. Start any keycard flow without reader connected
3. Connect the reader when asked

#### Expected behavior
Reader is detected, Keycard flow can be continued

#### Actual behavior
Keycard flow is stuck, reader is not detected.

### Additional Information
Logs (only ones related to keycard i have):
`ERR 2024-01-18 14:59:30.985+01:00 unknown timer reason                       topics="keycard-service" tid=12293829 file=service.nim:246 reason=reRunCurrentFlowLater`
Video:

https://github.com/status-im/status-desktop/assets/52439419/07dfc293-e46b-4e5b-b322-bc5ad4dae6c3

- Status desktop version: StatusIm-Desktop-240118-070404-f00493-aarch64
- Operating System: macOS

**Comment by saledjenic** [comment]
@lukaszso this one should be fixed in this PR https://github.com/status-im/status-desktop/pull/13238

**Comment by lukaszso** [comment]
Retested in latest nightly (StatusIm-Desktop-240122-035700-50e601-nightly-aarch64) and the issue is fixed.
