### ISSUE TITLE
Keycard: keycard module is busy error

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13243]
# Bug Report

## Description

"The keycard module is still busy error" is being displayed unexpectedly and could not be resolved without restarting.

## Steps to reproduce

Exact steps are unknown. It happened somewhere between starting and restarting a keycard flow from the settings screen and inserting/removing card

#### Actual behavior

App appears stuck in a loop, user is blocked from continuing

![image](https://github.com/status-im/status-desktop/assets/50769329/279f9d0c-690f-49aa-be39-2e60b9f84e21)

```
INF 2024-01-18 14:51:22.441+00:00 keycard shared module is still running     topics="profile-section-profile-module" tid=4898425 file=module.nim:101
Warning: qrc:/app/AppLayouts/Profile/ProfileLayout.qml:432: ReferenceError: Theme is not defined (qrc:/app/AppLayouts/Profile/ProfileLayout.qml:432, )
DBG 2024-01-18 14:51:22.444+00:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=4898446 file=threadpool.nim:54 messageType=TimerTaskArg:ObjectType threadid=4898446 task="{\"$type\":\"TimerTaskArg:ObjectType\",\"timeoutInMilliseconds\":1000,\"reason\":\"WaitForKeycardAvailability\",\"vptr\":105553141809088,\"slot\":\"onTimeout\",\"tptr\":4335445304}"
DBG 2024-01-18 14:51:23.445+00:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=4898452 file=threadpool.nim:54 messageType=TimerTaskArg:ObjectType threadid=4898452 task="{\"$type\":\"TimerTaskArg:ObjectType\",\"timeoutInMilliseconds\":1000,\"reason\":\"WaitForKeycardAvailability\",\"vptr\":105553141809088,\"slot\":\"onTimeout\",\"tptr\":4335445304}"
DBG 2024-01-18 14:51:24.451+00:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=4898449 file=threadpool.nim:54 messageType=TimerTaskArg:ObjectType threadid=4898449 task="{\"$type\":\"TimerTaskArg:ObjectType\",\"timeoutInMilliseconds\":1000,\"reason\":\"WaitForKeycardAvailability\",\"vptr\":105553141809088,\"slot\":\"onTimeout\",\"tptr\":4335445304}"
DBG 2024-01-18 14:51:24.903+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=4898425 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
DBG 2024-01-18 14:51:25.456+00:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=4898453 file=threadpool.nim:54 messageType=TimerTaskArg:ObjectType threadid=4898453 task="{\"$type\":\"TimerTaskArg:ObjectType\",\"timeoutInMilliseconds\":1000,\"reason\":\"WaitForKeycardAvailability\",\"vptr\":105553141809088,\"slot\":\"onTimeout\",\"tptr\":4335445304}"
```

### Additional Information

- Status desktop version: Master (local) 2024-01-18
- Operating System: Mac 14.2.1

**Comment by saledjenic** [comment]
@glitchminer the keycard lib is a singleton instance that cannot run 2 keycard flows simultaneously, instead it runs one after another. To avoid potential issues we introduced that "keycard module busy" popup letting the user know that some work is still in progress since communication with a keycard is way slower than anything else. Also as another step of protection popup buttons are disabled when switching from one to another state.

Again I don't say that the user cannot block the keycard flows, but I cannot reproduce that scenario. Also having in mind handlings we did in the past in regards to that, I am more likely to think that it comes from some unexpected response from the keycard lib or some hardware-related things.

**Comment by lukaszso** [comment]
I was able to reproduce this multiple times on both macOS and Windows builds. I did not find any exact steps yet.

**Comment by alaibe** [comment]
@lukaszso Could you try to provide the steps where you encounter this problem? even if not consistently

**Comment by saledjenic** [comment]
@glitchminer @lukaszso the only case when I see this is when the keycard lib cannot read the Keycard. Then I see busy keycard module... and the log looks like in the image below, those lines repeat to infinity. Then what I do is unplug the reader and plug it again and all good. It doesn't happen always, but If that's the case on your side we can update the message and add something like "Please, try re-plugging the keycard reader".

![image](https://github.com/status-im/status-desktop/assets/86303051/aef332ad-a36b-44ff-bab5-df219a6d76dc)
