### ISSUE TITLE
[Tokens Management] Change advanced tab view order

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13253]
### Description

[Design](https://www.figma.com/file/eM26pyHZUeAwMLviaS1KJn/%E2%9A%99%EF%B8%8F-Wallet-Settings%3A-Manage-Tokens?type=design&node-id=301%3A129048&mode=design&t=eVOJnoF5oY3ZSTlh-1)

1. Switches on top
2. List of tokens at the bottom
3. Display a prompt to save the changes (separate from Assets/Collectibles tabs)

![image](https://github.com/status-im/status-desktop/assets/5377645/e2276105-3e32-470f-8718-3e5ea282a709)

**Comment by caybro** [comment]
Should be part of the epic?

**Comment by noeliaSD** [comment]
> Should be part of the epic?

I added it there yes! However, low priority I guess

**Comment by caybro** [comment]
On a second thought: I'm missing the preview of the hidden tokens (because of the balance threshold) and if it's to be part of this panel then it would push the "Token lists" part down (perhaps making it invisible)... wdyt @benjthayer 

I very much preferred the original order...

**Comment by benjthayer** [comment]
> On a second thought: I'm missing the preview of the hidden tokens (because of the balance threshold) and if it's to be part of this panel then it would push the "Token lists" part down (perhaps making it invisible)... wdyt @benjthayer
> 
> I very much preferred the original order...

Thanks @caybro - the idea here is that a list of hidden tokens (as a result of the low balance threshold) would be shown underneath the low balance control, pushing the Token Lists section down. (I can't seem to find an example of this in the final designs however - will check and add back in). 

The original idea here was that the user's Token Lists could eventually be fairly lengthy, so if the Token Lists section was at the top of the page, they would push the 2 toggle controls down making discovery of those controls less likely.  

However, it is also true that if the hidden list becomes long, the Token Lists section is equally pushed down so I don't feel strongly either way regarding the order.

cc @John-44

**Comment by benjthayer** [comment]
@caybro I've re-introduced the preview of which assets will be hidden due to low balance threshold into the design - apologies, I'm not sure why that was not part of the final flows.
https://www.figma.com/file/eM26pyHZUeAwMLviaS1KJn/%E2%9A%99%EF%B8%8F-Wallet-Settings%3A-Manage-Tokens?type=design&node-id=1289-220330&mode=design&t=nhretUxy2oNy2P1i-4

**Comment by caybro** [comment]
> @caybro I've re-introduced the preview of which assets will be hidden due to low balance threshold into the design - apologies, I'm not sure why that was not part of the final flows. https://www.figma.com/file/eM26pyHZUeAwMLviaS1KJn/%E2%9A%99%EF%B8%8F-Wallet-Settings%3A-Manage-Tokens?type=design&node-id=1289-220330&mode=design&t=nhretUxy2oNy2P1i-4

OK, thanks. So the order is advanced -> token lists, got it.
