### ISSUE TITLE
Migration fails from 0.15 to nightly build: unable to login into existing account

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-desktop#13277]
# Bug Report

The account was working fine with 0.15. 
Installed the [nightly build](https://ci.status.im/job/status-desktop/job/nightly/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-240102-035700-73025c-nightly-aarch64.dmg) after which i am unable to login to the same account. 

## Description

Screenshot indicates error seen.

<img width="1751" alt="Screenshot 2024-01-24 at 11 24 37 AM" src="https://github.com/status-im/status-desktop/assets/20137744/8d6f1ed3-c722-41f6-b9d3-9b913aff24fe">

## Steps to reproduce

1. Create/login to an account using status desktop 0.15 
2. Install nightly build as mentioned above
3. Try logging in to same account

#### Expected behavior
Should be able to login without any issues

#### Actual behavior
Unable to login due to an error

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/nightly/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-240102-035700-73025c-nightly-aarch64.dmg
- Operating System: MacOS Sonoma 14.1.1 (23B81)

**Comment by chaitanyaprem** [comment]
Now i am not able to login to my account using 0.15 version as well. 
Seeing error below
<img width="1751" alt="Screenshot 2024-01-24 at 11 33 12 AM" src="https://github.com/status-im/status-desktop/assets/20137744/1fc10519-4999-4971-9350-dd2ce0403af0">


Will try to restore using seed phrase and see if it works with nightly build.

**Comment by anastasiyaig** [comment]
@chaitanyaprem thanks for checking!

@alaibe pls check that out, some new column missing when migrating from 0.15 to nightly?

**Comment by alaibe** [comment]
Yes I can confirm, i also reproduce this issue

**Comment by chaitanyaprem** [comment]
If i install today's nightly build, will i be able to reuse my old profile?

**Comment by igor-sirotin** [comment]
desktop is not yet pointing to status-go with the fix I think.
fix: 026194d97a4e2eddefd21d857b3c78651156f64c, https://github.com/status-im/status-go/pull/4616
current status-go: cd9617cad7f8934405b87a5404221f586831e9b8

cc @anastasiyaig

**Comment by igor-sirotin** [comment]
Opened a PR: https://github.com/status-im/status-desktop/pull/13298
