### ISSUE TITLE
Fix: mention dialog does not show all users in chat

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1328]
1. Go to #status-desktop
2. Type `@`
3. A list of users should popup in the mention popup.
4. Expected: the list of users should be all users in the chat
5. Actual: the list of users only shows some of the users in the chat (only three total were shown in the screenshot shown below).
![Imgur](https://imgur.com/zQArYsQ.png)

**Comment by iurimatias** [comment]
can confirm this is still an issue

**Comment by jrainville** [comment]
As far as I understand, this one is hard to fix because it's related to the contact signal that is not made often enough in the backend. I'm not sure how we can fix it without doing an ugly patch
