### ISSUE TITLE
Keycard: App is not restarted automatically at the end of the flow

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13287]
# Bug Report

## Description

The "Restart app & sign in using your new Keycard" button at the end of the "Setup a Keycard with an existing account" only closes the app. The user has to manually re-open it.

## Steps to reproduce

1. Open the app
2. Start the flow to setup a Keycard with an existing account
3. At the end of the flow click "Restart app & sign in using your new Keycard" button and wait for the app to re-open

#### Expected behavior
App re-opens without user action.

#### Actual behavior
User has to manually re-open the app.

### Additional Information

- Status desktop version: 
macOS: StatusIm-Desktop-240124-223025-654da3-aarch64
Windows: StatusIm-Desktop-240124-075601-8da684-nightly-x86_64
- Operating System: Windows 11 & macOS Sonoma

**Comment by anastasiyaig** [comment]
We don't have a way to logout user or restart the app.
So when that migration is completed, even the button says "Restart app & sign in using your new Keycard" we just close it, but user needs to open it manually.
