### ISSUE TITLE
[Communities] Add backend support for `Hide channel from members who don’t have permissions to view the channel`

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13291]
#### Design

https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?node-id=2563%3A524846&mode=dev

<img width="563" alt="Screenshot 2024-01-25 at 10 49 30" src="https://github.com/status-im/status-desktop/assets/47811206/2e73e898-8ec4-455a-85ca-22dc2e3b4b35">

The channel edit view has a new option to hide the channel from people that don't have the necessary permissions.
The purpose of this task is to add the backend support for this new option.

If all channels in a category are 'hidden' for a user, the Category (that appears to contains zero channels) should also be hidden from that user

**Comment by iurimatias** [comment]
note: this task is high priority and should not be moved to the next milestone
