### ISSUE TITLE
[Profile Showcase - General] Review existing drag/drop actions in Accounts / Assets / Collectibles and Communities. It seems in the current app state these actions are broken.

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13329]

**Comment by caybro** [comment]
There are 2 things:
- the NIM backend implements `move(from,to)` while the mock `ListModel` expects a `move(from,to,count)` so the drag and drop is broken in StoryBook
- the NIM showcase models implement the above `move` operation in terms of a full model reset (should be done as proper `moveRows` operation)
