### ISSUE TITLE
[Profile Showcase - General] Implement side-by-side preview

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13331]
- the preview is "live", need to track dirty settings for every Profile entry (including showcase)

![image](https://github.com/status-im/status-desktop/assets/5377645/fd415784-433d-43ae-84f4-a597ab49b740)

Figma: https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=5-118665&mode=design&t=Mtl2JT0sFQadXBJS-0

**Comment by caybro** [comment]
The result from the meeting with Ben: both options should be implemented (one in the preview is a must, the other here is nice-to-have)
