### ISSUE TITLE
[Profile Showcase - General] Add Profile preview perspective options [Stranger, Contacts, Verified Contacts]. This includes the filtering of the data visibility based on the dropbox. Also review `Send Message` button logic

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13332]
[Figma](https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=9-112784&mode=design&t=gxavA5yTTwXWFu9s-0)

**Comment by caybro** [comment]
Dupe of https://github.com/status-im/status-desktop/issues/13424
