### ISSUE TITLE
[Profile Showcase - Assets&Collectibles] Implement the `Intro popup` and show it on the first dirty state of Assets or Collectibles tab

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13338]
[Design](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-37890&mode=design&t=gCxrJlhpabmpM2WR-0):

![Screenshot 2024-02-07 at 15 38 26](https://github.com/status-im/status-desktop/assets/97019400/b5f0651c-5bd6-4a6a-986b-6cb49f7c4409)

Here the `User Story` this task must cover:
https://www.notion.so/Profile-showcase-7d7f95a3c9ad4bc38ad5368311a406fd?pvs=4#0e7f079cbca440ebb725d7fd6a292cc2

**Comment by noeliaSD** [comment]
Here the missing clarification form design: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=3525%3A230254&mode=design&t=4AXxqwmnwYfot3G3-1

**Comment by glitchminer** [comment]
QA Passed: Run R15126
