### ISSUE TITLE
[Profile Showcase - General] Saving Profile Showcase changes triggers a toast message

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13333]
[Figma](https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=104-97615&mode=design&t=gxavA5yTTwXWFu9s-0)

**Comment by caybro** [comment]
This is already the case; just keep an eye on making sure when/if the backend changes, we still emit them with the dirty state
