### ISSUE TITLE
[Profile Showcase - Profile Popup] Interactions. Review all different delegate cards for each tab and check if there are design updates. 

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13346]
[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-32244&mode=design&t=jumwFduKExodhRUc-4)

At least there are different context menu option for these cards. (Probably this task can be splitted by card type, i.e. one task for the communities card, one for the assets, card, one for the account,  one for the collectibles and one for the web cards.

**Comment by caybro** [comment]
Dupe of https://github.com/status-im/status-desktop/issues/13421
