### ISSUE TITLE
[Profile Showcase - Profile Popup] Review own profile details. Now QR code is a new popup.

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13348]
[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-30744&mode=design&t=jumwFduKExodhRUc-4)

**Comment by caybro** [comment]
Dupe of https://github.com/status-im/status-desktop/issues/13417
