### ISSUE TITLE
[Profile Showcase] Explore whether the filtering, data transformation and dirty state mgmt should happen on the backend or UI

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13341]

**Comment by noeliaSD** [comment]
@micieslak and @alexjba have been working on the `data and modules flow design` and have some conclusions. They can share them here and we can close this taks. I guess we should reasign this to them. WDYT @alexandraB99

**Comment by micieslak** [comment]
As concluded with @MishkaRogachev and @alexjba the approach beneficial in mid-term is to handle the dirty state of profile showcase management on the UI side (qml/cpp) components.

This approach gives several significant benefits:
- gives better separation between UI part (qml/cpp) and nim part
- reduces the nim part to required minimum
- makes the functionality testable via unit tests and fully runable in Storybook
- is intended to be built using reusable components, limits code duplication on nim side
- is a good opportunity to improve currently messy and incomplete nim implementation

The idea is depicted on the diagram:
https://miro.com/app/board/uXjVNxUvgDA=/

There is also related document (in progress):
https://docs.google.com/document/d/1Iv7Z4ZxY1HeXNqoKlzxvTAuW71wKthtD6xJya92kkh8/edit
