### ISSUE TITLE
[Profile Showcase - Collectibles] Add link to Accounts tab

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13340]
[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-37407&mode=design&t=jumwFduKExodhRUc-4)

**Comment by noeliaSD** [comment]
Similar to https://github.com/status-im/status-desktop/issues/13337
