### ISSUE TITLE
[Profile Showcase - Profile Popup] General layout updates: Review new design, there are some details updated (buttons, combobox for different perspectives..).

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13344]
[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-30704&mode=design&t=jumwFduKExodhRUc-4)

**Comment by caybro** [comment]
Dupe of https://github.com/status-im/status-desktop/issues/13416
