### ISSUE TITLE
Connection to store node is lost

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13355]
### Description

**Build:** master build, macOS, commit c8d17f48e5c4e1d618e3b04d5c5dea6f6bdc8728 (30-jan-2024). It is local build (dev)

**Logs:** 
[geth.log](https://github.com/status-im/status-desktop/files/14094285/geth.log)

**Steps**

No specific steps.
I did git pull , make clean and make update , then make run.
I logged in to an account i created before (last week)
I created community and then this banner appeared
I restarted app
I opened community and then sent an invitation to join the community
Then the banner appeared again

I am constantly on WiFi, it is stable (or it looks like it)

<img width="1420" alt="Screenshot 2024-01-30 at 10 27 10" src="https://github.com/status-im/status-desktop/assets/82375995/37390bb3-905d-4d1f-9456-b051ca2ce649">

**Comment by anastasiyaig** [comment]
@igor-sirotin maybe you saw this as well? 
@chaitanyaprem @richard-ramos can you please take a look what is going on?

**Comment by chaitanyaprem** [comment]
Taking a look at fleet logs from the fleet, it looks as though your app is running with some older code 


I saw that node started with clusterID as 0 which cannot be used with shards.test fleet which uses clusterID 16. Hence store nodes were disconnecting connections from your node.

`INFO [01-30|10:29:32.410|github.com/status-im/status-go/wakuv2/waku.go:192]                                 starting wakuv2 with config              config="&{MaxMess      ageSize:1048576 Host:0.0.0.0 Port:0 PeerExchange:true KeepAliveInterval:10 MinPeersForRelay:1 MinPeersForFilter:2 LightClient:false WakuNodes:[enrtree://AMOJVZX4V6EXP      7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.test.shards.nodes.status.im] Rendezvous:false DiscV5BootstrapNodes:[enr:-Ni4QAG-O7ryJQg1P-CDwE7nBoSx-pScZsRRq6tvBF0tRsCG      Ftbs2ag1bqsv7GpTD_2rTvwIT7PsOVNG_ytFZdfwT3cBgmlkgnY0gmlwhKdjEy-KbXVsdGlhZGRyc68ALTYoYm9vdC0wMS5kby1hbXMzLnNoYXJkcy50ZXN0LnN0YXR1c2ltLm5ldAZ2X4Jyc4cAEAIAgAEAiXNlY3AyNT      ZrMaEC3rRtFQSgc24uWewzXaxTY8hDAHB8sgnxr9k8Rjb5GeSDdGNwgnZfg3VkcIIjKIV3YWt1Mg0 enr:-OK4QFH-vPVmsKjlEd3jjS8heib42DO5ZGNVUYM-lbJkPL2QSP0Ye8VZV-WycXk8jVjv9LcQpuwlaBJ3xN1t      tPMy07wBgmlkgnY0gmlwhAjaF0yKbXVsdGlhZGRyc7g4ADY2MWJvb3QtMDEuYWMtY24taG9uZ2tvbmctYy5zaGFyZHMudGVzdC5zdGF0dXNpbS5uZXQGdl-CcnOHABACAIABAIlzZWNwMjU2azGhAz-wm0ZPmCicDhRTOG      fZ3stBj3O1jyWgsBpKTUcpWu5gg3RjcIJ2X4N1ZHCCIyiFd2FrdTIN enr:-OK4QFWlB2csVi4NhszuVmzOWd1q1Moy1DFTmq1Bt4_AWKh7U-eCRHTj3m9TOma53DLXN318cS7LapchI01ZxnEwLXEBgmlkgnY0gmlwhCK      HDVeKbXVsdGlhZGRyc7g4ADY2MWJvb3QtMDEuZ2MtdXMtY2VudHJhbDEtYS5zaGFyZHMudGVzdC5zdGF0dXNpbS5uZXQGdl-CcnOHABACAIABAIlzZWNwMjU2azGhAsY6oA0NFskUjopWFN9gwOZP1zZQ4rN5tVXV5CvcT      OpDg3RjcIJ2X4N1ZHCCIyiFd2FrdTIN enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.test.shards.nodes.status.im] Nameserver: Resolver:<nil> EnableDis      cV5:true DiscoveryLimit:20 AutoUpdate:true UDPPort:0 EnableStore:false StoreCapacity:0 StoreSeconds:0 TelemetryServerURL:https://telemetry.status.im EnableFilterFullN      ode:false DefaultShardPubsubTopic:/waku/2/rs/16/32 UseShardAsDefaultTopic:true ClusterID:0}`

Oddly though the previous start was showing clusterID 16 

`INFO [01-30|10:28:54.608|github.com/status-im/status-go/wakuv2/waku.go:192]                                 starting wakuv2 with config              config="&{MaxMess      ageSize:1048576 Host:0.0.0.0 Port:0 PeerExchange:true KeepAliveInterval:10 MinPeersForRelay:1 MinPeersForFilter:2 LightClient:false WakuNodes:[enrtree://AMOJVZX4V6EXP      7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.test.shards.nodes.status.im] Rendezvous:false DiscV5BootstrapNodes:[enr:-Ni4QAG-O7ryJQg1P-CDwE7nBoSx-pScZsRRq6tvBF0tRsCG      Ftbs2ag1bqsv7GpTD_2rTvwIT7PsOVNG_ytFZdfwT3cBgmlkgnY0gmlwhKdjEy-KbXVsdGlhZGRyc68ALTYoYm9vdC0wMS5kby1hbXMzLnNoYXJkcy50ZXN0LnN0YXR1c2ltLm5ldAZ2X4Jyc4cAEAIAgAEAiXNlY3AyNT      ZrMaEC3rRtFQSgc24uWewzXaxTY8hDAHB8sgnxr9k8Rjb5GeSDdGNwgnZfg3VkcIIjKIV3YWt1Mg0 enr:-OK4QFH-vPVmsKjlEd3jjS8heib42DO5ZGNVUYM-lbJkPL2QSP0Ye8VZV-WycXk8jVjv9LcQpuwlaBJ3xN1t      tPMy07wBgmlkgnY0gmlwhAjaF0yKbXVsdGlhZGRyc7g4ADY2MWJvb3QtMDEuYWMtY24taG9uZ2tvbmctYy5zaGFyZHMudGVzdC5zdGF0dXNpbS5uZXQGdl-CcnOHABACAIABAIlzZWNwMjU2azGhAz-wm0ZPmCicDhRTOG      fZ3stBj3O1jyWgsBpKTUcpWu5gg3RjcIJ2X4N1ZHCCIyiFd2FrdTIN enr:-OK4QFWlB2csVi4NhszuVmzOWd1q1Moy1DFTmq1Bt4_AWKh7U-eCRHTj3m9TOma53DLXN318cS7LapchI01ZxnEwLXEBgmlkgnY0gmlwhCK      HDVeKbXVsdGlhZGRyc7g4ADY2MWJvb3QtMDEuZ2MtdXMtY2VudHJhbDEtYS5zaGFyZHMudGVzdC5zdGF0dXNpbS5uZXQGdl-CcnOHABACAIABAIlzZWNwMjU2azGhAsY6oA0NFskUjopWFN9gwOZP1zZQ4rN5tVXV5CvcT      OpDg3RjcIJ2X4N1ZHCCIyiFd2FrdTIN enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.test.shards.nodes.status.im] Nameserver: Resolver:<nil> EnableDis      cV5:true DiscoveryLimit:20 AutoUpdate:true UDPPort:0 EnableStore:false StoreCapacity:0 StoreSeconds:0 TelemetryServerURL: EnableFilterFullNode:false DefaultShardPubsu      bTopic:/waku/2/rs/16/32 UseShardAsDefaultTopic:true ClusterID:16}"`


Looks like some config issue, ideally ClusterID should be saved locally and reused. 
Not sure what else could be reason though.
@igor-sirotin @richard-ramos may have some idea, as this is related to how the config in desktop is stored and reapplied on restart.

**Comment by richard-ramos** [comment]
Oh man, this is the missing clusterID issue! for some reason sometimes the clusterID just go away on its own!

>  I logged in to an account i created before (last week)

Gotta try to reproduce with this specific step. I'm thinking it has something to do with a migration being applied incorrectly.
