### ISSUE TITLE
Remove fleet selection from settings

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#13352]
As discussed with @John-44 within https://github.com/status-im/status-desktop/issues/13297, we don't want the user to be able to select a fleet. 

Changing a fleet should be a very careful procedure.

**Comment by igor-sirotin** [comment]
@iurimatias not sure what's the desired milestone for this

**Comment by richard-ramos** [comment]
Instead of removing the fleet selection, could this feature be hidden behind a flag? (maybe enabled only when it's not a release build?), I find this feature to be useful for when you want to test a new fleet deployment.

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one

**Comment by iurimatias** [comment]
remove it, unless there is a technical reason to just hide it
