### ISSUE TITLE
[Profile - Identity] Add `Use a collectible` for the profile picture

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13350]
[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-42944&mode=design&t=NCt83nZgIa72io0i-0)

**Comment by alexandraB99** [comment]
Use a collectible is out of scope -> https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-42944&mode=design&t=NCt83nZgIa72io0i-4

**Comment by iurimatias** [comment]
@benjthayer needs design

**Comment by benjthayer** [comment]
> @benjthayer needs design

On my list, thanks @iurimatias - I think the flow for adding and editing a collectible as a profile pic is out of scope for MVP

**Comment by alexandraB99** [comment]
> > @benjthayer needs design
> 
> On my list, thanks @iurimatias - I think the flow for adding and editing a collectible as a profile pic is out of scope for MVP

@benjthayer could you please confirm if it's out of scope?

**Comment by jrainville** [comment]
Closing as we don't have a scope of it yet
