### ISSUE TITLE
Switching community channels feels laggy

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#13354]
# Bug Report

Opening this issue as a replacement of https://github.com/status-im/status-desktop/issues/12363, as it has wrong description.
There was an initial assumption that chat loading animation is missing here. But it wasn't correct. The delay is happening for already loaded channels. This is a performance issue, not a missing animation bug.

1. I found that removing these lines fixes the delay:
https://github.com/status-im/status-desktop/blob/2d0047846739f076510378327ecbff85b05154f3/ui/app/AppLayouts/Chat/panels/UserListPanel.qml#L63-L70
https://github.com/status-im/status-desktop/blob/2d0047846739f076510378327ecbff85b05154f3/ui/app/AppLayouts/Chat/panels/UserListPanel.qml#L76-L79

2. I tried to replace `ExpressionRole` with `FastExpressionRole`, but it didn't really help:
https://github.com/status-im/status-desktop/pull/13299

## Steps to reproduce

1. Go to some big community, e.g. https://status.app/c/CxmACjEKDlRlc3QgQ29tbXVuaXR5Eg9PcGVuIGZvciBhbnlvbmUYrAEiByNGRjAwMDAqAgUJAw==#zQ3shnd55dNx9yTihuL6XMbmyM6UNjzU6jk77h5Js31jxcT5V
2. Start switching between channels, note a delay.

https://github.com/status-im/status-desktop/assets/25482501/8fc16fb1-7d33-461c-8ffc-01937420be63

**Comment by iurimatias** [comment]
it's very smooth right now, so likely not even an issue anymore, moved to 2.29 due to lack of space in this milestone

**Comment by igor-sirotin** [comment]
> it's very smooth right now, so likely not even an issue anymore, moved to 2.29 due to lack of space in this milestone

I can confirm the issue is still there. Try channels with many members, e.g. Status Test Community:
https://status.app/c/CxmACjEKDlRlc3QgQ29tbXVuaXR5Eg9PcGVuIGZvciBhbnlvbmUYrQEiByNGRjAwMDAqAhAgAw==#zQ3shnd55dNx9yTihuL6XMbmyM6UNjzU6jk77h5Js31jxcT5V

https://github.com/status-im/status-desktop/assets/25482501/fda7fa90-e10a-4cf2-b60f-886ba63dde5b

**Comment by caybro** [comment]
> > it's very smooth right now, so likely not even an issue anymore, moved to 2.29 due to lack of space in this milestone
> 
> I can confirm the issue is still there. Try channels with many members, e.g. Status Test Community: https://status.app/c/CxmACjEKDlRlc3QgQ29tbXVuaXR5Eg9PcGVuIGZvciBhbnlvbmUYrQEiByNGRjAwMDAqAhAgAw==#zQ3shnd55dNx9yTihuL6XMbmyM6UNjzU6jk77h5Js31jxcT5V
> 
>  Screen.Recording.2024-03-05.at.11.33.50.mov

I really can't reproduce this at all in current master, even in our Status CC. Is this still happening for you @igor-sirotin ?
