### ISSUE TITLE
[Channel permissions] Creating/editing channel permissions will spawn multiple notifications

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13369]
### Description

Found in https://github.com/status-im/status-desktop/pull/12160

When creating/editing/deleting channel permissions multiple notifications will be spawned.

This example is from creating a channel with 1 permission and it shows 3 notifications:

https://github.com/status-im/status-desktop/assets/47811206/f34b3a21-e646-4c9d-87c9-8e745ae1e733

**Comment by alexjba** [comment]
Blocked by https://github.com/status-im/status-desktop/issues/12142. The channel permissions needs to land first.

**Comment by iurimatias** [comment]
moving this to sprint 2
