### ISSUE TITLE
Editing messages that contain link previews

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13378]
Designs have been created to clarify what the user sees / what interactions are available when a user goes to edit a message they have sent that contains link previews.

The flows show how a message with link previews is shown in the edit state and the ability for the user to edit the message, links or delete link preview cards individually.

<img width="1440" alt="Message with unfurls" src="https://github.com/status-im/status-desktop/assets/110033914/cd23fbb3-947c-44e8-8c4c-5c41fb7762e7">

**Figma:**
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=24896-257059&mode=design&t=zq5S4qUvyDVOOEM6-4

**Comment by iurimatias** [comment]
needs analysis, and probably be broken down, this is more of an epic than an actuall issue

**Comment by noeliaSD** [comment]
On me to analyse for the next milestone

**Comment by alexjba** [comment]
@igor-sirotin Do you think we need extra backend work to support link previews in the reply input?

**Comment by igor-sirotin** [comment]
> Do you think we need extra backend work to support link previews in the reply input?

@alexjba @noeliaSD 
Looks like this PR covered the backend part already:
- https://github.com/status-im/status-go/pull/3974

**Comment by igor-sirotin** [comment]
- https://github.com/status-im/status-desktop/issues/14743

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
