### ISSUE TITLE
Some token actions are not propagated to token masters

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#13371]
How to reproduce:

Create community with community token with limited supply.
Add a member to community and send him token master token.
A member should have access to tokens.
Burn a token.

Expected:
All users who has access to tokens should see changes.

Result:
Only the user who burnt sees changes. After restart Total is still bad, but Remaining is ok, becuase it is computed on restart.
![image](https://github.com/status-im/status-desktop/assets/61889657/59f32f2c-5022-4c42-bd5c-e6da6dc05e7a)

This should be fixed for all operations:
burning, self-destructing, airdropping.

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone
