### ISSUE TITLE
Wallet settings: Change of RPC URLs requires app restart

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13380]
In order to implement changes to network RPC URLs in Wallet Settings, the user must restart the app after making their changes.

The designs have been updated in a couple of ways to promote this requirement and also to prompt the user to restart the app when attempting to save changes to Network settings which include any change to RPC URLs.

**Itemised changes to flow:**

1. Both RPC URLs (Main and Failover) have updated info text:
`Required (changes require restart)` and `Optional (changes require restart)`:

<img width="472" alt="Screenshot 2024-02-01 at 2 32 58 PM" src="https://github.com/status-im/status-desktop/assets/110033914/e6fc2494-7eac-431c-918b-fe2268508bcd">

--

2. When the user clicks `Save changes`, if there are any changes to RPC URLs (either Main or Failover or both), they are shown a dialog which enables them to restart in order for the changes to take effect or save the changes for later. 
<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/110033914/db1e83a0-e065-4fdd-9b03-9372beebb6d0">

--

3. If the user selects `Save and restart later`, the RPC URL changes will be implemented the next time they restart the app. The information text under the RPC URL field confirms this:

<img width="506" alt="Screenshot 2024-02-01 at 2 40 33 PM" src="https://github.com/status-im/status-desktop/assets/110033914/ecf0e687-c835-43d8-a83f-99adc4f9657d">

--

These changes have been implemented to ensure the user is able to change multiple RPC URLs across multiple networks before having to restart.

**Figma:**
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=23255-189132&mode=design&t=0DRwQJKDGYJPHkq1-4

**Comment by alaibe** [comment]
What is missing is the part that shows "restart required for changes to take effect"

**Comment by caybro** [comment]
> What is missing is the part that shows "restart required for changes to take effect"

In LanguageView.qml, we have sth very similar:
```qml
        Loader {
            id: languageConfirmationDialog
            active: false
            sourceComponent: ConfirmationDialog {
                headerSettings.title: qsTr("Change language")
                confirmationText: qsTr("Display language has been changed. You must restart the application for changes to take effect.")
                confirmButtonLabel: qsTr("Close the app now")
                onConfirmButtonClicked: {
                    languageConfirmationDialog.active = false
                    Qt.quit()
                }
            }
        }
```
