### ISSUE TITLE
Validate account name and keypairs that are under 5 characters

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13384]
New validation states have been added to the various flows listed below to prevent the user from entering an account or keypair name that is <5 characters. This change was requested originally by @saledjenic and has been completed as part of a sweep of backlog items. 

**Flows where this validation is now featured:**

**1. Editing an existing account**

<img width="543" alt="Screenshot 2024-02-01 at 4 34 17 PM" src="https://github.com/status-im/status-desktop/assets/110033914/8b3a30f6-4985-4087-a1e0-c0eb5735a91f">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21039-220481&mode=design&t=2O68lxNGG9g1b1tx-4

--

**2. Rename keypair (Wallet Settings)**

<img width="551" alt="Screenshot 2024-02-01 at 4 28 20 PM" src="https://github.com/status-im/status-desktop/assets/110033914/e2097cb3-2e84-47eb-826f-4f2684a98796">

Figma:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=23264-284147&mode=design&t=i8YMYAMFRqAFgJ3v-4

--

**3. Add new keypair via seed phrase**

<img width="523" alt="Screenshot 2024-02-01 at 4 27 22 PM" src="https://github.com/status-im/status-desktop/assets/110033914/8753ebdb-367e-4bb4-bda1-346d3ff7c902">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21240-102220&mode=design&t=2O68lxNGG9g1b1tx-4

--

**4. Add new account via private key**

<img width="537" alt="Screenshot 2024-02-01 at 4 30 47 PM" src="https://github.com/status-im/status-desktop/assets/110033914/c065ada3-9416-4567-93b5-f0228679b203">

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21240-102386&mode=design&t=2O68lxNGG9g1b1tx-4

--

5. Generate new keypair - naming the new keypair
(Validation same as others and not shown again in design as would be duplicative)

**Comment by lukaszso** [comment]
I've edited our existing test cases to include the minimum character limits:
1. [Editing an existing account](https://ethstatus.testrail.net/index.php?/cases/view/704433)
2. [Rename keypair (Wallet Settings)](https://ethstatus.testrail.net/index.php?/cases/view/703420)
3. [Add new keypair via seed phrase](https://ethstatus.testrail.net/index.php?/cases/view/703030)
4. [Add new account via private key](https://ethstatus.testrail.net/index.php?/cases/view/703029)
5. [Generate new keypair - naming the new keypair](https://ethstatus.testrail.net/index.php?/cases/view/703036)

And here is a completed test run for this ticket: [TestRail](https://ethstatus.testrail.net/index.php?/runs/view/15114)
