### ISSUE TITLE
Wallet Settings: Removing accounts and keypairs holding tokens required for community permissions

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13382]
Wallet Settings flows have been updated to show what the user will see if they remove an account or keypair that holds tokens required for community permissions/roles.

A new variant of each of the remove account/keypair dialogs has been added, showing a permissions section which clarifies which permissions will be lost if the user proceeds with the removal of the account/keypair.

_Eg removing an account that was imported via seed phrase:_
No permissions will be lost:
<img width="627" alt="Screenshot 2024-02-01 at 3 34 37 PM" src="https://github.com/status-im/status-desktop/assets/110033914/cd39cb6d-9646-4520-8762-66a24aaff9b2">

Permission will be lost:
<img width="684" alt="Screenshot 2024-02-01 at 3 34 45 PM" src="https://github.com/status-im/status-desktop/assets/110033914/51e03dd4-1f38-4f75-94d6-249dcd7bad7f">

The permissions section of the dialog is always hidden if no permissions will be lost via the removal of the account or keypair.

For consistency, across all remove dialogs (whether the permissions section is present or not) any checkbox acknowledgement is now pinned to the toolbar. This means that if the dialog does feature the permissions section, the acknowledgement (checking of which is required to continue) will always be seen, i.e. it will not be pushed below the viewable area of the dialog buried at the bottom of the scrollable area. Pls note that this is a global architectural change to all of the remove account and keypair dialogs even if the permissions section is not present/applicable.

In order to make the scrolling behaviour clear, each of these dialogs are presented at their full size and in situ of a min app height where the scroll behaviour and pinning of the acknowledgements area can be seen.

<img width="1221" alt="Screenshot 2024-02-01 at 3 38 06 PM" src="https://github.com/status-im/status-desktop/assets/110033914/b794d7cb-db7a-472a-98ea-79801ed75dc0">

If any permissions are lost after the user authenticates the removal of the account/keypair, an ephemeral notification is shown to confirm the loss of the permissions that were listed in the dialog (number of permissions lost only, not detail of permissions lost).
<img width="447" alt="Screenshot 2024-02-01 at 3 40 15 PM" src="https://github.com/status-im/status-desktop/assets/110033914/7f266896-8fc5-40c0-a443-193f26623edf">

**Figma**
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=23257-269374&mode=design&t=0DRwQJKDGYJPHkq1-4

**Comment by benjthayer** [comment]
Hey @saledjenic is there a list being compiles of these `stale` items just so we can refer back to them at a later date if they become a priority - saves us having to rewrite the issue / find the relevant flows again.

**Comment by saledjenic** [comment]
Exactly, we will get back to them at some point in the future if needed, that's why we added `stale` label, to filter them easier, but those issues are either too long here or not relevant according to our new strategy:
https://github.com/status-im/status-desktop/issues?q=label%3Astale+
