### ISSUE TITLE
Token Management: Items disappear temporarily after an item is unhidden

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13392]
# Bug Report

## Description

When unhiding the top item on the hidden list in Manage Tokens it can be observed that upon the list is refreshed some items may disappear. Switching tabs fixes the issue.

## Steps to reproduce

1. Have at least 2 items added to the hidden list
2. Go to Settings > Wallet > Manage Tokens > Hidden tab
3. Click three dots next to the top item on the list
4. Click "Show asset"
5. Observe the items on the list

#### Expected behavior
Item is removed from the list. The list is updated and all other hidden items remain on it.

#### Actual behavior
Some items disappear from the list.

### Additional Information
If the user switches tabs or backs out from this screen and comes back again, the list view is shown correctly.

https://github.com/status-im/status-desktop/assets/52439419/699a1ef1-0492-45ec-ab97-635435942cf1

- Status desktop version: StatusIm-Desktop-240201-060925-c995ff-aarch64
- Operating System: macOS Sooma

**Comment by caybro** [comment]
I noticed this with the introduction of the collapsible sections, can you have a look at it @micieslak ?
