### ISSUE TITLE
Collectible detail page revisions to accommodate community collectibles and other enhancements

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13399]
The collectible detail page layout has been updated to accommodate the community collectible type as well as to feature a number of enhancements to design and usability.

List of tasks (described below)
- [x] #13804
- [x] #13809
- [x] #13806
- [x] #13807
- [x] #13808
- [x] #13810 
- [x] #13918
- [x] #13927
- [x] #14203

**Comment by alaibe** [comment]
Need to be splitted (It is an epic)

**Comment by Khushboo-dev-cpp** [comment]
@benjthayer  I see that there is a difference in collectible and assets details view with regards to placement of community tag and network tag, can we align them? https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=18700-286023&mode=design&t=p83UaHavk7ekStvT-4

**Comment by dlipicar** [comment]
Broke this down into several different sub-tasks
