### ISSUE TITLE
Close Chat and Clear History flows updated to align with mobile app in terms of functionality and terminology

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13393]
The `Close Chat` and `Clear History` context menu items for 1:1 chat have been updated to align with mobile.

<img width="478" alt="Screenshot 2024-02-01 at 9 12 25 PM" src="https://github.com/status-im/status-desktop/assets/110033914/40c9f8e1-fc45-4e1d-af48-d0ad33c6999a">

In addition the confirmation dialogs for each action have also been updated to align with mobile:

**Close chat:**

<img width="472" alt="Screenshot 2024-02-01 at 9 14 08 PM" src="https://github.com/status-im/status-desktop/assets/110033914/b4aca102-8dd8-4376-ba7e-e14938ec880a">

Once the chat is closed, the chat disappears from the user's Chat list and the next chat down in the list is selected. If the user is closing their only chat, the empty state for the Messaging app is shown.

--

**Clear chat history:**
Note that there are 2 checkboxes:
`Delete all messages on my side`- mandatory (on and disabled)
`Delete my messages for [counterparty name]` - optional - if checked, this will delete all of the actioning user's messages from the chat on the counterparty side.

<img width="448" alt="Screenshot 2024-02-01 at 9 14 33 PM" src="https://github.com/status-im/status-desktop/assets/110033914/b6261593-8580-49ca-bc9a-f8e7d30798ce">

Figma:
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=24942-215153&mode=design&t=GWTxxV5I2KBpua8E-4

**Comment by noeliaSD** [comment]
Assigned to myself to better analyse

**Comment by noeliaSD** [comment]
It seems there's an open pr that needs to be reevaluated.
Moved to **2.31** since in **2.30**, the _ui-team_ will be focused on wallet.
