### ISSUE TITLE
[Tokens management] Wrong navigation to settings tab from hiden token toast link

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13409]
# Bug Report

## Description

Wrong navigation to settings from hiden token toast.

## Steps to reproduce

1. Go to wallet main view
2. Assets or Collectibles tab
3. Right click element and select Hide
4. Confirm you want to hide, in the confirmation popup
5. A toast is displayed, press the link to navigate to the settings

#### Expected behavior
Navigation to `Collectibles` or `Assets` tab depending on which element has been hidden

#### Actual behavior
Navigation to `Advanced tab`

https://github.com/status-im/status-desktop/assets/97019400/f1043266-bdd6-4f3c-8c7f-a1d608a627bd

**Comment by caybro** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/13319
