### ISSUE TITLE
API for fetching assets for a contact's wallet accounts 

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#13410]
### Description

[This](https://github.com/status-im/status-desktop/issues/13072) profile showcase issue needs a solution to get tokens for a contact. 

figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&mode=design&t=T89jp65Gs1Low18d-0

Use case:
- A user opens a profile for another user and application shows a list of tokens, presented in the profile showcase

<img width="793" alt="Screenshot 2024-02-02 at 21 12 25" src="https://github.com/status-im/status-desktop/assets/2522130/fd104fa1-13a4-469e-8871-df539ba831f4">

The source data i have from the profile showcase response (can be changed if needed):
- List of wallet accounts (addresses)
- List of verified tokens identified by `symbol`
- List of unverified (custom) tokens  identified by `contractAddress+chainId`

Expected data: list of tokens (combined or separated for verified and unverified) with fields:
- Summarised amount for provided wallet addresses
- Name
- Custom image for unverified token
- Symbol for verified token
- CommunityId for unverified token

The complexity is caused by the fact that both verified and unverified (e.g community) tokens must be presented in the profile showcase model.

**Comment by jrainville** [comment]
@MishkaRogachev does this mean that https://github.com/status-im/status-desktop/issues/13072 is no longer blocked?

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev does this mean that #13072 is no longer blocked?

Yes!
