### ISSUE TITLE
Failed to connect an ENS name from `.eth` domain

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#13422]
### Description

When trying to add my `sirotin.eth` name I faced this issue. 
I was successfully found as the owner of my ENS and kindly offered to connect it to Status, i.e. call `setPubkey` smart contract method.

<img width="1312" alt="Screenshot 2024-01-27 at 14 03 37" src="https://github.com/status-im/status-desktop/assets/25482501/4cc5f562-3d70-44f3-8d81-9e0ad46c3b75">

After making the transaction with the occurred popup I was notified that everything is good as far as the transaction is complete:

<img width="1312" alt="Screenshot 2024-01-27 at 14 08 00" src="https://github.com/status-im/status-desktop/assets/25482501/4bdfbe75-9853-4556-9d81-32894b341d3c">

But the transaction failed with `Warning! Error encountered during contract execution [out of gas]` 🙁 
https://etherscan.io/tx/0x4fc3ad9429fcf4bd9b75aee7c299db71192182a6ceb9b91112910ac26bbdd3c4

I tried a few times and faced the same result. Ended up calling the `setPubkey` manually from etherscan.io.

**Comment by anastasiyaig** [comment]
i cant use such ens names in saved addresses as well @alaibe

**Comment by saledjenic** [comment]
We can try to fit it in 2.30 if there is a time for it.

But my overall impression is that the entire UI for ens usernames is a bit odd/unintuitive/broken do we plan to redo/improve it anytime soon?
@benjthayer

**Comment by benjthayer** [comment]
> We can try to fit it in 2.30 if there is a time for it.
> 
> But my overall impression is that the entire UI for ens usernames is a bit odd/unintuitive/broken do we plan to redo/improve it anytime soon? @benjthayer

AFAIK, we are looking to completely overhaul / redesign this flow. It's on the list but not been prioritised as yet. 

cc @John-44
