### ISSUE TITLE
[Profile Showcase - Profile Popup] "Preview as ..." aspect combobox

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13424]
- preview changes based on the combobox options
- same for the side-by-side preview
- (preferably) this should be visible everywhere throughout the app

![image](https://github.com/status-im/status-desktop/assets/5377645/ddf06d1a-f59f-4263-a44a-4848d257e13d)

Figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-28481&mode=design&t=YkNSSPf4Iu2eiMQx-0

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one

**Comment by alexjba** [comment]
Depends on #14014

**Comment by caybro** [comment]
Possible candidate for 2.28.1
