### ISSUE TITLE
[Profile Showcase - Identity] Validate the display name against all members of joined communities

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13434]
### Description

Figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/👤-Profile-%7C-Desktop?type=design&node-id=2460-27121&mode=design&t=ZmeSQiEF0IUZft3G-0

There is a new validation requirement when setting up a display name. This validation states that the user cannot choose a display name that is identical to any member of his joined communities.

The purpose of this task is to implement the backend support for this validation.

<img width="575" alt="Screenshot 2024-02-06 at 14 58 01" src="https://github.com/status-im/status-desktop/assets/47811206/18618cb3-c646-4537-ba75-a3c7c236805c">

**Comment by alexjba** [comment]
The UI is implemented here: https://github.com/status-im/status-desktop/issues/13335

**Comment by alexandraB99** [comment]
@jrainville fyi

**Comment by jrainville** [comment]
@alexandraB99 why did you add the `needs-design` label? I thought the UI was already available for this?

**Comment by caybro** [comment]
Not yet fixed, was closed by the linked status-go PR
