### ISSUE TITLE
Cropped profile settings 

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#13432]
# Bug Report

The content in Profile settings is cropped.
Even when scrolling to the bottom, it's not possible to fully see the profile showcase communities list.

<img width="1312" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/324a71a1-99de-45ae-b8f1-00d8ef804831">

Version: nightly build 240206-035700-ae16bd

**Comment by caybro** [comment]
Superseded by https://github.com/status-im/status-desktop/issues/13330
