### ISSUE TITLE
ERC20 token miniting failing with "POKT & Infura down on Optimism" error

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-desktop#13441]
**Preconditions:**  Mainnet Optimism network is enabled

**Steps:** 

1. Open communtity with already minted Owner/Master tokens on optimism
2. Go to Community management => tokens => mint token = assets
3. Mint a token
4. See if minting process was successful

**Actual result:**  minting is failing with "POKT & Infura down on Optimism" error

[app_20240207_101439.log](https://github.com/status-im/status-desktop/files/14190999/app_20240207_101439.log)

https://optimistic.etherscan.io/address/0x527d22094166ad33e7523d2cbca287798e149c7f

<img width="1119" alt="Status Desktop 2024-02-06 20-57-25" src="https://github.com/status-im/status-desktop/assets/97245802/23dad5ea-8ddf-45a7-a591-02014b92d5b4">

https://github.com/status-im/status-desktop/assets/97245802/419d45a5-b3ca-4684-b5ef-2b1f45dd5e59

### Additional Information

- Status desktop version: StatusIm-Desktop-240206-035700-ae16bd-nightly-aarch64
- Operating System: macOS Monterey v. 12.0

**Comment by anastasiyaig** [comment]
@endulab can you please look into that? It might be something to do with account itself , the account used is quite old (more than 2 years) 
I tried to mint today with my account and everything went well. I am running out of ideas

**Comment by endulab** [comment]
I see the error during deployment:
`fallback failed with insufficient funds for gas * price + value: balance 686640593411180, tx cost 1756449076941033, overshot 1069808483529853`
Before deployment the calculated fee was as follows:
walletBalance=0.00068664059341118,  ethValue=5.78382255e-06 -> ethValue=0.00000578382255.
There is some mismatch between the real fee and the fee computed by us.
Asset contract deployment units=1650000 (it is fixed).
After quick computations it seems that:
 * real gas price = 0,000000001064515 ETH
 * our gas price = 0,000000000003505 ETH
@alaibe does these computations make sense?

**Comment by alaibe** [comment]
@endulab this is how we comnpute the fees:
https://github.com/status-im/status-go/blob/cb18e5295a185e8d589d66135c53704e895d54e3/services/wallet/fees.go#L88-L160

As u can see we mostly ask the chain what the fees are?

I think the only potential error could be on:
```	config := params.MainnetChainConfig```

I cannot see something wrong in our logic. Could it be the gas price change? or do you reproduce this all the times?

**Comment by anastasiyaig** [comment]
i think @pavloburykh can reproduce it all the times @alaibe

**Comment by anastasiyaig** [comment]
Arbitrum Mainnet in my case (the only place i have money on)

**Comment by anastasiyaig** [comment]
@pavloburykh i will close that one in favor or https://github.com/status-im/status-desktop/issues/13646 which now being worked on
