### ISSUE TITLE
Identity verification requests should be stored on waku

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13448]
### Description

ID Verification requests should be stored on waku.

Currently it is not the case (or works partially)

<img width="2032" alt="Screenshot 2024-02-07 at 15 34 24" src="https://github.com/status-im/status-desktop/assets/82375995/4099bb1c-24b8-4d50-b1c9-150cb12f37e1">

https://docs.google.com/spreadsheets/d/1VyVIg5ZaVSlKWZRHSLzSMCMGJsbprkWUfEqCUJKma8w/edit#gid=507125679

**Comment by anastasiyaig** [comment]
@jrainville looks like messenger team task, not sure when it should be implemented, it is kinda leftover since god knows when :)

**Comment by jrainville** [comment]
> not sure when it should be implemented, it is kinda leftover since god knows when :)

Yeah good catch. I know Identity verification work was paused for a while to focus on making contact requests and other features work.

Do you know if the basic Identity verification flow is now solid? If so, we can plan to do the backup in the next milestone.

**Comment by anastasiyaig** [comment]
it works somewhat! However there is a redesign coming soon

https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-197035&mode=design

**Comment by iurimatias** [comment]
this is descoped for the moment
