### ISSUE TITLE
Change the client behaviour for the banned community member

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#13454]
### Description

1. When a user is banned or kicked, the community should disappear from the community nav bar and the next community down should be selected (unless there are no other communities in the nav bar in which case the Find community page is selected).
2. If a user is banned from the community, they should not be able to see or search for the community in the Find Community page
3. If the user navigates to the community while they are banned (e.g. via a share link), they will see a banned state for that community.

https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=51860-257070&mode=design&t=pzq70E9CXbiufWaG-4

**Comment by jrainville** [comment]
Split task from https://github.com/status-im/status-desktop/issues/13034
