### ISSUE TITLE
Align delete message functionality across mobile and desktop

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13457]
### Description

Mobile client has 2 options to delete a message: `delete for everyone` and `delete for me`
Desktop client does have the only option `delete`

We need to align that 

![IMG_3446](https://github.com/status-im/status-desktop/assets/82375995/ae5bf40f-779f-4d46-bc3e-f217c6ad205d)

<img width="1512" alt="Screenshot 2024-02-07 at 17 13 57" src="https://github.com/status-im/status-desktop/assets/82375995/19ad7bc3-6258-4e7a-a2c5-72da4c48da32">

**Comment by anastasiyaig** [comment]
@jrainville @benjthayer @pavloburykh

**Comment by jrainville** [comment]
We have this already tacked here https://github.com/status-im/status-desktop/issues/7632.

Closing as duplicate.
