### ISSUE TITLE
Notifications about minting are received when adding watched address

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13452]
### Description

1. open app and create fresh account
2. add `0x02034eEA7af2bCb3e0bCe3abB4348ad5eC556f5b` as watch only
3. switch to test net

As result, i received a bunch of notifications that i have been airdropped with something

<img width="1512" alt="Screenshot 2024-02-07 at 16 32 34" src="https://github.com/status-im/status-desktop/assets/82375995/21bb9919-0b45-4d1e-8a0b-747da906da80">

**Comment by anastasiyaig** [comment]
@jrainville @alaibe is it somewhat new functionality or smth indeed working weird?

**Comment by alaibe** [comment]
Something weird. Khusboo opened the same issue today. We should ignore wat h only account

**Comment by anastasiyaig** [comment]
oh sorry, i did not find that one! If you have a link lets close one of those

**Comment by anastasiyaig** [comment]
lets keep it in https://github.com/status-im/status-desktop/issues/13458
