### ISSUE TITLE
Adding watched addresses shows wrong notifications

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#13458]
### Description

Adding watched addresses that have some owner tokens, leads to a bunch of notifications about receiving owner tokens. However these should not be seen as  watched addresses are not owned by them

![image](https://github.com/status-im/status-desktop/assets/60327365/f9c09e90-db77-48b6-9d9a-dacd9d4b3b7e)

**Comment by anastasiyaig** [comment]
i logged that as well :D https://github.com/status-im/status-desktop/issues/13452

**Comment by anastasiyaig** [comment]
@iurimatias we need to groom issues somehow a bit different, we spend time on planning, estimating and evaluating outdated issues
