### ISSUE TITLE
Align display name length with mobile requirements

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13456]
### Description

Current implementation on mobile allows to enter 24 chars for display name
When importing such account on desktop, we have validation error in settings

Since mobile uses newest designs i guess it is for to desktop client to get aligned

<img width="1512" alt="Screenshot 2024-02-07 at 17 12 51" src="https://github.com/status-im/status-desktop/assets/82375995/496989bd-e532-4e5c-b2bf-18fd503c6c7f">

**Comment by anastasiyaig** [comment]
cc @benjthayer @pavloburykh

**Comment by pavloburykh** [comment]
Just in case, here is a proof from Mobile [Figma](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465%3A89735&mode=dev)

<img width="297" alt="Onboarding for Mobile – Figma 2024-02-07 16-28-35" src="https://github.com/status-im/status-desktop/assets/97245802/6a82e256-2d59-4671-960c-208f4f222bcd">

**Comment by benjthayer** [comment]
@anastasiyaig @pavloburykh thanks for flagging - discussed with @John-44 and the decision is to reduce the display name character limit on mobile to 20 characters to align with desktop. Nicknames should also follow the same validation as display names. 

cc @pedro-et @mariocnovoa
