### ISSUE TITLE
[Profile Showcase - Collectibles&Assets] Explore whether the assets/collectibles filtering should happen on the backend or UI based on the accounts selected to showcase and/or Tokens management settings.

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13462]

**Comment by caybro** [comment]
@micieslak I guess we agreed to do that on the UI (C++) side?

**Comment by micieslak** [comment]
> @micieslak I guess we agreed to do that on the UI (C++) side?

Yes, it's part of architecture proposed in https://github.com/status-im/status-desktop/issues/13341 and depicted on diagram:
https://miro.com/app/board/uXjVNxUvgDA=/.

It assumes dynamic filtering done in the UI side:

![Screenshot from 2024-02-08 12-34-10](https://github.com/status-im/status-desktop/assets/20650004/7a7af5ba-ebfb-4592-8bf0-32ee576bd9e4)

**Comment by micieslak** [comment]
As designed https://github.com/status-im/status-desktop/issues/13341 and confirmed with the Wallet Team (https://docs.google.com/document/d/1tv0ZdD6eVU1uoYk4BgGL_PQO79Ogb8TkP6xL1DfJ83g/edit) we can reuse wallet models for profile showcase preferences for current user.
