### ISSUE TITLE
Allow E2E tests to circumvent file selection dialog

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13483]
### Description

**Current problem:** autotests cant pass on certain hosts because of system file upload dialog is not showing up. It is displayed at the top left and not expanding.

![image](https://github.com/status-im/status-desktop/assets/82375995/b6959948-88b9-4247-9106-7898d265be16)

As possible workaround to keep the tests without losing coverage - implement a way to use absolute path to files, for example a custom field where i can paste the path to a file and click submit button

Alternatively, we can ofc exclude the tests that are interacting with file uploads.

I can't use TEST MODE now, because it behaves weirdo. We running old QT version now that is most likely the case of slow rendering of the app (and tests failures)

I am waiting when the upgrade to QT 5.15.8 will happen for Linux hosts
https://github.com/status-im/status-desktop/pull/9232
https://github.com/status-im/status-desktop/issues/13311

**If i test the app built with QT5.15.8 and it is fine in test mode for tests, then this change will not be needed. So this ticket is dependant on the 2 above**

**Comment by jakubgs** [comment]
I think this is the correct way of dealing with this problem. The file dialog is system specific and linux desktop shell specific, and hence it is not that useful or easy to test. In addition to that the unpredictable behavior of the dialog within the virtual framebuffer(`Xvfb`) makes tests fail for no good reason on specific hosts in CI like `linux-03` without any clear cause.

I have narrowed down the software difference between `linux-03` and a host without issues to just kernel packages:
```
 > diff linux-03.list linux-05.list
978,980c978,980
< linux-image-5.15.0-94-generic/jammy-updates,no
< linux-image-generic/jammy-updates,no
< linux-libc-dev/jammy-updates,no
---
> linux-image-5.15.0-92-generic/jammy-updates,jammy-security,jammy-updates,jammy-security,no
> linux-image-generic/jammy-updates,jammy-security,jammy-updates,jammy-security,no
> linux-libc-dev/jammy-updates,jammy-security,jammy-updates,jammy-security,no
982c982
< linux-modules-5.15.0-94-generic/jammy-updates,no
---
> linux-modules-5.15.0-92-generic/jammy-updates,jammy-security,jammy-updates,jammy-security,no
984c984
< linux-modules-extra-5.15.0-94-generic/jammy-updates,no
---
> linux-modules-extra-5.15.0-92-generic/jammy-updates,jammy-security,jammy-updates,jammy-security,n
```
And yet the issue persists. I do not have time to debug heisenbugs like this, and I think avoiding the dialog altogether is the best option we have.

**Comment by jrainville** [comment]
I "fixed" that problem for the test that sends an image by adding a function in the QML code that the test could call that adds the image directly from the code instead of from the UI.

Doing it that way doesn't require to change the UI so it's pretty simple.

https://github.com/status-im/status-desktop/blob/5811285de6dd864ef612164f8c0db44bb6cbf818/ui/imports/shared/status/StatusChatInput.qml#L946-L950

**Comment by anastasiyaig** [comment]
i will check it out! thanks!

**Comment by igor-sirotin** [comment]
I took a look at this.
In `EditCroppedImagePanel`, which is used to set community logo and banner, we have `cropImage` function:
https://github.com/status-im/status-desktop/blob/3d1c98717ab04fc59d795aede075f78cbde737c9/ui/imports/shared/panels/EditCroppedImagePanel.qml#L41-L43

This seems to be right what's needed. 
Though I agree the function name not quite self-explanatory 😄

**Comment by anastasiyaig** [comment]
and it accepts the file path? Then i am good @igor-sirotin  :D
