### ISSUE TITLE
The "Allow new contact requests" toggle set to off does not stop CRs from an user that has been in contacts before

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13488]
# Bug Report

## Description

If the user sets the "Allow new contact requests" to off, then they can still get a contact request, but only if that user has been a contact before. This is confusing, because that user might change their name in the meantime and look like a brand new contact. This toggle should either block all of the requests or at least inform the user that old contacts might still contact them even when it's set to off.

## Steps to reproduce

1. Log into the app as two users
2. Send a contact request from user1 to user2. 
3. Accept the request as user 2
4. Go to settings -> messaging and set "Allow new contact requests" to off
5. Remove user1 from contacts
6. Send a contact request to user2 as user1

#### Expected behavior
"Allow new contact requests" set to off either blocks all of the requests or the user is informed that it blocks CRs only from accounts they have never been in contact with

#### Actual behavior
User is not informed that they can still receive a contact request. The toggle does not stop some of the requests from being received.

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/
- Operating System: macOS

**Behaviour when user is a new contact**
https://github.com/status-im/status-desktop/assets/155960867/da58d1e9-4f71-40cc-9409-e54b8357f787

**Behaviour when user is a deleted contact**
https://github.com/status-im/status-desktop/assets/155960867/cb74868f-8473-46e1-9778-54d1ef13fc03

**Comment by anastasiyaig** [comment]
@jrainville need your 👀 on this

**Comment by jrainville** [comment]
Nice catch. I'll assign it for next sprint

**Comment by Michal-Status** [comment]
I have added videos showcasing the behaviour of the app

**Comment by Michal-Status** [comment]
This issue does not occur on https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/14/
