### ISSUE TITLE
[Profile Showcase - Profile Popup] Place user image/identicon onto the QR code

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13482]
- the `ShareProfileDialog.qml` showing the user's QR code has to place the user's profile image or letter identicon in the center of the QR code
- find out whether this is indeed supported by our NIM module that generates the QR code for us; we get it as such:
```js
function getQrCodeSource(publicKey) {
  return globalUtils.qrCode(publicKey)
}
```
![image](https://github.com/status-im/status-desktop/assets/5377645/d84fb718-14bf-47b4-b568-33526e97b3cf)

Figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-31006&mode=design&t=PinU3PVz9XZkigA6-0

**Comment by alexjba** [comment]
@jrainville Can we add this task to the messenger team to have a look if the qr code can be generated in status-go? It makes sense to me to be generated in status-go because we need the same qr code for the mobile app as well.


<img width="329" alt="Screenshot 2024-02-09 at 17 05 06" src="https://github.com/status-im/status-desktop/assets/47811206/56eb1cf8-4338-4325-8a81-62883ce7faa0">

**Comment by jrainville** [comment]
I think QR codes are just magic like that where they have such high error correction that you can just put an image on top and it will still work.

Anyway, that's to say that IMO, it would be way simpler to just put the user image on top of the QR image in QML than try to generate a special QR in status-go.

Though, I agree that when stuff is shared between mobile and desktop, it's better to do in status-go, this is such a visual element, and also pretty minor, it's better to deviate from that rule of thumb.

**Comment by caybro** [comment]
@benjthayer what if there's no user image; do we show the letter identicon then, or nothing?

**Comment by benjthayer** [comment]
> @benjthayer what if there's no user image; do we show the letter identicon then, or nothing?

Hey @caybro thanks for checking - I've added this case into the designs:
https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=3415-251196&mode=design&t=H5RIhHYaNHdeIzDA-4

**Comment by caybro** [comment]
> > @benjthayer what if there's no user image; do we show the letter identicon then, or nothing?
> 
> Hey @caybro thanks for checking - I've added this case into the designs: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=3415-251196&mode=design&t=H5RIhHYaNHdeIzDA-4

Thanks, adjusted the issue description/screenshot
