### ISSUE TITLE
Wallet -> Assets are duplicated

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13486]
### Description

Can reproduce on test net

<img width="1524" alt="Screenshot 2024-02-09 at 10 31 55" src="https://github.com/status-im/status-desktop/assets/82375995/8320d28a-0baf-4aa5-aadd-79d3eadeb753">

@dlipicar saw that as well

![image](https://github.com/status-im/status-desktop/assets/82375995/b93c0aae-614a-4795-a954-adab1357478e)

**Comment by alaibe** [comment]
hint: it happens when assets are reloaded after 10min
