### ISSUE TITLE
[Profile Showcase - Web]: Create component maintaining dirty state for Web tab in settings

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#13495]
## Description

The analysis led to conclusions that it's beneficial to drop current nim implementation of intermediate state for Profile showcase and move it to the UI side. Analysis done here: https://github.com/status-im/status-desktop/issues/13341

This is the most straightforward tab bc the whole data is managed fully by profile showcase. No referencing to other models like in case of communities, accounts or tokens. 

https://miro.com/app/board/uXjVNxUvgDA=/

![Screenshot from 2024-02-09 14-47-36](https://github.com/status-im/status-desktop/assets/20650004/180d988b-5033-46cd-ba16-8aef11278b0b)

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-desktop/pull/13900
