### ISSUE TITLE
[Profile Showcase]: simplify API of `ProfileShowcase*Panel` tabs

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#13498]
## Description

Along with moving dirty state management form Nim to C++/QML, also UI components can be simplified, with concise and well defined API.

This task is applicable to following tabs: `Communities`, `Accounts`, `Assets` and `Collectibles`

The following description uses `Communities` tab as an example, but exactly same pattern should be applied to the rest of tabs as well.

![Screenshot from 2024-02-09 17-37-59](https://github.com/status-im/status-desktop/assets/20650004/15878bf2-1ce7-4ea2-8b50-9da6d3a3e550)

Apart from the final design (to be done in a separate task), we can define the interface that will stay unchanged even after introducing further visual changes to the component.

**INPUT**:
- `In showcase communities model` - providing entries for the upper section (community id and other metadata displayed by the delegate) + visibility level
- `Hidden communities model` - providing entries for the hidden section - structure the same as the model above but visibility info not needed here

**INTERACTIONS** (signals emitted by that component):
- `setVisibilityRequested(id, visibility)`: setting visibility of the community, triggered when user drags an item between sections or selects specific visibility from the dropdown menu

The assumption is to have visibility defined as noted by @caybro : https://github.com/status-im/status-desktop/issues/13498#issuecomment-1938438834

- `changePositionRequested(id, from, to)`: changing order withing `in showcase` section, triggered when user drags item within `in showcase` section

`ProfileShowcaseCommunitiesPanel` should display data from the models directly, possibly without any special transformations.

With API defined this way it's possible to easily provide mock data using `ListModel`s and also implement mocked reactions to signals emitted by the components (by taking item from one list and put to another on `hideItemRequested`/`showItemRequested` and calling `ListModel::move` on `changePositionRequested`.

Similarly connecting to the real component holding actual dirty state should be straightforward as well. The component intended to provide content to this UI component is defined here: https://github.com/status-im/status-desktop/issues/13435. The flow is depicted also in Miro: https://miro.com/app/board/uXjVNxUvgDA=/

The actual "save" operation shouldn't involve this component. "Save" operation will retrieve necessary info from dirty state component and form proper request to the backend.

Any data filtering, moves and sorting should be done outside the ui components, which are intended to only display the content provided by the model.

**Comment by caybro** [comment]
The 2 interaction calls (`hideItemRequested` and `showItemRequested`) could be merged into 1; the "hidden" is just one of the enum values:
```qml
enum ShowcaseVisibility {
        NoOne = 0, // <-- hidden
        IdVerifiedContacts = 1,
        Contacts = 2,
        Everyone = 3
    }
```
