### ISSUE TITLE
Activity controller and UI should not use symbol as param for get token details

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#13505]
### Description

the activity mechanism uses  symbol in their handling which may not a unique id. We may need to have more than symbol as we can have tokens with same symbol.

The unique identifier for client size has been done in tokens service and the logic behind it can be found here https://github.com/status-im/status-desktop/blob/dffa404fec921c525327eed6fa3bbacbb13be7eb/src/app_service/service/token/service.nim#L299

After this is done we can remove below calls which are needed because we using token symbol and token key
parseCurrencyValue
findTokenBySymbolAndChainId
findTokenBySymbol

**Comment by endulab** [comment]
This will be a bit changed in https://github.com/status-im/status-desktop/issues/15077.

**Comment by saledjenic** [comment]
Following the previous comment, this one is not valid anymore.
