### ISSUE TITLE
Replace old tests with new tests in PRs for desktop repository

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13514]
### Description

ITS TIME!

![image](https://github.com/status-im/status-desktop/assets/82375995/57560b2c-051b-49ce-a902-33923a0d7b71)

I am about to replace old tests with new tests. What does it mean? 

1. old tests  which code is living in status-desktop repository will not be executed in PRs
2. instead, new tests will become mandatory

<img width="1347" alt="Screenshot 2024-02-12 at 16 19 27" src="https://github.com/status-im/status-desktop/assets/82375995/f1c7cd26-a1dd-4117-90f8-319963d3f619">

Bright side of this change:
- make @jakubgs happy
- reduce the load to hosts running 2 types of tests
- reduce the load to support 2 frameworks

Significant difference to acknowledge. We used to run **all tests in each PR per each commit.** This is being changed the way we run **only critical (smoke) path** for PRs, and all pack (all tests we have) on nightly basis in order to reduce the time of tests.

I will keep monitoring the tests myself so if they fail i will notice but please DM me if you are blocked

**Comment by anastasiyaig** [comment]
@iurimatias @alexandraB99 @alaibe @jrainville ^^^^

**Comment by jakubgs** [comment]
![image](https://github.com/status-im/status-desktop/assets/2212681/53fc628f-843a-4384-8f45-71790e5bb793)
