### ISSUE TITLE
[Profile flow] Respond to/review an incoming CR

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13519]
![image](https://github.com/status-im/status-desktop/assets/5377645/4ee299b0-cb79-4795-9b7e-4c64829bde86)

- "Ignore" just closes the popup

Figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-200309&mode=design&t=qVMy2WcrL4fvxnwK-0

**Comment by caybro** [comment]
@MishkaRogachev we still don't have the required API for this; it's impossible to get the (challenge) message associated with the incoming CR, apart from manually parsing the AC model. Can we add this? :)

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev we still don't have the required API for this; it's impossible to get the (challenge) message associated with the incoming CR, apart from manually parsing the AC model. Can we add this? :)

I can add api to `ContactsStore.qml`, similar to `hasPendingContactRequest` but returning whole contact request json for provided pubKey

**Comment by caybro** [comment]
> > @MishkaRogachev we still don't have the required API for this; it's impossible to get the (challenge) message associated with the incoming CR, apart from manually parsing the AC model. Can we add this? :)
> 
> I can add api to `ContactsStore.qml`, similar to `hasPendingContactRequest` but returning whole contact request json for provided pubKey

Would be great! I also noticed we already have a ReviewContactRequestPopup.qml; would be nice if we could reuse the same popup from both places (AC and ProfileDialog)

**Comment by caybro** [comment]
Depends on https://github.com/status-im/status-desktop/issues/13604
