### ISSUE TITLE
[Chat] Profile qr code SVGs are too small when viewed in the chat

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13539]
### Description

There's the option to share an SVG image with a qr code for a user profile. A user can share its own profile qr code in the app, but the receiver will see a tiny image. It's quite difficult to scan this qr code.

<img width="1193" alt="Screenshot 2024-02-13 at 15 40 18" src="https://github.com/status-im/status-desktop/assets/47811206/ac413f07-0bff-4bf4-ba16-6bb2bcea0ef3">

Repro steps:
1. Go to your profile
2. Click share profile
3. Right click on the QR code
4. Copy Image
5. Send the image in a chat
6. Open the sent image

Expected behaviour:
7. The QR code image is easily scannable because it has a proper size

Actual behaviour:
7. The QR code image is too small. Scanning it is difficult

Found on MacOs with a pixel ratio of 2

**Comment by caybro** [comment]
What's that warning in the chat input?

**Comment by alexjba** [comment]
> What's that warning in the chat input?

Ignore that. I've tried to send the download qr code file. It's not accepted

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone

**Comment by alexandraB99** [comment]
after discussions this is not an actual bug, there is nothing to be fixed here
