### ISSUE TITLE
Implement notifications about failed autotests in Discord channel

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13536]
### Description

When autotests are failed in any PR of status-desktop repository, i want to be notified about that immediately. Easiest solution for now seems to post notifications in discord channel, for example like this

<img width="426" alt="Screenshot 2024-02-13 at 13 57 47" src="https://github.com/status-im/status-desktop/assets/82375995/d8bdc619-c520-4f6d-9376-ca6b8abfab67">

https://discord.com/channels/624205794384281629/697843216048717905/1206592285362618468

**Comment by anastasiyaig** [comment]
@Valentina1133

**Comment by jakubgs** [comment]
Done:

- https://github.com/status-im/desktop-qa-automation/pull/511
- https://github.com/status-im/status-jenkins-lib/pull/83
