### ISSUE TITLE
Clicking on ID verification notification in AC results in forever loading chat

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13533]
# Bug Report

## Description

If you click on the notification in the AC received from an ID verification, it ends up in an infinite loading animation on the chat that was supposed to open.

## Steps to reproduce

0. Be mutual contact with another account and  have that chat open
1. Send an ID verification request from the other account
2. See the AC notification appear
3. Click on it (not the button, but the notif itself)

#### Expected behavior

Goes to the 1x1 chat for the person who sent the ID request (or does nothing if we're already in that chat)

#### Actual behavior

Shows an infinite loading animation

[id-request-infinite-loading.webm](https://github.com/status-im/status-desktop/assets/11926403/1f4afd1a-6ccd-4dea-83cb-7fb0caf03ca6)

### Additional Information

- Status desktop version: master `568bf8e9755e4364adc76507a4a6f9c6371058e2`
- Operating System: Ubuntu 20

**Comment by igor-sirotin** [comment]
urghhh, why does this keep happening 😬

**Comment by jrainville** [comment]
Might be related to https://github.com/status-im/status-desktop/issues/13814
