### ISSUE TITLE
When an user responds to contact request with "Decline and block", the sender of the CR receives a notification that they have been removed from contacts

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13545]
# Bug Report

## Description

The user that sent the contact request that has been declined with a block receives a notification that they have been removed from contacts, despite not being a contact of the other user. This causes an issue, because this tells the user that they have been blocked.

## Steps to reproduce

1. Log into two accounts that don't have each other in contacts
2. Send a contact request from User1 to User2
3. As User2 use activity center to decline the contact request

#### Expected behavior
From the point of view of User1 the notifications for "Decline and block" should be the same as for a normal rejection without a block

#### Actual behavior
The user that sent the contact request that has been declined with a block receives a notification that they have been removed from contacts, despite not being a contact of the other user

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/
- Operating System: macOS

Notification after the request has been rejected:
<img width="544" alt="Screenshot_2024-02-13_at_13 08 41" src="https://github.com/status-im/status-desktop/assets/155960867/a855eabc-9651-4113-ac7d-c7bcedb7f030">

Notification after the request has been declined with a block:
<img width="559" alt="Screenshot_2024-02-13_at_13 11 25" src="https://github.com/status-im/status-desktop/assets/155960867/036e5c69-90ee-493d-930d-e94241db6608">

**Comment by anastasiyaig** [comment]
@jrainville i think we dont really have to send this notification (if that's possible ofc) wdyt?

**Comment by jrainville** [comment]
> @jrainville i think we dont really have to send this notification (if that's possible ofc) wdyt?

Yes you're right. We should do the same as a normal rejection, ie not tell the other user that we rejected. They shouldn't know that we responded, even less blocked them.
