### ISSUE TITLE
When the computer is set to dark mode, the app displays password instructions in light mode

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13549]
# Bug Report

## Description

When the computer is set to dark mode, the app displays password instructions in light mode. In previous versions the entire UI for creating a new password was dark.

## Steps to reproduce

1. Launch the app with system set to dark mode
2. Add new user
3. Go to the input field for a new password

#### Expected behavior
Every UI piece is in dark mode

#### Actual behavior
Password instructions are in light mode

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/systems/job/macos/job/aarch64/job/package/311/
- Operating System: macOS 

Dark mode in https://ci.status.im/job/status-desktop/job/systems/job/macos/job/aarch64/job/package/311/ build:
<img width="653" alt="Screenshot 2024-02-13 at 20 44 02" src="https://github.com/status-im/status-desktop/assets/155960867/7e36df96-5d8f-40f2-85fc-d3cc49cd089a">

Dark mode in https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/ build:
<img width="636" alt="Screenshot 2024-02-13 at 20 44 06" src="https://github.com/status-im/status-desktop/assets/155960867/5601f2e4-434d-41b8-8b63-49a56b1da0d7">

**Comment by igor-sirotin** [comment]
Can confirm, faced same thing.

<img width="1312" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/13fb2a38-75fa-44ff-91f4-a3ce28c8e454">
