### ISSUE TITLE
General: Disable WebEngine for Nix build testing

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#13540]
# Bug Report

## Description

Currently we are able to build the application using Qt 5.15.8 and older gblic (compatible with older system) using Nix. However the app crashes on login attempt.

There is a chance that dependency on `WebEngine` is a source of problems.

The goal of this task is to prepare modified version of the app with `WebEngine` disabled (not initialized or cut-off completely).

**Comment by yakimant** [comment]
You can do it in a separate branch or directly in PR:
https://github.com/status-im/status-desktop/pull/9232

This is how build dependencies are described in Nix:
https://github.com/status-im/status-desktop/blob/54ae166e25bdf597751170e2dd1fb21d843973c0/shell.nix
