### ISSUE TITLE
Owner token transfer: Unable to receive owner token on testnet

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13546]
# Bug Report

## Description

While testing the 2.27 RC1 i noticed that i am unable to transfer ownership for a community. The flow is completed successfully and i get the confirmation toasts (one for start of the transfer and one for it's completion) but it never arrives in recipients wallet. Tried three times already always with the same result.

Etherscan shows the transaction with Success status.

## Steps to reproduce

1. Create a community
2. Mint owner token
3. Transfer the token to another user
4. Wait for the token to arrive at recipients wallet

#### Expected behavior
Token is received and the recipient can continue the transfer flow.
#### Actual behavior
The token never arrives.
### Additional Information

- Status desktop version: StatusIm-Desktop-v2.27.0-rc.1-83cb1a-aarch64
- Operating System: Mac

**Comment by jrainville** [comment]
@alaibe should this be assigned to the wallet team?

**Comment by alaibe** [comment]
@dlipicar is it related to the opensea issue?

**Comment by dlipicar** [comment]
@alaibe hmm, if that were the case, the collectible wouldn't even show up in the original owner's account.

@lukaszso could you give me the public addresses and tx hashes? What network are you doing this on?

**Comment by lukaszso** [comment]
@dlipicar i used goerli mainnet. Here's the transaction details: https://goerli.etherscan.io/tx/0x569498c3130b7ae9027bd035b8a5f52a5d7d1d1e3f974e269eb20008a959c5cf

Sender address: [0x7E9950Bd1189a888Ca3F65A3DeAB180780cd1A6c](https://goerli.etherscan.io/address/0x7E9950Bd1189a888Ca3F65A3DeAB180780cd1A6c)
Receiver address: [0xc6E6Acc1900E50cd1E8408DD0cE096c3B1D200a0](https://goerli.etherscan.io/address/0xc6E6Acc1900E50cd1E8408DD0cE096c3B1D200a0)

**Comment by dlipicar** [comment]
Could reproduce this by transfering an Owner token on Opt Goerli. 
Manually triggering a collectibles refresh on the receiver client did the trick (toggling testnet mode off and on). 
![image](https://github.com/status-im/status-desktop/assets/11161531/a61ed821-e5f3-4ee6-8dc3-08f0cc6255fc)

What would normally happen is:
1) An incoming ERC721 Transfer gets detected
2) This triggers a refresh of the Owned Collectibles list.

However, after waiting for a long while (~10 min), the incoming transfer is not detected
![image](https://github.com/status-im/status-desktop/assets/11161531/f2d59165-f0f1-4701-9611-ebedc531feff)

@IvanBelyakoff or @rasom could you jump in and see why that is?
