### ISSUE TITLE
Communities cannot be shown in Profile Showcase

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13548]
# Bug Report

## Description

When attempting to show a community on profile showcase it is impossible to do so. When the changes are saved it reverts back to community not being shown.

## Steps to reproduce

1. Log into a user account with at least one community
2. Go to Settings -> Profile -> Communities
3. Drag and drop the community to show it to everyone
4. Click on "Save changes"

#### Expected behavior
Changes are saved and community is shown on the Profile

#### Actual behavior
Changes are not saved and community is not shown on the Profile

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/
https://ci.status.im/job/status-desktop/job/systems/job/macos/job/aarch64/job/package/311/
- Operating System: macOS 

https://github.com/status-im/status-desktop/assets/155960867/0b9b5724-20d1-4292-9a91-064019dd0d43

**Comment by anastasiyaig** [comment]
@jrainville @alexandraB99 do we have backend for this already or it is in todo?

**Comment by caybro** [comment]
CC @MishkaRogachev

**Comment by Michal-Status** [comment]
Issue is also present on the newest CI build - https://ci.status.im/job/status-desktop/job/systems/job/macos/job/aarch64/job/package/311/

**Comment by MishkaRogachev** [comment]
Confirmed, error is `ERR 2024-02-14 14:14:19.661+03:00 Error requesting profile showcase preferences topics="profile-service" tid=7630845 file=service.nim:179 msg="/Users/mikhailrogachev/Development/status/status-desktop2/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim(824, 10) `node.kind == JArray` : items() can not iterate a JsonNode of kind JNull"`
