### ISSUE TITLE
Wallet - cannot sort collectibles by date added

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13550]
# Bug Report

## Description

- Restored account with existing community collectibles via seed phrase
- Airdropped additional community tokens to the account
- Attempted to sort by date added but order does not change

https://github.com/status-im/status-desktop/assets/50769329/0e1d96cc-a001-4b47-8496-60c493496a0f

#### Expected behavior

Date added sorts collectibles by when they were added to the account

#### Actual behavior

Sorting by date added does nothing

### Additional Information

- Status desktop version: 2.27 RC1
- Operating System: Mac

**Comment by caybro** [comment]
@dlipicar you closed this as completed via https://github.com/status-im/status-desktop/issues/12942 ? What's missing here?
