### ISSUE TITLE
Links pasted from "copy channel link" do not navigate directly to channel

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13553]
# Bug Report

## Description

Copy link to channel from menu
Pasted link to channel in a different channel
Clicking on link does nothing

Copy link to channel from menu
Pasted link to channel in a 1-1 chat
Clicking on link goes to community, but not the channel

https://github.com/status-im/status-desktop/assets/50769329/ade952ae-5d32-4350-9d31-5b46fab84eb8

#### Expected behavior

Links from "copy channel link" option go directly to selected channel.

### Additional Information

- Status desktop version: 2.27R1
- Operating System: Mac

**Comment by jrainville** [comment]
I don't think this is a blocker for the RC, so I'll move it to 2.28

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone

**Comment by jrainville** [comment]
Couldn't be completed in 2.28. Moved to 2.29
