### ISSUE TITLE
Unable to open profile link variations in browser

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13555]
# Bug Report

## Description

Assuming the link formats are correct:
- https://status.app/u#{ens-name}
- https://status.app/u#{chat-key}

An error is shown when visiting the profile links in a browser.

![image](https://github.com/status-im/status-desktop/assets/50769329/ca8f59b5-5fc7-4642-b953-2ace2a3ff4fa)

#### Expected behavior

It is possible to navigate to the app after visiting the links in the browser.

### Additional Information

- Status desktop version: 2.27R1
- Operating System: Mac

**Comment by caybro** [comment]
How do you "visit" those links? BY clicking them in the chat?

**Comment by glitchminer** [comment]
The URLs are manually constructed/typed, the current tests are a bit old but based on URLs specified in this spec: https://github.com/vacp2p/rfc/blob/ac394e18866d02883e27158b7a64513ab22fe188/content/docs/rfcs/60/README.md
Despite it being draft, it has been around a long time - see https://github.com/status-im/specs/pull/159

It is possible they are out of scope now, especially since the changes to the default profile URL.

**Comment by caybro** [comment]
> The URLs are manually constructed/typed, the current tests are a bit old but based on URLs specified here: https://github.com/vacp2p/rfc/blob/ac394e18866d02883e27158b7a64513ab22fe188/content/docs/rfcs/60/README.md Despite it being draft, it has been around a long time - see [status-im/specs#159](https://github.com/status-im/specs/pull/159)
> 
> It is possible they are out of scope now, especially since the changes to the default profile URL.

I see... you can use this PR and either scan the QR code, or copy the "Profile link"; these do work fine

**Comment by glitchminer** [comment]
Yup, regular profile link is fine. This issue is only for the other link formats in the web app.
The behaviour of the same links sent inside the desktop app were tested separately.

**Comment by jrainville** [comment]
This is a website issue. Either they no longer support that format, or they forgot to support it. We should ask them and/or move this issue to their repo.

**Comment by jrainville** [comment]
@prichodko @felicio do we still want to support that link format (`https://status.app/u#{chat-key}`), and if so, could you take that issue on your repo. I think it's  not working on the website right now.

**Comment by felicio** [comment]
@jrainville

> do we still want to support that link format

I'd say yes, even though no platform of ours should generate it.

More info:

> 12/14/2023 5:01 PM
> Hello, in short I'd say yes.
> 
> I left this format in the spec so there'd be a less complex way that'd be straightforward and ready to fallback to, should
> 
> - today's solution not prove itself
> - Waku connection and info fetching become near-instant
> - or IPNS, or Codex replace the encoding
> 
> Of course, others might disagree.
>
> – https://discord.com/channels/@me/1151896186538692700/1184767192970039347

> I think it's not working on the website right now.

That was because of the change in fleets which has now been resolved. And same would happen if the updates were no longer pushed to the network. However, I opened https://github.com/status-im/status-website/issues/702 for more descriptive errors.

**Comment by jrainville** [comment]
Closing this as it was a fleet issue and it was resolved. I tried with my own and it works 
https://status.app/u#zQ3shrfWiK6B4CSAPZGSPTegPyutywaA8BGr2FQqM5zFT7Dak
![image](https://github.com/status-im/status-desktop/assets/11926403/26cca479-b703-4d2c-a2ca-53bc67cdf685)
