### ISSUE TITLE
Wallet - Token management - Hidden assets remain shown

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13551]
# Bug Report

## Description

Hidden assets are not hidden from the send dialog

![image](https://github.com/status-im/status-desktop/assets/50769329/15119948-33f8-4f86-84b4-38da0d259518)

![image](https://github.com/status-im/status-desktop/assets/50769329/af13fc2a-4923-4290-aafc-e8fa0e359391)

#### Expected behavior

Hidden assets do not appear in the send dialog

#### Actual behavior

Hidden asset was still shown in the send dialog

### Additional Information

- Status desktop version: 2.27 RC1
- Operating System: Mac

**Comment by alaibe** [comment]
Closing because issue has not yet been developed:
https://github.com/status-im/status-desktop/issues/13178
