### ISSUE TITLE
Visual bug when a channel is unmuted after set period of time

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13559]
# Bug Report

## Description

After muting a channel for a set period of time and waiting until it unmutes itself it can be noticed that it still appears muted on the channel header in the chat window.

Please note that this is only a visual bug as the functionality itself works as intended.

## Steps to reproduce
Prereq: Join/Create a community.
1. Right click any channel in the community and click mute - select any time
2. Wait the specified time for the channel to unmute (i sped up the process by changing OS time)
3. Check the channel header in the channel chat window

#### Expected behavior
The crossed bell icon disappears and the channel header is no longer greyed-out.
#### Actual behavior
The crossed bell icon is still visible, the header is greyed-out.
### Additional Information
<img width="869" alt="Screenshot 2024-02-14 at 11 21 23" src="https://github.com/status-im/status-desktop/assets/52439419/113e2a33-bcab-4399-a0ac-8a1466b02cf7">

- Status desktop version: 2.27_rc1
- Operating System: macOS

**Comment by jrainville** [comment]
I moved this from 2.27RC to 2.28 as it is not a blocker.

FYI @alexandraB99 I also changed the team to the UI team as the backend seems to work considering it does change on the left bar.

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone
