### ISSUE TITLE
Communities: tokenOwner is present in the list of collectibles when adding a permission

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13561]
### Description

<img width="1512" alt="Screenshot 2024-02-14 at 13 03 34" src="https://github.com/status-im/status-desktop/assets/82375995/fc71c811-069b-4d6b-88ba-e341d1daeb4a">

I think we should not display tokenOwner in this list. Not sure if thats UI issue or backend

**Comment by jrainville** [comment]
I think it might be backend. Either way, we can fix. It's probably simple
