### ISSUE TITLE
[Profile] Contact details' `largeImage` is always empty

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13563]
# Bug Report

Profile:
![image](https://github.com/status-im/status-desktop/assets/5377645/94767fed-c898-4623-8bf9-f2b37c8d8ff2)

Chat:
![image](https://github.com/status-im/status-desktop/assets/5377645/6da4228d-0c41-4325-9f6a-172d424159a4)

## Description
~~Looks like a regression from https://github.com/status-im/status-desktop/pull/13197 ; `getContactDetailsAsJson.largeImage`~~ (and maybe other image related fields) always returns an empty string

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
CC @jrainville @kounkou

**Comment by kounkou** [comment]
> CC @jrainville @kounkou

Thanks for creating the issue 😃 
I will have a look and come back with a thorough analysis on this ticket.
To be honest, I doubt this would be a `regression` from #13197 simply because the solution provided is a silent parameter added to images. Is it okay to process it in next iteration @jrainville which I believe is Feb 26th ?

**Comment by caybro** [comment]
> > CC @jrainville @kounkou
> 
> Thanks for creating the issue @caybro I will have a look and come back with a thorough analysis on this ticket.
> 
> ### EDIT
> This is interesting, from beginning this analysis just to get more context on the issue, it seems like the contact service is giving me this input (these output will be outdated at the time you read this, but putting the screenshot for explanation of what I observed) :
> 
> (name: "phoenix-2", optionalName: "", image: "https://Localhost:39763/contactImages?imageName=thumbnail&publicKey=0x047c8052016065a8d04282a890090584d84344473337b9c888fc215888b532c43b9863d3593a4d8c3dca4b789335ea094aa6fd41386b4678f662f95e11091fcda9", largeImage: "https://Localhost:39763/contactImages?imageName=large&publicKey=0x047c8052016065a8d04282a890090584d84344473337b9c888fc215888b532c43b9863d3593a4d8c3dca4b789335ea094aa6fd41386b4678f662f95e11091fcda9")
> 
> thumbnail image :
> 
> ![Image](https://private-user-images.githubusercontent.com/2589171/305885687-949ad9da-4a12-4ff2-82a0-043d49224e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzUyMDQsIm5iZiI6MTcwODMzNDkwNCwicGF0aCI6Ii8yNTg5MTcxLzMwNTg4NTY4Ny05NDlhZDlkYS00YTEyLTRmZjItODJhMC0wNDNkNDkyMjRlMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDkyODI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjJiMjVlZDQ3YzY5NzMyMGUxYjAwZjYwMzhjMjE3ZDkwNjAxZDAzNTU2ZTIzNjAxZjc4MzljMjZjMjFlMDM4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ED2XsXXvH9a7adSquVxtc7bd6i-ls6m20Nb3hPbxOJ0)
> 
> large image :
> 
> ![Image](https://private-user-images.githubusercontent.com/2589171/305886355-ba5e7392-15fe-4d9b-9457-25923807b151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzUyMDQsIm5iZiI6MTcwODMzNDkwNCwicGF0aCI6Ii8yNTg5MTcxLzMwNTg4NjM1NS1iYTVlNzM5Mi0xNWZlLTRkOWItOTQ1Ny0yNTkyMzgwN2IxNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDkyODI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQxYzc4NTU1YzU0MjE4OTkxNDM4MTBjMWE0OThiNWNlMDU1ZWEwZDkxMjhjNDg1YzcwYTU3NzhjNzY5NjUwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-FpkUM_Nvemu74hkXvrP6RLLicsLfcpEQ993x2dIcZo)
> 
> So this means that for some reason, since inception, the `large` image isn't available for display. I tried using the thumbnail image instead of the faulty large image generated and everything works perfect. So fixing the why the large image is wrongly generated is probably the path towards fixing this issue.

Yeah good analysis; I also noticed the small image is fine (like found in ProfileContextMenu)

**Comment by kounkou** [comment]
This issue seems deeper than I had thought, indeed I can see that the malformed image is root cause is not even in the service, but it goes all the way up to the status-go . So I am still currently investigating in status-go to understand why we generate an  invalid image. By invalid I mean that the rendered image in a browser show all pixels in white.

**Comment by caybro** [comment]
> FYI
> 
> The current code contained a bug where a 1:1 chat is incorrectly assigned a context of "Public chat." According to the existing logic:
> 
> > When the context is 'public-chat', only the 'thumbnail' IdentityImage is attached.
> > When the context is 'private-chat', all IdentityImages are attached.
> 
> As a consequence, messages with the ChatIdentity have only one image (thumbnail), leading to the large image being consistently empty on the client receiver side.
> 
> Above PR corrects this behavior by ensuring that 1:1 chats are correctly assigned the 'private-chat' context, allowing all IdentityImages to be attached to messages, thus resolving the issue of the large image being empty.

Great thanks! I'm reopening the bug though as the fix landed in status-go only so far

**Comment by caybro** [comment]
This is now fixed in master
