### ISSUE TITLE
Avatar not synced during sync. After logging out avatar is synced properly.

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13568]
# Bug Report

## Description

When account is synced to another device, the avatar is not synced and instead reverts to the default one after the user logs into the account. During sync correct avatar is displayed. After logging out and logging in again, the avatar is synced properly. 

## Steps to reproduce

1. Log into an account
2. Set an avatar for that account
3. Go to setting -> syncing
4. Generate a sync code and copy it
5. Open another instance of the app without closing the first one
6. Start adding an existing Status user with sync code
7. Log into the synced account

#### Expected behavior
Avatar is synced

#### Actual behavior
Avatar is not synced

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/ 
- Operating System: macOS

Initial sync:
https://github.com/status-im/status-desktop/assets/155960867/b1d24137-402f-460c-86b3-9ffa2e68b763

Logging into synced account after restarting the app:
https://github.com/status-im/status-desktop/assets/155960867/fb03cdab-1e7b-4d7b-8c8e-bdc7cbe69855

**Comment by jrainville** [comment]
It seems like it got fixed. Closing ![Image](https://github.com/user-attachments/assets/bf0d86a3-1444-403b-be1f-9fb42180512c)
