### ISSUE TITLE
Syncing: Difference in decimal places in wallet between synced devices

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13574]
# Bug Report

## Description
After performing sync between devices i noticed that decimal places in wallet are different for each device. 
Main device has 5 decimal points.
The synced one has 8 decimal points.

## Steps to reproduce

1. Log in on one device
2. Sync another device with the main account
3. Check decimal points in wallet for e.g. ETH

#### Expected behavior
There should be no difference.
#### Actual behavior
Different decimal places between synced devices
### Additional Information
Main device:
<img width="175" alt="Screenshot_2024-02-15_at_12 08 03" src="https://github.com/status-im/status-desktop/assets/52439419/264b8322-a663-4861-abf2-f2f6f0adf875">

Synced device:
<img width="236" alt="Zrzut_ekranu_2024-02-15_o_12 05 49" src="https://github.com/status-im/status-desktop/assets/52439419/28cdb8f6-97eb-4f94-97e0-e14be88e3c50">

- Status desktop version: 2.27-rc1
- Operating System: macOS Sonoma on both devices

**Comment by dlipicar** [comment]
Hmm until a price cache is available (should only be the case the first time the user logs into status with a given account), the default number of decimals (8) is shown for assets. The number of decimals gets refreshed on startup and every 1h after that, so eventually they'll be shown on the new device with the correct format. Perhaps we can add one more refresh after the first time prices are fetched to avoid this initial 1h wait? @alaibe

**Comment by alaibe** [comment]
@dlipicar why do u think reducing time will change things, the config should have been fetch?

**Comment by dlipicar** [comment]
@alaibe 
Sorry, I had to re-check the logic a little bit.

The wrong number of digits will only be shown the first time balances are shown. After the first refresh, we should already have populated `price_cache` and `currency_format_cache` tables and an up-to-date copy of the cache on the client side.

@lukaszso could you confirm if this only happened for about 10 minutes after you started the app or if it persisted after that?
