### ISSUE TITLE
Syncing: Collectibles on a synced device are shown in different order

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13577]
# Bug Report

## Description

After syncing a new device with an account that has collectibles i noticed that they are shown in different order to each other. The sorting is set to `Date Added ↓` on both devices.
## Steps to reproduce
1. Log in to account with Collectibles in wallet
2. Sync a new device
3. Check collectibles order in wallet

#### Expected behavior
Collectibles are shown in the same order on both devices.
#### Actual behavior
The order is different on each device.
### Additional Information
Main device:
https://github.com/status-im/status-desktop/assets/52439419/5e694677-5665-42da-b2dd-7dd8b6f51b19

Synced device:
https://github.com/status-im/status-desktop/assets/52439419/a343bf86-1f8c-4e8b-b5da-6f935e76bb43

- Status desktop version: 2.27-rc1
- Operating System: macOS Sonoma on both devices

**Comment by caybro** [comment]
CC @dlipicar

**Comment by dlipicar** [comment]
The sort by date fix has not been cherrypicked to the release branch yet: https://github.com/status-im/status-desktop/pull/13583
@alaibe I'm not fully sure what gets transferred during the sync process... Does it include the full wallet DB? Only some tables? Or only the account stuff and we expect the new device to fetch activity, balances and owned collectibles on its own?
To get the same sort order the user needs to have the collectibles and the transfer tables.

**Comment by alaibe** [comment]
@dlipicar collectibles and transfer are not sync cause they are re-queried.
however the order config itself is sync

**Comment by dlipicar** [comment]
Only the custom order is sync'ed if I'm not mistaken.
The `Sort By Date` order, which was used according to the bug description, won't be correct until both the collectibles list and the corresponding transfers are detected, which might take a while. So I guess it's expected behavior? Perhaps we need to somehow notify the user that the Transfer date was not determined for some entries to avoid confusion.
