### ISSUE TITLE
Pending contact requests not synced properly 

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13578]
# Bug Report

## Description

When syncing an account that has received requests that are still pending, they are not synced to the new device. Sometimes activity centre shows requests that are not there on the previous device. But the ones that are currently pending are not shown anywhere.

## Steps to reproduce

1. Log into an account that has pending contact requests that it has received
2. Sync this account to another device

#### Expected behavior
All contact requests are synced properly
#### Actual behavior
Contact requests that are pending are synced and visible on the new device. Sometimes requests that are not pending are shown as pending in the activity centre.

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/
- Operating System: macOS

Syncing process:
https://github.com/status-im/status-desktop/assets/155960867/abb4e4ae-46e4-4f93-ab5f-611b796d4cfd

Comparison of requests visible in settings on both devices:
https://github.com/status-im/status-desktop/assets/155960867/b5d8fe59-3d36-4fd0-9bdd-04e59fbcc78e

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one
