### ISSUE TITLE
Having a pending ID request makes it impossible to mark that contact as untrustworthy 

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13581]
# Bug Report

## Description

When we have a pending ID verification request from a contact, we cannot mark that contact as untrustworthy while the request is still pending. This can be confusing for the user, as they are not informed why the functionality does not work. Either it should be possible or the user should be informed why it's not. Current behaviour of the app can make it seem like the functionality just does not work.

## Steps to reproduce

1. Log into user1 and user2 
2. Add both accounts to each other's contacts
3. Send an identity verification request from user2 to user1
4. As user1 click on "mark as untrustworthy" on user2 while the request is still pending

#### Expected behavior
It is possible to mark user as untrustworthy while the request is pending, or the user is informed why it is not possible.
#### Actual behavior
Marking as untrustworthy is impossible and the user is not informed why
### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/
- Operating System: macOS

https://github.com/status-im/status-desktop/assets/155960867/02027813-3482-47fb-9d7e-8c2bbdbb6385

**Comment by Michal-Status** [comment]
@jrainville  you're right, I posted a video documenting a different issue. That's what I get for naming all of my recordings "screen recording". 

Now I have posted the correct video.

**Comment by jrainville** [comment]
Ah, looking at the video, it does seem more like a bug, but I'll still wait to see what designers say should be the behaviour.

**Comment by caybro** [comment]
I'll take this as we do have designs for these flows and I'll be going thru them very soon

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone

**Comment by caybro** [comment]
This is currently working fine in master:

[Záznam obrazovky z 2024-04-10 16-54-26.webm](https://github.com/status-im/status-desktop/assets/5377645/9795199b-34fa-44e8-b1d0-b67908cd422f)

Please check again @Michal-Status and if the action is still failing, please reopen and put it on the `messenger-team`, there's nothing else to do on the UI side at this point :)
