### ISSUE TITLE
Sepolia ENS/Sticker + Fix toggle

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13589]
* Add sepolia contract for ens and stickers
* Fix the toggle when enabling sepolia

**Comment by anastasiyaig** [comment]
Issues found:

https://github.com/status-im/status-desktop/issues/13672
https://github.com/status-im/status-desktop/issues/13698
https://github.com/status-im/status-desktop/issues/13697
https://github.com/status-im/status-desktop/issues/13696
