### ISSUE TITLE
Ban/unban/kicking pending state button disappearing after TM or admin actions when the control node is offline

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#13596]
### Description

If an admin or TM bans/unbans/kicks member when the control node is offline - the pending state of ban/unban/kick must be visible for all admins and TM

https://github.com/status-im/status-desktop/assets/117639195/d857441a-5399-492f-9b4e-3aa579aeefcd

Split task from https://github.com/status-im/status-desktop/issues/13034

**Comment by jrainville** [comment]
What disappears, the buttons or the user from the list? @mprakhov

**Comment by mprakhov** [comment]
updated the description
