### ISSUE TITLE
[Profile flow] Validate nickname on edit

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13591]
### Description

[Design](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/👤-Profile-%7C-Desktop?type=design&node-id=2460-197035&mode=design&t=Ls4I0tjTs64OVgkM-0)

Add nickname validation in the add/edit contact nickname popup. The `Add nickname`/`Edit nickname` button should be disabled if the validation fails.

<img width="1131" alt="Screenshot 2024-02-16 at 10 58 10" src="https://github.com/status-im/status-desktop/assets/47811206/e9eb0f4b-0562-4e7a-9628-afccf499976f">

**Comment by caybro** [comment]
Do we really want to add some validation here? This is for our own eyes only; the only reason I can think of is syncing between devices (so that both mobile and desktop have the same e.g. length?)

**Comment by alexjba** [comment]
> Do we really want to add some validation here? This is for our own eyes only; the only reason I can think of is syncing between devices (so that both mobile and desktop have the same e.g. length?)

I see no reason to validate it. Even if it's synced.. But I might miss some subtile details here.

@benjthayer What's the reasoning behind this validation?

**Comment by benjthayer** [comment]
> > Do we really want to add some validation here? This is for our own eyes only; the only reason I can think of is syncing between devices (so that both mobile and desktop have the same e.g. length?)
> 
> I see no reason to validate it. Even if it's synced.. But I might miss some subtile details here.
> 
> @benjthayer What's the reasoning behind this validation?

This was added more for consistency with those shown for display names - @John-44 any thoughts?

**Comment by John-44** [comment]
> > > Do we really want to add some validation here? This is for our own eyes only; the only reason I can think of is syncing between devices (so that both mobile and desktop have the same e.g. length?)
> > 
> > 
> > I see no reason to validate it. Even if it's synced.. But I might miss some subtile details here.
> > @benjthayer What's the reasoning behind this validation?
> 
> This was added more for consistency with those shown for display names - @John-44 any thoughts?

'Can't be longer than 20 characters' is must-have and important.  'Can't be less than 5 characters' (or at least 1 character) is also must-have and important.

The rest of the validations are good for consistency with profile names, but if challenging to implement could be split out into a seperate issue to be worked on later (the others other than the two I've mentioned here are low priority).

**Comment by caybro** [comment]
Got some local fixes for this too already, taking this
