### ISSUE TITLE
[StatusQ/WritableModel]: Add option allowing to remove items always when removed in source

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#13603]
## Description

In many scenarios it may be desired to always remove item (instead of moving to cache), whenever item is removed from the source model.

For example in profile showcase settings - we want to remove community when the user is kicked off, even if we already have some dirty state related to that entry.

It could be a boolean property flag, changing the present behavior when needed.

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone, however we might move this back for the stabilization period

**Comment by caybro** [comment]
> moved to 2.29 due to lack of space in this milestone, however we might move this back for the stabilization period

This is definitely needed for the whole Profile Showcase story
