### ISSUE TITLE
[Profile Showcase - Profile Popup] Add `Web` tab

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13606]
### Description

[Design](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-42949&mode=dev)

![Profile(1)](https://github.com/status-im/status-desktop/assets/31625338/0f2f1d20-ec21-49ac-9988-af0cc7f05de9)

**Comment by MishkaRogachev** [comment]
This UI should use new backend: https://github.com/status-im/status-go/pull/4775
