### ISSUE TITLE
SendModal:  Balances per chain looks weird

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#13620]
### Description

Please refer to screenshot below the scroll bar in bllue overlaps the items themselves. @benjthayer needs to be looked from a design perspective as to how we can solve this?

![image](https://github.com/status-im/status-desktop/assets/60327365/48209bd2-0937-47cd-8722-210eb2a5be5a)

**Comment by benjthayer** [comment]
Thanks @Khushboo-dev-cpp I think we may be missing this state which would prevent us from requiring horizontal scroll here:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=13877-383514&mode=design&t=iECJIIPiwRwlmxGd-4

<img width="430" alt="Screenshot 2024-02-19 at 11 05 11 AM" src="https://github.com/status-im/status-desktop/assets/110033914/80d7c780-a190-458c-8b87-a9ab464a9062">

When we reach the point where we run out of horizontal space, any tokens that cannot be shown in full should just be represented by the chain icon

**Comment by noeliaSD** [comment]
@caybro just a ping here to see if this task is conflicting with your existing assets list refactoring!

**Comment by caybro** [comment]
> @caybro just a ping here to see if this task is conflicting with your existing assets list refactoring!

Not at all but as the component will be soon gone, I wonder if it makes sense spending time on fixing it

**Comment by noeliaSD** [comment]
> > @caybro just a ping here to see if this task is conflicting with your existing assets list refactoring!
> 
> Not at all but as the component will be soon gone, I wonder if it makes sense spending time on fixing it

That's, indeed, my question! :)

cc: @saledjenic probably it's better to keep it open and linked with the refactor task that @caybro is doing but don't add more effort in solving it since it will be probably solved by the refactor!

**Comment by caybro** [comment]
@belalshehab ok, so if you start working on it, pls make sure you do it in this component as well please: `TokenSelectorAssetDelegate.qml`, thanks :)
