### ISSUE TITLE
Profile settings -> Identity : Addition of validation to bio field

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13623]
Currently, the `Bio` field in `Profile` Settings does not have any validation meaning the user can add any character / emoji they desire.

It was recently confirmed that this field should allow only ASCII characters, not UTF-8 and should support emojis.

@alexjba had a couple of questions in regards to this so creating an issue for us to discuss / track decisions

<img width="448" alt="Screenshot 2024-02-19 at 11 48 08 AM" src="https://github.com/status-im/status-desktop/assets/110033914/a05ae65e-15a6-4912-b409-7d1e933da955">

Figma
https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-27368&mode=design&t=zk0Rc4XSIlXFhE07-4

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one

**Comment by noeliaSD** [comment]
A good exercise could be also adding the `Identity Tab` into **storybook** if it's not there yet!
