### ISSUE TITLE
Permission intro view appears before first permission creation

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#13621]
# Bug Report

After clicking add permission - before view with created permissions permission intro view appears for a little while (but still noticeable) 

1. Create new community
2. Click Manage community/Permissions/Add new permission
3. Create any permission, click button Create permission

https://github.com/status-im/status-desktop/assets/141633821/04a71b6d-0e7d-405b-9483-496ae1d234b2
(0:12)

View with created permission appears right away

Before displaying view with created permissions, intro view appears for a very little while (if Become admin was chosen - then all good, but for any other options - there is a bug)

### Additional Information

- Status desktop version: the latest master build
- Operating System: Mac OS Ventura 13.5
- Link to autotests run - https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/215/allure/#suites/ea35bd66d78deeec4a096260dd1d8144/f3ff827840d43ec8/ (tests failed on that moment when intro view appears)

**Comment by anastasiyaig** [comment]
@caybro there is a video :D

**Comment by Valentina1133** [comment]
> @Valentina1133 would be nice to attach a small video

There is a link to the video in bug report description attached
 https://github.com/status-im/status-desktop/assets/141633821/04a71b6d-0e7d-405b-9483-496ae1d234b2

**Comment by caybro** [comment]
Ah, I see :) Kinda missed the link, sorry

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one

**Comment by Valentina1133** [comment]
Closing it, bug disappeared, checked it on the latest master build
