### ISSUE TITLE
Wallet -> Cant delete generated account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13628]
### Description

Can't delete some account that was recovered along with my seed phrase. Can reproduce in master and release.

```
ERR 2024-02-19 17:28:11.638+03:00 error:                                     topics="wallet-account-service" tid=17296535 file=service_account.nim:498 procName=deleteAccount errName=RpcException errDesription="\nstatus-go error [methodName:accounts_deleteAccount, code:-32000, message:no key for given address or file ]\n"
```

https://github.com/status-im/status-desktop/assets/82375995/5d7b71c4-9aa8-4759-972d-52fd6acce1f8

**Comment by anastasiyaig** [comment]
@alaibe something to do with waku  restore maybe?

**Comment by Khushboo-dev-cpp** [comment]
will be fixed under https://github.com/status-im/status-go/pull/4850
