### ISSUE TITLE
Wallet - Sort collectible by date does not order by date

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13630]
# Bug Report

## Description

The expected date order for the account per optimism goreli explorer: https://goerli-optimism.etherscan.io/address/0x01fbd5ba36b4a609a3a96a193d4608b9eb91984e#tokentxnsErc721

![image](https://github.com/status-im/status-desktop/assets/50769329/9eeae87c-aebf-47ca-974b-741571fe0556)

The actual order in the collectibles view:
![image](https://github.com/status-im/status-desktop/assets/50769329/5ca4dd29-4c35-4dca-acd6-e7e888834e84)

## Steps to reproduce

- Launch 2.27 RC2
- Restore account from seed phrase.
- Enable testnet mode
- Enable manage communities in testnet mode
- View collectibles and sort

### Additional Information

- Status desktop version: 2.27 RC2
- Operating System: Mac

**Comment by dlipicar** [comment]
@glitchminer note about sorting by date:
The Tx Timestamp value depends on the transfer detection module, which is a completely independent process. If the transfer doesn't show up in the Activity tab, the collectible will for sure not have the proper timestamp, so the sorting order for these won't be correct. Eventually, when the Tx gets detected, it should get re-sorted accordingly.

Could you verify if that's the case? If you wait long enough and the Activity entries show up, the order should be correct.

Perhaps it's something to discuss with Design? Somehow indicate that the Tx Timestamp for some of the collectibles is not ready yet.
