### ISSUE TITLE
Airdrop community collectible amount popup not showing up

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#13633]
# Bug Report

## Description

When selecting community collectibles for airdrop the amount popup is not showing up.

## Steps to reproduce

* Go to community
* Aidrop view
* Select collectible

#### Expected behavior

Amount popup is shows up (like on first collectible)

#### Actual behavior

Popup is not showing up

### Additional Information

- Status desktop version: master
- Operating System: Windows

https://github.com/status-im/status-desktop/assets/11396062/658a2f25-3749-43c9-827f-72510f5412a4

**Comment by caybro** [comment]
Any warnings there? Looks like the popup gets destroyed the first time it's closed. You could also try to play around with it in Storybook

**Comment by jrainville** [comment]
@anastasiyaig can you test this on your Windows machine?

**Comment by anastasiyaig** [comment]
I tried to reproduce that today but could not, it seem to be working for me :(

**Comment by alexandraB99** [comment]
@Cuteivist can you please re-test and close?

**Comment by alexjba** [comment]
The amount selector should not show up if the collectible is unique. Is it really a collectible with infinite supply? Maybe the supply amount in the collectible dropdown is wrong and it's not really infinite.

**Comment by noeliaSD** [comment]
cc: @Cuteivist reminder! ;)

**Comment by noeliaSD** [comment]
Moved to next milestone due to team capacity and priorities.
