### ISSUE TITLE
Token holder username shows as a weird address (`0x0000...123`)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13643]
# Bug Report

## Description

We were testing the TM airdrop to a non-member of the community. Nastya was the owner. She sent the TM token to me via my wallet address.
It did work in sending it, however, in her token holder list, I appeared as a weird address. Something like `0x0000...123`.

We're not sure why. We were using Arbitrum , so maybe there's that. Also, I wasn't in the community yet, so it's probably related.

## Steps to reproduce

0. Have someone with Arbitrum funds create a community and mint Owner token and TM token
1. The owner airdrops a TM token to someone **not** in the community yet
2. That person receives it correctly

Result: the token holder list shows a weird address

#### Expected behavior

It should show the display name of the user. If we can't show that since the user is not in the community, we should at least show the wallet address instead of that weird address.

#### Actual behavior

Holder shows a weird address starting with `0x000`

### Additional Information

- Status desktop version: 2.27 RC2
- Operating System: Mac

**Comment by jrainville** [comment]
@anastasiyaig do you have a screenshot of what the holder looked like?

**Comment by anastasiyaig** [comment]
yep, there it is
<img width="1822" alt="Screenshot 2024-02-20 at 17 25 21" src="https://github.com/status-im/status-desktop/assets/82375995/bc92232e-13b7-4e3e-a5bc-d117064865ba">

**Comment by jrainville** [comment]
This will be fixed by https://github.com/status-im/status-desktop/issues/12065 so it's kind of a duplicate

**Comment by kounkou** [comment]
> Expected behavior
It should show the display name of the user. If we can't show that since the user is not in the community, we should at least show the wallet address instead of that weird address.

This is correct, we should show the Wallet address in this case, and this will be handled in the mentioned ticket #12065
