### ISSUE TITLE
CPU usage is too high and fans go crazy on 2.27RC2

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13641]
# Bug Report

## Description

The CPU stays at around 10% for me when the app is opened and not doing anything (that's a lot of me as my laptop is very powerful).
Also, the fans go crazy because of it.
Even with a new account it does it

## Steps to reproduce

1. Open the app
2. Wait a little
VROOOOOOOOOM

#### Expected behavior

Almost no CPU usage when the app is idle

#### Actual behavior

CPU goes high for no reason

### Additional Information

- Status desktop version: 2.27 RC2
- Operating System: Ubuntu 20 (happens on Mac too)

**Comment by caybro** [comment]
Yup, I quickly ran hotspot and here's the culprit :) The CPU here is idling about 20% all the time

![image](https://github.com/status-im/status-desktop/assets/5377645/18e2d2e7-b542-4c45-9bd9-b1480c0a928c)

Something for @richard-ramos ? Seems to be doing lots of nothing inside waku/go-discover nodes

**Comment by richard-ramos** [comment]
Let's take a look!

**Comment by jrainville** [comment]
Sadly it didn't fix it.

Video for proof:


https://github.com/status-im/status-desktop/assets/11926403/3796f817-9be5-4635-aa3e-b6519eba10d9

**Comment by jrainville** [comment]
Latest commit did fix it!

**Comment by richard-ramos** [comment]
Cool! 
Let's wait for https://github.com/waku-org/go-waku/pull/1038 to be approved! :)

**Comment by richard-ramos** [comment]
Ah it's already approved!

**Comment by jrainville** [comment]
> Ah it's already approved!

I'll approve everything!!!

**Comment by richard-ramos** [comment]
We need @chaitanyaprem 's approval too because he's a code owner!
