### ISSUE TITLE
Cropped pill at the bottom of the token card

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13645]
# Bug Report

## Description

Small UI issue. There is some sort of UI pill element that is cropped and not visible. Hovering it shows a tooltip.

![image](https://github.com/status-im/status-desktop/assets/11926403/e94e2671-3057-4c17-9cb9-cf2c4294f66f)

## Steps to reproduce

1. Mint Owner and TM tokens in  a community
2. Go to Tokens screen
3. See the weird UI element

#### Expected behavior

UI element shows correctly

#### Actual behavior

Pill is cropped (sometimes it's visible but it's a small circle only, so it's probably missing test inside)

### Additional Information

- Status desktop version: 2.27RC2
- Operating System: Ubuntu 20

**Comment by jrainville** [comment]
@alexandraB99 you can choose the milestone. This is a pretty minor issue

**Comment by alexandraB99** [comment]
Closing as duplicate https://github.com/status-im/status-desktop/issues/13220
