### ISSUE TITLE
Add a Wallet reload button

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13652]
### Description

Currently, it takes 10 minutes for the balances and tokens to be updated in the wallet. It's a bit frustrating as a dev or a user. The other way is to restart the app.

We need a button in the wallet that does the reload manually.

We just need maybe to throttle to make sure a user doesn't press the button a hundred times and we do a hundred requests haha.

Also, once the button is pressed, the 10 minute timeout should probably be reset to the start. 

### Acceptance Criteria

- There is a button in the wallet that manually reloads balances
- That button is throttled in some way to make sure users don't spam the services

**Comment by jrainville** [comment]
@alaibe feel free top remove if this is a duplicate. Also you can re-prioritize.

**Comment by alaibe** [comment]
@benjthayer is it something you could look at to design?

**Comment by benjthayer** [comment]
> @benjthayer is it something you could look at to design?

Hey @alaibe I'm working on this as part of the WalletConnect work which is currently under way so shouldn't be too long. Will update as soon as the design is finalised.

**Comment by saledjenic** [comment]
@benjthayer I move this to 2.30, hopefully you will have time to provide the design by then.

**Comment by benjthayer** [comment]
> @benjthayer I move this to 2.30, hopefully you will have time to provide the design by then.

Hey @saledjenic designs are done, I just need to review with design team - when signed off I'll post the designs here. Thanks!

**Comment by saledjenic** [comment]
Related issue https://github.com/status-im/status-desktop/issues/14738
