### ISSUE TITLE
Filtering Activity by Token freezes the app

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#13660]
# Bug Report

## Description

https://github.com/status-im/status-desktop/assets/11161531/3ae850f7-fd5d-41f8-8ff2-d5326ceaf70a

## Steps to reproduce

- Load some account with collectibles activity
- In the filter section, toggle on some collectible

Expected: Only activity related to the collectible is shown
Actual: Activity stays in loading state

- Toggle off the collectible filter

Expected: Full list of activity is shown
Actual: App freezes

### Additional Information

- Status desktop version: latest master (e46f6c311c90d6c7024af2f946a7984c19214823)
- Operating System: macOS Sonoma 14.3

**Comment by dlipicar** [comment]
Seems to also happen with ERC20 tokens

**Comment by anastasiyaig** [comment]
i tried that on sepolia and it worked to me just fine.. Do you have any other insights @dlipicar ?

**Comment by anastasiyaig** [comment]
https://github.com/status-im/status-desktop/assets/82375995/66a01d84-3ebb-41d0-9e0a-6645bda3ebe2

**Comment by dlipicar** [comment]
> Screen.Recording.2024-02-21.at.18.47.41.mov

interesting! Gonna check if my DB is corrupted or something
