### ISSUE TITLE
Filtering TXs history issue

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#13663]
When the user is filtering TXs by an address won't see any results in some scenarios even TXs with such an address appear in the list when there is no filtering.

What else can be seen in this video:
- the address the user added to saved addresses is not displayed in the "Recent" tab of "Counterparty" of the filter popup menu
- after the user added the address to saved addresses, it appeared in the"Saved" tab of "Counterparty", but still there is no address in the "Recent" tab
- another issue is, that when the user filters by some address selected from the "Recent" tab of "Counterparty", it will appear in the filtering line as an address, that's ok, but then if the user goes to details and saves that address to saved addresses, it remains in the filtering line as an address, not changed to saved address' name.

https://github.com/status-im/status-desktop/assets/86303051/3ea7ca71-ae97-4566-ba50-9c0157d288d8

**Comment by stefandunca** [comment]
@saledjenic the counterparty is interpreted as `recipient`. In the first screen I can't see transactions where the save address is the `recipient` (except for bridge), so it might be expected if you think you didn't have one.
Regarding bridge transaction, I'm looking into why is not shown.

**Comment by stefandunca** [comment]
Looking further into it it seems one of the problem is that [menu for saving from address](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12441-285548&mode=design&t=fZQ2v94AVzEhCTej-0) should not be available. I'm looking into fixing this first.
<img src="https://github.com/status-im/status-desktop/assets/47554641/354a9ab1-c766-4632-a4d5-8d75c0ac7567)" height="200">

**Comment by stefandunca** [comment]
For save address lookup for newly created saved addresses it seems the model is not mapped directly to the lookup and the lookup is done manually. I will continue searching for a simple fix to force refresh the query.

In the meantime I found and fixed other small issues in this draft https://github.com/status-im/status-desktop/pull/14069

**Comment by stefandunca** [comment]
> When the user is filtering TXs by an address won't see any results in some scenarios even TXs with such an address appear in the list when there is no filtering.

I can't reproduce the issue therefore I assume for now that there were not transaction to the selected address in the list.
