### ISSUE TITLE
Sepolia: Sticker market is empty

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13672]
# Bug Report

## Description

Stickers can be obtained for free or bought for STT from the sticker shop. The sticker shop is not available when user is on Sepolia network.

## Steps to reproduce

1. Log in
2. Switch testnet on
3. Go to Advanced settings and switch to Sepolia network
4. App will restart
5. Go to a chat 
6. Go to stickers
7. Click on "Get more stickers"

#### Expected behavior
Sticker shop opens and stickers can be obtained

#### Actual behavior
Sticker shop is empty

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/systems/job/macos/job/aarch64/job/package/326/
- Operating System: macOS

Recording and logs when on Sepolia:

https://github.com/status-im/status-desktop/assets/155960867/f51d31f0-7d04-4c83-80ce-1368eb216962

[app_20240221_192545.log](https://github.com/status-im/status-desktop/files/14363625/app_20240221_192545.log)

Recording and logs when NOT on Sepolia:

[app_20240221_192036.log](https://github.com/status-im/status-desktop/files/14363616/app_20240221_192036.log)

https://github.com/status-im/status-desktop/assets/155960867/49602731-dc24-43f1-92b1-cd521da3211b

**Comment by anastasiyaig** [comment]
@alaibe can you please check it out? Sticker market is empty on Sepolia

<img width="1512" alt="Screenshot 2024-02-22 at 09 13 27" src="https://github.com/status-im/status-desktop/assets/82375995/19d20345-c737-405a-993d-f727f466d64c">

**Comment by 3esmit** [comment]
Now I registered all same sticker packs available to sale on Mainnet, also on sepolia. 

Please, verify if anything appears now. If still not showing up, and also dont show in mainnet, would be a problem with IPFS pinning.

**Comment by 0x-r4bbit** [comment]
Thank you @3esmit !

**Comment by anastasiyaig** [comment]
@3esmit @0x-r4bbit 

thanks guys i am seeing stickers packs there. I am also seeing 2 other issues, i will address separately:

- cant get fees to purchase the stickers
- stickers do not recognize network changes . so if i were on mainnet and then switch to test net (sepolia) then sticker pack from mainnet is still shown wanting me to purchase with SNT
