### ISSUE TITLE
[Profile Showcase] Prepare base models data for accounts and communities according to needs

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13678]
### Description
Order in hidden section must always be the following (also after moving from in showcase to hidden, the order should be rearranged to the original order):

**- Communities**
The order they appear in the user's nav bar

**- Accounts**
The order they appear in the user's wallet

**Comment by iurimatias** [comment]
moved due to lack fo space in this milestone, but we may pick this up on the stabilization period if possible

**Comment by caybro** [comment]
Same here, crucial for the Profile Showcase feature scheduled for 2.28

**Comment by noeliaSD** [comment]
Discussed with @alexandraB99 , moved again into 2.28

**Comment by alexjba** [comment]
The account order is correct

**Comment by alexjba** [comment]
Communities order is correct as well!
