### ISSUE TITLE
Sepolia: can't get STT on sepolia network (using contract), transaction fails with Fail with Custom Error 'NotAuthorized ()'

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13674]
### Description

Transaction sample: https://sepolia.etherscan.io/tx/0x616aa249eabfeb6cf40ca733018204bd8c75bbaf1b72344ff8d19f269b8a95db

**Steps i did:**

1. go to https://sepolia.etherscan.io/address/0xe452027cdef746c7cd3db31cb700428b16cd8e51#writeContract
2. connect wallet
3. switch to seploia
4. go to Generate section of the contract
5. enter address 
6. enter amount
7. click write

**Comment by anastasiyaig** [comment]
@alaibe can you please check it out?

**Comment by 0x-r4bbit** [comment]
@anastasiyaig you need to call `generateTokens()` on the controller, not the STT contract itself: https://sepolia.etherscan.io/address/0x785e6c5af58FB26F4a0E43e0cF254af10EaEe0f1#writeContract

**Comment by anastasiyaig** [comment]
ah, sorry my bad.  I will try now, thanks @0x-r4bbit for hint!
