### ISSUE TITLE
feat(ProfileShowcase): Simplified NIM backend for profile showcase settings

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#13688]
## Description

This task is backend-side counterpart of https://github.com/status-im/status-desktop/issues/13498

Dirty state is agreed to be handled on the UI side so there is no need to maintain it on Nim side. This make the nim side much simpler.

Nim side should expose read-only models with following roles:

- key
- visibility
- position

For all considered entities:
- communities
- accounts
- collectibles
- assets

**Note**: probably it's also possible to skip `position` role and just assume the order in the model already reflects the desired order

The only exception is `Web` section which should provide all necessary information directly from the model and there is no visibility role.

Saving updated showcase settings should be done via single method taking js/json object of e.g. following structure:
```
{
  accounts: [ { id: <string>, visibility: <int> }],
  communities: [ { id: <string>, visibility: <int> }],
  assets: [ { id: <string>, visibility: <int> }],
  collectibles: [ { id: <string>, visibility: <int> }],
  web: [ { all necessary data here }]
}
```
**Note**: If for some reason it's necessary to provide more info to save method (e.g. bc on nim side it's unhandy to get some metadata), it can be also specified as a required field. It shouldn't be a problem on UI side to provide that info as it's freely available there.

**Comment by noeliaSD** [comment]
1 question, otherwise it's clear to me and I agree:
- Regarding the saving _json_ object, do we need to also consider the `Identity` tab information? At least from the UI pov, whenever a change in this tab is done, the user can continue doing changes in the rest of the tabs and then save all together.

**Comment by MishkaRogachev** [comment]
> 1 question, otherwise it's clear to me and I agree:
> 
> * Regarding the save _json_ object, do we need to also consider the `Identity` tab information? At least from the UI pov, whenever a change in this tab is done, the user can continue doing changes in the rest of the tabs and then save all together.

if `save` button is global for all profile data in new designs, then my opinion is yes, better to pass all the data in one call. Otherwise, i think nim will be involved into dirty state management

**Comment by alexjba** [comment]
> Nim side should expose read-only models with following roles:
> - key
> - visibility
> - position

These role names might be too generic. There is currently a limitation in the LeftJoinModel and we don't support role naming collision between showcase model and source model. The only role name that can be identical is the key role (the one we're considering for left join). One example would be `accounts`. The base model also has `position`. Would be nice to minimise the risk of breaking these components by adding identical role names in the base models.

My proposal here is to add a prefix:

- showcaseKey
- showcaseVisibility
- showcasePosition
