### ISSUE TITLE
UI feature request: improve code tags display

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1368]
using ``` for code or snippets of text looks quite ugly as it is currently

**Comment by jrainville** [comment]
I think @emizzle fixed this in this PR https://github.com/status-im/nim-status-client/pull/1329

**Comment by emizzle** [comment]
I changed the background colour to match the design, but didn’t go beyond that. I think a better improvement would be to add syntax highlighting.

**Comment by jrainville** [comment]
You fixed the weird space at the start as well no?

**Comment by iurimatias** [comment]
the weird leading spaces have been fixed, this task is about the code tags display itself, and how to improve it visually. we should discuss this with @simonricoo

**Comment by simonricoo** [comment]
Im mostly done with the UI of code tags, I will update you guys on todays call

**Comment by malik-aljabr** [comment]
hey simon, any chance you could post the design here? i hacked up a demo and im pretty confident that i can pull this PR off.

i built the demo using nim's builtin highlite package. It only supports `c`, `c++`, `java`, `nim`, `yaml` and `c#` (the devel branch also has support for `python`). the interface and "factory-like" iterator exposed by `nim` is not open to extension however, the iterator can be adapted to support other languages (or wait for nim to implement other languages internally)

when you post a code tags to status-go it will return a message to chatId with the line containing backticks killed and no remnants left of anything after the backticks
ie
\```nim
test
\```
cannot be used to specify the language to highlight as the first line will be deleted

my demo requires the user to enter a language in the first line
ie
\```
lang=nim
proc new*(): string =
  return "test"
\```

the following tags are easily highlightable 
```
String Literal, Keyword, Comment, 
FloatNumber, HexNumber, DecNumber, 
Operator, Preprocessor, Other, RegularExpression, Hyperlink
```
more info [https://nim-lang.org/docs/highlite.html](https://nim-lang.org/docs/highlite.html)

![2021-01-20-173322_940x671_scrot](https://user-images.githubusercontent.com/58890963/105197795-aab82d00-5b45-11eb-8972-e11cbbd0c67e.png)

**Comment by simonricoo** [comment]
The design is here, its not finished yet I plan to add some more interactions regarding text formation. https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4170%3A20

**Comment by malik-aljabr** [comment]
i actually wont be able to complete this. the conversion to a highlighted form is a pretty expensive and slow operation since the `highlite` package linearly retrieves one matching token at a time in a source language. i considered breaking up the work done in a couple of threads, however, the design of `Nim` requires that threads who want to read/write from the same heap data not access any data that will be collected by the gc. Meaning I wouldn't be able use the `highlite` package in a threaded environment anyways as it contains gc data.

**Comment by pinebit** [comment]
@iurimatias please clarify: do we need syntax highlighting or not?
if not, then I will simply adjust the style to match the design.
if yes, then it will take some time - need to investigate how to implement this better.

**Comment by iurimatias** [comment]
we do need it

**Comment by pinebit** [comment]
Blocked by https://github.com/status-im/status-desktop/issues/3270
