### ISSUE TITLE
[Profile Showcase] Prepare base model data for collectibles according to needs

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13680]
### Description

1. Order in hidden section must always be the following (also after moving from in showcase to hidden, the order should be rearranged to the original order):
   - The current order in All accounts (so it needs to take into account the tokens management section).

2. There are also some restrictions and not all the collectibles in the model should be displayed. The ones hidden in tokens managements must be also hidden here.

**Comment by iurimatias** [comment]
moved due to lack fo space in this milestone, but we may pick this up on the stabilization period if possible

**Comment by caybro** [comment]
A must for 2.28

**Comment by noeliaSD** [comment]
Discussed with @alexandraB99 and moved again to this cycle. However this task can become blocked easily bc it depends on the current implementation of the `Tokens Management` and probably, once we start analysing it, we see there's the need of some adjustments / refactors in the tokens magamenten data management. Indeed, it could potentially need some backend works from `Wallet` team.

**Comment by caybro** [comment]
> Discussed with @alexandraB99 and moved again to this cycle. However this task can become blocked easily bc it depends on the current implementation of the `Tokens Management` and probably, once we start analysing it, we see there's the need of some adjustments / refactors in the tokens data management. Indeed, it could potentially need some backend works from `Wallet` team.

This should be as easy as getting the `property var collectiblesController: ManageTokensController` from CollectiblesStore.qml and and calling `compareTokens(leftSymbol, rightSymbol)` to get the sorting and `filterAcceptsSymbol(symbol)` to find out whether a symbol should be hidden

**Comment by noeliaSD** [comment]
> > Discussed with @alexandraB99 and moved again to this cycle. However this task can become blocked easily bc it depends on the current implementation of the `Tokens Management` and probably, once we start analysing it, we see there's the need of some adjustments / refactors in the tokens data management. Indeed, it could potentially need some backend works from `Wallet` team.
> 
> This should be as easy as getting the `property var collectiblesController: ManageTokensController` from CollectiblesStore.qml and and calling `compareTokens(leftSymbol, rightSymbol)` to get the sorting and `filterAcceptsSymbol(symbol)` to find out whether a symbol should be hidden

Ok! That's an option, but the ideal solution should be trusting on the backend, so we should need to integrate / save the controller information into the DB and here, instead of relying on the controller data, rely on the DB information. 
I need to check how the backend looks like right now, and if we can do the "save action" from the controller to the NIM layer by the json file you agreed with the backend guys and then here, directly get the expected data from the DB.

**Comment by noeliaSD** [comment]
Moved again since this is low prior in comparison of the one exchanged #13799

**Comment by noeliaSD** [comment]
Here the tokens management [task](https://github.com/status-im/status-desktop/issues/13313) that will integrate the settings now stored in the _local settings file to the DB._ Once done, this current task can directly rely on the backend data to decide which are the hidden collectibles and the default position for the showcase hidden section.
