### ISSUE TITLE
Stickers and images are missing preview in pinned messages

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13684]
### Description

1. open community
2. install stickers
3. send image to channel
4. send sticker to channel
5. pin sticker
6. pin image
7. open pinned messages modal

<img width="1967" alt="Screenshot 2024-02-22 at 15 48 33" src="https://github.com/status-im/status-desktop/assets/82375995/35c5809d-5c2d-4c14-85cc-a4683e4385ce">

**Comment by igor-sirotin** [comment]
I think it's just a QML issue. I remember this was working.
