### ISSUE TITLE
Can't do a transaction when previous one is in progress

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13685]
### Description

I have transaction that is stuck in blockchain https://optimistic.etherscan.io/tx/0xbf2a71611cc8bc76b35dcbf2bd9b1d1353b32e14bc9886d0ae74808a85918944

I tried to airdrop the other erc721 token meanwhile but i can't

<img width="1967" alt="Screenshot 2024-02-22 at 15 24 47" src="https://github.com/status-im/status-desktop/assets/82375995/72888042-72ac-4d74-bf00-e7bca2fd502a">

```
DBG 2024-02-22 15:21:46.992+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=21253589 file=core.nim:27 rpc_method=communitytokens_mintTokens
ERR 2024-02-22 15:21:47.667+03:00 rpc response error                         topics="rpc" tid=21253589 file=core.nim:36 err="\nstatus-go error [methodName:communitytokens_mintTokens, code:-32000, message:fallback failed with 'replacement transaction underpriced'. run error was 'replacement transaction underpriced' ]\n"
ERR 2024-02-22 15:21:47.668+03:00 error doing rpc request                    topics="rpc" tid=21253589 file=core.nim:40 methodName=communitytokens_mintTokens exception="\nstatus-go error [methodName:communitytokens_mintTokens, code:-32000, message:fallback failed with 'replacement transaction underpriced'. run error was 'replacement transaction underpriced' ]\n"
ERR 2024-02-22 15:21:47.668+03:00 Error airdropping tokens                   topics="community-tokens-service" tid=21253589 file=service.nim:833 message="\nstatus-go error [methodName:communitytokens_mintTokens, code:-32000, message:fallback failed with 'replacement transaction underpriced'. run error was 'replacement transaction underpriced' ]\n"
```

**Comment by anastasiyaig** [comment]
encountered with @pavloburykh today.

Per @alaibe i had to do another txn with higher gas, but not sure how it is possible in the status app. I tried and failed.

**Comment by alaibe** [comment]
It is simply not possible to this day. We cannot yet modify the gas price

**Comment by anastasiyaig** [comment]
@jrainville i added it to your team pls confirm that it is correct

**Comment by jrainville** [comment]
> Yes it is a wallet issue. However after having more thought, i believe it could potentially be because of nonce management
> 
> @saledjenic tagging you here as something to understand. Do we increase nonce correctly here?

It looks like we increase the nonce only once the transaction is complete.

**Comment by saledjenic** [comment]
Yes, that's what we're doing, you cannot place another TX from the same address until the current one is not accepted. We're fetching `nonce` from the network, we don't cache it and if you have two successive transactions placed immediately one after another they will have the same nonce and one of them (which is accepted later) will fail because of that.

**Comment by anastasiyaig** [comment]
Ya, but it was not immediately. The problem is if transaction takes a lot of time to process, then user is blocked to do any other transactions and does not know about it from app UI. In my case the transaction was processed within 8h

**Comment by saledjenic** [comment]
It looks a bit like an issue with the wrong value or chain, could be that this PR https://github.com/status-im/status-desktop/pull/13839 solves it.

**Comment by alaibe** [comment]
After offline discussion, it looks like we can for this bug, considered known pending tx nonce when computing the current nonce.
However this is not a full solution and see epic for full solution
https://github.com/status-im/status-desktop/issues/13854

**Comment by saledjenic** [comment]
This should be fixed in this PR https://github.com/status-im/status-go/pull/4912

**Comment by anastasiyaig** [comment]
i will close this one as it is already merged to status go (and it is in rc as well)
