### ISSUE TITLE
Stickers pack cant be purchased, no fees are calculated on Sepolia

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13696]
### Description

```
DBG 2024-02-23 10:07:07.305+03:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=21998653 file=threadpool.nim:54 messageType=GetSuggestedRoutesTaskArg:ObjectType threadid=21998653 task="{\"$type\":\"GetSuggestedRoutesTaskArg:ObjectType\",\"accountFrom\":\"0xf008ce0e07f8996c0fe71beb59e076207b214e2d\",\"accountTo\":\"0xf852198d0385c4b871e0b91804ecd47c6ba97351\",\"amount\":\"20000000000000000000\",\"token\":\"STT\",\"disabledFromChainIDs\":[],\"disabledToChainIDs\":[11155420,421614],\"preferredChainIDs\":[11155111],\"sendType\":4,\"lockedInAmounts\":\"{}\",\"vptr\":105553181882912,\"slot\":\"suggestedRoutesReady\",\"tptr\":4303020400}"
```

<img width="1512" alt="Screenshot 2024-02-23 at 10 09 46" src="https://github.com/status-im/status-desktop/assets/82375995/dd25df44-e6c0-47f6-8e72-7734485588d1">

**Comment by anastasiyaig** [comment]
@alaibe ^^

**Comment by saledjenic** [comment]
@anastasiyaig I've just tested this and it works fine, here is a buying stickers transaction I made: https://sepolia.etherscan.io/tx/0x5f20a43b31d76bfa4c3615b1bb04cc73ec3d5fd2d04014b02f059b36db8e58b0

And sticker I bought:



![Image](https://github.com/status-im/status-desktop/assets/86303051/af35707a-248d-40cd-a9e0-d5da0fc84427)

![Image](https://github.com/status-im/status-desktop/assets/86303051/5d85e7dc-8fb4-4fa1-b472-7179a8ef4e1b)

**Comment by anastasiyaig** [comment]
yep, that was fixed last week, thank you Sale
