### ISSUE TITLE
Edit RPC URL - Restart button does not restart the app

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13691]
# Bug Report

## Description

Related to issue https://github.com/status-im/status-desktop/issues/13380
Figma: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=23255-189132&mode=design&t=0DRwQJKDGYJPHkq1-4

1. Edit RPC URL
2. Select to save and restart the app
3. FAIL: App is closed and not automatically relaunched

### Additional Information

- Status desktop version: Nightly 22 Feb
- Operating System: Mac

**Comment by alaibe** [comment]
By "design" all the restart action are actually a close
