### ISSUE TITLE
Add a possibility to release ENS name on testnet (Sepolia) within reasonable time 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13698]
### Description

Currently, the value is hardcoded to 1 year which is making testing of release ens name functionality impossible

https://github.com/status-im/ens-usernames/blob/master/contracts/registry/UsernameRegistrar.sol#L23

I need a possibility to configure this value so i can test purchase - release flow within reasonable timeframe. I would love to have this param set to 1 or 5 minutes

**Comment by anastasiyaig** [comment]
@alaibe can we please plan this? Not really urgent but we need it

**Comment by alaibe** [comment]
Will do
