### ISSUE TITLE
[Profile showcase] Change stroke position from `outside` to `inside` according to the design

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13693]
### Description

![image](https://github.com/status-im/status-desktop/assets/97019400/5ce5935e-fc77-4b81-8be6-4ee77383d584)

- Top image is what we have now in the application (with stroke 20% blue).
- Bottom image is what it's in the design, inside and with stroke 10% blue line.

Update the current `ProfileShowcasePanel.qml/VisibilityDropAreaButton` in order to fit the [design](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460%3A40602&mode=design&t=wUWwdVGlQ4cYZ0Td-1).

**Comment by caybro** [comment]
Not sure this is technically possible/feasible with the QML Shape element

**Comment by noeliaSD** [comment]
> Not sure this is technically possible/feasible with the QML Shape element

Some element on top of the other?
