### ISSUE TITLE
[ProfileShowcase] Implement scrolling behavior in Profile Dialog 

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13704]
### Description

[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-32240&mode=dev)

Implement scrolling behavior in Profile Dialog as per figma design

**Comment by caybro** [comment]
And https://github.com/status-im/status-desktop/issues/13345 :laughing:

**Comment by alexandraB99** [comment]
Duplicate: https://github.com/status-im/status-desktop/issues/13420
