### ISSUE TITLE
Deploy community contracts to Sepolia Optimism

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13705]
### Description

https://www.notion.so/Contract-Deployment-Addresses-d6dd98b1b4f6461d82eec6ab18b852c8

We have Sepolia Arbitrum support, now it is time to support Optimism on Sepolia as well

![image](https://github.com/status-im/status-desktop/assets/82375995/7ca8bcec-7192-4116-abf0-8287391a6164)

```ERR 2024-02-23 14:24:04.141+02:00 error doing rpc request                    topics="rpc" tid=20997756 file=core.nim:40 methodName=wakuext_createCommunityTokenDeploymentSignature exception="\nstatus-go error [methodName:wakuext_createCommunityTokenDeploymentSignature, code:-32000, message:deployer contract not available for chainID ]\n"```

**Comment by anastasiyaig** [comment]
@jrainville can we allocate @endulab to do that? We recently made Sepolia enabled by default so it makes sense to have this change done soonish

**Comment by jrainville** [comment]
@0x-r4bbit could you take care of deploying the Community contracts to Sepolia, please? Thank you!

**Comment by jrainville** [comment]
@endulab can you add the addresses to status-go please. Thanks
