### ISSUE TITLE
No randomly selected emoji when adding new wallet account

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#13715]
<img width="562" alt="5" src="https://github.com/status-im/status-desktop/assets/86303051/f4809335-4566-4a4a-92c1-9847d0b2f73f">

**Comment by anastasiyaig** [comment]
thanks @saledjenic , i will add this verification in my tests once the bug is fixed so we have it covered

**Comment by alaibe** [comment]
Part of this: the flag should be out of the list for random emoji selection
