### ISSUE TITLE
[Profile flow] Mark as ID verified / remove verification

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13711]
Mark (contact) as ID verified:
![image](https://github.com/status-im/status-desktop/assets/5377645/43682ac0-36a9-4dc0-96a5-39db74c740a3)

Remove ID verification:
![image](https://github.com/status-im/status-desktop/assets/5377645/ee39e63d-0827-42b1-bff3-fd2277e2e77d)

Figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-204116&mode=design&t=GGhX1EHgbfuJP6Rh-0

**Comment by caybro** [comment]
Just a question here @MishkaRogachev : is it currently possible directly marking someone as "ID verified" without going thru the ping-pong?

**Comment by MishkaRogachev** [comment]
> Just a question here @MishkaRogachev : is it currently possible directly marking someone as "ID verified" without going thru the ping-pong?

There is a [verifiedTrusted](https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Profile/stores/ContactsStore.qml#L130) api func, but i in the current state it will return an error without having an existing verification request.

**Comment by caybro** [comment]
> > Just a question here @MishkaRogachev : is it currently possible directly marking someone as "ID verified" without going thru the ping-pong?
> 
> There is a [verifiedTrusted](https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Profile/stores/ContactsStore.qml#L130) api func, but i in the current state it will return an error without having an existing verification request.

OK, so this is something that needs fixing

**Comment by MishkaRogachev** [comment]
> > > Just a question here @MishkaRogachev : is it currently possible directly marking someone as "ID verified" without going thru the ping-pong?
> > 
> > 
> > There is a [verifiedTrusted](https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Profile/stores/ContactsStore.qml#L130) api func, but i in the current state it will return an error without having an existing verification request.
> 
> OK, so this is something that needs fixing

In this case let's open an issue for implementing a dedicated endpoint for marking contact as trusted without  the ping-pong. Should a call of that endpoint invoke AC notification? And what if a user already having pending verification request?

**Comment by caybro** [comment]
> > > > Just a question here @MishkaRogachev : is it currently possible directly marking someone as "ID verified" without going thru the ping-pong?
> > > 
> > > 
> > > There is a [verifiedTrusted](https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Profile/stores/ContactsStore.qml#L130) api func, but i in the current state it will return an error without having an existing verification request.
> > 
> > 
> > OK, so this is something that needs fixing
> 
> In this case let's open an issue for implementing a dedicated endpoint for marking contact as trusted without the ping-pong. Should a call of that endpoint invoke AC notification? And what if a user already having pending verification request?

Opened as https://github.com/status-im/status-desktop/issues/13716
