### ISSUE TITLE
Collectibles are not shown in wallet

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13725]
# Bug Report

## Description

When going into the collectibles tab in wallet, the tab does not load. The behaviour is the  same no matter if the account has collectibles or not. 

## Steps to reproduce

1. Log into an account
2. Add an account with collectibles to that account's wallet (can be as a watched address)

#### Expected behavior
Collectibles tab loads and collectibles are shown for accounts that have them.

#### Actual behavior
Collectibles tab does not load and collectibles are NOT shown for accounts that have them.

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/systems/job/macos/job/aarch64/job/package/342/
- Operating System: macOS

Addresses watched in video reproduction: 0xac30466407c0d7f82A37789bAB46B43679db4b3B and 0xf4A5E6aeFDdB163cE52d9F8A3804F2070Ea5ADa7

https://github.com/status-im/status-desktop/assets/155960867/6d5325e7-2195-4900-87db-d35b67c4820b

[app_20240226_161531.log](https://github.com/status-im/status-desktop/files/14407330/app_20240226_161531.log)

**Comment by alaibe** [comment]
I only see community token:
![image](https://github.com/status-im/status-desktop/assets/491074/de364caf-9dd5-4682-9037-c9a4326baadc)
