### ISSUE TITLE
Fix SendModal dialog to enter amount of tokens to send when there are many or no input when there is 1

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#13731]
This should be done when ERC1155 contract is ready for communities

This is  point 5 of issue #13430 
5) If a user selects a collectible which they have >1 of, they must select the QTY to send:

<img width="608" alt="Screenshot 2024-02-06 at 9 30 31 AM" src="https://github.com/status-im/status-desktop/assets/110033914/2ee300af-6c6b-4c2d-a84f-7fb17e0a8129">

**Comment by noeliaSD** [comment]
Maybe this task will fix the issue described here: https://github.com/status-im/status-desktop/issues/15215
