### ISSUE TITLE
support sending an image through drag & drop into the chat

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1374]

**Comment by simonricoo** [comment]
Design: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=1944%3A2431
![Uploading Screen Shot 2020-12-02 at 16.11.29.png…]()

**Comment by iurimatias** [comment]
closed by mistake
