### ISSUE TITLE
Endless Loading Status during login with wrong password

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#13758]
# Bug Report

## Description

When user input wrong password and click arrow button there is no error about wrong password. Endless Loading Status appears instead

<img width="1920" alt="Screenshot 2024-02-28 at 10 09 13" src="https://github.com/status-im/status-desktop/assets/82375995/55fd58b7-6986-4729-bbfa-7a72b9017aed">

## Steps to reproduce

1. Start Status 
2. Input wrong password for user
3. Click arrow button

#### Expected behavior
Error Password incorrect appears

#### Actual behavior
Endless Loading Status appears

### Additional Information

- Video: https://github.com/status-im/status-desktop/assets/141633821/5c639a6a-5bb1-4686-914a-2764cc7d5f98
- Status desktop version: the latest master build
- Operating System: masOS Ventura 13.5

```
DBG 2024-02-28 10:08:45.171+03:00 primary_action                             topics="app-controller" tid=26690289 file=module.nim:203 currFlow=AppLogin currState=LoginKeycardEnterPassword
Warning: Populating font family aliases took 164 ms. Replace uses of missing font family "Inter" with one that exists to avoid this cost.  (:0, )
ERROR[02-28|10:08:45.513|github.com/status-im/status-go/api/geth_backend.go:432] failed to initialize wallet db           package=status-go/api.GethStatusBackend err="failed to set `journal_mode` pragma: file is not a database"
failed to set `journal_mode` pragma: file is not a database
ERR 2024-02-28 10:08:45.513+03:00 error:                                     topics="accounts-service" tid=26690289 file=service.nim:673 procName=verifyDatabasePassword errDesription="failed to set `journal_mode` pragma: file is not a database"
DBG 2024-02-28 10:08:45.514+03:00 Account logged in                          topics="accounts-service" tid=26690289 file=service.nim:693
ERROR[02-28|10:08:45.677|github.com/status-im/status-go/api/geth_backend.go:432] failed to initialize wallet db           package=status-go/api.GethStatusBackend err="failed to set `journal_mode` pragma: file is not a database"
```

**Comment by anastasiyaig** [comment]
@igor-sirotin could that be a regression from recent go changes?

**Comment by igor-sirotin** [comment]
No idea how this could lead to such behaviour. let me take a look 👀

**Comment by igor-sirotin** [comment]
Ok I can confirm it is a regression from https://github.com/status-im/status-go/pull/4813 🙁
