### ISSUE TITLE
[ChangePasswordView] Cancel/Confirm buttons in biometrics popup are cut when opening the first time

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13760]
### Description

Original issue found [here](https://github.com/status-im/status-desktop/pull/13669#pullrequestreview-1895226148).

Steps to reproduce:
1) Run the app
2) Go to Profile - Password
3) Press the 'Enable biometrics' switch

Behavior:
The popup buttons are cut on top

![image](https://github.com/status-im/status-desktop/assets/31625338/4317f6f2-474c-4e54-a777-59ba2d14227d)

Test with Qt 5.15.12 as it not happening on 5.15.2

**Comment by alexjba** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/13669
