### ISSUE TITLE
Button to go to the latest message is barely visible on dark theme

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13771]
# Bug Report

## Description

Button to go to the latest message is barely visible on dark theme

## Steps to reproduce

1. Go to a chat / channel
2. Scroll up until button to `go to the last message` is shown

#### Expected behavior
Something similar than in light mode:

![Screenshot 2024-02-28 at 16 11 03](https://github.com/status-im/status-desktop/assets/97019400/4439699c-4b27-4f29-8fed-c0deae22bd04)

#### Actual behavior

![image](https://github.com/status-im/status-desktop/assets/97019400/65ac38f1-5b0f-40c6-9607-8d1caac987d6)

### Additional Information

- Status desktop version: **2.27.0-rc5**
- Operating System: _macos_

**Comment by caybro** [comment]
I think we even have a more recent design for this @benjthayer

**Comment by benjthayer** [comment]
Good spot @noeliaSD @caybro 

Designs for this are here, along with newly added dark theme variants for the buttons:
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=24973-422049&mode=design&t=KfCc29HM4Yvz2k5c-4

<img width="291" alt="Screenshot 2024-02-28 at 4 44 09 PM" src="https://github.com/status-im/status-desktop/assets/110033914/6221f544-9afb-4ea3-b2b8-862f77e2e8e4">
