### ISSUE TITLE
TokenMaster cannot post in a read only channel

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13779]
# Bug Report

## Description

TokenMasters, likes admins should have the right to post in any channel, even if it read only. However, it's not possible right now. 

It fails with a backend error:
```
ERR 2024-02-28 11:02:21.417-05:00 error doing rpc request                    topics="rpc" tid=1715538 file=core.nim:40 methodName=wakuext_sendChatMessage exception="\nstatus-go error [methodName:wakuext_sendChatMessage, code:-32000, message:can't post on chat ]\n"
```

## Steps to reproduce

1. Have a channel with an Owner and a TokenMaster
2. Create a new channel
3. Set a read-only permission on it
4. TM can't post on it
5. I don't think Owner messages get sent either, though the Owner can post

#### Expected behavior

TM can post to all types of channels

#### Actual behavior

TM can't post to read-only channels

### Additional Information

- Status desktop version: 2.27RC.5

**Comment by igor-sirotin** [comment]
I can reproduce this on latest master 🙁 

<img width="1386" alt="Screenshot 2024-03-01 at 12 30 39" src="https://github.com/status-im/status-desktop/assets/25482501/94f69c94-6e06-4ef2-98fc-a14a6fe0418c">
<img width="1386" alt="Screenshot 2024-03-01 at 12 30 43" src="https://github.com/status-im/status-desktop/assets/25482501/4e3089e6-f5c6-41ad-8c63-28302b894da9">

**Comment by igor-sirotin** [comment]
At some point of testing I wasn't able to edit one of channel permissions 👀 

<img width="634" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/1113e2b6-0ca2-4312-b6d8-148030e10a86">

**Comment by jrainville** [comment]
@igor-sirotin Ok I finally was able to reproduce your issue. It's because the Control node had an issue when checking the permissions/tokens.

Here are the logs:
```
DBG 2024-03-05 14:24:54.963-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=1529515 file=core.nim:27 rpc_method=wakuext_checkAllCommunityChannelsPermissions
ERR 2024-03-05 14:24:54.972-05:00 Error getting community tokens details     topics="community-tokens-service" tid=1529501 file=service.nim:808 message="Error creating token item\nstatus-go error [methodName:communitytokens_remoteDestructedAmount, code:-32000, message:fallback failed with 'hystrix: circuit open'. run error was 'hystrix: circuit open' ]\n"
```

It caused the member list to be empty on both the TM and the Owner. Since the TM doesn't see himself in the member list, he cannot post.
```
DBG 2024-03-05 14:25:11.279-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=1530207 file=core.nim:27 rpc_method=wakuext_sendChatMessage
ERR 2024-03-05 14:25:11.284-05:00 rpc response error                         topics="rpc" tid=1530207 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_sendChatMessage, code:-32000, message:can't post on chat ]\n"
ERR 2024-03-05 14:25:11.284-05:00 error doing rpc request                    topics="rpc" tid=1530207 file=core.nim:40 methodName=wakuext_sendChatMessage exception="\nstatus-go error [methodName:wakuext_sendChatMessage, code:-32000, message:can't post on chat ]\n"
ERR 2024-03-05 14:25:11.284-05:00 Error sending message                      topics="chat-service" tid=1530207 file=service.nim:563 msg="\nstatus-go error [methodName:wakuext_sendChatMessage, code:-32000, message:can't post on chat ]\n"
```

@alaibe is that something that is planned to improve with a better plan on the different services or we should be more lenient in our side and when the token requests fail just accept everyone for now?

**Comment by alaibe** [comment]
@jrainville do u know the error from the rpc endpoint?

FYI we already have built some resilience. On production networks, we have a main and fallback so at least one retry
However on testnet, due to lack of support this is not available

**Comment by jrainville** [comment]
@alaibe here is what I could find in geth.log
```
WARN [03-05|14:24:30.057|rpc/handler.go:305]                                                                     Served communitytokens_remoteDestructedAmount reqid=453 duration=38.097213ms err="fallback failed with '429 Too Many Requests: {\"jsonrpc\":\"2.0\",\"id\":90,\"error\":{\"code\":-32005,\"message\":\"project ID request rate exceeded\",\"data\":{\"rate\":{\"allowed_rps\":10,\"backoff_seconds\":30,\"current_rps\":11.433333333333334},\"see\":\"https://docs.infura.io/infura/networks/ethereum/how-to/avoid-rate-limiting\"}}}'. run error was 'hystrix: circuit open'"
```
> project ID request rate exceeded

I guess I don't have the right project ID for that one?

> However on testnet, due to lack of support this is not available

Ah that doesn't help. I did experience it once on release I think, but we can wait and see if we can reproduce and see if it's really that.
