### ISSUE TITLE
Token remote-destructed by TM didn't update the member list

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13778]
# Bug Report

## Description

As a TokenMaster, I remotely destructed the token of Patryk. That token gave access to a Read/Write channel.

Once the token was destructed, Patryk no longer appeared in the list of token holders, meaning that the destruction worked correctly.
However, the member list for that channel didn't update, so Patryk could continue to see and post in that channel.

## Steps to reproduce

1. Have a community with an Owner and a TokenMaster
2. Mint a new token
3. Create a new channel
4. Set that channel as Read-Post only when having that new token
5. Airdrop the token to a new user (Bob)
6. Bob can now see and post in that channel
7. Alice has no token so she cannot see or post in it
8. Remotely destruct Bob's token using as the TokenMaster
9. Wait for it to work and even the Owner no longer sees Bob as a holder of that token
10. Bob can still access the channel
11. The member list for that channel didn't change

#### Expected behavior

Once the Control node detects that someone is no longer a holder for a token, it should reevaluate the permissions that use that token and change the member list
Bob should no longer have access to that channel.

#### Actual behavior

The member list doesn't change and Bob can still access

### Additional Information

- Status desktop version: 2.27RC.5

**Comment by osmaczko** [comment]
Okey, I know what happened.

> 8. Remotely destruct Bob's token using as the TokenMaster

This only destroys the token but does not notify the control node about its destruction. As a result, the control node remains unaware that it needs to reevaluate permissions for community members. There is a loop that evaluates the members, but it is activated only once per hour. Consequently, we are faced with a situation where members who have lost permissions can still access the community or channel.

To mitigate this exact scenario, we could send an "remote-destruct" event to the control node from the token master, this would trigger an immediate re-evaluation of member permissions. Alternatively, we can accept this situation for now and live with the potential one-hour window of unauthorized access in the worst-case scenario.

wdyt @jrainville ?

**Comment by jrainville** [comment]
I think we should send a signal to the control node. If the signal is lost or the TM goes offline before the self-destruct is processed, then it's not the end of the world, but I think it's better to try and get it re-evaluated as fast as possible.

I'll move this out of 2.27RC since it's not as bad a bag as we thought.
