### ISSUE TITLE
Password settings flow

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13785]
Link to design:
https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-28567&mode=design&t=AE3iFxtTlP5h9kc9-0

- [x] #13893
- [x] #13894
- [x] #13895
- [x] #13896
- [x] #13897
- [x] #13898
- [x] #13983
- [x] #13992

**Comment by caybro** [comment]
@alaibe @alexandraB99 I think we've already implemented most of this, maybe except the last point (keycard)

**Comment by alaibe** [comment]
@caybro there must have been a design upgrade as I checked app and design and there is little diff here and there

**Comment by stefandunca** [comment]
All tasks are finalized
