### ISSUE TITLE
Show Context Menu on Collectible Details Transaction right-click

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#13786]
### Description

![image](https://github.com/status-im/status-desktop/assets/11161531/9ea2b394-b6ca-4632-8724-1e43827ca230)

Ben says:

_... we'd need to amend it slightly as some of the menu list items would not be appropriate for that location in the app - we'd probably want to remove Filter by similar given that usually filters the full account activity list (which is out of view at this point)
We'd also want to remove Repeat transaction for any activity items the user cannot repeat - eg they can't repeat a transaction that is a receive transaction._

**Comment by alaibe** [comment]
Estimation notes: we will refactor to reuse code
