### ISSUE TITLE
[ProfileShowcase] Integrate `Save` action with the new backend

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13799]
Integrate the new `save` API for the profile showcase settings as defined here https://github.com/status-im/status-desktop/issues/13688.

This is the first proposal for the `save` JSON argument to be sent to nim. Please check #13688 for the final API
```
{
  communities: [ { communityId: <string>, visibility: <int> }],
  accounts: [ { address <string>, visibility: <int> }],
  collectibles: [ { chainId: <int>, tokenId: <string>, contractAddress: <string>, visibility: <int> }],
  verifiedTokens: [ { symbol: <string>, visibility: <int> }],
  unverifiedTokens: [ { chainId: <int>, contractAddress: <string>, visibility: <int> }],
  socialLinks: [ { url: <string>, text: <string>, visibility: <int> }]
}
```

**Comment by iurimatias** [comment]
moving to next milestone due to lack of space in this one

**Comment by caybro** [comment]
Again, imho this is a must for the Profile Showcase feature scheduled for 
2.28; @alexjba @iurimatias

**Comment by iurimatias** [comment]
is there an equivalent effort issue still in the milestone we can move in exchange for this one?

**Comment by noeliaSD** [comment]
@iurimatias if you need to do an exchange, that could be one: https://github.com/status-im/status-desktop/issues/13680 but this task is a must! I'll take it instead of the other.

**Comment by alexjba** [comment]
Depends on https://github.com/status-im/status-desktop/issues/13688

**Comment by anastasiyaig** [comment]
@noeliaSD pls ping me when Save button starts working , i will enable my tests back

**Comment by noeliaSD** [comment]
Ok @anastasiyaig ! it will be a combination of this task done but also the backend related one too. Here the backend one: https://github.com/status-im/status-desktop/pull/13708

**Comment by noeliaSD** [comment]
Final agreed decision with @MishkaRogachev : 

```
{
  accounts: [ { showcaseKey <string>, showcaseVisibility: <int>, showcasePosition: <int> }],
  communities: [ { showcaseKey: <string>, showcaseVisibility: <int>, showcasePosition: <int> }],
  assets: [ { showcaseKey: <string>, showcaseVisibility: <int>, showcasePosition: <int> }],
  collectibles: [ { showcaseKey: <string>, showcaseVisibility: <int>, showcasePosition: <int> }],
  socialLinks: [ { url: <string>, text: <string>, showcaseVisibility: <int>, showcasePosition: <int> }]
}

```
