### ISSUE TITLE
[ProfileShowcase] Integrate the dirty state managers with the UI components

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13801]
### Description

Depends on:
https://github.com/status-im/status-desktop/issues/13498
https://github.com/status-im/status-desktop/issues/13490
https://github.com/status-im/status-desktop/issues/13494

The new UI API provided [here](https://github.com/status-im/status-desktop/issues/13498
) has stripped down all the dirty state related logic. DND position changes, and visibility should be integrated with the new dirty states managers provided [here](https://github.com/status-im/status-desktop/issues/13490) and [here](https://github.com/status-im/status-desktop/issues/13494) so that the visibility change and position change functionality is restored.

**Comment by alexandraB99** [comment]
[PR here](https://github.com/status-im/status-desktop/pull/13769)
