### ISSUE TITLE
[StatusQ/MovableModel] Add support for source model reset

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13800]
### Description

The movable model doesn't support source model reset. When the source model is reset the MovableModel should reset its synced state and discard the dirty state.

This is needed for the Profile showcase settings. The MovableModel is used to proxy the SFPM events so that the DND works correctly on top of a SFPM. But the Profile showcase settings changes can be discarded by the user resulting in a source model reset.

**Comment by alexandraB99** [comment]
[PR here](https://github.com/status-im/status-desktop/pull/13769)

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-desktop/pull/13769
