### ISSUE TITLE
Forever loading channel on certain channels

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13814]
# Bug Report

## Description

The return of the forever loading channel issue.

It's a bit random when it happens. Almost everyone could trigger it at the same time in the `#desktop` channel of the Status CC v1. But after a restart, it's now ok.

I can also easily reproduce on the `#desktop` channel in the old Status CCs Community.

The source is a bit unknown

## Steps to reproduce

Hard to 100% repro. Just click on a channel and it might happen. It seems to happen more on bigger channels?

#### Expected behavior

The loading ends at some point

#### Actual behavior

The channel loads forever

### Additional Information

- Status desktop version: 2.27RC5
- Operating System: Ubuntu 20

**Comment by jrainville** [comment]
Might be related to https://github.com/status-im/status-desktop/issues/13533

**Comment by igor-sirotin** [comment]
Done in https://github.com/status-im/status-desktop/pull/13883
