### ISSUE TITLE
Sending a message is very slow on encrypted channels

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13813]
# Bug Report

## Description

Only a few people experienced this one. Maybe it's related to some DBs being bigger than others? It only happens on encrypted communities (permission to join)

## Steps to reproduce

Nothing special, just send a message in an encrypted community.

[slow-send.webm](https://github.com/status-im/status-desktop/assets/11926403/b1fa6afb-647b-4809-a9e8-47ad4f8a38a6)

#### Expected behavior

It is almost as fast to send in an encrypted channel than on a non-encrypted one.

#### Actual behavior

Encrypted channels are WAY slower to send

### Additional Information

- Status desktop version: 2.27RC5
- Operating System: Ubuntu 20

**Comment by cammellos** [comment]
@jrainville I'll be working on this

**Comment by jrainville** [comment]
> @jrainville I'll be working on this

Thanks. Let me know if you need a hand

**Comment by anastasiyaig** [comment]
it is fixed
