### ISSUE TITLE
Crash when receiving certain messages (delete in this case)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13812]
# Bug Report

## Description

While testing the 2.27 RC, some of us experienced random crashes.

One of them had better logs and it happened when receiving a message deletion signal.

![image](https://github.com/status-im/status-desktop/assets/11926403/c6b55b09-2e56-4e1f-95c1-8e2816add917)

The other crashes didn't have as many logs. Mine showed just `message received`.

## Steps to reproduce

Unknown. Try to delete messages on one instance and see what happens.

#### Expected behavior

No crash

### Additional Information

- Status desktop version: 2.27RC5 +

**Comment by mprakhov** [comment]
Note:
`onMessageDeleted` was renamed on the latest master to `onMessageRemoved` (and all other similar fn), so this bug is related to the removing msg, not deleting msg of the banned members
