### ISSUE TITLE
Community: adding permission via edit channel triggers unnecessary toast messages

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13828]
### Description

1. create community
2. create channel
3. right click channel - edit
4. add permission from edit mode 
5. save the permission

as result, the app shows 3 toast messages in a row, when 1 is expected

https://github.com/status-im/status-desktop/assets/82375995/d41fac15-f69e-48ec-bc38-9fba5c61b597

**Comment by friofry** [comment]
Hi @anastasiyaig 

This problem no longer reproduces on the master: https://github.com/status-im/status-desktop/commit/d703d0e8

https://github.com/status-im/status-desktop/assets/1083341/a90b7de6-fc01-48bf-87ef-ceb900913623

**Comment by anastasiyaig** [comment]
sure feel free to close then  :)
