### ISSUE TITLE
Deploy a dummy NFT contract to allow minting of dummy NFTs on Sepolia

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13822]
### Description

The sample code i found is here https://blog.chain.link/how-to-create-an-nft/ but could be any.

Acceptance criteria: I have a contract deployed on Sepolia that I can use to mint a dummy NFTs (ERC721) which could be used for testing purposes

**Comment by dlipicar** [comment]
Solved by [https://status-im.github.io/nft-faucet](https://status-im.github.io/nft-faucet/networks)

**Comment by anastasiyaig** [comment]
thanks @dlipicar , i tried that today and it works :) I still need to figure out the picture, because it did not work to me but overall token is there and thats a huge help!

<img width="1635" alt="Screenshot 2024-04-04 at 11 39 15" src="https://github.com/status-im/status-desktop/assets/82375995/775b5c7b-9210-4c64-affa-028381193fa5">
