### ISSUE TITLE
CPU Usage of the Status desktop application is High, averaging 100% on a 2 CPU cores machine

### ISSUE THREAD

**Issue by kounkou** [status-im/status-desktop#13833]
### Description

While testing 2.27.0-rc.6 I noticed that the CPU taken by Status Desktop application averages 100% on a 2 cores hardware CPU's. Behavior is the same after a reboot of the application. At this point in time of writing the github issue, it's unclear what is causing the consistent 100% CPU. From observing the sample and the spindump, it seems like there's a need for overall CPU optimisation phase for the entire application.

### Geth logs

[geth.log.zip](https://github.com/status-im/status-desktop/files/14488157/geth.log.zip)

### Expected behavior

The CPU usage should reasonnably low or below 50% which is a common value for normally functioning applications.

### Screenshots

<img width="1415" alt="Screenshot 2024-03-04 at 3 05 38 PM" src="https://github.com/status-im/status-desktop/assets/2589171/60a1121c-4904-400f-818c-7c9b27447491">

### Others

Here am sharing some additional information related to the process : 

Spinddump : 

[spindump.log](https://github.com/status-im/status-desktop/files/14488203/spindump.log)

Sample :
 
[Sample of Status Desktop-1.txt](https://github.com/status-im/status-desktop/files/14488247/Sample.of.Status.Desktop-1.txt)

### Software components version

Status-desktop 2.27.0-rc.6
Status-go      0.174.8

### Hardware characteristics

MacBook Pro
Processor 2.3 GHz Dual-Core Intel Core i5
Graphics Intel Iris Plus Graphics 640 1536 MB
8 GB 2133 MHz LPDDR3
MacOs 13.6.4 Ventura

**Comment by jrainville** [comment]
Is there a Mac version of https://github.com/KDAB/hotspot you could run?
