### ISSUE TITLE
Changes in account order in Settings are not applied in Wallet 

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#13836]
# Bug Report

If we quickly change account order in Settings and then go to Wallet these changes are not applied there

1. Create several wallet accounts
2. Go to Settings/ Account order and quickly drag and drop one account to the end of list for example
3. Go to Wallet

#### Expected behavior
Account order in Wallet is the same as in Settings/Account order after drag and drop
#### Actual behavior
It remains the same as it was before drag and drop, changes are not applied
### Additional Information

https://github.com/status-im/status-desktop/assets/141633821/d2b4b380-498d-4cd2-808d-893ddf46b1f4

- Status desktop version: macOS Ventura 13.5
- Operating System: the latest master build

**Comment by anastasiyaig** [comment]
@iurimatias please prioritise. I already asked @saledjenic to check how massive / hard the change is , but there is no emergency to do it right away. So please plan the effort somewhere in nearest possible window
