### ISSUE TITLE
Application is not responding after adding account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13842]
### Description

I imported a seed
I added account as watch only `0xF38D2CD3C6Ad02dD6f8B68E0A7b2f959819954b6`
Application is not responding anymore

After restart of the app i tried to delete this watch only account and then application got stuck again (bench ball appeared). I waited for a couple of minutes and then the account was deleted.

It has to be something on this account in terms of tokens / collectibles that leads to that

<img width="1468" alt="Screenshot 2024-03-05 at 18 01 17" src="https://github.com/status-im/status-desktop/assets/82375995/16db5df6-f11d-4205-ad56-63ecf96a06f5">

<img width="274" alt="Screenshot 2024-03-05 at 18 01 10" src="https://github.com/status-im/status-desktop/assets/82375995/9bb9393e-8fa4-4868-a918-e767b2ee26fb">

**Comment by anastasiyaig** [comment]
@alaibe it happens to me with the seed from the account i shared with you, can you try?

**Comment by anastasiyaig** [comment]
maybe @dlipicar is interested :D

**Comment by alaibe** [comment]
@anastasiyaig i am unable to reproduce, can you confirm that you can and if u do what is the build that you re using?
