### ISSUE TITLE
[Wallet/Graph] Implement tooltips interactions in maximized graph view

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13846]
Tooltip interactions [figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=18869-231574&mode=design&t=6MpHaVeVGo29zuHA-4)

Sample screenshot

![fds](https://github.com/status-im/status-desktop/assets/31625338/f11cab5e-47c7-4b32-8da9-bab2ed05c74c)

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
