### ISSUE TITLE
[Wallet/Graph] Add hover states for maximized graph

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13844]
#### Problem

TODO

#### Desired Behaviour

Use Case

TODO

#### Relevant Resources & Links

Hover states [figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-202854&mode=design&t=6MpHaVeVGo29zuHA-4)

Legends [figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=18869-230255&mode=design&t=6MpHaVeVGo29zuHA-4)

<img width="1600" alt="Account with history (2 years) - chart expanded (ALL)" src="https://github.com/status-im/status-desktop/assets/31625338/8aec8d8b-d2cc-4ba6-a56e-e5dd673a79b8">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
