### ISSUE TITLE
[Wallet/Graph] Implement tooltips for maximized graph view

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13845]
Tooltips [figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=18869-230255&mode=design&t=6MpHaVeVGo29zuHA-4)

![tt](https://github.com/status-im/status-desktop/assets/31625338/c94814a6-c127-4033-a0bd-e641aeec4136)

**Comment by caybro** [comment]
Should be a full fledged `Popup`, a mere `ToolTip` won't cut it here

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
