### ISSUE TITLE
[Wallet/Graph] Add small graph representations inside Assets delegates (figma)

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13858]
[Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-197814&mode=design&t=WmMFD304gsIZiBOQ-4)

<img width="1188" alt="Account with history (2 years)(1)" src="https://github.com/status-im/status-desktop/assets/31625338/2337ec9f-186d-4a8e-a346-7df0e8f00543">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
