### ISSUE TITLE
[Wallet/Graph] Update graph UI in wallet to reflect new designs, minimized and maximized view

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13856]
Make sure you make both versions [color customizable](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-242845&mode=design&t=34EV2UEyI0MiAakf-4). 

[Figma minimized view](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-197814&mode=design&t=AmIqp4rkWlu530av-0)

<img width="1188" alt="Account with history (2 years)" src="https://github.com/status-im/status-desktop/assets/31625338/aea224d2-d86a-4d7c-a1a8-92efa3a29539">

[Figma maximized view](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-201871&mode=design&t=xmYGC3EyRT7nTPNH-0)

<img width="1188" alt="Account with history (2 years) - chart expanded (ALL)(1)" src="https://github.com/status-im/status-desktop/assets/31625338/e6f21cb4-5b41-4814-a45c-7b168231545c">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
