### ISSUE TITLE
[Wallet/Graph] Add "adding new account" graph behavior

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13859]
[Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-198522&mode=design&t=wJ3NuEQ2bl7cEzKl-4)

<img width="1188" alt="2nd day" src="https://github.com/status-im/status-desktop/assets/31625338/32d8efd5-2a07-4763-94b5-23c29d9c57af">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
