### ISSUE TITLE
contact bar message preview incorrectly treats markdown

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1385]
`test **bold** test` in a message results in the preview looking like this in the contact bar `testboldtest`

**Comment by jrainville** [comment]
This is fixed here https://github.com/status-im/nim-status-client/pull/1312

**Comment by iurimatias** [comment]
duplicate of #1315

**Comment by iurimatias** [comment]
correction, not duplicate of #1315 (I wrote on the wrong issue), but this has been fixed as well.
