### ISSUE TITLE
[Create Channel] Review discord import flows

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13855]
### Description

The create/edit channel had some recent changes in permissions and close confirmation flows and the discord import flows need to be aligned.

#### [Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba⎜Desktop---Communities?type=design&node-id=44525-269785&mode=design&t=m7VY5yzA2Em5jir5-0)

<img width="759" alt="Screenshot 2024-03-06 at 11 25 39" src="https://github.com/status-im/status-desktop/assets/47811206/99018d9f-dbed-4c8f-81c7-8f7d9c1f08c7">

TODO:
- [ ] Review the close confirmation popup in the discord import flow.
@benjthayer We'll need your help in this regard. The main questions are: Should we display the close confirmation popup in the discord import flows? If yes, when, under what conditions and what should we save when the save is accepted in the close confirmation popup? E.g: Closing the popup after selecting the discord import file. If we'll display the close confirmation popup and the user hits `save` the new channel will be saved with all the info filled by the user in the first screen.

- [ ] The permissions are not saved when importing a channel using discord import.
This flow is quite different than create/edit channel because it's done totally in the nim/status-go layer and it's currently not possible to save the permissions. There's two options to this: To update `requestImportDiscordChannel` to support permissions as well, or to return the newly created chat id when `requestImportDiscordChannel` is called so that the UI can update the channel permissions.

- [ ] `Close and delete channel` doesn't delete the channel.
This button is shown when the discord import started. Clicking will just close the popup and stop the import.

**Comment by iurimatias** [comment]
descoped for now
