### ISSUE TITLE
[Wallet/Graph] Add scrolling behavior for graph component

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13857]
[Figma link](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17035-258930&mode=design&t=bmOk26stxotIWP91-0)

<img width="1188" alt="Account with history (2 years)" src="https://github.com/status-im/status-desktop/assets/31625338/90bc3123-6d4e-4811-9dce-4282869e32e8">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
