### ISSUE TITLE
Community -> Tokens screen is not updated when community tokens are minted on Sepolia Arbitrum

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13851]
### Description

I minted owner token and token master on sepolia arbitrum and transaction is completed https://sepolia-explorer.arbitrum.io/tx/0x646eea1eac1a76b30ecaa940adef8d0d4c16a32facb254b418804810d30b2b6e

i have a notification about token owner received however the app UI says the status of token is still Minting

<img width="1512" alt="Screenshot 2024-03-06 at 09 56 16" src="https://github.com/status-im/status-desktop/assets/82375995/85355df3-5804-4f10-9575-8b33d6b434cc">
<img width="1512" alt="Screenshot 2024-03-06 at 09 56 33" src="https://github.com/status-im/status-desktop/assets/82375995/f7029c9f-5f05-4e26-91da-9690c54fb05e">

**Comment by jrainville** [comment]
I'm not sure if it's the same issue. Both are wallet related, so I'll change the label cc @alaibe

**Comment by dlipicar** [comment]
Seems like @endulab was already working on a rework that should fix this issue

**Comment by dlipicar** [comment]
The "proper" fix is what @endulab is doing: move the logic over to status-go and simply notify the UI. That's too big to include as a hotfix for the current release though.

**Comment by jrainville** [comment]
I'll close this issue, as it will be fixed by the refactor here https://github.com/status-im/status-go/issues/4351
