### ISSUE TITLE
[Wallet/Graph] Implement marquee drag to set timeframe

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13863]
### Description

[Figma ](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-200050&mode=design&t=34EV2UEyI0MiAakf-4)

<img width="1600" alt="Account with history (2 years) - chart expanded (ALL)(1)" src="https://github.com/status-im/status-desktop/assets/31625338/5ae5a070-e00f-44ff-8f2f-e74a17e96917">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
