### ISSUE TITLE
[Wallet/Graph] Review and update timeframe views if necessary in both minimized and maximized views

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13861]
[Figma minimized view](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-241669&mode=design&t=yjnzE24T4UQZUDqD-4)

<img width="1188" alt="Hover Tx" src="https://github.com/status-im/status-desktop/assets/31625338/51a9ee5c-99b7-4709-86ed-b45fbb35cdc7">

[Figma maximized view](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-200046&mode=design&t=34EV2UEyI0MiAakf-4)

<img width="1188" alt="Account with history (2 years) - chart expanded (ALL)" src="https://github.com/status-im/status-desktop/assets/31625338/2f5d0085-cfd4-44e4-aeaa-f8ba0c5dcd6b">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
