### ISSUE TITLE
Fix CollectiblesView storybook page

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#13866]
### Description

The storybook page `CollectiblesView` became glitchy after https://github.com/status-im/status-desktop/pull/13849

![image](https://github.com/status-im/status-desktop/assets/11161531/23a7415f-5e6e-41e6-839b-06d593bda7ad)

Apparently there's some weird interaction between:
- ListModel
- SFPM
- Using a proxyRole inside a filter

The real app works perfectly fine and the StoryBook page worked fine before the changes in that PR, so it might be some thing that nim models have and ListModel doesn't that's causing the SFPM to misbehave.

**Comment by caybro** [comment]
@dlipicar why not fix the issue right there in your PR (https://github.com/status-im/status-desktop/pull/13849) where you introduced it? :)

**Comment by caybro** [comment]
This is fixed now, the page works, besides some occasional reload problem
