### ISSUE TITLE
[Wallet/Graph] Review and implement custom timeframe

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13864]
### Description

Setting custom range to calendar [figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=19263-313606&mode=design&t=34EV2UEyI0MiAakf-4)

[Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=19262-302683&mode=design&t=34EV2UEyI0MiAakf-4)

<img width="1600" alt="Custom timeframe selection - maximised chart" src="https://github.com/status-im/status-desktop/assets/31625338/978a83eb-2472-45b8-ad3b-468cf8d9be2f">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
