### ISSUE TITLE
[Wallet/Graph] Add date fetching loading and failed states

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13887]
### Description

Data loading ([figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17057-41730&mode=design&t=WAhOgGbvkmCel760-4))

<img width="1188" alt="1W" src="https://github.com/status-im/status-desktop/assets/31625338/72fb93c7-5852-4569-bbee-8a10d0f95271">

Data fetch failed ([figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=19262-303976&mode=design&t=kDJ8xwojNqwNMZX3-4))

<img width="1600" alt="Custom timeframe failed to load - maximised chart" src="https://github.com/status-im/status-desktop/assets/31625338/1c877568-1a05-41aa-83ff-85776f731787">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
