### ISSUE TITLE
[Profile Showcase] Add network prefixes in profile showcase accounts delegate and include them in the searcher

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13899]
### Description

1. Account address delegate should include network prefixes ([figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460%3A40362&mode=design&t=Cg21jqu5IMq2bvFm-1)):

<img width="739" alt="Screenshot 2024-03-08 at 09 48 52" src="https://github.com/status-im/status-desktop/assets/97019400/1f4ceb97-a76b-435f-a70e-3186db2636bc">

2. Add network prefixes in the [search criteria](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=4592%3A437039&mode=design&t=Cg21jqu5IMq2bvFm-1):
<img width="739" alt="Screenshot 2024-03-08 at 09 51 50" src="https://github.com/status-im/status-desktop/assets/97019400/f9f48bcd-2775-4267-93a5-e221d4542ec7">

---
**NOTE for dev:**
- Currently in profile showcase we are using `WalletStore` to get the `accounts` model. This model doesn't contain information about the network prefixes.
- On the other hand the `Wallet Root Store` contains another reference to `accounts` model but in this case the model contains more extended data ([including network prefixes](https://github.com/status-im/status-desktop/blob/49f7accbc21012cc00fb06b3d693a4c6f6e26917/src/app/modules/main/wallet_section/accounts/model.nim#L21)).

I can see 2 different approaches here. Please analyse the pros and cons and decide which is the best one:
1. Replace the existing wallet store accounts model and use the root store one. To do that, we will need to apply a SFPM in the new accounts model to only display my own wallet accounts (filter watched accounts). Doing this we are breaking a bit the current approach where in the profile section only the wallet store is used.
2. Extend accounts model from wallet store with the needed network prefixes data.

_Originally posted by @alexjba in https://github.com/status-im/status-desktop/pull/13819#discussion_r1514439896_

**Comment by noeliaSD** [comment]
cc: @Khushboo-dev-cpp

**Comment by noeliaSD** [comment]
We can also include on this task, the filtering need to only show my own accounts (and not the watch-only ones).

**Comment by caybro** [comment]
I think this is a must for the 2.28 milestone, we shouldn't be exposing anything in the Showcase that doesn't belong to us; once we (and the ppl) start doing that, it will be hard to revert/fix that later
