### ISSUE TITLE
Slow startup time when switching to 2.27 RC6

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#13909]
# Bug Report

## Description

Application launch to beta confirmation screen took 6+ minutes. The app appears to become unresponsive at multiple stages, most obviously when the spinning Status loading stops.

Geth log supplied to @igor-sirotin  for troubleshooting.

### Additional Information

- Status desktop version: 2.27 RC6
- Operating System: Mac

**Comment by jrainville** [comment]
I don't think anyone else faced this issue. Reopen if you face it again
