### ISSUE TITLE
Integrate collectibles search into Community Permissions

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#13923]
UI side of parent epic

[Design](https://www.figma.com/design/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?node-id=53874-101256&t=RIMJzYaobu7ICeaj-0)

**Comment by noeliaSD** [comment]
I assign to myself to do the analysis and understand the scope
