### ISSUE TITLE
[Wallet/Graph] Implement TX markers&clusters interactions in maximized graph

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13935]
### Description

[Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=19087-335106&mode=design&t=vH4AdQ1XPRzrDjtY-4)

<img width="1600" alt="Account with history (2 years) - chart expanded (ALL)(2)" src="https://github.com/status-im/status-desktop/assets/31625338/976e168f-363c-4fdb-b192-0b2a09dc29da">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
