### ISSUE TITLE
[Wallet/Graph] Implement TX markers clusters in maximized graph

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13934]
### Description

[Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=19089-342721&mode=design&t=vH4AdQ1XPRzrDjtY-4)

<img width="1600" alt="Account with history (2 years) - chart expanded (ALL)(1)" src="https://github.com/status-im/status-desktop/assets/31625338/c7edbafb-864c-412b-93b8-723147940468">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
