### ISSUE TITLE
[Wallet/Graph] Implement TX markers in maximized graph

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13933]
### Description

[Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=17033-202854&mode=design&t=vH4AdQ1XPRzrDjtY-4)

<img width="1600" alt="Account with history (2 years) - chart expanded (ALL)" src="https://github.com/status-im/status-desktop/assets/31625338/d7cb1df0-4996-4d07-91e1-76cd9d7af418">

**Comment by noeliaSD** [comment]
Due to priorities and team capacity, moved to next milestone.
