### ISSUE TITLE
[Profile Showcase] Preview data should contain the dirty state but now it's only refreshed with saved data

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13949]
### Description
Right now the preview view is populated with saved data instead of dirty state data:

https://github.com/status-im/status-desktop/assets/97019400/bfc14aea-e3b3-4fe3-b7ad-d14076cd8cc3

In this task we should work on updating the models used on preview and use the dirty data instead of the saved data so we have a **live preview**.

**Comment by caybro** [comment]
Tagging as a "bug", this was working correctly before
