### ISSUE TITLE
[Profile Showcase] Align UI save flow according to backend response

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#13950]
### Description
Here the [design flow](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460%3A26771&mode=design&t=bBHrSG41SkFffTXt-1):

- Right now backend save action in profile settings / preferences is an async task that can take some time. To have a better UX, a loading state in the save button should be added until the backend response is received and cancel button is disable during this `in progress` state. The UI will be in this loading state for a maximum time of 5 seconds, otherwise it will consider the action as a failure (so failure flow to follow):
<img width="663" alt="Screenshot 2024-03-14 at 11 07 53" src="https://github.com/status-im/status-desktop/assets/97019400/4fddbe3f-695b-46f0-9520-dd7479289dde">

- When the action has succeded a signal will be received from the backend and a toast message will be shown:
<img width="663" alt="Screenshot 2024-03-14 at 11 09 48" src="https://github.com/status-im/status-desktop/assets/97019400/3f4594d4-3052-4752-a169-5ff17041d36e">

- When the action has failed, a signal will be received from the backend and a toast messages will be shown (dirty state changes will be kept, only user can discard the changes by pressing Cancel button):
<img width="663" alt="Screenshot 2024-03-14 at 11 10 16" src="https://github.com/status-im/status-desktop/assets/97019400/d4850504-3541-4c23-8b9e-ebc2405ba2d1">

**NOTE**: Here the corresponding **User Story** --> https://www.notion.so/Save-changes-25b1c4ebeb214f22949ea72f312247ba

**Comment by alexjba** [comment]
My proposal here is to add a loading state for 5 sec max and call `reset` if the dirty state is not cleared in this time. This should handle the error case until we'll have backend notifications on `save` errors.

Adding an indefinite loading state can block the user in the profile settings page in case of backend error.

**Comment by noeliaSD** [comment]
@alexjba @MishkaRogachev please take a look at this new flow agreed with @benjthayer .

I'll create the corresponding task for the backend where the signals need to be added.

**Comment by noeliaSD** [comment]
This is the backend related task: https://github.com/status-im/status-desktop/issues/13968

**Comment by noeliaSD** [comment]
It's worth it to take a look at this in here:
- It seems `ProfileStore` is instanciated multiple times so we will need to resolve this, otherwise we can have multiple toasts among other things.

_Originally posted by @noeliaSD in https://github.com/status-im/status-desktop/issues/13969#issuecomment-1997587339_

**Comment by MishkaRogachev** [comment]
> * ProfileStore

I assume we have `ProfileSectionStore` instantiated multiple times in the application, but the profile section will only use one instance of it
