### ISSUE TITLE
Create New Community: validation and ensuring min. 1 tag added

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13966]
A couple of changes have been made to the way we validate the Create New Community form.

1) The community Owner should be made to add a minimum of 1 tag
2) The `Next` and `Create Community` buttons should not be disabled if mandatory fields are not complete. Instead, upon clicking the button, all incomplete fields should be validated and the dialog should scroll up as necessary to ensure the first of the validated fields is in view. This is a much more user-friendly way to handle form validation as it directs the user to mandatory fields which require their attention (whilst avoiding the visual clutter of asterix's by each field and needing to find room for the corresponding legend on all of our forms).

We should also consider adding this method of validation to other forms/flows such as Edit Community and Create/Edit channel for consistency. Please await @John-44 's seal of approval prior to developing.

--

**Create New Community flow change summary** 

1) The `Next` button in the toolbar on the first step of the form should not be disabled even if mandatory fields are incomplete or completed in the wrong format for the field.
<img width="549" alt="Screenshot 2024-03-14 at 8 45 25 AM" src="https://github.com/status-im/status-desktop/assets/110033914/8536478d-b902-46f7-b6ae-2c36b8cabf6c">

2) When the user clicks the `Next` button, the dialog should auto-scroll to the top validated field that requires their attention
<img width="548" alt="Screenshot 2024-03-14 at 8 46 32 AM" src="https://github.com/status-im/status-desktop/assets/110033914/ae7a9c86-e568-4966-b934-07cd63fc335e">

3) If the user completes ALL mandatory fields in a format accepted by each respective field, clicking `Next` again should take the user to the next step in the flow

4) If the user clicks `Next` when any fields are still empty or validated, the dialog should auto-scroll as required to ensure the first validated field is in view. 

5) Community tags are now validated if the user has not yet entered a min. of 1 tag

------

**Community tags change summary**

Due to the new rule that the community Owner must enter at least 1 tag for their community:

i) When the user adds their first tag, that tag cannot be removed. If the user hovers the close `X` on that tag, a tooltip should populate reading `Your community must have at least 1 tag`

ii) When the user has added >1 tag, they are free to remove all but the final tag (see i)

-------

Other things to consider:
- We probably shouldn't block the user input for the `Community introduction and rules` and `Leaving community` fields message once they have hit the character limit. Community Owners may want to copy and paste or type a large amount of text and then edit down until they are within the limit (similar to how we now handle longer messages by validating but not preventing user input beyond the character limit). 

Link to Figma:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=52741-266923&mode=design&t=DE3K3NFx04sRPX3x-4

**Comment by benjthayer** [comment]
This relates to [11538](https://github.com/status-im/status-desktop/issues/11538)

**Comment by John-44** [comment]
@iurimatias +1 on approval from me.  Could we add this to 2.29?  Because it would be good to enforce a minimum of 1 tag per community prior to the release of the Mobile beta.
