### ISSUE TITLE
Community links have a random tag encoded

### ISSUE THREAD

**Issue by felicio** [status-im/status-desktop#13963]
# Bug Report

## Description

- Community links have a random tag encoded

## Steps to reproduce

- Right-click a Community in sidebar > Invite People > copy link
- Visit the link in remote browser
- Again, right-click the Community in sidebar > Invite People > copy link
- Visit the link in remote browser

#### Expected behavior

- Encoded tag match Community's settings

#### Actual behavior

- Randnom tag is encoded

### Additional Information

- Status desktop version: `2.27.0-rc.6`
- Operating System: `macOS 14.1.1 (23B81)`

**Comment by prichodko** [comment]
@xAlisher has been testing the URL today and he run into this again. 

> Tags "Collaboration, design, web3"
> Link https://status.app/c/G5QAAMSIdR2guHMRTlnZT5f4erKQq-2TbJQiCUmxoReB2xiepwjhk-qR_qTEFJ-mt37dDJ7-LCFnhGKkHOcFYoS5Tve8nw-v-Y73PNSQsPtNqFuXF57z-X3C-3zbA4J6CchgjynLfLtnARXyuRURHdsa#zQ3shVpDLHzmkXfN6X5hnuQThFB3gcewgvQjJMHyiahm5qVcc
> 
> Changing tags to "Collaboration, design, Ethereum"
> Link https://status.app/c/G5QAAMSwbY9oYiTijSiesmURLRE9WcjV9kk2SpGEpNjQi8BtDM9ThPBJ9cg_JbPeE6Xql5Tg6c8SckYoRsoxVxAjzHW65z4PV7njLrMQErbfhLp1eeE5z_eEe956QFAvARnsMWUpt93RaF3IrTAYR-EB#zQ3shVpDLHzmkXfN6X5hnuQThFB3gcewgvQjJMHyiahm5qVcc
> 
> Link is different
> 
> For the first link in first seconds it shows tags I never used (Privacy, food, entertainment) then shows (web3, colaboration, design)
> For the second link in first seconds it shows also tags I never used (Software, Event , Commerce) then shows outdated (web3, colaboration, design)

There is also an issue that waku has outdated information, but relevant part here is that it shows tags that haven't been used.

**Comment by igor-sirotin** [comment]
@xAlisher @prichodko 

I suppose Status Desktop 2.28.1 was used to create those links?
The fix https://github.com/status-im/status-go/pull/4992 will only be released in 2.29.0. I tried your community with [2.29.0-rc4](https://github.com/status-im/status-desktop/releases/tag/2.29.0-rc.4), here's the link I got:

https://status.app/c/G1IAAMTaOUjqF2UyXkaDlMWyGsSsflOGL3jAxZdT5b3VJcBETrQs_X6okUb-fbo6GJw8S4hGEILGgu6Usy8LHq8CqknyKpjqKCqyGg==#zQ3shVpDLHzmkXfN6X5hnuQThFB3gcewgvQjJMHyiahm5qVcc

Tags look correct to me 🙂

-----

Here's what I get before fetching from waku (pure URL info):

<img width="550" alt="Screenshot 2024-05-28 at 11 35 56" src="https://github.com/status-im/status-desktop/assets/25482501/8bd7b0e1-f1fc-4e76-8412-d89cd27d3c5d">

And this is after updating from waku:

<img width="550" alt="Screenshot 2024-05-28 at 11 36 02" src="https://github.com/status-im/status-desktop/assets/25482501/96e34ada-25b1-45b4-a896-91f6635a33dd">

**Comment by jrainville** [comment]
I'll close as it seems it was fixed in 2.29. If you can still reproduce in 2.29, please reopen
