### ISSUE TITLE
feat(wallet) save group settings for collectibles

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#13971]
The current `ManageTokensController` doesn't save the order of groups (`m_collectionGroupsModel`). Also the api on the backend is missing.

- [x] Implement backend for saving collectible group order and visibility
- [x] Add support in the front end for saving and loading of group settings `ManageTokensController`
  - Implemented in https://github.com/status-im/status-desktop/issues/13276

Notes:
- This experiment was trying to do that using the existing collectible API https://github.com/status-im/status-desktop/pull/13970
- The groups, hidden groups, hidden items and items in `ManageTokensController` are tightly coupled and the order of updating is sensitive to change and have to be untangled

**Comment by caybro** [comment]
Just FYI, I'm working on the second point at the moment, as part of https://github.com/status-im/status-desktop/issues/13276; almost done, will post a PR today or tomorrow

**Comment by stefandunca** [comment]
> Just FYI, I'm working on the second point at the moment, as part of #13276; almost done, will post a PR today or tomorrow

It sounds like you will conflict with my work here: https://github.com/status-im/status-desktop/pull/13903, please be mindful of my changes. Maybe first take a look there

**Comment by caybro** [comment]
> > Just FYI, I'm working on the second point at the moment, as part of #13276; almost done, will post a PR today or tomorrow
> 
> It sounds like you will conflict with my work here: #13903, please be mindful of my changes. Maybe first take a look there

Thanks, will have a look! Sorry for not having it done earlier, too busy :/

**Comment by stefandunca** [comment]
I was investigating why collectibles order is not properly stored. It seems the collectibles type doesn't arrive in DB properly. Now debugging the entire data chain to see where it is lost

**Comment by stefandunca** [comment]
Implemented with the last rebase here: https://github.com/status-im/status-desktop/pull/13903
