### ISSUE TITLE
Crash when save changes after editing community

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#13985]
# Bug Report

After editing community and clicking button Save changes the app crashes

## Steps to reproduce

1. Create community
2. Edit community - name, description etc.
3. Click Save changes button

#### Expected behavior
Changes are saved, community overview with new parameters displayed
#### Actual behavior
The app crashes
### Additional Information

- Status desktop version: the latest master build
- Operating System: masOS Ventura 13.5

**Comment by alexjba** [comment]
Cannot reproduce on latest master

@Valentina1133 Do we need any specific community/channel config? E.g. Community tokens, community members, community permissions, channel permissions etc.

**Comment by jrainville** [comment]
I tried as well with a basic community and then with a community with tokens and permissions and both worked fine

**Comment by Valentina1133** [comment]
Hi! I just checked on the latest master on my Mac. I cannot reproduce it anymore either. So let's close it then
