### ISSUE TITLE
Unable to Confirm Changes to Existing Community Permission

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-desktop#13989]
# Bug Report
When users have already reached the maximum limit of five community membership permissions, they are unable to save edits to existing permissions.

## Steps to reproduce
- Create or open a community
- Go to the permissions tab in the community settings
- Create 5 community 'become a member' permissions
- Try to edit one of the 5 'become a member' permissions

#### Expected behavior
Should be able to make changes to existing permission.

- Status desktop version: Nightly
- Operating System: MacOS

<img width="1512" alt="Screenshot 2024-03-15 at 15 41 43" src="https://github.com/status-im/status-desktop/assets/19279756/f2dbcb68-4cde-43bf-87a7-235d37cbbed6">

**Comment by anastasiyaig** [comment]
@John-44 @benjthayer is it indeed a requirement? Where is it coming from?

**Comment by caybro** [comment]
Ah I get the problem now; so we have this limit of `5` and that's fine (as designed). But the real issue here is that once you have those 5 permissions, you can't make/save any changes to any of them since the "Save" button is then disabled:

```qml
readonly property bool saveEnabled: root.isFullyFilled
                     && !root.permissionDuplicated
                     && !root.permissionTypeLimitReached
```

**Comment by caybro** [comment]
> @John-44 @benjthayer is it indeed a requirement? Where is it coming from?

Yes, confirmed with Ben, the limit should be indeed `5`

**Comment by benjthayer** [comment]
> Ah I get the problem now; so we have this limit of `5` and that's fine (as designed). But the real issue here is that once you have those 5 permissions filled-in, you can't make/save any changes to any of them since the "Save" button is then disabled:
> 
> ```qml
> readonly property bool saveEnabled: root.isFullyFilled
>                      && !root.permissionDuplicated
>                      && !root.permissionTypeLimitReached
> ```

Yeah the user should still be able to edit the 5 existing permissions. Unless of course, in doing so, they would be creating a 6th permission for another role eg Admin
