### ISSUE TITLE
[DesignAssets] List of all the illustrations and assets used in the app

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#14000]
### Description
**Context:**
The design team is planning to replace the desktop illustrations with the mobile ones.

**What to do:**
Gather a list of all the illustrations and assets used in the desktop app and provide it to design with their name and location in the app.

**Comment by alexandraB99** [comment]
@Francesca-G fyi

**Comment by noeliaSD** [comment]
Shared with @pedro-et the global folder: https://github.com/status-im/status-desktop/tree/master/ui/imports/assets/png

cc: @caybro

**Comment by caybro** [comment]
Is this still desired @Francesca-G ?

**Comment by Francesca-G** [comment]
> Is this still desired @Francesca-G ?

we're using the global folder: https://github.com/status-im/status-desktop/tree/master/ui/imports/assets/png provided. So if you can confirm everything's there I think we're good :)

**Comment by caybro** [comment]
> > Is this still desired @Francesca-G ?
> 
> we're using the global folder: https://github.com/status-im/status-desktop/tree/master/ui/imports/assets/png provided. So if you can confirm everything's there I think we're good :)

Yup, should be fine!
