### ISSUE TITLE
Permissions evaluation doesn't work for values >=1000

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#14006]
# Bug Report

## Description

Once the permissions value exceeds 999, the permissions evaluation doesn't work.

## Steps to reproduce

See video:

https://github.com/status-im/status-desktop/assets/33099791/597ac8a0-74e3-4cea-a0be-a1b15cc5ddd7

#### Expected behavior

Member does't satisfy the criteria and is kicked from channel.

#### Actual behavior

Member does satisfy the criteria and stays on channel.

### Additional Information

- Status desktop version: master (79fa3795ca4ef1233a1e3f7185dcd8c0f26c1c38)
- Operating System: Fedora

**Comment by caybro** [comment]
Might be related to https://github.com/status-im/status-desktop/issues/11918 ?
