### ISSUE TITLE
Closing a chat with unread message should clear the unread badge

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14025]
### Description

@benjthayer wdyt?

https://github.com/status-im/status-desktop/assets/82375995/996ab0dd-9e08-43fe-87ce-fbdddc1e8196

**Comment by anastasiyaig** [comment]
@jrainville is it possible to clear unread badge on chat left section and app icon?

**Comment by benjthayer** [comment]
> ### Description
> @benjthayer wdyt?
> 
>  Screen.Recording.2024-03-19.at.11.41.40.mov

Hey @anastasiyaig yes, I agree. If a chat is closed and any of that chat's badges are removed as a result, the global Messaging app badge number should be reduced by the same factor. The Messaging app badge should show the aggregate number of the badges from chats inside the app.

cc @John-44

**Comment by jrainville** [comment]
Yeah it makes sense. I'll add that to 2.29
