### ISSUE TITLE
Balance is not updated even after 2 restarts

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14035]
### Description

https://sepolia-optimism.etherscan.io/address/0x81e458A21D7d4870254A91977081Ac6281830310

<img width="1728" alt="Screenshot 2024-03-19 at 16 32 34" src="https://github.com/status-im/status-desktop/assets/82375995/c783cff6-8b11-434b-8c22-1f98122839dd">

I've sent 0.1 eth from one account to another on sepolia optimism. Even the transaction is completed and i restarted the app twice, the balance is not showing up

**Comment by anastasiyaig** [comment]
@alaibe pls take a look what is happening there?

**Comment by dlipicar** [comment]
@rasom

**Comment by anastasiyaig** [comment]
Thats done and merged
