### ISSUE TITLE
Admin permission is not recognized

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14036]
### Description

1. create community (Sepolia)
2. mint ownertoken and token master tokens (mainnet)
3. add member to that community
4. create a permission of 1 STT to become an admin for the community
5. send 1 stt to the member so he can match the requirements
6. as member, check if you can manage the community (create channel for example)

**Result:** user matching the requirement to become an admin has no admin rights

<img width="1659" alt="Screenshot 2024-03-19 at 17 18 46" src="https://github.com/status-im/status-desktop/assets/82375995/42cad6da-e965-42fc-8ce8-36d6fc3a41cd">

<img width="1512" alt="Screenshot 2024-03-19 at 17 18 53" src="https://github.com/status-im/status-desktop/assets/82375995/0e2c5b51-9a93-48a1-8fc9-01f4fbf9508e">

<img width="1512" alt="Screenshot 2024-03-19 at 17 22 33" src="https://github.com/status-im/status-desktop/assets/82375995/425ab131-edb9-4c4b-80e7-e9b52f0b8634">

**Comment by cammellos** [comment]
@jrainville it might be the issue I mentioned, if you give me until EOD I might have a PR out, I already fixed it in my code
