### ISSUE TITLE
[StatusMenu] StatusSuccessAction is not taking into account text content Width

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#14037]
### Description

When having a StatusSuccessAction in StatusMenu, the menu width is not fitting the StatusSuccessAction text if this is larger than the menu.

![sm](https://github.com/status-im/status-desktop/assets/31625338/877e1670-d481-46e7-8168-eb4919a1aff8)

**Comment by caybro** [comment]
@benjthayer should this popup resize after clicking, or should it stay the same width with text elided? (consider the fact that translated texts here can vastly differ in width)

**Comment by benjthayer** [comment]
> @benjthayer should this popup resize after clicking, or should it stay the same width with text elided? (consider the fact that translated texts here can vastly differ in width)

Hey @caybro ideally the menu would be show at the size required without being elided or having to grow. We can of course consider a max width for the menu - lets see what some of the worst case scenarios look like for menu width and we can take it from there on that.

**Comment by noeliaSD** [comment]
Moved to next milestone due to team capacity and priorities.

**Comment by noeliaSD** [comment]
> > Moved to next milestone due to team capacity and priorities.
> 
> We have a PR for this already

Where is it and which is the status of it?

**Comment by caybro** [comment]
> > > Moved to next milestone due to team capacity and priorities.
> > 
> > 
> > We have a PR for this already
> 
> Where is it and which is the status of it?

Hmm.. maybe not; I thought I'd see nit somewhere
