### ISSUE TITLE
Profile showcase management: Search shouldn't affect the preview

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#14040]
# Bug Report

## Description

The filtering done via search bar should be local thing to particular tabs, not affecting external world, preview in particular. Ideally this logic should be moved to the view from `ProfileShowcaseDirtyState.qml`.

Note: Currently `ProfileShowcaseDirtyState.qml` in `changePosition` doesn't take this search sfpm when mapping to source what can cause some undesired behaviors.

[Kazam_screencast_00098.webm](https://github.com/status-im/status-desktop/assets/20650004/f648dc77-785d-4acb-9a65-e6299102102c)

## Steps to reproduce
1. Go to Settings -> Profile -> Accounts
2. Make window wider to activate preview
3. Use the search bar

#### Expected behavior
Search doesn't affect preview.

#### Actual behavior
Preview is also filtered.

**Comment by alexjba** [comment]
Need to fix this for #13682
