### ISSUE TITLE
Saving profile image changes ENS display name to non-ENS

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14048]
# Bug Report

## Description

1. Restore account that uses ENS
2. Remove restored profile picture
3. Add new profile picture
4. Click on save
5. ENS name is overwritten with display name set during restore

Note: ENS display name is reapplied after restart

https://github.com/status-im/status-desktop/assets/50769329/2a25d37e-b297-404d-881a-b677924a7bfa

- Status desktop version: 2.27
- Operating System: Mac

**Comment by anastasiyaig** [comment]
@jrainville ^^

**Comment by kounkou** [comment]
Currently facing a roadblock with having an ENS name available for my testings.

**Comment by kounkou** [comment]
Hi there, I am a little bit confused by step `5. ENS name is overwritten with display name set during restore`, what do you mean by `during restore` ? 
I thought the restore of the account is by `seedphrase` for instance and done, and then the issue appears here during the saving, after the profile image is updated like shown on on the video.

**Comment by glitchminer** [comment]
Hey @kounkou , it just means that the display name reverted from ENS to a previously used one. In this case the previously used one was applied during the restore from seedphrase process.

**Comment by kounkou** [comment]
Hey @glitchminer 
I managed to setup a ENS name, but couldn't get to reproduce the issue on master.
Would you mind giving it a try on master? This would help me understand if my ENS name setup has something to do with the result of the test.
I'll also check on my side with 2.28.1 to avoid being blocked for now.

[Screencast_from_2024-05-13_075635_AM.webm](https://github.com/status-im/status-desktop/assets/2589171/88d98c5a-545d-47b3-95bf-b072c7c1b8c9)
