### ISSUE TITLE
Crash on editing display name field

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14047]
# Bug Report

## Description

Entering a new character in the display name field causes the app to crash.

```
DBG 2024-03-19 22:33:02.383+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
DBG 2024-03-19 22:33:04.693+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
DBG 2024-03-19 22:33:14.383+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
DBG 2024-03-19 22:33:17.374+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_isDisplayNameDupeOfCommunityMember
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [run-macos] Segmentation fault: 11
```

## Steps to reproduce

Open profile settings, attempt to add a character to the display name.

App crashes.

Notes: As it seems relevant to `wakuext_isDisplayNameDupeOfCommunityMember`, the account is a member of 6 communities (previously could have been ~20+ but they didn't show up after restore). 

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by caybro** [comment]
CC @MishkaRogachev

**Comment by anastasiyaig** [comment]
@jrainville thats for RC i guess (moved there, feel free to change)
