### ISSUE TITLE
Empty category is not displayed in community from member side

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#14059]
# Bug Report

Member of community doesn't see the category created by admin out of channel

1. Create new community
2. Add member
3. Create empty category (do not tick checkbox)

https://github.com/status-im/status-desktop/assets/82375995/0e212dda-a82b-497a-a26d-396b2b92e8cc

#### Expected behavior
Empty category is displayed and can be seen by admin and member

#### Actual behavior
Empty category is displayed and can be seen by admin, but it is not displayed and cannot be seen by member

### Additional Information
Category get displayed if admin edit category and tick checkbox 

- Status desktop version: the lates master build
- Operating System: macOS Ventura 13.5

**Comment by anastasiyaig** [comment]
@jrainville pls add to some milestone
