### ISSUE TITLE
Clicking on activity center mentions does not open necessary chat and scroll to message

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#14063]
# Bug Report

## Description

If I open the activity center with mentions and click on it - I should move to the necessary section, open the correct chat and scroll to the message, but it doesn't work now (only reply works, but from time to time (see video))

## Steps to reproduce

1. Have a community channel with a lot of messages (you should have few channels and last channel visit must be not the channel where you were mentioned)
2. Have a mention
3. Click activity center mention to see the message

#### Expected behavior

The correct channel is opened and scrolled to the message

#### Actual behavior

https://github.com/status-im/status-desktop/assets/117639195/4776dc7b-50ab-4508-9a5b-ccb9aab55730

### Additional Information

- Status desktop version: 2.27.0, master
- Operating System: macos

**Comment by jrainville** [comment]
I think this was fixed by @friofry or @igor-sirotin in master
