### ISSUE TITLE
View member messages popup in members settings does not render stickers and images

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#14060]
# Bug Report

## Description

View member messages popup in members settings does not render stickers and images

## Steps to reproduce

1. Add images or sticker
2. Go to Community settings -> Members -> and View member messages

#### Expected behavior

Images and stickers are rendered correctly

#### Actual behavior

Images and stickers are not rendered

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/status-go/pull/5131
