### ISSUE TITLE
Requirements check in `JoinCommunityView` are using selected addresses instead of all

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14088]
### Description

1. Initially, `JoinCommunityView` page uses ALL wallet accounts a user can have to determine if requirements are met.
2. After going through the `ShareAddresses` flow, and unselecting some accounts, then closing the popup, `JoinCommunityView` uses these new accounts selection to determine if requirements are met so it can cause an undesired situation where user is no longer able to go through the _reveal your addresses flow_.

Here a video for better understanding:

https://github.com/status-im/status-desktop/assets/97019400/bf994632-5715-4b9e-84dc-e242b1e86c36

**Summary:** `JoinCommunityView` page should allways consider ALL wallet accounts a user has.

**Comment by noeliaSD** [comment]
cc: @jrainville

**Comment by jrainville** [comment]
I'll put this a 2.29 as I don't think this is a blocker for the release. It's pretty annoying, but a niche use case. Restarting the app would fix it.

**Comment by caybro** [comment]
> @noeliaSD , @caybro I have a question related to this ticket.
> 
> When we click Reveal accounts - we fetch all account info. When we are unselecting an account - we are doing go request and fetching all account info, but this time without an unselected account (and updating the model).
> 
> The question is: taking into account that our model already contains all data for all accounts - do we need to do another request to status-go but without an unselected account? Couldn't we filter out this info on a UI?

Filtering in the UI would be quite hard I'd say in this case; we should do another request imho; thoughts @micieslak ?

**Comment by noeliaSD** [comment]
> @noeliaSD , @caybro I have a question related to this ticket.
> 
> When we click Reveal accounts - we fetch all account info. When we are unselecting an account - we are doing go request and fetching all account info, but this time without an unselected account (and updating the model).
> 
> The question is: taking into account that our model already contains all data for all accounts - do we need to do another request to status-go but without an unselected account? Couldn't we filter out this info on a UI?

Let me try to re-write just in case I'm wrong:

These are the 3 elements that interact here:
** Accounts model 
** JoinCommunityView
** CommunityMembershipDialog

You say that `Accounts model` is shared by these 2 views and each item contains a "selected" role that is used to take into account whatever needed in the 2 views. Am I right?

If, this is the case I guess the UI has in one shot the complete data (if you ensure the model is correctly updated) AND we can do the calculation of the permissions met omitting the `selected` criteria in case of `JoinCommunityView` AND taking into account the `selected` criteria in case of `CommunityMembershipDialog`.

Again, if I'm correct with the explanation, I don't see the need of fetching data twice.

The question is.. WHERE the MET criteria is evaluated?

**Comment by jrainville** [comment]
@kounkou do you think this issue is related to the one you are fixing right now?

**Comment by kounkou** [comment]
> @kounkou do you think this issue is related to the one you are fixing right now?

Hum, I am still trying to understand what's wrong in my ticket but what I am sure of is that the status-go function called `CheckPermissions` doesn't return the expected result. I am confident on this because I mocked the output of that function and everything works as expected.

There is also an opportunity to simplify here, because we possibly don't need the clients to check for permissions themselves and let the control node do that. Except before sending the request to join but as far as I understand this should be in another ticket?
