### ISSUE TITLE
Wallet -> Send: do not show community NFTs in send modal

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14080]
### Description

I am not really sure if we would support sending community NFTs through send modal ( currently only Assets are supported). Until then, lets hide the community minted NFTs in Send modal collectibles tab

Also, it looks like community minted NFT is treated as collection which is wrong

<img width="1796" alt="Screenshot 2024-03-21 at 16 46 34" src="https://github.com/status-im/status-desktop/assets/82375995/5b606609-5dc8-485c-9948-e6cf39e14355">

**Comment by anastasiyaig** [comment]
@benjthayer to confirm

**Comment by benjthayer** [comment]
> @benjthayer to confirm

I agree @anastasiyaig, the assets and collectibles tab component should be removed until the user can send both assets and collectibles - no point showing them if they can't be sent yet. @John-44 is probably better placed to comment on when sending of collectibles should be supported.

In relation to the screenshot attached @anastasiyaig the relevant flows are here:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=21284-137155&mode=design&t=qSXUHdx7JiHtr7ds-4

Any newly received community minted collectibles are automatically put in a relevant Community group. So if I receive 1 collectible from a community, then at the parent list under the collectibles tabs, I should see the community group list item with a count of `1`. 

I think there was a screenshot posted on Discord where the counter was `0` which should never happen. 

<img width="501" alt="Screenshot 2024-03-21 at 2 13 24 PM" src="https://github.com/status-im/status-desktop/assets/110033914/796d030f-9d77-4fd4-b7a7-8aa65c9b60f0">

<img width="1097" alt="Screenshot 2024-03-21 at 2 13 50 PM" src="https://github.com/status-im/status-desktop/assets/110033914/ee23396e-a48d-43f5-a5c8-82f9f4706e6e">

**Comment by alaibe** [comment]
We are going to hide then display them in 2.29. Can we not have them that way for now?

**Comment by anastasiyaig** [comment]
@alaibe my concern is that we are showing collections with 0 items (community tokens are considered as collections at some point which is wrong). we can fix just that and continue working on whatever is planned for 2.29 in this regard
