### ISSUE TITLE
Add missing `eligible to join tag` in `Request to join` community dialog

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14100]
### Description

[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=51863%3A144778&mode=design&t=zG1kYmX1563XWfkH-1)

`Request to join` dialog contains an **eligible to join tag** sticky to the base of the dialog with the relevant highest possible role the user can join the community as based on their aggregated token balances across all of their Status accounts

![image](https://github.com/status-im/status-desktop/assets/97019400/47aa61ae-7704-48df-a828-2218682fed4b)

- Build the tag with the necessary logic
- Add the tag in the `Request to join` dialog
- Add the tag also in `Shared addresses` dialog / panel:

<img width="613" alt="Screenshot 2024-03-22 at 11 00 19" src="https://github.com/status-im/status-desktop/assets/97019400/1417b5dc-7328-4a51-b206-271a21d649bc">

**Comment by caybro** [comment]
Could be eventually postponed to 2.29 if not enough space in 2.28.1
