### ISSUE TITLE
Add missing state in `JoinCommunityView` when communiy ONLY has private permissions and they are NOT MET

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14104]
### Description

[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=31357%3A559352&mode=design&t=ZVKAVuLOVzr6HY1n-1)

![Screenshot 2024-03-21 at 19 50 28](https://github.com/status-im/status-desktop/assets/97019400/e1f20e6b-cd93-4b56-b767-9c09cc31b345)

This view must be shown when the communiy **ONLY** has **private** permissions and they are **NOT MET**

**Comment by noeliaSD** [comment]
cc: @jrainville

**Comment by jrainville** [comment]
I think this one is a UI team issue. The model should already have all the required values.
It has `isPrivate` and `tokenCriteriaMet`, so if both of those are false, we need to show that screen.
