### ISSUE TITLE
Update shared accounts popup accounts ordering according tokens count and alphabetically

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14101]
### Description

This task is intended to implement 2) and 3) sorting criteria for accounts. The first one, based on checking permissions against a single account is moved to a separate ticket as a much more complex one.

The first criterion has been excluded to https://github.com/status-im/status-desktop/issues/14192

[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=53109%3A240544&mode=design&t=Groz41dMBGVwD9s1-1)

![Screenshot 2024-03-22 at 12 18 58](https://github.com/status-im/status-desktop/assets/97019400/5beaef7d-3f83-453b-b8f5-1e54fc27468f)

**Comment by caybro** [comment]
Depends on https://github.com/status-im/status-desktop/issues/14102

**Comment by caybro** [comment]
Possible candidate for moving to 2.29

**Comment by micieslak** [comment]
> Possible candidate for moving to 2.29due to the high complexity

Right now it's split and the permissions-related part is excluded to https://github.com/status-im/status-desktop/issues/14192

**Comment by noeliaSD** [comment]
This task is a must after speaking with @benjthayer. The permissions part, as @micieslak did, can be postponed!
