### ISSUE TITLE
Admins and token masters must not see setting the control node functionality

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#14105]
# Bug Report

## Description

Admins and TokenMasters must not see a "Make this device as control node..." option

![image](https://github.com/status-im/status-desktop/assets/117639195/97c4912a-270f-4b96-8808-14df64a171b9)

~~Also need to clarify if admins and token masters should see manage sharding option in the edit community~~

Same applies here:
![image](https://github.com/status-im/status-desktop/assets/117639195/b29c6610-035b-4fa3-9a9a-545cb882f814)

**Comment by jrainville** [comment]
> Also need to clarify if admins and token masters should see manage sharding option in the edit community

They should not
