### ISSUE TITLE
App has 0 peers - launches with `Internet connection lost` banner

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14119]
After a short period of the app working normally, I then get an issue where I have 0 peers.

Upon restarting, the `Internet connection` banner is shown and I see `0` peers in the `Node management` area.

Running 2.27.0 but this issue also happened with 2.26 RC's.

https://github.com/status-im/status-desktop/assets/110033914/c3e4f3c8-3cd8-4cfe-8ed3-277f32d552dc

Happy to provide any more info needed! :)

**Comment by jrainville** [comment]
Oh, I see in you're video that you're not connected to any History nodes. Can you try selecting one? The AMS one usually works fine.

**Comment by benjthayer** [comment]
> Oh, I see in you're video that you're not connected to any History nodes. Can you try selecting one? The AMS one usually works fine.

Ah I see! Thanks! I don't seem to have any options for History Nodes though - should I see something in here? Sorry, it seems I'm THAT annoying user! 🤣

<img width="528" alt="Screenshot 2024-03-22 at 5 24 08 PM" src="https://github.com/status-im/status-desktop/assets/110033914/7161b704-1de9-459e-898c-a86ed097841a">

**Comment by benjthayer** [comment]
@jrainville it seems to be when I quit and restart the app that I get 0 peers - not sure if the logs on this screenshot help? Everything seems to work fine and then as soon as I try and quit and re-open I get 0 peers. 

<img width="1268" alt="Screenshot 2024-03-22 at 5 29 35 PM" src="https://github.com/status-im/status-desktop/assets/110033914/cc25391a-aea4-477a-8db8-c99a4e78579d">

**Comment by jrainville** [comment]
> Ah I see! Thanks! I don't seem to have any options for History Nodes though - should I see something in here? Sorry, it seems I'm THAT annoying user! 🤣

Automatically selecting should work, but I'm not sure why yours doesn't. You can uncheck "Select node atuomatically" and then you'll have a list. Select the `ams` one. That's the one closest to you and it works fine for others.

**Comment by jrainville** [comment]
I assume this doesn't happen anymore. Feel free to reopen if it does
