### ISSUE TITLE
Community Collectible stuck in Minting state if Status closed before finish

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#14116]
### Description

1 - Mint a community token
2 - While on the minting state (before Tx finishes) close Status
3 - Open Status, go to Community Token Management screen

Expected: Token minting finished
Current: Token minting eternally in "Minting..." state

![image](https://github.com/status-im/status-desktop/assets/11161531/9d25b4c1-a9fd-410b-b792-903ba0e3fff8)

The PendingTxTracker does its job (tx is removed from Pending table on startup and the corresponding entry appears on the transfers table), but the Community side doesn't seem to pick up this event.

**Comment by anastasiyaig** [comment]
@dlipicar i belive the root cause of this issue is the same as for the one i logged a while ago https://github.com/status-im/status-desktop/issues/13700

we just dont fetch the transaction data async i guess no matter what happens (app closed, or transaction is processing 10h)

**Comment by anastasiyaig** [comment]
also here is another ticket for stuck minting state https://github.com/status-im/status-desktop/issues/13851

**Comment by dlipicar** [comment]
Closing this for now. My issue is easily reproducible by closing the app right after the minting process begins, we can see if my fix solves those two.
