### ISSUE TITLE
Community collectibles shown as 0-item groups in Send Modal

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#14115]
### Description

![image](https://github.com/status-im/status-desktop/assets/11161531/c977f684-1f39-437b-b70a-faedc1986c76)

**Comment by anastasiyaig** [comment]
i logged that yesterday literally @dlipicar https://github.com/status-im/status-desktop/issues/14080

**Comment by dlipicar** [comment]
> i logged that yesterday literally @dlipicar #14080

sorry, didn't see an issue had been created, closing this one
