### ISSUE TITLE
[Profile Showcase backend] Support assets for the profile showcase for a contact

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#14129]
Continue https://github.com/status-im/status-desktop/pull/13998
- [ ] Add support assets model for the profile showcase. It should fetch assets for provided wallet account addresses, including following:
    - Balances, summarised for all provided accounts 
    - Unverified tokens, including community tokens
 Approach should be close to the collectibles controller
- [ ] Refactor collectible's and asset's synthetic id conversion to utils

Note: tokens can be requested via [buildAllTokens](https://github.com/status-im/status-desktop/blob/master/src/app_service/service/wallet_account/service_token.nim#L80) with `store = false` and collected with `SIGNAL_WALLET_ACCOUNT_TOKENS_REBUILT`. But this may be dangerous, because signal may be handled with the wallet section, communities and etc. Consider to introduce a fetching id that can be compared with the signal received.

**Comment by MishkaRogachev** [comment]
Implementation can provide 2 models that can be joined on the Ui side: one for balances and another for unverified (custom, community) tokens metadata. These support assets models should be built based on data from the following endpoints:

1) [GetBalancesByChain](https://github.com/status-im/status-go/blob/550d74405795e9f419a426c6310929027f5bd48b/services/wallet/api.go#L70) to obtain balances for provided chainIds and wallet addresses and contract addresses.

2) [FindOrCreateTokenByAddress](https://github.com/status-im/status-go/blob/develop/services/wallet/token/token.go#L316) to get custom (community) token metadata: name, symbol, decimal and imageUrl.

**Comment by jrainville** [comment]
Closing as it doesn't seem like we'll support assets in the profile showcase in the end
