### ISSUE TITLE
App consistently crashes when navigating between account tabs

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14120]
App seems to consistently crash when I try to navigate from the collectibles tab of one account to another account:

https://github.com/status-im/status-desktop/assets/110033914/81c729cb-36cc-4e89-8c13-f5dc29e516b4

**Comment by anastasiyaig** [comment]
I cant reproduce , it has to be something else

https://github.com/status-im/status-desktop/assets/82375995/95e14f86-09e8-492c-aaf4-13d360b00871

**Comment by alaibe** [comment]
@benjthayer i cannot reproduce either, could you consider re-import the seed phrase?

**Comment by iurimatias** [comment]
cannot reproduce
