### ISSUE TITLE
Failure to send messages 

### ISSUE THREAD

**Issue by friofry** [status-im/status-desktop#14134]
# Bug Report
Whenever I send a message in group chat using build 2.28-rc1, I see a resend button for the message

## Steps to reproduce
1. Open the release version of Status
2. Send messages in group chat

#### Expected behavior
The message should send normally

#### Actual behavior
The message has not been sent. The Resend button is displayed

### Additional Information
This problem may be related to geolocation (UAE).
Node management displays 6 peers.
Develop build seems to be more reliable.
Changing the history nodes to automatic/manual does't help.

https://github.com/status-im/status-desktop/assets/1083341/5cc75cb1-f434-42bb-a745-8a4e7cdbb2fd

- Status desktop version: 2.28-rc1 
- Operating System: MacOS 14.4

**Comment by jrainville** [comment]
> it has to be fixed in rc2 please update @friofry

This is a different issue than the messaging issue. Somehow he gets the "resend" button for everything. I'm guessing his connection to the store node is not great

**Comment by friofry** [comment]
It turned out that I had "light mode".
After switching to "relay mode" the problem disappeared
<kbd>
![image](https://github.com/status-im/status-desktop/assets/1083341/cfdcb6b9-68a3-4215-a882-fd00203a3406)
</kbd>

**Comment by jrainville** [comment]
Closing. Turns out it wasn't really an issue
