### ISSUE TITLE
Window changes from maximum to normal size when you click on the Dock icon

### ISSUE THREAD

**Issue by friofry** [status-im/status-desktop#14132]
## Steps to reproduce
1. Maximize the Status Desktop window size
2. Switch to another application 
3. Click the Status icon in the system tray Dock
4. The window changes size from maximized to normal size

#### Expected behavior
the application should remain maximized at step 4 (as other applications)

#### Actual behavior
the window should remain maximized

https://github.com/status-im/status-desktop/assets/1083341/dd62005e-8d19-4d0f-9103-255f383a77a1

### Additional Information

- Status desktop version: 2.28.0-rc.1
- Operating System: MacOS 14.4

**Comment by noeliaSD** [comment]
Moved to next milestone due to team capacity and priorities.

**Comment by caybro** [comment]
Analysis; tray icon:
```qml
onActivated: {
    if (reason !== SystemTrayIcon.Context) {
        applicationWindow.makeStatusAppActive()
    }
}
...
function makeStatusAppActive() {
    applicationWindow.hide()
    applicationWindow.show() // <-- BUG !!! this will unmaximize/un-fullscreen the window
    applicationWindow.raise()
    applicationWindow.requestActivate()
}
```

**Comment by caybro** [comment]
Instead of calling `applicationWindow.show()`, we should call the respective `showFullscreen()` or `showMaximized()` depending on the window state.
