### ISSUE TITLE
App is able to be resized more than expected (much smaller)

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14137]
### Description

@benjthayer was testing version `2.28-rc1` and found he is able to resize the app like this:

![image](https://github.com/status-im/status-desktop/assets/97019400/23574b19-2072-44b7-aba0-f5d5c46bbcf2)

**Comment by caybro** [comment]
Moving to 2.29

**Comment by caybro** [comment]
> > This issue is a result of fixing an earlier problem: #13484
> > TLDR, due to missing Qt API, I'm unable to fix both issues at the same time. Thus, I ponder this issue is less severe than the former
> 
> Considering this at a higher level, I would perhaps say that support for different zoom levels is potentially less important than the min app size if there is a choice to be made. I don't think we follow AA contrast ratio etc so perhaps accessibility should be considered holistically (including tab ordering etc) at a later date?
> 
> If we allow the user to reduce the app window infinitely, we are implying that the user experience at smaller sizes is as good as at larger sizes but in reality, at very small sizes, the user may actually miss out on salient information eg clipping of notification banner messaging, missing warnings inside transaction dialogs etc.
> 
> WDYT @caybro @John-44

Yeah of course, there's also this third way to solve the problem: ie to disable the user option set arbitrary UI interface scale factor. Advanced users can still set the custom scale factor using env variables (`QT_SCALE_FACTOR` and/or `QT_SCREEN_SCALE_FACTORS`) via command line. I'll let you judge what's the best outcome here :)

**Comment by benjthayer** [comment]
Hey @caybro I spoke with @John-44 about this this morning and we agreed that not having the min app window functionality is critical and a blocker for future releases. We agreed as per your suggestion that we should remove the scaling section of the `Appearance` settings if needed to ensure the min app dimensions can be re-instated. I will take a look at the design of this as a priority this morning

**Comment by caybro** [comment]
> Hey @caybro I spoke with @John-44 about this this morning and we agreed that not having the min app window functionality is critical and a blocker for future releases. We agreed as per your suggestion that we should remove the scaling section of the `Appearance` settings if needed to ensure the min app dimensions can be re-instated. I will take a look at the design of this as a priority this morning
> 
> cc @iurimatias

Alright, thanks for the heads up! Removing is easy :)

**Comment by caybro** [comment]
This is how it looks with the UI scale option removed:

![image](https://github.com/status-im/status-desktop/assets/5377645/02324bd2-50ff-4914-9445-80f9ff35d29d)

**Comment by John-44** [comment]
@caybro thanks, we need to land this into 2.29 to fix this bug
