### ISSUE TITLE
Send: 0,001 value is treated as 1

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#14163]
# Bug Report

## Description

In Send dialog, when a decimal comma-separated value is entered (we should treat it as thousand separator), starting with`0`, it is treated as integer:
`0,001` it is treated as `1`

## Steps to reproduce

Wallet->Send

#### Expected behavior
Not a valid number

#### Actual behavior
Valid and confusing number

### Additional Information
<img width="551" alt="Screenshot 2024-03-26 at 11 44 06" src="https://github.com/status-im/status-desktop/assets/15627093/499facd3-2867-42ee-ab79-ac97667a7de0">

- Status desktop version: a09defbef
- Operating System: MacOs Sonoma 14

**Comment by caybro** [comment]
This is unfortunate... and I warned against this many times; we should simply not hardcode the input locale to `en_US`, and this is the result. :(

**Comment by caybro** [comment]
> @caybro I am not aware of all the details of the previous discussions about it. There must be a reason why we came up to using `en_US` locale hardcoded. Regarding this specific issue - if user enters 1,000 - it makes sense whether user means 1000 or 1, though it could be confusing. But input 0,0001 treated as 1 does not make sense at all. 

Yeah I agree, this is confusing but that's what you get as a result of hardcoding the `en_US` input locale; the `,` is then simply treated as a thousands separator, which is incorrect if your locale is not `en_US` -> unexpected number entered

> So if we stick to dot as decimal separator, we should not treat `0,0001` as a valid number, so we should handle only the case when a number starts with 0 as not valid. For the rest it should be fine, WDYT?

`0,0001` is a perfectly valid decimal number :) That's the whole point of this discussion; even Excel or any other sane app respects that

**Comment by alaibe** [comment]
We've gone over this a bunch of times, and honestly, it's not as easy as just going with whatever the computer's locale says.

Take France, for example. Officially, they use a comma (,) for decimals, but a lot of folks end up using a dot (.) instead, few reasons:
- Web forms that ask for numbers often get it wrong and don't adapt to local preferences, only accepting dots.
- The dot is what you find on keyboards, making it the go-to option.
- influence from the US and UK.

In a perfect world, everything would adjust to local preferences no problem. But people have their ways of doing things. AFAIR. we tried using the computer locale. We got reports saying that was wrong. It feels like we can’t win.

But here's what matters to me: making sure the fiat values we show make sense as a guide.

And I find it funny that this bug reports jump straight to calling something a bug without even saying what locale is being used. If it’s set to US/EN, then hey, it’s not a bug; it's just how it's supposed to work!

**Comment by caybro** [comment]
> We've gone over this a bunch of times, and honestly, it's not as easy as just going with whatever the computer's locale says.
> 
> Take France, for example. Officially, they use a comma (,) for decimals, but people end up using a dot (.) instead, few reasons:
> 
> * Web forms that ask for numbers often get it wrong and don't adapt to local preferences, only accepting dots.
> * The dot is what you find on keyboards, making it the go-to option.
> * influence from the US and UK.
> 
> In a perfect world, everything would adjust to local preferences no problem. But people have their ways of doing things. AFAIR. we tried using the computer locale. We got reports saying that was wrong. It feels like we can’t win.
> 
> But here's what matters to me: making sure the fiat values we show make sense as a guide.
> 
> And I find it funny that this bug reports jump straight to calling something a bug without even saying what locale is being used. If it’s set to US/EN, then hey, it’s not a bug; it's just how it's supposed to work!

The whole point of ppl always entering a dot `.` as the decimal separator can be easily overcome with a simple handler like this (from CurrencyAmountInput.qml):
```qml
Keys.onPressed: (event) => {
                        // additionally accept dot (.) and convert it to the correct decimal point char
                        if (event.key === Qt.Key_Period) {
                            root.insert(root.cursorPosition, Qt.locale(root.locale).decimalPoint)
                            event.accepted = true
                        } else if (event.modifiers === Qt.NoModifier && event.key >= Qt.Key_A && event.key <= Qt.Key_Z) {
                            // reject typing non-numbers (can happen when the validator is in an intermediate state)
                            event.accepted = true
                        }
                    }
```

**Comment by alaibe** [comment]
Would that means we would transform numbers like:
`1,000.5` to `1.000.5` ?

**Comment by caybro** [comment]
> Would that means we would transform numbers like: `1,000.5` to `1.000.5` ?

No, because the attached `DoubleValidator` would then reject the second separator, so you'd be able to type `1,000...` only.

See the CurrencyAmountInputPage in StoryBook

**Comment by anastasiyaig** [comment]
okay , we had this discussion earlier. https://github.com/status-im/status-desktop/issues/10125
we agreed to use dot as delimiter
we also cant lock comma completely on UI as we need to respect US locale to use thousands 
why it was decided to use comma as delimiter now?  Who approved that?
@IvanBelyakoff

**Comment by caybro** [comment]
> okay , we had this discussion earlier. #10125 we agreed to use dot as delimiter we also cant lock comma completely on UI as we need to respect US locale to use thousands why it was decided to use comma as delimiter now? Who approved that? @IvanBelyakoff @Cuteivist

You can still use the `.` as the delimiter it's just the display that is now consistent

**Comment by caybro** [comment]
Excel, my default OS calc app, even my physical keyboard has a comma as the decimal separator; I see no reason to even try to be different here.

**Comment by anastasiyaig** [comment]
alrighty :) thanks for details guys

**Comment by caybro** [comment]
To illustrate that, notice the numpad has `,` there:
![image](https://github.com/status-im/status-desktop/assets/5377645/b4662444-fdfb-480d-af67-f55c8f0962a8)

See https://kbdlayout.info/KBDCZ/

**Comment by caybro** [comment]
> @anastasiyaig FYI locale in app is same as system locale. It needs to be set before starting the app. That way you can check for example en_US or any other one.

Nope, the locale can be freely set/changed during runtime, see here for example:

[Záznam obrazovky z 2024-04-12 16-21-23.webm](https://github.com/status-im/status-desktop/assets/5377645/f26ca966-789e-41e2-aa9f-2b339c7c45dd)

**Comment by anastasiyaig** [comment]
i will adjust my autotest to have this verification as well , dots and commas

**Comment by caybro** [comment]
> i will adjust my autotest to have this verification as well , dots and commas

You don't have to, just set your locale before starting the tests
