### ISSUE TITLE
Community: Prove ownership modal is missing

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14160]
### Description

**2.28 rc2**: after i click Join community -> I am required to share some addresses with that community within Prove Ownership modal

https://github.com/status-im/status-desktop/assets/82375995/8fd91581-c4e5-4997-a5c7-9495b9f7cfbb

**master**: prove ownership modal is missing, when clicking Join i am joined right away, without proving ownership of addresses

https://github.com/status-im/status-desktop/assets/82375995/86fedee3-8564-46a6-a4f6-23487c9be039

**Comment by noeliaSD** [comment]
Hey @anastasiyaig this is the new flow described on figma. It's on propose and correct. When you have ONLY one authentication method, then it directly shows the authetication dialog to add your password. 

This would be the case of your video: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=51863%3A148233&mode=design&t=zFKH3iVdr67UOt5R-1

**Comment by anastasiyaig** [comment]
thanks a lot, all clear now @noeliaSD !
