### ISSUE TITLE
[Community authentication flow] `Join Community` button text instead of `Share all addresses to join` text in membership setup dialog

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14172]
### Description

[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=51863%3A148233&mode=design&t=vyWhf7eBzOp6rvsy-1)

![Screenshot 2024-03-26 at 16 40 48](https://github.com/status-im/status-desktop/assets/97019400/45fa09cb-4ef3-4dac-b376-6ec776708a10)

**App:**
![image](https://github.com/status-im/status-desktop/assets/97019400/600a6dea-36ac-4ecb-a226-d28e5d806e09)

**Comment by caybro** [comment]
CC @saledjenic pls have a look too :)

**Comment by saledjenic** [comment]
@caybro we see that button cause obviously "Token gated". community access type is not set to `3` (`communityChatOnRequestAccess`).
