### ISSUE TITLE
[Community authentication flow] When biometric is setup the authentication flow is not correct showing the password one instead

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14173]
### Description

When the user enables biometrics and goes through the shared address flow, when attempting to authenticate, the corresponding [biometric flow](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=6598-76671&mode=design) should be display. Instead, the password one is always shown.

https://github.com/status-im/status-desktop/assets/97019400/065f9c97-6604-4192-be74-a6b9d5462585

**Comment by caybro** [comment]
CC @saledjenic can you help with this one?
