### ISSUE TITLE
Share addresses button enabled when selected account does not meet permissions

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14171]
# Bug Report

## Description

1. When joining a community it is possible to select an account to share that does not meet the requirements for the community.
2. The share account to join button remains enabled in this case
3. Clicking it returns the user to the permissions overlay screen but they can no longer change what account is shared.
4. If the community is closed and then revisited the user can select another account to share

![image](https://github.com/status-im/status-desktop/assets/50769329/ddd321b8-ac4d-4b95-a225-0e088e69114f)

![image](https://github.com/status-im/status-desktop/assets/50769329/8e90bc49-28c5-4546-b593-654ad3fedad2)

#### Expected behavior

User cannot proceed to share address when account does not meet requirements
OR
User can select a different account to share after returning to the permissions overlay screen

### Additional Information

- Status desktop version: 2.28 RC2 C26110
- Operating System: Mac

**Comment by noeliaSD** [comment]
Partially related / dependent on this: https://github.com/status-im/status-desktop/issues/14088

**Comment by caybro** [comment]
@glitchminer yup, the other half of the issue (points 3 and 4) are actually for the messenger-team (see https://github.com/status-im/status-desktop/issues/14088)

**Comment by caybro** [comment]
OTOH, we could maybe now enable the button uncoditionally, since we're always going thru the popup
