### ISSUE TITLE
[Share addresses dialog] No proper dialog size when there are no permissions set up for the community

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14195]
### Description

https://github.com/status-im/status-desktop/assets/97019400/c676e248-7d89-4b2c-9f55-0a3a3d6457d2

**Comment by caybro** [comment]
Might be related to https://github.com/status-im/status-desktop/issues/14094

**Comment by glitchminer** [comment]
Possibly related, I had a community set up with 1 or 2 permissions and also token master. It was not possible to scroll down to view the permissions list.

![image](https://github.com/status-im/status-desktop/assets/50769329/82769655-25d3-40ad-8718-84c1d2bbc004)

**Comment by caybro** [comment]
Yeah... all these really seem like a Qt bug; I can't reproduce over here

**Comment by caybro** [comment]
It looks like this bug is reproducible on macOS only; which underlines my previous assumption this being a Qt bug (see the [comment](https://github.com/status-im/status-desktop/issues/14195#issuecomment-2024835415) above)
