### ISSUE TITLE
Update Balance tag background or add border as it not visible on whitebackground

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#14203]
![image](https://github.com/status-im/status-desktop/assets/60327365/5ffb95a7-9fe9-42ee-9717-5aea4971d3ba)

currently the balances tag on erc1155 is not visible on white background , need to update this to make it more visible once @benjthayer finalises a solution for this.

also handle comment here https://github.com/status-im/status-desktop/pull/14204#issuecomment-2034092641

**Comment by benjthayer** [comment]
@Khushboo-dev-cpp as discussed, here are a series of screens which clarify how to handle collectibles of different aspect ratios which should ensure that the number tag is always visible. :)

https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=22617-232319&mode=design&t=L1UVvYZNThZGgwti-4
