### ISSUE TITLE
Display for L1 fees on a transaction

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#14208]
We need design for how to handle and show the L1 fees component we see as of now while doing a tx on optimism. Waiting for @benjthayer solution and opening this ticket so that this is not lost

current implementation:
<img width="597" alt="image" src="https://github.com/status-im/status-desktop/assets/60327365/a56d8a20-dcc4-4183-9835-95227963866f">

expected:
![image](https://github.com/status-im/status-desktop/assets/60327365/6027c4c6-bb4d-490e-95c3-973dd759e2b2)

**Comment by benjthayer** [comment]
> We need design for how to handle and show the L1 fees component we see as of now while doing a tx on optimism. Waiting for @benjthayer solution and opening this ticket so that this is not lost

Designs complete and added to the Send flows here:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=22652-265707&mode=design&t=FzBHjGy3ckdRF9mn-4

cc @John-44

**Comment by saledjenic** [comment]
@noeliaSD is this something that gonna be handled by the ui-team in 2.30, as a part of SendModal improvements?

**Comment by noeliaSD** [comment]
I'll assign them to the team but will look at the capacity and the priorty so we can discuss
