### ISSUE TITLE
Token Management: Custom order is applied only after wallet refresh

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#14205]
# Bug Report

## Description

After changing order of tokens and saving changes to wallet it can be noticed that there is a significant delay until it's applied in wallet view. It looks to me like it the changes are visible only after the wallet refreshes which can take several minutes.

## Steps to reproduce
1. Log in
2. Go to Settings > Wallet > Manage tokens
3. Change the order of tokens
4. Click "Apply to my wallet"
5. Got Wallet view and check the order of tokens

#### Expected behavior
Tokens are displayed in the new order.
#### Actual behavior
Until wallet refresh is triggered tokens are shown in the old order.
### Additional Information

- Status desktop version: master
- Operating System: macOS

**Comment by caybro** [comment]
This has been fixed already right @stefandunca ? Feel free to close if it's the case :)

**Comment by stefandunca** [comment]
Fixed by: https://github.com/status-im/status-desktop/pull/14394
