### ISSUE TITLE
No need to check permissions ourselves as member when a community updates permisisons

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14220]
### Description

Right now, each time the control node updates the permissions for a community, each member does a small check up on the permission to see if they still fit the permission.

This causes a spike in CPU and also does a call to the ethereum provider for no reason.

We should be relying on the Community Description provided by the control node. Since the control node itself already reevaluates the permissions of each members, we can just check it.

For the community itself and being part of it, we would be out of the member list if we didn't fit the permission.

For the channels, each community channel comes with a list of members. Channels with permissions have an updated list of members for the ones that fit the permission. So we can just see if we are still in that list.

The only exception to that rule is when you are **not** part of a community. In that case, the control node doesn't know about you, so you need to check your own permissions yourself.

### Acceptance criteria

- When part of a community, members should not check the chain for permissions instead
  - for being part of the community, check the community member list
  - for being part of a channel, check the community channel's member list
    - If you are not part of a channel, then we can check the permissions to see which token is missing, but only when the channel is in view (user clicked on the channel)
- When not part of a community, we can check the join permission on chain, because we are not part of the member list yet

**Comment by osmaczko** [comment]
It should not result in such big spike, there is something wrong. Maybe there is circular event dependency or recursion.

**Comment by jrainville** [comment]
Turns out the spike wasn't on the backend but on the Nim/QML side. It was mostly resolved.

I think it's still worth it to improve the backend so that we don,t rely on 3rd party providers anyway. It should make it faster too.
