### ISSUE TITLE
CPU spike/hang when SIGNAL_CHECK_ALL_CHANNELS_PERMISSIONS_RESPONSE is called

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14234]
# Bug Report

## Description

Experienced by almost everyone. Especially Iuri himself. His app gets stuck a lot. We don't know exactly why. Sometimes, we need to kill the app.

**Edit**: Turns out the issue is with the return of checking all channels. See comment below: https://github.com/status-im/status-desktop/issues/14234#issuecomment-2032332072

**Comment by jrainville** [comment]
As a TokenMaster, I get a lot of those sometimes, I'm not sure if it's related:
```
DBG 2024-03-29 10:03:30.724-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=3876594 file=core.nim:27 rpc_method=wallet_getPendingTransactions
DBG 2024-03-29 10:03:30.724-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=3876594 file=core.nim:27 rpc_method=wallet_getPendingTransactions
DBG 2024-03-29 10:03:30.724-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=3876594 file=core.nim:27 rpc_method=communitytokens_remoteDestructedAmount
```

**Comment by jrainville** [comment]
In the geth log, I get a lot of those when the front-end is hanging:
```
DEBUG[03-29|10:06:17.016|github.com/status-im/status-go/wakuv2/waku.go:1373]                                         cached w envelope                        envelopeHash=0x9f2438f59f20e4ad7a6906af38f1fcab90456c8ee3618455c232f237de690ddf
DEBUG[03-29|10:06:17.016|github.com/status-im/status-go/wakuv2/common/filter.go:234]                                 no filters available for this topic      message=0x9b95a9a73dbd336fab8c84acf4c1c5ce75d5d27a65da663d0041615b6894577d pubsubTopic=/waku/2/rs/16/32 contentTopic=0xb5ddd12d
DEBUG[03-29|10:06:17.016|github.com/status-im/status-go/wakuv2/waku.go:1431]                                         filters did not match                    envelopeHash=0x9b95a9a73dbd336fab8c84acf4c1c5ce75d5d27a65da663d0041615b6894577d pubsubTopic=/waku/2/rs/16/32 contentTopic=/waku/1/0xb5ddd12d/rfc26 timestamp=1,711,721,176,609,976,000
DEBUG[03-29|10:06:17.016|github.com/status-im/status-go/wakuv2/waku.go:1383]                                         posting event                            envelopeHash=0x9f2438f59f20e4ad7a6906af38f1fcab90456c8ee3618455c232f237de690dd
```

**Comment by jrainville** [comment]
Could be a red herring, I get those logs when not hanging either

**Comment by jrainville** [comment]
Here are my geth logs. I killed the app when it started hanging: https://drive.google.com/file/d/1e89qvlIvbsy8jeh2j66yX-okuUqUfOI5/view?usp=drive_link

**Comment by jrainville** [comment]
It does happen at the same spot as before:
```
GOT PERMISSION RESULT
EMITTING checkAllChannelsPermissionsResponse
Time taken comm section: 0.1016210309999996
Time taken chat section: 149.050058137
```

However, it only happens to my TM account. My normal account gets the result super fast
 ```
 EMITTING checkAllChannelsPermissionsResponse
Time taken comm section: 0.07858115799999954
Time taken chat section: 0.07852978499999974
```

**Comment by jrainville** [comment]
The PR has been updated. The fix for admins+ is available

**Comment by kounkou** [comment]
**[WIP]**

Hi,

Started the investigation, 
based on reception of signal `SIGNAL_CHECK_ALL_CHANNELS_PERMISSIONS_RESPONSE` received in chatsection and communities controllers upon `onAsyncCheckAllChannelsPermissionsDone`
and I can observe that on a simple community with 2 categories and less than 20 channels per category, I observe that the time taken for creating or updating a permission is off chart in the case of Chat section update.

```mermaid
xychart-beta
    title "Execution Time (chat section)"
    x-axis [startup, create_permission, update_permission]
    y-axis "Execution Time (in ms)" 0 --> 1000
    bar [7, 477, 531]
    line [1, 2, 3]
```


```mermaid
xychart-beta
    title "Execution Time (communities)"
    x-axis [startup, create_permission, update_permission]
    y-axis "Execution Time (in ms)" 0 --> 10
    bar [3, 2, 2]
    line [1, 2, 3]
```

So I will focus on the function taking more time in chat section to find any possible improvements

**Comment by anastasiyaig** [comment]
@jrainville @kounkou could this issue be a reason for my app being super slow on login and sending messages? To me loggin in to the app takes several minutes , also when i am finally in, sending a single message is a huge pain (hitting send sends the message within several minutes as well)

I stared seeing this behavior since last Fri (march 30)

<img width="1531" alt="Screenshot 2024-04-03 at 10 03 17" src="https://github.com/status-im/status-desktop/assets/82375995/c6827a1f-ee50-47a5-992b-450759bbed16">

**Comment by jrainville** [comment]
@anastasiyaig it's possible, though it's hard to tell. In my case, when it's hanging, it's fully frozen, so I can't even focus the message input.

We'll see once it's merged if you still have that issue.
