### ISSUE TITLE
[Profile Showcase] Blinking while performing a profile showcase entry validation

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#14232]
From https://github.com/status-im/status-desktop/pull/13998#pullrequestreview-1966101791

Update loading state / timing to show only data after visibility validation is done so we don't reveal data to users that should not see the items bc of the visibility level.

Possible solution: force loading state for entries while `isShowcaseForAContactLoading` flag is true

**Comment by alexjba** [comment]
@MishkaRogachev `isShowcaseForAContactLoading` is a global flag. This means if this flag is true, we should show all communities in a loading state. But do you think it's safe? I'm thinking if there's a case where one community cannot be loaded and we'll always show the loading state for all communities instead of having just one community in a loading state.

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev `isShowcaseForAContactLoading` is a global flag. This means if this flag is true, we should show all communities in a loading state. But do you think it's safe? I'm thinking if there's a case where one community cannot be loaded and we'll always show the loading state for all communities instead of having just one community in a loading state.

At the moment the profile showcase is requested in two steps: first we get the available profile entries without validation, and then we make the same request but with validation and when the response comes back we set isShowcaseForAContactLoading = false. It is possible to split validation for each community separately, but I think it is an unnecessary complication and will lead to a large number of requests-responses between the client and status-go. About the danger: the response to the request will be returned in any case, but the communities for which the validation failed will be absent.
