### ISSUE TITLE
Sent 'Request to join' and Cancelling pending request does not change btn state

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#14265]
# Bug Report

## Description

When I sent `Request to join`, btn text does not switch on `Membership request pending` (only after a restart)
When I cancel request to join, btn text stays unchanged

## Steps to reproduce

1. Create a community with a manual approval of requests to join
2. User_1 tries to join the community
3. User_1 tries to cancel the request to join

#### Expected behavior

Step 2: `Request to join` changes to `Membership request pending`
Step 3: `Membership request pending` changes to `Request to join`

#### Actual behavior

Btn state is no changing

Step: 2

https://github.com/status-im/status-desktop/assets/117639195/e2646b66-4bbe-40a6-8552-761e016e2a17

Step 3:

https://github.com/status-im/status-desktop/assets/117639195/8d6828d8-f19b-4a27-969b-cc0f1bad2848

### Additional Information

- Status desktop version: latest master
- Operating System: macos

**Comment by caybro** [comment]
@mprakhov for me it works fine on master, albeit with a slight delay

**Comment by caybro** [comment]
> @caybro cancel works too?
> Do you have a simple community, without any permissions?
> Looks weird, I stashed all my changes and did `make clean`... still can observe 
> 

You are right, Cancel doesn't work reliably
