### ISSUE TITLE
Ensure keycard PIN is not logged 

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#14272]
## Bug Report

During login/restore with a keycard, it's PIN code is logged:
This should not be done, it's not safe.

`
DBG 2024-04-03 15:31:19.447+01:00 keycardResumeFlow topics="keycard-service" tid=2834593 file=service.nim:172 kcServiceCurrFlow=RecoverAccount payload="{\"pin\":\"123456\"}" response=ok
`

**Comment by saledjenic** [comment]
@igor-sirotin this is the case only for development builds, this code here is responsible for keycard details logging:

https://github.com/status-im/status-desktop/blob/master/src/app_service/service/keycard/service.nim#L93-L95

So we're good, closing this issue.
