### ISSUE TITLE
Can't mint tokens on Sepolia

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14270]
### Description

<img width="1635" alt="Screenshot 2024-04-03 at 17 19 09" src="https://github.com/status-im/status-desktop/assets/82375995/0b8ce5fb-a2e3-4426-949f-6da588ad7d59">

**Comment by anastasiyaig** [comment]
@iurimatias pls prioritise

**Comment by saledjenic** [comment]
@anastasiyaig I did check this now with the latest master and here is the result:

![image](https://github.com/status-im/status-desktop/assets/86303051/68ed7df4-279d-473b-b5b6-dce224f8a2ba)

Relevant transaction:
- https://sepolia-optimism.etherscan.io/tx/0xcb8ea1be272b6ddbc1ce59861bc1b5bb49452a50cf0e523f7d0bd665ae9baf71

Minted tokens:

![image](https://github.com/status-im/status-desktop/assets/86303051/e2f44c5c-27f6-48ba-8b46-4541a0a04846)

**Comment by anastasiyaig** [comment]
thanks @saledjenic

**Comment by anastasiyaig** [comment]
it works for newly created communities, but for previously created ones - still does not. Not sure, what is the reason of that, lets keep monitoring . i will re-open it if it happens constantly
