### ISSUE TITLE
Communities: make it possible to edit a community

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#1428]

**Comment by jrainville** [comment]
Currently unavailable in status-go

**Comment by iurimatias** [comment]
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=3806%3A582197

**Comment by iurimatias** [comment]
this should now be available in status-go

**Comment by jrainville** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/2565

**Comment by emizzle** [comment]
Was this fixed already by #2566?
