### ISSUE TITLE
No community invitation in the chat

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#14285]
We have test for joining community. For that test we use user data for both users. 
For some reason sometimes there is no community invitation (sometimes it is there). Even if we wait for some time - still nothing. So test fails at this step. We were not able to reproduce it manually.

![7a63064e2595971c](https://github.com/status-im/status-desktop/assets/141633821/31347aaf-3c55-4f8e-8aed-2cd576aca614)

Because we use user data there is already accepted contact request with message in chat and some old community invitation. I also noticed that sometimes instead of that invitation there is just a message 'ping' (see screenshot below)

![AUT_152432](https://github.com/status-im/status-desktop/assets/141633821/e3e912b2-11b8-45ac-a824-49b692c535fd)

I attach geth.log and also application logs

[geth.log](https://github.com/status-im/status-desktop/files/14864203/geth.log)

[INF_2024-04-04_084008.1910000_Version_0.9.90_topicsstatus-app_tid3272632_filenim_status_client.nim198_INF_2024-04-04_084008.1910000_Commit_de74a6ce0_topicsstatus-app.pdf](https://github.com/status-im/status-desktop/files/14864207/INF_2024-04-04_084008.1910000_Version_0.9.90_topicsstatus-app_tid3272632_filenim_status_client.nim198_INF_2024-04-04_084008.1910000_Commit_de74a6ce0_topicsstatus-app.pdf)

**Comment by jrainville** [comment]
This is very hard to "fix", as it relies on store nodes and they will never be 100% reliable.
The best solution for this is to make the local store node work, but I know it was not a simple task

**Comment by fryorcraken** [comment]
Randomly reading this issue (or was it forwarded to me?).

With store v3 sync (wip), the expectation will be for store node to have the same messages, and we will even be tracking metrics on that. Would that help solve this issue?
Seems like there is a different behaviour, is that depending on what store node the app connects to?

**Comment by jrainville** [comment]
Closing as this is something that should or will be fixed by store node upgrades
