### ISSUE TITLE
[Shared Addresses] Can't edit shared address while the join request is pending

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#14292]
# Bug Report

While our request to join a community is pending, we can't really edit the shared addresses; an attempt to do so results in:
```
ERR 2024-04-04 16:11:24.910+02:00 rpc response error                         topics="rpc" tid=2210695 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_editSharedAddressesForCommunity, code:-32000, message:not part of the community ]\n"
ERR 2024-04-04 16:11:24.910+02:00 error doing rpc request                    topics="rpc" tid=2210695 file=core.nim:40 methodName=wakuext_editSharedAddressesForCommunity exception="\nstatus-go error [methodName:wakuext_editSharedAddressesForCommunity, code:-32000, message:not part of the community ]\n"
ERR 2024-04-04 16:11:24.911+02:00 Error editing shared addresses             topics="community-service" tid=2210676 file=service.nim:1742 msg="\nstatus-go error [methodName:wakuext_editSharedAddressesForCommunity, code:-32000, message:not part of the community ]\n"
```

We should probably just disable/remove the action from the context menu

![image](https://github.com/status-im/status-desktop/assets/5377645/4a21a881-cb92-43d8-82f8-07ecb12864cc)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
@jrainville thoughts?

**Comment by jrainville** [comment]
I agree, disabling the option in the menu seems the simplest way. The user can always cancel their request and send with a new one or edit when joined
