### ISSUE TITLE
Extracting messages from history archive - infinite loop

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#14290]
# Bug Report

I encountered an infinite loop when running our application.
It seems that when the archive extracting fails, the process tries to extract it again and again.

![image](https://github.com/status-im/status-desktop/assets/61889657/1fa3b218-5a79-4bfa-a55a-09b34797494b)

I used [RC](https://github.com/status-im/status-desktop/commit/39f60ff1f) application and I was connected to Status community.

**Comment by jrainville** [comment]
Duplicate of https://github.com/status-im/status-desktop/issues/13105
