### ISSUE TITLE
During the join / edit shared addresses flow, if requirements check backend fails, UI doesn't act accordingly

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14299]
### Description
When selecting / unselecting account that contains tokens related to join permissions, the requirements check works the first time, but not the second one, triggering an error in log but the UI doesn't evaluates this result so that the user is able to continue with the join flow. In the following video the failure happens at the end but you can see from the very begining, that the initial behaviour is correct, then after more selections / unselections the flow becomes incorrect.

https://github.com/status-im/status-desktop/assets/97019400/10fea224-f4c5-4bf6-8872-c43fbe1ecb1e

**Log**:
```
ERR 2024-04-04 17:47:01.782+02:00 error doing rpc request                    
topics="rpc" tid=2251947 file=core.nim:40 methodName=wakuext_checkAllCommunityChannelsPermissions exception="\nstatus-go error [methodName:wakuext_checkAllCommunityChannelsPermissions, code:-32000, message:fallback failed with 'unsuccessful request: 403 Forbidden'. run error was 'hystrix: timeout' ]\n"
```

**Posible solutions:**
- Disable the dialog button while the app is in requirements checking state (ask _design team_ about this disable state).
- Backend to emit a signal on failure and UI to listen to it to act accordingly.

**Comment by noeliaSD** [comment]
cc: @alexandraB99 milestone to be assigned

**Comment by caybro** [comment]
Adding the messenger-team as well because the erratic UI behavior likely stems from the backend call failing

**Comment by noeliaSD** [comment]
cc: @alexjba

**Comment by jrainville** [comment]
Backend issue opened here: https://github.com/status-im/status-desktop/issues/14313

**Comment by MishkaRogachev** [comment]
@noeliaSD @caybro 
I've added a signal to view (communitiesModuleInst). Do you need it in some store?
PR: https://github.com/status-im/status-desktop/pull/14374

**Comment by caybro** [comment]
> @noeliaSD @caybro I've added a signal to view (communitiesModuleInst). Do you need it in some store? PR: #14374

Not sure yet, I can add it later if I need it :) Thx

**Comment by noeliaSD** [comment]
> > @noeliaSD @caybro I've added a signal to view (communitiesModuleInst). Do you need it in some store? PR: #14374
> 
> Not sure yet, I can add it later if I need it :) Thx

Sure we need to listen to that new signal! Thanks @MishkaRogachev for the addition!!!

**Comment by caybro** [comment]
> > > @noeliaSD @caybro I've added a signal to view (communitiesModuleInst). Do you need it in some store? PR: #14374
> > 
> > Not sure yet, I can add it later if I need it :) Thx
> 
> Sure we need to listen to that new signal! Thanks @MishkaRogachev for the addition!!!

Not denying that but I'm just not sure which store to add it too at this point. I can add it later when I've started working on this, so this PR is good enough for now
