### ISSUE TITLE
[Profile Showcase] Wrong X (Twitter) icon

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#14300]
# Bug Report

Wrong (old) icon:
![image](https://github.com/status-im/status-desktop/assets/5377645/bb4f831b-dd63-486b-b457-87fe017c2c0f)

Correct (new) icon:
![image](https://github.com/status-im/status-desktop/assets/5377645/9651c70e-a8dd-4520-a7b4-7a7f10f4de2a)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
> @caybro can I fix this issue?

We definitely welcome PRs from anybody :)

**Comment by dicethedev** [comment]
> > @caybro can I fix this issue?
> 
> We definitely welcome PRs from anybody :)

Alright!

**Comment by dicethedev** [comment]
@caybro please can you share your open-source contribution guide?

**Comment by dicethedev** [comment]
@caybro I just made a PR for this - https://github.com/status-im/status-desktop/pull/14430
