### ISSUE TITLE
[Profile Showcase] Missing community info in the collectibles delegate

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#14318]
# Bug Report

## Description

https://github.com/status-im/status-desktop/assets/47811206/c10675c8-636e-4dc3-9349-b2155c5d95d8

The collectibles delegate doesn't display the community image and the community name.

Works fine on 2.28.1 with all the profile showcase commits cherry-picked (https://github.com/status-im/status-desktop/pull/14267), so it could be related some new model updates or collectibles refactoring.

## Steps to reproduce

Open my profile:
https://status.app/u/G5wAAORsG-KRkG79R8hQqdZfFJVS6IBDDly_IwaAzWOtA2zrbMlvJ0HR87sk6We3ejtwD9MK5NWO92NDQPEODlZi1u-LgY-5_2u87QieSWLAQmiqpxEzjOB0mQE=#zQ3shQMuqq8XmQN1JUP4HtW6xCgRBc3FqmqWgsvvXBpSEuZGd

Go to collectibles tab

#### Expected behavior
Community icon and name is shown in the collectible delegates

#### Actual behavior

Community info is missing

**Comment by caybro** [comment]
Works fine in current master:
![image](https://github.com/status-im/status-desktop/assets/5377645/cfc7ed2f-5b74-4d24-94a0-a8697823854c)

Closing
