### ISSUE TITLE
Sometimes community info cannot be posted for several days 

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#14335]
# Bug Report

## Description

Whenever I tried to open the community on the desktop, the info seemed not posted to waku - so it couldn't be fetched from any other client
Doesn't depend on the user, examples of community: 
1) https://status.app/c/Cw6AChsKBmRzZnNkZhIGc2Rmc2RmGAEiByM0MzYwREYD#zQ3shnLieSySJDa4F7Xrvh6VHpeSqMhPTQt6w6nNHFR9pd8ji (still didn't log in after the bug, so community info is not fetched)

2) https://status.app/c/GzAAAGR3tkvtkstNP0WOS07Hu6Qdjs2jlEBSBXVjQjv5074iJOuo8nOVh2BiLS33AQ==#zQ3shpRqht2cZ1j4qM6wjuVCJTjr4WzjgwfmpW1vUPZ9xmLNj (logged in after the bug, so community info was fetched on 08/04) 

The issue existed for me from 03.04.24 to 08.04.24, and new communities that were created from 08.04 did not exhibit this problem.
After 08.04 when I logged into accounts where I created communities, their info started to post (like for community 2 described above) 

**Note: it seems that somehow I  as an admin was not detected as online for several days**
However, I had 6 peers, was on `shards.test` fleet and could send/receive contact requests.

It blocked my work for several days, so I decided to log it. I'm not sure that is something interesting in the logs, but best to have it in the repo.

## Steps to reproduce

1) Open the community
3) Share community link
4) Try to open it from any browser or client

#### Expected behavior
community info + banner are fetched

#### Actual behavior
"couldn't fetch info" (like for https://status.app/c/Cw6AChsKBmRzZnNkZhIGc2Rmc2RmGAEiByM0MzYwREYD#zQ3shnLieSySJDa4F7Xrvh6VHpeSqMhPTQt6w6nNHFR9pd8ji )

### Additional Information

- Status desktop version: [2.28.0-rc.3](https://github.com/status-im/status-desktop/releases/tag/2.28.0-rc.3) 
- Operating System: MAC OS 14.4.1

Desktop log: 
[geth_comm_info_is_not_posted.log](https://github.com/status-im/status-desktop/files/14908333/geth_comm_info_is_not_posted.log)

[Archive.zip](https://github.com/status-im/status-desktop/files/14908295/Archive.zip)

**Comment by anastasiyaig** [comment]
@jrainville pls take a look

**Comment by jrainville** [comment]
If I understand correctly, it didn't work from the 3rd to the 8th, but now it's back to working?

I wonder if it would be caused by a bad store node?

**Comment by jrainville** [comment]
Does this still happen?

**Comment by anastasiyaig** [comment]
@churik did you face with this recently?

**Comment by churik** [comment]
No, it blocked me for several days, but it hasn't happened since then.

**Comment by jrainville** [comment]
Ok, it was probably the problem we had with a store node that was wrongly upgraded. It has been fixed since then.

I'll close.
