### ISSUE TITLE
[Token Management] Wrong token list popup title

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#14366]
# Bug Report

![image](https://github.com/status-im/status-desktop/assets/5377645/f445d333-c0ed-4ad2-b9e2-dafaae83ecb8)

Too many "token list" in the popup title :)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by noeliaSD** [comment]
cc @Khushboo-dev-cpp : https://github.com/status-im/status-desktop/pull/14428

**Comment by belalshehab** [comment]
fixed: https://github.com/status-im/status-desktop/pull/14428

**Comment by belalshehab** [comment]
fixed with: https://github.com/status-im/status-desktop/pull/14428

**Comment by caybro** [comment]
It's not fixed, the PR is not merged yet
