### ISSUE TITLE
Add a banner for Owners when the member re-evaluation is in progress

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14378]
### Description

Currently, the member re-evaluation that happens periodically and when permissions are modified takes a lot of time (more than 10 minutes).

Since the process needs to fully end for it to take effect, closing the app as an owner when it runs is not ideal. It won't break anything, but it means that the process will need to be re-done.

What would be needed is a banner that shows when the re-evaluation is in progress. That way, the owner knows that something is going on (in case of higher network activity + CPU usage) and to tell them not to close the app.

### Acceptance Criteria

- When the member re-evaluation is in progress, a banner is shown that says something like "Member re-evaluation in progress in COMMUNITY_NAME. Please do not close the app."
- The banner can be green as it's not something that is dangerous
- The banner cannot be dismissed

**Comment by osmaczko** [comment]
I think it is better to add busy indicator/rotator on a members list rather than banner.
