### ISSUE TITLE
Token Management: Create custom order is missing from the app

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#14383]
# Bug Report

## Description

When the user has not created any custom order the app should show an option to create custom order in the sorting menu. Currently it always shows "Custom order" as if it was already created.

## Steps to reproduce

1. Create a fresh account
2. Log in
3. Go to wallet
4. Open the sorting menu

#### Expected behavior
There is an option "Create custom order"
#### Actual behavior
"Custom order" and "Edit custom order" is shown instead
### Additional Information

https://github.com/status-im/status-desktop/assets/52439419/00588346-a311-4e28-9ec0-dea72911419c

- Status desktop version: master
- Operating System: macOS

**Comment by caybro** [comment]
CC @stefandunca ; @iurimatias pls prioritize
