### ISSUE TITLE
[Chat] Unread badge even for unreachable channels

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#14421]
# Bug Report

No other channel or category is highlighted nor has any unread messages, so I'm assuming there's a hidden (unreachable to me due to permissions) channel here in the Mobile category that has some unread messages.

![image](https://github.com/status-im/status-desktop/assets/5377645/ab98961d-d6e0-4639-ad3a-10af152878cc)

#### Expected behavior
No highlighted category, no unread msg badge in the primary nav

#### Actual behavior
Highlighted category, unread msg primary badge

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
Similar thing for an unjoined community:
![image](https://github.com/status-im/status-desktop/assets/5377645/04ab80c5-dce1-4a28-a62a-b937ee59c9a9)

**Comment by jrainville** [comment]
I can reproduce the issue. It seems to happen only on restart. When you first receive the messages, the count doesn't update, but on restart it does. 
Even my branch with the refactor has the issue. 

I'm investigating at which level it fails.
