### ISSUE TITLE
Wallet: transactions are duplicated in Activity view

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14426]
### Description

NOTE: **Version:** **2.28.1, build 33**, i can't reproduce in master from today

1. sent stt to address
2. sent weenus to address
3. sent yeenus to address
4. opened activity view

Result: all transaction records are duplicated with "pending" state records

<img width="1212" alt="Screenshot 2024-04-15 at 15 33 57" src="https://github.com/status-im/status-desktop/assets/82375995/4565c979-82f2-48cc-89f4-94a25bcf0420">

**Comment by anastasiyaig** [comment]
@iurimatias please prioritise

**Comment by anastasiyaig** [comment]
yup i know! we need to cherry pick, can someone pls create pr for 2.28.x?

**Comment by anastasiyaig** [comment]
@dlipicar @stefandunca it is fixed in master, can we please find the commit and cherry pick to rc?

**Comment by stefandunca** [comment]
> @dlipicar @stefandunca it is fixed in master, can we please find the commit and cherry pick to rc?

Here they are: [status-go #5081](https://github.com/status-im/status-go/pull/5081) https://github.com/status-im/status-desktop/pull/14497 and [status-desktop #14497](https://github.com/status-im/status-desktop/pull/14497)
