### ISSUE TITLE
Community token showing community name as unknown

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14437]
# Bug Report

## Description

Minted owner token then viewed collectibles in wallet. Community badge shows community name as unknown and does not link to the community.

![image](https://github.com/status-im/status-desktop/assets/50769329/94af84fd-b112-4f09-a5ad-f7adfceac583)
![image](https://github.com/status-im/status-desktop/assets/50769329/ff1b9dfe-caa4-4229-9f87-5ea8bf5b1820)

#### Expected behavior

Community badge shows community name and links to the community.

### Additional Information

- Status desktop version: 2.28.1 RC 1
- Operating System: Mac

**Comment by anastasiyaig** [comment]
maybe not really critical? @dlipicar perhaps fixed in master too?
