### ISSUE TITLE
Permission overlay text incorrectly says that user must hold token

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14439]
# Bug Report

## Description

1. Create open community
2. Create channel with view only permission for all users
3. Visit community and open channel without joining community
4. Permissions overlay reads that a token must be held without specifying any token.

![image](https://github.com/status-im/status-desktop/assets/50769329/0b1d6b4b-4eed-45d5-819c-43e1e456b685)

#### Expected behavior

Message should not refer to holding tokens when none are required.

### Additional Information

- Status desktop version: 2.28.1 RC 1
- Operating System: Mac

**Comment by caybro** [comment]
@jrainville I think we've seen this before but I forgot what the actual cause was :) But we definitely do not have the correct icon in the UI at this stage

**Comment by jrainville** [comment]
> @jrainville I think we've seen this before but I forgot what the actual cause was :) But we definitely do not have the correct icon in the UI at this stage

In this case, it's not about the missing icon, it's not showing the right screen. It should be showing the channel, but with the input blocked. 
The permission is "Everyone can view only channel #bla", so the channel should be visible

We shouldn't put both team labels. I think in this case, it's probably ui team, since it used to work in 2.28.0 (I think).

**Comment by caybro** [comment]
@noeliaSD I think you worked on this last right?

**Comment by micieslak** [comment]
This task is blocked by https://github.com/status-im/status-desktop/issues/14748 because it's not only matter of UI to remove the overlay. The channel is encrypted and therefore messages are not available.

**Comment by jrainville** [comment]
@micieslak status-go PR opened here for the backend problem: https://github.com/status-im/status-go/pull/5164
