### ISSUE TITLE
Community updates are lost/erased sometimes (re-evaluation overrides it?)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14432]
# Bug Report

## Description

When Iuri adds a permission, if he then adds more permissions, there is a chance that the newest permissions will be removed/lost.

My guess of what is happening is that the member re-evaluation  starts when the first permission is created. Then, when it ends, it saves the community and publishes it. However, that re-evaluation is made on a separate thread, so it does it's own copy of the description. so at the end, if the re-evaluation takes a lot of time, there is a strong chance that it will save and publish an out of date description. In other words, if community changes were made while the re-evaluation was in progress, they will be lost.

I think the most straightforward way to fix this would be to cancel and restart the member reevaluation if `saveAndPublish` is ever called (there is a new version/clock).
Another option would be to make the reevaluation smarter and it got the community description again at the end and just applies the member permissions it calculated to it. However, this solution is more error prone, because if another permission was added that changes the way the members should be, it could cause a temporary weird state.

## Steps to reproduce

0. Have a big community with lots of channels, members, permissions and tokens
  or add some sleeps in the reevaluate method to fake a long time to evaluate
1. Add a community permission
2. Do some other updates, like adding another permission or just editing the name

Wait until the reevaluation is done. See that the changes made at step 2 were lost/overriden.

#### Expected behavior

No change is lost

#### Actual behavior

Changes are lost

### Additional Information

- Status desktop version: 2.28.0

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/status-go/pull/5060

**Comment by osmaczko** [comment]
> @osmaczko do we need to cherry-pick this to develop/master?

It has been [cherry-picked](https://github.com/status-im/status-go/pull/5063) to status-go develop already.
