### ISSUE TITLE
TokenMaster permission missing token name

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14449]
# Bug Report

## Description

The token master permission is missing the name of the TokenMaster token.

![image](https://github.com/status-im/status-desktop/assets/50769329/d7176943-288c-42e1-b94e-fd9468020ccb)

#### Expected behavior

TokenMaster token is correctly displayed in the permission.

### Additional Information

- Status desktop version: 2.28.1 RC1
- Operating System: Mac

**Comment by kounkou** [comment]
Looking into it, expected screen should look like the following if I understand it right :

![Screenshot from 2024-05-05 23-55-48](https://github.com/status-im/status-desktop/assets/2589171/7a21da17-4d38-47d8-9593-24aa222e2e59)

To move fast on this ticket, I have a one liner change #14609 that produces expected result. However, I saw that the model from which the data is coming from is a `SortFilterProxyModel` between the `assetsMOdel` and the `collectiblesModel` and that the `text` FastExpressionRole should provide the necessary data but, it seems that this is not enough, hence producing the missing token name bug.

I have also assessed the change, and couldn't see any specific regressions whatsoever.

Therefore, I am reaching out to the front end team, to have more expert view over this issue if you don't see any drawbacks.
