### ISSUE TITLE
App crashed when joining community after sharing addresses (on membership request pending state)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14444]
### Description

https://github.com/status-im/status-desktop/assets/82375995/7c31fb1f-c791-46ba-9be7-1cffa454c916

**Comment by jrainville** [comment]
I saw that too yesterday. I was planning on reproducing later to see if it was a fluke, but it seems to happen to you too.

I'll assign someone

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/status-desktop/pull/14451
