### ISSUE TITLE
Send tag in SendModal doesn't show correct value

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#14448]
# Bug Report

## Description

The send on top of routes in advanced view shows sender address and not receiver address

## Steps to reproduce

Launch send modal 
Try to send a tx
Observe advanced view

#### Actual behavior

<img width="1792" alt="Screenshot 2024-04-25 at 9 39 33 AM" src="https://github.com/status-im/status-desktop/assets/60327365/347394d8-249c-4347-84da-9975c87fc78e">

### Additional Information

- Status desktop version: 2.28.1
- Operating System: Linux

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp is there a wrong screenshot attached?

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp is there a wrong screenshot attached?
added the correct screenshot now
