### ISSUE TITLE
Remove `data` folder when uninstalling/removing Status

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#1444]
Current, when uninstalling/removing Status and then reinstalling it, it remembers the accounts from the previous installation, which is unexpected.

Clean installations should not know about previous keys, unless they have been manually moved there.

**Comment by iurimatias** [comment]
this should be done as part of the installer once the first installer is in

**Comment by pinebit** [comment]
@iurimatias this is done for Windows installer already:
- when the user is uninstalling the app, it is prompted at the end of uninstall flow whether he/she wants to remove account data or not.
