### ISSUE TITLE
Members list is empty on new channel

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14442]
# Bug Report

## Description

user 1: Create open community
user 2: View community without joining it
user 1: Add new channel
user 2: View new channel without joining community

Members list is populated when viewing other channels but not when viewing the new one.

#### Expected behavior

Members list to be populated for new channel

### Additional Information

- Status desktop version: 2.28.1 RC1
- Operating System: Mac

**Comment by jrainville** [comment]
It's possible that my refactor here helps/fixes the issue: https://github.com/status-im/status-desktop/issues/12595

**Comment by MishkaRogachev** [comment]
Pausing due to https://github.com/status-im/status-desktop/issues/14700

**Comment by MishkaRogachev** [comment]
<img width="1405" alt="Screenshot 2024-05-16 at 23 05 01" src="https://github.com/status-im/status-desktop/assets/2522130/692841f9-d34c-4a20-9086-e5d5de7f3334">
reproduced
