### ISSUE TITLE
Use New SubModelProxyModel in Wallets

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#14454]
### Description

Use the new SubModelProxyModel in places where we are manually calculating total balance
Also replace places where we get total balance from nim side and use this mechanism instead

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

**Comment by micieslak** [comment]
Update: instead of `SubmodelProxyModel`, `ObjectProxyModel` should be used (https://github.com/status-im/status-desktop/pull/15029).

**Comment by saledjenic** [comment]
@noeliaSD  @micieslak this one is defined too general, could you be more precise saying what need to be done within this issue or what are issues this one is referring to?

**Comment by noeliaSD** [comment]
cc: @Khushboo-dev-cpp

**Comment by Khushboo-dev-cpp** [comment]
@saledjenic we were using javascript for loops to calculate total balance in wallet as it was not possible under the `ObjectProxyModel` then. This task was created to use ObjectProxyModel and get rid of the those functions to calculate total balance as it can be done more efficiently using ObjectProxyModel.

**Comment by saledjenic** [comment]
Closing this, based on Emil's comment.

**Comment by Khushboo-dev-cpp** [comment]
> @saledjenic we were using javascript for loops to calculate total balance in wallet as it was not possible under the `ObjectProxyModel` then. This task was created to use ObjectProxyModel and get rid of the those functions to calculate total balance as it can be done more efficiently using ObjectProxyModel.

@saledjenic @Cuteivist was also was referring to the part where total balance is calculated on the nim side and simplifying those models to agreed way of doing things on qml side instead. Is that also done for Account lists?
