### ISSUE TITLE
Notification about being kicked from community is shown in AC when user leaves community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14456]
### Description

1. join community as a member
2. right click - leave the community
3. check activity center

As result, there is a notification that you've been kicked

<img width="556" alt="Screenshot 2024-04-17 at 15 58 03" src="https://github.com/status-im/status-desktop/assets/82375995/bb3088ba-903e-4fe4-a8cd-431e56435562">

**Comment by jrainville** [comment]
Gonna close as no reproducible. Please reopen if it happens again.

**Comment by jrainville** [comment]
> Today shard.test was updated and I did not observe step 9 anymore. So this issue is not actually after shard update or something has been broken/fixed/changed on a waku

I think we can assume the store nodes are probably more unstable now, so we can still try to fix the issue as if it still reproduced
