### ISSUE TITLE
In testnet mode shared collectibles are not displayed in profile

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14468]
# Bug Report

## Description

In testnet mode the profile showcase does not show any shared collectibles (community ones in case of this test). Noted some mentions of goerli in logs but lost specific instance - it may be attempting to retrieve from goerli instead of sepolia.

![image](https://github.com/status-im/status-desktop/assets/50769329/ff3c3253-46ea-4b3e-8df2-1c3fea17aea6)

Link to an account via preview:
![image](https://github.com/status-im/status-desktop/assets/50769329/c744be13-42ea-4ee1-8744-2a815b28b096)

## Steps to reproduce

1. Share owner and TM token created on Sepolia Opt. on profile to everyone
2. View profile from another account

#### Expected behavior

Collectibles for the relevant network/testnet are shown.

### Additional Information

- Status desktop version: 2.28.1 RC1 
- Operating System: Mac

**Comment by MishkaRogachev** [comment]
If both clients use test net and collectible uses test main net, it works..
https://github.com/status-im/status-desktop/assets/2522130/fdc34ac3-dede-43ea-a094-4d3613620aac

Now trying with Sepolia
