### ISSUE TITLE
Can't join an encrypted community

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#14473]
# Bug Report

## Description

Can't  joining an encrypted community, share addresses button is disabled if even conditions are matching.

<img width="718" alt="Screenshot 2024-04-18 at 15 58 55" src="https://github.com/status-im/status-desktop/assets/2522130/6c42eb76-8b73-4443-9af5-6e4ef7f14a53">

## Steps to reproduce

1. Create a community
2. Add a permission, for example to view & post in a channel 
<img width="579" alt="Screenshot 2024-04-18 at 16 41 45" src="https://github.com/status-im/status-desktop/assets/2522130/9fdb32ae-72d5-49d4-8717-7c6d7a4cdf82">

3. Try to join without satisfied channel permissions
<img width="713" alt="Screenshot 2024-04-18 at 15 07 28" src="https://github.com/status-im/status-desktop/assets/2522130/cd7fcec7-a8f6-43bf-972d-3a5bcc12b57d">

4. Try to join with satisfied channel permissions
<img width="718" alt="Screenshot 2024-04-18 at 15 58 55" src="https://github.com/status-im/status-desktop/assets/2522130/b95be939-3020-4ce0-acdc-d59dee17d042">

5. Remove permission
6. Try to join again
<img width="699" alt="Screenshot 2024-04-18 at 16 26 13" src="https://github.com/status-im/status-desktop/assets/2522130/c2bcd9f6-728a-49ca-a645-05345b1bcc57">

#### Expected behavior

A user is able to share addresses and join on on steps 3, 4 and 6

#### Actual behavior

A user is not able to share addresses and join on on steps 3, 4 and 6

### Additional Information

- Status desktop version: current. master
- Network: test net

**Comment by caybro** [comment]
You have to wait for the permission check(s) to finish, sometimes it can take really long. That's also why I suggested to split the `requirementsCheckPending` bool property into 2 separate entities (for join/channels checks), as we just really need the former to enable this button

CC @jrainville

**Comment by caybro** [comment]
@MishkaRogachev ah, I also noticed this is on testnet; so maybe the wallet checks here do not pass?

**Comment by jrainville** [comment]
When I experienced it as well, the checks seemed to have finished. In Mishka's screenshots, there isn't a loader as far as I can see. We can also see that when he has the right tokens in his wallet, the Permissions are green, and when he doesn't have the right tokens, the permissions are grey. That means the checks finished.

The modal still says we can't join though, so there is a bug in the logic somewhere that still blocks joining when there is a channel permission it seems.

**Comment by caybro** [comment]
Ie, I think we're hitting this issue 
(https://github.com/status-im/status-desktop/issues/14299) here as well

**Comment by MishkaRogachev** [comment]
<img width="1298" alt="Screenshot 2024-04-18 at 17 03 22" src="https://github.com/status-im/status-desktop/assets/2522130/798b8473-c009-4251-80f7-659f62ee79dd">
@caybro same behaviour on the main net

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev can you check if you have an error with regards to the community check when the joining problem is there? Thanks

```
DBG 2024-04-18 17:07:18.888+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=12569274 file=threadpool.nim:54 messageType=AsyncCheckAllChannelsPermissionsTaskArg:ObjectType threadid=12569274 task="{\"$type\":\"AsyncCheckAllChannelsPermissionsTaskArg:ObjectType\",\"communityId\":\"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aa\",\"addresses\":[],\"vptr\":5285916752,\"slot\":\"onAsyncCheckAllChannelsPermissionsDone\",\"tptr\":4333165640}"
DBG 2024-04-18 17:07:18.888+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=12569275 file=threadpool.nim:54 messageType=AsyncCheckPermissionsToJoinTaskArg:ObjectType threadid=12569275 task="{\"$type\":\"AsyncCheckPermissionsToJoinTaskArg:ObjectType\",\"communityId\":\"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aa\",\"addresses\":[],\"vptr\":5285919216,\"slot\":\"onAsyncCheckPermissionsToJoinDone\",\"tptr\":4333660872}"
DBG 2024-04-18 17:07:18.888+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=12569274 file=core.nim:27 rpc_method=wakuext_checkAllCommunityChannelsPermissions
DBG 2024-04-18 17:07:18.888+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=12569275 file=core.nim:27 rpc_method=wakuext_checkPermissionsToJoinCommunity
DBG 2024-04-18 17:07:18.888+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=12569273 file=threadpool.nim:54 messageType=AsyncGetRevealedAccountsArg:ObjectType threadid=12569273 task="{\"$type\":\"AsyncGetRevealedAccountsArg:ObjectType\",\"communityId\":\"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aa\",\"memberPubkey\":\"0x04c9e4188bc2e74834bf49c0b75a14b0cdb0db5da63e363fb2c5e0a4e065374da4889a5c0c54f4776fe23d4e3aa640fb44709c32788036438e5453caa9ef7f7f96\",\"vptr\":5285919216,\"slot\":\"onAsyncGetRevealedAccountsForMemberCompleted\",\"tptr\":4333778596}"
DBG 2024-04-18 17:07:18.889+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=12569273 file=core.nim:27 rpc_method=wakuext_getRevealedAccounts
```
hmmm, i don't see the response from these RPCs

**Comment by jrainville** [comment]
> hmmm, no errors, but i can't see responses from these RPCs

We only log the thread starts, RPC calls and RPC errors. The responses are often very big, so not worth logging.

If you don't see an RPC error, we can assume it worked or it never returned, but in that case, we'd still have the loading indicator.

**Comment by MishkaRogachev** [comment]
> > hmmm, no errors, but i can't see responses from these RPCs
> 
> We only log the thread starts, RPC calls and RPC errors. The responses are often very big, so not worth logging.

I've added a few more logs (one wallet account selected):
```
--------------------> succeeded asyncCheckPermissionsToJoinTask: (jsonrpc: "2.0", result: {"satisfied":false,"permissions":{"e0eeb42f-ade5-4434-bd96-a2fa6bbd15a5":{"roles":5,"tokenRequirement":[{"satisfied":false,"criteria":{"contract_addresses":{"11155111":"0x2609c66E694D60dab75772Cc16b7d5D1AAA9E8CA"},"type":2,"symbol":"TM","name":"TMaster-","amount":"1","amountInWei":"1"}}],"criteria":[false]}},"validCombinations":[{"address":"0x131e56004d1d05839c86d304d54b863225dcdaab","chainIds":[1,10,42161]}],"roles":[{"type":5,"satisfied":false,"criteria":[{"roles":5,"tokenRequirement":[{"satisfied":false,"criteria":{"contract_addresses":{"11155111":"0x2609c66E694D60dab75772Cc16b7d5D1AAA9E8CA"},"type":2,"symbol":"TM","name":"TMaster-","amount":"1","amountInWei":"1"}}],"criteria":[false]}]},{"type":2,"satisfied":true,"criteria":null}],"highestRole":{"type":2,"satisfied":true,"criteria":null},"networksNotSupported":false}, id: 0, error: nil)
--------------------> succeeded asyncCheckAllChannelsPermissionsTask: (jsonrpc: "2.0", result: {"channels":{"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aa300a1d07-1028-4db2-9a01-7f2eb7bcab5c":{"viewOnlyPermissions":{"satisfied":true,"permissions":{}},"viewAndPostPermissions":{"satisfied":true,"permissions":{}}},"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aa3d4f4b0a-1119-4b98-9f9a-78e835e8a078":{"viewOnlyPermissions":{"satisfied":true,"permissions":{}},"viewAndPostPermissions":{"satisfied":true,"permissions":{}}},"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aa431b28fe-3b99-4e02-b999-75c37904f171":{"viewOnlyPermissions":{"satisfied":true,"permissions":{}},"viewAndPostPermissions":{"satisfied":true,"permissions":{}}},"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aa46133ad9-7496-49c5-b8a1-55c5d07eda65":{"viewOnlyPermissions":{"satisfied":true,"permissions":{}},"viewAndPostPermissions":{"satisfied":true,"permissions":{}}},"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aaa6e64d9d-d6d5-446b-bac3-3115e901bbe9":{"viewOnlyPermissions":{"satisfied":true,"permissions":{}},"viewAndPostPermissions":{"satisfied":true,"permissions":{}}},"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aac9a1aae6-68cc-4521-9e7c-fb79a9ca5e4a":{"viewOnlyPermissions":{"satisfied":true,"permissions":{}},"viewAndPostPermissions":{"satisfied":true,"permissions":{}}},"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aad99d6352-fefd-4ad6-8db2-742ef43563f6":{"viewOnlyPermissions":{"satisfied":true,"permissions":{}},"viewAndPostPermissions":{"satisfied":true,"permissions":{}}},"0x03328eb67284f26f5de2cb127491e129c6340c2931f2c8ac32a52548e72af1a7aaf1a1f99d-f861-4e15-ad13-cf88ceef2bec":{"viewOnlyPermissions":{"satisfied":false,"permissions":{}},"viewAndPostPermissions":{"satisfied":false,"permissions":{"49a90314-f3c2-42bd-997d-c4aad1f85e4a":{"roles":4,"tokenRequirement":[{"satisfied":false,"criteria":{"contract_addresses":{"11155111":"0x9D5DBDa78193807E44989b353613b65C1Cf5C51b"},"type":2,"symbol":"GUDAIR","amount":"1","amountInWei":"1"}}],"criteria":[false]}}}}}}, id: 0, error: nil)
```

Current community permissions:

<img width="582" alt="Screenshot 2024-04-18 at 17 27 23" src="https://github.com/status-im/status-desktop/assets/2522130/60484abe-d3bd-4079-a063-68d008491d60">

**Comment by jrainville** [comment]
> you didn't define any criteria for becoming a plain member

If there is no permission to join the community, then the community is considered open (anyone can join), whether or not there are other permissions. If you fit the admin permission, then when you join, you become an admin.

Same thing for a channel permission. If a community has a channel permission but no Join permission, then every one can join, but only those satisfying the channel permission can see/post in the channel.

**Comment by caybro** [comment]
> > you didn't define any criteria for becoming a plain member
> 
> If there is no permission to join the community, then the community is considered open (anyone can join), whether or not there are other permissions. If you fit the admin permission, then when you join, you become an admin.
> 
> Same thing for a channel permission. If a community has a channel permission but no Join permission, then every one can join, but only those satisfying the channel permission can see/post in the channel.

Alright... that changes the perspective; will have a look at this tomorrow :)

**Comment by MishkaRogachev** [comment]
> Ah! So you have join-like permissions (for Admin and TM) and then it makes sense no? You can't join since GUIDAR (the token for channel permissions) is simply not enough to join (you didn't define any criteria for becoming a plain member)

Well, it's worked for me after adding a token criteria for community membership, so something is wrong here about joining token-gated communities without explicit permission for membership.

<img width="659" alt="Screenshot 2024-04-18 at 17 41 15" src="https://github.com/status-im/status-desktop/assets/2522130/4b09f3c9-c918-4154-96e4-7f2fb623a2d2">

<img width="589" alt="Screenshot 2024-04-18 at 17 41 42" src="https://github.com/status-im/status-desktop/assets/2522130/14f52b1e-274f-45c0-a880-551d1084a945">
