### ISSUE TITLE
status-go integration tests for P0 critical APIs [spike]

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#14478]
This task follows on `P0` requirements for `v2.3` [discussed](https://www.notion.so/Wallet-Quality-Must-Haves-90ef0704dd054500a89fef8ef57d48fe) by the wallet team

- [x] #14506
- [ ] #14535
- [ ] Basic test for `wallet_getSuggestedRoutes`
- [ ] Integrate with CI

Notes:

It builds on the debugging tests [here](https://github.com/status-im/status-desktop/blob/master/test/status-go/integration/README.md)

**Comment by stefandunca** [comment]
> Check [Foundry](https://book.getfoundry.sh/getting-started/installation) for blockchain abstraction

@anastasiyaig this was the task I planned to tackle for our blockchain end validation

**Comment by anastasiyaig** [comment]
https://github.com/status-im/desktop-qa-automation/issues/445 @stefandunca we have this task and made some progress but we have to do from scratch for Sepolia and Anton will do that from testing perspective with some backup from devs if needed (our app may not suite completely so i am predicting we will have to make some code changes to support all that) @stefandunca @alaibe

**Comment by stefandunca** [comment]
> [status-im/desktop-qa-automation#445](https://github.com/status-im/desktop-qa-automation/issues/445) @stefandunca we have this task and made some progress but we have to do from scratch for Sepolia and Anton will do that from testing perspective with some backup from devs if needed (our app may not suite completely so i am predicting we will have to make some code changes to support all that) @stefandunca @alaibe

Looking forward to see some configuration setup/code for deploying our contracts to reuse in our integration tests.

**Comment by anastasiyaig** [comment]
i will keep you updated for sure. anton starts on May 1 , and this is his high prio task when he finishes onboarding

**Comment by stefandunca** [comment]
@IvanBelyakoff had picked up the "increase automated testing for the critical workflows" that was the end goal for this prototype.

**Comment by saledjenic** [comment]
Closing this in favour of #14641
