### ISSUE TITLE
Cannot send ERC20 tokens

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#14487]
# Bug Report

## Description

The amount of ERC tokens is not reflected in send popup

## Steps to reproduce

1. Go to ENS usernames
2. Choose name and click next
3. Click register ens username

https://github.com/status-im/status-desktop/assets/141633821/6761f6d0-b758-496f-a8dc-8cc9d4600188

#### Expected behavior
The amount of 10 STT is reflected in send popup and we can send it 
#### Actual behavior
The amount is 0 and we cannot send 
### Additional Information

- Status desktop version: the latest master
- Operating System: macOS ventura 13.5

**Comment by anastasiyaig** [comment]
@dlipicar can you please check on that as well?

**Comment by saledjenic** [comment]
@Valentina1133 please cold you check this issue, after this one gets merged https://github.com/status-im/status-desktop/issues/14466?
It looks like the same issue.

**Comment by Valentina1133** [comment]
@saledjenic I checked, it works now, all good, so I am closing the issue
