### ISSUE TITLE
100% of the CPU is used when there is no network

### ISSUE THREAD

**Issue by friofry** [status-im/status-desktop#14510]
# Bug Report

## Description

When running Status Desktop without an Internet connection, CPU usage is very high.
Doesn't reproduce when network is enabled.

## Steps to reproduce
1. Turn off the network on the computer
2. Launch the application

#### Expected behavior
CPU usage should be as low as possible (around 0-3%).

#### Actual behavior
High CPU usage on application startup

### Additional Information

CPU usage is low when network is on

https://github.com/status-im/status-desktop/assets/1083341/8e3104a0-9b0f-4f6a-b30d-0044ba62d693

CPU usage is *high* when there is no network

https://github.com/status-im/status-desktop/assets/1083341/21ca0f24-5475-435f-a18b-ecff0920843d

- Status desktop version: master on [e8a78e21](https://github.com/status-im/status-desktop/commit/e8a78e21)

<kbd>
<img width="262" alt="image" src="https://github.com/status-im/status-desktop/assets/1083341/91df96e0-b238-4aa6-b095-740ebee429e8">

</kbd>

- Operating System: Macos

**Comment by jrainville** [comment]
@friofry it should be easy to identify the source if you use something like [hotspot](https://github.com/KDAB/hotspot). However, this one is for Linux, so you'd need to find a Mac version (I assume it exists somewhere).
If you can't find something that works for you, I can reassign to someone that's on Linux

**Comment by caybro** [comment]
> @friofry it should be easy to identify the source if you use something like [hotspot](https://github.com/KDAB/hotspot). However, this one is for Linux, so you'd need to find a Mac version (I assume it exists somewhere).
> If you can't find something that works for you, I can reassign to someone that's on Linux

Hotspot is Linux exclusive

**Comment by friofry** [comment]
The issue is related to the `manager.go` `StartTorrentClient()` method.

<kbd>
<img width="1423" alt="image" src="https://github.com/status-im/status-desktop/assets/1083341/3f4db6d5-2db0-438f-93bc-28fbdb61b722">
</kbd>

(I'm using the MacOS CPU profiler from Instruments and building the application with `INCLUDE_DEBUG_SYMBOLS=true`).

If I comment out this call, the CPU usage is normal. I continue to investigate this issue.

**Comment by jrainville** [comment]
Good find. If we can use some kind of function that can tell us if we have connection, then we can skip this function until connection is re-established. @richard-ramos might have an idea if we have such a function
