### ISSUE TITLE
Inclusion of Watched addresses in Balances: Wording change

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14517]
The toggle to include a watched address in the user's balance has been tweaked to make it's impact clearer.

----

Before:
Toggle label read: `Include in total balance`
<img width="1309" alt="Screenshot 2024-04-25 at 10 03 31" src="https://github.com/status-im/status-desktop/assets/110033914/908f0ae0-bcc7-4f59-ae96-c0903a9653c1">

----

After:
Toggle label now reads: `Include in balances and activity`
<img width="1291" alt="Screenshot 2024-04-25 at 10 04 26" src="https://github.com/status-im/status-desktop/assets/110033914/18b396f2-04f2-448e-9e32-ce72230594e9">

----

The toggle is located inside a Watched address in Wallet Settings:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=19218-314055&mode=design&t=eAPE9MgFwYAfzubf-4

----

The relevant right-click context menu wording has also been adjusted to align:

<img width="757" alt="Screenshot 2024-04-25 at 10 16 24" src="https://github.com/status-im/status-desktop/assets/110033914/a4e18109-acfb-4301-be7e-d28fa647de2f">

<img width="603" alt="Screenshot 2024-04-25 at 10 16 56" src="https://github.com/status-im/status-desktop/assets/110033914/604ea61c-6538-4e4b-8273-c868f99b5edc">

cc @Khushboo-dev-cpp

**Comment by benjthayer** [comment]
@caybro @Khushboo-dev-cpp this also includes the wording of the right-click context menus for Watched addresses (I've adjusted the description above) 🙏

**Comment by caybro** [comment]
@benjthayer I also took the opportunity to replace the wording here in the main overview under Settings/Wallet, wdyt?

![image](https://github.com/status-im/status-desktop/assets/5377645/25082c7e-4243-41a3-98e8-3540a1726e35)
