### ISSUE TITLE
[Check #14639] No routes found when bridging

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#14513]
# Bug Report

## Description

When bridging some ERC20 on latest master we get no routes found all the time. We need to validate if this is accurate as the l1 fee was newly added and we need to make sure its not leading to this issue.

### Additional Information

- Status desktop version:
- Operating System:

**Comment by anastasiyaig** [comment]
i will add a test for that https://github.com/status-im/desktop-qa-automation/issues/651

**Comment by saledjenic** [comment]
Should be tested after #14638 (#14635)

**Comment by saledjenic** [comment]
I checked this, it's not the case anymore.

@anastasiyaig you can test this in the router v2 integration PR https://github.com/status-im/status-desktop/pull/15344

![Image](https://github.com/status-im/status-desktop/assets/86303051/6380178a-1ca8-4a8e-b2b9-fd1961a37eb9)
