### ISSUE TITLE
Disable language selector, set `English` as default language and add option in advanced settings to manually enable its visualization

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14527]
### Description
1. By default, the language selector MUST be disabled and the default language set is `English`. The design for this use case is below in comments

2. If an existing user already has a language different than `English`, this will be reset to `English`.
3. The user shall be able to enable the `language selector` by selecting the following option in `Advanced settings`:
`Enable language selector` --> New advanced option shall be added

    And then, the design should be the following one (existing one):

<img width="1400" alt="Screenshot 2024-04-26 at 10 45 10" src="https://github.com/status-im/status-desktop/assets/97019400/12fd5395-a997-4acf-bb74-52f395483528">

4. Whenever a user disables the language selector, `English` must be set up as the default language.

**Comment by noeliaSD** [comment]
@benjthayer we need an easy design for that! :)

**Comment by noeliaSD** [comment]
@anastasiyaig here the task that needs to be added to the `2.28.1`, where the language selector is hidden and `English` is selected by default. Please, take a look at the description and if you think there are missing usecases, let us know!

**Comment by noeliaSD** [comment]
@caybro this task MUST land directly in `2.28.1`release and then being cherrypicked to `master`.

**Comment by noeliaSD** [comment]
cc: @iurimatias @jrainville

**Comment by benjthayer** [comment]
@noeliaSD quick proposal in relation to this

1) Disable the language selection control with English populated
2) Show tooltip on hover to clarify `Translations coming soon`
3) Add info panel to encourage users to engage with the community driven translation process, linking them out to https://status.app/translations
4) Avoid giving the everyday user any way to turn on the language selection control given we don't have any translations as I understand - so doing so will have minimal impact in the UI (if only the occasional word will be translated). We would need to add too many caveats along with the advanced setting control to inform the user of it's limited utility.
5) Instead, for development purposes, enable the control under `Full developer mode` so we can test the translations internally.

WDYT?
 
<img width="1353" alt="Screenshot 2024-04-26 at 10 52 29" src="https://github.com/status-im/status-desktop/assets/110033914/2335310e-75bf-4c1a-b506-a05029a404fb">

Figma
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=24303-93806&mode=design&t=hBUEKYIso1IfDH4i-4

cc @John-44

**Comment by caybro** [comment]
Still needs this backport: https://github.com/status-im/status-desktop/pull/14552
