### ISSUE TITLE
Update the app logo to the new one (multicoloured)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14531]
### Description

update the app logo in the task bar and tray and everywhere else it's used to the new one that is multicoloured.

cc @benjthayer where can I find the right images

**Comment by benjthayer** [comment]
> ### Description
> update the app logo in the task bar and tray and everywhere else it's used to the new one that is multicoloured.
> 
> cc @benjthayer where can I find the right images

Hey @jrainville will get back to you - reaching out to Filipe who I think designed it.

**Comment by caybro** [comment]
We have many variants (rounded x squircle, orange for dev, blue for release) :)

**Comment by benjthayer** [comment]
> We have many variants (rounded x squircle, orange for dev, blue for release) :)

Thanks @caybro are you able to share the suite of app icons we need to support using the new app icon? I can then use that as a basis to make sure we have everything covered off.

**Comment by caybro** [comment]
> > We have many variants (rounded x squircle, orange for dev, blue for release) :)
> 
> Thanks @caybro are you able to share the suite of app icons we need to support using the new app icon? I can then use that as a basis to make sure we have everything covered off.

Yup, will try to post them here :)

**Comment by caybro** [comment]
@benjthayer 

Dev icon (orange, rounded):
https://github.com/status-im/status-desktop/blob/master/status-dev.svg

Mac dev icon (orange, squircle):
https://github.com/status-im/status-desktop/blob/master/status-macos-dev.svg

Release icon (blue, rounded):
https://github.com/status-im/status-desktop/blob/master/status.svg

Mac release icon (blue, squircle):
https://github.com/status-im/status-desktop/blob/master/status-macos.svg

**Comment by caybro** [comment]
Oh, and another bundle pair for macOS:

https://github.com/status-im/status-desktop/blob/master/status.icns

and dev: https://github.com/status-im/status-desktop/blob/master/status-dev.icns

**Comment by caybro** [comment]
And for Windows installer:
https://github.com/status-im/status-desktop/blob/master/status-macos.ico

**Comment by jrainville** [comment]
The orange ones for dev can stay as is, but for the prod ones, we do want the multicolored ones.

**Comment by jrainville** [comment]
@benjthayer do you have news on this?

**Comment by benjthayer** [comment]
> And for Windows installer: https://github.com/status-im/status-desktop/blob/master/status-macos.ico

Hey @caybro just exporting these now with the new logo but this link looks to be the macos - is there a .ico file for Windows? Thanks!

**Comment by benjthayer** [comment]
Hey @jrainville - new logo exports attached. May be a couple more exports to come based on @caybro 's reply to my above comment.

[Status-New-Logo-Exports.zip](https://github.com/status-im/status-desktop/files/15231573/Status-New-Logo-Exports.zip)
