### ISSUE TITLE
Community: community invitation is missing intro and logo

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14536]
### Description

Steps:

1. add a contact
2. create community with the following params:

```
name	'29042024_045229'
description	'Rp5ErorOUwSsItH2heqJavi2Zxr61ncldXLVUsT38MwgMQVz5VEjcgxIzn43SKEBTG3eICtXEn8pCQAOorK4MVzzX9ddOcZ3v35Q8NDJ2rcnfKHfMM7h5pyqiKLKCZBzkrVlcv5YWotY'
intro	'4NL2F0D7pcGBClF3GXMCP3lwpkbrLmLpOB3QQudPetCpY53J93ss90D2EEjz1bFLVhqc6BjUUfrg1zpcbMigXIzttrjgM6Zgpkwzuwl0ZfevTvojOVXHW63AoKEkQBQEpntU1ZkBe9Ei4Ds8UsCLsn95iOWQbQZSuhytXrM2CB0i3g5fzltTpONo675x1q6fsINe0EgY'
outro	'8I18uJjDOs02UIULW7KqHU17HKUf4ghS1mngjDV8qldGBupziKyLeapuUBLXr1FPLeUlhKH29mrJBeYl'
````

3. invite a friend to that community
4. as invitee, click Join community

on my mac:

<img width="1512" alt="Screenshot 2024-04-29 at 11 11 44" src="https://github.com/status-im/status-desktop/assets/82375995/d69b0883-33a4-439b-bfe8-92a64ea693d5">

on linux:
![image](https://github.com/status-im/status-desktop/assets/82375995/9aaa72b1-ae0a-4aad-bc01-d38b53bca32f)

**Comment by caybro** [comment]
@anastasiyaig what Qt versions are those on mac and linux?

**Comment by anastasiyaig** [comment]
mac has 5.15.13
linux is 5.15.2
@caybro
