### ISSUE TITLE
Add WC connected dApps list

### ISSUE THREAD

**Issue by clauxx** [status-im/status-desktop#14557]
### Description
_As a user, I want to know which dApps I am connected to, so that I can manage them in the future (e.g. disconnect)_

The user should see the dApps they're connected to on a specific account. Shouldn't focus on design fidelity, but rather on the correctness of the flow.

[Design link](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=28-33839&mode=design&t=vDEK7XNRpW1HQBUi-4)

### Acceptance Criteria

- [x] The user should see a list of dApps having active sessions for the current account when pressing the "dApps" button
- [x] The user should see the empty state screen if there are no connections

**Comment by stefandunca** [comment]
Started working on this to integrate and test the persistence API here https://github.com/status-im/status-go/pull/5191
