### ISSUE TITLE
Non-transferrable community token can be chosen in "Send tx" assets

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#14578]
# Bug Report

## Description
Expected that tokens that are not transferrable wouldn't be possible to choose as assets for sending

## Steps to reproduce
*Prerequisite*: have 1 community token, non-transferable (Status CC in my case) 

step1: Open Send
step2: select community token 

Video:  [bug_1.mp4](https://drive.google.com/file/d/18uIgdSy7uoyYCcfrX3zdZ-JY2nDgVpqq/view?usp=drive_link)

- Status desktop version: nightly 30/04/24
- Operating System: Mac OSx
- Network: mainnet

**Comment by alaibe** [comment]
@churik why are you saying this is not transferrable?
As far i know, those are erc721 and they transferrable

**Comment by jrainville** [comment]
If it's the same StatusCC from the Status community, then it is **not** transferable
![image](https://github.com/status-im/status-desktop/assets/11926403/b97acacb-e974-4626-9910-161e90571afa)

**Comment by churik** [comment]
@jrainville StatusCC, you are right. They should be `not transferable` according to desktop UI

**Comment by belalshehab** [comment]
blocked by https://github.com/status-im/status-desktop/issues/15512
currently used `nestedCollectiblesModel` will be removed completely

**Comment by micieslak** [comment]
@xAlisher It requires some design updates or decisions. Should we just remove those not nontransferable tokens from the selector or present them as disabled (e.g. grayed-out)?
