### ISSUE TITLE
Community channel color should be by default, the community color one

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14570]
### Description
Issue spoted by the design and mobile QA team during the offsite:

Whenever a user creates a new channel on a community, the default color for this channel should be the community color. Right now, the default selected color is blue.

Here a video for better understending where the following community color is set to `green` but whenever a new channel is created, the default color is set to `blue` instead of the same `green` color:

https://github.com/status-im/status-desktop/assets/97019400/2c79fe23-0fb2-4593-90cb-35b5ad9f6599

**Comment by noeliaSD** [comment]
cc: @jrainville

**Comment by caybro** [comment]
I think this is more a UI issue? We can take the community color and preset it when creating the channel (before opening the dialog) @jrainville @noeliaSD

**Comment by jrainville** [comment]
Yeah that's probably true. Either way, it's a pretty simple issue

**Comment by benjthayer** [comment]
Speaking with @noeliaSD about this and I agree, the new channel colour should adopt the community colour by default. This enables the channel list to maintain the community "brand" by default, allowing the user to quickly spin up channels that are brand-congruent before potentially returning to create some other colour system eg changing colours per category like we do in the Status community.

If we do this, it might also make sense to pre-populate the community colour into the `Channel colour` field shown below. Reduces clicks for users wanting to spin up channels quickly with the default community colour and no change in number of clicks for users who want to deviate from the community colour for the new channel. WDYT?
 
<img width="1140" alt="Screenshot 2024-05-02 at 16 23 34" src="https://github.com/status-im/status-desktop/assets/110033914/f28ca3ba-66ad-4582-9c69-e243b440794d">

cc @John-44 @noeliaSD

**Comment by jrainville** [comment]
I just did a quick test and it's indeed a UI task. The community color is already available in `communityData.color`. You guys just need to pass that color to the ColorPicker.

I'll change the label to ui-team
