### ISSUE TITLE
Pasting address on "Send transaction" screen leads to the space in the end and jumping cursor to the beginning of the input

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#14576]
# Bug Report

## Steps to reproduce

- Paste legacy address to the address field

https://github.com/status-im/status-desktop/assets/4557972/51ee9cf5-9920-424f-835f-59c3e7dfa697

#### Expected behavior
- value is pasted as-is;
- The position of the cursor is not changing

#### Actual behavior
- ' ' added in the end
- cursor jumps to the beginning of the value

### Additional Information

- Status desktop version: nightly 30/04/24
- Operating System: Mac OSx
- Network: mainnet

**Comment by caybro** [comment]
Slightly different behavior on master:
- pasting via Ctrl+V works fine
- pasting with the "Paste" button does _NOT_
- the cursor still jumps to the beginning
