### ISSUE TITLE
Hidden channels appear in search if previous messages were unencrypted

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14586]
# Bug Report

## Description

Channel is hidden (assumed due to permissions not met) but messages from that channel still appear in search.

![image](https://github.com/status-im/status-desktop/assets/50769329/42a3eebc-08bc-4e28-8bde-7b8bc0497e26)

Edit by @jrainville : The problem is that the channels where "closed" later, so when they first were created, everyone had access and some unencrypted messages were sent to them (or encrypted, but to which you had access).
Then, once the channel was closed and hidden, the new messages are indeed encrypted and not findable in the search, but you can still find the old messages.
**The Solution**: We need either hide or not provide messages from those hidden channels. The optimal solution is to tweak the status-go code so that if a channel is closed/encrypted, we never return messages from that channel, because the user won't have access to it anyway (especially if it's hidden, we do not want to leak its existence [there is a task to encrypt hidden channel metadata so that it becomes impossible to leak]).

### Additional Information

- Status desktop version: 2.28.1 RC 6
- Operating System: Mac

**Comment by jrainville** [comment]
I think this might be because we added the permissions to the channel later, so the first messages posted to that channel are unencrypted.

We need to confirm if encrypted messages (from today for example) also appear in the search.

**Comment by jrainville** [comment]
I confirmed with Magnus that indeed, the newer messages are encrypted and only previous unencrypted messages are "leaked".

I'll move this to 2.29 then and modify the issue description

**Comment by jrainville** [comment]
This one could be related to https://github.com/status-im/status-desktop/issues/13878
