### ISSUE TITLE
Failure to get fees during airdrop

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14587]
# Bug Report

## Description

Cannot proceed with Airdrop on L2 due to failure to get fees. Confirmed on testnet and mainnet.

![image](https://github.com/status-im/status-desktop/assets/50769329/0555b5bc-a852-4339-a45e-000b48eacc9a)

### Additional Information

- Status desktop version: 2.28.1 RC 6
- Operating System: Mac

**Comment by anastasiyaig** [comment]
it is now fixed in rc
