### ISSUE TITLE
API keys for market providers

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#14591]
### Description

CoinGecko and CryptoCompare's free plans work fine as long as users access their APIs from different IP addresses. During the offsite we got disastrously throttled and many features got broken because we couldn't fetch token prices.
It's okay to keep the free plan as the main option, but we should have a backup plan and use API keys whenever we get throttled.

We probably need to strike some deal to allow multiple clients to access the same keys though
https://www.coingecko.com/en/api/pricing
https://min-api.cryptocompare.com/pricing

**Comment by saledjenic** [comment]
Closing this ion favour of #14509
