### ISSUE TITLE
Hovering community in the profile showcase leads to crash

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#14596]
# Bug Report

## Description

https://github.com/status-im/status-desktop/assets/2522130/f399b4e3-4080-463a-8381-f41e84f6d77c

## Steps to reproduce

1. Open profile for a contact
2. Hover some community in the contact's profile showcase

#### Expected behavior

No segfault

#### Actual behavior

Segfault

### Additional Information

Current master: 1884f6e03378f7c1ca713e6591c304bb8083b47f

**Comment by caybro** [comment]
@MishkaRogachev try again pls with latest master, I _think_ I fixed this with my PR https://github.com/status-im/status-desktop/pull/14564

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev try again pls with latest master, I _think_ I fixed this with my PR #14564

Hmm, just updated and tried again. Crashes for me with: 
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [run-macos] Segmentation fault: 11
```

**Comment by jrainville** [comment]
cc @noeliaSD . It's possible that this is only in master, so you can change the milestone to 2.29 if that's the case

**Comment by caybro** [comment]
Just for reference, this is crashing deep in Qt, with no code of ours in sight; reproducible in StoryBook too (ProfileDialogViewPage.qml)

![image](https://github.com/status-im/status-desktop/assets/5377645/8aeeb4ab-ce8e-4b45-ba55-0d59c284058a)

**Comment by caybro** [comment]
More investigation: the culprit looks like it's the `DropShadow` in the background of `StatusCommunityCard`

**Comment by caybro** [comment]
@MishkaRogachev to test a tentative fix from me
