### ISSUE TITLE
Community tag icon is missing

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14599]
### Description

1. open communities portal
2. check on the Status community tags

As result, there is no icon for the Ethereum tag

<img width="412" alt="Screenshot 2024-05-03 at 12 01 04" src="https://github.com/status-im/status-desktop/assets/82375995/b3eec92a-9d77-4fc3-ad73-3e631eae023a">

**Comment by anastasiyaig** [comment]
@jrainville i asked @caybro to check on that and he found that it has to be something on go / nim

**Comment by jrainville** [comment]
I'm letting this issue go back to the UI team. I tried to fix it, but I only created a new bug. The data is all ok from the backend, it just needs to be fixed in Twemoji or our QML components.
