### ISSUE TITLE
Changing the channel emoji doesn't update until saved (same thing in the wallet)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14605]
# Bug Report

## Description

When you edit the emoji of a channel or a wallet account, the emoji doesn't appear until you save.

[emoji-save.webm](https://github.com/status-im/status-desktop/assets/11926403/25e0760a-62f3-4715-a8b5-8e09e5a37615)

## Steps to reproduce

1. Right-click a channel and click edit
2. Click the emoji
3. Choose a new one
4. See that the icon stays empty
5. Save
6. See that it did update

Logs:
```
Warning: qrc:/StatusQ/Components/StatusLetterIdenticon.qml:29:5: QML StatusEmoji: Cannot open: qrc:/assets/twemoji/svg/3c.svg (qrc:/StatusQ/Components/StatusLetterIdenticon.qml:29, )
```

#### Expected behavior

The emoji shows right away

### Additional Information

- Status desktop version: master `3fd96986da1f8a4b997dd599f9a44c56adfecf29`

**Comment by jrainville** [comment]
cc @noeliaSD

**Comment by caybro** [comment]
Just tried locally (master) and  I can't reproduce either in the channel or rename account modal

**Comment by caybro** [comment]
It's again the function `Emoji.iconId`... maybe it's just a specific emoji that fails for you?

**Comment by jrainville** [comment]
Ah my bad, I thought I tested master, but indeed, my changes caused the bug
