### ISSUE TITLE
Remove the Browser from the app completely for now

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14614]
### Description

Since the browser is hidden by default, plus it is not gonna get any love until a later milestone, we should remove it from the app.

It will make the app bundle way smaller and possibly make the app start faster and maybe even use less memory.

### Acceptance Criteria

- Any UI reference to the Browser is removed (setting, icon in tab, etc)
- the NIM module at `modules/main/browser_section`
- ~~Binaries that are included for the browser are removed from the build (QtWebEngine) (double check with the Wallet team in case they use it for any of their features like WalletConnect)~~

**Comment by alexjba** [comment]
@jrainville Looks like we have some status-go code as well + DB table we need to clean. Can we reopen this task, or create a new one on status-go?

E.g. https://github.com/status-im/status-go/blob/develop/services/browsers/README.md

**Comment by jrainville** [comment]
> @jrainville Looks like we have some status-go code as well + DB table we need to clean. Can we reopen this task, or create a new one on status-go?
> 
> E.g. https://github.com/status-im/status-go/blob/develop/services/browsers/README.md

@alexjba it's better to open a new issue I think
