### ISSUE TITLE
[EPIC] Check the router

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#14638]
Within this issue we should go step by step through the router logic and confirm that it returns the appropriate routes for all different input values. 

Some things to check/improve:
1. the routing algorithm at the first step should find all potentially possible routes based on set parameters and how much each of them costs (which is `candidates` array in the current implementation) 
2. the second step should check if the cheapest route is selected as the best one (it should be like that in the current implementation)
3. after selecting the cheapest route we should check if there are enough balances to pay everything needed for all routes, at the current implementation `nativeBalance` is compared to `requiredNativeBalance` per route, but if there need to be multiple routes (transactions) current code always use the current value, doesn't subtract amount needed for previous transactions

Desktop app test page that will help testing the Router:
- https://github.com/status-im/status-desktop/pull/14846

Celer Bridge:
- set under the feature flag, and moved to 2.31 - #14652

Routes that need to be checked:
- [x] #14651
- [x] #14653
- [x] #14654
- [x] #14655
- [x] #14656
- [x] #14657
- [x] #14658
- [x] #14659
- [x] #14660
- [x] #14661
- [x] #15070

**Comment by alaibe** [comment]
regarding 3. This is because we don't send more than 1 tx per chain (except approval request)
