### ISSUE TITLE
Rename the `Bridge` interface to `PathProcessor `

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#14637]
The name `Bridge` for the interface which is used for many different purposes is misleading a bit, though it dates from the time when we had only bridge logic there, but later other transactions were added there like erc721 and erc1155 transfers, swap and now would be good to rename it to something more common to all that like `PathProcessor `.

**Comment by alaibe** [comment]
my 2 cents suggestion: TransactionConnector
