### ISSUE TITLE
Some tokens are missing in the permission's token list even though they are in the Admin's Token List

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14679]
# Bug Report

## Description

Iuri minted the Logos token multiple times, and each time, while we can see the tokens in the admin's Token List, they never show in the Permission view.

Shows here:
![image](https://github.com/status-im/status-desktop/assets/11926403/0b5c9b93-33a2-4c9a-945b-d9fadc1b6af5)
![image](https://github.com/status-im/status-desktop/assets/11926403/4b68f7ee-bf95-43dd-a7ae-615d6d89b70e)

Does **not** show here:
![image](https://github.com/status-im/status-desktop/assets/11926403/b8dbaed3-22b5-4a46-bcc5-4ee3dae45b92)
![image](https://github.com/status-im/status-desktop/assets/11926403/36207763-c963-40ec-94d0-1837f3f59deb)

## Steps to reproduce

We don't know the exact steps why it got this way.

The best way to work on this would be to be TokenMaster like @noeliaSD or me and debug the app as is.

#### Expected behavior

Any token in the token list is also available in the permission list (except special tokens like owner token)

#### Actual behavior

Missing tokens

### Additional Information

- Status desktop version: 2.28.1

**Comment by noeliaSD** [comment]
The first step we can follow is using the _monitoring tool_ to inspect the **backend model** easily. To run this tool:
- make clean
- make -j10 MONITORING=true run

Once running, inspect the following model like in this video: **communitiesModule/collectiblesModel**

https://github.com/status-im/status-desktop/assets/97019400/ad41e10b-02bc-4e31-b907-f49861777c05

- This model must contain exactly the same items than the ones shown in `Community Settings / Tokens page`. 
  - If some items are missing there, there's something wrong in the items exposed by the backend model.
  - If all the items expected are present, it's a UI filtering issue in permissions view.

**NOTE**: I tried to reproduce but couldn't bc my tokens list page is not updated with the last minted tokens data. The new created ones are still not part of the list my app displays. 

@jrainville if you already have the list updated with the "problematic" tokens, please, try this procedure!

**Comment by jrainville** [comment]
I have investigated and I found the reason for the discrepancy between the two lists.

The Permissions list uses the `communitiesModule` model that uses the `CommunityDto` as the source for its tokens.
The `CommunityDto` object is what is being passed in the community description.
It contains only the metadata for the tokens.

On the other hand, the Tokens list that Owners and TokenMasters can look at comes from the `community_tokens` table directly. Only TMs and Owners have that info, because it's heavier and is not needed by any other user.

I have not finished investigating, but my guess is that when minting the Logos tokens, something went wrong at the very end and the tokens were not properly saved to the community description, making them impossible to assign to permisisons.

The solution is gonna be twofold:
1. Try and identify why it failed and fix it
2. Retroactively fix previously failed tokens so that they are saved to the community description and sent to TokenMasters

**Comment by jrainville** [comment]
So it turns out it's quite related to https://github.com/status-im/status-desktop/issues/14699

The saving to the Community Description very much depends on the Nim code getting the notification that the transaction ended. Then, when it ends, Nim sends back a call to status-go to save the community token to the community desctription.

So for most of the new tokens, it sounds like the message from Nim <-> status-go had some issues somewhere.

As for the older tokens that I managed to have in my own DB and that I even could see for a moment in the permissions list, what I think happened is that we were hit with the [community changes being lost issue](https://github.com/status-im/status-desktop/issues/14432).
Thankfully, that issue doesn't exist anymore.

So the **solution** here is gonna be similar for both https://github.com/status-im/status-desktop/issues/14699 and this one. We need to calculate the differences between the tokens inside the Community description and the ones inside the `community_tokens`. 
When we detect that a token is in the table and not in the description, we need to add it using the `AddCommunityToken` function.

The TokenMaster will fix itself automatically when the community description gets updated with the completed token data, since it detects when it doesn't have a token in its DB and if not, fetches the data from the chain.

Since I don't want to step on @endulab 's toes plus I won't have much more time today, I'll let you do the start of the work, since it should be the same thing for you, or at least wait until you let me know if I can do the changes I listed above.

In theory, we both need the part about saving in the community description, you probably just need the additional check on chain to see if the transaction is done. If it is, then you can save. In case you forgot, you can use `FetchCommunityToken` to get the data from the chain about the token.

**Comment by endulab** [comment]
@jrainville we can't do this. We add the token to community description ONLY if the transaction was minted correctly.
If it is in progress, there is a possibility that it may fail and it should not be added to community description.
I think we need to consider adding my refactoring to the RC.

**Comment by jrainville** [comment]
After discussion, we agreed that the transaction refactor is the best way to solve the root cause.

However, we still want to fix retroactively the missing tokens in the description. Therefore, I'll implement a fix where it will sync the community tokens table with the community description. That way, we'll guarantee that any token that is correctly minted will always be in the description.

**Comment by jrainville** [comment]
Fixed here https://github.com/status-im/status-go/pull/5188 and here for the release https://github.com/status-im/status-desktop/pull/14752
