### ISSUE TITLE
Token gating flag for Status Community

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14671]
The Status community is a mix of token gated and open to public channels. 

I believe we should only show the token gating if it is relevant to joining the community? So in the case of the Status community, we shouldn't show any token gating details top right of the card?

<img width="387" alt="Screenshot 2024-05-09 at 17 05 57" src="https://github.com/status-im/status-desktop/assets/110033914/1effeade-6657-4069-a295-d8b411403b1c">

Relevant flows:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=2365-261989&mode=design&t=fBtpHEJlaNJGkl36-4

WDYT @John-44 ?

**Comment by benjthayer** [comment]
Also, we should probably consider a way for users to learn more about the token gating via the card - eg a tooltip on hover of the token gating tag (one for design to take on)

**Comment by John-44** [comment]
@benjthayer correct, if a community doesn't have any "tokens required to become a member" permissions, then no tokens should be displayed on the card.

cc'ing @jrainville @iurimatias

**Comment by caybro** [comment]
This is a UI bug... we simply show this row of icons when we detect _any_ permissions :/
```qml
visible: !!card.permissionsList && card.permissionsList.count > 0
```

**Comment by caybro** [comment]
I'll have a look at this

**Comment by caybro** [comment]
@benjthayer should we show the "lock" icon (without tokens) if the join permissions are private, or just hide it completely?
