### ISSUE TITLE
[UI - dapps Connection] Create `Connect a dApp` dialog and initial URL input page

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14674]
### Description

[Design](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=3649%3A30909&mode=design&t=LpX0Wx80R6SXcYAl-1)

![Screenshot 2024-05-09 at 19 44 57](https://github.com/status-im/status-desktop/assets/97019400/74eb11cd-120a-46b8-bf98-e53a3047c33f)

[Parent User Story link](https://www.notion.so/Establishing-dApp-connection-934645fe8d704cd1af8e4fc078805377)

- [x] #14675
- [x] #14676
- [x] #14677

**Comment by stefandunca** [comment]
All tasks are finished. This user story is ready for testing.
