### ISSUE TITLE
[UI - dApps Connection] Session proposal and establishment `User Story`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14688]
[Design](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=626%3A119496&mode=design&t=iMRTBgKquR8Eq9bf-1)

![Screenshot 2024-05-10 at 09 52 39](https://github.com/status-im/status-desktop/assets/97019400/dcf54435-ac83-4f46-8ded-15b9f9a859da)

Details of the `User Story` and scenarios to cover  [HERE](https://www.notion.so/dApp-Session-proposal-and-establishment-cc8d934bb77f4a73ac50076060819398)

- [x] #14690
- [x] #14691
- [x] #14692

**Comment by alexjba** [comment]
@anastasiyaig This user story is ready for testing

**Comment by alexjba** [comment]
Closing this one. QA will be done on the parent user story: https://github.com/status-im/status-desktop/issues/14678
