### ISSUE TITLE
When you detect that you have missing keys, you should ask the control node

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14683]
### Description

Follow-up to: https://github.com/status-im/status-go/issues/5057

While this first issue/PR fixes the case where you re-import a community, there can also be problems where you haven't opened your app in a while and missed the latest encryption keys.

This issue aims to solve it by also asking the Control node for the latest encryption keys for all/certain channels.

The technicalities of how to do it are not yet decided. Feel free to propose ideas in the comments.

One option is to just detect how how your last keys are and if they are older than the normal interval at which keys are re-distributed (2 days currently I think), then ask the control node.

Another option is more sophisticated, but more precise. If you see that you can no longer decrypt a channel and didn't receive a permission update on it, it means that you no longer have the keys for that channel, so you can ask for them.

### Acceptance Criteria

- When a member node is missing keys for a community/channel(s), it can ask the control node for them and get them back, getting access ti newer messages and channel members
- status-go tests are added to validate the behaviour

**Comment by osmaczko** [comment]
## Old Method: Early permissions check
```mermaid
flowchart LR
    A1(["Start"]) --> A2{"Satisfies permissions\n(on-chain check)?"}
    A2 -->|N| A3N{"Is private?"}
    A2 -->|Y| A3Y["Access channel"]
    A3N -->|N| A4N(["Show overlay\n(missing permissions)"])
    A3N -->|Y| A4Y(["Hide"])
    A3Y --> A5{"Has encryption key?"}
    A5 --> |N| A7(["No member list\nNo new messages"])
    A5 --> |Y| A6(["All fine"])

    style A7 fill:#f44,stroke:#333,stroke-width:2px
```

Previously, we estimated access to channels by performing on-chain checks. Therefore, even though we didn't have the encryption key and the channel was private, it remained visible, and we were able to interact with it, such as scrolling and even sending/receiving messages with an outdated encryption key. The drawback was the inability to read messages encrypted with the newest key and the already well-known issue of an empty members list.

## Current Method: Member list presence

```mermaid
flowchart LR
    B1(["Start"]) --> B2{"Is on member list/\nhas encryption key?"}
    B2 -->|N| B3N{"Is private?"}
    B3N -->|N| B4N{"Satisfies permissions\n(on chain check)?"}
    B4N -->|N| B5N(["Show overlay\n(missing permissions)"])
    B4N -->|Y| B5Y(["Show overlay\n(all permissions satisfied?)"])
    B3N -->|Y| B4Y(["Hide"])
    B2 -->|Y| B3Y["Access channel"]
    B3Y --> B4(["All fine"])

    style B4Y fill:#f44,stroke:#333,stroke-width:2px
    style B5Y fill:#f44,stroke:#333,stroke-width:2px
```

It has recently changed, so that we now estimate access to channels based on the presence in the channel's member list. This leads to another issue where private channels disappear until the newest encryption key is received. For non-private channels, the overlay is displayed, and an on-chain check is performed anyway. This is superior to the previous method because it doesn't require on-chain checks for channels of which we are a part.

## New Method Proposal: Member List Presence + Permissions check

```mermaid
flowchart LR
    C1(["Start"]) --> C2{"Is on member list/\nhas encryption key?"}
    C2 -->|N| C3N{"Satisfies permissions\n(on chain/cache check)?"}
    C3N -->|N| C4N{"Is private?"}
    C4N -->|N| C5N(["Show overlay\n(missing permissions)"])
    C4N -->|Y| C5Y(["Hide"])
    C3N -->|Y| C4Y(["Show overlay\n(waiting for encryption key)"])
    C4Y -.-> C5[["request keys from control node if not received in [t] minutes"]]
    C2 -->|Y| C3Y["Access channel"]
    C3Y --> C4(["All fine"])
```

The proposed new method is based on both member list presence and permissions checks. The obvious drawback is the potential for redundant permission checks in scenarios where the encryption key wasn't received on time, or the necessary criteria weren't met, and the channel remains hidden. To mitigate this, we could use a permissions check cache to limit the number of requests to the provider. Moreover, when the encryption key is missing, a new overlay is proposed to prevent confusion over the missing member list or the absence of new messages.

**Comment by jrainville** [comment]
Great proposition @osmaczko . Your chart makes it very easy to follow too! Thanks.

> To mitigate this, we could use a permissions check cache to limit the number of requests to the provider

I actually opened [an issue to address this](https://github.com/status-im/status-desktop/issues/14913). We should never be checking the chain for members IMO, since using the current wallet state/cache/DB is good enough.

> Moreover, when the encryption key is missing, a new overlay is proposed to prevent confusion over the missing member list or the absence of new messages.

Totally agree! I'll open an issue to add this screen/overlay.

--- 

So for this issue right here, the goal remains the same, if we detect that we are missing the encryption keys for a channel to which we do have access, we should ask the control node using @mprakhov 's mechanism implemented here https://github.com/status-im/status-go/pull/5142

It is probably safer to wait to implement it after https://github.com/status-im/status-desktop/issues/14913 just to avoid conflicts however.

**Comment by jrainville** [comment]
Overlay issue added here: https://github.com/status-im/status-desktop/issues/14931

**Comment by osmaczko** [comment]
Thanks @jrainville.

I just talked with @cammellos and he raised a good point, we should try to avoid permissions check on clients as much as possible. Ideally, we should only check permissions when we click on the channel and want to see what permissions we are missing. To achieve this, we need to determine whether we belong to the channel or not, without compromising the privacy gained by encrypting the members list. This is the challenging part. One idea is to have an additional members list containing `trim(hash(dh_common_secret, channel_name, community_clock), 4bytes)`, which allows each user to privately verify their membership. Additionally, we likely don't want to send the entire list; instead, we can use a Bloom filter or another more compact method.

The flow would look as follows:
```mermaid
flowchart LR
    C1(["Start"]) --> C2{"Is on member list/\nhas encryption key?"}
    C2 -->|N| C3N{"Is member on the magic list?"}
    C3N -->|N| C4N{"Is private?"}
    C4N -->|N| C5N(["Show overlay\n(calculate missing permissions on the fly)"])
    C4N -->|Y| C5Y(["Hide"])
    C3N -->|Y| C4Y(["Show overlay\n(waiting for encryption key)"])
    C4Y -.-> C5[["request keys from control node if not received in [t] secs"]]
    C2 -->|Y| C3Y["Access channel"]
    C3Y --> C4(["All fine"])
```

**Comment by jrainville** [comment]
> we should try to avoid permissions check on clients as much as possible

Agreed

> Ideally, we should only check permissions when we click on the channel and want to see what permissions we are missing.

I'm pretty sure that's what we do right now.

> One idea is to have an additional members list containing trim(hash(dh_common_secret, channel_name, community_clock), 4bytes), which allows each user to privately verify their membership

Is it not ok to verify your using permissions and your own cached wallet? I wonder why we need this method that is way more complex.
Ofc, the wallet might not be up to date, but I think we can live with that. The user will have the option to go reload the wallet balances in the wallet UI at worst.

**Comment by cammellos** [comment]
> Is it not ok to verify your using permissions and your own cached wallet? I wonder why we need this method that is way more complex.
Ofc, the wallet might not be up to date, but I think we can live with that. The user will have the option to go reload the wallet balances in the wallet UI at worst.

We could, I am not sure I would argue though is simpler, as it requires checks on both sides, and checking balances is more complex and it requires more coordination for example between paired devices (say that one device has changed which addresses are shared with a community etc). There's more that could go wrong in my opinion, while keeping a single source of truth is less complex in my opinion, but I am sure it could be argued both ways.

From mobile perspective, we don't check client side and currently there's no feature that requires it, so I would naturally be inclined with a solution that doesn't introduce the pattern, and showing the user which tokens are required and whether the user has access to a specific channel before they have access, in my opinion is not worth the complexity and we should not even build the feature at this stage.

**Comment by jrainville** [comment]
> One idea is to have an additional members list containing trim(hash(dh_common_secret, channel_name, community_clock), 4bytes), which allows each user to privately verify their membership

Ok, I re-read the solution and I totally misread. I thought you said that we'd have another member validate our membership.

I now understand what is suggested and it's actually pretty clever.

> showing the user which tokens are required and whether the user has access to a specific channel before they have access, in my opinion is not worth the complexity and we should not even build the feature at this stage.

We already have all this in desktop :sweat_smile: 

For sure, we are aligned in that members should never touch the chain. We currently already have the whole flow done with regards to checking the chain and changing that to using the wallet is still a good improvement. For example, when you want to join a community, you can select your addresses to share and for that we currently check the chain. We're changing that to check the wallet.

So while I agree that your solution is probably better in terms of one source of truth, since we already have the requirements and the implementations for the members doing checks, I think we can continue with our current approach.

Later on, we can then add this other method.

**Comment by cammellos** [comment]
> So while I agree that your solution is probably better in terms of one source of truth, since we already have the requirements and the implementations for the members doing checks, I think we can continue with our current approach.

I think that's when we want to talk to product etc to remove features, as we actively have to spend time and effort to maintain it, and it's not clear whether users have a real benefit, so far in my opinion is just a net loss, so it's ripe for being axed :)
