### ISSUE TITLE
Optimize Status app icons, use a white icon for the tray and use a standardized Mac icon

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14681]
### Description

Three issues in one, feel free to split.

Find all the icons here: https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?type=design&node-id=7514-242&mode=design&t=yyQz7dIHROEytXf3-0

1. Optimize the app icons
    - I used the icons as they were given to me by Ben or directly from Figma, but they were often way bigger than needed. I think that it why they are pixelized on Ubuntu
    - The goal is to used shrinked up versions so that they are the right size from the get got, it will be lighter + might solved the pixelized icon
2. Use white icon for trays
    - It's cleaner to use the white icon for the trays. It's kindof a standard to use white icons there, so it will look better.
    ![image](https://github.com/status-im/status-desktop/assets/11926403/885798d2-4d44-4637-9864-cef10052400a)
3. Use Mac icon with Drop shadow ~~Use standardized icon Mac icon~~
    - Change of plans, the current icon shape is ok, but just changing to have a drop shadow is good enough
    - ~~Mac has a standard for icons that are more rectangular~~
    - ~~This one will need designer input~~
    - ~~We used to have a rectangular icon, but not for the multicoloured one~~

**Comment by jrainville** [comment]
I assigned both backend and ui teams even though I shouldn't. There is not really a team in particular that should do this one, so whoever has time next week should take it as it would be good to fix for 2.29 (especially points 2 and 3)

**Comment by jrainville** [comment]
cc @benjthayer to get the rectangular icon for Mac (point 3)

**Comment by benjthayer** [comment]
> cc @benjthayer to get the rectangular icon for Mac (point 3)

Hey @jrainville we actually discussed point 3 today and decided to keep the logo in it's original form as opposed to conforming to the macOS rectangular standard. There are lots of apps that don't conform to this and given our nature it feels appropriate to use our own distinct shape.

I was discussing with Mishka that it would be good to add the standard dropshadow to the icon though so I'll update the app icons in the design system Figma and comment here when they are ready.

The app icons in the design system file are the standard sizes for MacOS so if any are missing feel free to let me know - happy to export at any set sizes required.

**Comment by jrainville** [comment]
Great thanks.

> The app icons in the design system file are the standard sizes for MacOS so if any are missing feel free to let me know - happy to export at any set sizes required.

Ah right, my point about optimizing was mostly for the other OSes. Especially Linux/Ubuntu, which is a bit pixelated for me.

I'm pretty sure Mac is using the rights sizes from the get-go since it has it's own format and icons.

**Comment by benjthayer** [comment]
> Great thanks.
> 
> > The app icons in the design system file are the standard sizes for MacOS so if any are missing feel free to let me know - happy to export at any set sizes required.
> 
> Ah right, my point about optimizing was mostly for the other OSes. Especially Linux/Ubuntu, which is a bit pixelated for me.
> 
> I'm pretty sure Mac is using the rights sizes from the get-go since it has it's own format and icons.

I'm no Linux/Ubuntu pro but from what I can see 128px, 64px and 32px are the standard icon sizes in use. The documentation on icon creation Linux is not great but I did find some info and created these if there is an easy way to test them? 
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?type=design&node-id=7558-1740&mode=design&t=dRCersK7jQH3am11-4

**Comment by prichodko** [comment]
> ... we actually discussed point 3 today and decided to keep the logo in it's original form as opposed to conforming to the macOS rectangular standard.

@benjthayer can you elaborate on this, please? In my opinion, the current situation doesn't look like "we are trying to be different" (as in the case of Notion) and more like an overlook and not being aware of any standards.

<img width="596" alt="image" src="https://github.com/status-im/status-desktop/assets/14926950/11c8ea1b-c0bb-4b59-b2a9-60bf19bcd2b1">

How is this good for a brand? To me, it looks totally out of place.

 Imagine someone not conforming to icon standards on iOS or tvOS. How frustrating would it be to look at that app on an iPhone or Apple TV? (it wouldn't because apple wouldn't accept it during review, but in theory)

---

> There are lots of apps that don't conform to this and given our nature it feels appropriate to use our own distinct shape.

What are "lots of apps" you refer to, except Notion and Spotify, that are recognizable and ship high-quality products?

I wouldn't take any pride in being in the same group as those apps. 😅

<img width="695" alt="image" src="https://github.com/status-im/status-desktop/assets/14926950/f83856bb-5123-41b5-8079-3f28fc1c6bb2">

**Comment by alexjba** [comment]
@benjthayer Can we have a white tray icon with a dark border?
On Mac and linux the tray icon can change from white to dark depending on the contrast and the monochrome icons are nice, but this is not an option on Windows at the moment.

Other apps are either using white icon with dark border, or a coloured icon.
![image](https://github.com/status-im/status-desktop/assets/47811206/2a96bc99-ecb5-46ed-b87e-8cbec154b796)
