### ISSUE TITLE
[UI - dApps Connection] Analyse if `AccountSelector` component can be used in `Connection request` view

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14691]
[Design](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=481%3A161066&mode=design&t=iMRTBgKquR8Eq9bf-1)

![Screenshot 2024-05-10 at 10 03 04](https://github.com/status-im/status-desktop/assets/97019400/01a88835-4f04-4dbe-b106-e9b62c63aeff)

- Analyse if `AccountsSelector` build in `Communities/controls` can be reused with the needed updates. 
- Review if there are other account selector components in `Wallet` folder that can be similar and unify in a single one as much as possible
- Decomponse `AccountsSelector` in the smallest components possible and make it backend agnostic. It can be used the analysis in [here](https://www.notion.so/Wallet-vulnerable-components-during-the-offsite-65ed3f05ed2d4446ae9d0d025f2eccf7?pvs=4#9d932dc7a2a8474bb197cd83235dbf21) as a reference
- Add it in `storybook` if not yet there
- Create `qml tests` for the isolated component
- Use the new or updated component inside `dApp Connect request` view dialog

**Comment by alexjba** [comment]
Agreed with @benjthayer to use the dApps selector in minting view as well to unify the account selector designs. Only the Swap modal will have extra info, showing the holdings as well.

**Comment by alexjba** [comment]
Opening until regression testing is finished

**Comment by virginiabalducci** [comment]
Closing as testing for this has been completed and passed
