### ISSUE TITLE
[UI - dApps Connection] Analyse if `NetworkFilter` component can be used in `Connection request` view

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14692]
[Design 1](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=3433%3A84355&mode=design&t=iMRTBgKquR8Eq9bf-1)

[Design 2](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=481%3A159256&mode=design&t=iMRTBgKquR8Eq9bf-1)

Amends form design in this comment https://github.com/status-im/status-desktop/pull/15073#issuecomment-2154273945

![Screenshot 2024-05-10 at 10 16 03](https://github.com/status-im/status-desktop/assets/97019400/bda3145e-b1f8-4019-91a7-bc8294a28245)

- Analyse if `NetworkFilter` build in `Wallet/controls` can be reused with the needed updates (not user selectable but all items highlighted)
- Review if there are other network filter comboboxes components in `Wallet` folder or in the rest of the app that can be similar and unify in a single one as much as possible
- Decomponse `NetworkFilter` in the smallest components possible and make it backend agnostic. It can be used the analysis in [here](https://www.notion.so/Wallet-vulnerable-components-during-the-offsite-65ed3f05ed2d4446ae9d0d025f2eccf7?pvs=4#9d932dc7a2a8474bb197cd83235dbf21) as a reference
- Add it in `storybook` if not yet there, or update page according to changes
- Create `qml tests` for the isolated components created
- Use the new or updated component inside `dApp Connect request` view dialog

**Comment by alexjba** [comment]
Closed in favour of https://github.com/status-im/status-desktop/issues/14780
