### ISSUE TITLE
[UI - Wallet Stability]  Review / analyse usage of `ManageTokensController`  and reduce its complexity giving the most possible responsability to the backend in terms of data management

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14703]
### Why this improvement needed?
- There is a lot of unnecessary dependency on this component in different views with potential introduction of bugs
- The complexity of the componenent itself 
- The functionality needs to be rechecked because of some recent changes have been introduced and can not be fully operative
- It's needed to ensure the data management  happens in the backend since syncronization between devices is a requirement

### Goal
The result of this analisys would be a **data tranformation diagram** _from service to store_ and identify all the needed subtasks for _UI Team_ but also for the _Wallet Core team_.

### Pre analysis notes

- **groupedAccountsAssetsModel** —> Candidate to attach / join with the TokenPreferences “status go table”
- **allCollectiblesModel** —> Candidate to attach / join information about _TokenPreferences_ “status go table”
- When doing this improvement we need to take into account:
    - Main wallet view
    - Tokens settings view (arrange by groups and individual items)
- Probably we are missing the information of the **sorting type** in the backend so it will need a task for that

**Comment by micieslak** [comment]
List of tasks leading to simplifications and better separation of concerns:

Backend side - exposing token management data via models:
- https://github.com/status-im/status-desktop/issues/14937
- https://github.com/status-im/status-desktop/issues/14936

Removing dependency on `ManageTokensController` in wallet's main view:
- https://github.com/status-im/status-desktop/issues/14939
- https://github.com/status-im/status-desktop/issues/14941

Cleaning up stores:
- https://github.com/status-im/status-desktop/issues/14945

Separation of UI and data transformation logic in `ManageTokensView`:
- https://github.com/status-im/status-desktop/issues/14944

**Comment by noeliaSD** [comment]
Analysis done and conclusions written, so it can be closed!
