### ISSUE TITLE
Everyone is stuck in "Membership request pending" even though it's an open community

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14700]
# Bug Report

## Description

Iuri created a new basic community that is open. Everyone tried to join it, but we all got stuck in "Membership request pending" and Iuri doesn't even see us in the Pending member requests.

![image](https://github.com/status-im/status-desktop/assets/11926403/8a367d0e-a1f3-45f5-a177-f37e622154dc)

## Steps to reproduce

Hard to tell. Iuri did:
1. Create a new open community (nothing special)
2. Shared it with us
3. We tried to join
We got stuck

The only special things about his setup are:
1. It's the control node of the Status community, so it does have another big community in the same instance. Maybe the other community was locked and the lock is bugged and applies to all communities?
2. He was minting the owner token at the same time, so maybe the community is in a limbo state where the community private key is no longer used, but the owner's key cannot be used yet because it doesn't have the owner token yet?

#### Expected behavior

Users can just join the community automatically

#### Actual behavior

We're stuck in pending state

### Additional Information

- Status desktop version: 2.28.1

**Comment by jrainville** [comment]
If it helps, here are Magnus' logs filtered with the community ID
[magnus-logs-join.txt](https://github.com/status-im/status-desktop/files/15276122/magnus-logs-join.txt)

**Comment by caybro** [comment]
FWIW, tried joining from master, same problem, request to join pending

**Comment by jrainville** [comment]
It seems like some people were able to join, so maybe it's really the lock on the other community:
![image](https://github.com/status-im/status-desktop/assets/11926403/75cfcfbe-648b-41cf-8150-f75969697db8)

An other option would be if the providers were having issues, then the control node maybe couldn't check if it could approve the members. If that's the case, then the simplest way to fix would be to first check if there is no permission to join, we don,t need to check anything.

**Comment by osmaczko** [comment]
> An other option would be if the providers were having issues, then the control node maybe couldn't check if it could approve the members. If that's the case, then the simplest way to fix would be to first check if there is no permission to join, we don,t need to check anything.

AFAICS providers are not called if there are no permissions: https://github.com/status-im/status-go/blob/dcc93dee965a39d9b4ee9dca79f546c497baa77e/protocol/communities/manager.go#L2436

**Comment by MishkaRogachev** [comment]
short update:
- I have not been able to reproduce the problem, trying with Sleep-s for artificial delays in the second community.
- `HandleCommunityRequestToJoin` does not use community locks, and no logic was found that could cause the hang
- I suspect it can be a hang in the receiver thread or some db locking issue, but in this case its not clear how messaging works then

**Comment by MishkaRogachev** [comment]
Just a little bit of thinking out loud:

Control node receives the message from waku and redirects it in `(m *Messenger) dispatchToHandler` to the specific handler - `(m *Messenger) handleCommunityRequestToJoinProtobuf` and next to `(m *Messenger) HandleCommunityRequestToJoin`.  Looking for possible reasons why it might be hanging:
- [Manger call](https://github.com/status-im/status-go/blob/release/0.177.x/protocol/messenger_handler.go#L1529) does not include code that can actually hang, except for _persistence_ access, which is very unlikely 
- It may be general messaging issue with delivery, but it's also very unlikely
- In case request is accepted, [this call](https://github.com/status-im/status-go/blob/release/0.177.x/protocol/messenger_handler.go#L1577) can lead thread to hang [here](https://github.com/status-im/status-go/blob/release/0.177.x/protocol/communities/manager.go#L2525). However it's possible only in case this community is already locked with another thread.
- Last option i see: _receiver_ thread may be busy or be hanged by another operation, but in this case receiving messages should not be working. 

Next steps: reproduce the issue artificially with test

**Comment by MishkaRogachev** [comment]
Oh, it hangs in this scenario:

```
func (s *MessengerCommunitiesSuite) TestMembershipRequestAutoAcceptedDuringReevaluateMembers() {
	community, _ := s.createCommunity()
	community2, _ := s.createCommunity()

	s.Require().NotEqual(community.ID(), community2.ID())
	s.Require().True(community.AutoAccept())

	advertiseCommunityToUserOldWay(&s.Suite, community, s.owner, s.alice)

	s.owner.communitiesManager.LockOnCommunity(community2.ID())
	s.joinCommunity(community, s.owner, s.alice)
}
```

**Comment by MishkaRogachev** [comment]
@jrainville @osmaczko 

After covering the code with additional logs i have discovered that there 2 ways how community can be locked in this scenario:
- Saving a shard [here](https://github.com/status-im/status-go/blob/release/0.177.x/protocol/communities/manager.go#L3599). I think having lock here is unneeded
- In `HandleCommunityDescriptionMessage` [here](https://github.com/status-im/status-go/blob/release/0.177.x/protocol/communities/manager.go#L1792), which can be called from the receiver thread or in [validateCommunity](https://github.com/status-im/status-go/blob/release/0.177.x/protocol/communities/manager.go#L553)

Here is the PR: https://github.com/status-im/status-go/pull/5155, but i don't have confidence it will help in case it was caused by `HandleCommunityDescriptionMessage`

**Comment by jrainville** [comment]
Moving to 2.29, as the fix involves ignoring some signals/messages and it seems to break a lot of tests and could potentially have side effects on the app.

**Comment by jrainville** [comment]
This might be fixed now. We can close if it is

**Comment by jrainville** [comment]
@MishkaRogachev can you run the test you had and see if it still happens. Also maybe check with @iurimatias if you can reproduce

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev can you run the test you had and see if it still happens. Also maybe check with @iurimatias if you can reproduce

I reanimated my old [PR](https://github.com/status-im/status-go/pull/5155) and rebased it on latest develop. The issue that the receiving thread will hang while communityLock is blocked is still occurring (and is still may be fixed by ignoring the communityDescription on the control Node).

**Comment by jrainville** [comment]
Like discussed in the meeting, let's open a new ticket for a refactor to solve the root cause. 

In this case, the pending request issue is solved because we solved the locking issue, but the refactor will be needed to avoid the same problem happening again.

Once the other ticket is opened, we can close this one.

**Comment by MishkaRogachev** [comment]
> Like discussed in the meeting, let's open a new ticket for a refactor to solve the root cause.
> 
> In this case, the pending request issue is solved because we solved the locking issue, but the refactor will be needed to avoid the same problem happening again.
> 
> Once the other ticket is opened, we can close this one.

Ready: https://github.com/status-im/status-desktop/issues/15136

**Comment by jrainville** [comment]
Closing as the issue is mostly fixed. The real solution is to do the refactor in https://github.com/status-im/status-desktop/issues/15136
