### ISSUE TITLE
Hide channels that have `hideIfPermissionsNotMet` by default and show only on permission success

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14709]
# Bug Report

## Description

Currently, when you join a community that has hidden channels, the channels show up in the list until the `checkAllCommunityChannelsPermissions` returns.
This happens with the Status Community for example.

Instead, what should happen is if a channel has the `hideIfPermissionsNotMet` property set to `true`, they should be hidden by default, and when `checkAllCommunityChannelsPermissions` returns, we should reveal them if the conditions are satisfied (`shouldBeHiddenBecausePermissionsAreNotMet == false` ).

## Steps to reproduce

0. Have a community that has hidden channels (like the Status Community)
1. Spectate and Join it
See that you can see all the hidden channels at first and then they get hidden

#### Expected behavior

The channels stay hidden by default and appear when we satisfy

#### Actual behavior

The channels are shown by default and are hidden when we don't satisfy

### Additional Information

- Status desktop version: 2.28.1

**Comment by jrainville** [comment]
@noeliaSD this is another issue that would be good to fix in 2.29 if possible. 

I thought we would [handle it from the backend](https://github.com/status-im/status-desktop/issues/13878), but as John pointed out, we do not want to encrypt the channel metadata, so it has to be done from the UI

**Comment by caybro** [comment]
We don't have that information (`hideIfPermissionsNotMet`) prior to joining the community

**Comment by jrainville** [comment]
> We don't have that information (`hideIfPermissionsNotMet`) prior to joining the community, it should be first part of the permissions model.

It's part of the `chat_section`'s model, so in theory, once you're inside a spectated community, `hideIfPermissionsNotMet` should be available.

This is only for the actual chat list, not the shared addresses modal

**Comment by caybro** [comment]
@jrainville is this still the case; e.g. in current master I see this:

Prior to joining:
![Snímek obrazovky z 2024-06-25 11-52-59](https://github.com/status-im/status-desktop/assets/5377645/df3d1015-f672-48ef-b1b5-a1aecf04f46d)

After request has been submitted:
![Snímek obrazovky z 2024-06-25 11-53-47](https://github.com/status-im/status-desktop/assets/5377645/913ae693-f364-4b6b-ae3d-5a2ef280393f)

I can't see any of the channels that should be hidden

**Comment by jrainville** [comment]
I might have fixed it during one of my refactors.

I tested also and I can't reproduce. I'll close.
