### ISSUE TITLE
[UI - Wallet Stability] Identify and create short `User stories` for `SendModal` use cases

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14717]
### Description

- Identify all different **use cases** and write a short `User Story` for each. Here the [design](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=9707-111554&mode=design&t=JrnEk4CYSlGW9CLy-0) of all flows.
  - Ensure the design shared contains new requirements for router / fees (probably it needs some discussion with the design team). Sync with @saledjenic on that point. 

- This exercice will give the global picture of the scope of the `SendModal` and will allow a better design of the _UI component_.

Link to Notion page with user stories: https://www.notion.so/b68de7395a0245909ad3b8755c460015?v=9d95d86c162944b68c8d55c7499f1140

**Comment by noeliaSD** [comment]
I think it would be nice to have @Khushboo-dev-cpp collaboration here!

**Comment by micieslak** [comment]
Basic user stories have been created: https://www.notion.so/b68de7395a0245909ad3b8755c460015?v=9d95d86c162944b68c8d55c7499f1140

Moreover, this task triggered broader discussion regarding send modal design, resulting with some ui improvements (done in Figma directly) and proposals: https://www.notion.so/SendModal-flow-adjustments-proposal-3d8b819b18c146c18b0a7f9bf39cf313

What's most important, this task initialized discussion regarding `ERC-721` and `ERC-1155` standards in context of community tokens minting. This gives you a chance to clarify this important issue for 2.30.0 release.

Notes from the last meeting:
https://www.notion.so/Desktop-Send-modal-review-8a466d99d1014c25a85e40b34e6f6707

**Comment by noeliaSD** [comment]
User Stories for send entry points completed!
