### ISSUE TITLE
[UI - Wallet Stability] Create generic/reusable assets listview component

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14716]
Create a new generic and reusable listview component and delegates used for assets (to replace `TokenListView`):

  - Called “list” but it’s not a list but a composition of some components + 2 different lists. It could be decomposed into lists itself and another top level component composing lists together using tabs
  - In related *storybook page* there are done a lot of data transformations, some dependency of `TransactionStore` / `WalletAssetsStore`  only to transform assets model data. This should be transparent for the storybook page itself. The storybook page for given component shouldn’t bother about earlier transformation we do in the app. It’s sufficient to provide just what’s expected by the component, in a form as easy as ListModel with static ListElement items. Then in storybook we clearly see what the structure of the model expected by the component. Having it done this way, we don’t need to copy logic from real store to stub store. Stub stores should be just empty QtObjects.
  - `TransactionStore` / `WalletAssetsStore` contains a lot of UI-side logic related to data transformation. It should be excluded from stores and kept in a separate components (Adaptors - responsible for that data transformation). Stores should be only a thin layer exposing backend’s models/properties/methods.
  - The component takes function for formatting balances, (`formatCurrentCurrencyAmount`, `formatCurrencyAmountFromBigInt`). In storybook page it could be very simplified implementation, like e.g. `Math.round(balance) + " USD`. No need to involve stores. Ideally, models taken by the component should contain ready-to-display data, with no need to use external methods for formatting
  - Instead of taking formatting info from `CurrenciesStore` via a method, we could have this info exposed as a model. Then on UI side left join may be performed to combine assets and corresponding formatting info. Other solution (probably more efficient) is to expose formatting details directly via assets model.
  - `TokenListView` exposes `assetSearchString` , the assumption is that model’s data are filtered externally according to that string. It makes that component not fully self-contained. When instantiated in storybook search doesn’t work. This type of search could be implementation detail of that component - encapsulated and hidden.
  - `TokenListView` takes networks model in order to do left joins internally for submodel of assets and collectibles. Currently, with the `SubmodelProxyModel` it’s no longer needed. That join may be done externally on submodels. It’s no longer needed to have network model as a dependency.
  - All model transformations, like adding role `"isCommunityAsset"` should be done externally. UI component should just depend on a model with such role.

**Comment by caybro** [comment]
@micieslak this is being used in the Swap designs so I guess a high(er) priority to finish this asap? (Figma: https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3406-234619&t=0m4QLdvh0QcUA2SP-0)

**Comment by noeliaSD** [comment]
@micieslak as discussed offline, you will create subtasks for that epic so that @Seitseman can work in small improvements!
