### ISSUE TITLE
Show wallet footer on all accounts screen

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#14732]
Was decided to show the wallet footer on the "All Accounts" screen
https://www.figma.com/file/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?type=design&node-id=3404-113561&mode=design&t=qJdSp8iLaXMZErYU-0

https://www.figma.com/file/TS0eQX9dAZXqZtELiwKIoK?type=design&node-id=3404-113561&mode=design#799594725

Need to add this

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

**Comment by noeliaSD** [comment]
This task is included in the following user story: https://www.notion.so/From-Main-Wallet-View-Footer-option-074007c66d474a309a9ebb7ffdb24571 and should be covered by this task: https://github.com/status-im/status-desktop/issues/15217

**Comment by noeliaSD** [comment]
> This task is included in the following user story: https://www.notion.so/From-Main-Wallet-View-Footer-option-074007c66d474a309a9ebb7ffdb24571 and should be covered by this task: #15217

Only the `SendModal` button is covered inside this **User Story** so, that's the only part already agreed with @benjthayer

**Comment by caybro** [comment]
This is already the case in master:

![image](https://github.com/user-attachments/assets/da406aa0-05a7-4177-ab71-8bfa1973f5c7)
