### ISSUE TITLE
[EPIC] Reload button 

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14738]
New designs have been added to allow the user to manually reload their Wallet data.

Designs:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=23330-214446&mode=design&t=8fOgIpBI8pbbJzxn-4

---

Breakdown:

1) There are an additional 3 icon buttons in the top-right of the UI which represent 3 new items of functionality which will be developed separately. These are, from left to right: `Hide balance`, `Refresh/Reload` and `Connected dApps`. Each of these buttons should only be revealed to the user in the UI once the underlying functionality has been implemented. In other words, there is no requirement to release all 3 buttons together given they are functionally distinct, e.g. if `Connected dApps` (dApp interactions) is developed first, that button should be shown without the other two needing to be present. This issue is specifically concerned with the `Refresh` button and underlying functionality.

<img width="1600" alt="Reload1" src="https://github.com/status-im/status-desktop/assets/110033914/f1c0014f-94cb-43e0-88f0-06b664fc3216">

----

2) Upon hovering the `Refresh` button from a single account or `All accounts` the user is presented with a tooltip featuring a timestamp of when the Wallet was last refreshed:
<img width="1600" alt="Reload2" src="https://github.com/status-im/status-desktop/assets/110033914/29ccd3f2-152a-4ca8-8498-ce11d0f478a8">

----

3) Once the `Refresh` button is clicked, the icon inside the button is replaced with the spinner icon to provide the user feedback that the refreshing of data is underway. There is no requirement to show any loading states other than this in the UI while the refresh is occuring. The user should retain full access to the current iteration of data and should be free to navigate around the app as normal while the more up to date data is being fetched.

Whether the user is reloading via the `Refresh` button on the `All accounts` page or via the `Refresh` button on the single account page, all Wallet data for all accounts should be refreshed, API permitting. This includes all balances, market values, assets and collectibles lists and activity.

<img width="1600" alt="Reload3" src="https://github.com/status-im/status-desktop/assets/110033914/09df53f1-24a5-48af-be12-65364efc605f">

----

4) Once the new data is fetched, we simply switch in the new data (no additional loading or transitions required). At this point, when the user hovers over the `Refresh` button again, the tooltip should reflect the new last refreshed timestamp.

<img width="1600" alt="Reload5" src="https://github.com/status-im/status-desktop/assets/110033914/5defa994-c3d5-4fda-aa62-eb3475ecb28d">

----

5) If there is an error fetching new data, we should aim to be as specific about the issue as possible to give the user the most information possible (i.e. we should show the `Internet connection lost` or POKT/Infura down messaging banners if applicable). If for whatever reason this level of specificity is not possible, the designs include a more generic banner which can be used.

<img width="1600" alt="Reload6-Error" src="https://github.com/status-im/status-desktop/assets/110033914/bca35426-d9dd-4cfa-b382-f027b5dd18ee">

----

6) Upon reducing the app window width, to ensure the visibility of the right-hand buttons, the name should truncate as required in order to maintain a min. padding of 20px between the buttons and the account name/emoji.

<img width="1188" alt="Reload-smallerWidths2" src="https://github.com/status-im/status-desktop/assets/110033914/b052e108-9b83-4856-920e-43b5da73ba01">

**Comment by iurimatias** [comment]
needs review, could be closed
