### ISSUE TITLE
[Join Communities] Token gating info when "Become a Member" permission not met and permission set to private

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14747]
This issue covers what we should show in the top right hand token gating area of the community card (as seen in the Discover communities page) when all of the following conditions are true:

1) Community membership is token gated 
2) The user does not hold the requisite tokens to meet the membership permission
3) The permission is set to be hidden from those that do not meet it.

Figma:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=53883-149101&mode=design&t=ybp3ZjfXuqh15S5x-4

Designs:

<img width="1253" alt="Screenshot 2024-05-14 at 10 44 16" src="https://github.com/status-im/status-desktop/assets/110033914/6654fc62-dff1-4d05-bef9-604f329b4eae">

----

Related to:
#14671 

cc @caybro

**Comment by caybro** [comment]
CC @noeliaSD
