### ISSUE TITLE
[Chat - Emoji] The emoji color selector animation is out of bounds

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#14744]
# Bug Report

## Description

The emoji color selector animation is out of bounds. It moves outside of the popup

## Steps to reproduce

1. Go to any chat
2. Open the emoji popup
3. Click the hand emoji next to search

#### Expected behavior
Emoji selector is bound to the popup

#### Actual behavior
Emoji selector moves outside of the popup

### Additional Information

https://github.com/status-im/status-desktop/assets/47811206/79bd5066-5c65-45ed-92b6-1fcaf911e286

- Status desktop version: 2.28.1
- Operating System: MacOs

**Comment by alexjba** [comment]
cc: @noeliaSD

**Comment by caybro** [comment]
Already fixed by https://github.com/status-im/status-desktop/pull/14841
