### ISSUE TITLE
Permissions lock icon is visible although there is no channel permission.

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#14746]
# Bug Report

I noticed that sometimes when I edit permissions, eg. from toJoin into channel,
the permission is received by the member (there is notification and access is correct), but the lock icon on the channel is still visible.
Permission set in control node:

![image](https://github.com/status-im/status-desktop/assets/61889657/185b19f5-b037-4955-a433-0cbaead0f965)

Member sees the lock icon, though there is only permission to join:

![image](https://github.com/status-im/status-desktop/assets/61889657/d244d56a-0dbc-474e-a47c-c771505fdda9)

### Reproduction steps

1. Have a community with 1 owner and 1 member
2. Owner adds a channel with a permission on it that the user doesn't meet
3. Member sees the channel appear with the lock icon and doesn't have access to the content (if view and post permission)
4. Owner removes the permission on the channel
5. Member can now see the content, but the lock icon is still on the `#`

Expected: the lock icon disappears along with the permission. Same thing if the member would have satisfied the permission

**Comment by jrainville** [comment]
@endulab do you think that it's because the re-evaluation wasn't done yet or with a restart the lock went away? 
ie is it "normal" or is it a model refresh issue?

**Comment by endulab** [comment]
I think this is a model issue. Reevaluation was done - I joined channel which was not available peviously and I could use this channel.

**Comment by kounkou** [comment]
Hi @endulab 

If I understand correct, to have a chance to reproduce, I should 
1- create a community, 
2- create a permission to join, and 
3- have the control node update the permission 

Then observe that if the client has access to the channel for which the permission was updated, the lock icon is correctly updated as well.

**Comment by endulab** [comment]
Hi @kounkou ,
Yes exactly. You need to have 2 apps: 1. the control node and 2. a member.
And play a bit with adding/removing channel permissions.
Sometimes the lock icon is still visible though the channel is not token-gated anymore.
I am attaching Figma file which helps you understand when it should be displayed - tl;dr anytime the channel has permissions.
https://www.figma.com/design/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?node-id=2578-351745&t=Bsz0F4NxVeZTgYn7-4

**Comment by kounkou** [comment]
Managed to reproduce, I will have a look now.
