### ISSUE TITLE
[dApps] Signing messages `User Story`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14756]
### Description
[Design](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=3418%3A74527&t=onun7PNHBei8WnPS-1)

[User story and acceptance criteria](https://www.notion.so/I-want-to-sign-messages-from-dApps-0bcfd42bb17c4afe89c1582b654c9cdd?pvs=4)

- [x] #14927
- [x] #14762
- [x] https://github.com/status-im/status-desktop/issues/14499
- [x] #14763
- [x] Check if it is worth sharing the basic frame and layout with swap; for details see: https://github.com/status-im/status-desktop/issues/14785
- [x] #15361

**Comment by stefandunca** [comment]
@anastasiyaig this user story is also completed and ready for testing
