### ISSUE TITLE
[dApps] Showing connected dApps `User Story`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14755]
### Description
[Design](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=356%3A99461&t=onun7PNHBei8WnPS-1)

[User story and acceptance criteria](https://www.notion.so/I-want-to-see-my-connected-dApps-139abf76a4744bb196eb080de49f7959)

- [x] #14759
- [x] #14760
- [x] #14761
- [x] #15189

**Comment by alexjba** [comment]
@anastasiyaig Can we close this one?
