### ISSUE TITLE
[Wallet -> Send] list of users assets does not reflect correct networks

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14768]
The network icons featured in each of the asset list items in the Send flow do not accurately reflect the networks on which the user has balances of that asset.

Alisher reported the following example when interacting with Send where inside his `Status account` he only has a balance of ETH on Mainnet but the ETH asset list item features all 3 networks - instead of just showing the Mainnet icon.

A network icon should only be shown if the user has any balance of that asset on that network.

<img width="620" alt="Screenshot_2024-05-15_at_09 36 28" src="https://github.com/status-im/status-desktop/assets/110033914/c4aa0056-7901-48a4-8cd2-f3bbaaee758a">

cc @Khushboo-dev-cpp

**Comment by saledjenic** [comment]
@noeliaSD I am changing label to ui team, cause this is pure UI issue.

**Comment by caybro** [comment]
To complete the whole issue, we first need to have support for collectibles (TBD here: https://github.com/status-im/status-desktop/issues/15121)

**Comment by micieslak** [comment]
> To complete the whole issue, we first need to have support for collectibles (TBD here: #15121)

@caybro could you please elaborate a bit? Is it working already fine in the newly created dropdown selector (assets part) but SendModal still uses old assets list and old dropdown? Is that the reason for dependency on https://github.com/status-im/status-desktop/issues/15121?

**Comment by caybro** [comment]
> > To complete the whole issue, we first need to have support for collectibles (TBD here: #15121)
> 
> @caybro could you please elaborate a bit? Is it working already fine in the newly created dropdown selector (assets part) but SendModal still uses old assets list and old dropdown? Is that the reason for dependency on #15121?

Yeah, SendModal still uses the old `HoldingSelector` (dropdown) and `TokenListView` (listview) which could eventually be replaced by the new `TokenSelector` when it gets support for collectibles

**Comment by caybro** [comment]
Should be already fixed by https://github.com/status-im/status-desktop/pull/15409
