### ISSUE TITLE
[Status Dialog] Support for image with badge in header

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14763]
Example of [design](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=3775%3A26012&t=onun7PNHBei8WnPS-1) to understand the need

![Screenshot 2024-05-14 at 20 26 31](https://github.com/status-im/status-desktop/assets/97019400/ff4ed79a-1408-4bb0-9ea6-585264587120)

- Add support to header image with badge

**Comment by caybro** [comment]
Any kind of extra component left of the Title/Subtitle is already supported by `StatusDialog`. This can be achieved by using a `StatusSmartIdenticon` together with its `bridgeBadge` property

**Comment by caybro** [comment]
Example from StatusMessage.qml:
```qml
StatusSmartIdenticon {
    id: profileImage
    Layout.alignment: Qt.AlignTop
    active: root.showHeader
    visible: active
    name: root.messageDetails.sender.displayName
    asset: root.messageDetails.sender.profileImage.assetSettings
    ringSettings: root.messageDetails.sender.profileImage.ringSettings
    bridgeBadge.visible: root.messageDetails.contentType === StatusMessage.ContentType.BridgeMessage
    bridgeBadge.image.source: root.messageDetails.sender.badgeImage
}
```

**Comment by caybro** [comment]
CC @Khushboo-dev-cpp
