### ISSUE TITLE
[Wallet] Watched address assets being shown in other addresses

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14769]
The assets from watched addresses are currently being shown in other addresses.

For example, I have added this watched address which has (or has had in the past) balances of `MATIC`, `WAMPL`, and `WETH`. Those assets are showing in the watched address asset tab even if the current balance is zero - which is the correct behaviour. 

However, those assets are also appearing in my other accounts which have never had balances of those tokens - which is the incorrect behaviour. Each individual account should only show assets which that account currently hodls or has hodl'd in the past. 

The watched address tokens should only appear in the assets tab of the watched address (and the All accounts assets tab if the user has opted to include that watched address' balances and activity).

Watched address containing the assets `MATIC`, `WAMPL` and `WETH`:
<img width="1446" alt="Screenshot 2024-05-15 at 12 04 52" src="https://github.com/status-im/status-desktop/assets/110033914/f26f4b3d-2667-4307-950c-ef33e700a9a1">

Status created account incorrectly showing those same assets:
<img width="1446" alt="Screenshot 2024-05-15 at 12 05 26" src="https://github.com/status-im/status-desktop/assets/110033914/9af6ee22-0929-4ee8-b54e-f22fdfa2336b">

cc @Khushboo-dev-cpp

**Comment by saledjenic** [comment]
> Those assets are showing in the watched address asset tab even if the current balance is zero - which is the correct behaviour.

@benjthayer why do you think it's ok to display tokens with 0 balances in the assets tab?

**Comment by benjthayer** [comment]
> > Those assets are showing in the watched address asset tab even if the current balance is zero - which is the correct behaviour.
> 
> @benjthayer why do you think it's ok to display tokens with 0 balances in the assets tab?

It's quite common in Wallets to display the assets the user has previously held when their current balance is 0. We don't want to show all assets in the token list, just those that the user has held and previously sent/spent. The user can manually hide these if they want to. 

There's a few benefits to this:
- If I have 100 MATIC and send all of it to an address using Status, when I come back to my assets list seeing a 0 balance for that asset is less confusing than the app automatically hiding the asset for me without my explicit consent. Seeing a 0 balance additionally confirms the transaction was successful.
- If it is an asset I have 0 balance for but am interested in this asset or expect to buy or receive it in the near future, I want to retain visibility of it in my assets list and be able to set which place in the asset list it appears so that it is in the correct place when I do receive that asset.

**Comment by saledjenic** [comment]
It was fixed recently.
