### ISSUE TITLE
Avoid locking the community until the end of the re-evaluation

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14775]
One thing to avoid locks that we discussed with @jrainville is to split the checking & commiting of changes, something on the lines of (oversimplified):

```
1) Lock
2) Take list of members
3) Unlock
4) Check memberships
5) Lock
6) Apply changes (members that have joined/left in the meantime would have to be handled)
7) Unlock
```

_Originally posted by @cammellos in https://github.com/status-im/status-desktop/issues/14379#issuecomment-2103340133_

In other words, we want to avoid locking the community for the whole re-evaluation. If we could lock only when applying the changes, it would be way better.

**Comment by osmaczko** [comment]
> 6) Apply changes (members that have joined/left in the meantime would have to be handled)

Also we should take permission changes and channels added/removed into consideration.

**Comment by jrainville** [comment]
> Another improvement vector is to reevaluate more precisely based on the changes made to the permissions. For instance, if a permission is added to a channel, only that permission should be reevaluated rather than the whole set of permissions.
> 
> @jrainville ^

Created the ticket here: https://github.com/status-im/status-go/issues/5185
