### ISSUE TITLE
[Wallet] Issue with padding of account selection button

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14778]
The account selection button has more generous L/R padding than in the designs.
The label is also sitting not sitting centrally in the vertical space.

<img width="1095" alt="Screenshot 2024-05-15 at 17 12 33" src="https://github.com/status-im/status-desktop/assets/110033914/2a6e7001-8e5b-471a-8c2a-55ce3307dcd3">

The correct padding and alignment can be found here:
https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=21284-137641&t=UoL57YmKanZINLdr-4

**Comment by noeliaSD** [comment]
@alexjba could you verify if we already fixed that with the refactor?

**Comment by alexjba** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/15099

<img width="294" alt="Screenshot 2024-06-26 at 23 33 39" src="https://github.com/status-im/status-desktop/assets/47811206/a6d91373-a76b-4c9e-91c2-8f0712c085b3">
