### ISSUE TITLE
[UI - Swap] Create swap sign dialog

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14785]
[Design](https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3542%3A471990&t=GIWodEjgr6YVv37j-1)

![image](https://github.com/status-im/status-desktop/assets/5377645/9138d56d-cad4-468e-949f-7bb7a56f1457)

The following `Sign` dialog looks really similar to the `Sign request` for [dApps](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=3620%3A38693&t=A6sNqy8lW7avoZsY-1).

Evaluate if both dialogs can be based on the same component, otherwise, build the dialog specifically for **swap sign** feature. 

This is the epic that shall cover `sign dapps requests`: https://github.com/status-im/status-desktop/issues/14756. Take it into account and use the same / similar pattern for that task.

- If there are new requirements introduced to a shared component, ensure to add the new support to `storybook`.
- If there are new requirements introduced to a shared component, ensure to add the needed `qml tests` to cover the changes.

**Comment by caybro** [comment]
> Will this also cover Approve flow https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3542-503662&m=dev ? @noeliaSD @caybro

It could... I guess the goal here is to create this dialog in a very generic way so that it's also (re)usable for the dApp feature

**Comment by noeliaSD** [comment]
> Will this also cover Approve flow https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3542-503662&m=dev ? @noeliaSD @caybro

That's something to consider when building the generic component. You are right that probably the "component body" is different for each particular use case (body component specific for _[dapps signing](https://github.com/status-im/status-desktop/issues/14762)_, another for _signing swap_ and another for  _swap approval flow_). 

I'll leave it to both of you to decide if you are more comfortable creating a new task to track the specific **approvals use case** and work on it in a separate task!

**Comment by caybro** [comment]
> > Will this also cover Approve flow https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3542-503662&m=dev ? @noeliaSD @caybro
> 
> That's something to consider when building the generic component. You are right that probably the "component body" is different for each particular use case (body component specific for _[dapps signing](https://github.com/status-im/status-desktop/issues/14762)_, another for _signing swap_ and another for _swap approval flow_).
> 
> I'll leave it to both of you to decide if you are more comfortable creating a new task to track the specific **approvals use case** and work on it in a separate task!

I'll probably create a base dialog for these 2 (or 3) and we'll see how much overlap there is .)

**Comment by Khushboo-dev-cpp** [comment]
https://github.com/status-im/status-desktop/issues/15442 created for approve flow
