### ISSUE TITLE
Display a Red Dot on the tray icon of the app when there are unread messages

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14788]
### Description

Part of [#10466](https://github.com/status-im/status-desktop/issues/10466)

First step of the Epic. Just start with a red dot when there are any types of unread messages. No need to bother with mentions or having a count for now.

### Acceptance Criteria

- when the app has an unread message, the app icon in the tray has a red dot

![image](https://github.com/status-im/status-desktop/assets/11926403/4916e8bb-2e70-4183-bf18-194cf82a6593)

**Comment by caybro** [comment]
Since we handle the tray icon in the same way for all platforms/OSs, I think this can be one task (instead of three)

**Comment by jrainville** [comment]
> Since we handle the tray icon in the same way for all platforms/OSs, I think this can be one task (instead of three)

Yeah that's what I realized after creating the issues. It's just in QML right? `SystemTrayIcon`?

**Comment by caybro** [comment]
> > Since we handle the tray icon in the same way for all platforms/OSs, I think this can be one task (instead of three)
> 
> Yeah that's what I realized after creating the issues. It's just in QML right? `SystemTrayIcon`?

Yup correct, in main.qml the `SystemTrayIcon`; note we have a pending PR here from @alexjba https://github.com/status-im/status-desktop/pull/14773

**Comment by jrainville** [comment]
@benjthayer could you kinda give us an image of the white icon with a red dot. Thank you 😄

**Comment by jrainville** [comment]
@benjthayer just refreshing your notification :)

**Comment by jrainville** [comment]
Turns out Ben is on vacation. @xAlisher could you do that for us then 😄

**Comment by xAlisher** [comment]
This feature is a standard part of macOS UI, so you do not need any graphic resources from my side to implement it.  
What do you mean by "any types of unread messages" Only in 1-1 chats? Or also unread message in communities?

**Comment by jrainville** [comment]
> This feature is a standard part of macOS UI, so you do not need any graphic resources from my side to implement it.

@xAlisher  For Windows and Linux, we'll probably need a custom icon with the dot manually added, because I don't think we can use OS tools

> What do you mean by "any types of unread messages" Only in 1-1 chats? Or also unread messages in communities?

Like Discord, we should show the dot when there is any unread messages in any unmuted channel.
Later, we we'll improve on it so that we can have a number on the main icon, but this is a quite simple  improvement
![image](https://github.com/status-im/status-desktop/assets/11926403/cb437ba8-579a-4a09-9ec6-cc8c094ad230)
