### ISSUE TITLE
[UI - Swap] Create swap switch button

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14782]
[Design](https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3413%3A279372&t=sPwTDYJeaYtdunds-1)

Create **circle button** component with the needed _click_ event and a border area that can be overlaped with the background as it looks in the design.

**States:**
- Arrow up / down hovered (`Qt.PointingHandCursor`)
![Screenshot 2024-05-15 at 21 15 01](https://github.com/status-im/status-desktop/assets/97019400/aa7feffb-e55a-4403-96cc-9d5f56cb5830)

- Arrow up / down NOT hovered
![Screenshot 2024-05-15 at 21 16 55](https://github.com/status-im/status-desktop/assets/97019400/d3394448-2087-4686-a644-911f13434066)

**Comment by caybro** [comment]
Fun fun, this one will be tricky due to the components cutout below

**Comment by caybro** [comment]
Depends on https://github.com/status-im/status-desktop/issues/14781
