### ISSUE TITLE
[UI - Swap] Create new `TokenSelector` component

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14783]
NOTE: To be implemented after https://github.com/status-im/status-desktop/issues/14716 and a similar component for collectibles

Goal is to replace the current `HoldingSelector` in `SwapInputPanel` and eventually when the collectibles support is done, also in `SendModal`; and then remove the `HoldingSelector*` completely

The view should contain 2 sections:
- Your assets on XXX (selected network)
- Popular assets (all the remaining ones with 0 balance, from the global token list)

[Design](https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3406%3A231273&t=hujKMKV9wXest5Ug-1)

- Component open:
![image](https://github.com/status-im/status-desktop/assets/5377645/34ca92c9-5c8d-4626-913a-b3fd2dd2c79e)

- Component with a selected value:
![Screenshot 2024-05-15 at 21 26 06](https://github.com/status-im/status-desktop/assets/97019400/bf1fe512-d1d2-47e7-94ba-e85f5c3f4983)

- The component is a selector / combobox
- It contains a floating dialog that shows the list of assets for a particular account
- It inlcudes a [searcher](https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3504%3A426138&t=hujKMKV9wXest5Ug-1)
- Each asset item (delegate) contains the _image_ of the asset, _symbol_, _name_, _total amount in the selected account_ and _total amount_ in the account but for a specific _chain_. 

- Ensure to add new component requirements inside `storybook` page if needed
- Ensure to cover new component requirements with appropiate `qml tests` if needed

**NOTE**: In the current `SendModal` component we already have a really similar component called `TokensListView`. Review it and reuse it as much as possible here. Take into account that there's a planned refactor to this component in [here](https://github.com/status-im/status-desktop/issues/14716)

**Comment by caybro** [comment]
The component exists and serves the purpose; what's missing:
- SB integration
- QML tests

**Comment by micieslak** [comment]
> The component exists as a combobox (`HoldingSelector/Item`) and serves the purpose; what's missing:
> 
> * SB integration
> * QML tests
> 
> However, we also have an almost identical duplicate called `TokenListView` (has SB integration) with very similar API. The goal of this task should be to unify the 2 components and reuse one or the other. Both of these are actually used in SendModal
> 
> CC @Khushboo-dev-cpp (for the SwapModal task); @micieslak (actually had the idea of unifying this) and @noeliaSD (for some planning ;)

The core part of `HoldingSelector` is `ListView` with read-only data and it should be really simple. Just single `model` as an input, with submodel representing balances per network. No data transformations inside ui component. It should be externalized and managed outside. Ideally it should be done already in https://github.com/status-im/status-desktop/issues/14781 to have Swap Modal clean in terms of API and dependencies. Or if not in that task, just a placeholder left, as suggested in the ticket. When build on old HoldingSelector, the refactor will be needed from the very beginning, what's rather not desired imo.

**Comment by caybro** [comment]
I think this should be merged with https://github.com/status-im/status-desktop/issues/14716; or rather we should start with a plain token listview, and then embed it as a building block for the whole HoldingSelector (a plain ComboBox)

**Comment by Khushboo-dev-cpp** [comment]
Also need consider this use case https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3504-426117&m=dev

in case token is selected in one panel we should disable it in the other one. Need api for this and also the look and feel is different than currently available

**Comment by caybro** [comment]
> Also need consider this use case https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3504-426117&m=dev
> 
> in case token is selected in one panel we should disable it in the other one. Need api for this and also the look and feel is different than currently available

Yeah 'm keeping this in mind in my current work here: https://github.com/status-im/status-desktop/pull/15157
