### ISSUE TITLE
[UI - Swap] Update / improve `NetworkFilter` component to cover swap design specs

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14780]
[Design](https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3410%3A271110&t=a1RWhuDHutbckkjJ-1)

![Screenshot 2024-05-15 at 19 34 54](https://github.com/status-im/status-desktop/assets/97019400/1ee0ada3-08f9-4dfa-80b9-6f224c2adbb0)

- Probably this task can be worked together or just after https://github.com/status-im/status-desktop/issues/14692.
- Ensure to use the reusable `NetworkFilter` component.
- Add new requirements like:
  - Single selection without checkbox or without radiobutton
  - Selected option just with the network icon, no text
- Ensure to add new component requirements inside `storybook` page
- Ensure to cover new component requirements with appropiate `qml tests`

**Comment by noeliaSD** [comment]
Depends on https://github.com/status-im/status-desktop/issues/14692

**Comment by noeliaSD** [comment]
@caybro what will happen when @alexjba finishes with the `NetworkFilter` refactor?? We will need to ensure that it's applied correctly on `swap` too, right? We agreed on keeping this task open until we have the refactor done, isn't it?

**Comment by caybro** [comment]
> @caybro what will happen when @alexjba finishes with the `NetworkFilter` refactor?? We will need to ensure that it's applied correctly on `swap` too, right? We agreed on keeping this task open until we have the refactor done, isn't it?

Well, assuming it's still the same component, nothing to do on our side; if it has a very different API or it's a new component, then our SwapModal's QML tests should ensure it gets integrated correctly right? Not sure what exact plans @alexjba has
