### ISSUE TITLE
[UI - Swap] Create tag error component

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14792]
[Design](https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3507%3A426544&t=XO6dcSms9Iilfx4i-1)

![Screenshot 2024-05-15 at 21 48 36](https://github.com/status-im/status-desktop/assets/97019400/bf42b450-b1dd-408f-80d8-24279d8fc7e7)

- Create following tag error component.
- Evaluate if the tag needs other configurations depending on the [following list](https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=1166%3A171137&t=XO6dcSms9Iilfx4i-1) of errors. If the design is not clear enough, ping the design team!
- If a new component is built, add it to `storybook` and create the needed `qml tests`.

**Comment by caybro** [comment]
Achievable with:
```qml
InformationTag {
    customBackground: Rectangle {
        color: Theme.palette.dangerColor3
        border.width: 1
        border.color: Theme.palette.dangerColor2
        radius: 36
    }
    asset {
        name: "info"
        color: Theme.palette.dangerColor1
    }
    tagPrimaryLabel.text: "Insufficient funds in helloworld to pay gas fees"
    tagPrimaryLabel.color: Theme.palette.dangerColor1
    tagPrimaryLabel.font.weight: Font.Medium
    rightComponent: StatusButton {
        size: StatusBaseButton.Size.Tiny
        type: StatusBaseButton.Type.Danger
        normalColor: Theme.palette.dangerColor1
        hoverColor: Theme.palette.hoverColor(normalColor)
        textColor: Theme.palette.white
        radius: 36
        text: "Buy ETH"
    }
}
```

Gives:
![image](https://github.com/status-im/status-desktop/assets/5377645/2bf0e7c7-4967-4af6-9bd6-67fc9c05a3a1)

**Comment by caybro** [comment]
CC @Khushboo-dev-cpp
