### ISSUE TITLE
[Community] Receiving mention notifications (@everyone) from spectated communities

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#14798]
### Description

When spectating a community the `@everyone` mention will trigger a mention notification

<img width="1956" alt="Screenshot 2024-05-15 at 23 36 18" src="https://github.com/status-im/status-desktop/assets/47811206/f5748592-c8f4-4ae0-b1fc-086408d88a1a">

Steps to reproduce:
1. Import an open community with request to join active
2. Add a `@everyone` mention in the community from a member account

Expected behaviour:
The `@everyone` mention doesn't trigger a mention notification if the user is not a member

Actual behaviour:
The `@everyone` mention triggers a mention notification

**Comment by jrainville** [comment]
> Expected behaviour:
The @everyone mention doesn't trigger a mention notification if the user is not a member

I just want to validate the expectations before having someone work on this. It's a pretty simple fix, but I want to be sure it's what we want. I don't mid either way. cc @benjthayer

**Comment by benjthayer** [comment]
> > Expected behaviour:
> > The @everyone mention doesn't trigger a mention notification if the user is not a member
> 
> I just want to validate the expectations before having someone work on this. It's a pretty simple fix, but I want to be sure it's what we want. I don't mid either way. cc @benjthayer

Yes, that's correct, if you're not a member you should not receive notifications
