### ISSUE TITLE
Wallet's RootStore: hide private properties in `d` object

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#14803]
## Description

Wallet's `RootStore` has many properties which are not accessed from outside but defined as helpers or because of performance concerns, e.g.:

![Screenshot from 2024-05-16 00-04-35](https://github.com/status-im/status-desktop/assets/20650004/851712a8-6070-4724-8112-9c19a59392b6)

All such properties should be gathered in `d` `QtObject` in order to make the API short and clean.

**Comment by caybro** [comment]
Potential caveat, we have a lot of things like this:
```qml
        readonly property Connections walletSectionConnections: Connections {
            target: root.walletSectionInst
            function onWalletAccountRemoved(address) {
                address = address.toLowerCase();
                for (var addressKey in d.activityFiltersStoreDictionary){
                    if (address === addressKey.toLowerCase()){
                        delete d.activityFiltersStoreDictionary[addressKey]
                        return
                    }
                }
            }
        }
```
