### ISSUE TITLE
[Community permissions] The community name is not updated in the permissions view

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#14800]
# Bug Report

## Description

The community name changes are not propagated in the community permissions view. We can still see the old community name in the permission definitions. See the video below for more info:

Old name: Token gated1
New name: Token gated

https://github.com/status-im/status-desktop/assets/47811206/d6d67777-1fb9-4e26-8c78-66930f9892de

## Steps to reproduce

1. set-up a community with permissions
2. change the community name

#### Expected behavior
The community name is updated in all permission definitions
#### Actual behavior
The community name is not updated in permissions view
### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/753825a40

**Comment by alexjba** [comment]
cc @noeliaSD

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/status-desktop/pull/14917
