### ISSUE TITLE
Switch input/output params

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#14827]
https://www.notion.so/Switch-input-output-assets-9dffbae3ce634d148ff93c215b157163
https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3410-278856&t=eTvhBjNa4YYvdRU7-0

Switch input/output parameters
Focus sticks with asset

**Comment by Khushboo-dev-cpp** [comment]
on switching test networks the form should be reset!! needs to be changed to that behaviour https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3410-271335&m=dev
