### ISSUE TITLE
Select Input params

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#14825]
https://www.notion.so/Select-input-parameters-56c5f81573d145f6b079678cdaaa362c
https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3406-233525&t=eTvhBjNa4YYvdRU7-0

- Select input asset
Fill selector with tokens with balance >0

- Enter input amount
Input validation, Max button

**Comment by Khushboo-dev-cpp** [comment]
closed under https://github.com/status-im/status-desktop/pull/15161
