### ISSUE TITLE
CodeBlock chatbox markdown and format do not match Figma

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14821]
# Bug Report

## Steps to reproduce
1. Open a chat and paste a piece of code, for example:
```
<!DOCTYPE html><html><body>
<h2>What Can JavaScript Do?</h2>
<p id="demo">JavaScript can change HTML content.</p>
<button type="button" onclick='document.getElementById("demo").innerHTML = "Hello JavaScript!"'>Click Me!</button>
</body></html>
```
2. Select the code and select "Code" formatting option.
Also try by writing three backticks before pasting the code.

#### Expected behavior
Chatbox: all block of code should be selected
When message is sent block of code should show in the format indicated by [this](https://www.figma.com/design/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?t=kq7w7aBzIx3iswo6-0) Figma design
See: Code block (non-coloured syntax)

**Chatbox**:
![Screenshot 2024-05-16 at 3 51 53 PM](https://github.com/status-im/status-desktop/assets/68916150/77b32ca6-4b71-48ed-96e9-59256e63d0ba)

**Message sent**:
![Screenshot 2024-05-16 at 3 52 03 PM](https://github.com/status-im/status-desktop/assets/68916150/c91d4334-ed4a-40dd-80df-84d832256829)

#### Actual behavior
When Code option is selected, only the first line of the block of code is formatted in the chatbox. 
<img width="1014" alt="Screenshot 2024-05-13 at 3 37 53 PM" src="https://github.com/status-im/status-desktop/assets/68916150/7cde4b0f-999f-4539-9189-db03015069aa">
To get the complete code block formatted, you have to remove spaces or you have to enter each line by pressing SHIFT + Enter. Even after doing so, message is sent as if each line was a separate line of code, instead of what can be seen in Figma.
<img width="1008" alt="Screenshot 2024-05-13 at 3 38 41 PM" src="https://github.com/status-im/status-desktop/assets/68916150/e7ab6b17-21c2-4133-a168-a7e0c6ef8544">

Code Block requires a closing pair of three backticks even though the above mentioned Figma has this comment: There is no need for a closing pair of ``` 

However, in the app 2.28.1 you do need closing pair of three backticks if not the code will not be sent in the Code format 

![Screenshot 2024-05-16 at 3 45 06 PM](https://github.com/status-im/status-desktop/assets/68916150/2ea72b5d-5c03-488b-b2b2-b376cf967a7e)

https://github.com/status-im/status-desktop/assets/68916150/9a8f6bc3-a705-410e-9020-5675600b0034
https://github.com/status-im/status-desktop/assets/68916150/f0dca7e0-0a93-42dc-b903-5b8a5c8e9c54

### Additional Information

- Status desktop version: 2.28.1
- Operating System: Mac OS Sonoma 14.4.1

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
