### ISSUE TITLE
Create New Community - Mandatory fields notification alerts missing

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14823]
# Bug Report

## Description
When creating a new community, there is no hint presented to the user to know which fields are mandatory and this makes the user experience confusing.

## Steps to reproduce
1. Go to Communities
2. Select Create Community
3. Fill in the name and a description.

#### Expected behavior
[Figma](https://www.figma.com/design/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5197-48166&t=g5dT0TetU5Hp8ADj-0) states that Name + Description is required
![Screenshot 2024-05-16 at 4 04 57 PM](https://github.com/status-im/status-desktop/assets/68916150/03a8bbdd-f1f4-410f-a9fc-0ed2dac4a6dd)

Would be nice to have hints to help the user fill in the required fields to proceed to the next page.

#### Actual behavior
The “Next” button is disabled. There are no hints to the user to know which fields are mandatory.

https://github.com/status-im/status-desktop/assets/68916150/1440e1a1-0ed2-42a6-9d94-48a5a03f06f4

### Additional Information

- Status desktop version: 2.28.1
- Operating System: Mac OS Sonoma 14.4.1

**Comment by jrainville** [comment]
Totally agree, that's why I opened [the same issue](https://github.com/status-im/status-desktop/issues/12486) a while back :smile: 

Sadly, I guess it won't be fixed til 2.31.

Anyway, I'll close this one as duplicate. Feel free to update the other issue with missing details.
