### ISSUE TITLE
Normal links do not open in the browser when clicked in a message

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14844]
# Bug Report

## Description

When a text contains a normal link (not a status link), clicking the link doesn't do anything and we get an error:

```
ERR 2024-05-17 15:25:43.599-04:00 failed to parse shared url:                topics="shared-urls-app-service" tid=551963 file=service.nim:32 url=https://curate.status.app/votes errDesription="\nstatus-go error [methodName:wakuext_parseSharedURL, code:-32000, message:not a status shared url ]\n"
```

## Steps to reproduce

1. Post a message with a link in a channel (eg: 
```
hmm clicking this link doesn't do anything, bug? https://curate.status.app/votes 

what about others like https://discuss.status.app 
```
2. Click on the links in the message

Nothing happens
Clicking on the unfurl works however

#### Expected behavior

Clicking on a link opens it in the browser

#### Actual behavior

Nothing happens

### Additional Information

- Status desktop version: 2.28.1 and master `4c61c115d43f39e3c10e5f9e3e79b9770ef62d67`
- Operating System: Ubuntu 22

**Comment by fryorcraken** [comment]
I noticed that one needs to click on the preview to open a link that has a preview. This is counterintuitive to me.
Seems that this issue is related.

**Comment by jrainville** [comment]
> I noticed that one needs to click on the preview to open a link that has a preview. This is counterintuitive to me. Seems that this issue is related.

Yeah that's exactly the issue. I have a fix in the linked PR
