### ISSUE TITLE
Wallet UI tests

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#14852]
Cover with QML UT tests:

- [ ] SendModal dialog
- [ ] ???

**Comment by iurimatias** [comment]
@noeliaSD @caybro  is this something for the UI team?

**Comment by noeliaSD** [comment]
I take it to have a frist analysis step and identify potential components to add qml tests. However, this task can be overlapping with the analysis in here: https://github.com/status-im/status-desktop/issues/14619

**Comment by noeliaSD** [comment]
Confirmed that this task goal is overlaping with https://github.com/status-im/status-desktop/issues/14619 so I'll close in favor of it!
