### ISSUE TITLE
[Windows] Align the tray icon with the new monochrome design used on other platforms

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#14855]
### Description

This task (#14681) introduced new tray icons for Linux and MacOs, but the new assets are not appropriate for Windows because the icon won't change color based on the contrast with the background.

Other apps are using a white icon with a stroke.

![331590053-2a96bc99-ecb5-46ed-b87e-8cbec154b796](https://github.com/status-im/status-desktop/assets/47811206/50a228c3-f2ee-43ca-8acc-727756d29ab5)

cc @benjthayer

**Comment by noeliaSD** [comment]
cc: @xAlisher

**Comment by xAlisher** [comment]
cc @pedro-et

**Comment by xAlisher** [comment]
@noeliaSD let me know if it works


![image](https://github.com/status-im/status-desktop/assets/7700914/cdd67b90-5367-43c1-ad8a-96657bc4cbb0)
<img width="16" alt="Win tray icon" src="https://github.com/status-im/status-desktop/assets/7700914/d0c43245-4ca5-4a46-a7d7-31adf4078751">

**Comment by noeliaSD** [comment]
@alexjba when you have time, can you do some quick test? Thank you! Low priority!

**Comment by alexjba** [comment]
@xAlisher We'd also need the asset with the red dot to indicate unread notifications.

**Comment by xAlisher** [comment]
@alexjba <img width="16" alt="Win tray icon red dot" src="https://github.com/status-im/status-desktop/assets/7700914/290acb4c-0e8e-43c6-b23b-d269bdade15e">

**Comment by jrainville** [comment]
@xAlisher can I get those as SVGs please.I tried PNGs and it doesn't work/show up (even on Linux). I guess it doesn't support PNGs at all
