### ISSUE TITLE
Balances are not retrieved and red banner appears (Cryptocompare and CoinGecko)

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#14862]
# Bug Report

Sometimes balances are not there and red banner appears (Cryptocompare and CoinGecko are down). I checked locally - it passes, but autotests on CI are still failing

I don't see balances:
- for added watched address 
![5749c8c7253a5e48](https://github.com/status-im/status-desktop/assets/141633821/26a6d837-da74-4ecc-a2fe-bd4e10a63e7c)

- for added watched address in Testnet mode
![d7c783fe9e960d55](https://github.com/status-im/status-desktop/assets/141633821/516b8993-e960-4732-a5d7-8a00c4bc7063)

- also button Send is disabled in test for sending 0 ETH
![d7c783fe9e960d55](https://github.com/status-im/status-desktop/assets/141633821/c82d03ec-5164-4e28-aa5b-9546810ec6ab)

### Additional Information
[app_logs_autotests.txt](https://github.com/status-im/status-desktop/files/15377379/app_logs_autotests.txt)

- Status desktop version: the latest master CI build
- Operating System:  macOS Ventura 13.5

**Comment by saledjenic** [comment]
I've noticed a few times that sometimes requests to cryptocompare may fail for some reason, maybe we can improve it with the logic to make up to 5 request times in a loop instead to make sure we got the response?

@glitchminer is this something that happens really often? I mean if we try what was said above can we know if that fixed the issue?

**Comment by Valentina1133** [comment]
That issue constantly appears in every nightly run of autotests on CI (last several nights), but locally - not so often

**Comment by saledjenic** [comment]
@Valentina1133 could you recheck this once this status-go PR https://github.com/status-im/status-go/pull/5207 is merged?

I'm moving this issue to code review, cause I'm pretty sure those changes will fix it.

**Comment by Valentina1133** [comment]
@saledjenic Ok. I will recheck it! Thank you

**Comment by Valentina1133** [comment]
@saledjenic Unfortunately it didn't help. There are still not retrieved balances, market data and red banners

**Comment by anastasiyaig** [comment]
Might be improved by https://github.com/status-im/status-desktop/pull/14969
