### ISSUE TITLE
expose wallet signing method on macOS

### ISSUE THREAD

**Issue by felicio** [status-im/status-desktop#14864]
## why

- deprecation of browser in desktop app

**Comment by saledjenic** [comment]
@felicio at first sight I thought that we could use QLocalServer for that, but then I realized that a web page cannot directly connect to a QLocalSocket and for that we will need Local Web Server that both sides will connect to to communicate.

Other options are, as you stated above, using Native Messaging and App Extension Support API and which requires an extension for each platform and browser, like one for Safari, other browser extensions for Chrome or Firefox. Also as I see this approach is slightly harder to do and maintain and also it brings some security risks cause communication in this case goes over std input/output and it might be hard to properly guard sensitive data.

So far I haven't ever used Native Messaging and App Extension Support API, but QLocalServer I was using in the past and at least one advantage I see that way is that we will have a single Qt code that will be compiled for all 3 platforms we're supporting and Local Web Server can be written in Go for example.

But for sure this is not something that we can do in a day or two. We should add this to our plan and assign somebody to familiarize ourselves with this and finally build it (to me it sounds interesting but I can't take it over before we finish the Router thing), but we can discuss this further and analyze how to do it.

**Comment by caybro** [comment]
What about WebSocket? https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API Sounds like this could be useful; also Qt supports it as well: https://doc.qt.io/qt-5/qtwebsockets-index.html

**Comment by saledjenic** [comment]
I think that they cannot be connected directly, must go over the local web server. But all that needs to be checked, we need to do some research on this.

**Comment by stefandunca** [comment]
> What about WebSocket? https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API Sounds like this could be useful; also Qt supports it as well: https://doc.qt.io/qt-5/qtwebsockets-index.html

For sure this should be the simplest way, not sure how easy is to allow browsers to connect to local opened sockets. Should be quick to prototype and expose the existing `web3provider` in status-go.

At first glance having our browser interface ([web3provider.ProcessRequest](https://github.com/status-im/status-go/blob/6f1b82966a12ca40e6f4e5b3991f17fa24690404/services/web3provider/api.go#L123) exposed through [Native Messaging API](https://developer.chrome.com/docs/extensions/develop/concepts/native-messaging) seems like a good start and also future proof.

**Comment by jrainville** [comment]
@felicio is this task for the Browser extension connector? If so, I already opened an Epic with a Spike to figure out how to do it here https://github.com/status-im/status-desktop/issues/14794

It's still good to have all the info from the rest of the team. Thanks everyone.

We're gonna start working on it in 2 weeks.

**Comment by jrainville** [comment]
> @jrainville yes, it is. And thanks for the link.

Cool. Then if you don't mind, I'll close those issues and link them in the Epic just so we keep the information shared here.

**Comment by jrainville** [comment]
> @jrainville I can continue to work with other apps that already expose such protocol (ws://, http://, ipc), but still, if there's anyone in desktop/wallet team that could expose at least one and show me how to run it locally until then, I could try to continue the effort on that end too.

@felicio my team wasn't planning on starting work on this until 2 weeks from now and we were gonna do a Spike to see what's the best solution.

I don't mind allocating someone to expose a quick and easy endpoint, but I don,t fully know what you'd need.

cc @iurimatias if you want @stefandunca to do it since he seems to have an idea.

**Comment by stefandunca** [comment]
Sorry @felicio but I have other high-prio on my list so better wait for the messenger team to get it moving.

> Also, like others have pointed out, I doubt this will be OS dependent, especially if we go with some sort of REST API.

For sure a socket based approach is platform independent but also generally accessible and offers less control. I'm thinking that using some IPC might make it complex but provide more control in boxed environment like MacOS and Windows provides.
