### ISSUE TITLE
Only show the Wallet Connect requests for the logged in user

### ISSUE THREAD

**Issue by clauxx** [status-im/status-desktop#14888]
### Description

An edge case, where if the user connected to a dapp on status profile A and logs out, then logs in to status profile B, they shouldn't see the request triggered by profile A's session. But, when logging back into profile A, the user should see the request.

**Current behavior:**

The user can see requests (broken) if logged into another profile.

**Expected behavior:**

The user can't see requests if logged into a different profile. Instead they should see a toast, telling them to "change to a different profile to see the request"

**Comment by noeliaSD** [comment]
No capacity for the `ui-team` this milestone. I remove the label, keeping the **dapps** one so @clauxx can decide. 

If you move it to the next milestone, you can add again the `ui-label` as agreed!

**Comment by clauxx** [comment]
@Seitseman thanks for taking this, but we have some higher priority issues/bugs that we can focus on at the moment. Please check the board for the [priorities](https://github.com/orgs/status-im/projects/65/views/39).
