### ISSUE TITLE
All channels are folded and missing bold indicator of unread when updating to 2.29

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14886]
# Bug Report

## Description

All channels are folded and missing bold indicator of unread when updating to 2.29

## Steps to reproduce

- Update to 2.29 rc 2
- Check Status community

#### Expected behavior

- categories with channels with unread messages are in bold
- categories are not folded (same state as before the upgrade)

#### Actual behavior

<img width="1470" alt="Screenshot 2024-05-23 at 10 31 37" src="https://github.com/status-im/status-desktop/assets/82375995/1b2149dd-9ed2-46d3-8cd0-e4757e8b2ec4">

### Additional Information

- Status desktop version: 2.29 rc 2, also master
- Operating System: macOS 14.4.1 (23E224)

**Comment by anastasiyaig** [comment]
@iurimatias could that be for 2.29? I marked it as such but feel free to deprioritise

**Comment by caybro** [comment]
Same in master fwiw

**Comment by anastasiyaig** [comment]
ya, i just wonder if we need that fix in 2.29 now, or fix in master and then it will be present in 2.30

**Comment by jrainville** [comment]
Ah I wanted to open this and forgot. Thanks ­for doing it @anastasiyaig 

I think we should fix in 2.29. Especially the missing bold indicator is very annoying.

**Comment by jrainville** [comment]
I'mm fairly sure it's a backend error with the models, so I'll assign my team
