### ISSUE TITLE
Clicking away from New Community creation window will close it without warning to the user

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14902]
# Bug Report

## Description
Clicking away from New Community creation window will close it without warning to the user

## Steps to reproduce
1. Go to Communities
2. Select "Create community"
3. On the Create new community screen, select "Create new"
4. Type a name and a short description.
5. click away from the status app (some other app or the desktop)

#### Expected behavior
Just as it happens with the creation of a new channel, window should not close itself without warning.
By clicking the X user is presented with the option to save or discard changes.

https://github.com/status-im/status-desktop/assets/68916150/ad8f7a86-2e1f-43d0-92dc-e996fec60efe

#### Actual behavior
When user clicks away from the New community creation, window is closed
When clicking on New community creation again, user has to start over. Previously entered information is not saved.

https://github.com/status-im/status-desktop/assets/68916150/4d443028-5063-4d08-90c2-da7f317c5b14

### Additional Information

- Status desktop version: 2.29.0-rc.2
- Operating System: Mac OS Sonoma 14.5

**Comment by anastasiyaig** [comment]
is that intentional @caybro , do you remember?

**Comment by caybro** [comment]
> is that intentional @caybro , do you remember?

Yup, as it was originally designed but @benjthayer might want to reconsider :)

**Comment by caybro** [comment]
> > > is that intentional @caybro , do you remember?
> > 
> > 
> > Yup, as it was originally designed but @benjthayer might want to reconsider :)
> 
> Yeah, I think this pattern is pretty awful. I think if there is an explicit close control then clicking outside of the dialog to close should not be possible. Otherwise the user stands to potentially accidentally lose lots of work!
> 
> If we limit the closing of the dialog to an explicit close, then we can more confidently clear the user's previously input content the next time they open the dialog.



> > > is that intentional @caybro , do you remember?
> > 
> > 
> > Yup, as it was originally designed but @benjthayer might want to reconsider :)
> 
> Yeah, I think this pattern is pretty awful. I think if there is an explicit close control then clicking outside of the dialog to close should not be possible. Otherwise the user stands to potentially accidentally lose lots of work!
> 
> If we limit the closing of the dialog to an explicit close, then we can more confidently clear the user's previously input content the next time they open the dialog.

Yeah, we could potentially work with (and change) this pattern application wide; CC @noeliaSD

**Comment by noeliaSD** [comment]
Created task to identify all other flows similar than the explained in this ticket: https://github.com/status-im/status-desktop/issues/15102

**Comment by noeliaSD** [comment]
We can fix only this specific flow described here for the current milestone

**Comment by caybro** [comment]
@jrainville @iurimatias as you can't currently create a new community (hidden behind experimental) I'd postpone this for 2.32

**Comment by jrainville** [comment]
> @jrainville @iurimatias as you can't currently create a new community (hidden behind experimental) I'd postpone this for 2.32

@caybro we don't know yet when we'll re-add the button, but I agree we don't have to work on it until then. We can reduce the priority for sure
