### ISSUE TITLE
Member list is empty in group chat

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#14907]
# Bug Report

## Description

User created chat with other users, but the member list is empty

## Steps to reproduce

1. Add several contacts 
2. Create group chat with users

#### Expected behavior
The member list includes all added to group chat users
#### Actual behavior
The member list is empty

### Additional Information
<img width="1512" alt="Screenshot 2024-05-24 at 14 27 22" src="https://github.com/status-im/status-desktop/assets/141633821/80ed6f3a-518e-4e2f-9329-ed61473db2f1">
- Status desktop version: the latest master build
- Operating System: macOS Ventura 13.5

**Comment by caybro** [comment]
@jrainville I know there have been some improvements lately, so this could be a potentially duplicate issue but perhaps the group chat has been neglected a bit?
