### ISSUE TITLE
Channel configuration to hide channel from certain members is not saved after editing member permissions

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14915]
# Bug Report

## Description
Channel configuration to hide channel from members who do not have permissions to view it, is not saved after editing member permissions

## Steps to reproduce

Prepare at least 2 users with the following:
- User1: community owner, holds at least 0,1 ETH
- User2: community member, does not hold any ETH

1. As  User1, add a channel (or edit a channel) with this rule:
2. Check the option: Hide channel from members who don’t have permissions to view the channel
3. Add permission: Anyone who holds 0,001  ETH is allowed to View only
4. Save changes
5. Look at the community as User2 (no ETH), notice user can still see the channel
6. As User1, go to Edit Channel
7. Notice that Channel configuration is not saved. “Hide channel from members who don’t have permissions to view the channel” option is unchecked.

#### Expected behavior
User2 who does not hold any ETH cannot see the channel
Channel configuration is saved. 

#### Actual behavior
User2 who does not hold any ETH can still see the channel
Channel configuration is not saved. I'm attaching a terminal log of the moment I click to save the channel configuration settings
<img width="1229" alt="Screenshot 2024-05-24 at 4 14 07 PM" src="https://github.com/status-im/status-desktop/assets/68916150/0c36cba2-a04c-491d-9982-972d495b7f75">

https://github.com/status-im/status-desktop/assets/68916150/1fe98ad8-3604-4159-be07-c59db5d3000c

### Additional Information
Might be related to issues 11948 and 13305
- Status desktop version: 2.29rc4
- Operating System:Mac OS Sonoma 14.5

**Comment by jrainville** [comment]
This is gonna be on the backend-team. It seems like the option wasn't passed or processed properly

**Comment by MishkaRogachev** [comment]
@jrainville in the master branch this feature seems to be working:

https://github.com/status-im/status-desktop/assets/2522130/0db9c9fa-b9af-4459-a1f9-228f129b4c9b

..except the UI bug with ETH precision:
![image](https://github.com/status-im/status-desktop/assets/2522130/55475566-b2b2-4dee-a7d0-f7eed7eb8f8d)

**Comment by MishkaRogachev** [comment]
<img width="1298" alt="Screenshot 2024-05-28 at 13 24 50" src="https://github.com/status-im/status-desktop/assets/2522130/32201288-a9d1-4abd-9d36-cb7bd9ef2076">

confirmed on the release branch

**Comment by MishkaRogachev** [comment]
There is a related issue in the master, but it manifests itself in the fact that when creating a channel permission it is deleted (after rebooting everything is ok).

https://github.com/status-im/status-desktop/assets/2522130/96921b54-4160-461c-9942-0164e4acac16

**Comment by MishkaRogachev** [comment]
Update. There are several issues that may be related to each other :
1) Then a user adds a permission to an existing channel. As a result channel gets disappeared on the control node side. Affects both master and release

https://github.com/status-im/status-desktop/assets/2522130/ddd828cc-5683-4066-9c8e-4095fd2a21c8

2) Then a user creates a permitted channel. In this case "Hide channel from members.." is not handled properly. Affects both master and release

https://github.com/status-im/status-desktop/assets/2522130/d4b05661-8baf-44f7-9b3e-78d4e31e3a07

3) Then a permitted channel got removed, community member is forced to kick:

https://github.com/status-im/status-desktop/assets/2522130/a5ee537a-1131-45b8-b466-e265b3a0d53c

**Comment by MishkaRogachev** [comment]
@jrainville, i've opened https://github.com/status-im/status-desktop/issues/14978 and https://github.com/status-im/status-desktop/issues/14979 for 1 and 3. Here i'm solving only 2.
