### ISSUE TITLE
Channel permissions - Add permission - User is allowed to enter an incorrect amount of ETH using a period as separator instead of a comma

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14916]
# Bug Report

## Description
User is allowed to enter an incorrect amount of ETH using a period as separator instead of a comma.

## Steps to reproduce

1. Log in with a user who is a community owner
2. Go to the Permissions of your community
3. Add a new permission or select an existing one and Edit it.
4. Add this rule "Anyone who holds" "ETH" is allowed to "View only" in channel.
5. Put the ETH amount using a period, for example "0.1"
6. Error message shows
7. Enter ETH amount "0.001"
8. Notice no error message displays
9. Select Update
10. Permission shows as 1 ETH instead of 0.001

#### Expected behavior
If periods are not allowed as a number separator, user should see an error message when typing 0.001
App should not allow user to select Update button

#### Actual behavior
No error message shows, user is allowed to enter 0.001 as ETH amount
App shows an incorrect ETH amount: 1 (ignoring the zeroes)
This can be confusing to the user and if correct permission is not set, channel may be inaccessible. 

https://github.com/status-im/status-desktop/assets/68916150/de6a06ce-2064-4b73-ab5d-44f91d57cb7d

https://github.com/status-im/status-desktop/assets/68916150/d31e3db1-ecf0-41ae-8658-a6e5c472884a

### Additional Information

- Status desktop version: 2.29rc4
- Operating System: Mac OS Sonoma 14.5

**Comment by caybro** [comment]
That's unfortunately how number parsing works in JavaScript, in this instance your decimal separator is `,` and thousands separator is `.`.
Watch the output of this little JS code snippet:

```js
var german = Qt.locale("de_DE");
var d;
d = Number.fromLocaleString(german, "0.001") // d == 1
console.warn("!!! 0.001 =>", d)
```

Output:
```
qml: !!! 0.001 => 1
```

**Comment by jrainville** [comment]
Seeing the videos, it seems like this is a real issue. @MishkaRogachev is this the same issue you were experiencing?
@friofry were you looking into it?

**Comment by caybro** [comment]
> Seeing the videos, it seems like this is a real issue. @MishkaRogachev is this the same issue you were experiencing? @friofry were you looking into it?

What is the issue exactly? `0.001` is a valid number and it gets parsed/validated as `1` under this locale, as demonstrated by the JS snippet I posted above; can't really fix how JavaScript works :/

**Comment by caybro** [comment]
But I agree this specific input (`AmountInput`) should not allow entering a thousands separator and we already have an issue opened for this: https://github.com/status-im/status-desktop/issues/14710

**Comment by caybro** [comment]
@micieslak can you pls look into this?

**Comment by caybro** [comment]
@virginiabalducci can you pls post a screenshot of your system locale settings which shows what decimal/thousands separator are currently in effect for you?

**Comment by virginiabalducci** [comment]
@caybro sure, does this help?
Number format shows `1.234.567,89`

<img width="480" alt="Screenshot 2024-05-27 at 3 55 23 PM" src="https://github.com/status-im/status-desktop/assets/68916150/a00e32e2-8c1b-4452-a306-a04a8c9543de">
<img width="470" alt="Screenshot 2024-05-27 at 3 55 43 PM" src="https://github.com/status-im/status-desktop/assets/68916150/18efcd6c-987d-484b-88f1-c1caa82ede7a">

**Comment by caybro** [comment]
> @caybro sure, does this help? Number format shows `1.234.567,89`
> 
> <img alt="Screenshot 2024-05-27 at 3 55 23 PM" width="480" src="https://private-user-images.githubusercontent.com/68916150/334191938-a00e32e2-8c1b-4452-a306-a04a8c9543de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDM3MzEsIm5iZiI6MTcxNjg0MzQzMSwicGF0aCI6Ii82ODkxNjE1MC8zMzQxOTE5MzgtYTAwZTMyZTItOGMxYi00NDUyLWEzMDYtYTA0YThjOTU0M2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDIwNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMmM1NGE1M2M0OGIzOTZlMzQ3NDAwMTY5NWI0YzRmYmM3MWM0ZjA0NmNkNmRhM2Q4MWM0NWU0N2I3MWYwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VGDdtKmf2EML1SSPvWVf59Xihg66t4s6xGTDXDmQic"> <img alt="Screenshot 2024-05-27 at 3 55 43 PM" width="470" src="https://private-user-images.githubusercontent.com/68916150/334191958-18efcd6c-987d-484b-88f1-c1caa82ede7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDM3MzEsIm5iZiI6MTcxNjg0MzQzMSwicGF0aCI6Ii82ODkxNjE1MC8zMzQxOTE5NTgtMThlZmNkNmMtOTg3ZC00ODRiLTg4ZjEtYzFjYWE4MmVkZTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDIwNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDk4ZWY1Zjg5YTI0YzEwNjdlYzRlNGNiMTlkZGUwYWYwNzhhM2I5NWVmZTJlM2Q2OTg2ZmVmN2YzN2QwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OtVymrcRZDwLgiaKGS_82WintdEJ2f3VC91X5ymOfC4">

Yup perfect, thanks. That confirms my earlier theory that `.` is your thousands separator, not decimal.
