### ISSUE TITLE
[UI - Wallet Stability] SendModal - remove first view with list of tokens

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#14924]
# Bug Report

## Description

The idea is to remove first step from SendModal where user can select tokens from the list. After selection this view is unreachable for the user. However the token selection can be still done via dropdown presenting the same content as that view.

![Screenshot from 2024-05-27 11-10-40](https://github.com/status-im/status-desktop/assets/20650004/e4195b2f-57ca-47b5-be2b-ee96429b7165)

It would be also more consistent with swap design, as there is no such view with list of tokens: https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3404-111405&t=GKsTboCVz2mFdrl0-0
Lack of asset selection is represented as `Select asset`. Similar approach could be used in send modal (`Select token` button).

cc @benjthayer

**Comment by noeliaSD** [comment]
This task will be covered in here: https://github.com/status-im/status-desktop/issues/15215
