### ISSUE TITLE
[UI - Wallet Stability] SendModal networks filtering is inconsistent

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#14923]
# Bug Report

## Description

`SendModal` dialog should take into account networks selection from main wallet view (this network selection is considered as global). Currently only account selector reflects networks selection properly. Assets selector presents the balance from all networks what is not expected. Also the "Max" value is incorrect.

[Screencast from 27.05.2024 10:58:30.webm](https://github.com/status-im/status-desktop/assets/20650004/aae61cbb-1d0f-4289-bf71-6db5ce768797)

#### Expected behavior
Global networks selection should be respected uniformly.

#### Actual behavior
Only account selector respects networks selection.

### Additional Information

- Status desktop version:
- Operating System:

**Comment by noeliaSD** [comment]
Please, ensure in the **SendModal** **User Stories** which is the requirement that covers that task. I remember the last agreed solution was: `SendModal` must use ALL networks. 

Take this task to review that the agreed requirement is developed this way in the current app.

**Comment by micieslak** [comment]
Already solved in the app along with using new adaptors providing data for selectors.
