### ISSUE TITLE
Sticker packs are not loading

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#14938]
# Bug Report

The list of sticker packs is empty and there is an error 

## Steps to reproduce

1. Create 1-1 chat
2. Click Stickers button in the message area
3. Click Get stickers

#### Expected behavior
A list of Sticker packs displayed

#### Actual behavior
There is an error saying Failed to load stickers and UI is broken

### Additional Information
<img width="1509" alt="Screenshot 2024-05-28 at 14 44 21" src="https://github.com/status-im/status-desktop/assets/141633821/181b266e-5f69-4189-8e68-e858adfa0eff">

Logs
[app_20240528_140202.log](https://github.com/status-im/status-desktop/files/15465994/app_20240528_140202.log)

- Status desktop version: the latest master build
- Operating System: masOS Ventura 13.5

**Comment by caybro** [comment]
Relevant log:
```
ERR 2024-05-28 14:02:17.194+07:00 rpc response error                         topics="rpc" tid=792819 file=core.nim:36 err="\nstatus-go error [methodName:stickers_market, code:-32000, message:Get \"QmWVVLwVKCwkVNjYJrRzQWREVvEk917PhbHYAUhA1gECTM\": unsupported protocol scheme \"\" ]\n"
ERR 2024-05-28 14:02:17.194+07:00 error doing rpc request                    topics="rpc" tid=792819 file=core.nim:40 methodName=stickers_market exception="\nstatus-go error [methodName:stickers_market, code:-32000, message:Get \"QmWVVLwVKCwkVNjYJrRzQWREVvEk917PhbHYAUhA1gECTM\": unsupported protocol scheme \"\" ]\n"
ERR 2024-05-28 14:02:17.194+07:00 Error in getMarketStickerPacks             tid=792819 file=async_tasks.nim:51 message="\nstatus-go error [methodName:stickers_market, code:-32000, message:Get \"QmWVVLwVKCwkVNjYJrRzQWREVvEk917PhbHYAUhA1gECTM\": unsupported protocol scheme \"\" ]\n"
```

Removing UI team ;) CC @jrainville

**Comment by caybro** [comment]
OK, that "Back" button probably needs fixing too..

**Comment by jrainville** [comment]
> OK, that "Back" button probably needs fixing too..

We'll take care of the loading issue. If you want, you can open a new issue for the back button

**Comment by MishkaRogachev** [comment]
Confirmed
```
ERR 2024-06-03 15:57:11.810+02:00 rpc response error                         topics="rpc" tid=8507842 file=core.nim:36 err="\nstatus-go error [methodName:stickers_market, code:-32000, message:Get \"QmbHJYDDW5CRdUfpLFRdJNCEDbZNYvAi7DAAfXrgheM1C3\": unsupported protocol scheme \"\" ]\n"
ERR 2024-06-03 15:57:11.810+02:00 error doing rpc request                    topics="rpc" tid=8507842 file=core.nim:40 methodName=stickers_market exception="\nstatus-go error [methodName:stickers_market, code:-32000, message:Get \"QmbHJYDDW5CRdUfpLFRdJNCEDbZNYvAi7DAAfXrgheM1C3\": unsupported protocol scheme \"\" ]\n"
ERR 2024-06-03 15:57:11.810+02:00 Error in getMarketStickerPacks             tid=8507842 file=async_tasks.nim:51 message="\nstatus-g
```

**Comment by MishkaRogachev** [comment]
It seems that build flags: version, commit and IpfsGatewayURL are empty...
```
INFO [06-03|21:38:33.838] Status backend initialized               backend=geth version= commit= IpfsGatewayURL=
```

**Comment by MishkaRogachev** [comment]
Status update: stickers are not loaded due to the missing `IpfsGatewayURL` parameter that should be set in `BUILD_FLAGS`, which are missing. I am currently looking into the Makefile
