### ISSUE TITLE
[UI - Wallet Stability] Simplify `AssetsView.qml` to be independent from `ManageTokensController`

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#14939]
## Description

Currently `AssetsView` is responsible for logic which is not necessary to do the primary goal of that component - displaying list of assets. 
Data preparation (like filtering) not related directly to that component should be externalized. Sorting done internally in the component should rely directly on the data from the model. `ManageTokensController` should not be involved - relying on model data directly will result in simpler and faster code here and better split responsibilities.

Once the data preparation logic is excluded it may be necessary to create additional Adaptor model for doing that work separately.

Blocked by: https://github.com/status-im/status-desktop/issues/14937
Related to (better to have this first ready but not mandatory): https://github.com/status-im/status-desktop/issues/14704

**Comment by caybro** [comment]
Just a side note, simlarly, the `TransactionStore` also depends on the controller (to get the correct sorting/filtering from the Manage Tokens settings)
