### ISSUE TITLE
Review ID verification reply is stuck

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14935]
# Bug Report

Review ID verification reply is stuck, user cannot do any action with it. If a new ID verification is requested, it does not show on the list.

## Description
I think I can explain this issue in two parts: 
**Issue 1**: Notification is stuck and cannot be accepted or cancelled.
test user `Test2281three` sent an ID verification request to user `Test2281`. 
`Test2281` has replied to `Test2281three` which has a pending ID verification request that has been replied by user `Test2281`.  User does not have any pending notifications.
As user `Test2281three`, check the Configuration -> messaging -> Contacts -> Pending requests -> Received, and see that the answer is there, but user cannot do anything with it. Cannot confirm, cancel. If user tries to send another verification request question, message seems not to be sent. `Test2281` user does not receive anything.

**Issue 2** ID verification notification for other user is not displaying in the Pending requests
While having a pending verification request from user`Test2281`,  user `Test2281three` sends an ID verification request to user `test004`.
As `test004` send 1 answer, then send a second answer, and then a third answer, one after the other. 

https://github.com/status-im/status-desktop/assets/68916150/45959b35-8e03-444b-99e2-f471a543224c

As `test004` go to Pending requests -> Received, send another message and click the green checkmark to close the request. 

As `Test2281three`  go to Pending requests -> Receive:  note that the request from `test004` is not in the Received list, but if user clicks on the notifications, the request is there. Send another question.

https://github.com/status-im/status-desktop/assets/68916150/4ca52e41-87e1-43df-9230-68c2c3f8622c

More videos showing the issue

https://github.com/status-im/status-desktop/assets/68916150/d2a0a661-462c-436b-b28a-c04992f9e750

https://github.com/status-im/status-desktop/assets/68916150/2ef204c2-ef19-44cc-980f-37e6ab4929e3

## Steps to reproduce

See Description

#### Expected behavior
- Pending requests -> Received to show the list of the pending notifications

#### Actual behavior
- Pending requests -> Received: notification is stuck and new requests do not show. They only show when clicking on the notifications bell on the top right.

### Additional Information
[testlogs_testuser2281three.txt](https://github.com/status-im/status-desktop/files/15461986/testlogs_testuser2281three.txt)

I'm not sure if this is an issue with a particular profile (`Test2281three` ), to check if this happens to more users, I will try to reproduce this with fresh new users shortly and post an update.

- Status desktop version: 2.29.0 rc-4
- Operating System: Mac OS Sonoma 14.5

**Comment by noeliaSD** [comment]
@jrainville maybe more for `backend-team`? WDYT?

**Comment by jrainville** [comment]
> @jrainville maybe more for `backend-team`? WDYT?

Yeah indeed
