### ISSUE TITLE
[Backend] Add an overlay when a user satisfies member permissions but doesn't have the newest encryption keys

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14931]
### Description

There is a problem currently where even though you are a member of a channel and have the right tokens, if the control node updated the encryption keys and you didn't receive them, the channel's member list will be encrypted to you and you won't be able to see it.

It is doubly a problem considering that we use the channel member list to know if a member has access to the channel.

Though we have [an issue](https://github.com/status-im/status-desktop/issues/14683) to help tackle the backend side of it (try to get the keys), we still want the user to know what is going on.
Especially considering that if the user tries to send a message, it will fail.

@osmaczko 's flow chart of the wanted behaviour:
```mermaid
flowchart LR
    C1(["Start"]) --> C2{"Is on member list/\nhas encryption key?"}
    C2 -->|N| C3N{"Satisfies permissions\n(on chain/cache check)?"}
    C3N -->|N| C4N{"Is private?"}
    C4N -->|N| C5N(["Show overlay\n(missing permissions)"])
    C4N -->|Y| C5Y(["Hide"])
    C3N -->|Y| C4Y(["Show overlay\n(waiting for encryption key)"])
    C4Y -.-> C5[["request keys from control node if not received in [t] minutes"]]
    C2 -->|Y| C3Y["Access channel"]
    C3Y --> C4(["All fine"])
```
source: https://github.com/status-im/status-desktop/issues/14683#issuecomment-2133910622

We want to implement the overlay at `waiting for encryption key`. This overlay needs to block the member list, since it will be empty. It also needs to block the input, since sending will not work. I think still showing the past messages is fine. As long as it's clear that the user might not be receiving new messages for now.

This issue is for the backend work on sending the right signals or setting the right view properties so that the UI can display the right overlay.
I encourage using placeholder text on the member list and on the input, but do not waste too much time making it pretty.

Easier to implement after https://github.com/status-im/status-desktop/issues/14913

### Acceptance Criteria

- There is a placeholder text on the member list when we detect that we are not in the member list but still satisfy (even for hidden channels)
- The input is blocked in that case too

**Comment by jrainville** [comment]
@benjthayer we're gonna be working on a placeholder version of this overlay, but it would be good to have a "final" design for it that we can give to the UI time for later in the milestone. Thanks!

**Comment by osmaczko** [comment]
Closing in favor of: https://github.com/status-im/status-desktop/issues/15064
