### ISSUE TITLE
Removing a pending ID verification request by clicking on the X does not cancel the verification request

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14950]
# Bug Report

## Description
Removing a pending ID verification request

## Steps to reproduce
As user1 `Test005` send a ID verification request to user 2 `Test006`. 

As user 2 `Test006` go to Settings -> Contacts ->Pending Request, and click on the X to remove the ID verification.

The verification request is deleted from the Pending Request but is not declined. This is confusing to the user. 
Request can still be accessed by clicking on the notification Bell

https://github.com/status-im/status-desktop/assets/68916150/c896a0be-fa2d-483b-b043-ed6c088ac1e5

#### Expected behavior
When user goes to Settings -> Contacts ->Pending Request and clicks on the X, the result of that action should be more clear to the user. 
Is the action meant to remove the notification and still keep it active or can user decline it?
If the intention is to keep the pending notification, is it ok that it only displays on the notification bell menu?
If the intention is for the user to quickly decline the ID verification request, a confirmation should be sent to the user such as asking them if they are sure they want to decline the request.

Could you help me clarify this? Thanks!

#### Actual behavior
The verification request is deleted from the Pending Request but is not declined.

### Additional Information

- Status desktop version: 2.29.0 rc-4
- Operating System: Mac OS Sonoma 14.5

**Comment by noeliaSD** [comment]
@jrainville maybe more for `backend-team`? WDYT?

Maybe also some clarification from design team? @benjthayer @xAlisher

**Comment by iurimatias** [comment]
closing as this feature is currently disabled
