### ISSUE TITLE
Discord Bridge edits do not work

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14955]
# Bug Report

## Description

They worked in 2.28, but in 2.29, they regressed.

Here is what they look like now.

![image](https://github.com/status-im/status-desktop/assets/11926403/0fac9480-faba-4ce3-a135-74a91567bdfc)

## Steps to reproduce

1. Send a message on Discord in a bridged community
2. Edit that message
See that it doesn't edit the message and even looks super weird in Status

#### Expected behavior

The message is edited in Status

#### Actual behavior

A weird empty message shows up

### Additional Information

- Status desktop version: 2.29 RC4

**Comment by endulab** [comment]
It seems that Matterbridge pr was not merged. I closed it by mistake. 🤦 
https://github.com/status-im/matterbridge/pull/7
