### ISSUE TITLE
There is no notification to inform User1 that the ID verification request has been declined

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14960]
# Bug Report

## Description
User1 sends an ID verification request to User2. The verification is declined but there is no notification or alert to User1 to let them know of this.

## Steps to reproduce

As user1 `Test006`, send a verification ID request to `test007`. 
As user2, `test007`, Decline the ID verification request.
As user1 `Test006`, check user2 `Test007` profile card, there is a “ID verification pending”. Click the pending verification button.
The request is pending with text “Awaiting Test007’s response” however, user2 `Test007` has already declined the verification request.

#### Expected behavior
There should be an indicator to user1 that user2 has declined the request.

#### Actual behavior
There is no indication to user1 (who sends the request), that the user2 has declined the verification.
There is no option to re-send the request, user1 can only cancel the request.

https://github.com/status-im/status-desktop/assets/68916150/5148c77d-1833-4251-89a8-28001de70a64

### Additional Information
May be related to issue https://github.com/status-im/status-desktop/issues/7377

- Status desktop version: 2.29.0-rc-4
- Operating System: Mac OS Sonoma 14.5

Update:
I quitted the app and logged back in as Test006 user, and I see the notification that the request has been declined.
![Screenshot 2024-05-28 at 3 02 13 PM](https://github.com/status-im/status-desktop/assets/68916150/9bb4f026-8305-4afa-863a-e19f2afcf7a4)

Is there a estimated time where user should see the declined response? or is it at this point needed for the user to restart the app? Thanks

**Comment by noeliaSD** [comment]
I'd say that's more for the `backend-team` @jrainville ??

**Comment by jrainville** [comment]
> I'd say that's more for the `backend-team` @jrainville ??

Yeah you're probably right
