### ISSUE TITLE
Automatic application theme detection does not work

### ISSUE THREAD

**Issue by Extrypto** [status-im/status-desktop#14986]
# Bug Report

## Steps to reproduce
1. Install Status on Linux Mint 21.3
2. Configure app

![image](https://github.com/status-im/status-desktop/assets/74716150/c63dfaa2-3c28-4bca-89bc-c898ed07a0bb)

### Additional Information
This is most likely the case for all Linux OS with GNOME.
- Status desktop version: 2.28.1
- Operating System: Linux Mint 21.3

**Comment by caybro** [comment]
Yeah this is unfortunately not supported by Qt on Linux
