### ISSUE TITLE
collapsed category does not remember its previous stage when re-starting the app

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#14992]
# Bug Report

## Description
The app is not remembering the last option saved by the user (collapse category)

## Steps to reproduce
Pre-requisite: log in with a user who is a member of a community. The community has a group of channels inside a channel category.

1. Go to the community and collapse the channel category so that the channel list is hidden.
2. Close the app
3. Re open the app

#### Expected behavior
when a user collapses a category (hides it), the category stays collapsed when reopening the app later.

#### Actual behavior
the category displays as expanded (all channels from the category are visible) when the app is re-opened.

https://github.com/status-im/status-desktop/assets/68916150/2b8bce63-4943-4405-92e2-4c871c90deae

### Additional Information
Related to https://github.com/status-im/status-desktop/issues/13944

- Status desktop version: 2.29.0-rc5
- Operating System: Mac OS Sonoma 14.5

**Comment by jrainville** [comment]
Ugh that's annoying. I just fixed it, but it still happens sometimes is seems.

Since it's basically the same behaviour as in 2.28, I'll log this in 2.30.

BTW, pro tips:
- Sign out and Quit is the same as pressing the X, so you can gain some time
- The spinner with the tips is an hardcoded 30 seconds loading. You can disable it in Advanced by unckecking Fake loading screen

**Comment by jrainville** [comment]
I can't seem to reproduce anymore. I tried master, RC7 and dev RC7. 

Do you have any other reproduction steps @virginiabalducci ? Or maybe it doesn't reproduce for you either on RC7?

**Comment by virginiabalducci** [comment]
@jrainville I tested it on RC7 with two different test accounts and can no longer reproduce it. I'll close this one for now!
