### ISSUE TITLE
Add SIWE to sign in via Wallet Connect

### ISSUE THREAD

**Issue by clauxx** [status-im/status-desktop#14996]
### Description

_As a user, I want to be able to sign in with a dapp in one interaction, so that the dapp onboarding is more user friendly._

Aside from the usual session establishment, we should also support authentication with SIWE (see [wallet connect docs](https://docs.walletconnect.com/web3wallet/authenticatedSessions)).

[Design link](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=4358-179637&t=pCPe4A3qPXuqsSSQ-4)

### Acceptance Criteria

- [ ] the user can see a connection screen when SIWE auth is triggered from the dapp
- [ ] the user can see the message from the dapp (no url highlights)
- [ ] the user can expand/collapse the message from the dapp on press
- [ ] the user can see and change the account used to sign in
- [ ] the user can use biometrics/password to sign the message from the dapp
- [ ] the user can log in with the dapp after the interaction is done

**Comment by alexjba** [comment]
Moving to 2.31

**Comment by alexjba** [comment]
@clauxx Do you forsee any issues with the SIWE dapps if we don't support it yet? Looking at the WC docs I see we should be ok if `personal_sign ` is supported.

```
Configuring your Web3Modal client with AuthRequestParams will prioritize authentication requests over regular session proposals. If the wallet supports One-Click Auth, the session will be created and the user will automatically authenticate without needing to send another SIWE request over personal_sign. If the wallet does not support One-Click Auth, it will fall back to the session proposal. In this case, to authenticate the user, you can send another session request to prove address ownership.
```

**Comment by clauxx** [comment]
Yeah I think we should be fine. One improvement from adding it would be fixing the edge case where:
1. dapp prompts user to connect
2. user approves connection
3. dapp sends personal_sign SIWE request
4. user rejects
5. dapp is shown as connected (but the dapp is not connected)

For this though dapps would have to explicitly add support to walletconnect's "one click auth" and from what we tested, none of the popular ones have this apart from the testing dapps.
