### ISSUE TITLE
Sepolia opt balance loading intermittently

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#15006]
# Bug Report

## Description

Balance on sepolia opt is not loading consistently.

## Steps to reproduce

1. Import account from seed that has a sepolia opt balance
2. Switch to testnet and view wallet
3. Balance is shown as 0
4. After bringing the app into focus again after 20 - 30 minutes the expected balance was shown
5. After a restart the balance was gone again and has not returned after further restarts or toggling testnet mode

Notes: 
- For some users the sepolia opt balance is never shown
- The api error banner appeared briefly on startup but went away
- It was not possible to find debug logs relevant to the API limit or timeout similar to other issues
- Please follow up with @anastasiyaig or @virginiabalducci if further QA support is needed.

#### Expected behavior

Balance to be correct on importing account.

![image](https://github.com/status-im/status-desktop/assets/50769329/21c8f096-4e61-43a5-97f3-e33b5bf5bfd0)

#### Actual behavior

Balance is missing

### Additional Information

Using the wallet is further complicated by balance issues in the send modal https://github.com/status-im/status-desktop/issues/14580

- Status desktop version: 2.29 RC6
- Operating System: Mac

**Comment by dlipicar** [comment]
saw this in the logs, as if we had some issue with POKT/Infura

```
ERROR[05-28|18:26:17.467|github.com/status-im/status-go/services/wallet/token/token.go:802]                   can't fetch erc20 token balance 6        account=0xE8681E58F6adC2bCC1959Abf982Ec141871E372E error="fallback failed with '401 Unauthorized: invalid project id\n'. run error was 'no result in JSON-RPC response'"
ERROR[05-28|18:26:18.648|github.com/status-im/status-go/services/wallet/token/token.go:802]                   can't fetch erc20 token balance 6        account=0xDD7946A69846A40b728FaBee25326FCD09438CFd error="fallback failed with '401 Unauthorized: invalid project id\n'. run error was 'no result in JSON-RPC response'"
ERROR[05-28|18:26:19.183|github.com/status-im/status-go/services/wallet/token/token.go:802]                   can't fetch erc20 token balance 6        account=0x1fD23B38cabe2BFEAcCA560626C742bb1a98Ec13 error="fallback failed with '401 Unauthorized: invalid project id\n'. run error was 'no result in JSON-RPC response'"
```

**Comment by alaibe** [comment]
@dlipicar @saledjenic  Could it be a cache issue?

**Comment by saledjenic** [comment]
> @dlipicar @saledjenic Could it be a cache issue?

I cannot say anything more about this before checking. Adding it to this milestone.

**Comment by anastasiyaig** [comment]
i did not see it for a while now
@virginiabalducci can you pls confirm?

**Comment by virginiabalducci** [comment]
I haven't been able to reproduce the issue on my end for some days now, I'm good with closing this one @IvanBelyakoff
