### ISSUE TITLE
Owner crown is absent in the members list

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#15000]
# Bug Report

## Description

The owner does not have an owner crown

![image](https://github.com/status-im/status-desktop/assets/117639195/cc9326ae-6a9d-4dde-9b7c-3f340d1fa933)

## Steps to reproduce

1. Create a community

#### Expected behavior

Community owner has a crown

#### Actual behavior

Community owner does not have a crown

### Additional Information

- Status desktop version: latest master
- Operating System: macos

**Comment by caybro** [comment]
Might be related :) https://github.com/status-im/status-desktop/issues/14994

**Comment by jrainville** [comment]
Closing as I can see the crown icon correctly on 2.30
