### ISSUE TITLE
Slippage Selector Issues

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#15017]
# Bug Report

## Description

The SlippageSelector.qml is missing some behaviours and behaves incorrectly in some cases as listed below
1. The various error messages - the reason I think this should be included in this base component is because only the component knows best the various reason for the error. FO example in case nothing is entered we should empty error and we cant know that from the outside if the slippageSelector.
hence, I think this component should show the error messages too. Ive listed the various error messages below
```

- 0 value entered
- no alphabets
- empty value
- max 2 decimals
- error in case value entered is greater than 5

```
2. https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3410-267460&m=dev design shows a possibility to enter letters but we aren't allowing it at all
3. Unable to enter values greater than 2 decimals points and showing error message
4. If I click on custom and switch to a predefined value without entering any value, the button should switch back to Custom cause the current behaviour seems wrong
https://github.com/status-im/status-desktop/assets/60327365/3b4f0086-c8b1-4c44-9783-365ace29728a
5. I see Unit tests missing for the  error scenarios mentioned here and would be great if UTs were added to confirm error message shown too.

**Comment by caybro** [comment]
I'll take this and let's discuss it tomorrow :)

**Comment by noeliaSD** [comment]
I'm removing the `ui-team` label since @Khushboo-dev-cpp is taking it and it's easier to track ui capacity then!

**Comment by Khushboo-dev-cpp** [comment]
can we keep it open for whoever has time to take it? as it is a bug? or maybe it doesn't work like that @noeliaSD ?
and unassign me so that either me or Lukas can pick it up.

**Comment by noeliaSD** [comment]
> can we keep it open for whoever has time to take it? as it is a bug? or maybe it doesn't work like that @noeliaSD ? and unassign me so that either me or Lukas can pick it up.

Alright, added into our ui backlog then! Thank you!!

**Comment by micieslak** [comment]
[Screencast from 25.07.2024 13:31:16.webm](https://github.com/user-attachments/assets/66d7a7e9-b4f8-45eb-984e-637acb46afff)

My findings recorded. Sometimes nothing is selected. Sometimes there is custom value but not applied and "Use default" button is not visible.

**Comment by caybro** [comment]
Another finding; this should not be marked as valid:

![image](https://github.com/user-attachments/assets/67377bab-6ecc-4aaf-a3da-1106c9d1461b)

**Comment by caybro** [comment]
One more in SwapModal (after typing a custom value) and selecting "Use default" -> nothing is visually selected although the internal value is correct:
![image](https://github.com/user-attachments/assets/f6f2499b-35fe-4884-9749-5c95c29392bf)

**Comment by caybro** [comment]
Reset after typing the default value (0.5) manually:
![image](https://github.com/user-attachments/assets/68db6e14-1e89-45fb-9418-f7d9fad5b127)

**Comment by caybro** [comment]
> * https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3410-267460&m=dev design shows a possibility to enter letters but we aren't allowing it at all
> * Unable to enter values greater than 2 decimals points and showing error message

These won't be implemented simply because the internal validator doesn't let you enter values with more than 2 decimals or letters
