### ISSUE TITLE
Illegal storage access issue when hitting Start using status button

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15035]
### Description

Try to create new account (reproducible on mac , linux and windows, but easiest is windows)

![Снимок экрана 2024-06-04 171824](https://github.com/status-im/status-desktop/assets/82375995/9dfe372e-c6bb-4f73-a45f-9cb51cf838fb)

Version: Windows 10 Pro, Linux, Mac

**Comment by lukaszso** [comment]
Retested today on Win 11 and it is still happening. Very easy to reproduce.

**Comment by igor-sirotin** [comment]
@lukaszso could you please give the repro steps on MacOS?
