### ISSUE TITLE
Syncing list is empty even the device is paired

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15053]
# Bug Report

## Description

Syncing screen is not showing devices list

## Steps to reproduce

Sync desktop application with any other , lets say mobile

#### Expected behavior

Syncing screen shows the list of devices

<img width="1547" alt="Screenshot 2024-06-05 at 16 06 41" src="https://github.com/status-im/status-desktop/assets/82375995/42db0f89-2e54-4d2e-b7d0-00a3f055ad5b">

#### Actual behavior

![image](https://github.com/status-im/status-desktop/assets/82375995/39565e18-566c-4ade-b76c-7ed733d8e04d)

![image](https://github.com/status-im/status-desktop/assets/82375995/223f27c2-80b9-45bf-8003-0c4027a06b7d)

### Additional Information

- Status desktop version: master build
- Operating System: Windows 10, Mac

**Comment by MishkaRogachev** [comment]
Confirmed, empty even after restarting the app
