### ISSUE TITLE
[dApps] Signing/sending transactions `User Story`

### ISSUE THREAD

**Issue by clauxx** [status-im/status-desktop#15057]
### Description
[User story and acceptance criteria](https://www.notion.so/I-want-to-sign-transactions-from-dApps-51e781a421f949efa999bad72a3ef694?pvs=4)

[Design](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=3620-38978&t=8vEIYMDgIVc4Ep4z-0)

![Screenshot 2024-06-06 at 14 13 14](https://github.com/status-im/status-desktop/assets/97019400/b3a44434-2938-4fc8-9165-1da2f650b781)

Ensure the following [task](https://github.com/status-im/status-desktop/issues/14762) also includes the use cases for signing transations meaning that:
- There's a different text in the header of the dialog (instead of related to messages, related to transactions)
- Fees box is shown properly

[comment]: # (Rules for the future PR to be accepted.)

Additional related tasks:

- [x] #15126
- [x] #15190
- [x] #15191
- [x] #15192

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-desktop/pull/15520

**Comment by clauxx** [comment]
Yeah the setup we have at the moment with the user stories and "tasks with tasks inside" is confusing.

**Comment by noeliaSD** [comment]
Initially this was just a single task! :) Once the tasks where created inside, then it should be marked as epic! :)

**Comment by alexjba** [comment]
Added a bug for the fees formatting

- [ ] https://github.com/status-im/status-desktop/issues/15612

**Comment by stefandunca** [comment]
@anastasiyaig this user story is also completed and ready for testing

**Comment by alexjba** [comment]
@anastasiyaig Can we close this? All the related tasks are closed and the bugs are tracked in separation.

**Comment by anastasiyaig** [comment]
lets do that :)
