### ISSUE TITLE
Bloom filter to confirm that we are member of a channel without using encryption keys

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15064]
I just talked with @cammellos and he raised a good point, we should try to avoid permissions check on clients as much as possible. Ideally, we should only check permissions when we click on the channel and want to see what permissions we are missing. To achieve this, we need to determine whether we belong to the channel or not, without compromising the privacy gained by encrypting the members list. This is the challenging part. One idea is to have an additional members list containing `trim(hash(dh_common_secret, channel_name, community_clock), 4bytes)`, which allows each user to privately verify their membership. Additionally, we likely don't want to send the entire list; instead, we can use a Bloom filter or another more compact method.

The flow would look as follows:
```mermaid
flowchart LR
    C1(["Start"]) --> C2{"Is on member list/\nhas encryption key?"}
    C2 -->|N| C3N{"Is member on the magic list?"}
    C3N -->|N| C4N{"Is private?"}
    C4N -->|N| C5N(["Show overlay\n(calculate missing permissions on the fly)"])
    C4N -->|Y| C5Y(["Hide"])
    C3N -->|Y| C4Y(["Show overlay\n(waiting for encryption key)"])
    C4Y -.-> C5[["request keys from control node if not received in [t] secs"]]
    C2 -->|Y| C3Y["Access channel"]
    C3Y --> C4(["All fine"])
```

_Originally posted by @osmaczko in https://github.com/status-im/status-desktop/issues/14683#issuecomment-2133950451_

---

This would replace the call we do when we see that we are not part of a channel to check the permissions (using the cache).

With this, we could just rely on what the control node sends. However, we will still need the overlay shown in the chart.

Also, we will still need to do the permission check if we are indeed **not** part of a channel, because then we need to show the user what tokens they are missing.

**Comment by osmaczko** [comment]
> Also, we will still need to do the permission check if we are indeed not part of a channel, because then we need to show the user what tokens they are missing.

Note: this will be only on demand, i.e. when the channel is opened on UI.

**Comment by osmaczko** [comment]
## Brief solution description

Build bloom filter for each private channel, as follows:
```golang
falsePositivesProbability := 0.001
filter := bloom.NewWithEstimates(len(channel.members), falsePositivesProbability)
for member := channel.members {
    filter.Add(hash(shared_secret(owner, member), channel_name, community_clock))
}
```

Probability of false positives: 0.1%
Number of hash functions: 10

Library to be used: https://pkg.go.dev/github.com/bits-and-blooms/bloom/v3 ([we already indirectly use it](https://github.com/status-im/status-go/blob/e2846f3936d7ffab833f1eef68b500d6224055cc/go.mod#L134)).

## Justification of hash parameters

`shared_secret` - other members MUST NOT be able to determine if you belong to a private channel
`channel_name` - private channels that share the same member list MUST be indistinguishable
`community_clock` - any private channels whose member list remains unchanged over time MUST be indistinguishable

## Probability of false positives and space required

| No. of members | Probability of false positives | Size     |
| -------------- | ------------------------------ | -------- |
| 10000          | 0.01                           | 11.7KiB  |
| 10000          | 0.001                          | 17.55KiB |

For comparison, if we were to use the trimmed hash approach (storing a list of `trim(hash, x bytes)`), it would look as follows:
| No. of members | Probability of false positives | Trimmed hash size | Size  |
| ------------- | ------------------------------ | --------------------- | ----- |
| 10000         | 0.01                           | 32 bits               | 39KiB |
| 10000         | 0.001                          | 36 bits               | 44KiB |
