### ISSUE TITLE
[UI - Wallet Stability] `Max` button component

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15066]
![image](https://github.com/status-im/status-desktop/assets/5377645/70985017-a0e9-4243-9d11-e89b6d030322)

- create a reusable component (Swap and Send modal both have a slightly different copy atm)
- use a plain `StatusButton` instead of `StatusListItemTag`
- take an unformatted `max` value, `symbol` (for fiat values), `valid` and `clickable` bool flags
- format the max value with configurable decimal places and optional symbol
- should act as a button, emit `clicked()` signal
- provide a "safe" max output value, to be used for value (string) based input components
- integrate in storybook
- provide basic QML tests

Example usage:

![image](https://github.com/status-im/status-desktop/assets/5377645/908723cf-093a-4a63-9ba1-28cd791ec6c3)

**Comment by alexjba** [comment]
@benjthayer Maybe we should display "Max. <0,01" for really small amounts?

**Comment by benjthayer** [comment]
> @benjthayer Maybe we should display "Max. <0,01" for really small amounts?

Good point. I think we actually have a formula for how many decimals to show for each asset which relates to the value of those decimals in the user's base currency. I think this is the issue:
https://github.com/status-im/status-desktop/issues/8640#issue-1476918485
