### ISSUE TITLE
Seed phrase input popup has invalid paddings

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#15074]
# Bug Report

Seems it has a redundant 5px padding on all sides.

<img width="295" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/371fbd26-324a-4954-acc1-1f00a8792803">

**Comment by jrainville** [comment]
This seems fixed ![Image](https://github.com/user-attachments/assets/231fcfa2-63f9-4321-b181-0b300d3b264d)

**Comment by caybro** [comment]
> This seems fixed ![Image](https://github.com/user-attachments/assets/231fcfa2-63f9-4321-b181-0b300d3b264d)

Yeah, probably fixed that already :)
