### ISSUE TITLE
Edited message that only contains emojis does not display the 'edited' status

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15081]
# Bug Report

## Description
Edited message that only contains emojis does not display the 'edited' status

## Steps to reproduce

1. Open a chat (1:1, group, community channel)
2. Send a message that contains only emojis
3. hover over the message and click Edit
4. edit the message by adding other emoji

#### Expected behavior
Edited message to display (edited) status
#### Actual behavior
Edited message does not display (edited) status.

Editing an emoji-only message
https://github.com/status-im/status-desktop/assets/68916150/a956a6d4-37e7-45b3-9dcb-53366eb43a6f

### Additional Information

- Status desktop version: 2.29.0rc7 abnd latest master https://github.com/status-im/status-desktop/commit/fdf47c4c2
- Operating System: Mac OS Sonoma 14.5

**Comment by caybro** [comment]
I'd tend to say `backend-team`... :) CC @jrainville

**Comment by jrainville** [comment]
It seems like it's all handled in the QML

https://github.com/status-im/status-desktop/blob/master/ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusTextMessage.qml#L42

We add the `(edited)` label lower below, but we return on that line if it's an Emoji

**Comment by caybro** [comment]
@noeliaSD milestone? :)

**Comment by caybro** [comment]
Whatever, simple fix :)

**Comment by jrainville** [comment]
> @noeliaSD / @jrainville I'll push this to master; worth backporting to 2.29? (I'm guessing not)

Nah it's not worth it
