### ISSUE TITLE
Not receiving messages in community channel with 7 peers 

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#15092]
# Bug Report

Not receiving messages in Status Community (#mobile channel) for several minutes despite having 7 peers in node management.

I then went to debug > fetch messages.

Messages finally showed up at 21:02:56

### Additional Information

- Status desktop version: 2.28.12
- Operating System: Linux x86_64 app image

### logs

[app_20240607_205241.log](https://github.com/user-attachments/files/15738205/app_20240607_205241.log)

[geth-upload.log](https://github.com/user-attachments/files/15738212/geth-upload.log)

**Comment by fryorcraken** [comment]
Cc @kaichaosun

**Comment by chaitanyaprem** [comment]
While going though the logs i found out these logs which i did not expect to be there. Could this be due to someone spamming the shards? Or are these logs expected?

```
   44 DEBUG[06-07|21:00:40.608|github.com/status-im/status-go/wakuv2/common/message.go:162]                                failed to extract content topic from message topi      c=my-ctopic-2 err="invalid content topic format"
   45 DEBUG[06-07|21:00:40.608|github.com/status-im/status-go/wakuv2/common/message.go:162]                                failed to extract content topic from message topi      c=my-ctopic-2 err="invalid content topic format"
   46 DEBUG[06-07|21:00:40.609|github.com/status-im/status-go/wakuv2/common/message.go:162]                                failed to extract content topic from message topi      c=my-ctopic-2 err="invalid content topic format"
```
cc @richard-ramos @cammellos

**Comment by chaitanyaprem** [comment]
@fryorcraken I see below messages in the logs which could be the reason why messages were not delivered to you eventhough you had 7 peers. 
By any chance was telemetry enabled?

`  148 INFO [06-07|21:00:41.749|go.uber.org/zap/sugar.go:168]                                                               Can't deliver message to subscription for topic /      waku/2/rs/16/32; subscriber too slow`


> # Bug Report
> 
> Not receiving messages in Status Community (#mobile channel) for several minutes despite having 7 peers in node management.
> 
> I then went to debug > fetch messages.
> 
> Messages finally showed up at 21:02:56
> ### Additional Information
> 
>     * Status desktop version: 2.28.12
> 
>     * Operating System: Linux x86_64 app image
> 
> 
> ### logs
> 
> [app_20240607_205241.log](https://github.com/user-attachments/files/15738205/app_20240607_205241.log)
> 
> [geth-upload.log](https://github.com/user-attachments/files/15738212/geth-upload.log)

**Comment by richard-ramos** [comment]
> While going though the logs i found out these logs which i did not expect to be there. Could this be due to someone spamming the shards or some invalid messages are being formed? Or are these logs expected?

I could not find mentions of `my-ctopic-2` in repos. Might be someone doing some tests

**Comment by fryorcraken** [comment]
Will close for now, assuming telemetry was the issue.

**Comment by fryorcraken** [comment]
@chaitanyaprem can you provide the reference to the issue tracking the telemetry bug?

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem can you provide the reference to the issue tracking the telemetry bug that impact message reliability?

Here it is https://github.com/status-im/status-go/issues/5240
