### ISSUE TITLE
Create community button setting is set per application and not per account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15091]
### Description

If i enable `Enable community creation` toggle in Advanced settings and then log out from the app and create new user, then the setting is still applied for newly created user

<img width="1591" alt="Screenshot 2024-06-07 at 13 08 59" src="https://github.com/status-im/status-desktop/assets/82375995/7c52315b-abb2-485d-a2ad-770d766d7341">

**Comment by jrainville** [comment]
Is this really an issue? I kinda did it voluntarily

**Comment by anastasiyaig** [comment]
@jrainville good question, i got this report from mobile team, worth checking with @John-44 maybe?

**Comment by jrainville** [comment]
My rationale was that if a user enabled community creation on one account, they're fine having it on on their other accounts too.

It's not a big fix, but it's also not a huge impact to leave it as is. Especially if we'll re-enable the button soon-ish

**Comment by anastasiyaig** [comment]
agree :)

**Comment by jrainville** [comment]
I'll close since we'll probably re-enable community creation at the end of 2.30 anyway
