### ISSUE TITLE
Can't restore account (windows and linux)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15101]
# Bug Report

## Description

On my windows 10 (as well as for @lukaszso on windows 11), several certain accounts can't be restored

## Steps to reproduce

1. open status
2. go with recovering account flow
3. restore `dizzy walnut dragon chef sweet shoot tooth fragile talk alone inside face`

https://github.com/status-im/status-desktop/assets/82375995/15dcc679-ba89-4a8a-9a42-131270956c27

The button `Finalise` does nothing

#### Expected behavior

can import account

### Additional Information

- Status desktop version: commit fdf47c4c21aa10dcc4d3afafc8c4aeba9ab8d3f0 master, release 2.29 rc 9
- Operating System: Windows 10, Ubuntu 22.04

Logs:
```
DBG 2024-06-07 11:51:54.532+03:00 Account saved succesfully                  topics="accounts-service" tid=4959 file=service.nim:438
ERROR[06-07|11:51:54.538|github.com/status-im/status-go/mobile/status.go:344] failed to restore account                error="account already exists"
```

**Comment by lukaszso** [comment]
Seed i used to reproduce `twist destroy lion inspire start misery rate fame energy wise major dice`

**Comment by caybro** [comment]
I wasn't able to restore mine on Linux too last time I tried (~2 weeks ago?)
