### ISSUE TITLE
Can't proceed further when clicking back button on any of keycards screens

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15113]
# Bug Report

## Description

When i am on a keycard screen during account set up, if i click Back button at the top left, then i can't resume any flow

## Steps to reproduce

1. open app
2. click I am new to status
3. click flow to create account with new keycard
4. on a PIN set up screen, click Back
5. click button to initiate flow to create account with keycard again

#### Expected behavior

user is redirected to next screen

#### Actual behavior

Nothing happens

https://github.com/status-im/status-desktop/assets/82375995/ab618296-3c4f-4216-b991-d85d75d5ba71

### Additional Information

- Status desktop version: 2.29 rc 10, but also happens in master
- Operating System: Windows , Linux
- Logs: 
[app_20240610_123215.log](https://github.com/user-attachments/files/15760045/app_20240610_123215.log)

**Comment by saledjenic** [comment]
@anastasiyaig please check it once the PR gets merged, hope you won't be able to reproduce it again.
