### ISSUE TITLE
`Ctrl+C` doesn't kill the app anymore

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#15124]
# Bug Report

With https://github.com/status-im/status-go/pull/5289 status-desktop is not killing with `Ctrl+C` signal 🙁 

This commit works: `a01ffdbe8e3549cbfe93cd9e8aa9e85026e52b7f`
Next commit doesn't: `3996d6fece58659e3ba7119ce9f30d8479d0c354`

## Steps to reproduce

1. `make run`
2. Login
3. Press `Ctrl+C`

It works before login, but not after.

#### Expected behavior

```
^CSIGINT: Interrupted by Ctrl-C.
make: *** [run-macos] Interrupt: 2
```

#### Actual behavior

```
^C
```

And the app continues to work like nothing happened.

### Additional Information

- Status desktop version: `54665ffba6db9becbfb7530c36e0774fa2b6eb5a`
- Operating System: MacOS 14.5 (23F79)

**Comment by igor-sirotin** [comment]
cc @richard-ramos

**Comment by richard-ramos** [comment]
![image](https://github.com/status-im/status-desktop/assets/1106587/1c6e9916-4a0e-4a34-a96a-82520d2bc041)
Interestingly enough, at this point, `StartMessenger` has not been invoked, yet `Ctrl + C` is not working.
This kind of make me think that the problem was introduced by a dependency.

**Comment by igor-sirotin** [comment]
Looks like I'm able to reproduce the same with status-cli.

```bash
cd cmd/status-cli
go run -tags=gowaku_no_rln . simulate
```

This should in theory make it simpler to debug, as it's pure go, no Nim

**Comment by richard-ramos** [comment]
After updating all the direct dependencies manually, I saw that the Ctrl+C issue were introduced by
```
github.com/libp2p/go-libp2p v0.35.0
github.com/libp2p/go-libp2p-pubsub v0.11.0
```
Time to dig deeper!! :thinking:

**Comment by richard-ramos** [comment]
@igor-sirotin look at this!
https://github.com/libp2p/go-libp2p/issues/2785

**Comment by richard-ramos** [comment]
So, looks like it got fixed in https://github.com/uber-go/fx/pull/1198 . I'll try to point to that commit.

**Comment by igor-sirotin** [comment]
@richard-ramos should we try this maybe?
> As a workaround your program can listen for sigint.

**Comment by richard-ramos** [comment]
> I'll try to point to that commit.

Using that commit did not help at all. :)

**Comment by anastasiyaig** [comment]
all my tests are stuck because of this bug, as i am simulating restart of the app literally by killing the process (ctr+c)

**Comment by richard-ramos** [comment]
> all my tests are stuck because of this bug, as i am simulating restart of the app literally by killing the process (ctr+c)

There's a proposed solution in https://github.com/libp2p/go-libp2p/pull/2829 . Once merged I'll update status-go/go-waku to use that libp2p version

**Comment by anastasiyaig** [comment]
i am just wondering if there is any solution for this now, because i am working on setting up tests on windows, and windows does not support `SIGKILL` from psutil module of python which i use now to terminate a process @igor-sirotin @richard-ramos

**Comment by igor-sirotin** [comment]
@anastasiyaig  Looks like it will take awhile. I doubt it will be solved faster then 1 month, just because it's in our sub-dependency. 

In theory it should be possible to apply a workaround in status-desktop by handling the `SIGINT` ourself. 
Since it's blocking you, we can ask @jrainville if it's ok to spend some time on investigation.

**Comment by anastasiyaig** [comment]
@igor-sirotin i am curious as i used to terminate process in my tests with `psutil.SIGTERM` which stopped working because of this bug. so i replaced it with `SIGKILL`, which is not working on windows. No big deal as we are not yet running tests for windows but i am working now to make it reality. So far tests are good on unix, i was just wondering. I might have to find a proper OS agnostic solution for process termination anyways

**Comment by igor-sirotin** [comment]
@anastasiyaig well this bug should be fixed anyway. Using `SIGINT` (or sigterm, or sigkill) IS the "proper OS agnostic solution" 🙂 
Not sure which one exactly to use though. But as I understand, none of them will work now.

**Comment by igor-sirotin** [comment]
Fixed in https://github.com/status-im/status-go/pull/5509#pullrequestreview-2172347541. Already in desktop `master`.
Thanks to @richard-ramos!

![image](https://github.com/user-attachments/assets/e0dcb4b2-dd48-4358-92d5-7b611a9566a1)
