### ISSUE TITLE
Migrate a key pair from Keycard  to Status flow asks for biometrics on Windows

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15123]
# Bug Report

## Description

![image](https://github.com/status-im/status-desktop/assets/82375995/7867c181-5c5c-463f-9e7b-1ad3872adec3)

## Steps to reproduce

Create account with keycard
Migrate this account to Status

#### Expected behavior

No biometrics prompt (i assume we want it on mac only). Also, my windows machine where i am seeing this issue does not have touch id at all

### Additional Information

- Status desktop version: 2.29 rc 10, also master
- Operating System: Windows

**Comment by lukaszso** [comment]
Retested today on my Windows machine (without any biometric capability) and the issue is no longer reproducible.
