### ISSUE TITLE
Community permissions: Setting NFTs based permissions with count > 1 doesn’t work

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15122]
# Bug Report

## Description

A channel with a permission of more than 1 NFT is not considering the correct amount and lets any user who holds at least 1 token in. 

## Steps to reproduce

1. As a Community owner or admin, set up a channel with the following permission: Anyone who holds 2 TOKEN is allowed to View and Post. 
2. Check the "Hide channel from members who don't have permissions to view channel"
3. Airdrop 1 TOKEN to member1, and 2 TOKENs to another member2.

#### Expected behavior
Member2 can see the channel because they met the channel permissions requirements.
Member1 cannot see the channel because they do not met the requirements. They need at least 1 more token.

#### Actual behavior
Member1 can see the channel even though they do not meet the requirements. They should hold at least 1 more token.

Test017 has 1 SIESTA token
<img width="1390" alt="Screenshot 2024-06-10 at 9 18 12 AM" src="https://github.com/status-im/status-desktop/assets/68916150/5a2b8757-b59f-4ed4-bf96-87316938cec9">

Notice the channel permissions are set for users who hold 2 SIESTA tokens
![Screenshot 2024-06-10 at 9 19 04 AM](https://github.com/status-im/status-desktop/assets/68916150/58cef493-34ab-4080-b791-d7a9d3b7fa53)

Test017 can see channel and post. (Message sent June 10)
<img width="1385" alt="Screenshot 2024-06-10 at 9 27 51 AM" src="https://github.com/status-im/status-desktop/assets/68916150/a134f7ed-c421-400f-b2fd-8d0dceede431">

Tested with other user as well, using 2 and 3 required tokens.
3 tokens are required on this channel
![Screenshot 2024-06-10 at 9 58 41 AM](https://github.com/status-im/status-desktop/assets/68916150/226b94e1-9dff-496c-a731-a8cb81ec38ac)
VirDevTest user holds 1 token
<img width="1243" alt="Screenshot 2024-06-10 at 9 57 04 AM" src="https://github.com/status-im/status-desktop/assets/68916150/815cd96b-bb93-4043-bd6f-f33616474815">
How user sees channel
<img width="1245" alt="Screenshot 2024-06-10 at 10 00 58 AM" src="https://github.com/status-im/status-desktop/assets/68916150/e2fd4e3e-8b90-450a-91b5-fa239965920f">

### Additional Information
This issue was discovered while testing https://github.com/status-im/status-desktop/pull/15038 

- Status desktop version: latest master version https://github.com/status-im/status-desktop/commit/54665ffba
- Operating System: Mac OS Sonoma

**Comment by anastasiyaig** [comment]
@jrainville do we want it in rc or 2.30?

**Comment by jrainville** [comment]
> @jrainville do we want it in rc or 2.30?

We already discussed in the meeting, but for posterity, 2.30 is fine as it's not a common use case
