### ISSUE TITLE
bug: bandwidth stats

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#15155]
In the node management tab, the bandwidth stats are no longer being reported. 
Executing `{"method":"settings_nodeConfig"}` I could see that `BandwidthStatsEnabled": false`. 
This value should be `true` on desktop

**Comment by igor-sirotin** [comment]
This is probably something to be added to status-go `LoginRequest`

**Comment by igor-sirotin** [comment]
After all I'd say it was 1 story point 😄

**Comment by jrainville** [comment]
> After all I'd say it was 1 story point 😄

Told ya :joy: 

Everyone always tells me I'm too optimistic smh
