### ISSUE TITLE
Swap - review of scope and flows

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15164]
https://www.notion.so/Swaps-c135dce850964689ae32da6f99165abd
https://www.notion.so/Swap-Story-and-Test-Cases-analysis-a63afde7ec014cb6ab43c52bbaaadc87#177b576e19ca4f1db2a791f50f64535b

**Comment by virginiabalducci** [comment]
Working on analysis of user stories and dev work
https://www.notion.so/Swap-Story-and-Test-Cases-analysis-a63afde7ec014cb6ab43c52bbaaadc87#177b576e19ca4f1db2a791f50f64535b

**Comment by virginiabalducci** [comment]
Test Rail link with the Swap test cases https://ethstatus.testrail.net/index.php?/suites/view/5513&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=62958

**Comment by anastasiyaig** [comment]
we will review this on tuesday jul2 with dario to check the coverage

**Comment by anastasiyaig** [comment]
we need to review the coverage in terms of missing end-to-end scenarios @lukaszso @glitchminer

**Comment by anastasiyaig** [comment]
https://www.notion.so/Desktop-Swap-M1-Release-State-2ba039cab7db42f4a320a512678eb000 should help in this regard
