### ISSUE TITLE
Implement Connect a dApp

### ISSUE THREAD

**Issue by kounkou** [status-im/status-desktop#15173]
### Description

Implement connect a dApp component

### Acceptance criteria

- Popup matches the Figma

### Figma

![Screenshot from 2024-06-13 13-46-06](https://github.com/status-im/status-desktop/assets/2589171/50e7ae60-b08c-43c2-9f92-5a14306506c9)

https://www.figma.com/design/1OYKMzU6KTQHQAqDhojk0r/Status-connector?node-id=2104-4428&t=vWYWD5UO1jTyT5mW-0

**Comment by noeliaSD** [comment]
Hey!! I see this task as a duplication of this epic: https://github.com/status-im/status-desktop/issues/14755

Please @jrainville review! If it's only to change the model data, _block_ it and link with the previously shared epic, please!

**Comment by jrainville** [comment]
This one is literally a duplicate of https://github.com/status-im/status-desktop/issues/14759 so I'll close and link https://github.com/status-im/status-desktop/issues/14759 in the Connector Epic
