### ISSUE TITLE
[Browser Plugin Connector] Trigger for signing a request popup

### ISSUE THREAD

**Issue by kounkou** [status-im/status-desktop#15182]
### Description

Part of Epic https://github.com/status-im/status-desktop/issues/15182

When the user needs to sign a transaction, for instance if a user performs a swap between a token USDC to another ETH for instance, we should trigger the sign popup on the status desktop app.

### Acceptance criteria

- Triggers opening of sign popup cf. https://github.com/status-im/status-desktop/issues/15172
- Fills the data for the signed transaction (ABI, Hex, Fees, etc)

**Comment by MishkaRogachev** [comment]
Waits https://github.com/status-im/status-desktop/issues/15337
