### ISSUE TITLE
Logs in UTC time

### ISSUE THREAD

**Issue by chair28980** [status-im/status-desktop#15198]
Proposing switching logs to use UTC time, this would simplify the debugging process by providing a consistent time reference.

**Comment by richard-ramos** [comment]
:-O i did not realize this task had already been assigned to @igor-sirotin 
Sorry!

**Comment by chair28980** [comment]
Fixed by https://github.com/status-im/go-ethereum/pull/108

**Comment by igor-sirotin** [comment]
I looked at the logs of the app we write from Nim. Local time is used there, not UTC.

But it seems that we don't really have control over this. `nim-chronicles` provide option to change the format of the timestamps (RFC 3339, Unix, None):
https://github.com/status-im/nim-chronicles/blob/33761a5f77610d3f87f774244490eae43a9ac5a1/README.md?plain=1#L376-L397

But it's always local time, this can be seen with usage of `now()` here:
https://github.com/status-im/nim-chronicles/blob/ccbb7566d1a06bfc1ec42dd8da74a47f1d3b3f4b/chronicles/log_output.nim#L425-L427

I don't think it's very important to have UTC in application logs, so far it was never a problem. It will be our of sync now with `geth.log`, but I guess we can live with that?

**Comment by fryorcraken** [comment]
I'd suggest UTC across all logs as we need to be able to correlate app events to Waku events. More intense debugging means it's a problem now.

**Comment by igor-sirotin** [comment]
@jrainville should we mark this as blocked or smth? 
I didn't investigate, but don't see a simple workaround until https://github.com/status-im/nim-chronicles/issues/151 is implemented.

**Comment by chaitanyaprem** [comment]
nwaku logs time in UTC, so maybe we can check with them how it is done. iirc chronicles-logging only must be used there. 
cc @Ivansete-status , maybe you can help how it is done using `nim-chronicles`

**Comment by igor-sirotin** [comment]
@Ivansete-status would be great if you share how it's done in `nwaku`, if it is like that indeed !

**Comment by Ivansete-status** [comment]
@chaitanyaprem , @igor-sirotin - the `nwaku` is not printing in UTC. Instead, it prints from the local time. What is happening is that the fleets' hosts have the local time set to UTC and therefore, `nwaku` gets that time zone.

I've submitted the following PR in `nim-chronicles` to allow printing in UTC regardless the local zone: https://github.com/status-im/nim-chronicles/pull/152

To use it, the following compilation flag should be added: `-d:chronicles_timestamps="UnixTimeReadable"`

**Comment by igor-sirotin** [comment]
> I've submitted the following PR in nim-chronicles

Thank you!

**Comment by Ivansete-status** [comment]
Hello @igor-sirotin , @chaitanyaprem - the time can be expressed now in `UTC` from `nim-chronicles`. Please update to the latest. Then, to enable the `UTC` time, the following compilation setting should be used: `-d:  chronicles_timestamps = "RfcUtcTime"`.
