### ISSUE TITLE
[Browser Plugin Connector] Share Status desktop running status to client

### ISSUE THREAD

**Issue by kounkou** [status-im/status-desktop#15197]
### Description

The status desktop application should be able to send its status to clients by answering through API call or by sending the status without prior API calls.

While writing this ticket, I wonder what status are we referring to, and this made me ask the question : what do we define by `Status desktop is running` ? Since the status desktop could be running and `offline`. In that case, the connection to the browser plugin  being on a local network, the notion of being online might prevail over `Status desktop running`

### Acceptance criteria

- Connector should be able to detect Status desktop states
- Connector should be able to respond to Status desktop state requests
- Connector should send the state of Status desktop to clients without a prior request

**Comment by jrainville** [comment]
Should we close this one now @MishkaRogachev @kounkou ?

**Comment by MishkaRogachev** [comment]
> Should we close this one now @MishkaRogachev @kounkou ?

Yes, for now it can be closed
