### ISSUE TITLE
Discuss and decide if Token Master should keep/restore requests to join with revealed accounts of a community members in/from backup

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#15196]
### Description

Token Master does not store other members' requests to join and revealed accounts in the backup.
If he restores his account by a seed phrase, he will lose this data and not be able to do airdrop, as an example
We will prepare the fix to request the control node resend this data on backup restore, but what if the control node is offline?
We need to decide if we want to store community members' requests to join with revealed accounts or request it from the control node during handling backup will be ok

**Comment by jrainville** [comment]
Requesting from the control node is fine. Closing.
