### ISSUE TITLE
[UI - Wallet Stability]  Rename `NetworkSelector` component to `RouterPanel` and analyse if some improvements needed

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15209]
[Design](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&node-id=9707-107649&t=AZaOmLOlFrWAfvL5-1)

[Design 2](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&node-id=9707-111554&t=AZaOmLOlFrWAfvL5-1)

![Screenshot 2024-06-17 at 15 30 47](https://github.com/status-im/status-desktop/assets/97019400/87b7dd2d-15e2-484a-8481-096e54b42b92)

![Screenshot 2024-06-17 at 15 30 29](https://github.com/status-im/status-desktop/assets/97019400/06e91cb7-6bc1-4ae4-8840-2cb10d22316b)

- Rename `NetworkSelector` component to `RouterPanel` (or more appropriate name).
- Quick analysis if there are some dependences or easy api cleanups we can do now.
- Maybe create some subtasks for next improvements setps.

**Notes:**
- There will be a new design of the `Transactions Card` in the next milestones so probably it does'n make sense to put a lot of effort now
- There will be the new router V2 that probably will need some additional information to be displayed but also effort for the next milestone.

**Comment by noeliaSD** [comment]
There's an improvement to add for this milestone for the **fees panel** inside the `RouterPanel` component. Here the task: https://github.com/status-im/status-desktop/issues/14208

**Comment by noeliaSD** [comment]
Take into account his comment here: https://github.com/status-im/status-desktop/issues/15216#issuecomment-2202911932

**Comment by noeliaSD** [comment]
Created _draft PR_ with the major part of the refactor but since there's no capacity to work on the **qml tests** for each small component neither adding them to **storybook**, it doesn't add a lot of value to the release **2.30**, without the small components testing. 

It's moved to next milestone. During stability phase we will work on components testing and then integrating the already done work into the app.

**Comment by noeliaSD** [comment]
@micieslak there's a _draft pr_ created and missing things are:

- Add the following components to _Storybook_ and create **qml tests** for each one:
  - NetworkCardsComponent
  - NetworksSimpleRoutingView
  - NetworksAdvancedCustomRoutingView
  - FeesView

**Comment by alexjba** [comment]
The SendModal will go through a re-design
