### ISSUE TITLE
[UI - Wallet Stability] Create new `SQ/StatusAmountInputPanel` for SendModal / BridgeModal / SwapModal

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15207]
[Design](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&node-id=9019-88679&t=AZaOmLOlFrWAfvL5-1)

![Screenshot 2024-06-17 at 14 50 45](https://github.com/status-im/status-desktop/assets/97019400/d201a241-7aa9-4654-a97e-bf86fa26351f)

![Screenshot 2024-06-17 at 14 50 37](https://github.com/status-im/status-desktop/assets/97019400/d1b140e6-c575-47d3-aa28-02d7b023e272)

- Replacement for `AmountToSend` and `AmountToReceive` (maybe we can do the replacement here or keep the integration for task https://github.com/status-im/status-desktop/issues/15215)
- Generic SQ component (some basic api, but needs design check / analysis):
  - Property to allow being aligned to the left or to the right  
  - Title
  - Editable input but can be also readonly
  - Subtitle
  - Status: ok / [failure](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&node-id=9707-106361&t=3Ip0TLH1dJ4RejL4-1) 
- Storybook page without warnings
- No stores dependencies
- Create qml tests for the component

**Comment by caybro** [comment]
Oh that's a new one! I like it, would definitely be a better replacement for the SwapModal/SwapInputPanel component

**Comment by caybro** [comment]
Just a reminder, this is also used in SwapModal like this: AmountToSend -> SwapInputPanel -> SwapModal

**Comment by noeliaSD** [comment]
As decided in our sync, maybe better to create a separate and new component, only apply this new component to **send** and **bridge** AND create a separate task to do the integration of the new component to **swap** for the next milestone.

**Comment by Khushboo-dev-cpp** [comment]
@micieslak as discussed, this is also something swap needs as we currently use double within the current AmountToSendInput and it causes loss of precision, As I understand from @noeliaSD the work done here will not be used in swap but a different issue will be created for it. Would be great if we can create a task for it so that its not forgotten :)

**Comment by caybro** [comment]
> @micieslak as discussed, this is also something swap needs as we currently use double within the current AmountToSendInput and it causes loss of precision, As I understand from @noeliaSD the work done here will not be used in swap but a different issue will be created for it. Would be great if we can create a task for it so that its not forgotten :)

We don't really use a double here (but the `rawValue` based on the `Big` number) in SwapModal

**Comment by caybro** [comment]
> > > @micieslak as discussed, this is also something swap needs as we currently use double within the current AmountToSendInput and it causes loss of precision, As I understand from @noeliaSD the work done here will not be used in swap but a different issue will be created for it. Would be great if we can create a task for it so that its not forgotten :)
> > 
> > 
> > We don't really use a double here (but the `rawValue` based on the `Big` number) in SwapModal
> 
> https://github.com/status-im/status-desktop/blob/c8744cf3bf53d4fbbc7f65ae1fbe281281bca612/ui/imports/shared/popups/send/views/AmountToSend.qml#L62

Yes, but in SwapModal we use the "text" for display, and `rawValue` when sending the transaction right?

But general yeah, there should be ideally no floats/doubles around in that code

**Comment by Khushboo-dev-cpp** [comment]
> > > > @micieslak as discussed, this is also something swap needs as we currently use double within the current AmountToSendInput and it causes loss of precision, As I understand from @noeliaSD the work done here will not be used in swap but a different issue will be created for it. Would be great if we can create a task for it so that its not forgotten :)
> > > 
> > > 
> > > We don't really use a double here (but the `rawValue` based on the `Big` number) in SwapModal
> > 
> > 
> > https://github.com/status-im/status-desktop/blob/c8744cf3bf53d4fbbc7f65ae1fbe281281bca612/ui/imports/shared/popups/send/views/AmountToSend.qml#L62
> 
> Yes, but in SwapModal we use the "text" for display, and `rawValue` when sending the transaction right?
> 
> But general yeah, there should be ideally no floats/doubles around in that code

The thing is that these floats are used to calculate the rawValue in the end and thats whats causing the issue withe losing precision.
