### ISSUE TITLE
[UI - Wallet Stability]  Create `BridgeModal` from `SendModal` as a new and isolated component

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15216]
- New `StatusAmountIputPanel` built on #15207
- New combo for selecting tokens build from #14716 and #15121
- The renamed component `RouterPanel` reworked on #15209
- The renamed `TransactionModalFooter` reworked on #15212
- No references to **send** feature
- **No** references to **global network** selections (only references to _testnet_)

Some pseudo-code:

```
StatusDialog {
    id: root

    property var selectedAccount
    property var selectedToken
    property var selectedAmount
    property var bestRoutes

    property models needed

    header: AccountSelector { ... }

    ColumnLayout {
        RowLayout {
            Bridge Text
            +
            Holdings selector
            +
            Max button component
        }
        StatusAmountInputPanel 1 (bridge) {}
        RouterPanel {}
    }

    footer: TransactionModalFooter { ... }
}

```

It should implement the new design flow defined in [here](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&node-id=23970-465372&t=VyetOnjSegfO0pec-1) (bridge will also follow it):

![Screenshot 2024-06-17 at 16 44 06](https://github.com/status-im/status-desktop/assets/97019400/808350d8-8efd-408f-af38-26564ef74e8b)

Note: [Bridge design reference](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&node-id=2829-147366)

**Comment by noeliaSD** [comment]
@caybro please, sync with @micieslak and me before starting! There is a new design flow to have better consistency with the `SendModal` but probably the description is not updated!

[New Figma](https://www.figma.com/design/qiooiIE9bTgdBipKshS5uu/Bridge---Milestone-1?node-id=1166-171137&t=I0uan83eU3K1tesG-1)

**Comment by anastasiyaig** [comment]
lets also aim to avoid this confusion what is selected and what is not (current state on the video below)

https://github.com/status-im/status-desktop/assets/82375995/dc30d24e-074c-4199-8815-eaa0501ce302

**Comment by alexjba** [comment]
The SendModal/Bridge will go through a re-design
