### ISSUE TITLE
[UI - Wallet Stability] Rename `SendModalFooter` to `TransactionModalFooter` and remove particular code for send modal

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15212]
[Design](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9707-107649&t=AZaOmLOlFrWAfvL5-0)

![Screenshot 2024-06-17 at 15 49 45](https://github.com/status-im/status-desktop/assets/97019400/9f0cdd75-edd9-4355-9360-e8bda958e61b)

- Rename `SendModalFooter` to `TransactionModalFooter`. It will be used by `SendModal` but also but `BridgeModal` ~~and probably by `SwapModal`~~.
- Rename the following properties inside the component:
  - nextButton.text: qsTr("Send") --> qsTr("Next")
  - objectName: "sendModalFooterSendButton"  --> "transactionModalFooterButton"
  - Expose authentication method icon : `nextButton.icon.name` as a property

**Comment by caybro** [comment]
Codewise this is a good idea but design wise, what are we getting? They are simply not the same:

Send:
![image](https://github.com/status-im/status-desktop/assets/5377645/293bab18-e0d3-4451-9e35-e440a0f0b5f5)

Bridge:
![image](https://github.com/status-im/status-desktop/assets/5377645/c93cf7ac-b1d7-4bb7-ab7f-904420fbb51b)

SwapModal:
![image](https://github.com/status-im/status-desktop/assets/5377645/1a856148-8266-43b2-85c7-e705ed22902b)

SwapSign:
![image](https://github.com/status-im/status-desktop/assets/5377645/4317d1af-be06-4982-8f82-30b651087549)

SwapApprove:
![image](https://github.com/status-im/status-desktop/assets/5377645/2b31ae1a-d3e0-4926-b7cd-2546a34f7f57)

Each and every of the variations is different :)

**Comment by noeliaSD** [comment]
I was just considering **Send** and **Bridge** usecases here. If you see it's possible to share something with **swap**, go ahead, otherwise, just _Send_ and _Bridge_! Thanks for sharing your thoughts!
