### ISSUE TITLE
Check on why owner token test is not scrolling the screen

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15262]
branch https://github.com/status-im/status-desktop/pull/15099
run https://ci.status.im/job/status-desktop/job/e2e/job/manual/2133/

looks like test is not scrolling down

![Image](https://github.com/status-im/status-desktop/assets/82375995/51830a55-055c-4e12-8a63-02008960a0d5)

when i opened this screen manually . i saw that fees are not rendered

![Image](https://github.com/status-im/status-desktop/assets/82375995/9bd0def3-0dd5-49c3-87dc-bb05dd994311)

**Comment by Valentina1133** [comment]
I fixed it and merged to that branch https://github.com/status-im/status-desktop/pull/15099. Hopefully there will not be more issues with this test
