### ISSUE TITLE
[SwapModal] Fix flaky tests and remove the `skip` flag

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#15272]
#### Description

The purpose of this task is to fix `test_modal_swap_proposal_setup` and `test_floating_header_list_items` and remove the skip flag.

It seems like these tests depend on some initialisation order because it's randomly failing.

              @Khushboo-dev-cpp I'll skip 2 tests here because it's randomly failing on master. Do you want me to add a task for them, or should I mention them in an existing one?

_Originally posted by @alexjba in https://github.com/status-im/status-desktop/pull/15099#discussion_r1647050544_

**Comment by caybro** [comment]
Yeah same prob for me, I had to disable one if them too

**Comment by Khushboo-dev-cpp** [comment]
@alexjba please take this up when you have time to fix on macos?

**Comment by alexjba** [comment]
> @alexjba please take this up when you have time to fix on macos?

Started looking on this. There are 2 flaky tests on my end:
`test_floating_header_list_items` - failing on subtitle. Looks like the first item has the `hovered` state active after clicking the Accounts selector. Maybe a mouseMove would fix it
`test_modal_swap_proposal_setup` - This one fails randomly on 2 checks for `receivePanel.value`. It's 0 and the receiver looks like it's stuck on loading state. No idea yet what could be wrong here

**Comment by caybro** [comment]
`test_modal_swap_proposal_setup` - This one fails randomly on 2 checks for `receivePanel.value`. It's 0 and the receiver looks like it's stuck on loading state. No idea yet what could be wrong here

Same here... I had to disable it locally; first thing is trying to get rid of the hardcoded `wait()` calls

**Comment by alexjba** [comment]
> `test_modal_swap_proposal_setup` - This one fails randomly on 2 checks for `receivePanel.value`. It's 0 and the receiver looks like it's stuck on loading state. No idea yet what could be wrong here

Added some logs there with a `wait` to catch it when it fails and now it doesn't fail anymore. Looks like a timing issue. Maybe the `loading state` is not always completed when we're checking the `value`. I'll see if something like tryCompare would work 🤔

**Comment by caybro** [comment]
> > `test_modal_swap_proposal_setup` - This one fails randomly on 2 checks for `receivePanel.value`. It's 0 and the receiver looks like it's stuck on loading state. No idea yet what could be wrong here
> 
> Added some logs there with a `wait` to catch it when it fails and now it doesn't fail anymore. Looks like a timing issue. Maybe the `loading state` is not always completed when we're checking the `value`. I'll see if something like tryCompare would work 🤔

Just tried to fix it locally... no dice; even with increasing those `wait()` values :/
