### ISSUE TITLE
`SwapModal` contents doesn't scroll

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15276]
The whole contents area is not scrollable:

![image](https://github.com/status-im/status-desktop/assets/5377645/7b410c7f-0017-40a1-9ff1-7bcc716545a3)

Esp. problematic with the slippage selector expanded

**Comment by caybro** [comment]
Maybe makes sense for @alexjba to work on this together with https://github.com/status-im/status-desktop/issues/15275 ? Makes sense as there will be a substantial change wrt to the contentItem

**Comment by alexjba** [comment]
I think it can stay on its own. https://github.com/status-im/status-desktop/issues/15275 needed only small localised changes
