### ISSUE TITLE
`TokenSelector` doesn't show list of all known assets

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15278]
The `TokenSelector` should list all the known assets under the "Popular assets" section at the bottom, with no balances:

![image](https://github.com/status-im/status-desktop/assets/5377645/b4c438b7-1ae6-4402-9d56-2cbdb3f1c0c9)

Design:
![image](https://github.com/status-im/status-desktop/assets/5377645/03f23eb8-4f9f-4de8-aa07-3b3eb68e0f71)

**Comment by micieslak** [comment]
@caybro Isn't the popular assets section relevant only to the receive section? What's the sense of choosing in "pay" section something that we don't own?

**Comment by caybro** [comment]
> @caybro Isn't the popular assets section relevant only to the receive section? What's the sense of choosing in "pay" section something that we don't own?

Yeah good point, we'll have to make this distinction in Swap; I'll fix/amend the PR

**Comment by caybro** [comment]
> I also have another doubt here.. Do we also need the **community assets**? For `Send Modal` yes, and probably a specific category / section for them. Not sure about _swap_ @dlipicar @Khushboo-dev-cpp

Yeah, in case of SendModal, we'll need it and the current view/adaptor already has support for optionally showing them

**Comment by dlipicar** [comment]
> @caybro Isn't the popular assets section relevant only to the receive section? What's the sense of choosing in "pay" section something that we don't own?

@micieslak the original design was like that (showing only assets with balance >0 for the Pay selector), but it was changed a couple of days ago (https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3802-77911&t=xBodPGGHwoAggJlC-0) for a couple of reasons:
- Simplicity
- Using the Swap modal as a "quote" machine to get conversion rates
- More scenarios where we show the "Buy" button
- Even without that, you can still end up with assets with 0 balance selected on the Pay side by switching the Network or using the "Switch Pay/Receive parameters" button

So yeah, we decided we would should the same lists on both sides.

**Comment by dlipicar** [comment]
> I also have another doubt here.. Do we also need the **community assets**? For `Send Modal` yes, and probably a specific category / section for them. Not sure about _swap_ @dlipicar @Khushboo-dev-cpp

Asked Ben about this, he said we should include them. I'm guessing in most cases there won't be a valid Swap proposal for those, but there's nothing preventing someone from setting up a Swap pool in Uniswap (or some other DEX) for their community asset, which would make Swapping possible.

**Comment by caybro** [comment]
> > I also have another doubt here.. Do we also need the **community assets**? For `Send Modal` yes, and probably a specific category / section for them. Not sure about _swap_ @dlipicar @Khushboo-dev-cpp
> 
> Asked Ben about this a while ago, he said we should include them. I'm guessing in most cases there won't be a valid Swap proposal for those, but there's nothing preventing someone from setting up a Swap pool in Uniswap (or some other DEX) for their community asset, which would make Swapping possible. There doesn't seem to be a special section for those in the list though.

OK, we can potentially show those as well :)
