### ISSUE TITLE
Application crashes when adding account (not constantly)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15286]
# Bug Report

###

Application segfaults when adding account (mostly with autotests)

## Steps to reproduce

none as i cant reproduce manually 

#### Actual behavior

```
Critical: Error parsing my revealed addresses SyntaxError: JSON.parse: Parse error (qrc:/app/AppLayouts/stores/RootStore.qml:54, expression for myRevealedAddressesForCurrentCommunity)
```

### Additional Information

- Status desktop version: recent master
- Operating System: linux at least

I saw this error as well with @micieslak but maybe it is not that exact error

**Comment by caybro** [comment]
@anastasiyaig is this app reproducible in the app, or just in tests?

**Comment by anastasiyaig** [comment]
in tests, to my knowledge

**Comment by jrainville** [comment]
Is it possible that @alexjba 's refactor fixed this? It was opened 3 weeks ago and the stack talks about `JSON.parse`, but in theory, we should be using JSOn for contacts anymore?

@anastasiyaig do you know if you've seen this crash in tests lately?

**Comment by anastasiyaig** [comment]
i tried to reproduce it lately and seems i cant. at least not the way it was reproducible before

**Comment by alexjba** [comment]
> Is it possible that @alexjba 's refactor fixed this? It was opened 3 weeks ago and the stack talks about `JSON.parse`, but in theory, we should be using JSOn for contacts anymore?
> 
> @anastasiyaig do you know if you've seen this crash in tests lately?

Sorry for the late reply! The refactor on contact details doesn't touch this part. We only have one usage for the refactored contact details with a plan to extend it in the future stabilization phases.



> i tried to reproduce it lately and seems i cant. at least not the way it was reproducible before

It's still crashing?

**Comment by Seitseman** [comment]
After running the test that crashed the app locally on windows more than 20 times, crash has never occurred. @anastasiyaig , could you please reenable that test?

**Comment by anastasiyaig** [comment]
@Seitseman yes, i will do that today :)
