### ISSUE TITLE
The application crashes when generating status user profile link preview

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#15297]
# Bug Report
## Steps to reproduce

Paste link to status user profile to chat (we use this one for autotest - https://status.app/u/iwWACgoKCHNxdWlzaGVyAw==#zQ3shvMPZSyaUbjBjaNpNP1bPGsGpQDp59dZ4Gmz7UEy5o791)

#### Expected behavior

Link preview is generated and shown

#### Actual behavior

Link is generating but at some point the app crashes

### Additional Information

- Status desktop version: the latest master build
- Operating System: Mac OS Ventura 13.5

**Comment by jrainville** [comment]
I can confirm the crash. Setting high priot
