### ISSUE TITLE
Link unfurls do not send/show when sending them with images

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15290]
# Bug Report

## Description

If you send a message with both image(s) and link(s), the links will not show as unfurled.

I'm fairly sure it's because we just do not send the full unfurl data when sending images. 

During normal messages, we send this
https://github.com/status-im/status-desktop/blob/8ca51c34cc64b242a7f5fac4400efa7e2542c960/src/backend/chat.nim#L59-L60

but for images, only this
https://github.com/status-im/status-desktop/blob/8ca51c34cc64b242a7f5fac4400efa7e2542c960/src/backend/chat.nim#L87

## Steps to reproduce

0. Go into a channel
1. Write some text and paste a link
2. Accept the unfurl
3. Add an image
4. Send
See that the image shows, but not the links

#### Expected behavior

Both links and images show. All side by side if possible

#### Actual behavior

Only images show

### Additional Information

- Status desktop version: master `033bf999743a11f9f2ac3e14f641d1ba6fb868db`
- Operating System: Ubuntu 22

**Comment by igor-sirotin** [comment]
oops, it's a pity. It was working, but I guess I didn't change the properties when renaming `linkPreviews` to `standardLinkPreviews`
