### ISSUE TITLE
Can't add account when being offline (activity check is required to add account)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15299]
### Description

Add account button is disabled when fetching activity is not possible, and it seems to be required

![Screenshot from 2024-06-21 14-37-24](https://github.com/status-im/status-desktop/assets/82375995/97cb89c9-511e-4125-a361-268e48a2d85e)

![Screenshot from 2024-06-21 14-41-33](https://github.com/status-im/status-desktop/assets/82375995/4c4b5721-7627-42c6-827a-9c67fb28afbc)

**Comment by anastasiyaig** [comment]
@alaibe do we really need to wait for fetching activity when adding account to wallet?

**Comment by alaibe** [comment]
No we don't i already fixed this issue in another life/design ;)

**Comment by anastasiyaig** [comment]
@saledjenic issue about activity check being required to add new account
