### ISSUE TITLE
Invalid Collectible Ownership TxTimestamp value is wrong

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#15312]
### Description

We expect the TxTimestamp that comes from status-go to be -1 for entries we haven linked to a Tx yet. However, we're getting a high int. Figure out where that problem is.

```
1711532826
txTimestamp
1711532826
txTimestamp
1711532826
txTimestamp
1711532826
txTimestamp
1711532826
txTimestamp
9223372036854775807
txTimestamp
9223372036854775807
txTimestamp
9223372036854775807
txTimestamp
9223372036854775807
```

**Comment by caybro** [comment]
Wrong signed vs. unsigned int handling somewhere is a usual cause for these :)

**Comment by dlipicar** [comment]
Got the spec wrong, the backend is supposed to return maxInt64 when no Tx is matched. This needs to be handled client-side.
