### ISSUE TITLE
Identicon ring is missing on the Profile view

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15314]
# Bug Report

## Description

Identicon ring is missing on the Profile view

## Steps to reproduce

Just create an account
Open profile from online identifier

#### Expected behavior

identicon ring is there

#### Actual behavior

<img width="1312" alt="Screenshot 2024-06-24 at 17 11 42" src="https://github.com/status-im/status-desktop/assets/82375995/d6cf7083-b859-4e6f-8105-bc15a5103a48">

### Additional Information

- Status desktop version: commit afde83651724a555626b5d9a3d582918de6c3d59
- Operating System: MacOS Sonoma 14

**Comment by caybro** [comment]
CC @alexjba related to recent changes?
