### ISSUE TITLE
Fix: scroll "stutter"

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1532]
> When scrolling through lots of messages, there is a very noticeable "stutter", and I'm concerned that this is due to the images being downloaded and possibly the logic of LinksMessage (which access appSettings). We may need to find a way to offload the downloading of images to a new thread, or only download images once scrolling has stopped for a period (like 100ms).

Please see the "Notes" section of the PR description https://github.com/status-im/nim-status-client/pull/1528#issue-539079152 for more information.

**Comment by iurimatias** [comment]
this was caused by the images and unfurling and has been fixed recently
