### ISSUE TITLE
Use optimized endpoint to get communities with images

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15340]
### Description

Split from https://github.com/status-im/status-desktop/issues/13061

The mobile team did the hard work of making the community images (banner, logo, icons) in this PR https://github.com/status-im/status-go/pull/5336

This ticket is to update desktop to use those as well. We'll be also able to remove the old endpoints after.

There is a mobile PR here for inspiration: https://github.com/status-im/status-mobile/pull/20481

### Acceptance criteria

- Community images still show as usual (banner, logo, thumbnail)
- It should be faster to load but hard to measure

**Comment by friofry** [comment]
I'm using the same ticket to remove old code
(https://github.com/status-im/status-go/pull/5336#discussion_r1639029431)
