### ISSUE TITLE
Retest keycard

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15355]
- retest known flows for keycard (mac and win)
- identify opened and valid issues for windows 
- onboarding flows and specific keycard flows (ideally as much as possible)
- imporve the coverage in test rail if needed / relevant

**Comment by lukaszso** [comment]
Test runs:
- [macOS](https://ethstatus.testrail.net/index.php?/runs/view/16981&group_by=cases:section_id&group_order=asc)
- [Windows](https://ethstatus.testrail.net/index.php?/runs/view/16980&group_by=cases:section_id&group_order=asc)
