### ISSUE TITLE
Not possible to mint community tokens with a secondary wallet account

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15382]
# Bug Report

## Description

Main account works:
![image](https://github.com/status-im/status-desktop/assets/11926403/5b925ea5-67b4-48da-966e-b368c4507b6f)

Secondary account shows `Unknown error`:
![image](https://github.com/status-im/status-desktop/assets/11926403/4865abfe-ab02-49cc-be93-b12a9f249d07)

Both accounts have ETH:
![image](https://github.com/status-im/status-desktop/assets/11926403/abf5e3d8-ad84-4de6-af51-0269e2c2f583)

The error in the logs is 
```
ERR 2024-06-28 13:13:14.014-04:00 error doing rpc request                    topics="rpc" tid=198663 file=core.nim:39 methodName=communitytokens_estimateMintTokens exception="\nstatus-go error [methodName:communitytokens_estimateMintTokens, code:3, message:execution reverted ]\n"
```

I think the issue is that the wallet address that is allowed to mint is inside the contract.

So in theory, we cannot use any other account.  I think then we should restrict the selector to only the account that is allowed to mint. And show a tooltip or a message explaining why using an other account doesn't work.

I think also if a user has multiple TokenMaster tokens, in multiple wallet accounts, they can be all used. So the optimal solution would take that into account, but we can do that in multiple parts.

## Steps to reproduce

0. Have a community with community tokens
1. Try to airdrop the token to someone
2. Select your secondary account (or the account that is the not the one that was used to mint the owner token)
-> Unknown error

#### Expected behavior

Either it's not possible to select an account that is not allowed to mint, or the error message is clear when trying to use the account taht it's because that address is not associated with the minting.

Either way, a clear message and UX is shown instead of "unknwon error" 

#### Actual behavior

"unknown error"

### Additional Information

- Status desktop version: 2.29 and master (`5c349d1938d5b3831d83994f73ced92d903b3fbe`)

**Comment by endulab** [comment]
Yes, it's because another wallet address does not hold owner or master token.
Some explanation in the UI is a very good idea.
