### ISSUE TITLE
Beta warning on the desktop app

### ISSUE THREAD

**Issue by nebolax** [status-im/status-desktop#15431]
# Bug Report

## Description

I am seeing a Beta warning every time I open the desktop app on my mac even though I have already signed up.
<img width="654" alt="image" src="https://github.com/status-im/status-desktop/assets/63492346/3c683e3c-456d-4589-bf03-85703f5eec10">

#### Expected behavior

I think this warning should not be shown on every app open 🤔 

### Additional Information

- Status desktop version: 2.29.0
- Operating System: mac os sonoma on mac air m1

**Comment by jrainville** [comment]
This was a design decision to make sure people never forget. Once we do the full release, we will remove it.
