### ISSUE TITLE
Integrate Sign and Approve modals into SwapModal

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#15443]
We need to integrate sign modal created here into swap https://github.com/status-im/status-desktop/pull/15410, as well as approve, created here: https://github.com/status-im/status-desktop/pull/15460

**Comment by noeliaSD** [comment]
Ideally it shold be covered by https://github.com/status-im/status-desktop/issues/14785

**Comment by caybro** [comment]
> Ideally it shold be covered by #14785. cc: @caybro

I'd rather keep it under a separate task
