### ISSUE TITLE
SwapModal: refresh currency price as well when fetching proposal

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#15454]
Design https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=4167-91099&m=dev

The requirements in design say that currency price should also be updated whenever auto-refresh occurs but we do not have an api or a way to do that directly right now, we rely on market values updated which occurs every 10 ins currently. 

We should evaluate an efficient way to do this as on go side we already refresh currency prices when fetching new route but that is not used to show updated values on the UI yet.

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

**Comment by dlipicar** [comment]
@Khushboo-dev-cpp see what SendModal does. Check if price cache gets refreshed.
