### ISSUE TITLE
Missing color and ring on the profile icon in the bottom left corner

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15479]
# Bug Report

## Description

![image](https://github.com/status-im/status-desktop/assets/11926403/77880aff-dc42-4cfe-a998-589392903196)

## Steps to reproduce

1. Open the app

#### Expected behavior

The icon has the same color as the popup and the ring 

#### Actual behavior

Color is black

### Additional Information

- Status desktop version: master `06184e4d955269c8cfa5163a07d0bf1bb8d5dbd3`
- Operating System: Ubuntu 22

**Comment by jrainville** [comment]
@noeliaSD this seems like a recent regression

**Comment by caybro** [comment]
This looks like some of the recent contact info changes @alexjba ?

**Comment by alexjba** [comment]
> This looks like some of the recent contact info changes @alexjba ?

Probably not. We only have the new contact info in the profile view. But let's see 😄
