### ISSUE TITLE
Implement design for the Opt-in metric checkbox

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15490]
### Description

 Follow up of https://github.com/status-im/status-desktop/issues/15446

Onboarding:
https://www.figma.com/design/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=40573-92941&t=1aCmIYrch9JqLCIa-0

Settings:
https://www.figma.com/design/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=24721-8826&t=J9tvSFrAc93owo5j-0

### Acceptance Criteria

- The backend is integrated with the UI
- The UI is implemented as per designs (needs a new settings page)

**Comment by endulab** [comment]
Done in #15628
