### ISSUE TITLE
Rework scroll methods

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15498]
### Description

1. scroll can lead to infinite loop
2. scroll is not working on smaller screens (cant scroll certain screens on certain configurations). Examples:

- tests can't scroll down to Sign out and Quit button on Mac 13 inch screen
- tests can't scroll Backup seed phrase modal on Windows 11 with 15.6 inch screen

This task should implement a suggestion to use this methods within StatusScrollView:

```
    function scrollHome() {
        flickable.contentY = 0
    }

    function scrollEnd() {
        flickable.contentY = flickable.contentHeight - flickable.height
    }

    function scrollPageUp() {
        root.ScrollBar.vertical.decrease()
    }

    function scrollPageDown() {
        root.ScrollBar.vertical.increase()
    }
```

**Comment by anastasiyaig** [comment]
note, that this wont help ensuring that scrolling with mouse will actually work

**Comment by anastasiyaig** [comment]
other thing is to implement send keys (Arrow Up and Arrow Down) @Valentina1133

**Comment by Valentina1133** [comment]
I also want to try this one: sendEvent("QWheelEvent")
