### ISSUE TITLE
[UI - Wallet Stability] SendModal - integrate new token selector for assets/collectibles, remove tokens list

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15512]
## Description

The new token selector is a replacement for old selector (which doesn't provide proper grouping for collectibles) and also tokens list view which so far was a first view of SendModal when token wasn't pre-selected.

It's continuation of https://github.com/status-im/status-desktop/issues/15121

**Comment by caybro** [comment]
Is the title correct? SwapModal, collectibles?
