### ISSUE TITLE
Import community flow is broken

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#15526]
# Bug Report

`zQ3shn2Y2MFo81UjK4SCu7AqmL7eBoFqBNgyDHX7R1KfBrfQq`

User story:
1. I have a link to the community (or it's public key)
2. I want to spectate this community

    There're only 2 ways of doing this: 
    - click the link in chat - not available for me, I don't have any chats yet
    - import community - let's try

3. I go to `Communties` -> `Import Community` and paste the key/link

<img width="1312" alt="Screenshot 2024-07-10 at 17 23 12" src="https://github.com/status-im/status-desktop/assets/25482501/4cdb6ba5-7356-4b29-9105-2326b726f1cb">

4. I click `Import` and get this:

<img width="1312" alt="Screenshot 2024-07-10 at 17 23 14" src="https://github.com/status-im/status-desktop/assets/25482501/e6f74a6e-4c9e-4194-9152-58132c54c043">

Nothing else is happening after 🙁 

### Expected behavior

After clicking import, community is spectated. Just as if I clicked such link in a chat.

### Actual behavior

I get a "Cancel Membership Request" popup.

**Comment by igor-sirotin** [comment]
@jrainville @noeliaSD could be important for 2.30?

**Comment by jrainville** [comment]
@noeliaSD do you have someone that would have time? I think I could find time to do it if not

**Comment by noeliaSD** [comment]
@alexjba could have time next week. **Alex**, let us know if not!

**Comment by caybro** [comment]
Indeed I can (sort of) reproduce but when I do, after the "Request to join..." popup, I always immediately get this crash:

```
DBG 2024-07-11 14:40:50.293+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=48216 file=core.nim:27 rpc_method=wakuext_checkPermissionsToJoinCommunity
DBG 2024-07-11 14:40:50.293+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=48223 file=threadpool.nim:56 messageType=AsyncCheckAllChannelsPermissionsTaskArg:ObjectType threadid=48223 task="{\"$type\":\"AsyncCheckAllChannelsPermissionsTaskArg:ObjectType\",\"communityId\":\"0x036dc0bcb627d55aa693096b447190eab3c5c57c117446ea44d93e97be0fe6ef46\",\"addresses\":[],\"vptr\":742936048,\"slot\":\"onAsyncCheckAllChannelsPermissionsDone\"}"
DBG 2024-07-11 14:40:50.294+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=48223 file=core.nim:27 rpc_method=wakuext_checkAllCommunityChannelsPermissions
DBG 2024-07-11 14:40:55.812+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=48197 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
panic: runtime error: slice bounds out of range [5177:5000]

goroutine 638 [running]:
github.com/status-im/status-go/telemetry.(*Client).pushTelemetryRequest(0x1c0073c3fa8?, {0x1c0228a6000?, 0x6bc?, 0x0?})
	/home/ltinkl/git/status/status-desktop/vendor/status-go/telemetry/client.go:201 +0x719
github.com/status-im/status-go/telemetry.(*Client).Start.func2()
	/home/ltinkl/git/status/status-desktop/vendor/status-go/telemetry/client.go:141 +0x1ff
created by github.com/status-im/status-go/telemetry.(*Client).Start in goroutine 573
	/home/ltinkl/git/status/status-desktop/vendor/status-go/telemetry/client.go:126 +0xf6
SIGABRT: Abnormal termination.
```

**Comment by igor-sirotin** [comment]
> Indeed I can (sort of) reproduce but when I do, after the "Request to join..." popup, I always immediately get this crash:
> 
> ```
> goroutine 638 [running]:
> github.com/status-im/status-go/telemetry.(*Client).pushTelemetryRequest(0x1c0073c3fa8?, {0x1c0228a6000?, 0x6bc?, 0x0?})
> 	/home/ltinkl/git/status/status-desktop/vendor/status-go/telemetry/client.go:201 +0x719
> github.com/status-im/status-go/telemetry.(*Client).Start.func2()
> 	/home/ltinkl/git/status/status-desktop/vendor/status-go/telemetry/client.go:141 +0x1ff
> created by github.com/status-im/status-go/telemetry.(*Client).Start in goroutine 573
> 	/home/ltinkl/git/status/status-desktop/vendor/status-go/telemetry/client.go:126 +0xf6
> SIGABRT: Abnormal termination.
> ```

I don't think it's related, looks like a crash during telemetry push 👀  
cc @vpavlin @adklempner  ^

**Comment by caybro** [comment]
Yeah it probably isn't related but there's no warning or errors in the console:
```
DBG 2024-07-11 15:14:29.941+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=57444 file=core.nim:27 rpc_method=wakuext_shareUserURLWithData
DBG 2024-07-11 15:14:29.971+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=57469 file=threadpool.nim:56 messageType=AsyncLoadDevicesTaskArg:ObjectType threadid=57469 task="{\"$type\":\"AsyncLoadDevicesTaskArg:ObjectType\",\"vptr\":781298544,\"slot\":\"asyncDevicesLoaded\"}"
DBG 2024-07-11 15:14:29.971+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=57469 file=core.nim:27 rpc_method=wakuext_getOurInstallations
WRN 2024-07-11 15:14:32.519+02:00 qt warning                                 topics="qt" tid=57444 text="QML StatusTextArea: Possible anchor loop detected on fill." file=qrc:/imports/shared/popups/ImportCommunityPopup.qml:156 category=default
DBG 2024-07-11 15:14:34.339+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=57466 file=threadpool.nim:56 messageType=AsyncGetRevealedAccountsArg:ObjectType threadid=57466 task="{\"$type\":\"AsyncGetRevealedAccountsArg:ObjectType\",\"communityId\":\"0x036dc0bcb627d55aa693096b447190eab3c5c57c117446ea44d93e97be0fe6ef46\",\"memberPubkey\":\"0x04effb663a86fcc5f7df47b2c945731789e338c7556cb30d935947be4db8be9e3c2791f8f8b19cd46758a887a22af09db522c98508ae0a6d79a2df33cb6468cd15\",\"vptr\":781295856,\"slot\":\"onAsyncGetRevealedAccountsForMemberCompleted\"}"
DBG 2024-07-11 15:14:34.339+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=57466 file=core.nim:27 rpc_method=wakuext_getRevealedAccounts
DBG 2024-07-11 15:14:34.339+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=57461 file=threadpool.nim:56 messageType=AsyncCheckPermissionsToJoinTaskArg:ObjectType threadid=57461 task="{\"$type\":\"AsyncCheckPermissionsToJoinTaskArg:ObjectType\",\"communityId\":\"0x036dc0bcb627d55aa693096b447190eab3c5c57c117446ea44d93e97be0fe6ef46\",\"addresses\":[],\"vptr\":781295856,\"slot\":\"onAsyncCheckPermissionsToJoinDone\"}"
DBG 2024-07-11 15:14:34.340+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=57461 file=core.nim:27 rpc_method=wakuext_checkPermissionsToJoinCommunity
DBG 2024-07-11 15:14:34.339+02:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=57463 file=threadpool.nim:56 messageType=AsyncCheckAllChannelsPermissionsTaskArg:ObjectType threadid=57463 task="{\"$type\":\"AsyncCheckAllChannelsPermissionsTaskArg:ObjectType\",\"communityId\":\"0x036dc0bcb627d55aa693096b447190eab3c5c57c117446ea44d93e97be0fe6ef46\",\"addresses\":[],\"vptr\":781293168,\"slot\":\"onAsyncCheckAllChannelsPermissionsDone\"}"
DBG 2024-07-11 15:14:34.347+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=57463 file=core.nim:27 rpc_method=wakuext_checkAllCommunityChannelsPermissions
```

@jrainville I see it's asking/checking for permissions but shouldn't we get the "Share addresses" dialog instead first? So that we can actually select which addresses to share when joining/spectating that community?

**Comment by jrainville** [comment]
> I see it's asking/checking for permissions but shouldn't we get the "Share addresses" dialog instead first? So that we can actually select which addresses to share when joining/spectating that community?

I feel like the order of screens or actions was messed up.

> The list (model) of communities doesn't get updated, might be some backend/NIM issue @jrainville ?
> 
> We haven't touched the community/share/import UI stuff for quite some time...

It's possible. I'll take a look

**Comment by igor-sirotin** [comment]
> ```
> SIGABRT: Abnormal termination.
> ```

@caybro can you please take a look what status-go version was it?

**Comment by vpavlin** [comment]
> Indeed I can (sort of) reproduce but when I do, after the "Request to join..." popup, I always immediately get this crash:

Yeah, sorry about this, it was introduced by my latest change - specifically this line https://github.com/status-im/status-go/blob/develop/telemetry/client.go#L200 - if `request` slice is bigger than `MaxRetryCache` it will hit this out of band error. 

Will submit a PR shortly. Sorry about this.

**Comment by caybro** [comment]
> > ```
> > SIGABRT: Abnormal termination.
> > ```
> 
> @caybro can you please take a look what status-go version was it?

```
❯ git last
commit 5336c47f1b28b1d1ee8ef5e2b1bbf9bdc479f409 (HEAD, tag: v0.181.34)
Author: Stefan <stefand@status.im>
Date:   Wed Jul 3 00:46:47 2024 +0300
```
