### ISSUE TITLE
Contact request message is not displayed on the side of receiver in message history

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15548]
# Bug Report

## Description

Found by @weboko 

The message sent by the contact request initiator is not displayed in the message list of the received once accepted.

## Steps to reproduce

1. user A sends add request to a user B and attach message in the field. In my case "Hello Danish";
2. user B receives request and chat is open;
3. user B does not see "Hello Danish" message;

> just tried to repro during another dogfooding and it was fine between desktop - mobile where desktop is user A and mobile is user B

#### Expected behavior

The message from the contact request should be shown in the message list of both users

#### Actual behavior

It is not shown for the receiver in the message list

### Additional Information

- Status desktop version: master?
- Operating System:

**Comment by endulab** [comment]
I tried to reproduce the issue but it seems that the contact request works correctly.

https://github.com/user-attachments/assets/6ce861d3-e817-4150-b509-f843b2ceac6e

**Comment by jrainville** [comment]
Closing as it seems fixed on master already.
