### ISSUE TITLE
[ChatInput]: not disabled with closed channels

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15547]
# Bug Report

![image](https://github.com/status-im/status-desktop/assets/5377645/f2046967-e5e9-4a76-88af-1d15ac0492be)

"announcements" channel is read-only, yet I can type something here

I'm even able to send it (status changes to "Sent"); although I have no idea whether it gets thru

![image](https://github.com/status-im/status-desktop/assets/5377645/122dbb7d-f569-4859-a57f-48391726d9f0)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by jrainville** [comment]
I can reproduce. Also, on a freshly created announcements channel, the message I sent as a normal member was even propagated. I'm guessing new users get the wrong role or something
