### ISSUE TITLE
[SwapModal] Potentially wrong account balance in Approve modal

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15554]
[Záznam obrazovky z 2024-07-12 00-56-19.webm](https://github.com/user-attachments/assets/528f3cf8-2ed8-4311-91c8-da85221b8889)

The code is (in SwapModalAdaptor, I even added the helper for chainId:
```qml
...
FastExpressionRole {
  name: "accountBalance"
  expression: {
    root.swapFormData.selectedNetworkChainId
    return d.processAccountBalance(model.address)
  }
  expectedRoles: ["address"]
  }
...
ModelEntry {
    id: selectedAccountEntry
    sourceModel: root.nonWatchAccounts
    key: "address"
    value: root.swapFormData.selectedAccountAddress
}
```

and then in SwapModal:
```qml
SwapApproveCapModal {
...
accountBalanceFormatted: root.swapAdaptor.selectedAccount.accountBalance.formattedBalance // <-- not actual code atm
```

Simply shows the "old" value from the previously selected network

_Originally posted by @caybro in https://github.com/status-im/status-desktop/pull/15530#discussion_r1674802306_

**Comment by DApps-Representative** [comment]
> Zaznam.obrazovky.z.2024-07-12.00-56-19.webm 
> The code is (in SwapModalAdaptor, I even added the helper for chainId:
> 
> ```qml
> ...
> FastExpressionRole {
>   name: "accountBalance"
>   expression: {
>     root.swapFormData.selectedNetworkChainId
>     return d.processAccountBalance(model.address)
>   }
>   expectedRoles: ["address"]
>   }
> ...
> ModelEntry {
>     id: selectedAccountEntry
>     sourceModel: root.nonWatchAccounts
>     key: "address"
>     value: root.swapFormData.selectedAccountAddress
> }
> ```
> 
> and then in SwapModal:
> 
> ```qml
> SwapApproveCapModal {
> ...
> accountBalanceFormatted: root.swapAdaptor.selectedAccount.accountBalance.formattedBalance // <-- not actual code atm
> ```
> 
> Simply shows the "old" value from the previously selected network
> 
> _Originally posted by @caybro in [#15530 (comment)](https://github.com/status-im/status-desktop/pull/15530#discussion_r1674802306)_

Hey there @caybro   ,

Thank you for reaching out! hi, it seems your address was blacklisted: kindly refresh your wallet, if the issue persists,then your query would be best dealt with by the support team.
 I’ll have to refer you to the official support Team with the ticket ID STAT7463
 
Please see the link below to our dedicated support line: 
 [Status Network Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.
