### ISSUE TITLE
Suggestion: permanent incognito option (and possibly the default?)

### ISSUE THREAD

**Issue by cyanlemons** [status-im/status-desktop#1555]
The current "Go Incognito" option in the browser does not persist after restarting Status Desktop. Perhaps there should be some option added in the `Profile>Browser settings` section that allows one to permanently enable incognito mode in a manner that will persist after restarts.

Also, I believe the browser should be incognito by default. It's already pretty mainstream for browsers to not store any history whatsoever, such as the DuckDuckGo mobile browser, or FireFox Focus – both of which have download counts in the millions. I think Status should always opt for "secure by default" configurations, and leaving a record of all your past internet activity by default seems like an unnecessary attack surface.

**Comment by jrainville** [comment]
The permanent incognito mode is a really good idea.

As for incognito by default, it makes sense. I'll bring it up with the UX guys and the team.

**Comment by hesterbruikman** [comment]
> Status should always opt for "secure by default" configurations
Absolutely. Thanks for the ping @jrainville 

As a related issue, also relevant for Desktop: https://github.com/status-im/status-react/issues/10575 

If no webaddress is recognized in address input bar, we could offer multiple safe search engine options, like Duckduckgo and in case of an address, the option to open blockexplorer. Suggested design for mobile in #10575. I think this should translate well to Desktop

**Comment by jrainville** [comment]
Yeah I like those designs

**Comment by iurimatias** [comment]
latest desktop build supports this (although it needs to be enabled in the settings)
