### ISSUE TITLE
Can't install the app to my MacBook Pro

### ISSUE THREAD

**Issue by Juliagera13** [status-im/status-desktop#15570]
# Bug Report

## Steps to reproduce
Download the file, click on the Status app icon and there is the pop-up that says Status Desktop has shut down unexpectedly 

### Additional Information
<img width="315" alt="image" src="https://github.com/user-attachments/assets/d9f30883-4e01-4e49-a304-0297c4ffeac0">

- Status desktop version: last on 10 July
- Operating System: MacOS Monterey

**Comment by Juliagera13** [comment]
<img width="315" alt="image" src="https://github.com/user-attachments/assets/2973615e-1323-4e49-8a4d-b67e83aec7ae">

**Comment by jrainville** [comment]
@Juliagera13 thanks for opening an issue. Could you tell us which version you are using (where did you download the app).

Also, do you use Mac with an Intel chip?

**Comment by Seitseman** [comment]
@jrainville , if needed I could help with more logs.

**Comment by jrainville** [comment]
If the isuse here really is the Intel based Mac issue, we already have an issue where we have made progress: https://github.com/status-im/status-desktop/issues/15134
