### ISSUE TITLE
SwapModal: SwapInputPanel cursor issues

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#15597]
### Description

When panel is launched with pre-filled values the cursor should be at the end of the amount , same thing when exchange button is clicked.

There is an additional issue that an amount set from outside the panel si reset to 0 when it launched which will also have to be addressed in this issue.

to solve this comment https://github.com/status-im/status-desktop/issues/15417#issuecomment-2222747127

![image](https://github.com/user-attachments/assets/f8a7bd8a-94e1-4389-a77a-ce4faeba03c8)

**Comment by caybro** [comment]
@Khushboo-dev-cpp I may have fixed this issue in my recent PR (https://github.com/status-im/status-desktop/pull/16106) but looks like problem solved? :)

https://github.com/user-attachments/assets/aeb4df51-b35f-4c54-8c7d-d2a0c77d5f2d
