### ISSUE TITLE
dApp - sd-6 - URI emoji validation

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#15594]
# Bug Report

## Description

Emoji error only appears when URI only 100% consists of emoji.

## Steps to reproduce

Paste a URI containing some emoji

#### Expected behavior

Emoji error displayed when any URI contains emoji

### Additional Information

- Status desktop version: Master, dapp flag
- Operating System: Mac

**Comment by virginiabalducci** [comment]
Adding a screenshot and a screen-recording showing the issue
<img width="606" alt="Screenshot 2024-07-17 at 3 46 00 PM" src="https://github.com/user-attachments/assets/ace84d4d-51d6-43fd-b867-c01e3291bd19">

https://github.com/user-attachments/assets/fc4ec095-4d36-467b-baa8-6716785954e8
