### ISSUE TITLE
dApp - sd-6 - Unable to read full contents of connection request dialog

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#15592]
# Bug Report

## Description

Unable to scroll to info on dApp access on the Connection request dialog

![image](https://github.com/user-attachments/assets/2cd5b0f5-c749-4ab4-b82b-52f9768e94c4)

## Steps to reproduce

Open connection request dialog with reduced window height.

#### Expected behavior

Scroll to dApp access info.

### Additional Information

- Status desktop version: Master, dApp flag
- Operating System: Mac

**Comment by caybro** [comment]
@Seitseman did you already start working on this? I see there's a branch created already... CC @noeliaSD

**Comment by Seitseman** [comment]
@caybro, I've only created a branch and checked storybook on this and switched to other issue.
