### ISSUE TITLE
dApp - sd-6 - dApp name not always displayed in connection list

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#15593]
# Bug Report

## Description

dApp name is not always shown

![image](https://github.com/user-attachments/assets/34c1efcf-7399-4510-ad3e-8f6a497cc49c)

## Steps to reproduce

Connect to yearn.fi, view dapp list

#### Expected behavior

Name displayed in dapp list item

### Additional Information

- Status desktop version: Master, dapp flag.
- Operating System: Mac

**Comment by clauxx** [comment]
Seems like the provider doesn't "provide" any useful visual metadata 
```edn
:metadata {:name "", :description "", :url "https://yearn.fi/", :icons []}
```

I guess if there is no name, we should format the url as the name, like: "yearn.fi" could be the name in this case.a

**Comment by clauxx** [comment]
@qoqobolo I guess this would be the case on mobile as well.

**Comment by qoqobolo** [comment]
> @qoqobolo I guess this would be the case on mobile as well.

Yep, name is not displayed for this particular dapp 

<img width="314" alt="Screenshot 2024-07-18 at 11 15 50" src="https://github.com/user-attachments/assets/6757c6bc-60f6-4c14-bb43-cdd480c6bba4">

Can I add this issue to https://github.com/status-im/status-mobile/issues/20769 or is it a separate problem? 
We will also double check the other dapps to see if the name is displayed.

**Comment by clauxx** [comment]
> > @qoqobolo I guess this would be the case on mobile as well.
> 
> Yep, name is not displayed for this particular dapp
> 
> <img alt="Screenshot 2024-07-18 at 11 15 50" width="314" src="https://private-user-images.githubusercontent.com/67952253/349895505-6757c6bc-60f6-4c14-bb43-cdd480c6bba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTUyMzQsIm5iZiI6MTcyMTI5NDkzNCwicGF0aCI6Ii82Nzk1MjI1My8zNDk4OTU1MDUtNjc1N2M2YmMtNjBmNi00YzE0LWJiNDMtY2RkNDgwYzZiYmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5Mjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDNkODU0OTA2NDM5OGFjZWI2OGVkMzZhZWFjYjIzODY4OTg4YmIxNzM1YTYxM2Q2Yjg2ZDFiMDE1NmEwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hEkWQ1sn5G2-5eVbMuyYDSFcSQwQ6pl7nuwWT_adAi4">
> Can I add this issue to [status-im/status-mobile#20769](https://github.com/status-im/status-mobile/issues/20769) or is it a separate problem? We will also double check the other dapps to see if the name is displayed.

Yeah, can add it there as well 👍. I think the only other edge case could be that the dapp didn't define any of the following: name, description, url. In this case we could show some placeholder, like "Unknown" or smth? cc: @xAlisher

**Comment by xAlisher** [comment]
@qoqobolo @clauxx 

In case name and picture missing I'll suggest to use URL instead if Title and use Wallet User avatar component to generate icon. 

![image](https://github.com/user-attachments/assets/135e9a1b-42b4-4fd1-8c4d-db7ee84087c4)

https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=114-7646&t=z70ji8Dxuvm80yAe-1
