### ISSUE TITLE
[WalletConnect] Format the fees in the sign popup to align with the standard in terms of number of decimals

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#15612]
# Bug Report

## Description

Related to https://github.com/status-im/status-desktop/issues/15057

We're currently not formatting the fees using the decimals numbers and it shows like this:

<img width="957" alt="Screenshot 2024-07-16 at 17 55 53" src="https://github.com/user-attachments/assets/a3493869-bcd0-4243-a07a-6467661d83da">

### Expected

It's expected for the fees to be formatted as described here https://www.notion.so/Wallet-Currency-Amount-Formatting-1648febf1b28479d99e141c74d0916f3

<img width="482" alt="Screenshot 2024-07-16 at 18 10 18" src="https://github.com/user-attachments/assets/cb6d2afe-f7bd-4b7f-a761-65d87d2311d2">

## Steps to reproduce

1. Connect a wallet connect dapp (E.g. https://react-app.walletconnect.com)
2. Send sign transaction from the dapp
3. Go back to Status. The sign modal should open

#### Expected behavior

4. The fees in the sign modal are formatted

#### Actual behavior

5. The fees in the sign modal are not formatted

**Comment by caybro** [comment]
I'm taking this for the next week as we share the functionality with the Swap modals and we want some unified approach here

CC @Khushboo-dev-cpp @dlipicar
