### ISSUE TITLE
On the Connection request pop up the user is able to select a L2 network but cannot connect

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15638]
# Bug Report

## Description

On the Connection request pop up the user is able to select a L2 network but cannot connect. 

## Steps to reproduce
1. Go to the Connect a dApp via WalletConnect screen 
2. Paste a dApp URI link
3. Click on the network dropdown list and select any L2 or both.
4. click Connect

#### Expected behavior
As per Figma notes, for M1 network should not be selectable or editable.
<img width="376" alt="Screenshot 2024-07-17 at 11 34 50 AM" src="https://github.com/user-attachments/assets/fafde0ab-29cf-4467-ad02-da1a1ba38f88">

#### Actual behavior
User is able to select any Layer 2 network or both Arbitrum and Optimism. But when clicking Connect button, nothing happens
<img width="543" alt="Screenshot 2024-07-17 at 11 43 35 AM" src="https://github.com/user-attachments/assets/ecdbc77c-593b-4618-bdd5-cc59b786b6c0">

### Additional Information

- Status desktop version: master https://github.com/status-im/status-desktop/commit/26508f5c9
- Operating System: Mac OS Sonoma

**Comment by clauxx** [comment]
the user shouldn't be able to select/unselect networks from the dropdown. It should be for display purposes only.

**Comment by virginiabalducci** [comment]
Adding a screen recording for further reference, no console errors are seen.

https://github.com/user-attachments/assets/8d26f337-6c4c-4b86-9ffd-adff07a9a46f

**Comment by alexjba** [comment]
Maybe there's a misunderstanding. I know there's been some amendments to the designs. [This](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=449-88374&m=dev) tells me the network should be configurable. @stefandunca does the integration currently support chain selection before connecting? If it does maybe we should keep it.

<img width="653" alt="Screenshot 2024-07-18 at 09 33 09" src="https://github.com/user-attachments/assets/221594f9-2c60-4ca5-9127-0873b7e4c975">

**Comment by stefandunca** [comment]
> @stefandunca does the integration currently support chain selection before connecting? If it does maybe we should keep it.

We don't support network selection, we report supporting all three and the result we get in the chain model is the intersection of dApps supported chains with ours. In the descoped version we implemented user should not be able to select or deselect but only visualize the result set
