### ISSUE TITLE
[WalletConnect] Sign request not received from siwe test app

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#15659]
# Bug Report

## Description

I'm testing with this test app: https://lab.web3modal.com/library/wagmi-siwe

The connection is successful, but when hitting `sign` in the web app we don't receive the sign request in Status. There's no log to indicate a sign request.

## Steps to reproduce

1. Go to https://lab.web3modal.com/library/wagmi-siwe/
2. Generate a new WC link
3. Go to Status, Wallet, DApps
4. Paste the link and connect to the DApp
5. Go back to the browser and hit `sign`

#### Expected behavior

Sign request received in Status

#### Actual behavior

Sign request not received in Status

**Comment by clauxx** [comment]
We don't plan to support SIWE in 2.30 as it was descoped. I think the request doesn't come in cause this test dapp uses walletconnect's special event `session_authenticate`, which isn't used by any dapp from what we've seen. Usually dApps that support SIWE just send a `personal_sign` request, but if we find major dApps that start making use of it, we'll consider adding support for it. @alexjba I'll close this, as we already have a [user story for it in notion](https://www.notion.so/I-want-to-use-SIWE-to-sign-in-with-dApps-e03d0c764b524b6d9f992732d7944d9f?pvs=4), which will help us track this feature.
