### ISSUE TITLE
dApp - Connect to Magic Eden - Sign request - Version section text is overlapped and unreadable

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15650]
# Bug Report

## Description

There is overlapped text and cut text on the Version section of the Sign Request screen when connecting a Magic Eden dApp.

## Steps to reproduce

1. Go to https://magiceden.io/ and copy a wallet connect URI
2. Go to dApp connections and select "Connect a dApp via Wallet Connect"
3. Paste the URI
4. Notice that there is text overlapped in the version section of the Sign Request screen

#### Expected behavior
No overlapped text, all text of the screen to be readable.

#### Actual behavior
The text on the Version section is overlapped. Cannot scroll with mouse wheel or trackpad.
![Screenshot 2024-07-17 at 4 54 10 PM](https://github.com/user-attachments/assets/bfa366db-1bf5-4279-80f3-f7a0168fda38)

https://github.com/user-attachments/assets/47a76625-93f3-46f5-90a3-308e452a18ed

### Additional Information

- Status desktop version: master
- Operating System: Mac OS Sonoma

**Comment by anastasiyaig** [comment]
still the case
<img width="1840" alt="Screenshot 2024-07-25 at 16 40 49" src="https://github.com/user-attachments/assets/e5ef6c4b-8ed5-498c-a2af-2192879bd325">

**Comment by caybro** [comment]
> still the case <img alt="Screenshot 2024-07-25 at 16 40 49" width="1840" src="https://private-user-images.githubusercontent.com/82375995/352129791-e5ef6c4b-8ed5-498c-a2af-2192879bd325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTU0MTksIm5iZiI6MTcyMTkxNTExOSwicGF0aCI6Ii84MjM3NTk5NS8zNTIxMjk3OTEtZTVlZjZjNGItOGVkNS00OThjLWEyYWYtMjE5Mjg3OWJkMzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEzNDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NWI4ODI5M2I2NDc1OTBhZTg1NjVkZDFmOTk3ODA5MjRiNWUzZDNmN2IyOWM3NjQ1ODljYjlhYzViYWJiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eUdNca12A4BzCyVNm2XNutSjnwq5JySv2Ylb56cBPjA">

Yeah, I'll have a look soon

**Comment by caybro** [comment]
I can't reproduce in current master; it has this "Expand" button now when you hover over the details area:

![image](https://github.com/user-attachments/assets/dfde7bef-af8e-42be-830e-c29b64efe23f)


Can you confirm pls @anastasiyaig @alexjba ?

**Comment by anastasiyaig** [comment]
@caybro we need to test that in RC and confirm

**Comment by anastasiyaig** [comment]
@caybro can confirm happening in RC

<img width="1512" alt="Screenshot 2024-07-29 at 12 01 01" src="https://github.com/user-attachments/assets/022793e3-a40c-4554-97fa-22a4c93e80aa">

**Comment by caybro** [comment]
> @caybro can confirm happening in RC
> 
> <img alt="Screenshot 2024-07-29 at 12 01 01" width="1512" src="https://private-user-images.githubusercontent.com/82375995/352983622-022793e3-a40c-4554-97fa-22a4c93e80aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDM5ODcsIm5iZiI6MTcyMjI0MzY4NywicGF0aCI6Ii84MjM3NTk5NS8zNTI5ODM2MjItMDIyNzkzZTMtYTQwYy00NTU0LTk3ZmEtMjJhNGM5M2U4MGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA5MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NTY4OGRiMmY2OGMyNTQ0NzI1YzA0MmFhMzUyNGZkZWMzYThmMzBjZGVmYmEwZmVkNGE5YmVjNzQ0OTU2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-GZltSpcBYBt7IKF78dePN2GSfTQOhq_yIkNCGkgr1k">

This is weird as the commit that introduced happened on July 12, so the release branch should have it

**Comment by caybro** [comment]
OK, with a carefully crafted text (length), I can reproduce too:

![image](https://github.com/user-attachments/assets/144ddd6a-45e2-45c1-be10-371546a8b65b)
