### ISSUE TITLE
Add or remove members from a chat group - cannot scroll the list of members, list is difficult to navigate

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15667]
# Bug Report

## Description

While on a group chat, user selects "Add / remove from group" option and tries to scroll the group members. Scrolling with mouse no wheel, by clicking on the navigation bar is not possible, can only scroll using the keyboard arrows. Can also scroll with trackpad horizontally, but this is difficult because mouse cursor has to be placed inside the member list in order to work. 

https://github.com/user-attachments/assets/65cde1cf-231a-44cd-81a9-433fdc4c355b

This is inconvenient for the user, the member list should show in a vertical list instead of horizontal. It would be nice to also have the option to remove a member directly by right-clicking on a member from the list on the right side and selecting an option "Remove member"

There is also inconsistency in the options to add or remove members. 

1. User clicking the three dot menu from the Chat's navigation bar at the top, "Add / remove from group" option displays. 
![Screenshot 2024-07-18 at 8 07 17 PM](https://github.com/user-attachments/assets/f22f429c-3773-48d9-ba7b-466943e3b92d)

2. User right-clicks on the group chat from the list of messages, only "add to group" option displays instead of "Add / remove"
![Screenshot 2024-07-18 at 8 07 06 PM](https://github.com/user-attachments/assets/94da8c48-1ee7-4217-b8ca-515fc50b4956)

https://github.com/user-attachments/assets/75f0ca5a-56ec-47f8-b8fc-bcf13ce859ea

### Additional Information

- Status desktop version: Nightly [StatusIm-Desktop-240717-125009-9f03c2-nightly-aarch64.dmg](https://ci.status.im/job/status-desktop/job/nightly/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-240717-125009-9f03c2-nightly-aarch64.dmg)
- Operating System: Mac OS Sonoma

**Comment by jrainville** [comment]
These issues will be fixed when we implement the improvements from the new designs: https://github.com/status-im/status-desktop/issues/8278
