### ISSUE TITLE
List of assets is the same for each account unless a number of items change

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#15683]
# Bug Report

## Description

https://github.com/user-attachments/assets/e1ec61d4-ad24-44cd-90de-3f250b2aa70e

## Steps to reproduce

see video

#### Expected behavior
Unique assets per account. A number of them depends on assets possession and history of possession
#### Actual behavior
A number and assets dones change from account to account unless a different number of assets present for some account
### Additional Information

- Status desktop version: 2b415bdc5359f424fbfcabf1b5319bc3a8595921, status-go: d07f9b5b162c078f71bf19a189e2e26c118a0db4
- Operating System: MacOS

**Comment by micieslak** [comment]
@IvanBelyakoff could you please record similar video but under Monitoring Tool as in the video below? In my env number of items only grows as the watch-only accounts are loaded, so I'd like to understand what happens in your case when items disappear.

[Screencast from 22.07.2024 21:24:30.webm](https://github.com/user-attachments/assets/bb8a47c8-1a25-4624-9dfa-b3aec0d2aa59)

**Comment by micieslak** [comment]
Other question, what should be presented? Only items with some history for given account and network, right?

**Comment by anastasiyaig** [comment]
its not the same assets, it is a bit different. so if you have some assets on account 1 with balances, then if you click another account which does not have balances for the same assets, you will still see the assets in the list, but with 0

we should not show asset if it has 0 balance, except the default ones (eth, dai and snt i guess)


https://github.com/user-attachments/assets/a66f1fc3-c0c5-4f4d-9e1f-b3f4176d80d9
