### ISSUE TITLE
Wrong value to send/receive are calculated when max value on chain is entered in SendModal

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#15693]
# Bug Report

## Description

<img width="554" alt="Screenshot_2024-07-22_at_09 41 54" src="https://github.com/user-attachments/assets/a604aae4-5445-459a-8989-90a2f568c710">

## Steps to reproduce

- Click Send
- enter max value available on chain (for me max on mainnet)
- when routes are calculated:
  - entered value is more than max value in top right corner
  - recipient wil get twice more than we send
  - value on mainnet is twice more than the balance on it

#### Expected behavior
Recipient should get the proper value (To be determined - is it sent - fee, or is it equal to sent?)
#### Actual behavior
See screenshot
### Additional Information

- Status desktop version: 2b415bdc5359f424fbfcabf1b5319bc3a8595921, status-go 94b20172262bede4ac4f9434c6e01e91a7868e1e
- Operating System: MacOS

**Comment by saledjenic** [comment]
It should be fixed in this PR https://github.com/status-im/status-go/pull/5615
Related desktop app PR https://github.com/status-im/status-desktop/pull/15843
