### ISSUE TITLE
 Limit the `Assets List` for `bridge` depending on the list of assets HOP supports

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15697]
### Description

Currently, the **Bridge Modal**  shows all assets where a user has positive balance but not all the tokens can be bridged (because HOP service does not support some).

The list of assets hop supports is static and can be found on _hop app_ itself or also from _status-go_.

![image](https://github.com/user-attachments/assets/50c2d0f0-1088-41fb-bf95-86a77db65352)

### What to do
Filter the `assestList` model in the UI to only show the supported HOP service assets.

**Comment by alaibe** [comment]
Here are the list of asset supported by hop (that will need an update when adding celer)
USDC
USDC.e
USDT
DAI
HOP
SNX
sUSD
rETH
MAGIC

**Comment by noeliaSD** [comment]
This issue depends on decission taken about **error handling**. There are to option on the table:
- Show proper error when trying to bridge a non-supported asset.
- Do the filtering that is described in this issue.

@saledjenic to decide the alternative to be implemented and the milestone / priority

**Comment by saledjenic** [comment]
The list Anthony shared above is taken from the Hop exchange, we should, at least for now, hardcode it on the client side and if the user is running Bridge flow we should offer the list which is an intersection of tokens the user has a positive balance on and that hardcoded list.

@ilmotta @briansztamfater maybe you're going to do the same?
