### ISSUE TITLE
fix: pending txs not working (possibly only related to Sticker packs)

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1569]
1. Buy sticker pack
2. Expected: Button should show "Pending..." then should automatically install after tx is complete (show green tick)
3. Actual: Transaction is pending forever (indicated by "Pending..." shown on the sticker button). Restarting app shows that the sticker pack was purchased (but not installed).

**Comment by jrainville** [comment]
This could be related to the fact that we use a dev Infura token and those don't have the history .
We'd need to double check using a prod token

**Comment by iurimatias** [comment]
possibly related to #1205

**Comment by iurimatias** [comment]
note: possible that PRs #2315 and #2321 fix or help with this

**Comment by iurimatias** [comment]
closed in favour of issue #2915 and PR #2914
