### ISSUE TITLE
Clicking on different stickers shows the wrong stickers inside

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15718]
# Bug Report

## Description

If stickers from different packs are posted in a channel, it seems like only the first pack will be correct when clicked on. The others will be the first one clicked:

[stickers.webm](https://github.com/user-attachments/assets/3e4aeb4f-eff7-435b-8b5e-6e3ee39c9e85)

It seems like the rest of the popup's content is fine.

## Steps to reproduce

1. Install  a couple of sticker packs
2. Post stickers from multiple different packs
3. Click on the stickers

#### Expected behavior

The pack shown should be the sticker you clicked on

#### Actual behavior

The pack shown has the images of the wrong pack (seems like the first one clicked)

### Additional Information

- Status desktop version: 2.29
- Operating System: Ubuntu 22

**Comment by jrainville** [comment]
@noeliaSD I'm not sure if this is a UI or backend issue

**Comment by caybro** [comment]
Looks like a backend issue to me; the only reference to `stickerPack` in QML is in `MessageView.qml` which gets it passed down from the model:

```qml
stickerPack: model.stickerPack
```

**Comment by caybro** [comment]
OTOH, looks like I broke it, assigning to myself :disappointed:
