### ISSUE TITLE
Hide MaxAmount button from the UI

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#15710]
Since the requirements for the Max Amount button were misunderstood at the moment of development and if users follow it, that very often leads to failed tx or not routes we need to hide it and reintroduce it via this issue https://github.com/status-im/status-desktop/issues/15709 in 2.31.

**Comment by caybro** [comment]
This doesn't apply to the SwapModal, does it? CC @Khushboo-dev-cpp @dlipicar

**Comment by dlipicar** [comment]
hmm yeah, it will probably get a bit more complicated once we add multi-chain swap+bridge, but for M1 we've got 2 scenarios:
1) Pay asset is ERC20 Token: We can just use the max amount
2) Pay asset is ETH: We subtract a small percentage to account for fees. This uses a very naive approach which could be improved (gas cost depends on the network, changes over time, etc), but it seems to work for now.
![image](https://github.com/user-attachments/assets/4a8ba85a-1a73-4ac7-82f1-02bdbdf8ea30)

I think we can keep it

**Comment by saledjenic** [comment]
>  Worst case you'll get error message "not enough balance to pay for gas".

With the current implementation that will be the case for sending tx, always.

Don't we want to have the same behavior for swap and send in that regard? I mean, if user clicks Max button he most likely wants to spend/swap all he has on that account, that's what is described in the #15709
