### ISSUE TITLE
[Browser pluging connector] Refactor DappsConnectorSDK to avoid code duplication

### ISSUE THREAD

**Issue by kounkou** [status-im/status-desktop#15711]
### Description

During the integration of Connector for Browser plugin connector,
it was decided that being able to launch Wallet connect `AND` Connector at the same time would require us to duplicated some code mainly coming from the Wallet connect request [Handler](https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Wallet/services/dapps/DAppsRequestHandler.qml)

### Acceptance criteria

- Code between WalletConnect and Connector is refactored to reuse the same building brics without the need to duplicated code.
- Both wallet connect and Connector are tested and work as expected.

**Comment by alexjba** [comment]
Closed by [Feat(DApps): Refactoring wallet connect service and bring BrowserConnect inline with WC #16730](https://github.com/status-im/status-desktop/pull/16730)
