### ISSUE TITLE
Double route with 0 balances when bridging USDC and having only mainnet in destination

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15723]
# Bug Report

## Description

Double route with 0 balances when bridging USDC and having only mainnet in destination which does not make sense as balances are 0

## Steps to reproduce

1. open bridge and disable Opt and Arb in Advanced
2. close the modal
3. open Bridge modal again
4. select USDC
5. open Advanced

#### Expected behavior

<img width="1312" alt="Screenshot 2024-07-23 at 11 11 52" src="https://github.com/user-attachments/assets/03336eae-3d20-46d7-ab0c-d4fed690a8ef">

#### Actual behavior

I think it should show no route as i dont have balance for USDC on L2

### Additional Information

- Status desktop version: nightly build July 23
- Operating System: macOS

**Comment by saledjenic** [comment]
This one should be fixed in this PR: https://github.com/status-im/status-go/pull/5569
