### ISSUE TITLE
Sending 0 is not possible, no fees are calculated

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15720]
# Bug Report

## Description

<img width="1312" alt="Screenshot 2024-07-23 at 10 18 32" src="https://github.com/user-attachments/assets/ef161dcc-ed1c-4173-8b05-38dfc33709c8">

## Steps to reproduce

Open wallet , having some funds on your account
Try to send 0 eth

#### Expected behavior

Fees are calculated, for example check on Metamask
<img width="361" alt="Screenshot 2024-07-23 at 10 23 46" src="https://github.com/user-attachments/assets/3038ffac-1783-45fb-be80-1c0379cac989">

#### Actual behavior

Fees are not calculated

### Additional Information

- Status desktop version: nightly build 434 July 23 https://ci.status.im/job/status-desktop/job/nightly/434/
- Operating System: MacOS

**Comment by anastasiyaig** [comment]
@noeliaSD please check on that with wallet team / design to align expectations but i think we should be able to send 0, so thats a bug to me (for now)

**Comment by saledjenic** [comment]
This issue is fixed by the following PR:
- desktop side one, here https://github.com/status-im/status-desktop/pull/15728
- statusgo one, here https://github.com/status-im/status-go/pull/5561
