### ISSUE TITLE
Swap Modal - switch input/output button functionality when all parameters are empty

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15751]
# Bug Report

## Description
When the Pay and Receive parameters are empty (amount and assets), the switch input/output button should still be clickable or should it be disabled as per this user story https://www.notion.so/Switch-input-output-assets-9dffbae3ce634d148ff93c215b157163 

## Steps to reproduce

1. Open Swap modal
2. Do not enter any amount
3. Reach to a state where the assets are not available on the selected network. For example, choose Pay and Receive tokens that are available on Mainnet but that are not available on Optimism. For example PERP and MAGIC. Then select Optimism network.
4. click on the Switch input/output button

#### Expected behavior
As per the user story, the switch button should be disabled.

#### Actual behavior
The switch is clickable but does nothing.

https://github.com/user-attachments/assets/604df5ac-0add-4368-937c-9f275da1a5dc

### Additional Information

- Status desktop version: Master of today
- Operating System: Mac OS Sonoma

I put 2.30.0 Milestone but please review and change accordingly. Thanks!

**Comment by caybro** [comment]
This should never be empty right, SNT should be pre-selected as the "Receive" token, or have we changed that requirement?

**Comment by caybro** [comment]
Ah I get it, it's a special case to which you can arrive to by changing the params
