### ISSUE TITLE
[Wallet]: Sending community-minted assets is broken

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15766]
# Bug Report

## Description

There are several problems related to sending community assets:

1. When `Show community assets when sending tokens` is disabled, the menu for those tokens should have no `Send` action:

[Screencast from 24.07.2024 12:31:20.webm](https://github.com/user-attachments/assets/8acf09a5-981f-45ce-9ced-fd645ce0fa52)

2. When `Show community assets when sending tokens` is enabled it's still impossible to send those tokens
   - when `Send Modal` is launched from menu, community asset preselection doesn't work, the token selection remains empty
   - when community asset is selected in `Send Modal`, the icon in set to default incorrectly
   - when amount and address is provided, routes are not found

[Screencast from 24.07.2024 12:33:18.webm](https://github.com/user-attachments/assets/2a7b401e-60c0-40b1-9343-1e80af259a81)

3. It's totally unclear for the potential user how to enable sending community assets when it's disabled. The option is hidden deep in settings.

#### Expected behavior
- Regarding behavior when sending community assets is disabled - no send action from menu
- Regarding sending - should work as for regular tokens

#### Actual behavior
As described above

**Comment by alexjba** [comment]
The asset details view should be aligned as well (if not already). The `Send` button should be disabled.

**Comment by noeliaSD** [comment]
@micieslak please reevaluate, create separated ui tasks and backend tasks if needed.

**Comment by micieslak** [comment]
The UI part has been merged: https://github.com/status-im/status-desktop/pull/15956

**Comment by caybro** [comment]
> The UI part has been merged: https://github.com/status-im/status-desktop/pull/15956

Pls forward port to master as well
