### ISSUE TITLE
[Wallet] Unhandled error when attempting to sending a null number with several 0 decimals

### ISSUE THREAD

**Issue by kounkou** [status-im/status-desktop#15763]
# Bug Report

## Description

When attempting to send a very low amount (0.000...0000) that is non positive value, after entering 18 zeroes, the user interface computes fees, estimated time and enables the user to send the amount even though the value is 0.
When the user tries to send the amount, an error is caught. However that error doesn't have a Status look and feel. This error might also be a leaking of non user facing status errors.

![Screenshot from 2024-07-23 23-49-28](https://github.com/user-attachments/assets/de1252a1-bfba-4870-bb7b-f5c2269e112b)

## Steps to reproduce

1- Click on wallet
2- Click on send
3- Use a valid wallet address 
4- start providing the amount : `0.00000....`
5- after 18 `0` after the comma, the `send` button is enabled
6- click send
7- observe the error as shown in the description

#### Expected behavior

- We should probably not allow such infinitesimal number 
- we should handle error in the context of Status and show the error in the Status UI
- we should handle client side field validations
- we should handle server side validation if client side validations can't be handled

#### Actual behavior

- The validations is not done
- The error is not showing with Status app design and look and feel

### Additional Information

- Status desktop version: master (https://github.com/status-im/status-desktop/commit/166a0376f)
- Operating System: `Linux 6.5.0-1022-oem #23-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr 25 13:29:45 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by micieslak** [comment]
Does it matter if the input is `0` or `0,0000000000000000000`? The component returns amount in base units, so the amount should be `0` in both cases.

**Comment by micieslak** [comment]
![Screenshot from 2024-07-24 17-21-02](https://github.com/user-attachments/assets/a375e789-3cb0-4cd6-961f-af11800d8abf)

It works in the same way no matter how many zeroes we have

**Comment by micieslak** [comment]
Ahh, ok, I got it

![Screenshot from 2024-07-24 17-24-45](https://github.com/user-attachments/assets/2fd99e68-f22d-4245-b945-4e614d43c681)

I think it should be considered along with https://github.com/status-im/status-desktop/issues/15710 How do we want to prevent that situation, especially that max button will be hidden?

Probably there are some low-level errors not propagated properly. Instead of popup from status-go, it should be propagated correctly upstream and presented to the user in civilized form. @saledjenic wdyt?

**Comment by kounkou** [comment]
> ![Screenshot from 2024-07-24 17-21-02](https://github.com/user-attachments/assets/a375e789-3cb0-4cd6-961f-af11800d8abf)
> 
> 
> 
> It works in the same way no matter how many zeroes we have

Hi sorry I saw you already got your answers while I was afk. Nice!

**Comment by saledjenic** [comment]
@Cuteivist the user should be able to send 0 ETH or 0 of any other token as long as he has enough ETH to pay for a gas for that tx.

As I see an error from the description doesn't say anything about the amount being sent, but about the necessary amount of ETH for paying for a gas.

Also maybe we should check and limit users to enter only the number of decimals that correspond to the selected token, 18 for ETH, 6 for USDC...

**Comment by saledjenic** [comment]
Yes, the Router raises an error if no enough ETH for gas and in that case we have disabled the Send button. So this issue is all about UI handling of entering 0.000... amount.

> I implemented it few weeks ago already :)

@Cuteivist could you share the PR where this UI handling of entering 0.000... is addressed?

**Comment by saledjenic** [comment]
Here is an issue for improving on handling sending transaction errors https://github.com/status-im/status-desktop/issues/15919
