### ISSUE TITLE
Weird routes generated for multi tx

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#15762]
There is 
0.03 eth on mainnet
0.03 eth on optimism
0.01 eth on arbitrum

When user tries to send 0.04, when all "from" and "to" networks are enabled, too many routes get generated.

<img width="591" alt="_a1" src="https://github.com/user-attachments/assets/1b2c6f04-3983-4b3f-9c72-3fcc43d2852d">

**Comment by anastasiyaig** [comment]
@saledjenic its a duplicate

**Comment by saledjenic** [comment]
This one should be fixed in this PR:
https://github.com/status-im/status-go/pull/5569

**Comment by saledjenic** [comment]
> @saledjenic its a duplicate of #15723

@anastasiyaig it looks like that. Should be fixed in https://github.com/status-im/status-go/pull/5569
