### ISSUE TITLE
Wallet: Hidden communities not accessible, hiding by community leads to crash

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15775]
# Bug Report

## Description

As presented in the video, collectibles hidden from wallet's main views are no longer accessible as they don't appear in "hidden" tab of `Manage Tokens` in settings.

Moreover using `Hide all collectibles from this community` leads to app crash:

```
DBG 2024-07-24 16:20:01.306+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=189867 file=core.nim:27 rpc_method=accounts_updateCollectiblePreferences
DBG 2024-07-24 16:20:01.327+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=189867 file=core.nim:27 rpc_method=accounts_getCollectiblePreferences
DBG 2024-07-24 16:20:09.260+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=189867 file=core.nim:27 rpc_method=accounts_updateCollectiblePreferences
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:821: run-linux] Segmentation fault (core dumped)
16:20:09: make exited with code 2
```

[Screencast from 24.07.2024 16:18:52.webm](https://github.com/user-attachments/assets/81fe9280-29e6-4cd5-aaf6-6c52fa58d991)

After app restart collectibles are not present as well:

![Screenshot from 2024-07-24 16-21-32](https://github.com/user-attachments/assets/df74c06c-fd61-44bc-991e-14833cc90dc5)

![Screenshot from 2024-07-24 16-21-21](https://github.com/user-attachments/assets/16149e26-fc31-4c0c-87ea-3975bb7b1ef7)

#### Expected behavior
Collectibles should appear in `Settings` -> `Wallet` -> `Manage tokens` -> `Hidden` tab

#### Actual behavior
Collectibles disappear

**Comment by micieslak** [comment]
Update: It turns out that layout is broken when `Manage Tokens` is opened via menu:
![image](https://github.com/user-attachments/assets/91619abc-5948-42f2-9c35-316665119e69)

Otherwise, content is presented correctly, also for hidden collectibles.
The remaining valid issue is also crash on per-community hiding.

**Comment by micieslak** [comment]
Another crash recorded

[Screencast from 24.07.2024 16:43:30.webm](https://github.com/user-attachments/assets/207c468c-6be4-418a-8456-f9a5a21c92cc)

**Comment by jrainville** [comment]
Should we just hide the "Hide Token" feature for now? cc @saledjenic @noeliaSD @dlipicar @anastasiyaig

**Comment by anastasiyaig** [comment]
i dont remember this feature at all to be honest (my bad). If it crashes - lets hide it

**Comment by caybro** [comment]
Let's jsut try to fix the crash at least? Can you run and repro the crash under gdb @micieslak ?

**Comment by noeliaSD** [comment]
> Should we just hide the "Hide Token" feature for now? cc @saledjenic @noeliaSD @dlipicar @anastasiyaig

It's now under experimental / Beta tag.. If we can fix the crash we could keep it.

**Comment by caybro** [comment]
I couldn't reproduce, worked correctly as expected:

Just hid the "Status" collectibles:
![image](https://github.com/user-attachments/assets/c0f2a5f0-bc9b-42be-bfa6-1bec3806a943)

And they're correctly placed under the Hidden section:
![image](https://github.com/user-attachments/assets/0500d53e-384d-46e8-a79c-b05dd93448ee)
