### ISSUE TITLE
Wallet: Hiding assets from wallet's main view doesn't work

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15777]
# Bug Report

## Description

Hiding assets from Wallet's main view doesn't work neither for regular nor community assets.

[Screencast from 24.07.2024 17:35:10.webm](https://github.com/user-attachments/assets/8223470a-a7c3-4df2-80a9-747559c8d4ce)

[Screencast from 24.07.2024 17:34:00.webm](https://github.com/user-attachments/assets/edd3db17-75e7-410e-b294-49638cb4eabc)

## Steps to reproduce
1. Open wallet, assets tab
2. Right click on asset
3. Click `Hide asset`

#### Expected behavior
Asset should be hidden

#### Actual behavior
No action

**Comment by caybro** [comment]
This definitely used to work prior to moving the backend to NIM/status-go; CC @Cuteivist @stefandunca any idea?

**Comment by stefandunca** [comment]
> This definitely used to work prior to moving the backend to NIM/status-go; CC @Cuteivist @stefandunca any idea?

I'm not sure I ever tested that functionality. I only was aware of the settings token management and use that to test.

**Comment by caybro** [comment]
> > This definitely used to work prior to moving the backend to NIM/status-go; CC @Cuteivist @stefandunca any idea?
> 
> I'm not sure I ever tested that functionality. I only was aware of the settings token management and use that to test.

It should use the same codepath; I'll try to reproduce locally first

**Comment by caybro** [comment]
> > > This definitely used to work prior to moving the backend to NIM/status-go; CC @Cuteivist @stefandunca any idea?
> > 
> > 
> > I'm not sure I ever tested that functionality. I only was aware of the settings token management and use that to test.
> 
> It should use the same codepath; I'll try to reproduce locally first

Reproduced, no errors/warnings; really seems like this was overlooked when doing the port. I can give this a quick try but I might need some help here @stefandunca

**Comment by caybro** [comment]
OK, seems like this is a leftover from porting to the new AssetsView; I'll fix this @micieslak
