### ISSUE TITLE
Onboarding: Failed import from seedphrase leads to creating malformed account

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15776]
# Bug Report

## Description

I created fresh account, took seed phrase and cleared `Status` directory. Then importing that account failed, but resulted in creating account with no name:

[Screencast from 24.07.2024 16:58:52.webm](https://github.com/user-attachments/assets/c9cb3488-ec3e-465a-a8a4-e88214febdf3)

Failing seedphrase:

![Screenshot from 2024-07-24 16-49-37](https://github.com/user-attachments/assets/6b5a7aef-459a-4105-9e9f-8d9b6061a6bc)

[Screencast from 24.07.2024 17:08:35.webm](https://github.com/user-attachments/assets/60c64052-f9b9-47fe-b141-897f0e2e795b)

## Steps to reproduce
1. Create new account
2. Save seed phrase
3. Close the app
5. Clear local data (`Status` dir)
6. Import account from seedphrase

For very fresh account, import should fail

#### Expected behavior
There is no new account created

#### Actual behavior
Malformed account is present after restart

**Comment by iurimatias** [comment]
this happens only when the seed phrase is re-imported immediatly, when not given enough time to have it backed up

**Comment by jrainville** [comment]
Superseded by https://github.com/status-im/status-desktop/issues/16608
