### ISSUE TITLE
Wallet: `Add a new account` modal accepts invalid addresses

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15779]
# Bug Report

## Description

It's possible to add address with invalid check sum via `Add a new account` modal.

[Screencast from 24.07.2024 17:52:52.webm](https://github.com/user-attachments/assets/3ce58116-90a0-436d-b255-80a9e4184313)

**Comment by saledjenic** [comment]
Explained here https://github.com/status-im/status-desktop/issues/15772#issuecomment-2258291148 there is no invalid address.
