### ISSUE TITLE
SwapModal: ErrorTag looks wrong

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#15788]
# Bug Report

## Description

The errorTag doesnt look okay on latest master. Perhaps a side effect of https://github.com/status-im/status-desktop/pull/15759#event-13630278976

## Steps to reproduce

Trying making a tx which returns no routes 

#### Expected behavior

The errorTag should look as defined in design https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=5862-85250&m=dev

#### Actual behavior

![image](https://github.com/user-attachments/assets/bf74b65d-91a4-4dd7-8401-5e4033acde1a)

### Additional Information

- Status desktop version:
- Operating System:

**Comment by caybro** [comment]
I can repro under SB as well:

![image](https://github.com/user-attachments/assets/4dc0d07a-9c24-40c0-9e21-85932a563bf2)
