### ISSUE TITLE
Other collectible info popup doesn't show the right information (in the send popup)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15786]
# Bug Report

## Description

Small bug in the send popup. If you have "other" collectibles in your wallet (I guess I received a scam coin), the Other category shows. There is a `?` icon you can click to know what those are.
It shows this:
![image](https://github.com/user-attachments/assets/106f49ae-8d76-4e2b-8c00-fe5ac0a51928)

It's the same popup as if I clicked on the `Community minted` one. I'm fairly sure this is a mistake. Also, even for the real community popup, it should probably say `Community collectibles` in  this case?

## Steps to reproduce

0. Receive a scam NFT or something?
1. Go in Wallet
2. Click Send
3. Go in Collectibles
4. Click the `?` in the Other category

#### Expected behavior

The popup explains what those Other tokens are

#### Actual behavior

It talks about the community tokens

### Additional Information

- Status desktop version: 2.29
- Operating System: ubuntu 22

**Comment by jrainville** [comment]
@noeliaSD this is a pretty minor issue, but also probably easy to fix

**Comment by caybro** [comment]
Can no longer happen; this particular `CommunityAssetsInfoPopup` is only triggered from the main wallet's AssetsView.qml
