### ISSUE TITLE
Wallet/SwapModal: Input presents various unexpected behaviors

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15780]
# Bug Report

## Description

The currently used `AmountToSend` should be replaced by `AmountToSendNew`. Old one should be removed completely and new one renamed.

[Screencast from 24.07.2024 18:15:01.webm](https://github.com/user-attachments/assets/3e113c2d-d827-446f-a7ac-fd528d5babe5)

Old input used in `SendModal` has many issues, some of them are presented in the video.

New component, based on `AmountValidator` is covered with tests and has initial user story page defined: https://www.notion.so/Desktop-Send-and-Bridge-Modals-24f1d179c28a4a26bd401568500e5c14?p=153462fca74f45cba6ec105d56af98de&pm=c

**Comment by caybro** [comment]
Likely a target for 2.31, it was on my TODO list anyway, thanks for reporting :) CC @noeliaSD @Khushboo-dev-cpp

**Comment by noeliaSD** [comment]
I'd say that it depends on the issues that the old component has. Could you @Khushboo-dev-cpp @dlipicar @caybro assess it?

**Comment by Khushboo-dev-cpp** [comment]
> I'd say that it depends on the issues that the old component has. Could you @Khushboo-dev-cpp @dlipicar @caybro assess it?

What I see already is that there is a loss in precision when entering a number with a lot of zeros after decimals places. Nothing else that feels major to me

**Comment by caybro** [comment]
> I'd say that it depends on the issues that the old component has. Could you @Khushboo-dev-cpp @dlipicar @caybro assess it?

My pet peeve is that currently the amount input is strictly bound to the selected holding (needs the market details, currency price etc)
