### ISSUE TITLE
Add `Beta` tag in `Advanced` and `Custom` router panel view 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15793]
### Description

This is a followup task of https://github.com/status-im/status-desktop/issues/15614.

Add tag in these 2 tabs:

<img width="617" alt="Screenshot 2024-07-25 at 10 22 54" src="https://github.com/user-attachments/assets/2fd6c2cc-ccf3-4845-a2b9-08122ab753c2">

**Comment by noeliaSD** [comment]
I've added this task according to the conversatio the _desktop team_ had yesterday but probably we need to sync and see if the final solution is just **hidding** them to be aligned with the proposal in here: https://www.notion.so/Send-and-Bridge-simplification-proposal-e7f49dd1837748d696822d90e5742dcc

**Comment by noeliaSD** [comment]
Marked as `blocked` since we need here to take some decissions:
cc: @iurimatias @saledjenic @alaibe @anastasiyaig

**Comment by alaibe** [comment]
@noeliaSD no reason to block that one. Hiding would be too limiting. Beta tag is good to go for now IMO

**Comment by noeliaSD** [comment]
@xAlisher where to put the `Beta` here?

**Comment by xAlisher** [comment]
> @xAlisher where to put the `Beta` here?

Where is the latest design for this modal? I'm seeing different design here 

![image](https://github.com/user-attachments/assets/73358599-2458-42c8-8d8d-988195778322)
https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&t=hlhedGAotKoUdaSV-1

**Comment by saledjenic** [comment]
Closing this in favour of this one https://github.com/status-im/status-desktop/issues/15833

**Comment by noeliaSD** [comment]
> https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&t=hlhedGAotKoUdaSV-1

This is the last discussion we had with @benjthayer : https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=23970-465372&t=rHtwlMOIQP3DHDoj-0
