### ISSUE TITLE
Remove or rewrite the `Welcome Beta` initial popup

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15796]
### Description

Currently the application initially shows the following popup:

![image](https://github.com/user-attachments/assets/f8edec35-fbbe-4954-9321-c7d0d396ae8b)

Since they have been added `Beta` tags to the experimental features, maybe this popup is redundant and we can remove it. Alternatively, we can rewrite.

Also, depending on the decission taken, there's the following onboarding popup that could be necessary to be rewritten since in the first sentence it refers to `Status Desktop Beta`.

![image](https://github.com/user-attachments/assets/1f77753d-d59b-4ed6-976f-84daf2bc6af2)

**Comment by noeliaSD** [comment]
@iurimatias assigned to you to take the final decision on how to proceed with it. Once decided, the `ui-team` can work on the solution.

**Comment by alexjba** [comment]
@iurimatias Should we keep these popups?

**Comment by iurimatias** [comment]
closing since we're keeping it
