### ISSUE TITLE
Wallet/SendModa: Send with bridging ends with status-go error popup

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15797]
# Bug Report

## Description

Sending ETH using custom routing involving bridging ends with status-go error.

![Screenshot from 2024-07-25 11-19-00](https://github.com/user-attachments/assets/99fb4285-a304-412f-a1b5-18738559eb3d)

## Steps to reproduce
1. Open send modal, select account with ETH on Mainnet
2. Go to "Advanced" tab in "Networks" panel
3. Disable Mainnet on a receiver side
4. Send

#### Expected behavior
Transaction is executed

#### Actual behavior
Error popup is presented to the user.

**Comment by jrainville** [comment]
@anastasiyaig @saledjenic close if already fixed thanks

**Comment by saledjenic** [comment]
Was already reported and fixed here:
https://github.com/status-im/status-desktop/issues/15722
