### ISSUE TITLE
SwapSignModal: inconsistent/incorrect decimal value formatting

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15790]
# Bug Report

![image](https://github.com/user-attachments/assets/67e38f1d-04a7-4e6d-826c-c18dba372c09)

Some decimals are correctly formatted according to the locale (`0,1`), some not (`0.1`)

The code is wrong:
```qml
subtitle: qsTr("%1 to %2")
    .arg(root.currencyStore.formatCurrencyAmount(fromTokenAmount, fromTokenSymbol))
    .arg(root.currencyStore.formatCurrencyAmount(toTokenAmount, toTokenSymbol))
```

as those value formatting functions expect a number while we deal with strings here (fromTokenAmount, toTokenAmount)

### Additional Information

- Status desktop version: linux
- Operating System: master

**Comment by caybro** [comment]
CC @Khushboo-dev-cpp

**Comment by caybro** [comment]
We have this (very naive) function to deal with such string-numbers:
```qml
function formatBigNumber(number: string, decimals = -1) {
        if (!number)
            return ""
        const big = SQUtils.AmountsArithmetic.fromString(number)
        const resultNum = decimals === -1 ? big.toFixed() : big.round(decimals).toFixed()
        return resultNum.replace('.', Qt.locale().decimalPoint)
    }
```

which does the job well.. but needs to know the desired amount of decimals after the separator. Can we get that from the backend @dlipicar ?

**Comment by micieslak** [comment]
> We have this (very naive) function to deal with such string-numbers:
> 
> ```qml
> function formatBigNumber(number: string, decimals = -1) {
>         if (!number)
>             return ""
>         const big = SQUtils.AmountsArithmetic.fromString(number)
>         const resultNum = decimals === -1 ? big.toFixed() : big.round(decimals).toFixed()
>         return resultNum.replace('.', Qt.locale().decimalPoint)
>     }
> ```
> 
> which does the job well.. but needs to know the desired amount of decimals after the separator. Can we get that from the backend @dlipicar ?

When it's only about final displaying, probably you can convert to js number and use existing formatters here.
