### ISSUE TITLE
Add additional information to the `Beta` tags

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15795]
### Description
Add additional information to the `Beta` tags added in the application. One option could be as a _tooltip_ like in here:

[Figma](https://www.figma.com/design/bZJgpgchRfMGIKNBoyYUh8/Experimental-tag?node-id=31-3746&t=OR3ihpCDVCgfJkth-1)

The **mobile** product will incorporate this additional information like this: https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=16352-56074&t=FaoguIBuruqiMZbn-1 and probably the **desktop** product should have the same / similar approach.

**Comment by noeliaSD** [comment]
@xAlisher @pedro-et we need your input here. We also thing it would be more clarifying to the user to have additional information whenever the `Beta` tag is added.

**Comment by noeliaSD** [comment]
For the **Activity** tab in **Wallet**, we have this new design: 

[Design](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&t=e9ipUXABtxAfVSYW-1)

![image](https://github.com/user-attachments/assets/4a2c41ea-0165-4b65-af01-355c63ac3149)

**Comment by noeliaSD** [comment]
@benjthayer we have this additional information design for `Activity`. Can you give us some other ideas for the rest of `Beta` tags? some tooltips maybe?

@jrainville do we still want this additional info??

**Comment by noeliaSD** [comment]
> > @jrainville do we still want this additional info??
> 
> @noeliaSD yeah I think it could be good to have some small tooltips on the different Beta tags, to add info about what could go wrong.
> 
> I don't think we need much design input on this since we can just reuse the existing tooltip component and we know what are the possible issues. I can try to compile a list of the paces and the text we could put on them so you can review.

Ok, thank you @jrainville ! Please share here the texts to add to the tooltips and @caybro will add them in the app!

**Comment by caybro** [comment]
My suggestions: 

> * Account order: don't know 🤷  cc @noeliaSD @saledjenic
> * Manage tokens: don't know 🤷 cc @noeliaSD @saledjenic

"Under construction, you might experience some minor issues"
