### ISSUE TITLE
Swap:: No balance shown when there is sufficient balance

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#15802]
# Bug Report

## Description

The modal shows "No balance" when there is balance available and after after auto refresh the message goes away

## Steps to reproduce

1. Launch SwapModal
2. Try to swap a small DAI value to Eth

#### Expected behavior

No error

#### Actual behavior

https://github.com/user-attachments/assets/c8470515-66f4-49d9-bee4-169909bd5a1c

### Additional Information

- Status desktop version:
- Operating System:

**Comment by dlipicar** [comment]
Couldn't reproduce this :(
Neither on master nor the Release build.

Could you try it again @Khushboo-dev-cpp ? Also perhaps share your log files to see if there's anything weird.

**Comment by Khushboo-dev-cpp** [comment]
<img width="1719" alt="image" src="https://github.com/user-attachments/assets/c6df716c-d000-4c4a-b61d-fae9721ae6e1">
 on release!

**Comment by Khushboo-dev-cpp** [comment]
not able to reproduce this issue on latest release! Will close it until someone notices this again. Its perhaps fixed with another PR
