### ISSUE TITLE
dApps - When disconnecting from Zapper app, Status app does not reflect this and shows connection

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15815]
# Bug Report

## Description

When initiating logging out (disconnect) from Zapper dapp, Status app does not receive its signal

## Steps to reproduce

1. connect to Zapper with status app through wallet connect
2. in Zapper dapp, disconnect (log out)

#### Expected behavior

Status app receives the signal and disconnects from the dapp

#### Actual behavior

Shows as connected

<img width="1796" alt="Screenshot 2024-07-25 at 18 26 26" src="https://github.com/user-attachments/assets/b6d4e9a0-d318-460f-8b39-fb55bfa88b24">

<img width="2032" alt="Screenshot 2024-07-25 at 18 26 32" src="https://github.com/user-attachments/assets/b2c86140-d13c-4f96-9989-1ec4137f6e7d">

### Additional Information

- Status desktop version: master, with dapps
- Operating System: macOS, Chrome

**Comment by anastasiyaig** [comment]
@Seitseman can you pls take a look at this one as well?

**Comment by jrainville** [comment]
cc @anastasiyaig @Seitseman is it fixed by that other PR?

**Comment by stefandunca** [comment]
Tried some time an I could not reproduce it.

**Comment by anastasiyaig** [comment]
thats fixed in RC4
