### ISSUE TITLE
Wallet: Display the "Buy" button everywhere

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15813]
# Bug Report

More of a suggestion, as part of the revenue motto, we should display the "Buy" button also on the "All accounts" screen: (we currently only show Send/Swap)

![image](https://github.com/user-attachments/assets/f1fdd52a-8d08-47e9-8688-f4ea6fbdaab5)

We display the Buy button on every individual account, even the watch ones:
![image](https://github.com/user-attachments/assets/975bfb53-c887-4091-871a-517bd5e4a7f0)

### Additional Information

- Status desktop version: linux
- Operating System: master

**Comment by 86doteth** [comment]
would like to see the same for bridge and other wallet buttons. bit tiring to tap on an asset to then realize ‘fuck i tapped it from the all accounts screen’ then to the specific account and *then* on the asset again before finally getting the wallet functions available 😅
