### ISSUE TITLE
Swap: SNT is disabled w/o reason

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#15810]
# Bug Report

## Description

SNT asset is disabled in swap window.

![image](https://github.com/user-attachments/assets/e6bd23c6-a166-4a1b-9942-607becde935d)

## Steps to reproduce

1. I swapped ETH to SNT.
2. Then I opened Swap window to swap again.

#### Expected behavior

My assets should be enabled to use. And if they are disabled I should know why (some label).

#### Actual behavior

SNT asset is disabled

**Comment by endulab** [comment]
Ok, my bad. I had SNT set in Receive.

**Comment by caybro** [comment]
> Ok, my bad. I had SNT set in Receive.

Yeah, that's exactly the reason :laughing:
