### ISSUE TITLE
Send modal adjustments

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#15833]
We're keeping the multichain send for 2.30 for sure and will re-evaluate it for 2.31.

Since simple, advanced and custom tabs are just different views (UI) of the same complex thing under the hood the following has been decided for 2.30:
- the simple tab needs to show a beta warning when it detects a multichain transaction
- disable access to the custom tab
- show a beta label on the advanced tab

**Comment by noeliaSD** [comment]
Here a comment that should be also tracked here: https://github.com/status-im/status-desktop/issues/15793#issuecomment-2250158187

**Comment by noeliaSD** [comment]
Here a comment that should be also tracked here: https://github.com/status-im/status-desktop/issues/15793#issuecomment-2250158187

**Comment by saledjenic** [comment]
> Here a comment that should be also tracked here: [#15793 (comment)](https://github.com/status-im/status-desktop/issues/15793#issuecomment-2250158187)

@noeliaSD it's not about the beta tag, it's about UI, so you can create an issue for the UI team to update Send modal according to Figma.
