### ISSUE TITLE
Communities: Owner token / Token Master token not visible in community settings

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15830]
# Bug Report

## Description
Token master was minted for a community. It's visible in the wallet (with icon is missing), but not visible in community settings, blocking minting of another assets/collectibles.

[Screencast from 26.07.2024 14:28:13.webm](https://github.com/user-attachments/assets/36d92f01-92ba-4b02-96a2-4223f5c563f3)

## Steps to reproduce
1. Create community
2. Mint owner/token master tokens
3. Optionally airdrop some token master tokens to your wallet
4. Wait/restart app to have tokens visible in a wallet
5. Check community settings, Tokens tab

#### Expected behavior
Tokens are always visible in Community Settings/Tokens tab

#### Actual behavior
Tokens are visible only every ~second app restart

### Additional Information
master, `ff005a219a5f0008c418332ea2cdf6efc851f130`

**Comment by jrainville** [comment]
@friofry could this be a regression of the work you did, or maybe just a remaining bug?

**Comment by friofry** [comment]
Yeah, looks very similar, I'll check on Monday

**Comment by friofry** [comment]
As @jrainville and @micieslak suggested, I was able to reproduce it reliably on testnet:
1. Have a community with minted tokens
2. Turned off the network
3. Restart the application, see the banner that Infura is not available
4. Open the Wallet tab. See all the community tokens available
5. Open Community -> Tokens, screen is empty

continue investigating
