### ISSUE TITLE
Amount Input Field Blocked Despite Sufficient Balance

### ISSUE THREAD

**Issue by belalshehab** [status-im/status-desktop#15853]
# Bug Report

## Description

Occasionally, users are unable to input the amount they want to send in the wallet, even if their account has a positive balance. This issue is accompanied by a "balanceExceeded" error in the logs, despite the entered amount being within the available balance.

## Steps to reproduce

1. start the app
2. navigate to wallet
3. choose an account with balance greater than zero.
4. Verify that the displayed max send amount is also greater than zero.
5. Attempt to enter any amount in the "amount to send" field.

#### Expected behavior

The user should be able to enter any amount up to their available balance without encountering an error.

#### Actual behavior
The user is unable to enter any number in the "amount to send" field, regardless of whether it's within their available balance.

### Additional Information

occurrence: This bug occurs approximately 20% of the time.

recovery:  Restarting the app seems to resolve the issue temporarily.

Error Log: The following error message is observed in the logs:
`ERR 2024-07-29 13:50:01.932+03:00 qt error                                   topics="qt" tid=562554 text="\ncmp (qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:163)\nexpression for balanceExceeded (qrc:/imports/shared/popups/send/SendModal.qml:462)\nexpression for errorType (qrc:/imports/shared/popups/send/SendModal.qml:105)\nexpression for errorType (qrc:/imports/shared/popups/send/SendModal.qml:636)\nopen (qrc:/app/mainui/AppMain.qml:1613)\n (qrc:/app/AppLayouts/Wallet/WalletLayout.qml:327)\nonClicked (qrc:/app/AppLayouts/Wallet/panels/WalletFooter.qml:110)" file=qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:163 category=default`

https://github.com/user-attachments/assets/ad6e37de-c8e2-41be-8ecd-5bbf0e2cf66a

- Status desktop version:
- Operating System:
MacOs

**Comment by saledjenic** [comment]
@noeliaSD @micieslak could you check this one?

**Comment by micieslak** [comment]
I cannot reproduce. @belalshehab, could you check once again on the recent release branch?
