### ISSUE TITLE
dApps - Missing disconnect session call when disconnecting from a dapp

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15886]
### Description

When disconnecting from a dapp in Status, the wallet is shown as connected in dapp itself in browser until the page is refreshed
If disconnectSession is emitted, then the dapp should react to it

https://github.com/user-attachments/assets/ee6ee0d4-530d-4edf-8333-805388608945

```
(defn disconnect-session
  [{:keys [web3-wallet reason topic]}]
  (oops/ocall web3-wallet
              "disconnectSession"
              (bean/->js {:topic  topic
                          :reason reason})))
```

**Version:** **2.30 RC2**

**Comment by stefandunca** [comment]
There is no mode of signaling outside WalletConnect SDK API which we use for disconnecting a dApp. I also tested with the test wallet and the `rarible.com` doesn't process the disconnect session event: https://react-web3wallet.vercel.app/sessions

**Comment by anastasiyaig** [comment]
@stefandunca could you please elaborate? So this specific dapp does not do what we want? because i tested other dapps and they seem to work

**Comment by stefandunca** [comment]
> ... So this specific dapp does not do what we want?  ...

Yes, they don't respond to the session delete notification that is triggered by the WC SDK when we disconnect a session. Nothing we can do about it. The fact that after refresh it is disconnected it means that they process it at some point but not dynamically.
Also testing with another wallet confirms this.

**Comment by anastasiyaig** [comment]
alright then we simply can close that :)
