### ISSUE TITLE
Hard to message contacts

### ISSUE THREAD

**Issue by arnetheduck** [status-im/status-desktop#1589]
In the contacts list, when I click a username, nothing happens - instead, I have to look for 3 tiny dots that have pretty low contrast far to the right -  it's even hard to match them up with a contact due to the length of empty space between - would be nice to be able to click the whole list item instead.

**Comment by PascalPrecht** [comment]
So turns out the contact list didn't have the width it was supposed to have. I've send a PR that changes that, maybe that fixes your problem?

Otherwise we need to discuss this with @simonricoo and go back to the drawing board.

**Comment by arnetheduck** [comment]
well, not really - the extra dots feel more like something that makes my life harder - they take up space, are harder/smaller to click and don't... provide any value. 

for reference, telegram/discord/irc.. really all "lists" in desktop apps allow you to click on the list item text to do stuff - file managers etc

**Comment by arnetheduck** [comment]
just for the record, even in the app, all other lists behave like normal - you don't need to click hard-to-see dots in the list of active conversations for example

**Comment by PascalPrecht** [comment]
Looping in @simonricoo 
I think we need to redesign the contacts list on that regard

**Comment by simonricoo** [comment]
So lets start step by step:
1. Increase icon container on 32x32
<img width="94" alt="Screenshot_2021-01-14_at_11_04_30" src="https://user-images.githubusercontent.com/52249767/104582036-aed4de00-565f-11eb-83e0-66f938774d84.png">
2. Fix list item behaviour: https://github.com/status-im/nim-status-client/issues/1663
3. Contact list item behaviour = on click open chat
4. See figma contact list new design: https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=2123%3A0
5. See video
https://user-images.githubusercontent.com/52249767/104582191-ddeb4f80-565f-11eb-97cd-91cd3473381b.mov
6. Try prototype
https://www.figma.com/proto/eHgUBBg80qvAjI48Mq4OhS/Prototype-Status-Desktop-Contact-List-Item?node-id=1%3A2063&viewport=943%2C262%2C0.21522438526153564&scaling=min-zoom
