### ISSUE TITLE
All my accounts appear as Keycard accounts even though they are normal accounts

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15899]
# Bug Report

## Description

![image](https://github.com/user-attachments/assets/20c999d4-ef13-40e7-bb1e-c13779aae736)

## Steps to reproduce

I just opened the app (upgraded now to RC2). I don't recall seeing this on RC1

#### Expected behavior

Accounts show as normal accounts

#### Actual behavior

Accounts have the keycard account

### Additional Information

- Status desktop version: 2.30 RC2
- Operating System: Ubuntu 22

**Comment by jrainville** [comment]
cc @noeliaSD @saledjenic I'm not sure if it's UI or Wallet core issue

**Comment by jrainville** [comment]
It also prevent me from sending transactions or do anything in the wallet, as it thinks my account is a keycard for real:
```
DBG 2024-07-30 13:38:31.596-04:00 NewBE_callPrivateRPC                       topics="rpc" tid=136155 file=core.nim:27 rpc_method=wallet_createMultiTransaction
keycard - listing readers
keycard - waiting for card
ERR 2024-07-30 13:38:32.319-04:00 unexpected error while keycard signing transaction topics="wallet-send-module" tid=136155 file=module.nim:268
```

**Comment by alexjba** [comment]
Ohh, I have the same issue on rc2! RC1 was fine

**Comment by saledjenic** [comment]
@jrainville could you please check if it's reproducible in the build from this PR: https://github.com/status-im/status-desktop/pull/15917 cause it handles migration issues on the statusgo side which caused this behaviour.

**Comment by jrainville** [comment]
@saledjenic it seems like this fixed the issue. My account no longer shows as a keycard account. However, in the bridge modal, it only shows DAI now (of which I have 0), but I guess that's an unrelated issue

I can confirm that a basic send worked fine.
