### ISSUE TITLE
Profile showcase: Cancel button doesn't work

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15904]
# Bug Report

## Description

If you put a collectible in the verified section of profile showcase, the Cancel and Save buttons appears. Pressing the Cancel button doesn't work.

[no-cancel.webm](https://github.com/user-attachments/assets/6ff1a0be-5772-4f40-8db8-7c087924eb23)

(in the video, I manually undo the action, but that is no necessary to reproduce, the cancel doesn't work even if you just put the collectible in)

Log when pressing the button:
```
WRN 2024-07-30 14:02:19.064-04:00 qt warning                                 topics="qt" tid=136155 text="TypeError: Type error" file=qrc:/app/AppLayouts/Profile/stores/ProfileStore.qml:138 category=default
```

## Steps to reproduce

0. Have community collectibles
1. Go to profile
2. Select Collectibles
3. Put a collectible in Verified
4. Click cancel

#### Expected behavior

State goes back to the original position before modifying

#### Actual behavior

Nothing happens

### Additional Information

- Status desktop version: 2.30 RC2
- Operating System: Ubuntu 22

**Comment by caybro** [comment]
Calls:
```qml
profileStore.resetSocialLinks()
```

Which is (was) slated to be removed as part of https://github.com/status-im/status-desktop/issues/13688:
```qml
    // Social links related: All to be removed: Deprecated --> Issue #13688
    function containsSocialLink(text, url) {
        return root.profileModule.containsSocialLink(text, url)
    }

    function createLink(text, url, linkType, icon) {
        root.profileModule.createLink(text, url, linkType, icon)
    }

    function removeLink(uuid) {
        root.profileModule.removeLink(uuid)
    }

    function updateLink(uuid, text, url) {
        root.profileModule.updateLink(uuid, text, url)
    }

    function moveLink(fromRow, toRow, count) {
        root.profileModule.moveLink(fromRow, toRow)
    }

    function resetSocialLinks() {
        root.profileModule.resetSocialLinks()
    }

    function saveSocialLinks(silent = false) {
        root.profileModule.saveSocialLinks(silent)
    }
    // End of social links to be removed
```

but somehow didn't get removed; and since the call is used inside a JS block, it breaks the code flow 

CC @MishkaRogachev 

@jrainville I'm inclined to say `backend-team` :)

**Comment by caybro** [comment]
But I can take this and just remove the code if that's all it takes :)

**Comment by jrainville** [comment]
> But I can take this and just remove the code if that's all it takes :)

We can take it, thanks for looking into it.
