### ISSUE TITLE
Bridge modal Simple mode's scroll is very clunky

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15902]
# Bug Report

## Description

If I try to bridge SNT from mainnet to something else, it doesn't let me do it because the screen doesn't scroll if I'm top of the middle part. I need to put the mouse on the side. See video:

[scroll.webm](https://github.com/user-attachments/assets/01af7801-1a19-4b11-a115-217f1cddf49e)

You probably can't see super clearly in the video, but when nothing happens, I'm using the scroll wheel on my mouse and nothing moves. When I go on the side, then it works

## Steps to reproduce

1. Go to wallet section
2. Select Bridge
3. Select a token (eg SNT)
4. Wait for the chains to appear
5. Try to scroll with your mouse over the networks

#### Expected behavior

The content can be scrolled as usual

#### Actual behavior

Can't scroll on top of the network container

### Additional Information

- Status desktop version: 2.30 RC2
- Operating System: Ubuntu 22

**Comment by jrainville** [comment]
cc @noeliaSD

**Comment by caybro** [comment]
Some kind of ListView/Flickable obstructing the overall scroll again I assume
