### ISSUE TITLE
The app doesn't die when closing with the X (or right click - close on Mac)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#15939]
# Bug Report

## Description

If you close the app with the X button (and most likely with any other means other than CTRL-C), it doesn't die (stays "logging out...")

## Steps to reproduce

1. Open the app in a console
2. Login
3. Make the computer go to sleep
4. Come back from sleep
5. Close the app with the X
6. See the console

#### Expected behavior

The app dies in less than 5 seconds

#### Actual behavior

The app doesn't die even after 2 minutes

### Additional Information

- Status desktop version: 2.30 RC3
- Operating System: Ubuntu 22

**Comment by jrainville** [comment]
I tried with a very basic account that only has one community (1 member) and it closes fine.

So then I retried my main account on the latest release branch.. and it doesn't reproduce. Alright then. I'll close

**Comment by jrainville** [comment]
I was able to reproduce and I know the repro step now: It happens after coming back from sleep!
I'll update the description.

@igor-sirotin can you check if you can repro on Mac?

**Comment by igor-sirotin** [comment]
@jrainville seem to be working fine for me on Mac 🙁

**Comment by igor-sirotin** [comment]
I think I accidentally faced the same behaviour. 
<img width="464" alt="image" src="https://github.com/user-attachments/assets/0b85e358-f822-47b5-818a-7d2cf4e9b33f">
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/d9c1c535-5121-46b0-a2e9-72b8a55874fe">

Attached debugger, it didn't really help.
I noticed that the thread 1 is `CrBrowserMain`, which is weird.

After some point the CPU usage came down:

<img width="467" alt="image" src="https://github.com/user-attachments/assets/a40572ec-35e6-4773-82f1-f5bec548b3e7">

## MacOS hang report

After killing the app I saved 90k lines MacOS report.
Some interesting notes from it:

```nim
Heaviest stack for the main thread of the target process:
  79  runtime.asmcgocall.abi0 + 200 (libstatus.dylib + 485480) [0x10d7ba868]
  79  <patched truncated backtrace>
  79  runtime.pthread_cond_wait_trampoline.abi0 + 24 (libstatus.dylib + 491352) [0x10d7bbf58]
  79  __psynch_cvwait + 8 (libsystem_kernel.dylib + 18924) [0x19fd7d9ec]
 *79  psynch_cvcontinue + 0 (com.apple.kec.pthread + 18232) [0xfffffe000b834a58]
```

```nim
  Thread 0xdf9dec    DispatchQueue "com.apple.main-thread"(1)    Thread name "CrBrowserMain"    79 samples (1-79)    priority 46 (base 46)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [423], IO tier 0>
  79  runtime.asmcgocall.abi0 + 200 (libstatus.dylib + 485480) [0x10d7ba868] 1-79
    79  <patched truncated backtrace> 1-79
      79  runtime.pthread_cond_wait_trampoline.abi0 + 24 (libstatus.dylib + 491352) [0x10d7bbf58] 1-79
        79  __psynch_cvwait + 8 (libsystem_kernel.dylib + 18924) [0x19fd7d9ec] 1-79
         *49  psynch_cvcontinue + 0 (com.apple.kec.pthread + 18232) [0xfffffe000b834a58] 1-49
  <2000ms gap with no samples>
         *30  psynch_cvcontinue + 0 (com.apple.kec.pthread + 18232) [0xfffffe000b834a58] 50-79
```

**Comment by jrainville** [comment]
On the latest release branch, I can't reproduce so far with a pretty small account.

I'll try with my main account to see if it's something about having some sort of wallet account or community

**Comment by jrainville** [comment]
hmm, even with my main account, I can no longer reproduce 🤔 

I'm fairly sure I could reproduce in dev, so it shouldn't be about that. I'll give it a try with a recent release build just in case

**Comment by jrainville** [comment]
I still can't reproduce from just going to sleep, waking up and closing.

So I guess to reproduce, I need to wait longer before closing. Maybe some sort of timer needs to trigger first.
Because I did try leaving it sleeping for 30 minutes when going to sleep and it didn't reproduce.

**Comment by jrainville** [comment]
I let it run in dev for 40 minutes after a sleep and then closed it and it closed without issue.

it's very weird, when I don't want to reproduce the issue, it reproduces, but when I try to reproduce, it works fine 😩

**Comment by jrainville** [comment]
I finally had a reproduction on a dev build with my main account. This time, the sleep was for the whole night and I ran it for one hour and a half before trying to close it.

Here are the interesting things in the logs:
- I can see that we have the logout calls in geth.log like `filters uninstall`, `running shutdown task`, `Stopping node`, `Discv5 loop stopped`, etc.
- There seems to be some store node queries being sent after those logouts still: `messages for next store hash query`
- Some errors being thrown after it all `Error sending messages.`, `Failed to persisten epoch`, `Failed to get pending transactions`,  etc.
- Some calls seem to still be calling from time to time even 5 minutes after the logout: `Evicting item from balance/nonce cache`
- Nothing listed in the Nim logs

Here are the full logs:
[geth.log](https://github.com/user-attachments/files/16549758/geth.log)

Now I'll try to compare with a successful app close

**Comment by jrainville** [comment]
Ok, on a successful close, the amount of logs is way lower. We still have some of the same logs as before, for example `Error sending messages.` and `Failed to persisten epoch`.

However, I see in the end `Epoch processing stopped`, there is no `Failed to get pending transactions`, no `Evicting item from balance/nonce cache`, and I don't see `messages for next store hash query` after the logout

Geth log of a success:
[geth.log](https://github.com/user-attachments/files/16550018/geth.log)

**Comment by jrainville** [comment]
I have another repro, this time on the release app.

I don't see `messages for next store hash query`, so that was probably a red herring.

Some logs are still there though, like `Failed to get pending transactions`. I think I'll investigate if that pending transaction loop fails to close itself

[geth.log](https://github.com/user-attachments/files/16564704/geth.log)

**Comment by jrainville** [comment]
Another repro. Still the same logs that happen again, ie `Failed to get pending transactions`.

This one was there again too `Evicting item from balance/nonce cache`

[geth.log](https://github.com/user-attachments/files/16565397/geth.log)

**Comment by jrainville** [comment]
turns out the main issue was with a waitGroup in the waku package that didn't call its Done and the Telemetry service that didn't use the context
