### ISSUE TITLE
Some limits for Wallet section

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#15934]
**Initial proposal:**
~We should limit the number of:~
~- keypairs to 3 (excluding profile keypair)~
~- accounts per keypair to 5~
~- watch only accounts to 3~
~- saved addresses to 20~

----
**After the discussion** 

Discord discussion starts here https://discord.com/channels/1210237582470807632/1254827811873620068/1268470171232899145 the following is decided:

- limit the number of accounts to 20 (it includes all accounts, keyapir + watch-only)
- limit keypairs to 5 (including profile keypair)
- limit watch-only accounts to 3
- limit saved addresses to 20 (this doesn't count in accounts limit)

When the user tries to add:
- 21st account, a popup should appear saying "Limit of 20 accounts reached. Please remove an account to add a new one." (the popup has 2 options, "Cancel", "Manage accounts")
- 6th key pair, a popup should appear saying "Limit of 5 key pairs reached. Please remove a key pair to add a new one." (the popup has 2 options, "Cancel", "Manage keypairs")
- 4th watch-only account, a popup should appear saying "Limit of 3 watched addresses reached. Please remove a watched address to add a new one." (the popup has 2 options, "Cancel", "Manage accounts") 
- 21st saved address, a popup should appear saying "Limit of 20 saved addresses reached. Please remove a saved address to add a new one." (the popup has 2 options, "Cancel", "Manage addresses") 

----

The mobile team should be aware of this change as well.
@ilmotta @J-Son89

**Comment by J-Son89** [comment]
Hey @saledjenic this all sounds great but it's really a product decision. Did we get some input from design too. Seems like something to discuss first! Definitely in agreement on the general direction though.

**Comment by ilmotta** [comment]
Thanks @saledjenic. I don't understand the specifics in the wallet, but would be good to add some context to each number, otherwise they seem arbitrary. What are the technical reasons to impose the limitation about each bullet point?

**Comment by saledjenic** [comment]
Having limits which we do not have atm, is definitely something good, this way we can hear from our users what they really want/need. It's easy to increase those limits later if we really need to do that. Leaving the app without limits, when even we as developers don't know how well it performs with many accounts, is not something we should push for.

The rationale behind this decision is at first that performance, then hitting the providers (network/prices) limit.

We can discuss the numbers...
- but adding 3 keypairs (without counting profile keypair) while each of them may have up to 5 accounts max, sounds ok to me,
- limiting watch-only accounts to 3 also sounds reasonable (since these accounts potentially can be very heavy for handling in terms of loading their history), but we have another issue for hiding adding new watch-only accounts (this has to be synced with the mobile team @ilmotta @J-Son89, this is the decision fo 2.30), editing/removing watch-only accounts sounds remains https://github.com/status-im/status-desktop/issues/15933
- for saved addresses I am not sure, maybe letting the user add up to 20 addresses sounds ok for the start


@ilmotta @J-Son89 @alaibe @iurimatias opinions?

**Comment by J-Son89** [comment]
> Having limits which we do not have atm, is definitely something good, this way we can hear from our users what they really want/need. It's easy to increase those limits later if we really need to do that. Leaving the app without limits, when even we as developers don't know how well it performs with many accounts, is not something we should push for.
> 
> The rationale behind this decision is at first that performance, then hitting the providers (network/prices) limit.
> 
> We can discuss the numbers...
> 
> * but adding 3 keypairs (without counting profile keypair) while each of them may have up to 5 accounts max, sounds ok to me,
> * limiting watch-only accounts to 3 also sounds reasonable (since these accounts potentially can be very heavy for handling in terms of loading their history), but we have another issue for hiding adding new watch-only accounts (this has to be synced with the mobile team @ilmotta @J-Son89, this is the decision fo 2.30), editing/removing watch-only accounts sounds remains [Remove Functionality for Adding New Watch-Only Accounts #15933](https://github.com/status-im/status-desktop/issues/15933)
> * for saved addresses I am not sure, maybe letting the user add up to 20 addresses sounds ok for the start
> 
> @ilmotta @J-Son89 @alaibe @iurimatias opinions?

@saledjenic - I think it's best to move this discussion into the organisation where Design have a chance to contribute etc to.
Can we discuss in the product chat?

I had no idea about this issue to disable adding new watch only addresses. Thanks for raising it. I think it's better to raise it in chat as more likely to be seen/discussed properly.
cc @belalshehab

**Comment by benjthayer** [comment]
New designs added preventing user from adding account, watched address or key pair once their respective limit has been reached:

User attempts to add new account from main Wallet UI while account limit reached:
https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=24955-171232&t=UQ4HvtPr0wqCoRrk-4

User attempts to add new watched address from main Wallet UI while watched address limit reached:
https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=24955-171521&t=UQ4HvtPr0wqCoRrk-4

User attempts to add new key pair from main Wallet UI while key pair limit reached:
https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=24956-49610&t=UQ4HvtPr0wqCoRrk-4

User attempts to add new account from Wallet Settings UI while account limit reached:
https://www.figma.com/design/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=24898-94983&t=IxuSDFnpVS3Gwwwd-4

User attempts to add new saved address via Wallet Settings UI while saved address limit reached:
https://www.figma.com/design/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=24898-93848&t=IxuSDFnpVS3Gwwwd-4

cc @saledjenic @xAlisher

**Comment by saledjenic** [comment]
Limits for keycard flows:
- https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=24963-48474&m=dev
- https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=24963-48846&m=dev

**Comment by saledjenic** [comment]
@anastasiyaig user stories added for this issue (new project wallet general created for dealing with wallet global/general stuff):
- https://www.notion.so/Wallet-General-9fd1781dbb274a0f9064b1e182ea41f2
