### ISSUE TITLE
[Instructions] Building on Fedora

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#15978]
Issue to describe steps to successfully compile on Fedora

### Install QT 5.15.2 (with online installer)

Get the online installer [here](https://www.qt.io/download-qt-installer-oss?utm_referrer=https%3A%2F%2Fwww.qt.io%2F)
Then run it:

```
cd ~/Downloads
chmod +x qt-online-installer-linux-x64-4.8.0.run
./qt-online-installer-linux-x64-4.8.0.run
```

1. Create account and login
2. Select "Custom installation". Remember your "Installation folder". It defaults to `/home/<username>/Qt`. I change it to `/home/<username>/.local/lib/Qt`
4. click "Archive" and then "Filter":

![image](https://github.com/user-attachments/assets/f60f107b-e883-413e-a001-ffacfb558faa)

Select "Qt 5.15.2" and proceed to install.

then sort your exports:

```
export QTDIR=~/.local/lib/Qt/5.15.2/gcc_64
export PATH="${QTDIR}/bin:${PATH}"
```

### OR Install QT 5.15.14 (with `dnf` from Fedora repos)

Alternative method to use QT 5.15.4 that may contain some memory leak fixes:

```
sudo dnf install qt5-qtbase qt5-qtbase-devel qt5-qtquickcontrols
```

Setup env variables:

```
export QTDIR=/usr/lib64/qt5/
export PATH=$PATH:$QTDIR/bin
```

### Install necessary packages

This seems to be the necessary packages. Do comment if you think one is not needed or you needed more. I did a fresh system install recently so I think it's accurate:

```
sudo dnf install pcsc-lite-devel pcre-devel ssl-devel crypto-devel protobuf-compiler
```

### Install openssl 1.1 dev libs

Openssl 1.1 is not available in Fedora since version [40](https://discussion.fedoraproject.org/t/f40-change-proposal-removing-openssl-1-1-package-system-wide/92899). Meaning with Fedora 39 you should be fine to install openssl-dev 1.1 with `dnf`.

```
sudo dnf install perl-FindBin perl-File-Compare perl-File-Copy perl-Pod-Html
wget https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/openssl-1.1.1w.tar.gz
tar xavf openssl-1.1.1w.tar.gz
cd openssl-1.1.1w
./config --prefix=$HOME/.local/lib/openssl1.1
make && make install
```

If the make files complains about any file not found, remember you can find the package that provides it this way: `dnf provides '*/File/Copy.pm'`

Then sort out your exports:

```
export LD_LIBRARY_PATH=$HOME/.local/lib/openssl1.1/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$HOME/.local/lib/openssl1.1/lib:$LIBRARY_PATH
```

### Compile

Time to build:

```
make update
make run
```

### Troubleshooting

If you encounter any issue, maybe because you did not setup correctly. It's always good to do a clean:

```
make clean
make update
```

Or for a more bruteforce version:

```
git submodule foreach git clean -d -f -x
```

**Comment by fryorcraken** [comment]
Added instructions to install QT 5.15.14 from Fedora repos

**Comment by osmaczko** [comment]
@fryorcraken, based on this issue, I've updated the build instructions in Notion to include Fedora: https://www.notion.so/Building-ca1db4fb3baf4f15bab8da717832b743. Is there anything I might have missed? Are you comfortable with closing the issue so that we can maintain a single source of truth in Notion?

**Comment by fryorcraken** [comment]
> @fryorcraken, based on this issue, I've updated the build instructions in Notion to include Fedora: [notion.so/Building-ca1db4fb3baf4f15bab8da717832b743](https://www.notion.so/Building-ca1db4fb3baf4f15bab8da717832b743). Is there anything I might have missed? Are you comfortable with closing the issue so that we can maintain a single source of truth in Notion?

I would add `export QTDIR=/usr/lib64/qt5/` to the instructions as it may not be evident where Fedora installs QT when using `dnf`. Then you can close yes.

**Comment by fryorcraken** [comment]
protoc is now needed. Instructions here and in notion updated (`protobuf-compiler` package).
