### ISSUE TITLE
Minimize on close makes app icon not repsonding

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15986]
# Bug Report

## Description

![image](https://github.com/user-attachments/assets/6d64faa1-0393-4fbf-b1c5-62fadde77ffb)

## Steps to reproduce

Open app on Windows
Click Cross button
(settings in the app should have the toggle Minimise on close enabled)

#### Expected behavior
App is minimzied and can be opened from the task bar 

#### Actual behavior

App icon is grey, clicking it gives me nothing

### Additional Information

- Status desktop version: release 2.30
- Operating System: Windows

**Comment by jrainville** [comment]
@anastasiyaig can you try again with the latest release branch or RC5? I just tried latest release branch and it worked fine for me on Windows 10

**Comment by jrainville** [comment]
I also tried RC4 and it works for me. Which version of Windows are you on?

**Comment by anastasiyaig** [comment]
i checked in RC 5 and it works fine now

**Comment by jrainville** [comment]
@anastasiyaig I wonder if maybe the issue you had was this one actually: https://github.com/status-im/status-desktop/issues/15939
Are you sure the Minimize on close was on?

**Comment by anastasiyaig** [comment]
Ah perhaps that is it! I was keeping updating my windows app from rc to rc multiple times, maybe i changed the setting and forgot about it
