### ISSUE TITLE
dApp is requesting to connect on an unsupported network error message 

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15993]
# Bug Report

## Description
If a connected dApp is not disconnected from an account, when user wants to connect to it under certain scenarios, `dApp is requesting to connect on an unsupported network` error message shows and dApp cannot be connected.

## Steps to reproduce

1. User connects to a dApp, for example: 
https://yearn.fi/
https://lido.fi/
https://dydx.trade/markets
https://zapper.xyz/

2. Do not disconnect the dApp, and close the app.
3. Log into another instance of the app with the same user or a different one: it can be the same version, for example 2.30 rc-4, or logging into a newer version of the app, going from rc-3 to rc-4, or from latest master build to 2.30.

On the console logs, this is the relevant error message: 
`DBG 2024-08-05 12:14:33.543-03:00 qt message                                 topics="qt" tid=1408782 text="WC WalletConnectSDK.onBuildApprovedNamespacesResponse; approvedNamespaces: -, error: Non conforming namespaces. approve() namespaces methods don't satisfy namespace methods for eip155:1" file=qrc:/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml:383 category=qml
WRN 2024-08-05 12:14:33.544-03:00 qt warning                                 topics="qt" tid=1408782 text="QML StatusBaseInput: Binding loop detected for property \"valid\"" file=qrc:/imports/shared/popups/walletconnect/PairWCModal/WCUriInput.qml:22 category=default
DBG 2024-08-05 12:14:34.165-03:00 NewBE_callPrivateRPC                       topics="rpc" tid=1408782 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport`
Full log here [console log zapper.txt](https://github.com/user-attachments/files/16501086/console.log.zapper.txt)

#### Expected behavior
- We need to clarify if a user under these scenarios is able to connect to a dApp, if not, maybe we should change the error message to one that gives context of what is happening. 
- Instead of the error message, is there anything that can be done to fix this? Can the dApp from the previously logged in instance get disconnected somehow, and thus allowing user to connect to the same dApp on the current instance?

#### Actual behavior
explained on the description

### Additional Information

I also tested two different users, user1 able to connect to Lido while user2 unable. I disconnected Lido dApp and then tried connecting it to user2 with the unlucky results. No error message on the front end but as you can see, the same errors triggered on the console.
As user2 is a profile that I often use for testing, it is very possible that I have connected several dApps while using an older version of the app and this leads me to believe that the dApps are still connected to that old version, and that is the reason why they won't connect for the same user on the new version of the app.

Console log
```
DBG 2024-08-05 15:02:55.082-03:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=79347 file=threadpool.nim:56 messageType=BuildTokensTaskArg:ObjectType threadid=79347 task="{\"$type\":\"BuildTokensTaskArg:ObjectType\",\"accounts\":[\"0x32e12fd7c2c7984dd6de153691d901445fc8aa07\",\"0x9e5b664af1afcaa853155cb3f37ce25384483c1c\",\"0x94bcd7c8b4c1822fe299019d4bdf35625c0c9969\"],\"storeResult\":true,\"vptr\":105553182127616,\"slot\":\"onAllTokensBuilt\"}"
DBG 2024-08-05 15:02:55.082-03:00 NewBE_callPrivateRPC                       topics="rpc" tid=79347 file=core.nim:27 rpc_method=wallet_fetchOrGetCachedWalletBalances
ERR 2024-08-05 15:02:57.621-03:00 error:                                     topics="token-service" tid=79318 file=service.nim:147 errDesription=
DBG 2024-08-05 15:02:57.644-03:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=79345 file=threadpool.nim:56 messageType=BuildTokensTaskArg:ObjectType threadid=79345 task="{\"$type\":\"BuildTokensTaskArg:ObjectType\",\"accounts\":[\"0x32e12fd7c2c7984dd6de153691d901445fc8aa07\",\"0x9e5b664af1afcaa853155cb3f37ce25384483c1c\",\"0x94bcd7c8b4c1822fe299019d4bdf35625c0c9969\"],\"storeResult\":true,\"vptr\":105553182127616,\"slot\":\"onAllTokensBuilt\"}"
DBG 2024-08-05 15:02:57.644-03:00 NewBE_callPrivateRPC                       topics="rpc" tid=79345 file=core.nim:27 rpc_method=wallet_fetchOrGetCachedWalletBalances
WRN 2024-08-05 15:02:57.667-03:00 qt warning                                 topics="qt" tid=79318 text="TypeError: Cannot read property 'symbol' of null" file=qrc:/app/AppLayouts/Wallet/views/LeftTabView.qml:347 category=default
DBG 2024-08-05 15:03:01.345-03:00 qt message                                 topics="qt" tid=79318 text="WC WalletConnectSDK.wcCall.getActiveSessions;" file=qrc:/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml:127 category=qml
ERR 2024-08-05 15:03:01.346-03:00 qt error                                   topics="qt" tid=79318 text="Uncaught TypeError: Cannot read property 'getActiveSessions' of null" file=webpack://wallet_connect_integration/./src/index.js?:122 category=js
DBG 2024-08-05 15:03:09.290-03:00 NewBE_callPrivateRPC                       topics="rpc" tid=79318 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
```

https://github.com/user-attachments/assets/ca1eb966-ef2d-488d-a92b-f7b8ed18a3be

https://github.com/user-attachments/assets/63e82e23-778a-47f6-9444-a90a74bb83e0
![Screenshot 2024-08-05 at 11 46 05 AM](https://github.com/user-attachments/assets/a7a5115f-80ce-4b8a-afc2-8d28ad51d1c7)

This is somewhat hard to reproduce.

- Status desktop version: master build and 2.30 rc-3 and rc-4
- Operating System: Mac OS Sonoma

**Comment by stefandunca** [comment]
@virginiabalducci @alexjba the [console log zapper.txt](https://github.com/user-attachments/files/16501086/console.log.zapper.txt) logs show that dapp requested to connect with account `0x69a4f3ebdeb18d5783848c2558136718837f36bc` but only the following are available `0x32e12fd7c2c7984dd6de153691d901445fc8aa07`, `0x9e5b664af1afcaa853155cb3f37ce25384483c1c`, `0x94bcd7c8b4c1822fe299019d4bdf35625c0c9969`. For this general non-conforming namespace we show chains don't match error because I didn't encountered this accounts mismatch.

For the other errors I see that SDK is not initialized which might happen if you have two status-desktop instances running at the same time. There is a limitation of our SDK runtime that was not high-prio given that this running two instances is not as usual.

**Comment by virginiabalducci** [comment]
Thanks @stefandunca for taking a look at the logs. 
I was able to connect to Zapper dApp by running only 1 Status app instance.

However, I'm noticing the same issue with a dApp I've never connected to before, and running a single Status instance 2.30 rc-4
dApp: https://metamask.github.io/test-dapp/

[console log E2E metamask.txt](https://github.com/user-attachments/files/16515267/console.log.E2E.metamask.txt)

Would you be able to take a look? Let me know if I can provide any other information. Thanks!

**Comment by alexjba** [comment]
Looks like a symptom caused by the shared cookies between app instances. I've reproduced it once, but it involved switching between 2 Status folders containing the same account.

Now I've checked to see if it can be reproduced while migrating, restoring from seed, using multiple accounts and I cannot.

@virginiabalducci I'd move it to 2.31. Seems to be an issue only on development environments

**Comment by alexjba** [comment]
@virginiabalducci Can't reproduce it on latest master. The cookies are now stored in a unique folder for each user. Could you please confirm?

**Comment by virginiabalducci** [comment]
This is no longer reproducible on latest builds. Closing this one.
