### ISSUE TITLE
dApps - Uniswap - incorrect high fees on a Send transaction 

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16008]
# Bug Report

## Description

When user initiates a Send transaction via Wallet Connect Uniswap, the fee on Status's app side is extremely high.

## Steps to reproduce

1. Connect a wallet to Uniswap
2. Initiate a send transaction 
3. Pick a low amount, for example 1 usdt
4. Go to Status app to approve the transaction

#### Actual behavior
Network cost on Uniswap show 0.39

![Screenshot 2024-08-06 at 7 58 50 PM](https://github.com/user-attachments/assets/1a7fd2e5-8741-4267-878c-60acf015c55f)

Max fees on Status are extremely high
154418898,0644262
62417,197416 ETH
![Screenshot 2024-08-06 at 7 58 41 PM](https://github.com/user-attachments/assets/ef374b95-9542-43d2-9369-3e21dcdd62a3)

https://github.com/user-attachments/assets/b4981de9-6096-4647-96f7-54b58fb58a70

#### Expected behavior
Fees should not be that high on Status app

### Additional Information

- Status desktop version: 2.30 rc-4
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
seems related to 15947 and 15991

**Comment by caybro** [comment]
@virginiabalducci pls try to reproduce with the latest RC: https://github.com/status-im/status-desktop/releases/tag/2.30.0-rc.5

**Comment by alexjba** [comment]
Fixed by https://github.com/status-im/status-desktop/issues/15947
