### ISSUE TITLE
[Browser plugin connector] Implement `personal_sign` endpoint

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#16015]
https://docs.metamask.io/wallet/reference/personal_sign/

**Comment by MishkaRogachev** [comment]
Current state:
- status-go part merged
- status-desktop part is [draft](https://github.com/status-im/status-desktop/pull/16047). I did not manage time to finish it

**Comment by caybro** [comment]
CC @alexjba
