### ISSUE TITLE
[Performance] High memory usage with 0 activity on the account

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#16017]
# Bug Report

Looks like there's a regression on latest master in terms of memory consumption. The ram usage goes to 10 GB after login on a new Status account.

## Description

<img width="789" alt="Screenshot 2024-08-07 at 15 00 52" src="https://github.com/user-attachments/assets/1b73ff30-c7d5-477c-a787-c8ff41a4ee2d">

The initial profiling is not conclusive! It seems there's lots of DB and waku activity. But the DB size on disk doesn't grow abnormally. The initial assumption is that it's related to a recent status-go change. Was spotted on a PR after updating the status-go version to the one on master.

<img width="1866" alt="Screenshot 2024-08-07 at 15 35 30" src="https://github.com/user-attachments/assets/819b6729-a500-49f5-9604-52c6538cee1f">

## Steps to reproduce

1. Create a new account
2. Login
3. Wait a few minutes

#### Expected behavior
The memory usage is around 500MB
#### Actual behavior
The memory usage is around 10GB
### Additional Information

- Status desktop version: bef66612c
- Operating System: MacOs

**Comment by alexjba** [comment]
The release branch is not affected as of now.

**Comment by osmaczko** [comment]
Since we are in the stability phase and focused on quality, I believe we should have some kind of monitoring for a few basic scenarios (for instance: app with a new account and nothing else, app with a community, app with an imported wallet account). The first thing that comes to mind is a nightly job that runs the app for a few hours and dumps the memory profile. With this, we would catch memory leaks quicker and identify the culprit easier by reviewing the list of changes made that day.

**Comment by alexjba** [comment]
> Since we are in the stability phase and focused on quality, I believe we should have some kind of monitoring for a few basic scenarios (for instance: app with a new account and nothing else, app with a community, app with an imported wallet account). The first thing that comes to mind is a nightly job that runs the app for a few hours and dumps the memory profile. With this, we would catch memory leaks quicker and identify the culprit easier by reviewing the list of changes made that day.

Good point! We have a task for this that was postponed for much too long IMO. Any suggestions are really appreciated
https://github.com/status-im/status-desktop/issues/13015

**Comment by anastasiyaig** [comment]
its more than that, i think there is a huge degradation in account creation even, for example https://ci.status.im/job/status-desktop/job/e2e/job/prs/1719/allure/#suites/bd9760512df3263fbffb002313961e62/ef2a3acc09a7f868/
none of tests were able to create a new account in the app, because logging in after you click Start using status button takes more than 15 seconds

**Comment by alexjba** [comment]
> its more than that, i think there is a huge degradation in account creation even, for example https://ci.status.im/job/status-desktop/job/e2e/job/prs/1719/allure/#suites/bd9760512df3263fbffb002313961e62/ef2a3acc09a7f868/ none of tests were able to create a new account in the app, because logging in after you click Start using status button takes more than 15 seconds

If it's on PRs than probably we'll need to increase the task priority since it's blocking everyone, right?

**Comment by anastasiyaig** [comment]
@alexjba i was wrong. i found this

```
INF 2024-08-09 12:02:01.437+03:00 logging out...                             topics="app-controller" tid=6001852 file=app_controller.nim:292
tables.nim(232)          raiseKeyError
Error: unhandled exception: key not found:  [KeyError]
```

**Comment by anastasiyaig** [comment]
> > its more than that, i think there is a huge degradation in account creation even, for example https://ci.status.im/job/status-desktop/job/e2e/job/prs/1719/allure/#suites/bd9760512df3263fbffb002313961e62/ef2a3acc09a7f868/ none of tests were able to create a new account in the app, because logging in after you click Start using status button takes more than 15 seconds
> 
> If it's on PRs than probably we'll need to increase the task priority since it's blocking everyone, right?

i also was wrong, it was indeed a problem in PR @alexjba 
sorry i was too fast

**Comment by caybro** [comment]
I was able to reproduce, just created a new empty account, and the RAM usage started skyrocketting... 5 GB right after login, after a few minutes 13 GB, then around 16 GB my laptop froze and eventually the app got OOM killed. I'll try to run hotspot after the new account creation, at least to figure out what are we doing there...

**Comment by caybro** [comment]
OK, so from a brief look at the output of hotspot (master, empty account, debug enabled), it seems that the issue is coming from (status)go:

![image](https://github.com/user-attachments/assets/32a730dc-71c1-44aa-bdf1-29112cbd830c)

Roughly 70% of CPU time of an otherwise idle app is spent on garbage collection which seems to fail somewhere (hence the skyrocketting RAM usage)

**Comment by caybro** [comment]
Worth noting this is happening with a new account only, my regular (oldish) account is not affected

**Comment by caybro** [comment]
The log is filled with repetitive entries like this, and almost nothing else:

```
DEBUG[08-09|10:50:58.203|github.com/status-im/status-go/wakuv2/waku.go:1441]                                         received new envelope                    messageType=relay envelopeHash=0xeeee9a7131e51226775b49
DEBUG[08-09|10:50:58.203|github.com/status-im/status-go/wakuv2/waku.go:1485]                                         cached w envelope                        envelopeHash=0xeeee9a7131e51226775b497a3f4eeceb3bc10266
DEBUG[08-09|10:50:58.203|github.com/status-im/status-go/wakuv2/waku.go:1495]                                         posting event                            envelopeHash=0xeeee9a7131e51226775b497a3f4eeceb3bc10266
DEBUG[08-09|10:50:58.203|github.com/status-im/status-go/wakuv2/common/filter.go:234]                                 no filters available for this topic      message=0xeeee9a7131e51226775b497a3f4eeceb3bc102663856e
DEBUG[08-09|10:50:58.203|github.com/status-im/status-go/wakuv2/waku.go:1555]                                         filters did not match                    envelopeHash=0xeeee9a7131e51226775b497a3f4eeceb3bc10266
DEBUG[08-09|10:50:58.231|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:769]                  wakuV2 storenode status verification
DEBUG[08-09|10:50:58.245|go.uber.org/zap/sugar.go:198]                                                               validation done; took 25.668µs
```

**Comment by caybro** [comment]
Any idea @richard-ramos ?
