### ISSUE TITLE
dApps - Yearn.fi - user can connect wallet but cannot do transactions

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16020]
# Bug Report

## Description

Even though Yearn.fi dApp is connected, user cannot deposit funds to start using the dApp.

## Steps to reproduce

1. Log into an account with some funds
2. Go to https://yearn.fi/ and connect your wallet
3. Choose Yearn.fi V3 and try to deposit some funds, for example DAI ethereum, or USDC ethereum.
4. Click on "Approve" 

#### Expected behavior
Sign approval pop up to show up on Status app

#### Actual behavior
Sign approval pop up does not show up on Status app, flow cannot continue.

https://github.com/user-attachments/assets/bd8b1729-4999-42f5-a9a1-b38381e09ce3

https://github.com/user-attachments/assets/1c582133-ed92-4df9-b8dc-a71791ecb0d7

### Additional Information
[console log Yearn finance.txt](https://github.com/user-attachments/files/16532741/console.log.Yearn.finance.txt)

I haven't seen any relevant issues on the Yearn.fi site itself, this leads me to believe there may be an issue in our end.

- Status desktop version: 2.30 rc-5
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
I can still reproduce this issue on the Status desktop app but this is also reproducible on Trust Wallet mobile app connected to this dApp through Wallet Connect. This leads me to believe that there may be an issue on the dApps's end.

**Comment by virginiabalducci** [comment]
I tried testing this issue again and every time I want to sign a transaction, the desktop app crashes

https://github.com/user-attachments/assets/066d3e3d-fb85-4a86-9e7d-61a84cfe0e71

https://github.com/user-attachments/assets/cdeaf5b4-9c11-4c72-9af2-3098804527d4
[app_20240905_154300.log](https://github.com/user-attachments/files/16899351/app_20240905_154300.log)
[app_20240905_162422.log](https://github.com/user-attachments/files/16899350/app_20240905_162422.log)
[app_20240905_162447.log](https://github.com/user-attachments/files/16899348/app_20240905_162447.log)
[geth 2.log.zip](https://github.com/user-attachments/files/16899355/geth.2.log.zip)

**Comment by alexjba** [comment]
@virginiabalducci We can close this issues as it seems the dApp is broken. There's this error in the dapp logs:
`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.ethereum.useForknetForMainnet')`
