### ISSUE TITLE
Sending messages in community sometimes stays in a 'sending.. ' state and fails even though the message went through

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#16034]
# Bug Report

## Description

It happens sometimes, but I could only see it on 1 client while the other it works fine.

## Steps to reproduce

1. send message in community

![Screenshot 2024-08-05 at 3 03 39 PM](https://github.com/user-attachments/assets/85dae63a-a4b0-45bc-9a14-04f4508128d7)

it says grey while sending, then shows a fail state, but the message actually went through

### Additional Information

- Operating System: Ubuntu

**Comment by Ivansete-status** [comment]
@iurimatias , @igor-sirotin  - a new version with a fix candidate has been deployed in `status.prod`. Kindly check whether the issue is sorted out. Thanks!

**Comment by igor-sirotin** [comment]
Looks better on my side now 👍 
Thanks @Ivansete-status
