### ISSUE TITLE
dApps - issue with shared cookies and app instances

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16036]
# Bug Report

## Description

There is an issue with shared cookies when running multiple instances of the app.
As per AlexJ comment we should make sure we don't run into the same problems in these 2 flows:
1. Upgrading the app (keeping or removing the Status folder)
2. Using multiple accounts

I'd believe a regular user would not change the Status folder, only update the app when a new version is released. Not sure about a user or users sharing a computer having multiple accounts. 

## Steps to reproduce

1. on rc-4 I disconnected all the dApps I had on my test account and closed the app.
2. switched to rc-5 and tried to connect the dApps
3. notification of a successful connection displayed, but when checking the dApps list, there is none.
4. Went back to rc-4, and I'm seeing the dApps that I connected on rc-5, even though I had disconnected them and closed the app.

#### Expected behavior
dApps to show on the application that is currently running, and where the apps are to be synched. Instead of showing in rc-4 where the apps had already been disconnected.

#### Actual behavior
dApps are connected again to rc-4, but this is only visible if rc-4 is re-launched
dApps are not connected to rc-5 even though a successful toast message shows.

2.30 rc-5 app connecting a dApp

https://github.com/user-attachments/assets/1c494198-c679-471c-9665-89096d8ab177

dApp showing on 2.30 rc-4  after intending to connect to rc-5

https://github.com/user-attachments/assets/4626143e-ea9d-4818-a513-8ce80f515f97

### Additional Information
This issue seems to be related to the browser cookies and was solved by deleting the browser cookies. 

- Status desktop version: 2.30 rc-4 and rc-5
- Operating System: Mac OS Sonoma

**Comment by alexjba** [comment]
@virginiabalducci We don't share cookies anymore. Each user has its own cookies folder. Please have a look if we can close this

**Comment by virginiabalducci** [comment]
This is no longer reproducible on latest builds, closing this bug
