### ISSUE TITLE
[dApps] Refactor WalletConnectService to seamlessly operate with multiple SDKs

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#16044]
### Description

WalletConnectService.qml was designed to operate with a single SDK (WalletConnect). But now we also have the Browser Plugin Connector that implements a similar SDK. With the current state the WalletConnectService.qml needs to be patched to support this configuration and tends to become sticky, difficult to maintain and difficult to understand.

The purpose of this task is to analyse the current implementation, design and implement a WalletConnectService component that can seamlessly operate with multiple SDKs with a common API.

**Comment by alexjba** [comment]
https://github.com/status-im/status-desktop/pull/16387#issuecomment-2378969887
> I made a data flow map of how I see BC and WC in the Status app working together and would like to discuss it. Please have a look. [ ![BC_WC data flow](https://private-user-images.githubusercontent.com/86303051/371492580-97b7df00-af79-4b85-b603-c38994397a01.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODM5MTQsIm5iZiI6MTcyNzk4MzYxNCwicGF0aCI6Ii84NjMwMzA1MS8zNzE0OTI1ODAtOTdiN2RmMDAtYWY3OS00Yjg1LWI2MDMtYzM4OTk0Mzk3YTAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDE5MjY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYTU0YWU3OGVmOWVmMzZiNjIyYmQxOTAyZTE2ZDExMjVmYzFhOTQ3Y2ExYjQ5NjdkMjRmNzY1ZmZjNjlmNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qj9m0K_Gf7710H2dsiBtE7SN-Il1dAWmPNwz84b_vWs) ](URL)
> 
> Basically, a dapp is a dapp, and we don't defer daps in the UI how they were connected (via WC or BC). Also, all WC connections are coming from the wallet connect SDK and there is no other way to interact with those dapps except via WcSDK. On the other hand, all requests from the dapps connected via Status Browser Plugin are coming from the statusgo side and no other way to interact with those dapps except via statusgo. Because of that, we know where the request comes from and where we should send the response. Having that in mind we can simplify implementation in a way:
> 
> * `connector_dapps` and `wallet_connect_dapps` tables can be merged into a single one with just a flag to know if the dapp was connected via BC or WC (or maybe better some enum instead of bool flag in case we support some other method in future)
> * we need only WC-related implementation on the qml side (look now how many functions that do the same/almost the same things we have on the qml side, just search the qml for functions like `getTxObject`, `isTransactionMethod`, `prepareData`, `executeSessionRequest`, `extractMethodData`...).
> * we need to map all BC requests to the form that will be recognized by WC implementation in the Stauts app, which is the same form WalletConnect is using.
> 
> @alexjba wdyt about that idea?

@saledjenic I'll move the discussion here as it's more meaningful for this task.

Had a similar view on how we should arrange the building blocks for dApps, so I totally agree on most points.

The only difference is that I've never thought of translating the BC data in WC specific data structures. I'm worried that it could become an overhead for the BC integration. The reasoning behind this idea is that the WC API is quite heavy, with nested JSON objects and some async functions BC doesn't need. It could be an overhead to reuse it for BC and could potentially become difficult to adapt BC data flows to WC data flows. Just imagine trying to implement BC integration with no idea what WC is 😄.

I was actually thinking of having 2 translation layers (Adaptors - in our new terminology), one for BC and one for WC to translate each API to what the UI can consume (UI in this case starts from the service as it represents the abstraction layer). 

In my view the `WalletConnectService` becomes `DAppsService` and knows how to operate with it's own type of objects. E.g. Defines a `SessionProposal` object type with the following properties `chains, dAppUrl, dAppName, dAppIcon, key`. Now all the SDKs that will feed the data in the service needs to adapt its own data to the service data types and flows. And this is where the 2 Adaptors mentioned above come into play.

So we'd end-up with the following list of responsibilities:
- DAppsService: Replacing `WalletConnectService`. Communicates with the 2 adaptors and Wallet store (sign message, authenticate, etc.). This would probably resolve the code duplication you've mentioned.
- BrowserConnectAdaptor: Translate the BC APIs to what the DAppsService and the UI can consume. Replacing current `DappsConnectorSDK`. This Adaptor would probably become really slim as the data for BC is mostly tailored on the current UI needs.
- WalletConnectAdaptor: New component that brings an abstraction on top of WC API. Translates the WC APIs to what the DAppsService and the UI can consume.
- WCRequestHandler: Implementation detail of the WalletConnectAdaptor. Handles WC specific flows, request/response mapping, etc. Mostly maintaining current form.
- WalletConnectSDK: Implementation detail of the WCRequestHandler. Maintaining current form.

**Comment by saledjenic** [comment]
@alexjba I see the point, it makes sense for sure.

But what I see from it is that we will have still a code duplication, in parts of dapps management (connected/disconnected dapps), mapping requests from WC and BC to the form requested by the appropriate service calls.

In this comment https://github.com/status-im/status-desktop/pull/16387#issuecomment-2378969887 I posted an image explaining (maybe not detailed enough, but from some high-level view) what I meant under "we need to map all BC requests to the form that will be recognized by WC implementation" I meant exactly that, so I didn't mean that we need to have **all calls** and those complex jsons that WC is using, but to map calls that BC is using (there are a way less calls that are coming from BC) to WC form and avoid any code duplication.

In that proposal (image) `WC Request Handler` would be part of the qml side that will know to read requests coming from the WC and BC and ask `WalletConnect Service` for necessary action. Also requests that are coming from the BC will be processed on the statusgo side before being forwarded to the client (desktop app), that would be exactly what `WalletConnect` do.

Anyways, it would be good to have a call about this and analyze it.

**Comment by alexjba** [comment]
Closed by
[fix(BC)_: Notify client on dapp connection changes status-im/status-go#6051](https://github.com/status-im/status-go/pull/6051)
[Feat(DApps): Refactoring wallet connect service and bring BrowserConnect inline with WC #16730](https://github.com/status-im/status-desktop/pull/16730)
