### ISSUE TITLE
(SendModal): Hide Custom button for release

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#16052]
# Bug Report

## Description

Custom button is disabled on release, but is still visible. Not able to interact with it looks like bugged state

![image](https://github.com/user-attachments/assets/f24e58fc-dbdc-4daa-a8f7-6136f2296728)

**Comment by caybro** [comment]
@xAlisher @benjthayer hide it completely, or make it look disabled?

For reference, this is how it could look disabled:

![image](https://github.com/user-attachments/assets/4667ce28-44bf-4239-832b-85efc1d7a3e3)

**Comment by caybro** [comment]
> Removal for me - if we kept it, we'd need to somehow explain what it is and how it is different from advanced - best to keep things as simple as possible and mitigate any additional feedback/comments from users. We can then always promote/tease the custom feature ahead of launch, going into more detail about how it works / what it enables you to do

**Comment by saledjenic** [comment]
We should just hide "Custom" tab in `production` mode, for the develop mode we should keep it enabled and keep using/improving it.

**Comment by caybro** [comment]
> We should just hide "Custom" tab in `production` mode, for the develop mode we should keep it enabled and keep using/improving it.

Yup makes sense imho, I can do this
