### ISSUE TITLE
Can't send in send modal if one of processors failed

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16053]
# Bug Report

## Description

Cant send on Mainnet if Arb fails

## Steps to reproduce

on testnet for example (to replicate faster) try to send on Mainnet when you see a red banner for Arb

#### Expected behavior

Can send

#### Actual behavior

![Screenshot 2024-08-09 144909](https://github.com/user-attachments/assets/8d63e1aa-bc7b-45dd-8338-7de663431332)

![Screenshot 2024-08-09 144836](https://github.com/user-attachments/assets/c52182c5-b6a5-43b2-8e80-1599143c56be)

### Additional Information

- Status desktop version: 2.30 rc5
- Operating System: MacOS, Windows, Linux

**Comment by saledjenic** [comment]
@anastasiyaig this one should be fixed in this statusgo PR: https://github.com/status-im/status-go/pull/5695

**Comment by anastasiyaig** [comment]
@saledjenic very good, we need to bump version then once this status go PR is merged, so this change could be validate both in master and release

**Comment by saledjenic** [comment]
@anastasiyaig here is desktop PR where you can test it
https://github.com/status-im/status-desktop/pull/16077
