### ISSUE TITLE
Browser plugin - transaction via Uniswap doesn't go through

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16063]
# Bug Report

## Description

When connected to Uniswap via Browser plug in, transaction gets stuck

## Steps to reproduce

1. Have the Status browser extension installed
2. Open the desktop app and use an account that has some funds
3. Go to Uniswap and connect the wallet to Status browser
4. On Uniswap, make a swap for example 1 usdt to 1 usdc
5. On the Status desktop app, Sign the transaction.

#### Expected behavior
Sign transaction details to show correct data 
Sign transaction to go through correctly

#### Actual behavior
Sign transaction details are ilegible
![Screenshot 2024-08-09 at 11 00 34 AM](https://github.com/user-attachments/assets/a551bd82-0730-481d-8c0f-88b5b86f2004)
Transaction on Uniswap's end remains Pending
Status app shows a successful toast but nothing else happens
I re-tried the transaction and the Status Sign modal showed up 1 or 2 times but nothing happens on Uniswap's end.

https://github.com/user-attachments/assets/85e096ab-079d-4a78-bad3-b49e04652a8a
https://github.com/user-attachments/assets/3bae0ed9-44ec-48ab-8d0f-b5cd8fc42533
![Screenshot 2024-08-09 at 10 26 35 AM](https://github.com/user-attachments/assets/2b79b53a-c53a-42d2-b92b-75db08508b90)
![Screenshot 2024-08-09 at 10 25 52 AM](https://github.com/user-attachments/assets/0cdc7fe8-d376-4bbd-b87c-207ebe9e70c7)
![Screenshot 2024-08-09 at 10 18 50 AM](https://github.com/user-attachments/assets/91b99c1e-f5a8-422a-b326-514734c08297)

### Additional Information
[app.uniswap.org-1723211704025.log](https://github.com/user-attachments/files/16562115/app.uniswap.org-1723211704025.log)

- Status desktop version: 2.30 rc-5
- Operating System: Mac OS Sonoma, Chrome Version 127.0.6533.89 (Official Build) (arm64)

**Comment by anastasiyaig** [comment]
i tried to do a swap in Uniswap today with wallet connect and nothing happens when i click Exchange button in Uniswap dapp, no prompt to sign transaction in Status

**Comment by anastasiyaig** [comment]
I tested transactioning with Uniswap in 2.30 r7 today and i cant sign message to uniswap
![unsiwap reject](https://github.com/user-attachments/assets/480c9ef5-ac81-44d8-824c-7781b6c09724)


https://github.com/user-attachments/assets/2499da67-249a-422f-98dd-1503aab15ebc


also, disconnecting from Uniswap in dapp browser does not disconnect it from Status, still shows as connected

**Comment by virginiabalducci** [comment]
Issue still reproducible on BC and WC https://github.com/status-im/status-desktop/issues/16303
