### ISSUE TITLE
Wrong range passed to eth_getLogs calls

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#16062]
### Description

While looking at Grove and Infura usage stats, I found a bunch of errors caused by calling `eth_getLogs` with a wrong block range (from > to).

![image](https://github.com/user-attachments/assets/c3806040-e6ee-40fa-81d2-042ff6d98525)

This is most likely a bug in activity fetching, we need to figure out the root cause.

**Comment by saledjenic** [comment]
This issue is not relevant anymore, since we decided to drop fetching history transactions for accounts.
