### ISSUE TITLE
[WalletConnect] Incorrect authentication method icon on sign modal

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#16089]
# Bug Report

## Description

The authentication icon on the `Sign` button is not correct when using a local profile and importing a keycard wallet account.

## Steps to reproduce

1. Import a wallet account from keycard
2. Connect a dApp to this account
3. Request any sign method
4. Go to sign request dialog in Status

#### Expected behavior

The authentication icon on the `Sign` button shows the keycard icon

#### Actual behavior

The authentication icon on the `Sign` button shows the password (or any profile authentication method)

**Comment by virginiabalducci** [comment]
Hi @alexjba 

I'm testing a Sign Request with an account that has two wallet accounts with keycards, and I see this icon on the sign request. 
![Screenshot 2024-09-09 at 5 16 26 PM](https://github.com/user-attachments/assets/32d2fc48-8577-4b65-919d-58275f0bb97f)
![Screenshot 2024-09-09 at 5 24 52 PM](https://github.com/user-attachments/assets/a76380eb-94d5-4254-af80-7ef4dc50cfc5)

I can't find this keycard flow on the Figma to see how the icon should look like: https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=0-1&node-type=canvas&t=Q1gTOY5IWGhubGIz-0

**Comment by alexjba** [comment]
@virginiabalducci Looks like you have a nice setup. I assume the profile login is with password, the accounts are stored on keycard and the keycard pin is stored in the os keychain. Please correct me if I'm wrong.

In this case looks to me like the icon on `Sign` should be the keycard, but the icon on Authentication screen looks ok.

**Comment by caybro** [comment]
Evil typo there:
```qml
loginType: account.migragedToKeycard ? Constants.LoginType.Keycard : root.loginType
```

Fixing :)
