### ISSUE TITLE
Wallet connect - wallet account color icon shows incorrectly as black on the Sign approval pop up

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16094]
# Bug Report

## Description

Wallet account icon shows incorrectly as black on the Sign approval pop up

## Steps to reproduce

1. Do a transaction on a dApp that triggers a Sign approval on the desktop app. For example connect to https://se-sdk-dapp.vercel.app/

#### Expected behavior
Wallet icon for Account 1 should be blue
![Screenshot 2024-08-13 at 10 32 00 AM](https://github.com/user-attachments/assets/cafa6eeb-59b6-4114-a41a-c6ad4de550e1)

#### Actual behavior
Wallet icon for Account 1 shows as Black

![Screenshot 2024-08-13 at 10 35 00 AM](https://github.com/user-attachments/assets/f5ca2b56-26ac-4977-8cab-adeec4890272)

![Screenshot 2024-08-13 at 10 28 47 AM](https://github.com/user-attachments/assets/3b4928ed-7246-4fa1-a3f5-99168cc364dc)
![Screenshot 2024-08-13 at 10 28 28 AM](https://github.com/user-attachments/assets/6e9bb985-eef3-4fb9-a82d-efceb1b89dd0)

### Additional Information

- Status desktop version: 2.30 rc-7
- Operating System: Mac OS Sonoma

**Comment by caybro** [comment]
@virginiabalducci do you get any warnings in the log?

**Comment by virginiabalducci** [comment]
Hi @caybro 

Thanks for taking a look at this!
I see no warnings on the console log at first sight but I'm attaching a couple of the logs of the profile I've been using for this test

![Screenshot 2024-09-05 at 5 29 33 PM](https://github.com/user-attachments/assets/3934a594-fd33-4d60-bdc1-b810edc19f33)
[app_20240905_105554.log](https://github.com/user-attachments/files/16899963/app_20240905_105554.log)
[app_20240905_153747.log](https://github.com/user-attachments/files/16899964/app_20240905_153747.log)

This log corresponds to the screenshot, I just tested with an approve transaction request from Opensea.
[app_20240905_171420.log](https://github.com/user-attachments/files/16899941/app_20240905_171420.log)

**Comment by caybro** [comment]
Yup, thank you :) The relevant warning is:
```
WRN 2024-09-05 15:16:55.375-03:00 qt warning                                 topics="qt" tid=24844086 text="Unable to assign QJSValue to QColor" file=qrc:/app/AppLayouts/Wallet/panels/DAppsWorkflow.qml:170 category=default
```

**Comment by caybro** [comment]
@virginiabalducci looks good? :)

![image](https://github.com/user-attachments/assets/106888a6-b8a2-42cd-b04f-b2097eddcc5c)

**Comment by virginiabalducci** [comment]
@caybro looks great thanks! I'll be keeping an eye for any updates :)
