### ISSUE TITLE
Wallet connect - Sake.lido.fi dApp - Staking transaction gets stuck

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16096]
# Bug Report

## Steps to reproduce

1. Log into an account with funds
2. Connect the wallet to https://stake.lido.fi/
3. Stake some eth
4. Sign the approval on the desktop app

#### Expected behavior
Transaction to succeed

#### Actual behavior
![Screenshot 2024-08-13 at 12 22 21 PM](https://github.com/user-attachments/assets/a4f48a8b-2b19-41b3-ac5c-ff935178a85d)

Lido website shows: "You are staking 0.0002 ETH"
Etherscan: https://etherscan.io/tx/0x3ef063390129dde22b802941279dd960ea7321b2cffc599a5355ad4114e0a38c
![Screenshot 2024-08-13 at 12 26 49 PM](https://github.com/user-attachments/assets/dcccca41-c533-4b0f-9ecf-2ca669514dc9)

Desktop app shows:
![Screenshot 2024-08-13 at 12 22 04 PM](https://github.com/user-attachments/assets/8d40d0e9-4292-4da7-8fc7-b99d8c5652da)
![Screenshot 2024-08-13 at 12 21 52 PM](https://github.com/user-attachments/assets/a65bf9bc-93a3-4ef7-a596-57a03d309b5a)

Attaching console log of test account
[Stake lido app cannot stake test035b.txt](https://github.com/user-attachments/files/16601841/Stake.lido.app.cannot.stake.test035b.txt)

### Additional Information

- Status desktop version: 2.30 rc-7
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
I did the same test with a Trust wallet connecting to Lido via wallet connect and transaction succeeded
https://etherscan.io/tx/0xe69176881ef55248c7a0e33cd0a09d514b8b0f60a201b4083ee6a052678f3489

**Comment by alexjba** [comment]
Possibly related to:
https://github.com/status-im/status-desktop/issues/16063
