### ISSUE TITLE
[Browser plugin connector] Can't reconnect the dApp

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#16107]
After disconnecting the dApp is not possible to connect to status-desktop again. It may happen because of geth websocket management issue. 

NOTE: there is a [test](https://github.com/status-im/status-go/pull/5711/files#diff-79080f2bfda23a2bdaaedb6f40f2303627489fa7d411acb3efe5ce262fe0dc8cR176) which checks ability to reconnect  a dApp. 

https://github.com/user-attachments/assets/e5badf33-727f-4329-b6b7-5c3714e78654

**Comment by alexjba** [comment]
Cannot reproduce on latest master

https://github.com/user-attachments/assets/fb907942-5a97-46f0-8cc7-841410121f15

**Comment by virginiabalducci** [comment]
Working as expected on master, using WC and BC
