### ISSUE TITLE
Add external link to download extension plugin in status-desktop

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#16111]
### Description

The goal is to add a link somewhere in the app, most likely the wallet, that takes the user to download the browser extension.

Design: https://www.figma.com/design/1OYKMzU6KTQHQAqDhojk0r/Status-connector?node-id=2104-6529&m=dev

**Comment by caybro** [comment]
@jrainville I can do that once we have the design

**Comment by xAlisher** [comment]
This is what initially suggested https://www.figma.com/design/1OYKMzU6KTQHQAqDhojk0r/Status-connector?node-id=2104-4428&t=K3jMTlSTb7eqABCn-1
Also we are looking for the way to include link to extension into Onboarding, but we do not have design for it yet.  
cc @benjthayer
 
![image](https://github.com/user-attachments/assets/b77bdfa3-4857-4192-8d2d-ce7398be1997)

**Comment by benjthayer** [comment]
> This is what initially suggested https://www.figma.com/design/1OYKMzU6KTQHQAqDhojk0r/Status-connector?node-id=2104-4428&t=K3jMTlSTb7eqABCn-1 Also we are looking for the way to include link to extension into Onboarding, but we do not have design for it yet. cc @benjthayer
> 
> ![image](https://private-user-images.githubusercontent.com/7700914/358201356-b77bdfa3-4857-4192-8d2d-ce7398be1997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjA1MDYsIm5iZiI6MTcyMzcyMDIwNiwicGF0aCI6Ii83NzAwOTE0LzM1ODIwMTM1Ni1iNzdiZGZhMy00ODU3LTQxOTItOGQyZC1jZTczOThiZTE5OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTExMDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2I2NzI4NDQxZDQ3ZTgzYmExYTViNjE4ZTg1NWYxMjI5ODBkMWMwODlmZDczZDJiOWQxNGJiZDQzODViMDRjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7bPUV1jCwzq4CfNgqus0kloZz3WcJQDul-_VXaoef0Y)

Another option here would be to use a split button potentially to avoid the need for the subsequent dialog. Although it would be the same number of clicks, it might be more fluid for the user to review the connection options from the dropdown side of the split button? We would just need to determine what the primary CTA is and what the menu items for the dropdown would be... for example:

Primary CTA:
`Connect` - Launches WC dialog (URI entry)

Dropdown:
`Via WalletConnect`
`Via Status Connector`
----
`Install Status Connector`

Just a thought - WDYT @xAlisher ?

**Comment by xAlisher** [comment]
@benjthayer It's hard to form an opinion from just the plain text. But if you think it will be better, let's explore it.

**Comment by xAlisher** [comment]
Final design approved by @benjthayer and @pedro-et 

![image](https://github.com/user-attachments/assets/f1220255-9697-4c06-9798-0d716fada08e)
https://www.figma.com/design/1OYKMzU6KTQHQAqDhojk0r/Status-connector?node-id=3216-5618&t=1Xfb06pKtsh10qfq-1

**Comment by alexjba** [comment]
> For the download link, and for now, you can use https://chromewebstore.google.com/detail/a-wallet-connector-by-sta/kahehnbpamjplefhpkhafinaodkkenpg. It's accessible to some. And the dev builds are still available to all in [status-im/status-browser-extension#35 (comment)](https://github.com/status-im/status-browser-extension/pull/35#issuecomment-2277586278).

@felicio Should we use another link for the release? This one is not working for me

**Comment by alexjba** [comment]
> [@alexjba](https://github.com/alexjba) do you mean the one for Chrome Web Store?

Yes

> It shouldn't change after second Google review. And currently it's only accessible to some. Would you like me to add your email to the list?

Yes, please 😄 

> Also, when you get to preparing a release checklist for this, I'd say release should be blocked by the second Google review. Which we haven't submitted yet. Please, let us know when it's ready for testing.

How long does it usually take for the review?
We're quite close of being ready for the release. You can use the builds here to test. Please add `FLAG_CONNECTOR_ENABLED=true` as env variable and the dapps integration will be available.

https://github.com/status-im/status-desktop/pull/16816#issuecomment-2500413052

**Comment by alexjba** [comment]
> Added you on the list, let me know if you can access it now.
I have it now! Thanks!

> Private beta took about 2 days, public release could take longer. When do you plan to release?
15th of December. Is that doable?
