### ISSUE TITLE
[Wallet Connect] Signing is allowed after the request expires

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#16114]
# Bug Report

### Case 1
Used dapp: Rarible, YearnFi

The Sign tx popup was displayed in the Status app, I let it expired, and then click on the Sign button.
The tx was signed, and the signature was sent to the dapp, and ephemeral notification (bottom right) was displayed saying the dapp accepted transaction, but in real nothing happened on the dapp side, that tx was just ignored.

For the fact on the dapp side when the request expires a Continue button was displayed just to runs the request again.

### Case 2
Used dapp: OpenSea, Rarible, YearnFi

After connection request is made by the dapp, and we let it expire, on the dapp side, the connection string is refreshed (a new one is created) but on the Status app side nothing happens, and the previous connection string remains in the popup. After user proceeds with it, clicking the Connect button an error is received like "WC WalletConnectSDK.onApproveSessionResponse; sessionTopic: \"\", error: Missing or invalid. Record was recently deleted - proposal: 1723549782269158

### Case 3
Used dapp: OpenSea

After successful connection, when the sign tx popup appears in the Status app, leave it to expire, notification about expired request is displayed in the dapp, but in the Status app nothing changes, then proceed with the buying, tx will be successfully made and the collectible will be bought. 

We should invalidate signing request when expiration timestamp is reached.

Identified by @saledjenic in https://docs.google.com/spreadsheets/d/1QkV08jm0ECV01x3yWTLnVGCjTluKQ-IBDJXsHjNeAQg/edit?gid=0#gid=0

**Comment by virginiabalducci** [comment]
Adding testing notes

**Notes for Case 1:**

https://yearn.fi/v3

I let the connection from the dApp expire, then clicked on the Sign button on the Sign Request pop up and the app crashed.
https://github.com/user-attachments/assets/d0b2dee1-ec61-44e6-9fe1-d4c552ab68c0
https://github.com/user-attachments/assets/0462fdb6-dd4f-40b8-94b3-450dd65315e9

[app_20240906_140314.log](https://github.com/user-attachments/files/16911194/app_20240906_140314.log)
[geth.log.zip](https://github.com/user-attachments/files/16911199/geth.log.zip)

**Rarible**

I let a sign request from Rarible expire, the dApp page showed an error message. But on the desktop app, after Signing a notification of success displayed, and nothing else happened.

https://github.com/user-attachments/assets/1cbdabed-d50a-4be1-aaef-64594db25237

https://github.com/user-attachments/assets/3b89f5d9-d2da-461b-b037-f2b90d7e14cc


```
ERR 2024-09-06 14:47:23.731-03:00 rpc response error                         topics="rpc" tid=26022344 file=core.nim:36 err="\nstatus-go error [methodName:connector_sendTransactionAccepted, code:-32000, message:empty requestID ]\n"
ERR 2024-09-06 14:47:23.731-03:00 error doing rpc request                    topics="rpc" tid=26022344 file=core.nim:39 methodName=connector_sendTransactionAccepted exception="\nstatus-go error [methodName:connector_sendTransactionAccepted, code:-32000, message:empty requestID ]\n"
ERR 2024-09-06 14:47:23.731-03:00 sendTransactionAcceptedFinishedRpc failed:  topics="connector-service" tid=26022344 file=service.nim:114 err="\nstatus-go error [methodName:connector_sendTransactionAccepted, code:-32000, message:empty requestID ]\n"
WRN 2024-09-06 14:47:23.731-03:00 qt warning                                 topics="qt" tid=26022344 text="TypeError: Cannot read property 'url' of null" file=qrc:/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml:301 category=default
ERR 2024-09-06 14:47:23.732-03:00 qt error                                   topics="qt" tid=26022344 text=">Error finding event for topic 7ec204e150e66bffea0569c6516af334a66332f863b52472bbe11d79a3d7fe6d id 1725644410188121" file=qrc:/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml:344 category=qml
```

[app_20240906_143809.log](https://github.com/user-attachments/files/16911472/app_20240906_143809.log)

**Comment by alexjba** [comment]
fixed by https://github.com/status-im/status-desktop/pull/16467
