### ISSUE TITLE
Adding saved address is way too slow

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16121]
# Bug Report

## Description

![image](https://github.com/user-attachments/assets/cea932a8-6e3c-4254-ae6a-1e94b3101a03)

It is introduced very recently, for last few days or something. Now adding saved address is taking too long. I talked to Sale and there are 2 things we need to check:
- ens check call that could be not async and takes too much time
- db slowness

This issue appears in master and release 2.30 RC 8, however it **was not the case for 2.30 RC 7**

I am also seeing this in logs, perhaps it is impacting:

```
RR 2024-08-15 01:24:11.525+00:00 rpc response error                         topics="rpc" tid=2536913 file=core.nim:36 err="\nstatus-go error [methodName:stickers_market, code:-32000, message:eth-archival.rpc.grove.city.error: context deadline exceeded, mainnet.infura.io.error: context deadline exceeded ]\n"
ERR 2024-08-15 01:24:11.526+00:00 error doing rpc request                    topics="rpc" tid=2536913 file=core.nim:39 methodName=stickers_market exception="\nstatus-go error [methodName:stickers_market, code:-32000, message:eth-archival.rpc.grove.city.error: context deadline exceeded, mainnet.infura.io.error: context deadline exceeded ]\n"
ERR 2024-08-15 01:24:11.526+00:00 Error in getMarketStickerPacks             tid=2536913 file=async_tasks.nim:51 message="\nstatus-go error [methodName:stickers_market, code:-32000, message:eth-archival.rpc.grove.city.error: context deadline exceeded, mainnet.infura.io.error: context deadline exceeded ]\n"
WRN 2024-08-15 01:24:11.645+00:00 qt warning                                 topics="qt" tid=2536881 text="error parsing saved address for address:  0x8397bc3c5a60a1883174f722403d63a8833312b7  error:  JSON.parse: Parse error" file=qrc:/app/AppLayouts/Wallet/stores/RootStore.qml:302 category=qml
```

## Steps to reproduce

Just add saved address in settings and check how soon the address will appear after filling the form

- Status desktop version: 2.30 rc8 
- Operating System:
- Geth log 
[data_attachments_5cc4e6bd1d474f28.txt](https://github.com/user-attachments/files/16623042/data_attachments_5cc4e6bd1d474f28.txt)

- Application log 
[data_attachments_1bbdaf3d517db15e.txt](https://github.com/user-attachments/files/16623046/data_attachments_1bbdaf3d517db15e.txt)

**Comment by caybro** [comment]
Isn't this the introduced proxy at work?

**Comment by anastasiyaig** [comment]
@caybro i am not entirely sure but most likely you are right

@alaibe @dlipicar wdyt?

**Comment by saledjenic** [comment]
@anastasiyaig I've just tested this in the latest master `7c10b16b674cbf34a750307004578ad38b0199ab` and the last release/2.30 commit `869ca5b3c95ae3bdd98d0ed40428a7358e2d1b0e` and in both of them adding saved addresses is literally an instant action, no delay as all. Could you check it again?

**Comment by anastasiyaig** [comment]
yep just tested it, seems to be fine @saledjenic 
i opened PR to reduce timeout for tests, which was added because of this issue https://github.com/status-im/status-desktop/pull/16140

**Comment by saledjenic** [comment]
> i opened PR to reduce timeout for tests, which was added because of this issue https://github.com/status-im/status-desktop/pull/16140

Well, maybe you should not, cause that varies based on the network congestion.

Maybe a better way would be to update your test to periodically check for added saved addresses up to some max waiting time, that way waiting time for adding saved address would be a minimum of `time needed for an address to appear in the list of saved addresses` and `max waiting time of 20 seconds`. In theory, test should never wait for max waiting time.

**Comment by anastasiyaig** [comment]
now i am waiting for 5 seconds. if that wont be enough , i can add more, before the change it was 60 seconds which is way too much

**Comment by saledjenic** [comment]
It is not a problem to have a max waiting time of 60 seconds at all, as long as we do repetitive checks within that time.
