### ISSUE TITLE
Wallet - Bridge - a bridge transaction of ERC20 token (to or from L2) does not show the network on the activity list and details

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16133]
# Bug Report

## Description

After performing a bridge transaction of a ERC20 token, for example DAI, from L1 Mainnet to L2 Arbitrum, the activity list and details do not show the network name.

Update: this can be also reproduced from L2 Optimism to L1 Mainnet.

## Steps to reproduce

1. Do a bridge transaction from Mainnet to Arbitrum of an ERC20 token, for example DAI
2. Check the activity list and activity details

#### Expected behavior
Activity list and details to mention Arbitrum as the network.

#### Actual behavior
From L1 to L2 Arbitrum:
Transaction in "Sending" status
<img width="1192" alt="Screenshot 2024-08-15 at 4 29 22 PM" src="https://github.com/user-attachments/assets/f685078d-5faf-40e1-bfa8-196cd8ec942a">
<img width="1193" alt="Screenshot 2024-08-15 at 4 29 36 PM" src="https://github.com/user-attachments/assets/0fa94b18-db9a-4a4a-806c-2a41d5a3c188">

Transaction 
<img width="783" alt="Screenshot 2024-08-15 at 5 31 17 PM" src="https://github.com/user-attachments/assets/bb7df88a-f7cc-426e-b209-20b464100c5f">
in "Sent" status
<img width="754" alt="Screenshot 2024-08-15 at 5 31 25 PM" src="https://github.com/user-attachments/assets/cb6aec0e-6270-4d89-bc82-4c2cb248e4bb">

From L2 Optimism to L1 
<img width="771" alt="Screenshot 2024-08-15 at 5 39 33 PM" src="https://github.com/user-attachments/assets/dadd352b-3bae-4591-80ae-9660454344cd">
<img width="803" alt="Screenshot 2024-08-15 at 5 39 46 PM" src="https://github.com/user-attachments/assets/4d182290-23fb-4b68-aac2-7ea99e2322b4">

### Additional Information
https://etherscan.io/address/0x32e12fd7c2c7984dd6de153691d901445fc8aa07
wallet address: 0x32e12fd7c2c7984dd6de153691d901445fc8aa07

- Status desktop version: 2.30 rc-8
- Operating System: Mac OS Sonoma

I selected 2.30 as Milestone, feel free to change it.

**Comment by anastasiyaig** [comment]
should be closed now i guess
