### ISSUE TITLE
Group chat info / member list needs style adjustments

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#1616]
Right now it looks like this:
<img width="479" alt="Screenshot 2021-01-11 at 17 53 21" src="https://user-images.githubusercontent.com/445106/104212812-e82a0580-5435-11eb-9f17-ca76d7be0bd5.png">

But it should be looking like this:

<img width="344" alt="Screenshot 2021-01-11 at 17 54 57" src="https://user-images.githubusercontent.com/445106/104212993-20314880-5436-11eb-8533-c1b82df85f69.png">

**Comment by staked-smart-ace** [comment]
Could I work on this issue?

**Comment by jrainville** [comment]
Yes, go ahead
