### ISSUE TITLE
Adding contact modal needs to work with chat keys

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#1617]
We've got a report that adding a contact by chat key via the contact list didn't work.
The app says it can't find the user but at the same time it enables the button to add a contact.

This needs to be verified and looked into.

**Comment by PascalPrecht** [comment]
Cannot reproduce this. This was reported by @simonricoo and is indeed a visible issue in one of his recorded feedback video. However I wasn't able to reproduce this and when tested with a different account, Simon couldn't reproduce it anymore either.

**Comment by iurimatias** [comment]
I cannot reproduce it anymore
