### ISSUE TITLE
Change password functionality missing in Privacy and Security pane

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#1620]
This needs to be added. Designs are available in figma

**Comment by staked-smart-ace** [comment]
Could I work on this issue?
If so, please assign to me with right Figma url for this functionality

**Comment by jrainville** [comment]
I assigned you @staked-smart-ace 
You can find the design here: https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1432%3A6693
See the Modal that comes with it on the right.

Do note that we already have a very similar Modal for the registration of users in the onboarding (when you create a new account), so if it it possible to reuse that Modal, it would be great

**Comment by staked-smart-ace** [comment]
I dont have access on provided Figma file, or wrong URL?

**Comment by jrainville** [comment]
hmm, I think @simonricoo would need to give you view access

**Comment by simonricoo** [comment]
Should work now!

**Comment by staked-smart-ace** [comment]
@jrainville 
Does anyone provide nim side interface to send update password request?

**Comment by jrainville** [comment]
Oh, I just realized, it is very possible that this feature doesn't exist in our backend (status-go). I'll ask @cammellos if he knows.

**Comment by jrainville** [comment]
@staked-smart-ace I just asked and it's not possible for now to change the password from the backend. We'll revisit this issue once that feature is added. 
For now, I'll remove the assignment and you can select another issue

**Comment by staked-smart-ace** [comment]
ok, i just add comment to #1612

**Comment by iurimatias** [comment]
we can implement this now than https://github.com/status-im/status-go/pull/2223 is implemented
