### ISSUE TITLE
Bad notification message for specific Swap

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#16200]
### Description

Performing a Swap on Optimism from DAI to USDT results in a bad notification text. Other combinations of tokens and chains seem to work fine though.

![image](https://github.com/user-attachments/assets/b7c0c938-ad8e-4582-aa25-1347b59852bc)
![image](https://github.com/user-attachments/assets/b632aea7-26a2-4e49-ae23-6ae4ced88c3f)

**Comment by Khushboo-dev-cpp** [comment]
tested on latest master again it works fine. so closing this issue


![Image](https://github.com/user-attachments/assets/e3c0a92e-7e6f-4ef9-88cf-96ec859bd989)
![Image](https://github.com/user-attachments/assets/22340f33-9cb2-453c-9027-4fc17cbf4899)
