### ISSUE TITLE
Context menu is destroyed (model reset)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16236]
# Bug Report

## Description

https://github.com/user-attachments/assets/953e082d-13fb-45d9-aa65-20ea626b2797

https://github.com/user-attachments/assets/338b55f6-7304-424e-8488-7b1e76244937

## Steps to reproduce

1. create status new account
2. open wallet, add wallet account
3. right click the added account
4. notice that context menu is closed

### Additional Information

- Status desktop version: commit 7c184f35002886947493070400500e7e05de74b6
- Operating System: any

**Comment by alexjba** [comment]
@anastasiyaig This issue is fixed on master. Tests can be re-enabled
