### ISSUE TITLE
Password instructions missing max length requirement

### ISSUE THREAD

**Issue by schoedon** [status-im/status-desktop#16239]
The app password is only allowed to have 64 characters but the requirements don't state it.

Creating a long password with >64 characters results in the error message that only letters, numbers, hyphens, and underscores are allowed.

I would recommend changing the "min lenght" requirement description in the singup-frontend into a "length" requirement containing both boundaries (8, 64).

:pray:

**Comment by virginiabalducci** [comment]
The "Create Password" button is greyed out after user passes the 64 characters, however, user can still type in characters indefinitely. In my video, I'm typing to 190+ characters and the app lets me continue. The more characters I type the more laggy the app becomes. No errors on the console app side. I hope this helps!

https://github.com/user-attachments/assets/c3d16e55-dc85-4c8f-ab38-f3fb4201a61e

**Comment by caybro** [comment]
@benjthayer @jrainville @alexjba so for the password max length, we could basically have these 2 options:

![Image](https://github.com/user-attachments/assets/ade68d37-1089-45af-b3bf-01e098cb7057)
![Image](https://github.com/user-attachments/assets/98e911e2-87dd-4468-bf61-75dd1657f80b)


- either validate, and display the "pass too long" message
- or just set and display the hard limit as a hint in the topright corner, above the text field; like we do elsewhere too
(here for brevity I set the max length to 5 in order not to have to type 64 chars 🙂

**Comment by jrainville** [comment]
I think I prefer the first option. I doubt users will often reach 64 characters and thus we don't need to add extra UI elements

**Comment by caybro** [comment]
> I think I prefer the first option. I doubt users will often reach 64 characters and thus we don't need to add extra UI elements

Does not prevent pasting a large amount of text though

**Comment by benjthayer** [comment]
Thanks for the options @caybro - I agree with @jrainville that the first option is best out of the two IMO as its the most clutter free - it means we only need to show info relating to the limit in the very small number of scenarios where it is relevant. Most users will use a much shorter password.

**Comment by benjthayer** [comment]
@caybro I noticed the design files currently don't have any password validation states so I will add them in. 

Mobile also has these states. I will add them also but we may need to sync with mobile to see which of these have been implemented so we are aligned across the 2 platforms. @xAlisher do you know who worked on the implementation of the password entry and validation on the mobile side?

![Image](https://github.com/user-attachments/assets/409bc76b-2ce0-4285-a3ef-e570b059f652)

![Image](https://github.com/user-attachments/assets/c69a8da9-a3a2-4091-a210-cdcea5c29197)

![Image](https://github.com/user-attachments/assets/f8069a58-43d4-474e-a1d4-0c224a4798db)

Mobile Figma:
https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=11465-88185

**Comment by benjthayer** [comment]
@caybro @xAlisher the 64 max character validation and the others in mobile have been added to the desktop flows:

Password creation flow:
https://www.figma.com/design/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=41014-22302&t=Uajdz9nEx8sL7f51-4

Password change flow (Settings):
https://www.figma.com/design/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=7859-187799&t=9iOabUUVyDB4IN91-4

**Comment by xAlisher** [comment]
We finally agreed on 100 chars. @benjthayer 

> [@caybro](https://github.com/caybro) [@xAlisher](https://github.com/xAlisher) the 64 max character validation and the others in mobile have been added to the desktop flows:
> 
> Password creation flow: https://www.figma.com/design/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=41014-22302&t=Uajdz9nEx8sL7f51-4
> 
> Password change flow (Settings): https://www.figma.com/design/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=7859-187799&t=9iOabUUVyDB4IN91-4

**Comment by benjthayer** [comment]
> We finally agreed on 100 chars. [@benjthayer](https://github.com/benjthayer) 

Thanks @xAlisher will tweak the designs now @caybro

**Comment by anastasiyaig** [comment]
@caybro pls ping me when you have PR to test, i will have to change tests for this

**Comment by caybro** [comment]
> [@caybro](https://github.com/caybro) pls ping me when you have PR to test, i will have to change tests for this

WIP https://github.com/status-im/status-desktop/pull/16522 but it passes :)

**Comment by anastasiyaig** [comment]
ya it passes, i want to change the upper limit later (and maybe check other tests that are not in PRs )

**Comment by caybro** [comment]
> ya it passes, i want to change the upper limit later (and maybe check other tests that are not in PRs )

PR submitted officially :)

**Comment by anastasiyaig** [comment]
i will take a look tomorrow thanks
