### ISSUE TITLE
Missing hover in the top settings

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#16263]
# Bug Report

## Description

Video speaks more than words:

[missing-hover.webm](https://github.com/user-attachments/assets/2706d21c-a680-479c-b533-fd275ec49efd)

## Steps to reproduce

1. Go in Settings
2. Hover over the top setting options

#### Expected behavior

There is a visual hover effect

#### Actual behavior

There is no hover effect

### Additional Information

- Status desktop version: master `16d0df694c7986478c54df902da39ebeeb8607e0`
- Operating System: Ubuntu 22

**Comment by jrainville** [comment]
@caybro small regression probably introduced with the beta label. cc @micieslak in case Lukas is busy

**Comment by caybro** [comment]
> @caybro small regression probably introduced with the beta label. cc @micieslak in case Lukas is busy

I can have a look tomorrow
