### ISSUE TITLE
The ERC-20 token's value is still shown as approved after swap transaction is conirmed

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-desktop#16304]
### Steps:
1. Go to the swap page and select an ERC-20 token (e.g., DAI 0.1 -> ETH).
2. Approve the transaction for the specified amount (e.g., 0.1 DAI).
3. Confirm the transaction using the same value (0.1 DAI).

### Actual Result:
- The transaction is confirmed, and the balances are updated.
- However, the 0.1 DAI still appears as "approved" on the blockchain (tested on Arbitrum and Optimism).
- The approved amount remains visible at [Optimistic Etherscan](https://optimistic.etherscan.io/tokenapprovalchecker), [Arbiscan](https://arbiscan.io/tokenapprovalchecker), and [Etherscan](https://etherscan.io/tokenapprovalchecker) for the address `0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5`.
- How here is the id of a transaction after [approving](https://arbiscan.io/tx/0x0d3953e38ef1f216d3c2ce49f17dd186918086d6d2514d6905ef491f0ba97322)  and after confirmation https://arbiscan.io/tx/0xdd13d17f5b4a443de2ae35feb599fef6de811db96c34aa6d5279dfb9168f3eb7

https://github.com/user-attachments/assets/f3731a76-2923-44a3-bf49-c8248d7b4457

### Expected Result:
Once the transaction is confirmed, the approved amount should be reduced on the blockchain, reflecting the deduction of the confirmed transaction value.

### ENV:
- Pixel 7a, Android 13
- Desktop: Master 10 Sep, 2024

### Logs
[desktop swap (1).txt](https://github.com/user-attachments/files/16943587/desktop.swap.1.txt)
[geth.log.zip](https://github.com/user-attachments/files/16943600/geth.log.zip)

**Comment by dlipicar** [comment]
Hey @VolodLytvynenko 
Hmm just to make sure, will Status let you perform a new swap using 0.1 DAI? I'd guess most likely not.

If you're looking at this list, this shows you how much you initially approved when you sent the Approve tx to the chain.
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/d134daa9-caa1-46be-a174-314085bd9858">

If you want to check how many tokens are "left" to be used by that smart contract, you need to click "Revoke" to get this scren
![image](https://github.com/user-attachments/assets/1138800a-356c-46c9-9d0f-ec88056f5c61)

More info here: https://info.etherscan.com/tokenapprovals/

Please tell me if I misunderstood the issue.

**Comment by VolodLytvynenko** [comment]
invalid
