### ISSUE TITLE
[WC] Add countdown pill to sign dialogs

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#16314]
#### Add the countdown pill

[Figma](https://www.figma.com/design/HrmZp1y4S77QJezRFRl6ku/dApp-Interactions---Milestone-1?node-id=3967-288216&m=dev)

![image](https://github.com/user-attachments/assets/00f1865d-1267-44af-b400-d9818e7c5b40)
![image](https://github.com/user-attachments/assets/a23ee129-b7cd-405d-b585-93c6866e0338)

Spec here: https://github.com/WalletConnect/walletconnect-monorepo/pull/1851

**Comment by caybro** [comment]
@alexjba do we already have the corresponding notification in place? 

![image](https://github.com/user-attachments/assets/fd65af3d-a8b2-4b88-8f98-7fe225a28052)

Should the little timer component be covered here, or in separate ticket? That said, I'm not totally convinced the timer itself should be part of the countdown pill here, wdyt?

**Comment by alexjba** [comment]
> @alexjba do we already have the corresponding notification in place? 
> 
> ![image](https://github.com/user-attachments/assets/fd65af3d-a8b2-4b88-8f98-7fe225a28052)
> 
> Should the little timer component be covered here, or in separate ticket? That said, I'm not totally convinced the timer itself should be part of the countdown pill here, wdyt?
> 

We don't have the notification. Not totally convinced either. Maybe it would be nice to have the visual component as a base class and the timer logic in the upper component. Just in case we find different use cases for it.
