### ISSUE TITLE
Token Mint Failed error message

### ISSUE THREAD

**Issue by nileshsamin** [status-im/status-desktop#16326]
### Description

I am trying to mint a token in Status on the Optimism network and am getting an error message "Token minting failed   Something went wrong".  I don't see any information I entered that looks incorrect on the Mint token page, and the error message doesn't provide any details indicating why the minting failed.  

I found the following in the application log:

ERR 2024-09-12 09:20:36.620-04:00 rpc response error                         topics="rpc" tid=53924 file=core.nim:36 err="\nstatus-go error [methodName:communitytokens_deployAssets, code:-32000, message:open /C:/Users/test/Desktop/test.jpg: The filename, directory name, or volume label syntax is incorrect. ]\n"
ERR 2024-09-12 09:20:36.620-04:00 error doing rpc request                    topics="rpc" tid=53924 file=core.nim:39 methodName=communitytokens_deployAssets exception="\nstatus-go error [methodName:communitytokens_deployAssets, code:-32000, message:open /C:/Users/test/Desktop/test.jpg: The filename, directory name, or volume label syntax is incorrect. ]\n"
ERR 2024-09-12 09:20:36.620-04:00 Error deploying contract                   topics="community-tokens-service" tid=53924 file=service.nim:690 message="\nstatus-go error [methodName:communitytokens_deployAssets, code:-32000, message:open /C:/Users/test/Desktop/test.jpg: The filename, directory name, or volume label syntax is incorrect. ]\n"
ERR 2024-09-12 09:20:46.784-04:00 Community token transaction has finished but the system error occured. Probably state of the token in database is broken. topics="community-tokens-service" tid=53924 file=service.nim:603 errorString="token does not exist in database: chainID=10, address=0xe72293621cC0A0681Dbb98Ca20854CF1a23108e6" transactionHash=0xea1bd892e4a2cde6f1b3fa328e1080cc233afe2832dddcc1fe551c7423d595fa transactionSuccess=true

Does anyone have any ideas on how to fix the error.

Thanks

**Comment by jrainville** [comment]
@nileshsamin thanks for the opening this issue.

On which Operating System are you?

It seems like the images fails to be opened because of wrong paths. We can look into it once you confirm which OS to try to reproduce on. Thanks.

**Comment by nileshsamin** [comment]
Were you able to reproduce the issue?

Let me know if you need any additional information.

Thanks

**Comment by jrainville** [comment]
Hi @nileshsamin , sorry for the delay, we were busy with fixing other parts of the app.

I was able to reproduce and I created a fix here https://github.com/status-im/status-desktop/pull/16422

It's gonna be included in 2.31 :smile:

**Comment by nileshsamin** [comment]
Thank you
