### ISSUE TITLE
processor network error on Send transaction

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16352]
# Bug Report

## Description

Erroe message: WPP-025 - status-proxy-O.error: insufficient funds for gas * price + value: add ress 0x3212fD7C2C7984DD6de153691D901445fC8AA07 have 2783037892
8767798 want 159078669589875316

## Steps to reproduce

Use an account that has enough funds to do a send transaction on Mainnet

1. Go to the Wallet
2. Click Send
3. When the modal opens, select a small amount of eth to sent
4. Notice that an error displays 

#### Expected behavior
User to be able to perform a Send tx

#### Actual behavior
User unable to do a send tx, even though they have enough funds
![Screenshot 2024-09-16 at 4 43 40 PM](https://github.com/user-attachments/assets/ce5e7a64-c40b-440c-9977-6b71070c33a1)

### Additional Information
[geth 2.log.zip](https://github.com/user-attachments/files/17019596/geth.2.log.zip)
[app_20240916_154447.log](https://github.com/user-attachments/files/17019600/app_20240916_154447.log)

- Status desktop version: 2.30 rc-1
- Operating System: Mac OS Sonoma

**Comment by saledjenic** [comment]
@virginiabalducci that error doesn't come from our side, it's from the network. Not sure what we can do there.

During the sending process if any network error occurs the transfer processor will display it as `WPP-025` error, but the description may differ, it reflects a real error.

Also I see that you got this error: `WPP-025 - status-proxy-O.error: insufficient funds for gas * price + value: address 0x3212fD7C2C7984DD6de153691D901445fC8AA07 have 27830378928767798 want 159078669589875316`
but no chain we support has a positive balance for the used address `0x3212fD7C2C7984DD6de153691D901445fC8AA07`
so the error is expected, not sure what's wrong?

**Comment by saledjenic** [comment]
@virginiabalducci to get a better understanding about router's logic, please have a look at this comment https://github.com/status-im/status-mobile/issues/21292#issuecomment-2363275012

**Comment by saledjenic** [comment]
> @saledjenic our best shot to fix those issue is to allow custom gas

I guess yes, that's what we're going to do with the new Send modal design.

**Comment by jorge-campo** [comment]
I experience this error whenever I try to transfer funds, such as buying a Status ENS domain or trying wallet-to-wallet transaction. The origin Status Wallet has 21 USD, and I can't transfer any amount of money to the destination Wallet on the Ethereum mainnet. The error is always the same in both Simple and Advanced modes:

`WPP-028 - status-proxy-O.error: failed with 50130704 gas: insufficient f unds for gas * price + value: address 0×925Bd[...]2917E have 0 want 4025019521328142`

This is using my Status account on mainnet, not a test account on testnet (Status desktop 2.30.0).

I'm far from an expert here, but I don't think this error is expected, @saledjenic (CC/ @virginiabalducci )

I hope this helps!

![Image](https://github.com/user-attachments/assets/a757427c-333b-4104-a404-081fcb772701)

**Comment by saledjenic** [comment]
Hi @jorge-campo you're right it should not be like that when buying ens name. There are 2 potential reasons for that:
- you should confirm that your account (the one you're using for sending the tx) has enough ETH to pay for the tx execution besides having 10 SNT for the ens name (in the screenshot I see that the selected token is ETH and you're trying to send 10 ETH actually). So that's most likely the reason. If you want to buy an ens name, go to Settings/Ens usernames section
- we're still using grove provider and the error that you're experiencing is coming from it and it can be unreliable in some cases and should not be there after we switch to nodefleet, that supposed to be very soon, these days. But based on the screenshot, that's not the case there.

**Comment by jorge-campo** [comment]
> * you should confirm that your account (the one you're using for sending the tx) has enough ETH to pay for the tx execution besides having 10 SNT for the ens name (in the screenshot I see that the selected token is ETH and you're trying to send 10 ETH actually). So that's most likely the reason. If you want to buy an ens name, go to Settings/Ens usernames section

Thanks, @saledjenic !

The screenshot is unrelated to the ENS name purchase; it's a direct wallet-to-wallet transaction of ETH on Ethereum mainnet. I have 21 USD in my wallet, and I can't send 10, 5, or 2 USD with the "insufficient gas fee" error.

I am happy to hear that the switch to Nodefleet will happen soon! 👍

**Comment by virginiabalducci** [comment]
Closing this one as it has been concluded this is related to network issues and not from the app itself
