### ISSUE TITLE
SendModal: Improvements: Missing loading state when ENS name is being resolved

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#16355]
https://github.com/user-attachments/assets/d65a5ceb-ad51-4461-9e84-beacf9e614b9

As seen in the screenshot when the sendModal is prefilled with an ens name, we can see the recipient selector while the ens name is being resolved.
As soon as the ens name is resolved we replace it with the wallet address
There is not loading state during this time and its not clear that the ens name is being validated in the background. 

Need some designs to handle this usecase.

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

@benjthayer fyi

**Comment by benjthayer** [comment]
Proposed design:
https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25380-133002&t=e4UnH984VDFtuhiJ-4

cc @Khushboo-dev-cpp 

We'll also look to refine this in the simplified send flow designs (where we remove multichain support).

**Comment by caybro** [comment]
> Proposed design: https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25380-133002&t=e4UnH984VDFtuhiJ-4
> 
> cc @Khushboo-dev-cpp
> 
> We'll also look to refine this in the simplified send flow designs (where we remove multichain support).

Can I also see the Paste button in there, together with the spinner and other trailing components? :)

**Comment by benjthayer** [comment]
> @benjthayer can I also see the Paste button in there, together with the spinner and other trailing components? :)

Hey @caybro the `Paste` button should be removed and replaced with the spinner and `X` clear icon button as soon as a string has been entered. Upon clicking the `X` clear icon button, the field should clear and the `Paste` button should be re-instated.

**Comment by caybro** [comment]
> > @benjthayer can I also see the Paste button in there, together with the spinner and other trailing components? :)
> 
> Hey @caybro the `Paste` button should be removed and replaced with the spinner and `X` clear icon button as soon as a string has been entered. Upon clicking the `X` clear icon button, the field should clear and the `Paste` button should be re-instated.

@benjthayer got it! :) See the video in https://github.com/status-im/status-desktop/pull/16356
