### ISSUE TITLE
Profile context menu opened in community settings does not show image or name 

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16367]
# Bug Report

## Description

Right clicking a member in the community members list opens a profile context menu that does not show image or name. The menu does display correctly when opened from other locations.

## Steps to reproduce

- New community with members
- Navigate to community settings, members
- Right click on a member

#### Expected behavior
Standard profile context menu

#### Actual behavior
Profile context menu that does not show image or name

![image](https://github.com/user-attachments/assets/3db269e0-7b9e-4192-82fa-0f54a2cc967c)

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by caybro** [comment]
Seems like a recent regression in master; the panel is empty for me:

![image](https://github.com/user-attachments/assets/1a2e2fcf-5b06-467c-8835-a42c3c351d05)

**Comment by caybro** [comment]
@jrainville didn't you do something here recently? ;)

**Comment by caybro** [comment]
Alright, mea culpa :) I've been doing some changes to the StatusMemberListItem too :D My fault, will fix
