### ISSUE TITLE
Cant do Swap with 100% slippage

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16394]
# Bug Report

## Steps to reproduce

open wallet
open swap
select optimism
try swapping any asset to any asset with 100% slippage

#### Expected behavior

Should not be possible to enter 100% slippage as Paraswap is not supporting it

#### Actual behavior

Can submit the form , however txn is not initiated

https://github.com/user-attachments/assets/5f7aaf74-d0de-4282-8500-b0408afe4316

On mobile, it at least says something

![image](https://github.com/user-attachments/assets/3719176d-5512-4c4a-8fca-4d59d42725d9)

### Additional Information

- Status desktop version: commit 6f80461371cba1218f2bca0ea55fa6c0da71c01c
- Operating System: any

**Comment by anastasiyaig** [comment]
@dlipicar can you pls look into this?

**Comment by caybro** [comment]
Ah, this one should be easy; will do
