### ISSUE TITLE
Untrusted contract is marked as trusted if message is sent from mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#16392]
# Bug Report

## Description

Untrasted contact became trusted after receiving message from mobile from them.

## Steps to reproduce

1. User A (desktop): add User B as contact
2. User A (desktop): mark User B untrusted
3. User B (mobile): send message to User A

#### Expected behavior
User B stays as "untrusted" on desktop

 #### Actual behavior
User B is marked as Trusted

https://github.com/user-attachments/assets/964b2f58-f1da-4843-af3f-4cdbb421eed0

### Additional Information

- Status desktop version: master 23/09/24
- Operating System: Mac Osx

**Comment by mariia-skrypnyk** [comment]
Hey guys!

Some update : this issue take place also if both users are using desktop app

**My steps:**

1. User A adds User B to the contact
2. User A has a chat with user B
3. User A marks UserB as untrusted
4. User B sends one more message to User A

**Result:** User B is not untrusted anymore, +1 sent message from him dismisses untrusted mark and user becomes trusted.
