### ISSUE TITLE
Message context menu displaying incorrectly 

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16409]
# Bug Report

## Description

Multiple issues noted on the message context menu in master while testing #16390 

Investigation into failing automation tests suggest these may have been introduced by https://github.com/status-im/status-desktop/pull/16357

- Unable to unselect reactions
![image](https://github.com/user-attachments/assets/e88e4e4c-2283-47d5-874b-c7be763a60bf)

- Line appearing through emoji reactions
![image](https://github.com/user-attachments/assets/630af693-efa2-4a7c-bcb1-1776f02a931a)

- Emoji reactions clipped when no longer a contact or pending request 
![image](https://github.com/user-attachments/assets/eefc26ce-1382-4abb-9009-408c0802049d)

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by caybro** [comment]
Most probably due to recent changes in StatusMenu; will fix

**Comment by anastasiyaig** [comment]
ya, sadly my test got passed on this component as it is functional test and all buttons were clickable . maybe we can add / imporove QML test? I could try (if that is not yet done and it is not super complex)
