### ISSUE TITLE
Display name is gone in Settings

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16429]
# Bug Report

## Description

Display name is not appearing

## Steps to reproduce

Receive a contact request or just add a few contacts to the list and open it in Settings

![image](https://github.com/user-attachments/assets/c85bb99d-b1dc-420d-aa25-7e3b80ea1feb)

#### Actual behavior

Display name is missing

### Additional Information

- Status desktop version: commit 83d7c03585f86f98ac7a23dc9e983276ba7f3440
- Operating System: any

**Comment by jrainville** [comment]
@caybro @micieslak @iurimatias could it be a regression from one of your recent refactors?

**Comment by jrainville** [comment]
> > @caybro @micieslak @iurimatias could it be a regression from one of your recent refactors?
> 
> @jrainville Actually, it's regression of your recent refactor: #16363 😆 ;)

![image](https://github.com/user-attachments/assets/71e652bc-e862-4e61-851b-30306ff4a4e5)
