### ISSUE TITLE
Update "Welcome to Status Beta" startup dialog

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#16447]
### Description

The dialog shows the following information that might be confusing for new users (Status 2.30.0):

> We are workign to fix all these issue ASAP, ahead of Status Desktop's 1.0 release!

![Screenshot 2024-10-03 at 8  13 08@2x](https://github.com/user-attachments/assets/d57a9609-d2f4-4152-bc29-42903def8db3)

**Comment by caybro** [comment]
CC @benjthayer

**Comment by benjthayer** [comment]
> CC [@benjthayer](https://github.com/benjthayer)

Good spot! Perhaps we simply remove `ahead of Status Desktop's 1.0 release!` ?

**Comment by caybro** [comment]
> > CC [@benjthayer](https://github.com/benjthayer)
> 
> Good spot! Perhaps we simply remove `ahead of Status Desktop's 1.0 release!` ?

Dunno, maybe @iurimatias wants to add something here too?

**Comment by jorge-campo** [comment]
It would be great to see if we still need "The wallet is not yet safe or secure to use." Someone in the Status community asked this question precisely. CC/ @iurimatias

**Comment by iurimatias** [comment]
yeah simple remove the 1.0 message as it doesn't make sense
