### ISSUE TITLE
Blocking/unblocking users generates improper notifications

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#16454]
# Bug Report

## Description

1. Both blocking and unblocking generate `Contact removed` notification.
2. On unblocking there is no notification informing about successful unblocking

https://github.com/user-attachments/assets/4f0868ad-ad88-440f-8485-17a578daae70

## Steps to reproduce
Block or unblock user

#### Expected behavior
Blocked/unblocked notifications.

#### Actual behavior
Contact removed notification, lack of contact unblocked notification

### Additional Information

- Status desktop version: `100389aa8d1d0eb3facabd9643dec216b36d721d`

**Comment by jrainville** [comment]
Fixed here: https://github.com/status-im/status-desktop/pull/16889
