### ISSUE TITLE
chat: chat input locked in a blocked state

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#16450]
# Bug Report

## Description
After opening chat for blocked user, chat input remains blocked also for other chats.

https://github.com/user-attachments/assets/f1e83356-e632-4625-9bc9-c345c7f72062

## Steps to reproduce
1. Open chat with blocked user
2. Switch to other chat, with not blocked user

#### Expected behavior
Chat input should be enabled.

#### Actual behavior
Chat input remains inactive with information: "This user has been blocked"

### Additional Information

- Status desktop version: `100389aa8d1d0eb3facabd9643dec216b36d721d`

**Comment by jrainville** [comment]
Closing as this is no longer an issue. When blocking a user, their 1-1 chat is now removed
