### ISSUE TITLE
Incorrect error message when adding a long community description

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#16479]
# Bug Report

## Description

When you create a new community using Status desktop, you must fill a community description no longer than 140 characters. If you paste into the `Give a short description` a text over 140 characters, the error is `You need to enter a community description`.

## Steps to reproduce

1. Open Status desktop
2. Click `Communities` and, on the `Discover communities` page, click `Create community`
3. Click `Create new`
4. Enter the community name
5. Copy any text over 140 characters to your computer's clipboard and paste this text in `Give it a short description`

#### Expected behavior

The error message should indicate that the number of characters is more than the allowed 140. Instead, the error indicates the community description is missing. This is an example of a text to include when the number of characters pasted on the description field is over 140:

"Your community description is too long"

#### Actual behavior

The error when pasting a description with more than 140 characters is `You need to enter a community description`..

### Additional Information

- Status desktop version: 2.30.0
- Operating System: macOS Sequoia 15.0.1

![Image](https://github.com/user-attachments/assets/99a238ad-e72d-4b2e-811f-e2742cc05607)

**Comment by caybro** [comment]
Finally understood the issue :) There is a hard limit on the character count and we prevent actually pasting anything beyond that limit. So what happens here is that the paste triggers the validation but since the input stays empty, the first validator (which happens to be the "non empty validator") gets triggered and displays the error message.
