### ISSUE TITLE
[CI] Squish fails to start the login flow

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#16499]
Sometimes squish fails to start the login flow because it's stuck in the `Before you get started` modal. This makes the CI tests fail in some situations.

https://ci.status.im/job/status-desktop/job/e2e/job/prs/2640/allure/#suites/e7302c67a3826ebb6614f7b8a0aafaff/76a6be2f52714b1f/

**Comment by anastasiyaig** [comment]
it happens when you restart the app that was previously terminated when being stuck

**Comment by anastasiyaig** [comment]
thats the possible root cause https://github.com/status-im/status-desktop/issues/15345 (maybe, i am not sure)

**Comment by anastasiyaig** [comment]
the problem is here https://github.com/status-im/status-desktop/issues/16645
