### ISSUE TITLE
StatusQ: create ability to easily call `StatusQ` methods from `nim` code

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#16496]
## Description

Currently nim side is calling various C++ methods via `DOtherSide` and `NimQML`.

This method has various drawbacks:
- we need to put application specific code to `DOtherSide` and `NimQML`
- that code is not accessible from `StatusQ`. If given functionality is also needed within the `StatusQ`/`QML` it must be exposed from the backend. It makes it inaccessible in qml tests and Storybook.

How it could be done?

Instead of placing c++ code into `DOtherSide`/`NimQml` we can keep it directly in `StatusQ` and, with hopefully little effor, make it exposed to `nim` code. It will give ability to share routines between `nim`/`cpp`/`qml`.

As a side-effect, this approach also fully solves the problem described here: https://github.com/status-im/status-desktop/issues/10218

**Comment by caybro** [comment]
Truly interested in how this will pan out :)
