### ISSUE TITLE
Remove ENS Flow - Improve handling the communications to the user

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16506]
# Bug Report

## Description

We should warn the user that in order to release an ens name, they should select the original account they used to send the tx to purchase the ens name in the first place.

## Steps to reproduce

1. Use account 2 to purchase ens name
2. Go to the "release ens flow"
3. If the default account selected is "account 1" instead of showing an error that is difficult to understand or see, we could be more clear in the communication to the user. They should select the account they have purchased the ens with.

#### Expected behavior
Would be useful for the user to have a notification as a heads up reminding them that they need to do the release transaction using the same account they used to purchase the ens name 

#### Actual behavior
If the wrong account is selected, there is an error message
![Image](https://github.com/user-attachments/assets/bcea7536-e4f6-4a58-9bae-74cf256672c4)
https://github.com/user-attachments/assets/2652d983-7001-4a49-97df-94c5ea8e6bb7

### Additional Information

- Status desktop version:
- Operating System:

Feel free to edit this ticket accordingly as per possible acceptance criteria.

**Comment by saledjenic** [comment]
Under this issue, when the user runs the Send modal from "Release username" button we should:
- make an account that the ens name was bought with as selected account
- make ETH token as selected token
- disallow changing account, amount, token, chain and address

**Comment by saledjenic** [comment]
I think points from this issue are already addressed here https://github.com/status-im/status-desktop/pull/16644, guess we can close this issue? @virginiabalducci

**Comment by virginiabalducci** [comment]
Closing issue as it has been addressed in #16644
