### ISSUE TITLE
[Startup] Building contacts takes too long on app startup

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#16509]
# Bug Report

The call to `wakuext_contacts` takes consistently around 10 seconds on my machine (Status CC joined, over 1k members). 

```
DBG 2024-10-09 15:25:18.055Z NewBE_callPrivateRPC                       topics="rpc" tid=37575 file=core.nim:27 rpc_method=wakuext_contacts
DBG 2024-10-09 15:25:27.444Z NewBE_callPrivateRPC                       topics="rpc" tid=37575 file=core.nim:27 rpc_method=wakuext_getReceivedVerificationRequests
```

Then a few moments later, the app is spammed with these 2 calls repeatedly for another 18 seconds, during which the main thread is blocked and app can appear stuck:
```
BG 2024-10-09 15:25:28.487Z NewBE_callPrivateRPC                       topics="rpc" tid=37575 file=core.nim:27 rpc_method=wakuext_getContactByID
DBG 2024-10-09 15:25:28.504Z NewBE_callPrivateRPC                       topics="rpc" tid=37575 file=core.nim:27 rpc_method=wakuext_getTrustStatus
...
DBG 2024-10-09 15:25:46.404Z NewBE_callPrivateRPC                       topics="rpc" tid=37575 file=core.nim:27 rpc_method=wakuext_getContactByID
DBG 2024-10-09 15:25:46.420Z NewBE_callPrivateRPC                       topics="rpc" tid=37575 file=core.nim:27 rpc_method=wakuext_getTrustStatus
```

The whole sequence takes roughly half a minute, adding considerably to the overall startup time

#### Expected behavior
- main thread is not blocked
- startup time reduced

#### Actual behavior
- main thread blocked, app stuck

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
CC @jrainville

**Comment by anastasiyaig** [comment]
I also observed this issue  https://github.com/status-im/status-desktop/issues/16641
