### ISSUE TITLE
Can't compile due to protoc

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#16520]
# Bug Report

## Description

When doing

```
make update
make run
```

`protoc` is now needed to compile.

When I installed Fedora 40 system protoc `protobuf-compiler-3.19.6-8.fc40.x86_64`
 
I get the following errors:

```
protoc --go_out=. ./chat_message.proto ./application_metadata_message.proto ./membership_update_message.proto ./command.proto ./contact.proto ./pairing.proto ./push_notifications.proto ./emoji_reaction.proto ./enums.proto ./shard.proto ./group_chat_invitation.proto ./chat_identity.proto ./communities.proto ./pin_message.proto ./anon_metrics.proto ./status_update.proto ./sync_settings.proto ./contact_verification.proto ./community_update.proto ./community_shard_key.proto ./url_data.proto ./community_privileged_user_sync_message.proto ./profile_showcase.proto ./segment_message.proto
google/protobuf/timestamp.proto: File not found.
anon_metrics.proto:6:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
anon_metrics.proto:29:3: "google.protobuf.Timestamp" is not defined.
protocol/protobuf/service.go:7: running "protoc": exit status 1
```

I can see that there is Makefile job to install a protogen binary

https://github.com/status-im/status-desktop/blob/663364452e7e4ac8ffdddcfccb5a819fa74d71a8/Makefile#L449

However, this installs a `protoc-gen-go` binary in `$GOPATH`, not `protoc`.

How are we supposed to compile now?

Also did a `git clean -dfx` just in case, and it did not help. (as well as `make update`

### Additional Information

- Status desktop version: 663364452e7e4ac8ffdddcfccb5a819fa74d71a8
- Operating System: Fedora 40

**Comment by caybro** [comment]
Make sure to also install `protobuf-develop`

**Comment by igor-sirotin** [comment]
Can you try to install both `protobuf-compiler` and `protobuf-develop` ?

The former will provide `protoc`. 
And the latter will fix the issue you mentioned.

-----
```
google/protobuf/timestamp.proto: File not found.
anon_metrics.proto:6:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
anon_metrics.proto:29:3: "google.protobuf.Timestamp" is not defined.
```
This error means that `protoc` was found, but `timestamp.proto` wasn't.
And `timestamp.proto` is installed with `protobuf-develop` package.

**Comment by fryorcraken** [comment]
Fixed with 

```
sudo dnf install protobuf-compiler protobuf-develop
```
