### ISSUE TITLE
[RenameGroupPopup] Wrong group chat name validation

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#16523]
# Bug Report
The `&` sign is not an allowed character

![Image](https://github.com/user-attachments/assets/d53eca2c-6784-4c06-821b-b6b58edd0593)

## Description

- the default created group chat name fails the validation
- the whole popup has fixed height and is not scrollable -> impossible to change the color

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
@benjthayer do we have any more up-to-date designs of this? The dialog title doesn't reflect the fact we can change the group color as well

**Comment by caybro** [comment]
Groupchat spec for reference: https://github.com/status-im/feature-specs/blob/d66c586f13cb1fa0486544030148df68e06928f0/content/raw/chat/group_chat.md

**Comment by benjthayer** [comment]
> [@benjthayer](https://github.com/benjthayer) do we have any more up-to-date designs of this? The dialog title doesn't reflect the fact we can change the group color as well

Hey @caybro - thanks for raising, I see you point. It's more or less the same on mobile. I think it's ok that the user can edit the colour from this flow without it being specified in the title tbh. I'm not a fan of `Edit group name, image and colour` (too long) and similarly `Edit group` seems misleading given this is not where you manage members from. 

WDYT @xAlisher ?

![Image](https://github.com/user-attachments/assets/f836b92a-2325-4d47-8384-fd20ffe8f758)
