### ISSUE TITLE
Swap toast notification shows zeroes

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16564]
# Bug Report

## Description

![Image](https://github.com/user-attachments/assets/283dadc8-b147-4e42-8639-ea013fa76627)

## Steps to reproduce

Just do swap and check toast when swap starts

#### Expected behavior

Values are not zeroes, reflecting the correct amount user entered for swap

### Additional Information

- It works fine in 2.30
- Status desktop version: master and 2.31 rc1

**Comment by caybro** [comment]
Looks like a rounding error (value too small)? :)

**Comment by anastasiyaig** [comment]
the corresponding PR is merged to release. the pr wont be cherry picked as we agreed to fix all the notifs in bigger task for 2.32
