### ISSUE TITLE
Swap transaction - Wrong copy on the tooltip of the 'Swap' button

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16568]
# Bug Report

## Steps to reproduce

1. Do a Swap transaction of ERC20 to ERC20 to get an approval sign, for example DAI to USDT
2. Approve the DAI spending cap to Swap, check that the tooltip is correct
3. Once the Approval is signed, the 'Swap' button is enabled

#### Expected behavior
when hovering over the 'Swap' button, it should be related to the Swap transaction and not to the Approval
 
#### Actual behavior
The tooltip when user approves the spending cap is correct here:
https://github.com/user-attachments/assets/a091a1f2-f994-48e1-9038-76a39858abe4
But, after approving, the Swap button is enabled, but the tooltip copy is wrong 'Approve DAI spending cap to Swap'

![Image](https://github.com/user-attachments/assets/f39cbfb2-6f70-45a2-99ee-59d86161712d)

### Additional Information

- Status desktop version: 2.31.rc-0
- Operating System: Mac OS Sonoma

**Comment by Khushboo-dev-cpp** [comment]
closed by https://github.com/status-im/status-desktop/pull/16647
