### ISSUE TITLE
No feedback after token approval. Once the approval is confirmed the Swap dialog becomes editable again, with the Swap button enabled

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16569]
# Bug Report

## Description

No feedback after token approval. Once the approval is confirmed the Swap dialog becomes editable again, with the Swap button enabled (a really subtile change there in the modal. Maybe obvious for people that worked on it. But it tricked me to think it's broken until @Khushboo-dev-cpp explained the difference 😄). IMO that's not very clear for the user. Ideally the user knows in advance that we'll request 2 actions and once the Swap flow started, the maybe the input data cannot be changed until user reject or error. E.g. IIRC Uniswap uses two checkboxes in the modal. Once the approval is completed, the approval checkbox is green and the Swap checkbox is pending.
cc @benjthayer @alexjba @benjthayer for visibility. This issue was created to track separately issue #1 described in https://github.com/status-im/status-desktop/issues/16563

No feedback after token approval. Once the approval is confirmed the Swap dialog becomes editable again, with the Swap button enabled
This is confusing because the user has approved a certain balance of spending cap, and then they can still go ahead and modify the Swap amount, and the Sign button is still enabled.

## Steps to reproduce

Case 1: User modifies the balance amount to a lower amount after the approval has been made
1. Start a Swap transaction for example USDT 0.30 to USDC
![Image](https://github.com/user-attachments/assets/2a1429a7-53a3-4a10-a193-7e3184a47183)
2. Approve the USDT spending cap
![Image](https://github.com/user-attachments/assets/fd62803e-f60c-448f-88ea-2c56b10b37a7)
3. The 'Swap' button is enabled but user can still modify the Swap conditions (in this case the amount to swap has been lowered)
![Image](https://github.com/user-attachments/assets/1d144e1f-127c-496e-9b5f-2f9a7b888bbd)
4. User is able to Sign without any warning
![Image](https://github.com/user-attachments/assets/be7b5b03-2b91-4894-a7bd-2f440511d04f)

Case 2: User modifies the balance amount to a higher amount after an approval of a lower spending cap has been made and signed
In this case, the 'Sign' Button turns back to 'Approve', if user either:
- modifies the balance for a higher amount
- modifies the asset pair
https://github.com/user-attachments/assets/354fc528-dbc3-45c1-8879-43c6cb1b0a43

#### Actual behavior

https://github.com/user-attachments/assets/1e889be9-fff7-4f0c-b3f6-9f1b64be95a5

### Additional Information

- Status desktop version:
- Operating System:

**Comment by anastasiyaig** [comment]
the corresponding PR is merged to release. the pr wont be cherry picked as we agreed to fix all the notifs in bigger task for 2.32
