### ISSUE TITLE
Package name shows wrong versioning

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16561]
# Bug Report

## Description

![Image](https://github.com/user-attachments/assets/8b160d3a-9e94-40ab-be5b-26b4df135f27)

https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.31.x/

## Steps to reproduce

Donwload build from release branch above

#### Expected behavior

Version is set to 2.31

**Comment by caybro** [comment]
Because of https://github.com/status-im/status-desktop/issues/12349

**Comment by anastasiyaig** [comment]
ya, i think for releases we did that manually all the time, but forgot this time :)

**Comment by jrainville** [comment]
Fixed @iurimatias
