### ISSUE TITLE
Add "Mark as Trusted" and "Remove trusted mark" to the profile context menu

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#16586]
Works nicely, I just think we are missing the "Mark as trusted" and "Remove trusted mark" from ther profile context menu. Right now, the only place to set those is going to the Profile dialog, and opening the hamburger menu there

_Originally posted by @caybro in https://github.com/status-im/status-desktop/pull/16548#pullrequestreview-2388070311_

**Comment by caybro** [comment]
I can take this when the backend is merged
