### ISSUE TITLE
Swap - The success toast is not launched when a successful swap transaction occurs

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16585]
# Bug Report

## Steps to reproduce

1. Perform a successful Swap transaction

#### Expected behavior

As per user story SD-17 Notifications
```
Given an Swap transaction succeeds
Then a success toast is launched with text: "Swapped {Input Amount} {Input Asset} to {Output Amount} {Output Asset} in {Selected Account} using {DApp URL} on {Selected Network}"
```
Figma: https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3542-496941&node-type=instance&m=dev
![Image](https://github.com/user-attachments/assets/729452ff-4b19-451c-9526-228ff1cc8e64)

#### Actual behavior
No notification toast for successful swap displays

https://github.com/user-attachments/assets/e1967ddb-6624-409b-8b92-18160b47363e

### Additional Information

- Status desktop version: 2.31 rc-1
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
Removing from 2.31 scope as we don't have data available in that format to fix for 2.31
This issue will be worked in base of new designs https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25111-368170&node-type=instance&m=dev and implemented on a future release

**Comment by Khushboo-dev-cpp** [comment]
@saledjenic Assigning it to you as you will be handling these parts in your notification mechanism rework.

**Comment by saledjenic** [comment]
Closing this in favour of this one https://github.com/status-im/status-desktop/issues/16338
