### ISSUE TITLE
Storybook: Add switch determining how stores are resolved in QtCreator

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#16582]
## Description

In `Storybook` project opened in `QtCreator`, store components are currently resolved to stubs, which is not handy because those are just empty files. In most cases it's handier to resolve to real stores or have a switch for easily setting desired behavior.

**Comment by caybro** [comment]
Btw the same happens to the real app code, if you have both Status and Storybook projects open at the same time in QtC
