### ISSUE TITLE
[Community] No way to directly add/invite users to community

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#16597]
Suggestion here:
![Image](https://github.com/user-attachments/assets/018a0ae0-6375-45ad-83fb-e1f4451053d2)

The only way to add/invite members is by right clicking the secondary nav icon; far from ideal I'd say
it took me quite some time to figure out 🙂 I think we'd benefit from having a button in the topright corner on this page to "Add/invite people", much like we have on all the other pages, .eg.:

![Image](https://github.com/user-attachments/assets/ceb58bcb-0847-426a-8874-ae09e1cbbf04)

**Comment by jrainville** [comment]
I don't mind your idea. It's simple.

Just an FYI, there is also this button that does it, but usually people remove it:

![Image](https://github.com/user-attachments/assets/3957d5b6-b0a8-49fd-b7bf-d01b8d89f0db)

Also, another FYI, the "Add members" is really just sending an invite. maybe we should rename the buttons to `Invite People` like the context menu has.

**Comment by benjthayer** [comment]
> CC [@benjthayer](https://github.com/benjthayer) [@xAlisher](https://github.com/xAlisher) [@jrainville](https://github.com/jrainville) [@iurimatias](https://github.com/iurimatias) thoughts?

100% agree. As mentioned in chat also @caybro I'd go one further and replace this Chat icon in the context of the community with a context menu of community level actions much like Discord do. The Chat icon button here feels a little redundant - it suggests by its placement that the user can message anyone in the community but when launched, you still can only message mutual contacts - which the user can do by heading to the Chat app.

Odd:
![Image](https://github.com/user-attachments/assets/c014b9ae-406c-4e2e-be95-4ab5180b2543)

Much better:
![Image](https://github.com/user-attachments/assets/5d77d0bf-91f6-429f-a818-7cae1a1832a3)

**Comment by jrainville** [comment]
> I'd go one further and also replace this Chat icon in the context of the community with a context menu of community level actions much like Discord do

While I agree that the "Start chat" button is very weird, we can't just remove/change it without a big change to the current design, because that button is the only way to start a group chat and to a lesser extent, the fastest and easier way to create a 1-1 chat and send contact requests.

**Comment by benjthayer** [comment]
> While I agree that the "Start chat" button is very weird, we can't just remove/change it without a big change to the current design, because that button is the only way to start a group chat and to a lesser extent, the fastest and easier way to create a 1-1 chat and send contact requests.

![Image](https://github.com/user-attachments/assets/84c58035-c268-46c2-8804-7112ea6a51ea)

Oh sorry I wasnt saying to remove it completely - we would show it when the user is in Chat but when they click on a community, we swap the action out to a context menu (same button placement but a kebab type icon button which launches the community level controls) WDYT?

**Comment by jrainville** [comment]
> Oh sorry I wasnt saying to remove it completely - we would show it when the user is in Chat but when they click on a community, we swap the action out to a context menu (same button placement but a kebab type icon button which launches the community level controls) WDYT?
> 
> Kind of like how when the user is in the Wallet, we change that button to a create new account button.

Ah yes that makes more sense. I think it works. I wonder if it's gonna be confusing to lose the old behaviour in the community, but to be fair, the behaviour was weird from the start.

**Comment by benjthayer** [comment]
> Ah yes that makes more sense. I think it works. I wonder if it's gonna be confusing to lose the old behaviour in the community, but to be fair, the behaviour was weird from the start.

Yeah maybe - personally I found it weird as a new user that the chat there wasn't in any way contextual to the Community. I'll do a quick mockup of both @caybro 's concept and this and we can decide 👍

**Comment by caybro** [comment]
Cool! My initial idea was to really just add the button to the Settings/Members screen but having it more aligned to what Discord does makes more sense to me idd

**Comment by benjthayer** [comment]
> Cool! My initial idea was to really just add the button to the Settings/Members screen but having it more aligned to what Discord does makes more sense to me idd

I've created a couple of quick flows showing both concepts - addition of "Invite People" button top right of members list and Discord style menu from Community header banner. Explored how the right-click menu can also be aligned to this. We don't have to include all of these menu items but I think all of them have utility and bring us closer to Discord and the Mobile app.

Invite People button in Members list:
https://www.figma.com/design/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?node-id=54586-222303&t=KVIFP84lOERJr3qq-4

Community context menu:
https://www.figma.com/design/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?node-id=54586-298873&t=KVIFP84lOERJr3qq-4

Let me know what you think. If you're keen on one / both routes I can finalise the designs.

**Comment by caybro** [comment]
> > Cool! My initial idea was to really just add the button to the Settings/Members screen but having it more aligned to what Discord does makes more sense to me idd
> 
> I've created a couple of quick flows showing both concepts - addition of "Invite People" button top right of members list and Discord style menu from Community header banner. Explored how the right-click menu can also be aligned to this. We don't have to include all of these menu items but I think all of them have utility and bring us closer to Discord and the Mobile app.
> 
> Invite People button in Members list: https://www.figma.com/design/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?node-id=54586-222303&t=KVIFP84lOERJr3qq-4
> 

This one is a no brainer 👍 

> Community context menu: https://www.figma.com/design/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?node-id=54586-298873&t=KVIFP84lOERJr3qq-4
> 

Made some comments in the Figma; there's a lot of menu items that are a bit unclear (at least to me) or would definitely require some more work elsewhere. But in general, I like this approach better than having the misleding "Start chat" button there

**Comment by benjthayer** [comment]
> Made some comments in the Figma; there's a lot of menu items that are a bit unclear (at least to me) or would definitely require some more work elsewhere. But in general, I like this approach better than having the misleding "Start chat" button there

Thanks @caybro I've replied and amended the context menus. We can definitely split this into 2 tasks given the community context menu item is a little larger and perhaps requires further design and dev review.

**Comment by jrainville** [comment]
> Let me know what you think. If you're keen on one / both routes I can finalise the designs.

I like both.

Like Lukas said, the new menu items, while pretty nice, should be added as further work, since some of them require some non negligible work (looking at you "View Token Requirements")

So yeah, splitting the community context menu changes in two issues sound good to me

**Comment by benjthayer** [comment]
> So yeah, splitting the community context menu changes in two issues sound good to me

Sounds like a plan!
