### ISSUE TITLE
New contact request notification without contact request

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16594]
# Bug Report

## Description

Related mobile bug: https://github.com/status-im/status-mobile/issues/21438

In some cases a new contact request notification is being shown with the contents of a received message, separate to an actual contact request taking place.

1. Sent contact requests from A to B
2. A goes offline
3. B accepts and sends messages
4. A goes online
5. Message received OK and existing contact request notification updated to accepted
6. New notification added for the 4th message received as if it's a contact request

![Image](https://github.com/user-attachments/assets/e575a52b-59ab-41d1-a066-5869073c93ac)

### Additional Information

- Status desktop version: 2.31 RC 1
- Operating System: Mac

**Comment by jrainville** [comment]
I just did some fixes to contact requests. I wonder if I fixed this by the side.

**Comment by jrainville** [comment]
It worked for me in this one example:
![Image](https://github.com/user-attachments/assets/dffe24fc-44eb-477a-8b94-d858d669d595)

I'll close since I think I fixed it. You can reopen if it happens again
