### ISSUE TITLE
Suggested mentions only lists "everyone"

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16602]
# Bug Report

## Description

In a channel, typing @ now only gives the suggestion of "everyone" instead of also displaying other users.

Manually typing the @<display name> continues to work.

It seems likely that this was introduced as part of a refactor - it was found that in 2.30.1 this same behaviour exists in 1-1 and group chats but communities work as expected. 

## Steps to reproduce

1. Create new community and have other users join
2. In a channel type @ and see that only "everyone" is available

![Image](https://github.com/user-attachments/assets/502a5f3b-66fb-4dc6-8b47-a23eb5e1b37c)

#### Expected behavior

Typing @ suggests everyone and other members of the channel or group

### Additional Information

- Status desktop version: 2.31 RC 1
- Operating System: Mac

**Comment by caybro** [comment]
Are there any warnings in the log/console output?

**Comment by jrainville** [comment]
I ended up creating a new issue. The fix for this one is done, so might as well open a PR and then I can work on the new one, since it's not as straightforward.

New issue here: https://github.com/status-im/status-desktop/issues/16614
