### ISSUE TITLE
Community settings does not show pending requests to join

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16600]
# Bug Report

## Description

Requests to join are being displayed in notification centre but not in community settings pending requests.

Confirmed this was working in 2.30.1

## Steps to reproduce

1. Create an open community with request to join enabled
2. Request to join community from another account
3. Observe notification is displayed but not listed in pending requests

![Image](https://github.com/user-attachments/assets/ef742529-6668-4eab-958f-8900de553230)

#### Expected behavior

Requests to join are shown in community settings, pending requests and in notification centre.

### Additional Information

- Status desktop version: 2.31 RC 1
- Operating System: Mac

**Comment by anastasiyaig** [comment]
@jrainville that got broken in 2.31 , worth fixing i think, feels like just UI issue maybe? wdyt

**Comment by jrainville** [comment]
Yeah I can fix it. I know I did a lot of refactors and I think of my latest refactor maybe fixes it, but it's too big to put in the release 😄 
I'll find a simple fix
