### ISSUE TITLE
Adding ens contacts in the profile view is not working correctly

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1660]
It says user not found, on a valid chat key: 
<img width="495" alt="Screenshot 2021-01-14 at 10 52 57" src="https://user-images.githubusercontent.com/52249767/104574825-ca87b680-5656-11eb-9900-5971f6fbb795.png">

Found on this PR: https://github.com/status-im/nim-status-client/pull/1659

**Comment by PascalPrecht** [comment]
Duplicated of #1617

**Comment by PascalPrecht** [comment]
Reopening because, while the reported issue is already tracked, we found out the `Add Contact` button doesn't seem to be working.

**Comment by iurimatias** [comment]
re-opening, this issue includes searching for an ENS name for e.g

**Comment by iurimatias** [comment]
this issue is still there in profile -> contacts -> add contact ; we need to update this view to work the same as the start new chat form

**Comment by PascalPrecht** [comment]
I don't follow.
Two things:
1. Entering an ENS name and getting a search result seems to work fine
2. Making this view exactly the way it is when starting a new chat is probably not what we want, given that we already know we want to add a *new* contact. Also, the add contact form hasn't been designed this way.

@iurimatias can you clarify these two please?

**Comment by iurimatias** [comment]
@PascalPrecht this is what I mean, that modal is still the old one/design at least for the ENS names, and we need to update it


https://user-images.githubusercontent.com/176720/111662583-6dd78200-87e6-11eb-80ae-c64a04a75fd3.mov

**Comment by simonricoo** [comment]
@iurimatias you are right this is the "old way". However, it cant work exactly the same as starting a 1:1 chat modal. Had a chat with @PascalPrecht so I designed an optimised version for adding contacts based on the new way we are using for starting a 1:1 chat. https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=2390%3A47
