### ISSUE TITLE
The permissions view is too wide

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#16617]
# Bug Report

## Description

![Image](https://github.com/user-attachments/assets/e6e5b151-a9bc-443a-af3c-081295b5cd81)

It should only go up to the right of the `Add new permission` button, similar to the Airdrop view:

![Image](https://github.com/user-attachments/assets/71622e4a-9014-406c-a25e-c0e02ebe5e67)

## Steps to reproduce

0. Be owner of a new community
1. Go to the admin screens
2. Select Permissions (I guess you need to not have any permissions yet)

#### Expected behavior

The view's width matches the design

#### Actual behavior

The view goes all the way to the right

### Additional Information

- Status desktop version: 2.31.0 RC1
- Operating System: Ubuntu 22

**Comment by caybro** [comment]
> It looks fine once a permission is added: ![Image](https://github.com/user-attachments/assets/b5ba41de-66b7-4133-9024-31f98cc13850)

Yeah, just the `initialItem` was wrong
