### ISSUE TITLE
Share community link is gone

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16637]
# Bug Report

## Description

Share community link is gone

![Image](https://github.com/user-attachments/assets/2c244ffa-a8e5-420f-979f-6314e700ea95)

### Additional Information

- Status desktop version: master

**Comment by anastasiyaig** [comment]
@jrainville perhaps an easy fix, it got broken recently, not in release yet

**Comment by anastasiyaig** [comment]
@jrainville then assigning to you :)

**Comment by caybro** [comment]
It was this comment: https://github.com/status-im/status-desktop/pull/16508#pullrequestreview-2391854639

**Comment by caybro** [comment]
> [@jrainville](https://github.com/jrainville) then assigning to you :)

OK, let me have a look 💪

**Comment by caybro** [comment]
Most likely have the fix locally already

**Comment by jrainville** [comment]
> It was this comment: [#16508 (review)](https://github.com/status-im/status-desktop/pull/16508#pullrequestreview-2391854639)

I don,t know what happened. I for sure checked that line when I saw your comment, I even commented with the line 🤔 . Maybe there was a rebase that broke it.

Anyway, thanks for fixing
