### ISSUE TITLE
Advanced "Chat scrolling" option doesn't respect the option set

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#16671]
# Bug Report

## Description

Advanced "Chat scrolling" option doesn't respect the option set

## Steps to reproduce

1. Open Status desktop 2.30.0
2. Go to ⚙ Settings > ⚙ Advanced
3. In the **Chat scrolling** section, click **>** to open the options
4. Select any chat scrolling option, eithere **System** or **Custom**
5. Close the **Chat scrolling** dialog

#### Expected behavior

The Chat scolling option honors the option set.

#### Actual behavior

The Chat scrolling option doesn't change, no matter what's the option chosen.

### Additional Information

- Status desktop version: 2.30.1
- Operating System: macOS Sequoia, 15.0.1

![Image](https://github.com/user-attachments/assets/b2ce7f40-f08d-485d-a183-98a8cdd4001b)

**Comment by caybro** [comment]
Already fixed, can't reproduce in master or 2.31
