### ISSUE TITLE
List of account is not shown for custom derivation path when clicking Select Address

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16683]
# Bug Report

## Description

![Image](https://github.com/user-attachments/assets/92bde005-9e8e-47f7-8cee-0cb44de00c09)

```
WRN 2024-11-01 08:05:21.622Z qt warning                                 topics="qt" tid=21431780 text="QQuickItem::stackBefore: Cannot stack QQuickRectangle(0x6000037c72e0, parent=0x6000079f5b00, geometry=0,0 448x0) before QQuickRepeater(0x6000074d4a50), which must be a sibling" file=:0 category=default
```

## Steps to reproduce

Open add wallet account modal
Edit derivation path
Select any derivation path option
Click Select Address

#### Expected behavior

List of addresses is displayed when clicking Select Address

![Image](https://github.com/user-attachments/assets/b56f0b3f-021d-4694-a8e1-22a8fc3239b4)

#### Actual behavior

List is not there

### Additional Information

- Status desktop version: master

**Comment by anastasiyaig** [comment]
@caybro leftover for recent fix? The warning looks pretty much the same

**Comment by caybro** [comment]
> [@caybro](https://github.com/caybro) leftover for recent fix? The warning looks pretty much the same

Could be a similar issue, yeah; I'll have a look

**Comment by caybro** [comment]
> > [@caybro](https://github.com/caybro) leftover for recent fix? The warning looks pretty much the same
> 
> Could be a similar issue, yeah; I'll have a look

Idd, it is a similar issue, albeit in a different component now
