### ISSUE TITLE
[Community] Changing logo doesn't get propagated

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#16688]
Perhaps related (or the same issue):
 
![Image](https://github.com/user-attachments/assets/c4701515-6649-4c52-81d6-b2b887a54e95)
 
If I change the community logo, it's persisted but will update only after app restart (I suspect the banner too but this one is hard to check as it's not visible anywhere else in the app) 

 _Originally posted by @caybro in [#16672](https://github.com/status-im/status-desktop/issues/16672#issuecomment-2451535908)_

**Comment by jrainville** [comment]
Turns out adding the role is not enough. I'm very confused why it doesn't want to update. I checked the url from the localhost and it's indeed the new image. I've been banging my head on this for a while and I can't understand. The model is passed correctly as far as I can see, so the `dataChanged` should propagate correctly.

I'll give it a rest and come back to it.

In the meantime, I found and fixed this: https://github.com/status-im/status-go/pull/6026

**Comment by caybro** [comment]
> Turns out adding the role is not enough. I'm very confused why it doesn't want to update. I checked the url from the localhost and it's indeed the new image. I've been banging my head on this for a while and I can't understand. The model is passed correctly as far as I can see, so the `dataChanged` should propagate correctly.
> 
> I'll give it a rest and come back to it.
> 
> In the meantime, I found and fixed this: https://github.com/status-im/status-go/pull/6026

Is the URL still the same after the update, or a different one? Because if the former is true, the QML Image simply won't reload

**Comment by jrainville** [comment]
> Is the URL still the same after the update, or a different one? Because if the former is true, the QML Image simply won't reload

yes. It's something like `localhost://communityId="0x1234...890"&format="thumbnail"`.

Is there a way to force the QML to reload the image?

**Comment by caybro** [comment]
> > Is the URL still the same after the update, or a different one? Because if the former is true, the QML Image simply won't reload
> 
> yes. It's something like `localhost://communityId="0x1234...890"&format="thumbnail"`.
> 
> Is there a way to force the QML to reload the image?

Yeah, sth like:
```qml
image.source = ""
image.source = newUrl
```

**Comment by jrainville** [comment]
> > > Is the URL still the same after the update, or a different one? Because if the former is true, the QML Image simply won't reload
> > 
> > 
> > yes. It's something like `localhost://communityId="0x1234...890"&format="thumbnail"`.
> > Is there a way to force the QML to reload the image?
> 
> Yeah, sth like:
> 
> image.source = ""
> image.source = newUrl
> oh, and you probably have to set `cache: false` on the `Image`

This worked, but the code is **very** ugly.

I created a commit here https://github.com/status-im/status-desktop/commit/85dd85d56d8c93f140f2bc04a2ae9809b8f89a1d, but I think I'll try to see if I can fix it on the status-go side by appending some sort of index at the end of the URL when it gets updated. It would be **much cleaner**

**Comment by caybro** [comment]
> > > > Is the URL still the same after the update, or a different one? Because if the former is true, the QML Image simply won't reload
> > > 
> > > 
> > > yes. It's something like `localhost://communityId="0x1234...890"&format="thumbnail"`.
> > > Is there a way to force the QML to reload the image?
> > 
> > 
> > Yeah, sth like:
> > image.source = ""
> > image.source = newUrl
> > oh, and you probably have to set `cache: false` on the `Image`
> 
> This worked, but the code is **very** ugly.
> 
> I created a commit here [85dd85d](https://github.com/status-im/status-desktop/commit/85dd85d56d8c93f140f2bc04a2ae9809b8f89a1d), but I think I'll try to see if I can fix it on the status-go side by appending some sort of index at the end of the URL when it gets updated. It would be **much cleaner**

Yeah this is indeed ugly 😄 BTW I just found out that we have this function in Utils.qml:
```qml
    function addTimestampToURL(url) {
        return globalUtilsInst.addTimestampToURL(url)
    }
```

which calls:
```nim
import times

proc addTimestampToURL*(url: string): string =
  if url.len == 0:
    return ""

  let timestamp = epochTime()

  if '?' in url:
    return url & "&timestamp=" & $timestamp
  else:
    return url & "?timestamp=" & $timestamp
```

and we wrap some images with it already in QML code (like profile icon).

The NIM code above is kinda naive but we could actually call sth like that already in the models serving images; this way the URL won't be the same, and thus no need to disable caching, or forcing an empty URL to reload the Image on the QML side

**Comment by jrainville** [comment]
I have status-go code that adds a version number to the image path and it works in the status-go side. The branch is here: https://github.com/status-im/status-go/compare/fix/community-image-not-updating?expand=1

However, even when using that and confirming with logs that the dataChanged is called, the image still doesn't update. I even put the cache to false. See my wip code with logs here: https://github.com/status-im/status-desktop/compare/fix/community-image-not-updating-2?expand=1

Here is what it looks like. You can see that I even confirm that the URL points to the right image now:

https://github.com/user-attachments/assets/bdbbf981-7c32-4a64-81dd-9d5b2e7dbf1d

**Comment by caybro** [comment]
> I have status-go code that adds a version number to the image path and it works in the status-go side. The branch is here: https://github.com/status-im/status-go/compare/fix/community-image-not-updating?expand=1
> 
> However, even when using that and confirming with logs that the dataChanged is called, the image still doesn't update. I even put the cache to false. See my wip code with logs here: https://github.com/status-im/status-desktop/compare/fix/community-image-not-updating-2?expand=1
> 
> Here is what it looks like. You can see that I even confirm that the URL points to the right image now:
> 
>  image-doesnt-update.webm

How does the resulting URL look like? I fear that if you just append a query there, it still won't work (QML will likely discard that part)

**Comment by jrainville** [comment]
> How does the resulting URL look like? I fear that if you just append a query there, it still won't work (QML will likely discard that part)

Indeed, I just change the version number in the query param.

Why would it discard it? 

Also, isn't it what `addTimestampToURL` does also? Why does it work for that one?

```
OLD IMAGE https://Localhost:46739/communityDescriptionImages?communityID=0x03c5ece7da362d31199fb02d632f85fdf853af57d89c3204b4d1e90c6ec13bb23c&name=thumbnail&version=2
NEW IMAGE https://Localhost:46739/communityDescriptionImages?communityID=0x03c5ece7da362d31199fb02d632f85fdf853af57d89c3204b4d1e90c6ec13bb23c&name=thumbnail&version=3

```
