### ISSUE TITLE
Adapt Fees component

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#16706]
Adapt to new simple designs

Design https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25660-251226&t=x7Ukt7ixxp7Ji84n-4

1. Simplified single entry in fees as we dont have multi tx as of now
2. Add error state to be shown in case of insufficient fees

**Comment by micieslak** [comment]
My suggestion here is to create a new separate component, and keep the existing one, multi-line version for the future. It's purely ui component with well defined api so it can be useful later.
