### ISSUE TITLE
Adapt AmountToSend

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#16703]
Tasks created to adapt the AmountToSend to follow new simple send designs https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25202-37778&t=x7Ukt7ixxp7Ji84n-4
https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25660-238506&t=x7Ukt7ixxp7Ji84n-4

Enhancements: 
1. Removing the `Recipient will receive` side of the header leaves more room for ‘Amount to send’ value entry. This means progressive pt size reduction for longer digits is not required. Instead we should block entry when header area is filled given there is adequate room for 99% of realistic entries. 
2. The user should only be able to enter the maximum number of decimals specified by the token contract however.
3. In case of max amount being clicked in case of ETH, this input area should display a tooltip with text "X ETH reserved for gas"

**Comment by micieslak** [comment]
`AmountToSend` seems to be good candidate to be reused here without any significant API changes. Visual layout needs to be adjusted. `AmountToReceive`, not refactored so far can be removed.
