### ISSUE TITLE
Community Settings/Members: nickname change not reflected in a delegate

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#16735]
# Bug Report

## Description

When adding/changing/removing nickname in community settings / members view, the change is not reflected in a delegate.

Probably there is a problem with the model's notification on a nickname role.

https://github.com/user-attachments/assets/c66ce4b1-02b5-49bb-9300-748c7a3d9d4a

## Steps to reproduce
1. Go to community
2. Go to community settings / members
3. Right click on any member (not self)
4. Select Add/Change/Remove nickname
5. Set/change/remove nickname

#### Expected behavior
The change is immediately visible in a given delegate

#### Actual behavior
The change is applied (visible after restart or via other lists) but not applied properly to the list in settings/members.

**Comment by jrainville** [comment]
Fixes here https://github.com/status-im/status-desktop/pull/16959
