### ISSUE TITLE
Wallet Connect - Zapper.fi - Sign Request does not show the correct account to connect, transaction does not complete

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16747]
# Bug Report

## Description

The Sign Request does not show the specific account that the dApp will connect to.
When scrolling through the information of the Sign Request, the app becomes laggy
There are many errors on the console

## Steps to reproduce

1. Go to https://yearn.fi/v3/
2. Connect the dApp to the Desktop Wallet using a specific account, for the purpose of this testing 'Account 1' was connected
3. Choose an asset to deposit for example USDC
4. Choose an amount and select 'Deposit and Stake'
5. On the Desktop app, when the Sign Request pops up, try to scroll. Notice the scroll is very laggy. Also notice that the Account to connect is not showing the correct information

#### Expected behavior
- Sign Request to display the correct account to connect to

#### Actual behavior
[app_20241111_145345.log](https://github.com/user-attachments/files/17708101/app_20241111_145345.log)

On the desktop side:
- Console errors display
- The account to connect to is not correctly displaying; it should show 'Account 1'
- When scrolling, the pop-up becomes laggy

On the dApp side:
- Transaction does not go through, after 5-10 minutes of the transaction loading, error shows 'Unknown RPC request'

The error seems to be related to the Fees, is there anything that can be done from the desktop app/s end? such as providing an error message (not enough balance for fees, etc) to guide the user on a possible reason why they cannot use this dApp? 

```
ERR 2024-11-11 20:47:45.711Z qt error                                   topics="qt" tid=91663074 text="\nfromString (qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:87)\ngetEstimatedMaxFees (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:418)\ngetEstimatedFeesStatus (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:469)\nupdateFeesParamsToPassedObj (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:289)\nonTriggered (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:665)" file=qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:87 category=default
ERR 2024-11-11 20:47:45.711Z qt error                                   topics="qt" tid=91663074 text="\nfromString (qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:87)\ngetEstimatedMaxFees (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:419)\ngetEstimatedFeesStatus (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:469)\nupdateFeesParamsToPassedObj (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:289)\nonTriggered (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:665)" file=qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:87 category=default
ERR 2024-11-11 20:47:45.712Z qt error                                   topics="qt" tid=91663074 text="\nfromString (qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:87)\ngetEstimatedMaxFees (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:420)\ngetEstimatedFeesStatus (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:469)\nupdateFeesParamsToPassedObj (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:289)\nonTriggered (qrc:/app/AppLayouts/Wallet/services/dapps/plugins/SignRequestPlugin.qml:665)" file=qrc:/StatusQ/Core/Utils/AmountsArithmetic.qml:87 category=default
```

![Image](https://github.com/user-attachments/assets/254a8207-686f-45c3-91ef-17185aff47bf)

![Image](https://github.com/user-attachments/assets/15e7087d-aac9-40a5-a30e-d43ca94d78dc)

https://github.com/user-attachments/assets/9845c573-5b84-444c-bba5-c3860a9f5850

Test with USDT
There seems to be an error as well, and while dApp connects, the transaction doesn't go through.

![Image](https://github.com/user-attachments/assets/cdfb2daf-433e-45a2-bae7-ba0678e95f96)

https://github.com/user-attachments/assets/888f1ad4-2e1f-400e-a18a-e09656283590

Console log:
[app_20241111_145345.log](https://github.com/user-attachments/files/17708185/app_20241111_145345.log)

### Additional Information

- Status desktop version: build from https://github.com/status-im/status-desktop/pull/16730
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
cc @alexjba for visibility

**Comment by alexjba** [comment]
There are several issues here:
1. Incorrect value. This is what the dApp sends `\"value\":\"0x0\"`
2. Laggy UX. Looks like it's due to the periodic fees. All WC actions are done on the main thread and the fee request is blocking for a short period of time. Now we do periodic checks for the fees, and it blocks every few seconds.
3. Incorrect account in the modal - Something we need to investigate. The address is case sensitive, but the matching should be case insensitive.

**Comment by alexjba** [comment]
Note: The dApp behaves differently based on the Browser. On Safari it won't trigger the transaction request, on Chrome it triggers the tx request, but the value is 0

**Comment by virginiabalducci** [comment]
fixed in https://github.com/status-im/status-desktop/pull/16767
