### ISSUE TITLE
Browser Connect - SIWE authentication sign does not work on appkit-lab.reown.com

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16750]
# Bug Report

## Steps to reproduce

1. Go to https://appkit-lab.reown.com/library/ethers-siwe/
2. Connect to the dApp via Browser Connect
3. Accept the connection request on the desktop app's end

#### Expected behavior
Once the connection is accepted on the dApp's end user sees a 'Sign In' request
When clicking on Sign, the Sign authorization dialog should trigger on the desktop app's end, and when user Signs, the dApp should successfully connect through Browser Connect

#### Actual behavior
Once the connection is accepted on the dApp's end user sees a 'Sign In' request
When clicking on Sign, nothing is triggered on the Desktop App's end, and the dApp shows an error message 'Signature declined'
On the desktop's end, a toast shows 'Disconnected from appkit-lab.reown.com'

https://github.com/user-attachments/assets/0923a076-bfa6-4f0f-b964-18c61c43f687

![Image](https://github.com/user-attachments/assets/bb1427ba-9ef8-4c12-8cd0-2d5596d1cbaa)

![Image](https://github.com/user-attachments/assets/5009fc17-93e1-4b8f-95c0-ec32cb7237c8)

Console log
[app_20241112_092050.log](https://github.com/user-attachments/files/17716660/app_20241112_092050.log)

### Additional Information
This dApp works correctly if connected via Wallet Connect.

https://github.com/user-attachments/assets/d60963b4-6264-4d4f-88cb-776a7d1953a6

- Status desktop version: https://github.com/status-im/status-desktop/pull/16730
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
cc @alexjba

**Comment by alexjba** [comment]
@virginiabalducci personal sign is not implemented on BC. I'm just working on it and will add a PR in a few. 
https://github.com/status-im/status-desktop/issues/16015

**Comment by alexjba** [comment]
@virginiabalducci For reference, the BC currently implements only send transaction.
It's missing: personal_sign, eth_sign, eth_signTypedData_v4, eth_signTypedData, eth_signTransaction

**Comment by virginiabalducci** [comment]
closing this issue as per the comments
