### ISSUE TITLE
Wallet Connect - cannot do transactions on app.aave.com

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16755]
# Bug Report

## Description

It's not possible to complete a transaction on Aave 

## Steps to reproduce

1. Go to app.aave.com
2. Connect to Status desktop using Wallet Connect
3. go to https://app.aave.com/?marketName=proto_optimism_v3 and select an asset to supply
4. Sign the request on the desktop app

#### Expected behavior
After signing the request, the transaction should go through

#### Actual behavior
The transaction does not complete

https://github.com/user-attachments/assets/ffce3a3d-a806-4b9a-b15e-7aed8cf8b90f

[app_20241112_145350.log](https://github.com/user-attachments/files/17733208/app_20241112_145350.log)
[app_20241112_101904.log](https://github.com/user-attachments/files/17733207/app_20241112_101904.log)

### Additional Information

- Status desktop version:  build from https://github.com/status-im/status-desktop/pull/16730
- Operating System: Mac OS Sonoma

**Comment by alexjba** [comment]
@virginiabalducci Can you please have a look on the optimistic explorer to see if the tx has been registered and what's the status? If the tx is successful there could be an issue with the dApp

**Comment by virginiabalducci** [comment]
fixed in  https://github.com/status-im/status-desktop/pull/16767
