### ISSUE TITLE
Set up an new keycard with an existing account screen does not show keypairs

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16785]
### Description

![Image](https://github.com/user-attachments/assets/140806e7-e24d-4020-84d6-9ade92a1a3ea)

https://github.com/user-attachments/assets/cf558fdf-76dd-4b7d-a484-ff1d24744d4f

Expected: this screen should show all key paris that have accounts that are following the default Status' derivation path and not migrated to a Keycard

**Comment by anastasiyaig** [comment]
@micieslak could be related to the changes to settings recently made?

**Comment by caybro** [comment]
Ping @saledjenic but I don't think we've made any recent changes there

**Comment by anastasiyaig** [comment]
@caybro https://github.com/status-im/status-desktop/pull/16676 i remember only this, could it be a case?

**Comment by caybro** [comment]
> [@caybro](https://github.com/caybro) [#16676](https://github.com/status-im/status-desktop/pull/16676) i remember only this, could it be a case?

Nope... this is about the Settings section

**Comment by caybro** [comment]
> okay but it has to be something as it works in 2.31

Hmm ok, maybe some store refactoring @micieslak ? Are there any warnings printed to console when this happens?

**Comment by anastasiyaig** [comment]
sadly no warnings :(
