### ISSUE TITLE
Improvements for community admins

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16790]
### Description

this is the minimum set of improvements needed to enable community admins to perform their duties effectively:

- add ability to copy display name for a contact / member
- add possibility to search for a member by chat key

Currently, searching by chat key is not possible as well as copying display name

![Image](https://github.com/user-attachments/assets/8ddae357-1511-4841-9e9e-a7d801ec8bf1)

![Image](https://github.com/user-attachments/assets/0a404700-1890-45cd-b4db-18f05866f5c0)

**Comment by anastasiyaig** [comment]
@xAlisher @benjthayer do you guys have any UX insights how that could be done? I wonder if any design work is needed there

**Comment by anastasiyaig** [comment]
@jrainville we need to plan that, maybe for 2.33 ?

**Comment by caybro** [comment]
@anastasiyaig @xAlisher where do you want to copy from?

**Comment by anastasiyaig** [comment]
i have no idea, therefore i asked design :D

**Comment by xAlisher** [comment]
It's currently impossible to select and copy display name text from the app, whether in chat or in the profile modal. I suggest making it possible to select the display name with the mouse cursor and press **Ctrl+C** to copy it.

@caybro @anastasiyaig

**Comment by xAlisher** [comment]
Good example https://github.com/user-attachments/assets/f4c31b15-d957-48df-8e30-c2809bbc6d59
Currently in Status
https://github.com/user-attachments/assets/6392c08a-4ddb-4344-8f35-e0f4ab90956e

**Comment by jrainville** [comment]
I think part of this issue is just a bug.

For example, searching by chat key does work:
![Image](https://github.com/user-attachments/assets/c6933920-9188-4ef7-888b-5feebce78711)

However, I think I needed to reload the app to make it work.

I just tested on master and I can't reproduce the issue, so it seems my latest changes to the community updates fixed that already.

So that leaves us with:
> add ability to copy display name for a contact / member

I think @xAlisher 's proposal makes sense. Hopefully it's simple, but sometimes QML doesn't cooperate 😅

**Comment by anastasiyaig** [comment]
@jrainville to make sure, you are able to search through members list in community by public key? i checked in 2.31 and some branch of master today and it did not work to me

**Comment by jrainville** [comment]
> [@jrainville](https://github.com/jrainville) to make sure, you are able to search through members list in community by public key? i checked in 2.31 and some branch of master today and it did not work to me

@anastasiyaig  Hmmm, I think our search is dumb and uses only the elided chat key. 

This works:
![Image](https://github.com/user-attachments/assets/4ba46cfd-e99a-4ca8-9d13-7796503a70dd)

This doesn't work:
 ![Image](https://github.com/user-attachments/assets/8ad9b5fd-a67f-4875-8f62-8d171049c01a)

I assume it should be an easy fix

**Comment by benjthayer** [comment]
@xAlisher @jrainville @anastasiyaig I'd also suggest amending the search prompt by replacing the community name and number of members with what facets can be searched i.e. name (which encompasses display name or nickname) and chat key. WDYT? If agreed, I can amend the designs. 

![Image](https://github.com/user-attachments/assets/9d3c7b45-ef2a-456f-ad5b-43d27aff9d45)
