### ISSUE TITLE
Different balance for some tokens when swap compared to Paraswap. Max value available is different as well

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16828]
### Description

**Problem 1:  Different balance for some tokens when swap compared to Paraswap**

Having account with ~5 DAI, Paraswap allows to swap only half of it. It causes issues in both apps

![Image](https://github.com/user-attachments/assets/1d2c50cb-1b8a-43c5-bad4-df5b89788374)
![Image](https://github.com/user-attachments/assets/e87b8df6-0d43-48da-9c8e-87395c4f46cd)
![Image](https://github.com/user-attachments/assets/8a899c3e-212b-472b-946e-5295eb76836d)

https://github.com/user-attachments/assets/5338b785-fca6-4514-9ee7-c47cb01862aa

https://optimistic.etherscan.io/address/0xf38d2cd3c6ad02dd6f8b68e0a7b2f959819954b6

MM and Etherscan and Desktop app shows 5 DAI for Optmisim, when Paraswap does not

![Image](https://github.com/user-attachments/assets/2fdefa28-ea3d-4825-80f8-7b78fbb5de03)
![Image](https://github.com/user-attachments/assets/ddf343c9-c066-47d6-8d9c-27b84b025adf)
![Image](https://github.com/user-attachments/assets/817d4b9d-b803-42f9-9fbd-e891094147ca)
![Image](https://github.com/user-attachments/assets/ea361bb2-b6ca-44de-818b-24f6010f93ab)

**Problem 2: Different MAX value in Paraswap vs Desktop**

> we have a Max indicator, not a max button. If we had a button, we could simply put the exact amount in the input
> since we don't have a button, if a user wants to manually enter the max amount they currently do not have a place in Status where the exact balance is shown 
> and since what we display rounds to the closest, Max will show something larger than your actual balance in some cases

![Image](https://github.com/user-attachments/assets/1ad8b4f3-0591-440b-b5c9-1b963b8e8602)
![Image](https://github.com/user-attachments/assets/e3c9366e-a70b-4e4c-8379-e6eab5969220)

**Comment by anastasiyaig** [comment]
cc @alaibe @VolodLytvynenko

**Comment by dlipicar** [comment]
This is most likely caused by this logic https://www.notion.so/Wallet-Currency-Amount-Formatting-1648febf1b28479d99e141c74d0916f3 rounding values up. I guess we could ensure MAX always rounds down?
