### ISSUE TITLE
Package to UWP

### ISSUE THREAD

**Issue by danimesq** [status-im/status-desktop#1684]
Porting into the Universal Windows Platform would allow the Status .exe app to be packaged inside an .appx package, listed in the Microsoft Store while using UWP's notifications, live tile and other of its features. Maybe it would be the first Ethereum/Web3 wallet to enter Microsoft Store and take advantage of the UWP's APIs.

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5747
