### ISSUE TITLE
Can't mint tokens for community (Windows): SIGSEGV: illegal storage access

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16858]
**NOTE: happens not only for keycard, but for imported seed as well**

```
SIGSEGV: illegal storage access
```

1. restore account with keycard
2. enable testnets
3. enable managing community on testnets flag
4. create new community
5. open it
6. click manage community
7. click Mint tokens
8. scroll down to account selection

![Image](https://github.com/user-attachments/assets/9a08e37e-b51c-471a-b7c8-423ef7d71db4)

[geth.log](https://github.com/user-attachments/files/17991989/geth.log)

[app_20241203_141529.log](https://github.com/user-attachments/files/17991997/app_20241203_141529.log)

**Comment by alexjba** [comment]
Cannot reproduce! Double checked by @virginiabalducci and @anastasiyaig with similar results
