### ISSUE TITLE
Not possible verify the Linux image GPG signature

### ISSUE THREAD

**Issue by gugol2** [status-im/status-desktop#16861]
# Bug Report

## Description

It is not possible to verify the linux status image with GPG.

## Steps to reproduce

Follow the instructions:

1. `curl -s 'https:///status.app/gpg/release.asc' | gpg --import`

#### Expected behavior

Download and import the Status release public key.

#### Actual behavior

```
gpg: [don't know]: invalid packet (ctb=3c)
gpg: read_block: read error: Invalid packet
gpg: import from '[stdin]' failed: Invalid keyring
gpg: Total number processed: 0
```

### Additional Information

- Status desktop version:  StatusIm-Desktop-v2.31.1-a322b9-x86_64.AppImage
- Operating System: Ubuntu 22.04.5 LTS

**Comment by gugol2** [comment]
By the way my gpg version is:
```
gpg --version
gpg (GnuPG) 2.2.27
libgcrypt 1.9.4
```

I have also tried in and sandbox with Ubuntu 24.04 and gpg 2.4.4 and I got the same result.

**Comment by caybro** [comment]
https://status.app/gpg/release.asc gives a 404

Can we fix that pls @felicio @jakubgs ?

**Comment by jakubgs** [comment]
Where are these instructions at that you followed?

Since we switched the website from `status.im` to `status.app` the old content was simply not copied and there is nothing at:
https://status.app/gpg/release.asc

So the GPG error is a red herring, there's simply no public key file there.

**Comment by jkbktl** [comment]
> Where are these instructions at that you followed?

It's in [docs](https://status.app/help/getting-started/download-status-for-linux#verify-the-status-app-gpg-signature), seems like someone changed links and never tried it.

**Comment by jakubgs** [comment]
Right, a classic case of mindless search and replace.

**Comment by jkbktl** [comment]
It's fixed and can be closed.

**Comment by gugol2** [comment]
> https://status.app/gpg/release.asc gives a 404
> 
> Can we fix that pls [@felicio](https://github.com/felicio) [@jakubgs](https://github.com/jakubgs) ?

Sure, that was the problem, I also got the 404.

Sorry, I did not add the docs in this bug, I took for granted that piece of information.

Now the import of the key works but I am not sure I understand step 3:

> 3. Update the GPG trust database to include the Status' public key:
> echo '1DD92FFA442D4B5C85C039231A151FD0883555FE:6:' | gpg --import-ownertrust

Did I not add the public key already in step 2? Sorry I am not familiar with gpg... 

Anyway it is fixed now, Thanks!!!
