### ISSUE TITLE
Swap - After approving Spending Cap with a keycard the Swap transaction fails

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16867]
# Bug Report

## Steps to reproduce

Have a keycard set up for your account 
1. Approve a spending cap for erc20, for example USDT <-> DAI
2. Sign the approval for spending cap using the keycard
3. Sign the Swap transaction

#### Expected behavior
Sign transaction to proceed

#### Actual behavior

- Nothing happens on the UI
- Error message shows on console:

[app_20241204_104857.log](https://github.com/user-attachments/files/18009701/app_20241204_104857.log)

```
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - card protocol T1
ERR 2024-12-04 14:08:46.440Z error                                      topics="wallet-send-module" tid=115527569 file=module.nim:292 err="unexpected error while keycard signing transaction"
```

https://github.com/user-attachments/assets/f8da8f88-3ec6-4a8b-bc0f-4206b41c3ca8

### Additional Information

- Status desktop version: latest master
- Operating System: Mac OS Sonoma

**Comment by anastasiyaig** [comment]
i see that as well

https://github.com/user-attachments/assets/759c66bd-bb6a-4211-bf74-83cdc1a9fe54

**Comment by virginiabalducci** [comment]
attaching geth.log file 
[geth 2.log.zip](https://github.com/user-attachments/files/18026692/geth.2.log.zip)

**Comment by saledjenic** [comment]
Fixed here https://github.com/status-im/status-go/pull/6177
