### ISSUE TITLE
Wallet connect - The 'connect' button of the Connection request pop up can still be clicked when there is no internet connection

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16882]
# Bug Report

## Steps to reproduce

1. Trigger a connection request via Wallet Connect
2. When the Connection Request pop up displays, disconnect the internet

### Expected behavior
'Connect' button should not be clickable when there is no internet connection

### Actual behavior
'connect' button is clickable

![Image](https://github.com/user-attachments/assets/2b0567a7-daf5-45c4-9bd1-9b222421364c)

https://github.com/user-attachments/assets/606eefd9-6a05-406c-8930-5ece2790d02d

### Additional Information
Related to https://github.com/status-im/status-desktop/pull/16580

- Status desktop version: 2.32 RC-1
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
This was fixed in https://github.com/status-im/status-desktop/pull/16892

**Comment by Alfreddexo** [comment]
@virginiabalducci Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.
