### ISSUE TITLE
system tray icon doesn't look right when on light mode

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1690]

**Comment by simonricoo** [comment]
You mean the menu bar icon right? ![Screenshot 2021-02-08 at 15.37.04.png](https://images.zenhubusercontent.com/5eba533dc999132939d1d6ae/893e5cd2-330c-42d5-9b16-606ce3bc141e)

**Comment by michaelsbradleyjr** [comment]
Yes, in the macOS's light mode the menu bar icon's colors need to be inverted.

Also there's a question as to whether there could be special assets for the menu bar (one for OS dark, the other for OS light) that don't suffer from as much pixelation as the one in the screenshot.

**Comment by PascalPrecht** [comment]
Talked to @simonricoo about this. Turns out we just have to use the SVG version of the icon instead and the OS is gonna take care of inverting the pixels accordingly
