### ISSUE TITLE
Cannot sing tx sent from imported key pair if the profile is migrated to keycard

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#16901]
When the profile key pair is migrated to the keycard, the user cannot sign any tx for any imported key pair.
Getting this error:
![Image](https://github.com/user-attachments/assets/6e86a2c8-409e-4a52-878d-6213acc12e5a)

**Comment by biotq23DE** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Status Desktop Support](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
