### ISSUE TITLE
Change the card date format 

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1692]
<img width="348" alt="Screen_Shot_2021-01-19_at_10_24_52" src="https://user-images.githubusercontent.com/52249767/105014551-de5d5f00-5a40-11eb-8fe7-124d28283bb9.png">
The current format is too long, lets match it with mobile design: so this will look as **JAN 19, 2021**

**Comment by staked-smart-ace** [comment]
Could I work on this issue?
