### ISSUE TITLE
Update Group Naming functionality

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1693]
Lets improve this, when I type Capital letter "A" it displayed as "a" in the input. Do following:
Letters: A → a
Space: SPACE → - (dash)
Symbols: *&.`*@# etc... → don't allow to type these (nothing happens when I type a symbol)
Emojis: 😃 →  don't allow to type these

<img width="560" alt="Screen Shot 2021-01-19 at 10 23 59" src="https://user-images.githubusercontent.com/52249767/105014689-03ea6880-5a41-11eb-94ec-a1c4e9d6eed5.png">

**Comment by simonricoo** [comment]
Allow hitting ENTER to create a group
<img width="584" alt="Screen Shot 2021-01-19 at 10 24 01" src="https://user-images.githubusercontent.com/52249767/105015410-d356fe80-5a41-11eb-9d8b-e68e240f0b14.png">

**Comment by staked-smart-ace** [comment]
Could I work on this issue?
