### ISSUE TITLE
Don't quit the app when clicking on "x" and Enable closing the app with CMD + W

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1694]
Currently we quit the app when clicking on the "x" we should just close it and let it run. This is the expected behaviour on MacOS.
<img width="324" alt="Screen_Shot_2021-01-19_at_13_49_46" src="https://user-images.githubusercontent.com/52249767/105036843-618cae00-5a5d-11eb-89e1-2e0a1e305621.png">

CMD + W (Close window) shortcut is not working on MacOS. The expected behaviour is to close the app (not quit)

So when I click on "x" or hit CMD + W the app should close but still "live" the the app bar
<img width="136" alt="Screen Shot 2021-01-19 at 13 49 53" src="https://user-images.githubusercontent.com/52249767/105037068-b29ca200-5a5d-11eb-8328-a1875babacad.png">

**Comment by simonricoo** [comment]
I can't reopen the app when its closed by "x"

https://user-images.githubusercontent.com/52249767/110110774-9e172d80-7daf-11eb-9d94-49e852a4eb7e.mov

**Comment by iurimatias** [comment]
this has been implemented but is a setting that is false by default, it will be put true by default in #1900
