### ISSUE TITLE
No toast on removal of untrusted mark

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16949]
# Bug Report

## Description

- Remove the untrusted mark from a user via the context menu. 
- No toast is displayed

Expected this in line with other actions from the profile context menu such as remove nickname.

![Image](https://github.com/user-attachments/assets/57165cdc-5e4c-43af-87cf-f1c2cba23e08)

### Additional Information

- Status desktop version: 2.32 RC4
- Operating System: Mac

**Comment by jrainville** [comment]
Moved to 2.33 since it's not a high impact regression worth fixing in the RC

**Comment by caybro** [comment]
Correct assumption @glitchminer :) Looks like this was never implemented though; will do for 2.33

![Image](https://github.com/user-attachments/assets/0f5456d1-ca7d-4b7d-8d31-5f81af30eaf0)
