### ISSUE TITLE
Clicking the a display name in a chat does not open the profile context menu

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16950]
# Bug Report

## Description

- Hovering over a display name still underlines it as if an action is available.
- Clicking the a display name in a chat does not open the profile context menu.

This is likely to have been impacted by the change to allow display names to be copied. The context menu is still available from the profile image.

### Additional Information

- Status desktop version: 2.32 RC 4
- Operating System: Mac

**Comment by caybro** [comment]
Works for me... but I'll double check
