### ISSUE TITLE
Community admin members list - Nickname is not displayed

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16957]
# Bug Report

## Description

- Nicknames are not displayed in the community admin members list
- Nicknames are not displayed in the profile context menu opened from the members list
- A nickname can be set in the profile context menu, but it is not displayed in the list
- If a nickname is set, the profile context menu does not show the options for edit or remove nickname

![Image](https://github.com/user-attachments/assets/ffc8c352-6467-49b3-a431-c819582fa050)

#### Expected behavior

- Nicknames should be displayed in the community admin members list
- The profile context menu options should reflect the current state of the nickname for the selected user

### Additional Information

- Status desktop version: 2.32 RC4
- Operating System: Mac

**Comment by jrainville** [comment]
I just tested and I can reproduce the issue. I discovered that it is a "live update" issue, ie after a minute or two and after a restart, the nickname does appear.

I'll move this to 2.33 then, since the impact is not that big and solves itself after a few minutes.

**Comment by jrainville** [comment]
Turns out it's a very minor fix. I'm fine putting it in the release.
