### ISSUE TITLE
Possible to send a contact request to a blocked user

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16951]
# Bug Report

## Description

Using this function to send a contact request to a blocked user can result in a state after unblocking where 1 user sees the other as a contact but the other does not.

![Image](https://github.com/user-attachments/assets/1d4e13c7-3e0e-42ea-9c76-fb518d04f6b1)

- User A blocks user B
- User B has a pending contact request to user A
- User A clicks on send contact request
- User A & B are contacts, but A is still blocking B

- User A unblocks user B
- User A is no longer a contact with B, but user B is still a contact with A (Messages can be sent 1 way only)
- User A sends a contact request to B, neither users are contacts and the request must be accepted to continue.

#### Expected behavior

Contact requests to blocked users should be disabled?

#### Actual behavior

Possible to send contact requests to blocked users.

### Additional Information

- Status desktop version: 2.32 RC4
- Operating System: Mac

**Comment by anastasiyaig** [comment]
@jrainville would that be for release?
