### ISSUE TITLE
Community admin members list - Not possible to search by partial chat key or nickname

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#16956]
# Bug Report

## Description

It is not possible to search by a partial chat key or nickname in the community admin members list.

Searching by full key, full display name or partial display name works as expected.

Related to https://github.com/status-im/status-desktop/pull/16824

![Image](https://github.com/user-attachments/assets/fe309851-6c03-49a7-9329-6936b3d9c68e)

## Expected

It should be possible to search by:

- Full chat key
- Partial chat key
- Full display name
- Partial display name
- Nickname

### Additional Information

- Status desktop version: 2.32 RC4
- Operating System: Mac

**Comment by caybro** [comment]
We decided to search only by the full key, partial key would give too many false positives

**Comment by caybro** [comment]
I also remember adding this, the search by nickname definitely worked when I implemented it 😑

**Comment by jrainville** [comment]
Considering that searching by full key is the only thing we want to support and that Nickname search does work just with a delay (see https://github.com/status-im/status-desktop/issues/16957#issuecomment-2539753316), it seems like there is nothing to fix here.

Closing as won't fix.
