### ISSUE TITLE
Profile icons color is not adjusting for dark mode

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1731]
Please change the color to the: #758EF0 on dark mode

<img width="304" alt="Screen_Shot_2021-01-21_at_20_30_12" src="https://user-images.githubusercontent.com/52249767/105402388-a3695000-5c27-11eb-8261-4094a3fac5f4.png">

**Comment by staked-smart-ace** [comment]
Could I work on this issue?
