### ISSUE TITLE
Wrong "Generate New keys" button

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1749]
### Current
<img width="888" alt="Screen Shot 2021-01-22 at 17 09 10" src="https://user-images.githubusercontent.com/52249767/105515061-8d659900-5cd4-11eb-82ca-81b4c845b7ac.png">

### Fix
<img width="1131" alt="Screen Shot 2021-01-22 at 18 01 27" src="https://user-images.githubusercontent.com/52249767/105521183-da993900-5cdb-11eb-9761-53a3e3063851.png">

**Button behaviour**
<img width="205" alt="Screen Shot 2021-01-22 at 18 01 52" src="https://user-images.githubusercontent.com/52249767/105521254-edac0900-5cdb-11eb-8824-c2fcadf418a3.png">

**Font weight: 400!**
Figma here:
https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=590%3A298

**Comment by staked-smart-ace** [comment]
Can I fix this issue?

**Comment by PascalPrecht** [comment]
Hey @staked-smart-ace Feel free to work on this!

**Comment by staked-smart-ace** [comment]
> Hey @staked-smart-ace Feel free to work on this!

Ok, please assign this me
