### ISSUE TITLE
Highlight color is still wrong on chat input and status update input

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1750]
### Problem
<img width="164" alt="Screen Shot 2021-01-22 at 17 16 25" src="https://user-images.githubusercontent.com/52249767/105516890-ad965780-5cd6-11eb-84c1-1af0b0f2ac03.png">
<img width="433" alt="Screen Shot 2021-01-22 at 17 23 01" src="https://user-images.githubusercontent.com/52249767/105516891-aec78480-5cd6-11eb-8803-146f4bb0eee0.png">

### Fix
Right color: #4360DF 20% Opacity
<img width="531" alt="Screen Shot 2021-01-22 at 17 21 07" src="https://user-images.githubusercontent.com/52249767/105517031-d1599d80-5cd6-11eb-83c7-484522b529a4.png">

**Comment by staked-smart-ace** [comment]
I am not sure why it was not fixed yet.
It should been merged in https://github.com/status-im/status-desktop/pull/1659/files
![image](https://user-images.githubusercontent.com/29419562/105534064-61fba200-5d06-11eb-8b0e-09e704126cc9.png)
According to the current latest source file, it isn't merged from my fixes.

**Comment by jrainville** [comment]
I went through the commits and your PR was indeed merged correctly @staked-smart-ace, but somehow, you deleted your own change by accident: https://github.com/staked-smart-ace/nim-status-client/commit/086c868bdc5733c989eb9cb9e1c0424902055731#diff-dd9525f1c05aa0109a03e997c49075136bfc5aa33396e8a762a03bda15ed030e

**Comment by staked-smart-ace** [comment]
yeah, you right, it was my mistake.
So, right now how to figure it out?
If you assign this issue to me, let me make new PPR
