### ISSUE TITLE
Fix looooot of buttons  🎉

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1751]
### Primary button - All over the app (hover state broken)
**Current**

<img width="600" alt="Screen_Shot_2021-01-22_at_18_05_38" src="https://user-images.githubusercontent.com/52249767/105521691-83e02f00-5cdc-11eb-833b-c4a30ff57ec7.png">
<img width="560" alt="Screen_Shot_2021-01-22_at_18_06_31" src="https://user-images.githubusercontent.com/52249767/105521758-9ce8e000-5cdc-11eb-9a5b-cddad6fc9742.png">

+ ALL OVER THE APP, MOSTLY IN SETTINGS + WALLET?

**Fix**
Behaviour
<img width="260" alt="Screen Shot 2021-01-22 at 18 08 13" src="https://user-images.githubusercontent.com/52249767/105521877-cc97e800-5cdc-11eb-9dfc-a4a3c461d788.png">

 **Hover State Color: FF2D55 20% Opacity**
 

#### Current
<img width="248" alt="Screen Shot 2021-01-22 at 17 16 12" src="https://user-images.githubusercontent.com/52249767/105517643-97d56200-5cd7-11eb-86a7-d52c7cc41b86.png">

#### Fix
**Active State**

<img width="204" alt="Screen Shot 2021-01-22 at 17 30 15" src="https://user-images.githubusercontent.com/52249767/105517683-a3c12400-5cd7-11eb-97b8-5cf331db88e3.png">

**Hover State**

<img width="212" alt="Screen Shot 2021-01-22 at 17 30 17" src="https://user-images.githubusercontent.com/52249767/105517694-a7ed4180-5cd7-11eb-841f-8ae16e7260d2.png">

Font weight: 400

Figma here:
https://www.figma.com/file/n0NB83EpT076bc1xQBKdYg/%F0%9F%97%A3-Status-Updates%E2%8E%9CDesktop?node-id=1927%3A0

#### Current
https://user-images.githubusercontent.com/52249767/105518300-690bbb80-5cd8-11eb-9f3f-9c42d89a7870.mov
<img width="423" alt="Screen_Shot_2021-01-22_at_17_38_10" src="https://user-images.githubusercontent.com/52249767/105518543-b5ef9200-5cd8-11eb-9724-8b72e733a23b.png">

#### Fix
**Active State**

<img width="637" alt="Screen Shot 2021-01-22 at 17 37 17" src="https://user-images.githubusercontent.com/52249767/105518349-7a54c800-5cd8-11eb-88e4-547122a03071.png">

**Hover State**

<img width="991" alt="Screen Shot 2021-01-22 at 17 37 51" src="https://user-images.githubusercontent.com/52249767/105518408-8e98c500-5cd8-11eb-98d2-616088049fbd.png">

Font weight: 400

Figma here:
https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1559%3A72

#### Current

<img width="444" alt="Screen Shot 2021-01-22 at 17 55 14" src="https://user-images.githubusercontent.com/52249767/105520426-fe0fb400-5cda-11eb-81cf-662ab731f129.png">

 #### Fix
 **Hover State Color: FF2D55 20% Opacity**

<img width="388" alt="Screen Shot 2021-01-22 at 17 49 18" src="https://user-images.githubusercontent.com/52249767/105519810-277c1000-5cda-11eb-97d3-2489246898a9.png">

Figma here:
https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=590%3A298

#### Current
<img width="670" alt="Screen_Shot_2021-01-22_at_17_50_20" src="https://user-images.githubusercontent.com/52249767/105520000-67db8e00-5cda-11eb-9b5c-55450500fd0b.png">
<img width="608" alt="Screen_Shot_2021-01-22_at_17_42_39" src="https://user-images.githubusercontent.com/52249767/105520029-72962300-5cda-11eb-92bc-95df8a44d774.png">

####Fix

**Hover color: 4360DF 20% Opacity**

<img width="386" alt="Screen Shot 2021-01-22 at 17 52 38" src="https://user-images.githubusercontent.com/52249767/105520165-9eb1a400-5cda-11eb-95b0-68e5b2d29d1d.png">

Figma here:
https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=590%3A298

**Comment by simonricoo** [comment]
Hey @PascalPrecht found one more here, I reaslised I havent designed a hover state for this one so here is the behaviour, I added it to all buttons and called it Outlined Primary... Probably it would be secondary and the one we call secondary now would be tertiary but I didnt wanted to confuse you with that now... 

<img width="519" alt="Screen_Shot_2021-01-27_at_16_38_00" src="https://user-images.githubusercontent.com/52249767/106130422-9ab1d600-6161-11eb-82e0-8c26a11b8ddc.png">


https://user-images.githubusercontent.com/52249767/106130437-9eddf380-6161-11eb-8fea-eacd3f12e602.mov


<img width="324" alt="Screen Shot 2021-01-28 at 12 09 18" src="https://user-images.githubusercontent.com/52249767/106130457-a7cec500-6161-11eb-9501-abddbd21ae04.png">

https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=590%3A298

**Comment by PascalPrecht** [comment]
Thanks!
A lot of these things are handled by #1772 #1773 #1774 #1775 #1776 

However, as mentioned in one of the commits, we'll have to revisit the `StatusButton` to properly encode the "outlined" variant in its API. For, I've added changed based on heuristics.

**Comment by PascalPrecht** [comment]
Should be all addressed with the mentioned PRs
