### ISSUE TITLE
app doesn't use system-wide network proxy on macOS

### ISSUE THREAD

**Issue by arthurk** [status-im/status-desktop#1754]
I have a system-wide HTTP/HTTPS proxy configured in macOS. When I started the app I noticed that the client makes direct connections rather than using the proxy. It would be great if the status desktop client would proxy the requests like all other apps.

I'm using beta.5 on macOS 10.15.7
StatusDesktop/v0.68.3/darwin-amd64/go1.13.4

**Comment by corpetty** [comment]
can you be specific on which requests ignore the proxy?

**Comment by iurimatias** [comment]
closing as we'lre unlikely to 'fix' this, it sounds like a feature if anything.
