### ISSUE TITLE
Overwrite Random 3 words name with ENS  in contacts (if applies)

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1760]
Even if user has ENS I see Random 3 words name in contacts.

<img width="1221" alt="Screen_Shot_2021-01-26_at_13_39_04" src="https://user-images.githubusercontent.com/52249767/105846127-023e1900-5fdc-11eb-96b6-2802bdc5e8f6.png">

**Comment by richard-ramos** [comment]
Please verify in latest master:

![image](https://user-images.githubusercontent.com/1106587/107267643-92894e80-6a1d-11eb-8b9e-45a000079c04.png)

**Comment by jrainville** [comment]
I think this issue could be because of the back-end contact updates. Sometimes you don't receive the ENS contact update straight away. It's not really something that can be fixed on our end

**Comment by iurimatias** [comment]
fixed since then
![Screen Shot 2021-03-10 at 9.54.38 AM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/483fba1b-66bb-4822-a1e9-93502a2a6bb5)
