### ISSUE TITLE
Fix Wrong password Error State on Log in

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1762]
### Current

<img width="1221" alt="Screen_Shot_2021-01-26_at_14_05_50" src="https://user-images.githubusercontent.com/52249767/105848940-fb190a00-5fdf-11eb-8dd3-1a688981baad.png">

### Design
<img width="1044" alt="Screen Shot 2021-01-26 at 14 27 01" src="https://user-images.githubusercontent.com/52249767/105850840-8f846c00-5fe2-11eb-8098-5875303aa310.png">

Figma: https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=1381%3A0

**Comment by staked-smart-ace** [comment]
May I work on this issue?

**Comment by iurimatias** [comment]
yes
