### ISSUE TITLE
Mentions are not displaying ENS + other issues

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1795]
The user has an ENS but in mentions I see his Random name, this should be also applied when I give a nickname to someone. 

<img width="1225" alt="Screenshot_2021-02-03_at_14_04_39" src="https://user-images.githubusercontent.com/52249767/106751810-02689500-662a-11eb-847d-bad1db40f8c5.png">

After I select a @person from the dropdown the @mention should be highlighted.

**Current**
<img width="417" alt="Screenshot 2021-02-03 at 14 14 46" src="https://user-images.githubusercontent.com/52249767/106751948-304dd980-662a-11eb-8c5a-f6af8fc77bf9.png">

**Design**
<img width="695" alt="Screenshot 2021-02-03 at 14 15 14" src="https://user-images.githubusercontent.com/52249767/106752030-4491d680-662a-11eb-9bd4-4139bdd9273f.png">

Extras:
Dismiss the highlight when the mention is not complete eg. @vitali (originally @vitalik)

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4024%3A0

**Comment by richard-ramos** [comment]
Fixed with #1797
