### ISSUE TITLE
1. Nickname is not updating in the users detail after I change it

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1810]
To reproduce = Add a nickname to any user

Other issue visible on the recording: Nickname is not visible in the field when there is a nickname to reproduce: Add a nickname to any user, close user detail modal, open it again.

https://user-images.githubusercontent.com/52249767/107366459-7ac5cf00-6ade-11eb-8260-f47ab61d3777.mov

**Comment by ace-smart** [comment]
Could I fix this issue?

**Comment by ace-smart** [comment]
Currently, `Name` and `ENS` of this modal is wrong, it is `Nickname`.
Regarding to `ProfileSettings->ContactList->ProfileModal`, it should be shown `ensName`. So it doesn't update name and ens once updated `nickname`
Finally, the correct solution is to show the right `ensname`

**Comment by ace-smart** [comment]
![image](https://user-images.githubusercontent.com/76216456/107654917-865ef480-6c9c-11eb-8616-04ce4163f191.png)

**Comment by jrainville** [comment]
Yes correct

**Comment by ace-smart** [comment]
> Yes correct

Could you merge https://github.com/status-im/status-desktop/pull/1827 right now?
The fixes for this issue would be conflicted with that commit.

**Comment by jrainville** [comment]
Done
