### ISSUE TITLE
Confirm button when removing from contact is wrong

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1811]
**Problem:** When I remove contact from its detail the Confirm button is wrong. 
<img width="1048" alt="Screen Shot 2021-02-09 at 13 56 39" src="https://user-images.githubusercontent.com/52249767/107366866-ea3bbe80-6ade-11eb-8512-7e072c5a1627.png">

**Solution:** Make the button look the same as when I remove a contact from Profile->Contacts
<img width="1039" alt="Screen Shot 2021-02-09 at 13 58 12" src="https://user-images.githubusercontent.com/52249767/107366936-fe7fbb80-6ade-11eb-84f7-1e54632bbc75.png">

**Comment by ace-smart** [comment]
Could I fix this issue?
