### ISSUE TITLE
Profile Images are not loading on the latest master

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1812]
Its not loading even when me on the other account "@simon" have the image set to show to everyone.
<img width="639" alt="Screen Shot 2021-02-09 at 14 12 43" src="https://user-images.githubusercontent.com/52249767/107368582-03456f00-6ae1-11eb-9a07-bf087fd63560.png">

**Comment by PascalPrecht** [comment]
@simonricoo can still reproduce this on latest `master`?

**Comment by simonricoo** [comment]
Images are being loaded on latest master. So no :)

**Comment by PascalPrecht** [comment]
Cool! Closing as resolved
