### ISSUE TITLE
Names in 2nd panel are disappearing 😳

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1813]
FYI I experience the similar behaviour in settings in the second panel too.

https://user-images.githubusercontent.com/52249767/107368989-7f3fb700-6ae1-11eb-8b28-3be026c32d54.mov

**Comment by jrainville** [comment]
I tried replicating but I couldn't. Do you remember the steps you took?

**Comment by iurimatias** [comment]
can't replicate
