### ISSUE TITLE
Small tooltip fix (applies to all tooltips)

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1817]
### Issue 1: Make tooltip 4 px from the element.

<img width="357" alt="Screen_Shot_2021-02-09_at_16_24_00" src="https://user-images.githubusercontent.com/52249767/107387025-b4a1d000-6af4-11eb-9531-a15fc2c1c4c6.png">

### Design

<img width="268" alt="Screen Shot 2021-02-09 at 16 35 32" src="https://user-images.githubusercontent.com/52249767/107387178-dd29ca00-6af4-11eb-81df-fc2745463fc7.png">
<img width="474" alt="Screen Shot 2021-02-09 at 16 35 26" src="https://user-images.githubusercontent.com/52249767/107387190-def38d80-6af4-11eb-94d7-d7b4d86b6a36.png">
<img width="508" alt="Screen Shot 2021-02-09 at 16 35 23" src="https://user-images.githubusercontent.com/52249767/107387201-e1ee7e00-6af4-11eb-81f8-5ec984e9196a.png">

### Issue 2 Make the padding from left and right 8px
<img width="462" alt="Screen_Shot_2021-02-09_at_16_23_58" src="https://user-images.githubusercontent.com/52249767/107387439-1cf0b180-6af5-11eb-8a13-d44a8615f7b0.png">

**Comment by simonricoo** [comment]
@jrainville issue created :)

**Comment by ace-smart** [comment]
Could I fix this issue?

**Comment by jrainville** [comment]
@ace-smart yes you can. FYI, fixing the width (horizontal padding) is gonna be hard since tooltips work with a hard set width. Hopefully, you can find a way that works at following the text width with a max-width
