### ISSUE TITLE
Enable ellipsis on long names in chat detail

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1830]
This is an edge case for random name but there are still Nicknames where user can set long names, better to have it covered. 

### Current
<img width="603" alt="Screen_Shot_2021-02-11_at_14_58_06" src="https://user-images.githubusercontent.com/52249767/107646471-4850d900-6c7a-11eb-8e70-a83229403f81.png">

<img width="525" alt="Screen_Shot_2021-02-11_at_15_04_12" src="https://user-images.githubusercontent.com/52249767/107646628-76361d80-6c7a-11eb-8372-a15a692b6d8e.png">

**Comment by ace-smart** [comment]
Could I fix this issue?

**Comment by jrainville** [comment]
@ace-smart yes, thanks. If you could, look around the app for other cases where that could be a problem, like the profile, the mentions, the group chats and  info popups. To test, you can check in `#test`, The is a message there by "Forceful Stateblue Queenalexandria.." that you can test with to send messages and invite to groups (it's one of my random test accounts so I don't care)
