### ISSUE TITLE
Communities: implement new design for communities in the left tab

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#1835]
See design here: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4251%3A42913

**Comment by jrainville** [comment]
@simonricoo is the current design I linked above complete and/or ready to begin work on for next week?

**Comment by simonricoo** [comment]
Its done Jo, just make sure the "-" separator only appears when you have joined at least one community. Only communities and chat appear above that separator everything else would go to the bottom section.

**Comment by jrainville** [comment]
Perfect, thanks
