### ISSUE TITLE
Messages with mentions are ugly in dark mode

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#1838]
![image.png](https://images.zenhubusercontent.com/5ea70e106499d53d00627c49/b3cb907a-b23a-483a-b81c-15e9ca05fce1)

@simonricoo is there a design for the colour of mentions in dark mode?

**Comment by simonricoo** [comment]
on my todo list, I might start working on the new dark theme on Monday so probably no reason to make it for the current one.

**Comment by jrainville** [comment]
Good point. Thanks for the update 👍
