### ISSUE TITLE
Update tab bar icons

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1843]
Somehow the browser icon is smaller and I have updated the Status Updates logo. Best way to make sure everything is consistent and right update all icons with icons that you can find here: https://www.figma.com/file/n0NB83EpT076bc1xQBKdYg/%F0%9F%97%A3-Status-Updates%E2%8E%9CDesktop?node-id=1968%3A13644

<img width="92" alt="Screenshot_2021-02-15_at_10_38_01" src="https://user-images.githubusercontent.com/52249767/107929876-90be0e80-6f7a-11eb-803a-5edc830b34ce.png">

 **Design** (Dont mind the icons order...)
<img width="369" alt="Screenshot_2021-02-15_at_10_37_56" src="https://user-images.githubusercontent.com/52249767/107929849-856ae300-6f7a-11eb-8960-1fa92b794fa3.png">

Also please fix the outline of the dot indicator is adjusting when its color also on hover state on both dark and light mode.
<img width="136" alt="Screenshot 2021-02-15 at 10 44 30" src="https://user-images.githubusercontent.com/52249767/107930086-ce229c00-6f7a-11eb-9851-6ad0c29a41e3.png">

**Comment by ace-smart** [comment]
Can I fix this issue?

**Comment by ace-smart** [comment]
Could you give me the access to me for above figma?

**Comment by simonricoo** [comment]
<img width="217" alt="Screen Shot 2021-02-26 at 09 35 59" src="https://user-images.githubusercontent.com/52249767/109279343-ed8eb400-7819-11eb-9e6e-d62ea0ed665d.png">

Icons are still not correct. Some of them are thicker or bigger. Please double check if you are using these icons in svg and at the same scale: https://www.figma.com/file/n0NB83EpT076bc1xQBKdYg/%F0%9F%97%A3-Status-Updates%E2%8E%9CDesktop?node-id=1968%3A13644

**Comment by ace-smart** [comment]
@simonricoo I dont have access to the figma you attached.
Please give the access (minmax17842@gmail.com)

**Comment by simonricoo** [comment]
@ace-smart I can see you as a view member. Anyway sent an email invite again. Make sure you are logged in to figma with this email.

**Comment by ace-smart** [comment]
I can see right now

**Comment by simonricoo** [comment]
@ace-smart have you made some progress with this issue? Can I help somehow?

**Comment by PascalPrecht** [comment]
@simonricoo this issue was closed as fixed with https://github.com/status-im/status-desktop/commit/bda1582ea0acbb80ff3b1bdc1ebb3bb610f8a39d

**Comment by simonricoo** [comment]
Its strange, I see values 22, and 20. Im not using non of these in figma... @PascalPrecht 

<img width="288" alt="Screen Shot 2021-04-22 at 10 40 07" src="https://user-images.githubusercontent.com/52249767/115683931-37e26c00-a357-11eb-9ab7-cbd0cc5072b9.png">
<img width="511" alt="Screen Shot 2021-04-22 at 10 41 03" src="https://user-images.githubusercontent.com/52249767/115683959-3d3fb680-a357-11eb-97a6-4e43936d24af.png">
<img width="421" alt="Screen Shot 2021-04-22 at 10 40 11" src="https://user-images.githubusercontent.com/52249767/115683968-3f097a00-a357-11eb-8f66-0d18c1f8c868.png">

**Comment by simonricoo** [comment]
But I guess the new nav bar component will be in progress soon, so I dont know how big of an issue is this atm.

**Comment by simonricoo** [comment]
Just to add something, icons live in container 24, its important that you export it with that container as there are precisely centered (not always centerXcenter) within that container. So when you export just a shape and say its 22x22 it will never work :)

**Comment by PascalPrecht** [comment]
The issue was about these, right? (https://github.com/status-im/status-desktop/issues/1843#issue-808371998)

<img width="276" alt="Screenshot 2021-04-22 at 10 43 35" src="https://user-images.githubusercontent.com/445106/115684388-99a2d600-a357-11eb-9cd1-c1c0aca1fa96.png">

**Comment by simonricoo** [comment]
Yes, see my comment above about the container :)

**Comment by simonricoo** [comment]
<img width="608" alt="Screen_Shot_2021-04-22_at_10_45_14" src="https://user-images.githubusercontent.com/52249767/115684704-e2f32580-a357-11eb-8a33-3c7d287fdd2d.png">
you can take nodes icon as example the shape is 21.58x20.5.

But all icons are inside 24x24px container always.
Community images are bigger, as optically 24 circle feels small therefore its 28x28 :)
