### ISSUE TITLE
Setting nickname dismisses users' image in the background.

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1844]
https://user-images.githubusercontent.com/52249767/107931622-d2e84f80-6f7c-11eb-87e6-11a678a9a73f.mov

**Comment by ace-smart** [comment]
This is duplicated with https://github.com/status-im/status-desktop/issues/1761
Need to be updated by backend.

**Comment by jrainville** [comment]
Closing since it is a duplicate
