### ISSUE TITLE
Implement new dark theme

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#1862]
https://www.figma.com/file/k2h3UyN2f5m4rYppxfOzFE/%F0%9F%8C%93-Dark-Mode%E2%8E%9CDesktop?node-id=4660%3A17206

**Comment by PascalPrecht** [comment]
This is most likely a huge effort, given that we'll probably have to switch to component based theming. Shall we create a plan on how to tackle this?

**Comment by jrainville** [comment]
I already did this. It wasn't that bad. There is just a small problem in normal mode that I didn't catch
