### ISSUE TITLE
default empty list image in dark mode has a white background

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1896]
![Screen Shot 2021-02-24 at 3.40.37 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/45e246e0-55ba-49dd-a63b-ff13075fdaa6)

**Comment by ace-smart** [comment]
May I fix this issue?

**Comment by jrainville** [comment]
@ace-smart we're waiting for the new PNG image from design so we can't fix it yet

**Comment by ace-smart** [comment]
> @ace-smart we're waiting for the new PNG image from design so we can't fix it yet

Ok, but it is easy to update to a transparent image

**Comment by jrainville** [comment]
Yes, changing the image is going to be easy, but we need to wait for the designers to give us the new image anyway

**Comment by jrainville** [comment]
Closing this one as the duplicated issue has more details
