### ISSUE TITLE
new dark mode needs some fixes

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1903]
in some places the font color is not really readable anymore
![Screen Shot 2021-02-24 at 4.27.05 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/b4e2b2ae-f68f-4c79-b792-1c406ec48d83)

![Screen Shot 2021-02-24 at 4 31 46 PM](https://user-images.githubusercontent.com/176720/109068642-23b72100-76be-11eb-8553-7f01ccf3833c.png)

**Comment by ace-smart** [comment]
Could I fix this issue?

**Comment by simonricoo** [comment]
The design is here @ace-smart https://www.figma.com/file/k2h3UyN2f5m4rYppxfOzFE/%F0%9F%8C%93-Dark-Mode%E2%8E%9CDesktop?node-id=4660%3A17206
