### ISSUE TITLE
Pinned Messages

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1905]
https://github.com/status-im/status/issues/11

User Story
As a user, I want to pin or star messages in public channels for users of those channels to access them easily and quickly.

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4119%3A2

**Comment by iurimatias** [comment]
the status-go part of this is now ready

**Comment by anastasiyaig** [comment]
per Simon:

- Pinned messages should **not** be available in Public Chat
- Only admin can Pin in group chats
- anyone can pin in Private chat (1on1)
- in community channels only admin can pin

**Comment by guylouis** [comment]
behaviour of pinned messages clarified here 

https://github.com/status-im/status/issues/11#issuecomment-773982069
