### ISSUE TITLE
bug: changing setting "display images in chat" to true does not show already displayed link previews

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1906]
Setup: There are link previews displayed in a chat and the user has the "display images in chat" setting disabled.

Reproduction steps:
1. Change setting "display images in chat" to true
2. Go back to the chat that has link previews
3. Expected: link previews should appear
4. Actual: link previews do not appear. Instead, there is space for the preview (ie the height has changed), but the preview does not appear.

**Comment by iurimatias** [comment]
tested, can't replicate anymore
