### ISSUE TITLE
Windows application unresponsive when fetching Status updates

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#1919]
# Problem
Application becomes unresponsive when selecting 'Fetch messages' on Status updates

#### Current
Recording: https://drive.google.com/file/d/10kxfsQHDxc13Hv7xrJgCVBeIE7qUnALZ/view?usp=sharing
Fetch messages button does not have a press down state, so it's unclear if the application is responsive
After seconds, the hand cursor changes to the Windows native spinning cursor and the application is shown as `Not responding`
Waiting longer, the fetch messages jump into view

#### Expected
- [ ] Fetch more messages button has a button down state 
- [ ] Fetch more messages has a loading state, which is shown when messages are being fetched

@simonricoo are you ok with the expected behavior? 👆

### Note
See also #1920 and #1921

**Comment by iurimatias** [comment]
@hesterbruikman does this still happen in the latest beta? I can't replicate locally

**Comment by hesterbruikman** [comment]
I checked on yesterday's Master. It definitely occurs less often and shorter:
- on Login
- on Switching to Timeline/Status updates
I no longer see the issue with Fetch messages; In chats or in Status updates. That said it seems like Fetch messages is no longer visible in Status updates altogether and it seems like the issue moved to tab switching. Are all messages of the last 30 days fetched on tab selection?

Perhaps related, the timestamps for Status updates seem to be off. All updates older than 7 days are currently showing with the timestamp April 6th (today).

**Comment by jrainville** [comment]
> Perhaps related, the timestamps for Status updates seem to be off. All updates older than 7 days are currently showing with the timestamp April 6th (today).

It's not related, it's a bug that was introduced when we changed the way the list is ordered. I'll add an issue for that.
