### ISSUE TITLE
Show last Status update at top of screen

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#1921]
# Problem
Standard for feeds is to have latest updates at the top. Design follows this standard and the current implementation on Mobile. On Desktop the last messages currently appear at the bottom. (Probably to due with endless scroll/ergonomics of scroll, not sure would need to investigate)

### Current
Latest status updates appear at the bottom

### Expected
Latest status appear at the top

### Note
See also #1919 and #1920

**Comment by jrainville** [comment]
Fixed
