### ISSUE TITLE
App crashes silently on macOS after getting back from sleep mode

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#1923]
Run status app, close the macbook, open it back after 24h, there is no status app opened anymore

**Comment by iurimatias** [comment]
closing in favour of issue #2012 ,it's quite likely the same issue related to concurrency

**Comment by flexsurfer** [comment]
still an issue on latest master

**Comment by michaelsbradleyjr** [comment]
> still an issue on latest master

Yes, and we understand better now what is happening, at least we think we do: https://github.com/status-im/status-desktop/blob/master/src/status/mailservers.nim#L244-L260.

That code is unsafe (the compiler is forced to accept it via the `{.gcsafe.}` pragma on L245. While locks are used in an attempt to make it safe, that unfortunately doesn't help. In Nim you can't safely read/write data subject to GC that's on another thread's heap. If you do, then you introduce errors/instability in the GC ref counts and the program will eventually crash with an unrecoverable error. We're running that code every 10 seconds after login, so it's just a roll of the dice as to when it will crash. Sometimes it crashes just after login, sometimes it's hours later.

@emizzle and I are working to re-architect this piece. We've already eliminated all the other GC unsafe code in status-desktop, but this one is a bit more involved. We'll figure it out, stay tuned!

**Comment by iurimatias** [comment]
closed in favour of #2143 that should fix this
