### ISSUE TITLE
Screen turns off when the application is starting on macos

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#1924]
At the moment when the application is starting, the screen turns off for a few seconds on the macbook

**Comment by iurimatias** [comment]
did that happen once? or happens consistently? what is the model and OS version?

**Comment by iurimatias** [comment]
This is likely a QT issue, will revisit once we can update

**Comment by iurimatias** [comment]
closing as it's likely been fixed in the qt update
