### ISSUE TITLE
dismiss the bold formation when pressing CMD+B

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1930]
I want to hit CMD+B (or any other shortcut) to dismiss the bold formation.

Watch video + audio recording...

https://user-images.githubusercontent.com/52249767/109282871-65f77400-781e-11eb-9227-d032082d944a.mov

**Comment by PascalPrecht** [comment]
@simonricoo This works in the linked PR. Just with one caveat (as mentioned there):

Shortcuts only work when the text you want to format was selected with the keyboard. When it's selected with the mouse the context menu opens with the formatting buttons, at which point the shortcuts don't seem to activate. However toggling the selection works the same then
