### ISSUE TITLE
use SVG code icon

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1934]
Please use SVG for this icon, its blurred

<img width="218" alt="Screen_Shot_2021-02-26_at_10_44_05" src="https://user-images.githubusercontent.com/52249767/109283955-a1df0900-781f-11eb-8e16-c5850992632f.png">

**Comment by iurimatias** [comment]
![Screen Shot 2021-03-08 at 4.28.13 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/f5975517-d4ef-43c7-b8b5-7e74ab538539)
