### ISSUE TITLE
Chat input field & emoji issue

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1944]
### Chat inpput field's hight increase when I insert an emoji.
Input field should have a fixed hight

https://user-images.githubusercontent.com/52249767/109635413-9dca2880-7b4a-11eb-864f-2da663b033f4.mov

### Align emojis with text
<img width="225" alt="Screenshot_2021-03-02_at_11_27_37" src="https://user-images.githubusercontent.com/52249767/109635553-cfdb8a80-7b4a-11eb-9e4e-67a6ca8f3279.png">

**Comment by iurimatias** [comment]
we should attempt to align vertically the emoji with the text
