### ISSUE TITLE
missing line on the sidebar

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1948]
![Screen Shot 2021-03-02 at 9.26.25 AM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/a6f538e8-cc83-46fb-b011-1bcdd33008fb)

**Comment by jrainville** [comment]
I can't reproduce even with the same appearance settings and the 99+ badge. Is there anything else you did?

**Comment by iurimatias** [comment]
Uploading Screen Recording 2021-03-03 at 4.45.35 PM.mov…
