### ISSUE TITLE
Random crash related to reactions

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#1951]
My app was idle and all of a sudden crashed.

Here is the stack trace:
![image](https://user-images.githubusercontent.com/11926403/109669874-8dad4b80-7b40-11eb-8436-ab909589d162.png)

It seems like a reaction might have come in for a channel I no longer had?

**Comment by iurimatias** [comment]
so this is likely the issue we had & fixed in regards to leaving a channel and the associated index for the select channel was the incorrect one
