### ISSUE TITLE
Order of messages is wrong

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1956]
From the perspective of sender, this is not an expected behaviour.
Watch this video ➡️➡️➡️ https://user-images.githubusercontent.com/52249767/109802083-a3457280-7c1f-11eb-89b8-6de8f1d06559.mov
 ### How is should appear:
<img width="1007" alt="Screen Shot 2021-03-03 at 12 53 31" src="https://user-images.githubusercontent.com/52249767/109802124-b7896f80-7c1f-11eb-91ae-8d10dedc1312.png">

**Comment by jrainville** [comment]
This was already fixed in master
