### ISSUE TITLE
Community detail

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1958]
<img width="593" alt="Screen_Shot_2021-03-03_at_13_02_48" src="https://user-images.githubusercontent.com/52249767/109803496-68dcd500-7c21-11eb-9268-b6826444c75a.png">

### Design

<img width="446" alt="Screen Shot 2021-03-03 at 13 06 48" src="https://user-images.githubusercontent.com/52249767/109803516-6da18900-7c21-11eb-9604-f4362bfc5963.png">

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4724%3A0

**Comment by iurimatias** [comment]
closing as all of this is now in master
