### ISSUE TITLE
Community top bar

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1961]
<img width="392" alt="Screen_Shot_2021-03-03_at_14_05_16" src="https://user-images.githubusercontent.com/52249767/109810264-9c236200-7c29-11eb-855a-62fc149f38a2.png">

### Design

<img width="583" alt="Screen Shot 2021-03-03 at 14 05 49" src="https://user-images.githubusercontent.com/52249767/109810288-a7768d80-7c29-11eb-8abd-633712d3408f.png">

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=3705%3A62829

**Comment by jrainville** [comment]
I think you are testing the old version. Are you testing on master? If so, the latest community changes have not been merged yet

**Comment by ace-smart** [comment]
Could I fix this issue?
