### ISSUE TITLE
Replace images

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1965]
To prevent this on dark mode:
<img width="1210" alt="Screenshot 2021-03-03 at 14 54 24" src="https://user-images.githubusercontent.com/52249767/109815932-79487c00-7c30-11eb-9e10-8e48f114622d.png">
<img width="1206" alt="Screenshot 2021-03-03 at 14 54 30" src="https://user-images.githubusercontent.com/52249767/109815945-7c436c80-7c30-11eb-89aa-1c2e94846f27.png">

### New images
![browser](https://user-images.githubusercontent.com/52249767/109815981-849ba780-7c30-11eb-915a-6f4065affa29.png)
![chat](https://user-images.githubusercontent.com/52249767/109815997-882f2e80-7c30-11eb-822f-02118fb5118f.png)

**Comment by ace-smart** [comment]
Duplicated with #1896
Please assign any one to me
