### ISSUE TITLE
Trying to rejoin a community after leaving it crashes

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#1983]
Steps:
1. Join a community
2. Leave it
3. Join again
-> crash?

If it doesn't crash, great!

This other repro step might crash too:
1. Create a community
2. Leave it
3. Join again
-> crash

**Comment by PascalPrecht** [comment]
I wasn't able to reproduce the crashes, but I did find bugs related to these two user stories. Sent fixes for them in #1989 and #1986
