### ISSUE TITLE
On request communities don't let joined members write in the channels

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#1985]
Steps:
1. create a community with the permission: "Request approval"
2. create a channel
3. invite one of your other accounts to that community
-> that other account can see the channel but can't write to it

**Comment by PascalPrecht** [comment]
I tested this and it turns out we already guard around that. Only when you're either admin, or the community has public access, the chat input is rendered.

Found another bug though that channels can't be created anymore #1998

**Comment by PascalPrecht** [comment]
I was wondering though, if someone is invited to a community that needs "Request Approval", that invite is an approval already no? So as an invitee, I should get write access to the channel, or is every individual channel protected?

I tried reading from the code when/how someone can actually request to join (which is `community.access = communityChatOnRequestAccess`) and that only seems to be possible from the communities detail popup, which I can't access when I'm already in the community.

So I guess that leaves me with two questions here:

1. Are we sure that the invitee is now allowed to write in the channels, given that he has just been invited and accepted the invite?
2. If "yes" to 1), then what do I need to do as someone who has just been invited to actually write in channels?

**Comment by jrainville** [comment]
I think being invited to an on-request community should count as being approved, since it's the admin that invites.
It's possible however that something is not correct in status-go, where if the user accepts the invite, it still doesn't count as an approval and you are still not considered a `member`. 

Do you have the community data that we get from status-go? We could check what it returns and see if something that was supposed to be switched to `true` wasn't. If that's the case, we'll report it to Andrea

**Comment by PascalPrecht** [comment]
I just realized I completely misunderstood the issue :D
This is a bug report, not a feature request haha
