### ISSUE TITLE
Profile: ENS unsernames fixes

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1993]
<img width="1233" alt="Screen_Shot_2021-03-05_at_10_55_11" src="https://user-images.githubusercontent.com/52249767/110099965-30b0d000-7da2-11eb-8cea-6c65c0795ff0.png">

Dark image: https://www.figma.com/file/k2h3UyN2f5m4rYppxfOzFE/%F0%9F%8C%93-Dark-Mode%E2%8E%9CDesktop?node-id=4753%3A88

<img width="1244" alt="Screen_Shot_2021-03-05_at_11_03_19" src="https://user-images.githubusercontent.com/52249767/110100380-a0bf5600-7da2-11eb-8847-a0521daa06be.png">
ui

**Comment by rinzlxr** [comment]
hey Simon. i cant log into figma to get the image. any chance you can post it here?

**Comment by jrainville** [comment]
@rinzlxr There it is

[🌓 Dark Mode⎜Desktop.zip](https://github.com/status-im/status-desktop/files/6191507/Dark.Mode.Desktop.zip)

**Comment by rinzlxr** [comment]
thanks!
