### ISSUE TITLE
Issue with space bar not respected in chat text input

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#2000]
## Current
When moving cursor to first position after last character of a word, the space bar is not respected. The cursor jumps backwhen space bar is used
Recording: https://www.loom.com/share/bd54202b712741ebb74a9c72ae65b985
![Screenshot 2021-03-05 121403](https://user-images.githubusercontent.com/35233054/110108344-5a6ef480-7dac-11eb-94fa-20655993f391.png)

## Expected
When moving cursor to first position after last character of a word, the space bar is respected

**Comment by iurimatias** [comment]
related behaviour is this:

type a sentence, then press space , say, 5 times
result: it forces 1 space

**Comment by iurimatias** [comment]
related

```
Steps:
1. write text on the first line of a chat message
2. hit SHIFT+space (to go to the second line)
3. Enter a mention and hit Enter to apply it
-> goes back to the first line. Line breaks are gone
```
