### ISSUE TITLE
There is no way how to change Wallet Account Color back to original Blue.

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2003]
There is no way how to change it back to original blue... 
<img width="493" alt="Screen Shot 2021-03-05 at 12 43 59" src="https://user-images.githubusercontent.com/52249767/110112222-bee08280-7db1-11eb-9b20-f498f8c3e91e.png">

### Fix
Add defualt blue account color to the list as a first default item that is checed by default when you are creating a new account
<img width="523" alt="Screen Shot 2021-03-05 at 13 15 24" src="https://user-images.githubusercontent.com/52249767/110114419-ebe26480-7db4-11eb-92b4-b815dd5d9cdd.png">

https://www.figma.com/file/k2h3UyN2f5m4rYppxfOzFE/%F0%9F%8C%93-Dark-Mode%E2%8E%9CDesktop?node-id=4700%3A692

**Comment by PascalPrecht** [comment]
This seems to have been fixed with https://github.com/status-im/status-desktop/commit/b9594591b#diff-6c31eea2d43fcc933c79d6c466e894bebac1c1107e6e57ba9e9b77c4d92104deR87
