### ISSUE TITLE
browser: some links are not supported by "Add favorite" modal

### ISSUE THREAD

**Issue by dzuqe** [status-im/status-desktop#2008]
![2021-03-06-042113_483x477_scrot](https://user-images.githubusercontent.com/58890963/110191936-f132c400-7e33-11eb-8e6e-d4de3cbaa8d3.png)

other links:
- https://torn.community/
- https://ceramic.network
- https://idle.finance/
- https://www.rari.capital/

**Comment by Khushboo-dev-cpp** [comment]
Tested the issue with latest pull and it is not reproduced
