### ISSUE TITLE
browser: favorite list gets truncated when too long

### ISSUE THREAD

**Issue by dzuqe** [status-im/status-desktop#2009]
https://user-images.githubusercontent.com/58890963/110192522-399fb100-7e37-11eb-8edd-4b743d54b7fb.mp4

possible fix:
arrange the favorites in a grid-like fashion

**Comment by Khushboo-dev-cpp** [comment]
@simonricoo  @carlfairclough  Whats the solution for this? Is the grid view implementation confirmed from design side?

**Comment by simonricoo** [comment]
Hey, just updated the design for grid views. I adjusted the padding between multiple elements compare to the old current implementation. https://www.figma.com/file/Lhg5cbN1HZiNMrVNddMzrQ/%F0%9F%A7%AD-Browser%E2%8E%9CDesktop?node-id=2671%3A3878

Please keep max 7 items in the row, if the screen gets smaller it wraps into more rows.
<img width="1626" alt="Screen Shot 2021-08-16 at 13 45 39" src="https://user-images.githubusercontent.com/52249767/129558904-69ba628a-5e73-4eda-8b99-5f3e2e130587.png">

**Comment by simonricoo** [comment]
Can we please update the image when the favicon is not fetched. Ideally we take the first letter and create this avatar from it.
<img width="766" alt="Screen_Shot_2021-08-16_at_13_49_31" src="https://user-images.githubusercontent.com/52249767/129559323-c3c857bf-455a-4e38-a4d2-6a1fefa0ab56.png">
