### ISSUE TITLE
crash on macos when receive lots of messages

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#2012]
Join some popular public chats, close the app, open after one week, sign in, wait for messages from mailserver and crash, reopen doesn't crash

**Comment by iurimatias** [comment]
this is likely cause due to some concurrency issues we're looking into, I'll revisit this ticket and close it once we're fairly confident it's fixed

**Comment by iurimatias** [comment]
latest master has a lot of thread related fixes that should fix/help with this

**Comment by flexsurfer** [comment]
still an issue

**Comment by iurimatias** [comment]
I believe this was the issue as the one in #705 which should have been fixed, tentatively closing this issue for now.
