### ISSUE TITLE
Status Updates: Adjust the input field

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2018]
<img width="728" alt="Screenshot_2021-03-09_at_10_46_49" src="https://user-images.githubusercontent.com/52249767/110451903-f3f81800-80c4-11eb-8efa-b407a9183aa9.png">

### Expected view
<img width="688" alt="Screenshot 2021-03-09 at 10 46 54" src="https://user-images.githubusercontent.com/52249767/110451971-03776100-80c5-11eb-9a25-3ccabd610ae3.png">

**Comment by PascalPrecht** [comment]
This is something I've wrestled with for hours.
Fun fact: once you click on the input, the text is properly aligned.

I couldn't get it to be aligned from the start :(

**Comment by PascalPrecht** [comment]
Gave it another shot. Think I've fixed it. Wrestling is fun. #2107
