### ISSUE TITLE
Update token icons to match mobile

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2019]
All supported token icons here: https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=56%3A26
<img width="516" alt="Screenshot 2021-03-09 at 11 38 18" src="https://user-images.githubusercontent.com/52249767/110458341-f27e1e00-80cb-11eb-834b-8fe5b55e82e8.png">

**Comment by PascalPrecht** [comment]
@simonricoo is there by any chance a way you could just provide us with a package/folder/zip that has these token icons in their `@x2`, `@x3` forms etc (ideally as `.png`)?

Make updating them easier as we'd just have to drop them here: https://github.com/status-im/status-desktop/tree/master/ui/app/img/tokens

**Comment by PascalPrecht** [comment]
Friendly ping! @simonricoo :)

**Comment by jrainville** [comment]
He was on vacation last week and this week ;)

**Comment by simonricoo** [comment]
[Assets.zip](https://github.com/status-im/status-desktop/files/6294868/Assets.zip)
@PascalPrecht @jrainville Sorry for delay guys :) Should be all here.

This is how unknown or custom tokens should appear:
<img width="680" alt="Screen Shot 2021-04-12 at 09 59 15" src="https://user-images.githubusercontent.com/52249767/114360816-bda33200-9b75-11eb-9563-bdba6494a2fb.png">
