### ISSUE TITLE
Set "Compact Mode" as a default chat mode

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2021]
Requirements:
1. Set compact mode as default
2. Delete Chat Mode option from Settings -> Appearance

**Comment by hesterbruikman** [comment]
From my recollection we only discussed using compact mode as default. @simonricoo Can you elaborate on what you mean with the 2nd point?

**Comment by simonricoo** [comment]
2: Point: Dismiss normal mode option as we are no longer testing it and there are issues with it.

**Comment by johnlea-quiup** [comment]
I'm +1 on removing it for now, because then there is one less feature to test, fix bugs, get to release quality, etc...  Most users never change default settings.  Perhaps remove and place on the backburner, and we could re-include it in the future??

**Comment by hesterbruikman** [comment]
Thanks @simonricoo makes sense to reduce the number of features that need QA review. @iurimatias is there the option of hiding the feature?

**Comment by iurimatias** [comment]
Se we can hide, but inevitably if enough time passes it will start breaking as we add & test new features only on compact mode.
removing it does simplify the code a lot but then re-adding then will be a lot of work

so the options are:

* keep it as it is, with compact mode as default
* hide the chat mode option, with compact mode as default BUT => **with the intention in the short term to bring it back** <=
* remove chat mode completely & forever, hold a funeral (or a party)


---

@simonricoo compact mode is/was already the default.

**Comment by simonricoo** [comment]
I would say 2 (hide the chat mode option, with compact mode as default BUT => with the intention in the short term to bring it back), assuming the QA person will be on board soon (hopefully) this can be his first task, after he test it and its gonna be fixed and improved we can bring it back. @iurimatias
