### ISSUE TITLE
Community import doesn't work

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#2024]
The import feature of communities only does half the work. 

It currently works fine in mobile, so we can check if we're not missing a call to get the community data.

Discussion about it with Guy-Louis: https://discord.com/channels/624205794384281629/743483790898233374/818851421087858709

**Comment by jrainville** [comment]
Wait for the status-go function to get community description
(https://discord.com/channels/624205794384281629/743483790898233374/818857356480741416)

**Comment by guylouis** [comment]
It seems it worked for me with rc8 
I went to 'access existing communities', pasted the private key. 
I did not get any confirmation message though, and the community did not show up immediately, but when I came back to my communities it showed up.
