### ISSUE TITLE
Communities: Profile Pic is not uploaded from the Edit section after I hit Edit + Text Fix on button

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2027]
<img width="874" alt="Screen Shot 2021-03-10 at 11 21 32" src="https://user-images.githubusercontent.com/52249767/110614724-ea3ce600-8192-11eb-8601-79d2c853f500.png">
 
<img width="874" alt="Screen_Shot_2021-03-10_at_11_21_32" src="https://user-images.githubusercontent.com/52249767/110614895-1c4e4800-8193-11eb-9e2a-8e1937598e75.png">

**Comment by jrainville** [comment]
The Edit functionality isn't available right now. The form was added to save time for when the feature was added in status-go.

For now, I can hide the Edit button to remove the confusion

**Comment by jrainville** [comment]
I hid the Edit button here: https://github.com/status-im/status-desktop/pull/2080

I'll move this task to the backlog for now

**Comment by iurimatias** [comment]
on hold, this feature is not available on the backend yet

**Comment by jrainville** [comment]
This was fixed by Eric in a previous commit
