### ISSUE TITLE
Follow the same name limitation principles in community channels as on public chats

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2050]
<img width="341" alt="Screen_Shot_2021-03-16_at_14_38_31" src="https://user-images.githubusercontent.com/52249767/111318637-866c5e80-8665-11eb-81fe-8ad94e8edb06.png">

Public chat formation example:
<img width="417" alt="Screen Shot 2021-03-16 at 14 38 36" src="https://user-images.githubusercontent.com/52249767/111318674-8f5d3000-8665-11eb-85a9-3b02c83ce057.png">

**Comment by hesterbruikman** [comment]
For reference, these are the validation rules shown on mobile

![Screenshot_20210318-123731_Status.jpg](https://images.zenhubusercontent.com/5eaacc9bd76e4cffd53fcf08/1e05c9ad-59fc-4068-93ed-00470ca05b06)

@simonricoo @jrainville is there currently validation on creating a channel in communities? I suspect this is necessary to prevent issues when deeplinking to a community chat (if that is an option aside from deeplinking to a community)

cc @guylouis

**Comment by jrainville** [comment]
>  is there currently validation on creating a channel in communities?

Not yet, that's why Simon opened the issue. We do have that validation for normal channels and community names, so it's a simple fix to use the same validation on both

**Comment by anastasiyaig** [comment]
@jrainville  @emizzle  can we please rebase (so mac OS build is fixed) and rebuild? I picked up the one alive mac os image (StatusIm-210406-021639-e27aa1-pr.) and there is no validation for the public chats created in community, but i blame the build (for example, i can create a chat with only spaces, or space in between, and etc)

![Снимок экрана 2021-04-17 в 00.03.22.png](https://images.zenhubusercontent.com/6074560cfd1d342d606f37d3/64a90b3c-56f4-439f-9e11-c891e701e798)

**Comment by anastasiyaig** [comment]
![Снимок экрана 2021-04-19 в 11.56.01.png](https://images.zenhubusercontent.com/6074560cfd1d342d606f37d3/6044cbec-ebba-4c4d-8161-7a4ec5867323)

so basically as we talked with @simonricoo , the current PR is okay to merge, because we will change the flow soon again. Expectation is the following: channel name validation ≠ community name validation (will be addressed soon when clarified) . There is an open discussion for this now: https://discord.com/channels/624205794384281629/743483790898233374/832530510893940756

**Comment by emizzle** [comment]
@anastasiyaig -- should the above comment be on https://github.com/status-im/status-desktop/pull/2168 instead?

**Comment by anastasiyaig** [comment]
@emizzle right sorry :D
