### ISSUE TITLE
UI scalling still too small on 4K

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-desktop#2057]
As part #737 UI scaling settings have been added. The problem is tho that even with XXL setting the fonts are still far too small for a 4K screen:

![image](https://user-images.githubusercontent.com/2212681/111349827-c2adb800-8681-11eb-85ef-0a514b7ac629.png)

Especially the chat names are tiny.

**Comment by johnlea-quiup** [comment]
Prob. worth looking at #2124 at the same time as looking at this issue.

**Comment by iurimatias** [comment]
to be fixed in #2178
