### ISSUE TITLE
segfault after creating new community with image

### ISSUE THREAD

**Issue by rinzlxr** [status-im/status-desktop#2085]
and sometimes the user wont be able to log back in thereafter. 

notes:
there's no segfault if you havent attached an image while creating the community.

```
DBG 2021-03-20 03:25:51+02:00 callPrivateRPC                             topics="rpc" tid=30855 file=core.nim:20 rpc_method=wakuext_createCommunity
qrc:/shared/ImageLoader.qml:74:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
make: *** [Makefile:460: run-linux] Segmentation fault (core dumped)
```

**Comment by jrainville** [comment]
I tried creating 5 different communities with images of varying sizes and types and I couldn't reproduce the issue. 

I see in your error message that it talks about the deprecation of the old Connection syntax. Could it be possible that you use Qt version 5.15? It has caused issues for one of us before where the chat list would crash, but that only happened in 5.15 and not 5.14, which is what all of the team uses.

**Comment by rinzlxr** [comment]
Yea I'm using the incorrect version, mine is 5.15.2 . Just re-read the build reqs and saw that I should be using 5.14.2. I haven't linked this version to the project yet though since the qt5 group is still linked to other software in my system. I think we can reopen this if i still find the issue after having dealt with my versioning
