### ISSUE TITLE
Date not visible in status updates

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2097]
<img width="352" alt="Screen_Shot_2021-03-23_at_11_59_36" src="https://user-images.githubusercontent.com/52249767/112136558-6857ae80-8bcf-11eb-8855-009cc8c3b7bc.png">

https://www.figma.com/file/n0NB83EpT076bc1xQBKdYg/%F0%9F%97%A3-Status-Updates%E2%8E%9CDesktop?node-id=1970%3A10

**Comment by jrainville** [comment]
This was already fixed with the new dark theme changes
