### ISSUE TITLE
Enable zoom in/out the app

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2098]
On windows CTRL + (Zoom in), CTRL - (Zoom out)
On MacOS CMD + (Zoom in), CMD - (Zoom out)

Expected behaviour as Discord:

https://user-images.githubusercontent.com/52249767/112141554-b374c000-8bd5-11eb-86f9-5e9159193119.mov

**Comment by iSpeakNerd** [comment]
There is the scaling "Change Zoom" feature in appearance, but it causes an infinite loop hang on windows desktop client

App version: Version: 0.3.0-beta
Node version: StatusDesktop/v0.85.0/windows-amd64/go1.15
