### ISSUE TITLE
Can `chatsModel.resolveENS` be removed?

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#2103]
`chatsModel.resolveENS` doesn't seemed to be used. Can we remove it?

**Comment by richard-ramos** [comment]
It's currently being used in https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Chat/components/PrivateChatPopup.qml#L34 but perhaps it can be replaced by a call to EnsResolver.resolveEns() ?

**Comment by iurimatias** [comment]
closing as this is not an issue per se
