### ISSUE TITLE
Review stickers collectibles support

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#2104]
Collectibles calls for purchased stickers seems to fail with the following in the console:
```shell
ERR 2021-03-24 18:09:56+11:00 rpc response error                         topics="rpc" tid=28731566 file=core.nim:24 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":3,\"message\":\"execution reverted: ERC721Enumerable: owner index out of bounds\"}}"
```

**Comment by jrainville** [comment]
That's a known issue. It's the way the contract let's us know that there is no sticker. There was no other function to check for token ownership. So all we could do was have a try catch and on error, just know that there is nothing.
