### ISSUE TITLE
Trying to add http://localhost:8555 rpc url shows "invalid url"

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#2114]
1. Add custom network: Profile > Advanced > Network > Add network
2. Type a name, then type in manually `http://localhost:8555` in to the rpc url field
3. Select "custom" for network chain
4. Click save
5. Expected: network should successfully save
6. Actual: rpc url shows error "invalid URL"

![imgur](https://imgur.com/8y0V8Rg.png)

**Comment by anastasiyaig** [comment]
it works fine in latest master of version: 0.1.0-beta.10
