### ISSUE TITLE
implement buy crypto feature

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2120]

**Comment by hesterbruikman** [comment]
I'm guessing this needs a design on how to handle web content when browser is disabled. Or were you thinking to redirect to open in default browser?

Keeping an eye on this issue as there is a compliance requirement (i.e. explicit redirect away from Status), that I want to make sure carries over to Desktop

**Comment by iurimatias** [comment]
@hesterbruikman I guess this will need to wait for the wallet redesign

**Comment by iurimatias** [comment]
putting this on hold due to upcoming wallet redesign
