### ISSUE TITLE
Scrolling the message pane with a mouse wheel on windows is too slow.

### ISSUE THREAD

**Issue by johnlea-quiup** [status-im/status-desktop#2121]
Steps to reproduce:

1. Open both Discord and Status Desktop on Windows
2. Make sure lots of messages are loaded into the message pane in both Status Desktop and Discord
3. Try scrolling the message pane using mouse wheel in both Discord and Status Desktop

Current incorrect behaviour: scrolling using the mouse wheel is too slow in Status Desktop, to the extent that scrolling using the mouse wheel isn't really feasible. 

Desired behaviour: scrolling using the mouse wheel in Status Desktop should be the same speed as scrolling using the mouse wheel in Discord.

**Comment by jrainville** [comment]
I can confirm, it's been slow since the change to the scroll we've done a while back, but it was because it was apparently way too fast for Linux, so it seems to be OS based for some reason.

We'll need to use a different setting for each OS it seems.
