### ISSUE TITLE
Issues with scaling on Windows in a multi-monitor environment 

### ISSUE THREAD

**Issue by johnlea-quiup** [status-im/status-desktop#2124]
When testing Status desktop beta 7 on a Windows computer with three monitors that each use different scaling settings (200%, 150% and 100%) the scaling of the app gets messed up in multiple ways.  Rather than describing, it's probably easiest to see looking at the screenshots below:

On monitor with scaling set to 100% (this is a 4K monitor)
![Status Desktop using Windows on monitor with scalling set to 100 precent](https://user-images.githubusercontent.com/22846356/112505636-e0b3a080-8d84-11eb-906c-213fb5872dfe.png)

On monitor with scaling set to 150% (this is also a 4K monitor)
![Status Desktop using Windows on monitor with scalling set to 150 precent](https://user-images.githubusercontent.com/22846356/112505629-df827380-8d84-11eb-9324-2ac9e31f4c0a.png)

On monitor with scaling set to 200% (this is also a 4K monitor)
![Status Desktop using Windows on monitor with scalling set to 200 precent](https://user-images.githubusercontent.com/22846356/112505634-e01b0a00-8d84-11eb-9d8c-8a263e870d2f.png)

Nothing was changed in-between taking these screenshots, other than dragging the window to a different monitor.

Notice how the internal app scaling does something weird on the monitor with scaling set to 150% (everything becomes very large), and then everything gets much smaller on the monitor with 200% scaling - to the point that all the elements on the monitor with 200% scaling are smaller than the elements on the monitor with 100% scaling.  

Also notice the window title bars get smaller as the monitor's scaling factor increases.

Prob. worth looking at #2057 at the same time as looking at this issue.

I promise I didn't change the size of the window at all in-between taking these screenshots!  ;-)

**Comment by iurimatias** [comment]
to be fixed in #2178
