### ISSUE TITLE
Replies to comments UI implementation doesn't match design

### ISSUE THREAD

**Issue by johnlea-quiup** [status-im/status-desktop#2125]
See screenshot below which shows beta 7 next to the relevant Figma design.

![replies to comments UI implementation doesn't match design](https://user-images.githubusercontent.com/22846356/112508412-6b959a80-8d87-11eb-928a-f4f128d7bd42.png)

The primary issues in the implementation are:
- the text at the top of the reply bubble (the "-> @[name]" text and the quoted comment text) is the wrong colour.
- the separator line is the wrong colour 
- the "-> @[name]" text at the top of the bubble should be the same size as quoted comment text size
- the margins of text at the top of the reply bubble and the reply itself don't match up (they should be the same)
- the expand button in the implementation doesn't seem to match the figma design, see screenshot below
![2021-03-25 16_40_53-💬 Chat⎜Desktop - Figma](https://user-images.githubusercontent.com/22846356/112510013-f034e880-8d88-11eb-8e61-0b53bd751e0a.png)

It's also worth checking that the font sizes match with the design.  Difficult for me to tell if the font sizes are correct in the implementation due the the scaling issues ( #2124 ) on Windows.

**Comment by iurimatias** [comment]
closing because this classic bubble mode is not supported anymore, and when it is we need to revisit it everything
