### ISSUE TITLE
Sending [group] message freezes mac for a few seconds

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#2130]
There is a rainbow ball for a few seconds when sending message

**Comment by michaelsbradleyjr** [comment]
We need to move the sending-message action, along with many other actions, off of the main thread.

The effort to do that will be underway in the near future; we now have a [better mechanism](https://github.com/status-im/status-desktop/pull/2034) for tackling the problem. See also PRs #2075 and #2105.

**Comment by iurimatias** [comment]
@flexsurfer I take this is for group messages in particular and on beta.7  not master?

**Comment by iurimatias** [comment]
this is fixed in master and I can replicate the freeze behaviour in beta.7

**Comment by iurimatias** [comment]
related #1315

**Comment by iurimatias** [comment]
related #2131

**Comment by flexsurfer** [comment]
still in the latest master

https://user-images.githubusercontent.com/11790366/128890619-aceddc9f-5f5a-462a-9f7f-923c3896d836.mov

**Comment by anastasiyaig** [comment]
this is a duplicate of https://github.com/status-im/status-desktop/issues/3157

**Comment by anastasiyaig** [comment]
we do have a common problem of slow sending messages no matter of chat. Also the problem is related to data folder, when the data folder is not new - sending messages is getting slower and slower

**Comment by iurimatias** [comment]
closing as duplicate of #3157
