### ISSUE TITLE
Communities: It is not possible for non-admins to share a community

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#2139]
Only the admin can share and invite to  a community. Normal users should be able to do it as well, at least in the case of public communities.

The other types are a little bit more complex, but invite should at least let the invitees see the community in community list to request access for example.

Might need some design for where to show the button cc @simonricoo

**Comment by jrainville** [comment]
All good for the design, sorry for the ping Simon, I now see the menu has "Invite people" in it 👍

**Comment by guylouis** [comment]
@jrainville cool if the designs are clear! I imagine above when you say "public community" you mean "no requirement" community as in the screenshot below 

![image](https://user-images.githubusercontent.com/11461437/113125274-ba738200-9216-11eb-8279-cd32aebf1748.png)

**Comment by jrainville** [comment]
> I imagine above when you say "public community" you mean "no requirement" community as in the screenshot below

Yes
