### ISSUE TITLE
Global Display and Language settings

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#2144]
#### Current behavior
- Display and Language settings are per account and can only be changed after account creation/import and login
- When Display and Language settings are changed, these changes are not visible on the login screen

#### Proposed behavior
- ~Account creation: Support 'default app mode' on Windows (and equivalent on Mac and Linux) and set appearance mode on first time launch to 'System' as default~ moved to #2177 
- Login screen: Add option to change global Display and Language setting on the login screen (https://i.imgur.com/FQZMMcG.png)
- Settings: Keep option to change global Display and Language setting in Settings post login
- Additional account creation: When a new account is created, the global setting is applied

**********
#### User stories
- User story 1
     - As a user _who opted to change the display setting,_
     - I want _this setting to apply to my most frequently visited screens_
     - Because _that's why I chose the setting_

- User story 2 --> addressed by #2177 
     - As a user _who is new to Status_
     - I want _for the application to respect my system Language and Display settings on launch (account creation/import)_
     - Because _these are settings I prefer for my applications_
     
## Notes
A 3rd user stories is not covered by this solution as it has conflicting requirements
- User story 3
     - As a user _who has multiple accounts,_ 
     - I want _to set a language for each_ 
     - So that _I can switch between languages_

I suspect changing these might be different issues:
- Listen to dark mode system setting on windows, mac, Linux
- Change toolbar to respect appearance setting
- Hide Language on login screen when only one language (EN) is available

**Comment by simonricoo** [comment]
After the chat with @hesterbruikman, we agreed on following requirements:
Appearance and Language should work globally, not per account, meaning when you change language or appearance setting on Acc 1 the same applies to Acc 2, Acc 3 (the whole app) etc...

There will be no change to log in screen.
