### ISSUE TITLE
app icon is barely visible in windows systray

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2151]
press x to 'close' app / minimize to systray

![Screenshot_21.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/3c5c6726-c9c6-4e82-8636-634e3e0a20a6)

![tenor.gif](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/1a2b5227-378c-4711-88a7-4a7528a3960d)

**Comment by jrainville** [comment]
This is also related to the Theme not being respected on Windows. Doing `Universal.Theme` always returns `0`.
