### ISSUE TITLE
Wallet feature: send transaction dialog should use ens search component

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#2164]
1. Go to wallet
2. Click Send
3. The send transaction dialog appears. There is a box there allows you to type an address or enter an ENS name. The problem is that the ENS name must be exact for it to work. Instead, it should be a search, just like when starting a new chat. 

To see the ENS search:
1. Go to Chat
2. Click "+" > Start new chat
3. Type "obama", and you should see "obama.stateofus.eth" appear.

**Comment by iurimatias** [comment]
we need a design for this

**Comment by PascalPrecht** [comment]
> Instead, it should be a search, just like when starting a new chat.
Should be noted here that, even when starting a new chat, ENS name has to be exact to work. The search just looks up as you type and might still be unsuccessful (also it looks in your existing contacts as well with [partial] ENS name match and/or three-name alias)
