### ISSUE TITLE
ability to add language next to triple backticks and retrieve value back during unmarshalling

### ISSUE THREAD

**Issue by dzuqe** [status-im/status-desktop#2192]
In reference to https://github.com/status-im/status-desktop/pull/2175#issuecomment-812534066 we require a user to state the language of their code block right after the triple backtick.

Steps have been made to add a new `language` attribute here https://github.com/status-im/markdown/pull/3 but currently the value of the attribute comes back empty. The model layer needs to be analyzed to check whether this attribute is correctly stored and sent back via rpc.

**Comment by richard-ramos** [comment]
Created this PR to update the version of markdown used in status-go
https://github.com/status-im/status-go/pull/2238

**Comment by iurimatias** [comment]
putting this on hold due to upcoming wallet redesign

**Comment by iurimatias** [comment]
duplicate of #1368
