### ISSUE TITLE
ux: if you scroll extremely fast in a chat the hover state will affect multiple messages when coming to a halt

### ISSUE THREAD

**Issue by rinzlxr** [status-im/status-desktop#2196]
https://user-images.githubusercontent.com/58890963/113908151-8419a200-97d6-11eb-928e-42a27c90b0bb.mp4

**Comment by iurimatias** [comment]
fixed in https://github.com/status-im/status-desktop/commit/2e25bf4f8afcf04b122f2422f17bb08ef49ef13e
