### ISSUE TITLE
Implement activity center

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#2203]
We need to implement the activity center on desktop for these chat requests

~~New design for the setting for accepting new chats from non-contacts~~

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=572%3A4521

https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=2428%3A15796

![image.png](https://images.zenhubusercontent.com/5ea70e106499d53d00627c49/41baf5fb-7318-44b8-8def-695e2d7c0508)

**Comment by iurimatias** [comment]
updated issue description

**Comment by iurimatias** [comment]
related to #2345

**Comment by jrainville** [comment]
Closing as it has been replaced by an epic here https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/2611
