### ISSUE TITLE
Dark Mode UI Review

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2218]
Great job with implementing dark mode and new light mode :) So happy. I've noticed some very small things here is the list:

<img width="920" alt="Screen_Shot_2021-04-12_at_10_51_59" src="https://user-images.githubusercontent.com/52249767/114368072-5a1d0280-9b7d-11eb-9e2e-35796c697a2f.png">
![Screen_Shot_2021-04-12_at_10_51_47](https://user-images.githubusercontent.com/52249767/114368115-63a66a80-9b7d-11eb-8690-ff611ed5d8e6.png)
<img width="177" alt="Screen_Shot_2021-04-12_at_10_45_25" src="https://user-images.githubusercontent.com/52249767/114368210-7ae55800-9b7d-11eb-88f5-311b5a54fe22.png">
<img width="179" alt="Screen_Shot_2021-04-12_at_10_46_03" src="https://user-images.githubusercontent.com/52249767/114368246-820c6600-9b7d-11eb-84dc-1209c6744aaa.png">

The hover from View Profile is still on even when Im hovering over the item above (profile item) + make the hover color on the profile item the same as all the hovers (10% white)

https://user-images.githubusercontent.com/52249767/114368715-f8a96380-9b7d-11eb-89a6-c2d1b8aa1bfd.mov

<img width="307" alt="Screen_Shot_2021-04-12_at_10_58_28" src="https://user-images.githubusercontent.com/52249767/114369009-3efec280-9b7e-11eb-94e0-6787c7794aec.png">

<img width="371" alt="Screen_Shot_2021-04-12_at_10_59_12" src="https://user-images.githubusercontent.com/52249767/114369075-50e06580-9b7e-11eb-87fd-82a7bedcb0de.png">
<img width="306" alt="Screen_Shot_2021-04-12_at_11_00_55" src="https://user-images.githubusercontent.com/52249767/114369205-6fdef780-9b7e-11eb-918d-69a91a0bac46.png">
<img width="418" alt="Screen_Shot_2021-04-12_at_11_03_06" src="https://user-images.githubusercontent.com/52249767/114369498-bd5b6480-9b7e-11eb-87bd-37153a4f95b4.png">
<img width="382" alt="Screen_Shot_2021-04-12_at_11_17_47" src="https://user-images.githubusercontent.com/52249767/114371482-d06f3400-9b80-11eb-88d1-81ca1f6a03d4.png">

Dark mode uses light mode hover effect here:
https://user-images.githubusercontent.com/52249767/114371888-3f4c8d00-9b81-11eb-97d5-9b0f2a9a36f8.mov

<img width="663" alt="Screen_Shot_2021-04-12_at_11_13_48" src="https://user-images.githubusercontent.com/52249767/114372056-6e62fe80-9b81-11eb-9db2-d1caa4d39ae3.png">
<img width="952" alt="Screen_Shot_2021-04-12_at_11_23_46" src="https://user-images.githubusercontent.com/52249767/114372241-9d797000-9b81-11eb-85cc-9200d02a59c9.png">

**Comment by jrainville** [comment]
@PascalPrecht , I fixed some of those issues last week. They haven't been merged yet since Iuri was off.>
Here are two of them: 
- https://github.com/status-im/status-desktop/pull/2189
- https://github.com/status-im/status-desktop/pull/2197

it's not a big deal if you do a fix as well, though the submenu one was a bit harder to fix, so if it can save you some time, that's great.

**Comment by PascalPrecht** [comment]
@jrainville thanks for letting me know!

**Comment by simonricoo** [comment]
Found out that the separator is missing on light mode, is that fixed too @jrainville? CC @PascalPrecht 
<img width="244" alt="Screen_Shot_2021-04-13_at_11_30_29" src="https://user-images.githubusercontent.com/52249767/114531156-ed246e00-9c4b-11eb-8f2f-06105243025f.png">

**Comment by simonricoo** [comment]
Found one more:
<img width="619" alt="Screen_Shot_2021-04-13_at_13_50_00" src="https://user-images.githubusercontent.com/52249767/114548039-814c0080-9c5f-11eb-8773-f863e3906f1a.png">

**Comment by simonricoo** [comment]
<img width="758" alt="Screen_Shot_2021-04-13_at_13_49_17" src="https://user-images.githubusercontent.com/52249767/114552137-8cedf600-9c64-11eb-8dab-4e1975879d92.png">

**Comment by PascalPrecht** [comment]
Linking a few fixes here:

- #2229
- #2230
- #2231
- #2232
- #2233
- #2234
- #2235
- #2236

**Comment by simonricoo** [comment]
<img width="343" alt="Screen_Shot_2021-04-13_at_17_07_22" src="https://user-images.githubusercontent.com/52249767/114575839-de08e480-9c7a-11eb-8588-70afafd77f12.png">

**Comment by simonricoo** [comment]
<img width="722" alt="Screen_Shot_2021-04-13_at_17_07_16" src="https://user-images.githubusercontent.com/52249767/114576020-0abcfc00-9c7b-11eb-8c7b-493ee18542cf.png">
![Uploading Screen_Shot_2021-04-13_at_17_07_03.png…]()

**Comment by PascalPrecht** [comment]
All of the bugs mentioned in this issue are fixed in these PRs: https://github.com/status-im/status-desktop/issues/2218#issuecomment-818713912

Sorry for so many separate ones, I think some of them needed separate PRs for review, but there are others that have been added later one as the reports came in later as well.

**Comment by simonricoo** [comment]
Found one more: @PascalPrecht 
<img width="267" alt="Screen_Shot_2021-04-14_at_15_46_00" src="https://user-images.githubusercontent.com/52249767/114721366-24bd1400-9d39-11eb-9515-9b57fc99dddc.png">

**Comment by PascalPrecht** [comment]
Once #2251 lands we can close this issue as solved.

**Comment by PascalPrecht** [comment]
Aaaand it's done.
