### ISSUE TITLE
fix: utilise `sourceClipRect` for Create Community modal image preview

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#2224]
In the Create Community modal, the image preview is not cropped due to the complexity in the math involved. Qt 5.15 introduced the `sourceClipRect` property that we should utilise to crop correctly in the preview.

Once we upgrade to 5.15 or 6, we should also update the image preview to use this property.

**Comment by iurimatias** [comment]
note: needs qt upgrade

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5241
