### ISSUE TITLE
Can't back up the seed phrase, stuck on step 3

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2232]
On the last step when Im going to verify the 2nd word, when Im clicking next , i am prompted to enter the same info endlessly.

<img width="631" alt="Screen Shot 2021-04-13 at 13 54 36" src="https://user-images.githubusercontent.com/52249767/114548465-15b66300-9c60-11eb-9c7a-09ee34a5edad.png">

Version: beta.8.rc3
StatusDesktop/v0.72.1/darwin-amd64/go1.13.4

**Version:** `beta.8`

**Comment by richard-ramos** [comment]
@simonricoo, can you try again but running desktop from the terminal to see if there's any error message that would be helpful to debug the issue? I tried to reproduce the issue unsuccefully: 

https://user-images.githubusercontent.com/1106587/115283275-257aef00-a119-11eb-8749-5cec3f0ecabf.mp4


(notice that I first click outside the confirmation dialog to see if it would reset the parent dialog)

**Comment by anastasiyaig** [comment]
@richard-ramos nothing special in terminal, just a loop when entering last word:

`DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wakuext_getLinkPreviewWhitelist
DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wallet_getPendingTransactions
DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=mailservers_getMailservers
DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wakuext_contacts
DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wallet_getCustomTokens
DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=accounts_getAccounts
DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=eth_getBalance
DBG 2021-04-22 11:50:56+03:00 Connecting to mailserver                   topics="mailserver model" tid=2606596 file=model.nim:84 enode=1a4ab7d1d5dd67ca27427@178.128.142.94:443
DBG 2021-04-22 11:50:56+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=admin_addPeer
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=eth_getBalance
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606598 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606599 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606600 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606601 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_saveSetting
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606600 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606599 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606598 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wakuext_chats
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wakuext_loadFilters
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606602 file=core.nim:20 rpc_method=wakuext_chatMessages
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606603 file=core.nim:20 rpc_method=wakuext_chatMessages
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606603 file=core.nim:20 rpc_method=wakuext_emojiReactionsByChatID
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606602 file=core.nim:20 rpc_method=wakuext_emojiReactionsByChatID
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=browsers_getBookmarks
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=eth_getBlockByNumber
DBG 2021-04-22 11:50:57+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:50:58+03:00 callPrivateRPC                             topics="rpc" tid=2606601 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:50:58+03:00 callPrivateRPC                             topics="rpc" tid=2606601 file=core.nim:20 rpc_method=wallet_getCustomTokens
DBG 2021-04-22 11:50:58+03:00 callPrivateRPC                             topics="rpc" tid=2606601 file=core.nim:20 rpc_method=eth_getBalance
ERR 2021-04-22 11:50:58+03:00 rpc response error                         topics="rpc" tid=2606598 file=core.nim:24 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}"
ERR 2021-04-22 11:50:58+03:00 rpc response error                         topics="rpc" tid=2606600 file=core.nim:24 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":3,\"message\":\"execution reverted: ERC721Enumerable: owner index out of bounds\"}}"
DBG 2021-04-22 11:50:58+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:50:58+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wallet_getPendingTransactions
DBG 2021-04-22 11:50:58+03:00 Peer disconnected                          topics="mailserver model" tid=2606596 file=model.nim:124 peer=enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443
WRN 2021-04-22 11:50:58+03:00 Active mailserver disconnected!            topics="mailserver model" tid=2606596 file=model.nim:128 peer=enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@178.128.141.87:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://a5fe9c82ad1ffb16ae60cb5d4ffe746b9de4c5fbf20911992b7dd651b1c08ba17dd2c0b27ee6b03162c52d92f219961cc3eb14286aca8a90b75cf425826c3bd8@104.154.230.58:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://4ea35352702027984a13274f241a56a47854a7fd4b3ba674a596cff917d3c825506431cf149f9f2312a293bb7c2b1cca55db742027090916d01529fe0729643b@134.209.136.79:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://4e0a8db9b73403c9339a2077e911851750fc955db1fc1e09f81a4a56725946884dd5e4d11258eac961f9078a393c45bcab78dd0e3bc74e37ce773b3471d2e29c@134.209.136.101:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://0d9d65fcd5592df33ed4507ce862b9c748b6dbd1ea3a1deb94e3750052760b4850aa527265bbaf357021d64d5cc53c02b410458e732fafc5b53f257944247760@178.128.141.42:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://2b01955d7e11e29dce07343b456e4e96c081760022d1652b1c4b641eaf320e3747871870fa682e9e9cfb85b819ce94ed2fee1ac458904d54fd0b97d33ba2c4a4@134.209.136.112:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://fbeddac99d396b91d59f2c63a3cb5fc7e0f8a9f7ce6fe5f2eed5e787a0154161b7173a6a73124a4275ef338b8966dc70a611e9ae2192f0f2340395661fad81c0@34.67.230.193:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://0624b4a90063923c5cc27d12624b6a49a86dfb3623fcb106801217fdbab95f7617b83fa2468b9ae3de593ff6c1cf556ccf9bc705bfae9cb4625999765127b423@35.222.158.246:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://a8bddfa24e1e92a82609b390766faa56cf7a5eef85b22a2b51e79b333c8aaeec84f7b4267e432edd1cf45b63a3ad0fc7d6c3a16f046aa6bc07ebe50e80b63b8c@178.128.141.249:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://b706a60572634760f18a27dd407b2b3582f7e065110dae10e3998498f1ae3f29ba04db198460d83ed6d2bfb254bb06b29aab3c91415d75d3b869cd0037f3853c@35.239.5.162:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://282e009967f9f132a5c2dd366a76319f0d22d60d0c51f7e99795a1e40f213c2705a2c10e4cc6f3890319f59da1a535b8835ed9b9c4b57c3aad342bf312fd7379@35.223.240.17:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://c07aa0deea3b7056c5d45a85bca42f0d8d3b1404eeb9577610f386e0a4744a0e7b2845ae328efc4aa4b28075af838b59b5b3985bffddeec0090b3b7669abc1f3@35.226.92.155:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://ce559a37a9c344d7109bd4907802dd690008381d51f658c43056ec36ac043338bd92f1ac6043e645b64953b06f27202d679756a9c7cf62fdefa01b2e6ac5098e@134.209.136.123:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://182ed5d658d1a1a4382c9e9f7c9e5d8d9fec9db4c71ae346b9e23e1a589116aeffb3342299bdd00e0ab98dbf804f7b2d8ae564ed18da9f45650b444aed79d509@34.68.132.118:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@178.128.141.0:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://cf5f7a7e64e3b306d1bc16073fba45be3344cb6695b0b616ccc2da66ea35b9f35b3b231c6cf335fdfaba523519659a440752fc2e061d1e5bc4ef33864aac2f19@47.75.221.196:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://e87f1d8093d304c3a9d6f1165b85d6b374f1c0cc907d39c0879eb67f0a39d779be7a85cbd52920b6f53a94da43099c58837034afa6a7be4b099bfcd79ad13999@35.238.106.101:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://ac3948b2c0786ada7d17b80cf869cf59b1909ea3accd45944aae35bf864cc069126da8b82dfef4ddf23f1d6d6b44b1565c4cf81c8b98022253c6aea1a89d3ce2@47.75.88.12:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://32915c8841faaef21a6b75ab6ed7c2b6f0790eb177ad0f4ea6d731bacc19b938624d220d937ebd95e0f6596b7232bbb672905ee12601747a12ee71a15bfdf31c@47.75.59.11:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://385579fc5b14e04d5b04af7eee835d426d3d40ccf11f99dbd95340405f37cf3bbbf830b3eb8f70924be0c2909790120682c9c3e791646e2d5413e7801545d353@47.244.221.249:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://8bebe73ddf7cf09e77602c7d04c93a73f455b51f24ae0d572917a4792f1dec0bb4c562759b8830cc3615a658d38c1a4a38597a1d7ae3ba35111479fc42d65dec@47.75.85.212:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://13d63a1f85ccdcbd2fb6861b9bd9d03f94bdba973608951f7c36e5df5114c91de2b8194d71288f24bfd17908c48468e89dd8f0fb8ccc2b2dedae84acdf65f62a@47.244.210.80:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://b77bffc29e2592f30180311dd81204ab845e5f78953b5ba0587c6631be9c0862963dea5eb64c90617cf0efd75308e22a42e30bc4eb3cd1bbddbd1da38ff6483e@47.75.10.177:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://b957e51f41e4abab8382e1ea7229e88c6e18f34672694c6eae389eac22dab8655622bbd4a08192c321416b9becffaab11c8e2b7a5d0813b922aa128b82990dab@47.75.222.178:443
DBG 2021-04-22 11:50:58+03:00 Peer connected                             topics="mailserver model" tid=2606596 file=model.nim:133 peer=enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443
qrc:/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesHeader.qml:82:13: QML SVGImage: Binding loop detected for property "sourceSize.height"
qrc:/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesHeader.qml:82:13: QML SVGImage: Binding loop detected for property "sourceSize.height"
qrc:/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesHeader.qml:82:13: QML SVGImage: Binding loop detected for property "sourceSize.height"
DBG 2021-04-22 11:50:58+03:00 callPrivateRPC                             topics="rpc" tid=2606605 file=core.nim:20 rpc_method=eth_getBlockByNumber
DBG 2021-04-22 11:50:59+03:00 callPrivateRPC                             topics="rpc" tid=2606605 file=core.nim:20 rpc_method=wallet_getTransfersByAddress
DBG 2021-04-22 11:50:59+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:00+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:01+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:03+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
qrc:/app/AppLayouts/Wallet/components/collectiblesComponents/CollectiblesHeader.qml:82:13: QML SVGImage: Binding loop detected for property "sourceSize.height"
DBG 2021-04-22 11:51:04+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:04+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:51:05+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:06+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
WRN 2021-04-22 11:51:06+03:00 Automatically switching mailserver         topics="mailserver model" tid=2606596 file=model.nim:219
WRN 2021-04-22 11:51:06+03:00 Finding a new mailserver...                topics="mailserver model" tid=2606596 file=model.nim:197
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=mailservers_ping
DBG 2021-04-22 11:51:06+03:00 Connecting to mailserver                   topics="mailserver model" tid=2606596 file=model.nim:84 enode=1a4ab7d1d5dd67ca27427@178.128.142.94:443
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=wakuext_updateMailservers
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=mailservers_getMailserverTopics
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=mailservers_addMailserverTopic
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=mailservers_addMailserverTopic
DBG 2021-04-22 11:51:06+03:00 Requesting messages from                   topics="mailserver model" tid=2606596 file=model.nim:149 mailserver=enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=waku_generateSymKeyFromPassword
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=wakuext_requestMessages
DBG 2021-04-22 11:51:06+03:00 Requesting messages from                   topics="mailserver model" tid=2606596 file=model.nim:149 mailserver=enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=waku_generateSymKeyFromPassword
DBG 2021-04-22 11:51:06+03:00 callPrivateRPC                             topics="rpc" tid=2606596 file=core.nim:20 rpc_method=wakuext_requestMessages
DBG 2021-04-22 11:51:07+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:08+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:10+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:11+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:12+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:13+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:14+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:16+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:16+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:51:17+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:18+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:19+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:20+03:00 callPrivateRPC                             topics="rpc" tid=2606604 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:21+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=accounts_getAccounts
DBG 2021-04-22 11:51:21+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=eth_call
DBG 2021-04-22 11:51:22+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=wallet_getPendingTransactions
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
DBG 2021-04-22 11:51:26+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:51:36+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:51:40+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:51:46+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:51:56+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:52:06+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
qrc:/app/AppLayouts/Profile/Sections/BackupSeedModal.qml:185:9: QML ConfirmationDialog: cannot find any window to open popup in.
DBG 2021-04-22 11:52:06+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:52:16+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
qrc:/app/AppLayouts/Profile/Sections/BackupSeedModal.qml:185:9: QML ConfirmationDialog: cannot find any window to open popup in.
DBG 2021-04-22 11:52:16+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:52:18+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-04-22 11:52:26+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:52:36+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:52:46+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:52:54+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
qrc:/app/AppLayouts/Profile/Sections/BackupSeedModal.qml:185:9: QML ConfirmationDialog: cannot find any window to open popup in.
DBG 2021-04-22 11:52:56+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:52:57+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
qrc:/app/AppLayouts/Profile/Sections/BackupSeedModal.qml:185:9: QML ConfirmationDialog: cannot find any window to open popup in.
DBG 2021-04-22 11:53:02+03:00 callPrivateRPC                             topics="rpc" tid=2606565 file=core.nim:20 rpc_method=settings_getSettings
qrc:/app/AppLayouts/Profile/Sections/BackupSeedModal.qml:185:9: QML ConfirmationDialog: cannot find any window to open popup in.
DBG 2021-04-22 11:53:06+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:53:16+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:53:26+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:53:36+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:53:46+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:53:56+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:54:06+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:54:16+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:54:26+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229
DBG 2021-04-22 11:54:36+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=2606596 file=model.nim:229

`

**Comment by jakubgs** [comment]
The `v0.1.0-beta.9` also has this issue.
