### ISSUE TITLE
Notification preview is shown as raw code when having text + emoji

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2246]
Notification preview is shown as raw code when having text + emoji

**Steps:**

1. install Status Desktop build
2. join any status public channel
3. send status to background
4. send a message to the same chat from another device, message should contain text + emoji
5. receive a push-up notification

<img width="278" alt="Снимок экрана 2021-04-14 в 13 14 04" src="https://user-images.githubusercontent.com/82375995/114695391-3e079580-9d24-11eb-85ad-323fcb6b0a45.png">

**Build:** `Version: beta.7.rc2`
**Node version:** `StatusDesktop/v0.72.1/darwin-amd64/go1.13.4`
**OS:** `MacOS Big Sur 11.2.3, Apple M1`

**Comment by iurimatias** [comment]
can confirm this also happens in beta.8

**Comment by anastasiyaig** [comment]
seems yes, i can reproduce it on `Version: beta.8` (in case anything is not cached)
