### ISSUE TITLE
Notification preview is duplicated

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2247]
Notification preview is duplicated when Status Desktop is running on background but not collapsed in tray 

**Steps:**

1. install Status Desktop build
2. join any status public channel
3. open any other app to have it in active window, for example Discord messenger is active and status is on background but not collapsed
4. send a message to the same chat from another device
5. receive a push-up notification

https://user-images.githubusercontent.com/82375995/115872120-19a96880-a44a-11eb-9650-176e9a3dd33e.mov

**Actual result:**  the push notification is duplicated

**Build:** `Version: 0.1.0-beta.9`
**Node version:** `StatusDesktop/v0.72.1/darwin-amd64/go1.13.4`
**OS:** `MacOS Big Sur 11.2.3, Apple M1`

**Comment by emizzle** [comment]
@anastasiyaig -- I cannot replicate this in `beta.7.rc2` nor `beta.8`.

**Comment by anastasiyaig** [comment]
> @anastasiyaig -- I cannot replicate this in `beta.7.rc2` nor `beta.8`.

i will check it out again, thank you

**Comment by anastasiyaig** [comment]
cant reproduce it either now, will monitor and maybe will get more details on how to reproduce if get it again

**Comment by anastasiyaig** [comment]
and it can't be reproduced in Version: beta.8 master 20-04-2021

**Comment by anastasiyaig** [comment]
@emizzle i found a way to replicate it, please checkout the video . However nothing suspicious in application logs found

**Comment by emizzle** [comment]
I still cannot replicate this issue at all. Maybe there is an environment difference? I'm not running Big Sur and I'm on an Intel Mac. Maybe we can ask a few other people to test on Intel macos 10.15.x @iurimatias @PascalPrecht @michaelsbradleyjr?

**Comment by PascalPrecht** [comment]
I just tried reproducing this with the latest beta release (beta.9) and couldn't.
I'm also not on Big Sur and on an Intel Mac

**Comment by emizzle** [comment]
Should we close this issue for now?
