### ISSUE TITLE
Close button on "Back up your seed phrase" top bar is missing

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2248]
<img width="705" alt="Screen_Shot_2021-04-14_at_14_04_18" src="https://user-images.githubusercontent.com/52249767/114707376-701bf600-9d2a-11eb-99b1-40b37135995a.png">

Design:
<img width="685" alt="Screen Shot 2021-04-14 at 14 05 27" src="https://user-images.githubusercontent.com/52249767/114707411-79a55e00-9d2a-11eb-9772-77802f615df0.png">

https://www.figma.com/file/Iz6vZHRiA1j08VbUZi7ySa/%F0%9F%92%B0-Wallet%E2%8E%9CDesktop?node-id=381%3A587

Expected behaviour:
Keep "Back up your seed phrase" top bar closed until user Quit and reopen status again.

**Comment by anastasiyaig** [comment]
[Uploading... Запись экрана 2021-04-21 в 17.31.48.mov]
