### ISSUE TITLE
in the wallet adding account from private key hangs (sometimes?)

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2259]
steps

1. run ganache and copy paste the first private key
2. go to the wallet and select add account from private key
3. paste the private key and press add account

result: it hangs

~~note: it seems this is also affecting login afterwards~~

**Comment by iurimatias** [comment]
login issue is unrelated

**Comment by iurimatias** [comment]
I couldn't replicate this a second time might indicate there is a different issue at play

**Comment by jrainville** [comment]
I also can't reproduce. I tried about 6 private keys and logged out once and it never happened.

I was trying on Linux with a normal ganache server `ganache`.

**Comment by jrainville** [comment]
I still couldn't reproduce with the fork param.
I used this command that I copied from one of your messages:
```
ganache-cli -f https://mainnet.infura.io/v3/key...-m "clutch ... become" -i 999 -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28 --chainId 1
```
I censored some secrets just in case

**Comment by iurimatias** [comment]
can't replicate in the latest
