### ISSUE TITLE
switching currency when pointing to a local dev node crashes app

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2262]
steps

1. point desktop to local ganache node (add custom rpc, restart app)
2. go to the wallet and select currency, switch currency

result: crash/hang

**Comment by jrainville** [comment]
I tried reproducing it and it worked for me.

I'm on Linux and I used a normal ganache start. No fork or anything.

Did you do anything special @iurimatias ?

**Comment by jrainville** [comment]
I still couldn't reproduce with the fork param.
I used this command that I copied from one of your messages:
```
ganache-cli -f https://mainnet.infura.io/v3/key...-m "clutch ... become" -i 999 -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28 --chainId 1
```
I censored some secrets just in case

**Comment by iurimatias** [comment]
can't replicate in the latest
