### ISSUE TITLE
Some issues with on request communities

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2264]
**When you request an access to a community:**
1. You should **not** see it in the nav bar unless you are accepted
<img width="176" alt="Screen_Shot_2021-04-16_at_09_21_30" src="https://user-images.githubusercontent.com/52249767/114987204-2ef42500-9e95-11eb-85aa-a9a6e1bf55f8.png">

2. You should **not** be allowed inside the community, you simply stay on the preview modal.
<img width="318" alt="Screen_Shot_2021-03-25_at_10 50 52" src="https://user-images.githubusercontent.com/52249767/114987316-50eda780-9e95-11eb-8b06-d6ec458fc57d.png">

Here is the full flow how it should work when you are requesting an access to a community:
<img width="1860" alt="Screen_Shot_2021-03-25_at_10 55 42" src="https://user-images.githubusercontent.com/52249767/114987461-78dd0b00-9e95-11eb-940f-a7341d57c968.png">
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4920%3A44580

You see just a preview unless you are accepted :) The button changes its state to "Pending"

**Comment by jrainville** [comment]
I fixed this with this PR: https://github.com/status-im/status-desktop/pull/2469

It is now merged in master and I tested again in master
