### ISSUE TITLE
Add possibility to distinguish PROD and DEV builds

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2268]
We can create a possibility within tags to have DEV and PROD builds so it gives a chance to use 2 builds on 1 machine, it will be helpful to test (comparison with master and PRs or at least with releases and dev builds)

**Comment by michaelsbradleyjr** [comment]
It's not quite that simple. We do already check for an environment variable `NIM_STATUS_CLIENT_DEV`. However, it's utility is low, and if you set the variable when running a packaged build from CI/release the app would crash or at least not function correctly, as the filesystem layout of resources inside the repo does not match the layout in packaged builds (and the layout in packaged builds varies by platform: Linux, macOS, Windows).

What we need instead is a way to provide defaults and command-line / environment overrides for things like the path for the data folder. I think we can use [nim-confutils](https://github.com/status-im/nim-confutils) for that purpose. I'll conduct some experiments and create a PR if it works out.
