### ISSUE TITLE
Can't delete a community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2272]
1. Open app
2. Chats -> Add -> Community -> Add community
3. Manage community
4. Delete

Actual result: delete button does not make any effect -> community can't be deleted

<img width="1167" alt="Снимок экрана 2021-04-16 в 23 42 50" src="https://user-images.githubusercontent.com/82375995/115082117-09efc880-9f0e-11eb-9a89-0564ad455556.png">

**Device:** `macBook Pro`
**OS:** `MacOS Big Sur 11.2.3`
**Version:** `beta.8`
**Node:** `StatusDesktop/v0.72.1/darwin-amd64/go1.13.4`

**Comment by guylouis** [comment]
as discussed today, it can be removed
