### ISSUE TITLE
Can't kick member from community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2274]
1. Open status app
2. Chats -> Add -> Community
3. Create a community and open it
4. Manage community -> Invite people
5. Add a contact to community
6. For the same contact click 3 dots -> Kick option

<img width="1167" alt="Снимок экрана 2021-04-17 в 00 29 51" src="https://user-images.githubusercontent.com/82375995/115086317-ae750900-9f14-11eb-9344-17d04dd0c4ba.png">

As a result, member can't be excluded from community

**Device:** `macBook Pro`
**OS:** `MacOS Big Sur 11.2.3`
**Version:** `beta.8 , build from 17/04/2021`
**Node:** `StatusDesktop/v0.72.1/darwin-amd64/go1.13.4`

`qrc:/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml:158: TypeError: Property 'removeUserFromCommunity' of object ChatsView(0x7fa982577d10) is not a function`

**Comment by abhi-status** [comment]
This seems to have regressed.
Opening again.

**Comment by anastasiyaig** [comment]
the issue is still actual in master
