### ISSUE TITLE
docs: QML API - Chats Model (`src/app/chat/view.nim`)

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#2280]
Chats model documentation has been partially completed. The `Methods` and partial views (ie `ChannelsList`) need to be completed, as it has been done for the Wallet Model

**Comment by iurimatias** [comment]
closing this sort of PRs for now as they should be in another repo and in a differnt effort, also we're in process of refactoring this views, after that we can attempt to better document them again
