### ISSUE TITLE
Component Library: Rethink StatusSectionMenuItem, StatusSettingsLineButton and StatusButtonRow

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2295]
There's a UI element, which at the moment is implemented in a bunch of different ways, but it might be worth to rethink how they are done. There's nothing wrong with having multiple components rendering similar variations of the same thing, but I'm seeing it being used in other places where more reusability could be beneficial.

I don't have a good name for it yet, but it's an element that is used as navigation control as well as form control. Here are a few places where it's used:

Most basic form (label + arrow [caret]):
<img width="667" alt="Screenshot 2021-04-20 at 09 49 21" src="https://user-images.githubusercontent.com/445106/115358198-b3101a80-a1bd-11eb-8a06-adb6409aef4e.png">

Same but hovered state:
<img width="667" alt="Screenshot 2021-04-20 at 09 49 11" src="https://user-images.githubusercontent.com/445106/115358255-c15e3680-a1bd-11eb-9129-4e767b449e96.png">

Here it has an additional supportive text, as well as useful and important information related to its data (also hovered):
<img width="671" alt="Screenshot 2021-04-20 at 09 50 58" src="https://user-images.githubusercontent.com/445106/115358409-ea7ec700-a1bd-11eb-9a99-f99fba97b867.png">

With badge:
  <img width="653" alt="Screenshot 2021-04-20 at 10 17 52" src="https://user-images.githubusercontent.com/445106/115362304-adb4cf00-a1c1-11eb-9fec-aa6190378eac.png">

As form control (can be radio, checkbox/switch etc), also hovered in this case:
<img width="672" alt="Screenshot 2021-04-20 at 09 51 19" src="https://user-images.githubusercontent.com/445106/115358451-f79bb600-a1bd-11eb-93d6-f37eec6b7f12.png">

As switch form control (hovered and idle):
<img width="668" alt="Screenshot 2021-04-20 at 09 48 29" src="https://user-images.githubusercontent.com/445106/115358069-92e05b80-a1bd-11eb-8998-6a8fa2ba58a4.png">
<img width="667" alt="Screenshot 2021-04-20 at 09 48 13" src="https://user-images.githubusercontent.com/445106/115358084-983da600-a1bd-11eb-87d5-9294a8b31022.png">

Here's a different place in the app with practically the same element, but with an icon attached to it:
<img width="470" alt="Screenshot 2021-04-20 at 09 51 51" src="https://user-images.githubusercontent.com/445106/115358509-0a15ef80-a1be-11eb-8252-114b37a2f1d4.png">

^ A few important notes on this last use case here:

- While these are all the same, they are visually different (e.g. the ones above the divider have black font, the ones below have blue font, also the hover color is supposed to be different). We need to a good way to distinguish the two
- The icons as of right now are implemented as `StatusRoundButton`, which is semantically wrong as those can't actually be clicked. We probably want to introduce a dedicated `StatusIcon` or StatusRoundIcon` component
- The color of the icons has a level of transparency, so when the element is hovered, the color of the icon changes as well in relation to its parent hover color. This is something that isn't supported in `StatusRoundButton` either (another reason to not use it here)

Profile menu items (although, this one is semantically very different than the others, so could be a separate component):
<img width="307" alt="Screenshot 2021-04-20 at 10 12 06" src="https://user-images.githubusercontent.com/445106/115361434-e011fc80-a1c0-11eb-8d1c-d62a531b6f37.png">

## Proposal

At the moment, these components in the screenshots are implemented as:

- `CommunityPopupButton` - (last screenshot) Not a good name for the component for various reasons. They don't always open a popup, they aren't always buttons but form controls, they aren't used just in community modals etc
- `StatusSectionMenuItem` - (first screenshot) Also not a good name because it isn't used just in menu sections (but mostly). Also can't handle form controls (which is fine but it should still be more aligned with dedicated components then)
- `StatusRadioButtonRow` - This thing is really just called a "row" because it was originally used in `Column` elements
- `StatusSettingsLineButton` - Can be either a switch or just a the same thing that `StatusSectionMenuItem` is

Essentially these components are either a button to navigate somewhere, or a form control to change some setting. They can be used within modals, pages, setting sections etc.

I propose we introduce the following components respectively:

### `StatusSectionButton`

```qml
StatusSectionButton {
  text: "Chat preview links"
  hint: "Supportive text" // default: "" - not rendered when empty
  value: "None"
  hasBadge: false // default: false - renders `value` inside of badge instead of text
  showArrow: true // default: true - Can be disabled when used in profile menu context
  icon.name: "edit" // default: "" - Will be resolved by component, if empty, no icon is rendered
}
```

**Additional thoughts:**

Still need a way to configure whether we want a "round" icon or an icon without background (like it's done in the profile menu section). If the profile menu items are becoming completely different elements, then this can be omitted. Otherwise we'd have to maybe at `icon.bgColor` which defaults to `transparent`, but that would force us to override it with a color when we do want to have a round icon (makes it impractical when it comes to theming). So alternatively we could have `StatusSectionButtonWithIcon` and `StatusSectionButtonWithRoundIcon` respectively. The API would look exactly the same as `StatusSectionButton` just that it has the "round" encoded into it.

### `StatusSectionRadioControl`, `StatusSectionSwitchControl`

```qml
StatusSectionRadioControl {
  text: "Chat preview links"
  hint: "Supportive text"
  checked: false // default: false
}

StatusSectionSwitchControl {
  text: "Chat preview links"
  hint: "Supportive text"
  checked: false // default: false
}
```

Same thoughts about icons apply here as well.

## Needs discussion

As mentioned above, in the case of the community modal, there's multiple variants of the same component that are exactly the same functionality-wise, but are rendered in different colors and hover effects. We need to encode that somehow. Maybe with a property `variant` that can be individually configured?

**Comment by jrainville** [comment]
Nice writeup. I agree that we need to consolidate all those components. Your proposal makes sense. I guess `StatusSectionRadioControl` and `StatusSectionSwitchControl` would use `StatusSectionButton`? It might not be possible, but if we could, it could make it even less duplicated.

As for the community buttons needing different colors, if need be, we can always just expose aliases or properties to change those from the exterior as to not create new components just for a color change for example.

**Comment by PascalPrecht** [comment]
> I guess StatusSectionRadioControl and StatusSectionSwitchControl would use StatusSectionButton? It might not be possible, but if we could, it could make it even less duplicated.

Thanks! Correct, form controls and buttons are two different types of components. Despite it being hard/impossible to have a component be an actual `Button` and something else at the same time, I believe that we're better off composing components from smaller ones anyways.

> As for the community buttons needing different colors, if need be, we can always just expose aliases or properties to change those from the exterior as to not create new components just for a color change for example.

That's true. Would vote for that as well, but we need to be selective what components we want to expose and don't just have a one-component-to-fit-all case, where one compnoent has a radio, a switch, a this, a that, and we expose all of them, while only one of them is used at a time. It would make the component unnecessarily complex (see `StatusButton` as one example for that)

**Comment by simonricoo** [comment]
Nice work! @PascalPrecht I started creating these list item components in figma and I created all variants that we use/ some of the we dont use yet but its better to have them. I call them List Item 64 (64 is the hight). As you pointed out, list items on profile 2nd panel will be a different list item I will call it "List item 48" again 48 is the hight, you can see in the figma how Im preparing all the list item components: https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=792%3A80
<img width="1027" alt="Screen Shot 2021-04-21 at 17 37 35" src="https://user-images.githubusercontent.com/52249767/115581412-4766a400-a2c8-11eb-8f1a-4201e9669164.png">

Planned list items:
64 (those discussed here) 
52 (eg. copy share link)
<img width="438" alt="Screen Shot 2021-04-21 at 17 40 36" src="https://user-images.githubusercontent.com/52249767/115581871-afb58580-a2c8-11eb-88b4-bfccee542059.png">
48
(eg. In Profile 2nd panel)
<img width="353" alt="Screen Shot 2021-04-21 at 17 41 39" src="https://user-images.githubusercontent.com/52249767/115582039-d70c5280-a2c8-11eb-8191-530ee0f3f800.png">
36
(eg. in chat 2nd panel)
<img width="342" alt="Screen Shot 2021-04-21 at 17 42 10" src="https://user-images.githubusercontent.com/52249767/115582119-e7243200-a2c8-11eb-8cbf-c9c5aea20b14.png">
34 (eg. those in the right click dropdown)
<img width="278" alt="Screen Shot 2021-04-21 at 17 42 18" src="https://user-images.githubusercontent.com/52249767/115582136-eee3d680-a2c8-11eb-9e40-b44709d8ecc8.png">

**Comment by PascalPrecht** [comment]
Thanks @simonricoo that cools awesome.
We need to ensure we don't make component too generic because then they quickly get too complex.
I'd consider channel items, context menu items and that copy share link thingy separate components.

The profile menu items are a case I'd consider for being a `StatusSectionButton` though

**Comment by simonricoo** [comment]
The reason I call it list item is that it might also have a badge on the right side, eg Privacy (Back up your seed phrase) in the future this might also indicate some problems with synching or IDK anything really :)
<img width="673" alt="Screen Shot 2021-04-22 at 10 20 40" src="https://user-images.githubusercontent.com/52249767/115681171-90fcd080-a354-11eb-9906-6fd6e893c530.png">
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=821%3A92
<img width="444" alt="Screen Shot 2021-04-22 at 10 22 09" src="https://user-images.githubusercontent.com/52249767/115681207-99550b80-a354-11eb-81d0-42134533477a.png">

**Comment by PascalPrecht** [comment]
No worries, you can call them however you see fit. Once it comes to implementing them, we need to take into account "what" they are. In all of those screenshots, the thing looks like a list item and it mostly shows up in some form of list, but they aren't just list items, they are always some call to action item. Essentially buttons, or form controls (radio, switch etc).

If there are other cases where the same look&feel applies but the item not triggering any action, we would introduce a component that encodes that semantically

**Comment by PascalPrecht** [comment]
Closing this in favour of https://github.com/status-im/status-qml/issues/19
