### ISSUE TITLE
Implement Text Styles in new Component Library

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2328]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A9

**Comment by PascalPrecht** [comment]
This issue is hard to actually "solve" or close because we're unlikely to create components for all of the text variants. Let's leave this open until things have crystalized more.

**Comment by PascalPrecht** [comment]
Closing in favour of https://github.com/status-im/status-qml/issues/20
