### ISSUE TITLE
Implement StatusIcon component

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2330]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=63%3A0

**Comment by PascalPrecht** [comment]
Some things to keep in mind here:

- It probably makes sense to create a `StatusIcon` component that simply renders an icon based on an icon name
- I've recently learned that all icons are "wrapped" with a 24x24 space so they are always centered properly. We already have many icons downloaded and available in the app, but it probably makes sense to redownload all of them with the wrapping space so they are consistent
- The color of the icons need to be configurable (most likely using `ColorOverlay`). We've been doing that already with plenty other components
- While it's nice to have a `StatusIcon` component to render icons, we won't be able to use it every where, where icons are needed. Buttons for example come with their own `icon` property that should be leveraged whenever possible

I guess the API of such a component could look like this:

```
StatusIcon {
  icon: "close"  // some `name` that resolves to `path/to/svg/source/{name}.svg`
  width: 24 // default 24
  height: 24 // default 24
  color: "black" // default "black"
}
```
