### ISSUE TITLE
Revisit StatusRoundButton component

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2333]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A12

**Comment by PascalPrecht** [comment]
This is implemented as `StatusRoundButton` at the moment (https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusRoundButton.qml). It should do most of the job, also uses `states`, which we should in #2332 as well.

We need to double check theme colors here.

**Comment by PascalPrecht** [comment]
Adding here that there's also `StatusIconButton` which is a `RoundButton` as well, but was used for buttons with icons that aren't necessarily circular such as the ones in the chat input:

<img width="616" alt="Screenshot 2021-04-22 at 12 58 19" src="https://user-images.githubusercontent.com/445106/115703434-6ae22b00-a36a-11eb-8a77-bf44cb095c54.png">

Maybe it makes sense to unify those (maybe not)?

**Comment by PascalPrecht** [comment]
`StatusIcon` is available in #2435

**Comment by PascalPrecht** [comment]
Closing this in favour of https://github.com/status-im/status-qml/issues/9
