### ISSUE TITLE
implement checkbox, radio & toggle elements in the component library

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2334]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=706%3A1566

**Comment by PascalPrecht** [comment]
We already have

- `StatusCheckbox` - https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusCheckBox.qml
- `StatusRadioButton` - https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusRadioButton.qml
- `StatusSwitch` - https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusSwitch.qml
- `StatusSlider` - https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusSlider.qml

Those need to be revisited, especially colors and (animation) behaviour.

**Comment by PascalPrecht** [comment]
Closing in favour of https://github.com/status-im/status-qml/issues/10, https://github.com/status-im/status-qml/issues/11, https://github.com/status-im/status-qml/issues/12, https://github.com/status-im/status-qml/issues/13
