### ISSUE TITLE
support for editing chat categories in communities

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2340]
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=2431%3A28468

**Comment by anastasiyaig** [comment]
creating / editing / deleting categories for channels in communities is already merged and working in master. Would be nice to refer to PR next time, so issues will be closed automatically
