### ISSUE TITLE
Component Library: introduce loading indicator component

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2360]
Some components need a way to show a loading indicator animation. We already have `LoadingImage` for that https://github.com/status-im/status-desktop/blob/master/ui/shared/LoadingImage.qml#L4.

It does the job quite well, we should move it into the component library, ensure that the loading SVG comes with it (and isn't located in `ui/app/img` and we probably should rename it to `StatusLoadingIndicator` or something like that.

It uses `SVGImage` under the hood, which is really just an `Image` that sets the source width and height, so we can probably just inline that: https://github.com/status-im/status-desktop/blob/master/ui/shared/SVGImage.qmlma:

Figma: https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=706%3A1566

Although, we already have the asset and everything, just need to move the `LoadingImage` to the componen library and maybe rename it etc

**Comment by iurimatias** [comment]
@PascalPrecht is there a figma link for this? every task related to the component library should be backed up by a figma link of the component library

**Comment by PascalPrecht** [comment]
Updated the issue
