### ISSUE TITLE
close chat suggestions button looks blurred

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2366]
![Screen Shot 2021-04-22 at 2.32.30 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/d9c54df4-e4e8-4895-b0f9-4732a09a6717)

**Comment by iurimatias** [comment]
I tried different things, it seems to be an issue with Qt, comparing the image with one rendered in the browser, the browser one does look somewhat better. also this pixelation is reduced when the image size is bigger![Screen Shot 2021-05-03 at 4.50.03 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/d5aec870-5137-4b68-9db1-1e8846b2c62c)

**Comment by emizzle** [comment]
In the past, I've tried doubling the `sourceSize` and it seems to increase the pixel density, rendering it more clearly.
