### ISSUE TITLE
Mentions font weight changes randomly

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#2371]
![image](https://user-images.githubusercontent.com/1106587/115768788-c2879300-a378-11eb-94a8-42ab10498049.png)

**Comment by iurimatias** [comment]
can't replicate

**Comment by richard-ramos** [comment]
![image](https://user-images.githubusercontent.com/1106587/127517822-067c4a84-0e29-44ac-8ba2-33b2f7ba04f6.png)

Seems to be still happening. Maybe it only happens in Linux?

**Comment by Khushboo-dev-cpp** [comment]
This seems to be a QT issue. When I assign the same text in html program it works as expected, in Qt it adds this extra weight on the first element and strangely only when background-colour is defined. how do we proceed @iurimatias ?
