### ISSUE TITLE
deleting a chat should show a confirmation dialog

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2378]
see figma https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=70%3A0

steps
1. right click on a chat, and click 'delete chat'

result: just deletes the chat
expected result: should display a modal to confirm the user really wants to delete this chat

**Comment by ITwrx** [comment]
I came to open an issue to have this feature(?) removed after hulk smashing my whole office, and i found this issue when searching first. 

Why should the user be asked to confirm what they just requested? What is the threat that the user is being protected against? Can't they just rejoin the chat if they didn't have temporary control over their own fingers? Maybe status should use their camera to make sure they are wearing approved Typing Mittens? :) 

i can understand if they were deleting some important records from their database, but unless i'm missing something (quite possible), i don't see anything important being lost if status just goes ahead and does what it was asked to do.

thanks
