### ISSUE TITLE
emoji reaction menu needs a slight adjustment

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2385]
current:

![Screen Shot 2021-04-22 at 3.16.10 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/dc7ec7f3-a9b8-456d-bf8e-e9a2df3dcbec)

desired:

![Screen Shot 2021-04-22 at 3.16.18 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/15c75494-8ce8-400d-93f8-d611d7cf4ece)

**Comment by iurimatias** [comment]
this condition `messageContextMenu.y -= Math.max(messageContextMenu.emojiContainer.height, 56) + Style.current.padding ` is the issue, everytime clicking on the emoji reaction, the y where the menu shows is slightly different each time

**Comment by jrainville** [comment]
Just an FYI, positioning this correctly was pretty hard at the time. Maybe someone else will find the right way to do it, but I'm just saying this, because the issue itself is pretty minor, but trying to fix it is a bit hard and can take time.

**Comment by iurimatias** [comment]
moving back as it's much harder to fix than it looks
