### ISSUE TITLE
clicking on fetch more messages should have immediate feedback and prevent multiple clicks

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2409]
currently when we click "Fetch more messages" it's not clear that something is happening, we should disable that url after the first click, and re-enable it after the fetch has been done

**Comment by saledjenic** [comment]
@iurimatias I found ( as @anastasiyaig also) that "Fetch more messages" is available only if you add new contact and switch to 1:1 chat. In that moment clicking "Fetch more messages" looks like something is happened behind, like loading icon is displayed. But not sure at all if that is working as it should. Also not sure do we need to have that option here cause when you add new contact it's assumed that there is no history messages. Any thoughts on this?

**Comment by iurimatias** [comment]
closing because fetch more messages option has been removed
