### ISSUE TITLE
on macOS command+, should open the Profile view

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/status-desktop#2410]
On macOS `command+,` is the common keyboard shortcut for opening an app's preferences view/window/modal.

**Comment by iurimatias** [comment]
tried different apps and this shortcut didn't work, general list of keyboard shortcuts is to be done in a different task anyway so closing this

**Comment by iurimatias** [comment]
tried different apps and this shortcut didn't work, general list of keyboard shortcuts is to be done in a different task anyway so closing this

**Comment by michaelsbradleyjr** [comment]
Are you sure you tried *"command plus comma"*?

I just now tried in Brave, Chrome, Firefox, Discord, Telegram, BBedit, 1Password, Notes, Reminders, Messages, Mail, Music, etc., and I was always taken to a window/modal for app preferences.

For Status Desktop, the Profile view is the equivalent of a window/modal for the app's preferences.

**Comment by michaelsbradleyjr** [comment]
> general list of keyboard shortcuts is to be done in a different task anyway so closing this

Ah, I read too quickly. Close away.

But, *"command comma"* does work in many app, it's nearly universal for macOS app, so should be part of the general keyboard shortcuts task for macOS.

**Comment by iurimatias** [comment]
should be done as apart of the general shortcuts revamp
