### ISSUE TITLE
Transaction bubbles don't work correctly

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2413]
It's possible to send transactions from within  a 1:on:1 chat.
When receiving users don't have an ENS name attached to their account, senders have to request their wallet address first, before they can actually transact value.

Receivers can then accept and share their address and get to decide what the address is (for example when multiple wallet accounts are configured within Status, any of these accounts can be the address that receives the transaction.

Once accepted and shared, senders should be prompted to sign and send the transaction. However, there seems to be a bug that the "Sign and Send" button appears on the **receiver** side instead.

This needs fixing.

**Comment by jrainville** [comment]
This should be fixed by https://github.com/status-im/status-desktop/pull/2914
