### ISSUE TITLE
Back button is missing when creating a community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2414]
1. Open app
2. enable Communities in settings
3. create any community

**Actual result:** back button is missing

**Version:** `0.1.0-beta.9`

<img width="1023" alt="Снимок экрана 2021-04-23 в 12 20 29" src="https://user-images.githubusercontent.com/82375995/115850463-8c0c4f80-a42e-11eb-9669-d67b36dd2ebf.png">

**Comment by iurimatias** [comment]
that back button is part of an older design, the communities are now on the sidebar and so the back button is not needed anymore
