### ISSUE TITLE
Notifications option is not implemented for Communities

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2421]
<img width="1440" alt="Снимок экрана 2021-04-23 в 17 14 47" src="https://user-images.githubusercontent.com/82375995/115884351-7e1ef480-a457-11eb-9234-575bcc708995.png">

**Comment by jrainville** [comment]
This was hidden as it is part of Phase 2. I'll move it back to the Future tasks and label phase 2
