### ISSUE TITLE
Error: event "accountsChanged" does not exist when clicking Disconnect in browser

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2423]
Can't disconnect a wallet in browser, also `Error: event "accountsChanged" does not exist` is shown. Wallet drop-down is closed

1. open app
2. enable browser
3. go to simpledapp.eth and connect your wallet
4. click wallet icon and select Disconnect

<img width="1440" alt="Снимок экрана 2021-04-23 в 18 43 29" src="https://user-images.githubusercontent.com/82375995/115896365-04413800-a464-11eb-8bd0-bca273ff0d2d.png">

**Comment by emizzle** [comment]
@richard-ramos I removed line https://github.com/status-im/status-desktop/blob/093f7cff7accac5eba417d6f0a23572bdcb63b41/ui/app/AppLayouts/Browser/provider.js#L810 and it worked without error. I don't see any code that listens for this event emission. Do we need this line?

**Comment by richard-ramos** [comment]
> Do we need this line?

It's part of [EIP 1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#accountschanged)
