### ISSUE TITLE
Expose status-go version to About section

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2431]
It would be nice which status-go version is running with the build, we can expose it to About section in the app

**Comment by iurimatias** [comment]
it's actually there in Node version, for e.g here it's status-go 0.72.1

![Screen Shot 2021-05-05 at 4.37.18 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/a330d9bf-cbe5-40a0-ad1c-184c499ec7e6)
