### ISSUE TITLE
Set up "catalog" to view and test ui components

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2438]
With a growing component library that offers many variants, options, states etc. it's useful to have some place where components can be viewed and tested.

Originally we have added a new application tab which was used as a kitchen sink. We later removed it because it slowed down the app. However, we were also quite unexperienced with QML and the tech stack, so it might be worth revisiting that option.

Otherwise, I think @borismelnik had some idea about this.

**Comment by PascalPrecht** [comment]
We talked about this offline and decided to reactivate our UIComponents application tab but only make it available inside debug mode.

**Comment by iurimatias** [comment]
https://github.com/status-im/status-qml/issues/2
