### ISSUE TITLE
Decide on component library structure

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2439]
At the moment, many components that are reused in the application live inside `ui/shared`. Last year we started building dedicated Status components with proper look and feel, which ended up in `ui/shared/status`.

This is the current home of our component library.

Since the component library is growing, it might make sense to think about if and how we want to break them up into different silos so they are semantically grouped as well.

Here are some ideas:

- `status/forms` - Reusuable form controls. This includes checkboxes, radio buttons, inputs, text areas, sliders etc
- `status/buttons` - Obviously button components. Although, it might make sense to put them inside form controls
- `status/layout` - Components used to build application layouts, like `StatusNavbar`, `StatusApplicationBar`, primary/secondary pane etc.
- `status/modals` - All modal and dialog components
- `status/core` - Components that don't really fit in the other buckets but also aren't too specific e.g. `StatusIcon`

**Comment by borismelnik** [comment]
we can use standard naming like `controls popups core views`

**Comment by PascalPrecht** [comment]
Closing, in favour of https://github.com/status-im/status-qml/issues/4
