### ISSUE TITLE
Status client is irresponsive when collapsing it to trey by clicking cross button

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2440]
1. Open app
2. At the top left click red cross button
3. Try to expand the app from dock

`ERR 2021-04-26 16:19:27+03:00 TODO: if user is logged in, logout         topics="main" tid=3209992 file=nim_status_client.nim:155
anastasiya@MacBook-Pro-Anastasiya /Applications % cd /Applications
Status.app/Contents/MacOS/nim_status_client
Network Cache Dir:  "/Users/anastasiya/Library/Application Support/Status/tmp/netcache"
qml: Unknown theme. Valid themes are "light" and "dark"
`

As a result, status is irresponsive and i have to force close it and reopen again

https://user-images.githubusercontent.com/82375995/116094199-00a1f100-a6b0-11eb-8d6e-8adc171ea09d.mov

Expected: status is opened from dock after being send to dock

**Comment by iurimatias** [comment]
possible duplicate of 2311

**Comment by anastasiyaig** [comment]
moved details to https://github.com/status-im/status-desktop/issues/2311
