### ISSUE TITLE
Sometimes shortcuts are not being applied on MacOS

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2452]
I faced with it when testing #2429 : when you resize the app with CMD+ - there is no delay in zooming in the app, one keyboard press zooms in the app for 1 step. This is not a case when you try to zoom out -> sometimes it hangs, and does not do anything (CMD - ). Sometimes you need to press 3 times to do 1 step zoom out . Also i saw the following console message (not sure if is relevant though): libpng warning: iCCP: known incorrect sRGB profile - it shows when zooming out (cmd - )

However it is not related to the scaling PR rather than shortcuts functionality on Desktop, sometimes it does not work and you need to apply a combination several times to make it work.

**Comment by iurimatias** [comment]
putting in the icebox since 2429 was closed in the meanwhile

**Comment by iurimatias** [comment]
cloosed since it was specific to a now closed PR, shortcuts is a different issue
