### ISSUE TITLE
Redundant push notifications when creating / leaving group chat as an owner

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2484]
When creating / leaving a group chat owner of which i am, there is no need to show a push notification to me that i joined a group chat or left it, since i am already aware of it -> i either created it or left it

@simonricoo it would be nice to have some insight from you

<img width="1440" alt="Снимок экрана 2021-05-04 в 10 51 28" src="https://user-images.githubusercontent.com/82375995/116978134-fdb88900-accb-11eb-9113-56b2a64ad82c.png">

<img width="1440" alt="Снимок экрана 2021-05-04 в 11 08 42" src="https://user-images.githubusercontent.com/82375995/116978104-f2fdf400-accb-11eb-9e51-79fa60870e91.png">

**Comment by simonricoo** [comment]
What is the push notification saying? @anastasiyaig

**Comment by anastasiyaig** [comment]
@simonricoo basically all is on the screenshot -> nothing meaningful, just a chat key and group chat name

**Comment by simonricoo** [comment]
Ok we dont need that indeed.
