### ISSUE TITLE
Remove [More] option in Manage menu for user who is logged in (owner or participant of community)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2486]
**Steps:**

1. login to the app
2. enable Communities in Settings
3. create a random community 
4. click manage -> members
5. select yourself and click kick / view profile

<img width="1440" alt="Снимок экрана 2021-05-04 в 12 43 15" src="https://user-images.githubusercontent.com/82375995/116986339-55f48880-acd6-11eb-8e45-488d90701623.png">

**As a result:**
- community is present in the list
- community contains 0 members
- i am still able to manage the community

**Expected:** need to clarify the expected result, but probably we want to disable the option for community creator to kick off himself since it does not make any sense as well as seeing your own profile (three dots options only available for other community members when managing but not for the admin)

@simonricoo please advise

**Comment by simonricoo** [comment]
Yes, the solution is to remove "Kick" from the dropdown menu if its an admin.

**Comment by anastasiyaig** [comment]
how about View profile? Do we need it in the same case? @simonricoo

**Comment by simonricoo** [comment]
true we dont need that either as thats you. Ok so the whole more icon can be dismissed than :)

**Comment by anastasiyaig** [comment]
amazing thank you !
