### ISSUE TITLE
Backup seed phrase prompt is shown when upgrading application

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2494]
**Steps:**

1. install some version of the app 
2. back up seed phrase
3. delete status app (do not remove keys)
4. install new image of the app
5. login and go to profile -> privacy and security 

As a result -> backup seed phrase is shown, which is not needed because the phrase was already backed up

**Comment by alaibe** [comment]
@anastasiyaig could you confirm this is still happening, I am not able to reproduce.

Also I installed 2 times the same version.

To confirm: 
backup seed phrase is show but it is grey and cannot be clicked.
![image](https://user-images.githubusercontent.com/491074/125593249-881d11a2-a0be-4b9c-a716-9f942067e04f.png)

Do you expect this entry to disappear totally?

**Comment by anastasiyaig** [comment]
@alaibe this solution is totally fine , the initial issue was that the prompt to back it up was active.

**Comment by alaibe** [comment]
When restoring an account from seed phrase we should not ask to back up the seed phrase
