### ISSUE TITLE
Share community link contains extra C in the Url

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2501]
1. create community
2. tap manage community
3. copy Share community url

**As a result**, the link contains **extra C** in the url, which **can't be** opened on mobile. 

<img width="752" alt="Screenshot 2021-05-05 at 23 50 10" src="https://user-images.githubusercontent.com/82375995/117207798-0b216080-adfd-11eb-9c96-624a0406bef1.png">

<img width="1124" alt="Screenshot 2021-05-05 at 23 53 40" src="https://user-images.githubusercontent.com/82375995/117207951-3c019580-adfd-11eb-8dcd-9b2fcd482ca4.png">

**Comment by jrainville** [comment]
Do we have a spec for what URLs should look like? Because in status-go, they use `cc` as well https://github.com/status-im/status-go/blob/develop/protocol/chat.go#L314
cc @cammellos

**Comment by anastasiyaig** [comment]
dunno, havent ever seen it @jrainville but the way it works: link copied from Share community does not work on mobile, however same link without c - does. So maybe something wrong on mobile , not quite sure

**Comment by cammellos** [comment]
oh, yes, there's a discrepancy, we should just settle for one or the other `/c/` or `/cc/`, we can go for `cc` and we'll update status-react

**Comment by anastasiyaig** [comment]
@cammellos do i need to create a ticket somewhere in status-go repo to have this fixed?

**Comment by cammellos** [comment]
if you could, please, but in status react

**Comment by anastasiyaig** [comment]
@cammellos logged https://github.com/status-im/status-react/issues/12084

**Comment by cammellos** [comment]
thank you!

**Comment by cammellos** [comment]
oh wait a second :)
it needs to be fixed on desktop 
`cc` is a link to a community chat (therefore cc). 
If you are linking to a community, then `c` should be used

**Comment by jrainville** [comment]
Ah ok, that makes sense. I'll update our link to the community to use `c`.
I think you can close the issue for status-react then?

**Comment by anastasiyaig** [comment]
it is closed already
