### ISSUE TITLE
Application crashes when switching to Chats tab having the very last channel in the Community active

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2504]
**Steps:**

1. open app and enable communities
2. join any random public chat
2. create community with at least 2 channels (could be more)
2. select the very last channel in the list to make it active
3. click Chats tab

https://user-images.githubusercontent.com/82375995/123400149-1ba8b880-d5ae-11eb-9373-dca703e4be1f.mov

https://user-images.githubusercontent.com/82375995/117276843-f4642380-ae67-11eb-8ddb-6d346ae431b0.mov

`Traceback (most recent call last)
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(220) nim_status_client
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(162) mainProc
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

**Comment by PascalPrecht** [comment]
@anastasiyaig is that something you can still reproduce on latest `master`?

Because I can't reproduce this one

**Comment by anastasiyaig** [comment]
yes @PascalPrecht i can reproduce it in master

**Comment by PascalPrecht** [comment]
Tried this with existing accounts that have communities (+ channels) as well as brand new accounts. Still no way to reproduce this.

Anyone else **without** macOS Big Sur who can try to reproduce this error? @michaelsbradleyjr @emizzle maybe?

**Comment by jrainville** [comment]
I tired on Windows and couldn't reproduce either

**Comment by emizzle** [comment]
I'm not able to reproduce this on macos 10.15.7.

**Comment by anastasiyaig** [comment]
> I'm not able to reproduce this on macos 10.15.7.

thanks for giving it a try, looks like it is specific for Big Sur

**Comment by anastasiyaig** [comment]
confirmed this happens on Catalina / Big Sur as well
