### ISSUE TITLE
1x1 chat preview is not shown on desktop when initiated from mobile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2506]
When 1 x 1 chat is initiated from mobile to desktop -> on desktop there is no any sign of it , no chat preview, no notification, nothing

**Steps:**

1. create account on mobile (device A)
2. create account on desktop (device B)
3. as device A -> scan a QR code to start chatting with device B
4. send some messages
5. check the Chat tab on device B (desktop)

**Comment by jrainville** [comment]
This is because account A is not a contact. It will be fixed along with https://github.com/status-im/status-desktop/issues/2345

**Comment by jrainville** [comment]
Should be fixed in https://github.com/status-im/status-desktop/pull/2571 because it will send a contact request

**Comment by anastasiyaig** [comment]
@jrainville as far as i can see, when lets say on mobile i pick someone and start chatting, for example, from public chat i click a random profile (let it be a desktop app) and click send message -> then on desktop is not shown anything still, no contact request, no chat

![Screenshot 2021-05-31 at 14.21.22.png](https://images.zenhubusercontent.com/6074560cfd1d342d606f37d3/3390142a-39a8-4f32-9fd0-f49f3f40994f)

**Comment by jrainville** [comment]
@anastasiyaig ah yes that's normal. They still don't have the contact request feature and we don't have the activity center yet, so we both have implemented solutions that work but are not compatible yet.

If you want to receive a message from someone on mobile, you need to have them added as a contact from desktop.

If you want, we can keep this issue opened in the backlog and see if the activity center for us fixes or if they have the contact requests, it should fix it as well.

**Comment by anastasiyaig** [comment]
ya lets keep it in backlog for now, thank you @jrainville !

**Comment by jrainville** [comment]
Ah also, since we have contact requests, if you add from mobile an account on desktop as a contact, desktop would still receive the contact request, so it's something haha

**Comment by anastasiyaig** [comment]
@simonricoo i need your eyes on this one. Basically, we are implementing Contact Request for Desktop, however when initiating such a request from mobile - it is still old functionality

**Comment by anastasiyaig** [comment]
@iurimatias please move this to backlog for now

**Comment by simonricoo** [comment]
@anastasiyaig I guess we need to wait for Mobile to implement it otherwise there are a lot of edge cases to cover.

**Comment by anastasiyaig** [comment]
thats right @simonricoo , lets wait

**Comment by iurimatias** [comment]
closing as this is an issue on mobile, we did changes to these feature isn't a blocker for these specific 1 on 1 messages, and there will other tasks related to this
