### ISSUE TITLE
RPC response error when posting to a channel in community as a banned user

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2507]
**Steps:**

1. on mobile, create a community 
2. from mobile, invite desktop to this community
3. on mobile (as admin) add a channel
4. on desktop open this channel to keep it visible
5. on mobile as admin , ban desktop user
6. on desktop, as already banned user, send any message to channel in community

<img width="1440" alt="Screenshot 2021-05-06 at 15 07 42" src="https://user-images.githubusercontent.com/82375995/117296082-4fecdc00-ae7d-11eb-8d96-afcd8ca04259.png">

`DBG 2021-05-06 15:06:56+03:00 callPrivateRPC                             topics="rpc" tid=505158 file=core.nim:20 rpc_method=wakuext_sendChatMessage
ERR 2021-05-06 15:06:56+03:00 rpc response error                         topics="rpc" tid=505158 file=core.nim:24 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"can\'t post on chat\"}}"
`

**Comment by PascalPrecht** [comment]
As discussed offline with @anastasiyaig, this needs clarification on what the expected "solution" is.

One thing that is crucial though is, the application hangs when running into this scenario. This should be addressed no matter what the expected (ui) behaviour is.

**Comment by anastasiyaig** [comment]
@PascalPrecht per discussion happened in # communities (discord) -> the solution (per @cammellos ) is the following (applied on mobile):

> there should be a canPost flag, input should be disabled if that's false, I think that's what we use in mobile

also, per @guylouis: 

> As per the issue you raised above, as a user the ideal would be to get a message "you're not a member of this community, you can't post", but at this stage any technical solution that just prevents desktop to hang is good enough I think (BTW It might happen the other way around too when mobile user tries to post in a community from which he has been banned)
