### ISSUE TITLE
Request access functionality is missing when being [shared] with community that requires approval from mobile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2513]
**NOTE:** _**there is significant difference between ### SHARE and ### INVITE community flows on mobile**_

**Steps:**

1. as a mobile (device A) -> create a community that requires approval to join
2. as a mobile (device A) -> add desktop (device B) to contacts
3. as mobile (device A) -> go to community you just created and tap 3 dots -> view profile -> **SHARE** icon 
4. as mobile (device A) -> select desktop (device B) to share the community

**As a result on device B (desktop):**

- join community button is shown in 1x1 chat 
- when clicked Join -> user is joined as follower (can't post messages, can't see channels)

<img width="1431" alt="Screenshot 2021-05-07 at 09 38 42" src="https://user-images.githubusercontent.com/82375995/117408229-4d8b9000-af18-11eb-9be8-2207856a26b6.png">

<img width="1431" alt="Screenshot 2021-05-07 at 09 41 03" src="https://user-images.githubusercontent.com/82375995/117408326-72800300-af18-11eb-8383-46d3b2eed1eb.png">

![IMG_DFBEB9CB5AC0-1](https://user-images.githubusercontent.com/82375995/117408407-92172b80-af18-11eb-99aa-d4fd9296bf92.jpeg)

**Expected:**

1. Request access should be shown instead of join since this community requires approval
2. When user clicks Request approval -> get approval -> he can post messages to any channels, all channels are visible to the user

**Comment by jrainville** [comment]
This should be fixed with this PR https://github.com/status-im/status-desktop/pull/2471

**Comment by jrainville** [comment]
This was merged in master. You can test it again to see if the problem was fixed

**Comment by anastasiyaig** [comment]
@jrainville thank you for pointing on this! I will close this one since i do receive a request to join now, however there is another issue i will open separatly: when requested access and approved -> request bubble shows "pending" until the app is relaunched. And community is not shown even i am approved and joined it

<img width="1433" alt="Screenshot 2021-05-28 at 15 48 00" src="https://user-images.githubusercontent.com/82375995/119986760-ec158900-bfcc-11eb-8e9d-899894d4d724.png">
