### ISSUE TITLE
Invite members option is not available for non-admins of community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2516]
**Steps:**

- create a community on mobile to be an admin here
- add a desktop device to contacts of mobile
- add desktop to the community
- as desktop -> go to members and click 3 dots button

As a result, a member of community can't invite people there, however it should

<img width="1231" alt="Screenshot 2021-05-07 at 16 55 52" src="https://user-images.githubusercontent.com/82375995/117460410-2901d900-af55-11eb-9d7f-f2975b5ff5c5.png">

**Comment by anastasiyaig** [comment]
admin:

<img width="1231" alt="Screenshot 2021-05-07 at 16 39 59" src="https://user-images.githubusercontent.com/82375995/117462099-f527b300-af56-11eb-9b8c-6af23f651dcf.png">

non-admin

<img width="1231" alt="Screenshot 2021-05-07 at 16 55 52" src="https://user-images.githubusercontent.com/82375995/117462132-fe188480-af56-11eb-91ba-55c7525027ff.png">

on mobile non-admin can invite as well

**Comment by iurimatias** [comment]
@anastasiyaig @guylouis can we close this issue then?

**Comment by anastasiyaig** [comment]
sure thing, @churik you may want to open an issue in status-react to align the functionality (do not let non-admins invite , only share)

**Comment by churik** [comment]
> I agree with @jrainville only admins can invite, and non admins can only share
that's not great terminology, but anyway it seems the invitation concept will be revamped in phase 3

@guylouis 
Ok then, to prevent ambiguity for available options and permissions for each role in "Require approval" community:
1) Admin
2) Invited user
3) User, with whom the community was shared 
please open a separate issue for mobile to be on the same page.
Thanks!

**Comment by guylouis** [comment]
clarified here 
https://github.com/status-im/status-react/issues/12135
