### ISSUE TITLE
Notification through notify-send on Linux

### ISSUE THREAD

**Issue by danrobi11** [status-im/status-desktop#2520]
Hello 
First thank you for status.
Everything works fine except for notification.
Please send notification to `notify-send` on Linux.
That way the users can config their notification the way they like through notifier app like [dunst](https://github.com/dunst-project/dunst)

For some reason that I cant explain I dont get any notification on my lappy but I do on my desktop.
This is very strange since both devices run the same OS :/
However, the notification that I do have on the desktop does disappear like 5 sec after. Thats useless!

I wouldnt have any issue if status would send notification to `notify-send`
My dunst is configured to keep notification up until I click on it. Therefore I cant miss any messages ;)

Thanks!

**Comment by ScyDev** [comment]
+1
