### ISSUE TITLE
Status connection to googleusercontent.com

### ISSUE THREAD

**Issue by danrobi11** [status-im/status-desktop#2521]
I can see that status makes connection to `googleusercontent.com` 
How is this good for privacy ?

```
connection: <1620445161> <eth0>:49292 => 17.240.223.35.bc.googleusercontent.com.:443 (tcp) up/down Bps: 96/96 process: "nim_status_clie"
connection: <1620445161> <eth0>:36358 => 58.230.154.104.bc.googleusercontent.com.:443 (tcp) up/down Bps: 96/96 process: "nim_status_clie"
connection: <1620445161> <eth0>:56418 => 101.106.238.35.bc.googleusercontent.com.:443 (tcp) up/down Bps: 96/64 process: "nim_status_clie"
connection: <1620445161> <eth0>:59586 => 193.230.67.34.bc.googleusercontent.com.:443 (tcp) up/down Bps: 96/64 process: "nim_status_clie"
connection: <1620445161> <eth0>:45866 => 118.132.68.34.bc.googleusercontent.com.:30305 (tcp) up/down Bps: 96/64 process: "nim_status_clie"

```

**Comment by danrobi11** [comment]
> could you please confirm in what context you saw this?

./StatusIm-Desktop-0.1.0-beta.9-093f7c.AppImage

> browser to check your gmail or use a google service

Never !

I dont see the connection here between the AppImage and my browser. But im just a non-technical user

**Comment by danrobi11** [comment]
@corpetty I see. Well the only thing i've done is to add a contact (my laptop). I've send a few msg and 1 picture from my local storage.

**Comment by iurimatias** [comment]
@danrobi11 do/did you have url unfurling enabled and/or "display images in the chat automatically"?

screenshots for reference

![Screen Shot 2021-05-12 at 9 27 21 AM](https://user-images.githubusercontent.com/176720/117982805-62936500-b304-11eb-8315-4eaba2b2e152.png)

![Screen Shot 2021-05-12 at 9 27 34 AM](https://user-images.githubusercontent.com/176720/117982841-69ba7300-b304-11eb-9ff0-cabfefcf33ea.png)

**Comment by danrobi11** [comment]
@iurimatias 

chat link preview = disabled 

display images in the chat automatically = enabled

**Comment by iurimatias** [comment]
@danrobi11 ok so it's highly likely that what you saw was due to an image posted in a channel that was hosted in googleusercontent.com, with `display images in the chat automatically` enabled that will cause the app to fetch the image causing that connection to appear. I hope that clarifies things.

**Comment by danrobi11** [comment]
@iurimatias Ok Thanks for the support
