### ISSUE TITLE
Back up seed phrase bug

### ISSUE THREAD

**Issue by Nacretr** [status-im/status-desktop#2523]
_English;_
Hello there,
As you can see in the short video I shared with you below, I cannot proceed in the "Backup Seed Phrase" section.
After confirming the second word, it asks for the same "word" value over and over but does not continue.
The "StatusIm-Desktop-v0.1.0-beta.9" version I downloaded on 08.05.2021.
I hope I didn't keep you busy unnecessarily.
Have a nice day. 

_Turkish;_
Merhaba,
Aşağıda sizinle paylaştığım kısa videoda da göreceğiniz gibi "Backup Seed Phrase" bölümünde ilerleyemiyorum.
İkinci kelimeyi de onayladıktan sonra, aynı "word" değerini tekrar tekrar soruyor ama devam etmiyor.
08.05.2021 tarihinde indiriğim "StatusIm-Desktop-v0.1.0-beta.9" sürümünü.
Umarım sizi gereksiz yere meşgul etmemişimdir.
İyi çalışmalar...

https://user-images.githubusercontent.com/83866464/117541649-79446e00-b01d-11eb-8436-88438c28fe1e.mp4

**Comment by emizzle** [comment]
@iurimatias, I can replicate this in "StatusIm-Desktop-v0.1.0-beta.9", but cannot replicate in latest master https://github.com/status-im/status-desktop/commit/079aa825cd036a0cdfe917a2988d4fb54aa16da1.

**Comment by iurimatias** [comment]
fixed in beta.10
