### ISSUE TITLE
Logged in user is shown in mention suggestions

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2530]
1. create any chat (group / public chat) 
2. enter @ to start mentioning

**As a result:**

- you are shown in suggestions (no reason to highlight yourself)
- custom pic of yours is not shown as well

<img width="1429" alt="Screenshot 2021-05-10 at 19 53 27" src="https://user-images.githubusercontent.com/82375995/117696540-16440a00-b1ca-11eb-81d1-bb205de41001.png">

No need to fix a picture, lets remove yourself from mentioning at all, so when i enter @ to check suggestions, I am not shown in the list

**Comment by iurimatias** [comment]
So in fact this is the expected behaviour and it's common in other messengers as well (to be able to @ oneself)
