### ISSUE TITLE
Custom picture is shown for a contact in chat only after relogin

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2531]
**Steps:**

1. go to public chat and send some message from mobile device there
2. as mobile, set a custom picture
3. as desktop, go to the same public chat -> check that custom picture is not shown for non-contacts
4. as desktop , add mobile to contacts

Expected: custom picture of a contact is shown immediately after adding user to contacts

Actual result: contact's custom pic is shown only after relogin

**Comment by iurimatias** [comment]
no longer happens in latest master, probably fixed by #2512
