### ISSUE TITLE
Getting "Not enough ETH for gas" when attempting to buy a sticker pack (could just be very high gas prices)

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2535]
Getting "Not enough ETH for gas" when attempting to buy a sticker pack, but the account should have enough ETH, unclear if bug or just very high gas prices

![Screen Shot 2021-05-10 at 4.47.51 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/4d6050e9-2655-487c-ba9d-d7475e9ad162)

**Comment by anastasiyaig** [comment]
I can reproduce it as well , also gas price is low now

**Comment by anastasiyaig** [comment]
`DBG 2021-07-20 18:12:23+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=5947173 file=model.nim:190
qrc:/shared/Input.qml:175:5: QML QQuickTextEdit: Cannot anchor to an item that isn't a parent or sibling.
qrc:/shared/Input.qml:175:5: QML QQuickTextEdit: Cannot anchor to an item that isn't a parent or sibling.
qrc:/shared/Input.qml:175:5: QML QQuickTextEdit: Cannot anchor to an item that isn't a parent or sibling.
qrc:/shared/Input.qml:175:5: QML QQuickTextEdit: Cannot anchor to an item that isn't a parent or sibling.
qrc:/shared/Input.qml:175:5: QML QQuickTextEdit: Cannot anchor to an item that isn't a parent or sibling.
qrc:/shared/status/StatusStickerPackPurchaseModal.qml:65: TypeError: Cannot read property 'symbol' of undefined
qrc:/shared/status/StatusStickerPackPurchaseModal.qml:137: TypeError: Cannot read property 'symbol' of undefined
qrc:/shared/status/StatusStickerPackPurchaseModal.qml:158: TypeError: Cannot read property 'symbol' of undefined
qrc:/shared/status/StatusStickerPackPurchaseModal.qml:87: TypeError: Cannot read property 'symbol' of undefined
qrc:/shared/status/StatusStickerPackPurchaseModal.qml:166: TypeError: Cannot read property 'symbol' of undefined
qrc:/shared/status/StatusStickerPackPurchaseModal.qml:11: TypeError: Property 'getStatusToken' of object WalletView(0x7f82d5548430) is not a function
qrc:/shared/status/StatusStickerPackClickPopup.qml:89: ReferenceError: root is not defined`

**Comment by iurimatias** [comment]
fixed in beta.11
