### ISSUE TITLE
Profile options disappear when hovering any icon at the navigation pane (left side)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2546]
**Steps:**

1. open status app -> profile
2. select any profile option, for example Appearance
3. hover over any item at the left pane (chats or wallet for example)

As a result, profile option is not shown

<img width="1552" alt="Screenshot 2021-05-12 at 11 33 52" src="https://user-images.githubusercontent.com/82375995/117944526-05a0aa80-b316-11eb-8f80-4fa0968fd3df.png">

https://user-images.githubusercontent.com/82375995/117944561-0fc2a900-b316-11eb-901b-c31931e33636.mov

**Comment by saledjenic** [comment]
@anastasiyaig I was checking the latest master and few commits before it and I was not able to reproduce this issue. Please try again and let me know if the issue is still happening.

**Comment by anastasiyaig** [comment]
not able to reproduce now
