### ISSUE TITLE
Muted contacts and Muted chats modals are blank when nothing added to list

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2549]
In case nothing is added to mute (chat or contact) -> the modals are empty. Would be nice to add some placeholder inside the modals saying "no records" or something

@simonricoo or @errorists what do you think?

<img width="1440" alt="Screenshot 2021-05-12 at 12 38 53" src="https://user-images.githubusercontent.com/82375995/117985215-2d593800-b341-11eb-9ad7-28a237feb771.png">

<img width="1440" alt="Screenshot 2021-05-12 at 12 39 06" src="https://user-images.githubusercontent.com/82375995/117985267-39dd9080-b341-11eb-8d3e-bbd77d4c9258.png">

**Comment by simonricoo** [comment]
Yes indeed, "Muted chats will appear here"
