### ISSUE TITLE
Mobile onboarding slider is shown on desktop

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2558]
<img width="1552" alt="Screenshot 2021-05-13 at 12 00 51" src="https://user-images.githubusercontent.com/82375995/118103764-efaceb80-b3e2-11eb-8e1c-100ad523cbae.png">

This slider should not be there, onboarding flow for desktop does not have it 
https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=6%3A0

@simonricoo is the figma design accurate for onboarding? 

@iurimatias i assume this comes with the ALPHA disclaimer , can we move it somehow to another screen?

**Comment by jrainville** [comment]
The design is either not up to date or people need to talk lol.

@iurimatias declared it a big issue when we no longer had that screen. It's important to have it since we are still in beta and we need to show the warning

**Comment by anastasiyaig** [comment]
warning is okay, however the slider is something we dont want to have right now as i got from @simonricoo , but maybe i got it wrong

**Comment by iurimatias** [comment]
I'm fine with whatever it needs to look like design wise, but the warning and checkbox absolutely *need* to be there

**Comment by anastasiyaig** [comment]
@simonricoo could you please help us to create something nice and pretty which we can implement instead of this screen? We need some help. The goal is to keep the warning for user when launching the app after install and user must accept this to proceed

**Comment by simonricoo** [comment]
New design:
<img width="837" alt="Screenshot 2021-05-28 at 11 18 24" src="https://user-images.githubusercontent.com/52249767/119961503-6d0d5a00-bfa6-11eb-94b6-ce1bdaaa7681.png">
https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=1681%3A2169
