### ISSUE TITLE
Can't sign in to Kyberswap

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2559]
<img width="1552" alt="Screenshot 2021-05-13 at 16 37 35" src="https://user-images.githubusercontent.com/82375995/118133471-8d1b1600-b409-11eb-9200-fa198114168f.png">

`js: 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.`

**Comment by iurimatias** [comment]
apparently we can get around this by enabling/disabling compatibility mode

**Comment by iurimatias** [comment]
duplicate of #3323
