### ISSUE TITLE
Hover over Join button has wrong shape

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2563]
Precondition: community is created and invitation is sent to desktop, which awaits  a user to Join

**Steps:**

1. use either dark mode or basic
2. hover over Join community button

<img width="812" alt="Screenshot 2021-05-15 at 10 31 40" src="https://user-images.githubusercontent.com/82375995/118352210-d03fcb00-b568-11eb-8b15-5a890fd1b58e.png">

**Expected:** check figma https://www.figma.com/file/k2h3UyN2f5m4rYppxfOzFE/%F0%9F%8C%93-Dark-Mode%E2%8E%9CDesktop?node-id=4800%3A10279

**Comment by alexandraB99** [comment]
@anastasiyaig could somehow get an invitation to a community so that I can reproduce this on my end?

**Comment by anastasiyaig** [comment]
sure thing, send me your chat key so I can invite you
