### ISSUE TITLE
refactor to remove some libstatus imports in src/app

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2586]
some files (e.g stickers) in the app are using directly libstatus which breaks the abstraction, we need to refactor this

**Comment by jrainville** [comment]
I think this was done because of the threading effort. Using the `status` model wasn't possible because it uses `self` iirc.

**Comment by anastasiyaig** [comment]
@iurimatias is it related to any PR? Can u please provide the PR number or if this is merged already - close this issue?
