### ISSUE TITLE
Status process is not killed when doing Logout&Quit

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2587]
1. open status desktop on windows
2. login
3. click Logout&Quit
4. check Task manager

As a result, the Status process is still running. 

**Expected:** Status process is killed when:

1. user selects Logout&Quit
2. user click the cross button and then right click Status in tray -> Quit

**Comment by iurimatias** [comment]
doesn't seem to happen on windows

**Comment by anastasiyaig** [comment]
i dont see it happening anymore as well
