### ISSUE TITLE
Clicking Add Contact button does not have any visual representation

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2595]
1. open status and create account
2. click + button -> new chat
3. paste a valid chat key, for example `0x04bbec328a75540705fcbed9c73f5b4a9ffb5d4ef12d9bc6d7cefc376c842ffc09cd72418efcb757d68af8c050c1f09cddb8ca3b1b7b4fb41b045911405bcb5b31`
4. click Add Contact button

As a result, user does not see the action output -> he stays on the same screen , the + button is not shown as clicked, no confirmation that contact was added

https://user-images.githubusercontent.com/82375995/119480000-dfd5c580-bd59-11eb-913e-4520c4f78b92.mov

Also, this contradicts with Contact Request feature, since we should first send a Request to user to add him to contacts, so we might change this as well (maybe remove the + button in the PR #2571 and replace it with "Request")

![image](https://user-images.githubusercontent.com/82375995/119481173-17913d00-bd5b-11eb-9906-3cad647f0393.png)

@simonricoo please take a look, would be nice to improve UX here

**Comment by simonricoo** [comment]
Yea this is conflicting with the new way of adding people to contacts. The solution is to get rid of the "Add to Contacts" icon. I will update the figma.

**Comment by alaibe** [comment]
@simonricoo I don't think figma has been updated, could you confirm the solution is still to only get rid of the icon on the right?
Thanks
