### ISSUE TITLE
Crash on login possibly due to getSettings, SIGSEGV on login

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#2603]
Once in a while, I get a crash on login on both Windows and Linux.

The stack trace is:
```
DBG 2021-05-27 11:08:34-04:00 callPrivateRPC                             topics="rpc" tid=16563 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-05-27 11:08:34-04:00 callPrivateRPC                             topics="rpc" tid=16563 file=core.nim:20 rpc_method=settings_saveSetting
DBG 2021-05-27 11:08:34-04:00 callPrivateRPC                             topics="rpc" tid=16563 file=core.nim:20 rpc_method=settings_getSettings
ERR 2021-05-27 11:08:34-04:00 TODO: if user is logged in, logout         topics="main" tid=16563 file=nim_status_client.nim:160
Object 0x55c08b05e330 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/main.qml:248: function() { [native code] }
Traceback (most recent call last)
/home/jonathan/dev/nim-status-client-runnable/src/nim_status_client.nim(220) nim_status_client
/home/jonathan/dev/nim-status-client-runnable/src/nim_status_client.nim(162) mainProc
/home/jonathan/dev/nim-status-client-runnable/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGABRT: Abnormal termination.
make: *** [Makefile:412: run-linux] Error 1
```

It seems to always be because of `settings_getSettings`, so something must still be unsafe there.

**Comment by michaelsbradleyjr** [comment]
I don't believe this is a memory safety problem re: `settings_getSettings` per se; rather, I think we have a QObject or something related to a QObject that's getting GC'd or freed in an untimely manner. We may need to review how we're wiring up some things with NimQML.

**Comment by anastasiyaig** [comment]
also was able to reproduce it on MacOS

`DBG 2021-06-01 11:49:31+03:00 callPrivateRPC                             topics="rpc" tid=2062073 file=core.nim:20 rpc_method=web3_clientVersion
DBG 2021-06-01 11:49:32+03:00 callPrivateRPC                             topics="rpc" tid=2062073 file=core.nim:20 rpc_method=settings_getSettings
DBG 2021-06-01 11:49:32+03:00 callPrivateRPC                             topics="rpc" tid=2062073 file=core.nim:20 rpc_method=settings_saveSetting
DBG 2021-06-01 11:49:32+03:00 callPrivateRPC                             topics="rpc" tid=2062073 file=core.nim:20 rpc_method=settings_getSettings
ERR 2021-06-01 11:49:32+03:00 TODO: if user is logged in, logout         topics="main" tid=2062073 file=nim_status_client.nim:160
Object 0x7f80c7936e80 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/main.qml:248: function() { [native code] }
Traceback (most recent call last)
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(220) nim_status_client
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(162) mainProc
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete`

**Comment by iurimatias** [comment]
very hard to fix/replicate because it's too random

**Comment by pinebit** [comment]
Reproduced on the latest master (39dace238bf5745782a26b4193b430f28c8f0260).
