### ISSUE TITLE
Add contact requests to the `activityCenterNotifications` call

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#2616]
Right now, contact requests are not part of the `activityCenterNotifications` API. Once it is added in status-go by us or the core team, we need to change how we show the contact requests in the activity center.

It should be part of the normal list and handle `seen`.

**Comment by iurimatias** [comment]
TODO: move this task to status-go

**Comment by iurimatias** [comment]
moved to https://github.com/status-im/status-go/issues/2293
