### ISSUE TITLE
add toggle to switch between waku v1 and waku v2

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2621]
including any work on status-go

**Comment by anastasiyaig** [comment]
@richard-ramos is it somewhere visible already in master? can't find it. If it is not merged yet, could u please link the issue to relevant PR?

**Comment by richard-ramos** [comment]
Done. Also, this wasnt implemented as a toggle switch because it made no sense. What I did was enabling/disabling wakuv2 if you choose a waku fleet.
