### ISSUE TITLE
Contact Request screen does not disappear automatically after the request is accepted

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2624]
The screen to the right does not disappear when my contact request is approved, i need to switch chats to make it gone and be able to chat. 

![image](https://user-images.githubusercontent.com/82375995/120335114-e20bc700-c2f9-11eb-905f-a17966b5e660.png)

Steps:

1. on desktop 1 create an account
2. on desktop 2 create an account
3. as account 1 send some message to # test channel
4. as account 2 join the same channel -> open account1 profile and send a message -> contact request should be sent
5. as account 1 in Contact Requests approve the request
6. as account 2 see that the UI says the request is still pending

**Comment by emizzle** [comment]
Can confirm this is happening in latest master (c0013a0956c2983543ffaf75922b06bebdc80a01)

**Comment by iurimatias** [comment]
fixed in beta.11
