### ISSUE TITLE
Allow 📋 Copy & ⬇️ Download image

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2627]
Expected behaviour: Right click on image opens dropdown with options to copy or download the image.
<img width="1658" alt="Screen Shot 2021-06-02 at 11 00 07" src="https://user-images.githubusercontent.com/52249767/120452243-5db95280-c392-11eb-946f-1d294e9547c1.png">
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5052%3A0

**Comment by iurimatias** [comment]
task done  and in master
