### ISSUE TITLE
Avatar is missing for pinned messages modal

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2632]
Once a message is pinned, the modal should show the userpic of the one who pinned it

![image](https://user-images.githubusercontent.com/82375995/120505817-03d67e00-c3ce-11eb-8e34-33d50c898655.png)

It is missing right now

![image](https://user-images.githubusercontent.com/82375995/120505865-0e911300-c3ce-11eb-8023-70449e436ff8.png)

**Comment by richard-ramos** [comment]
It seems functionality for pinned messages was added back
![image.png](https://images.zenhubusercontent.com/5a80e7574b5806bc2bc68100/e57bae6e-c7f2-413f-98f3-fe5d0bfacf9a)
