### ISSUE TITLE
Contact request accepted notification appears multiple times

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#2637]
Once someone accepts your contact request (by adding you back as contact), it sends a notification to you.

However, I've experienced a few cases where I receive that notification even when I had received one before from the same person.

I'm not exactly sure how to reproduce, but it sounds like it happens like this:
1. Send contact request to user X
2. X accepts the contact request
3. You get a notification (all good)
4. X closes their app and reopens
5. I think we receive the signal again for some reason

We need to make sure that even if we receive the signal, we don't show the notification again because we already received it before.

**Comment by anastasiyaig** [comment]
The notification duplicates appear everywhere in the app , there are several issues for this already, maybe it makes sense to fix them all

**Comment by alaibe** [comment]
@jrainville I couldn't replicate this specific one.
Could it be OS related issue?

@anastasiyaig as you mentioned it happens everywhere in the app. Do you have a reproducible scenario?

**Comment by anastasiyaig** [comment]
@alaibe yes, they are described in issues there: https://github.com/status-im/status-desktop/labels/push_notifications

For instance u receive as many notifs as u do changes to the profile (change a nickname, or change a user picture) https://github.com/status-im/status-desktop/issues/2685
