### ISSUE TITLE
integrate SortFilterProxyModel

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2639]
[https://okcerg.github.io/SortFilterProxyModel/](https://okcerg.github.io/SortFilterProxyModel/)

for replacing the sort logic we have in the chat messages as well any list that requires filtering its values (it ends up simplifying the QML a lot)

**Comment by anastasiyaig** [comment]
@richard-ramos please link the issue to relevant PR

**Comment by richard-ramos** [comment]
done!
