### ISSUE TITLE
App start is extremely slow

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2642]
1. install the application
2. run it for the very first time, so you need to pass this macOS security check as well

As a result, the application is starting slow, approximately 15 seconds or so

https://user-images.githubusercontent.com/82375995/120613172-a4747e80-c45e-11eb-9aff-08408bc11d35.mov

**Comment by iurimatias** [comment]
latest build (beta.11) it takes 2 seconds to open
