### ISSUE TITLE
Error execution reverted: ERC721Enumerable: owner index out of bounds when adding a watch-only account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2645]
When adding a watch-only account for the very first time, the following errors appear

`ERR 2021-06-03 14:30:10+03:00 rpc response error                         topics="rpc" tid=3022763 file=core.nim:24 methodName=eth_call payload="[{\"to\":\"0xf852198d0385c4b871e0b91804ecd47c6ba97351\",\"data\":\"0x2f745c59000000000000000000000000f38d2cd3c6ad02dd6f8b68e0a7b2f959819954b60000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"]" result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":3,\"message\":\"execution reverted: ERC721Enumerable: owner index out of bounds\"}}"
`

**Comment by alaibe** [comment]
@anastasiyaig could you help me by providing the steps to reproduce this issue?

**Comment by anastasiyaig** [comment]
@alaibe 

1. create new account
2. settings -> enable wallet
3. click + button
4. select watch only account and add it, for example `0xf38d2cd3c6ad02dd6f8b68e0a7b2f959819954b6`
5. close the modal
6. click the account you just added

The error will appear in console

https://user-images.githubusercontent.com/82375995/125056538-ff7a4080-e0b0-11eb-88e3-c62be5d97659.mov
