### ISSUE TITLE
Error execution reverted when quitting app having pending transaction

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2646]
**Steps:**

1. being on ropsten, add another wallet
2. claim some eth or tokens in simpledapp.eth
3. send a token or ETH to your new account
4. quit the app when the txn is pending

NOTE: it also happens when adding a watch only account, for example `0x101848D5C5bBca18E6b4431eEdF6B95E9ADF82FA`

<img width="1440" alt="Screenshot 2021-06-03 at 14 29 28" src="https://user-images.githubusercontent.com/82375995/120638643-0d68f000-c479-11eb-9569-5d9793f361e8.png">

`ERR 2021-06-03 14:20:32+03:00 rpc response error                         topics="rpc" tid=3015740 file=core.nim:24 methodName=eth_call payload="[{\"to\":\"0xcd520707fc68d153283d518b29ada466f9091ea8\",\"data\":\"0x2f745c59000000000000000000000000f38d2cd3c6ad02dd6f8b68e0a7b2f959819954b60000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"]" result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}"
`

**Comment by saledjenic** [comment]
@anastasiyaig I am not able to reproduce this, in my case when I send a transaction and close the app while the pending transaction bubble is still in progress I don't get any errors, the only what happens is that app becomes busy for a few seconds (while it gets done background jobs most likely) and it is closed well after that, without any errors. So please check if this still is an issue for you?
