### ISSUE TITLE
communities that one left show up again the UI after a time

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2649]
I observed this bug after a time of the app being open

1. leave a community
2. wait X amount of time (dunno how much but few hours max)

result: the community re-appears in the sidebar

**Comment by anastasiyaig** [comment]
is not it the same? https://github.com/status-im/status-desktop/issues/2517 @iurimatias

**Comment by anastasiyaig** [comment]
I was able to reproduce it as well, however without logs on Windows. Community re-appeared in less than 10 minutes. Trying to reproduce on MacOS to have some logs as well

**Comment by anastasiyaig** [comment]
so basically i was able to recreate the issue:

1. create a very new account
2. open public chat (might be not necessary but just in case)
3. create first community
4. create second community
5. leave first community (notice that the community which u left, is still in communities list)
6. wait for a while for the left community to reappear. It usually takes ~ 10 minutes, but may take less


https://user-images.githubusercontent.com/82375995/122017790-f3a9a000-cdca-11eb-86e7-10ba5355dd0e.mov

**Comment by emizzle** [comment]
On step 5, i believe that the community should still appear in the list, because the user can request to join the community again. But maybe it's something that @simonricoo should clarify.
