### ISSUE TITLE
Can't send 0 transaction from wallet

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2652]
0 transactions must be allowed, it is metamask and trustwallet standart

Use case: to get custom tokens i need to send 0 txn to contract `0x101848D5C5bBca18E6b4431eEdF6B95E9ADF82FA` and it is not possible now

<img width="1552" alt="Screenshot 2021-06-04 at 17 21 34" src="https://user-images.githubusercontent.com/82375995/120816378-555f4400-c559-11eb-9c11-90447a7408cc.png">

**Comment by PascalPrecht** [comment]
Based on the use case, I think this can be considered indeed a bug.
This probably needs an update in one of our validators
