### ISSUE TITLE
label Jenkins builds for Linux as tar.gz instead of pkg

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/status-desktop#2662]
![image](https://user-images.githubusercontent.com/194260/121070574-86778880-c794-11eb-8e58-4f7ad0406932.png)

It's a nit, certainly low priority, but notice how `dmg` and `zip` are accurate but `pkg` is not.

**Comment by jakubgs** [comment]
There you go: https://github.com/status-im/github-comment-manager/commit/0dd5915f

![image](https://user-images.githubusercontent.com/2212681/129611250-7fec7d76-e30e-4417-8f4a-353a66723ab1.png)
