### ISSUE TITLE
Long wallet amount should be truncated

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2667]
To reproduce the issue, add `0x81b7e08f65bdf5648606c89998a9cc8164397647` to watch-only account

<img width="1552" alt="Screenshot 2021-06-08 at 16 18 30" src="https://user-images.githubusercontent.com/82375995/121192143-4d631500-c875-11eb-88c2-04281eb02442.png">

**Comment by iurimatias** [comment]
putting this on hold due to upcoming wallet redesign

**Comment by iurimatias** [comment]
no longer on hold, spoke to simon, we should truncate it

**Comment by Khushboo-dev-cpp** [comment]
@simonricoo how exactly do we truncate the value. From the example shown the value -
210,453,690,8061 USD 
should be truncated as 210,453... USD ? something like this?

**Comment by carlfairclough** [comment]
This is one thing that would need to be updated globally, we settled on representing numbers (whether fiat or token) using the following logic:

`2,550,000,000.00 USD` would become `2.55B USD`
`2,550,000.00 USD` would become `2.55M USD`
`2,505,000.00 USD` would become `2.5M USD` (always round down)
`2,505.58 USD` would remain unchanged

There is a separate discussion/task for token decimal places which depends on the user's preferred fiat currency and available price feeds for tokens.
