### ISSUE TITLE
Can't click the links and hashtags in timeline

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2673]
Links and hashtags are not clickable when posted to timeline

<img width="1552" alt="Screenshot 2021-06-09 at 16 38 06" src="https://user-images.githubusercontent.com/82375995/121365413-4dc8e200-c941-11eb-962b-68d93ad1ac83.png">

**Comment by churik** [comment]
still reproducible for me on 0.2.1-beta - closed, but not released?
