### ISSUE TITLE
Can't paste text containing a picture

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2682]
When copypasting text which contains a picture, for instance any wikipedia article to status chat box, the following happens:

1. message is pasted as of being spaces only
2. text is missing
3. picture is missing
4. it is not possible to send such message

https://user-images.githubusercontent.com/82375995/121476157-fffabb00-c9ce-11eb-8da8-13b324962571.mov

**Comment by iurimatias** [comment]
fixed in beta.11
