### ISSUE TITLE
Unread badge (counter) for group chat is not shown when having unread messages and being on another tab

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2683]
**Steps:**

1. create account1 on device1 
2. add account2 from device2 to contacts list
3. as account1 create a group chat with  account2
4. as account2 open any other tab than chats , for example open wallet
5. as account1, send some messages to group chat
6. as account 2, check the unread counter

As result, no unread badge is shown for group chat messages when being on another tab

https://user-images.githubusercontent.com/82375995/121477294-56b4c480-c9d0-11eb-8a2a-ee1036b1cfe8.mov

**Comment by PascalPrecht** [comment]
@anastasiyaig can you still reproduce this on latest master?

**Comment by anastasiyaig** [comment]
there is a little blue dot now when having ureads
