### ISSUE TITLE
Chat preview is not shown after community is created

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2686]
Steps:

1. open a 1x1 chat or a public chat to be shown at the left nav bar
2. create a community
3. open Chats tab (switch from community to Chats)

As result, the chat preview is not shown. U need to switch between chats to make it visible

https://user-images.githubusercontent.com/82375995/121488671-f4fa5780-c9db-11eb-9ac3-45627b6d198f.mov

**Comment by emizzle** [comment]
@anastasiyaig I cannot replicate this on latest master (c0013a0956c2983543ffaf75922b06bebdc80a01). I've tried creating a community from both User A's and User B's perspective. Could you please confirm it is still an issue?

**Comment by anastasiyaig** [comment]
@emizzle ya, please check out the video. So the issue is: when u are having any active (opened) chat on chat page -> at the right half of the screen u can see the messages of this chat. When u create community and then open Chats tab -> none of existing chats are active, so the right half which supposed to show u messages, shows the stub with a phone (which belongs to community as there is no any messages yet)


https://user-images.githubusercontent.com/82375995/122004627-4e3bff80-cdbd-11eb-9de6-d29a7247eee7.mov

**Comment by PascalPrecht** [comment]
I cannot reproduce this either.

**Comment by Serhy** [comment]
I'm able to reproduce it on MacOS Catalina and Status Version: 0.1.0-beta.10 `c0013a0` 
Having one chat in the list list of chats and then creating a community -> there is a chat preview shown (and only way to see chat view with message box again was to restart Status or join another chat)

**Reproduction** for me is:
1) Open Status
2) Create new account (`Generate new keys` -> select username -> create and confirm password)
3) Join any chat (e.g.`#status`)
4) Enable `Communities` option from `Profile` -> `Advanced` -> `Community` toggle button -> submit with click on `I understand`
5) Open Chats view again
6) Click on public chat (so the chat is active now) 
7) Create Community ( `+` -> `Communities` -> `Create community` -> enter valid name and description) -> `Create`)
8) Click on `Chats` button to return back.

**Actual result:** `Share your key or invite` preview is shown. Clicks upon the chat from Chats list has no effect (no messages / message editbox view).

**Comment by anastasiyaig** [comment]
@emizzle could u please link it to the new-ish PR when ready? Thank you
