### ISSUE TITLE
Community invitation is shown only after relogin for the sender in 1 x 1 chat

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2689]
**Steps:**

1. create a community
2. invite some contact to it
3. in 1 x 1 chat of this contact check community invitation

As result, the invitation is not shown, it appears only after relogin

<img width="1440" alt="Screenshot 2021-06-10 at 11 34 53" src="https://user-images.githubusercontent.com/82375995/121522014-5bdc3880-c9fd-11eb-83a4-9a80fba0ebac.png">

**Comment by emizzle** [comment]
@anastasiyaig, I'm not able to replicate this (I'm always able to see the invitation without restarting). Could you please confirm that this is still an issue?

**Comment by anastasiyaig** [comment]
@emizzle yes, it happens when u use + button in the community and Invite members option, not the Add members button

**Comment by emizzle** [comment]
I still cannot replicate this. I've tried with an accepted contact, and a contact that hasn't been accepted yet. Also, I don't see the "Join" invitation bubble, but i see the "View" invitation bubble.

![imgur](https://imgur.com/5VV4qsT.png)

**Comment by anastasiyaig** [comment]
@emizzle indeed, there is a view, something has been changed with this invitations.


https://user-images.githubusercontent.com/82375995/122732742-411f8480-d285-11eb-8d4f-0e5bafc350d6.mov

**Comment by emizzle** [comment]
This is likely related to #2686, a PR for which was closed by @iurimatias, but I'm not sure why.

**Comment by emizzle** [comment]
@anastasiyaig PR for #2686 is https://github.com/status-im/status-desktop/pull/2766. Please let me know if this does not fix the issue.
