### ISSUE TITLE
Pin icon is misplaced 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2690]
![image](https://user-images.githubusercontent.com/82375995/121526725-546b5e00-ca02-11eb-9630-ecb4dea7a46b.png)

Should be like this

![image](https://user-images.githubusercontent.com/82375995/121526869-7fee4880-ca02-11eb-9467-843f560d9098.png)

**Comment by iurimatias** [comment]
has already been fiixed
