### ISSUE TITLE
My profile link is not shown when starting 1x1 chat having someone in contacts

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2707]
There is a difference in mobile and desktop. When starting 1x1 chat, the modal which shows possible contacts, does not have My Profile link which is present on mobile app. However, it was never designed as such on Desktop.

<img width="1440" alt="Screenshot 2021-06-15 at 13 57 23" src="https://user-images.githubusercontent.com/82375995/122041632-d6340080-cde1-11eb-87db-ce05ba053555.png">

@simonricoo do we want to have it aligned the way both platforms have this link ? is there any use case we can do with this link at all ? Maybe just remove it for all?

**Comment by simonricoo** [comment]
Updated our design: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5224%3A2707
<img width="391" alt="Screen Shot 2021-06-18 at 10 56 35" src="https://user-images.githubusercontent.com/52249767/122535439-dae7f700-d023-11eb-983d-51de39679f40.png">

**Comment by simonricoo** [comment]
Expected behaviour-> Open Profile -> My Profile
