### ISSUE TITLE
bug(wallet): "not enough eth for gas" shown on top of custom gas specification

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#2714]
1. Go to wallet
2. Click "send" to send a tx
3. In the first step, select an account with 0 ETH and then enter an address or select a contact to send to
4. Click "continue"
5. Enter a value for ETH in "Asset and Amount"
6. Click "Use custom" to the right of "Priority". This should expand the fields allowing you specify custom gas parameters.
7. Expected result: "not enough eth for gas" should appear below the custom gas specification
8. Actual result: "not enough eth for gas" is shown on top of the custom gas specification
![imgur](https://imgur.com/NmRkQH2.png)

**Comment by iurimatias** [comment]
putting this on hold due to the upcoming wallet redesign

**Comment by iurimatias** [comment]
no longer on hold
