### ISSUE TITLE
Number of block confirmations for transaction is always 9999

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2715]
Number of block confirmations is always 9999, no matter of the actual value on etherscan

1. login and restore some account with funds
2. send 1 stt to a contact
3. go to wallet -> history and click the most recent transaction
4. open etherscan and find this transaction there (copy the wallet address and look up at https://ropsten.etherscan.io/)
5. compare the values of block confirmations in wallet UI and etherscan

<img width="1012" alt="Screenshot 2021-06-16 at 12 51 49" src="https://user-images.githubusercontent.com/82375995/122198258-ad734000-cea1-11eb-8422-04ba5784d785.png">

**Comment by iurimatias** [comment]
putting this on hold due to upcoming wallet redesign
