### ISSUE TITLE
Sign and Send appears for both recipient and sender when sharing the address

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2719]
**Precondition:** either recover account with funds or request roETH / STT in simpledapp.eth

1. Add someone to contacts
2. Open 1x1 chat
3. Click + button at the bottom left
4. click Send transaction
5. Click continue
6. fill in valid amount and click Preview
7. click Request access
8. as recipient click Accept and Share address
9. review the command in both chats
10. sign and send is shown for both recipient and sender, however it should be different, since one person requests and other one -> sends upon request

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=572%3A4520

<img width="1439" alt="Screenshot 2021-06-16 at 11 51 53" src="https://user-images.githubusercontent.com/82375995/122227670-c559bc80-cebf-11eb-9c8b-2752881f4591.png">

**Comment by iurimatias** [comment]
closed in favour of issue #2915 and PR #2914
