### ISSUE TITLE
Accept and Send remains active after the transaction was sent

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2720]
**Precondition:** either recover account with funds or request roETH / STT in simpledapp.eth

1. Add someone to contacts
2. Open 1x1 chat
3. Click + button at the bottom left
4. click Request transaction
5. Click continue
6. fill in valid amount and click Preview
7. click Request 
8. as recipient Click Accept and Send
9. sign with password the transaction
10. click send

**As result:**

requester still see Waiting to accept
sender still see the Accept and Send active

<img width="1439" alt="Screenshot 2021-06-16 at 12 40 06" src="https://user-images.githubusercontent.com/82375995/122229215-3b125800-cec1-11eb-8cc7-873654c58a26.png">

**Comment by iurimatias** [comment]
closed in favour of issue #2915 and PR #2914
