### ISSUE TITLE
Clicking Load More button when having no transactions crashes the app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2725]
1. Create a fresh account
2. Enable wallet
3. Open history
4. Click Load More

https://user-images.githubusercontent.com/82375995/122390408-9eac8c00-cf7a-11eb-859d-2f8bd2d54747.mov

`DBG 2021-06-17 14:38:09+03:00 callPrivateRPC                             topics="rpc" tid=6779906 file=core.nim:20 rpc_method=wakuext_updateMailservers
Object 0x7fb31e8b0320 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/app/AppLayouts/Wallet/HistoryTab.qml:264: function() { [native code] }
Traceback (most recent call last)
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(220) nim_status_client
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(162) mainProc
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGABRT: Abnormal termination.
`

**Comment by emizzle** [comment]
@anastasiyaig is this still an issue for you in the latest master? I cannot reproduce a crash, I can only see a QML error in the logs (which I can easily fix).

**Comment by anastasiyaig** [comment]
@emizzle correct, the crash is gone, the error in console is still there

`DBG 2021-07-06 10:41:06+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=6281470 file=model.nim:186
qrc:/app/AppLayouts/Wallet/WalletLayout.qml:113: TypeError: Property 'checkIfHistoryIsBeingFetched' of object HistoryTab_QMLTYPE_503(0x7fed35da2710) is not a function`
