### ISSUE TITLE
Add Delete to community channels

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2734]
In terms of Edit channels feature, there should be a Delete channel functionality that was not implemented yet

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5203%3A43695

![image](https://user-images.githubusercontent.com/82375995/122577904-0555a680-d05c-11eb-8c09-91fd50864a7f.png)

**Comment by pback34** [comment]
The delete channel feature does not exist as far as i can tell - why is this issue closed? No sign of this feature in Android or Linux Desktop.
