### ISSUE TITLE
Add Account modal is not being closed when clicking Add Account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2752]
1. create an account
2. enable wallet
3. click + button -> generate an account

`qrc:/app/AppLayouts/Wallet/components/AddAccount.qml:16: TypeError: Cannot call method 'rowCount' of undefined`

<img width="1344" alt="Screenshot 2021-06-23 at 15 36 11" src="https://user-images.githubusercontent.com/82375995/123097428-cf883780-d438-11eb-8c32-a6b5fe03540f.png">

**Comment by iurimatias** [comment]
putting this on hold due to upcoming wallet redesign
