### ISSUE TITLE
Various small UI bugs during the onboarding

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2762]
![Screen_Shot_2021-06-23_at_15_31_04](https://user-images.githubusercontent.com/52249767/123240420-960b0700-d4e0-11eb-87f2-a4c24cc87849.png)
<img width="550" alt="Screen_Shot_2021-06-23_at_15_31_17" src="https://user-images.githubusercontent.com/52249767/123240476-a15e3280-d4e0-11eb-898a-c923dd62a9a3.png">
<img width="780" alt="Screen_Shot_2021-06-23_at_15_31_23" src="https://user-images.githubusercontent.com/52249767/123240609-baff7a00-d4e0-11eb-8b61-321213ca9963.png">

**Comment by alexandraB99** [comment]
@simonricoo could you elaborate a bit more with providing some design references? I don't know what the arrow supposed to be in the first image or what color should the loading icon have. I am looking in Figma for it with no success :/

**Comment by simonricoo** [comment]
Hey, our Designs are on light mode only so Im going to point you to the right design on the light mode / components

1 image - the arrow should be blue (dark mode blue)https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=771%3A57
2 image - (Paswords don't match not paswords-don-t-match) https://www.figma.com/file/BTS422M9AkvWjfRrXED3WC/%F0%9F%91%8B-Onboarding%E2%8E%9CDesktop?node-id=588%3A12615
3 image - Wrong colors on loading state on both light and dark mode, https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1029%3A5340

**Comment by PascalPrecht** [comment]
1) and 3) are already handled in StatusQ (that particular view just doesn't use any of StatusQ's components yet. So for those cases it's just a matter of replacing them with StatusQ controls.

As for 2) this should be solved by running our i18n scripts.
