### ISSUE TITLE
[Windows] Clicking notification for 1x1 chat from notification center does not open the app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2768]
1. install any build to windows and create account there
2. install a build to mobile and create account there
3. add both to contacts
4. collapse the windows app 
5. from mobile -> send a message to 1x1 chat
6. on windows do not click push notification (close it)
7. open notification center and click the notification from there

https://user-images.githubusercontent.com/82375995/123476835-e465f600-d605-11eb-9d8e-683223481997.mov

**Comment by pinebit** [comment]
@iurimatias @anastasiyaig 
Here is my research on this topic.

1. Currently we are making toasts via SystemTrayIcon component, which in turn uses `Shell_NotifyIcon` WINAPI. This method is designed to show intermediate toast on the system tray icon and it is not meant to interact with Windows "Action Center".
https://code.woboq.org/qt5/qtbase/src/plugins/platforms/windows/qwindowssystemtrayicon.cpp.html#291

2. In previous projects we used 3rdparty library called SnoreNotify with SnoreToast backend (plugin) that essentially did the same as 1. and has the same effect described in this ticket.
https://github.com/TheOneRing/Snoretoast

3. The proper way of integration with Windows "Action Center" is to follow thes guidelines:
https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl
https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/toast-desktop-apps
which is not trivial, requires the installer to register COM, add app shortcut, the app must accept command line arguments, etc. 
Obviously we cannot do that from QML and probably not from NIM. Therefore a bit of C++ or C# would be required.

4. If you check, for instance, how Telegram does it:
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/win/windows_app_user_model_id.cpp
it follows the approach described in 3, and it manages all COM and app shortcut stuff in runtime by patching Windows Registry.
Also, notice how they implemented this for different platforms: Linux, Mac and Windows. One this thing deserves a dedicated project...

To me the only proper way to show toasts is to clone Telegram's implementation, express it in NIM(?) or introduce a C++ library that will be linked to NIM client. I do not see an easy-to-do workaround that can be done quickly in one day and make this thing magically working. Cloning Telegram's behavior would be an epic IMO, unless we find a 3rdparty library for C++/NIM that implemented that already in a cross-platform way.

What's your take on this? Let's take it to Discord to discuss.

**Comment by iurimatias** [comment]
thanks for the detailed finding sin the ticket. Given the reward/effort for seems low, specially compared to other things we can do instead, I think we should push this issue back, mark is as a feature, and do it at some point later, it does seem this feature needs other things done first in the meanwhile anyway such as the installer etc..

**Comment by iurimatias** [comment]
closed in favour of #2996
