### ISSUE TITLE
[Windows] Chat timestamp appears with every message

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2769]
<img width="1440" alt="Screenshot 2021-06-25 at 22 29 46" src="https://user-images.githubusercontent.com/82375995/123477489-ce0c6a00-d606-11eb-8a38-9707ba1f2d57.png">

**Comment by iurimatias** [comment]
@anastasiyaig does this happen to you on windows still on latest master?

**Comment by anastasiyaig** [comment]
it was fixed in one of recent PRs
