### ISSUE TITLE
Crash when clicking notification with mention

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2819]
Mentioning someone in community channel and clicking the notification as recipient crashes the app

https://user-images.githubusercontent.com/82375995/124781420-0dfb1780-df4c-11eb-97ff-a9a1c9f40497.mov

`Traceback (most recent call last)
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(220) nim_status_client
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(217) mainProc
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qapplication.nim(8) exec
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(572) onSlotCalled
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/app/chat/views/channel.nim(150) setActiveChannel
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/app/chat/views/chat_item.nim(33) setChatItem
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
`

**Comment by saledjenic** [comment]
I checked this and yes, crash is happening not only when you click on a notification bubble with mentions, but on any chat notification.

The current implementation does this: 
- user clicks notification bubble
- the app changes the section calling appMain.changeAppSection(Constants.chat), and that sets the first channel as active one
- the app tries to find ChatView for chat id stored in qml as currentNotificationChatId (whatever bubble is clicked), but cannot find it empty ChatView is returned from getChannelById called from setActiveChannel proc in ChannelView and app crashes

All in all general flow is not good here. The proper way for this is to have community id and chat id set for each notification bubble (or notification bubble id, but in that case we need to maintain list of them which bubble id points to what) and when user clicks a bubble to send those two params and they will uniquely define what we need to do in the app.

That is not possible to do using SystemTrayIcon qml component, as the only signal it provides for handling click on notification bubble is messageClicked without any additional params. Also SystemTrayIcon qml component doesn't maintain any list of displayed notifications. 

How this can be solved:
- handling this in a native code 
- updating qt source by adding title/message, and use our custom build from now on
- wait to switch to Qt 5.15+ version and try with Notification QML Type, ( https://doc.qt.io/QtApplicationManager/qml-qtapplicationmanager-notification.html#details )

@iurimatias what do you suggest on this?

**Comment by jrainville** [comment]
It's not my call, but I'd say that for now, we should start by just fixing the crash.
The notification issue of not opening the right channel has been known for a while, so we can endure it some more, but the crash is pretty recent and should be fixed IMO.

**Comment by saledjenic** [comment]
@jrainville the only we can do is just displaying the app as the top most window when someone clicks a bubble notification, cause we don't have appropriate information for displaying any particular channel.
