### ISSUE TITLE
Accepting contact request crashes the app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2837]
`Traceback (most recent call last)
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(220) nim_status_client
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(217) mainProc
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qapplication.nim(8) exec
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(578) onSlotCalled
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/app/chat/views/channel.nim(187) joinPrivateChat
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/app/chat/views/channel.nim(150) setActiveChannel
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/app/chat/views/chat_item.nim(33) setChatItem
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
`

**Comment by anastasiyaig** [comment]
i am not sure 100% how to reproduce it, maybe it depends on the timestamp of contact request (too old)

**Comment by anastasiyaig** [comment]
i see it now how to reproduce

https://images.zenhubusercontent.com/261270348/4e091850-0366-4f01-818a-1da4195019c2/screen_recording_2021_07_09_at_10_54_46.mov

**Comment by pinebit** [comment]
channel.nim:149
I think we should add a check for `selectedChannel` here:
```
    let selectedChannel = self.getChannelById(channel)
    self.activeChannel.setChatItem(selectedChannel)
```
