### ISSUE TITLE
Update options for a message in Pinned messages modal

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2840]
As discussed with @simonricoo and @errorists , the possible list of actions for messages in Pinned messages modal should be limited to:

1. Unpin (the permissions should not be changed -> only admin can unpin in community channels and participants can unpin in 1x1 chat)
2. Jump to (should redirect to the pinned message itself when selected)

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4161%3A0

![image](https://user-images.githubusercontent.com/82375995/124892139-46e5cb80-dfe2-11eb-824a-bb89479135de.png)

**Comment by anastasiyaig** [comment]
I am reopening the issue to limit the list of options as stated in initial description. Current picture:

<img width="1344" alt="Screenshot 2021-07-30 at 12 37 03" src="https://user-images.githubusercontent.com/82375995/127650019-1fc8d3e8-7b5c-4cb4-8851-f933ea2aa41a.png">

**Comment by pinebit** [comment]
@anastasiyaig fixed this in the new linked branch.
