### ISSUE TITLE
Navigating from Chats to Timeline shows wrong messages

### ISSUE THREAD

**Issue by pinebit** [status-im/status-desktop#2845]
Steps:
1. Open a chat.
2. Click Timeline icon
3. See the messages displayed from the chat (step 1), not from Timeline
4. Navigate to Profile/Browser/whatever, but Chat
5. Navigate to Timeline
6. See the correct messages (from timeline) are displayed

**Comment by anastasiyaig** [comment]
More details are posted here: https://github.com/status-im/status-desktop/pull/2844#issuecomment-877020416
