### ISSUE TITLE
Fetch more messages functionality is gone in public chats

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2856]
`Fetch more messages` is missing now. It should be present across the chats (1x1, public chat, group chat, community channel)

![image](https://user-images.githubusercontent.com/82375995/124922141-e070a580-e001-11eb-951d-2e1390f42209.png)

<img width="1012" alt="Screenshot 2021-07-08 at 15 34 07" src="https://user-images.githubusercontent.com/82375995/124922282-05651880-e002-11eb-8d44-e86c3fd5f903.png">

**Comment by iurimatias** [comment]
reopening as I'm seeing this issue on master

**Comment by simonricoo** [comment]
specified in DMs
