### ISSUE TITLE
Can't jump to new messages by clicking arrow button

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2874]
When having a long chat history and reading it from the beginning, i want to be able to jump to the end of it by clicking arrow button which is shown at the left side. Clicking this button however does not redirect me to the last message. Instead, error is shown in console:

`qrc:/app/AppLayouts/Chat/ChatColumn/ChatMessages.qml:121: Error: Cannot assign to non-existent property "newMessages"`

https://user-images.githubusercontent.com/82375995/125258953-83c60100-e307-11eb-90d8-1061ff290901.mov

**Version:** 0.1.0-beta.10

**Comment by pinebit** [comment]
This is fixed in one of the recent PRs.
