### ISSUE TITLE
Message count badge in chat view only disappears after switching to different views

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2878]
Something I ran into while working on #2869. Here's what happens:

Assuming you're part of a bunch of chats, doesn't matter if public channels or one on one chats, if there are mentions in any of the chats, the message count badge is correctly shown for individual items. However, when activating any of the chats, the badge count persists, while it should actually go away (as mentions could then be considered as "read").

They only disappear after the user switches to a different view (e.g. a community or settings).

It seems we're not signalling correctly the clearance of the counter.

**Comment by iurimatias** [comment]
I believe this has been fixed, need to confirm

**Comment by iurimatias** [comment]
this counter currently is counting the number of contact requests NOT messages, it seems that's the intended behaviour now, if not we should reopen this

**Comment by PascalPrecht** [comment]
> this counter currently is counting the number of contact requests NOT messages

Not sure what you're referring to here, but the message badge counter of the chat tab button correctly counts 1-on-1 messages + mentions + contact requests.

The message badge counter on chat list items correctly counts 1-on-1 messages and mentions.

I've just tested the again, and it seems that the badge counter in the chat tab button is now correctly reset when activating chat list items that have a badge count.

So this issue can indeed be closed.
