### ISSUE TITLE
Markdown issue when using `

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#2920]
Weird stuff happens when using this markdown symbol ` for text formatting. When using a space after the 2nd symbol to close the formatting, the 2nd symbol gets removed. In case of a line break including text that followed the symbol https://www.loom.com/share/12086d855c85459686cac5eb4bf22492

### Current
` seems supported, but when used the issue occurs that text is removed

### Expected
` is not supported or can be used without text being removed when using space or when the symbol is used after a line break

**Comment by alexandraB99** [comment]
This missbehavior is caused because of `formatInputMessage()` function which is called in _StatusChatInput.qml_ in line **321** since it falls into the _Key_QuoteLeft_ condition. As I have no idea about the background of why this function was in general introduced, I am not sure whether I shall just remove that function or try fixing it. If the latter, I would need specs on how exactly should the text input behave in all cases (eg when ` is inserted, etc). @PascalPrecht since git blames you, would you have any input on this?

**Comment by PascalPrecht** [comment]
@alexandraB99 Yea, that whole thing is somewhat of a beast. Feel free to remove that function entirely if it makes things easier for you. I wouldn't be surprised if there's some things relying on that but that shouldn't stop of from replacing it with something better that actually works.

re: behaviour: I think generally the input should behave somewhat like the input does on Discord. Usually that's a very good reference.

**Comment by jrainville** [comment]
@alexandraB99 I wouldn't remove the whole function completely, as that would remove the formatting of all the other types (bold, italic, etc).

I do  agree with Pascal though that the whole formatting is very complex. So if you feel like you can improve anything there, feel free to do so.

Basically, how it works is that we do a regex (right now on the Nim side), to see if something was wrapped with a special character, `*` for italic, `**` for bold and  (\`) for code. If the regex spots something that is wrapped, it returns the position in the string to replace that with the tags, `<code>` for example.

In this issue, it seems like the `code` regex might be misbehaving. You can check the regex on the Nim side in format_input.nim at line 58

Let me know if you have other questions

**Comment by alexandraB99** [comment]
@jrainville we discussed with @iurimatias, @PascalPrecht and @borismelnik and agreed that we'd push this task back for now as it requires more refactoring and it doesn't seem as a simple fix. In this case we would temporarily remove the formatting.

**Comment by jrainville** [comment]
Sounds good. I do agree that the formatting is very complex and we indeed have had issues with it for a while. 

I don't mind removing it for now, since it's only a small UI feature for the Input. Even  if the formatting is not there in the input, it still works for the chat messages in the list.

**Comment by alexandraB99** [comment]
PR created
