### ISSUE TITLE
support enabling an empty bloom filter

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2927]
The goal here is to expose some settings in status-go so it's possible to configure the desktop node as a full node.

This builds on top of #2877 , so instead of a toggle we want now a slider or drop down menu with 3 options ( we can think about the exact wording for this later)

- light node - bloom filter disabled
- normal node - bloom filter enabled
- full node - uses an empty bloom filter so all messages are forwarded

**Comment by oskarth** [comment]
FWIW there's no bloom filter in Waku v2, might make sense to prioritize exposing Waku v2 as a full node instead? Wrt what protocols it supports, which messages it stores etc

**Comment by iurimatias** [comment]
task done
