### ISSUE TITLE
[Windows] Deinstalling the .exe app does not remove shortcuts / task bar pins

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2929]
1. install the app to windows with .exe
2. create a shortcut for it on desktop
3. pin the app to task bar
4. deinstall the app

As result, shortcut and pin are not removed while the application itself is deleted

<img width="1440" alt="Screenshot 2021-07-15 at 17 30 28" src="https://user-images.githubusercontent.com/82375995/125805839-3bacd2e0-ea29-4d7d-9895-62a99ec175f2.png">

**Comment by pinebit** [comment]
@anastasiyaig I created a PR for this issue, but we cannot fix "pin/unpin" issue.
Microsoft made it impossible to pin/unpin items to/from taskbar programmatically. Only fileexplorer.exe process is allowed to do this. Therefore, we cannot automatically unpin Status from taskbar in case a user has it pinned. This is true for the recent Windows 10 versions and I did not want to enable this feature for older Windows version, except for Windows 10 2021.

The new features I added:
1. Creates program group (start menu) with Launch Status link and Uninstall Status link.
2. Adds "Launch Status" option when installation is finished.
3. Uninstall shall remove everything from the user machine (as long as the application was not running in background).
