### ISSUE TITLE
implement search results for communities, channels

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2934]
the search results here would be grouped into
- matched communities
- matched chat names
- matched community channels
- matched messages

see https://github.com/status-im/StatusQ/issues/264

this needs to be implemented in status-go as well

**Comment by iurimatias** [comment]
to be integrated with UI component https://github.com/status-im/StatusQ/issues/264

**Comment by saledjenic** [comment]
@iurimatias discussing with designers a requests for this ticket by [this design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=6042%3A1) are:

1. both searches the one on the left side (above chat list) and the one on the right side (magnifier icon) should open same modal for the search
2. selecting a location (where to search) and entering a phrase should search for community, chats, channels and messages in a way:
2.1 Communities, channels, chats - case insensitive search, where name must start with the entered phrase (when you type "c" or "C" you will see only **C**ore, **C**ore-ui and **C**ommunities-phase3, but not the status-**c**ore)
2.2 Messages - case insensitive search, contains entered phrase

**Comment by saledjenic** [comment]
@PascalPrecht as we discussed earlier, messages' time need to be handled on the side of qml, the same way we have that for messages now (including tooltip).
