### ISSUE TITLE
`joinedCommunities` doesn't seem to update underlying community models in the view

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2972]
We're using `chatsModel.communities.joinedCommunities` to render community tab buttons in the navigation bar:

<img width="88" alt="Screenshot 2021-07-20 at 11 21 11" src="https://user-images.githubusercontent.com/445106/126296413-d2fd7148-3476-492b-a5eb-f3eebe2172ee.png">

There's some logic applied to these buttons so that they render a badge when there's `unviewedMessagesCount > 0 `. It should render the same badge as seen on the chat tab button (a badge without a value, but still a visible badge).

It seems that the underlying `Community` data attached to `joinedCommunities` isn't updated in realtime. I've noticed this when I added a membership request to one of my communities. While the membership request does show up in the community view, inside `AppMain` where we access community data via `joinedCommunities`, the request count is still `0`.

**Notice that there's no data access implemented for `membershipRequests` in `CommunityList` yet, but I've done it locally to verify this ill behaviour**.

Expected behaviour:

1. Community tab buttons should show a badge without value when there's unviewed/read messages in any of the community channels that aren't muted (same logic as done in main chat view)
2. badge should show count value for membership requests (similar to contact requests in chat view)
3. Badge should render count of mentions (+ pending membership requests) if there are any in any of the channels of the community
4. Badge disappears while community is active **unless there's a count in there** (again, same behaviour as chat view badge)

**Comment by iurimatias** [comment]
note: need to check if this is still happening

**Comment by iurimatias** [comment]
so the badge indicator shows but not the counter
