### ISSUE TITLE
Category validation message is misplaced

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2973]
1. create a community
2. click create a category
3. enter a name of category and delete it

`qrc:/shared/Input.qml:175:5: QML QQuickTextEdit: Cannot anchor to an item that isn't a parent or sibling.
QString::arg: Argument missing: you-need-to-enter-a--1, category name`

<img width="1012" alt="Screenshot 2021-07-20 at 12 39 55" src="https://user-images.githubusercontent.com/82375995/126300184-1ebc18ef-c496-40ed-8a8e-297df57b386c.png">

**Comment by anastasiyaig** [comment]
@simonricoo would be nice to approve / suggest the error message here as well

**Comment by simonricoo** [comment]
You can find this in the new input field component :) I believe it will be soon finished in the StatusQ.
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1750%3A8516

**Comment by PascalPrecht** [comment]
FYI: we only have a super basic input so far with no knowledge about validation etc. but will focus on that soon. For now we have to fix this in the components that live inside Desktop
