### ISSUE TITLE
Various issues on text formatting

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2977]
Issue 1
when i highlight text and set it to bold it results in: boboldld**
https://user-images.githubusercontent.com/52249767/126315426-9dbc85c3-eb3f-4be6-88c3-3124030c2dbc.mov

Issue 2
Shortcuts like CMD+B, CMD+I etc doestn work. List of shortcuts here: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4358%3A43335

**Comment by iurimatias** [comment]
closing in favour of #3063 although can't replicate issue 1 right now, and issue 2 is a duplicate, it happens due to selecting with mouse vs selecting with keyboard
