### ISSUE TITLE
Undefined when creating community channel

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2981]
<img width="1552" alt="Screenshot 2021-07-20 at 17 51 27" src="https://user-images.githubusercontent.com/82375995/126345600-26224ae5-e184-4cff-9c4e-d107bdbce730.png">

**Comment by PascalPrecht** [comment]
This was fixed in https://github.com/status-im/status-desktop/commit/4213f953e07bbbebc0d5fff55525fc6586b1b1d3#diff-3c65a0e9828319b1651e47defc9d7b1a451fc8e44a32011e2fe97f97266bd593L34
