### ISSUE TITLE
Timestamp appears after each message in community channel, also Fetch messages as well

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2992]
<img width="1552" alt="Screenshot 2021-07-21 at 09 42 56" src="https://user-images.githubusercontent.com/82375995/126443509-f96f49a3-ce2d-4c08-a458-d2be1bc34a10.png">

![image](https://user-images.githubusercontent.com/82375995/126443595-79c9e70a-c50a-47db-8b5d-137ac15c5945.png)

**Comment by jrainville** [comment]
I was able to reproduce with these steps:
1. have a community with one channel.
2. Type a couple of messages in that channel
3. Create a new channel in the community
4. Go back to the original channel
-> bug appears
