### ISSUE TITLE
Clicking push notification does expand the app but does not open correct channel / chat

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2996]
1. having device A, create community with a channel
2. having device B, add device A to contacts
3. as device A, add device B to community members
4. as device B, hide the app
5. as device A, send a message to community channel (reply on something, or mention)
6. as device B, receive PN and click it

As result, clicking the notification does expand the app , but does not redirect to a particular message and does not open certain chat

<img width="1440" alt="Screenshot 2021-07-21 at 11 00 02" src="https://user-images.githubusercontent.com/82375995/126453647-f1f15cda-ea26-43e7-98f1-922df54a7012.png">

**Comment by iurimatias** [comment]
@saledjenic what does it mean to handling this in native code, handling in Nim and/or on the Dotherside?

**Comment by saledjenic** [comment]
> @saledjenic what does it mean to handling this in native code, handling in Nim and/or on the Dotherside?

I meant that we should do it in Xcode for MacOs, so for each platform in a platform specific way.
