### ISSUE TITLE
Delete category button is misplaced

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3013]
1. create a community
2. add a category there
3. click 3 dots for category -> edit

https://user-images.githubusercontent.com/82375995/126555049-bde9d8f5-7ba4-4466-96e2-05101e734ac5.mov

<img width="481" alt="Screenshot 2021-07-21 at 23 24 44" src="https://user-images.githubusercontent.com/82375995/126555200-635127d4-7ffb-4da9-a245-b9dddd27f266.png">

**Comment by PascalPrecht** [comment]
Bunch of things going sideways here... @anastasiyaig can you try again with this PR: https://github.com/status-im/status-desktop/pull/3020
