### ISSUE TITLE
Editing community channel kicks it out from the category

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3015]
1. create a community
2. create a category there
3. create a channel in this category
4. click more -> edit channel -> update channel description and save

As result, the channel does not belong to category anymore

https://user-images.githubusercontent.com/82375995/126559181-83ba219c-e211-49fb-9cd0-a0954c3ff01e.mov

**Comment by PascalPrecht** [comment]
@anastasiyaig this is fixed with #3023
