### ISSUE TITLE
Replies to your own messages are not shown after the restart of the app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3016]
1. having a community channel send some messages
2. reply to some of your own messages
3. reply to someone else's messages
4. quit and close and open the app again

Replies , that were done to your own messages, are not shown as such after restart. To fix this u need to switch to Chats tab and then back to Community channel

<img width="1071" alt="Screenshot 2021-07-22 at 10 30 15" src="https://user-images.githubusercontent.com/82375995/126603846-6064f799-f896-46af-985a-da5d43d76f92.png">

<img width="1096" alt="Screenshot 2021-07-22 at 10 32 11" src="https://user-images.githubusercontent.com/82375995/126603946-63d7b460-0733-4ec2-bd1f-de2b7e72f979.png">

**Comment by alaibe** [comment]
@anastasiyaig  Can you reproduce this one consistently? I think I am only able to reproduce when leaving the app open for sometime. Then everything seems messed up

**Comment by anastasiyaig** [comment]
i was able to reproduce it with the restart but i am pretty sure leaving the app IDLE will produce a mess as well (replies are not rendering) . I need to dig more on that

**Comment by iurimatias** [comment]
fixed by #3033
