### ISSUE TITLE
Channel history is not shown when upgrading the app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3022]
- Having build A (lets say master from 21 July), create a community 
- Create a channel and send a reasonable amount of messages
- Wait for next day
- Delete the app (but not the data folder)
- Having a build B (master from July 22), install the build
- Login and open same community channel
- Send some messages there

As result, only new messages are shown. Old messages (history) is not shown. To fix it u need to restart the app

**Comment by pinebit** [comment]
@anastasiyaig I cannot reproduce this on the latest master (commit 39dace238bf5745782a26b4193b430f28c8f0260).
I think this may be due to many other fixes we did over the last week.
Can you please try reproducing this again and let me know if the issue is still there?
