### ISSUE TITLE
clicking unfurling 'Enable in Settings' should direct to the privacy & security section not just the profile section

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3043]
1. post a url in the chat
2. click 'Enable in the settings'

expected result: it should open the "privacy & security" section of the profile section
actual: it opens the profile section

<img width="371" alt="Screen Shot 2021-07-23 at 5 41 44 PM" src="https://user-images.githubusercontent.com/176720/126844413-7e004e46-90c2-4134-9c88-9660d1658e0c.png">

**Comment by iurimatias** [comment]
similar to https://github.com/status-im/status-desktop/pull/3107

**Comment by saledjenic** [comment]
@anastasiyaig please check this, I checked it in the latest master and clicking "Enable in Settings" points me always to tab "Privacy and security" form profile settings.

**Comment by anastasiyaig** [comment]
it works to me as well
