### ISSUE TITLE
creating a channel resets the colors of other channels until they are clicked

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3044]
https://images.zenhubusercontent.com/261270348/b2322204-1404-4c0a-b8dd-33237036f4a3/screen_recording_2021_07_23_at_6_43_51_pm.mov

**Comment by iurimatias** [comment]
possiblly fixed by #2995 related to issue #2826

**Comment by pinebit** [comment]
Fixed by #2995
