### ISSUE TITLE
blocking a contact, changes the existing chat to the mutual contacts warning

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3047]
This is partially a bug, partially an undefined behaviour, steps are:

1. open a chat with an existing contact
2. block that contact
3. open the 1 on 1 chat again

result: it shows "you need to be mutual contacts with this person.. etc.." message
expected result: unclear but either 1) that chat should be removed or 2) the message shown should be instead "youo have blocked this user", we should clarify with @simonricoo

**Comment by alaibe** [comment]
@simonricoo what is your opinion here. Note that currently it is only possible to open the chat via the blocked contact popup, maybe we should just blocked that action. That would be impossible to have a chat with a blocked contact that way

**Comment by simonricoo** [comment]
When you block a contact, you should stay a contact with that user. However, you should not be able to send messages. You can still scroll through the message history though, access pinned chats and search chat. Created a screen for that scenario.
<img width="1054" alt="Screen Shot 2021-08-09 at 10 55 00" src="https://user-images.githubusercontent.com/52249767/128682002-119cf7c8-0586-476e-88fc-15e1b0bbe47e.png">

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=7831%3A48348

**Comment by alaibe** [comment]
Is it a new behaviour, from looking at the current code, it seems that when blocking a contact:
we execute this code: https://github.com/status-im/status-go/blob/develop/protocol/message_persistence.go#L1207
which does:
// BlockContact updates a contact, deletes all the messages and 1-to-1 chat, updates the unread messages count and returns a map with the new count

Could you confirm we want to change this behaviour as this will have an impact on mobile too I'd image

Adding @cammellos for context

**Comment by cammellos** [comment]
Thanks @alaibe for adding me to the conversation,

yes, the behavior on mobile is to completely remove the user and all their messages etc.

The reason is that it happened in the past that they would send messages that would crash the app for example, so deleting the messages etc recovers from that scenario.

Though we could just pass a boolean flag to the api (or a different endpoint etc), where no deletion happens, we just block it as described above, so we can keep both behaviors (unless we want to be consistent), we could also provide users an option "Block and delete all messages, Block" for example, but I am not UX guy.
What do you think?

**Comment by alaibe** [comment]
As far as I can tell, so far we tried to keep in sync behaviour between mobile/desktop. That seems to make sense to me to keep it that way right?

@cammellos can you open a chat with a blocked contact?
Maybe we could start by keeping in sync behaviour of desktop with mobile and as a second step, improve the behaviour with what @simonricoo is suggesting?

Thoughts?

**Comment by alaibe** [comment]
Discussed offline with Simon, I will update to Simon suggestion on desktop. Also regarding the API we only need to add the systemTags as we don't delete chat/message. So I will pass a flag to the status-go API.

@hesterbruikman @cammellos Can I leave it to you for updating the mobile side according to the new description. The API will be backward compatible (with a flag)

**Comment by hesterbruikman** [comment]
One thing I'd like to understand is what happens if a message contains spam that crashes the app and the chat is not deleted. (But chat key is blocked)

- Can messages that are already fetched and rendered still crash the app?
- If yes, how can this be mitigated?

**Comment by alaibe** [comment]
@hesterbruikman you can see on desktop the PR attached, it seems that the app doesn't crash (at least desktop one) when receiving message from a blocked contact
