### ISSUE TITLE
gas amount limit should not accept decimal values

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3048]
1. attempt to buy stickers
2. choose custom gas values
3. input `0.1`

actual result: the input field seems ok with this
expected result: it should validate this and not accept it

bonus: we should make sure the QML endpoint also does not accept decimals for the gas limit

![Screen Shot 2021-07-24 at 6.23.47 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/f99cab0c-1f00-4a01-ac87-74c23409fd4a)

**Comment by alaibe** [comment]
@iurimatias what do you mean by:
> bonus: we should make sure the QML endpoint also does not accept decimals for the gas limit

do you refer to the input per-gas overall limit?

I thought gwei wasn't the lowest decimal and as such floating point number should be accepted?

**Comment by iurimatias** [comment]
@alaibe I mean that, even if the QML does not validate this, the backend should not allow it or should crash/throw an exception etc.. anything rather than cause some weird transaction behaviour to go through
