### ISSUE TITLE
community user search& invite workflow / UI needs review

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3053]
This functionality works, but the UI looks strange, we should review the designs to see if it's implemented properly

1. in a community click "add members"
2. search for an ens name

now clicking on a user in the list sends an invite, but note there is an invite button here in the first place that doesn't do anything, it probably need checks check boxes similar to the group member list invite

![Screen Shot 2021-07-24 at 7.17.47 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/e54de0b2-3ffa-4835-99f7-1c06142ba65a)

**Comment by iurimatias** [comment]
so in fact, it's the search results that are missing the checkbox

**Comment by PascalPrecht** [comment]
Correct, this is using a component that encaspulates contacts and contact search results. The component is used in different places in the application and has not been touched during the modal refactor. Chances we need to break it depending on its flexibility.
