### ISSUE TITLE
history tab not loading history for a watch only account

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3055]
so I added this account (random account found on etherscan with cryptokitties) `0x2ff1e192a07791b17346c158b507af10acf5a53f` and added it as a watch only account, then go to the history tab, result it shows no history found, but this account does have a bunch of transactions https://etherscan.io/address/0x2ff1e192a07791b17346c158b507af10acf5a53f

![Screen Shot 2021-07-24 at 7.33.56 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/a454cb4a-5341-4d10-969f-2dbe69b3f400)

**Comment by anastasiyaig** [comment]
@iurimatias i see the history in last master but the scrolling is way slow:

<img width="1440" alt="Screenshot 2021-07-26 at 16 27 07" src="https://user-images.githubusercontent.com/82375995/126996561-445d9d6e-2dc6-4e05-a855-10b512bc73b2.png">
