### ISSUE TITLE
Message search results are overlapping each other when searching more than 1 time

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#3059]
1. open a status-desktop public channel
2. search for W
3. search for D

<img width="721" alt="Screenshot 2021-07-26 at 13 27 01" src="https://user-images.githubusercontent.com/445106/126981620-9cd3cfd1-d068-4b1b-b5aa-2f2831941799.png">
<img width="703" alt="Screenshot 2021-07-26 at 13 28 10" src="https://user-images.githubusercontent.com/445106/126981712-eb875b09-487a-4123-a1e5-84b10227868c.png">

`DBG 2021-07-26 16:07:54+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=11004921 file=model.nim:196
qrc:/app/AppLayouts/Chat/ChatColumn/MessageComponents/CompactMessage.qml:255:13: QML ChatText: Binding loop detected for property "implicitHeight"`

Haven't investigated yet why that is, just wanted to make sure we don't lose this.

**Comment by anastasiyaig** [comment]
it happens when searching more than 1 time i guess, so searching for W and then for D results in glitches

**Comment by PascalPrecht** [comment]
Not sure what you mean by that, but for me the opposite is true. I can search for e.g. "D" get results, then backspace + some other letter, and I get results as well.

I believe this is related to particular message(s) (types) but could be wrong

**Comment by jrainville** [comment]
I had tat issue when implementing the search. The way I could reproduce was by searching something, like "W", wait for results, erase, wait for the list to go out, then search again.

I had fixed it in my PR by switching the default message type if I recall corectly.

Maybe the fixed was reversed or maybe there is something else, because you seem to have seen a binding loop warning, which I didn't have back then.

**Comment by iurimatias** [comment]
@PascalPrecht @anastasiyaig I cannot replicate this at all on latest master, see video above, any objections to closing this issue?

https://images.zenhubusercontent.com/261270348/fd7716bc-403e-463c-a119-33199c4c56b9/screen_recording_2021_07_26_at_3_29_37_pm.mov

**Comment by PascalPrecht** [comment]
Can't replicate either anymore.. closing this!
