### ISSUE TITLE
Mentions suggestions are not shown when editing a message

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3072]
1. having any chat, send a message there
2. hover the message and click edit button
3. enter @ character to mention someone

As result, no mention suggestions are shown

<img width="1552" alt="Screenshot 2021-07-27 at 13 18 32" src="https://user-images.githubusercontent.com/82375995/127138186-7836abca-8542-438c-a6ce-ae8445f7fbe4.png">

**Comment by iurimatias** [comment]
this one is more of a new feature than a bug
