### ISSUE TITLE
Persist application window state / geometry

### ISSUE THREAD

**Issue by pinebit** [status-im/status-desktop#3073]
I have 4K screen with 250% scale factor set in display settings (Windows OS).
This makes the default window size to span beyond the desktop area. I had to resize the window (make it smaller) or maximize it.
In any case after I restart the app, it gets its initial size and centered position within the desktop.
I think we need to persist in settings:
- window state: Normal | Maximized
- window geometry

and restore these when launching the app.

**Comment by MishkaRogachev** [comment]
As i see it we store only width/height in local_app_settings.nim. I can add x/y, screen number and window state too, but this behaviour will override OS's desktop enviroment default one.
