### ISSUE TITLE
Linux cpu usage due to StatusQ commit and other commits

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3096]
There is some commits that seemed to have increased the cpu usage on linux, currently under investigation

**Comment by richard-ramos** [comment]
Checking this commit, it seems that this line on the Makefile is causing an increase on the CPU usage:
https://github.com/status-im/status-desktop/blob/master/Makefile#L233
```
nim_status_client: NIM_PARAMS += $(RESOURCES_LAYOUT)
```
`RESOURCES_LAYOUT` has the value `-d development` when running desktop with `make run` and seems to be related to the  translations https://github.com/status-im/status-desktop/blob/master/src/nim_status_client.nim#L81-L83

Here's my experience with that line of code:

https://user-images.githubusercontent.com/1106587/127338874-eef79b07-f8db-4c24-9508-f4a9291e2bd0.mp4

After commenting it

https://user-images.githubusercontent.com/1106587/127338909-363aa653-3a02-4e77-a34a-c1640806440c.mp4


cc: @iurimatias, @saledjenic, @michaelsbradleyjr

**Comment by richard-ramos** [comment]
![image](https://user-images.githubusercontent.com/1106587/127362343-d27fb352-78dd-4d6d-8daa-afa738d116b3.png)
If i comment line 270 on DOtherside, CPU usage goes down a lot, but then the texts are not translated on runtime. It's necessary to quit the app and start again to see any language change

**Comment by richard-ramos** [comment]
Disabling translations on runtime in Linux reduces the CPU usage to levels similar to not having the RESOURCE_LAYOUT variable set

**Comment by saledjenic** [comment]
> Disabling translations on runtime in Linux reduces the CPU usage to levels similar to not having the RESOURCE_LAYOUT variable set

@richard-ramos yes, that's known, described [here](https://doc.qt.io/archives/qtjambi-4.5.2_01/com/trolltech/qt/qtjambi-linguist-programmers.html).
