### ISSUE TITLE
when the members section is selected, the button should have a background

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3101]
see design https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=2816%3A15806

![Screen Shot 2021-07-28 at 11 51 18 AM](https://user-images.githubusercontent.com/176720/127354799-411e7767-9002-4535-b09e-4fd5743a0690.png)

**Comment by Khushboo-dev-cpp** [comment]
Setting ->
                membersButton.highlighted: showUsers
in ChatLayout.qml solves the bug.
