### ISSUE TITLE
Undefined in communities members count and community channel validation message

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3106]
<img width="1012" alt="Screenshot 2021-07-29 at 10 20 01" src="https://user-images.githubusercontent.com/82375995/127449335-1160ee17-a9a9-4afc-8bb1-feec3ffa7d40.png">

<img width="1012" alt="Screenshot 2021-07-29 at 10 22 47" src="https://user-images.githubusercontent.com/82375995/127449379-928e63cd-69b5-4ab8-a8f6-989bd540a8aa.png">

**Comment by alaibe** [comment]
The second part about the error message is already fixed on master since the translation have been updated
