### ISSUE TITLE
Remove margin between chat messages and left pane

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3123]
![image](https://user-images.githubusercontent.com/82375995/127674421-ba2cdc32-f3fe-4f1f-ac3e-61e0e9683194.png)

**Comment by pinebit** [comment]
`SplitView.handle` needs to be customized: https://doc.qt.io/qt-5/qtquickcontrols2-customize.html#customizing-splitview
@simonricoo to provide the link to the design.
The ticket should be moved to StatusQ project.

**Comment by anastasiyaig** [comment]
@PascalPrecht please take a look as well

**Comment by PascalPrecht** [comment]
Yes, this issue belongs to StatusQ

**Comment by iurimatias** [comment]
moved to https://github.com/status-im/StatusQ/issues/307
