### ISSUE TITLE
Community chat preview is not shown when switching between chat and community

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#3148]
open app
you should have a few chats
open any chat
switch to community chat and back
"default" chat will be opened, or empty chats view (with the radio)

<img width="1344" alt="Screenshot 2021-08-04 at 11 51 24" src="https://user-images.githubusercontent.com/82375995/128152057-22f5f3e0-8096-440f-912a-7ce05e157b63.png">

Version: 0.1.0-beta.11

**Comment by anastasiyaig** [comment]
@flexsurfer i remember we had this issue before, but we fixed it. Could u please take a look and advise if this is what u are seeing now? https://github.com/status-im/status-desktop/issues/2686

**Comment by anastasiyaig** [comment]
When switching between community channel and public channels , there is an issue with right pane, where chat preview is displayed. So having a community channel opened, switch to public chat -> as result, none of public chats is being set to active (selected) and the preview at the right pane contains the conversation from the community channel instead. 

https://user-images.githubusercontent.com/82375995/128153144-72ef9d75-43f3-45ce-a4e1-90dce9cd4c62.mov

**Comment by anastasiyaig** [comment]
i noticed that i accidentally switched OFF the community flag which leaded to this scenario showed on video

**Comment by iurimatias** [comment]
I think @alaibe fixed this already

**Comment by alaibe** [comment]
@anastasiyaig I think this one is fix, now when you toggle off communities they don't appear anymore. Could you confirm, the bug is fixed for you?

**Comment by anastasiyaig** [comment]
right it is fixed in latest master. the confusion was caused by the toggle

**Comment by flexsurfer** [comment]
original issue still not fixed

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-desktop/issues/3195
