### ISSUE TITLE
Chat history is not shown when messages are sent from non-contact

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3154]
![image](https://user-images.githubusercontent.com/82375995/128175156-3ac76741-2a9a-4e3a-b3e2-d1fa2838140d.png)

<img width="1027" alt="Screenshot 2021-08-04 at 14 00 50" src="https://user-images.githubusercontent.com/82375995/128175177-13a40644-2094-462c-aa66-966557ec72b0.png">

Fetch messages throws an error:

`/Users/jenkins/workspace/us-desktop_branches_macos_master/src/status/libstatus/core.nim(24) callPrivateRPC
ERR 2021-08-04 13:53:21+03:00 rpc response error                         topics="rpc" tid=8253361 file=core.nim:25 methodName=wakuext_syncChatFromSyncedFrom payload="[\"0x047125e73606d93ee1aa288b15b16be75bb0aa8f914651a8435452fd74501e917bc2342b8d1a393bc5770dcf4148c0a452e568ba4d8aed3ccdbb3f1d24f2f19fd2\"]" result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"invalid \'From\' value which is greater than To\"}}"
`

It helps to receive the messages if i restart the app several times

<img width="1552" alt="Screenshot 2021-08-04 at 15 10 37" src="https://user-images.githubusercontent.com/82375995/128178583-e788a9fd-e40a-4465-800a-7544b978587a.png">

**Comment by anastasiyaig** [comment]
i think the root cause of the issue also prevents users from joining the community when invitation is sent from non-contact @iurimatias (the situation i was in yesterday)

**Comment by iurimatias** [comment]
is it sort of expected? i.e we don't want to receive messages from non-contacts

**Comment by iurimatias** [comment]
ups closed by mistake (misclick), reopened

**Comment by iurimatias** [comment]
@anastasiyaig for this issue, assuming the mutual contacts was working in all clients, would this be expected behaviour? i.e how can we receive messages if it's not a mutual contact, the point is to avoid spam. in that case receiving invites seems to also something that should not work. what do you think?

**Comment by anastasiyaig** [comment]
> @anastasiyaig for this issue, assuming the mutual contacts was working in all clients, would this be expected behaviour? i.e how can we receive messages if it's not a mutual contact, the point is to avoid spam. in that case receiving invites seems to also something that should not work. what do you think?

ya lets close this one and i will check the receiving invites separately
