### ISSUE TITLE
add unfurling support for tenor

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3160]
the gif selector sends messages with the tenor url, we should add tenor.com to the list, probably needs changes in status-go

![Screen Shot 2021-08-04 at 5 56 49 PM](https://user-images.githubusercontent.com/176720/128260554-71a1ff65-6ec4-4de3-ac45-af5b668dd71c.png)

marking as mandatory because it's not obvious to the use there is an advanced setting to display any image

**Comment by alaibe** [comment]
It seems that it was previously enabled: https://github.com/status-im/status-go/blob/develop/protocol/urls/urls.go#L77-L81

**Comment by alaibe** [comment]
https://github.com/status-im/status-go/pull/2302
