### ISSUE TITLE
mentioning an ens user doesn't display the username highlighted

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3161]
this happens in communities only, probably due to the user list

![Screen Shot 2021-08-04 at 6 03 41 PM](https://user-images.githubusercontent.com/176720/128261260-f604ab04-7db6-49d6-b6be-962a9d5c61ee.png)

**Comment by anastasiyaig** [comment]
@iurimatias i logged it already https://github.com/status-im/status-desktop/issues/3149
