### ISSUE TITLE
member list should be clickable and have a context menu

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3162]
1. Left clicking a user should open that user profile modal

![Screen Shot 2021-08-04 at 6 06 28 PM](https://user-images.githubusercontent.com/176720/128261562-2f1db6db-7651-45bc-a731-b667641b16da.png)

2. Right clicking should show a context menu for that user same as the one that shows when clicking their username on the a message

![Screen Shot 2021-08-04 at 6 06 14 PM](https://user-images.githubusercontent.com/176720/128261665-c3d80068-432d-4459-844c-8b994b980e88.png)

**Comment by iurimatias** [comment]
@Khushboo-dev-cpp this is missing the right click context menu

**Comment by Khushboo-dev-cpp** [comment]
hmm works on linux again, I think its the same issue that we faced with the copy/download image feature. All of these may have to be defined as non Modal I think

**Comment by Khushboo-dev-cpp** [comment]
@iurimatias work as expected for me
![image.png](https://images.zenhubusercontent.com/610aa02b14ef6a62cbf14bf1/3770010f-b204-4b71-94d2-c224bcc454ee)

**Comment by Khushboo-dev-cpp** [comment]
@iurimatias Does this not work for you?
