### ISSUE TITLE
Can't copy a part of message, only entire message can be copied

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3189]
1. open status and navigate to test public chat
2. select any part of message -> right click -> copy to clipboard
3. paste the selection in the text box

**Actual result:** no matter of the selection made, the whole entire message is copied.

**Expected:** i want to be able to copy any part of message

**Comment by iurimatias** [comment]
I seem a different bug which is that the `copy to clipboard` is missing

**Comment by alexandraB99** [comment]
I agree, @anastasiyaig could you confirm that `copy to clipboard` is missing in general? BTW, when using ctrl+c/v this bug is not reproducible.

**Comment by alexandraB99** [comment]
@anastasiyaig, @iurimatias after discussing with @Khushboo-dev-cpp, "copy to clipboard" option is not part of the message context menu anymore as per [new design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?node-id=5395%3A43214) so I guess this ticket can be closed
