### ISSUE TITLE
Scrolling increases the real memory usage in several times

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3190]
1. join # test channel
2. open monitor on Mac and double click status process to see its data
3. notice the memory usage value
4. scroll the chat from bottom to top and from top to bottom several times

**Actual result:** the memory usage jumps from 400 mb up to 1.1 GB even the pictures previews are disabled

https://user-images.githubusercontent.com/82375995/128833591-26049a38-e9f2-4008-a70f-fab0d528a7a4.mov

**Comment by saledjenic** [comment]
@anastasiyaig is this still an issue? Any specific steps to reproduce it? I've tried and scrolling like 7 days in the past, scrolling up and down, increased memory for 40MB, not that dramatically jumps in memory usage. I will check that, but I would be better if I could reproduce that insane memory usage which you got.

**Comment by anastasiyaig** [comment]
@saledjenic when having an account with data folder (contacts chats and etc) , it is visible. With new account it is better. I noticed that clicking Fetch messages consumes a lot as well

https://drive.google.com/file/d/15MEqQI0xbHzQK4Z-cKjzebl_f0kWjmDn/view?usp=sharing
