### ISSUE TITLE
Some links does not show the preview setting bubble 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3199]
1. some links are not being resolved, for instance https://github.com/status-im/status-desktop/issues/705 does show the bubble and https://www.nim-lang.org/ is not when sending in chat

2. the preview setting is shown to the sender, and not shown to the recipient and vice versa

<img width="1436" alt="Screenshot 2021-08-11 at 15 41 41" src="https://user-images.githubusercontent.com/82375995/129031967-1f54f23c-539c-4aaa-8b34-644af7662983.png">

**Comment by iurimatias** [comment]
not resolving nim-lang.org is normal since only some sites are supported, however if the preview setting is not shown to the sender this seems like a bug

**Comment by alaibe** [comment]
@anastasiyaig could you confirm this is still happening, when receiving or sending link (github one) I can see the suggestion to enable link previews for both.
Is there anything that needs to be done to trigger this one?

**Comment by anastasiyaig** [comment]
not sure i can reproduce anymore
