### ISSUE TITLE
Messages counter is increasing dramatically when scrolling chat back and force

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3221]
1. Create 1x1 chat
2. Send 10 messages there, so the history of it is scrollable
3. Scroll the chat up and down, noticing the counter showing how many messages are left to the very last one

As result, the counter increases all the time i scroll up.

https://user-images.githubusercontent.com/82375995/129337159-9edcc7a5-0b33-4af9-8618-164bfd3938c8.mov

**Comment by anastasiyaig** [comment]
I've set it as medium since i am not sure, if this really kills the performance , because when scrolling the chat the memory usage goes crazy, so if we are trying to fetch wrong amount of messages (or wrong messages) - it is definitely not only issue with counter representation then.

**Comment by saledjenic** [comment]
@iurimatias I checked this in the latest master branch, and it works fine if the request is "Show number of new messages if you're not positioned at the bottom when new messages arrive", comparing with other chat apps that should be use case. But if we need to show number of total messages bellow when we scroll up, then it's not good, please confirm.

**Comment by anastasiyaig** [comment]
Looks like it is fixed , i am not able to reproduce it in Master `Build #1279 (27-Aug-2021 13:24:41)`
