### ISSUE TITLE
Add the option for enabling chat bubbles

### ISSUE THREAD

**Issue by ducheng0** [status-im/status-desktop#3226]
I hate the Discord-style where all messages are on the left and there's nothing separating them. It would be great to have the option to add chat bubbles back for those who get a headache with the Discord style.

**Comment by iurimatias** [comment]
Hi @ducheng0 , for the moment there are no plans to bring this back as we need to focus on getting the current chat functionality chat right, in the future however we might reintroduce this as an alternative UI mode or supported though custom themes etc..
