### ISSUE TITLE
Long name in communities and channel overlap

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#3242]
To reproduce:
1 - create a communities with max size name and description
2 - create channel with max size name

=> it overlap while it should be truncated?

![image](https://user-images.githubusercontent.com/491074/129878061-2306a18b-058f-4d01-92ef-5c1e071c0a36.png)

Same result when joining very long public chat:

![image](https://user-images.githubusercontent.com/491074/129878327-d1cec415-995f-4616-8d1e-71af4df0cd03.png)

**Comment by alexandraB99** [comment]
Depends on [StatusQ #335](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/statusq/335)

**Comment by alexandraB99** [comment]
@alaibe I can't reproduced this anymore, please check and close accordingly

**Comment by alaibe** [comment]
@alexandraB99 see screenshot below, the community name still overlap with the + button:

![image](https://user-images.githubusercontent.com/491074/133097451-811c826a-0396-4f42-8636-fb31d0ada05d.png)

**Comment by alexandraB99** [comment]
Thanks @alaibe! Please check fix in StatusQ [here](https://github.com/status-im/StatusQ/pull/408).

**Comment by alaibe** [comment]
Closing as being fixed in StatusQ. Thanks ;)
