### ISSUE TITLE
Communities feature missing buttons for adding categories/channels in Linux/Android

### ISSUE THREAD

**Issue by pback34** [status-im/status-desktop#3264]
I create communty from MacOS, can see full set of features for adding categories for a community just created. This is completely absent from Linux Version: 0.2.1-beta. No way to create channels/categories in the community. I also did not see these features in Android as well.

**Comment by pback34** [comment]
Correction: I was able to see the features appear after enabling the Communties features in settings. Perhaps that setting needs to hide all of the communities features. I was still able to create a community with that setting disabled. Makes it confusing to users who think they are using the feature.

**Comment by alaibe** [comment]
@pback34 yes, you are correct, this is a bug in v0.2.1. We fixed it on master already, it should be fixed for the next release

Here is the PR for reference: https://github.com/status-im/status-desktop/pull/3153
