### ISSUE TITLE
Reply to image doesn't show image in reply

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#3272]
When replying to an image, the image is not include as a thumbnail in chat text input. Instead a statement is shown as though the client doesn't support images "Update to the latest version to see a nice image here!"

### Current
Chat input shows "Update to the latest version to see a nice image here!" when replying to image

![Screenshot 2021-08-23 174106](https://user-images.githubusercontent.com/35233054/130477228-115c7dc3-798d-46ed-9faf-b8292cb46c14.png)

### Expected
Chat input shows 
↪`username` (without content if content cannot be displayed in chat input box)

OR

Chat input shows 
↪`username` (with thumbnail image if thumbnail image can be displayed)

**Comment by hesterbruikman** [comment]
@simonricoo wdyt?

This is already better than what I had in mind 🙏

> I also notice that an image in which you also add some text is handled as a separate message. Isnt that not ideal for the user?

Indeed, the separate messages for image and text is not ideal. I find it more prominent in the status updates/timeline tab. That said, I've understood that this is an impactful change to the current payloads, wrappers, message size, etc. in status-go (specs: https://specs.status.im/spec/6). I personally can't judge the pros and cons. If you'd like to investigate what is possible, @Samyoul is a great person to talk to

**Comment by Khushboo-dev-cpp** [comment]
Aah didnt know about the constraints with the messages, sure I can discuss further with Sam.

**Comment by simonricoo** [comment]
Hey, @Khushboo-dev-cpp find the design for images and stickers reply here :) https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=865%3A4136
