### ISSUE TITLE
Issues in Communities channel behavior

### ISSUE THREAD

**Issue by pback34** [status-im/status-desktop#3275]
This may be more than one issue, but will list all here and maybe some can be addressed:
1. channel naming limitations exist on linux version (such as capitalization), but not on Android. 
2. Channels cannot be deleted - why is this not possible?
3. Some channels I am unable to change the description for no apparent reason. Save button is greyed out (Linux). 
4. Unable to edit existing channels at all in Android - can only create new channels
5. Where is the documentation for Communities? There needs to be a resource for users to test things out and understand the intended behavior.

**Comment by iurimatias** [comment]
@pback34 thanks for reporting this, w.r.t 2. it should be possible to delete a community channel if you are an admin, we'll give a look. as for docs you can find __some__ docs here under the `Communities` section https://hackmd.io/@status-desktop/main/https%3A%2F%2Fhackmd.io%2F%40status-desktop%2FrkUZ6fWnO

**Comment by pback34** [comment]
Edit channel seems to be working again for some reason - I had trouble editing some channels previously for an unknown reason (related to community having 2 owners?). However:
1. Channel names cannot contain capitals when made from linux app, but can from Android.
2. Delete is still non-existant in channels created in either linux or android. (I've looked everywhere i could think of).

Thanks and let me know if you have any other questions.

**Comment by iurimatias** [comment]
latest build in master these issues seem all addressed
