### ISSUE TITLE
Profile Settings -> Advanced, content on the right side is not scrollable

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#3278]
If you navigate to Profile Settings -> Advanced section and reduce the height of the app, bottom content won't be visible. We should add a vertical scroll bar for the content on the right side, the same way other sections work.

![SettingsAdvancedNoScroll.png](https://images.zenhubusercontent.com/60d33ac5a2886cc4c09ca323/8adffadd-a7fa-467d-ab2c-58ac132fc153)

**Comment by alaibe** [comment]
@saledjenic are you on latest master, there is now a scrollbar here?

**Comment by saledjenic** [comment]
@alaibe I've just built the latest master, and yes, you're right, it's fixed there (not sure now what version I checked when I logged this issue). I am closing it. Thanks.
