### ISSUE TITLE
Text in chat input is invisible if pasting message from clipboard with emoji via cmd+c/cmd+v

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#3291]
#### Expected behavior
can see message text

#### Actual behavior
https://user-images.githubusercontent.com/4557972/130805586-e6695c67-4bc0-4228-83ce-00e0f1d985c6.mp4

### Reproduction

- open any public chat
- copy message with emoji via cmd+c
- paste it to chat input

### Additional Information

- Status version: 0.2.1-beta 
- Operating System: Mac OS Big Sur 11.5.2 (20G95)

[comment]: # (Please, add logs/notes if necessary)

**Comment by anastasiyaig** [comment]
The issue is back now in 0.8.1 (reproduced as described)

**Comment by caybro** [comment]
@anastasiyaig I can still reproduce... wow

**Comment by anastasiyaig** [comment]
i can reproduce as well!

**Comment by caybro** [comment]
Some hint: if I paste using the middle mouse click (on Linux), it works fine

**Comment by alexandraB99** [comment]
also, if I delete the emoji then the plain text appears

**Comment by caybro** [comment]
another observation: it happens already in StatusBaseInput; so not related to our extra functionality in StatusChatInput

**Comment by caybro** [comment]
the plot thickens; in storybook we get this warning when pasting:

```
file:///home/ltinkl/git/status/status-desktop/ui/imports/shared/status/StatusChatInput.qml:1227:25: QML TextArea: Cannot open: qrc:/StatusQ/src/assets/twemoji/svg/1f642.svg?72x72
```
