### ISSUE TITLE
support optimism in the new wallet - status-go

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3297]
needs discussion on the best way to implement this in status-go

**Comment by alaibe** [comment]
@simonricoo in the UI when we show the balances, do we show the full total accross all networks enabled or only mainnet?

@iurimatias by looking at the new design, it seems that feature needed are:
* Add custom network EIP3085
* Remove a custom network
* Get asset balance accross multiple network
* Enable/disable network
* Choose a network when doing a tx (to keep it simple, no multi chain tx to start), default is mainnet

In general, support for more than 1 network enabled

What are the network available by default?
    - Mainnet
    - Optimism
    - ? (currently we have ropsten/kovan....)


How the network added differ from advance settings network selection?
    - Does it mean we need to allow to change network on the fly?

**Comment by simonricoo** [comment]
@carlfairclough would know better :)
