### ISSUE TITLE
add new settings tab to the new wallet

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3303]
see design https://www.figma.com/file/0m5JUlP8dv9szwQiGvP9gb/Wallet-Redesign-Sketchpad-%5BWIP%5D?node-id=357%3A33670

this should have a settings tab for each account, and the following at this stage to support:

- back up seed phrase if it's the main status account
- view private key if imported account
- account signing phrase
- security preferences

out of scope:
- ens name
- preferred networks
- connected apps

**Comment by Khushboo-dev-cpp** [comment]
Hey in the design flow for "security preferences" is missing?
is the "Global wallet settings" in scope @iurimatias
