### ISSUE TITLE
dragging or clicking in categories can make membership requests section disappear

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3315]
https://user-images.githubusercontent.com/176720/131024449-54177214-3edf-47c6-b420-cbc3621b0d72.mov

**Comment by Khushboo-dev-cpp** [comment]
It seems the call 
status_chat.reorderCommunityChat(communityId, categoryId, chatId, position) 
and 
status_chat.reorderCommunityCategories(communityId, categoryId, position)
reset the membership requests to 0.

**Comment by Khushboo-dev-cpp** [comment]
@iurimatias Please reschedule this as discussed. The issues is in the status-go API
