### ISSUE TITLE
Windows zip version?

### ISSUE THREAD

**Issue by snakyjake1** [status-im/status-desktop#3324]
Is there a zip version of 0.2.1-beta (beta 11)?
I am hoping I can get a zip version like we had with 0.1.0-beta.10.

Thank you.

**Comment by michaelsbradleyjr** [comment]
@snakyjake1 can you explain why you prefer or need a zip version? Does the installer `.exe` work correctly on your Windows computer?

**Comment by snakyjake1** [comment]
I prefer to have something portable.
I want to use on devices where I am not the administrator of the device, therefore cannot install.
I had a zip version in a previous release.
