### ISSUE TITLE
Community invite is not shown in 1-1 chat from desktop

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#3329]
#### Expected behavior
invite is shown with "View" option, like on mobile

#### Actual behavior
no invite is shown in chat history
<img width="634" alt="Status Desktop 2021-08-30 12-17-09" src="https://user-images.githubusercontent.com/4557972/131324685-58ca6c77-f3c3-4164-8b99-bda85e0617e9.png">

### Reproduction

1) Add User A to contacts, exchange several messages 
2) Create a community
3) Add User A to community via + > Invite member
4) after "Invite is successfully sent!" message check 1-1 chat with User A

### Additional Information

- Status version: 0.2.1-beta 
- Operating System: Mac OS Big Sur 11.5.2 (20G95)

[comment]: # (Please, add logs/notes if necessary)

**Comment by iurimatias** [comment]
@churik just to confirm ,this is the same as #3280 right? i.e the community links take time to unfurl sometimes both on desktop and mobile

**Comment by churik** [comment]
no, it is just missing message in 1-1 chat. Mobile-mobile works fine.

**Comment by iurimatias** [comment]
oh I see, missunderstood that, we'll take a look, thanks for reporting it
