### ISSUE TITLE
Prevent windows from opening two instances

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-desktop#3340]
Description: Windows build have a feature "hide to tray". When Status is already open, prevent it from opening again, instead just show the already opened version, or just message that an instance is already running and user should check the system tray. 

However, some users might want to run more then one instance at Windows, if thats the case, maybe allow running more than one instance if the executable is in another folder?

**Comment by iurimatias** [comment]
fixed by https://github.com/status-im/status-desktop/pull/3003
