### ISSUE TITLE
Update navigation bar icons to newer bigger versions

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#3342]
There was a misunderstanding in what icons need to be used in the navigation bar of the application.
In most of the places where icons are used, we refer to "normal" sized icons provided by StatusQ. This happens every time for example a `StatusIcon` component is used:

```
StatusIcon {
  icon: "profile"
}
```

The same mechanism is used in the nav bar tab buttons, but the icons rendered there are meant to be bigger.
There's a PR in StatusQ that introduces that bigger set of icons: https://github.com/status-im/StatusQ/pull/362

One that lands, we'll have to update Status Desktop to use those icons as well.
You can see in the StatusQ PR how that is done in the demo app.

**Comment by iurimatias** [comment]
outdated
