### ISSUE TITLE
It shouldnt be possible to reply to stickers?

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#3346]
Currently mobile does not allow replying to stickers, while desktop does:

Desktop:
![image](https://user-images.githubusercontent.com/1106587/131539805-f2e1d374-7ba1-4d48-8fd9-e50d31baab35.png)

Mobile:
![image](https://user-images.githubusercontent.com/1106587/131539827-12df48f6-ea0c-4d9b-af55-19fef5304ced.png)

Either desktop should have the reply option disabled for stickers, or status-react should add the option to reply to stickers and render the reply correctly

**Comment by iurimatias** [comment]
I think this issue is specific to mobile, they should show the sticker in the reply
