### ISSUE TITLE
Why is the UI so small?

### ISSUE THREAD

**Issue by zach-is-my-name** [status-im/status-desktop#3352]
I feel like most apps today offer big, cushy UI's... 
Status for desktop feels small => not modern => not user friendly... like cpp docs...

v0.2.1
Ubuntu 20.04
![Screenshot from 2021-09-01 17-14-50](https://user-images.githubusercontent.com/16063092/131746831-ef926fe5-19bf-4779-8fee-9c515d39db47.png)

**Comment by iurimatias** [comment]
HI @zach-is-my-name , thanks for reporting this, you're in luck! PR https://github.com/status-im/status-desktop/pull/3356 has been merged recently and the next version `0.3.0` will have the option to zoom and generally work better in 4k screens
