### ISSUE TITLE
Human Readable data display when signing using `eth_signTypedData_v3`

### ISSUE THREAD

**Issue by D4nte** [status-im/status-desktop#3355]
For the Status Community Curation dApp, poll responses and votes are signed using [EIP-712](https://eips.ethereum.org/EIPS/eip-712): Ethereum typed structured data hashing and signing.

Currently, the data is displayed in one line JSON format:

![image](https://user-images.githubusercontent.com/300805/131761492-ddaa8534-155a-40d3-91fb-c91f6b0c9a44.png)

Instead, we should display the data in a more human readable format.

The [EIP-712](https://eips.ethereum.org/EIPS/eip-712) provides examples such as:

![image](https://user-images.githubusercontent.com/300805/131761569-345fb1ae-7e49-4bf2-bfe9-11d3820f2f86.png)

https://status-im.github.io/js-waku/eth-pm/ can be used to play around (broadcast encryption public key step).

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6775
