### ISSUE TITLE
[Windows] could not load: DOtherSide.dll

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3363]
<img width="1552" alt="Screenshot 2021-09-03 at 11 42 56" src="https://user-images.githubusercontent.com/82375995/131980075-5a647920-8890-4e3f-aee5-d4d9c34bc406.png">

I am not able to run the app after installation, the following error appears: `could not load: DOtherSide.dll`

<img width="1552" alt="Screenshot 2021-09-03 at 12 05 23" src="https://user-images.githubusercontent.com/82375995/131980246-4060fd0c-6428-47d6-82d6-615c9b9be345.png">

**Comment by pinebit** [comment]
Probably we should close it, since this is Windows 11 @ ARM.

**Comment by samuel-lucas6** [comment]
I'm getting this error in a Windows 10 VM.
