### ISSUE TITLE
Can't drag and drop a channel inside / outside in / of category

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3364]
As a user i want to be able to order a channels within category by drag and drop feature. It is not working right now.

1. create a community
2. add several channels
3. create a category
4. select any of channels and drag it into the category
5. having a channel inside the category drag and drop it outside, so it should be uncategorised

https://user-images.githubusercontent.com/82375995/132000639-e03a966a-b0ac-48ac-9bd8-8e008a388b4b.mov

**Expected:** having a channel that does not belong to any category in community, drag and drop it inside the category should be possible. Opposite case (drag and drop to move outside the category) should also work.

**Note:** some error is shown in console when drag and drop `QQmlExpression: Expression qrc:/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml:130:25 depends on non-NOTIFYable properties:
    QQmlDelegateModel::model`

**Comment by iurimatias** [comment]
on hold until base bc is merged

**Comment by iurimatias** [comment]
note: needs backend

**Comment by endulab** [comment]
A bit related to #7422

**Comment by jrainville** [comment]
This might need this refactor first: https://github.com/status-im/status-desktop/issues/5286

**Comment by anastasiyaig** [comment]
**Acceptance criteria:**

1. Community channels re-ordering within category works within drag & drop
2. Community categories re-ordering works with drag & drop
3. Can drag & drop the channel out from the category (standalone channel)
4. Can drag & drop the channel into category

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5204%3A39333&t=VHrsnoDvp5KatqdX-4

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5204%3A38765&t=VHrsnoDvp5KatqdX-4

**Comment by jrainville** [comment]
Moving this to 0.10 as it requires https://github.com/status-im/status-desktop/issues/5286 which is not trivial to do at the end of the milestone

**Comment by jrainville** [comment]
The blocking issue of flattening the chat model has been merged.  @alexandraB99 you can have your team start this task now!

**Comment by alexandraB99** [comment]
@jrainville please notify when you finish with the further improvements

**Comment by jrainville** [comment]
@alexandraB99 I added this issue to track the refactor. I'll ping you here anyway once it's done https://github.com/status-im/status-desktop/issues/9494
