### ISSUE TITLE
Leave chat is shown instead of Delete confirmation when deleting community channel

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3365]
1. create a community
2. create a channel
3. right click this channel
4. select Delete option

<img width="1552" alt="Screenshot 2021-09-03 at 14 55 51" src="https://user-images.githubusercontent.com/82375995/132001566-bb9b66ea-3090-40ce-8af6-f86c73458e1f.png">

Expected: we need to align UX here, if user is deleting then confirmation modal should also say "delete"

**Comment by Khushboo-dev-cpp** [comment]
as per design there should be 2 options, delete and cancel. Also I notice that in the design the channel name is mentioned in the popup. Will fix that too.

@anastasiyaig What do you mean by step 3? right click on channel?do you mean the three dots buttons?

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp right click the channel item -> context menu shown -> select delete
