### ISSUE TITLE
Clean up root folder

### ISSUE THREAD

**Issue by pinebit** [status-im/status-desktop#3367]
Submitting the issue to address this comment:
https://github.com/status-im/status-desktop/pull/3362#issuecomment-912382112

**Comment by jakubgs** [comment]
Yes, there's a lot of assets like the cert, images, metadata files and so on:
![image](https://user-images.githubusercontent.com/2212681/132020464-db0b5948-d729-41ac-bc26-d8058793caab.png)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5747
