### ISSUE TITLE
improve performance of group messages

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3370]
currently group messages are very slow, specially on windows, leading some messages to be dropped because the envelope expires

**Comment by pinebit** [comment]
I benchmarked `sendMessage()` call and here is what I've got:

on Windows:
- 1-1 chat: 30ms average
- group chat of 6 members: 60ms average

on Linux (VMWare, granted all CPU power and RAM):
- 1-1 chat: 25ms average
- same group chat: 30-40ms average

Therefore I can conclude if there is a difference in encryption speed, then it is about 20%.
Anyway, the figures I am getting here are so small, not sure what we could optimize here to have a noticeable difference.
However, I suspect there might be networking issues (e.g. latency spikes) that you may experienced.
