### ISSUE TITLE
Share community link is shown as undefined

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3394]
<img width="1552" alt="Screenshot 2021-09-07 at 15 41 10" src="https://user-images.githubusercontent.com/82375995/132346212-f7a30cc1-cc3b-4e32-a884-24852679171e.png">

1. create a community
2. click Invite Friends
3. pay attention to the share link at the top of the modal
4. copy the link by clicking the copy button

Copying this link is not possible because of error:

`DBG 2021-09-07 15:42:17+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=1888715 file=model.nim:196
qrc:/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupInviteFriendsView.qml:40: TypeError: Cannot read property 'id' of undefined
`

**Comment by PascalPrecht** [comment]
This is fixed with: https://github.com/status-im/status-desktop/pull/3407
