### ISSUE TITLE
Handle ctrl+v shortcut to paste image from clipboard

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-desktop#3395]
Any normal messenger that supports images will support also pasting images into chat from clipboard.

This is also a crucial feature for collaboration because it makes it easy to show people things without having to go through the tedious process of saving screenshots first as files and then navigating to them.

Acceptance Criteria:
- on the browser, right click on an image and choose copy image, then go to the desktop app and in the chat input, do ctrl +v. the image should be pasted as an attachment

**Comment by PascalPrecht** [comment]
Working on this atm.
Currently trying to get clipboard image -> base64 support in DOtherside.
There's a WIP branch here which for some reason doesn't compile: https://github.com/status-im/dotherside/pull/76

@caybro will help making this work.

Once that is done I'll extend the paste functionality in StatusChatInput to hydrate the image preview area with the clipboard image.
