### ISSUE TITLE
Pressing enter/return with unconfirmed password in "Confirm password" field creates account using password in that field

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/status-desktop#3412]
In the *Create a password* modal during onboarding, type `foobar` into the `New password` field and `foo` into the `Confirm password` field, then press enter/return.

Account creation will proceed and the app will fully load.

Quit the app and restart. Login will be successful with password `foo`, but not `foobar`

https://user-images.githubusercontent.com/82375995/132489557-333d7ddb-aacf-4596-a340-f8110cf34140.mov

**Comment by anastasiyaig** [comment]
also , after this bug happens, then change password feature is not working

https://github.com/status-im/status-desktop/issues/3426

**Comment by PascalPrecht** [comment]
Should be fixed with https://github.com/status-im/status-desktop/pull/3428
