### ISSUE TITLE
Sign out confirmation modal is missing

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3423]
Sign out confirmation modal is missing, it should be present

1. log in to the app
2. go to profile and click Sign out and Quit

**Actual:** the app is closed immedaitely

**Expected:** confirmation modal is shown. Discarding it user stays in, confirming it logs user out and closes the app.

https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/👤-Profile⎜Desktop?node-id=2339%3A14576

**NOTE:** use `lose` instead of `loose` when adding this modal copy

<img width="1552" alt="Screenshot 2021-09-08 at 14 43 00" src="https://user-images.githubusercontent.com/82375995/132503376-da7467e7-35be-46b6-842f-8b174050bf70.png">

**Comment by PascalPrecht** [comment]
This has landed with #3447
