### ISSUE TITLE
Settings is mistakenly named as Profile, also wrong icon is used

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3429]
![image](https://user-images.githubusercontent.com/82375995/132518845-61ad0984-b9cc-4d51-88cb-dafb02aaa1f0.png)

**Comment by PascalPrecht** [comment]
This is fixed with #3451. The profile icon will be restored with the next StatusQ release on monday (with this commit: https://github.com/status-im/StatusQ/commit/48309d3040dcaa5a6ee955f8a95153b18316edbc)
