### ISSUE TITLE
Add confirmation modal when changing password

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3432]
Currently when password is changed the application is shit down immediately after clicking Change Password button which is confusing. Mobile has nice UX -> confirmation that password has been changed and warning that u must restart the app. We need to implement something similar

https://user-images.githubusercontent.com/82375995/132526492-8ceba71c-c997-4263-b8fe-035678edfc4e.mp4

Design input is required as i dont see this screen at https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/👤-Profile⎜Desktop?node-id=1507%3A608

**Comment by alexandraB99** [comment]
Design in Figma: https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/👤-Profile⎜Desktop?node-id=3058%3A18473
