### ISSUE TITLE
Search popup search location doesn't seem to be correct in dark mode

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#3441]
Starting from scratch with a brand new account without any chats, opening the search popup looks like this:

<img width="1344" alt="Screenshot 2021-09-09 at 10 41 17" src="https://user-images.githubusercontent.com/445106/132653335-a186c6fe-86a1-4913-bf9c-d2c3423830d4.png">

This probably needs to be populated with different search location data?

**Comment by iurimatias** [comment]
this is fine as a default first state, new designs might clarify it
