### ISSUE TITLE
Network ID is not being displayed when adding a custom network

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#3456]
When the radio button for "Custom" networks is selected,  the input field for network ID is not being displayed,:

ui/app/AppLayouts/Profile/Sections/NewCustomNetworkModal.qml
```qml
Input {
            id: networkInput
            visible: customRadioBtn.checked
            //% "Network Id"
            label: qsTrId("network-id")
            //% "Specify the network id"
            placeholderText: qsTrId("specify-the-network-id")
            validationError: addNetworkPopup.networkValidationError
        }
```

![image](https://user-images.githubusercontent.com/1106587/132721615-b1e54cf3-7641-44a0-8cb6-294cab796524.png)

**Comment by corpetty** [comment]
I know it's a UI issue, but I am unable to connect to the AVAX C-chain via Status (both mobile and desktop) but metamask can. I have the assumption that we're mangling the URI. 

Can this be investigated during this being fixed, or shall I open another issue?

**Comment by anastasiyaig** [comment]
@corpetty this is a good catch, what i see is that the RPC url is being lower-cased when entered on mobile. I need to check if something similar happens to the URL on desktop (see the screenshot), but i believe we need to fix current issue before that. Mobile issue will be tracked in mobile repo separately

<img width="1344" alt="Screenshot 2021-09-10 at 11 59 42" src="https://user-images.githubusercontent.com/82375995/132829452-bc308236-9a94-498d-bce2-cb9e68ccbe57.png">

**Comment by qoqobolo** [comment]
@corpetty thanks for reporting this!
The issue is registered in mobile repo here https://github.com/status-im/status-react/issues/12569
