### ISSUE TITLE
Sometimes messages from blocked users remain in the chat

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#3473]
Open public chat
Block user
See if messages from that user are not in the chat anymore

**Expected result:**
No messages from the blocked user in the public chat

**Actual result:**
Sometimes messages are still in the chat after user has been blocked 

Master `Build #1339 (11-Sep-2021 21:52:06)`

<img width="1552" alt="Screenshot 2021-09-13 at 12 34 52" src="https://user-images.githubusercontent.com/82375995/133060730-fdf93b3e-ce0e-4122-881c-5d515b2bd73c.png">

**Comment by emizzle** [comment]
On master (`dc150005`), I cannot reproduce this at all. 

1. Create a new account.
2. Join a public chat (`#status-desktop`)
3. Block a random user (i chose a spammer)
4. The messages from that user were removed successfully.

Tested on macos 10.15.7.

Were there any other details of the reproduction steps that i may be missing?

**Comment by flexsurfer** [comment]
@emizzle just block more users, until you face the issue,  also try to change screens right after block is pressed
