### ISSUE TITLE
When a user views their own profile they have an option to block themselves and add themselves to their own contacts, these options should be removed

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3475]
When a user clicks on "My profile -->" here

![my_profile_entry_point](https://user-images.githubusercontent.com/22846356/133076579-33055275-9d1f-4023-8b5e-7082feb8ffcf.png)

They then see this dialogue that includes an option to block themselves (the "block user" button"), see screenshot below:  

![Why_would_a_user_want_to_block_themselves](https://user-images.githubusercontent.com/22846356/133076718-66ccee8d-ad6f-4c2f-8040-339c3485ffd9.png)

This option is not relevant to a user when they are viewing their own profile (as opposed to somebody else's profile) and should be removed.  Also the option to add oneself to one's own contacts list is also irreverent and should be removed

**Comment by anastasiyaig** [comment]
@John-44 i logged it already https://github.com/status-im/status-desktop/issues/3462
