### ISSUE TITLE
Can't turn off sounds for the notifications, toggling the setting off does not make an effect

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3477]
1. in settings, turn off the notification sound
2. receive a message in a public chat

<img width="1440" alt="Screenshot 2021-09-13 at 15 53 12" src="https://user-images.githubusercontent.com/82375995/133087012-9c4cde3b-830a-469a-b828-af90292269f8.png">

Actual result: Sounds are there even the setting is off

**Comment by iurimatias** [comment]
changing to high since there is no workaround apparently, and the spammer is driving me nuts

**Comment by iurimatias** [comment]
won't fix, turns out this is related to how the OS is configured. we can however consider making notifications on mentions the default
