### ISSUE TITLE
tooltip for the left hand nav settings icon says "profile".  It should say "settings"

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3481]
tooltip for the left hand nav settings icon says "profile".  It should say "settings"

![2021-09-13 14_20_04-Status Desktop](https://user-images.githubusercontent.com/22846356/133090969-a3e1d822-9ae9-4617-a871-57e0dafcd7a7.png)

**Comment by anastasiyaig** [comment]
fixed in master!
