### ISSUE TITLE
contact request showing in the activity center but not in the mutual requests section

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3483]
![Screen Shot 2021-09-13 at 9 35 42 AM](https://user-images.githubusercontent.com/176720/133093340-e48af8de-ff11-44df-85ae-78d706b9d138.png)

**Comment by emizzle** [comment]
I'm having a very hard time replicating this. In fact, what I'm seeing is that the contact request appears in the "contact requests" section in the channel list, but it does not appear in the Activity Center at all.

Could you outline the exact steps used to reproduce this?

I've tried reproducing with 0.3.0 beta and master (`dc150005`).

From Profile > Contacts > add new contact, I've tried the following things:
1. from an account with a registered ENS name > adding contact using a chat key
2. from an account with a non-ENS name > adding contact using an ENS name 
3. from an account with a non-ENS name > adding contact using a chat key
