### ISSUE TITLE
clicking on the group collapse arrow sometimes doesn't work

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3484]
clicking on the arrow to collapse/expanse the section doesn't always work, however clicking on the group name itself always works

![Screen Shot 2021-09-13 at 9 38 55 AM](https://user-images.githubusercontent.com/176720/133093812-ddd41889-deff-42a1-a8f2-1ace7b0b0f20.png)

**Comment by alexandraB99** [comment]
Please find fix in StatusQ [here](https://github.com/status-im/StatusQ/pull/412)
