### ISSUE TITLE
gif search sometimes not displaying results

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3487]
![Screen Shot 2021-09-13 at 9 44 35 AM](https://user-images.githubusercontent.com/176720/133094864-39cbfb3c-5691-4b27-9950-88ed71113818.png)

**Comment by iurimatias** [comment]
note: low priority vs other issues

**Comment by alaibe** [comment]
Reason: Just saw this in the log: Connection was closed before full request has been made

It looks like there is a timeout on a network error
