### ISSUE TITLE
Rendering issue in chat list when cursor is between community info and first category

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#3493]
Super weird, when I move the cursor out of the chat list and get closer to the community info, all chat names disappear:

<img width="387" alt="Screenshot 2021-09-13 at 15 59 05" src="https://user-images.githubusercontent.com/445106/133097244-1fd7dc73-2ff0-453a-b67e-f4df7a97ee98.png">
<img width="349" alt="Screenshot 2021-09-13 at 15 59 16" src="https://user-images.githubusercontent.com/445106/133097258-d213e04e-cad9-4a39-8d0c-5a5ab305f4a6.png">

**Comment by alaibe** [comment]
Also, not sure if related but the mouse cursor shows like it is expendable while it is not

**Comment by iurimatias** [comment]
I saw this but more like a flickering, do you see this consistently with some particular steps?

**Comment by alaibe** [comment]
@iurimatias yes I can see it consistently

**Comment by PascalPrecht** [comment]
I can't seem to reproduce this in StatusQ sandbox and also not in a test community that I've created inside Status.

Looks like this is only reproducible in communities that have many channels (+ categories) but need to verify

**Comment by PascalPrecht** [comment]
Okay, I've been debugging this for quite a while now and it seems this is related to the font we're using.

I've noticed that the only items that are disappearing are the ones that have a `font.weight: Font.Medium`.

Changing this to `Font.Normal` or even all to `Font.Bold` causes the flicker to go away.

There's a chance that maybe there's a QML bug when scaling the font.weight, but I can't say for sure. So one "solution" to this would be to switch to `Font.Normal`, but this makes the appearance significantly different.

/cc @simonricoo

**Comment by PascalPrecht** [comment]
Some more insights:

@pinebit looked into it as well. He found out that replacing `StatusBaseText` with `Text` removes the flicker. Also when setting `renderType: Text.NativeRendering` (which essentially renders a default font), the flicker is gone.

So this were indications that it's related to the font we're using specifically (`Inter`). I've tried different formats of the font (`.ttf` instead of `.otf`) and the flicker still exists.

I've even replaced the font with a completely different one (`Ubuntu`) and the the flicker also happens. 

But again, only when using `font.weight: Font.Medium`.

I still think there's a possibility that scaling the font doesn't work well:

> There's a chance that maybe there's a QML bug when scaling the font.weight, but I can't say for sure.

As a matter of fact, even though we're loading all different shapes of a font, we only use `baseFont` in StatusQ and then use `font.weight` to set the weight of the font. I don't think `QML` automatically knows that we're now interested in using the `-Bold` or `-Medium` variant of the font.

**Comment by PascalPrecht** [comment]
Tried another experiment to verify whether it's related to scaling:

Instead of setting `font.weight` based on a condition I'd directly set `font.family` instead and don't touch font-weight at all.

Unfortunately, this results in the text to never change its `font.weight`, even though the font family changes.

Running out of ideas here....

**Comment by PascalPrecht** [comment]
If we can't find a proper solution to this, the one way out we have is not using a custom font at all in that component. At least on mac, the difference isn't that big. So might be a feasible option.

Not sure how it is on other machines though.

BTQ: We've confirmed this flickering is happening on all major platforms (macOS, Windows, Linux)

**Comment by emizzle** [comment]
> Tried another experiment to verify whether it's related to scaling:
> 
> Instead of setting `font.weight` based on a condition I'd directly set `font.family` instead and don't touch font-weight at all.
> 
> Unfortunately, this results in the text to never change its `font.weight`, even though the font family changes.
> 
> Running out of ideas here....

To isolate the issue, (not completely clear if you've tried this already), have you tried simply using the medium font without font scaling and completely removing the condition so the font family never changes on load? Just to test it and see if the flickering no longer happens...

**Comment by PascalPrecht** [comment]
> have you tried simply using the medium font without font scaling and completely removing the condition so the font family never changes on load?

Using any font shape directly (bold, medium, regular etc), results in always the same shape, as if the font source aren't different. Only specifying `font.weight` will change them visually.

**Comment by PascalPrecht** [comment]
Some further experimentation:

Trying to reduce the number of fonts being loaded by StatusQ (at the moment we load three different fonts in ~5-7 different shapes), but that didn't change anything either.

**Comment by iurimatias** [comment]
this has been fixed in the meanwhile
