### ISSUE TITLE
Not seeing profile picture on profile section in main menu

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#3497]
See screenshot:
![image](https://user-images.githubusercontent.com/491074/133105708-f76b1195-aec1-41d0-8e29-689ff5481ddd.png)

**Comment by iurimatias** [comment]
@alaibe I see what you did there... 😆

**Comment by iurimatias** [comment]
@alaibe I see what you did there... 😆

**Comment by iurimatias** [comment]
this has been fixed
