### ISSUE TITLE
custom window title bar for windows

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3500]
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=133%3A12060

**Comment by pinebit** [comment]
@simonricoo what is the difference between the custom titlebar shown in Figma and the one provided by OS?
Also, I remember your message here https://discord.com/channels/624205794384281629/633669891999793165/884409631559012413
> Anything thats not behaving as native system is bug to me...

why do you want to make a difference here?

**Comment by pinebit** [comment]
As discussed in the meeting, we should keep it in backlog.

**Comment by iurimatias** [comment]
designs for this now are now outdated and there are no plans to add this title bar on windows
