### ISSUE TITLE
Community link unfurling is too slow

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3518]
Community link unfurling is too slow , it takes a while to get the invitiation to be rendered (sometimes more than 20 minutes)

1. share a community link for example https://join.status.im/c/0x02ba409c50c82a8d900223f4a188df03f888053c12b8651705650105687b37870a in any of chat
2. wait to have it resolved (so Join button or View appears)

<img width="1552" alt="Screenshot 2021-09-14 at 12 48 55" src="https://user-images.githubusercontent.com/82375995/133238228-ed75a256-54af-43cb-9061-35dd9b3587ff.png">

**Comment by iurimatias** [comment]
@anastasiyaig could you check if the history node improved this please

**Comment by anastasiyaig** [comment]
@iurimatias as result, i see that the link is not being resolved at all for sender, but it is resolved as a rocket on mobile

<img width="1396" alt="Screenshot 2021-09-21 at 15 44 58" src="https://user-images.githubusercontent.com/82375995/134174670-326a5280-9438-4977-a1d6-a7fd3231db6b.png">

Maybe it worth a separate issue

**Comment by anastasiyaig** [comment]
i just checked it with recent master and the link is still not resolved on desktop for sender. I will move the task back to backlog then
