### ISSUE TITLE
Activity center is showing wrong messages

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3522]
<img width="1552" alt="Screenshot 2021-09-14 at 13 37 55" src="https://user-images.githubusercontent.com/82375995/133243221-cb1f4aef-e60b-4348-917c-b479b9dc2692.png">

enable activity center
receive a contact request
open activity center

**As result:**

- [ ] incoming message is shown there and looks like contact request
- [ ] there are group chat notifications that should not be there 
- [ ] there are community invitations that should not be there

**Comment by iurimatias** [comment]
related #3483
