### ISSUE TITLE
Application is crashing after stay idle for a while

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3527]
It is not crashing to me, but @flexsurfer and @pinebit saw them 

`signal_controller.nim:51
self.status.events.emit(signal.signalType.event, signal)`

Probably related to group chats management (join / leave) but i am not clear yet.

**Comment by flexsurfer** [comment]
```
 pinebit — Yesterday at 12:02 PM
just 3 of 5
I noticed errors in the log saying "unhandled event message.delivered"
probably this is related given that it crashed in the signal handler
```

**Comment by pinebit** [comment]
![image](https://user-images.githubusercontent.com/6468078/133274607-7c647187-a46b-41de-b66a-d024c8d9abd8.png)
this is one of the locations that crashes and how I worked around it.
The other location is in `src/core/profile/core.nim`, similar code pattern.
The exact event that triggers this: "signal:message.new". Looks like when the event is emitted, the corresponding Args parameter is of a wrong type.
Someone how has better context on these events may be the right person to fix this properly.
