### ISSUE TITLE
user set as offline but showing as online

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3528]
to investigate: a user in communities set himself as offline, but still shows as online 5 hours later. it's possible that the reason is because we consider typing messages as being online, but could be something else going on

**Comment by michaelsbradleyjr** [comment]
I can't offer a diagnosis yet, but after experimenting I observed that a user's "network state" as displayed in another user's *Members* column in a community is often out of sync with the set state or actual state of the user:

Let's say there are two users: User1 and User2.

User1 sets their state as online and is not idle: User2 over time sees User1 transition from online to idle to offline (any order, seems non-deterministic). Those transitions don't happen quickly (usually): you have to setup the experiment and keep an eye on it.

Same thing when User1 sets their state as online and *is* idle.

Some thing when User1 sets their state as offline and is or is not idle.

Re: all the above, what User1 sees in their own *Members* column re: *themselves* can likewise be out of sync.

I intend to dig into the code, but clearly network state tracking re: signals coming from the network is completely out of whack re: what's expected to be displayed in own or others' *Members* column.

**Comment by michaelsbradleyjr** [comment]
> I intend to dig into the code...

Work on this issue has been shelved for now, will be reprioritized.
