### ISSUE TITLE
bug(ui): reaction/reply tooltip should have solid background when hovered above pinned message

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#3538]
1. In communities, go to a pinned message.
2. Hover over the first message *below* the pinned message
3. Expected: the reaction/reply tooltip should appear with a solid background colour
4. Actual: the reaction/reply tooltip appears with a mostly solid background, but the background of the pinned message is showing through the tooltip as well.

![imgur](https://imgur.com/QgSFxcA.png)

NOTE: likely this does not just affect communities, and should be looked at in other chats

**Comment by iurimatias** [comment]
fixed in latest master
