### ISSUE TITLE
Who has a green or yellow online status dot or who is in the Offline state seems a bit random + fixing the colour blindness issue + adding user selectable "Automatic" state

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3541]
Who gets a green or orange dot and who is displayed in the 'Offline' seems a bit random.  See this screenshot:

![2021-09-15 07_03_26-Status Desktop](https://user-images.githubusercontent.com/22846356/133380692-58db2be6-c5ba-4a0f-8895-f3bddb08fa86.png)

It's currently 07:04 in the morning UK time, and I see that Carl and Petty are (for example) currently marked with a green dot even though I would assume they aren't at their computers atm (given the current time), but Simon, Guy-Louis, Shivek and many others currently have a yellow/orange dot next to their name.  And even though I set my status to 'offline' in the status picker yesterday, this morning a green dot is still displayed next to my name.

@iurimatias @richard-ramos mentioned that the current rules are supposed to be: >5.5 minutes since last broadcast = yellow (you're probably offline), >7 minutes offline

A second issue is that it is difficult for people with common forms of colour blindness to distinguish between the green and yellow dots.  Also I'm not sure what value the current fine distinction between 'online' (green dot) and 'you're probably offline' (yellow dot) states provides to users.

----------------------------

Desired resolution:

Note : everything written below only pertains to the 'communities' functionality.  Public unmoderated group chats will be removed as soon as the communities functionality is ready, so any time we spend on specific functionality for public unmoderated group chats is time we've spent of functionality we are going to remove from the product.

- add an "Automatic" option to the bottom left user state selector.  This state would be the default state for all new users, and when 'Automatic' is selected a user's state would be displayed to other users in the Communities Members bar as either Online or Offline following the automatic online/offline rules we have implemented (e.g. anybody who is >5.5 minutes since their last broadcast is shown in the "Offline" category with a grey dot next to their name, and anybody who is <5.5minutes since their last broadcast is shown in the "Online" category with a green dot next to their name). 

- A user could then optionally set their state to either "Online" or "Offline" manually, and then the state the user has manually selected will always be displayed as long as that user's instance of status desktop or mobile is running.  If a user has manually set their state as 'Online' and they stop running running any Status desktop or mobile instance, then their state will revert to "Offline" after 5.5 minutes until the next time they launch their instance of Status desktop or mobile.

- remove the yellow dot 'you're probably offline' state

- ensure that anybody who is ">5.5 minutes since last broadcast" or who has manually selected the "Offline" state is shown in the "Offline" category with a *grey* dot next to their name.

- ensure that anybody who is "<5.5 minutes since last broadcast" or who has manually selected the "Online" state AND who has their Status mobile or desktop instance running is shown in the "Online" category with a *green* dot next to their name.

**Comment by John-44** [comment]
To clarify, a user should be able to select any one of the following three state settings:
- Online (means: user has manually set their status to online and has at least one instance of Status running somewhere)
- Offline (user has manually set their status to offline)
- Automatic (user is displayed as being Online if they have been active in any community or 1on1 or ad-hoc group chat in the last 5.5min, otherwise they are displayed as offline)

By default new users should be set to "Automatic".

**Comment by iurimatias** [comment]
@pinebit 

Summary
===

|                         | Public Chats                                            | Communities                                                   |
| ----------------------- | ------------------------------------------------------- | ------------------------------------------------------------- |
| Sidebar Title           | 'last seen'                                             | 'members'                                                     |
| Sorting                 | Single list sorted by last seen message from user                | Grouped by online & offline users, then sorted alphabetically |
| online/offline selector | no effect, sorting is implicit based on message history | has to reflect status set by user                             |
| Toggled  |   Off by default                                                      |   On by default                                                            |

Public chats
===

- The member list sidebar should be titled 'last seen'
- The member list is a single list, and should have no separation between 'online' & 'offline'
- The users in this member list CANNOT have online/offline indicator (i.e no green/yellow circles)
- The member list sidebar should have users sorted by 'last seen'.
- under the hood: 'last seen' is based on the message history, e.g if the last 3 messages are from users A, B, C, then the order in the member list is C, B, A. if user A posts a new message then he gets pumped up and it becomes A, C, B.
- The online/offline selector has no effect in the member list of public chats given this list and its sorting is calculated implicitly depending on the message history
- The member list sidebar for public chats should be toggled off by default

Communities
===

- The member list sidebar should be titled 'members'
- The member list should be grouped by 'online' & 'offline' users
- The users in this member list that are online should have the green circle, the users that are offline should be slightly faded out
- Within each online/offline section, users should be sorted by 1) users with ENS name 2) alphabetical
- If the user has 'online' as selected, then they should always show online in the communities member list. If the user has 'offline' as selected, then they should be shown offline for everyone within 5 minutes regardless of activity, even if the user sends new messages, if he has the offline state set, then they should not be shown as online.
- under the hood: a user that has the online state sends a ping to a special community channel, if the user selects offline state, then they stop sending this ping, and it's assumed by other clients the user went offline if they don't receive another ping within 5 minutes.
- The member list sidebar for public chats should be toggled on by default
