### ISSUE TITLE
Add a Blocked bar for blocked user profile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3547]
Current, when user is blocked:

<img width="1552" alt="Screenshot 2021-09-15 at 10 54 34" src="https://user-images.githubusercontent.com/82375995/133393628-29bb1d3f-5893-4ccc-bf18-a783d9478d56.png">

Expected: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?node-id=2426%3A0

![image](https://user-images.githubusercontent.com/82375995/133393698-7608ed98-436f-463d-ad1a-b434b7270aae.png)

**Comment by noeliaSD** [comment]
It has been created a status bar ui component and added into the Contacts/Blocked Contacts/View Profile view.
The following PRs have been created in order to close the task:
- [#513](https://github.com/status-im/StatusQ/pull/513)
- [#4392](https://github.com/status-im/status-desktop/pull/4392)
