### ISSUE TITLE
Small UI Issues

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#3552]
<img width="637" alt="Screen_Shot_2021-09-15_at_09_59_26" src="https://user-images.githubusercontent.com/52249767/133394491-af257a98-584a-4f24-80d4-b239447ce308.png">
<img width="532" alt="Screen_Shot_2021-09-15_at_09_59_14" src="https://user-images.githubusercontent.com/52249767/133397375-b02f7c23-e393-4108-b86b-65260ae4aa7a.png">

https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%E2%9A%99%EF%B8%8F-Settings%E2%8E%9CDesktop?node-id=2817%3A18621

Color for "online" and "offline" labels: Graphite 5 (#909090)

**Comment by Khushboo-dev-cpp** [comment]
@simonricoo you have mentioned that online and offline labels should be  Graphite 5 (#909090)
but design states background: #939BA1;

**Comment by Khushboo-dev-cpp** [comment]
I am removing the back arrow from the pinned popup but just wanted to mention that design still includes it - https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?node-id=4148%3A40713
