### ISSUE TITLE
As an admin, requests to join community are not the same on different devices

### ISSUE THREAD

**Issue by guylouis** [status-im/status-desktop#3553]
desktop: 0.3.0-beta 
mobile: 1.16.0 (20210913065934)

Note: fixing requests to join might not be highest priority since not part of phase 3

**Issue**: requests to join the communities are not the same on mobile and desktop**
- desktop
<img width="1231" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/11461437/133396390-7d82e6eb-c76e-457c-b74a-286795118290.png">
- mobile 
<img width="448" alt="Capture d’écran 2021-09-15 à 10 22 13" src="https://user-images.githubusercontent.com/11461437/133397726-124ed21a-3c9c-4125-a973-2c22ad0e1638.png">

**Comment by iurimatias** [comment]
this is quite possibly due to the history syncing

**Comment by iurimatias** [comment]
closing as this was due to history syncing which has been improved a lot since then
