### ISSUE TITLE
As an admin, I can't get rid of a request to join from someone who is already a member 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-desktop#3554]
desktop: 0.3.0-beta
mobile: 1.16.0 (20210913065934)

Note: fixing requests to join might not be highest priority since not part of phase 3

**Issue**: 
I am an admin of the community
I approved John request yesterday night on mobile, this morning I have still the request on desktop, and he is shown as a member. Problem does not solve even if I close status desktop and launch it again. The only way to make the request to go away is to approve him again

<img width="965" alt="Capture d’écran 2021-09-15 à 10 22 21" src="https://user-images.githubusercontent.com/11461437/133397945-8335315d-1e18-46f7-ae11-37837b877b3f.png">

**Comment by iurimatias** [comment]
this is likely due to the history syncing

**Comment by anastasiyaig** [comment]
i can't reproduce it now with latest master, but will look into it tomorrow as well to have a more wide gap in time

**Comment by saledjenic** [comment]
I've tried to reproduce this in following ways:
- created community in the desktop app, joined to it from the desktop app
- created community in the desktop app, joined to it from the mobile app
- created community in the mobile app, joined to it from the desktop app, and then login desktop app using seed phrase to accept request

Non of them had the issue form description.

**Comment by anastasiyaig** [comment]
I cant reproduce it in master
