### ISSUE TITLE
Close dropdown on the second click (multiple places)

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#3558]
https://user-images.githubusercontent.com/52249767/133422610-c7ad191a-2180-46f7-b7ac-de34bcfc670b.mov

https://user-images.githubusercontent.com/52249767/133422725-e53838d9-6301-4229-9914-8edd580bcc6c.mov

https://user-images.githubusercontent.com/52249767/133422750-6b63ceb9-131a-48c2-99a3-43986c1dfc27.mov

Might be on more places, needs more investigation @anastasiyaig

**Comment by anastasiyaig** [comment]
i feel it is known and will be handled in statusQ @simonricoo
