### ISSUE TITLE
Native emoji picker is no working on MacOS

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#3565]
control + CMD + space is shortcut on macOS to open native emoji picker (I use it all day every day across multiple apps on MacOS) this is not working anywhere besides the chat input field, though it is not working as expected as instead of opening a native emoji picker it opens the status emoji picker. Expected behaviour is as Discords (video).

Accepted criteria: Allow native emoji picker everywhere (all input fields and search inputs) across the Status App.

**Current behaviour (or not working)**
https://user-images.githubusercontent.com/52249767/133436870-cb16a1a9-52e5-4fba-b026-603324af2ab8.mov

**Expected behaviour**

https://user-images.githubusercontent.com/52249767/133436832-c62452c8-4422-46e6-a24d-928de3c27633.mov

**Comment by iurimatias** [comment]
related https://bugreports.qt.io/browse/QTBUG-70319

**Comment by elina2015** [comment]
I left a comment in the pull request https://github.com/status-im/status-desktop/pull/6016
