### ISSUE TITLE
Cannot run when building on Arch Linux

### ISSUE THREAD

**Issue by D4nte** [status-im/status-desktop#3568]
I am not able to launch the UI when building on Arch Linux.

Steps:

1. `git clone`
1. `sudo pacman -Sy qt5-base` (see the files available on the filesystem attached)
2. `make update`
3. `make -j 12`
4. `make run`

Output of (4):

```
▶ make run                          
Building: resources.rcc
Running: bin/nim_status_client
INFO [09-16|14:37:23.433] Status backend initialized               backend=geth version=0.86.5 commit=07651d4d
11867 resources added
Network Cache Dir:  "/home/froyer/src/status-im/status-desktop/Status/tmp/netcache"
QQmlApplicationEngine failed to load component
qrc:/main.qml: No such file or directory
INF 2021-09-16 14:37:23.833+10:00 Starting application...                    topics="main" tid=3675870 file=nim_status_client.nim:284
```
Output of `pkg-config`:

```
▶ pkg-config --variable=libdir Qt5Core               
/usr/lib
```
[qt5-base-files.txt](https://github.com/status-im/status-desktop/files/7174958/qt5-base-files.txt)

**Comment by pinebit** [comment]
Please make sure you have Qt `5.14.2`, we require that exact version. You can run `qmake --version` to see your current Qt version.

The default Qt version installed with pacman may have a wrong version and may have WebEngine component missing, but it is required for the app.
The best and the most reliable way would be to use Qt Online Installer, that will download and install the exact version of Qt (5.14.2) and where you are supposed to enable checkbox "WebEngine". Do not forget to uninstall qt5-base. 

Alternatively you can build the app with Docker, please check `ci/README.md` for the instructions.

**Comment by D4nte** [comment]
Indeed, 5.15.2 is only available through pacman. Will try to install qt5 manually.

**Comment by pinebit** [comment]
> Indeed, 5.15.2 is only available through pacman. Will try to install qt5 manually.

Please install `5.14.2` _and_ set checkbox "WebEngine" (Qt component).

**Comment by iurimatias** [comment]
@D4nte did that work?

**Comment by D4nte** [comment]
Was off and did not try yet. Happy to close and revert if it does not help.

**Comment by D4nte** [comment]
So actually qt 5.14.2 has a bug with gcc11, fixed in qt6.

Some patches are available but I haven't tested yet. See https://github.com/archlinux/svntogit-packages/blob/6377ce26f3d50c0ab92d3a239e13c549ca89f519/qt5-base/repos/extra-x86_64/PKGBUILD and https://aur.archlinux.org/packages/qt5-xcb-private-headers-git/#comment-824148 (numeric bug).

I did not try to use the qt runner because I don't want to create an account.

Will look in more details at a later stage.

Is there an intent to upgrade to a more recent version of qt?

**Comment by D4nte** [comment]
See latest update above

**Comment by iurimatias** [comment]
we will be updating to qt6
