### ISSUE TITLE
Community type selection is gone

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3572]
<img width="1344" alt="Screenshot 2021-09-16 at 15 53 53" src="https://user-images.githubusercontent.com/82375995/133615631-c64fd530-70ea-4390-93b7-35a3c9be814c.png">

**Expected:** there is a selection of community types which should include 2 options for now

<img width="1344" alt="Screenshot 2021-09-16 at 15 54 54" src="https://user-images.githubusercontent.com/82375995/133615791-09c4a733-cf91-419c-8aa8-646a13cbc4f2.png">

**Comment by iurimatias** [comment]
should have been fixed by #3513
