### ISSUE TITLE
Refactor Makefile

### ISSUE THREAD

**Issue by pinebit** [status-im/status-desktop#3573]
Check this PR comments: https://github.com/status-im/status-desktop/pull/3545

**Comment by jakubgs** [comment]
Build targets should probably start with platforms:
```
make linux-deb
make linux-app
make linux-run
make windows-zip
make windows-exe
make windows-run
make macos-dmg
make macos-run
```
So you can get better tab completion with `make linux-<tab>`.

**Comment by iurimatias** [comment]
closing due to upcoming new makefile
