### ISSUE TITLE
white screen when scrolling down

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#3589]
https://user-images.githubusercontent.com/11790366/133775125-8fe2172e-a68c-4918-860a-ea7b723a32e0.mov

**Comment by iurimatias** [comment]
@flexsurfer what mouse do you have? I have a similar issue with my mouse and it seems there is no easy fix, it's a issue with Qt and some mouses that scroll too fast

**Comment by flexsurfer** [comment]
@iurimatias its an apple touchpad, this happens only when there is a link preview image in the middle of the scrolling content

**Comment by qoqobolo** [comment]
> @flexsurfer what mouse do you have? I have a similar issue with my mouse and it seems there is no easy fix, it's a issue with Qt and some mouses that scroll too fast

Faced the same issue. I use Logitech MX Master 3

**Comment by dlipicar** [comment]
Also seeing this when using the scroll wheel of my MX Master 2S. Tried toggling a couple of scroll-related settings in the Logitech app, but it did not improve the behavior.
If its any help, [qBittorrent](https://www.qbittorrent.org/) is a Qt application as well, scrolling there seems to work fine in all the screens I could test.

**Comment by glitchminer** [comment]
I have an MX Master 3 and get the same issue appearing on Mac. Setting the scrollwheel speed to the very slowest option in options+ app showed some slight improvement for the issue (but also was too slow generally). It makes me think it's related to the resolution/speed of the scrollwheel. I also have a very simple old wired mouse which does not have this issue.

**Comment by noeliaSD** [comment]
Moved to next milestone due to team capacity and priorities.

**Comment by iurimatias** [comment]
can no longer replicated this on a MX3
