### ISSUE TITLE
Clicking a notification in activity center does not redirect u to that message in chat

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3592]
1. enable activity center
2. join a community
3. send some messages there
4. receive a mention or reply to your message (to have something in activity center)
5. send more messages so the chat history becomes scrollable
6. open AC and click the notification

**Expected result:** it should redirect u to the exact chat and point to the exact message that u clicked from activity center

https://user-images.githubusercontent.com/82375995/133784021-210539cf-ef5d-4331-978a-07cf5433d231.mov

**Comment by iurimatias** [comment]
I can replicate this in some cases, seems to happen for messages not loaded, the fix for this involves doing whatever was done for the search
