### ISSUE TITLE
Scrolling of the chat with code blocks and reactions is repetitive

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3594]
When i try to scroll the chat which has code blocks as messages and messages with reactions, in some cases scrolling is infinite loop getting back to the same messages again and again instead of going down to the list of messages

https://user-images.githubusercontent.com/82375995/133786301-72b73b55-ec8f-43c7-934c-02801bd6c071.mov

**Comment by saledjenic** [comment]
@anastasiyaig please will you help with this one, would be good if we would have some channel where this is always reproducible, or some steps how to reproduce it for sure. I was trying and managed to reproduce it when I scroll fast, but not every time, actually more like rare.

Just as a track, it may be same/similar to #3327
