### ISSUE TITLE
Can't select text of a notification is activity center

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3595]
Can't select the content of the notification in activity center

<img width="1552" alt="Screenshot 2021-09-17 at 16 01 45" src="https://user-images.githubusercontent.com/82375995/133786762-862c1332-8124-41c6-9d75-ce762306cbd7.png">

**Comment by MishkaRogachev** [comment]
Fixed here: https://github.com/status-im/status-desktop/pull/8094
