### ISSUE TITLE
.deb deployment

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#3601]
Requires
- https://github.com/status-im/status-desktop/pull/3512

TODO:
- [ ] Add changelog and copyright file to .deb
- [ ] Verify .deb file with lintian
- [ ] GPG sign dpkg
- [ ] Create .asc (ASCII-armored) file
- [ ] Create apt repository
- [ ] Publish .deb dockerfile 
- [ ] Configure jenkins to build .deb on PRs / releases

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5747
