### ISSUE TITLE
Resend state for messages looks broken

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#3606]
Here's a message (reply) which didn't go through.
After restart of the application, the message showed up again, but with the "resend" state bleeding into the message text:
<img width="837" alt="Screenshot 2021-09-20 at 10 56 51" src="https://user-images.githubusercontent.com/445106/133978023-135583ef-3fa0-4221-9075-1a5522cbf9c2.png">

**Comment by emizzle** [comment]
On master https://github.com/status-im/status-desktop/commit/0c73febf2c8703b0a9b6a377bb5ac7d13b582ea3, I am seeing the `Resend` link in the correct place. I have recreated the scenario above by sending the same messages in the `#test` channel, and set the `Retry` (child component of `CompactMessage`) component to always be visible. This is what it looks like on macos:
![imgur](https://imgur.com/dx40gHC.png)

**Comment by emizzle** [comment]
Oh, it's light theme only:
![imgur](https://imgur.com/UgA57rM.png)

**Comment by emizzle** [comment]
With #3625, the "Resend" link nows like:
![Imgur](https://imgur.com/ysfj0OU.png)
![Imgur](https://imgur.com/a0JJOhY.png)
![Imgur](https://imgur.com/rzgknCl.png)
![Imgur](https://imgur.com/bb4dirS.png)
