### ISSUE TITLE
Open last channel viewed after navigating to other tab

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#3607]
## Current
When navigating away from a community chat to any other tab (e.g. browser to open a channel, settings/profile or wallet) and coming back, the community chat opens on the first channel in the list of community channels

## Expected
When navigating away from a community chat to any other tab and coming back, the community chat opens on the last channel viewed in the community chat.

**Comment by alaibe** [comment]
I think this has been fixed via: https://github.com/status-im/status-desktop/pull/3597 @Khushboo-dev-cpp

**Comment by iurimatias** [comment]
duplicate of 3486
