### ISSUE TITLE
Application logs should be configurable for master / release builds

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3609]
Enhances https://github.com/status-im/status-desktop/pull/3534:

to the logs feature added in the PR above, please add the following feature: 

- [ ] ability to switch (enable) on / off logs for develop and release builds (to be aligned with mobile). Release builds should not contain logs for security purposes
- [ ] ability to select log level

**Comment by richard-ramos** [comment]
It could be nice to be able to select the log level too

**Comment by anastasiyaig** [comment]
@richard-ramos i will add it as another ticket as well

**Comment by endulab** [comment]
@anastasiyaig 
Is the UI functionality to change log level, within the scope of the ticket ?
![image](https://user-images.githubusercontent.com/61889657/159917575-d679bfa4-1004-42b0-965d-b08da03c7e09.png)

**Comment by endulab** [comment]
After some discussions, UI will not be part of this task.
