### ISSUE TITLE
Stop archiving logs by default and add an advanced setting to keep them

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3610]
Enhances #3534:

edit: see comment for new wanted behaviour https://github.com/status-im/status-desktop/issues/3610#issuecomment-1525759780

we need to inform user that the logs are being created automatically from the moment when app starts and the app starts "eating" free space (i am not sure how long the logs could be but anyway)

It is important i think.

**Comment by anastasiyaig** [comment]
@John-44 @iurimatias @benjthayer do we want to have this? Perhaps to incorporate to onboarding? Or just close as not needed?

**Comment by caybro** [comment]
Ideally we would "rotate" (for example https://pkg.go.dev/github.com/yieldr/go-log/log/logrotate) the logs after some time; it's unacceptable imho the logs are eating the disk space forever.

**Comment by iurimatias** [comment]
adding this to 0.13 and increasing priority because we do need to rotate the logs as the diskspace used by the current logs becomes a huge problem over time and we need to fix this before the mvp

**Comment by jrainville** [comment]
> So it is correct to assume that with this change the logs will do something FIFO (first in first out) like?

Yes

> the size of the logs will be bounded

It is already the case. When the log file reaches 105MB, it archives it and starts a new file. Though I guess you mean the number of archive files will be bounded, so after, let's say, 3 archives files, we just delete the previous one.

> we won't need to add anything to the app UI?

As you wish. We can still inform the user that up to, again for example, 300MB of logs will be saved on disk, but I have no idea where we would inform that

**Comment by caybro** [comment]
> As you wish. We can still inform the user that up to, again for example, 300MB of logs will be saved on disk, but I have no idea where we would inform that

Here?

![image](https://user-images.githubusercontent.com/5377645/234873208-a712d643-4791-4899-8cac-1c95edd18418.png)

**Comment by John-44** [comment]
> As you wish. We can still inform the user that up to, again for example, 300MB of logs will be saved on disk, but I have no idea where we would inform that

Probably better to just have a reasonable max size for logs, and not give the user the option to switch logs on or off or change the log size.  Best config. is no conifg ;-)

**Comment by John-44** [comment]
> > As you wish. We can still inform the user that up to, again for example, 300MB of logs will be saved on disk, but I have no idea where we would inform that
> 
> Here?
> 
> ![image](https://user-images.githubusercontent.com/5377645/234873208-a712d643-4791-4899-8cac-1c95edd18418.png)

Yup somewhere in advanced is the right place to give users access to export the logs

**Comment by iurimatias** [comment]
@John-44 @John-44 IMO we should delete the archive logs automatically. perhaps this could be overriden on the UI too if the user so wants. but they shouldn't be kept around by default.

**Comment by John-44** [comment]
> @John-44 @John-44 IMO we should delete the archive logs automatically. perhaps this could be overriden on the UI too if the user so wants. but they shouldn't be kept around by default.

Agreed, that's what I was trying to say by mentioning we should do some FIFO-like scheme
