### ISSUE TITLE
Abnormal CPU usage and slowness

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3626]
**Spotted in:** `Build #1391 (20-Sep-2021 21:34:52)`

When typing in anything in a chat box, the input is very slow, also there is abnormal CPU usage when doing so. 
It is getting worse when using mentions.

<img width="1248" alt="Screenshot 2021-09-21 at 10 30 31" src="https://user-images.githubusercontent.com/82375995/134130432-48c57176-c5de-4be6-b28c-ec0867b19bd7.png">

https://user-images.githubusercontent.com/82375995/134130266-dc552868-26ca-49a6-9ec0-8fdf6a9d7f95.mov

maybe be related to https://github.com/status-im/status-desktop/pull/3555

**Comment by Khushboo-dev-cpp** [comment]
not sure but could the added logging in the mailservers.nim causing the lag ?

INF 2021-09-22 11:42:29.625+02:00 ping                                       topics="mailserver-interaction" tid=108353 file=mailservers.nim:11 rpc_method=mailservers_ping addresses="@[\"enode://e85f1d4209f2f99da801af18db8716e584a28ad0bdc47fbdcd8f26af74dbd97fc279144680553ec7cd9092afe683ddea1e0f9fc571ebcb4b1d857c03a088853d@47.244.129.82:443\", \"enode://606ae04a71e5db868a722c77a21c8244ae38f1bd6e81687cc6cfe88a3063fa1c245692232f64f45bd5408fed5133eab8ed78049332b04f9c110eac7f71c1b429@47.75.247.214:443\", \"enode://44160e22e8b42bd32a06c1532165fa9e096eebedd7fa6d6e5f8bbef0440bc4a4591fe3651be68193a7ec029021cdb496cfe1d7f9f1dc69eb99226e6f39a7a5d4@35.225.221.245:443\", \"enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@178.128.142.26:443\", \"enode://30211cbd81c25f07b03a0196d56e6ce4604bb13db773ff1c0ea2253547fafd6c06eae6ad3533e2ba39d59564cfbdbb5e2ce7c137a5ebb85e99dcfc7a75f99f55@23.236.58.92:443\", \"enode://2c8de3cbb27a3d30cbb5b3e003bc722b126f5aef82e2052aaef032ca94e0c7ad219e533ba88c70585ebd802de206693255335b100307645ab5170e88620d2a81@47.244.221.14:443\", \"enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@178.128.142.54:443\", \"enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443\", \"enode://ee2b53b0ace9692167a410514bca3024695dbf0e1a68e1dff9716da620efb195f04a4b9e873fb9b74ac84de801106c465b8e2b6c4f0d93b8749d1578bfcaf03e@104.197.238.144:443\"]" timeoutMs=500 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":[{\"address\":\"enode://e85f1d4209f2f99da801af18db8716e584a28ad0bdc47fbdcd8f26af74dbd97fc279144680553ec7cd9092afe683ddea1e0f9fc571ebcb4b1d857c03a088853d@47.244.129.82:443\",\"rttMs\":379,\"error\":null},{\"address\":\"enode://30211cbd81c25f07b03a0196d56e6ce4604bb13db773ff1c0ea2253547fafd6c06eae6ad3533e2ba39d59564cfbdbb5e2ce7c137a5ebb85e99dcfc7a75f99f55@23.236.58.92:443\",\"rttMs\":204,\"error\":null},{\"address\":\"enode://2c8de3cbb27a3d30cbb5b3e003bc722b126f5aef82e2052aaef032ca94e0c7ad219e533ba88c70585ebd802de206693255335b100307645ab5170e88620d2a81@47.244.221.14:443\",\"rttMs\":383,\"error\":null},{\"address\":\"enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@178.128.142.94:443\",\"rttMs\":81,\"error\":null},{\"address\":\"enode://ee2b53b0ace9692167a410514bca3024695dbf0e1a68e1dff9716da620efb195f04a4b9e873fb9b74ac84de801106c465b8e2b6c4f0d93b8749d1578bfcaf03e@104.197.238.144:443\",\"rttMs\":204,\"error\":null},{\"address\":\"enode://606ae04a71e5db868a722c77a21c8244ae38f1bd6e81687cc6cfe88a3063fa1c245692232f64f45bd5408fed5133eab8ed78049332b04f9c110eac7f71c1b429@47.75.247.214:443\",\"rttMs\":379,\"error\":null},{\"address\":\"enode://44160e22e8b42bd32a06c1532165fa9e096eebedd7fa6d6e5f8bbef0440bc4a4591fe3651be68193a7ec029021cdb496cfe1d7f9f1dc69eb99226e6f39a7a5d4@35.225.221.245:443\",\"rttMs\":203,\"error\":null},{\"address\":\"enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@178.128.142.26:443\",\"rttMs\":80,\"error\":null},{\"address\":\"enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@178.128.142.54:443\",\"rttMs\":81,\"error\":null}]}"
INF 2021-09-22 11:42:29.626+02:00 Connecting to mailserver                   topics="mailserver model" tid=108353 file=model.nim:84 enode=bd6ebe5ae838fcfaf3a49@178.128.142.54:443
INF 2021-09-22 11:42:29.626+02:00 Mailserver changed                         topics="mailserver model" tid=108353 file=model.nim:95 enode=enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@178.128.142.54:443
DBG 2021-09-22 11:42:29.626+02:00 callPrivateRPC                             topics="rpc" tid=108353 file=core.nim:20 rpc_method=wakuext_updateMailservers
INF 2021-09-22 11:42:29.629+02:00 update                                     topics="mailserver-interaction" tid=108353 file=mailservers.nim:15 rpc_method=wakuext_updateMailservers peer=enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@178.128.142.54:443 response="{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":null}"

I  noticed a lag with the pull today and after the logs are printed it performs okay again
