### ISSUE TITLE
The @mention emblem isn't being displayed on the channel list 

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3630]
See this screenshot from the designs, the blue circle with the "1" in it informs the user that they have one @mention in the #beginners channel

![2021-09-21 10_37_20-Window](https://user-images.githubusercontent.com/22846356/134148623-f51ca4b4-f2d9-488a-b46c-0b95a99fc8a8.png)

However it looks like this is currently broken, the @mention emblem only appears on the *Community* icon (correct) but doesn't appear next to the channel name as shown in the design above (incorrect).  See screenshot below, here I've been @mentioned in the #test-channel and I haven't visited this channel since I was @mentioned so the @mention emblem should be shown next to this channel name but it isn't.

![2021-09-21 10_26_49-Window](https://user-images.githubusercontent.com/22846356/134149133-1b51f6b3-5f28-4e8c-801d-779fd5c62e69.png)

-------------
Desired resoltuion:

- @mention emblems should be shown both on the community icon and after the channel name.

**Comment by PascalPrecht** [comment]
@saledjenic I think you've fixed that a long time ago no?

**Comment by saledjenic** [comment]
> @saledjenic I think you've fixed that a long time ago no?

Yes in some point I was working on something like that, actually the issue I was working on was about not clearing counter badge when you mark a message in Activity Center as read. It was ticket #2788.

**Comment by iurimatias** [comment]
can confirm still happens in latest master

**Comment by saledjenic** [comment]
This was mostly handled in the `base_bc`, I rechecked it and improved it a bit more. Here is a [video](https://drive.google.com/file/d/1JUDp9jOBALbLhi-cByh2Ef7bOo4E33Ne/view?usp=sharing) where you can see the test in my case. I used mobile app and firstly added normal messages in community, for both channels that's the reason why blue dot was added. Then I opened community where after marking second channel in the community blue dot for community went away. Then I tested mentions and you may see in the video what is mentions behaviuor.
