### ISSUE TITLE
Right click action items menu is misplaced

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3637]
1. open the app and join several chats
2. right click the one at the bottom of the list
3. pay attention to the placement of actions menu

As result, the menu is not glued to the selected chat

<img width="1557" alt="Screenshot 2021-09-21 at 16 22 37" src="https://user-images.githubusercontent.com/82375995/134178641-61e33578-006a-4c29-a339-641cf826a951.png">

**Comment by PascalPrecht** [comment]
This will be fixed by https://github.com/status-im/StatusQ/pull/426 with the next release of StatusQ
