### ISSUE TITLE
Keychain storage selection modal renders very slow

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3638]
<img width="1344" alt="Screenshot 2021-09-21 at 11 13 40" src="https://user-images.githubusercontent.com/82375995/134181717-a93aec77-c931-4b87-b9c1-443675ade309.png">

When the app is launched there is a dialog for keychain storage selection . The dialog seems to be very slow loading, also buttons are not responsive for a while, I even saw a ball of death when clicking here and there at the modal.

**Expected:** the buttons are responsive, hovering them shows another color (clealry displaying the button is hovered), no ball of death , the application is not stuck

**Comment by iurimatias** [comment]
I don't see this happening anymore in latest master
