### ISSUE TITLE
GIF is not being resolved in Timeline

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3641]
Posting a GIF to timeline is not being resolved to an actual GIF

<img width="1552" alt="Screenshot 2021-09-21 at 17 13 11" src="https://user-images.githubusercontent.com/82375995/134187076-9cf5904d-b5c0-4cd2-9181-1e028aec1d7a.png">

**Comment by alaibe** [comment]
Currently in the timeline, we don't use the same renderer as in the traditional chat, it only support image. Is there any reason to not use the same rendere as normal chat? @iurimatias @anastasiyaig

**Comment by alaibe** [comment]
Kinda related, do you know what is compactMessage, I can see this settings in multiple place but no way to change that, and when set to false, the message don't display well.
