### ISSUE TITLE
refactor: contacts

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#3651]
Once PR https://github.com/status-im/status-go/pull/2372/ is merged, update desktop code to use `added` and `blocked` attributes instead of `systemTags`

**Comment by michaelsbradleyjr** [comment]
Is this related or potentially related to #3529?

**Comment by richard-ramos** [comment]
It's possible!

**Comment by flexsurfer** [comment]
@richard-ramos status-im/status-go#2372  is ready to be merged, should I merge or should I wait for the dekstop implementation ?

**Comment by richard-ramos** [comment]
Can it wait to be merged on monday? I can work on this changes on desktop today

**Comment by flexsurfer** [comment]
sure, will wait then
