### ISSUE TITLE
Can't jump to a message from search results

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3662]
```
DBG 2021-09-22 15:08:45.791+03:00 callPrivateRPC                             topics="rpc" tid=2198815 file=core.nim:20 rpc_method=wakuext_chatPinnedMessages
qrc:/app/AppLayouts/Chat/ChatColumn.qml:115: TypeError: Cannot call method 'scrollToMessage' of undefined

```
1. open a chat with history
2. search for any relevant message
3. click any message from search results

<img width="1440" alt="Screenshot 2021-09-22 at 15 11 37" src="https://user-images.githubusercontent.com/82375995/134341332-342c0d72-fe6a-4104-b9be-83f49c46806b.png">

**Comment by PascalPrecht** [comment]
This was fixed with https://github.com/status-im/status-desktop/pull/3681
