### ISSUE TITLE
Can't load GIFs 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3663]
`NF 2021-09-22 15:58:20.681+03:00 getPinnedMailserver                        topics="mailserver-interaction" tid=2198814 file=settings.nim:101 fleet=eth.prod result=
qrc:/shared/status/StatusGifColumn.qml:70:13: QML AnimatedImage: Error Reading Animated Image File https://media.tenor.com/images/772893c362a469d95f42e6443df07995/tenor.gif
`

<img width="1552" alt="Screenshot 2021-09-22 at 15 58 53" src="https://user-images.githubusercontent.com/82375995/134347893-53468322-df1a-4b15-88ff-781a9b95a22f.png">

**Comment by iurimatias** [comment]
issue is fixed
