### ISSUE TITLE
Message history for #desktop channel lost, unable to fetch previous messages

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3664]
Last night I think Status desktop may have crashed my computer, and in the morning I had to relaunch Status desktop.  When I navigated to the Status Internal community, I found that the previous message history for my #desktop channel had disappeared.  

See the screenshot from #desktop below.

![2021-09-22 14_12_05-Status Desktop](https://user-images.githubusercontent.com/22846356/134350247-137ea6da-6309-4358-afe7-93c63265f1a9.png)

Clicking on "Fetch more messages" brings up a spinner and then nothing happens.  I've now been periodically clicking on "Fetch more messages" for over 5 hours, and the messages still do not load, so this issue is probably not just a syncing delay.

-----------------------------------
Desired resolution:

- Previously fetched messages should never be lost.  It is critical that we fix this issue before we widen dogfooding, because as we have not yet built the 'message history service' we (Status internal folks) will be relying on our local copies of the message history in each channel to be able to scroll back up to previous conversations, search the chat history, etc...  Until the 'message history service' is built, once the chat history is older than 30 days, if it is lost from local clients there is no mechanism to retrieve this history.

- Fix the issue that is causing "Fetch more messages" to fail

**Comment by iurimatias** [comment]
this should have been fixed in the meanwhile
