### ISSUE TITLE
Sandbox doesn't build on Linux machines

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#3674]
./sandbox/spellchecker.cpp:3:10: fatal error: hunspell.hxx: No such file or directory
3 | #include "hunspell.hxx"
| ^~~~~~

Need to add checks OS checks to resolve these errors

**Comment by alaibe** [comment]
@Khushboo-dev-cpp isn't it a duplicate of this one: https://github.com/status-im/StatusQ/issues/413 ?

**Comment by Khushboo-dev-cpp** [comment]
oh wait I didn't know this was already reported! will close it

**Comment by Khushboo-dev-cpp** [comment]
I will just add an extra comment there and close it. Cause there the reported error is different @alaibe

**Comment by Khushboo-dev-cpp** [comment]
duplicate of status-im/StatusQ#413
