### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by closewall** [status-im/status-desktop#3700]
If someone adds me as a contact, can they see my IP address?

**Comment by iurimatias** [comment]
no, it's p2p and encrypted, the contact request is just like any other message and the peers can't decrypt it and even know it's a contact request and to who it's intended for. for more details please see https://specs.status.im/

**Comment by iurimatias** [comment]
note: you can get even better privacy (at the cost of bandwith) by going to profile -> advanced and setting the bloom filter level
