### ISSUE TITLE
Enable bandwidth stats 

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#3745]
On mobile it was requested to disable the bandwidth stats signal since it consumes resources on the js thread.
https://github.com/status-im/status-go/pull/2391, so once desktop uses that status-go version, bandwidth stats are going to be disabled by default.

To reenable them we need to add the following setting in the node config, and logout/login. This is something that can be done on a toggle.
```js
...
"ShhextConfig": {
    "BandwidthStatsEnabled": true
  }
...
```
Another possibility suggested by @cammellos is to modify status-go to have two API endpoints to enable/disable the bandwidth stats, and once the user enters the node management section, enable the stats, and disable them on leave. If this option is implemented, please remove the `BandwidthStatsEnabled` setting from status-go

**Comment by iurimatias** [comment]
duplicate of https://github.com/status-im/status-desktop/issues/4990
