### ISSUE TITLE
Welcome screen is missing the picture

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3753]
<img width="1552" alt="Screenshot 2021-10-01 at 12 58 50" src="https://user-images.githubusercontent.com/82375995/135601796-f262f28a-a40c-4fe9-a153-89f06d736aee.png">

**Expected:**
![image](https://user-images.githubusercontent.com/82375995/135602038-1b0a1b95-6ead-4d03-966e-255325663305.png)

**Comment by alexandraB99** [comment]
Issue not reproducible in master
![keys.png](https://images.zenhubusercontent.com/60e32e06eddded5b0a4e2749/c06709c7-78ef-4cbc-bedd-be80ca3acfa3)

**Comment by anastasiyaig** [comment]
it was logged almost 2 months ago :D and yes, it is fixed already by @saledjenic
