### ISSUE TITLE
[Windows] Crash on creating new account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3754]
1. install master Build 1139 (30-Sep-2021 14:37:23)
2. open the app and select Generate new keys
3. select the very last item in the list and proceed

As result, the app is being closed (crashed?). No logs unfortunately , also it is not crashing on Mac

**Env:**  `Windows 11, Parallels build (VM)`

**Comment by anastasiyaig** [comment]
Does not happen all the time though, hard to reproduce, checking

**Comment by anastasiyaig** [comment]
was able to reproduce it today. I installed recent master (having already a data folder) and wait for a while with the app open. It closed without any error message.

**Comment by iurimatias** [comment]
fixed in latest master
