### ISSUE TITLE
Contact request reappears even it was declined

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3756]
**Precondition:** u need 2 devices, ether separate instances (VM machine can help), or desktop + mobile. Enable Activity Center as well. 

1. as user A, copy a chat key of user B
2. as user A, click + button -> start new chat
3. as user A, paste the chat key and open 1x1 chat with user B
4. click Send contact request button
5. as user B, on chat tab receive incoming Contact Request
6. as user B, open this request and click Decline
7. as user A, send a message to the same chat with user B

As result, the contact request re-appears for User B. **NOTE:** could reappear after a while, need to wait

<img width="1433" alt="Screenshot 2021-10-01 at 16 29 48" src="https://user-images.githubusercontent.com/82375995/135628258-bbff58bd-b985-4a99-a799-60f6a303e728.png">

**Expected result:**

1. if user B declined the contact request, user A should not be able to send messages to this chat
2. if user B declined the contact request, user A should see a placeholder saying that the contact request was not approved

<img width="726" alt="Screenshot 2021-10-01 at 16 38 03" src="https://user-images.githubusercontent.com/82375995/135629579-7dac8c06-ff7e-4ba7-8bf6-4c0ad3aed775.png">

**Comment by iurimatias** [comment]
tried these steps in latest master, it doesn't happen anymore
