### ISSUE TITLE
Keychain storage selection modal shows up even when password is wrong

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#3800]
<img width="1344" alt="keychain_modal" src="https://user-images.githubusercontent.com/31625338/136796314-4ef74199-53fd-48f0-8ec5-b194cfa36452.png">

**Comment by saledjenic** [comment]
@anastasiyaig I am not able to reproduce this, this is an old issue and most likely fixed in meantime. Checked with @alexandraB99 she is not able to reproduce it as well. Please try it as well, if you cannot reproduce it just close it, if you can, please share the steps.
