### ISSUE TITLE
Move Wallet to new architecture

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3807]
1. create base
2. add subtasks to this issue
3. work in one or more subtasks

**Comment by alaibe** [comment]
- [ ] create new structure
- [ ] copy implementation to new structure
- [ ] move qml call to new path (needs https://github.com/status-im/status-desktop/pull/3778)
- [ ] ensure browser part using wallet code has been migrated
- [ ] delete old wallet nim code
