### ISSUE TITLE
Identify new chats

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#3888]
Related PRs:
- https://github.com/status-im/status-go/pull/2384
- https://github.com/status-im/status-react/pull/12654

**Comment by jrainville** [comment]
Copy design from mobile here https://github.com/status-im/status-mobile/issues/10087

**Comment by iurimatias** [comment]
This seems to be an outdated issue. The current app identifies new chats with a dot which seems to be the desired behaviour.

![Screen Shot 2023-04-27 at 10 33 53 AM](https://user-images.githubusercontent.com/176720/234896759-27c2c488-600d-44e6-9058-e9f9019a732a.png)
