### ISSUE TITLE
[refactoring/base_01] can't relogin to newly created account on windows

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3974]
1. create an account on windows build
2. sign out and quit
3. open the app again and login to the newly created account

As result, the app is closed (crashed). Nothing useful in logs. 

https://drive.google.com/file/d/1_I4_ipO2xLbdVX34pmxx31CtXWOwRLiz/view?usp=sharing

**Build info:** 

Build #2 (28 Oct 2021, 15:42:03)

https://ci.status.im/job/status-desktop/job/branches/job/windows/view/change-requests/job/PR-3949/2/

**Comment by jrainville** [comment]
@anastasiyaig I couldn't reproduce on a newly built base_01.
Did you have any channel or changed setting? I didn't see any from your screen capture, but I'm asking just in case

**Comment by anastasiyaig** [comment]
@jrainville that could probably related to general crash, that was fixed in PR 4008 i guess. checking now

**Comment by anastasiyaig** [comment]
@jrainville seems it is not reproducible anymore, i am closing it
