### ISSUE TITLE
[refactoring/base_01] moving channels between categories, does not move them and also changes their colors

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3985]
![upload_e3f1bb1939d976fd72c30814b6d9a066](https://user-images.githubusercontent.com/176720/139673695-d4de99e7-ced7-48fc-a28c-22d0e420a99c.png)
![upload_a149fbddac06ea25b51a0471b434cafc](https://user-images.githubusercontent.com/176720/139673708-2cfa91cf-68af-43b8-870c-b53d1a92df4b.png)

**Comment by PascalPrecht** [comment]
Dragging channels across categories isn't implemented yet. There was some work in progress + a potential blocker in status-go.
However, the channel colors are off indeed. Community channels should inherit the community color, which is done in: https://github.com/status-im/status-desktop/pull/4027
