### ISSUE TITLE
[refactoring/base_01] deleting a channel does not work

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4001]
it worked for me on the second try

![desktop_stack](https://user-images.githubusercontent.com/176720/139725592-b751a183-f99c-46b3-9d56-b16a1e7cc78b.png)

**Comment by jrainville** [comment]
@iurimatias I could not reproduce the issue. I did find one warning/error that happens at the end of the delete. It's fixed here https://github.com/status-im/status-desktop/pull/4026
