### ISSUE TITLE
QML replying to a sticker makes it disappear

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#4023]
![upload_609c464e8c5d7449407c1ea3ebe245d5](https://user-images.githubusercontent.com/31625338/139960934-03ed57d1-cd93-431b-98ff-9141a8ea6f06.png)
![upload_05aceec0dbf21443f6fb05be9e7739ef](https://user-images.githubusercontent.com/31625338/139960938-0d3d023a-8deb-4ae0-8f8f-ba279d90b430.png)

**Comment by anastasiyaig** [comment]
this is still reproducible in master and base_02

<img width="1344" alt="Screenshot 2021-11-09 at 16 25 48" src="https://user-images.githubusercontent.com/82375995/140932122-4330c06b-092f-49fe-9a86-b2e0eca0585b.png">
