### ISSUE TITLE
App Sync not working

### ISSUE THREAD

**Issue by snakyjake1** [status-im/status-desktop#4035]
Syncing between iOS and Windows doesn't appear to be working or doing anything.  Advertising on both devices does nothing.  The devices do not see each other.

**Comment by iurimatias** [comment]
@anastasiyaig could you verify if this works in master please

**Comment by anastasiyaig** [comment]
@iurimatias i will work on investigating this, however my Windows VM is not reliable (can't run windows builds, they are crashing). I will check with Mac + iOS, but i am pretty sure this feature was never fully operational ,as well as designed / implemented

**Comment by anastasiyaig** [comment]
@iurimatias I have synced a bit knowledge of how this feature should work with mobile team and I can safely assume it is not working (at least 90 percent of it) on desktop. I suggest it is designed and planned and reimplemented as dedicated tasks

**Comment by anastasiyaig** [comment]
even the feature is having issues for sure, it works partially , so "advertising device" performs an action (and the syncing partially works). We might close the issue and address designs and implementation accordingly. The screenshot below indicates what was synced and how . I was using latest master commit `528210b50f40de99a951e7f95b8c57940aea6467` and latest develop from mobile 

<img width="1439" alt="Screenshot 2022-01-03 at 14 06 32" src="https://user-images.githubusercontent.com/82375995/147923834-0d59688d-8dec-4f94-a540-32982b73e54d.png">
