### ISSUE TITLE
[refactoring/base_01] adding to favorites modal is empty

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4037]
base_01 branch:

<img width="1012" alt="Screenshot 2021-11-04 at 11 00 23" src="https://user-images.githubusercontent.com/82375995/140278181-f9019047-4e56-4f9f-83ca-5ee4499331cb.png">

<img width="1344" alt="Screenshot 2021-11-04 at 11 10 36" src="https://user-images.githubusercontent.com/82375995/140279204-93679699-4857-4ea1-82e4-53335692eadf.png">

<img width="1344" alt="Screenshot 2021-11-04 at 11 10 26" src="https://user-images.githubusercontent.com/82375995/140279228-2f83dd33-1571-4a57-9aae-a512579d8123.png">

master:

<img width="1344" alt="Screenshot 2021-11-04 at 11 03 19" src="https://user-images.githubusercontent.com/82375995/140278209-3e15f915-5385-4876-a475-23f621261c01.png">

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig unable to reproduce this on latest refactoring/base_01 can you please check and let me know?

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp yes, please take a look


https://user-images.githubusercontent.com/82375995/140471546-585fc71e-3d89-4399-94e8-f6894578c8fa.mov

i am on commit `abc707933671ff58d5b5e6ad68f6659946f5ace2`

<img width="1552" alt="Screenshot 2021-11-05 at 10 06 04" src="https://user-images.githubusercontent.com/82375995/140471658-aad44f67-d201-4d6c-90e9-0f245a352de9.png">

**Comment by Khushboo-dev-cpp** [comment]
I can see it now. Thanks @anastasiyaig :)
