### ISSUE TITLE
[refactoring/base_01] collectibles are not shown

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4039]
<img width="1440" alt="Screenshot 2021-11-04 at 12 29 19" src="https://user-images.githubusercontent.com/82375995/140290044-30f25efb-9326-41ac-a7ee-bfb55d43cdcf.png">

**Comment by alaibe** [comment]
@anastasiyaig I just double check this in base_01 and I can see the collectibles, see:
![image](https://user-images.githubusercontent.com/491074/140385457-4e8ea205-faf6-4d66-b299-2a5c568b2d08.png)

On your screenshot I can see that the loaded account is 111111 which is different than the Status account loaded on master. Could it be possible that this account don t have any collectibles.

Also if you could give the public key so we can double check this account in opensea and locally

**Comment by anastasiyaig** [comment]
@alaibe this account should have cryptokitties! And also, it should have paid stickers

https://etherscan.io/address/0xf38d2cd3c6ad02dd6f8b68e0a7b2f959819954b6#tokentxnsErc721

maybe there is an issue with cryptokitties then? I dont have anything on openSea.. And u are right, the screenshot shows wrong wallet account but anyway, i dont see this cats (just double checked correct account)

<img width="1344" alt="Screenshot 2021-11-05 at 09 38 20" src="https://user-images.githubusercontent.com/82375995/140468866-26773754-36b4-453b-af00-fc6fd0423bd1.png">

**Comment by alaibe** [comment]
Indeed there is something wrong! it might be related to the fact that the collectibles are owned by the Status Account, I loaded your account as a watch only and I can see the kitties!
![image](https://user-images.githubusercontent.com/491074/140482339-f493b017-0fdf-4d44-b088-f717a9f86589.png)

Also this match with opensea: https://opensea.io/0xf38d2cd3c6ad02dd6f8b68e0a7b2f959819954b6
![image](https://user-images.githubusercontent.com/491074/140482462-4982d278-3d06-44d3-872a-905645de4759.png)

If you don't see that :point_up:  on opensea it would mean that you have access issue?

**Comment by anastasiyaig** [comment]
turned out that opensea is blocked from usage in some countries: https://nftoco.com/where-opensea-is-banned/

i can access and see collectibles in OpenSea directly and in wallet when being under VPN.
