### ISSUE TITLE
[refactoring/base_01] profile picture is wrong for online indicator

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4044]
<img width="1344" alt="Screenshot 2021-11-04 at 17 02 23" src="https://user-images.githubusercontent.com/82375995/140327807-f2cb0635-f075-4c94-9605-2b3df56c9a92.png">

**Comment by Khushboo-dev-cpp** [comment]
This is not reproduced with PR from @alexandraB99  https://github.com/status-im/status-desktop/pull/3965/files
