### ISSUE TITLE
[refactoring/base_01] sending a sticker multiplies it

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4045]
1. recover account
2. install pre-bought stickers or free pack
3. send a sticker to someone in 1x1 chat (ideally to mobile app)
4. check desktop UI and mobile UI

<img width="1344" alt="Screenshot 2021-11-04 at 17 19 31" src="https://user-images.githubusercontent.com/82375995/140330604-28c9ce27-e96e-4c60-9389-4a98d84adbbc.png">

![image](https://user-images.githubusercontent.com/82375995/140330664-e5f980bf-143b-4f33-a45c-01bf7cf6729d.png)

**Comment by alexandraB99** [comment]
This is addressed here: https://github.com/status-im/status-desktop/pull/4033
