### ISSUE TITLE
request transaction shows incorrect preview

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4048]
note: also present in 0.3.0

1. start a 1 on 1
2. select request transaction

see message preview

![Screen Shot 2021-11-04 at 11 10 32 AM](https://user-images.githubusercontent.com/176720/140381249-d9b0c0f2-a97e-4732-a24d-5f559718e143.png)

**Comment by Khushboo-dev-cpp** [comment]
Available on latest master
