### ISSUE TITLE
[refactoring/base_02] online/offline selector not changing color/state

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4049]
in the latest refactor branch:

![Screen Shot 2021-11-04 at 12 20 20 PM](https://user-images.githubusercontent.com/176720/140383074-c8e5833c-9f32-44db-a67f-16b4fc249407.png)

select offline, the state color is still green

**Comment by anastasiyaig** [comment]
reopening because it is reproducible in base_02 branch but for some reason i forgot to do it earlier. It is fixed in master

**Comment by alexandraB99** [comment]
re-assigning to @saledjenic for finishing the userProfile feature
