### ISSUE TITLE
refactor: chat section changes needed for backend refactor

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4062]

**Comment by alexandraB99** [comment]
Implement changes described in Level 2 [here](https://docs.google.com/document/d/1cCMkknb6jKck2DBSZS7LQfEHTwgF6ULLdSo7EuHSz_s/edit)

**Comment by alexandraB99** [comment]
Additional changes can be found in [StatusQ](https://github.com/status-im/StatusQ/pull/486)

**Comment by alexandraB99** [comment]
Fixed in [StatusQ](https://github.com/status-im/StatusQ/pull/486) and [base_bc](https://github.com/status-im/status-desktop/pull/4196)
