### ISSUE TITLE
Validation error is missing when adding wallet account from seed phrase / private key with wrong password

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4068]
1. enable wallet
2. open wallet
3. click + button 
4. click enter seed phrase
5. enter any valid seed phrase of known account (or u may enter private key instead)
6. enter wrong password
7. proceed

As result, the modal is closed, and no errors are shown to user explaining why the account was not added

**Expected:** should not be able to proceed with wrong password, there should be a clear indication of this on UI

```
ERR 2021-11-09 10:34:14.237+03:00 rpc response error                         topics="rpc" tid=2116181 file=core.nim:34 err="\nstatus-go error [methodName:wallet_getOpenseaCollectionsByOwner, code:-32000, message:invalid character \'e\' looking for beginning of value ]\n"
ERR 2021-11-09 10:34:14.237+03:00 error:                                     topics="collectible-service" tid=2116181 file=service.nim:36 errDesription="\nstatus-go error [methodName:wallet_getOpenseaCollectionsByOwner, code:-32000, message:invalid character \'e\' looking for beginning of value ]\n"
```

**Comment by alexandraB99** [comment]
Fixed [here](https://github.com/status-im/status-desktop/pull/4109)
