### ISSUE TITLE
[refactoring/base_02] Signing phrase is missing sometimes 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4069]
`base_02`

<img width="1344" alt="Screenshot 2021-11-09 at 11 56 40" src="https://user-images.githubusercontent.com/82375995/140894012-d7332431-87a9-46f4-a9de-511512d0d0b4.png">

`master`

<img width="1344" alt="Screenshot 2021-11-09 at 11 59 15" src="https://user-images.githubusercontent.com/82375995/140894047-729f10ab-44fa-4969-9fff-9bac56a42a64.png">

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig I am unable to reproduce it. Can you please tell me if its the same with you?

**Comment by anastasiyaig** [comment]
I cant reproduce it either now, maybe some race condition. Let's close it for now
