### ISSUE TITLE
Can't login to recovered account on Windows

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4115]
# Bug Report

## Description

Can't login to recovered account on Windows

## Steps to reproduce

1. install a build on windows
2. create an account
3. maybe it will crash. If not - just log out
4. recover any known account with seed phrase
5. maybe it will crash. If not - just log out
6. try to login to this account again

#### Expected behavior

able to log in. Crashes should not happen

#### Actual behavior

1. when trying to login back - there is an endless connecting screen

<img width="1552" alt="Screenshot 2021-11-15 at 14 43 29" src="https://user-images.githubusercontent.com/82375995/141777211-67deafed-8256-4245-9f44-d1d6d6391896.png">

2. when i close the app and try relogin - error is shown

<img width="1552" alt="Screenshot 2021-11-15 at 14 44 29" src="https://user-images.githubusercontent.com/82375995/141777190-be99ae8c-14d5-4c3c-853c-8c44676e4d5c.png">

<img width="1552" alt="Screenshot 2021-11-15 at 15 11 51" src="https://user-images.githubusercontent.com/82375995/141780111-a26b43fe-e2a8-4004-8eff-db11c6f64325.png">

### Additional Information

- Status desktop version: `0.4.0 Build #1 (15 Nov 2021, 10:05:59)`
- Operating System: `windows 11`

```
INF 2021-11-15 15:11:32.130+03:00 Starting application...                    topics="main" tid=11048 file=nim_status_client.nim:241
DBG 2021-11-15 15:11:37.723+03:00 Account logged in                          topics="accounts-service" tid=11048 file=service.nim:311
ERR 2021-11-15 15:11:37.807+03:00 node.crashed                               topics="signals" tid=11048 file=signal_controller.nim:49 error="{\"type\":\"node.crashed\",\"event\":{\"error\":\"failed to create database at C:\\\\Users\\\\anastasiya\\\\AppData\\\\Local\\\\Status\\\\data\\\\ethereum\\\\mainnet: The process cannot access the file because it is being used by another process.\"}}"
ERR 2021-11-15 15:11:37.817+03:00 node.login                                 topics="signals" tid=11048 file=signal_controller.nim:46 error="failed to create database at C:\\Users\\anastasiya\\AppData\\Local\\Status\\data\\ethereum\\mainnet: The process cannot access the file because it is being used by another process."
ERR 2021-11-15 15:11:37.820+03:00 error:                                     topics="startup-controller" tid=11048 file=controller.nim:41 methodName=init errDesription="login error failed to create database at C:\\Users\\anastasiya\\AppData\\Local\\Status\\data\\ethereum\\mainnet: The process cannot access the file because it is being used by another process."
```

**Comment by PascalPrecht** [comment]
@anastasiyaig do you have any logs by any chance?

**Comment by anastasiyaig** [comment]
not yet unfortunately :/

**Comment by anastasiyaig** [comment]
i do have ones, but they are useless, attaching them anyway


[app_1636976284.log](https://github.com/status-im/status-desktop/files/7538469/app_1636976284.log)
[app_1636976429.log](https://github.com/status-im/status-desktop/files/7538470/app_1636976429.log)
[app_1636976528.log](https://github.com/status-im/status-desktop/files/7538471/app_1636976528.log)
[app_1636976658.log](https://github.com/status-im/status-desktop/files/7538472/app_1636976658.log)
[app_1636977430.log](https://github.com/status-im/status-desktop/files/7538473/app_1636977430.log)

**Comment by anastasiyaig** [comment]
i am checking now if this is related to default installation path (`C:\Users\anastasiya\AppData\Local\StatusApp`) @PascalPrecht , maybe this is the case.

**Comment by anastasiyaig** [comment]
when changing the installation path to `C:\StatusApp` , the crashes are more rare, but still occur

**Comment by jrainville** [comment]
@anastasiyaig I tried with a dev build as well as the Jenkins build, both worked fine for me.
With the Jenkins build, I tried creating a new account then importing another.
Afterwards, I removed my old install folder and data folders et installed the build again at the same path as you. Again it worked fine.

So I'm not sure what is going on. If you try again on a fresh reboot, does it work? It feels like something was still running or your node was corrupted.

**Comment by anastasiyaig** [comment]
@jrainville which windows are u running? I am running Win 11 (also, it is VM) , maybe this is the case, i will check more

**Comment by jrainville** [comment]
@anastasiyaig Windows 10. Do we have someone else on the team that has Windows 11?
Also, if you use a previous build, like 0.3.0, everything works fine?

**Comment by iurimatias** [comment]
@anastasiyaig can you still replicate this in latest master/

**Comment by anastasiyaig** [comment]
@iurimatias yes, I can, however it makes sense to test it on real windows . @abhi-status , please validate

**Comment by abhi-status** [comment]
I can confirm, I am not able to reproduce this against the latest Master on Windows 11.
@iurimatias This can now be closed ?
