### ISSUE TITLE
Activity center replies and mentions are overlapped 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4139]
# Bug Report

## Description

In activity center, when u do have more than 1 mention and more than 1 reply, they are overlapping each other in the list

## Steps to reproduce

1. create a communty
2. add some device u have access to (for example phone) to the community
3. mention the user from desktop by the mobile device
4. reply to some messages sent from desktop

#### Expected behavior

Mentions and replies are being shown in activity center as a list. User can click any record and be navigated accordingly

#### Actual behavior

<img width="1344" alt="Screenshot 2021-11-19 at 14 50 48" src="https://user-images.githubusercontent.com/82375995/142618738-faadad19-5e52-4510-98b4-3d88f3eaf31c.png">

<img width="1344" alt="Screenshot 2021-11-19 at 14 49 48" src="https://user-images.githubusercontent.com/82375995/142618759-a9d3f1a6-bd22-4ad5-9d55-4ee6ca6cd87c.png">

### Additional Information

- Status desktop version: master from 19-nov-2021, commit `0597fab1ac57dc83872858ff30b99af8167d3210`
- Operating System: macOS BigSur

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig not able to reproduce this on macOs on latest master -

![image.png](https://images.zenhubusercontent.com/610aa02b14ef6a62cbf14bf1/94cd3207-55ce-4d07-9e60-d0136b058989)

do check and close it if the same for you

**Comment by anastasiyaig** [comment]
indeed, can't reproduce in latest master
