### ISSUE TITLE
Can't decline a contact request for recovered account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4140]
# Bug Report

## Description

In case there is incoming request , that was already present before, so lets say u imported account and have incoming contact request and u do nothing with it and wipe all your data folder and import the same account again - in this case the contact request re-appears and u can't decline it.

## Steps to reproduce

1. get any account with seed phrase and recover it
2. send an incoming contact request to this account
3. wipe all the data for status
4. reimport the account again
5. try to decline the incoming contact request

#### Expected behavior

I am not clear if the contact requests should be recovered along with account but until that is resolved , i want to be able to decline them

#### Actual behavior

https://user-images.githubusercontent.com/82375995/142624404-eeedd474-e67b-4144-85e7-b427a2c5381a.mov

### Additional Information

- Status desktop version: master 19-nov-2021
- Operating System: macOS BigSur

**Comment by Khushboo-dev-cpp** [comment]
Not able to reproduce this on latest master on macOS and linux

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp u mean u were not able to see the incoming contact request when it was already present for account before, or declining such contact request works normally?

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig Sorry for not clarifying. I dont see the pending contact request after recovering the account.

**Comment by anastasiyaig** [comment]
okay then, however it is not that easy to reproduce since it is not clear if we must recover contact requests or not when recovering account in general. Anyway this is something on status-go. I can reproduce it , so it is not that sporadic. I do agree the priority of the issue is unknown now and i will put it as low

**Comment by Khushboo-dev-cpp** [comment]
aaah okay. so it only happens sometimes? I will leave it for now then

**Comment by Khushboo-dev-cpp** [comment]
Decision is pending on behaviour and it also not easy to reproduce it, as the priority has been reduced moving I back to open state

**Comment by iurimatias** [comment]
This is likely due to the history fetching, the contact request is fetched, but not the answer, likely because because rejecting a contact request is actually ignoring it. We might review this if the behaviour of contact requests is meant to show to the sender the request was rejected or not.
