### ISSUE TITLE
Cannot download uploaded or embed images in private chat

### ISSUE THREAD

**Issue by VictorianSubmission** [status-im/status-desktop#4143]
# Bug Report

## Description
Downloading uploaded embed images in private chat is broken.

## Steps to reproduce
1. Proceed to a private chat.
2. Have an uploaded, embed picture/image present in the chat.
3. Right click, press "Download Image".
4. Select Desktop.
5. Name the file.
6. Press save.

#### Expected behavior
Pictures and images save to your computer without error.
#### Actual behavior
Pictures and images cannot be saved, produces "Path does not exist" error if file is
named, if it is not, the save button just closes the tab without saving.
### Additional Information
N/A
- Status desktop version: Version: 0.3.0-beta
- Operating System: Windows 7

**Comment by Khushboo-dev-cpp** [comment]
Not able to reproduce on linux. Dont have a windows os to test this on

**Comment by jrainville** [comment]
I tried and was able to reproduce

**Comment by alexandraB99** [comment]
Fix is here https://github.com/status-im/status-desktop/pull/4357, however I was not able to test on Windows, hopefully works there too.
