### ISSUE TITLE
Resend button appears for sticker upon the application restart

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4155]
# Bug Report

## Description

Resend button appears for sticker upon the application restart

## Steps to reproduce

1. open app
2. if on Ropsten, enable stickers flag in Advanced
3. open public chat
4. open stickers modal and install any free stickers
5. send a sticker to chat
6. restart the app
7. open the same chat again

#### Expected behavior

Stickers are sent and persistent on app restart

#### Actual behavior

<img width="1449" alt="Screenshot 2021-11-23 at 12 59 47" src="https://user-images.githubusercontent.com/82375995/143014959-91e7248c-3a15-4186-9ac1-ad34de21dbf5.png">

### Additional Information

- Status desktop version: beta 0.3.0, master
- Operating System: macOS

**Comment by alaibe** [comment]
@anastasiyaig is it something that you can reproduce consistently? I haven't been able to reproduce in 5 attempts

**Comment by anastasiyaig** [comment]
it is more visible in beta 3, also i just realised that it could be an issue when i am running concurrent sessions (beta 3 and beta 4) at the same time @alaibe , can u please check it as well? If so, then it is not relevant
