### ISSUE TITLE
Setting local nickname of contact crashes application

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#4173]
# Bug Report

## Description

When trying to set the local nickname of a contact, the application crashes. The reason is the same as what's reported in https://github.com/status-im/status-desktop/issues/4171: `base_bc` uses no longer existing APIs of status-go.

## Steps to reproduce

1. Open profile popup of some contact
2. Select nickname
3. Enter nickname and hit save

#### Expected behavior

Changing the nickname, should reflect the change in all contact related components.

#### Actual behavior

The application crashes.

### Additional Information

- Status desktop version: `c67384367`
- Operating System: macOS Cataline (10.15.3)

**Comment by Khushboo-dev-cpp** [comment]
Can see this is in the log  2021-11-29 11:43:36.888+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=166315 file=core.nim:24 rpc_method=wakuext_saveContact
ERR 2021-11-29 11:43:36.890+01:00 rpc response error                         topics="rpc" tid=166315 file=core.nim:34 err="\nstatus-go error [methodName:wakuext_saveContact, code:-32601, message:the method wakuext_saveContact does not exist/is not available ]\n"

**Comment by PascalPrecht** [comment]
> When trying to set the local nickname of a contact, the application crashes. The reason is the same as what's reported in #4171: base_bc uses no longer existing APIs of status-go.

Yeap! Rebasing `base_bc` on top of latest `master` should fix all of this again

**Comment by anastasiyaig** [comment]
it happens in master as well, i reproduced it in `d639219b940b0eb665f89b617bb07713e57e7a11` commit (master from Dec 20,2021)

**Comment by PascalPrecht** [comment]
@anastasiyaig Can confirm that this breaks in latest `master`. But this is new and now breaks with a different error.

Looking into this now..
