### ISSUE TITLE
Group chat popup member list doesn't have proper visuals

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#4176]
# Bug Report

**This issue might not exclusively exist in `refactoring/base_bc`, so should be double checked in latest `master` as well**

## Description

The popup of a group chat shows its members and lets users change the name of the group. The member list doesn't have any visual feedback when hovering over items (most likely this doesn't use StatusQ components yet).

In addition, the edit button in the modal header doesn't seem to look properly in dark theme (again, this might also because of lack of StatusQ Components):

<img width="498" alt="Screenshot 2021-11-25 at 13 28 48" src="https://user-images.githubusercontent.com/445106/143441876-0b21762b-73e4-4788-b678-3bcf25a69adc.png">

## Steps to reproduce

1. Start app, login
2. Create group chat with any member
3. Open group chat popup of created group

#### Expected behavior

The member list items should behave like other list items that are implemented using `StatusListItem` from StatusQ

### Additional Information

- Status desktop version: c67384367
- Operating System: macOS Cataline (10.15.3)

**Comment by Khushboo-dev-cpp** [comment]
This exists on master too.

**Comment by anastasiyaig** [comment]
it is also present in beta 3, beta 4 and master as well, sitting here for quite a while
