### ISSUE TITLE
Remove timeline from the application

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#4177]
### Description

This issue is specifically created for the `refactoring/base_bc` branch. There's already an issue created for that at #4064 for `master`. Just want to make sure we don't end up removing it there and not in the `base_bc` branch.

**Comment by alexandraB99** [comment]
fixed in [status-desktop](https://github.com/status-im/status-desktop/pull/4198) and [status-lib](https://github.com/status-im/status-lib/pull/119)
