### ISSUE TITLE
Clicking on a sticker on a message does not display the list of stickers belonging to the same sticker pack

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4181]
Steps to reproduce:
1. Send a sticker
2. Click on the sticker message
3. Nothing happens

A dialog like this one should be shown instead
![image](https://user-images.githubusercontent.com/1106587/143483719-c0ed5d09-ec20-44fe-ba16-3eeed5844353.png)

**Comment by PascalPrecht** [comment]
This is a duplicate of #4203 (well actually #4203 is a duplicate of this one here, but there's already a PR with a fix that references #4203 so I'm closing this one here)
