### ISSUE TITLE
All the channels within a community have the same color

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4182]
I'm not 100% sure if this is a bug, tho. Please close it if it is not the case

![image](https://user-images.githubusercontent.com/1106587/143484042-4ac944da-ab0d-4359-a127-dfb6c16d927a.png)

**Comment by PascalPrecht** [comment]
This is by design as of https://github.com/status-im/status-desktop/pull/4027

**Comment by PascalPrecht** [comment]
Closing this.

**Comment by jrainville** [comment]
Oh damn, it IS by design. I never saw that before. TIL
