### ISSUE TITLE
Invalid profile picture for replied message

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4185]
![image](https://user-images.githubusercontent.com/1106587/143484688-fbe2e379-f389-4ca5-8767-1b4d94decddd.png)

**Comment by anastasiyaig** [comment]
<img width="1440" alt="Screenshot 2021-11-26 at 10 35 35" src="https://user-images.githubusercontent.com/82375995/143543923-cfe804eb-8630-4e46-a7b2-915a82fadbe0.png">
