### ISSUE TITLE
Appimage does not work

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4189]
Using 0.4.0 App freezes on login
Nothing of interest is shown in the logs
Attaching gdb to the running process displays the following stacktrace. It's possible these are not related at all to the login error
![image](https://user-images.githubusercontent.com/1106587/143485227-53b6ae3f-bd0a-43a3-9bcf-07c1893003ca.png)
![image](https://user-images.githubusercontent.com/1106587/143485242-df7478e0-c411-41fb-958e-d3a10bc08d31.png)

**Comment by richard-ramos** [comment]
PR https://github.com/status-im/status-desktop/pull/3580/ causes the issue

**Comment by jrainville** [comment]
That's very random. It didn't change the Makefile or anything related to builds. Have you been able to determine which part of the PR causes the issue?
