### ISSUE TITLE
 Messages do have wrong indentation (alignment) when being sent in a row

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#4211]
# Bug Report

## Description

I've noticed that, when sending multiple messages, the last message has always an additional indentation that is not expected.
This changes with every next message sent (by the same logged-in user)

<img width="591" alt="Screenshot 2021-11-30 at 12 01 42" src="https://user-images.githubusercontent.com/445106/144035873-8ab53d4a-74b1-46d0-b767-70ee9b1793e9.png">

<img width="602" alt="Screenshot 2021-11-30 at 12 01 52" src="https://user-images.githubusercontent.com/445106/144035842-46c9d510-6585-4dcb-9ecc-61dfb3d8e18c.png">

## Steps to reproduce

1. Log into Status, open community channel
2. Send a message, then send another one
3. The last message should have indentation
4. Send yet another message, notice how the second to last message restored its indentation while the new last message has the indentation now

#### Expected behavior

No weird indentation when sending messages. (or indentation for all messages as stated in comment below)

#### Actual behavior

Weird indentation.

<img width="1440" alt="Screenshot 2021-11-30 at 15 13 25" src="https://user-images.githubusercontent.com/82375995/144045579-7d3c9175-026b-47e2-85d3-f5867d0a9859.png">

<img width="1440" alt="Screenshot 2021-11-30 at 15 13 59" src="https://user-images.githubusercontent.com/82375995/144045595-71d90c6a-651c-48b1-8620-00fa49012d4e.png">

**NOTE**: it is gone when switching back and forth 

### Additional Information

- Status desktop version: `4d7d2261a` (latest `master` at the time of creating this issue)
- Operating System: macOS 10.15.3

**Comment by PascalPrecht** [comment]
After further fiddling with this, it seems the issue is that the indentation is there to have the text not bleed into the profile picture of the message author.  In other words, it does make sense to have that indentation in the first line of the message **or** to keep things simple, we should always have that indentation.

**Comment by Khushboo-dev-cpp** [comment]
@Pacal: In chat view its always indented, so will keep it consistent and remove the part where it is misaligned.
