### ISSUE TITLE
Error: Insufficient arguments when hitting Enter when editing a message

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4213]
# Bug Report

## Description

`qrc:/imports/shared/views/chat/CompactMessageView.qml:382: Error: Insufficient arguments` when hitting Enter when editing a message

## Steps to reproduce

1. open a public chat
2. send a text message
3. hover 3 dots, edit
4. make an update and hit Enter on the keyboard

#### Expected behavior

The message edit dialog is closed, message is edited

#### Actual behavior

Edit dialog is still active, message is not saved, error in console

<img width="1440" alt="Screenshot 2021-11-30 at 15 23 14" src="https://user-images.githubusercontent.com/82375995/144046739-2ce35272-487c-4932-944a-69d516bf3e76.png">

### Additional Information

- Status desktop version: master `4d7d2261aa50325ae27e44e50100c230d93ae8b6` from 30-nov-2021
- Operating System: `macOS BigSur 11.6`

**Comment by alexandraB99** [comment]
@anastasiyaig can't reproduce on current master `94d67717c899699b703817429918e7af4c400159`

https://user-images.githubusercontent.com/31625338/144081827-4ba065a1-1cfc-48b2-8f83-31ef324e6e3a.mov

**Comment by anastasiyaig** [comment]
@alexandraB99 u can't reproduce because u are clicking Save button which is not the case, u need to hit enter button on keyboard as it is stated in the issue itself. I can reproduce it within described steps on master `8be841e0ace343129ae15a80737c36846057bf52`

**Comment by alexandraB99** [comment]
you are right @anastasiyaig, I overlooked the description sorry about that! fix [here](https://github.com/status-im/status-desktop/pull/4232)
