### ISSUE TITLE
Search placeholder text is misaligned and shifts when clicked

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#4222]
# Bug Report

## Description

When using the StatusBaseInout, the placeholder text is not aligned vertically and when the user clicks on it shifts to right position

## Steps to reproduce

1. Open group info
2. Click on the Add members buttons

#### Expected behaviour

The search text should be horizontally aligned

#### Actual behavior

https://user-images.githubusercontent.com/60327365/144241707-65adf3d2-5e68-4706-8f2a-cfffb4f7c325.mov

#### Additional Information
- Status desktop version: master
- Operating System: Linux Ubuntu 16

**Comment by PascalPrecht** [comment]
Need to fiddle with `bottomPadding` and `topPadding here to make this work
