### ISSUE TITLE
Download page for updater

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4231]
### Description

The download page for an update should look as follows

![Screen Shot 2021-12-01 at 3 31 20 PM](https://user-images.githubusercontent.com/176720/144309466-b0501aeb-de41-423c-bf1f-62bab3f1b17f.png)

### Acceptance Criteria

**main use case**
1. New application version is released
2. User gets a notification there is an update (already implemented)
3. User clicks to download new version, a screen like the following should appear:

![Screen Shot 2021-12-01 at 3 31 20 PM](https://user-images.githubusercontent.com/176720/144309466-b0501aeb-de41-423c-bf1f-62bab3f1b17f.png)

4. clicking the `Get Status` button should download the binary for the new application

**other notes**
- since we know what OS the user is in, then that binary should already be the one appropriate for that platform

### Open questions

some of the following is not well defined and/or is missing and could require clarification before starting the task:
- What is the `'Check what's new` link, where would it link to and how could that data be updated
- How problematic are translations here, what languages should be supported
- Most users also want a sha256 file and this is missing here

**Comment by jrainville** [comment]
This is kinda blocked by this https://github.com/status-im/status-desktop/issues/4221
since the function to get the latest version fails (app version isn't pinned.

It would be possible to ignore that bug however and just work on the UI (with some hardcoding to test)

**Comment by ducheng0** [comment]
I think there should be a way to reject the update, and opt-out of updates altogether. I hate it when my phone gives me a fullscreen popup that forces me to accept the TOS and update.

I don't think it should be a fullscreen takeover just for updates, I think there should be more information like a changelog, and an obvious option to opt-out of the current update, and all future updates.
