### ISSUE TITLE
TypeError: Cannot call method 'unshift' of undefined when selecting emoji

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4240]
### Description

Selecting emoji is not possible in chat

**Version:** `beta 0.4.0 , Build #33 (2 Dec 2021, 14:13:53)`
**OS**: `macOS Big Sur 11.6`

```
qrc:/imports/shared/status/StatusEmojiPopup.qml:64: TypeError: Cannot call method 'unshift' of undefined
```

**To reproduce:**

1. open any chat
2. select emoji

https://user-images.githubusercontent.com/82375995/144579775-0e14530a-a424-423c-a557-3edca2d0c84c.mov

**Comment by anastasiyaig** [comment]
https://github.com/status-im/status-desktop/issues/4102 was logged and fixed for the same problem

**Comment by alaibe** [comment]
It seems to work on master, I think someone with uber permission needs to cherry pick this one to 0.4.0:
https://github.com/status-im/status-desktop/pull/4135

**Comment by PascalPrecht** [comment]
Looking into this now

**Comment by PascalPrecht** [comment]
I have tested this locally with latest `release/0.4.0` as well as the release build from CI and this works perfectly fine for me.
