### ISSUE TITLE
Browser: Edit favourite does not reflect immediately

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#4279]
# Bug Report

## Description

After editing a saved favourites name in browser the change doesn't reflect immediately

## Steps to reproduce
1. Add a favourite in browser
2. Try to edit it and change the name

#### Expected behaviour
The change in name should reflect immediately 

#### Actual behaviour
The change is only visible after a restart

### Additional Information

- Status desktop version: release_0.4.0
- Operating System: MacOS and Linux

**Comment by iurimatias** [comment]
fixed in master
