### ISSUE TITLE
[base_bc] Timeline code is still present

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4284]
### Description

Timeline code was removed from master, however it is still there for `base_bc`. We need it to be removed.

<img width="1427" alt="Screenshot 2021-12-13 at 14 46 30" src="https://user-images.githubusercontent.com/82375995/145807309-38461752-89d3-43f8-a589-adabf2a175ae.png">

**Comment by PascalPrecht** [comment]
This is fixed with https://github.com/status-im/status-desktop/pull/4257

**Comment by PascalPrecht** [comment]
Closing this as this has been fixed with https://github.com/status-im/status-desktop/pull/4257
