### ISSUE TITLE
move stickers nim  code to status-go

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4289]
### Description

To simplify the code we want to move complex logic to the status-go backend so the frontend only needs to call simple apis, this also makes the transition to other codebases easier

 https://github.com/status-im/status-lib/blob/master/status/stickers.nim

**Comment by iurimatias** [comment]
https://github.com/status-im/status-go/pull/2518

**Comment by anastasiyaig** [comment]
i believe it is done, based on the assumption that https://github.com/status-im/status-go/pull/2518 is merged already

**Comment by anastasiyaig** [comment]
@iurimatias @richard-ramos please reopen if this is still relevant

**Comment by iurimatias** [comment]
reopening, the status-go part has been done but we need to now remove the logic from the app and use the new services

**Comment by iurimatias** [comment]
correction, done here https://github.com/status-im/status-desktop/pull/4808
