### ISSUE TITLE
Enabling browser in settings / clicking Send button in wallet makes the app irresponsive 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4323]
### Description

1. open advanced
2. enable browser toggle
3. enable wallet and click send button in the wallet tab

https://user-images.githubusercontent.com/82375995/146750373-6a4e2ed5-663a-4a4e-9ec4-e7a0a10bb413.mov

**Build info:** master from Dec 20, 2021, commit `d639219b940b0eb665f89b617bb07713e57e7a11`

**Comment by iurimatias** [comment]
can't replicate in master

however opened https://github.com/status-im/status-desktop/issues/4351 which is similar but not a crash
