### ISSUE TITLE
Playing media in browser doesn't work

### ISSUE THREAD

**Issue by du64** [status-im/status-desktop#4326]
## Description

Trying to play a video in the browser causes the video to load and then turn black and become unplayable. The same thing happens for audio files.

## Steps to reproduce

* Open Status and go to browser
* Try going to a URL containing just a video/audio file
* Play the media

#### Expected behavior

The media should play

#### Actual behavior

The media won't play and turns to an unplayable icon

### Additional Information

- Status desktop version: Latest release
- Operating System: Zorin 16 (Debian-based Linux)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6775
