### ISSUE TITLE
Add a placeholder for collectibles in case of missing preview

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4379]
### Description

For status stickerpacks we dont have any icons there at OpenSea (https://opensea.io/collection/status-sticker-pack-v2) , as a result, desktop app shows nothing in this case , which looks weird. 

We need to show a placeholder and not an empty space in this situation

<img width="1568" alt="Screenshot 2022-01-06 at 16 30 47" src="https://user-images.githubusercontent.com/82375995/148391186-60a7af11-5293-48a0-96f7-a3e438bc8b06.png">

**Comment by iurimatias** [comment]
empty will be acceptable for now, this needs a bigger think through, ongoing elsewhere
