### ISSUE TITLE
[base_bc] switching channels show same messages

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4418]
note: possibly fixed by https://github.com/status-im/status-desktop/pull/4380

https://user-images.githubusercontent.com/176720/149029887-ca5341a4-8673-4990-8a85-6d09207d8092.mov

**Comment by anastasiyaig** [comment]
i cant reproduce it now at commit 71110d040d66cbec846d6da012b9ee824d2f0fdb

**Comment by saledjenic** [comment]
This should be fixed in commit `b5435dfa3052bae76405c36dea820cfb46a957ed` (issue was in `controller.nim` file of the message module). After that I wasn't able to reproduce this.

**Comment by richard-ramos** [comment]
I can confirm that this issue cannot be reproduced in latest base_bc

**Comment by anastasiyaig** [comment]
confirming that as well, it is fixed in base_bc
