### ISSUE TITLE
[base_bc] mutual contact requests have various issues in base_bc

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4420]
- view profile and then doing add contact, is unclear what it’s doing, shouldn’t it send a mutual contact request? on mobile no multual contact request is received
- sent a mutual request (from mobile) to the contact in desktop (base bc branch), nothing showed in the UI, after restart it did show up
- crash after accepting contract request (possibly unrelated)

```
/Users/iurimatias/Projects/Status/status-desktop/src/nim_status_client.nim(146) nim_status_client
/Users/iurimatias/Projects/Status/status-desktop/src/nim_status_client.nim(131) mainProc
/Users/iurimatias/Projects/Status/status-desktop/src/app/boot/app_controller.nim(215) delete
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/private_interfaces/module_access_interface.nim(9) delete
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/module.nim(146) delete
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/node_section/private_interfaces/module_access_interface.nim(1) delete
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/node_section/module.nim(40) delete
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/node_section/controller_interface.nim(7) delete
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/node_section/controller_interface.nim(8) delete
Error: unhandled exception: No implementation available [ValueError]
```
- error on accepting contact request

```
qrc:/app/AppLayouts/Chat/popups/ContactRequestsPopup.qml:49: TypeError: Cannot call method 'createOneToOneChat' of undefined
```

**Comment by iurimatias** [comment]
related to or the same as https://github.com/status-im/status-desktop/issues/4171

**Comment by jrainville** [comment]
> view profile and then doing add contact, is unclear what it’s doing, shouldn’t it send a mutual contact request? on mobile no multual contact request is received

As far as I know, contact requests are not implemented on mobile yet, so it's normal if they do not receive anything. The way to "connect" to mobile from desktop as of when I implemented the feature was that you need the contact added on desktop, but then you can send a message to the mobile account. That mobile account will then receive that message in the activity center. 
Desktop also has that activity center feature. So we have a double mutual contact feature.
