### ISSUE TITLE
[base_bc] can't start 1 on 1 chats

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4421]
1. go to chat section and click the `+` icon
2. click start new chat and select a contact
3. click next

**Comment by abhi-status** [comment]
Approving this, as this currently works on Ubuntu.
I havent been able to test on Win11 since this build contains the old version of Status-Go.
The new Status-Go version has a fix specific to Windows.
So, I'll test this on base_bc instead.
