### ISSUE TITLE
All current Jenkins Windows builds fail to launch the app successfully 

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#4492]
# Bug Report

None of the Jenkins builds for Windows are able to launch the app successfully after installing.

## Steps to reproduce

Install the latest Windows build on base_bc branch from our Jenkins build page 
--> https://ci.status.im/job/status-desktop/job/branches/job/windows/view/change-requests/job/PR-3951/

Once installed, try and launch the desktop app.

#### Actual behavior : 
![image](https://user-images.githubusercontent.com/95302135/150135088-1718ab43-7e98-4c0f-a0c0-11f7d63eebd6.png)

This behaviour is also observed on Master branch.

- Status desktop version: 0.4.0
- Operating System: Observed on Win10 & Win11

**Comment by jakubgs** [comment]
This is the only recent Windows CI host chance that could possibly have some effect: https://github.com/status-im/infra-ci/commit/21f94970

I installed `mingw` package from `scoop` for the sake of fixing `nim-waku` builds in https://github.com/status-im/nim-waku/issues/738.

**Comment by jakubgs** [comment]
This is the version: https://github.com/ScoopInstaller/Main/blob/master/bucket/mingw.json

It's `mingw-w64` version `8.1.0`: https://www.mingw-w64.org
Which is a bit old, and there are newer alternative distributions like [`mingw-nuwen`](https://github.com/ScoopInstaller/Main/blob/master/bucket/mingw-nuwen.json) or [`mingw-winlibs`](https://github.com/ScoopInstaller/Main/blob/master/bucket/mingw-winlibs.json).
But not sure if this is actually related.

**Comment by jakubgs** [comment]
I've uninstalled `mingw` and installed `mingw-winlibs`, which does fix the build:

![image](https://user-images.githubusercontent.com/2212681/150206018-01fe3d7c-88d1-4868-9117-423803581f02.png)
https://ci.status.im/job/status-desktop/job/branches/job/windows/job/master/1341/

But it breaks the `nim-waku` build:
```
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```
https://ci.status.im/job/nim-waku/job/prs/job/windows/view/change-requests/job/PR-821/3/

No idea how a dependency that wasn't necessary for desktop builds before broke them, and not sure how I can keep `mingw` installed without breaking desktop builds, but at least we know what is the cause.

**Comment by jakubgs** [comment]
Actually, after restarting the host this build didn't fail with the `CMake Error`:
https://ci.status.im/job/nim-waku/job/prs/job/windows/view/change-requests/job/PR-821/5/console

So possibly the previous failure was just a red herring due to change in `PATH` not taking effect.

I will test with the second host.

**Comment by jakubgs** [comment]
One new issue that we can see today is this failure of `make statusgo-lib`:
```
mkdir -p C:\Users\jenkins\workspace\_desktop_branches_windows_master\vendor\status-lib\vendor\status-go\build/bin/statusgo-lib
go run cmd/library/*.go > C:\Users\jenkins\workspace\_desktop_branches_windows_master\vendor\status-lib\vendor\status-go\build/bin/statusgo-lib/main.go
/usr/bin/sh: C:Usersjenkinsworkspace_desktop_branches_windows_mastervendorstatus-libvendorstatus-gobuild/bin/statusgo-lib/main.go: No such file or directory
```
https://ci.status.im/job/status-desktop/job/branches/job/windows/job/master/1343/console
Appears to be a windows path formatting issue, not sure if related to `mingw-winlibs` installation.

**Comment by jakubgs** [comment]
And indeed, if I uninstall it the `make status-go` step works fine:
https://ci.status.im/job/status-desktop/job/branches/job/windows/job/PR-4487/6/console

**Comment by jakubgs** [comment]
I've attempted to install `mingw-nuwen` instead and it appears to work for Desktop builds:
https://ci.status.im/job/status-desktop/job/branches/job/windows/job/PR-4487/7/console

**Comment by jakubgs** [comment]
Fix: https://github.com/status-im/infra-ci/commit/78859767

**Comment by jakubgs** [comment]
I consider this resolved.

**Comment by abhi-status** [comment]
Yes, this is now fixed.
Cheers Jakub!
