### ISSUE TITLE
[bace_bc] messages do appear under separate timestamps when being sent at the same day

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4526]
### Description

1. send a message from mobile to 1x1 chat
2. send a message from desktop to the same 1x1 chat
3. restart the desktop app

<img width="1331" alt="Screenshot 2022-01-24 at 09 49 08" src="https://user-images.githubusercontent.com/82375995/150735157-2d605044-2b65-439a-9817-1503662bec7e.png">

**Comment by saledjenic** [comment]
@anastasiyaig if can please assist on this, as I cannot reproduce it. Would be great if there are some specific steps to follow to reproduce this.

**Comment by anastasiyaig** [comment]
@saledjenic sure, will take a look

**Comment by anastasiyaig** [comment]
can't reproduce now
