### ISSUE TITLE
[base_bc] can't select a community channel

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4538]
### Description

1. create a community
2. select a channel there to send some messages

As result, the placeholder is shown

<img width="1208" alt="Screenshot 2022-01-24 at 16 19 22" src="https://user-images.githubusercontent.com/82375995/150789980-1d087319-f081-498c-a24c-b93554b3fb85.png">

**Comment by jrainville** [comment]
This was fixed by @alaibe in another PR/issue

**Comment by iurimatias** [comment]
this has been fixed
