### ISSUE TITLE
[base_bc] can't search across membership request modal

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4541]
### Description

1. create community which requires membership approval
2. send a request to join
3. open a membership request modal
4. try to search there

![image](https://user-images.githubusercontent.com/82375995/150790883-b3256642-39d5-4ba6-926a-41e05e83de5d.png)

**Comment by Khushboo-dev-cpp** [comment]
https://images.zenhubusercontent.com/261270348/58d65ae5-d879-4df5-8a71-d83a4200cd47/screen_recording_2022_01_26_at_9_42_54_pm.mov

Hey @anastasiyaig this seems to be working as expected? in case the video attached doesn't represent the issue can you please explain what it is?

**Comment by anastasiyaig** [comment]
i can't reproduce the problem in fresh and shiny base_bc, closing this one
