### ISSUE TITLE
Improve translation process (don't use qsTrId)

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#4544]
### Description

The current process of i18n requires changes to the source code, which should not be the case. Currently, with the use of `qstrConvert.js`, each `qsTr()` is substituted with `qsTrId()` in order to make strings aligned with id-based status-react translations (see reasoning [here](https://hackmd.io/@status-desktop/r1ytYSzn_)).

This approach leads to problems when it comes to using a separate Qml Components library, such as StatusQ:

> So far we have avoided putting qsTr() calls in StatusQ. The reason being that status desktop will replace all occurances of qsTr() with qsTrId().
So essentially, it will change the source of StatusQ when it performs i18n.
Hence, we rather expose text properties (with a decent default) so apps like Status Desktop can then assign a qsTr from the outside.

[source](https://github.com/status-im/StatusQ/pull/535#discussion_r787663277)

In short: all strings used in StatusQ are not translated. The client needs to remember that and usually do the boilerplate in the application source code, that is:

StatusQComponent.qml:
```
property string labelStrong: "some default strong label description here"
...
```

ClientApp.qml
```
StatusQComponent {
    labelStrong: qsTr("some default strong label description here")
    // that will be changed by the script to qsTrId("label-strong")
}
```

### What should be done

This could be avoided/improved by not using `qstrConvert.js` as an intermediate step that alters the source code. Instead, `xmlTranslator.js` logic should be enhanced to look for appropriate translations based on strings used in the app (not the ids), in other words: `qstrConvert.js` should be partially merged with `xmlTranslator.js` (more about these scripts [here](https://hackmd.io/@status-desktop/r1ytYSzn_)).

### Acceptance criteria

- enhance `xmlTranslator.js` logic to do translations based on strings rather than ids
- change all `qsTrId()` back to `qsTr()`
- add `qsTr()` for all the strings in StatusQ
- remove duplication of default StatusQ string values in status-desktop
- update [wiki](https://hackmd.io/@status-desktop/r1ytYSzn_) description
- update binary translation files (translate the app)

**Comment by anastasiyaig** [comment]
@iurimatias moved to backlog (reason - nothing to be tested here, no need to keep it in Code Review and QA column)
