### ISSUE TITLE
[base_bc] Communities showed duplicated after restarting app and other issues

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#4546]
# Bug Report

## Description
Issues : 
 - After creating the first community, any community created next is all invisible on the navigation panel
 - After logging out and logging back in, the created communities are visible, but duplicated
 - The Dapp browser & Wallet are not visible any more in the navigation panel.

#### Expected behavior : 
 - All communities must be visible (in the navigation panel) at the first instance of creation without removing any of the enabled apps in the navigation panel

#### Actual behavior : 
https://www.loom.com/share/f400ae94b2f3459b891093016926005a

![image](https://user-images.githubusercontent.com/95302135/150815536-953b1cb0-1fa1-4da4-a758-1eda00a545eb.png)

### Additional Information

- Status desktop commit version: 6caed13f359b17d8e4baa3f4094a873656133411
- Operating System: Ubuntu 20.04 LTS

**Comment by iurimatias** [comment]
fixed in master

**Comment by abhi-status** [comment]
Re-opening this, as this behaviour is now caught on camera! 

https://user-images.githubusercontent.com/95302135/157775703-5f2e601c-1fa2-4d37-8b54-31d42e1133f2.mp4

### Additional Information

- Status desktop version: Master on commit: c80e80bc31584b8d9977a6bb03f9c2a7cea0181d
- Operating System: Ubuntu 20.04 LTS

**Comment by iurimatias** [comment]
can't duplicate
