### ISSUE TITLE
[base_bc] Improve community profile popup to clean up section_item

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#4552]
The section_item has become pretty big because it contains all the community properties that are needed for the community profile popup and community section.

We need to create a community store and when opening the popup, we populate that store from the service using the community Id so that we don't have to put it all in section_item.

Here it is explained by Sale:
That popup which is opened on "EditCommunity", should work with the  "CommunityStore" for example
on an action when we need to open that popup we just need to pass id of the community
that popup updates "CommunityStore" finding appropriate chat section store (for that community) and setting it to the property "communitySectionModule"
store will look something like this:

```qml
QtObject {
    id: root

    property string communityId: ""
    property var chatCommunitySectionModule

    onCommunityIdChanged: {
        mainModule.prepareCommunitySectionModuleForCommunityId(root.communityId)
        root.chatCommunitySectionModule = mainModule.getCommunitySectionModule()
    }

    // This is just a dummy example what functions we should have there
    function getCommunityName(){
        if(!root.chatCommunitySectionModule)
            return ""
        return root.chatCommunitySectionModule.getCommunityName()
    }
 ```
 that means every time we open that popup we just set communityId of the store and related components knows to display everything needed from that store

**Comment by iurimatias** [comment]
removing base_bc tag since this is not really a bug fix
