### ISSUE TITLE
[base_bc] wrong identicon for a 1x1 chat

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4571]
### Description

1. open 1x1 chat with someone
2. notice his identicon color
3. scroll up the chat to see the identicon

<img width="1341" alt="Screenshot 2022-01-25 at 18 05 31" src="https://user-images.githubusercontent.com/82375995/151002514-c788657d-840a-40a6-91fa-da91c16eee2e.png">

**Comment by saledjenic** [comment]
@anastasiyaig I am not sure how to reproduce this, maybe it's fixed in meantime in `base_bc`, but I've tried with few old 1:1 chats, as well as creating new account and initiating 1:1 chat, and all that looked good for me.
