### ISSUE TITLE
[base_bc] Opening the Activity centre blocks clicking UI elements like 'Chat' or 'Settings' in Navigation panel

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#4587]
# Bug Report

## Description

Once the Activity Centre is opened, the Navigation panel is inaccessible to the user.
The Navigation panel is then only available for the user once the Activity centre is not in view.

## Steps to reproduce

- Create a Community
- Create channels within it
- From Settings, enable 'Activity Centre'
- In the channel, open the 'Activity Centre'
- Try selecting any of the options in the navigation panel.

#### Expected behaviour
The user must be allowed to select any of the options available

#### Actual behaviour
The user is blocked from activating any of the selections

https://www.loom.com/share/7a00fa70006e46e6b4ec2688fef8bf33
### Additional Information

- Status desktop version : base_bc on commit : 1246da663e2471bc22abd4363208f27589cce583

**Comment by anastasiyaig** [comment]
this is existing behavior in master and it happens across all the application. Nothing to do with base_bc. and also it is not a bug (for now)
