### ISSUE TITLE
[base_bc] Gif images dont always render in Chats

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#4600]
# Bug Report

## Description

When Gif images dont render on chats, there is only a box that appears in the chat.

## Steps to reproduce
- Go to Settings-->Privacy&Security-->Privacy
- Set both the Display settings to 'On'
- Enable GIFs in Chat Link previews
- Enable Gif Widget in Advanced
- Go to chat and try posting GIFs

#### Expected behavior 
The Gifs must render correctly in chat

#### Actual behavior
![image](https://user-images.githubusercontent.com/95302135/151389916-426fad4f-a4cd-4070-8b48-d014152e3554.png)

### Additional Information

- Status desktop version: base_bc, commit: fc8b4211aa974296cceaabe093ff402b28f17dab

**Comment by iurimatias** [comment]
I can't replicate this

**Comment by alaibe** [comment]
In some cases, when we cannot unfurl properly the link such as: https://giphy.com/clips/therokuchannel-roku-the-channel-doomlands-nGRZFVSOlUXoCc34c9

It shows nothing
