### ISSUE TITLE
[base_bc] unfurling a link does not shown properly in chat

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4608]
### Description

example URL https://our.status.im/v1-18-release-binance-ens-reliability-syncing/

```
qrc:/imports/shared/views/chat/CompactMessageView.qml:551: TypeError: Property 'scrollToBottom' of object MessageStore_QMLTYPE_968(0x7f9dae23bf70) is not a function
```

<img width="1027" alt="Screenshot 2022-01-28 at 09 38 54" src="https://user-images.githubusercontent.com/82375995/151499755-fe75d556-bf9e-4ac4-9922-fae8553d09f4.png">

**Comment by abhi-status** [comment]
This issue is now present in Master. 
Re-opening.
![image](https://user-images.githubusercontent.com/95302135/152166352-fbd0f410-9af6-47eb-9af7-36f432ddfbd9.png)
