### ISSUE TITLE
Integrate codechecker with Jenkins

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#4640]
To ensure everyone is following clang-tidy configuration (https://hackmd.io/@tvcxYXntQVCosMs79UIszw/rJxhcBHCY) [codechecker](https://github.com/Ericsson/codechecker) should be [integrated](https://github.com/Ericsson/codechecker/blob/master/docs/usage.md#step-8) with Jenkins to generate daily report summaries and to implement CI guard to prevent the introduction of new bugs into the codebase.

Relates to: #4430

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5745
