### ISSUE TITLE
re-add to master: fix(@desktop/wallet): Fix for - Recipient of the transaction message 

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4680]
35388b0f6d4f59e851fbb86d2d728b1c5d54b064

**Comment by jrainville** [comment]
The Chat command stuff is not fully refactored yet, so I'll keep this one in the backlog for now

**Comment by jrainville** [comment]
Fixed by #4762

**Comment by Khushboo-dev-cpp** [comment]
Done under https://github.com/status-im/status-desktop/pull/4762
