### ISSUE TITLE
List of suggestions is not showing up when pasting @ to mention someone in chat

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4754]
### Description

mentions don't show the autocomplete menu, also emojis etc..

**Comment by anastasiyaig** [comment]
i was not able to reproduce problem with emojis and etc, however the mentions indeed are not showing up (list of suggestions when using @ )

**Comment by jrainville** [comment]
I think this was fixed in master already, can you try again?

**Comment by anastasiyaig** [comment]
i will close it
