### ISSUE TITLE
Can't perform transaction in Dapp

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4776]
### Description

1. open status and recover account with test ETH
2. switch to Ropsten
3. enable browser
4. open simpledapp.eth
5. go to assets tab
6. click Request STT

As result, error in console:

```
qrc:/imports/shared/controls/ContactSelector.qml:200:25: Unable to assign [undefined] to QString
qrc:/imports/shared/popups/SignTransactionModal.qml:350:9: Unable to assign [undefined] to QObject*
qrc:/app/AppLayouts/Browser/views/WebProviderObj.qml:61: TypeError: Cannot assign to read-only property "sendTransaction"
```

**Comment by jrainville** [comment]
Can you test again on master. I was able to request the STT and after a delay and closing an re-opening I got the STT in my account
