### ISSUE TITLE
new direct chat / group chat functionality

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4781]
### Description

as per design https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop-(rolled-back-version-to-recover-a-screen%2C-ignore)?node-id=112%3A26519

should use the `StatusTagSelector` component from statusQ https://github.com/status-im/StatusQ/pull/537
to be done after new `startGroupChat `API introduced by https://github.com/status-im/status-desktop/issues/4735
should use status-go PR https://github.com/status-im/status-go/pull/2531

![Screen Shot 2022-02-10 at 5 30 54 PM](https://user-images.githubusercontent.com/176720/153507626-d84551f7-1307-4d18-9ddd-98143472dd34.png)

**Comment by alexandraB99** [comment]
backend https://github.com/status-im/status-go/pull/2525
