### ISSUE TITLE
contact verification request

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4784]
### Description

to be done after https://github.com/status-im/status-desktop/issues/4783

design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1838%3A358150

spec: https://github.com/status-im/feature-specs/pull/41

**Comment by elina2015** [comment]
@iurimatias I cannot open the design for this ticket. Could you kindly help?
![Image](https://user-images.githubusercontent.com/14942081/170894775-517e8250-beb5-4229-beb9-3f54cb645c68.png)
