### ISSUE TITLE
Can't open transaction details on etherscan

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4786]
### Description

1. open status (u should have some test ETH)
2. switch to ropsten
3. enable browser 
4. open simpledapp.eth
5. click Assets
6. reqest stt
7. confirm transaction
8. click View on etherscan link
9. select Open in Status
10. select Open in Browser

As result, I can't open the link , it is undefined

```
http://undefined/0x4896135625ac8987886047e99865007f5337f497a4514540f8461565ad40cdd4
```

<img width="1035" alt="Screenshot 2022-02-11 at 10 09 31" src="https://user-images.githubusercontent.com/82375995/153550793-e58adcf0-f277-4e7c-9310-af4f49a0bf4b.png">

<img width="372" alt="Screenshot 2022-02-11 at 10 09 09" src="https://user-images.githubusercontent.com/82375995/153550825-2cc528a4-443a-4ee6-93e0-a54052c893e0.png">

**Comment by iurimatias** [comment]
assigning to wallet cohort, this needs to be fixed taking into account new multinetwork and the test mode
