### ISSUE TITLE
support sending audio messages

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#479]
https://github.com/status-im/status-react/pull/10810

**Comment by richard-ramos** [comment]
This codec is open source / royalty free, and it's the same one being used by Discord: 
https://opus-codec.org/docs/

**Comment by iurimatias** [comment]
https://github.com/status-im/status-desktop/pull/729

**Comment by pinebit** [comment]
New design from @simonricoo https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=8135%3A48835

**Comment by pinebit** [comment]
We still cannot move on with this feature, until we finalize the protocol change and, in particular, Opus support with mobile team.

**Comment by iurimatias** [comment]
previous PR to re-implement in new architecture: https://github.com/status-im/status-desktop/pull/3164
