### ISSUE TITLE
mentions not showing all known contacts in the chat

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4794]
# Bug Report

## Steps to reproduce

1. join a chat
2. trying @ another user in the chat log

result: user not showing

there is also this issue where typing `@` deletes the begining of the text input

https://user-images.githubusercontent.com/176720/153677980-64df2dcd-8f9c-4059-b35e-9dcafada3e52.mov

**Comment by alexandraB99** [comment]
I wasn't able to reproduce this on current master.
