### ISSUE TITLE
the search is showing chats as search results and clicking on it shows the view profile modal

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4795]
# Bug Report

## Description

the search is showing chats as search results (do the designs have this?) and when clicking on the chat it shows a view profile modal

expected: it shouldn't show the view profile modal for sure since it's a chat not a profile, but unclear what is the behaviour here, I don't recall seeing this in the designs

**Comment by jrainville** [comment]
I confirmed that it should show channels: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=6044%3A794

The click on them is clearly a bug though. I'll fix it.
