### ISSUE TITLE
No chat shown when new messages are sent immediately after adding a contact (msg sent via the added contact)

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#4799]
# Bug Report

## Description

New message chat is not shown until either the contact request sender reboots the app or the user selects the new contact (via Settings --> Contacts)

## Steps to reproduce
1 - Add a known contact on the desktop app
2 - On another app, accept the contact request and send a message immediately to the request sender.

#### Expected behavior
Message chat is shown (on the contact request sender's desktop app) when there are new messages

#### Actual behavior
https://www.loom.com/share/1f0af2ac718042ba9d7d050bbf12d239

### Additional Information

- Status desktop version: Master on commit: 7268ec377349f97c40164a9097588ccecd954d78

**Comment by saledjenic** [comment]
@iurimatias @abhi-status I checked the latest master and it works just fine there. 

Once one accepts a sent contact request 1:1 chat is created on the side of one who sent a contact request, even if none message is sent by callee.

**Comment by jrainville** [comment]
Yeah this was fixed by Boris previously
