### ISSUE TITLE
Fetching messages is not being performed automatically when reconnecting

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4810]
### Description

1. open status and join # nastya public chat
2. switch off internet connection completely
3. click Fetch messages (nothing fetched, indicator of loading is present)
4. enable internet connection
5. nothing is fetched, i have to click Fetch messages several times to get messages displayed eventually

**Comment by jrainville** [comment]
I created this https://github.com/status-im/status-desktop/pull/4895 PR that re-adds the connected banner.
The code to re-fetch messages was already there when the re-connect happens. Can you check @anastasiyaig if now it works as you expect?
