### ISSUE TITLE
Chat: Usage of stores needs to be stream lined

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#4823]
# Bug Report

The issue in chat is that in some places the module from the store is directly exposed in a file and then passed to other files, this is incorrect and the store instance should be shared instead. 

Example : https://github.com/status-im/status-desktop/blob/0acfd9b50c4be8a81d676ba94fdb26e44b1318cd/ui/app/AppLayouts/Chat/views/ChatContentView.qml#L31

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5744
