### ISSUE TITLE
error uploading image to a channel

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4825]
# Bug Report

## Description

uploaded an image to a community channel and got the following

![Screen Shot 2022-02-16 at 9 42 35 AM](https://user-images.githubusercontent.com/176720/154288252-59ce9931-4c04-4180-8059-55a908b1e252.png)

**Comment by jrainville** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/4761
