### ISSUE TITLE
Message history is not fetched when getting back from sleep mode

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4832]
### Description

1. join community (GammaOne in my case)
2. receive some messages here
3. close the laptop or move it to sleep mode, so status app is not shut down
4. during this, send some messages to community
5. open the app and check messages

As result, u need to restart the app to fetch the messages

**Comment by iurimatias** [comment]
possibly fixed by https://github.com/status-im/status-desktop/pull/5001
