### ISSUE TITLE
Adding a public chat automatically adds it to community channels list

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4859]
### Description

1. create community
2. create several channels there
3. join a public chat
4. review list of channels in community

As result, the channel that u joined, is added to channels' list of community

Also, 
- your contacts get added into the Community
- When you create another community and create channels here, this gets duplicated in the first community
![image](https://user-images.githubusercontent.com/95302135/155181478-f9a92cd4-716d-46b3-8e51-12e90299b056.png)

**Comment by jrainville** [comment]
I think this is related to #4858, so I'll try to fix them both at the same time
