### ISSUE TITLE
revamp notifications settings & behaviour

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4902]
figma: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=973%3A105649

before starting development on this task, the spec on https://github.com/status-im/feature-specs/pull/33 needs to be updated based on the new design and using a tool such as https://www.archimatetool.com/ to create a diagram

**Comment by iurimatias** [comment]
the spec needs to upgraded, with a diagram based on the new design and using https://www.archimatetool.com/

**Comment by saledjenic** [comment]
@iurimatias specs updated, diagrams added, [here](https://github.com/status-im/feature-specs/blob/dec51e11671453e3d471f703c311728757369069/content/raw/chat/notifications.md).
