### ISSUE TITLE
editing a channel name does not immediatly update the name in the channel list

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4912]
# Bug Report

## Steps to reproduce

1. create a community
2. create a channel
3. right click and edit the channel name

result: the channel name is updated but not in the channel list

![Screen Shot 2022-02-25 at 5 18 34 PM](https://user-images.githubusercontent.com/176720/155810872-435fbb10-f98c-43a7-844b-d8316242ccc3.png)

**Comment by endulab** [comment]
@iurimatias do you mean automatic update of these places when click "Save" ? 

![image](https://user-images.githubusercontent.com/61889657/157460771-623015ed-4645-4dbb-9823-61c68801c0a6.png)

If yes, it seems to work correctly.

**Comment by endulab** [comment]
@status-im/desktop-qa maybe someone can verify it too.

**Comment by jrainville** [comment]
It might have been fixed since then. There were a couple of code fixes to the community signals

**Comment by iurimatias** [comment]
confirmed, it has been fixed
