### ISSUE TITLE
selecting the category menu should not toggle the category itself

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4914]
# Bug Report

https://user-images.githubusercontent.com/176720/155811453-19379172-05d8-4b8e-90ad-e608929fa5b8.mov

**Comment by PascalPrecht** [comment]
I think the description of this issue is a bit misleading as mentioned here: https://github.com/status-im/StatusQ/pull/603/files#r836330202

Clicking the category should still toggle it. Clicking the buttons of the category should not.
Can you confirm @iurimatias
