### ISSUE TITLE
Keycard settings screen & functionality using status-keycard-go

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4920]
### Description

see designs: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=199%3A2653

![Screen Shot 2022-02-27 at 2 16 36 PM](https://user-images.githubusercontent.com/176720/155896465-109fe951-0c60-499d-9ba1-2310dc644d84.png)

New Setting screen for keycard that supports setting up a new card, importing an account into a keycard, importing an account from a keycard, and unlocking a keycard using the [status-keycard-go](https://github.com/status-im/status-keycard-go) library.
For the scope fo this task, only the settings screen functionality should be implemented, the integration with the wallet should be done in another task.

- [x] #7023
- [x] #7025
- [x] ~~toggling keycard in advanced settings will display the new Keycard section in the settings - **???? to check if this is still a requirement**~~
- [x] #7026
- [x] #7027
- [x] #7028
- [x] #7029
- [x] #7030
- [x] #7031
- [x] #7032
- [x] #7033
- [x] #7034
- [x] #7035
- [x] #7036
- [x] #7037
- [x] #7038
- [x] #7641
- [x] #7642
- [x] #8759

**Comment by John-44** [comment]
@iurimatias design update: @ahowell3 has restarted design of these screens from where Blake left off, I think it will probably take 2 to 3 weeks to get the designs of these screens completed.

**Comment by saledjenic** [comment]
The design from the description is a bit outdated, this is a link to new keycard settings figma file:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=3589%3A157367
