### ISSUE TITLE
New Onboarding screens

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4921]
### Description

designs: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop-(rolled-back-version-to-recover-a-screen%2C-ignore)?node-id=1023%3A298171

The goal is to adjust & implement the onboarding screens to match the new designs.

However In the scope of this task the following is excluded:
- the keycard screens are excluded since #4920 is needed first
- windows & linux keychain auth is excluded (it's a task on its own), however touch id is included since that functionality is already supported
- settings/profile screens are excluded, the scope of this task is for onboarding only

other:
- new profile screen is being done in #4783 by @richard-ramos
- password strength screen is being done in #4785 by @noeliaSD 
- the sync screen is likely not possible at this point but would be nice to have the UI ready so this can be done in another task

- [x] #4954
- [x] #4974
- [x] #4956
- [x] #4957
- [x] https://github.com/status-im/StatusQ/issues/567
- [x] #4955
- [x] #5230

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8839
