### ISSUE TITLE
Intermittent login issue after a log out

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#4927]
# Bug Report

## Description

As a community member has reported recently [here](https://www.reddit.com/r/statusim/comments/t0qf3e/wrong_password_every_time_i_logout/),
the user is not able to log back in after a logout operation.

I have not been able to reproduce this.

## Steps to reproduce 
1 - Do a clean installation of the desktop app (beta).
2 - Enter the keys and notice everything works fine. 
3 - Then close the app and the next time I try to log in it says that my password is wrong.

### Additional Information
Noelia may have had a _slightly similar_ issue (on every branch) where the error msg was :
![image](https://user-images.githubusercontent.com/95302135/156034953-2f9f5115-6b2f-49bc-baea-c6fae8be260f.png)

However, this was rectified by deleting the Status folder.

- Status desktop version: n/a
- Operating System: n/a

**Comment by iurimatias** [comment]
This usually happens when different versions of status-go are used, it usually happens to devs because we keep switching branches. Still will keep this open for now so we can investigate further

**Comment by saledjenic** [comment]
@abhi-status this is really hard to reproduce if it's still an issue, if you have any input how, would be great, so far it works fine for me.

**Comment by abhi-status** [comment]
@saledjenic I have not seen this behaviour recently.
