### ISSUE TITLE
Communities Settings screen

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4932]
### Description

design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1511%3A137580

![Screen Shot 2022-02-28 at 5 25 26 PM](https://user-images.githubusercontent.com/176720/156068688-eb8602d3-abd3-4283-bb9a-9de8a78dd2e0.png)

out of scope:
- Community welcome message

**Comment by elina2015** [comment]
@borismelnik please check my [comment](https://github.com/status-im/status-desktop/pull/5097). Thanks!:)

**Comment by elina2015** [comment]
@borismelnik please check my comments for the PR. Thanks!

**Comment by elina2015** [comment]
@borismelnik please check the [PR](https://github.com/status-im/status-desktop/pull/5097) - there are some issues are found. Thanks!

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9200&group_by=tests:status_id&group_order=asc
