### ISSUE TITLE
Update Help & Glossary to the new design

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4934]
### Description

~~design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1511%3A137592~~ Design needs to be updated

![Screen Shot 2022-02-28 at 5 33 55 PM](https://user-images.githubusercontent.com/176720/156069772-07d8da12-8637-4981-96b7-fc43b571d55c.png)

**Comment by stefandunca** [comment]
Closing after talking to @John-44. Major concept redesign is coming in this area, making current designs absolute.

**Comment by iurimatias** [comment]
closing since this section has been removed
