### ISSUE TITLE
Communities Portal

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4936]
### Description

Designs: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2244%3A246844

![Screen Shot 2022-02-28 at 5 44 47 PM](https://user-images.githubusercontent.com/176720/156070912-3797bcbb-f4a2-4d66-a69c-934f4917e8f2.png)

Scope:
- UI/QML only

Out of scope:
- **Tags row** component `StatusListItemTagRow` --> https://github.com/status-im/StatusQ/issues/690
- **Searcher** (just only add the control and keep it disabled)
- **Import** and **Create** buttons  (just only add the controls and keep them disabled)
- **Community Card**: neither tags nor community requirements and it will be clickable but the navigation action will be pending to implement.

Subtasks:
* [x] General `Community Portal` layout
* [x] Page API (needed property models and signals)
* [x] Create `StatusQ` component: `StatusCommunityCard` as it is in desktop desing. --> Second iteration here: https://github.com/status-im/StatusQ/issues/692

**Comment by iurimatias** [comment]
A possibility is to start with the UI work, skip search and import, and using a hard coded json list of featured communities. then implement the portal getting the list from somewhere (i.e blockchain) in a different task.

**Comment by noeliaSD** [comment]
Backend parallel task: https://github.com/status-im/status-desktop/issues/5720
