### ISSUE TITLE
New Communities settings

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4938]
### Description

designs: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop-(rolled-back-version-to-recover-a-screen%2C-ignore)?node-id=3250%3A369535

Clicking "Manage Community" or the Category name at the top should show the communities settings. This replaces the previous modal.

![Screen Shot 2022-02-28 at 6 01 02 PM](https://user-images.githubusercontent.com/176720/156072781-9f85fb91-3f68-4e58-b850-984c8cd3917f.png)

![Screen Shot 2022-02-28 at 6 04 38 PM](https://user-images.githubusercontent.com/176720/156073137-69d9f81c-e515-43cd-a1b0-51b695e8818b.png)

In scope:
- Overview
- Members
- Notifications (simple toggle)

Out of scope sections:
- Permissions, Tokens, Airdrops, Token sales, subscriptions,

Out of scope in overview:
- Transfer Owner Node
- Tags
- Community history service
- Block users with duplicate usernames (unless already implemented)
- Any member can pin a message
- Dialog for new members
- New color picker

Out of scope in members:
- Pending Requests (unless already implemented)
- Number of Messages
- view messages
- delete messages from a banned user

**Comment by osmaczko** [comment]
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=3250%3A369535
link to correct figma

**Comment by osmaczko** [comment]
As discussed with @John-44 and @cammellos the confirmation mechanism is missing or the clarification of how auto-save should work. Waiting for further input.
