### ISSUE TITLE
Support permissions based posting based on ENS names

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4939]
edit: "We already have ENS token permissions in place, the only thing that's missing is that we need to check them onchain."

status-go task for https://github.com/status-im/status-desktop/issues/5981

- [ ] Api to associate a ens name (any domain, or a custom one) to read and/or write (for now? other stuff out of scope) to 1 or more community channels
- [ ] flag & field to indicate a community channel needs permission and what requirements it needs

note: this is a backend task required by https://github.com/status-im/status-desktop/issues/5981

**Comment by anastasiyaig** [comment]
@richard-ramos @iurimatias what is the state of it?

**Comment by richard-ramos** [comment]
There's an open PR that modifies status-go to add ensOnly communities: https://github.com/status-im/status-go/pull/2722
I see that the UI work was marked as complete https://github.com/status-im/status-desktop/issues/5981 so I imagine a task shoub be created to do the integration between UI and status-go change

**Comment by 0x-r4bbit** [comment]
**UPDATE**: This issue is now for tracking whether we're checking ENS in token permissions for BECOME_MEMBER permissions. Channel based permissions aren't implemented yet.

**Comment by 0x-r4bbit** [comment]
Permissions checks on ENS names have landed in the reference PR
