### ISSUE TITLE
Improve StatusEmojiPopup speed and add loading indicator

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#4959]
The StatusEmojiPopup, which is the component that is used for the chat emoji selector in the bottom right and now for the channel emojis, is pretty slow to open because it needs to parse the emojis to create the categories. 

I checked it out and it can be improved a bit.

More importantly, it should have a loading indicator or at least a "Loading..." text to show that it is doing something.
Right now, when you click the button to show the emojis, nothing happens for a second.

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5744
