### ISSUE TITLE
Inject HTML Code in several sections

### ISSUE THREAD

**Issue by serhanwbahar** [status-im/status-desktop#4961]
# Bug Report

## Description

It is possible to use HTML code in several places. This bug came from HackerOne. The original report is [here](https://hackerone.com/reports/1491346). There is no security impact. _(JavaScript code is not running)_

1. Add Contact:

![add_contact](https://user-images.githubusercontent.com/47040097/156632774-5c2df92b-16ca-4ba0-b055-1e11b6685da3.png)

2. Web Browser Tabs:

![webbrowser](https://user-images.githubusercontent.com/47040097/156633158-bb02e13c-e6dc-490b-a701-8f1476de3b0a.png)

3. Homepage Configuration:

![homepage](https://user-images.githubusercontent.com/47040097/156633505-3e183e45-18af-4b29-ab75-9d32062570e1.png)

4. Username:

![nickHtmlPage](https://user-images.githubusercontent.com/47040097/156633775-84abf3a9-8647-4190-b4a7-6cd195845bdb.png)

5. Wallet Name:

Payload: `<img src="https://www.w3schools.com/tags/planets.gif" width="145" height="126" alt="Planets">`

![wallet_name](https://user-images.githubusercontent.com/47040097/156633965-e7754eeb-353d-44f5-a702-2541238f3cd9.png)

![wallet2](https://user-images.githubusercontent.com/47040097/156634056-cf8b0224-82f8-4cab-8cd0-84ff90bbe38e.png)

## Steps to reproduce

1. Input HTML code to the sections above.

**Comment by elina2015** [comment]
@stefandunca Hey, there are some bugs that are still reproduced. Could you kindly check? 

**1. In the Homepage configuration:**
**Steps:**
 - Go to Setting-Browser-Homepage
 - Enter: `<img src="https://www.w3schools.com/tags/planets.gif" width="145" height="126" alt="Planets">` and click "Paste"
 - Check the Settings page
**Actual Result:**
The HTML injection is applied
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/14942081/158515502-4195bcc4-64ca-410b-8695-97d8d3dcc848.png">

**Expected Result:** 
The injection is not applied.

**2. In "Favorites" websites:**
**Steps:**
1. Go to Browser - Add Favorite
2. For Name and URL enter: 
`<img src="https://www.w3schools.com/tags/planets.gif" width="145" height="126" alt="Planets">` and click "Add"
**Actual Result:**
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/14942081/158516113-9c8302cd-343b-458d-a167-a5544f1f309c.png">
**Expected Result:**
It's impossible to save HTML injection as Name or URL for the Favorite website

**Comment by elina2015** [comment]
@stefandunca I found two places where the HTML injections still have place. Could you kindly check them?

1. Settings - Contacts - Add new contact. Enter the html injection in the field: <img src="https://www.w3schools.com/tags/planets.gif" width="145" height="126" alt="Planets">
**Actual Result:** the loader is shown infinitely:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/14942081/159144167-e36ce669-57f1-4815-ab2a-efba8398b24b.png">

3. As a wallet name, user can enter the HTML injection:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/14942081/159145072-b1396807-bc99-420f-99fb-5417efa1b08c.png">

**Comment by stefandunca** [comment]
> @stefandunca I found two places where the HTML injections still have a place. Could you kindly check them?
> 
>     1. Settings - Contacts - Add new contact. Enter the html injection in the field: `<img src="https://www.w3schools.com/tags/planets.gif" width="145" height="126" alt="Planets">`
>        **Actual Result:** the loader is shown infinitely:
> 
> 
> <img alt="image" width="542" src="https://user-images.githubusercontent.com/14942081/159144167-e36ce669-57f1-4815-ab2a-efba8398b24b.png">
> 
>     3. As a wallet name, user can enter the HTML injection:
> 
> 
> <img alt="image" width="1182" src="https://user-images.githubusercontent.com/14942081/159145072-b1396807-bc99-420f-99fb-5417efa1b08c.png">

@elina2015 great findings. Given that these issues pop up more and more I will talk later on with the team to switch the defaults of our text custom components to plain text and go for an application regression to handle the side effects of switching from HTML input as default.

**Comment by stefandunca** [comment]
@elina2015 I covered Saved Addresses and Wallet Account Name. Please have another look.

**Comment by elina2015** [comment]
@stefandunca thank you so much for fixing the issues with contacts and wallet. I found another place where the HTML injections are still available. Could you kindly check it?
**HTML injection is available in the community description**
1. Go to create a public community and add the HTML injection in the Description field: `<img src="https://www.w3schools.com/tags/planets.gif" width="145" height="126" alt="Planets">` or `<a href="https://www.w3schools.com">Visit W3Schools</a>`
2. Save the community and check the community description
_Actual Result:_
<img width="542" alt="image" src="https://user-images.githubusercontent.com/14942081/160265355-647bbafa-0f08-40ee-a268-b22ea210f94a.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/14942081/160265400-59d543d4-dbf4-4e5d-8cd2-2c05c7c587f7.png">

**Comment by elina2015** [comment]
@stefandunca thank you so much!
