### ISSUE TITLE
Chatting with yourself is not restricted properly

### ISSUE THREAD

**Issue by serhanwbahar** [status-im/status-desktop#4962]
# Bug Report

## Description

It is possible to chat with yourself. Normally, there is a restriction when you want to add your key without going through this form. But it is possible to add you as a contact.

This bug came from HackerOne. The original report is [here](https://hackerone.com/reports/1491346). There is no security impact.

## Steps to reproduce

1. Click on the share chat key.
2. Click on "Add to contact."
3. Say "Hi" to yourself.

![addYou](https://user-images.githubusercontent.com/47040097/156636075-634e1873-776f-4fb5-b98f-63b9c97c6829.png)

**Comment by endulab** [comment]
I could not reproduce the problem.
Also, I discussed it with @abhi-status.
It seems that there is no way to chat to yourself in a current master.
FYI @serhanwbahar @status-im/desktop-qa
