### ISSUE TITLE
Add button to toggle use of mailservers

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#5000]
It should use `wakuext_toggleUseMailservers` from https://github.com/status-im/status-go/pull/2512/

**Comment by iurimatias** [comment]
![tempFileForShare_20220317-172718](https://user-images.githubusercontent.com/176720/158898279-7fbea715-7a3b-4421-8308-04042276ccc9.jpeg)

**Comment by jrainville** [comment]
For more info and the designs, see here: https://github.com/status-im/status-desktop/issues/5015
