### ISSUE TITLE
Can't sign in to Cryptokitties (sing a message to dapp)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5013]
### Description

1. create account
2. enable browser in settings - advanced - browser
3. open browser
4. in browser open cryptokitties.io
5. slick Start button
6. allow the permissions when asked for
7. sign a message to this dapp

<img width="1395" alt="Screenshot 2022-03-10 at 17 52 02" src="https://user-images.githubusercontent.com/82375995/157688135-079540fa-3535-4409-9948-2b8bd757139e.png">

**Comment by iurimatias** [comment]
duplicate of #3323

**Comment by Khushboo-dev-cpp** [comment]
https://user-images.githubusercontent.com/60327365/168264192-fa52caac-00af-477e-be14-d3ffd2d6f1ba.mov
