### ISSUE TITLE
On other App instances, adding or deleting channels don't always get updated in the Community until the app is restarted

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5023]
# Bug Report

## Description
Deleting channels works locally.

However, on other app instances (that have accounts present in a community), the Community channels list does not always update the deletion until the app is restarted. Same for adding channels.

It seems like sometimes we don't send or maybe we don't receive the signal.

## Steps to reproduce
- Create a few community channels
- Add a contact
- On the added contact's app, accept the invite
- From the primary app, delete 1 of the channels
- Go back to the 2nd app and note the channel list

#### Expected behavior
The channel is deleted from the 2nd app

#### Actual behavior
The channel remains until the app is restarted

### Additional Information

- Status desktop version: Master on commit: c80e80bc31584b8d9977a6bb03f9c2a7cea0181d

https://user-images.githubusercontent.com/95302135/157775008-8deed9f3-0842-43aa-b9b4-a9b8dbcdc1f3.mp4

**Comment by jrainville** [comment]
We both can' reproduce anymore

**Comment by abhi-status** [comment]
> We both can' reproduce anymore

can'T  😆
