### ISSUE TITLE
User cannot re-encrypt new keys

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5029]
# Bug Report

## Description

This happens only when the App is in the state - 
logged out after being signed in previously and user having tried to enter a wrong pwd. 

In this situation, when the user tries to use the seed phrase to re-encrypt a new pwd, they find that the UI is stuck & they cannot re-encrypt the new keys when they hit `Create Pwd` button at the end of the Re-encrypt flow with the following log :

![image](https://user-images.githubusercontent.com/95302135/158075937-085ca67b-cc15-4b18-bd4b-a73acdb50bcf.png)

## Steps to reproduce 
- Sign in to an account
- Once signed in, go to `Settings` and click `Sign out & Quit` to sign out.
- Launch the app again and entera wrong Pwd to simulate user forgetting their Pwd
- Click the drop down arrow beside the account name
- Click the `Add another existing key` button to enter the existing saved seed phrase for this account (_**or another account**_)
- Hit `Re-encrypt your keys` button
- Enter the new Pwd and hit `Create Pwd`

#### Expected behaviour
User is able to create a new Pwd

#### Actual behaviour
https://user-images.githubusercontent.com/95302135/157882689-c8483702-26bf-4ad8-94ae-f4f67b7a0d9f.mp4

### Additional Information

- Status desktop version: Master

**Comment by jrainville** [comment]
This is the "wanted" behaviour in status-go:
```go
// ErrAccountAlreadyExists is returned if an account attempted to import is
// already present in the keystore.
ErrAccountAlreadyExists = errors.New("account already exists")
```

We have 2 options:
- Show a warning in the UI saying "you can't import this account again, it already exists". We can also tell them if they lost their password, they can delete the database and re-import
- Edit status-go to permit doing that, but then, it wouldn't re-encrypt the existing DB. We'd need to erase the previous one and re-create it, so the user might get bamboozled
- I guess there is a third option which is the mix of both where we still return the error as it is from status-go, we show a warning in the UI, but add a button that says "I want to create a new DB I understand that I'll lose my data", then we create a new status-go endpoint that does what I said above, forces the deletion of the old DB and re-creates it.

cc'ing @iurimatias and @cammellos for their opinion on the matter

**Comment by jrainville** [comment]
I'll tackle this issue as mobile has done, which is to show a warning when this happens.

Then I created a new issue to further improve the behaviour https://github.com/status-im/status-desktop/issues/5130
