### ISSUE TITLE
User stays on removed account view in wallet after account removal from settings

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5037]
### Description

1. open status
2. go to settings and enable wallet toggle
3. add watch only account (in addition to the status account) and select it (click on it)
4. go to settings - apps - wallet 
5. select watch only account 
6. click remove and confirm
7. click wallet tab

As result, the wallet is still showing previously selected (and currently removed) account

https://user-images.githubusercontent.com/82375995/158198023-f6193e96-53d0-4bf0-8630-ffa6e386b268.mov

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8813&group_by=cases:section_id&group_order=asc
