### ISSUE TITLE
refactor: new getWallets api

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5050]
### Description

This needs to be done after other refactors in the wallet api, and we need to specifying the API before agreeing.
A possibility is to do an api similar to the new getChats api, which returns everything that is needed in one call, and then changes are sent through signals.

```
{
    AccountA:
        name: foo
        type: generated
        balance
        Tokens:
            A :value
              :price
              :balance
            B :value
              :price
              :balance
        collectible:
            A:
            B:
        history:
          txA: 
          txB        
}
```

**Comment by alaibe** [comment]
On hold till CPP app

**Comment by iurimatias** [comment]
closing in favour of https://github.com/status-im/status-desktop/issues/5744
