### ISSUE TITLE
The seed phrase field doesn't have the words limit

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5060]
# Bug Report

## Description
The seed field doesn't have restrictions about the number of words inputted

## Steps to reproduce
1. Sign out
2. On the main screen click on the arrow near the user name
3. Click 'Add another existing key'
4. Enter the long text (e.g. 40000 words)

#### Expected behavior
The field has a limit of 24 words
#### Actual behavior
the field doesn't have a limit of words
### Additional Information
<img width="507" alt="image" src="https://user-images.githubusercontent.com/14942081/158531534-984b5ef8-f4e4-40f3-933d-c8cde30b881a.png">

- Status desktop version: commit b07910e27feed930ba0b73b18b791bffb7b7b229
- Operating System: Mac OS Big Sur 11.6.5 (20G517)

**Comment by iurimatias** [comment]
note: this issue might soon become outdated with @alexandraB99 work on the onboarding section

**Comment by iurimatias** [comment]
marking this issue as on hold / icebox, to be reviewed after the new onboarding work

**Comment by iurimatias** [comment]
closing since UI changed and this no longer applies
