### ISSUE TITLE
It's possible to enter and save more than 24 characters as a Display Name

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5066]
# Bug Report

## Description
Users can enter more than 24 characters as a Display Name

## Steps to reproduce
1. Sign out
2. Click 'Generate new keys'
3. In the field 'DisplayName'  enter more than 24 characters
4. Click on the arrow-button
#### Expected behavior
It's impossible to enter more than 24 characters
#### Actual behavior
It's possible to enter 24 characters and save it
<img width="519" alt="image" src="https://user-images.githubusercontent.com/14942081/158737999-165ed437-7fb3-44ef-ad0c-a52a96704902.png">

### Additional Information

- Status desktop version: commit b07910e27feed930ba0b73b18b791bffb7b7b229
- Operating System: MacOS 11.6.5 (20G517)

**Comment by iurimatias** [comment]
same/similar issue as https://github.com/status-im/status-desktop/issues/5067

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8799&group_by=cases:section_id&group_order=asc
