### ISSUE TITLE
The error 'Faucet request error' appears when trying to add test ETH

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5085]
# Bug Report

## Steps to reproduce
1. Sign in
2. Open Settings - Advanced
3. Activate wallet and browser and click "I understand"
4. Activate Settings - Advanced - Network - Ropsten ..., click "Confirm"
5. Relaunch the app
6. Open browser in the app and open simpledapp.eth
7. Click "Assets" - Request Ropsten ETH

#### Expected behavior
Ropsten ETH is added correctly without errors
#### Actual behavior
1. The error is shown: Faucet request error
3. The text of the error is not clear
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/14942081/158933429-7a866b61-5857-4261-94e9-21b703a7a516.png">
<img width="695" alt="image" src="https://user-images.githubusercontent.com/14942081/158933466-08422909-0eeb-4482-b683-779f77d1f367.png">

### Additional Information

- Status desktop version: commit e1b7475884a8d1f8ab3c39a3e05abaf03821129b
- Operating System: MacOS 11.6.5 (20G517)

**Comment by anastasiyaig** [comment]
it is not a bug of the status app. it is a bug of simpledapp. also, the ETH is actually sent.
