### ISSUE TITLE
'Add new Contact' feature is missing

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5095]
# Bug Report

## Description

Go to Messaging -> Contacts

#### Expected behavior
The user must see the 'Add new Contact' button
![image](https://user-images.githubusercontent.com/95302135/159243300-36bd3dbd-2cfa-4579-9b8a-9d2744cca954.png)

#### Actual behavior
There is no option to add new users
![image](https://user-images.githubusercontent.com/95302135/159243343-d625cd59-990c-4b27-9427-c339f3ea54d6.png)

### Additional Information

- Status desktop version: Master on commit: 9e0b8c5e90d3e2413698d334867ca56d847b41bf

**Comment by anastasiyaig** [comment]
it is expected , please check new designs that were implemented recently

@iurimatias @jrainville

**Comment by iurimatias** [comment]
confirmed, it's expected behaviour
