### ISSUE TITLE
The loader is shown infinitely in the chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5108]
# Bug Report

## Description

The loader is shown infinitely in any chat after all content appears

## Steps to reproduce
1. Sign in
2. Open any chat (public, private, 1-1)
3. Check the bottom right corner of the chat screen

#### Expected behavior
The loader is not shown infinitely.
#### Actual behavior
The loader is shown infinitely while there is no content for loading.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/14942081/159355817-33a27fe4-a27e-47d4-8bbc-cb69ef2dfc13.png">

### Additional Information

- Status desktop version: commit 803cc77e9578be1d1f906a3fe10e742ff49af925
- Operating System: MacOS Monterey, v. 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
changing this to high, despite better fitting the definition of low due to being very visible and very annoying.
