### ISSUE TITLE
Distinguish invited/join requests from joined community members

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5115]
### Description

When a user is invited to a community, it should not be displayed as a member until they have been approved.

**Comment by borismelnik** [comment]
@jrainville Hey! I think you fixed it in some of your PRs right?

**Comment by jrainville** [comment]
Yes and no. The flow when a user requests access should be good, but better to test again.

For invite, it needs to be updated. Right now, when we invite someone, we add them to the community directly, but now it should be just a link that they have to click to join. Until they click it, they are not part of the community.
This might require changes on the status-go side.

@John-44 might have other details for that last part. Do we have a spec for it?

**Comment by elina2015** [comment]
Tested and approved

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9610&group_by=tests:status_id&group_order=asc
