### ISSUE TITLE
Contact lists should only shown mutual contacts

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5117]
### Description

The list of contacts should only show mutual contacts.

### Acceptance Criteria

* [x] starting a 1 on 1 or group chat should only show mutual contacts as options
* [x] invite users to a community should only show mutual contacts in the list of users to invite
* [x] in the settings, the contact list should only show mutual contacts
* [x] it should not be possible to start a 1 on 1 with a user that is not a mutual contact (i.e clicking profile -> send message)

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8870
