### ISSUE TITLE
Chat action buttons should have tooltip to provide information what they are about

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5136]
![Screenshot from 2022-03-24 09-07-09](https://user-images.githubusercontent.com/445106/159870514-da671b4a-0b6a-49d7-ba23-641738f65880.png)

The two buttons next to the search bar are used to trigger (group) chats and communities menus.
Unfortunately, there's no indication that these are indeed about those two things.

We should provide some more information/hint about this. One way to do this is to add a tooltip to these so they say what they are when hovered.

/cc @John-44 to loop you in

**Comment by John-44** [comment]
@PascalPrecht having short tooltips on all icons is a good idea, it's something we should really do everywhere
