### ISSUE TITLE
Search popup location menu backdrop gets darker the deeper the menu goes

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5139]
This is a funny one, here I'm opening the search popup:

![Screenshot from 2022-03-24 09-16-24](https://user-images.githubusercontent.com/445106/159872135-9b71fb03-63d0-41b0-8238-556bbac0ea63.png)

Now I'm opening the location menu:
![Screenshot from 2022-03-24 09-16-56](https://user-images.githubusercontent.com/445106/159872239-ee8585b0-653f-4a69-8bf0-4c0967d3bc25.png)

It's hard to see, but notice how the backdrop got slightly darker. This is most likely because the search popup modal introduces a backdrop, and the location menu introduces another one which is then layered on top of the first one.

We can test this thesis by opening another level of the menu:

![Screenshot from 2022-03-24 09-18-43](https://user-images.githubusercontent.com/445106/159872526-507ba316-b9fb-4424-bd6d-693995db4f15.png)

It got slightly darker again.

### Expected behaviour

The backdrop should stay the same all the time because otherwise it introduces some flickering which is not only annoying but stressful haha

**Comment by alexandraB99** [comment]
Fixed in statusq https://github.com/status-im/StatusQ/pull/635
