### ISSUE TITLE
Input value of search popup bleeds out of the modal when it gets too long

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5140]
![Screenshot from 2022-03-24 09-26-06](https://user-images.githubusercontent.com/445106/159873954-d02706d1-b265-45a7-8f1f-12640de99cef.png)

^ I know this is not typically a value someone would put in there, but the input should still not allow this.

Most likely something that should be addressed in StatusQ

**Comment by borismelnik** [comment]
@PascalPrecht I think it fixed here https://github.com/status-im/StatusQ/pull/589/files#diff-e7ba973bd5a37c5ec3c370cf9f31f73abea21eed65cdffe0862c5463b0070ab8

**Comment by PascalPrecht** [comment]
It seems it did!

But it introduced a new bug:
![Screenshot from 2022-03-28 13-36-38](https://user-images.githubusercontent.com/445106/160389965-0703f845-eb76-46fd-b0cf-8aa82f4d9385.png)

**Comment by PascalPrecht** [comment]
Closing this one

**Comment by PascalPrecht** [comment]
Opened https://github.com/status-im/status-desktop/issues/5219 accordingly
