### ISSUE TITLE
Input placeholder and button label disappear in chat selection view when hovering context menu

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5145]
This one is fun as well, so here I am, opening the chat selection view:

![Screenshot from 2022-03-24 09-50-13](https://user-images.githubusercontent.com/445106/159878275-c0220624-00d0-4e24-8507-ee3f61021af6.png)

From here, I click the other button to open the context menu:
![Screenshot from 2022-03-24 09-50-51](https://user-images.githubusercontent.com/445106/159878907-7aa1eefc-8ad8-4d23-9666-fb26ad341105.png)

Firs thing to note here: it seems that the trigger button loses part of its "highlighted" state when the menu is open but the button itself is no longer hovered. I think such a button should keep its "highlighted" state while the context menu is open. Will file a separate issue for that.

Anyways, now I hover the first item of the context menu (You can't see the hover effect on the menu item because of me doing a screenshot):

![Screenshot from 2022-03-24 09-52-53](https://user-images.githubusercontent.com/445106/159878845-21153bad-5fd6-4616-a5ef-78baf8e581f2.png)

Notice how both: the input and the button in the right screen have lost their placeholder and label respectively. This stay as it is while hovering menu items, until the context menu gets closed.

Maybe some funny z-index issue?

**Comment by alexandraB99** [comment]
I can't reproduce this one 
https://user-images.githubusercontent.com/31625338/162289984-4b3839dc-8588-4ecb-98e6-5be42e598ebf.mov

**Comment by iurimatias** [comment]
seems to have been fixed already

**Comment by PascalPrecht** [comment]
Can confirm that this is no longer reproducible
