### ISSUE TITLE
Contacts view search input doesn't match design

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5148]
Here's what it looks like in the app:

![Screenshot from 2022-03-24 10-05-15](https://user-images.githubusercontent.com/445106/159881109-b05c39ee-0eda-424b-b6e2-a3bcba6187a9.png)

This is what it looks like in the design:

![Screenshot from 2022-03-24 10-06-14](https://user-images.githubusercontent.com/445106/159881194-7fea758c-44eb-46c0-a752-02762ad10010.png)

Differences:

1. There shouldn't be a search icon in the input
2. The input need a bigger `height`

This might be a good opportunity to use `StatusInput` instead of `Input`

**Comment by jrainville** [comment]
> This might be a good opportunity to use StatusInput instead of Input

This last point is fixed here: https://github.com/status-im/status-desktop/pull/5103

**Comment by stefandunca** [comment]
Closing it for now. It was confirmed by @John-44 that the magnifying glass hint is fine. I also added a note on the right design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=661%3A65882
