### ISSUE TITLE
Status navbar profile button should use identicon ring and letter identicon instead of identicon

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5149]
Here's what it looks like with an account that doesn't have a profile picture:

![Screenshot from 2022-03-24 10-08-46](https://user-images.githubusercontent.com/445106/159881903-3104d85d-0bd9-4a3c-9a15-2be2076f8dfe.png)

There are few issues with this:

1. It doesn't have a border (usually identicon images need a border which is why we have `isIdenticon`)
2. We're phasing out identicons so this should use the alias name initials as used in other places
3. It should have the identicon ring

**Comment by jrainville** [comment]
Just a small clarification

> It should have the identicon ring

The identicon ring is only for non-contacts.

For the rest, I agree. it should at least have a normal ring or at least a color background.

**Comment by PascalPrecht** [comment]
> The identicon ring is only for non-contacts.

Yeap, that's what I realized today as well. The designs show a color ring there though. I still think they should always be shown.

**Comment by iurimatias** [comment]
the view profile for the users own profile shows the identicon ring, so IMO it should be the same

![Screen Shot 2022-03-25 at 10 32 14 AM](https://user-images.githubusercontent.com/176720/160141059-ad3b44bb-f4fe-4c05-8f15-15ae3574a37a.png)

**Comment by iurimatias** [comment]
marking this as high because the inconsistency is very obvious and should be fixed before release
