### ISSUE TITLE
Identity emojis are blurry

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5152]
This is what they look like on my machine:

![Screenshot from 2022-03-24 10-14-45](https://user-images.githubusercontent.com/445106/159883020-811d9f8c-1e52-46fc-809e-0b34cf4ba785.png)

I'm on Ubuntu.

I believe we had a similar issue before with emojis used in the chat. Maybe @richard-ramos remembers what we did about it..

**Comment by iurimatias** [comment]
fixed by https://github.com/status-im/status-desktop/pull/5133
