### ISSUE TITLE
User cannot log back in after having changed the Wallet account name 

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5160]
# Bug Report

## Steps to reproduce
- Go to Wallet -> Settings --> Account settings
- Change the Account name to something else & save changes
- Signout and quit
- Launch app again and try signing back in

#### Expected behavior
User must be able to sign in again

#### Actual behavior
![image](https://user-images.githubusercontent.com/95302135/159913736-74c67571-a16a-4d07-afcf-04ad33ed5383.png)

### Additional Information

- Status desktop version: Master on Commit: bf1c809f150ba555020ccb429a529b66f9bb7203

**Comment by iurimatias** [comment]
can't replicate. I believe this issue is caused by switching branches with different status-go versions
