### ISSUE TITLE
Onboarding validation doesn't seem to behave properly

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5163]
When generating new keys, there's a few things off since latest `master`:

First, I only get one account propose. It's selected, and the button to continue is disabled. Not sure if that is desired, but it seems it requires me to set a display name.

<img width="735" alt="Screenshot 2022-03-24 at 16 32 24" src="https://user-images.githubusercontent.com/445106/159952958-b7bf5aeb-29b8-4d6d-9ab2-4304d93ef58c.png">

Fine, I set a display name. Oh, it validates, but the validation never turns off, even though I seem to fulfill the requirements. The button to continue is now enabled.
<img width="559" alt="Screenshot 2022-03-24 at 16 32 33" src="https://user-images.githubusercontent.com/445106/159952936-39a56567-8d4b-47ca-ae6f-4efbd2b51ef4.png">

Then, next step, not really a behaviour issue but a UI/UX issue.. the password strength indicator looks exactly like an input, just smaller. First I thought this is another input to enter my password in again. Maybe we can change the design here a bit? /cc @John-44 

<img width="536" alt="Screenshot 2022-03-24 at 16 35 42" src="https://user-images.githubusercontent.com/445106/159953516-ca5b3216-c9bb-4b82-8105-c3664ea789de.png">

**Comment by borismelnik** [comment]
@PascalPrecht Hey! I think validation was fixed here https://github.com/status-im/status-desktop/pull/5100
<img width="627" alt="Снимок экрана 2022-03-25 в 16 02 56" src="https://user-images.githubusercontent.com/82511785/160126096-f1ad909f-5000-4407-80de-4b5757bfdc07.png">

**Comment by iurimatias** [comment]
this was fixed in PR https://github.com/status-im/status-desktop/pull/4985 as part of issue https://github.com/status-im/status-desktop/issues/4921
