### ISSUE TITLE
Contact state isn't properly updated in chat tool bar

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5164]
See here:
![Screenshot from 2022-03-24 16-39-57](https://user-images.githubusercontent.com/445106/159954533-15a16dc1-b2db-4a34-82af-f09768d9c16e.png)

Notice how the chat toolbar in the top says "Not a contact".
Then, notice how the modal of that contact has the option to "Remove contact".

Here's how to reproduce this:

1. Take any account on some public channel
2. Right click -> Send message
3. Then use toolbar to "add to contacts"
4. Open modal again and see how it's actually added but still not updated in the toolbar

**Comment by iurimatias** [comment]
note: "Send a message" to non-contacts should not be possible (anymore)
it's possible this has been fixed in PR https://github.com/status-im/status-desktop/pull/5171

**Comment by Khushboo-dev-cpp** [comment]
Fixed with https://github.com/status-im/status-desktop/pull/5778 implemented by Sale

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/edit/9248/1&group_by=tests:status_id&group_order=asc
