### ISSUE TITLE
Messages from recently added contact don't arrive in time

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5165]
Look a this screen:

![Screenshot from 2022-03-24 16-43-31](https://user-images.githubusercontent.com/445106/159955229-6983c4f3-e1e0-46f3-960a-07b0efa00f23.png)

It looks like I have sent one message ("Hi fren") 
Then got a reponse ("Hi other fren I've got a community for you")

However, that second part ("I've got a community for you") is actually also **my** message, which I have sent **after** the other account has sent the "Hi other fren" message (it just didn't render in my app yet).

Here's what it looks like on the other side (perspective from other account):

<img width="440" alt="Screenshot 2022-03-24 at 16 46 49" src="https://user-images.githubusercontent.com/445106/159955828-d66c8dfa-86c9-4ec7-91e8-7d9df959bec6.png">

Which renders properly.

Steps to reproduce:

1. Send a message to some account that isn't a contact yet
2. Then send contact request
3. Accept request from via other account, send a reply (this then isn't visible yet)
4. Go back to account 1, send another message
5. At some pointn the message from account 2 arrives, resulting in such a state in account 1's chat.

**Comment by saledjenic** [comment]
@iurimatias @PascalPrecht I've tried to reproduce this using desktop and mobile app, but was not able to get the scenario described above. Also once we merge changes done here https://github.com/status-im/status-desktop/pull/5171 we won't be able to send message to any but the mutual contacts.

All in all let me know what to do with this ticket.

**Comment by PascalPrecht** [comment]
It's probably hard to reproduce without two machines.
Happy to try this again with latest `master`.

**Comment by elina2015** [comment]
Tested in test run https://ethstatus.testrail.net/index.php?/runs/view/8955
