### ISSUE TITLE
User cannot place the cursor by clicking at a location in the Create Pwd & Change Pwd fields

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5167]
# Bug Report

## Steps to reproduce
- Launch the app
- Hit 'Generate new keys'
- Enter Display name & hit next
- On the create Pwd page, Enter Pwds in both fields
- Using the mouse, click in between the entered text

#### Expected behavior
The cursor must be placed where clicked.

#### Actual behavior

https://user-images.githubusercontent.com/95302135/160034295-a8e64af1-ef7d-4f2e-b558-69ac0c189e75.mp4

### Additional Information

- Status desktop version: Master on commit: a20686324e14f33d42e5ae1575ab67746d972fb8

**Comment by borismelnik** [comment]
@abhi-status I think that can be possible `feature` cos `dots` can hide more than one character and vise verse. Are you sure that it's a bug?

**Comment by abhi-status** [comment]
> @abhi-status I think that can be possible `feature` cos `dots` can hide more than one character and vise verse. Are you sure that it's a bug?

But the dots appear in the field when I add a character. So, 1 dot per character
Are you sure they are encapsulating more than one character ?

Yes, I think this is a bug.

Because the users would have to use the arrow keys to traverse backwards and position the cursor as they want. 
And if it is a long-ish Pwd (say 15 characters or more) they'd have to hit the left arrow 15 times to reach the first character (if they wanted to change it).

**Comment by alexandraB99** [comment]
@John-44 could you please give some insights here? apparently nothing was specified in figme (cc @noelia-santos)
