### ISSUE TITLE
Fetch more messages date representation should be fine-tuned

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5168]
I just opened up Status and entered a channel of some community and this is what I saw:

![Screenshot from 2022-03-25 09-31-40](https://user-images.githubusercontent.com/445106/160084589-07406107-938a-42c5-9ba1-39085c41c44c.png)

Seems unparsable. We should fine-tune the representation of the information we want to show

**Comment by iurimatias** [comment]
to be fixed in https://github.com/status-im/status-desktop/issues/5726

**Comment by PascalPrecht** [comment]
#5726 fixes the issue that no date is shown at all but doesn't actually change how the date is formatted.
