### ISSUE TITLE
pressing close button is not minimizing nor closing app

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5189]
# Bug Report

## Steps to reproduce

1. login to application
2. click X on the window bar

#### Expected behavior

Should either close or minimize the application (depending on the configuration in the settings)

#### Actual behavior

nothing happens, error in the terminal:

`qrc:/main.qml:341: ReferenceError: login is not defined`

### Additional Information

- Status desktop version: master 
- Operating System: mac

**Comment by saledjenic** [comment]
@iurimatias closing this as this is counterpart of #5170
