### ISSUE TITLE
attempting to download image on a 1 on 1 crashes on mac

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5194]
# Bug Report

## Steps to reproduce

1. open a 1 on 1 message with a contact on mobile
2. on mobile, send an image
3. on desktop, right click on the image and try to download it

#### Expected behavior

should download the image to the choosen folder

#### Actual behavior

the save dialog shows 'open' instead, and then crashes

### Additional Information

- Status desktop version: master
- Operating System: mac

**Comment by Khushboo-dev-cpp** [comment]
copy image also leads to crash. checking it now
