### ISSUE TITLE
after unblocking a user, messages are still not received until app is restarted

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5198]
# Bug Report

## Steps to reproduce

1. aadd a mutual contact request
2. after send messages to each other
3. block the user A
4. have user A send messages -> nothing is displayed as expected
5. unblock user A
6. have user A send messages

#### Expected behavior

new messages from user A since the unblocking should be displayed

#### Actual behavior

new messages are not displayed

**Comment by abhi-status** [comment]
https://ethstatus.testrail.net/index.php?/runs/view/8833&group_by=cases:section_id&group_order=asc
