### ISSUE TITLE
Profile picture edit button in profile view looks off

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5210]
Here's what the "edit" button for the profile picture in the profile view looks like when hovered:

![Screenshot from 2022-03-28 11-48-54](https://user-images.githubusercontent.com/445106/160372768-669c1e1c-8ba5-4502-9ecf-8750338f6645.png)
![Screenshot from 2022-03-28 11-49-10](https://user-images.githubusercontent.com/445106/160372785-cb545880-3b88-4f88-a7c7-2d720234e771.png)

The hover state is barely noticable. Chances are, a wrong version of `StatusButton` is used here but this depends on what the design says.

**Comment by iurimatias** [comment]
the hover looks different now/stronger

**Comment by PascalPrecht** [comment]
I don't think this was ever properly addressed, but maybe I'm seeing it wrong..
