### ISSUE TITLE
Chat list doesn't seem to be properly centered in chat view

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5211]
Have a look at this chat list:

![Screenshot from 2022-03-28 11-51-27](https://user-images.githubusercontent.com/445106/160373253-de1d339f-12ac-47c8-9447-1afbfb35331c.png)

Notice how the left margin of the selected item is smaller than the right margin. 

This is not the case in the community chat view:
![Screenshot from 2022-03-28 11-52-54](https://user-images.githubusercontent.com/445106/160373421-e9908651-b09a-406b-aa4a-8b2cdf9cf44d.png)

**Comment by iurimatias** [comment]
fixed in the meantime

**Comment by PascalPrecht** [comment]
Sorry, don't want to be annoying, but this is also still the case on latest `master`.

**Comment by Hbouaz** [comment]
@PascalPrecht can you please elaborate, is it the highlithed area to the right that is bigger? could you please share a figma link?
@iurimatias can you please share a screenshot? I tried on Master and other recent branches but I am not 100% sure, so I can't mark it as passed just yet

**Comment by PascalPrecht** [comment]
@Hbouaz this seems to be fixed now with latest changes by @alexandraB99 !
