### ISSUE TITLE
Create chat view contact list has a weird width

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#5222]
I noticed an unexpected scollbar in the contact list suggestions. Unfortunately I can't screenshot it so I changed the background color of the list to visualize that it's way too thin:

![Screenshot from 2022-03-28 14-23-33](https://user-images.githubusercontent.com/445106/160397422-05977db9-8c26-4ef4-a710-9b969bb110fd.png)

This seems to be using the same list that  is also used for the suggestions popup. I think these should be rather two separate things..

**Comment by noeliaSD** [comment]
Once https://github.com/status-im/StatusQ/issues/682 is done, it will be needed to add the contacts list in this chat view and with that change the view layout will need to be redone.

**Comment by jrainville** [comment]
This is a very old issue. Seems like it was fixed in the past already.
