### ISSUE TITLE
After removing contacts, the user keeps getting contact requests from the removed users 

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5225]
# Bug Report

## Steps to reproduce

The user gets contact requests from the removed users without being sent one.

This takes a while to appear as the **_unsent contact requests_** take time to show up

On the freshly installed desktop app, create new account and add a few known contacts
- start 1 to 1 chats with a couple of the added contacts
- remove each of these contacts from the contacts list and wait for a few minutes

#### Expected behavior
The user must not get a contact request notification without having been sent one.

#### Actual behavior
The user keeps getting the contact request notification 
![image](https://user-images.githubusercontent.com/95302135/160429681-29ef38ce-ba06-48a4-b2de-a4d96deff463.png)
![image](https://user-images.githubusercontent.com/95302135/160429768-a9dd75f0-d380-406d-82e3-f126de16c0c6.png)

### Additional Information

- Status desktop version: Master on commit: bc23762a05dd80204f52da692372f1e8133b7b2d

**Comment by saledjenic** [comment]
@abhi-status I've tried multiple scenarios to reproduce this, but was not able. Would you add more details here how exactly to reproduce this (a video would be appreciated)? 

Is contact you're removing a mutual contact (added from both sides) or it's enough to add contact and run 1:1 chat and remove it? (in both cases I was not able to reproduce the issue)

**Comment by abhi-status** [comment]
Yes, remove a contact after it was added on both sides. 

Once you remove the contact, you need to leave the app open for a while to see the contact request coming in again.

I cannot test this at the moment, as I cannot remove a contact on the latest Master due to -> #5354 

I'll look for a build where the Remove Contact feature isn't broken.

**Comment by saledjenic** [comment]
@abhi-status I assigned #5354 to myself, cause I already have #5225 and #5198 and all of them refer to the same thing, flags we have/maintain for each contact. 

@iurimatias I discussed with cammellos today about those flags, [here](https://discord.com/channels/624205794384281629/697843216048717905/960825670483718194) is a conclusion. In short we will remove `Rejected Requests / Sent` from the view and add some new flags on the `status-go` side which will (I hope) uniquely define which contact belongs to which section. 

@iurimatias do you agree to postpone these 3 tickets till cammellos finish that part?

**Comment by iurimatias** [comment]
@saledjenic yes it's ok to wait for that

**Comment by saledjenic** [comment]
Just for the reference, in terms of contacts [this diagram](https://drive.google.com/file/d/1XIGChZhlSeCUlSWCcZ4QeUwYZTFf-9QT/view) should define the flow we need to follow. It's created discussing with @John-44 in `desktop-ui` channel and following design in Figma files.
