### ISSUE TITLE
Users can save an empty Display name in new onboarding

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5236]
# Bug Report

## Description
Users can save an empty Display name in the new onboarding
## Steps to reproduce

1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Enter a space in the field "Display name"
4. Hit the button "Next"

#### Actual result
Users can save an empty Display name in the new onboarding
<img width="648" alt="image" src="https://user-images.githubusercontent.com/14942081/160513644-997d24ba-26cf-496a-8ee6-1f7d72ff1a52.png">

#### Expected behavior
Users cannot save an empty Display name in new onboarding

### Additional Information

- Status desktop version: commit dcab50fe0944f65a1fafef3fdb9e7abe66277b6c
- Operating System: MacOS Big Sur 11.6.5 (20G526)

**Comment by iurimatias** [comment]
changing this to a high
