### ISSUE TITLE
The profile picture applied even if user didn't hit "Finish"

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5238]
# Bug Report

## Steps to reproduce

1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Hit "+" and upload a photo for the profile image
4. Hit "Done"
5. Hit "+" and click on the profile picture, select a new image and click "Open"
6. Don't click on "Finish" and just close the dialogue

#### Expected behavior
The new image is not applied
#### Actual behavior
The new image is applied as a new profile picture 

### Additional Information

- Status desktop version: commit dcab50fe0944f65a1fafef3fdb9e7abe66277b6c
- Operating System: MacOS Big Sur 11.6.5 (20G526)

https://user-images.githubusercontent.com/14942081/160518320-9bc91b5d-3674-482c-bb16-8451055635d3.mov

**Comment by elina2015** [comment]
@endulab hey, thank you for fixes!
 I found that if our user selected an image and quit the image popup or cropping popup, the image will not be saved as a profile image on the onboarding page. 
But, this image **will appear** on the Settings-Profile or any profile image icon everywhere in the app. Could you kindly check?

**Comment by endulab** [comment]
@elina2015 it seems to be ok:

https://user-images.githubusercontent.com/61889657/161705167-2cafb08e-175a-4270-8a27-970dff858d6f.mov

Btw, the cropping does not work well, and a cropping area should be a circle instead of rectangle.
Is there any ticket for that ?

**Comment by elina2015** [comment]
@endulab thank you for the video record! Yep, this case works well, but if our user selected an image, click 'Finish' for cropping and quit the image popup (click 'x') the image will not be saved as a profile image on the onboarding page.
But, this image will appear on the Settings-Profile or any profile image icon everywhere in the app. Could you kindly check?

https://user-images.githubusercontent.com/14942081/161902107-94263c58-d9a6-4dbc-b1f0-a6c7bbbcabbe.mov

About cropping - thank you, I noticed this bug too and added it to our backlog.

**Comment by endulab** [comment]
@elina2015 please check again. I fixed it.

**Comment by elina2015** [comment]
@endulab hey, I selected an image and cropped it and saved successfully on the the onboarding page. But after finishing the onboarding process I see the profile picture is not saved (Settings-Profile). Could you kindly check the video?

https://user-images.githubusercontent.com/14942081/162358586-69cddb5c-14e9-4e1f-a79b-3b2e19bc9eb9.mov

**Comment by endulab** [comment]
> @endulab hey, I selected an image and cropped it and saved successfully on the the onboarding page. But after finishing the onboarding process I see the profile picture is not saved (Settings-Profile). Could you kindly check the video?
> 
>  no.saved.profile.picture.mov

@elina2015 thank you for catching this ! Fixed.

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8959
