### ISSUE TITLE
It's impossible to delete a profile image on the onboarding page

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5240]
# Bug Report

## Description

It's impossible to delete a profile image on the onboarding page

## Steps to reproduce

1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Hit "+" and upload a photo for the profile image
4. Try to delete the profile picture

#### Expected behavior
It's possible to delete the profile picture
<img width="470" alt="image" src="https://user-images.githubusercontent.com/14942081/166985992-c1dbc8ec-0312-4584-9acb-7dbda917b1c8.png">

#### Actual behavior
There is no button for deleting the profile picture
<img width="577" alt="image" src="https://user-images.githubusercontent.com/14942081/160523156-8ec7b818-7134-49b9-8515-1c17017a25d0.png">

### Additional Information

- Status desktop version: commit dcab50fe0944f65a1fafef3fdb9e7abe66277b6c
- Operating System: MacOS Big Sur 11.6.5 (20G526)

**Comment by elina2015** [comment]
@saledjenic hey, the button for deleting the uploaded picture is still not shown. 
Also, if I click on the 'x' icon for closing the dialogue after uploading the profile image, and finish the onboarding, the uploaded image is shown (but it shouldn't). Could you check it?

**Comment by elina2015** [comment]
https://user-images.githubusercontent.com/14942081/166991728-d09269ac-d2c8-4b1e-bbab-fc6fd1a36a1b.mov

**Comment by saledjenic** [comment]
@elina2015 I've checked, in order to set image for your profile you have to click "Done", only in that case if you open "Upload profile picture" again "Remove" button will show up. The case when you upload image and just close the popup and image is set as your profile image is an error, should be good now, please check.

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9103&group_by=tests:status_id&group_order=asc
