### ISSUE TITLE
The 'Create password' placeholder differs from the design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5243]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Enter some Display Name and hit "Next", hit "Next"
4. Check the placeholder of the "Create password" button

#### Expected behavior
The placeholder should be "Create Password" according to the design
<img width="719" alt="image" src="https://user-images.githubusercontent.com/14942081/160534168-0883c37a-eb96-4301-be85-e4f61b7b154f.png">

#### Actual behavior
The placeholder is "Create password" and it differs from the design
<img width="568" alt="image" src="https://user-images.githubusercontent.com/14942081/160534255-b268910d-b94f-475a-a0e0-d3256664703d.png">

### Additional Information
- Status desktop version: commit dcab50fe0944f65a1fafef3fdb9e7abe66277b6c
- Operating System: MacOS Big Sur 11.6.5 (20G526)

**Comment by iurimatias** [comment]
fixed in the meanwhile
