### ISSUE TITLE
No hover indication for action buttons in contacts list

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5246]
Go to Settings -> Messaging -> Contacts, Requests, Blocked users

You'll see a contacts list that looks like this:
![Screenshot from 2022-03-29 13-07-41](https://user-images.githubusercontent.com/445106/160598791-0d7c9241-c78f-47e5-9959-7b8682fe127c.png)

Each item in the list has two action buttons ("send message" and a trigger to open a context menu)
Both of the action buttons don't have a hover indication (or maybe they do but the hover color is the same as the list item's background color).

**Comment by Hbouaz** [comment]
PR checked and passed for both Dark and Light modes
