### ISSUE TITLE
Emojihash should have margin between emojis

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#5247]
There should be a very small margin (1px or 2px) between the emojis in the emoji hash. The emoji look a bit too tightly packed together right now.

Also spacing between Emojihash and chat key fragment or icon is too big - that's a regression.

![image](https://user-images.githubusercontent.com/33099791/160597688-a55278a1-b883-4ef2-89ef-86c9d03cb1d1.png)
![image](https://user-images.githubusercontent.com/33099791/160597794-0a610bba-30b2-4235-a393-5124496a05e0.png)

#### Additional Information
EmojiHash component should be extracted (to StatusQ?). It should have fine-grained control on padding between emojis (probably by using properly positioned `SVGImage`s instead of `StatusText` rows).

**Comment by alexandraB99** [comment]
@osmaczko it seems this issue could fix also https://github.com/status-im/status-desktop/issues/5242, what do you think?

**Comment by osmaczko** [comment]
@alexandraB99 yes indeed, it should fix both the topMargin and spacing between emojis.

**Comment by elina2015** [comment]
@PascalPrecht thank you for fixes! Could you kindly add them on the onboarding pages too?
<img width="878" alt="image" src="https://user-images.githubusercontent.com/14942081/163255388-5c14b81d-3fd9-47c7-80aa-cb28d939b6dd.png">
