### ISSUE TITLE
The Activity Center doesn't work properly

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5256]
# Bug Report

## Description
Users cannot see the list of mentions present in the Activity Center and use the functionality of the Activity Center

## Steps to reproduce
1. Launch the app and sign in with the user that has a few mentions and replies from a few of his or her contacts
2. Open the Activity Center and check the tab "All", "Replies", "Mentions" and try to use any functionality of the Activity Center

#### Expected behavior
The Activity Center works correctly and the user can use all AC functionality

#### Actual behavior
All functionality of the Activity Center doesn't work

https://user-images.githubusercontent.com/14942081/160709363-4aa2f8be-ea86-471e-a8e5-90043f608b1c.mov

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by jrainville** [comment]
@elina2015 I can't reproduce. I just sent a mention in a community and it worked. tested on latest master (`6d9c5c4286777669f4f0792f93d672fb7f231eec`)
Example: 
![image](https://user-images.githubusercontent.com/11926403/161626383-552c16ba-411d-4932-b014-29e87a0e2304.png)

Maybe you were looking at the wrong account? 
Also, reminder that mentions and reply activity center notifications only work in communities and group chats.
