### ISSUE TITLE
[m1 rosetta] The app is crashed after trying to add reaction to a chat message

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5257]
# Bug Report

## Steps to reproduce
1. Launch the app and sign in with a user that has at least one contact
2. Start the chat and add a reaction to a message
3. Click on the icon for adding one more reaction to the message under the message

#### Expected behavior
The dialog for adding a reaction appeared

#### Actual behavior
The app is crashed

https://user-images.githubusercontent.com/14942081/160711532-9539fd05-e1e7-4f46-829c-b5c6a6aa69d8.mov

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/14942081/160710859-5649cec0-5983-4e88-8e5b-0a1c967615d7.png">
`rosetta error: unexpectedly need to EmulateForward on a synchronous exception x86_rip=0x4499387456 arm_pc=0x4503948664 num_insts=5 inst_index=2 x86 instruction bytes: 0x6215344901283465301 0x17764810576535701587`

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by saledjenic** [comment]
@elina2015 I checked this behaviour in the latest master, looks ok, see the video below. Let me know if the issue still persists and how to reproduce it?


https://user-images.githubusercontent.com/86303051/163355055-f5d61d0e-5694-4f84-81a0-e891a87ea75a.mov

**Comment by elina2015** [comment]
Tested on the latest master and it is not reproduced.
