### ISSUE TITLE
It's impossible to add a sticker in any chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5260]
# Bug Report

## Description

The sticker dialog is empty and the loader is shown infinitely

## Steps to reproduce
1. Launch the app
2. Sign in the user that has 1-1 and group chats
3. Open chat and try to send a sticker to 1-1 or group chat

#### Expected behavior
The sticker is successfully added to 1-1 and group chats
#### Actual behavior
The sticker dialog is empty and the loader is shown infinitely
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/14942081/160723602-ba02cc5f-c3bc-4cb9-b55b-fb4f5996d086.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
this should have been fixed in the meanwhile

**Comment by iurimatias** [comment]
this has been fixed in another PR
