### ISSUE TITLE
Cannot delete 1-1 chat with blocked or unblocked user

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5262]
# Bug Report

## Steps to reproduce

1. Launch the app
2. Sign in with a user that has at least one contact (for example, User B)
3. Open the chat and write and receive a few messages
4. Click on the contact's image (open User B profile) and click on "Block user", click "Block user" again
5. Click on the chat with User B and click "Delete chat"
OR
7. Click on the contact's image (open User B profile) and click on "Unblock user"
8. Click on the chat with User B and click "Delete chat"

#### Expected behavior
The chat is deleted
#### Actual behavior
The chat is not deleted
### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by borismelnik** [comment]
@elina2015 it should work on latest master

**Comment by elina2015** [comment]
Tested on the latest master  commit efd641226648d6773785342e08627a23d3bdf06d through the test run https://ethstatus.testrail.net/index.php?/runs/view/9022&group_by=tests:status_id&group_order=asc
