### ISSUE TITLE
Nothing happens after clicking on a sticker in any chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5264]
# Bug Report

## Description
Nothing happens after clicking on a sticker in any chat
## Steps to reproduce
1. Launch the app
2. Sign in with a user that has 1-1 and group chats with stickers were sent by other users there
3. In 1-1 or group chat click on sent sticker

#### Expected behavior
The sticker pack is shown
#### Actual behavior
Nothing happens
### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
can no longer replicate
