### ISSUE TITLE
Current user sees themselves in the list for mentioning

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5265]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Sign in with a user that has 1-1 and group chats
3. Open 1-1 or group chat and enter '@' in the message field
4. Check the appeared list

#### Expected behavior
The current user is not shown in the users' list for mentioning
#### Actual behavior
1. The current user is shown in the users' list for mentioning
2. After clicking on themselves and clicking "Send" the incorrect mentioning is shown

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/14942081/160761067-2861a705-0e97-4579-b4f7-5322738db6eb.png">
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/14942081/160761166-400bad28-4551-4b76-a1fc-bdcd40712bd8.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by ducheng0** [comment]
That is useful, because instead of saying "myself" in a chat you can link to your account

**Comment by iurimatias** [comment]
this behaviour is the expected one, the user should see themselves in the mention list
