### ISSUE TITLE
The reply for a sticker message looks incorrect

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5266]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Sign in the user that has 1-1 or a group chat
3. Receive a sticker in a chat from any contact
4. Reply to the message-sticker

#### Expected behavior
The reply looks good - the sticker is shown correctly
#### Actual behavior
The reply message doesn't look good - the sticker is black
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/14942081/160761717-0f7fc1c9-43b5-4a62-8f30-65f398e40ab5.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
updated test case steps to catch issue https://ethstatus.testrail.net/index.php?/cases/view/695780
