### ISSUE TITLE
Better thread support

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#527]
Suggested by @zah 
> A solution is to introduce an I/O thread that will run a separate message loop responsible for operations that may perform I/O and computational tasks without blocking the GUI thread. Then the workflow will be like this:
> 1) User performs action
> 2) Code running on the GUI threads decides to create a "task" for the I/O thread. The task is posted to something we call "AsyncChannel"
> 3) A loop in the I/O thread receives the task from the AsyncChannel. It starts executing arbitrary code using the async/await paradign. Multiple such tasks can progress in parallel (similar to goroutines). 
> 4) Some of the tasks in the I/O thread perform network requests to the Status GO RPC service. These requests are handled in the Status Go thread. The results are awaited and handled back in the Nim I/O thread.
> 5) Any such I/O or compute task can notify the UI for progress at any time by sending a Qt signal back to the UI thread.
> With this setup, you'll have 3 long-running threads and you don't need to deal with spawning new ones. The ownership of all the data is well assigned to a thread and there are no gc safety issues

**Comment by richard-ramos** [comment]
> https://github.com/status-im/nim-chronos/pull/45

> The async channel developed there can tranfer only bytes, and it would be enough to start introducing the above architecture.
> The next step would be to define a type-safe higher-level interface that transfers strongly-typed objects over the channels (this will boil down to using nim-serialization to encode and decode the messages)

**Comment by mratsim** [comment]
Note for sending tasks across services, I've explored the following serialization/cross-service calls macros:

https://github.com/mratsim/blocksmith/blob/36e7892decfbc4c5dba600cc52304db33c49980f/cross_service_calls.nim#L177-L217

**Comment by iurimatias** [comment]
https://github.com/status-im/nim-task-runner
