### ISSUE TITLE
Community channel colors are not loaded consistently

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5272]
This has been a issue for a while and seems to persist:

![Screenshot from 2022-03-30 15-52-49](https://user-images.githubusercontent.com/445106/160851253-f0442a75-8108-40ea-bcec-cf38610d3333.png)

Above you see a community with two channels. The community was freshly joined. Notice how the channel color is `black` in two places. Usually this means that the actual color isn't properly set.

I wonder at this point. weren't channels supposed to use exactly the same color as the community color anyways?

**Comment by iurimatias** [comment]
should not happen anymore since all channels require an emoji
