### ISSUE TITLE
Settings menu navigation is scrollable horizontally

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5276]
### Description

Seems like the content of the scrollable area is slightly bigger than the viewport, causing it to be scrollable horizontally:

![Screenshot from 2022-03-30 16-47-56](https://user-images.githubusercontent.com/445106/160863579-187b0ae2-132c-4b3f-b17f-dd850db502a4.png)

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9363&group_by=tests:status_id&group_order=asc
