### ISSUE TITLE
The search request is shown incorrectly

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5279]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Sign in and enter any text in the chat search field

#### Expected behavior
The search text request is shown correctly
#### Actual behavior
The text of the search request is shown not in full
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/14942081/160946313-c69d9998-503f-43ba-910c-6be3ca9f1d94.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
fixed in the latest master
