### ISSUE TITLE
[getChats] refactor chats models to only be one layer, with categories being sections

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#5286]
This would be a relatively big refactor of the chat model and QML, but with the goal of simplificating.

This is meant as both a proposal, and a task once we agree on doing it.

As it is right now, the Chat is a bit complex, because we have a need to have a model, that has a submodel, for the categories and the chats.

Then in the QML, we need to have ListViews inside ListViews to display it.

That is a bit complex and it also limits some features we would like to do, like drag and drop in the Chat list.

My proposal, which has been thought of in conjunction with @alexandraB99  and @iurimatias, would be to flatten the Chat model. ie we only have one model per chat section (or channel group) that would contain all channels.
To display the categories, we would use the `section` attribute of the ListView component.
Since we now use the new `getChats` API, this is even simpler than before, because the API gives us the chats directly per section. So we'd be able to populate the model directly.

One small use case that needs a special handling is the case of an empty category. Since we want to show those as well, we'd need to populate it with an "empty chat", which would basically be resolved as an invisible item. @alexandraB99 has done a small test and found it to be doable easily.

With this new flattened model, we hope to remove a lot of the complexity,  clean up some code and enable the drag and drop in the chat list.

Let me know if doing this would bring some undesired side effects that I haven't thought about, if you have reservations or just any questions or comments.

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5744
