### ISSUE TITLE
Unblocked user is not shown in the group chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5289]
# Bug Report

## Steps to reproduce
1. Launch the app and sign with a user that has at least two contacts
2. Block one contact and unblock it
3. Create a group chat for the not blocked and **unblocked** contacts
4. After the unblocked user joined accepted the group chat, check the list of members

#### Expected behavior
The unblocked contact is shown in the members' list of the group chat

#### Actual behavior
The unblocked contact is not shown in the members' list of the group chat
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/14942081/161153697-bc42a7bf-3904-4873-ac4f-2b0e2e19ea7d.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/5171
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by MishkaRogachev** [comment]
<img width="947" alt="Screenshot 2022-07-06 at 17 12 55" src="https://user-images.githubusercontent.com/2522130/177570884-b79ff8d3-de99-4e36-8768-d360d2b69631.png">
I can't reproduce bug, but i've found and fixed weird thing about chat context menu, it represented wrong states for contacts including state of blocking

**Comment by MishkaRogachev** [comment]
> <img alt="Screenshot 2022-07-06 at 17 12 55" width="947" src="https://user-images.githubusercontent.com/2522130/177570884-b79ff8d3-de99-4e36-8768-d360d2b69631.png">
> 
> I can't reproduce bug, but i've found and fixed weird thing about chat context menu, it represented wrong states for contacts including state of blocking

@elina2015 can you please try to reproduce this using my branch https://github.com/status-im/status-desktop/pull/6372
