### ISSUE TITLE
User cannot see the group chat invitation from the unblocked contact

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5292]
# Bug Report

## Steps to reproduce
1. Launch the app and sign in with a user that has at least one contact
2. Block and unblock the contact (let it be user B)
3. Unblocked user  (user B) creates a group chat and adds there the current user
4. Current user checks the list of chats and invitations

#### Expected behavior
The invitation to the group chat from the unblocked user is shown
#### Actual behavior
The invitation to join the group from the unblocked user is not shown
### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/issues/5117
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by jrainville** [comment]
I think this was fixed already, probably by Sale and his contact upgrade PRs
