### ISSUE TITLE
The long category name is shown incorrectly

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5293]
# Bug Report

## Steps to reproduce
1. Sign in and create a community
2. Go to community and click '+' and 'Create category'
3. Enter the long category name(30 characters) and save
4. Hover over the created category under the community name

#### Expected behavior
The long category name looks good
#### Actual behavior
The long category name doesn't look good
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/14942081/161173634-1400eb1a-115e-41c9-8fee-fa45d823f268.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/5171
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
we now limit it to 24 characters so this isn't possible anymore
