### ISSUE TITLE
The search contact field looks incorrect if user entered a chat key there

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5294]
# Bug Report

## Steps to reproduce
1. Sign in and click on the pencil icon near the search field
2. Enter a chat key in the field 'To' (for example, 0x049ba5e88581c9e41f549c113bdc92ea5f580b5f8bd1dcdc4229f7e4643bb4cd36e5f7f2d97db6a7373f8c1d76efc4ba39b5166cdbba35cab602e78cc72448c6c8) in the 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/14942081/161191975-bb5e33a6-1cc2-42b4-a714-7d937030e9e8.png">

#### Expected behavior
The text is not going outside the field
#### Actual behavior
The text is going outside the 'To' field
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14942081/161194377-79390670-97bf-4050-8ae1-515ba33bd2e1.png">

### Additional Information
- Status desktop version: https://github.com/status-im/status-desktop/pull/5171
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
it should not be possible to paste a private key in this field anymore since this behaviour changed with mutual contact requests. this task goal should be to prevent this and only support auto completing existing contacts.
