### ISSUE TITLE
The code is shown instead of a channel logo

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5295]
# Bug Report

## Steps to reproduce
1. Sign in and create a new community
2. Create a new channel in the community
3. Open the new channel and check the logo in the center of the screen

#### Expected behavior
The logo is shown correctly
#### Actual behavior
The code is shown instead of the channel's logo
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14942081/161195004-a7968df0-ef4a-4ff5-a197-7989cfed40bd.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/5171
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
this was fixed and should no longer happen for new communities
