### ISSUE TITLE
Cannot edit a logo for a community in a category

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5296]
# Bug Report

## Steps to reproduce
1. Launch the app and sign in
2. Create a community and a few channels inside the community
3. Create a category and add there one channel
4. Open the channel inside the category, click '...' and click 'Edit channel'
5. Click on the logo of the channel for changing it

#### Expected behavior
The dialog for changing the logo Is opened. I
#### Actual behavior
After clicking on the logo of the channel nothing happens.
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/14942081/161198013-ae10cfe5-5704-4bdb-b03e-98821fa40eb2.png">

### Additional Information
- Status desktop version: https://github.com/status-im/status-desktop/pull/5171
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
cannot replicate, fixed in master
