### ISSUE TITLE
Including emojis in a channel name causes bad rendering on both mobile & desktop Apps

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5301]
# Bug Report

## Description

- Channels render badly on the mobile app whenever emojis are used in a channel name (channel created on the desktop and then sent an invitation to an account using the mobile app)

![image](https://user-images.githubusercontent.com/95302135/161268387-97ed5626-e971-4b1f-bdbe-c89b44236c91.png)

- On Desktop, the emojis are sometimes not centred and not displayed and badly rendered

![image](https://user-images.githubusercontent.com/95302135/161290546-9ddfcee0-f8fa-409b-acec-bcfc486893b9.png)

![image](https://user-images.githubusercontent.com/95302135/161268640-00ae3bb3-068f-489b-86c6-c71d00c4fca9.png)

![image](https://user-images.githubusercontent.com/95302135/161268775-0680a136-6566-4369-bc24-ded141ed35ed.png)

![image](https://user-images.githubusercontent.com/95302135/161269498-fe84eb40-b6aa-43f4-bdec-f8db9ed1fbf5.png)

### Additional Information

- Status desktop version: Master : 149ff69310d1e94f8196d2310c33a391d5e13477

**Comment by iurimatias** [comment]
this has been fixed in the meantime
