### ISSUE TITLE
Emojihash is blurred in the onboarding

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5306]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Generate new keys and enter some Display Name, click Next
3. Check the Emojihash

#### Expected behavior
Emojihash looks correct
<img width="772" alt="image" src="https://user-images.githubusercontent.com/14942081/161330577-a53ab35f-dbb0-46bf-bc6b-2d036f327e97.png">

#### Actual behavior
The Emojihash is blurred
<img width="805" alt="image" src="https://user-images.githubusercontent.com/14942081/161330338-0a9c967d-5307-4738-a14b-7ca71e19a529.png">

### Additional Information

- Status desktop version: commit e26befb6c26141529a5c4263bc8b26aa7c27e042
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by iurimatias** [comment]
fixed by https://github.com/status-im/status-desktop/pull/5549
