### ISSUE TITLE
The Onboarding and Profile chat key, emojhash and identicon ring are different.

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5307]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Generate new keys and enter some Display Name
3. Remember the generated Chat name, Emojihash and Identicon ring
4. Click 'Next' and enter a new password and confirm it
5. Go to your profile and check the chat key, emojihash and identicon ring. Compare them with the remembered in the step 3

#### Expected behavior
The onboarding and profile chat key, emojhash and identicon ring are the same.
#### Actual behavior
The onboarding and profile chat key, emojhash and identicon ring are different.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/14942081/161331691-e5b5f8a9-830d-48fb-8969-533b38860d22.png">
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/14942081/161331761-8064979b-6a71-4a65-a08e-7f632ae9ab16.png">

### Additional Information

- Status desktop version: commit e26befb6c26141529a5c4263bc8b26aa7c27e042
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by abhi-status** [comment]
This should be fixed by #5287
