### ISSUE TITLE
No restrictions for the Display name onboarding field

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5310]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Generate new keys
3. Enter the Display Name that is more than 24 characters, including not only letters, numbers, underscores and hyphens. For example: %^&*^&* ^&*(Tfgjhghjhj &*(&8098hjk +_(*^%$##ghjg JKJKN<Ngyuyg gyuiguigu*&&^%$23442'|><?±~X 

#### Expected behavior
The error appeared and it's not possible to save the incorrect Display Name
<img width="606" alt="image" src="https://user-images.githubusercontent.com/14942081/161334544-641c2877-f104-459e-a795-14258c958615.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/14942081/161334579-326a447f-bd71-43de-a52f-7bbcb8ff16a3.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/14942081/161334608-a5876665-e468-40cb-aed2-0ffcc1031997.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/14942081/161334649-8160309a-6706-4709-9f9a-fdfa39448bbc.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/14942081/161334684-281e3995-1421-45c6-b110-506487be2b0e.png">

#### Actual behavior
The error doesn't appear and it's possible to save the incorrect Display Name
<img width="571" alt="image" src="https://user-images.githubusercontent.com/14942081/161334046-ac2a3c9e-e9ca-43f1-993d-c69248ca1120.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/14942081/161334148-9026d7d4-e478-4d69-b9aa-3d633d9a8b90.png">
<img width="528" alt="image" src="https://user-images.githubusercontent.com/14942081/161334218-887014bf-c53e-4e80-b2f6-d20bfa5a8ea3.png">
<img width="474" alt="image" src="https://user-images.githubusercontent.com/14942081/161334299-b30fa786-89c1-4d93-85ae-884893a3665a.png">
<img width="553" alt="image" src="https://user-images.githubusercontent.com/14942081/161334419-9aee5625-5d70-47b4-98a7-8d5692a7c66d.png">

### Additional Information
- Status desktop version: commit e26befb6c26141529a5c4263bc8b26aa7c27e042
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by borismelnik** [comment]
@elina2015 https://github.com/status-im/status-desktop/commit/f36648627758f7783f5effd39e2eff36a15f71b5 fixed here
