### ISSUE TITLE
Typo on Create password account screen: characters word is misspelled

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5316]
### Description

<img width="1512" alt="Screenshot 2022-04-04 at 10 44 09" src="https://user-images.githubusercontent.com/82375995/161497515-417cd22f-f0d6-44e2-ae0b-f0cfa041aaf6.png">

Expected: `characters`
Actual: characers

**Comment by elina2015** [comment]
The same typo in the Settings - Privacy and Security - Change password:
<img width="979" alt="image" src="https://user-images.githubusercontent.com/14942081/161657236-6a48dcb7-3320-4068-aa9e-c16f282ae2b8.png">
