### ISSUE TITLE
Have you written down your password screen suggests the correct password length

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5320]
### Description

When entering a password confirmation on `Have you written down your password` screen, the Finalise button is getting enabled when u reach the length of the password u entered on step before, and gets disabled , when the length is more.

It is kinda compromising the password strength. The immediate validation of the password entered should be removed and being triggered after the button is enabled and pressed. The button should be enabled when password length is 6 symbols and more

https://user-images.githubusercontent.com/82375995/161505761-a5ab6b27-2c0e-4f8a-8ee1-4ae8cc9e2d80.mov

**Comment by iurimatias** [comment]
modified test case to catch this issue https://ethstatus.testrail.net/index.php?/cases/view/702116

**Comment by noeliaSD** [comment]
I'm not sure about that solution. The password confirmation button was only enabled when the password was exactly the same as the one entered on the previous screen (not when the length was the same, it was enabled when it was exactly the same and no other options (or at least intended to)). This is just a confirmation, the password strength selection has already been made on the previous screen. 
Could @iurimatias, @John-44 review it?
