### ISSUE TITLE
Cannot start a 1 to 1 chat with anyone

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5323]
# Bug Report

## Description

Trying to start a one to one chat is not possible after adding a new contact via 
- Settings -> Contacts 
- Adding a user on a Public chat 

#### Expected behavior
User must be able to intitiate a 1 to 1 chat with contact

#### Actual behavior
![image](https://user-images.githubusercontent.com/95302135/161514107-6f89151e-f2ab-4000-8bb7-e6193eaee301.png)

### Additional Information

- Status desktop version: Master : a8e946f602268f31746125f46bc423f67812aaf2

**Comment by jrainville** [comment]
Was this using a Jenkins build or a local build? If this was a local build, it might be because status-go wasn't rebuilt.

**Comment by abhi-status** [comment]
This is a Jenkins build.

**Comment by jrainville** [comment]
@abhi-status I cannot reproduce this issue on latest master (`17c16039a64c0d30a0cb48444ab2d7ac144153b4`)

The only issue I've had is the one we've had previously where sometimes messages get received on one app and not the other between VM and Windows or VM and mobile. I'm still not sure what that one is about, but it's not really about joining 1-1 chats.

**Comment by abhi-status** [comment]
yeah, I cant reproduce this either on latest Master now.
Closing.
