### ISSUE TITLE
Allow users to Sign out without quitting the app

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5329]
At the moment, the only way to "officially" sign out is using the "Sign out & Quit" button in the settings.
Given that there can be multiple accounts imported into Status Desktop, it makes sense to allow users to quickly switch between them.

So maybe a "Sign out" option could be added.

**Comment by iurimatias** [comment]
duplicate of https://github.com/status-im/status-desktop/issues/349
