### ISSUE TITLE
Indicate notifications on Status App icon on the taskbar - Linux

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#5333]
### Description

This is a continuation of ticket: #4922.
Version to handle: Ubuntu 22.04 LTS

**Comment by elina2015** [comment]
Acceptance criteria:
- if the user minimized the app and got a mention in the app, the notification will appear on the Status App icon
- if the user minimized the app and got a new message in the app, the notification will appear on the Status App icon

**Comment by caybro** [comment]
@iurimatias this will involve writing a much more elaborate linux notifications backend, using DBUS :)

**Comment by PascalPrecht** [comment]
@caybro do you have experience doing this? If yes, would it make sense if you took this issue?

**Comment by caybro** [comment]
This is a bit controversial... define "Taskbar" on Linux. There are many desktop environments (Gnome, KDE, Mate and a dozen others) and not all of them have a concept of a taskbar (task switcher, icon dock or what is meant here?). Furthermore, even within one DE (like Gnome), many replace the builtin "icon dock" with a different one (Dash to Dock). Then we finally get to the point of supporting the "badge indicators"... something that is Ubuntu/Unity specific and for example vanilla Gnome doesn't implement it (and otoh KDE _does_)

So... what to do here? :)

I can definitely take the task and implement this (something I'd wanted to do for other reasons too) but one can't simply expect to making it work everywhere

**Comment by PascalPrecht** [comment]
Thanks @caybro !

**Comment by caybro** [comment]
@alexandraB99 can we move this to 0.11? I see this as very low priority (for the given amount of work and the reasons stated in my above comment)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/10466
