### ISSUE TITLE
Display name is rendered in all lower case letters even though it was entered differently

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5336]
I've created a new account with a display name `Test Account 7`.
Notice that `T` and `A` are capital letters. This happens automatically when entering a display name during onboarding (as if the UI doesn't allow for lower case display names).

However, once set up, the name is in fact rendered in lower cases letters only in various places:

Here's the profile view:
![Screenshot from 2022-04-04 17-06-53](https://user-images.githubusercontent.com/445106/161574025-74edd579-b81b-4f58-a51f-7833342cb3b5.png)

Here's profile popup:
![Screenshot from 2022-04-04 17-07-21](https://user-images.githubusercontent.com/445106/161574109-0829b575-eaef-4b9f-97d6-c87227d3ffad.png)

I think the onboarding process should either allow me to use lower case letters, or at least render the display name exactly how it was entered. Not sure in which scenario we would not want this to be true.

**Comment by abhi-status** [comment]
As with #5223, closing this as this looks resolved in the latest Master.

**Comment by PascalPrecht** [comment]
Actually, that's hard to verify now because it seems whitespaces are no longer allowed when setting up a display nam
![Screenshot from 2022-04-05 14-24-53](https://user-images.githubusercontent.com/445106/161753018-b9ba9f63-0c5c-459e-9c87-548c13bfa689.png)
e

**Comment by abhi-status** [comment]
Ah apologies ! 

I thought white spaces were not allowed any more since we were doing away with the 3 word names.
Is this not the case ?

I'll leave this open until we have some clarity on it.

**Comment by stefandunca** [comment]
Closing and following up with the https://github.com/status-im/status-desktop/issues/5364
