### ISSUE TITLE
Incorrect error is shown if user entered the wrong community private key

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5346]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Sign in and activate all experimental features  in Settings -Advanced
3. Go to Chat and click on the icon of bullhorn near the search field
4. Click Communities - ...
5. Enter '0x04df0ea1c07475625dc596516a0a75555801533ea8f20472c9b06f8f019785ede45649ba452bf59f9f7dd0c19e2a7ffa6e827879b42bc365848fef8245f2235fb1' and click 'Import'

#### Expected behavior
The correct error is appearedor the field has a limit of characters and it's impossible to exceed it
#### Actual behavior
The incorrect error notification appears
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/14942081/161668772-d757abf5-68b7-433c-9433-9460ad326e43.png">

### Additional Information

- Status desktop version: master - commit 6d9c5c4286777669f4f0792f93d672fb7f231eec
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by iurimatias** [comment]
@richard-ramos could you check if this is working with a valid key plz, and this error really is just for invalid keys
