### ISSUE TITLE
Linux Appimage not allowing logging in

### ISSUE THREAD

**Issue by Tim-LaRocque552** [status-im/status-desktop#5347]
# Bug Report

## Description

Set up the Linux appimage with the credentials from my mobile account.  It worked fine, and then I shut the program down.  When I tried to restart the program I got an error message `Login failed. Please re-enter your password and try again`.

### Additional Information

- Status desktop version: StatusIm-Desktop-v0.3.0-beta
- Operating System:  Ubuntu 20.04.4 LTS

**Comment by iurimatias** [comment]
hey @anastasiyaig could you double check if importing seed phrase mobile results in this scenario in latest master please

@Tim-LaRocque552 do you haev any logs?

**Comment by anastasiyaig** [comment]
i was not yet able to reproduce the issue. 
- i took a mobile build (iOS from App Store)
- i created new account there and set password
- i backed up the seed
- i took latest master for desktop
- i recovered the seed on desktop and set password (passwords on desktop and mobile are different)
- i synced both devices
- i shut down both apps

As result, i was able to login to desktop with expected password as well as to mobile with needed password too. Any details how to reproduce the issue are more than appreciated

@iurimatias @Tim-LaRocque552

**Comment by iurimatias** [comment]
closing but will reopen if there are further details. this is probably an old build.
