### ISSUE TITLE
The messages are selected while editing the settings of a channel

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5348]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Create any community and add there a channel
3. Write some messages in the channel and open its settings
4. Click on any element on the setting dialogue and check the messages behind the dialogue

#### Expected behavior
The messages of the channel are not selected while using the channel settings dialogue
#### Actual behavior
The messages are becoming selected

https://user-images.githubusercontent.com/14942081/161671230-dc694968-9408-4a1d-893d-aef792c31cfb.mov

### Additional Information

- Status desktop version: master - commit 6d9c5c4286777669f4f0792f93d672fb7f231eec
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by alexandraB99** [comment]
@elina2015 I can't reproduce this one

**Comment by iurimatias** [comment]
can't reproduce
