### ISSUE TITLE
'Add reaction' appears while editing a category

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5349]
# Bug Report

## Steps to reproduce
1. Sign in with a user that has a community, a category and a few channels in the category
2. Open the category setting for editing and check and uncheck the checkboxes for communities there

#### Expected behavior
The tooltip 'Add reaction' doesn't appear while editing a category and the messages are not selected behind the dialogue
#### Actual behavior
The messages behind the dialogue are becoming selected and the tooltip 'Add reaction' appears while checking the checkboxes
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/14942081/161672311-32283fb3-da41-4a62-9fb0-19cdc22a928a.png">

### Additional Information

- Status desktop version: master - commit 6d9c5c4286777669f4f0792f93d672fb7f231eec
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by alexandraB99** [comment]
@elina2015 I cannot reproduce this one.

**Comment by iurimatias** [comment]
I also cannot reproduce
