### ISSUE TITLE
The icons of channels are not shown in the Editing channel dialogue

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5350]
# Bug Report

## Steps to reproduce
1. Sign in with a user that has a community, a channel and a few channels with avatars  inside this channel
2. Open the settings of the channel and check the avatars of the channels

#### Expected behavior
The avatars are shown correctly
#### Actual behavior
The avatars are not shown and the default images with letters appear
<img width="928" alt="image" src="https://user-images.githubusercontent.com/14942081/161672700-a5e4e4c2-8562-4829-8baf-9929a9ee8766.png">

### Additional Information

- Status desktop version: master - commit 6d9c5c4286777669f4f0792f93d672fb7f231eec
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by iurimatias** [comment]
updated https://ethstatus.testrail.net/index.php?/cases/view/695840 to have steps for edit category

**Comment by iurimatias** [comment]
correction: https://ethstatus.testrail.net/index.php?/cases/view/695837
