### ISSUE TITLE
Cannot change the password in the app settings

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5351]
# Bug Report

## Steps to reproduce
1. Launch the app and sign in
2. Go to Settings - Privacy and Security - Change the password
3. Enter correct current password. new password and confirmation, click 'Change password'

#### Expected behavior
The password is changed
#### Actual behavior
The dialogue is updated and the fields are empty, the password is not changed

In logs:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/14942081/161674651-8843d5b8-f55e-4089-9ab5-56d6f5a3dc75.png">

### Additional Information

- Status desktop version: master - commit 6d9c5c4286777669f4f0792f93d672fb7f231eec
- Operating System: macOS Big Sur, 11.6.5 (20G526)

**Comment by jrainville** [comment]
This is fixed by https://github.com/status-im/status-desktop/pull/5416
