### ISSUE TITLE
Can't scroll when having focus in seed phrase grid in wallet

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5355]
### Description

1. enable wallet
2. click Add account
3. click Advanced
4. click Use 24 words
5. hover any cell of the grid
6. try to scroll

https://user-images.githubusercontent.com/82375995/161717924-0fb2ba6e-51bc-46e6-8fcc-43a1130a053d.mov

**Version:** MacOS, master commit https://github.com/status-im/status-desktop/commit/b54111f82ac0bdbecdace09358080f53891a5505 , april 5 2021

**Comment by iurimatias** [comment]
cannot replicate anymore

**Comment by Khushboo-dev-cpp** [comment]
Works ok on linux, issues on Mac. :(

**Comment by Khushboo-dev-cpp** [comment]
ok another updated is that it works with a mouse wheel on macOS too, only doesnt with touchpad, will investigate further in this directions
