### ISSUE TITLE
Profile icon in app nav bar seems to be too small

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5360]
This is what's designed:

![Screenshot from 2022-04-05 11-40-34](https://user-images.githubusercontent.com/445106/161726179-5d9b22a5-54f1-4221-8375-ad6509a8825b.png)

This is reality right now:

![Screenshot from 2022-04-05 11-40-54](https://user-images.githubusercontent.com/445106/161726225-72196f42-b1cd-4c14-ac98-0ee4f1a77516.png)

**Comment by iurimatias** [comment]
I measured this and it's consistent with the designs
