### ISSUE TITLE
Copying chat key from the Profile page in Settings, copies the old uncompressed Chat key

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5361]
# Bug Report

## Description

Everywhere in the UI, when allowed to copy the chat key, it is the new compressed chat key that is copied.

But on the Profile page (Settings--> Profile), the chat key copied is the old uncompressed chat key.

https://user-images.githubusercontent.com/95302135/161737663-bbac9265-582c-4cf5-9ab8-bf117c190409.mp4

### Additional Information

- Status desktop version: Master : b54111f82ac0bdbecdace09358080f53891a5505

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8918&group_by=tests:status_id&group_order=asc
