### ISSUE TITLE
Cropping has a square shape, while it should be a circle

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5378]
# Bug Report

## Steps to reproduce
1. Go to crop the Profile picture or community picture
2. Check the shape of the cropping area

#### Expected behavior
The cropping area should be a circle
#### Actual behavior
The cropping area is a square
<img width="506" alt="image" src="https://user-images.githubusercontent.com/14942081/161907249-e5028143-a91d-4869-a379-0ace92926ea2.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/5338
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
this is a new feature, being worked on here https://github.com/status-im/status-desktop/issues/5401
