### ISSUE TITLE
The error of database appears while trying to login with a new password

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5379]
# Bug Report

## Steps to reproduce
1. I had a user with a recovery seed phrase
2. While the sign-in process I used the seed phrase and created and saved a new password
3. Now I'm trying to sign in using the new password

#### Expected behavior
User signed in successfully
#### Actual behavior
The error message appears:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/14942081/161904496-bfe9c428-739c-4734-b233-e467f25eaa34.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/14942081/161904596-5d10d7e1-e8d7-4db7-a0bb-f1bd6148740b.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/5338
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
fixed in the meanwhile
