### ISSUE TITLE
Add Date & Time Format in Language & Currency screen

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#5386]
Subtask of [#4917](https://github.com/status-im/status-desktop/issues/4917)

### Description

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=701%3A74776

* [x] Add Date & Time Format 

Make relevant UI code use the chosen Format

* [x] `FetchMoreMessagesButton` component
* [x] `ChatTimePanel` component --> messages tooltip
* [x] Chat messages time
* [x] `AppSearch` component
* [x] `TransactionDelegate` component
* [x] `TransactionBubbleView` component

**Comment by noeliaSD** [comment]
From the new **Language & Currency settings design** the user will be able to decide the date and time format.

There are 2 views where date and time are present in our app:
* **App Searcher:** Messages found and tooltip
* **Chat:** Fetch more messages info and message time info.

Here some screenshots:
<img width="739" alt="Screenshot 2022-04-08 at 14 41 20" src="https://user-images.githubusercontent.com/97019400/162441893-d6c14727-2c93-4468-a8a0-909fa63d9648.png">


<img width="995" alt="Screenshot 2022-04-08 at 14 43 33" src="https://user-images.githubusercontent.com/97019400/162441622-68503ee9-f283-4767-ab3f-76db6e5d98d5.png">

Nowadays we are using the **locale** to display the date but to make it consistant we will use the selected format that the user will configure in the settings screen.

If the user selects:

1. **DD/MM/YY format** the app will display the date like this (option to be decided):

- Wednesday 6 April 2022
- 6 April 2022
- 06/04/22
- 6/4/22
- ... (other option??)

2. **MM/DD/YY format** the app will display the date like this (option to be decided):

- Wednesday, April 6, 2022
- April 6 2022
- 04/06/22
- 4/6/22
- ... (other option??)

3. **24-Hour Time format** the app will display the time like this (option to be decided):

- 06:55
- 6:55
- 23:22 (also time zone info?)
- ... (other option??)

4. **12-Hour Time format** the app will display the time like this (option to be decided):

- 06:27 PM (also time zone info?)
- 6:27 PM
- ... (other option??)

Could the design team @John-44, take a look at it and specify all cases?

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9158&group_by=tests:status_id&group_order=asc
