### ISSUE TITLE
Language needs to be updated at runtime on Linux OS

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#5387]
Nowadays it is needed to restart the desktop application to apply new language setting on Linux OS. A popup is shown to ask the user to quit the app. 

Here the current popup behaviour:

https://user-images.githubusercontent.com/97019400/161928461-3e0977e8-108f-4e1c-9d6a-d4ba6c2c8153.mp4

The expected behaviour is the same than on the other OS, so **the language should follow an 'auto-save' pattern.**

Related to [PR #5300](https://github.com/status-im/status-desktop/pull/5300)

**Comment by iurimatias** [comment]
closing as currently this feature is not supported
