### ISSUE TITLE
Make the reserved space for Saved addresses dynamic

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5399]
### Description

No reason to keep reserved space for Saved addresses section when there are no such addresses, we can make the space dynamic and dependant on actual presence of saved addresses.

Actual result: having no saved addresses i have to scroll to the very bottom of the modal to reach the priority field for the transaction which is odd

<img width="1512" alt="Screenshot 2022-04-06 at 15 24 15" src="https://user-images.githubusercontent.com/82375995/161979359-504b72fe-107f-45db-8de8-bf53259f0a63.png">

**Comment by iurimatias** [comment]
already solved
