### ISSUE TITLE
Change the behaviour of auto jumping fields in the seed phrase page

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5409]
# Bug Report

## Description

Based on the conversation on Discord : 

![image](https://user-images.githubusercontent.com/95302135/162083558-56ef7ed1-1cb8-4ea0-afab-47be8d65c181.png)

#### Expected behavior
 - _Edit:_ Auto-jump only when a word is 100% completed.

 - Word to be completed (when TAB / ENTER is pressed) with whatever word is selected in the auto-complete menu and focus is moved to the next field. 
 
 - When no arrows are pressed, the field must default to the top selected word in the auto-complete menu

 - User must be able to select the word from the auto-complete drop down menu by pressing up and down arrow keys

**Comment by John-44** [comment]
Plus auto-jump if a word is 100% completed

**Comment by anastasiyaig** [comment]
i doubt it is a bug
