### ISSUE TITLE
Cannot add a picture in a public chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5431]
# Bug Report

## Steps to reproduce
1.  Launch the app
2. Sign in and join any public chat
3. Try to add a picture as a message or to a message

#### Expected behavior
There is an icon near the new message field for adding a picture and it's possible to add a picture as a message or to a message
<img width="818" alt="image" src="https://user-images.githubusercontent.com/14942081/162353095-fe846b22-8111-45b5-a3ac-c187bb250ce5.png">

#### Actual behavior
There is no icon near the new message field for adding a picture and it's impossible to add a picture as a message or to a message
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/14942081/162352899-70ddf659-ee1f-4afc-984c-a2b9796eaded.png">

### Additional Information

- Status desktop version: commit 1a8dfde1b28e73213d4a5f37fa774e679a7232bc
- Operating System: macOS 11.6.5 (20G526)

**Comment by iurimatias** [comment]
hey @elina2015 , so in case of image attachments, they are not meant to be supported in public chats
