### ISSUE TITLE
18 words seed option is missing when adding an account in wallet

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5445]
### Description

for onboarding we allow to import 12/18/24 seed , it should be so for wallet as well . It somehow was missed during implementation. before fixing this, a design should be provided. @carlfairclough please assist

<img width="1512" alt="Screenshot 2022-04-08 at 16 31 44" src="https://user-images.githubusercontent.com/82375995/162448621-c8380ff3-48d3-4a9d-8bf5-d2bf7f29bdca.png">

**Comment by iurimatias** [comment]
@anastasiyaig is this one still an issue?

**Comment by anastasiyaig** [comment]
as of today, yes @iurimatias
