### ISSUE TITLE
User is taken to the Community channel directly after logging in

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5454]
# Bug Report

## Description

User is taken to the Community channel directly after logging in. 

## Steps to reproduce

- Launch app and create a new Community and a few Community channels
- Add a couple of known contacts to this Community
- Sign Out and Quit
- Remove Data folder
- Launch app again and use the seed phrase to restore the same account

#### Expected behavior
- User must land on the Chat view

#### Actual behavior
- User is shown the Community that was created and **the Settings cog is now missing**

https://www.loom.com/share/3ca2cadec9124739968ac895ee89af6d

### Additional Information

- Status desktop version: Master : f2898b6bf75ed3aae8fc8abe641646949bf78823

**Comment by iurimatias** [comment]
hey @abhi-status what path was this data folder? it's super weird that it could login in the same account if the data folder itself was removed.

Also could you give this another try using the latest master `85ba478c497da356ac3b3cc46dc8f891c93ebfb7` there was a crucial hotfix 1 hour ago, and might be related to this

**Comment by abhi-status** [comment]
> it's super weird that it could login in the same account

hey @iurimatias 
Sorry that was a bit of typo. 
I've edited it to say 'use the seed phrase' to restore the same account.

**Comment by abhi-status** [comment]
I have tried the latest Master, and the issue persists here as well
