### ISSUE TITLE
Generated account is not expected / same as mobile

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5470]
# Bug Report

## Description

This is a very important issue in master that needs to be fixed before any release.

## Steps to reproduce

1. open the app and generate a new app account and take note of the seed phrase
2. go to mobile and import that seed phrase
3. on mobile, generate a new wallet account
3.1 take note of account address
4. on desktop, generate a new wallet account
4.1 click add account
4.2 type password and a name
4.3 press add account
4.4 take note of account address

#### Expected behavior

generated account in desktop is the same as mobile

![IMG_5790](https://user-images.githubusercontent.com/176720/162615618-7c86b7f7-4c3f-4bfc-a20d-d0ce7a0bb7de.PNG)

![Screen Shot 2022-04-10 at 7 19 30 AM](https://user-images.githubusercontent.com/176720/162615575-c27e6872-b9eb-4d80-bf9d-a96a0e07aefd.png)

#### Actual behavior

the accounts are different.

### Additional Information

test rail case added to ensure we always catch this in the future https://ethstatus.testrail.net/index.php?/cases/view/702193

**Comment by iurimatias** [comment]
possibly fixed by https://github.com/status-im/status-desktop/pull/5281

**Comment by anastasiyaig** [comment]
it looks fixed now
