### ISSUE TITLE
adding an account with lots of NFTs is slow

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5494]
# Bug Report

## Description

Adding this account `0xb77b2cddd60CFd880583294c2f71bf128d55Fa56` (random account found in opensea) that has a lot of NFTs, takes quite a while.

## Steps to reproduce

1. click add account
2. select watch only
3. add this account `0xb77b2cddd60CFd880583294c2f71bf128d55Fa56`
4. click add

#### Expected behavior

should immediatly add this aaccount, or add it in a reasonable time (2 seconds tops)

#### Actual behavior

takes 30 seconds and hangs the app

**Comment by alaibe** [comment]
Should be fix by: https://github.com/status-im/status-desktop/pull/5506
