### ISSUE TITLE
collectibles not displaying

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5495]
# Bug Report

## Description

![Screen Shot 2022-04-11 at 4 42 03 PM](https://user-images.githubusercontent.com/176720/162828567-a20c4951-2a3d-4993-b030-74b4140c2da9.png)

## Steps to reproduce

1. add account
2. select watch only
3. add an address with NFTs, for e.g `0x466450ac1ec17f1e01dbfd9af99288f00086e187`
4. go to collectibles tab
5. select one of the collections and expand

#### Expected behavior

should display the NFTs inside the collections

#### Actual behavior

displays "no collectibles available"

### Additional Information

- Status desktop version:
- Operating System:

**Comment by alaibe** [comment]
it should be fixed by: https://github.com/status-im/status-desktop/pull/5506
