### ISSUE TITLE
Move Language and Currency stores logic to backend (initialization to nim, data to status-go)

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#5498]
New **Language & Currency screens** design is currently using Stores but implemented in QML. It would be better to move the logic to the backend.

Comented here: 
https://github.com/status-im/status-desktop/pull/5417#discussion_r847649288 and https://github.com/status-im/status-desktop/pull/5417#discussion_r847650372

Related task: https://github.com/status-im/status-desktop/issues/4917 

**NOTE:** Maybe it is better to address it when the migration to C++ is ongoing!

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5744
