### ISSUE TITLE
Add copy / paste possibility for seed phrase

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5501]
### Description

1) copy a seed phrase
2) focus the first input field on the seed phrase form
3) CTRL+V  paste the seedphrase, which results in every field being populated

If the seed phrase is longer than available inputs, we should also auto switch to the correct number of inputs to match the seed phrase.

Places to implement:

1. when doing onboarding (i am new to status , I already use status)
2. when importing a wallet account with seed phrase (12 and 24 words options)

**Comment by John-44** [comment]
Perhaps if the seed phrase that is copied is exactly 12, 18 or 24 words, paste the seed phrase from the beginning field, irrespective of which field is focused at the moment the user presses CTRL+V?

Also the implementation should be tolerant of seed phrase words being separated by:
- single spaces
- multiple spaces
- comma, followed by a space
- carriage returns
- spaces followed by carriage returns

If the seed phrase words are separated by any of the things mentioned above, this functionality should still work.

In terms of "Places to implement", I think this should be implemented everywhere the seed phrase entry control is used (e.g. there shouldn't be any instances anywhere in the app where the seed phrase entry control is used and this functionality isn't supported).

**Comment by jrainville** [comment]
Unassigned Boris, since I already did this in my seed phrase improvement PR here https://github.com/status-im/status-desktop/pull/5632

**Comment by John-44** [comment]
@ulisesmac I forgot one in the list above, we should also add: comma, NOT followed by a space
