### ISSUE TITLE
@ Mention is broken on latest Master

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5505]
# Bug Report

## Description

The user can select a contact using `@`
But as soon as the msg goes on to the Chat window, the `@` highlight link disappears

![image](https://user-images.githubusercontent.com/95302135/162941980-9371e5a1-b88d-4d0e-906b-9447cc8c0300.png)

### Additional Information

- Status desktop version: Master : 8d4aa7dd56708ed58cd14f92440649100f0dbcd6

**Comment by saledjenic** [comment]
@abhi-status I tested this on 1:1, group and public chats, as well as for community channels and it looks ok everywhere for me, tested on latest master, commit `d94abcb31ef0400a81ff21439aa3c0a79f6778c1 `.

**Comment by abhi-status** [comment]
I've just verified on latest Master as well. 

I could replicate the behaviour until I rebooted the app.

Now it works as expected.
