### ISSUE TITLE
Profile image isn't shown in contacts list

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5514]
![Screenshot from 2022-04-12 16-34-52](https://user-images.githubusercontent.com/445106/162987220-034ea89c-ca22-4a13-bcfb-2759659c3b24.png)

**Comment by PascalPrecht** [comment]
This in Settings -> Messaging -> Contacts

**Comment by iurimatias** [comment]
![Screen Shot 2022-05-10 at 11 09 06 AM](https://user-images.githubusercontent.com/176720/167661563-42462d3b-940b-4c76-866c-db87585487b6.png)

cannot replicate anymore

**Comment by PascalPrecht** [comment]
Can still reproduce this in latest master:
![Screenshot from 2022-05-13 10-56-09](https://user-images.githubusercontent.com/445106/168248703-55307895-4e98-4753-9510-80ccb6ce4e79.png)

**Comment by iurimatias** [comment]
ok I'll try to replicate again, perhaps it's for people without profile pictures

**Comment by PascalPrecht** [comment]
That could very well be!

**Comment by osmaczko** [comment]
Needs https://github.com/status-im/status-desktop/issues/5951

**Comment by borismelnik** [comment]
@iurimatias @PascalPrecht looks like fixed in current master

**Comment by elina2015** [comment]
@borismelnik  @PascalPrecht @iurimatias hey, I tested on the latest [master](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2239/):
I can see the profile image of my mutual contact if this user uploaded it:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/14942081/175786149-f8e6e4b0-8e15-49d8-87ae-fa6f3d6faaa2.png">
But I cannot see the default profile image for the mutual contact:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/14942081/175786278-ea2c64e6-f5be-4760-a54e-5096379b6efb.png">

**Comment by borismelnik** [comment]
@elina2015 thank you!
