### ISSUE TITLE
Implement "Add / remove from group" button for group chats

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#5522]
Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=417%3A243810

![image](https://user-images.githubusercontent.com/11926403/163033786-a8c4e5ec-4b82-42e1-8ec9-7f363cda69e9.png)
![image](https://user-images.githubusercontent.com/11926403/163033825-3d708378-1ba8-4abd-99c8-44826a9d6223.png)

**Comment by noeliaSD** [comment]
It requires implementation of https://github.com/status-im/StatusQ/issues/694

**Comment by elina2015** [comment]
@noeliaSD could you kindly check my comments in https://github.com/status-im/status-desktop/pull/5823?

**Comment by elina2015** [comment]
The found issues will be separated and moved to another ticket.
