### ISSUE TITLE
The infenite loader is shown after finishing the onboarding process

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5526]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Click 'I am new to Status' - 'Generate new keys'
3. Fill out the Display Name, and passwords pages and click 'Finalize ...'

#### Expected behavior
The onboarding process is finished successfully
#### Actual behavior
The infinite loader is shown after finishing the onboarding process on the page'
<img width="879" alt="image" src="https://user-images.githubusercontent.com/14942081/163067673-efa1373b-6510-4ba1-904a-65bb8c7896ca.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/4502
- Operating System: macOS Big Sur, v. 11.6.6 (20G604)

**Comment by anastasiyaig** [comment]
it is a duplicate, please check it carefully before logging https://github.com/status-im/status-desktop/issues/5519
