### ISSUE TITLE
The menu 'Paste' appears in the Password field and it doesn't work

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5547]
# Bug Report

## Steps to reproduce
1. Launch the app and hit 'I am new to Status' - 'Generate the new keys'
2. Enter some Display name' and click 'Next'
3. Copy some text and right click on the Password or Confirmation password field, or the next Confirmation password field

#### Expected behavior
Variant A:
Nothing appeared, it's impossible to paste any text in the Password field

Variant B:
The button 'Paste' appears and after clicking the copied text appears in the Password field
#### Actual behavior
The menu 'Paste' appeared, but when click on it - it doesn't work
<img width="633" alt="image" src="https://user-images.githubusercontent.com/14942081/163308059-39a338bb-df5a-4e84-ad3e-7db477dff4d2.png">
<img width="518" alt="image" src="https://user-images.githubusercontent.com/14942081/163308126-b714df55-6db9-4c66-8179-181eb4201cb3.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/14942081/163308203-dfef84e8-b4ca-4c33-9407-1cb56aa3f5e6.png">

### Additional Information

- Status desktop version: commit 31728940c4d8efd0b9b8c4c6ed22801dde8c3309
- Operating System: MacOS Big Sur, v. 11.6.6 (20G604)

**Comment by alaibe** [comment]
Could you re-test, I have no problem on Linux/Windows with the right-click -> paste

**Comment by iurimatias** [comment]
can confirm this happens on mac

**Comment by elina2015** [comment]
Tested the latest [master ](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-220518-122121-8eff1b.dmg/*view*/) - the button 'Paste' works and the copied text appears in the password field:


![Image](https://user-images.githubusercontent.com/14942081/169141880-cdd9c40b-13dd-4f08-9e55-9eca9f131e8e.png)
