### ISSUE TITLE
Getting black profile colors and missing identity rings in members list:

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5551]
![Screenshot from 2022-04-14 12-28-47](https://user-images.githubusercontent.com/445106/163369990-fc6da412-361a-4266-ad8d-ec687075632d.png)

/cc @osmaczko

**Comment by noeliaSD** [comment]
Check if it is possible to use `StatusMemberListItem` component from `StatusQ`.

**Comment by PascalPrecht** [comment]
Another thing to note here, though doesn't have to be part of this issue, it seems that the contact list that's rendered **below** the tag selector component is part **of** the tag selector component. 

That doesn't look right to me. Would be cool if that gets extracted at some point.

**Comment by noeliaSD** [comment]
> Another thing to note here, though doesn't have to be part of this issue, it seems that the contact list that's rendered **below** the tag selector component is part **of** the tag selector component.
> 
> That doesn't look right to me. Would be cool if that gets extracted at some point.

This will be addressed here: https://github.com/status-im/StatusQ/issues/682

Closed issue bc it has been solved in https://github.com/status-im/status-desktop/issues/5625.
