### ISSUE TITLE
Group chat color is different for different accounts

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5555]
So I started a group chat and I'm looking at the chat with two different accounts. 
For one account, it looks like this:
![Screenshot from 2022-04-14 12-41-01](https://user-images.githubusercontent.com/445106/163373053-ac5bfbf2-6623-415d-a0ca-f676e93df94d.png)

For the other, the same group chat looks like this:
![Screenshot from 2022-04-14 12-41-11](https://user-images.githubusercontent.com/445106/163373133-6a221c3d-cc50-4970-8e9b-3b5b8f64e81b.png)

They both render different colors. I'd expect them to be the same

**Comment by jrainville** [comment]
I think this might be fixed already by @endulab 's work

**Comment by elina2015** [comment]
Tested on https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.8.x/17/ and the bug is not reproduced

**Comment by endulab** [comment]
> I think this might be fixed already by @endulab 's work

Yes, this was fixed long time ago.
