### ISSUE TITLE
User cannot log back in after changing Fleet

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5569]
# Bug Report

## Description

After changing the fleet, the app crashes (or shuts down (?))
User is not able to log back in after this.

![image](https://user-images.githubusercontent.com/95302135/163635133-e51f8d71-0f84-47e2-b56d-05ad87286465.png)

[data.zip](https://github.com/status-im/status-desktop/files/8498356/data.zip)

### Additional Information

- Status desktop version: Master

**Comment by jrainville** [comment]
I cannot reproduce on Linux on latest master `2154626a5bba42bf70ae89cf4a7fbd7633aa4dbb`
The inability to login seems because it semi-crashed and there was a zombie, but since I'm now able to change fleet successfully, login back in works.
