### ISSUE TITLE
Allow notifications page missing on first app run

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5583]
# Bug Report

## Description

Allow notifications screen is missing when the app is launched after a fresh install.

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1075%3A312335

![image](https://user-images.githubusercontent.com/95302135/165034840-25c9ff50-668d-4f34-9d63-e33f96ef2d4b.png)

### Additional Information

- Status desktop version: Master on Commit - 5e05a7613c0d7ca1a7a87059cc76cd01d6ed11e9

**Comment by carlfairclough** [comment]
Here is the notification png, with shadow. @1x, @2x, and @3x are included
![Notification (Double Button)@1x](https://user-images.githubusercontent.com/4670881/169528591-4ffc52eb-8918-4165-94d4-7cebb1409bd2.png)
<img width="364" alt="Notification (Double Button)@2x" src="https://user-images.githubusercontent.com/4670881/169528595-d1fd54c3-662d-49e5-9a5f-f4698f72fc39.png">
![Notification (Double Button)@3x](https://user-images.githubusercontent.com/4670881/169528598-d64ce740-0071-47b9-82c8-d09bf0bf2110.png)

**Comment by carlfairclough** [comment]
Here is the notification png, with shadow. `@1x`, `@2x`, and `@3x` are included
![notification-with-hand](https://user-images.githubusercontent.com/4670881/169537094-f82caa80-d45d-4354-ba24-134b939e78bc.png)
<img width="400" alt="notification-with-hand@2x" src="https://user-images.githubusercontent.com/4670881/169537100-5f2a733c-fc55-49dc-b609-8346b18968ba.png">
![notification-with-hand@3x](https://user-images.githubusercontent.com/4670881/169537103-39b02ed5-8656-4f72-8011-0f859e75026e.png)
