### ISSUE TITLE
Biometrics screen updates

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5585]
# Bug Report

## Description

The following changes need to be made on the Biometrics screen :

1- change spelling of `TouchID` to `Touch ID`
2- replace `I prefer to use my PIN` with `I prefer to use my password`
3- remove back button on biometrics screen as the account is already created at that point
4- update the image with the latest asset from here -> https://www.figma.com/file/S5XnhIrgmmCS90CVE454mB/Illustration-Assets?node-id=70%3A38
![image](https://user-images.githubusercontent.com/95302135/165046383-dc4d0320-3645-47f8-b394-96f7839f6ff2.png)

### Additional Information

- Status desktop version: Master

**Comment by alexandraB99** [comment]
@abhi-status regarding point 3, there was a [discussion on Discord about this](https://discord.com/channels/624205794384281629/730410574428504166/953356230515105792), is this changed now?

**Comment by MishkaRogachev** [comment]
Status update:
1. Done
2. Done
3. Out for now (https://github.com/status-im/status-desktop/issues/5585#issuecomment-1114616073)
4. Waiting access to Figma

Questions:
1. I did not find any translation files for the Biometrics screen. Are they exist?
2. How I can get to the Biometrics screen?

**Comment by alexandraB99** [comment]
@abhi-status please ignore my comment, I saw that this is decided to be removed

**Comment by MishkaRogachev** [comment]
All changes ready for review
