### ISSUE TITLE
Add/correct hard keys behavior in Seed Phrase Input screen

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5608]
### Description

- Pressing enter in forms should submit the form
- Pressing tab in inputs should jump to next one
- Up down Arrows should select the word in the suggestions list
- First item in autosuggest dropdown menu should be always focused and if user clicks tab, the focused word should be and inserted in text field

**Comment by jrainville** [comment]
This is a duplicate of https://github.com/status-im/status-desktop/issues/5409
