### ISSUE TITLE
Check the position of the message error in the Confirmation Screen

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5610]
### Description
The position of the message error in the Confirmation Screen should be as in [figma](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?node-id=1023%3A298171)

**Comment by noeliaSD** [comment]
In figma it is not specified the case of message error for this screen but to have consistency with other screens it will be positioned like this:

![Screenshot 2022-05-05 at 16 22 44](https://user-images.githubusercontent.com/97019400/166944677-d792b1d5-454a-4836-b5c2-9170f4bba0cd.png)
