### ISSUE TITLE
Check when “Finalize Status Password Creation” should be enabled

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5611]
### Description
Now it is enabled when introduced chars are 6 and maybe it should only be enabled when the password is exactly the same as the one introduced in the previous screen.

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2796%3A381870

**Comment by noeliaSD** [comment]
Agreed with @John-44 that this screen will not display any error message and the only way of enabling the finalize button is if it is exactly the same password than created in the previous screen.
