### ISSUE TITLE
scrolling messages is not smooth and hiccups

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#5616]
version [StatusIm-Desktop-220503-160728-952f39.dmg](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-220503-160728-952f39.dmg)

its hard to describe or show on the video, but scrolling is not smooth and it stops, jumps, freezes, starts to move again, so it  hiccups

also, I think highlighting messages on mouse over is not a good idea as well

**Comment by iurimatias** [comment]
duplicate of https://github.com/status-im/status-desktop/issues/3067
