### ISSUE TITLE
[Onboarding] Enable scan sync code, Login with Keycard 

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5621]
### Description
Connect your keys page to include Scan sync code, Login with Keycard

Figma link:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1042%3A303014

**Comment by iurimatias** [comment]
on hold for now until some keycard designs are finalized
