### ISSUE TITLE
[Onboarding] Implement new flow for sync with Waku

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5622]
### Description
Implement new flow for sync with Waku to get user profile data to be added

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1193%3A318169

**Comment by John-44** [comment]
Also see this relevant discussion

![2022-05-12 15_07_23-desktop-ui - Discord](https://user-images.githubusercontent.com/22846356/168094386-f06b31fd-0092-445c-a45f-8b398c370fe2.png)

about which was triggered by this bug https://github.com/status-im/status-desktop/issues/5704

**Comment by iurimatias** [comment]
@alexandraB99 @John-44 the figma link no longer works, what was was the design intended for this task?

**Comment by jrainville** [comment]
Isn't this already done by @saledjenic ?

**Comment by John-44** [comment]
> Isn't this already done by @saledjenic ?

the designs were updated one week ago (on one of these screens the QR scanner was missing from the designs, and instead a QR code was incorrectly displayed), so this part is definitely not implemented

**Comment by saledjenic** [comment]
> Isn't this already done by @saledjenic ?

@jrainville short answer nothing is ready yet as of recover account flow.


@jrainville during the onboarding phase there are 3 ways (from the UI perspective) how you can recover your account:
1. login by scanning a  sync code
2. login with Keycard
3. login with seed phrase

Basically flows UI flows 2 and 3 are the same, so we can say there are 2 logical ways to recover an account:
1. (UI case 1) - getting data from the paired device if user has another device with installed Status app and wants to get the state from it
-> I am not sure if anyone started with it neither if it's assigned to anyone, actually exactly as @John-44 described.

2. (UI cases 2 and 3) - fetching data from waku
-> That's on my todo list, but that won't be done soon cause I have to finish some other things before I move to that. Also before I start with it have to explain and discuss with mobile team an idea I want to apply there. The list of things that need to be backed up and fetched from waku is long, it affects all parts of the application, there will be a lot of changes and I don't expect it to be done quickly.
