### ISSUE TITLE
[Login] Add Welcome back Status logo

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5623]
### Description
Add Welcome back Status logo in login screen:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1535%3A347198

**Comment by PascalPrecht** [comment]
@MishkaRogachev In case you haven't started yet, maybe can assign me to this one? I've started on tihs today, wasn't aware of this issue..

**Comment by MishkaRogachev** [comment]
Yep, as you wish )
