### ISSUE TITLE
[Login] Move generate new keys button in the user dropdown

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5624]
### Description
Generate new keys button should be in the user dropdown list:

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?node-id=1535%3A347198

**Comment by PascalPrecht** [comment]
This has landed as https://github.com/status-im/status-desktop/commit/1b7be6060d3dcf1a348e5c679ed8cb250eeae9dc
