### ISSUE TITLE
Create needed enums for date format and time format and replace boolean properties (when C++ project is ready and exposing enums is not costly)

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#5635]
### Description
Nowadays we are using 2 boolean properties to manage **date and time format** in `src/app/global/local_account_sensitive_settings.nim`:
- `isDDMMYYDateFormat`
- `is24hTimeFormat`

It will improve the code if instead of using booleans, an enumerator is used so it is clear what happen in both cases, if true or if false and they can be prepared, as well, for future formats. 

See comments on the following PR for more information:
_Originally posted by @Khushboo-dev-cpp in https://github.com/status-im/status-desktop/pull/5543#discussion_r865662961_

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5744
