### ISSUE TITLE
[Activity Center] Update to show contact and pending requests

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5639]
### Description
Update activity center to show contact requests as well as pending requests

Figma link: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1838%3A363377

**Comment by endulab** [comment]
Blocked by #5905

**Comment by MishkaRogachev** [comment]
Closed with https://github.com/status-im/status-desktop/pull/7620
