### ISSUE TITLE
[Chat] Create new chat input should be single line

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5641]
### Description

Disable multiline from create new 1-1/group chat view text input

**Comment by MishkaRogachev** [comment]
Can i request a picture, what component i should change

**Comment by alexandraB99** [comment]
Sure, it's the SttausTagSelector component which you can see when trying to create a new chat:
<img width="771" alt="nc" src="https://user-images.githubusercontent.com/31625338/167100980-2d4af6a5-b06c-4258-af34-43d2929d6c2e.png">
