### ISSUE TITLE
[Chat] Add Add/remove contacts option for group chat creator 

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5644]
### Description
Group chat creator must see Add/remove contacts option

**Comment by alexandraB99** [comment]
@noeliaSD, @jrainville I guess this duplicates this https://github.com/status-im/status-desktop/issues/5522? please check and close one accordingly :)

**Comment by noeliaSD** [comment]
Ok! So closed issue because of duplication with #5522.
