### ISSUE TITLE
[Settings] Fix all margins in settings views

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5646]
### Description
All margins within settings should have consistent width

**Comment by MishkaRogachev** [comment]
So, all the stuff here must have same margins. Should they be fixed or dynamic according widow width?
![image](https://user-images.githubusercontent.com/2522130/167097513-e50f4473-3e73-48fe-ab94-d1d85226b7e8.png)
![image](https://user-images.githubusercontent.com/2522130/167097577-e37efdf2-9304-43d5-94f5-490a404bf952.png)
![image](https://user-images.githubusercontent.com/2522130/167097721-84f0e891-14d3-42e5-be4f-80af605f5e98.png)

**Comment by alexandraB99** [comment]
You can check [here](https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/⚙%EF%B8%8F-Settings-%7C-Desktop?node-id=7%3A183) for settings screens.
