### ISSUE TITLE
[very hard to replicate] 1 to 1 chat window contains messages from other contacts

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5668]
# Bug Report

## Description

1 to 1 chats seem to contain messages from other contacts.

Also, @PascalPrecht noticed this discrepancy where a public chat msg was seen on a 1 to 1 chat -> [here](https://discord.com/channels/624205794384281629/697843216048717905/971327104698449960)

## Steps to reproduce

1. Launch app, sign in (Usr-1) and send a contact request to a user (Usr-2)
2. Sign out and sign in as Usr-2 and accept the contact request from Usr-1
3. Send a msg to Usr-1 and then sign out
4. Sign in as another user (Usr-3) and send a contact request and then a msg to Usr-1
5. Sign out and sign back in as Usr-1
6. Accept the contact request from Usr-3 
7. Check the 1 to 1 chat from Usr-2

#### Expected behavior
The user must only see the msg from the selected user

#### Actual behavior
The chat window also shows msg from another 1 to 1 chat 
![image](https://user-images.githubusercontent.com/95302135/167388011-1109dbb7-2322-4d83-8842-2304808e30b7.png)

### Additional Information

- Status desktop version: Master : d4ef0ff5e864d342857b51f58cea67c5db5004c2

**Comment by saledjenic** [comment]
Following the steps the description I am not able to reproduce this issue (using mac + mobile). 
If anyone is able to reproduce and share how to reproduce this issue, I will be happy to fix it.

**Comment by PascalPrecht** [comment]
This turns out to be hard to reproduce indeed.
I'd keep this issue around though, because we don't know if this will happen again.
