### ISSUE TITLE
[Onboarding] Update SeedPhraseInput Layout

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5669]
### Description

Update onboarding SeedPhraseInput component according the the new designs:
https://www.figma.com/proto/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=4160%3A160332&scaling=min-zoom&page-id=2499%3A150211&starting-point-node-id=4160%3A160332

**Comment by Hbouaz** [comment]
Old:


![Image](https://user-images.githubusercontent.com/26457452/169275110-2eeedaff-c9f0-4763-9176-39767f238d0f.png)

New:


![Image](https://user-images.githubusercontent.com/26457452/169275218-65a71027-d3b7-47ce-aad3-1d8cea7d57d4.png)
