### ISSUE TITLE
Polish create channel name input

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#5673]
Remove smiley on the right.

Also, remove the extra space between channel and colour below.

**Comment by alexandraB99** [comment]
Hey @jrainville I was about to start with #5636 but I guess we need this issue first right? would it make sense that 5636 is part of #5673?

**Comment by jrainville** [comment]
@alexandraB99 I think you should be good to start now. I already have a PR anyway, so worst case, you can branch off my branch.

Anyway, I worked mostly on the channel name input, whereas your issue is for the colour input.
