### ISSUE TITLE
Remove + sign in Community and show create ad-hoc group button instead

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#5677]
Remove the + button at the top of communities and show the ad-hoc group button (same one that's in the personal chat section.

Also add a new "button" text at the button to add channels or categories

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2674%3A367792

**Comment by elina2015** [comment]
@jrainville could you kindly check my comments in the [PR](https://github.com/status-im/status-desktop/pull/5682)?

**Comment by elina2015** [comment]
For QA: test run is available [here](https://ethstatus.testrail.net/index.php?/runs/view/9197&group_by=tests:status_id&group_order=asc)
