### ISSUE TITLE
New Create new Community modal

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5679]
![Screen Shot 2022-05-09 at 1 31 32 PM](https://user-images.githubusercontent.com/176720/167465156-2fd76876-053b-49d7-b4f3-18bff2d1c1a2.png)

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2563%3A524846

note: task scope is redesign, new features are out of scope and should be done in a separate task

**Comment by jrainville** [comment]
This task is kindof a duplicate. There are already separate tasks that split this one in multiple smaller ones, like:
- this for the bottom checkboxes: https://github.com/status-im/status-desktop/issues/5660
- this for the banner https://github.com/status-im/status-desktop/issues/5118
- this for enabling pins by anyone https://github.com/status-im/status-desktop/issues/5662

**Comment by jrainville** [comment]
Closing because this is a duplicate
