### ISSUE TITLE
Creating community tags

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5680]
### Description

see https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2759%3A388620

**Comment by iurimatias** [comment]
this needs to be analyzed first

**Comment by iurimatias** [comment]
to be done after https://github.com/status-im/status-desktop/issues/5720

**Comment by noeliaSD** [comment]
Once it is done, it could be added that https://github.com/status-im/StatusQ/issues/690 into the `Community Portal` section.
