### ISSUE TITLE
C++ - Add internationalisation support

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#5689]
### Notes

Patryk has in-depth knowledge of the nim-app translation process
The nim app has translation disabled due to performance issues. Not sure if nim/QML integration or something else
Live language change is not fully supported now but it is desired for the C++ app

**Comment by MishkaRogachev** [comment]
First thing: if we want to pack translations to the binary app there is solution to generate temporary .qrc files with compiled .qm-files. Usage (cmake):
```
# Create translations QRC file from .ts files
file(GLOB TS_FILES "translations/*.ts")
tr_to_qrc("${CMAKE_CURRENT_BINARY_DIR}/some_name.qrc")

# Generate 
qt5_add_resources(QRC_SOURCES ${QRC_FILES} )

# Compile
target_sources(${PROJECT_NAME} PRIVATE ${QRC_SOURCES})
```
[TrToQrc.cmake.txt](https://github.com/status-im/status-desktop/files/8671460/TrToQrc.cmake.txt)
