### ISSUE TITLE
C++ - Add live/hot reloading support

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#5690]
### Notes

Good overview of available options to consider: https://qml.guide/live-reloading-hot-reloading-qml/
Internal experience using [QMLLive](https://doc.qt.io/QMLLive/qmllive-index.html); [src](https://codereview.qt-project.org/admin/repos/qt-apps/qmllive)
The StatusQ sandbox had hot-reloading implemented and was removed [here](https://github.com/status-im/StatusQ/commit/2ee91475e5c8450283e403bff9835b0d9436d9e0#diff-8bc5cfea75e182f293c1b43795de4722c544570cb323c41ae82c4d6bf8ae9b84L46)

**Comment by anastasiyaig** [comment]
@iurimatias i moved it to Iteration backlog, please be aware
