### ISSUE TITLE
C++ - Logging support with QT/QML integration

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#5692]
### Notes
Required logging system with filters and policies
Deep integration with Qt/QML
Something already in place in the old code: [Qt registering](https://github.com/status-im/status-desktop/blob/e4feaa39ac99ee3572a22363209844da9f534630/src-cpp/main.cpp#L20)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5745
