### ISSUE TITLE
C++ - CI: add clang-tidy and clang-format checks

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#5693]
### Notes
Files are already available [.clang-format](https://github.com/status-im/status-desktop/blob/master/.clang-format), [.clang-tidy](https://github.com/status-im/status-desktop/blob/master/.clang-tidy)
Requires integration with CI
Nice to have setup guides for IDEs (vscode, QtCreator)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/5745
