### ISSUE TITLE
Contact details are not being reflected without restart

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5709]
### Description

1. add a desktop account to contacts from mobile device and check incoming contact requests -> nothing is shown without restart
2. add a desktop account to contacts from mobile device and confirm on desktop (so mobile should be your contact now) -> it is shown as `not in contacts` until restart

![image](https://user-images.githubusercontent.com/82375995/167851904-7c6ae514-fdb7-48c0-8365-2a06462e379c.png)

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9247&group_by=tests:status_id&group_order=asc

**Comment by elina2015** [comment]
@jrainville please check my and @igor-sirotin comments - we need a fix of the found issue.
