### ISSUE TITLE
Password validation for transaction and add account

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#5719]
Since password rule have changed, this 2 places probably needs to be updated too

1. click generate account
2. type 7 characters in the password field
3. add account

result: no error
expected result: should validate that the password needs to be at last X characters, use same validations as the onboarding.

**Comment by alexandraB99** [comment]
@alaibe I can already see an error message "Wrong password" if I only type 7 characters
![Image](https://user-images.githubusercontent.com/31625338/188409081-d9fc8518-1796-4c4f-b006-0ede88b82d83.png)

I update it to what's on onboarding 
![Image](https://user-images.githubusercontent.com/31625338/188409140-5a19a9ab-c9b6-44f4-bcdb-150b8f07ba33.png)

without changing any other behavior, please have a look at the PR https://github.com/status-im/status-desktop/pull/7224 and let me know!
