### ISSUE TITLE
Receiving a contact request is broken in Contacts

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#5730]
## Description

<img width="1123" alt="Screen Shot 2022-05-12 at 14 25 54" src="https://user-images.githubusercontent.com/47554641/168244994-c592ca65-4dc7-4bce-b321-90de15df2c40.png">
<img width="1123" alt="Screen Shot 2022-05-12 at 14 28 04" src="https://user-images.githubusercontent.com/47554641/168245008-06888da3-b9e2-4af9-9f18-d32f5c43e9c5.png">

## Steps to reproduce

1. New account, no contact added
2. Receive a contact request

#### Actual behavior

Contact request is not displayed in "Contacts, Requests and Blocked Users".
The tabs with Contacts/Pending ... are overlapping

### Additional Information

- Status desktop version: edbaccd6bfb99641703bc0da972df84283960bd6
- Operating System: Mac

**Comment by MishkaRogachev** [comment]
Current master, Kubuntu 20.04
![image](https://user-images.githubusercontent.com/2522130/168542826-0207e05b-7ae1-496c-ae1c-624c3f436af6.png)

**Comment by MishkaRogachev** [comment]
![contacts-2022-05-16_10 41 52](https://user-images.githubusercontent.com/2522130/168543637-0f9bdded-d528-419c-8640-f4ef08531dfb.gif)

**Comment by stefandunca** [comment]
Checked it with the latest master, and it doesn't reproduce anymore.

**Comment by MishkaRogachev** [comment]
> Checked it with the latest master, and it doesn't reproduce anymore.

@iurimatias can i close issue?
