### ISSUE TITLE
"Password must be at least 10 characters long" appears only after re-focus

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#5734]
https://user-images.githubusercontent.com/33099791/168293593-3365c0b3-7d2c-4482-801d-36b277b1915f.mp4

**Comment by alexandraB99** [comment]
@osmaczko I can't reproduce this one

**Comment by osmaczko** [comment]
@alexandraB99 I believe you need to:
1) type into "confirm password" field
2) remove the whole content from "confirm password" field
3) type again

https://user-images.githubusercontent.com/33099791/168996320-4036eb3a-4ff6-4fb1-a152-2219e25a9485.mp4
