### ISSUE TITLE
Secure your seedphrase banner

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5743]
### Description

When the user has not backed up their seedphrase a banner should show on the top

![Screen Shot 2022-05-15 at 8 28 17 AM](https://user-images.githubusercontent.com/176720/168472929-ab68364f-00f7-419d-83ed-675a17ad524b.png)

### Acceptance Criteria

- [ ] creating an account and going to the profile section should show the banner
- [ ] clicking the 'X' in the banner should not display the banner anymore

**Comment by John-44** [comment]
This banner has already been implemented (the banner pattern is also used for 'testnet mode' and for 'informing the user of an available app update'), the existing implementation should be reused for this.

All top banner notifications (backup seed phrase, testnet mode, update available) should be visible on all screens in the app (post login)
