### ISSUE TITLE
Community Intro Message for new members

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5746]
### Description

Communities should have an intro message associated to them that new users see when attempting to join. This is different from the description.

### Acceptance Criteria

- [x] Creating a community should have text input for intro message
- [x] Editing a community should have a text input for intro message (see [design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=3132%3A383870))
- [x] When joining a community the user should see an intro message in a modal and have to accept to join the community (see [design](https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop-(rolled-back-version-to-recover-a-screen%2C-ignore)?node-id=2457%3A342267))

out of scope: captcha

**Comment by elina2015** [comment]
@osmaczko please check my comments in https://github.com/status-im/status-desktop/pull/5882

**Comment by elina2015** [comment]
@osmaczko tested it again and has some new issues. Could you kindly check https://github.com/status-im/status-desktop/pull/5882?

**Comment by osmaczko** [comment]
@elina2015 I've addressed your new findings. Could you please take a look https://github.com/status-im/status-desktop/pull/5882?
