### ISSUE TITLE
changing username is not immediatly updating

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5765]
# Bug Report

1. go to profile and edit username
2. go to left corner and click view profile to open modal

result: modal still shows old username

![upload_f21b56f2257bb80039f80e31caa7503f](https://user-images.githubusercontent.com/176720/168678445-5c1dcd62-9523-45d2-b496-4d3e5335531b.png)

**Comment by elina2015** [comment]
@Khushboo-dev-cpp Could you kindly help me to see the PR for this task?

**Comment by anastasiyaig** [comment]
i linked the PR and going to test it @elina2015
