### ISSUE TITLE
should not be possible to edit stickers

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5766]
# Bug Report

1. send a sticker
2. right click and press edit

result:

![upload_80629691b5c584f4e801abbfbdd7a3b8](https://user-images.githubusercontent.com/176720/168678611-ab2687bc-4dca-4446-9868-98374b5a37e7.png)

**Comment by Hbouaz** [comment]
Testing this as part of the linked PR "May be fixed by https://github.com/status-im/status-desktop/pull/5788"
