### ISSUE TITLE
adding a contact with chat key should not immediatly open a 1 on 1 chat or should block input

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5767]
# Bug Report

1. copy a user pubkey
2. go to profile -> messaging -> contacts -> request using chat key
3. go to chat section

result: a 1 on 1 with that user is open and it's possible to send messages
expected result: chat input should be blocked until that contact accepts the mutual contact request

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9248&group_by=tests:status_id&group_order=asc
