### ISSUE TITLE
when creating a community #general chat doesn't appear by default

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5771]
# Bug Report

## Steps to reproduce

1. create a community

expected result: #general channel should appear

**Comment by iurimatias** [comment]
this was done in https://github.com/status-im/status-desktop/pull/5619 but seems to not be working or at least there is some sort of delay

**Comment by alaibe** [comment]
I am on latest master: 
![image](https://user-images.githubusercontent.com/491074/168755796-4549f540-7290-4d1e-a91a-d64854db4f10.png)

The channel is here as expected

**Comment by anastasiyaig** [comment]
I can't reproduce it in master
