### ISSUE TITLE
The Communities Settings page is empty if user doesn't join any community

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5773]
# Bug Report

## Description
As we [implemented](https://github.com/status-im/status-desktop/issues/4932) the Communities Settings page, there is a case that appears when a user without communities sees an empty settings page.
## Steps to reproduce
1. Sign up a new user
2. Go to Settings-Advanced and activate Communities
3. Go to Settings - Communities

#### Expected behavior
@iurimatias we do need a design for this case:)
#### Actual behavior
<img width="889" alt="image" src="https://user-images.githubusercontent.com/14942081/168702579-b08e5bcc-c536-4849-93bd-d50c963c087c.png">
### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/5097
- Operating System: macOS 12.3 Beta (21E5227a)

**Comment by borismelnik** [comment]
@elina2015 should be fixed :)
