### ISSUE TITLE
Group chat list members is empty

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5774]
### Description

<img width="1512" alt="Screenshot 2022-05-17 at 09 55 33" src="https://user-images.githubusercontent.com/82375995/168748251-ed6c17ac-ece9-453f-8015-549c7054a347.png">

1. create group chat
2. as admin open members list

**Comment by alaibe** [comment]
Should be fixed by #5717

**Comment by iurimatias** [comment]
sort of expected behaviour since invited member didn't join yet
