### ISSUE TITLE
ScrollView twitches

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#5781]
# Bug Report

## Description

All ScrollViews in the app twitches when flicking over bounds with trackpad (doesn't happen with mouse).

https://user-images.githubusercontent.com/25482501/168774202-b8263f70-8aae-4ac6-9d74-9c3fd33ada40.mov

- Status desktop version: 0.4.0 - 54e2217c9
- Operating System: MacOS 12.3.1

**Comment by MishkaRogachev** [comment]
[Discord discussion](https://discord.com/channels/624205794384281629/697843216048717905/997443503304999013)
