### ISSUE TITLE
The app is crashed after click on 'Send' in Wallet

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5804]
# Bug Report

## Description
The app is crashed after click on 'Send' in Wallet

## Steps to reproduce
1. Sign in and activate Wallet in Settings
2. Go to Wallet and click 'Send'

#### Expected behavior
The app is not crashed and the modal for sending appeared
#### Actual behavior
The app is crashed
### Additional Information
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/14942081/168958667-cf93433c-0f5c-4e20-add1-47e0c2c1bd31.png">

https://user-images.githubusercontent.com/14942081/168958728-e9f818f5-fc95-428f-a06d-762d3667eecb.mov

- Status desktop version: 
commit a51080c17f3b9f68b91a217d3b9d783c6e5e9a56 (HEAD -> master, origin/release/0.5.0, origin/master, origin/HEAD)
Author: Iuri Matias <iuri.matias@gmail.com>
Date:   Tue May 17 17:04:58 2022 -0400

    release(@desktop): 0.5.0 beta

- Operating System: macOS Big Sur 11.6.6 (20G604)

**Comment by anastasiyaig** [comment]
can't reproduce it in `a51080c17f3b9f68b91a217d3b9d783c6e5e9a56` https://ci.status.im/job/status-desktop/job/platforms/job/macos/159/ (release 0.5.0) @elina2015 , please provide more details.

**Comment by saledjenic** [comment]
@elina2015 I was not able to reproduce it in the latest master build.
