### ISSUE TITLE
Slider controls in appearance settings overlap with labels

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5809]
This seems to be new and most likely needs to be fixed in StatusQ.
The labels attached to the slider control conflict with the slider handle.

![Screenshot from 2022-05-18 11-49-43](https://user-images.githubusercontent.com/445106/169011512-d1cbc162-c247-4c88-90fc-ded7a7ed5026.png)

**Comment by MishkaRogachev** [comment]
![image](https://user-images.githubusercontent.com/2522130/169548837-1af501f5-cb76-4897-9981-74053eae2287.png)
Maybe i should implement this component in StatusQ?

**Comment by PascalPrecht** [comment]
If this is a new slider, then yes. Can even make a new variation of `StatusSlider` and then create a wrapper component that knows about the labels. That would enable us to have it for both.
