### ISSUE TITLE
make all onboarding screens layout consistent

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5832]
### Description

see figma

Currently some onboarding screens the buttons jump location, some header titles are not on the same position as others etc.. all of this needs to be made consistent

### Acceptance Criteria

- All onboarding screens have header text, images, action buttons at the same height

**Comment by elina2015** [comment]
@alexandraB99 could you check my comment in [#5889 ](https://github.com/status-im/status-desktop/pull/5889)
