### ISSUE TITLE
review & improve emojihash onboarding screen

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5833]
# Bug Report

## Description

for this screen:
1. create new account
2. generate new keys
3. input username

improvements:
- [x] Review the emoji chain position (follow figma layout)
- [x] Review layout in general (position of button and ring and all components)  the ‘next’ button isn’t centered correctly

**Comment by Hbouaz** [comment]
PR tested and https://ethstatus.testrail.net/index.php?/cases/view/700292 TC Step 3 updated with figma design
