### ISSUE TITLE
Contact requests should support a message

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5846]
### Description

Contact requests should support sending/receiving a message.

### Acceptance Criteria

- [x] profile -> messaging ->  contacts, requests, and blocked users -> send contact request to chat. User should be able to type a message to send as part of the contact request
- [x] user receiving contact request should see the message

**Comment by MishkaRogachev** [comment]
Is there some figma mockups for `SendContactRequestModal`?

**Comment by MishkaRogachev** [comment]
![image](https://user-images.githubusercontent.com/2522130/170478707-b399b81b-e11c-48a3-9441-4544f6e1160a.png)
Is it message field for contact request?

**Comment by MishkaRogachev** [comment]
Should we also be able to send message here? 
![image](https://user-images.githubusercontent.com/2522130/170660044-d928694f-2363-404b-8139-86894b1e75c0.png)

**Comment by MishkaRogachev** [comment]
> Should we also be able to send message here? ![image](https://user-images.githubusercontent.com/2522130/170660044-d928694f-2363-404b-8139-86894b1e75c0.png)

Yes, there are mockups for this: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=2%3A10

**Comment by MishkaRogachev** [comment]
In the current implementation, a contact request is just adding a contact to the user's list. Modified mechanism alredy done in status-go [here](https://github.com/status-im/status-go/pull/2665/files). We can wait for this PR ready and support mutual contact requests in this issue.

**Comment by elina2015** [comment]
@MishkaRogachev hey, I found some issues and added them in https://github.com/status-im/status-desktop/pull/5905. Could you kindly check?
