### ISSUE TITLE
Mentions have very bad color/contrast ratio in dark mode

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5877]
Wanted to mention someone and this is what I saw:

![Screenshot from 2022-05-25 10-04-36](https://user-images.githubusercontent.com/445106/170213000-b8e68a81-809c-4f70-a35e-f049b81035f9.png)

**Comment by PascalPrecht** [comment]
This is only the case inside the chat input, so should be easy to fix:
![Screenshot from 2022-05-25 12-20-38](https://user-images.githubusercontent.com/445106/170240586-02149d03-5236-4b78-864c-98d480f63b86.png)

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9355&group_by=tests:status_id&group_order=asc
