### ISSUE TITLE
Don't render logged in account as not trustworthy in member list

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5883]
The latest memberlist update in community shows the trust level of each member by using a little indicator icon. One of them looks like this:

![Screenshot from 2022-05-25 12-18-13](https://user-images.githubusercontent.com/445106/170241870-e6e95b50-2612-4462-8ab2-3c6c01f3715f.png)

The issue here is that this very member is actually the logged in account (myself).
I should be considered trusted instead.

**Comment by endulab** [comment]
Checked after #5951 and the problem does not exist.

![image](https://user-images.githubusercontent.com/61889657/173785264-a7308e3c-8115-4259-bbfb-4bd9501f8cb8.png)

I am closing the ticket.

**Comment by PascalPrecht** [comment]
Closing as solved
