### ISSUE TITLE
The error 'Login Failed: FAILED TO APPLY MIGRATIONS...' appears when trying to login

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5901]
# Bug Report

## Steps to reproduce
1. Sign up for a new account in your Desktop app
2. Delete the Desktop app
2. Install the app from https://github.com/status-im/status-desktop/pull/5898
3. Enter the correct password and try to log in
#### Expected behavior
The login process is successful
#### Actual behavior
The error 'Login Failed: FAILED TO APPLY MIGRATIONS...' appears
### Additional Information
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/14942081/170627851-86de43ff-1587-4141-ac46-0b39b061e98f.png">

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/14942081/170627885-ce65730d-2b95-406f-8a65-0d42204e6d37.png">

- Status desktop version: https://github.com/status-im/status-desktop/pull/5898
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
can't replicate
