### ISSUE TITLE
Update group chat creation view: admin shown in left with a `king pill` and without `X` option

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#5904]
### Description
When a user starts creating a new 1 on 1 or ad-hoc group chat, they should be shown at the beginning (left) of the add user pill input field, using the 'king pill'. In this state there is no "X" on the 'king pill' because it doesn't make any sense for a user to remove themself from a group chat before they have even started it.

**Requires:**
* [ ] Update `StatusTagSelector` component: https://github.com/status-im/StatusQ/issues/694
* [ ] Needed uptades in `desktop`.

**Comment by iurimatias** [comment]
we decided not to do this
