### ISSUE TITLE
Last item in the `StatusTagSelector` drop-down  is out of boundaries

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#5907]
### Description
Wherever the `StatusTagSelector` is used in `desktop`, the last item in the drop-down is out of boundaries. (It is now used at least in Create Chat (1:1 and group)).

![Screenshot 2022-05-27 at 15 41 38](https://user-images.githubusercontent.com/97019400/170714549-e7b82419-13ad-4d9f-93fc-b98c82f7fb20.png)

![Screenshot 2022-05-27 at 15 49 56](https://user-images.githubusercontent.com/97019400/170714578-e93cd30b-4af3-4efc-b796-a46425635e55.png)

**Comment by borismelnik** [comment]
![Image](https://user-images.githubusercontent.com/82511785/170974381-e657c838-e2ad-41cf-b9d1-e30554b11a1e.png)

looks like fixed in master? @noeliaSD

**Comment by noeliaSD** [comment]
> 

Yes! I cannot reproduce it anymore in master.
