### ISSUE TITLE
Various image croppers and their bugs

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#5921]
# Bug Report

First of all, there's currently a mess of components for cropping images.
There are various implementations of the cropper, but there should be just reusable one.

And I also noticed these bugs:

1. During onboarding, after selecting the image:
    * [x] The IdentIcon shows the full image instead of cropped one
    * [ ] The image is not saved (it dissapears after finishing the onboarding) [ Opened a separate Issue: https://github.com/status-im/status-desktop/issues/6861]
2. There's no way to remove the profile/community image, only replacing is available
3. The designs doesn't have the behavior of image uploading failure - not a bug
4. There's a bunch of leftover unused files, e.g.:
   - `UploadProfilePicModal`
   - `ChangeProfilePicModal`
   - `EditCroppedImagePanel`
5. There're also croppers coming from https://github.com/status-im/status-desktop/pull/5437

**Comment by elina2015** [comment]
@igor-sirotin hey, could you kindly add a pull request for this task? Thanks!
