### ISSUE TITLE
Enable some features and remove their experiment toggles

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5922]
### Description

- [x] Communities should be enabled by default, and the toggled should be removed
- [x] Activity Center should be enabled by default, and the toggled should be removed
- [ ] Community History Archive Protocol should enabled by default, and the toggle should be removed (note: needs confirmation from @PascalPrecht )

**Comment by PascalPrecht** [comment]
As mentioned offline, I'd suggest we run the Community History Archive Protocol for a while before we turn it on by default.

**Comment by elina2015** [comment]
@borismelnik could you help me to find a pull request for this task?
