### ISSUE TITLE
Scrolling is not shown for Sent and Received Pending Contact Requests

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5925]
# Bug Report

## Description
User cannot see all Sent and Received Pending Contact Requests because the scrolling of the lists is not shown

## Steps to reproduce
1. Receive 8 Contact requests
2. Send 5 Contact Requests
3. Go to Settings - Messaging - Contacts - Pending

#### Expected behavior
The additional lists scrolling are shown for Sent and Received Contact Requests for providing the information that there are more requests to see
#### Actual behavior
The additional lists scrolling are NOT shown for Sent and Received Contact Requests and user don't see that there are more requests on the screen
### Additional Information
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/14942081/171078272-6fa50465-7156-4381-9e2a-bd7ed9f5e194.png">

Status desktop version: [Build #2137 (May 30, 2022, 9:02:25 AM)](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2137/)
Operating System: macOS Monterey 12.3 Beta (21E5227a) M1

**Comment by endulab** [comment]
FYI @alexandraB99

**Comment by elina2015** [comment]
Need to discuss with John

**Comment by iurimatias** [comment]
this has been fixed in the meanwhile
