### ISSUE TITLE
The Contact search doesn't work by chat key

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5928]
# Bug Report
## Steps to reproduce
1. Copy a chat key of your contact, pending or Blocked contact (for example, zQ3shpaw79hkMgwvaoDvXo3613XrKX8xrGjUemh8iTfNCWcj3)
2. Go to Settings - Messaging - Contacts and enter the copied chat key to the search contacts field
3. Check Contacts, Blocked and Pending contacts

#### Expected behavior
The contact with copied chat key is found
#### Actual behavior
Nothing found
### Additional Information

Status desktop version: [Build #2137 (May 30, 2022, 9:02:25 AM)](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2137/)
Operating System: macOS Monterey 12.3 Beta (21E5227a) M1

**Comment by micieslak** [comment]
@elina2015 I cannot reproduce. It works as intended for me. So maybe it's already fixed or I'm missing something...

**Comment by anastasiyaig** [comment]
@micieslak i can reproduce as described, contacts tab search is not working

<img width="1594" alt="Screenshot 2022-07-21 at 13 18 31" src="https://user-images.githubusercontent.com/82375995/180191007-90a8a72e-c4bb-4bc1-b3b1-8a8060052b68.png">
