### ISSUE TITLE
It's possible to save a URL as a Nickname

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5931]
# Bug Report

## Steps to reproduce
1. Open a profile and click on 'Nickname'
2. In the Nickname field enter '_____________________' and save
3. Edit the nickname again, select the text in the field, and past 'https://www.google.com/'
4. Click 'Done'

#### Expected behavior
The error is shown and the button 'Done' is not active OR 'Done is active' but after clicking the nickname changes are not saved.
#### Actual behavior
The URL is saved as a nickname
### Additional Information
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/14942081/171092197-34d5ca45-220d-43e2-9601-3f785d70c247.png">

Status desktop version: [Build #2137 (May 30, 2022, 9:02:25 AM)](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2137/)
Operating System: macOS Monterey 12.3 Beta (21E5227a) M1

**Comment by iurimatias** [comment]
merged with https://github.com/status-im/status-desktop/issues/5930
