### ISSUE TITLE
Untrustworthy mark is shown for the mutual contact and for myself in the list of community members

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5932]
# Bug Report

## Steps to reproduce
1. Add a mutual contact
2. Create a community and add there your mutual contact
3. Open the created community and check the members' list

#### Expected behavior
Untrustworthy mark is NOT shown for the mutual contact and for myself in the list of community members
#### Actual behavior
Untrustworthy mark is shown for the mutual contact and for myself in the list of community members
### Additional Information
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/14942081/171093830-4a98811d-478f-4174-9818-7b3b66824b03.png">

Status desktop version: [Build #2137 (May 30, 2022, 9:02:25 AM)](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2137/)
Operating System: macOS Monterey 12.3 Beta (21E5227a) M1

**Comment by iurimatias** [comment]
should be reviewed after https://github.com/status-im/status-desktop/pull/5558 is merged

**Comment by iurimatias** [comment]
this is not happening anymore, and should be fixed after the contact verification PR
