### ISSUE TITLE
Nothing happens after clicking on any notification

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5935]
# Bug Report

## Steps to reproduce
1. Switch on the notifications
2. get some messages to 1-1 chat
3. Click on the appeared notifications

#### Expected behavior
The chat is opened after clicking on the notification
#### Actual behavior
Nothing happens
### Additional Information
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/14942081/171095859-6b57ea3e-f00f-4e63-b4e2-f159d638fff5.png">

Status desktop version: [Build #2137 (May 30, 2022, 9:02:25 AM)](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2137/)
Operating System: macOS Monterey 12.3 Beta (21E5227a) M1

**Comment by elina2015** [comment]
Tested and Approved

**Comment by iurimatias** [comment]
closing due a github issue
