### ISSUE TITLE
Unable to join already joined community

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5966]
I know the title sounds weird but I couldn't come up with a better short description. Alright so here's what's happening:

1. I have an account which happens to be the owner of 3 different communities
2. For various reasons had to wipe my `Status` folder, so I re-imported the seedphrase of that same account
3. After starting the app, I go to Settings -> Advanced -> Enable communities
4. I then head to the chat view and see if I can find a way to restore the communities my account is an owner of
5. The first thing I notice: 1 out of 3 communities seems to be listed in the communities modal:

There's a few things off here: 

a) there's only one community although I was part [and even owner] of  more, but okay **maybe it's just a list of communities that desktop app knows unrelated to whether or not I was/am part of them** 
b) the search input seems off in the modal

![Screenshot from 2022-06-02 10-57-53](https://user-images.githubusercontent.com/445106/171594766-d8675710-f9fc-4021-b409-afd6b782ca88.png)

Anyways, those were side notes, here's the real issue:

1. I know I was part of "Misaka community 3", in fact I'm the admin/owner of it. So I click on it which gives me a screen to join the community:
![Screenshot from 2022-06-02 11-02-58](https://user-images.githubusercontent.com/445106/171595483-4ddbd2fc-b4b7-4a41-bfbc-1fb80f97bcc1.png)

So I think, heck yea I want to join **my own** community, so I hit "join" and nothing happens.

Looking at the logs, it turns out that there's an error:
```
DBG 2022-06-02 10:46:06.803+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=85630 file=core.nim:20 rpc_method=wakuext_requestToJoinCommunity
ERR 2022-06-02 10:46:06.805+02:00 rpc response error                         topics="rpc" tid=85630 file=core.nim:29 err="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-3
2000, message:already a member ]\n"                                                                                                                                                            
ERR 2022-06-02 10:46:06.805+02:00 Error requesting to join the community     topics="community-service" tid=85630 file=service.nim:478 msg="\nstatus-go error [methodName:wakuext_requestToJoin
Community, code:-32000, message:already a member ]\n" communityId=0x020219e273da612c2532564e5927c341af00a3336195304313c7912b6ccd40a56a ensName= 
```
What happens here is that there's a `requestToJoin` the community (kinda implying that desktop doesn't already know that I'm part of that community), however that request fails because `status-go` first checks if the logged in user is already part of the community (which is true).

**So all in all there's a few things to be figured out**:

1. When I import an account which happened to be part of communities (whether owner or not), do we expect those communities to show up after import - yes or no (I would expect yes of course)
2. As we can see, 1) is not the case at the moment. There are no communities in the sidebar, so this might be the first thing to look into
3. Contradictory, we **do** see at least one of the communities in the communities modal, so it seems desktop  **is aware** at least to some degree, however, apparently only as much aware that such a community exists, not necessarily that I'm part of it (otherwise it wouldn't perform a `requestToJoin` [either that, or, if the listed communities are all there for possible request to join, the community shouldn't be listed in the modal])
4. The `requestToJoin` fails because status-go knows that I'm a member of that community. This implies that all the information is there, but apparently not in desktop. This should be streamlined.

**Comment by jrainville** [comment]
I think this issue is now a non-issue, because when the sync gets the communities, we "auto-join" the ones we were member of.
The feature is a bit bugged right now, but this PR fixes the same crash https://github.com/status-im/status-desktop/pull/6421
For example, if you import this seed phrase
```
music race alert orphan print dry trumpet journey rival tower aerobic hammer
```
you should get a couple of communities back, some of them being ones you're owner of.

Anyway, like you said, it's a bit flaky, because it happens in the background. It's all triggered by status-go , so we don't have a lot of control over it.

**Comment by jrainville** [comment]
Yeah the sync is hella finnicky. This time I only managed to recover two communitie, but here you can see that I am the owner and the other is the StatusCCs community

![Image](https://user-images.githubusercontent.com/11926403/178798182-508b2daa-ae9a-41c0-91ff-f81a6b6bfa32.png)

**Comment by PascalPrecht** [comment]
With the communities modal gone, do we expect previously owned/joined communities to show up in the communities portal (similarly to how they showed up in the modal)?

**Comment by PascalPrecht** [comment]
I guess this issue can be closed as we no longer have the "Communities" modal.
We should however look into why previously joined/owned communities are not fully recovered.
