### ISSUE TITLE
Seed phrase words are cut

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5967]
### Description

<img width="1541" alt="Screenshot 2022-06-02 at 12 18 42" src="https://user-images.githubusercontent.com/82375995/171598697-c836c554-d239-4006-8848-402327edf775.png">

**version**: master `046aa365655ab65e67fbf5beff0d36d713d9df59`

**Comment by alexandraB99** [comment]
fixed in StatusQ https://github.com/status-im/StatusQ/pull/716
