### ISSUE TITLE
Display name field is off when entering a value

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5968]
### Description

<img width="1541" alt="Screenshot 2022-06-02 at 12 18 59" src="https://user-images.githubusercontent.com/82375995/171599115-7f48695e-0faf-4b43-a99a-e7eedb226dfc.png">

<img width="1541" alt="Screenshot 2022-06-02 at 12 19 03" src="https://user-images.githubusercontent.com/82375995/171599137-30958783-44ae-4d87-bd5a-23c8a2eb6fc1.png">

**version**: master `046aa365655ab65e67fbf5beff0d36d713d9df59`

**Comment by iurimatias** [comment]
ahs been fixed in the meanwhile
