### ISSUE TITLE
App crashes when importing seedphrase

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5970]
Starting with a blank slate, using Status Desktop latest `master` (https://github.com/status-im/status-desktop/commit/046aa365655ab65e67fbf5beff0d36d713d9df59)` and status-go latest `develop` (https://github.com/status-im/status-go/commit/a471fed6a64e01a1aba8d925377fba045a5aa9f9), and a removed `Status` folder, when importing a seed, the application crashes with the following error after password finalization:

```
ERR 2022-06-02 12:22:50.038+02:00 rpc response error                         topics="rpc" tid=233020 file=core.nim:29 err="\nstatus-go error [methodName:multiaccounts_storeIdentityImage, code
:-32000, message:open : no such file or directory ]\n"                                                                                                                                         
ERR 2022-06-02 12:22:50.038+02:00 error:                                     topics="profile-service" tid=233020 file=service.nim:53 procName=storeIdentityImage errName=ValueError errDesription="\nstatus-go error [methodName:multiaccounts_storeIdentityImage, code:-32000, message:open : no such file or directory ]\n"  
```

**Comment by iurimatias** [comment]
@anastasiyaig could you check if you can replicate this plz

**Comment by PascalPrecht** [comment]
Can no longer reproduce this either. Happy to close this.
