### ISSUE TITLE
Add "Welcome to your Community" and "Back up community key" buttons to community overview

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5978]
### Description

see figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=3413%3A380348

1. create a community
2. click manage community and go to overview\

![Screen Shot 2022-06-02 at 1 27 04 PM](https://user-images.githubusercontent.com/176720/171688626-f70cecb1-f18d-48d6-bef6-db293fcc06ac.png)

### Acceptance Criteria

- [x] add "Welcome to your community", clicking the button should open the invite modal
- [x] add "Back up community key", clicking the button open the back up modal
- [x] add "Airdrop tokens", the code should be commented out

**Comment by elina2015** [comment]
Tested and Approved
