### ISSUE TITLE
Community Permissions Settings UI

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5981]
### Description

figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481538

The goal of this task is to implement the UI of the permissions tab. This should use a mock backend for now. (including for tokens, collectibles, etc..)

It will be separated in different subtasks:

- [x] https://github.com/status-im/status-desktop/issues/6036
- [x] https://github.com/status-im/status-desktop/issues/6037
- [x] https://github.com/status-im/status-desktop/issues/6038
- [x] https://github.com/status-im/status-desktop/issues/6039
- [x] https://github.com/status-im/status-desktop/issues/6337
- [x] https://github.com/status-im/status-desktop/issues/7158
- [x] https://github.com/status-im/status-desktop/issues/6338
- [x] https://github.com/status-im/status-desktop/issues/6339
- [x] https://github.com/status-im/status-desktop/issues/6040
- [x] https://github.com/status-im/status-desktop/issues/6041 
- [x] https://github.com/status-im/status-desktop/issues/6042

Needed `StatusQ` components update to fit the specific `Community Permissions Settings` designs:
- [x] https://github.com/status-im/StatusQ/issues/724 
- [x] https://github.com/status-im/StatusQ/issues/753

### Acceptance Criteria

- Community -> manage community should now have the "Permissions" tab
- Experimental features settings should have a new toggle called "Community Permisions", only if this is toggled should any permissions related UI components be displayed
- New permissions form
- New permissions form - select token from a list, and amount. (note: "Mint token" and "Import existing token" options should not do anything for the moment or be commented out in the code)
- New permissions form - select a collectible from a list
- New permissions form - select ENS
- New permissions form - select "is allowed to"
- New permissions form - select "in" (note: ideally in this case, it should use the actual categories and channels from the community and not mocked data)

**Comment by noeliaSD** [comment]
It will be separated in different subtasks:
- [ ] `Welcome` page will include adding the new `Permissions` tab and the first permissions page when there are not permissions created yet (https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2992%3A367890)
- [ ] `New permission` page will include the complete layout and navigation between the welcome page and the current one (https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A480020)
- [ ] `Who holds` Dropdown component will include three tabs (token, collectible, ens), dropdown detailed view (list of tokens, collectives...) and the `and/or` dropdown (https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A484670 and https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A482661)
- [ ] `Who holds` dropdowns integration with `new permission page` and add needid logic (https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481555)
- [ ] `Is allowed to` dropdown component and integration with the page (https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481558)
- [ ] `In`dropdown component and integration with the page (https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481559)
- [ ] `Permissions created` page and logic fro `Create permission` button and `Add permission` button (https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A484715)

**Comment by noeliaSD** [comment]
All subtasks listed have been integrated. New related tasks for the feature have been separaterly created so we can close this task.
