### ISSUE TITLE
The field of Communities search is placed very close to the edge

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5988]
# Bug Report

## Steps to reproduce
1. Activate Communities in Settings-Advanced
2. Go to Chat - Communities 
3. Check the 'Search communities or topics' field

#### Expected behavior
The search field is placed correctly
#### Actual behavior
The 'Search communities or topics' field appears very close to the left edge
### Additional Information
<img width="889" alt="image" src="https://user-images.githubusercontent.com/14942081/171762253-78fde2a3-d13f-4a8d-bbe9-c2daa2b2502d.png">

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2151/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
closing in favour of https://github.com/status-im/status-desktop/issues/6002
