### ISSUE TITLE
The Communities page doesn't look good if no one community found

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5989]
# Bug Report

## Steps to reproduce
1. Activate Communities in Settings-Advanced
2. Go to Chat - Communities
3. Enter some search request in the search field like '---' for finding nothing
4. Check the page

#### Expected behavior
There is a placeholder 'No communities found' or something like that is shown.
#### Actual behavior
The Communities page doesn't look good if no one community found - there are only the first letters of communities are shown (if a user has some communities) OR the page is just empty if a user is a new one.

### Additional Information
<img width="901" alt="image" src="https://user-images.githubusercontent.com/14942081/171762493-7dd9389f-945a-41b7-94e3-8871fce68b58.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/14942081/171763013-e180f055-f612-46f5-902f-95e158206207.png">

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2151/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
this is a 'wont-fix' because this modal will soon disapear because of the communities portal
