### ISSUE TITLE
Add new model properties needed to render new community information / settings in CommunityPortal page 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#5995]
New community card design has been implemented following this task: https://github.com/status-im/StatusQ/issues/692

In order to render more community information / settings, the new card expects the following properties:
- `banner`
- `activeUsers`
- `communityColor`
- `isPrivate` 
- `tokenLogo`

Steps:
- Add the needed properties into the `src/app/modules/main/communities/models/curated_community_item.nim`
- Implement the needed logic in `status-go`
- Update `ui/app/AppLayouts/CommunitiesPortal/CommunitiesPortalLayout.qml` adding the new model properties in `StatusCommunityCard`.

**Comment by micieslak** [comment]
It's almost covered by https://github.com/status-im/status-desktop/pull/7941. UI looks complete but backend needs some further development (e.g. `activeUsers` implementation in status-go).

**Comment by osmaczko** [comment]
`banner` and `communityColor` is done
`isPrivate` and `tokenLogo` need to wait for token-gated communities implementation
`activeUsers` this needs to be implemented in status-go first
