### ISSUE TITLE
Edit Channel context menu missing for #general channel only

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6003]
# Bug Report

## Steps to reproduce

1. create a community
2. create a category and some channels
3. right click the #general channel

#### Expected behavior

Should see the "Edit Channel" Option

![Screen Shot 2022-06-03 at 1 56 35 PM](https://user-images.githubusercontent.com/176720/171920251-cf31b9b5-dcef-4214-95c4-36c6e18d6eaa.png)

#### Actual behavior

"Edit Channel" Option is missing

![Screen Shot 2022-06-03 at 1 56 31 PM](https://user-images.githubusercontent.com/176720/171920242-e36bf29d-0233-4126-abde-80c67d3ee813.png)

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9482&group_by=tests:status_id&group_order=asc
