### ISSUE TITLE
posting gifs should not display the url

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6005]
### Description

1. select a gif and send

result: message has the link to the gif
expected result: message should not contain the link

![Screen Shot 2022-06-03 at 4 45 50 PM](https://user-images.githubusercontent.com/176720/171949963-a800cd08-9a18-4a1a-986a-bbb959fbed36.png)

**Comment by elina2015** [comment]
@borismelnik please check found issues in https://github.com/status-im/status-desktop/pull/6014

**Comment by elina2015** [comment]
Added a separate ticket [The GIF dialog doesn't disappear after sending a GIF #6083](https://github.com/status-im/status-desktop/issues/6083) - found on master too.
