### ISSUE TITLE
Can't login to a dapp

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6006]
### Description

1. enable wallet
2. enable browser
3. open cryptokitties.io
4. login to the dapp
5. sign a message to the dapp

As result, the screen below can't be bypassed

<img width="1468" alt="Screenshot 2022-06-06 at 15 17 46" src="https://user-images.githubusercontent.com/82375995/172159610-1a7b6888-248e-48ba-ae64-dc7a3260a1b2.png">

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6775
