### ISSUE TITLE
The notifications popup doesn't look like on the onboarding image

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6017]
# Bug Report

## Steps to reproduce
1. Install the app
2. Open the app
3. Check the appeared system popup for Status notifications

#### Expected behavior
1. The Allow button doesn't overlap the text
2. The popup doesn't differ from the Notification popup image on thee 1st onboarding screen
<img width="494" alt="image" src="https://user-images.githubusercontent.com/14942081/172540450-04cbbf6b-cc9c-4e2f-8680-ae248aa7547f.png">

#### Actual behavior
1. The Allow button overlaps the text
2. The popup differs from the Notification popup image on thee 1st onboarding screen
<img width="386" alt="image" src="https://user-images.githubusercontent.com/14942081/172540418-c68b89c4-631d-4012-9edd-ca753e16706a.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2163/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
This UI is from macos, we can't fix it
