### ISSUE TITLE
The checkboxes for Terms and Acknowledge don't look clickable on the onboarding screen

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6018]
# Bug Report

## Steps to reproduce
1. Install the app
2. Go to Sign up for a new account
3. Hover over the checkboxes on the onboarding screen 'Before you get started...'

#### Expected behavior
The cursor changes its state to 'hand' for showing to the user that it's clickable

#### Actual behavior
The cursor doesn't change its state to 'hand' for showing to the user that it's clickable
### Additional Information
<img width="719" alt="image" src="https://user-images.githubusercontent.com/14942081/172542166-54b59f1f-888b-4d59-b036-25a5ea6151da.png">

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2163/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
The correct behaviour seems to show the pointer https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_checkbox
