### ISSUE TITLE
The button 'Get Started' should be 'Get started'

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6019]
# Bug Report

## Steps to reproduce
1. Install the app
2. Go to create a new account
3. Check the button 'Get Started' on the screen 'Before you get started'

#### Expected behavior
The button should be - ' Get started'
Design:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/14942081/172542560-d3d30fa0-1970-43ab-b827-8f3f38987f30.png">

#### Actual behavior
The button differs from Design (there is a capital 'S' instead of 's') :
<img width="602" alt="image" src="https://user-images.githubusercontent.com/14942081/172542636-72467974-4d99-4c26-a190-b6a3676ea4ed.png">

### Additional Information

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2163/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
fixed in latest master
