### ISSUE TITLE
The app is not save the size of its window after switching between apps

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6025]
# Bug Report

## Steps to reproduce
1. Sign in and maximize the app window
2. Click on the Discord icon app
3. Click on the Status app icon

#### Expected behavior
The window saved its previous state and its maximized
#### Actual behavior
The window of Status app is minimized
### Additional Information

https://user-images.githubusercontent.com/14942081/172550249-d0970b38-bd42-408f-ade0-96e3bf55fcbc.mov

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2163/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
this is the expected behaviour on a mac
