### ISSUE TITLE
Adjust modals heights

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#6027]
From here: https://github.com/status-im/status-desktop/pull/5884#issuecomment-1148970710

![image](https://user-images.githubusercontent.com/2522130/172581499-26a69088-265b-4546-81cb-a78be525f01d.png)

Modal should go to the full height of the window (but with a 64px margin top and bottom) if the window isn't tall enough to display the modal content without scrolling (which will almost always be the case with this modal, unless a user is using a monitor in portrait mode or something like that).

This same behaviour should apply to most tall modals in status desktop

**Comment by MishkaRogachev** [comment]
@anastasiyaig @John-44 i've created new issue for modal heights, names of the fields are already done by Patryk

**Comment by MishkaRogachev** [comment]
After first look it seems that I need to change the sizing mechanism of StatusQ StatusModal mechanism. @borismelnik @Khushboo-dev-cpp git log says you are the last who worked with StatusModal, can you advise me - should i implement it in StatusModel or inherit component on status-desktop level?

**Comment by Khushboo-dev-cpp** [comment]
Hey @MishkaRogachev I think this should be implemented generically within the StatusModal itself. Wdyt?

**Comment by MishkaRogachev** [comment]
Also i should implement StatusStackModal and replace with it nested modals like color picker from create community dialog. 
https://discord.com/channels/624205794384281629/730410574428504166/984791107974094879

**Comment by osmaczko** [comment]
@MishkaRogachev this is the same as https://github.com/status-im/status-desktop/issues/6049 (already done)

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev this is the same as #6049 (already done)

Yes and no)
In this PR i've replaced nested modals with StackView-like component and modified Global.openPopup to resize modals within main application window. But i've missed bottom margin can be different from top one. Created hotfix for that : https://github.com/status-im/status-desktop/pull/6248/files
