### ISSUE TITLE
Community creation fails when `ñ` char is present in the title and the length is 30 chars

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#6032]
### Description
`ñ` char is considered as len 2 in some point and then the length of the community title exceeds the allowed one and it is not created.

Error logged:
`````
DBG 2022-06-08 17:44:38.028+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=849155 file=core.nim:20 rpc_method=wakuext_createCommunity
ERR 2022-06-08 17:44:38.030+02:00 rpc response error                         topics="rpc" tid=849155 file=core.nim:29 err="\nstatus-go error [methodName:wakuext_createCommunity, code:-32000, message:create-community: invalid name ]\n"
ERR 2022-06-08 17:44:38.030+02:00 Error creating community                   topics="community-service" tid=849155 file=service.nim:602 msg="\nstatus-go error [methodName:wakuext_createCommunity, code:-32000, message:create-community: invalid name ]\n"
``````

**Comment by richard-ramos** [comment]
This is because when dealing with utf8 characters we need to count runes instead of using length.
for example:

```go
import "fmt"
import "unicode/utf8"
fmt.Println("ñ", len("ñ"), utf8.RuneCountInString("ñ"))  // ñ,  2, 1
fmt.Println("世界", len("世界"), utf8.RuneCountInString("世界"))  // 世界,  6, 2
```

```nim
import std/unicode
echo "ñ ", "ñ".len, ",", "ñ".runeLen # ñ 2,1
echo "世界 ", "世界".len, ",", "世界".runeLen # 世界 6,2
```

We need to fix status-go and/or desktop to validate the length of a string with rune count functions in any place we use normal string lengths

**Comment by iurimatias** [comment]
confirmed: we wouldn't be supporting this due to impersonation risks

**Comment by felicio** [comment]
@iurimatias, please

> the specs specify

Are you referring to https://github.com/status-im/feature-specs/pull/42?

> we wouldn't be supporting this due to impersonation risks

How do characters like these enable that and alphanumeric ones alone don't? For those risks I understood we're implementing the mechanisms mentioned in https://github.com/status-im/feature-specs/pull/42#discussion_r764177845.

Finally, will this limitation apply to display names of other entities like the community or channel, and to description as mention on the meeting about link sharing? Are you tracking it somewhere to address that?
