### ISSUE TITLE
[Community Permissions] `In`dropdown component and integration with the page 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#6041]
### Description
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481559

Acceptance Criteria:
- This component should be viewable and testable in storybook

**Comment by noeliaSD** [comment]
Feature branch here: https://github.com/status-im/status-desktop/tree/feat/issue-5981

**Comment by micieslak** [comment]
![Screenshot from 2022-09-23 11-32-32](https://user-images.githubusercontent.com/20650004/191932386-a75f9443-46a7-474a-991c-6d7e22fb7180.png)

@John-44 I have several doubts about this design. The community on top ("Socs" in our example) is always the current community and the radio box is exclusive with all checkboxes below which represent channels within that community? What are those section labels "Discussion" and "Support", channel categories? What should be scrollable, only channels list or community name as well?
