### ISSUE TITLE
The list of users appears very close to the bottom edge of the screen

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6054]
# Bug Report

## Steps to reproduce
1. Sign in and sign out
2. Launch the app
3. Click on the arrow near the user name

#### Expected behavior
The list appears not very close to the bottom edge of the screen
<img width="743" alt="image" src="https://user-images.githubusercontent.com/14942081/172961241-dcc9f298-5ed9-4762-a299-842c23f848ea.png">
Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1023%3A298171
#### Actual behavior
The list appears very close to the bottom edge of the screen
<img width="688" alt="image" src="https://user-images.githubusercontent.com/14942081/172961203-41d33525-8564-4d6c-819d-784fe1712117.png">

### Additional Information

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2169/
Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6822
