### ISSUE TITLE
The asset name is overlapped by an arrow

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6056]
# Bug Report

## Steps to reproduce
1. Open 1-1 chat and Request a transaction
2. On the second screen of the request select an Asset with a long name (for example, ABYSS)

#### Expected behavior
The name of the asset is not overlapped by the list arrow
#### Actual behavior
The name of the asset is overlapped by the list arrow
<img width="659" alt="image" src="https://user-images.githubusercontent.com/14942081/172965668-4bf41172-3541-41e9-baa3-d7d49403efbe.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/14942081/172965717-71944278-f0ab-48aa-9771-43a8b1e60775.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/14942081/172965754-32cba919-6d56-4749-af1a-99d740ee6642.png">

### Additional Information
Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2169/
Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by elina2015** [comment]
@Khushboo-dev-cpp I checked in the latest [master ](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2316/)and the bug is still reproduced:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/14942081/178609692-172563c7-de26-4af7-8195-46c8467434a3.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/14942081/178609803-0490c283-5e3b-45a5-9fba-a2ac47113f6c.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/14942081/178609839-1d71eddf-72ad-48b8-807a-d3613ded0ef2.png">
Could you kindly check?

**Comment by Khushboo-dev-cpp** [comment]
@elina2015 I can see it now! working on it :)
