### ISSUE TITLE
Create a unified Authentication component

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#6097]
We have several procedures in the application which require additional authentication, e.g.:
- Change password
- Add wallet account
- Sync new device

Currently all of those procedures have their own password input to authenticate.

<img width="1083" alt="Снимок экрана 2022-06-15 в 20 09 39" src="https://user-images.githubusercontent.com/25482501/173887847-12411b01-297d-440f-83d0-c473e2cac73b.png">

But there should be a unique workflow component for that, which would consider different methods of authentications, such as:
- password
- biometric (technically, this is when the password is stored in a secure enclave, and the OS biometrics release the password)
- keycard + pin
- keycard + biometric (technically, this is when the pin is stored in a secure enclave, and the OS biometrics release the pin)

This component should be reused wherever it's needed.

It could probably be an Embeddable component, or a standalone Popup, depending on the way it's used.
But it seems we don't actually have a defined designs for that.
But `Sync New Device` designs seems to have to closest variant.

Design links:
- [Sync new device](https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1592%3A128969)
- [Change Password](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2203%3A237514)
- [Add Wallet Account](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=5248%3A188817)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/7205
