### ISSUE TITLE
Enable by default community history archive

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6098]
[ ] Remove "Community History Archive Protocol" toggle from advanced and enable it by default
When creating a community, the checkbox is checked by default for history archive

Acceptance Criteria:
- Settings -> advanced no longer has Community History Archive Protocol
- New communities created have by default history archive on, but it can still be changed
- Bittorrent is being used for long term history fetching (this can be checked with a tool)

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9546&group_by=tests:status_id&group_order=asc

**Comment by iurimatias** [comment]
this issue was on a unclear state due to being `Done` in the board. Reopening since the PR has not been merged yet.
