### ISSUE TITLE
Two loaders are shown infinitely in the public chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6103]
# Bug Report

## Steps to reproduce
1. Sign in and open any public chat (for example, '#status')
2. Check the page for loaders

#### Expected behavior
The loader should be shown only while loading the page and it should be only one loader
#### Actual behavior
Two loaders are shown before the content s shown and after that 
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/14942081/173989170-c86b8763-0ab1-4790-a6ae-ae740d499d2f.png">
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/14942081/173989208-fd382866-318b-46f1-8d93-9f10114a36ea.png">

### Additional Information

- Status desktop version: latest master https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2197/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
cant replicate anymore
