### ISSUE TITLE
Members, Menu and search button in toolbar are bigger than activity center button

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6120]
The following screenshot shows the member button being active which reveals the actual size of the button:

![Screenshot from 2022-06-17 16-39-01](https://user-images.githubusercontent.com/445106/174320582-64d3cf51-0be7-4e0c-8c88-e89919e393aa.png)

The search button has the same size.
The activity center button (not highlighted in this screenshot) is smaller (and has the correct size).

I think the other buttons need to be smaller.

**Comment by PascalPrecht** [comment]
This seems to have been addressed in #6216, however it looks like the activity button size has been increased, instead of making the other ones smaller.

Discussing this with @noeliaSD

**Comment by iurimatias** [comment]
should be fixed in #6350
