### ISSUE TITLE
"Add Contact" should be replaced with "Send Contact Request"

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6125]
figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1838%3A364692

- [x] "Add Contact" should be replaced with "Send Contact Request"
- [x] Send Contact Request should open the send contact request modal built in https://github.com/status-im/status-desktop/issues/5846

**Comment by MishkaRogachev** [comment]
> * [x]  Send Contact Request should open the send contact request modal built in [Contact requests should support a message #5846](https://github.com/status-im/status-desktop/issues/5846)

Profile send contact request modal is quite different but i planning to unify them in https://github.com/status-im/status-desktop/issues/6027
