### ISSUE TITLE
No visual indicator that community has received membership request

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6140]
After receiving a membership request for a community my account owns, I did get a sound but no visual indication. Without the sound I wouldn't know that I have received a request.

The chat view looks like this:

![Screenshot from 2022-06-19 10-54-06](https://user-images.githubusercontent.com/445106/174473306-7c2fe8b6-408d-44ff-9622-3fdd6802e0db.png)

^ I would at least expect a badge icon indicator in the community tab button on the left hand side.
Even better, the "membershipt request" button we used to have

However, I know i have a request because I sent it myself using a second desktop instance, so I go to the community view:
![Screenshot from 2022-06-19 10-56-31](https://user-images.githubusercontent.com/445106/174473409-262f4f57-2559-4f55-878f-42d72a50611b.png)

^ Also here, no visual indicator

Only after going to "members" I see a notification:
![Screenshot from 2022-06-19 10-50-18](https://user-images.githubusercontent.com/445106/174473431-d9c37e7d-4cc5-4a0c-869d-c84b977418a7.png)

Unfortunately it doesn't work but that's logged here: https://github.com/status-im/status-desktop/issues/6141

**Comment by PascalPrecht** [comment]
Playing around with this further, essentially there are two things missing:

1. A badge indicator in the app navbar for the community, indicating that there's **something** in the community
2. A badge indicator in the "members" item in the community settings view, in case it was the last active view (like in my case)
3. The membership request item does show up in the general community view, so this is fine

**Comment by iurimatias** [comment]
should be fixed with new work on the join workflow and activity center
