### ISSUE TITLE
Can't accept community membership requests anymore

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6141]
I have an account with a community and received a request to join.
I want to accept the request.

The first issue: from the normal  chat view, there's no indication that I indeed have received a membership request (https://github.com/status-im/status-desktop/issues/6140)

But because I sent the request myself using a second desktop instance, I know there has to be one. So I go to the community view, and navigate to "members" where I find the notification:
![Screenshot from 2022-06-19 10-50-18](https://user-images.githubusercontent.com/445106/174473454-366c439b-97ae-4593-9ee8-cf1241035a44.png)

Unfortunately, clicking that one doesn't do anything. So I can't accept the request :( 

Seems this is easy to fix. There's a QML error:
```
qrc:/app/AppLayouts/Chat/views/CommunitySettingsView.qml: ReferenceError: membershipRequestPopup is not defined 
```

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9536&group_by=tests:status_id&group_order=asc
