### ISSUE TITLE
Cannot send a contact request from profile

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#6145]
# Bug Report

Right client on a message, click on view profile then click on send contact request

error in log:
ERR 2022-06-20 09:43:35.699+02:00 rpc response error                         topics="rpc" tid=49153 file=core.nim:29 err="\nstatus-go error [methodName:wakuext_sendContactRequest, code:-32000, message:send-contact-request: invalid message ]\n"
ERR 2022-06-20 09:43:35.701+02:00 an error occurred while sending contact request topics="contacts-service" tid=49153 file=service.nim:309 msg="\nstatus-go error [methodName:wakuext_sendContactRequest, code:-32000, message:send-contact-request: invalid message ]\n"

**Comment by iurimatias** [comment]
fixed by https://github.com/status-im/status-desktop/pull/6152
