### ISSUE TITLE
Chat scrolling twitches

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#6187]
Might be related to https://github.com/status-im/status-desktop/issues/5781
But actually behaves differently.

## Description

https://user-images.githubusercontent.com/25482501/174867379-5efdf04d-4ea7-4fa3-86c2-03b692831122.mov

## Steps to reproduce

1. Open chat
2. Scroll

#### Expected behavior

Smooth scrolling

#### Actual behavior

Unbearable twitching

### Additional Information

- Status desktop version: 0.5.0
- Operating System: MacOS 12.4

**Comment by Hbouaz** [comment]
just adding some similar scrolling issues on the seed 

Uploading 176884683-8193f9a3-dc03-41dc-af61-5f2168d441a1.mp4…

phrase backup modal:
