### ISSUE TITLE
contact request accepted but not reflected on sender's side

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6189]
# Bug Report

## Description

note: was using 2 desktop instances locally so it might affect the results. maybe it affected the connections etc..

## Steps to reproduce

1. on client A, go to `#test` channel
2. on client B, go to `#test` channel and type something
3. on client A, click user B and send mutual contact request
4. on client B, accept contact request

result:
- on client A request is still pending
- on client A the contact list does not show client B
- on client B, manually opened a chat with client A and client A cannot see the profile picture of client B

note: after a few seconds/minutes it was ok

**Comment by saledjenic** [comment]
The steps which are reproducing this bug in ~100% cases are:
```
1. create new users A and B
2. copy user B public key
3. user A send contact request to user B
4. user B receives request sent by user A
5. user B accepts contact request sent from user A
6. user A becomes mutual contact for user B
7. BUT on the side of user A nothing happens cause user B has not been broadcasted any signal to update user A
```

**Comment by richard-ramos** [comment]
Doing tests with @cammellos, when using different IPAddresses, we were not able to reproduce the issue. 
Something I noticed when running the test on two local instances is that the number of peers in one of the nodes is very different:
![image](https://user-images.githubusercontent.com/1106587/175319115-24d5d439-c741-44ae-873b-0f692eefd3d9.png)

And after a while, the node with 1 peer does not see public messages on a chat. This problem might be network related.
