### ISSUE TITLE
ENS Usernames

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#6192]
**Pending usernames are missing the `stateofus.eth` subtitle**
![image](https://user-images.githubusercontent.com/1106587/174888631-80fdb733-a4f7-446b-a0ff-32f712b90097.png)

---

**Releasing username button is immediately available (unless it's been selected as a primary username). The release button should be disabled since the username is locked for 1Y**
![image](https://user-images.githubusercontent.com/1106587/174888962-c95db437-183e-4db6-b566-2d86ef7f16bd.png)

---

**Release button is executing `setPubkey(bytes32 node, bytes32 x, bytes32 y)` . It should run the smart contract function that releases username instead**
See trx: https://ropsten.etherscan.io/address/0x42d63ae25990889e35f215bc95884039ba354115

---

**After selecting an ens username as primary name, the release date is calculated incorrectly. Should be 1Y after buy date.**
![image](https://user-images.githubusercontent.com/1106587/174888420-e9f80602-4639-4fb0-b0bd-b09f4e50433c.png)

**Comment by elina2015** [comment]
Cannot test because I don't have ETH to buy ENS. Look at https://discord.com/channels/624205794384281629/869581754858635314/1001673451880321074
