### ISSUE TITLE
The app starts blinking suddenly

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#6195]
### Description
I cannot write steps to reproduce it because I cannot reproduce it but it's the second time I experiment it in the last 2 / 3 weeks. 

Here a video. It is not related to the specific action done in the video, but it is more visible when a modal popup is open because of the background color.

No error traces reported.

https://user-images.githubusercontent.com/97019400/174977474-97694097-9da4-43b7-9bed-1d85634171e7.mov

**Comment by iurimatias** [comment]
this is an issue with QT it happens sometimes with multiple monitors, moving the app between monitors fixes it. we have to update Qt (probably qt 6 with c++) and hopefully it fixes it
