### ISSUE TITLE
`Collectibles` are not shown / partially shown when enabling multinetwork option

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#6197]
### Description
1. Navigate to Wallet with some `watch-only` accounts that have collectibles. 
2. Click into the `Collectibles` tab and check that collectibles are correctly shown.
3. Navigate to advanced settings and enable `Multinetwork` option.
4. Check the Wallet settings are correct (testnet / ropsten).
5. Navigate to the Wallet to see again the collectibles.

**Expected:**
Collectibles are correctly shown as in the first instance.

**Actual:**
Collectibles are not shown or partially shown.

See video for better understanding:

https://user-images.githubusercontent.com/97019400/174987474-6ecb698d-8d37-40a7-b150-b32bc83e038b.mov

**Comment by alaibe** [comment]
@noeliaSD this is "normal" behaviour, as you switched to test net, the collectibles are query on rinkeby, this is then normal that you see different collectible than before you enabled multinetwork + test net
