### ISSUE TITLE
Recent transaction done is not shown in the `History` tab 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#6198]
### Description
1. Having 2 different wallet accounts, complete a send transation from one to the other.
2. Wait until the transaction has been executed.

**Expected:**
After tokens are in the receiver wallet, check the history and see the transaction done.

**Actual:**
After tokens ares in the receiver wallet, the history doesn't show the transaction done.

In the following video, 2 different tranactions of 1 STT each one have been done from the `Stauts account` to the `TestAccount` but in the `History` tab no transactions are listed:

https://user-images.githubusercontent.com/97019400/174989334-f650fef8-b04e-4a7c-a901-f05f7d216eda.mov

**Comment by alaibe** [comment]
@noeliaSD could you share the public address of the account? thanks

**Comment by noeliaSD** [comment]
> @noeliaSD could you share the public address of the account? thanks

Yeah!

- The SENDER address: **0x795AafF5715D01f18A094f55001a6aF30a470E55**
- The RECEIVER address: **0x92b28B5Dec2C4f1db8EDEd871141A2bcacA043B5**

**Comment by alaibe** [comment]
@noeliaSD see below, this is now fixed:
![image](https://user-images.githubusercontent.com/491074/178495078-da5b340b-df51-4eb0-822f-b3df59fc5ca1.png)
