### ISSUE TITLE
Community - wrong names of contacts when inviting

### ISSUE THREAD

**Issue by Hbouaz** [status-im/status-desktop#6200]
# Bug Report

## Description

when inviting contacts their names (and photos sometimes) are wrong, although behind the scene it is the right contacts 

## Steps to reproduce

1- Create a community 
2- Click on add members 

#### Expected behavior

Invite Friends popup shows up with a listing of contacts you can invite
#### Actual behavior
Invite Friends popup shows up with a listing of contacts you can invite, but the names are wrong
<img width="940" alt="image" src="https://user-images.githubusercontent.com/26457452/174998431-40198fb0-3752-4e25-9b9d-d72c72f352d3.png">

vs expected contacts:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/26457452/174998610-6f71e20d-5118-4d85-ac3d-7e8a19f193cc.png">

### Additional Information

- Status desktop version: Master
- Operating System: MacOS

**Comment by iurimatias** [comment]
this has been fixed
