### ISSUE TITLE
Activity center is empty when having mentions and replies

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6201]
### Description

1. as user , get mentioned in public chat
2. as user, get mentioned in community channel
3. as user , get replied in public chat
2. as user, get replied in community channel

As result, activity center is empty

**Comment by jrainville** [comment]
It worked for me (in community)

![Image](https://user-images.githubusercontent.com/11926403/178320518-6e7944a8-10f5-4dda-9c32-beb1b90bd234.png)

@anastasiyaig did you have any special use case? Or reproduction step?

**Comment by elina2015** [comment]
@jrainville @iurimatias @anastasiyaig hey,  I tested it on the [latest master ](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2319/)and replies and mentions in the public chat (test) are not shown in the Activity center: 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/14942081/178855470-5896cc25-cd64-4764-adec-1e688a3c436d.png">
While mentions and replies in community are shown correctly in the Activity center:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/14942081/178855812-a001fdb4-f952-42ef-accd-d05435afa3ce.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/14942081/178855903-f7758732-451d-4e25-8fdd-67cdfd6348b7.png">

**Comment by anastasiyaig** [comment]
ah okay, then i will close this one
