### ISSUE TITLE
Move mailserver disconnect notification to app's banner line

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#6213]
Within this issue we should do the following:
- Remove "Can not connect to mailserver" popup (since we will display it as app global notification, in banner line)
- Figure out the list of notifications we need to display in banner line. So far known info are:
  - new app version available - green line - has "Download" button
  - your version is up to date - green line - has "Close" button
  - backup seed phrase - red line - has "Back up now" button
  - mailserver disconnected - orange line - has "Retry now" button
- In case more than a single info is present at the same time we should display banner lines in a vertical column, one below another, in order red notifications at top, orange ones below, green at the bottom
- Logic we need behind mailserver disconnection:
  1. once the app notices that mailserver is disconnected, it should try to reconnect to a mailserver automatically after `reconnectionTimeout` seconds (set to 5 seconds initially)
  2. if reconnection is successful then the app removes banner line and resets `reconnectionTimeout` to initial value (5 seconds)
  3. if reconnection fails the app does next try in `2 x  reconnectionTimeout` seconds (what will be 10 seconds for second try, 20 seconds for third try, 40 for fourth... but `reconnectionTimeout` must not be longer than let's say 150 seconds), if reconnection succeed in any of those tries go to step ii. and reset `reconnectionTimeout` to initial value
  4. in any point of time if user manually runs "reconnection process", clicking on "Retry now" button from the banner line, the app will try to reconnect immediately and reset `reconnectionTimeout` to initial value (5 seconds) 
- We should check do we need close button ("X" button on the right) for each of above mentioned notifications, and if not, which we need that close button for

Current banner line:
![BannerLine](https://user-images.githubusercontent.com/86303051/175251051-deaa14b0-6527-453a-ac65-31b80e586037.png)

**Comment by PascalPrecht** [comment]
This has landed as of https://github.com/status-im/status-desktop/issues/6213

**Comment by PascalPrecht** [comment]
@saledjenic can you confirm and close this issue?
