### ISSUE TITLE
In Profile menu show options for "Respond to Contact Request", "Contact Request Pending"

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6251]

**Comment by Hbouaz** [comment]
@iurimatias can you add Figma links please if available

**Comment by iurimatias** [comment]
> @iurimatias can you add Figma links please if available

This is a sub task that is part of an epic, that's why the figma is not here. To find it on the top you'l see `Tracked in
 https://github.com/status-im/status-desktop/issues/6114`, the figma can be found there

**Comment by elina2015** [comment]
figma: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1125%3A139397

**Comment by elina2015** [comment]
Will be tested in the epic
