### ISSUE TITLE
The dialog 'Back up your seed phrase' is cropped and the buttons are not visible there

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6253]
# Bug Report

## Steps to reproduce
1. Create a new account and go to Settings (the app is in the minimized window)
2. Click 'Secure your seed phrase Back up now'
3. Check the buttons that appeared in the 'Back up your seed phrase' dialog

#### Expected behavior
The buttons are shown correctly
#### Actual behavior
The buttons are hidden by the bottom edge of the window
### Additional Information
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/14942081/176033592-4b7691fe-84ec-497a-9723-7209f9f82e1e.png">
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/14942081/176035181-5dee2aed-372c-4435-944a-ea84e1091b7f.png">

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2246/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
already fixed
