### ISSUE TITLE
There is no hint for the Chat tab

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6254]
# Bug Report

## Steps to reproduce
1. Sign in and open Community Portal or Settings
2. Hover over the Chat icon in the navigation left bar

#### Expected behavior
The hint 'Chat' is shown
#### Actual behavior
There is no hint for the Chat tab
### Additional Information
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/14942081/176034475-8968996e-3f9e-4b26-803b-698bbf3eb0e9.png">

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2246/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by caybro** [comment]
@elina2015 by "hint" you mean a tooltip?

@iurimatias Anyways, I think I know what the issue is here, I already noticed the same in the StatusQ Sandbox app, one-liner fix. Shall I take it :)
