### ISSUE TITLE
Contact requests dialog is placed incorrectly

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6258]
# Bug Report

## Steps to reproduce
1. Get a 1-1 request from a new contact
2. Open Chat tab - Contact Requests
#### Expected behavior
The dialog is shown correctly
#### Actual behavior
The dialog is shown very close to the top and bottom edges of the window (in minimized and full window)
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/14942081/176079173-7889e32a-a83f-4355-a490-89b351bbdd82.png">

### Additional Information

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2246/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
this has been fixed
