### ISSUE TITLE
Nothing happens when accepting a contact request

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6259]
# Bug Report

## Steps to reproduce
1. Get a 1-1 request from a new contact
2. Open Chat tab - Contact Requests
3. Click on the green icon for accepting the request

#### Expected behavior
The request is accepted, and the 1-1 chat with the accepted user is shown
#### Actual behavior
Nothing happens
### Additional Information

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2246/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
can't replicate
