### ISSUE TITLE
Nothing happens when request a transaction in 1-1 chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6265]
# Bug Report

## Steps to reproduce
1. Open 1-1 chat and click '+' - Request transaction
2. Follow all steps, enter an amount and click 'Request'

#### Expected behavior
The request transaction appeared in 1-1 chat
#### Actual behavior
Nothing happens
### Additional Information
https://user-images.githubusercontent.com/14942081/176089757-a4d88c0e-6f7a-4ee9-ac1a-41af03cb8ee9.mov

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2246/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6778
