### ISSUE TITLE
Cannot create a wallet account 

### ISSUE THREAD

**Issue by Hbouaz** [status-im/status-desktop#6272]
# Bug Report

## Description

after using a valid password, account creation fails and throws an error
## Steps to reproduce

Go to wallet
Try to create a new account by using your valid password
Notice error popup
![BF9252DD-2F9C-424D-A193-1663B344656F](https://user-images.githubusercontent.com/26457452/176206994-da4abae6-b80f-48a7-a393-92f6caf31541.jpeg)

### Additional Information

- Status desktop version: master
- Operating System: MacOS

**Comment by alaibe** [comment]
@Hbouaz did u use advance section of the popup?
By simply generating account, i have been able to do it 2 times:
![image](https://user-images.githubusercontent.com/491074/176383611-9bc4d318-43a2-43c0-a177-fb4887dd9365.png)

Do u have reproducible steps?

Here is my scenario:
- create a new account
- enable wallet
- go to wallet
- click on add account
- enter password
- enter account name
- click on add account
=> account generated

**Comment by anastasiyaig** [comment]
i was not able to reproduce as well, works to me

**Comment by Hbouaz** [comment]
Worked now after clearing app data and creating a new user. Thanks for trying

**Comment by Hbouaz** [comment]
closed now as cannot repro
