### ISSUE TITLE
Squish-Login-Flow-24 SeedPhrase

### ISSUE THREAD

**Issue by OlufemiAdeOlusile** [status-im/status-desktop#6276]
Include Sign up flow
with 24 digit seed phrase flow
and verify wallet address.

TestRail: https://ethstatus.testrail.net/index.php?/cases/view/702171&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=50829

**Comment by anastasiyaig** [comment]
closed during clean-up
