### ISSUE TITLE
Wallet, clicking send causes the app to crashes 

### ISSUE THREAD

**Issue by Hbouaz** [status-im/status-desktop#6283]
# Bug Report

## Description

Wallet, clicking send causes the app to crashes 

## Steps to reproduce

create a new user
enable wallet
go to wallet 
click on Send
The app crashes

#### Expected behavior
Send modal opens up 

#### Actual behavior
App crash

### Additional Information

- Status desktop version: master CI Build #2250 and local master latest build
- Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
I was not able to reproduce it in latest master `Build #2316 (12 Jul 2022, 21:00:16)`
