### ISSUE TITLE
The profile image is blurred in different places

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6295]
# Bug Report

## Steps to reproduce
1. Get a mutual contact with an image
2. Open the profile of this mutual contact and check the profile image
3. Open the 1-1 chat with this mutual contact and check 

#### Actual behavior
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/14942081/176533139-0ab04685-25d5-47bd-9156-8957d711922d.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/14942081/176533310-806ed1b5-a42b-4244-9d1f-2e9bbad3b819.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2255/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by elina2015** [comment]
@iurimatias, I fund that the bug is still reproduced on the latest master:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/14942081/177613473-6dc6da9a-9dc0-4811-8717-e8d30824bac1.png">

**Comment by caybro** [comment]
Same here, I can also reproduce (and got a fix too ;)

**Comment by elina2015** [comment]
Tested and approved
