### ISSUE TITLE
The emoji hash icons are very big

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6300]
# Bug Report

## Steps to reproduce
1. Open your own profile or any contacts profile
2. Check the size of the emojis in the emoji hash according to the design https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=662%3A320379

#### Expected behavior
<img width="655" alt="image" src="https://user-images.githubusercontent.com/14942081/176550261-159d1e9e-2bd1-4e35-9244-9b806e6a8c13.png">
Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=662%3A320379

#### Actual behavior
The emoji hash icons are very big:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/14942081/176550131-299da255-daeb-4ee0-b05a-e01d3e7b7b45.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2255/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by elina2015** [comment]
@themarvi hey, thank you for fixes! I noticed there is no gap between some icon. Could you kindly check? 
<img width="729" alt="image" src="https://user-images.githubusercontent.com/14942081/179379718-e35011ec-23ed-4222-ac2e-a839cf82588c.png">

**Comment by themarvi** [comment]
Hi @elina2015, sure! Thanks for bringing this up! 

In deed, I set the spaces between icons to 0, while designs requests 0.2 (Letter property).
For testing purpose I set it locally to 0.2 and run the app, now it looks like below:
![obraz](https://user-images.githubusercontent.com/84290812/179574582-6a95e6a9-1da3-4217-96fb-a176026375e2.png)

With full/square icons:
![obraz](https://user-images.githubusercontent.com/84290812/179574843-34216265-f234-4d12-937d-11bb09e9599c.png)

Real size:
![obraz](https://user-images.githubusercontent.com/84290812/179574915-562d719b-39bd-49ee-9d2e-614eb0e3df8a.png)


I set also 0.5 to make spaces more visible, here is how it looks:
![obraz](https://user-images.githubusercontent.com/84290812/179578293-388e6fca-f8a2-4c8b-b398-9a90faa06e72.png)
Real size:
![obraz](https://user-images.githubusercontent.com/84290812/179578349-6862f5cd-07e9-479d-9eed-6b5bc7ac6882.png)
...but with 0.5 we are not aligned with the design 👮

Do you think, 0.2 is acceptable space? I think also in design, grandma(👵) is almost touching 🅱 :)


Thanks,
Kamil

**Comment by themarvi** [comment]
NP! Great, I will push changes with space = 0.2 asap.

**Comment by themarvi** [comment]
☝️ PR Updated :)

**Comment by elina2015** [comment]
@themarvi well done! Thank you for the fixes!
