### ISSUE TITLE
'Show my profile picture to no one' doesn't work

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6301]
# Bug Report

## Steps to reproduce
1. User A gets a mutual contact, 
2. Add a Profile picture, leave a message in the text chat, 
3. Go to Settings - Messaging
4. Select 'No one' for 'Show my profile picture to"
5. Sign out and Sign in with User B (User A mutual contact) and go to the test chat
6. Check User A profile picture

#### Expected behavior
If the settings are installed to 'Show my profile picture to no one' - the profile picture shouldn't be shown to any user (contact or not)
#### Actual behavior
The profile image is shown for mutual contacts even if user installed Settings 'Show my profile picture to no one'.
<img width="888" alt="image" src="https://user-images.githubusercontent.com/14942081/176564822-a000557f-1130-4ac8-b038-e65f326089c7.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/14942081/176564772-88c9b19b-15e9-44d8-b7be-074af851e260.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2255/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
replaced by https://github.com/status-im/status-desktop/issues/7609
