### ISSUE TITLE
Mouse scroll doesn't work when chat is in topmost position

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#6319]
# Bug Report

## Description

Mouse scroll doesn't work when chat is in the top most position. To unblock mouse scrolling the scrollbar must be dragged manually to exit the topmost position.

https://user-images.githubusercontent.com/33099791/176771015-80ffd0b5-15a7-4da1-a784-82bd37e68949.mp4

### Additional Information

- Status desktop version: beta 0.6.0
- Operating System: Ubuntu

**Comment by MishkaRogachev** [comment]
Should be resolved with https://github.com/status-im/status-desktop/pull/6456
