### ISSUE TITLE
The notifications sign is not shown for the Activity Center on the New Chat page

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6346]
# Bug Report

## Steps to reproduce
1. Get a few notifications to Activity Center (new contact, mentions, was added to group chat)
2. Click on the icon of New Chat icon and check the number of notifications on the bell icon (Activity Center) in the right top corner.

#### Expected behavior
The number of new notifications appears on the Activity Center icon. 

#### Actual behavior
There is no number of new notifications on the Activity Center icon. 
If I click on any public chat in the Secondary Nav panel, the part of the number icon appears near the Activity Center
<img width="898" alt="image" src="https://user-images.githubusercontent.com/14942081/177218070-9f22b96e-fb40-4366-8d0b-536f9f3a529d.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
this is being done in a another task to make the activity center global
