### ISSUE TITLE
The left margin in the Secondary Nav is too narrow

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6347]
# Bug Report

## Steps to reproduce
1. Sign in and check the left margin in the Secondary Navigation panel

#### Expected behavior
<img width="704" alt="image" src="https://user-images.githubusercontent.com/14942081/177223641-89a50294-1f1c-4e60-aaf1-25e1b7f0dc7b.png">

#### Actual behavior
<img width="897" alt="image" src="https://user-images.githubusercontent.com/14942081/177223614-6fde22a9-3fe6-4812-83f7-e59e0db4940d.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by caybro** [comment]
This should get fixed together with #6393

**Comment by elina2015** [comment]
Tested and approved
