### ISSUE TITLE
The font size of the grey "To:" text in the start new chat field is too small

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6349]
# Bug Report

## Steps to reproduce
1. Sign in
2. Click on the icon for starting a new chat near the Search field
3. Check the text 'To:' in the start new chat field
#### Expected behavior
<img width="788" alt="image" src="https://user-images.githubusercontent.com/14942081/177230739-4e0829d7-833f-4e7e-9bc9-095539c5f5d8.png">
Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=112%3A26519
#### Actual behavior
The font size of the grey "To:" text in the start new chat field is too small
<img width="888" alt="image" src="https://user-images.githubusercontent.com/14942081/177230845-24b9218d-e773-47ce-8fae-95f4bcff73f4.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by alexandraB99** [comment]
change already in desktop
