### ISSUE TITLE
Nothing happens after click on a chat title

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6351]
# Bug Report

## Steps to reproduce
1. Sign in and join a few public chats
2. On the Chat page, click on the 'Start chat' icon
3. Click on any public chat title in the Secondary Nav panel

#### Expected behavior
The chat page is shown
<img width="894" alt="image" src="https://user-images.githubusercontent.com/14942081/177233342-69f0a499-073f-46e7-b973-e8aaa16593dc.png">

#### Actual behavior
Nothing happens
<img width="891" alt="image" src="https://user-images.githubusercontent.com/14942081/177233278-76cf97db-d3a0-4fcc-ae64-eed3cdbf39ef.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by alexandraB99** [comment]
@elina2015 I cannot reproduce this on current master

**Comment by caybro** [comment]
Yup, I fixed this in #6393, couldn't find the corresponding issue :) See https://github.com/status-im/status-desktop/pull/6393/files#diff-622893584a18833087a17569ce21d7594e5b6c7fe3e01469edb9afdaa81b0b6eR154
