### ISSUE TITLE
Communities cards on the Communities Portal don't match design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6359]
# Bug Report

## Steps to reproduce
1. Create a few communities and open the Communities Portal
2. Check the Communities cards according to the [Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2090%3A245814)

#### Expected behavior
<img width="935" alt="image" src="https://user-images.githubusercontent.com/14942081/177244555-92f8a734-2099-4b08-8b56-6a8012669ba9.png">

#### Actual behavior
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/14942081/177244620-862d8210-f68f-4921-926c-5e0e71545f07.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
in this particular case, the designs have been updated and the portal matches the new designs
