### ISSUE TITLE
Search doesn't work on the Communities Portal page

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6360]
# Bug Report

## Steps to reproduce
1. Create a few communities
2. Open Communities Portal and click on the Search field

#### Expected behavior
The cursor appears in the search field and it's possible to search a community

#### Actual behavior
The cursor doesn't appear in the search field and it's impossible to search a community
### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by micieslak** [comment]
When I create new communities they appear in the `Communities Portal` (the first 3 appear in `Featured` section, next one goes to `Popular`). But after restarting the app, all communities from the portal disappear. Where does those entries should come from? How it's decided to which section given community belongs to? @John-44 & @alexandraB99 I need more details about that section and how it should work. And probably search is not the issue which should be solved first here.
