### ISSUE TITLE
Profile-Preview doesn't match the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6362]
# Bug Report

## Steps to reproduce
1. Go to Settings-Profile-Preview
2. Check according to the [Design](https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1223%3A124882)

#### Expected behavior
<img width="919" alt="image" src="https://user-images.githubusercontent.com/14942081/177247489-1454b6fd-a95a-4514-afa1-84a6dd1582ed.png">

#### Actual behavior
Profile-Preview doesn't match the Design
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/14942081/177247447-15a7fe89-5aa4-4e80-8b50-e96cd42605a9.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by noeliaSD** [comment]
AFAIK this work is already done by @caybro [here](https://github.com/status-im/status-desktop/pull/7621). Please confirm and close if it is the case.

**Comment by caybro** [comment]
Yes :) Being reworked as part of https://github.com/status-im/status-desktop/pull/7621
