### ISSUE TITLE
Send multiple images (album) in one message

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#6374]
![image](https://user-images.githubusercontent.com/2522130/177584630-23c2612c-697d-4634-9961-677c2dfa98cd.png)

### Description

Sending several images should be implemented with one message 

### Acceptance Criteria

- [ ] Sent message with several images shown in chat view with horizontal layouted images
- [ ] UI selection shows that is one whole message

This is coming from mobile implementation:

> Also if album is sent, then you should be able to do the following actions:

- [ ] - Editing this message with album (changing text, pictures)
- [ ] - Leave reaction to a message with album
- [ ] - Delete message with album
- [ ] - Copy text if text exist in the message
- [ ] - Reply

All of those actions are able to be done for album, but not for separate image inside this album

**Comment by anastasiyaig** [comment]
@benjthayer @John-44 i guess we need designs for it ? Since it is implemented on mobile side now (and we have APIs)

**Comment by benjthayer** [comment]
The new destkop designs for reference - @John-44 I could take a look at the current desktop designs and align them functionally with what Filipe has for the new desktop designs?
https://www.figma.com/file/qSIh8wh9EVdY8S2sZce15n/Composer-for-Desktop?node-id=7150%3A392522&t=oE2Z1Xd0UGswbsOC-4

**Comment by John-44** [comment]
> @benjthayer @John-44 i guess we need designs for it ? Since it is implemented on mobile side now (and we have APIs)

@anastasiyaig we already have designs for this, see the figma I linked to in this comment https://github.com/status-im/status-desktop/pull/9744#issuecomment-1456337978

**Comment by John-44** [comment]
@anastasiyaig see https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=9295%3A338105&t=3ZGbkEvF2CRlQglr-1

![2023-03-06 15_40_33-💬 Chat⎜Desktop – Figma](https://user-images.githubusercontent.com/22846356/223158274-511b4905-1f7e-4ce4-a613-a49783ef7e6e.png)
