### ISSUE TITLE
Opening file manager/browser is not working on some linux distribution

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#6391]
Nothing happens when I click "Application Logs" In Settings > Advanced (using Linux Fedora, Gnome, Firefox)
Link clicking "open in my default browser" does not work for me on Status Desktop (using Linux Fedora, Gnome, Firefox)

**Comment by caybro** [comment]
Works fine here (Fedora 36); logs open in Nautilus, a test http link in my browser
