### ISSUE TITLE
Weird behaviour with replies

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#6407]
# Bug Report

## Description

If chat contains more than one reply, they mention wrong messages

## Steps to reproduce

- Open 1-to-1 chat
- Write a message
- reply it
- Write another message and also reply it with another message

#### Expected behavior

Each reply mentions valid message

#### Actual behavior

Second and subsequent replies mentions invalid message or nothing

### Additional Information

- Status desktop version: 0.6.0 (current master)
- Operating System: MacOS X Montery 12.4

https://user-images.githubusercontent.com/2522130/178289526-4a25e1a3-9c69-4700-85e4-3d1924979f74.mov

**Comment by osmaczko** [comment]
![image](https://user-images.githubusercontent.com/33099791/180143639-2cc7feaf-1ee4-4f87-96a9-fbfca79b5948.png)

@MishkaRogachev I can't reproduce it on current master -> 819d210ab8cfbcd7b1a195a7764304ddbb4b297d :man_shrugging: 
Could you please check if it still happens for you?

**Comment by MishkaRogachev** [comment]
> * reply to the message of the user with an avatar picture
crazy
