### ISSUE TITLE
Create language model on the nim side

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#6416]
### Description

Currently, the language model is created in `LanguageStore.qml`. Instead, it should be made by the backend: https://github.com/status-im/status-desktop/pull/5853#pullrequestreview-981841672

### Motivation
Target languages are driven by the Lokalise platform now. The app should be able to auto-adapt to added/removed target languages or the adaptation should require as least code as possible.

### Acceptance criteria
- language model is created on nim side
   - (if possible) language model is created programmatically by scanning `qml_*.qm` files
- bugprone imperative code `initializeLanguageModel` is removed

**Comment by caybro** [comment]
@osmaczko this is somewhat wrong; only Qt (and QTranslator) knows about the available UI languages, and you can query such list with `Qt.locale().uiLanguages` (see https://doc.qt.io/qt-5/qml-qtqml-locale.html#uiLanguages-prop). No need to build the model; scanning `*.ts` files would be equally wrong, you want the `*.qm` files, and those better be bundled in the qrc resource file when compiling.

**Comment by osmaczko** [comment]
blocked by: https://github.com/status-im/status-desktop/issues/6500
