### ISSUE TITLE
Transaction bubbles are not present in chat 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6429]
### Description

1. add a mutual contact
2. open 1x1 chat
3. click Request transaction button
4. request some funds

As result, transaction bubble is missing

<img width="1512" alt="Screenshot 2022-07-13 at 09 44 45" src="https://user-images.githubusercontent.com/82375995/178668374-062e7e76-7c9a-4cee-8e40-32383ddae5c5.png">

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6778
