### ISSUE TITLE
NaN instead of balance when transacting in chat

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6430]
### Description

1. add mutual contact
2. open 1x1 chat
3. click Send transaction
4. pay attention to the balance

<img width="1512" alt="Screenshot 2022-07-13 at 09 43 26" src="https://user-images.githubusercontent.com/82375995/178668603-e1824d71-811a-46af-b09c-435b2e7d19d4.png">

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6778
