### ISSUE TITLE
Display price changes

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6482]
### Description

to be done after https://github.com/status-im/status-desktop/issues/6481

Asset list should display price changes in the select fiat currency and % wise

<img width="683" alt="Screen Shot 2022-07-17 at 1 32 44 PM" src="https://user-images.githubusercontent.com/176720/179417716-ca30973b-627a-45b4-bbc5-6f58daf25a02.png">

**Comment by Khushboo-dev-cpp** [comment]
@iurimatias should this change be change in 24 hours or whats time line?
