### ISSUE TITLE
Send Transation modal colors need to be adjusted to match designs

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6497]
# Bug Report

## Description

figma: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=2798%3A146177

- Background color is different
- Balance needs to be aligned to the left
- input field background is different

current:

<img width="605" alt="Screen Shot 2022-07-17 at 4 07 24 PM" src="https://user-images.githubusercontent.com/176720/179423005-20bfef2a-fa85-4251-a8ec-2f6eeeda7bfd.png">

expected:

<img width="504" alt="Screen Shot 2022-07-17 at 4 07 29 PM" src="https://user-images.githubusercontent.com/176720/179423010-77e17ef6-582b-4571-899b-1ace11c6e251.png">

**Comment by Khushboo-dev-cpp** [comment]
@John-44 We have put this is on hold, because this is the only place in status desktop, where modals have a background color like this one. Not sure if we should adapt this only for wallet, or leave like the default one used elsewhere.
