### ISSUE TITLE
The default image consists of only capital letters

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6516]
# Bug Report

## Steps to reproduce
1. Go to sign up a new user
2. On the page 'Your profile' enter 'Andrea' or any name started with a capital letter

#### Expected behavior
The default image consists of one capital letter and one small letter
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1023%3A298171

#### Actual behavior
The default image consists only in the capital letters
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/14942081/179633381-d42c7553-9d7c-4a67-82e2-56e3540f99d9.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2347/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
all other designs use upper case, so it seems to be an issue in this particular figma
