### ISSUE TITLE
The stranger's profile doesn't look good and doesn't match the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6537]
# Bug Report

## Steps to reproduce
In the minimized window:
1. Go to any public chat and click on any stranger's nem there
2. Click 'View Profile'
#### Expected behavior
<img width="477" alt="image" src="https://user-images.githubusercontent.com/14942081/179870934-6b6e48c6-a54e-4be4-9ff5-7752e8ebc014.png">
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=662%3A320379
#### Actual behavior
<img width="932" alt="image" src="https://user-images.githubusercontent.com/14942081/179870901-98c379db-76a6-44ba-9b65-23dfba79e410.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2347/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
seems ok in latest master
