### ISSUE TITLE
'Rename' leads to a profile's popup

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6541]
# Bug Report

## Steps to reproduce
1. Go to any public chat and click on any stranger's name there
2. Click 'View Profile'
3. Click 'Rename'

#### Expected behavior
The popup 'Give <stranger's name> a nickname' appeared
<img width="727" alt="image" src="https://user-images.githubusercontent.com/14942081/179880657-dcb3bbcf-dc32-4dfb-8983-832ab26c40cb.png">

#### Actual behavior
The stranger's profule appeared
<img width="789" alt="image" src="https://user-images.githubusercontent.com/14942081/179880707-cd917b10-a3d9-4eea-a589-eb9ac605cc35.png">

### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2347/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
already done in https://github.com/status-im/status-desktop/pull/6377
