### ISSUE TITLE
Contact request message and very next message are separated with [Today] timestamp

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6543]
### Description

1. create user one
2. create user two (separate instance)
3. as user one, send a message in public chat
4. as user two, click the message and send contact request
5. as user one, accept the contact request
6. as user one, send a message to 1x1 chat with user two
7. as user two, open 1x1 chat with user one

As result, the contact request message and newly received message are divided with [Today] timestamp

<img width="927" alt="Screenshot 2022-07-20 at 10 41 04" src="https://user-images.githubusercontent.com/82375995/179925782-b17a6d2f-65d2-45a1-a279-f9fbb40f9ae3.png">

**Comment by MishkaRogachev** [comment]
Confirmed
<img width="1012" alt="Screenshot 2022-08-01 at 13 27 39" src="https://user-images.githubusercontent.com/2522130/182129055-a113b4c5-2837-4b99-84c1-926d4cae324d.png">
