### ISSUE TITLE
Cant invite user to community

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6544]
### Description

```
qrc:/app/AppLayouts/Chat/views/CommunitySettingsView.qml:231: TypeError: Cannot call method 'inviteUsersToCommunity' of undefined
```
1. create community
2. add at least 1 mutual contact
3. open community -> invite new people -> invite

<img width="1594" alt="Screenshot 2022-07-20 at 10 51 20" src="https://user-images.githubusercontent.com/82375995/179927383-9c84baef-9a20-4fb4-bcb5-368930d7a7cc.png">

**Comment by iurimatias** [comment]
can't replicate in latest master
