### ISSUE TITLE
[Wallet] Implement set favourite/unfavourite for saved addresses

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#6546]
### Description
<img width="626" alt="fav" src="https://user-images.githubusercontent.com/31625338/179945017-2bf86c69-2837-4aa8-a2d8-fdffd287570a.png">
Pressing the star button in the right side should set/unset the address as favourite

**Comment by iurimatias** [comment]
there should be apis for this already but if not they will need to be implemented in status-go
