### ISSUE TITLE
Creating a community shows the general channel with no info on the main panel

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#6554]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/11926403/180006080-05c43b7b-00a1-4b86-8a4b-d3679dbf4600.png)

## Steps to reproduce

1. Go to Community portal and click Create a community
2. Create a very basic community with just a name and description (plus intro and outro)
3. See that the channel has no name or icon in the middle panel

**Comment by iurimatias** [comment]
can't replicate but there has been reports of this before, it's one of those that doesn't always happen

**Comment by osmaczko** [comment]
After trying like 30 times I almost gave up on it..

It happens only when we are not connected to the mailserver. The channel name and icon become correct as soon as connection is back.

**Comment by osmaczko** [comment]
May be related to this line of code: https://github.com/status-im/status-desktop/blob/b70a1c3a45422163674e94ce8e6253dbc590c164/src/app_service/service/community/service.nim#L574
