### ISSUE TITLE
Community channel category flickers when clicked

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6555]
When clicking on a community channel category, it flickers and also throws the following error:

```
ERR 2022-07-20 16:15:28.202+02:00 Error reordering category channel          topics="community-service" tid=2599508 file=service.nim:997 msg="\nstatus-go error [methodName:wakuext_reorderCommunityCategories, code:-32000, message:no change in category position ]\n"
```
There's a few issues here:

1. We shouldn't even try to call `reorderCommunityCategories` when we merely click the category (to toggle it). So something is going on that an actual drag/n'drop event is triggered
2. The flicker happens because, visually, when we drag and drop, we render a half transparent copy of the dragged item. Because the simple click seems to be interpreted as a drag, it shows that "ghost" element for a very short period (as long as the click is pressed), which makes it look like it flickers

**Comment by PascalPrecht** [comment]
In addition, it seems that clicking the entire category is bugged as well. It flickers shortly but doesn't toggle the category (maybe it's intended for it not to toggle when the category is clicked [but only when the caret icon is clicked]), still, it shouldn't flicker

**Comment by caybro** [comment]
Likely another instance of the problem when a `MouseArea` that handles the clicks fights with another one handling the drag. Suggest refactoring that to use `TapHandler` and `DragHandler` respectively

**Comment by micieslak** [comment]
https://github.com/status-im/status-desktop/pull/6792 Fixes mentioned error but flickering is still there.

**Comment by PascalPrecht** [comment]
I cannot reproduce this anymore
