### ISSUE TITLE
The error message 'Error sending the transaction' doesn't look good

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6557]
# Bug Report

## Steps to reproduce
1. Enable Wallet in Settings-Advanced
2. Get 10 SNT
3. Go to Settings-ENS usernames
4. Click Start - enter some free name - Next
5. Click 'Agree' - Register-Low-Continue
6. Click 'Sign with password'-enter your password-Sign with password

#### Expected behavior
The error notifications looks correct.
@John-44 could you kindly help with the design for it?
#### Actual behavior
The dark error message appeared that looks incorrect
<img width="891" alt="image" src="https://user-images.githubusercontent.com/14942081/180101801-0b632c14-31c9-45bc-a13a-426c33962f14.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2347/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6778
