### ISSUE TITLE
Tolerate better network disconnects - stickers

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6567]
### Description

There are instances the app hangs a bit if there are network issues. we should improve it so it can tolerate these better. for instance:

1. open stickers menu and look for a free sticker
2. turn off your network on your machine
3. click to get stickers

result: app hangs until the network connections comes back

**Comment by endulab** [comment]
After consulting with @richard-ramos there are 2 possible improvements
- use context timeout in status-go/stickers - this way, the long operation will automatically close goroutines with requests, if they last too long
- additionally use nim thread pool and run function asynchronously

There is no good way to check connection by Qt. This requires pinging a server that we trust. 
See https://forum.qt.io/topic/98676/how-to-check-whether-the-computer-connects-the-internet/8
Also there are a few native ways, which means we should handle 3 different implementations. 
However, regarding stickers, first we should apply context timeouts.
