### ISSUE TITLE
QR code in the Receive modal of the wallet doesn't appear

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#6570]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/11926403/180250805-e4b68d2d-36d1-4348-9e12-fcecf4e8893b.png)

![image](https://user-images.githubusercontent.com/11926403/180250859-89684842-878c-4e88-a46b-03e4d0648a67.png)

**Comment by jrainville** [comment]
Found this log when rebuilding the app on Windows:

```
Building: QR-Code-generator
make[1]: Entering directory 'C:/dev/nim-status-client/vendor/QR-Code-generator/c'
mkdir -p .deps
touch .deps/timestamp
gcc -std=c99 -O -c -o qrcodegen.o -MMD -MF .deps/qrcodegen.d qrcodegen.c
ar -crs libqrcodegen.a qrcodegen.o
gcc -std=c99 -O -c -o qrcodegen-demo.o -MMD -MF .deps/qrcodegen-demo.d qrcodegen-demo.c
gcc -std=c99 -O -o qrcodegen-demo qrcodegen-demo.o -L . -l qrcodegen
gcc -std=c99 -O -DQRCODEGEN_TEST -o qrcodegen-test qrcodegen-test.c qrcodegen.c
gcc -std=c99 -O -c -o qrcodegen-worker.o -MMD -MF .deps/qrcodegen-worker.d qrcodegen-worker.c
gcc -std=c99 -O -o qrcodegen-worker qrcodegen-worker.o -L . -l qrcodegen
make[1]: Leaving directory 'C:/dev/nim-status-client/vendor/QR-Code-generator/c'
```

I think the QR code generator vendor is broken, that's why QR codes don't work

**Comment by iurimatias** [comment]
works for me, could be an windows issue

**Comment by caybro** [comment]
I can reproduce on Linux too; strange thing is that usually after switching the tabs and/or changing the networks, the QR finally appears

**Comment by Khushboo-dev-cpp** [comment]
Hey I am unable to reproduce this behaviour too. @caybro do you not see the qr code by default or you need perform some steps?

**Comment by caybro** [comment]
@Khushboo-dev-cpp OK, I can no longer reproduce this too, must have been fixed recently :)

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp OK, I can no longer reproduce this too, must have been fixed recently :)

**Comment by caybro** [comment]
I swear I've seen it only a few days ago :) Now all good

**Comment by jrainville** [comment]
Ok, it was fixed somewhere, because I can no longer reproduce on Windows nor on Linux 🤷 

At least I have proof above that I'm not crazy haha.
