### ISSUE TITLE
Investigate if the patch to chat switching is still needed

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#6572]
The original patch to chat switching set the height of the channel to 0 instead of setting the loader to inactive. 

However, with the latest fix to switch slowness (https://github.com/status-im/status-desktop/pull/6342), that original hack might not be necessary anymore.

In a recent test PR, I set the visible to `false` when it is not the active chat so that the test could work better, but we need to test if that broke the performance increase https://github.com/status-im/status-desktop/pull/6556/files#diff-d0940252dc1c1a32eee839673dfa28495557a53f453ffbf0427eb04c4b093229R220

**Comment by iurimatias** [comment]
this is not needed anymore
