### ISSUE TITLE
Add custom waku2 nodes

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#6592]
It should be possible to add any wakuv2 node as a peer either by using the node multiaddress, or a node's ENR, and rely on Identify protocol to determine the node capabilities. 

Acceptance Criteria:
-  settings- > advanced, user can click 'add waku v2 node' enter an addres or ENR and see a multiadress in the list of waku nodes

**Comment by richard-ramos** [comment]
https://github.com/status-im/status-go/pull/2438 is required for this, although it introduces a breaking change (read PR description)

**Comment by glitchminer** [comment]
@anastasiyaig, updated QA_Status to blocked. Awaiting designs for modal and dependant on https://github.com/status-im/status-go/pull/2438 to merge for functionality.

**Comment by jrainville** [comment]
This issue has some big changes on the status-go side. I recommend moving it out of the 0.8 release since it will be safer to have QA testing both on the desktop and mobile side before merging it

**Comment by glitchminer** [comment]
@richard-ramos @iurimatias, looking at clarifying acceptance criteria for this. It's noted that a user should be able to add a node but how will it be possible to know that adding a node as worked please?

**Comment by alexandraB99** [comment]
*removed `ui` label as it's popping up in our backlog
