### ISSUE TITLE
Waku2 - Improve wakuv2 visualization / management

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#6594]
The following information is useful when using wakuv2:
- Listen Addresses
- Connected peers, protocols supported
- Pubsub topic(s) used
- Protocols that were mounted
- Add / Remove / Connect / Disconnect peers
- https://rfc.vac.dev/spec/30/ - adaptive node desktop intermittent vs persistent, visualize as slider

This issue might need to be converted into an epic

**Comment by anastasiyaig** [comment]
@iurimatias please add a milestone
