### ISSUE TITLE
Mac traybar icon issue when using multiple monitors

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6595]
# Bug Report

## Description

When using multiple monitors, the monitor that is currently the active one shows the icon correctly, but the others it shows this resized icon.

## Steps to reproduce

1. open the app, put it in the background
2. click a browser window on monitor 1

result on monitor 1:

<img width="67" alt="Screen Shot 2022-07-24 at 11 29 05 AM" src="https://user-images.githubusercontent.com/176720/180654429-c00f4470-a6c3-43df-915d-bfec974f1b06.png">

result on monitor 2:

![Screen Shot 2022-07-24 at 11 29 02 AM](https://user-images.githubusercontent.com/176720/180654435-0eac4c3b-e28f-4ec7-9ef3-488a36d18b99.png)

3. now click a browser window on monitor 2

result on monitor 1:

![Screen Shot 2022-07-24 at 11 29 02 AM](https://user-images.githubusercontent.com/176720/180654435-0eac4c3b-e28f-4ec7-9ef3-488a36d18b99.png)

result on monitor 2:

<img width="67" alt="Screen Shot 2022-07-24 at 11 29 05 AM" src="https://user-images.githubusercontent.com/176720/180654429-c00f4470-a6c3-43df-915d-bfec974f1b06.png">

**Comment by MishkaRogachev** [comment]
https://bugreports.qt.io/browse/QTBUG-88600

**Comment by iurimatias** [comment]
this is no longer an issue
