### ISSUE TITLE
invite user to community list is overflowing

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6596]
### Description

![Screen Shot 2022-07-24 at 11 49 25 AM](https://user-images.githubusercontent.com/176720/180655440-e30bd29b-1ad5-4635-8dec-c8f358c3e50d.png)

1. create a community
2. invite members

**Comment by alexandraB99** [comment]
@iurimatias I can't reproduce this one:
https://user-images.githubusercontent.com/31625338/180788861-bcd19a2a-4aee-4e2a-8a29-5fa4591f1095.mov

**Comment by iurimatias** [comment]
can confirm it's fixed in the latest master
