### ISSUE TITLE
Chain id does not match with signing typed message on ropsten in simpledapp

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6610]
### Description

In simpledapp.eth click Sign typed message on Ropsten

<img width="1372" alt="Screenshot 2022-07-25 at 15 32 15" src="https://user-images.githubusercontent.com/82375995/180778582-333a9f2d-be8b-4447-ac85-e166dda8dbd0.png">

<img width="399" alt="Screenshot 2022-07-25 at 15 32 12" src="https://user-images.githubusercontent.com/82375995/180778214-2c0ad36b-9766-4700-afc1-ad3b43b042a2.png">

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/6775
