### ISSUE TITLE
External join.status.im deep links not launching app

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#6612]
# Bug Report

## Description

Found during testing of
https://github.com/status-im/status-desktop/pull/6450

Spec for links is at https://github.com/status-im/specs/blob/1597103cb9c246b542db13b7a30bf1110102afc5/docs/draft/17-url-scheme.md

The following links are opening **status.im/get** instead of 

1. The following URLs are resolving to https://status.im/get instead of loading the app:

- /browser/[url] (currently implemented using only /browse/ but spec was updated)
- /pm/[user_pk or ens_name]
- /p/[chat_key]
- /private-message/[user_pk or ens_name]
- /public/[chat_key]
- /group/[group_name]/u/[user_pk_1 or ens_name_1]/…/u/[user_pk_19 or ens_name_19]

2. The following URLs are resolving to an error message of Error: Invalid group chat URL: Missing arguments!:

- /g/[group_name]/u/[user_pk_1 or ens_name_1]/…/u/[user_pk_19 or ens_name_19]

## Steps to reproduce

1. Navigate to an external deep link (eg. https://join.status.im/public/status )
2. User is redirected to https://status.im/get

#### Expected behavior

1. Navigate to an external deep link (eg. https://join.status.im/public/status )
2. User is redirected to a page where it is possible to follow link to open app
      ![image](https://user-images.githubusercontent.com/50769329/180779320-2b6c47c8-844e-4289-a788-1b70aac5dac5.png) 
4. Status desktop launches

User is taken to a page with the option to open the location in the app:

#### Actual behavior

User is taken to https://status.im/get or shown an error.

### Additional Information

- Status desktop version: StatusIm-Desktop-220713-174002-0ddf0c-pr6450
- Operating System: Tested on Windows but all OS applicable
- Browser: Chrome

**Comment by endulab** [comment]
I am going to close this ticket, because the set of links has changed.
Also there will be a new web site which will handle them correctly.
