### ISSUE TITLE
Fixing a mnemonic keyword and switching tabs causes keyword to remain as it was instead of using correction

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6619]
# Bug Report

## Description

This is a bit hard to explain so video should make it a bit more clear but essentially typing an incorrect mnemonic word, then fixing it, seems to revert bad to the incorrect word if switching tabs. then the submit considers it an invalid seed phrase even if the mnemonic was fixed

https://user-images.githubusercontent.com/176720/180800407-d8aa3c72-1549-4e27-8a50-df0fba01f1d7.mov

**Comment by micieslak** [comment]
The problem is with words which are prefixes of other words (e.g. add/address, win/wine, kid/kidney)

**Comment by micieslak** [comment]
minimal example:

https://user-images.githubusercontent.com/20650004/183384891-707c3329-0f92-410c-ab10-edc9a779f218.mp4
