### ISSUE TITLE
User profile image on sidebar should be a bit bigger larger

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6622]
### Description

The profile picture should be slightly larger see https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop-(rolled-back-version-to-recover-a-screen%2C-ignore)?node-id=106%3A20383

![Screen Shot 2022-07-25 at 10 52 48 AM](https://user-images.githubusercontent.com/176720/180806787-ea377b29-a0f8-4619-b1da-9371a34328bc.png)

**Comment by caybro** [comment]
@iurimatias shouldn't it be also a bit lower? (btw the link to the design doesn't work for me)
