### ISSUE TITLE
Support editing/deleting/replying to emoji/sticker/audio messages

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#6624]
Implement the required UI changes

This status-go PR adds the required backend functionality
- https://github.com/status-im/status-go/pull/2771

**Comment by stefandunca** [comment]
Emoji in 1-1 work fine
- Reply: ![image](https://user-images.githubusercontent.com/47554641/186945485-89b425a9-f0cb-4b4f-b168-025d135d7847.png)
- Delete your own:
![image](https://user-images.githubusercontent.com/47554641/186945737-133e24bd-83a6-41a9-9526-2e1389322356.png)

**Comment by stefandunca** [comment]
Audio messages work also: 
![image](https://user-images.githubusercontent.com/47554641/187218940-560c6afe-441f-4e30-84c0-8dc9c53189ba.png)
