### ISSUE TITLE
current status state should be bold

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6626]
### Description

current:

![Screen Shot 2022-07-25 at 11 10 03 AM](https://user-images.githubusercontent.com/176720/180812732-a89aca0d-9efe-44e3-a9e9-2031154a245e.png)

expected:

![Screen Shot 2022-07-25 at 11 10 25 AM](https://user-images.githubusercontent.com/176720/180812753-49013112-7f6f-4b2e-8cf9-fef805acaf50.png)

**Comment by caybro** [comment]
@iurimatias it works fine here on latest master, even survives app restart:

![Snímek obrazovky z 2022-07-25 18-19-11](https://user-images.githubusercontent.com/5377645/180826600-e3a96c8b-ce7c-4e5b-9b63-6fa90f7d9fd9.png)
