### ISSUE TITLE
Initial screen logo can look (slightly) pixelated in large monitors

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6629]
### Description

![Screen Shot 2022-07-25 at 9 39 32 AM](https://user-images.githubusercontent.com/176720/180817493-ccc53d6c-b24b-4dea-972c-48bad998b9d7.png)

it looks ok in a laptop monitor, but on a 27'' monitor the pixelation can be more noticeable

**Comment by saledjenic** [comment]
This issue is fixed in [this](https://github.com/status-im/status-desktop/pull/6755) PR.
