### ISSUE TITLE
Ding sound but no visual notification when sending message from mobile to desktop without adding user.

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#6639]
# Bug Report

## Description

Ding sound but no  visual notification when sending message from mobile to desktop without adding user.

## Steps to reproduce

Try sending a message from mobile to your desktop account without adding them s a contact.
Observe the ding sound, but no visual notification 

#### Expected behavior

Either we should have no notification sound or there should be visual notification along with the ding.

#### Actual behavior

ding sound, but no visual notification 

Uploading Screen Recording 2022-07-25 at 9.54.06 PM.mov…

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by iurimatias** [comment]
since it's not a mutual contact we should not be hearing the sound, so the fix should remove the sound
