### ISSUE TITLE
Profiles opened via deeplink stack on top of each other

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#6650]
# Bug Report

## Description

Found during testing of https://github.com/status-im/status-desktop/pull/6450

If a profile is already open and a deep link is used for another profile then it is stacked on top. Each profile must then be closed one after the other to return to the main screen. 

## Steps to reproduce

1. Open a profile

2. Navigate to another via deep link ( status-im://u/[ENS or chatkey] )

3. Multiple profiles now open on top of each other

https://user-images.githubusercontent.com/50769329/181018688-223c724b-6656-439b-83fa-d9f818bd5cec.mov

#### Expected behavior

[Assumed] Currently open profile should close and only the last one should remain open

#### Actual behavior

Profiles can stack on top of each other

### Additional Information

- Status desktop version: master
- Operating System: All

**Comment by glitchminer** [comment]
@iurimatias, discussed this with @jrainville that this appears to be a bug but will require input from design to confirm.

**Comment by caybro** [comment]
@alexandraB99 not working at all under Linux atm due to https://github.com/status-im/status-desktop/issues/8027

Somebody on mac has to work on this for now
