### ISSUE TITLE
Profile does not show ENS name when opened via ENS deeplink

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#6651]
# Bug Report

## Description

When a user opens a profile via a deep link (status-im://u/[ENS name] then the profile opens but it does not reference the ENS name, only the username. This could cause doubt that the profile is in fact linked to the ENS name.

## Steps to reproduce

1. Open a profile via deep link for an ENS name status-im://u/[ENS name]
2. See that profile only refers to the username not the ENS name entered in the URL

#### Expected behavior

Profile opened via deep link using ENS name should refer to the ENS

#### Actual behavior

Profile opened via deep link using ENS name does not refer to the ENS

### Additional Information

- Status desktop version: Local build for Master (25/07)
- Operating System: Tested on Mac and Windows

**Comment by caybro** [comment]
@endulab worth verifying together with https://github.com/status-im/status-desktop/pull/7621

**Comment by endulab** [comment]
I see this for status-im://u/sirotin, so probably it is ok now.

![image](https://user-images.githubusercontent.com/61889657/195870174-63a8a3fb-d3ac-4f41-9674-673f0f63768e.png)
