### ISSUE TITLE
Add alpha and beta sections to languages selector

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#6662]
### Description

Currently, status-desktop's set of translation languages is driven by the Lokalise platform. This does not guarantee all translations are provided and that they are provided correctly. It must be indicated in the app by appropriate sections: main, beta, and alpha.

- main: languages that have 90% of translations done and have been reviewed(accepted)
- beta: languages that have 90% of translations done
- alpha: languages that have 35-90% of translations done

languages that have <35% translations done shouldn't be displayed in any of the sections.

**Comment by osmaczko** [comment]
Yeah, that's fair. "100%" is more precisely the Lokalise metrics at the time of export. But still, this export time window may be very narrow making it almost impossible to reach 100%.

We should probably lower it to ~95% (at the time of export). The next question is: how often should we do exports? Exports will also probably lead to a languages section redefinition (the main language may become beta or even alpha..)

@John-44 WDYT? (triggering John because we came up with the original requirements together yesterday)

**Comment by John-44** [comment]
> Yeah, that's fair. "100%" is more precisely the Lokalise metrics at the time of export. But still, this export time window may be very narrow making it almost impossible to reach 100%.
> 
> We should probably lower it to ~95% (at the time of export). The next question is: how often should we do exports? Exports will also probably lead to a languages section redefinition (the main language may become beta or even alpha..)
> 
> @John-44 WDYT? (triggering John because we came up with the original requirements together yesterday)

Good point @caybro !

@osmaczko How about we make beta languages any language that is 90% done, to provide some leeway?  Or 95% as you suggested?  I'm happy with either (90% or 95%).

**Comment by caybro** [comment]
> > Yeah, that's fair. "100%" is more precisely the Lokalise metrics at the time of export. But still, this export time window may be very narrow making it almost impossible to reach 100%.
> > We should probably lower it to ~95% (at the time of export). The next question is: how often should we do exports? Exports will also probably lead to a languages section redefinition (the main language may become beta or even alpha..)
> > @John-44 WDYT? (triggering John because we came up with the original requirements together yesterday)
> 
> Good point @caybro !
> 
> @osmaczko How about we make beta languages any language that is 90% done, to provide some leeway? Or 95% as you suggested? I'm happy with either (90% or 95%).

Anything between 90-95% sounds plausible

**Comment by osmaczko** [comment]
@John-44 @caybro updated threshold from 100% to 90%
