### ISSUE TITLE
`UserImage` component doesn't take privacy settings into account inside message replies

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6668]
Here's a an example message history:
![Screenshot from 2022-07-27 16-34-27](https://user-images.githubusercontent.com/445106/181276025-1c941ee8-fb4e-487f-adf2-ecfcf145971a.png)

There's a reply, notice how the image of the message to be replied to is shown while, it's not shown in the original profile image.
The reason it's not shown in the original message is because by default, we don't show profile images.

When turning this setting on for "everyone" it looks like this:

![Screenshot from 2022-07-27 16-37-24](https://user-images.githubusercontent.com/445106/181276278-58d7d4a8-c182-4d7b-9e74-08873b043642.png)

This means, inside message replies `UserImage` doesn't seem to honor the settings.

**Comment by iurimatias** [comment]
putting this on hold because the profile photo visibility settings will probably change

**Comment by iurimatias** [comment]
replaced by https://github.com/status-im/status-desktop/issues/7609
