### ISSUE TITLE
Contact settings items have their right side options hidden (clipped)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#6669]
[Screencast 2022-07-27 11:29:20.webm](https://user-images.githubusercontent.com/11926403/181288426-a9e98f99-88fb-48b1-b565-730f85dfabc7.webm)

In the video above, we can see that the contact jonathan2 is there, but we cannot see the "send message" or "more options" buttons on the right.

They seemed to be clipped out. 

The solution is to resize the contact items to fit the parent. **No horizontal scrolls**!

**Comment by caybro** [comment]
Probably some missing `anchors.right` or `width`, will fix
