### ISSUE TITLE
Import tool: consecutive discord messages should be grouped like status messages

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6678]
Consecutive messages from the same sender within a certain time range are usually "grouped"  so that the senders profile avatar and username is only shown once until a message has a different sender.

Because imported discord messages have the same sender (the community itself), they will all show up as a single message stream provided by a single sender, even though they actually represent messages from different discord message authors.

This task is about teaching the front-end that different discord message authors is the same as different senders, in terms of UI representation.

**Comment by PascalPrecht** [comment]
@caybro would be cool if you could help out with this one.
Not a super crucial one though.

Lemme know if you can

**Comment by caybro** [comment]
> @caybro would be cool if you could help out with this one. Not a super crucial one though.
> 
> Lemme know if you can

Sure, just ping me whenever you have time :)
