### ISSUE TITLE
Import-tool: Message ordering is sometimes incorrect

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6679]
Not sure yet why this is happening, but I've noticed that, after importing many discord messages, sometimes the order in which they appear in the front-end is not correct.
![Screenshot from 2022-07-28 09-39-37](https://user-images.githubusercontent.com/445106/181449245-c8e7cfb3-38d0-442f-878c-aaa2006e71e5.png)

**Comment by glitchminer** [comment]
Is this related? https://github.com/status-im/status-desktop/issues/7058 (Chat - Messages in 1-1 chat arrive out of order)

**Comment by PascalPrecht** [comment]
Could be but hard to say. Would need to debug this. Opened this issue to not forget about this.

**Comment by PascalPrecht** [comment]
This has been fixed in status-go already
