### ISSUE TITLE
Import-tool: Handle discord message reactions

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#6681]
Discord message can have reactions. The data looks like this:

```json
      "reactions": [
        {
          "emoji": {
            "id": "",
            "name": "\uD83D\uDE02",
            "isAnimated": false,
            "imageUrl": "https://twemoji.maxcdn.com/2/svg/1f602.svg"
          },
          "count": 1
        }
      ],
```

These should be translated to reactions within Status

Acceptance criteria:

- Message reactions are shown on messages imported from Discord

**Comment by PascalPrecht** [comment]
I did not get to work on these, but I also think it's okay to leave them as as their impact is not crucial.

**Comment by 0x-r4bbit** [comment]
CLosing for now
