### ISSUE TITLE
Functionality unavailable at min width

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#6688]
# Bug Report

## Description

When the app is set to the minimum width elements become unavailable. In the case of scrollbars and toggles this limits functionality, such as in the settings screen.

## Steps to reproduce

1. Navigate to screen with content wider than min width
2. Resize app to minimum width

#### Expected behavior

Minimum width accommodates all elements, maintaining functionality

AND/OR

Components are responsive to resizing

#### Actual behavior

Elements hidden by resizing smaller

![image](https://user-images.githubusercontent.com/50769329/181470426-87f3bc5a-4db8-4a61-a3a4-327c3b79703e.png)

### Additional Information
Link to previous discussions on similar issues: https://hackmd.io/@status-desktop/B1naRjxh_/https%3A%2F%2Fhackmd.io%2F8f_JiTtRQSCUZ4Kl5C5XFQ#Broken-layouts

List of some other elements effected: https://docs.google.com/spreadsheets/d/1KQstc5KOykQZgdIliH6NhZOhnnHvTzTj1zYpdZslebc/edit?usp=sharing

- Status desktop version: Master (local build 28/07)
- Operating System: Mac

**Comment by iurimatias** [comment]
it's still scrollable so it's acceptable. We have a responsive design but that is to be done in 2.0

**Comment by glitchminer** [comment]
> it's still scrollable so it's acceptable. We have a responsive design but that is to be done in 2.0

Please note that at minimum width it is not entirely scrollable - only vertically via trackpad or scrollwheel. The vertical scrollbar itself is hidden and there is no horizontal scrolling possible to reach it or the other components that are not visible.
