### ISSUE TITLE
Import-tool: Need a way to extend StackModal children at runtime

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6689]
So we have this `StatusStackModal` thing that can have a bunch of children "views":

```qml
StatusStackModal {
  ...
  stackItems: [
     Component, Component, Component
  ]
}
```

^ This gives a wizard like experience where the user can step through individual items of the stack.

What we need however, is a way to extend `stackItems` of an existing StackModal.
For example, the `CreateCommunityPopup` has 2 hardcoded stackitems. We need this to be extended by three more items, depending on how the Modal is instantiated.

See: https://github.com/status-im/status-desktop/pull/6441#discussion_r920060863 for more information.

@MishkaRogachev has some ideas about this.

**Comment by MishkaRogachev** [comment]
I have thoughts about providing api similar to [StackView](https://doc.qt.io/qt-6/qml-qtquick-controls2-stackview.html), there you can push, pop and replace stack items. But existing functionality is also should be saved

**Comment by caybro** [comment]
`stackItems` looks line a plain JS array, you can just push/shift/unshift/splice as needed?

**Comment by PascalPrecht** [comment]
@caybro Ah you're saying it's possible to push component definitions into it?

Like 

```
stackItems.push(Component {
...
})
``` 

?

**Comment by caybro** [comment]
@PascalPrecht yeah it should be possible; question is how to detect changes inside the StackModal... will need to look at the code

**Comment by caybro** [comment]
@PascalPrecht effectively it's the `list` type (https://doc.qt.io/qt-5/qml-list.html), so should be possible

**Comment by caybro** [comment]
But it also means it can only be appended to; for dynamic changes, you'd probably have to use a temporary variable
