### ISSUE TITLE
Community chats and categories cannot be reordered

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#6698]
# Bug Report

## Description

The whole community list is scrolling on drag instead of dragging single element. Reordering chats/categories is infeasible.

## Steps to reproduce

Open community chats list, drag item

#### Expected behavior

- Particular items should be draggable in order to change their order.
- List shouldn't be scrollable horizontally.

#### Actual behavior

https://user-images.githubusercontent.com/20650004/181524522-cdc3b853-0c76-4f84-81de-e6fcafc51a82.mp4

### Additional Information

- Status desktop version:
- Operating System: Ubuntu

**Comment by micieslak** [comment]
Cannot reproduce now, ticket probably no longer valid

**Comment by endulab** [comment]
@micieslak probably you was not a community admin.
Also, channels reordering was fixed here: https://github.com/status-im/status-desktop/issues/7422
