### ISSUE TITLE
Cannot join community from the invitation

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#6712]
# Bug Report

Clicking "Join" in the bubble in the chat has no effect.

## Steps to reproduce

Invite users, login as the use who was invited, click "Join" in the direct chat.

#### Expected behavior

Community view should be opened.

#### Actual behavior

Nothing happens

https://user-images.githubusercontent.com/20650004/181729266-81659936-e567-42dc-84b3-4c6c8c1920ad.mp4

### Additional Information

- Status desktop version:
- Operating System: Ubuntu

**Comment by borismelnik** [comment]
So basically, it can be cos you use an old version of `status-go`. I checked it and I can reproduce it on some old version `phase4` from last dogfooding session, but can't reproduce it on new one. Based on new logic, `Join` button should be removed. Please try to reproduce it on latest status-go version.

**Comment by elina2015** [comment]
@borismelnik @iurimatias I tested this issue on the latest master and the bug is stably reproduced. Could we move this bug for fixing?

**Comment by borismelnik** [comment]
Now I understand it. It happens cos we still not process rejected requests. I request was rejected - we can't resend it even if sender sent new invitation cos request still `Pending`. I think, the solution for it is add new method to `status-go` like `myRejectedJoinCommunityRequests` (which is similar as `myPendingJoinCommunityRequest`) and update current list of pending requests.

**Comment by iurimatias** [comment]
to be reviewed after https://github.com/status-im/status-desktop/issues/7072

**Comment by iurimatias** [comment]
no longer seems to happen, also will issue is no longer valid after new join workflow
