### ISSUE TITLE
Community: reordering chat categories causes reshuffling chats with no category

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#6722]
# Bug Report

When category is reordered for the first time, chats with no category are reshuffled (according to the `position` property).
It's related with #6709 

## Steps to reproduce

- Go to Community, create several chats with no category and several categories
- Restart the app
- Reorder categories

#### Expected behavior
- only currently moved category should be reordered

#### Actual behavior

https://user-images.githubusercontent.com/20650004/181799661-a3ddb388-b18b-496b-bc45-7bbd9ece3c54.mp4

### Additional Information

- Status desktop version:
- Operating System: Ubuntu

**Comment by elina2015** [comment]
Tested and approved
