### ISSUE TITLE
Add Community Banner to Create Community Modal

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6726]
### Description

The Create Community Modal is missing the Community Banner. This already exists in Edit Community, so it should just be a matter of adding this to the create community modal as well.

<img width="344" alt="Screen Shot 2022-07-29 at 3 54 23 PM" src="https://user-images.githubusercontent.com/176720/181834118-785b37c5-54fb-41d7-a898-14fc7e675314.png">

**Comment by caybro** [comment]
@iurimatias this needs some backend work, both in status-go and NIM. The UI change is pretty simple, just needs someone with status-go/NIM knowledge

Sadly, the banner is supported for `editCommunity()` only, not for `createCommunity()`

**Comment by caybro** [comment]
Ok, so it turns out status-go backend already does support it, just need to add code to NIM backend, on it
