### ISSUE TITLE
Left arrow is too small

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6727]
### Description

1. go to portal
2. create a community
3. see back button

current:

<img width="68" alt="Screen Shot 2022-07-29 at 3 56 03 PM" src="https://user-images.githubusercontent.com/176720/181834354-ebb0bc92-8c17-4126-b091-ef30e34ef49b.png">

expected:

<img width="66" alt="Screen Shot 2022-07-29 at 3 56 06 PM" src="https://user-images.githubusercontent.com/176720/181834358-26dd2560-db96-49c9-9c7e-4ac58ec17fe3.png">

**Comment by alexandraB99** [comment]
fixed in statusq: https://github.com/status-im/StatusQ/pull/821
