### ISSUE TITLE
Create Channel modal adjustments

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6730]
### Description

- [ ] input should have the `#` for the channel
- [ ] Emoji icon needs to be adjusted to look like design

current:

<img width="515" alt="Screen Shot 2022-07-29 at 4 11 58 PM" src="https://user-images.githubusercontent.com/176720/181836440-ec74e480-6e56-48f3-ab45-5ec6ba9b219c.png">

expected:

<img width="522" alt="Screen Shot 2022-07-29 at 4 12 03 PM" src="https://user-images.githubusercontent.com/176720/181836454-6440550e-0a0a-47d2-bb59-4f358a7ab127.png">

**Comment by caybro** [comment]
Ooops, noticed too late but it's already being done here: https://github.com/status-im/status-desktop/pull/6745
