### ISSUE TITLE
The modal of uploading a community logo differs from the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6737]
# Bug Report

## Steps to reproduce
1. Go to create a new community
2. Click "+" for uploading a new logo
3. Check the appeared modal according to the Design https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2563%3A524846

#### Expected behavior
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2563%3A524846
#### Actual behavior
There are some different elements that are different from the Design
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/14942081/182084141-604d2f9e-1497-475e-9023-6074c43d8319.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/master/20/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
already logged in other issues
