### ISSUE TITLE
The modal of adding a new community differs from the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6740]
# Bug Report

## Steps to reproduce
1. Go to create a new community
2. Check the appeared modal according  to the Design

#### Expected behavior
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2638%3A358579
#### Actual behavior
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/14942081/182083296-72789b21-6218-47bc-906b-5db6c35e9715.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14942081/182085605-32431fda-554b-4136-898b-8af4287d9064.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14942081/182085864-36379074-0364-417d-bbb4-48d1a5412248.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/14942081/182088496-d68c9c71-51c5-4de3-b6a9-85ef2a110542.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/master/20/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
these issues have been logged already
