### ISSUE TITLE
RangeError: Maximum call stack size exceeded & TypeError: Type error

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#6742]
**What happens:**

When application starts, following errors show up:
```
qrc:/imports/shared/polyfill.number.toLocaleString.js: RangeError: Maximum call stack size exceeded.
qrc:/imports/shared/xss.js: RangeError: Maximum call stack size exceeded.
<Unknown File>: RangeError: Maximum call stack size exceeded.
<Unknown File>: RangeError: Maximum call stack size exceeded.
// a lot of Range Error
// then really lot of 
file:///Users/michal/Qt/5.14.2/clang_64/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:146: TypeError: Type error
file:///Users/michal/Qt/5.14.2/clang_64/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:146: TypeError: Type error
```

And in the middle 3 times:
```
file:///Users/michal/Qt/5.14.2/clang_64/qml/QtQuick/Controls/Styles/Base/ButtonStyle.qml:146: TypeError: Property 'stylizeMnemonics' of object [object Object] is not a function
```

After log in there is only white screen.

**When:**

There were a couple of situations when error appeared. It's hard to say if there are any relations between them.

1. Noelia's branch: https://github.com/status-im/status-desktop/pull/6110. Just checkout and compile.

2. master branch: can reproduce by using EditCroppedImagePanel in RenameGroupPopup. This one can be fixed by making changes in ImageCropWorkflow (which is used by EditCroppedImagePanel): replace "import QtQuick.Dialogs 1.3" with "import Qt.labs.platform 1.1". I noticed that in this case the problem was produced by FileDialog object.

**Os:**
MacOs

**Comment by jrainville** [comment]
Just popping in to say I experienced this as well. I did a fix to it back in the day, but I didn't find the root cause.

Igor has found it and is on the case!
