### ISSUE TITLE
Windows CI is broken due to fixtures

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#6743]
Also, we should only keep what is absolute necessary for the test to run (no log file...)

CI error:
```
error: unable to create file test/ui-test/testSuites/suite_status/tst_groupChat/data/keystore/0x14c36af7255a6a75cecadd2aad3ed9e9cbb98127ea4e4eafc204bfeb00569479/UTC--2022-07-22T11-35-18.382818000Z--66f4321c3b7b0a26258fbf6fd0175f5a8945c30e: Filename too long
```

Cause:

* https://github.com/status-im/status-desktop/pull/6613

**Comment by jakubgs** [comment]
Also, this could be avoided by editing a Registry entry:
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled
```
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

But this is on Windows 10, it MIGHT work on Windows Server 2019.

**Comment by jakubgs** [comment]
I have done this as part of the Ansible bootstrap role: https://github.com/status-im/infra-role-bootstrap-windows/commit/fb11ee28

![image](https://user-images.githubusercontent.com/2212681/182198412-75893310-2b77-49f7-9f5d-84211d5207d4.png)

Lets see if that does anything.

**Comment by jakubgs** [comment]
Nope, still seeing the error:
```
stderr: error: unable to create file test/ui-test/testSuites/suite_status/tst_groupChat/data/keystore/0x14c36af7255a6a75cecadd2aad3ed9e9cbb98127ea4e4eafc204bfeb00569479/UTC--2022-07-22T11-35-18.014338000Z--0568750156c53c50fb9c6a0b9c0ec5b32876c99a: Filename too long
```
https://ci.status.im/job/status-desktop/job/branches/job/windows/view/change-requests/job/PR-6759/2/console

**Comment by jakubgs** [comment]
Ok, I think also setting the `core.longpaths` Git option fixes it in combination with the registry edit:
https://ci.status.im/job/status-desktop/job/branches/job/windows/view/change-requests/job/PR-6759/3/console

Change: https://github.com/status-im/infra-role-bootstrap-windows/commit/90a2e475
