### ISSUE TITLE
Community chats reordering not persisted properly

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#6777]
# Bug Report

## Description

After changing the order of chats a few times, it is not persisted correctly. This is because a property 'position' is not updated in the model after reorder.

## Steps to reproduce

The initial order of chats is improper (#6709). Sorting can be enforced by reordering categories.

https://user-images.githubusercontent.com/20650004/182398948-f73f7843-8f23-44cf-9d8a-1a12e901edc5.mp4

#### Expected behavior

After app restart the order should be the same.

#### Actual behavior

Order is different.

### Additional Information

- Status desktop version:
- Operating System: Ubuntu

**Comment by elina2015** [comment]
Tested and approved
