### ISSUE TITLE
Onboarding - New user signup - Error after confirming password

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#6802]
# Bug Report

## Description

Error given during signup "Keys for this account already exist" even though it's a new install and new user. After closing error it is possible to continue to main chat screen and behaviour is ok.

![image](https://user-images.githubusercontent.com/50769329/182693954-0914549d-074f-43bd-9f66-1ce31e3f2acb.png)

## Steps to reproduce

Sign up as new user.
Finalise password.

Error is then shown.

Note: Issue appears to be intermittent. Have also seen this happen one screen later after confirming to use password instead of biometric on Mac.

#### Expected behavior

Signup completes without error.

#### Actual behavior

Intermittent error during signup after finalising password screen.

### Additional Information

- Status desktop version: Mac build 198
- Operating System: Mac

**Comment by endulab** [comment]
I am not able to reproduce the problem. FYI @glitchminer

**Comment by glitchminer** [comment]
@endulab, same. Assuming issue is no longer relevant - closing as cannot reproduce.
