### ISSUE TITLE
Onboarding - Profile pic - Picture is lost if back button is used

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#6803]
# Bug Report

## Description

After setting a profile picture and proceeding, if the user presses the back button then the picture is lost.

![2022-08-03_20-49-06 (1)](https://user-images.githubusercontent.com/50769329/182696725-b34e2b36-a894-4fa6-8128-f72e71e7e481.gif)

## Steps to reproduce

Set display name and profile pic
Review emojihash and identicon
On password screen navigate back to previous page
Pic is now lost

#### Expected behavior
Profile pic remains set

#### Actual behavior
Profile pic is removed

### Additional Information

- Status desktop version: Mac build 198
- Operating System: Mac

**Comment by faust4exe** [comment]
Tested on master branch from yesterday. Issue does not appear on Linux and Mac for me. @glitchminer can you check again the issue ?

**Comment by glitchminer** [comment]
@faust4exe, it seems resolved in latest master. Thanks for checking. Setting to closed.
