### ISSUE TITLE
Message time needs to be closer to username

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6832]
### Description

figma: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=9892%3A364390

current:

![image](https://user-images.githubusercontent.com/176720/182924289-3ab306cc-649e-4fd7-beb6-276d58cf5a9f.png)

expected:

![Screen Shot 2022-08-04 at 2 26 39 PM](https://user-images.githubusercontent.com/176720/182924390-3ab5e89b-e80a-4e17-9a15-792263329686.png)

**Comment by caybro** [comment]
And vertically centered, this is killing me :)
