### ISSUE TITLE
Keycard: user is stuck in Repeat PIN screen

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6838]
### Description

I think in case the connection between reader and laptop was interrupted, then there is no chance to continue

1. get new empty card
2. start the new keys flow
3. when being on repeat PIN screen, stay there for a while (10 min or so)
4. try to repeat PIN

What logs are saying:

```
1 currFlow=FirstRunNewUserNewKeycardKeys currState=KeycardRepeatPin
DBG 2022-08-05 10:54:01.081+03:00 keycardResumeFlow                          topics="keycard-service" tid=895614 file=service.nim:117 flowType=2 payload="{\"overwrite\":true,\"mnemonic-length\":12,\"pin\":\"000000\",\"new-pin\":\"000000\",\"new-puk\":\"743186816266\"}" response=ok
keycard - init failed scard: Service not available.
DBG 2022-08-05 10:54:01.138+03:00 keycard_signal                             topics="keycard-service" tid=895614 file=service.nim:91 response="{\"type\":\"keycard.flow-result\",\"event\":{\"error\":\"scard: Service not available.\"}}"
DBG 2022-08-05 10:54:01.139+03:00 on_keycard_response                        topics="app-controller" tid=895614 file=module.nim:240 currFlow=FirstRunNewUserNewKeycardKeys currState=KeycardRepeatPin
```

<img width="1436" alt="Screenshot 2022-08-05 at 10 54 30" src="https://user-images.githubusercontent.com/82375995/183030171-8d53068a-c1e6-4870-a231-d234189c8c7d.png">

**Comment by saledjenic** [comment]
@bitgamma I guess this it a case for you?

@anastasiyaig said that she left the app for some time untouched and after that she got `scard: Service not available.` error (check the description). 

What should we do then? Is that something we need to check and fix in the keycard lib?

**Comment by bitgamma** [comment]
what OS is this being tested on?

**Comment by bitgamma** [comment]
a fix has been now implemented in status-keycard-go
