### ISSUE TITLE
Profile image is not saved during onboarding

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#6861]
# Bug Report

## Description

https://user-images.githubusercontent.com/25482501/183310001-52b48bf3-1514-4691-a398-d7ba425e6257.mov

### Additional Information

- Status desktop version: `c6c76a1e8e9fb3bdeb9ee53d2fed9af3b5bdcd55`
- Operating System: MacOS 12.5

**Comment by iurimatias** [comment]
this fix should include a squish test
