### ISSUE TITLE
Regression in ImageCropWorkflow

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#6866]
Use QtQuick.Dialogs instead of Qt.labs.platform in ImageCropWorkflow.
FileDialog from the latter one has a different interface.

**Comment by caybro** [comment]
@endulab generally not a good idea, because `QtQuick.Dialogs` is based on QtQuick.Controls**1**

**Comment by endulab** [comment]
@caybro, the story is that it used to be QtQuick.Dialogs originally. I broke this during my last merge (because of a famous StackLayout thing). Now, I am reverting it back because with Qt.labs.platform it was not fully functional.

**Comment by caybro** [comment]
@endulab what was the issue?

**Comment by endulab** [comment]
> @endulab what was the issue?

Different interface. Some functions are different.
