### ISSUE TITLE
Mnemonic input not considered as valid in some cases, improper z-order

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#6909]
# Bug Report

## Description

When correct word is typed in and focus is switched to another input via clicking, word is not considered as a valid input. Additionally there are some related problems with z-ordering.

## Steps to reproduce

As presented in the video.

[Kazam_screencast_00032.webm](https://user-images.githubusercontent.com/20650004/193604694-97ec5241-37af-4100-8b06-3115623af26d.webm)

NOTE: after entering "add" please change focus using mouse, not enter!

#### Expected behavior

When all fields are properly filled, "Restore Status Profile" button should be enabled. Suggestion list should be always on top.

#### Actual behavior

"Restore Status Profile" disabled in described circumstances, suggestion list under input fields.

### Additional Information

- Status desktop version:
- Operating System: ubuntu

**Comment by alexandraB99** [comment]
@micieslak can't see the video here - is it still an issue?
