### ISSUE TITLE
ENS does not recognize goerli network

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6921]
### Description

<img width="1281" alt="Screenshot 2022-08-09 at 12 09 50" src="https://user-images.githubusercontent.com/82375995/183631588-fbf0c220-9e20-4139-9158-f51b299c9d03.png">

**Comment by Khushboo-dev-cpp** [comment]
fixed with https://github.com/status-im/status-desktop/pull/6925
