### ISSUE TITLE
Blank screen when switching theme during loggin in

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#6926]
### Description

1. open status and start new user creation
2. on the screen that suggests "I prefer to use my PIN", select an option (any)
3. while user is being logged in, change the theme 

As result, the screen is blank

```
qrc:/imports/shared/status/StatusGifPopup.qml:216:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-light.svg
qrc:/app/AppLayouts/Profile/views/EnsWelcomeView.qml:34:13: QML Image: Cannot open: qrc:/imports/assets/png/ens-header-light@2x.png
```

<img width="1012" alt="Screenshot 2022-08-09 at 16 35 23" src="https://user-images.githubusercontent.com/82375995/183675997-e82cf6c2-478d-464f-8b15-1084c560e897.png">

**Comment by iurimatias** [comment]
no longer happens
