### ISSUE TITLE
The app UI doesn't load with many `RangeError: Maximum call stack size exceeded` errors in log

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#6930]
# Bug Report

This is pretty much it in the title.
The problem is somewhere around `StatusPopupMenu`.

The problem arises before loading the UI. So it doesn't matter if you put the "problem origin component" into the `Loader` and create it dynanically.
It seems that while loading the engine processes whole code tree and gets into some recursive loop at this step.

**Comment by endulab** [comment]
Linking this issue: https://github.com/status-im/status-desktop/issues/6742

**Comment by osmaczko** [comment]
One of the causes of `Maximum call stack size exceeded` is infinite recursion, example:
```qml
function foo() { foo(); }
```
see:
```cpp
void tst_QScriptEngine::infiniteRecursion()
{
    // Infinite recursion in JS should cause the VM to throw an error
    // when the JS stack is exhausted.
    // The exact error is back-end specific and subject to change.
    const QString stackOverflowError = QString::fromLatin1("RangeError: Maximum call stack size exceeded.");
    QScriptEngine eng;
    {
        QScriptValue ret = eng.evaluate("function foo() { foo(); }; foo();");
        QCOMPARE(ret.isError(), true);
        QCOMPARE(ret.toString(), stackOverflowError);
    }
    ...
}
```

maybe some smuggled qml code with infinite recursion is the root cause.. :thinking:

**Comment by osmaczko** [comment]
We should try `QV4_CRASH_ON_STACKOVERFLOW`, see: https://doc.qt.io/qt-5/qtqml-javascript-finetuning.html

**Comment by caybro** [comment]
> By the way, it's interesting that this is happening at some early stage of QML loading. I always was able to workaround this issue by commenting out the code that wasn't even loaded.
> 
> E.g., having code like this (actually, this is `StatusMenuItemDelegate`:
> 
> ```qml
> Item {
>    Component { 
>       id: c1
>       Item { ... }
>    }
>    Component { 
>       id: c2
>       Item { ... }
>    }
>    Component { 
>       id: c3
>       Item { ... }
>    }
>    
>   Loader {
>     sourceComponent: c1
>   }
> }
> ```
> 
> And then comment out any of `c2` or `c3`, **which are not even ever loaded**, fixes the problem. man_shrugging

@igor-sirotin the thing has to be "compiled" first I believe, it doesn't mean it gets instantiated

**Comment by Cuteivist** [comment]
Reopening this bug.

Fix introduced in #6977  doesn't work for Windows platform. 
Code 
```
os.putEnv("QV4_JS_MAX_STACK_SIZE", "10485760")
```
Isn't applied, but when env var is setup before running application it works fine.

**Comment by jrainville** [comment]
I confirm this. I tested on Windows and the issue happens in the wallet. Once i apply the env var manually, it works

**Comment by caybro** [comment]
> I confirm this. I tested on Windows and the issue happens in the wallet. Once i apply the env var manually, it works

Quick dirty idea, we need to do it earlier, in C++ (DOtherSide)

**Comment by caybro** [comment]
I mean before creating the QGuiApplication instance

**Comment by caybro** [comment]
> @caybro Imgine that your idea worked perfectly :)

Where's the PR? ;)

**Comment by Cuteivist** [comment]
> > @caybro Imgine that your idea worked perfectly :)
> 
> Where's the PR? ;)

Tested on my side, but want to double check from @jrainville on Windows side and Linux too, because I have Windows and Mac only.
