### ISSUE TITLE
It's impossible to add a reaction to Reply message

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6939]
# Bug Report

## Steps to reproduce
1. Reply to some message (text, gif, emoji) or find a reply message
2. Try to add a reaction 

#### Expected behavior
Reactions modal is shown and after clicking on any reaction it is correctly added
#### Actual behavior
The reactions modal is shown and after clicking on any reaction it is not added

https://user-images.githubusercontent.com/14942081/183786895-00a7ac9b-8d68-4ec3-850a-86814d17ddfd.mov

### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
can't replicateet
