### ISSUE TITLE
The Start chat page without contacts doesn't look good in the minimized window

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6942]
# Bug Report

## Steps to reproduce
1. Sign in with a user without contacts
2. Go to Start a group or 1-1 chat in the minimized window

#### Expected behavior
The page looks correct
#### Actual behavior
<img width="901" alt="image" src="https://user-images.githubusercontent.com/14942081/183801226-18af9027-7834-414d-9068-6e3de2b6bc8c.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
https://user-images.githubusercontent.com/176720/184683756-1d103b4d-74c5-49bf-b72f-b68750789fc7.mov
