### ISSUE TITLE
The loader during the sign in process is blurred

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6943]
# Bug Report

## Steps to reproduce
1. Sign in
2. Check the appeared loader screen

#### Expected behavior
The loader is not blurred
#### Actual behavior
The loader is blurred
<img width="716" alt="image" src="https://user-images.githubusercontent.com/14942081/183807988-64d7ec3b-aab2-40ad-8472-db8725d430e3.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by caybro** [comment]
This has been fixed in master already here: https://github.com/status-im/status-desktop/pull/7811
