### ISSUE TITLE
The stickers packs' icons are shown incorrectly in the Chat's Actions modal

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6967]
# Bug Report

## Steps to reproduce
1. Go to 1-1 or Group chat
2. Add a few stickers pack
3. Click on the stickers' icon in the Chat
4. Check the stickers' packs icons

#### Expected behavior
The stickers' icons are shown on the level of the clock icon  (according to the Design https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=572%3A4519)
<img width="430" alt="image" src="https://user-images.githubusercontent.com/14942081/184054070-be5927ba-7fb4-4cad-99ab-89922ea36aad.png">

#### Actual behavior
The icons are shown as very low
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/14942081/184054044-aa166f86-3c94-4b4d-aa2c-6e685e9cfd51.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by caybro** [comment]
@alexandraB99 didn't you fix that already?

**Comment by iurimatias** [comment]
this is a duplicate / should have been fixed in another issue already
