### ISSUE TITLE
The black circle is shown instead of some stickers

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6969]
# Bug Report

## Steps to reproduce
1. Join 'test' chat
2. Add all free packs of stickers
3. Go to add a sticker from any pack
4. There are mostly of stickers are unavailable and after click the black circle appears in the chat

#### Expected behavior
The stickers are shown and the correct sticker appears in the chat after clicking on it
#### Actual behavior
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14942081/184055776-3fb85da4-753b-4613-92d7-2fab4c792509.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
this should be fixed by the recent fix to the infura key
