### ISSUE TITLE
The untrusted mark is shown very close to the Admin icon in the Community members' list

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6972]
# Bug Report

## Steps to reproduce
1. Join a community
2. Add the community admin to the mutual contacts
3. Open the profile of the community admin and click Mark Untrustworthy
4. Come back to the community and click the 'Members' icon
5. Check the admin
#### Expected behavior
The admin's icon is shown correctly
#### Actual behavior
<img width="673" alt="image" src="https://user-images.githubusercontent.com/14942081/184062915-dca869e3-e59f-48e8-b06a-601d293da785.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by faust4exe** [comment]
Another PR with updated StatusQ was already merged so PR related to this Issue was closed.
This Issue can also be closed.
