### ISSUE TITLE
Community invite modal - Share button does not align per Figma

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#6982]
# Bug Report

## Description

Minor alignment issue with a shared component as confirmed with @MishkaRogachev during testing of https://github.com/status-im/status-desktop/pull/6655 (item 7 in issues found).

## Steps to reproduce

Visual inspection

### Expected
   ![image](https://user-images.githubusercontent.com/50769329/182887807-c45af9c6-bad0-47aa-bb8e-49cd4963a836.png)

### Actual
   ![image](https://user-images.githubusercontent.com/50769329/182888261-30769834-720a-4e3d-9862-4b4967304d4e.png)

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6655/2/
- Operating System: Mac

**Comment by iurimatias** [comment]
fixed in latest master
