### ISSUE TITLE
Text formatting toolbar doesn't show the "text quote" option

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#6988]
# Bug Report

## Description

In Status desktop, the text formatting toolbar you can use to format text in messages doesn't show the text quote option. This option can still be used in markup with the `>` markup right before the text.

This is related to https://github.com/status-im/status-desktop/issues/6030.

## Steps to reproduce

1. Write any message on Status desktop, but don't send the message.
2. From your message, select one or more words.
3. The formatting toolbar shows up with the four following options: bold, italics, strikethrough, and code.

#### Expected behavior

When you select the text, the formatting toolbar shows the quote-style text format option and the other formatting options.

#### Actual behavior

When you select the text, the formatting toolbar doesn't show the quote-style format option, only the bold, italics, strikethrough, and code options.

You can still add the quote-style format to your text using the `>` markup right before the text.

### Additional Information

- Status desktop version:
- Operating System: macOS 12.5 "Monterrey."

![Frame 1](https://user-images.githubusercontent.com/62282406/184199084-1b89527a-5a75-43ae-aa94-564aea26390f.png)

**Comment by elina2015** [comment]
Tested and approved
