### ISSUE TITLE
Factory reset a Keycard

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#7036]
This issue refers to the `Factory reset a Keycard` flow, which starts here:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=7258%3A188342

- This flow is partially done since it's shared with onboarding/login flow, but we need the second part of where user is able, in case he knows the pin, to see what is stored on the keycard before factory reset.

Part of Keycard settings part which is the epic tracked under https://github.com/status-im/status-desktop/issues/4920

**Comment by anastasiyaig** [comment]
this is already implemented and merged
