### ISSUE TITLE
[Keycard]: Can't proceed with Factory reset 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7040]
### Description

<img width="1823" alt="Screenshot 2022-08-16 at 12 14 48" src="https://user-images.githubusercontent.com/82375995/184845022-62c5acde-fbdc-4c44-b88d-b52f770a3c36.png">

```
DBG 2022-08-16 12:15:54.098+03:00 keycard_signal                             topics="keycard-service" tid=10067771 file=service.nim:92 response="{\"type\":\"keycard.flow-result\",\"event\":{\"error\":\"unknown-flow\"}}"
```

**Comment by saledjenic** [comment]
@anastasiyaig this behaviour is very weird, I cannot reproduce it. Are you sure that you've built the app with the latest `status-keycard-go` changes? Please try it again.

**Comment by anastasiyaig** [comment]
yes, yes sorry for ping @saledjenic , i rebuilt the keycard lib and now it is fine
