### ISSUE TITLE
Communities - Manage Community - Cannot unblock user

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7052]
# Bug Report

## Description

It is not possible to unblock users

## Steps to reproduce

1. Block a user from the community
2. Unblock user
3. User is not unblocked or found in members list or any other tab

#### Expected behavior

Possible to block and unblock users

#### Actual behavior

Cannot unblock

### Additional Information

- Status desktop version: Master (16/Aug)
- Operating System: Mac

**Comment by iurimatias** [comment]
this should have a squish test

**Comment by jrainville** [comment]
@borismelnik what's the status of this issue? There is an old PR attached, but still open. Also, that PR is only tests, so is the actual issue of not being able to unblock already fixed in master?

**Comment by jrainville** [comment]
Should be fixed in master since a couple weeks
