### ISSUE TITLE
Chat - Messages in 1-1 chat arrive out of order

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7058]
# Bug Report

## Description

In a 1-1 chat, messages sent close together consistently arrive out of order

## Steps to reproduce

1. Log in with two instances
2. Message from 1 user to the other
3. Observe order messages arrive in.

#### Expected behavior

Messages arrive in order

#### Actual behavior

Messages arrive out of order

Actual
![2022-08-09_17-22-43 (1)](https://user-images.githubusercontent.com/50769329/183867604-9a3f543f-45aa-42c3-8a06-e9d95798ddb9.gif)

### Additional Information

- Status desktop version: https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220817-135906-0a4bfa-pr6508.dmg
- Operating System: Mac

**Comment by PascalPrecht** [comment]
That's a nice find. We first thing to check is whether the signals arrive out of order, or if processing in desktop is off
