### ISSUE TITLE
Pinned mailservers are stored with an incorrect format

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#7059]
Currently desktop stores the pinned mailservers in the settings like this:
```
{
  "eth.prod": "the mailserver@enode.address",
 "eth.test": "the mailserver@enode.address"
...
}
```
Status-go expects the pinned mailservers to be stored like this instead:
```
{
  "eth.prod": "mailserver-id",
 "eth.test":  "mailserver-id",
...
}
```

Fixing this issue requires making the mailserver models aware that there's an id: for the fleet, the id is the name of the mailserver, while custom mailservers have a uuid. In https://github.com/status-im/status-desktop/pull/7001 i modified the function to save custom mailservers to return this uuid

The fix should also take in account that the environment variable `MAILSERVER` expects an address. It should probably be changed to check this address in the list of fleet mailservers and custom mailservers, to calculate which id should be used to pin the mailserver.

**Comment by jrainville** [comment]
This landed in master
