### ISSUE TITLE
New join community workflow

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7072]
### Description

figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2312%3A298851
feature spec:  https://github.com/status-im/feature-specs/pull/79/files

out of scope:
- **token based permissions IS OUT OF SCOPE FOR THIS TASK**
- hcaptcha

goal: implement the various features & changes present in the workflow in figma:
- [x] Should be possible to view a community without being a member (but not send messages)
- [x] Button to join community if community doesn't require membership approval
- [x] Button to request to join community if community requires membership approval
- [x] Modify welcome modal to be as in the design (note buttons are different depending if it's to join a community or to request joining one)
- [x] User should see an ephermeral notification that a request has been made
- [x] User should see an ephermeral notification that a request has been accepted or rejected
- [ ] #8313
- [x] User should be able to cancel an ongoing membership request
- [x] Community invites in chat should still work as expected
- [ ] Squish tests might need to be updated or made for this

**Comment by John-44** [comment]
(copying a comment into this issue as this comment contains pictures that describe what's needed a bit clearer)

-----------------------------------------

@iurimatias @osmaczko @faust4exe @jrainville  The behaviour shown in this screencast is incorrect.  

https://user-images.githubusercontent.com/22846356/190130162-23c0ff99-d6ca-4cf2-94f8-51808aaa53f6.mp4

When the user in the right screen clicks "Request Access" (btw this button text should be changed to "Go to Community" in all cases), a popup *should not* appear.

Instead the user should be redirected to the home screen for the community:  

1) If the Community is an open community (e.g. no token permissions at the community level) and if 'manual membership approval' is set to No, then the user should see this:
![2022-09-14 11_00_16-Window](https://user-images.githubusercontent.com/22846356/190124545-ad94d39f-eff8-4ea0-adbc-cc3232381a95.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2244%3A260547 )

2) If the Community is an open community (e.g. no token permissions at the community level) and if 'manual membership approval' is set to Yes, then the user should see this:
![2022-09-14 11_01_26-Window](https://user-images.githubusercontent.com/22846356/190124756-96fd1bdf-e813-4574-93ca-f2bc9b8ed33f.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2365%3A296006 )

3) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to No, then the user should see this *if they hold the tokens needed to access the community*:
![2022-09-14 11_03_11-Window](https://user-images.githubusercontent.com/22846356/190125118-cf63743b-b5b6-4255-94c4-2a5b5453b564.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2314%3A257946 )

4) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to No, then the user should see this *if they **do not** hold the tokens needed to access the community*:
![2022-09-14 11_04_21-Window](https://user-images.githubusercontent.com/22846356/190125463-58811278-06d8-4245-95f5-f0bb89668135.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2367%3A280302 )

5) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to **Yes**, then the user should see this *if they hold the tokens needed to access the community*:
![2022-09-14 11_05_39-Window](https://user-images.githubusercontent.com/22846356/190125727-5cb581c7-b824-47ac-8ad5-ee2aa432672c.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2365%3A317460 )

6) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to **Yes**, then the user should see this *if they **do not** hold the tokens needed to access the community*:
![2022-09-14 11_06_52-Kuba⎜Desktop – Figma](https://user-images.githubusercontent.com/22846356/190126076-575acd5a-444a-4a7f-a44b-54983f79da1c.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2365%3A317901)
