### ISSUE TITLE
New design for Transaction History and Transaction Details

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7073]
### Description

figma: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6105%3A75943

- [ ] make activity history work again (if it's not already) 
- [ ] Change activity history to look like design (see https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6105%3A75943 ) https://github.com/status-im/status-desktop/issues/7215
- [ ] Support view transaction (similar to view token & view collectible), see design https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=7394%3A99017 https://github.com/status-im/status-desktop/issues/7214
- [] Squish tests https://github.com/status-im/status-desktop/issues/7213

**Comment by anastasiyaig** [comment]
I suggest to keep this "epic" until https://github.com/status-im/status-desktop/issues/7215 is done
