### ISSUE TITLE
Channel name missing in community category

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#7098]
# Bug Report

## Description

Discovered with autotest:  https://github.com/status-im/status-desktop/pull/7078

## Steps to reproduce

 - Create new community
 - Create new channel 
 - Create new Category with  created channel  and **general** channel

#### Expected behavior

- Category contains both channels with names displayed normal

#### Actual behavior

<img width="359" alt="Screenshot 2022-08-19 at 15 40 57" src="https://user-images.githubusercontent.com/2522130/185630343-cb511510-7c0b-49ce-afd7-da1f59fb4755.png">

### Additional Information

Does not repeat regularly

**Comment by alexandraB99** [comment]
this sounds like https://github.com/status-im/status-desktop/issues/7380 , @MishkaRogachev please close if duplicate
