### ISSUE TITLE
Keycard does not work on Ubuntu

### ISSUE THREAD

**Issue by michelleplur** [status-im/status-desktop#7103]
Just freshly built Status Desktop. Smartcard reader is working, pcscb is installed (since ubuntu 18 it's default). 
In the logs of the app: ```keycard - keycard-error: no pcsc service```

Also tested on MacOS, iMac M1, here it works fine.

**Comment by alaibe** [comment]
@michelleplur did u enable the service?
```
sudo systemctl start pcscd.socket
```

On ubuntu this service is not enabled by default

**Comment by michelleplur** [comment]
yes

**Comment by michelleplur** [comment]
It works with running it in dev mode from master, but when i build it with docker there's no pcscd service found.

**Comment by alaibe** [comment]
After changing the keycard debug to:
```
cardCtx, err := scard.EstablishContext()
	if err != nil {
		err = newKeycardError(err.Error())
		l(err.Error())
		close(kc.connected)
		return err
	}
```
In order to have the "real" error, here it is:
`keycard - keycard-error: scard: Service was stopped.`

But the service is running correctly. It looks like the scard program is having an issue?

**Comment by alaibe** [comment]
@michelleplur ☝ is it something you can look at?

**Comment by alaibe** [comment]
Done
