### ISSUE TITLE
Wallet: Bad formatting in Asset VIew

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#7129]
### Description
Bad formaating of token balance

![image](https://user-images.githubusercontent.com/60327365/186421037-bbb7616b-01c8-4226-b9e0-054f894c8250.png)

**Comment by stefandunca** [comment]
> ![image](https://user-images.githubusercontent.com/60327365/186421037-bbb7616b-01c8-4226-b9e0-054f894c8250.png)

@Khushboo-dev-cpp it will be great to understand here which is your locale and what are the expected values.
Judjing from the code and screenshot I can only assume that you have the European regional settings (where , and the `.` separation is the default English locale. What is our expectation? Locale is followed in number formatting by default, right?

**Comment by caybro** [comment]
> > ![image](https://user-images.githubusercontent.com/60327365/186421037-bbb7616b-01c8-4226-b9e0-054f894c8250.png)
> 
> @Khushboo-dev-cpp it will be great to understand here which is your locale and what are the expected values.
> Judjing from the code and screenshot I can only assume that you have the European regional settings (where , and the `.` separation is the default English locale. What is our expectation? Locale is followed in number formatting by default, right?

As noted elsewhere, working on that in a separate branch 😊
