### ISSUE TITLE
Chat - Pinned messages - Pinned limit reduces after unpinning

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7130]
# Bug Report

## Description

After a message has been unpinned then the pinned message limit is reduced by 1.

## Steps to reproduce

1. Pin 4 messages (pin limit)
2. 5th pin causes pinned limit reached prompt
3. Unpin 1 message (3 pinned messages)
4. Pin 1 more message - pin limit reached at 3 messages

(pin limit reduces each time)

#### Expected behavior
Pinned message limit remains consistent

#### Actual behavior
![image](https://user-images.githubusercontent.com/50769329/186421353-8e586926-e4e8-4694-8390-6d8ea4f166e3.png)

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-220824-111243-1c7719.dmg
- Operating System: Mac

**Comment by endulab** [comment]
Already fixed in  https://github.com/status-im/status-desktop/pull/7330.
Tested.
