### ISSUE TITLE
Various issues with community invitation message state

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#7139]
## 1

- send two invitations to the same user to the community that requires the request to join
- send a request to join
- accept the user
- one of user invitations message is "Pending" instead of "View"

https://user-images.githubusercontent.com/33099791/186612309-384de00d-8967-44ec-8d5b-c599352214ae.mp4

#### Note
application restart fixes the issue
## 2
- leave the community that requires the request to join
- user invitation is "Join" instead of "Request access"
![image](https://user-images.githubusercontent.com/33099791/186613248-e7c79573-9146-4577-b32f-fbb5de16738f.png)

**Comment by John-44** [comment]
@iurimatias @osmaczko @faust4exe @jrainville  Note the behaviour shown in the 1) screencast is incorrect.  When the user in the right screen clicks "Request Access" (btw this button text should be changed to "Join"), a popup *should not* appear.

Instead the user should be redirected to the home screen for the community:  

1) If the Community is an open community (e.g. no token permissions at the community level) and if 'manual membership approval' is set to No, then the user should see this:
![2022-09-14 11_00_16-Window](https://user-images.githubusercontent.com/22846356/190124545-ad94d39f-eff8-4ea0-adbc-cc3232381a95.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2244%3A260547 )

2) If the Community is an open community (e.g. no token permissions at the community level) and if 'manual membership approval' is set to Yes, then the user should see this:
![2022-09-14 11_01_26-Window](https://user-images.githubusercontent.com/22846356/190124756-96fd1bdf-e813-4574-93ca-f2bc9b8ed33f.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2365%3A296006 )

3) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to No, then the user should see this *if they hold the tokens needed to access the community*:
![2022-09-14 11_03_11-Window](https://user-images.githubusercontent.com/22846356/190125118-cf63743b-b5b6-4255-94c4-2a5b5453b564.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2314%3A257946 )

4) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to No, then the user should see this *if they **do not** hold the tokens needed to access the community*:
![2022-09-14 11_04_21-Window](https://user-images.githubusercontent.com/22846356/190125463-58811278-06d8-4245-95f5-f0bb89668135.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2367%3A280302 )

5) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to **Yes**, then the user should see this *if they hold the tokens needed to access the community*:
![2022-09-14 11_05_39-Window](https://user-images.githubusercontent.com/22846356/190125727-5cb581c7-b824-47ac-8ad5-ee2aa432672c.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2365%3A317460 )

6) If the Community is a closed community (e.g. there are token permissions at the community level) and if 'manual membership approval' is set to **Yes**, then the user should see this *if they **do not** hold the tokens needed to access the community*:
![2022-09-14 11_06_52-Kuba⎜Desktop – Figma](https://user-images.githubusercontent.com/22846356/190126076-575acd5a-444a-4a7f-a44b-54983f79da1c.png)
(link to figma https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2365%3A317901)
