### ISSUE TITLE
[Community Permissions] Add `Searcher` in collectibles dropdown

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7158]
### Description
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A484524

Acceptance Criteria:
- This component should be viewable and testable in storybook

**Comment by glitchminer** [comment]
Hi @iurimatias , please can you confirm if is this related only to storybook? Thanks

**Comment by noeliaSD** [comment]
It is related to the integration in the app as well, but right now using mocked data, and also it will be incorporated to storybook.
