### ISSUE TITLE
Community/Settings/Permissions - Holdings dropdown - Entering a large amount, switches to notation for long numbers

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7162]
### Description

In **Community Settings Permissions** view, when entering a really large amount of tokens or collectibles, it switches to notation for long numbers. 

See screenshot for better understanding:

![Screenshot 2022-08-26 at 17 04 07](https://user-images.githubusercontent.com/97019400/186935463-587b2e2b-179e-4419-b72f-10edf002d518.png)

**Comment by John-44** [comment]
I don't think we should make this change.  If not being able to support a number that is so long that it don't fit into the text entry box becomes a problem in the future, then design can find a better solution.  In the meantime I suggest that if the user tries to enter a number that is soo long the whole number doesn't fit into the text entry box, we just block this with an error message e.g. "Number cannot be longer than X digits".  This will do for the MVP, we can revisit post MVP.
