### ISSUE TITLE
User picture is not being displayed in profile , when being set during onboarding

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7165]
### Description

1. create new user
2. during onboarding, select any user picture to make it non-default
3. when logged in, open profile

<img width="1512" alt="Screenshot 2022-08-29 at 17 08 15" src="https://user-images.githubusercontent.com/82375995/187220815-aee0f8b0-c8a5-4096-bfc0-dbfe3ccfaf4e.png">

**Expected:** user picture is shown
**Actual:** default picture

**Comment by faust4exe** [comment]
Cannot reproduce the issue on commit 
```
b2485603de4daffcf0dc0fe1a487ea87a5dbdf81 (HEAD -> master, origin/master)
Date:   Fri Sep 2 17:56:14 2022 +0300
    fix(AppMain): Made all banners global and stacked
```
Tested on Linux 
  
https://user-images.githubusercontent.com/6445843/189172628-0179271d-cc84-43c3-95b4-1ff6f9c08c25.mp4

**Comment by faust4exe** [comment]
Also tested on MacOS

https://user-images.githubusercontent.com/6445843/189174393-110ce324-952e-446d-b45f-0fbd77f081d7.mov

**Comment by anastasiyaig** [comment]
i confirm it is fixed in latest master as of today :D
