### ISSUE TITLE
Can't copy and paste community share link

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7166]
### Description

1. create a community
2. open community modal -> copy the sharing link
3. paste it into public chat 

**As result**, pasting is not working

https://user-images.githubusercontent.com/82375995/187233682-eb654a84-6b56-4fd9-9a4f-9f1b50413f57.mov

**Expected**: i want this link to be pasted into the public chat

`https://join.status.im/c/0x02267180ddbb439f097d711ee6376f8235dacbb33159cb7a5c235aa0668c486508`

**Comment by faust4exe** [comment]
Cannot reproduce the issue on latest master
```
commit a1e7831dcb2091f47ea64be58c26b43a81659561 (HEAD -> master, origin/master, origin/HEAD)
Date:   Thu Sep 8 14:46:28 2022 +0200
    feat(@desktop/chat): add welcome message for community chats
```
Tested on Linux

https://user-images.githubusercontent.com/6445843/189353414-9dcba39f-e087-4a13-abb9-4c99db59d8aa.mp4

**Comment by faust4exe** [comment]
Tested on MacOS

https://user-images.githubusercontent.com/6445843/189355626-398d7a82-e38a-40c5-9d9a-cc6611427b85.mov

**Comment by faust4exe** [comment]
@anastasiyaig Please retest with latest master, looks like issue is already fixed

**Comment by anastasiyaig** [comment]
confirmed as fixed now, thank you @faust4exe !
