### ISSUE TITLE
Communities and chats are sometimes duplicated with no setting button

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#7167]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/11926403/187235392-c9413438-ef9c-4c0b-8856-0373960a1619.png)

## Details

This is most likely caused by the community sync.

The bug happened when importing an account using the seed phrase. That account had communities previously joined/administrated.

## Unclear steps

1. Create a new account
2. Create communities and join some as well
3. Backup the seed phrase somewhere
4. Close the app and delete (or change the name) of the data folder
5. Re-import that account using the seed phrase.
6. Wait for communities to come back in.

**Comment by cammellos** [comment]
Can replicate on my installation as well, unable to access settings

**Comment by jakubgs** [comment]
Nice, thanks.

**Comment by du64** [comment]
Can confirm, problem is solved.

**Comment by du64** [comment]
Still a problem, has not been fixed yet. Might want to reopen this issue.
It happened about a half hour later this time, along with a thing telling me it couldn't find a mailserver.
![Screenshot from 2022-10-06 22-37-53](https://user-images.githubusercontent.com/65834069/194462904-ae2d05c7-db1f-4c8b-86a5-c3d7b5ef8b6d.png)

**Comment by jrainville** [comment]
I can also replicate on RC2 

![image](https://user-images.githubusercontent.com/11926403/203086684-6a9af22b-2d45-46cc-9b6c-008152cae0d6.png)

**Comment by jrainville** [comment]
I'm investigating.
One intersting thing I found is that even with the same exact db (copy pasted it), I only reproduce it on a release build. If I build it myself in dev, the bug doesn't happen.
I even tried the latest master build and the issue is reproducible, while on a local build, it isn't. 
I'll continue investigating to try to find out why. (god why to I always get the issues related to release builds :neutral_face:  :gun: )

**Comment by caybro** [comment]
> I'm investigating. One intersting thing I found is that even with the same exact db (copy pasted it), I only reproduce it on a release build. If I build it myself in dev, the bug doesn't happen. I even tried the latest master build and the issue is reproducible, while on a local build, it isn't. I'll continue investigating to try to find out why. (god why to I always get the issues related to release builds neutral_face gun )

Interesting... maybe that's why I've never seen this happen myself

**Comment by jrainville** [comment]
Another update: it seems related to the DelegateChooser. I switched to a Loader and the problem doesn't happen. I just need to make the model passing work

**Comment by jrainville** [comment]
Alright, I fixed it here: https://github.com/status-im/status-desktop/pull/8440
