### ISSUE TITLE
Scrolling doesn't work automatically and user cannot see the entered chat message while typing

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7171]
# Bug Report

## Steps to reproduce
1. Go to the text chat and start to type some long messages there
2. Check the cursor and the scrolling of the chat message field

#### Expected behavior
The scroll in the chat message field works automatically and the user can see the text that he/she is typing and the cursor all the time
#### Actual behavior
The scroll in the chat message field doesn't work automatically and the user cannot see the text that he/she is typing.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/14942081/187267648-02b8183b-1e7c-4794-9d8c-f19dc8517b76.png">

https://user-images.githubusercontent.com/14942081/187267405-efe513b0-7d26-41e8-81ae-0d21322cec08.mov

### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by caybro** [comment]
I believe @faust4exe was just working on this?

**Comment by faust4exe** [comment]
> I believe @faust4exe was just working on this?

Yes - already fixed and merged to master.
