### ISSUE TITLE
New user cannot save changes in Settings - Profile

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7177]
# Bug Report

## Steps to reproduce
1. Sign up a new user
2. Go to Settings-Profile
3. Add some text to the field 'Bio' or any social networks' field
4. Check the appeared modal for saving changes

#### Expected behavior
In the modal, the button 'Save changes' is active and user can save the changes 

#### Actual behavior
In the modal, the button 'Save changes' is disabled and the user cannot save the changes 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/14942081/187330827-2d6e838e-bf96-4330-bf6d-f5e7d44cd267.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by caybro** [comment]
@osmaczko confirmed and reproduced

**Comment by osmaczko** [comment]
That's a regression, btw. there is a squish test which covers this exact case.
