### ISSUE TITLE
The message field is shown very close to the bottom edge of the new DM page

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7179]
# Bug Report

## Steps to reproduce
1. Sign in with a user who has at least one contact
2. Click on the Start chat icon and check the message field in the bottom part of the page

#### Expected behavior
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=112%3A26519
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/14942081/187346980-1ab0764b-7068-4d15-86bb-c31b69d3d660.png">

#### Actual behavior
The message field is shown very close to the bottom edge of the page
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/14942081/187346938-a96211a0-c477-4455-a8e7-f8dc5a128d23.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by caybro** [comment]
@elina2015 I can't reproduce with current (today's) master:

![Snímek obrazovky z 2022-09-01 11-33-25](https://user-images.githubusercontent.com/5377645/188010167-e0dacfb8-4596-4862-8041-12b55bc5c440.png)
