### ISSUE TITLE
Contact status is not accurate across UI

### ISSUE THREAD

**Issue by du64** [status-im/status-desktop#7180]
The contact information ("Not a contact" / "Trusted contact") is not reflected accurately across the app. In some places like the header it will never change, while in other places it shows the changes on mobile but not on the device it was supposed to.

![DeepinScreenshot_select-area_20220830012542](https://user-images.githubusercontent.com/65834069/187365288-37d939d4-c299-4d49-8486-1a3e6f9c3ccf.png)

**Comment by John-44** [comment]
@iurimatias @endulab  the 'Not a contact' and 'Contact' grey text in the header of a 1on1 chat should be removed (as with mutual contacts it will only be possible to 1on1 chat with mutual contacts, and therefor this text is superfluous.  Instead the User's username should be middle aligned relative to their avatar in the 1on1 chat header.

**Comment by caybro** [comment]
> @iurimatias @endulab the 'Not a contact' and 'Contact' grey text in the header of a 1on1 chat should be removed (as with mutual contacts it will only be possible to 1on1 chat with mutual contacts, and therefor this text is superfluous. Instead the User's username should be middle aligned relative to their avatar in the 1on1 chat header.

This is already done and fixed
