### ISSUE TITLE
Adding new fetching profile illustrations and animation to syncing profile in the onboarding workflow

### ISSUE THREAD

**Issue by ahowell3** [status-im/status-desktop#7191]
### Description

The existing placeholder illustrations require updating. Once the user has synced their profile they must wait for their profile to be fetched. The new fetching animation loops whilst this takes place. There is also a success/failure state both of which have static illustrations. 

The flow can be found in this Desktop Figma file: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=13653%3A450701

All assets can be found in this Drive folder: https://drive.google.com/drive/u/1/folders/1YXwHyaNPNqXTYVpdAben4qQdPBqLLx5m

Theres also a short storyboard of the animation flow along with details of the short transition from animation to static illustration in the above folder. 

<img width="1173" alt="Screenshot 2022-08-30 at 14 39 49" src="https://user-images.githubusercontent.com/43401360/187470533-d5ccb612-e392-4481-993f-2ee6abfd888a.png">

**Comment by iurimatias** [comment]
moving this to 0.9.0

**Comment by alexjba** [comment]
Not needed. See #8467
