### ISSUE TITLE
The Login with a Keycard page differs from the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7192]
# Bug Report

## Steps to reproduce
1. Go to Sign in
2. Select 'Add existing Status user'
3. Choose 'Login with Keycard'
4. Plug in an empty keycard
5. Check the page according to the Design

#### Expected behavior
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1023%3A298171
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/14942081/187554167-a968c27d-52fa-4b1e-b08a-9282ca39b766.png">

#### Actual behavior
1. The red text is smaller
6. The spaces differ from the Design
7. In the red text, the word 'keycard' should be started with a capital letter
8. The image differs from the Design
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/14942081/187553330-eebdb213-01f4-4428-b0d4-fe79f74e8d83.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by saledjenic** [comment]
Closing this cause all that has been change according to new figma design, done in #7646
