### ISSUE TITLE
'Create new Keycard PIN' page differs from the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7193]
# Bug Report

## Steps to reproduce
1. Go to Sign in
2. Select 'Add existing Status user'
3. Choose 'Login with Keycard'
4. Plug in an empty keycard
5. Click 'Generate keys for a new keycard'
6. Check the page according to the Design

#### Expected behavior
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1023%3A298171
<img width="589" alt="image" src="https://user-images.githubusercontent.com/14942081/187554955-546e9daf-b3fa-42ce-8027-f7f291db7bbd.png">

#### Actual behavior
1. The space differs from the Design
2. The text should be bigger and red colored
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/14942081/187554897-72d28d9b-b030-4130-a4d5-80a65df1556a.png">

### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by saledjenic** [comment]
I am not sure if this is relevant issue any more since lot of changes are applied in the #7629
