### ISSUE TITLE
It's impossible to create a new Keycard PIN

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7194]
# Bug Report

## Steps to reproduce
1. Click 'Add new user' - 'Generate keys for a new Keycard'
2. Plug in a reader and a new empty keycard
3. Wait

#### Expected behavior
The new Keycard PIN is created
#### Actual behavior
The page 'Create new Keycard PIN' and the loader  are shown infinitely
<img width="876" alt="image" src="https://user-images.githubusercontent.com/14942081/187559426-aa782b89-ae31-41f3-82ba-d831e64c3627.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by saledjenic** [comment]
@elina2015 would you mind trying the same again, but running the app from the terminal and recording entire testing and  provide the log file. Why I am asking that... cause there should be logged the steps you did and with them I can reconstruct everything you did and find out what was the issue. 

I've tried out to reproduce this and on my side it works fine. What I suspect is that maybe you clicked somewhere else and pin dots lost focus, if you didn't click explicitly anywhere on that screen focus should be on the first pin dot and you just need to press the number on your keyboard, if the focus is lost, just click on the first dot and enter the pin using keyboard, just to be sure if that's the issue.

**Comment by anastasiyaig** [comment]
cant reproduce it neither in latest master nor in https://github.com/status-im/status-desktop/pull/7246
