### ISSUE TITLE
After editing and saving a message the user cannot see it

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7195]
# Bug Report

## Steps to reproduce
1. Go to test chat
2. Add some message
3. Edit the message and click 'Save' or hit Enter

#### Expected behavior
The message is visible to the user
#### Actual behavior
The message went down and the user cannot see it
### Additional Information

https://user-images.githubusercontent.com/14942081/187566359-4783c012-ffdf-4fce-a835-5544ec990d6c.mov

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by faust4exe** [comment]
Looks like on latest master issue is not present
```
commit cdfbb4ac875ff3177082456aa8e7700e0bb270f4 (HEAD -> master, origin/master, origin/HEAD)
Date:   Tue Sep 6 12:45:16 2022 +0300
    fix(@desktop/chat): adjust mentions handing logic
```
Tested on Linux
https://user-images.githubusercontent.com/6445843/189389210-36fe97a3-04a1-48ca-baac-e9bb8491e1ab.mp4

**Comment by faust4exe** [comment]
Tested on MacOS
https://user-images.githubusercontent.com/6445843/189391241-32b5e094-69f2-470a-96c9-3f1b4f7a7d8e.mov

**Comment by faust4exe** [comment]
@elina2015 Can you retest the latest master , looks like issue is already fixed.

**Comment by elina2015** [comment]
@faust4exe I checked it on the latest master and the issue us not reproduced.
