### ISSUE TITLE
Not all accounts in the list have the hash ring on the accounts' Sign in list

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7196]
# Bug Report

## Steps to reproduce
1. Sign in a few accounts with an image and without it
2. Go to Sign in and open the list of the accounts
3. Check the hash ring

#### Expected behavior
All accounts in the list have the hash ring
#### Actual behavior
Not all accounts in the list have the hashring
<img width="553" alt="image" src="https://user-images.githubusercontent.com/14942081/187567050-76b56736-3d3b-489c-a052-5aa96428df54.png">

### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/212/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by endulab** [comment]
@elina2015 I can't encounter the problem in current master: 


![Image](https://user-images.githubusercontent.com/61889657/189314741-5b3fa280-d396-4ba1-8166-4b9c721668d2.png)

**Comment by elina2015** [comment]
Tested on the latest master and it's not reproduced
