### ISSUE TITLE
Add possibility for a quoted line to be surrounded by non quoted lines

### ISSUE THREAD

**Issue by faust4exe** [status-im/status-desktop#7207]
### Description

At the moment a simple line placed after a quoted line also becomes quoted.
And if a simple line is placed before a quoted line it will just not work as a quoted line.

Here you can see the comparison of Desktop, HackMD and Mobile versions, with 3 cases of placement of > (quote start)
![Screenshot from 2022-08-29 18-29-11](https://user-images.githubusercontent.com/6445843/187779401-2dfbcaab-1873-43ae-a9c0-6c0b23252289.png)

After some investigation I found this comment and code below which looks like is the code which needs to be updated 
```
// blockquote ends with at least one blank line
// followed by something without a blockquote prefix
func (p *Parser) terminateBlockquote(data []byte, beg, end int) bool {
```
it is located here https://github.com/status-im/markdown/blob/master/parser/block.go#L785 in `markdown` Go lib.

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
