### ISSUE TITLE
Consolidate date/time formatting

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#7230]
# Bug Report

## Description

Currently, in a lot of places, datetime  formatting is broken. 

Most of the formatting functions reside in `ui/imports/utils/Utils.qml`. Introduce a new module, `LocaleUtils.qml`, extract the relevant methods from `Utils.qml` and fix them, taking into account default values coming from QML `Locale` and `Date` objects. Options like short/long date formats and 12/24 hour format should be preserved.

- Status desktop version: All
- Operating System: All

**Comment by dlipicar** [comment]
Seems like the Currency part of this is solved in https://github.com/status-im/status-desktop/issues/8640
Linking for reference
