### ISSUE TITLE
Start chat - 5 user group limit is not enforced

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7240]
# Bug Report

## Description

Found during testing of https://github.com/status-im/status-desktop/pull/7057
It is possible to add more than 5 users in the To: field when starting chat

@osmaczko : 5 users limit is a design mistake, it should be 20

## Steps to reproduce

1. Add multiple contacts to To: field

#### Expected behavior
![image](https://user-images.githubusercontent.com/50769329/187042053-aa691fef-5818-47d1-ab67-7dc767c9be16.png)

#### Actual behavior
![image](https://user-images.githubusercontent.com/50769329/187042066-ca4ff354-aa6e-40d7-8eee-b4edbeaa1c6d.png)

### Additional Information

- Status desktop version: https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220905-082919-050a0b-pr7057.dmg
- Operating System: Mac

**Comment by du64** [comment]
Whats the reason for such a limitation, considering groups with hundreds of users already exist on Status?
I don't want communities, I just want one simple chat room for dozens of people.

**Comment by du64** [comment]
Nerfing groups to push an inferior and more complex offering without end to end encryption (Communities) is sad to see

**Comment by iurimatias** [comment]
@du64 there will be fully encrypted communities you can follow it [here](https://github.com/status-im/status-mobile/issues/12017), communities are far more flexible than groups, but groups will continue to exist.

**Comment by osmaczko** [comment]
The limit of 5 is a design mistake, it should be 20, at least for now, see: https://github.com/status-im/status-mobile/issues/13066

**Comment by du64** [comment]
> @du64 there will be fully encrypted communities you can follow it [here](https://github.com/status-im/status-mobile/issues/12017), communities are far more flexible than groups, but groups will continue to exist.

With flexibility comes complexity. I don't want a full community just for one chat to update a group of people with... It's the same reason I don't like Discord, besides lacking E2E encryption

**Comment by du64** [comment]
> The limit of 5 is a design mistake, it should be 20, at least for now, see: [status-im/status-mobile#13066](https://github.com/status-im/status-mobile/issues/13066)

Groups with 50 people would be awesome... Please don't patch the unlimited group member count hack on mobile haha
