### ISSUE TITLE
Communities portal: community tag is not shown

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7243]
### Description

Community , that was mapped to a contract, was created with tag. However, this tag is not shown

<img width="1512" alt="Screenshot 2022-09-06 at 11 41 58" src="https://user-images.githubusercontent.com/82375995/188594155-5f2ad393-0dd0-4d1b-b9b3-6fb4225d5933.png">

**Comment by alexandraB99** [comment]
@anastasiyaig could you please add steps to reproduce?

**Comment by anastasiyaig** [comment]
@alexandraB99 basically u need to:
create community with tags
copy its
public key
add this key to the contract that is responsible for the storing of these communities so they are shown in Featured
