### ISSUE TITLE
Figure out why some reply-to-messages are rendered incorrectly

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7248]
I've noticed after importing a discord community that some reply-to-messages are missing their details:

![Screenshot from 2022-09-06 12-40-44](https://user-images.githubusercontent.com/445106/188615354-139e750c-fca7-4fe7-8ea8-31b975d5eee3.png)

Haven't investigated this yet, but the first thing that comes to mind is that the reply-to-message is not available in memory, because we only fetch the last 20 messages of an active channel when the import is done.

If this turns out to be in fact the reason, that this is an issue unrelated to discord imports, but status in generell

**Comment by PascalPrecht** [comment]
So seems like this is not only happening when messages are not in memory. See the following screenshot.
The message I'm replying to is the first one in the screenshot yet, the reply message renders it as deleted:
![Screenshot from 2022-11-08 10-44-08](https://user-images.githubusercontent.com/445106/200531166-9c4fb079-68e0-491b-96ac-bcf7b3dbf641.png)

**Comment by PascalPrecht** [comment]
Here's another case:
![Screenshot from 2022-11-16 13-42-19](https://user-images.githubusercontent.com/445106/202183697-03a3bbe8-98bd-4480-8364-51bb1ab596d2.png)

**Comment by borismelnik** [comment]
@PascalPrecht if message was deleted you should see `<deleted>` as expected :)

**Comment by jrainville** [comment]
Added this issue to fix the deleted issue https://github.com/status-im/status-desktop/issues/8369
