### ISSUE TITLE
Wallet -> Activity tab: transaction history issues

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7278]
### Description

There are several issues with this screen:

1. when scrolling this list (with touchpad) -> the list is hardly scrollable
2. not trivial for user that there is Load More button in the bottom, especially when scrolling is pain
3. when clicking Load More -> no visual effect is happening, so user is not clear on what is the app doing -> is the history being fetched? We can add a "click" visual effect (pressed state) for the button and maybe a spinner to show the load is ongoing

<img width="1512" alt="Screenshot 2022-09-08 at 18 56 24" src="https://user-images.githubusercontent.com/82375995/189169407-6bb20102-e646-4086-9b00-ff8dd42ab66c.png">

**Comment by alaibe** [comment]
@anastasiyaig isn't this issue global, the touchpad is totally not working on the whole app AFAIR?

**Comment by anastasiyaig** [comment]
@alaibe when i was adding the issue, that was specific to the history but the scrolling functionality evaluates that fast so i cant really be sure now. most likely scrolling is broken in general

**Comment by Khushboo-dev-cpp** [comment]
The scrolling seems to be working okay for this screen, under a fix for this PR I can adding a loading indicator on the load more button to show that a fetch is ongoing

**Comment by Khushboo-dev-cpp** [comment]
ok so what I see is the loading button is there but its just to quick, I think these needs to be handled by the design first and then we can update instead of doing it twice @alaibe @anastasiyaig @John-44
