### ISSUE TITLE
[Onboarding] loading animation

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7292]
### Description

An animation moving from the last onboarding screen to the app view gets stuck. It should animate for all the time while everything gets completely loaded on the backend part.

**Comment by caybro** [comment]
Yeah, that's a general problem with the amount of "stuff" that we load once the user has logged in; probably not easy to fix w/o some major refactorings

**Comment by alexandraB99** [comment]
right, so this was changes [here](https://github.com/status-im/status-desktop/commit/70a1381e8606b975c829c9e63382033a23dd45ac) from @saledjenic. Do you think we should bring back the Timer instead?

**Comment by caybro** [comment]
I doubt the timer has anything to do with the animation being stuck

**Comment by saledjenic** [comment]
@alexandraB99 no, timer doesn't have anything with that issue, I am pretty sure that won't help. The thing with stucked loading animations originates most likely from the qml structure which loads everything on the app start and most of those calls communicate with status-go and it looks all that is happening in the main thread. So this issue is not that straightforward for fixing without some good plan and bigger change.

**Comment by caybro** [comment]
Well gave it a fast debug, the animation isn't actually stuck, it's properly unloaded because the main.qml enters the `Constants.appState.main` state, but it takes quite some time before AppMain is actually instantiated and rendered (that happens because we simply load almost everything at startup)

**Comment by osmaczko** [comment]
We should use QML Profiler to figure out the root cause. Until that we don't really know if this is strictly related to qml components creation. The event loop may be blocked by big amount of signals we handle synchronously in nim.

**Comment by alexandraB99** [comment]
@caybro @saledjenic  I didn't say the timer has something to do with the animation being stuck haha :'D I mean to switch back to timer because it wasn't stacking before! (even though it won't be realistic)
