### ISSUE TITLE
[Dialogs] fix content cut

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7293]
### Description

When dialogues scroll, the top and bottom of the body area should be cut off by the grey lines at the top and bottom.  But at the moment there is some white space at the top and bottom, things get cut off too early

Note: similar problem in `InviteFriendsToCommunityPopup`, but not directly related to Popups is covered by a separate task: https://github.com/status-im/status-desktop/issues/7606

![Screenshot from 2022-09-23 13-21-09](https://user-images.githubusercontent.com/20650004/191949897-bdc9fb26-0594-4384-9804-e0168ce1c19e.png)

**Comment by micieslak** [comment]
@alexandraB99 @John-44 I need more details about that issue. I cannot find figma designs covering that. I presume that it's about situation like on the screenshot, but it would be nice to have some reference in sigma.


![Image](https://user-images.githubusercontent.com/20650004/191839413-38338c7d-a2af-441a-b21b-00ba4ab07704.png)

![Image](https://user-images.githubusercontent.com/20650004/191839808-d33bca76-813c-4d34-abcb-3ec699155dfa.png)

**Comment by micieslak** [comment]
After discussion with John the issue from the first screenshot (snowman) is handled separately in https://github.com/status-im/status-desktop/issues/7525.
The issue from the second screenshot (community members list) is handled here: https://github.com/status-im/status-desktop/issues/7526
I'm also attaching relevant screenshot to the description.
