### ISSUE TITLE
[Members List] context menu is nos showing up

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7304]
### Description

Right clicking on members in the Member list is broken.  The context menu for a member should be displayed

**Comment by faust4exe** [comment]
Duplication of https://github.com/status-im/status-desktop/issues/7298 ?
Anyway looks like also fixed by https://github.com/status-im/status-desktop/pull/7329

**Comment by caybro** [comment]
Yup, another dupe :) Closing
