### ISSUE TITLE
Even though “show profile pictures to contact” non-contacts can see profile pictures of logged-in user

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7311]

**Comment by micieslak** [comment]
As agreed with @John-44 the whole section 
![Screenshot from 2022-09-22 13-25-29](https://user-images.githubusercontent.com/20650004/191782997-e630bc63-dd29-4560-a01e-e06ec31879c6.png)
will be removed (but some latter discussion is still needed). The default option is `everyone` in both cases, what is covered in https://github.com/status-im/status-desktop/issues/7310. Therefore this task is not relevant any more.

**Comment by micieslak** [comment]
As agreed with @John-44 the whole section 
![Screenshot from 2022-09-22 13-25-29](https://user-images.githubusercontent.com/20650004/191782997-e630bc63-dd29-4560-a01e-e06ec31879c6.png)
will be removed (but some latter discussion is still needed). The default option is `everyone` in both cases, what is covered in https://github.com/status-im/status-desktop/issues/7310. Therefore this task is not relevant any more.
