### ISSUE TITLE
[Messages] Adjust height when multiple messages are sent in less than 2 mins

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7318]
### Description

Where user messages are sent in a row (multiple messages sequentially within 2 mins without other users typing inbetween) - the messages should appear grouped. Adjust line height per the designs

**Comment by alexandraB99** [comment]
Closing as not reproducible:
![Image](https://user-images.githubusercontent.com/31625338/197798685-3175984c-3eed-4e6b-805f-54bb6e99fce7.png)

**Comment by benjthayer** [comment]
Rules for line height / padding for sequential versus multiline messaging. Any questions just shout!
<img width="1139" alt="Sequential-multiline" src="https://user-images.githubusercontent.com/110033914/200658020-0895ba79-968f-4dc2-a23b-13fcb0dfeb3d.png">
