### ISSUE TITLE
[User Profile] ens name issues

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7319]
### Description

User profile, when it has ENS it should be `@NAME.eth` - Should also not render identicon ring

**Comment by caybro** [comment]
@alexandraB99 which part is this pertaining to? (user profile dialog, user list, chat view, or just everywhere?). I also believe the ENS name is already prefered (when it's present), maybe bot everywhere

**Comment by caybro** [comment]
@John-44 need some clarifications please :) ^^

**Comment by osmaczko** [comment]
@caybro everyone with registered ENS should NOT have identicon ring rendered, also ENS name should take precedence over user name, see: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2034%3A217021

This should happen everywhere in the app where we display identicon ring or user name.

**Comment by John-44** [comment]
> @John-44 need some clarifications please :) ^^ Preferably with some links how it all should look like

@caybro @alexandraB99 @osmaczko answer to the question is everywhere where the user's name is displayed.  See this figma page ( https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=662%3A320379 ), it should cover most contexts.  

If there is something that isn't clear ping me tomorrow and we can hope on a quick call.

**Comment by endulab** [comment]
> @endulab would this be covered by your PR: #7428 ?

Nope, it's only about not-displaying identicon.
