### ISSUE TITLE
'Add new user' and 'Add existing Status user' have the wrong icons

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7323]
# Bug Report

## Steps to reproduce
1. Open Sign in page
2. Click on the arrow near the user's name for opening a list of items for actions

#### Expected behavior
'Add new user' and 'Add existing Status user' have the correct icons
<img width="470" alt="image" src="https://user-images.githubusercontent.com/14942081/189462942-60fa95dd-66d7-4018-92cc-57b1e47df2a1.png">
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1023%3A298171
#### Actual behavior
'Add new user' and 'Add existing Status user' have the wrong icons
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/14942081/189462899-929ad8d9-af6f-43cb-9a6e-b6f66040a39b.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/215/
- Operating System: macOS Monterey

**Comment by endulab** [comment]
Fixed in https://github.com/status-im/status-desktop/pull/7288. You can close.
