### ISSUE TITLE
There is no gap between emojis in the chat's message

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7324]
# Bug Report

## Steps to reproduce
1. Go to chat and enter in the message field a lot of emojis
2. Send the message

#### Expected behavior
There is some gap between the emojis in the chat's message
#### Actual behavior
There is no gap between emojis in the chat's message
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/14942081/189463894-f9ae26b2-08c1-4a69-97aa-fad8fdcbc561.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/215/
- Operating System: macOS Monterey

**Comment by alexjba** [comment]
Closing this based on the offsite meeting with design team.
Currently there is no need to add padding between lines that contain emojis and the effort to do it is too high considering there is limited support from Qt to do this.
