### ISSUE TITLE
Communities: empty screen when having 0 communities joined in Profile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7337]
### Description

<img width="1566" alt="Screenshot 2022-09-13 at 16 58 20" src="https://user-images.githubusercontent.com/82375995/189920924-3535256b-b373-4564-b49f-571eff6f4ca4.png">

@John-44 we might need a design for that

**Comment by elina2015** [comment]
@iurimatias @John-44 do we have a design for this case?

**Comment by jrainville** [comment]
Need to ask @benjthayer or @juliaiskandarian for designs on this one

**Comment by juliaiskandarian** [comment]
I found this one https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=4760%3A167454&t=B5OMggUlETPX9IdZ-1

<img width="993" alt="image" src="https://user-images.githubusercontent.com/109152754/205465731-0b771fde-399c-4477-b8da-0e1a5bd431bb.png">

**Comment by jrainville** [comment]
That sounds reasonable to me
