### ISSUE TITLE
It's possible to add an empty message to chat and add a reaction to it

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7343]
# Bug Report

## Steps to reproduce
1. Go to any chat or community
2. In the Message field enter a space or a few spaces, send the message
3. Add a reaction to this empty message

#### Expected behavior
All popular messengers are not allowing sending an empty message because they just add a gap between the tread of messages.
#### Actual behavior
1. The empty message is sent
2. The reaction is added
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/14942081/190055345-0590366a-6954-413c-9519-de3054dce617.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/216/
- Operating System: macOS Monterey

**Comment by alexandraB99** [comment]
@John-44 could you clarify, what should be the behavior here?

**Comment by alexandraB99** [comment]
@benjthayer could you clarify, what should be the behavior here?

**Comment by caybro** [comment]
I believe this is fixed already in master; empty messages can no longer be sent

**Comment by jrainville** [comment]
Indeed, I also tested and I no longer can send empty messages
