### ISSUE TITLE
Account selector identicons are broken in login screen

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7344]
Check this out:

![Screenshot from 2022-09-14 10-35-58](https://user-images.githubusercontent.com/445106/190104622-8650fed8-ff93-4aa2-95f8-eeb9c6071705.png)

"Add new user" option used to have an icon
"Add existing user" option used to have an icon as well, but now uses letter identicon

**Comment by alexandraB99** [comment]
@PascalPrecht I belive this is already fixed in master, could you please check again?

**Comment by PascalPrecht** [comment]
@alexandraB99 Can confirm that this is no longer reproducible on latest `master`
Closing.
