### ISSUE TITLE
Wallet: collectibles are not displayed in status app while showing fine in Ledger

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7347]
### Description

I am able to see my Collectibles for account when checking it in Ledger app. However, to see them in Status app, i need to use VPN (because OpenSea banned my location )

We need to investigate why Ledger is not 

<img width="1909" alt="Screenshot 2022-09-14 at 12 57 57" src="https://user-images.githubusercontent.com/82375995/190130503-d6ae8fbb-7d9e-4142-8605-330d4dc8890d.png">

**Comment by alaibe** [comment]
In order to validate that ledger use a server, could u use a tool that inspect connection made remotely.

It might be because ledger call opensea via their server and we call opensea directly
