### ISSUE TITLE
Pasting an image from clipboard to chat doesn't work

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#7354]
# Bug Report

## Steps to reproduce

1. Copy an image to clipboard
2. Open any chat in status-desktop
3. Press `Cmd+V` (or `Ctrl+V` on windows)

#### Expected behavior

Image is pasted into message, just the same as it would be chosen from Finder window

#### Actual behavior

Nothing happens

### Additional Information

- Status desktop version: 0.6.0 `a1e7831dc`
- Operating System: MacOS 12.5

**Comment by flexsurfer** [comment]
it's like #1 feature for dogfooding, @iurimatias could we rise a priority?

**Comment by jrainville** [comment]
Duplicate of https://github.com/status-im/status-desktop/issues/3395
@flexsurfer I assigned Pascal to work on it this iteration :smile:

**Comment by caybro** [comment]
Duplicate of https://github.com/status-im/status-desktop/issues/3395
