### ISSUE TITLE
New Profile Modal

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7360]
### Description

figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=4%3A23932

figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=4%3A23932

Contact profile
![Screen_Shot_2022-09-14_at_10 02 13_AM](https://user-images.githubusercontent.com/176720/190255672-4f4d7f58-e2c5-4f7d-9f2d-dc31512ba0e4.png)

Own profile

<img width="654" alt="Screen Shot 2022-09-14 at 4 29 55 PM" src="https://user-images.githubusercontent.com/176720/190256259-f0d98c8a-00fc-4981-933d-703e09938481.png">

The profile modal should be replaced with the new one.
note: other sections shown in the design such as NFTs, accounts, etc.. are out of scope

**Comment by elina2015** [comment]
@caybro hey, there are some small issues found. Could you kindly check?
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/14942081/195248903-eb3433f5-d1c9-4b8b-ae34-630295fe321f.png">
