### ISSUE TITLE
The `Import Community` button needs to look like other buttons

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7362]
# Bug Report

profile -> apps -> communities

The `Import Community` button needs to look like other buttons

Design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1511%3A137580

![Screen Shot 2022-09-14 at 4 37 39 PM](https://user-images.githubusercontent.com/176720/190257716-2c416f90-239d-4ee4-beb2-4cfb02eb7f70.png)

![Screen Shot 2022-09-14 at 4 37 41 PM](https://user-images.githubusercontent.com/176720/190257733-f4be73c4-ee0e-463b-bdd1-25c5c8e97213.png)

**Comment by caybro** [comment]
@iurimatias link to design? This button has an explicit "small" type assigned, so it indeed looks a bit different (smaller)

**Comment by caybro** [comment]
List items design is off too
