### ISSUE TITLE
Mutual Contact Requests should be displayed in the activity center

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7363]
# Bug Report

figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1424%3A327656

## Steps to reproduce

1. Receive a request to join a community
2. go to activity center

#### Expected behaviour

Item displaying request. option to accept or reject.

**Comment by MishkaRogachev** [comment]
Resolved here:  https://github.com/status-im/status-desktop/pull/7620

**Comment by elina2015** [comment]
Tested on Master: https://ethstatus.testrail.net/index.php?/runs/view/10377&group_by=tests:status_id&group_order=asc
