### ISSUE TITLE
Profile icons not shown in “invite contacts to community” popup

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7364]
# Bug Report

## Description

![upload_1e22575f913a4c2e3c9c27d3d4637034](https://user-images.githubusercontent.com/176720/190260122-24cea06c-2739-442f-9109-0bc1a8989183.png)

**Comment by caybro** [comment]
@endulab just stumbled upon this, there's another bug, it shows users that _are_ already members of the community, because:

```
qrc:/imports/shared/views/ExistingContacts.qml:78: TypeError: Property 'hasMember' of object QQmlDMAbstractItemModelData(0x726fd80) is not a function
```
