### ISSUE TITLE
Communities portal categories have some gradient in dark theme

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7368]
### Description

<img width="886" alt="upload_c75473b0544a2e846fec614273e1de45" src="https://user-images.githubusercontent.com/176720/190262870-55641ff9-68bf-4a9c-b90b-684e090623d8.png">

**Comment by caybro** [comment]
This is like a third time this has been reported :) Can't find the dupes now :/

**Comment by alexandraB99** [comment]
closing as duplicate https://github.com/status-im/status-desktop/issues/7257
