### ISSUE TITLE
Mute button the chat list is not working

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7370]
# Bug Report

## Description

![upload_103b0e33df2ed5a5392800e8b44d6a0b](https://user-images.githubusercontent.com/176720/190263222-7c987ca0-26ea-4ac8-b94e-65e01a3ed207.png)

## Steps to reproduce

1. mute the channel
2. hover mouse over channel and click icon

#### Expected behavior

should unmute channel

**Comment by caybro** [comment]
Already got a fix locally :)
