### ISSUE TITLE
Identity Verification Requests should be displayed in the activity center

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7373]
# Bug Report

figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1424%3A327656

## Steps to reproduce

1. Receive a identity verification request
2. go to activity center

#### Expected behaviour

Item displaying request. option to accept or reject.

Acceptance Criteria:

- Identity verification requests **received** are shown in the AC
  - "Answer" button is shown. Clicking on it shows the Identity request popup
  - Once the answer is sent from the AC or from an extrenal answer, the AC notif should show "Edit Answer". Clicking it shows the popup again where you can edit your answer
  - Once the sender approves the verif, the AC notif shows "Verification Complete" (not clickable)
- Identity verification requests **sent** are shown in the AC
  - The label "Sent" is shown (not clickable)
  - Once the user responds to the request, the answer is shown. (See design). The "Verify Identity" button is shown. Clicking on it takes you to the Identity verification popup where you can Verify, decline or mark untrustworthy
  - When the request is verified, the AC shows "Identity Verified" in green. (not clickable)
  - When the request is declined, the AC shows "Verification Request Declined" in red (no clickable)
  - When the request is marked untrustworthy, the AC shows "Marked Untrustworthy" in red (not clickable)

**Comment by richard-ramos** [comment]
Related status-go PR
https://github.com/status-im/status-go/pull/2831

**Comment by MishkaRogachev** [comment]
Blocked by https://github.com/status-im/status-desktop/pull/8380

**Comment by MishkaRogachev** [comment]
Fixed here: https://github.com/status-im/status-go/pull/3029

**Comment by elina2015** [comment]
Tested and approved
