### ISSUE TITLE
When banned in community user needs some sort of notification and/or visual clue

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7374]
# Bug Report

## Steps to reproduce

1. join a community
2. have admin ban

result: community is still visible

**Comment by iurimatias** [comment]
needs the join workflow to be done first

**Comment by jrainville** [comment]
Is there a design for this? If not, @pedro-et do you have an idea of what we should show for the banned user?

**Comment by borismelnik** [comment]
@jrainville can i get it to work?

**Comment by jrainville** [comment]
@borismelnik you can start. I'm just not sure what the wanted behaviour is. You can check Figma and/or talk with Pedro

**Comment by borismelnik** [comment]
@borismelnik waiting for design from @pedro-et

**Comment by jorge-campo** [comment]
> Is there a design for this? If not, @pedro-et do you have an idea of what we should show for the banned user?

@jrainville, @borismelnik in the mobile designs, we send a notification when a user is kicked out from a community, but we don't send any notification when the user is banned; this is intentional. The user can still search for the community, though. I guess the workflow should be the same for desktop

You can check the Figma mobile designs [here](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=7674%3A521368&t=3JDVFco05zFPSL2r-0).

**Comment by borismelnik** [comment]
I'm still waiting some design from @pedro-et

**Comment by pedro-et** [comment]
@borismelnik its like @jorge-campo says: no design needed as nothing is sent to the banned user.

**Comment by borismelnik** [comment]
Okay I got it :)

**Comment by jrainville** [comment]
Closing this since it is intentional to not show a banned user that he is banned

**Comment by jrainville** [comment]
@pedro-et I see in the design that there is this screen for banned users: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?node-id=7674%3A521411&t=F1InDIoXMBwETcsq-0

Is that old design? If I understand what you said, we don't even tell a banned user that he was banned.

**Comment by jorge-campo** [comment]
> Closing this since it is intentional to not show a banned user that he is banned

Hey @jrainville, it's not exactly like that. Allow me to explain:

1. **Kick out** someone - The user receives a notification and sees the "Kicked" pill when they try to open the community again.
2. **Ban** someone - The user doesn't receive a notification but sees the "Banned" pill when they try to open the community again.

These Figma designs are current and valid.

Hope this helps!

**Comment by jrainville** [comment]
Ah ok, yeah I misunderstood. Reopening
