### ISSUE TITLE
“Jump to” button doesn’t work in pinned messages popup

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7375]
# Bug Report

## Description

<img width="547" alt="upload_8d98732e4f57c1ef2e14b8b739db2c00" src="https://user-images.githubusercontent.com/176720/190266448-588eaf3e-9cf4-435a-aaab-e2977ca014db.png">

## Steps to reproduce

1. pin some messages
2. go to pinned messages right click and select jump to

**Comment by caybro** [comment]
Was never implemented
