### ISSUE TITLE
refusing an identity request doens’t seem to do anything

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7377]
# Bug Report

## Steps to reproduce

1. have other user send an identity request
2. refuse identity request

Doesnt' seem to do anything. we should review the workflow to see what is the correct behaviour.

**Comment by PascalPrecht** [comment]
To be clear #8277 is about **accepting** contact requests. I haven't checked if this happens for declining requests as well.

**Comment by caybro** [comment]
> To be clear #8277 is about **accepting** contact requests. I haven't checked if this happens for declining requests as well.

It does, same issue, similar error msg for me

**Comment by MishkaRogachev** [comment]
Fixed here: https://github.com/status-im/status-desktop/pull/8246
