### ISSUE TITLE
Strange behaviour with group chats

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7381]
# Bug Report

## Description

Often removing a user and re-adding that same user results in strange behaviour where not all messages are visible anymore. we should confirm if this happens in mobile as awell since then it would indicate this is happening at the status-go level.

**Comment by osmaczko** [comment]
Expected behavior:
- when user joins existing group chat he can't see the history prior to that
- when user leaves and joins group chat he can't see messages written in between

**Comment by osmaczko** [comment]
@richard-ramos could you please check what is the result for status-desktop for the same scenario?

**Comment by richard-ramos** [comment]
I executed the same scenario in status-desktop, and got the same result

**Comment by iurimatias** [comment]
@richard-ramos we can still replicate the issue, it's possible it might be waku v2

**Comment by jrainville** [comment]
@osmaczko any chance your group chat fixes fixed this?

**Comment by osmaczko** [comment]
@jrainville yes, most likely. This scenario was tested last week with a group of 4 ppl a couple of times. Nevertheless, it could be that we didn't have enough "luck" to reproduce it.

I would close it for now and reopen if it happens again.

**Comment by jrainville** [comment]
Closing as completed by Patryk. Re-open if the issue re-happens
