### ISSUE TITLE
[Communities] “Transfer ownership” button for community is missing

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7411]

**Comment by iurimatias** [comment]
moved to 0.13.0, needs design

**Comment by alexandraB99** [comment]
@benjthayer please update when there's more news regarding this

**Comment by benjthayer** [comment]
@alexandraB99 this flow is currently under review with John. Some final tweaks required - should be ready early next week.

**Comment by alexjba** [comment]
Handled by https://github.com/status-im/status-desktop/issues/11319. It's already implemented.
