### ISSUE TITLE
[Communities] Transferring key, user cant edit channel in the sidebar, but option shows after restart app

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7413]

**Comment by endulab** [comment]
Related to #7414.
Blocked by: https://github.com/status-im/status-go/issues/2878

**Comment by endulab** [comment]
Will be fixed in #7414

**Comment by elina2015** [comment]
Tested and approved

**Comment by jrainville** [comment]
Got merged in https://github.com/status-im/status-desktop/issues/7414
