### ISSUE TITLE
[CommunitiesPortal] Banner is missing in community portal cards

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7417]
### Description

Figma design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=8159%3A415655

**Comment by micieslak** [comment]
@alexandraB99 I need more details about that. I'm looking here: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2563%3A532867 but there are no banners. Am I missing sth?

**Comment by micieslak** [comment]
Ok, after discussion with John I have a proper figma design for that, attaching to the description.
