### ISSUE TITLE
“I-beam” cursor over “Contact” label in profile button above the chat

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7419]
### Description

<img width="151" alt="b" src="https://user-images.githubusercontent.com/31625338/190683354-afefaaf7-d8b4-4a61-9bb9-529b5f1a8d57.png">

**Comment by caybro** [comment]
@alexandraB99 debatable... the text is selectable by mouse(`StatusSelectableText` component), so it is the correct cursor to display. The other option would be to just use `StatusBaseText` component here.

**Comment by Khushboo-dev-cpp** [comment]
@caybro this was done a ling time back before the whole revamp of designs for chat and community, in case that this is not a requirement for the user anymore as per design, we can just use the StatusBaseText now.
