### ISSUE TITLE
Wallet -> Send: Can't send asset , no network available shown

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7429]
### Description

```
qrc:/imports/shared/views/AssetsDetailView.qml:85: TypeError: Cannot read property 'timeRangeTabBarIndex' of null
```

<img width="1427" alt="Screenshot 2022-09-19 at 14 04 56" src="https://user-images.githubusercontent.com/82375995/191003994-a2e182f4-2c8d-4374-9776-360c6fa55cef.png">

**Comment by caybro** [comment]
That warning is unrelated though

**Comment by anastasiyaig** [comment]
@caybro that is all that is weirdly shown in console, so i decided to attach it anyway :(
