### ISSUE TITLE
Community: accepted invitation is shown as pending

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7437]
### Description

1. get an invitation to join a community that requires approval in chat
2. click Send Request button
3. approve this request as community owner

As result, the invitation bubble is always shown as Pending, even though the user is accepted to join

<img width="1283" alt="Screenshot 2022-09-19 at 17 17 07" src="https://user-images.githubusercontent.com/82375995/191039116-b6634cb0-85bb-4762-8079-3dbb2cc77a93.png">

**Comment by iurimatias** [comment]
this issue might no longer be relevant after https://github.com/status-im/status-desktop/issues/7072

**Comment by borismelnik** [comment]
No longer relevant cos of invitation bubble always display `Go To Community`
