### ISSUE TITLE
Add option to create encrypted community

### ISSUE THREAD

**Issue by cammellos** [status-im/status-desktop#7446]
As a user
I want to be able to create an encrypted community
So that I can make sure nobody who's not a member can read the messages

### Description

We just added support for encrypted communities, the user should be presented with a checkbox that allows to enable encryption when creating the community.

https://github.com/status-im/status-go/blob/eb4ab9316cc0f0ba07b01b4177bd50bdfc3ae33a/protocol/requests/create_community_request.go#L46 can be set to `true` if the checkbox is enabled.

Only communities with a concept of membership should have this option (regardless of whether is manual or automatic approval)

**Comment by cammellos** [comment]
cc @John-44

**Comment by du64** [comment]
I think this should be the default setting, because otherwise communities would be just as insecure as Discord servers
