### ISSUE TITLE
When sending invitations to multiple contacts, they're all duplicated to one contact

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#7455]
# Bug Report

## Description

NOTE: 
This can only be tested above this PR: https://github.com/status-im/status-desktop/pull/7454, because invitations weren't sent at all.

https://user-images.githubusercontent.com/25482501/191323354-e560029f-ebd5-4089-a795-d255fe7547b1.mov

**Comment by iurimatias** [comment]
@igor-sirotin is this still happening?
