### ISSUE TITLE
Identicon shows up in chat tool bar when accepting a contact request

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7467]
I've received a contact request, accepted it, this opens a 1-on-1 chat

![Screenshot from 2022-09-21 16-46-50](https://user-images.githubusercontent.com/445106/191537600-3699087b-d541-446d-8c1e-8936c45ee642.png)

Notice how it shows an identicon on the chat toolbar. It shouldn't be there.

**Comment by caybro** [comment]
Before rename:
![Snímek obrazovky z 2022-09-21 16-55-11](https://user-images.githubusercontent.com/5377645/191538622-4c3ee216-0c47-44fe-b113-b05184a429d5.png)

After rename:
![Snímek obrazovky z 2022-09-21 16-55-20](https://user-images.githubusercontent.com/5377645/191538615-c62109b4-3b50-44e2-9f69-c91c2ea9574d.png)

**Comment by caybro** [comment]
Notice how also the rename nick isn't propagated, but the icon is

**Comment by iurimatias** [comment]
duplicate

**Comment by PascalPrecht** [comment]
@iurimatias can you please link the original issue that this one is a duplicate of?
I'd like to track this as we still have it in latest `master`
