### ISSUE TITLE
Settings -> Messaging -> Contacts: contacts list is not scrollable

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7469]
### Description

Having more than 5-6 contacts, resize the app and try to scroll the list

<img width="1362" alt="Screenshot 2022-09-21 at 17 52 44" src="https://user-images.githubusercontent.com/82375995/191537819-fcfac9fa-a31e-46ec-94a3-6e5f56c48424.png">

**Comment by caybro** [comment]
Can no longer reproduce with https://github.com/status-im/status-desktop/pull/7485
