### ISSUE TITLE
create community, blank channel before restart (possible duplicate)

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7470]
# Bug Report

## Description

![Screen Shot 2022-09-21 at 10 54 34 AM](https://user-images.githubusercontent.com/176720/191538299-db53d370-0bbd-4bc8-a44f-057001b9df15.png)

**Comment by anastasiyaig** [comment]
duplicate

**Comment by PascalPrecht** [comment]
@anastasiyaig please link the duplicate issue

**Comment by anastasiyaig** [comment]
lol i am not sure why it was not posted :D Fixed!
