### ISSUE TITLE
"Send contact request to chat key" label is too small

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7471]
Compared to all other button labels, this one seems smaller

![Screenshot from 2022-09-21 16-54-23](https://user-images.githubusercontent.com/445106/191538359-2b5f4f3a-231f-4c0e-92ad-bd4ba5af4f10.png)

**Comment by alexandraB99** [comment]
@PascalPrecht could you please double check and close if not valid anymore?

**Comment by PascalPrecht** [comment]
@alexandraB99 Yes, but I need to know where this is in figma files. Having a hard time finding stuff.
Created #7753 accordingly. Can you help out?
