### ISSUE TITLE
Action buttons for accepting/rejecting contact requests should be identical in different places

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7473]
When receiving a contact request, there's multiple places where they can be accepted. 

Here's one:

![Screenshot from 2022-09-21 16-57-12](https://user-images.githubusercontent.com/445106/191539023-3ca58582-0b17-4e91-86cf-160ff21869a7.png)

Here's another one:

![Screenshot from 2022-09-21 16-57-34](https://user-images.githubusercontent.com/445106/191539035-45b80c5b-26fb-444d-b67f-2e00ac4f5900.png)

Notice how they have the action buttons swapped out.

**Comment by John-44** [comment]
The dialogue in the image below should be removed from the product as soon as the Activity Centre that @MishkaRogachev is currently working on is ready.
![191539023-3ca58582-0b17-4e91-86cf-160ff21869a7](https://user-images.githubusercontent.com/22846356/193096627-e5a52c75-ead5-4626-8de5-656cda6174bf.png)

The 'Pending Requests' entry for contact requests (found inside Settings/Messaging/Contacts) shown in the image below matches the design and is correct.
  
![191539035-45b80c5b-26fb-444d-b67f-2e00ac4f5900](https://user-images.githubusercontent.com/22846356/193097903-51ab5d6d-58ec-4e9a-acd5-0ba190e4f5c6.png)

So I don't think anything needs to be fixed here.

@PascalPrecht @iurimatias @alexandraB99 @micieslak

**Comment by micieslak** [comment]
The situation looks clear. I'm closing the issue.

**Comment by PascalPrecht** [comment]
Thanks for clarifying!
Should the action buttons still be swapped though?
Feels weird to have the reject button coming first.

**Comment by caybro** [comment]
> Thanks for clarifying! Should the action buttons still be swapped though? Feels weird to have the reject button coming first.

I still swapped them in my WIP PR #7621 since I need to display the panel inside the new Profile Modal

**Comment by John-44** [comment]
> > Thanks for clarifying! Should the action buttons still be swapped though? Feels weird to have the reject button coming first.
> 
> I still swapped them in my WIP PR #7621 since I need to display the panel inside the new Profile Modal

Super :-)
