### ISSUE TITLE
Contact request: the text of contact request is shown as push notification when contact request is accepted

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7475]
### Description

1. send a contact request
2. wait it to be accepted
3. check the push notifications
4. check the activity center

<img width="1404" alt="Screenshot 2022-09-21 at 18 03 27" src="https://user-images.githubusercontent.com/82375995/191540640-ff8773dc-80cb-4660-bc3b-b92ea22992d4.png">

**Comment by MishkaRogachev** [comment]
Resolved here: https://github.com/status-im/status-desktop/pull/7620
