### ISSUE TITLE
Back from sleep don t show icon

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#7486]
![image](https://user-images.githubusercontent.com/491074/191564732-8bfb6c09-e030-4974-bc68-384f6020701b.png)

**Comment by caybro** [comment]
This looks like a gfx driver problem (Mesa)

**Comment by alaibe** [comment]
No specific trick to make it happen. All I can say is: this is the only app where I have this behaviour

@caybro is there anything I could try to reveal more info?

**Comment by caybro** [comment]
> No specific trick to make it happen. All I can say is: this is the only app where I have this behaviour
> 
> @caybro is there anything I could try to reveal more info?

I don't think so; nothing other than "update your distro" :)

**Comment by alaibe** [comment]
I am quite close to the latest:
Ubuntu 22.04.1 LTS

and my nvidia driver is: 510 which is not latest but quite close too!

**Comment by caybro** [comment]
> I am quite close to the latest: Ubuntu 22.04.1 LTS
> 
> and my nvidia driver is: 510 which is not latest but quite close too!

Oh nvidia... it's notorious for having these kind of problems after suspend/resume

**Comment by caybro** [comment]
> alright then, we can close if this not related to us. The only thing I find weird is that telegram (which is made with QT too) don't have this problem

Yeah... hard to tell w/o seing the source; also they likely ship their own Qt version
