### ISSUE TITLE
AC: "Hide read notifications" should be sticky

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#7489]
# Bug Report

Currently it doesn't remember it had been checked before; so it always shows all notifications when the popup is reopened.

![Snímek obrazovky z 2022-09-21 20-45-19](https://user-images.githubusercontent.com/5377645/191585721-16ec4f29-6761-48b3-8bd9-339f72aa624e.png)

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by caybro** [comment]
CC @MishkaRogachev

**Comment by MishkaRogachev** [comment]
Resolved here: https://github.com/status-im/status-desktop/pull/7523
