### ISSUE TITLE
Start chat - No indicator that when there are no results

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7495]
# Bug Report

## Description

After going to Start Chat and entering text in the To field that does not match any contacts the user is not informed that there are no results to the filter.

![image](https://user-images.githubusercontent.com/50769329/191602793-22f0ee5d-e9fe-4451-b18f-03a8cbfe5fc4.png)

## Steps to reproduce

Start Chat
Enter text in To: field that does not match a contact

#### Expected behavior

User knows that reason nothing is happening is because there are no results

#### Actual behavior

No action

### Additional Information

- Status desktop version: Master 21 Sept.
- Operating System: Mac

**Comment by osmaczko** [comment]
Offsite discussion: context modal should always appear but contain "no results found" info in that case.
