### ISSUE TITLE
Activity Center item with lots of mentions overlaps next item

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7497]
# Bug Report

## Description

<img width="591" alt="Screen Shot 2022-09-21 at 6 08 38 PM" src="https://user-images.githubusercontent.com/176720/191619443-f3909f73-450c-4451-b752-fcaeb8688624.png">

**Comment by MishkaRogachev** [comment]
Fixed here: https://github.com/status-im/status-desktop/pull/7523
