### ISSUE TITLE
Activity Center item  replies original messages are blank

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7499]
# Bug Report

## Description

<img width="594" alt="Screen Shot 2022-09-21 at 6 08 46 PM" src="https://user-images.githubusercontent.com/176720/191619532-cfb4c325-8354-4ed5-b007-5d0225c2b42b.png">

**Comment by MishkaRogachev** [comment]
Fixed here: https://github.com/status-im/status-desktop/pull/7523
