### ISSUE TITLE
Contact request: can't accept contact request after the app was restarted

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7503]
### Description

I've left the app over night and when i started it again, a contact request appeared which i cant accept

<img width="1404" alt="Screenshot 2022-09-22 at 09 22 25" src="https://user-images.githubusercontent.com/82375995/191674274-f8e87752-00e7-4b2a-9ac7-a3609e340eaf.png">

**Comment by jrainville** [comment]
@anastasiyaig I just tried this and the contact request was accepted correctly.

Just to be sure, the steps were:
1. Desktop account (DA) sends a message in `#test`
2. Put desktop in sleep
3. Mobile Account (MA) sees the message in `#test` and sends a contact request (adds to contact)
4. Reopen desktop
5. DA receives the contact request
6. DA accepts

Can you try again and if it happens, give me the logs. I assume something would have bugged and shown an error.

I tested on latest master (`2e05a9784e36c4e0bc2baa54e0ede7489895e318`)

**Comment by anastasiyaig** [comment]
@jrainville i tested it but just forgot to reply :D Closing it
