### ISSUE TITLE
Text replied to is truncated

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#7504]
![image](https://user-images.githubusercontent.com/33099791/191676839-2ee855f7-8fbb-4062-85c4-13309b7b92e1.png)

**Comment by iurimatias** [comment]
this might intended

**Comment by caybro** [comment]
it should at least elide, even if it's meant to occupy at most 1 line

**Comment by caybro** [comment]
So, after some investigation: the text can't elide as `StatusTextMessage` uses a readon-only `TextEdit` which hasn't this capability; so it's simply `clip`ped

**Comment by jrainville** [comment]
iirc from the offsite, we decided to remove the RichText parsing and use elide instead, but I might be wrong. Can someone  remember and confirm? I think @igor-sirotin or @osmaczko asked the question

**Comment by caybro** [comment]
Yes, it's now faded away

**Comment by osmaczko** [comment]
> iirc from the offsite, we decided to remove the RichText parsing and use elide instead, but I might be wrong. Can someone remember and confirm? I think @igor-sirotin or @osmaczko asked the question

I don't remember this exact discussion. Since we should be able to jump back to the original message I think the "elide" option is enough.

**Comment by jrainville** [comment]
Fixed by Igor
