### ISSUE TITLE
Keycard: setting up a new account with keycard on Linux ends up with biometrics screen

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7505]
### Description

Biometrics screen should be shown only for MacOS

![image](https://user-images.githubusercontent.com/82375995/191684095-307f7d60-a42e-4883-9cf0-2b71227eb837.png)

**Comment by anastasiyaig** [comment]
@richard-ramos was the one who encountered it, i dont have linux sadly

**Comment by saledjenic** [comment]
@anastasiyaig I am not sure if this is the relevant issue any more, what we're checking in all places you can get to the biometrics screen from is something like this:
```
if not defined(macosx):
  return
go to biometrics screen
```
so we're going to biometrics only if it's a mac os.
