### ISSUE TITLE
[Community] Update back up popup UI

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7511]
### Description

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2927%3A348534

**Comment by iurimatias** [comment]
moved to 0.13.0, needs design

**Comment by alexandraB99** [comment]
@benjthayer please update when there's more news regarding this

**Comment by alexjba** [comment]
Handled by https://github.com/status-im/status-desktop/issues/11319. It's already implemented.

**Comment by alexandraB99** [comment]
@benjthayer could you please check/confirm whether this is still needed?

**Comment by alexandraB99** [comment]
@benjthayer reminder

**Comment by benjthayer** [comment]
Hey @alexandraB99 I'm not sure what this refers to. The Figma link in the desc doesn't appear work - it may be that the relevant frame in the design has been removed / replaced. Do we have any additional information on what is required for this one?

**Comment by alexandraB99** [comment]
@benjthayer not sure either, I think it refers to the back up community popup?

**Comment by alexandraB99** [comment]
@John-44 is this issue still valid? do we have to update any back up community popup? cc @benjthayer
