### ISSUE TITLE
GIFs play forever

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#7518]
# Bug Report

## Description

GIF animations, when embedded/sent as a message, keep on playing/looping forever. I reckon they should stop after a couple of iterations, and only replay on click

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by caybro** [comment]
@iurimatias Discord does stop after some time

**Comment by alexandraB99** [comment]
@benjthayer would like some input here on the GIFs behavior, are we supposed to be playing the GIFs all time, or we could stop those after some time in order to gain in performance? could you please specify the behavior?

**Comment by benjthayer** [comment]
I checked in with @John-44 on this - although the constant looping makes the channel/chat feel more active/alive, to help with CPU it might be best to limit the gifs to a few loops and then stop. The user could then replay the gif with the same number of loops by clicking the gif.

If we do go that route, the question becomes what interaction the user can leverage to restart the gif looping. On WhatsApp they obviously have a centred watermark GIF button which does this. A reason to include an explicit button like that is to give the affordance to the user that clicking it will re-loop the animation as opposed to opening the media in the expanded lightbox form.

Currently our Tenor gifs have a Tenor title and URL bar at the base. Is that something we plan to keep or is the aim to remove this per Discord/WhatsApp etc? If so, there would be even more reason to have an explicit CTA to identify the media as a GIF and reinitiate the loop.

**Comment by alexandraB99** [comment]
@benjthayer we can try adding a CTA, could you provide me with a design solution for this please?

**Comment by benjthayer** [comment]
No problem @alexandraB99. Is there a way to remove the Tenor bar at the base of the gifs per Discord, WhatsApp and the new mobile and desktop designs? 

The reason I ask is, adding a GIF button while the Tenor banner is still presented at the base of the gif duplicates the cue/affordance to the user that the media is a gif and not an image. If, for technical reasons, we need to keep the Tenor banner at the base of the gif, we may want to do something more subtle - say a replay icon in the corner of the gif.

<img width="384" alt="Screenshot 2023-01-19 at 17 42 07" src="https://user-images.githubusercontent.com/110033914/213520038-b9550747-aa0c-46d1-9a56-d797bd138bd2.png">

**Comment by benjthayer** [comment]
@alexandraB99 I've confirmed with John that we can remove the title/subtitle bar for all GIFs. I'll work up the GIF replay button and interaction flow detailing :

1) Removal of title/subtitle from the GIF
2) How many loops we should show before stopping the animation
3) What button/icon to show for the user to replay the GIF
4) What happens when the user clicks the GIF while it is playing (lightbox presentation)

Before I work through the above, do you foresee any issues with the above from a technical perspective or anything that might be tricky / take considerable time? Thanks!

**Comment by alexandraB99** [comment]
nothing I can't point out now, sounds doable. Please go ahead with providing these, If we encounter any problems during implementation we can discuss further!

**Comment by benjthayer** [comment]
Hi @alexandraB99 @caybro @iurimatias @jrainville 

Just to keep you up to date on this, I've put the attached proposal together for GIF looping and interactions. 

@John-44 is happy with it. I'll run it by the design team too and let you know if there are any changes requested. Do let me know if you feel anything here is hard/time-consuming to achieve and we can adjust as necessary.

I noticed the right-click options to copy/download are not present for images when being viewed in the lightbox but is present in the designs so I wonder if that is something that could be added if trivial enough to do. If not I can do another issue for that.

https://user-images.githubusercontent.com/110033914/215095689-17e11910-34b9-4bdd-a002-3d4205244f85.mov

**Comment by benjthayer** [comment]
Sorry @caybro I meant while the image is maximised / in the lightbox. Might just be my version of the app but I can't right click to get the controls there. Given we're replicating the interactions of the image here, it would be ideal if the right-click options were also implemented for the GIF but we could add later if tricky/time consuming.

**Comment by caybro** [comment]
Reopening since:

1: Every image is marked with the GIF CTA (not just GIFs):
![Snímek obrazovky z 2023-02-03 16-28-13](https://user-images.githubusercontent.com/5377645/216645767-d20acf1c-ab0f-4e56-bc3b-04eaad9af524.png)

2. The animation never stops playing if you hide/close the window within the 10second interval

**Comment by alexandraB99** [comment]
@caybro I can't reproduce

**Comment by alexandraB99** [comment]
@caybro you may open a bug instead with steps to reproduce, could you please do that and close the original issue?

**Comment by caybro** [comment]
Fixed in master
