### ISSUE TITLE
"Remove contact" button in ProfilePopup doesn't work

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7519]
# Bug Report

## Description

Clicking "Remove contact" has no effect, following message is is printed out:
```
qrc:/imports/shared/popups/ProfilePopup.qml:234: Error: Cannot assign QObject* to Popup_QMLTYPE_270*
```

#### Expected behavior

Popup with confirmation should appear

#### Actual behavior

Nothing happens

### Additional Information

[Kazam_screencast_00006.webm](https://user-images.githubusercontent.com/20650004/191923797-d752d43b-61ba-405a-80b9-4d8bdfde5ccc.webm)

- Status desktop version:
- Operating System:

**Comment by caybro** [comment]
Easy fix :)

```diff
--- ui/imports/shared/popups/ConfirmationDialog.qml
+++ ui/imports/shared/popups/ConfirmationDialog.qml
@@ -11,7 +11,7 @@ StatusModal {
     id: confirmationDialog
     anchors.centerIn: parent
 
-    property Popup parentPopup
+    property var parentPopup
     property var value
     property var executeConfirm
     property var executeReject
```
