### ISSUE TITLE
Tabs shouldn't be in a scrollable area in profile's settings

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7525]
# Bug Report

## Description

Tabs bar should have a fixed position.

![Image](https://user-images.githubusercontent.com/20650004/191839413-38338c7d-a2af-441a-b21b-00ba4ab07704.png)

## Steps to reproduce

Go to Settings -> Profile, scroll the content

#### Expected behavior

Tabs should be in a scrollable area

#### Actual behavior

Tabs are scrolled

### Additional Information

- Status desktop version:
- Operating System:

**Comment by alexandraB99** [comment]
@micieslak where did you see this specified? tabs behave the same in all settings page, not just profile, so if this is the case, should change to all pages

**Comment by micieslak** [comment]
> @micieslak where did you see this specified? tabs behave the same in all settings page, not just profile, so if this is the case, should change to all pages

It's outcome of discussion with @John-44 :)
