### ISSUE TITLE
[Wallet] Show pending transactions in the Activity view right after sending

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#7530]
Follow the investigations in [fixing new transactions never show PR](https://github.com/status-im/status-desktop/pull/7527) which found that pending transactions don't appear in the Activity tab view. They are visible only after a restart or when the next 20-minute cycle updates the transaction history for all the wallet accounts.

Also, it was found that the cyclic 20 minutes blocks the UI

The following consideration are to be addressed for an improved user experience:

- [ ] Show pending transactions in the activity view as soon as the send dialog goes away
- [ ] Don't block UI when updating all the transactions
  - Given that the call `checkRecentHistory` which executes RPC call `wallet_checkRecentHistoryForChainIDs` doesn't return or wait for the processing to be done investigate which of the solutions are optimal to implement
    - Run async `checkRecentHistory` if the RPC call is blocking until the results are updated
    - Address signal manager updates if they are the culprit

**Comment by alaibe** [comment]
@stefandunca the call checkRecentHistory, even if executed sync, should return fast, it mainly starts a worker and return. It doesn't return any data AFAIK

**Comment by stefandunca** [comment]
> @stefandunca the call checkRecentHistory, even if executed sync, should return fast, it mainly starts a worker and return. It doesn't return any data AFAIK

This is my understanding hence the request for investigating/profiling to understand which side effect slows the UI thread, it might be that the generated signals are to blame or just the processing. For certain the call hangs the UI for me noticeably with few accounts.
