### ISSUE TITLE
No error is reported and workflow is blocked if password is invalid when authenticating transaction

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#7531]
The progress indicator never finishes if the password is wrong and the error is not reported back to the user.

User should 

![image](https://user-images.githubusercontent.com/47554641/191969095-cfa67c0c-1000-4397-8441-a720b4a43d00.png)

## Steps to reproduce

1. Prepare a transaction -> after adding the amount and destination account user has the option to proceed to the next step
2. Enter a wrong but valid password to authenticate -> send button is available if the password matches the requirements

#### Expected behaviour

See an error message and have the chance to reenter the password and try again

#### Actual behavior

The send button is transformed into a wait button that never finishes

### Additional Information

- Status desktop version: a9d2ecf839ce6fe062833eaf8dae5d7475b86336
- Operating System: Mac

**Comment by alaibe** [comment]
Assigning Sale, as it will be rewrote with new authentication flow
