### ISSUE TITLE
Wallet -> Send: Block sending flow if pre-gas tip limit is not fetched

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7545]
### Description

We need to disable send button when required data is not received

<img width="1522" alt="Screenshot 2022-09-26 at 15 18 39" src="https://user-images.githubusercontent.com/82375995/192274277-c07305d1-3227-4d05-8931-412f35f600e7.png">

**Comment by alaibe** [comment]
Outdated with latest design
