### ISSUE TITLE
Wallet -> Send: dead end if maxPriorityFeePerGas is 0

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7546]
### Description

1. send token with maxPriorityFeePerGas = 0

```ERR 2022-09-26 16:08:16.806+03:00 Error sending token transfer transaction   topics="transaction-service" tid=3076330 file=service.nim:346 msg="maxPriorityFeePerGas should be a number > 0"```

<img width="1522" alt="Screenshot 2022-09-26 at 16 10 05" src="https://user-images.githubusercontent.com/82375995/192284986-fb5123ea-e624-486c-af88-fc1758c85036.png">

**Comment by alaibe** [comment]
not relevant with new design
