### ISSUE TITLE
[StatusQ] Merge StatusQ into desktop

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7548]
Merge proposal:
- merge StatusQ into desktop
- make StatusQ repoo read only, and then 
- migrate the existing PRs to status-desktop

Things to take into consideration:
Prevent StatusQ having dependencies to status-desktop, e.g detect things like `import "../app/appLayouts/chat/controls"`.
This could be mitigated either by not using system resources or by extending CI checks. The first one will have drawback of not working hot reloading

PR in `status-destkop`: https://github.com/status-im/status-desktop/pull/7462

**Comment by micieslak** [comment]
PR's migrated with [StatusQ] prefix.
