### ISSUE TITLE
[StatusQ] Support proper syntax highlighting in code blocks

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7565]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=207%3A44228

![Screen Shot 2022-01-12 at 4 24 06 PM](https://user-images.githubusercontent.com/176720/149223634-f9df1774-fbe4-494c-a2ce-9e6041bcfe22.png)

![Screen Shot 2022-01-12 at 4 24 20 PM](https://user-images.githubusercontent.com/176720/149223645-55f3de6d-e6d8-48fd-99cd-b4471403ec08.png)

**Comment by PascalPrecht** [comment]
Now that we're dogfooding desktop, this has become more and more apparent.
Sharing code snippets a kind of a pain with the current state of affairs.

Here's a screenshot of a message I sent today:
![Screenshot from 2022-11-16 10-54-32](https://user-images.githubusercontent.com/445106/202148994-454f674e-3e42-46a2-829b-01f0dfba6b67.png)

Notice that it's not just syntax highlighting but also formatting (indentation etc).

Would be cool if this issue could get some priority as this is getting more important the more we use Status as our means of communication.
