### ISSUE TITLE
[StatusQ] Implement `StatusProfileMenuItem`

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7568]
relevant spec: https://github.com/status-im/feature-specs/pull/42/files
relevant figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=1837%3A335128

![Screen Shot 2022-01-12 at 2 52 40 PM](https://user-images.githubusercontent.com/176720/149211881-ee783288-c72a-40e6-9040-370229a84bac.png)

**Comment by caybro** [comment]
This has landed together with the new Profile Modal; however there is a duplicity now which will be taken care of in https://github.com/status-im/status-desktop/issues/7886
