### ISSUE TITLE
[StatusQ] bug: expanding a category produces warning

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#7572]
1. Add a few categories to a community
2. Collapse/expand the categories by clicking the title
3. **Expected:** no warning
4. **Actual:** warning in the console for each category
```
QQmlExpression: Expression qrc:/StatusQ/src/StatusQ/Components/StatusChatListAndCategories.qml:144:25 depends on non-NOTIFYable properties:
    QQmlDelegateModel::model
```

**Comment by caybro** [comment]
This is obsolete; we no longer use DelegateModel in StatusChatList
