### ISSUE TITLE
[StatusQ] `StatusMenuPopup` should adjust its `width` when menu items take more space

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7577]
When there's menu items with text that is longer than the menu is wide, the text bleeds out:

<img width="221" alt="Screenshot 2021-07-19 at 11 39 06" src="https://user-images.githubusercontent.com/445106/126139451-74faa784-564e-443a-a483-902d757c3124.png">

The menu should be able to grow when the content is too wide, however we should probably still cap with a max width.

**Comment by 0x-r4bbit** [comment]
@alexandraB99 do you or your team know if this is still an issue?

**Comment by caybro** [comment]
No longer an issue afaik
