### ISSUE TITLE
[StatusQ] Add spellchecking support to `StatusBaseInput`

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7585]
Input components in StatusQ should provide the a way to spellcheck their contents. Ideally, this can be either configured via a flag, or by composition:

```qml
StatusBaseInput {
  spellcheck: true|false
}
```

Or 

```qml
StatusBaseInput {
  spellchecker: StatusSpellChecker {} // if feasible/possible
}
```

**Comment by iurimatias** [comment]
moved to https://github.com/status-im/status-desktop/issues/5742 epic
