### ISSUE TITLE
Paste action in status chat input doesn't work at the first try

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7600]
# Bug Report

When trying to copy something in chat input already stored in the clipboard, the first try doesn't work, it is needed a second try to really see the copy action working.

## Steps to reproduce

0. Ensure you have something saved in the clipboard
1. Go to status chat input
2. Paste: Ctrl+V

#### Expected behavior

Paste action should write the clipboard content.

#### Actual behavior

Paste action does nothing.

#### Additional information

Next try, paste action works as expected.

**Comment by micieslak** [comment]
I cannot reproduce that. Works in 100%.

**Comment by iurimatias** [comment]
also cannot replicate

**Comment by caybro** [comment]
I can reproduce.... sometimes I need 2 or even 3 tries (Ctrl+V) for the paste to actually happen

**Comment by fryorcraken** [comment]
Also have the issue. Fedora Linux.

**Comment by du64** [comment]
I have the issue - Linux Mint
Works fine on Zorin OS

**Comment by sashayar13** [comment]
I’ve experienced this bug - MacOS. Works only if Cmd+V are pressed at the same time (which is not normal/expected behavior)

**Comment by 0x-r4bbit** [comment]
CMD+V is the keystroke necessary to do normal pasting from clipboard. So if it works with that, it's correct.

For anyone who's working on this, I did some digging when I worked on adding copy&pasting images and it turns out we have a keypress and an onrelease handler on the chat input that conflict with each other.
Removing one of them makes pasting reliable agian.

**Comment by sashayar13** [comment]
Hi @0x-rabbit. Normally CMD+V works the way "press and keep "CMD" and then press "V". For StatusChat input "pasting" works only if "CMD" and "V" are both pressed at the same time from the beginning. And I'd say it is not normal behavior

**Comment by 0x-r4bbit** [comment]
Ah, I see what you mean now! Yes then this is a bug (probably just a result of what I've described above).
