### ISSUE TITLE
Ephemeral notifications showing up higher and higher

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7613]
Notice where the notification is positioned in the screenshot below:

![Screenshot from 2022-09-27 15-40-14](https://user-images.githubusercontent.com/445106/192542622-c1e7018a-aaaf-4d8b-acc0-f853d11c9f5e.png)

With every following notification of this kind, the notification show up higher and higher, even though the notification stack has only a single item

**Comment by faust4exe** [comment]
I am working on https://github.com/status-im/status-desktop/issues/7487 and while investigation I found this bug. Going to fix it there as it is one of reasons leading to bad behavior.

**Comment by faust4exe** [comment]
This is fixes by PR https://github.com/status-im/status-desktop/pull/7669
