### ISSUE TITLE
Pasting text into chat input doesn't always work immediately

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7614]
Not sure if this is linux related, but whenever I try to paste text into the chat input, it never works the first time I hit CTRL+V
It needs at least two, sometimes three attempts.

**Comment by noeliaSD** [comment]
I think it is the same as this: https://github.com/status-im/status-desktop/issues/7600. Can we consider it as duplicated?

**Comment by PascalPrecht** [comment]
Ah nice! Yes closing as duplicate.
