### ISSUE TITLE
Community channel names disappear when hovering hover community image

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7617]
Kinda hard to reproduce it seems (although I can), when moving the cursor from a community category into the community image in the top left corner (chat info button), the channel names of the community disappear:

![Screenshot from 2022-09-27 16-21-11](https://user-images.githubusercontent.com/445106/192553195-70f50163-d7ab-4f58-ac63-a1dc0ecf4e69.png)

**Comment by caybro** [comment]
@PascalPrecht I just can't reproduce in the latest master

**Comment by PascalPrecht** [comment]
I reproduced this again with the latest production build
![Screenshot from 2022-10-17 13-06-58](https://user-images.githubusercontent.com/445106/196162420-5b308b76-0960-4b9c-8cff-e5113e3886bb.png)

**Comment by endulab** [comment]
FYI, from time to time I am able to catch it also.

**Comment by caybro** [comment]
> FYI, from time to time I am able to catch it also.

@endulab any other steps to reproduce? Also, when this happens, does it "fix" itself after some time/action, or do you need to restart the app?

**Comment by noeliaSD** [comment]
I didn't tested on last master but I think it will be the same.. let's see if it helps you to reproduce it.. it's kind of trick (move the mouse super slow):


https://user-images.githubusercontent.com/97019400/196405552-3c4598b9-81dc-437e-8857-f04739e2cf9b.mov

**Comment by PascalPrecht** [comment]
Nice!
Can anyone else on 15.5 confirm this?

**Comment by alexandraB99** [comment]
> Nice! Can anyone else on 15.5 confirm this?

yes, @caybro !

**Comment by PascalPrecht** [comment]
Super happy to hear, cause this one has been quite mystery.
Are we officially using 15.5? If yes, then this can be closed, but I think we're still on 15.4?

**Comment by endulab** [comment]
We use 5.14

**Comment by caybro** [comment]
I can't reproduce (never ever) on Qt 5.15, meaning that this bug is more than likely a Qt bug

**Comment by PascalPrecht** [comment]
Alright, then we can close this as soon as we've officially moved to 5.15

**Comment by caybro** [comment]
> Alright, then we can close this as soon as we've officially moved to 5.15

The problem here is we haven't "officially" moved to 5.15 yet (due to some obscure reasons around nim and the tooling) but trying to "fix" this bug in Qt 5.14 is pointless unless we want to also ship a patched version of Qt (we don't want that! :)

**Comment by alexandraB99** [comment]
@iurimatias this will be solved when we upgrade to at least 5/15 - please decide whether you want to keep it open or close it.

**Comment by noeliaSD** [comment]
I have another input here.. I didn't take a look at the code but just to be completely sure that it is some `Qt bug` and will be solved in `5.15` or it is really our bug..

I could reproduce it very easy when I was waiting to join the new community using `0.8.0-rc.2` version. See the video:

https://user-images.githubusercontent.com/97019400/202772233-0a40a4dc-ece2-4bec-85a2-9da728568a07.mov

What makes me feel is that we have an issue when we are trying to hover this `button` area, but when it is hidden, we still have some mouse area that makes it happen but not as easy. Could the ones that have the `5.15`version (@alexandraB99 @caybro) test it again when this button is visible? And also, the community needs to have more than one channel, bc the selected one doesn't disappear.

**Comment by alexandraB99** [comment]
@noeliaSD tested negative :)

https://user-images.githubusercontent.com/31625338/206706819-ee4fc34b-1c7f-47e8-953b-a6510e11fbec.mov

**Comment by alexandraB99** [comment]
to be fixed with https://github.com/status-im/status-desktop/issues/8642

**Comment by alexandraB99** [comment]
@0x-r4bbit can we close this now?

**Comment by 0x-r4bbit** [comment]
@alexandraB99 as per https://github.com/status-im/status-desktop/issues/7617#issuecomment-1305799767, if we have officially upgraded, then yes.

**Comment by 0x-r4bbit** [comment]
Based on https://github.com/status-im/status-desktop/issues/7617#issuecomment-1402313396 looks like we have.
Closing this as fixed!
