### ISSUE TITLE
Implement "delete for me" feature

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7632]
This is about to land in the protocol here: https://github.com/status-im/status-go/pull/2866 and there's already a corresponding PR for mobile here https://github.com/status-im/status-mobile/pull/14007

Motivation: https://github.com/status-im/status-mobile/issues/13873

Let's get this implemented for desktop also.
At a first glance, what we need to do is:

1. Add an option in the context menu for messages to "delete for me"
2. Make use of the newly introduced API
3. Ensure the for me deleted message is removed from memory

/cc @iurimatias @John-44

**Comment by iurimatias** [comment]
descoped for now
