### ISSUE TITLE
"Send contact request" context menu action opens profile modal unnecessarily

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7633]
Inside of a community, when opening the context menu of a member in the member list and hitting "Send contact request", not only the modal to send a contact request is opened, but also the profile modal of that member, which should happen:

![Screenshot from 2022-09-28 13-37-54](https://user-images.githubusercontent.com/445106/192769726-55521b2d-7a01-4e9c-be20-09172d54fde8.png)

Just open the contact request modal.

**Comment by caybro** [comment]
Already in the works as part of https://github.com/status-im/status-desktop/issues/7360, PR https://github.com/status-im/status-desktop/pull/7621

**Comment by alexandraB99** [comment]
this is also a duplicate of https://github.com/status-im/status-desktop/issues/6941

**Comment by iurimatias** [comment]
duplicate of https://github.com/status-im/status-desktop/issues/6941

**Comment by alexandraB99** [comment]
@caybro please move to done if this is the case
