### ISSUE TITLE
Add tooltips to contact trust status in messages

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7634]
As a user, I'm seeing messages from a mutual contact that look like this:

![Screenshot from 2022-09-28 14-48-14](https://user-images.githubusercontent.com/445106/192782430-5689ffa6-665b-49e3-bc36-93d7569ad8eb.png)

The trust status (the little blue icon next to the name) doesn't really say what it is/means.
This is especially tricky for new users.

How about we add a tooltip to it so users can learn what the thing means?

**Comment by elina2015** [comment]
@iurimatias, @John-44 what is the text for this tooltip? Now the tooltip is 'Contact':
<img width="321" alt="image" src="https://user-images.githubusercontent.com/14942081/195737498-5c8adfc0-be6d-4f1f-8e86-c54b05623163.png">

**Comment by elina2015** [comment]
Tested on Master https://ci.status.im/job/status-desktop/job/platforms/job/macos/230/
