### ISSUE TITLE
"Hide read notifications" tooltip in activity center is misplaced

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7635]
The tooltip activated by the eye-icon button is incorrectly positioned and needs fixing

![Screenshot from 2022-09-28 15-09-36](https://user-images.githubusercontent.com/445106/192786859-b91ced83-821d-4bca-92cb-e3174e46d2c4.png)

**Comment by caybro** [comment]
@PascalPrecht not very obvious from the screenshot :)

**Comment by PascalPrecht** [comment]
I'd need to make changes in code to make this screenshot-able so I trust whoever works on this reads the issue description

**Comment by MishkaRogachev** [comment]
> @PascalPrecht not very obvious from the screenshot :)

<img width="217" alt="Screenshot 2022-09-28 at 17 23 01" src="https://user-images.githubusercontent.com/2522130/192789832-3f265164-7b1b-4cfa-918a-25c1bf211bdd.png">

**Comment by caybro** [comment]
Alt+PrtScr :)

**Comment by MishkaRogachev** [comment]
Fixed here: https://github.com/status-im/status-desktop/pull/7667
