### ISSUE TITLE
Resend button shown next to message even after being received

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7643]
# Bug Report

## Description

Resend buttons are appearing next to messages even when they have been received. Clicking on the button appears to do nothing. It is not possible for the user to determine whether the message was sent or not.

## Steps to reproduce

![image](https://user-images.githubusercontent.com/50769329/192832445-d2f2c211-beb6-45c3-ad37-7bcbdf848e48.png)

![image](https://user-images.githubusercontent.com/50769329/192831761-f49a271c-683c-4504-b779-141cb3c78863.png)

#### Expected behavior

Resend button appears only when message was not received.
Resend button is removed when message has been successfully sent.

**Comment by jrainville** [comment]
@glitchminer can you still reproduce?

**Comment by anastasiyaig** [comment]
@jrainville i can reproduce however i dont get any logic behind it (how to reproduce)

<img width="984" alt="image" src="https://user-images.githubusercontent.com/82375995/204760963-950d1e01-5835-4601-9762-cbc4c85a7a86.png">

**Comment by qoqobolo** [comment]
Adding my case too, although I don't have steps either. Faced this two days ago (28/11) and yesterday (but it seems that the button did not appear immediately after sending, I noticed it only now).
Also, noticed that nothing happens in logs on pressing it.

<img width="746" alt="Screenshot 2022-11-30 at 11 41 12" src="https://user-images.githubusercontent.com/67952253/204781371-0f710f6d-9f5e-4f02-becb-4561114c0f45.png">
<img width="293" alt="Screenshot 2022-11-30 at 12 23 30" src="https://user-images.githubusercontent.com/67952253/204783772-0fb50bb6-0c8f-440d-b2aa-84e4d9b0dde7.png">

**Comment by zah** [comment]
I've ran into the same issue with the latest 0.8 build. I wasn't seeing the Resend buttons immediately. I think they appeared after for some of my messages after I restarted the app.

**Comment by jrainville** [comment]
If one of you still have Resend buttons showing, can you try the builds from my PR to see if clicking the Resend button does something now? Thanks https://github.com/status-im/status-desktop/pull/8703
(I don't think there is a migration issue with using master, but just to be sure, it might be worth doing a backup of your data dir just in case. Do not use my PR if you don,t know what you're doing)
