### ISSUE TITLE
Unreachable buttons in community header at min width

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7647]
# Bug Report

## Description

On linux, buttons in the group chat header become unreachable at min width. Search, members and meatball menu become hidden.
![image](https://user-images.githubusercontent.com/50769329/192864852-35f7c40f-111f-4c4d-b4ae-3404b78cdd4c.png)

## Steps to reproduce

On a group chat with a long name, resize the window smaller.

#### Expected behavior

Same as on Mac, group chat is overlapped by controls to maintain functionality.

#### Actual behavior

Buttons become unreachable

### Additional Information

- Status desktop version: dogfooding/master
- Operating System: linux

**Comment by micieslak** [comment]
Video with wider context:

https://user-images.githubusercontent.com/20650004/194052233-e452b143-fba7-46b4-b9f7-5a2544d9e304.webm
