### ISSUE TITLE
'Plug in Key Card reader' screen is shown even if the user decided to enter a seed phrase

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7650]
# Bug Report

## Steps to reproduce
1. Install the app (and clean the Status folder before it)
2. Click 'I already use Status' - 'Login with Keycard' - back - 'Enter a seed phrase'

#### Expected behavior
The 'Plug in Key Card reader' screen is shown only before the user decided to go back and click on the left arrow button to return to another screen
#### Actual behavior
'Plug in Key Card reader' screen is shown even if the user decided to enter a seed phrase
### Additional Information

https://user-images.githubusercontent.com/14942081/192949122-ee2729db-beab-4db5-a377-d81135de1190.mov

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/221
- Operating System: macOS Monterey

**Comment by saledjenic** [comment]
@elina2015 this one should be fixed in #7629 please check this there.
