### ISSUE TITLE
There's a "Download" option in the chat view which doesn't do anything

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7657]
![Screenshot from 2022-09-29 13-03-35](https://user-images.githubusercontent.com/445106/193015275-45c96985-a842-44f6-8a05-4d160cb0c684.png)

The one below "Clear history"
I clicked it, it doesn't do anything. Nor do I know what this **would** download.

**Comment by caybro** [comment]
@PascalPrecht seems like a developer option:

```qml
StatusMenuItem {
        text: qsTr("Download")
        enabled: localAccountSensitiveSettings.downloadChannelMessagesEnabled
        icon.name: "download"
        onTriggered: downloadDialog.open()
    }
```

**Comment by PascalPrecht** [comment]
Ah, good catch!
At least we know where it's coming from. Now it has to be made functional haha

**Comment by iurimatias** [comment]
@PascalPrecht this works for me, maybe it's an issue in linux?

**Comment by PascalPrecht** [comment]
Possible. It doesn't seem to do anything on my machine when clicked.
