### ISSUE TITLE
[Wallet] Display historical balance of a token

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#7662]
Use the transaction we have in the db in order to rebuild the history. This won't go back in block 0 but only to the block that the user use the app for the first time

[Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6770%3A76490)

![image](https://user-images.githubusercontent.com/47554641/195792822-44d6d0fc-f55a-4802-8352-8bf91cdf2710.png)

**Comment by stefandunca** [comment]
The transaction experiment didn't work but learned a lot while building the associated PR. The following prototype PR https://github.com/status-im/status-desktop/pull/7951 is the foundation for the following epic task https://github.com/status-im/status-desktop/issues/8175
