### ISSUE TITLE
Activity center activies don't show reply messages

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7664]
![Screenshot from 2022-09-29 15-21-04](https://user-images.githubusercontent.com/445106/193042763-5c7dd530-87ea-4d7a-a7a6-94daf00ee880.png)

**Comment by caybro** [comment]
I think we have a bug for this already, cc @MishkaRogachev

**Comment by MishkaRogachev** [comment]
Fixed here: https://github.com/status-im/status-desktop/pull/7523

**Comment by PascalPrecht** [comment]
Closing as fixed then!
