### ISSUE TITLE
Community overview/settings layout broken

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#7666]
# Bug Report

- left panel lost the margins
- right panel is cut off at the right side

![Snímek obrazovky z 2022-09-29 15-38-02](https://user-images.githubusercontent.com/5377645/193046881-8d0d505f-11cb-4269-a1b5-375d15c44c8f.png)

- Status desktop version: master
- Operating System: Linux

**Comment by PascalPrecht** [comment]
Also, links in the bottom of the left panel are sticking to the right. Those were centered
