### ISSUE TITLE
rainbow ring missing on onboarding

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7671]
# Bug Report

## Description

created a new account, then notice in onboarding on the right, the rainbow ring is missing

![Screen Shot 2022-09-29 at 2 03 26 PM](https://user-images.githubusercontent.com/176720/193108629-b05c2b6d-1f50-46c9-a6dd-a64bc58d65ef.png)

**Comment by caybro** [comment]
@iurimatias from the log:

```
qrc:/imports/utils/Utils.qml:532: ReferenceError: mainModule is not defined
```

which is:

```JS
da6fe00528 ui/imports/utils/Utils.qml (Sale Djenic        2021-12-31 13:29:51 +0100)     function getContactDetailsAsJson(publicKey) {
da6fe00528 ui/imports/utils/Utils.qml (Sale Djenic        2021-12-31 13:29:51 +0100)         let jsonObj = mainModule.getContactDetailsAsJson(publicKey)
```

No idea for how long this has been broken

**Comment by caybro** [comment]
@iurimatias my guess is that the `mainModule` init has been moved to a later stage
@saledjenic ? :)

**Comment by saledjenic** [comment]
@caybro `mainModule` is registered once user logs in, not before that. If we need something from the backend during the onboarding/login flow we need to fetch that via `startupModule`. Also after user logs in, `startupModule` gets deleted, doesn't exist any more.

**Comment by caybro** [comment]
> 

The context here is to get the user's details in order to draw the identicon ring
