### ISSUE TITLE
Identity ring shouldn't be rendered for contacts with ENS

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7672]
Below are two screenshots of user with the ens "cammellos.stateofus.eth".
In the message view, it correctly doesn't show an identity ring.
In the member list, it does.

![Screenshot from 2022-09-29 20-06-51](https://user-images.githubusercontent.com/445106/193109979-e052794c-c32d-4cff-8b71-050c243a3f8f.png)
![Screenshot from 2022-09-29 20-06-58](https://user-images.githubusercontent.com/445106/193109988-3fd04592-e3ba-45b4-b57a-ef919d666767.png)

**Comment by caybro** [comment]
@PascalPrecht I don't see this in latest master (I fixed it in #7517)

**Comment by PascalPrecht** [comment]
Sweet. Closing as solved then.
