### ISSUE TITLE
Reply-to-message text isn't truncating or wrapping

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7673]
See the text of the reply-to-message below:

![Screenshot from 2022-09-29 20-12-33](https://user-images.githubusercontent.com/445106/193110774-401a2fea-a8c9-4624-850c-7b674369ef37.png)

If it's long enough, it'll just go "behind" the panel.
I think it should either truncate at a certain length or wrap around (probably the former).

**Comment by caybro** [comment]
It's truncated because we use a `TextEdit` in `StatusTextMessage` for rendering the text reply; it doesn't support `elide` and I suspect the reason for using it is simply we need to be able to select the text with mouse (which otoh a regular `Text` component doesn't support)

**Comment by caybro** [comment]
> @caybro is right. But maybe we could kill two birds with one stone here.
> What if we make the reply message text not selectable, but clickable?
> And with click we could jump to the original message.
> 
> This would both:
> - allow us switching to `Text` component, which has `elide` property
> - give user ability to read the whole message, which is not possible now
> 
> And btw, this is related to https://github.com/status-im/status-desktop/pull/7770
> 
> @John-44, wdyt?

I like this idea fwiw

**Comment by PascalPrecht** [comment]
This seems to be behaving differently in different messages:

Notice how one reply goes "behind" the member list, while the other super long one wraps

![Screenshot from 2022-11-03 10-57-09](https://user-images.githubusercontent.com/445106/199692380-9d38af3f-3f7a-4b61-8180-be5f1150d47e.png)

**Comment by PascalPrecht** [comment]
Ah, nevermind. The second one is not a reply
