### ISSUE TITLE
Search location doesn't use correct channel color

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7681]
See here. The channel color of the #defi channel in the screenshot is purple-ish. But in the search location dropdown it appears black:

![Screenshot from 2022-09-30 08-40-45](https://user-images.githubusercontent.com/445106/193206930-595e2f4b-7a1b-4807-8347-cf48b1c7fb5b.png)

**Comment by iurimatias** [comment]
duplicate of https://github.com/status-im/status-desktop/issues/7702
