### ISSUE TITLE
Channel list in community view scrolls horizontally

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7683]
Can't really see this on the screenshot, but if you create a community and have a channel, you can horizontally wobble the contents of the left panel.

![Screenshot from 2022-09-30 08-43-58](https://user-images.githubusercontent.com/445106/193207691-bd49daab-553a-49bd-bf97-e5004cddcc1e.png)

**Comment by micieslak** [comment]
I cannot reproduce. @PascalPrecht could you check if it still happends?

**Comment by micieslak** [comment]
It happens in `0.7.0-beta` but works as expected on master for the exactly same data. I think we can close it.

**Comment by PascalPrecht** [comment]
Sorry, I didn't get to respond here quickly enough. Yes this has been fixed by a short while ago, but apparently this issue was not referenced/closed.
