### ISSUE TITLE
Chat input: unexpected characters appear when using shortcuts after mention

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7685]
# Bug Report

## Description

Shortcuts behave in an unexpected way when used right after a mention.

## Steps to reproduce

Insert mention, position the cursor right after the mention using arrows, use shortcut (ctrl+z, ctrl+x, ctrl+v, etc)

[Kazam_screencast_00021.webm](https://user-images.githubusercontent.com/20650004/193225667-9e253852-3dee-4358-a1d0-25e9f2a9e0f5.webm)

#### Expected behavior

Shortcuts should work as usual

#### Actual behavior

Strange character appear

### Additional Information

- Status desktop version:
- Operating System:

**Comment by alexjba** [comment]
@micieslak could you please retest this on latest master? I could not reproduce

**Comment by micieslak** [comment]
I can still reproduce on master, in the exactly same way as it's done in the attached video.

**Comment by caybro** [comment]
Yup, same here
