### ISSUE TITLE
Image of unfurled link is of poor quality

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7689]
# Bug Report

## Description

The preview is of obviously lower quality compared to other messaging software.

![Kazam_screenshot_00003](https://user-images.githubusercontent.com/20650004/193238659-05c1bda3-defa-4a41-8222-b5cb8e97e34f.png)

#### Expected behavior

Image should be smooth

#### Actual behavior

Image is pixelated

### Additional Information

- Status desktop version:
- Operating System:

**Comment by caybro** [comment]
@micieslak sth to do with scaling the image; I noticed that when I see this on my 4k screen (which has scale of 2x, the image is crisp)
