### ISSUE TITLE
deep link with ens not opening 1 on 1

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7704]
# Bug Report

## Description

1. add a ens contact, say `username`
2. go to a link like `https://join.status.im/u/username.stateofus.eth` and open with status

result: status app opens but nothing happens
expected result: should open 1 on 1 with `username

unclear: what happens if `username` is not a contact?

**Comment by endulab** [comment]
/u/ link does not open 1:1 chat but only user profile.
If user is not a contact the profile dialog will be opened with 3-words name.
