### ISSUE TITLE
reacting to a message at the bottom does not auto scroll

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7705]
# Bug Report

## Description

https://user-images.githubusercontent.com/176720/193481882-493afc03-09bb-4521-93c1-43018eff21a6.mov

**Comment by caybro** [comment]
I can't reproduce on my side with https://github.com/status-im/status-desktop/pull/7698

**Comment by micieslak** [comment]
I can't reproduce on master nor https://github.com/status-im/status-desktop/pull/7698
