### ISSUE TITLE
Invite contacts modal contact list has huge empty space between each contact

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7707]
# Bug Report

## Description

1. create a community or go to a community you are an admin
2. click "add members"

<img width="659" alt="Screen Shot 2022-10-02 at 8 24 17 PM" src="https://user-images.githubusercontent.com/176720/193483126-6d0c5f5e-1151-43fd-977d-f07c94b1a4b7.png">

**Comment by iurimatias** [comment]
still an issue

**Comment by micieslak** [comment]
Some initial investigation: https://github.com/status-im/status-desktop/tree/release/0.7.x-invite-panel-spacing-fix
