### ISSUE TITLE
Chat -> Link is not fully visible when sent in chat as very last message

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7710]
### Description

1. join public chat
2. send a link as a message to the chat, for example: https://cointelegraph.com/news/ethereum-merge-spikes-block-creation-with-a-faster-average-block-time

**Result**: the link is not fully visible no matter how huge your status window is

<img width="1224" alt="Screenshot 2022-10-03 at 10 52 07" src="https://user-images.githubusercontent.com/82375995/193526947-ee991f92-241b-4202-baaa-e289090a33a7.png">

<img width="1268" alt="Screenshot 2022-10-03 at 10 59 37" src="https://user-images.githubusercontent.com/82375995/193528253-7b5b5f79-b65f-49b4-aff3-8c91f8c020a5.png">

**Comment by caybro** [comment]
Another "overlapping messages" duplicate

**Comment by anastasiyaig** [comment]
oh sorry i did not realise it is the same ! Closing this one then, thanks @caybro !
