### ISSUE TITLE
Wallet -> Keycard: can't bypass password validation for buying ENS

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7713]
### Description

1. create account with Keycard flow
2. get some STT and ETH on goerli
3. try to buy ENS

As result, user can't bypass the password validation

<img width="1192" alt="Screenshot 2022-10-03 at 12 25 08" src="https://user-images.githubusercontent.com/82375995/193544835-7ea03733-d8d2-4ec1-9172-dbd6bfa2ada8.png">

**Comment by stefandunca** [comment]
This was never implemented for a keycard. It only works with a password workflow and in the case of a keycard, the password is owned by the keycard implementation.

@saledjenic assigned it to you for a faster implementation

**Comment by alaibe** [comment]
This is now working
