### ISSUE TITLE
Wallet -> Keycard: import seed is not possible (add account button is disabled)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7715]
### Description

1. create account with keycard
2. enable wallet
3. click add account
4. import with seed

As result, the Add account button is not enabled

<img width="1192" alt="Screenshot 2022-10-03 at 12 53 44" src="https://user-images.githubusercontent.com/82375995/193549888-5584c3b9-efaf-4393-8895-6010ff3b8597.png">

**Comment by stefandunca** [comment]
For me the "Add account" is available after authenticating. However, it seems the keycard is not implemented for creating wallet APIs. Only password workflow is supported.

Investigating the issue leads to status-go's APIs for creation accounts failing due to the wrong password (password being the KeyUID of the account we try to authenticate). Following this lead, I found that we actually intentionally set the wallet password to `KeyUID` for which purpose I can't easily tell.

**Comment by stefandunca** [comment]
It seems the `keystore` is empty for the keycard account, hence failing to initialize the account when verifying password:
```
ll keystore/0x891e7a5867bf5e25a21cc74e3863284a8bc2e12289d899046b2eb3319f83889f
total 0
drwx------  2 stefan  staff    64B Oct 10 22:29 .
drwxr-xr-x  3 stefan  staff    96B Oct 10 22:29 ..
```

@saledjenic do we initialize the keystore when logging in with a keycard for the first time?

**Comment by saledjenic** [comment]
@stefandunca yes, we init a keystore, check the following lines:
- when login a keycard account [here](https://github.com/status-im/status-desktop/blob/de2c421b5e7e1a88fe08953ac2ab7a68197beb4a/src/app_service/service/accounts/service.nim#L588)
- when setting up a keycard account [here](https://github.com/status-im/status-desktop/blob/de2c421b5e7e1a88fe08953ac2ab7a68197beb4a/src/app_service/service/accounts/service.nim#L396)

**Comment by stefandunca** [comment]
It seems the keycard is initialized successfully but no keystore file is generated for the default account and no error is propagated/generated

**Comment by stefandunca** [comment]
Update: `StoreKey` is not called for the `setupAccountKeycard` with the latest changes. However, can't tell why yet.

**Comment by stefandunca** [comment]
@saledjenic finally found the root cause for the use-case that failed for me and created a new issue to fix this separately https://github.com/status-im/status-desktop/issues/7867

**Comment by stefandunca** [comment]
Coming back to this issue, it seems that pasting that specific seedphrase, @anastasiyaig is using for testing, is triggering an invalid seedphrase in the `AddAccountModal.qml` even though it is valid. The order of events that drives the enabled state fo "Add account" button in there is not providing a correct and stable result in some corner cases. Didn't find a quick fix yet.
