### ISSUE TITLE
Biometrics registers as enabled after TouchID setup cancelled

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7726]
# Bug Report

## Description

Biometrics is shown as enabled even when TouchID config is cancelled during account set up.
This can result in the following error during the next login:
![image](https://user-images.githubusercontent.com/50769329/193679766-e31b9069-f60e-4e9d-ae5d-59ce5e04dfaf.png)

## Steps to reproduce

- During account setup select to enable TouchID, but then cancel the TouchID prompt.
- Check that Biometrics shows as enabled in settings
- Quit app
- Open app (touchid prompt will be displayed)
- Attempt to login with TouchID

#### Expected behavior

- Biometrics is disabled if TouchID setup is not completed.

#### Actual behavior

- Biometrics is still enabled even though setup is not complete.

### Additional Information

- Status desktop version: 0.7 rc1 (dogfooding)
- Operating System: Mac

**Comment by iurimatias** [comment]
closed in favour of #10424
