### ISSUE TITLE
Previously used pic and ENS shown to contacts after account restore when neither are set

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7733]
# Bug Report

## Description

Previously used pic and ENS shown to contacts after account restore when neither are set

## Steps to reproduce

Instance 1.
Set up account with profile picture and ENS
Both are shown to contacts
Close instance

Instance 2.
Import previously used account using seed phrase
Do not set up ENS or Profile picture (user does not see these configured in their instance - eg. 2 letters instead of pic)
Previously used ENS and profile picture are still shown to contacts

#### Expected behavior

Profile picture and ENS shown to contacts reflect the settings shown to the user in the active instance

### Additional Information

- Status desktop version: 0.7.0 RC1 (dogfooding)
- Operating System: Mac

**Comment by igor-sirotin** [comment]
As discussed with @saledjenic, postponing this issue until https://github.com/status-im/status-desktop/issues/8315
