### ISSUE TITLE
Contacts showing as 3 word username after restoring account

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7735]
# Bug Report

## Description

After importing an account using seed phrase not all contacts resolve to their display or ENS names

![image](https://user-images.githubusercontent.com/50769329/193809922-ebf74adb-1aad-48ae-bdc4-ba1d717b3dea.png)

## Steps to reproduce

1. Start new instance with imported seedphrase
2. Observer contacts list resolving names

#### Expected behavior

1. All contacts resolve to their ENS, display or nickname

#### Actual behavior

1. Some contacts only get displayed as 3 word usernames

### Additional Information

- Status desktop version: 0.7.0 RC1 (dogfooding)
- Operating System: Mac

**Comment by endulab** [comment]
@glitchminer @igor-sirotin after restoring account there are only 3-words names in database. Display names are not downloaded. But it is possible to do. FYI @cammellos.

**Comment by John-44** [comment]
Perhaps we should sync the latest chosen usernames of all users the user has encountered between devices + back also back this information up to waku?  This would ensure that all usernames are correctly displayed when an existing user restores their Status account. If so, this will be a task for @saledjenic or @rasom who will be working on widening the scope of the user state that is backed up to waku.

**Comment by saledjenic** [comment]
@endulab @igor-sirotin @glitchminer display name and profile image are not part of the waku synchronization yet and that's the reason why you see 3 words name without profile image when you're restoring an account.

I started today with checking what we have on the status-go side at this moment and introducing myself to that part. Sync profile details from waku should be part of https://github.com/status-im/status-desktop/issues/8315 issue assigned to me.

**Comment by cammellos** [comment]
@qfrank is working on backing up / syncing profile picture & display name, so please coordinate with him to avoid any extra/duplicate work https://github.com/status-im/status-mobile/issues/14395

**Comment by saledjenic** [comment]
@cammellos I messaged him, waiting for his answer. Thanks.

**Comment by jrainville** [comment]
This should be fixed in latest master. Can you test @glitchminer , please.
