### ISSUE TITLE
Online indicator seems to miss border in darkmode

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7755]
Here's a 1-on-1 chat item in lightmode:

![Screenshot from 2022-10-05 12-14-22](https://user-images.githubusercontent.com/445106/194037414-edceffdc-2d6b-4a61-a558-74f93caa34fb.png)

Here's the same in darkmode

![Screenshot from 2022-10-05 12-11-21](https://user-images.githubusercontent.com/445106/194037345-313aba27-844d-4cf2-ae7f-a183023fed38.png)

Here's the item in hovered state:

![Screenshot from 2022-10-05 12-11-31](https://user-images.githubusercontent.com/445106/194037499-26a74211-e90f-4a29-9704-90f489814cb7.png)

Notice how the online status indicator looses its border

**Comment by caybro** [comment]
Not hovered:
![Snímek obrazovky z 2022-10-05 14-44-42](https://user-images.githubusercontent.com/5377645/194063535-f19ddb21-5fe8-4f5d-9d08-ff8ec2a43df7.png)

Hovered:
![Snímek obrazovky z 2022-10-05 14-44-47](https://user-images.githubusercontent.com/5377645/194063530-6acb9501-720a-4f8f-a41c-e42eaa6626fc.png)

Aka it works here @PascalPrecht :)

**Comment by PascalPrecht** [comment]
Could also be location specific. But even in your screenshots you can see that the border flickers on hover, which in this particular spot also doesn't seem to be correct?

**Comment by caybro** [comment]
Hmm no... I don't see anything weird. Maybe the choice of colors and the lack of some color transition makes it seem so

**Comment by PascalPrecht** [comment]
Right so... the issue with the border is that we can't use a transparent color there because depending on its background it'll look off. Just like it's slightly different in your hovered screenshot.

That's why, in some cases, the border color for the online status needs to get a hardcoded color, really depending on what background the item sits on.

Anyways, that's a different issue (which exists for a long time btw, but has mostly been accounted for in previous implementations of views in desktop. Seems like we lost it with refactors in StatusQ.

In this issue here I see the border disappearing entirely as you can see in my screenshots.

**Comment by caybro** [comment]
> Right so... the issue with the border is that we can't use a transparent color there because depending on its background it'll look off. Just like it's slightly different in your hovered screenshot.
> 
> That's why, in some cases, the border color for the online status needs to get a hardcoded color, really depending on what background the item sits on.
> 
> Anyways, that's a different issue (which exists for a long time btw, but has mostly been accounted for in previous implementations of views in desktop. Seems like we lost it with refactors in StatusQ.
> 
> In this issue here I see the border disappearing entirely as you can see in my screenshots.

Ouch I'm stupid, that's (sadly yet another) different component; will investigate some more
