### ISSUE TITLE
Community color is not shown in left bar

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#7763]
# Bug Report

## Description

<img width="411" alt="image" src="https://user-images.githubusercontent.com/25482501/194068611-8a1d01ec-7c4d-4865-9a05-bf758ed3e521.png">

**Comment by caybro** [comment]
@igor-sirotin it's even worse, it doesn't show the "notifications badge" at all either (if there's new messages in that community). See the first "Chats" icon, it has this blue dot in the topright corner

**Comment by caybro** [comment]
> @caybro but should it? thinking Not sure where're designs for this

Hell yeah it should imo! :) There's no other way to get notified of new messages when they arrive, esp. when you have the window hidden/minimized into systray.
