### ISSUE TITLE
Wallet -> Keycard -> Add account: Blank Add account screen when reopening it

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7765]
### Description

<img width="1512" alt="Screenshot 2022-10-05 at 15 21 14" src="https://user-images.githubusercontent.com/82375995/194065835-0ba8f6bf-382c-4991-b693-4b9e3d24ca33.png">

1. create account with keycard
2. use pin verification
3. enable wallet
4. click Add account
5. bypass Authentication
6. select Import New seed phrase
7. fill in the form
8. close the modal
9. click Add account again

**Comment by saledjenic** [comment]
@anastasiyaig please check this, I would say it's an outdated issue. I cannot reproduce it.

**Comment by anastasiyaig** [comment]
cant reproduce it either, closing
