### ISSUE TITLE
Messages stop being received after computer idle

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-desktop#7766]
# Bug Report

I left Status Destkop logged in on my user in Mac, after that the laptop was closed (idle), and user was switched
After few days when I logged back in, Status Desktop was not receiving messages anymore, but it said it was connected.

## Description

TBD

## Steps to reproduce

TBD

#### Expected behavior
TBD
#### Actual behavior
TBD
### Additional Information

- Status desktop version: Version: 0.3.0-beta
- Operating System: Mac Monterey 12.6

**Comment by iurimatias** [comment]
hey @3esmit 0.3.0 is somewhat old and newer versions don't have such issues. for example https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4 (note that you should backup data folder, and this uses waku v2)
