### ISSUE TITLE
Cannot copy a link to community

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7776]
# Bug Report

## Steps to reproduce
1. Create a community
2. Click 'Add members' and click on the icon to copy the community address
3. Paste the copied address to some chat
#### Expected behavior
The community address is copied successfully

#### Actual behavior
The community address is not copied
<img width="650" alt="image" src="https://user-images.githubusercontent.com/14942081/194209946-e7c694c3-d732-4a6e-8a3e-05bd3fcbb3ef.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4
Operating System: macOS Monterey

**Comment by PascalPrecht** [comment]
@elina2015 This copy button copies a link to `join.status.im/....` which will later unfurl to a community chat bubble in the chat.
It's not supposed to only copy a community address.

Also, this seems to work for me.

**Comment by iurimatias** [comment]
as per pascals comment
