### ISSUE TITLE
Community: The field of private community key is empty

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7777]
# Bug Report

## Steps to reproduce
1. Create a community
2. Click 'Backup' and check the field of private community key

#### Expected behavior
The field is not empty
#### Actual behavior
The field is empty
<img width="587" alt="image" src="https://user-images.githubusercontent.com/14942081/194210187-058b2bec-ed10-4bea-94c6-1c7bbc84fed3.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/14942081/194210233-aa36f720-2f2d-44d5-be49-e8be1777b89c.png">

### Additional Information
Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4
Operating System: macOS Monterey

**Comment by caybro** [comment]
CC @alexandraB99
