### ISSUE TITLE
Activity center -> Mentions: mention notification text is overlapped

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7784]
### Description

1. install https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.7.x/4/ RC 4
2. wait for community to be restored (i tested it with Status community)
3. check activity center (u should be mentioned to have this notification)

<img width="1512" alt="Screenshot 2022-10-06 at 12 42 23" src="https://user-images.githubusercontent.com/82375995/194293148-ef455133-7e85-48d9-91d4-d4a0423e089f.png">

**Comment by iurimatias** [comment]
can confirm it's fixed in `release/0.7.x` after cherry picking the fix
