### ISSUE TITLE
Banner loses issue count when import progress modal is closed

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7787]
When a discord import is ongoing and progress updates are received, we also show the global issue count in the application banner.
When the modal is closed via "hide window", the issue count is lost until the next progress update is received (currently within 2secs).

Not sure yet why this is happening. Maybe @caybro you can take a look?

**Comment by caybro** [comment]
So it turns out the culprit is our (English) translation:
```xml
<message>
  <location filename="../imports/shared/panels/ModuleWarning.qml" line="185" />
  <location filename="../imports/shared/panels/ModuleWarning.qml" line="185" />
    <source>%1%</source>
    <translation type="unfinished">%1D {1%?}</translation>
</message>
```

**Comment by caybro** [comment]
Also visible here:
![](https://cdn.discordapp.com/attachments/993526936980693043/1031886500964605993/unknown.png)

**Comment by PascalPrecht** [comment]
This issue is describing a different behaviour though.

![Screenshot from 2022-10-18 14-24-05](https://user-images.githubusercontent.com/445106/196428569-e6bf4d53-01fb-4a43-adf2-447643a947a7.png)

This ^ looses its `(#n issues)` count when the modal is closed

**Comment by caybro** [comment]
> 

Might be a similar problem, will look into that

**Comment by caybro** [comment]
Some investigation; I inserted this debug:
```qml
readonly property int warnings: communitiesPortalLayoutContainer.communitiesStore.discordImportWarningsCount
onWarningsChanged: console.warn("!!! WARNINGS CHANGED IN BACKEND:", warnings)

if (warnings)
 result += qsTr("Check progress (%1)").arg(qsTr("%n issue(s)", "", warnings))
else {
  console.warn("!!! FOOBAR, progress with empty count")
  result += qsTr("Check progress")
}
```

And it yields:
```
qml: !!! WARNINGS CHANGED IN BACKEND: 16
qml: !!! WARNINGS CHANGED IN BACKEND: 0
qml: !!! FOOBAR, progress with empty count
qml: !!! WARNINGS CHANGED IN BACKEND: 16
```

So for whatever reason, the backend sends a `0` warnings value, resulting in the `(#n issues)` disappearing from the topbar
