### ISSUE TITLE
Community:A message overlaps another message

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7797]
# Bug Report

## Steps to reproduce
1. Open Status community and Messenger channel
2. Check the messages there

#### Expected behavior
The messages should overlap other messages
#### Actual behavior
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/14942081/194444059-59240ebd-5c0f-40a7-a179-dfb23f78443e.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4
Operating System: macOS Monterey

**Comment by iurimatias** [comment]
fixed in rc5
