### ISSUE TITLE
Community->Invite members: In the minimized window, the next step of inviting is not possible

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7799]
# Bug Report

## Steps to reproduce
In the minimized window
1. Create a community
2. Go to add new members
3. Select any contact and try to find the button 'Next'

#### Expected behavior
The modal is available and all elements are visible
#### Actual behavior
The button 'Next' is hidden at the bottom edge of the window
<img width="897" alt="image" src="https://user-images.githubusercontent.com/14942081/194446511-97120031-aa06-45e6-a912-8987e00dfca9.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
cannot replicate, seems fixed
