### ISSUE TITLE
ENS: The name of a user with ENS is not shown as ENS

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7800]
# Bug Report

## Steps to reproduce
1. I restored a user with an ENS name
2. Go to any chat or community channels and add a message
3. Another user check my message and don't see my name as ENS

#### Expected behavior
The primary ENS name should be shown in chats and communities
#### Actual behavior
Another user check my message and don't see my name as ENS
<img width="894" alt="image" src="https://user-images.githubusercontent.com/14942081/194447111-f890f53a-2b90-4cce-98c9-b35cb47c77f0.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/14942081/194447782-f8b97e21-0866-42ac-ac97-26c86f975ef7.png">

### Additional Information
Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4
Operating System: macOS Monterey

**Comment by jrainville** [comment]
This is likely already fixed in master. I can see people with ENS names even in the 0.8.0 RCs.
Can you check again @elina2015 ?

**Comment by iurimatias** [comment]
is this still an issue?

**Comment by jrainville** [comment]
Feel free to reopen if it happens again
