### ISSUE TITLE
Community: The logo of community is blurred

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7802]
# Bug Report

## Steps to reproduce
1. Add a good-quality picture as a community picture and save it
2. Check the community picture in the community overview
3. Open the community for editing and check the community picture
#### Expected behavior
The community picture is not blurred

#### Actual behavior
The community picture is blurred
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/14942081/194450043-1bd52829-799b-4af1-979a-43ed25ad9d00.png">
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/14942081/194450123-22f0ef63-c425-4108-b61b-bc0d11fd5439.png">
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/14942081/194450269-d75909d9-bdbc-4f8e-9d77-99b9bd290fe6.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4
Operating System: macOS Monterey

**Comment by iurimatias** [comment]
this has been fixed
