### ISSUE TITLE
Communities: the search of messages doesn't work

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7803]
# Bug Report

## Steps to reproduce
1. Add a message 'test' in any chat or community channel
2. In the secondary navigation bar click on the search field and enter 'test' 
3. Select the chat of the community channel with your message 'test' for searching

#### Expected behavior
After the loader is shown, the message 'test' is found and shown
#### Actual behavior
The loader is shown infinitely
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/14942081/194453536-7b71f21a-ded3-4774-9733-d9db4fb6ee2b.png">
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/14942081/194456110-0e716dff-1f13-4f07-8d2d-727924704cd3.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.4
Operating System: macOS Monterey

**Comment by alexandraB99** [comment]
Fixed in [status-go](https://github.com/status-im/status-go/pull/2898)

**Comment by PascalPrecht** [comment]
Here: https://github.com/status-im/status-go/pull/2898
