### ISSUE TITLE
Community chat: header buttons overlaps

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#7808]
# Bug Report

## Description

<img width="1143" alt="Снимок экрана 2022-10-07 в 13 09 01" src="https://user-images.githubusercontent.com/25482501/194529997-b38e5728-59c6-41af-8b3d-1ac5be88bb05.png">

**Comment by caybro** [comment]
@micieslak you have a PR for this, right?

**Comment by caybro** [comment]
Fixed in master already
