### ISSUE TITLE
Community settings UI bugs

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#7809]
# Bug Report

## Description

<img width="1467" alt="Снимок экрана 2022-10-07 в 13 13 22" src="https://user-images.githubusercontent.com/25482501/194530943-512be777-993a-4955-adaa-1df41e86d06b.png">

**Comment by caybro** [comment]
@noelia-santos haven't you been working on that already?

**Comment by noeliaSD** [comment]
> @noeliaSD haven't you been working on that already?

mmm yess.. it should be already on master. Let me check
