### ISSUE TITLE
Redefine onboarding objects creations/deletion and enable retranslation

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7823]
### Description

1.  Redefine onboarding related qml objects creations and deletion and syncronize them correctly with the `startupModule` since now ui and backend are "not syncronized" so it is causing a crash when retranslating, since reevaluation of bindings are causing to  calling `startupModule` that is already null.
At least `OnboardingLayout.qml` should be destroyed after loggin as it is done with the `startupModule` instance.

2. Revert https://github.com/status-im/status-desktop/pull/7822

Once it is done, ensure the app doesn't crash after changing language and it is dynamically updated on mac and windows.

**Comment by caybro** [comment]
@noeliaSD (macOS) and me (on linux) are going to try to revert the linked PR to see if the language change is applied correctly w/o restart and doesn't crash
