### ISSUE TITLE
Second Nav Tab Search: the icons don't look good if user doesn't have a profile picture

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7830]
# Bug Report

## Steps to reproduce
1. Enter some text (for example, 'r') in the search field in the Second Nav tab
2. Check the default images of users in the appeared results

#### Actual behavior
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/14942081/194670344-1759a5b5-8243-4928-b8da-bb589ee4db62.png">
<img width="862" alt="image" src="https://user-images.githubusercontent.com/14942081/194670392-f2b00e2f-a166-4a6a-99c4-8cfecec908b3.png">
<img width="773" alt="image" src="https://user-images.githubusercontent.com/14942081/194670425-eadf8be4-c503-4377-ae9e-47bfadc1f5bd.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.6
Operating System: macOS Monterey

**Comment by caybro** [comment]
Already fixed in https://github.com/status-im/status-desktop/pull/7720

**Comment by jrainville** [comment]
I can confirm that I can no longer reproduce. Closing.
