### ISSUE TITLE
Communities: there is a  horizontal scroll in the Secondary Nav bar on a Community page

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7831]
# Bug Report

## Steps to reproduce
1. Create or import a community
2. Open the community and try to horizontally scroll in the Secondary Nav bar

#### Expected behavior
There's no horizontal scroll in the Secondary Nav bar on a Community page
#### Actual behavior
There is a  horizontal scroll in the Secondary Nav bar on a Community page
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/14942081/194671586-163eeb49-31a4-4f04-9e0b-8efd3d3d0733.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.6
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
fixed in the meantime
