### ISSUE TITLE
Communities and Chats: not all messages are shown and the order of messages is wrong

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7832]
# Bug Report

## Steps to reproduce
1. Write a few messages with ordered numbers in any chat or community
2. Check these messages by other users

#### Actual behavior
The author can see all the messages that she was sending:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/14942081/194673312-cbfefa83-3e26-4ea6-bbd3-872a1c17150d.png">
Other users can see only part of these messages and not in the proper order:
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/14942081/194674586-127e42c7-87a6-4aaa-8076-d0f2860ea474.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.7.0-rc.6
Operating System: macOS Monterey

**Comment by jrainville** [comment]
This has been fixed by Patryk
