### ISSUE TITLE
C++ - CI: check if the app is run correctly

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#7836]
cpp app often fails to run on Linux due to plugin loading failure. The reason is the new, immature Qt6 CMake API we use, it does not produce the same results on different platforms (e.g. it does generate dynamic libraries for plugins defined on macOS but it does not generate them on linux).

Acceptance criteria:
- write a script that runs the app and waits for ~10s, if there is an error code returned then make the CI red
- all platforms should be covered (windows, macos, linux)

**Comment by osmaczko** [comment]
Currently, Linux is not runnable:
```
$ ./status-desktop 
QQmlApplicationEngine failed to load component
qrc:/Status/Application/qml/main.qml:8:1: Type StatusWindow unavailable
qrc:/Status/Application/qml/Status/Application/StatusWindow.qml:8:1: module "Status.Controls.Navigation" plugin "StatusQ_Controls_Navigationplugin" not found
```

that's because `qt6_add_qml_module` does not produce libraries for some reason on Linux.

**Comment by caybro** [comment]
Great idea, I'd even extend slightly to also cover the NIM app :)

Don't even need some timer/wait, just setup a SignalSpy on https://doc.qt.io/qt-5/qml-qtquick-window-window.html#frameSwapped-signal (this is first emitted as soon as the window has appeared on screen)

**Comment by osmaczko** [comment]
> Great idea, I'd even extend slightly to also cover the NIM app :)

Thanks. I don't know if it will bring any value to NIM app as we have squish tests there already :thinking: 

> Don't even need some timer/wait, just setup a SignalSpy on https://doc.qt.io/qt-5/qml-qtquick-window-window.html#frameSwapped-signal (this is first emitted as soon as the window has appeared on screen)

How would you do that exactly?  I imagine we could pass some flag (--quit-instantly-when-rendered) and only then setup the signal spy :thinking: IMO we shouldn't modify status-desktop cpp code in order to test if it runs.
