### ISSUE TITLE
Wallet -> Accounts: account alignment is broken (wallet main and settings)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7837]
### Description

1. add wallet account in main section
2. check wallet accounts list in settings

<img width="1512" alt="Screenshot 2022-10-10 at 14 41 31" src="https://user-images.githubusercontent.com/82375995/194865330-fdd2afbe-8f9a-4240-9331-edf0a1afdb55.png">

<img width="1512" alt="Screenshot 2022-10-10 at 15 21 12" src="https://user-images.githubusercontent.com/82375995/194865444-8b916361-304d-48c3-8b8d-a3e394d9803e.png">

**Comment by caybro** [comment]
@alexandraB99 needs some `asset.width/height` love :)

**Comment by anastasiyaig** [comment]
@IvanBelyakoff perhaps! :) Feel free to close then

**Comment by saledjenic** [comment]
Closing this in behalf of @IvanBelyakoff as he said it's not reproducible.
