### ISSUE TITLE
Still not fixed #7167

### ISSUE THREAD

**Issue by du64** [status-im/status-desktop#7849]
The bug at https://github.com/status-im/status-desktop/issues/7167 is still not fixed.
It works just fine until I completely close and reopen the app, or restart my laptop. Then the sidebar issue comes back.

![Screenshot from 2022-10-06 22-37-53](https://user-images.githubusercontent.com/65834069/194462904-ae2d05c7-db1f-4c8b-86a5-c3d7b5ef8b6d.png)

**Comment by du64** [comment]
Sometimes it takes two or three open and complete close to cause the glitch, but it has been bothering many people in a few communities I'm a part of

**Comment by iurimatias** [comment]
@du64 what desktop version is this happening?

**Comment by du64** [comment]
> @du64 what desktop version is this happening?

the latest merged PR
It's been an issue for atleast a year now, maybe longer

**Comment by du64** [comment]
any updates on this? anyone found a fix?

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/status-desktop/pull/8477
