### ISSUE TITLE
Community -> Activity center: notifications are overlapped and duplicated

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7850]
### Description

1. recover an account in release 7 version 
2. you should be a part of Status community and have several mentions and replied messages
3. open community and check Activity Center

<img width="1790" alt="Screenshot 2022-10-11 at 10 37 38" src="https://user-images.githubusercontent.com/82375995/195028926-e053a1fb-29c6-44be-a42e-78419896fb14.png">

**Comment by MishkaRogachev** [comment]
Should be fixed here: https://github.com/status-im/status-desktop/pull/7771
