### ISSUE TITLE
AC: showing already accepted contact request

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#7851]
# Bug Report

The AC shows a challenge to accept/reject an already accepted contact request. Furthermore, it doesn't register that the contact had been renamed meanwhile and still shows the old display name.

![Snímek obrazovky z 2022-10-11 00-58-49](https://user-images.githubusercontent.com/5377645/195036670-e8b5d2c1-daa3-4eb8-b65e-9646a45a5bba.png)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
CC @MishkaRogachev

**Comment by MishkaRogachev** [comment]
> CC @MishkaRogachev

By [designs](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1854%3A298987) AC should show accepted and declined CRs. But, yes username should be updated

**Comment by caybro** [comment]
@MishkaRogachev also the accept/reject buttons should not be there

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev also the accept/reject buttons should not be there

Why? it's required both by designs and [specs](https://docs.google.com/spreadsheets/d/1tZn24TRPHiROxz5YaLzAxZWneM2HP6MI0b1VkiPw-IA/edit#gid=0) ?

**Comment by caybro** [comment]
> > @MishkaRogachev also the accept/reject buttons should not be there
> 
> Why? it's required both by designs and [specs](https://docs.google.com/spreadsheets/d/1tZn24TRPHiROxz5YaLzAxZWneM2HP6MI0b1VkiPw-IA/edit#gid=0) ?

Not about design, it doesn't make sense when the request had been already accepted

**Comment by MishkaRogachev** [comment]
> 
> Not about design, it doesn't make sense when the request had been already accepted

Ah, i get it :)
This problem caused not by AC, but general by possibility to send CR for mutual contacts. Added this issue here: https://github.com/status-im/status-desktop/issues/7734

**Comment by caybro** [comment]
> > Not about design, it doesn't make sense when the request had been already accepted
> 
> Ah, i get it :) This problem caused not by AC, but general by possibility to send CR for mutual contacts. Added this issue here: #7734

@MishkaRogachev yeah I have a similar prob; the Design wants to display the contact request challenge message in the new Profile Dialog; that's outright impossible atm as the message only comes as part of the notification, you can't query for it later or from somewhere else :/

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev yeah I have a similar prob; the Design wants to display the contact request challenge message in the new Profile Dialog; that's outright impossible atm as the message only comes as part of the notification, you can't query for it later or from somewhere else :/

Probably we can ping @cammellos to discuss how to provide api for managing contact requests

**Comment by PascalPrecht** [comment]
@MishkaRogachev @caybro what is the state of this issue?

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev @caybro what is the state of this issue?

Iteration backlog ;)
As i remember we just need to limit user to send contact request to mutual contacts

**Comment by caybro** [comment]
I haven't seen those in some time...
