### ISSUE TITLE
Device sync: second instance of the same account recovered requires a back up of the seed

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7859]
### Description

**Precondition**: u need to install 2 instances of the same build into different folders and its data folder should be empty

1. given a known seed, recover an account
2. recover the same account on the second instance of the app

As result, the secondary instance requires a seed back up

![image](https://user-images.githubusercontent.com/82375995/195109354-a088b4d0-59bf-4017-9e44-c2c008c1de1d.png)

**Comment by igor-sirotin** [comment]
It seems that this is not an issue anymore.
Tested at latest master 7f2563edf4fa03a436cfe59ebc7ac91bb3be218a.

<img width="1584" alt="Снимок экрана 2023-01-23 в 22 00 43" src="https://user-images.githubusercontent.com/25482501/214127302-f5195bda-a7f5-4b31-94a2-c2e5e944b27c.png">
<img width="1584" alt="Снимок экрана 2023-01-23 в 22 02 26" src="https://user-images.githubusercontent.com/25482501/214127354-1e0009a0-4460-491b-a217-4dcbb9c78b32.png">
<img width="1584" alt="Снимок экрана 2023-01-23 в 22 03 40" src="https://user-images.githubusercontent.com/25482501/214127364-1fed2068-d248-446c-b6a0-eb6ca0b81f54.png">
<img width="1584" alt="Снимок экрана 2023-01-23 в 22 03 52" src="https://user-images.githubusercontent.com/25482501/214127374-3ad0ecf6-d089-4381-8745-1aef1fc27146.png">
