### ISSUE TITLE
Send Transaction Modal fix: Send to a contact

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#786]
Sending to a contact currently doesn't work because the `ContactSelector` component selects the contact's whisper key instead of his/her wallet address. May need to figure out how this is done in status-react. As it stands, attempting to send to a contact will crash the app (due to `parseAddress()` called with a whisper key as a parameter).

**Comment by jrainville** [comment]
I just tested in Status-React and the released phone version and they both **do not** support this feature. I would say, that considering the difficulty of doing that feature (there is no way to get the address of a contact unless he has an ENS name) and considering that Status-React doesn't have it either, we should move that task back to the backlog
