### ISSUE TITLE
Device sync: can't see pairing devices without restart

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7861]
### Description

**Precondition**: u need to install 2 instances of the same build into different folders and its data folder should be empty

1. given a known seed, recover an account
2. recover the same account on the second instance of the app
3. on both apps, open device settings to check pairing and click Advertise

As result, no devices to be paired with until the app is restarted

<img width="1900" alt="image" src="https://user-images.githubusercontent.com/82375995/195113555-1a4ec427-9536-481c-86a7-eb57e25cbf3e.png">

<img width="1900" alt="image" src="https://user-images.githubusercontent.com/82375995/195114111-63d8293e-16ce-4af7-950a-cfeda19c0114.png">

NOTE: weird warning shown which might not be related to the issue itself
```
WRN 2022-10-11 17:03:10.705+03:00 Error decoding signal                      topics="signals-manager" tid=795324 file=signals_manager.nim:43 err="/Users/jenkins/workspace/s-desktop_branches_macos_PR-7738/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim(746, 10) `node.kind == JArray` : items() can not iterate a JsonNode of kind JNull"
```

**Comment by jrainville** [comment]
This will probably be fixed by the re-design Igor is working on
