### ISSUE TITLE
Agree on design of ChatHeaderContentView when width is limited

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7862]
# Bug Report

## Description

There was a problem causing that buttons were inaccessible when window width was small. It's fixed by https://github.com/status-im/status-desktop/pull/7783 however this solution wasn't discussed with the design team in depth. So the design may change and inflict further changes in code.

![Screenshot from 2022-10-11 16-54-27](https://user-images.githubusercontent.com/20650004/195125788-c267678c-d30f-4f64-aad2-22a4f20e1ca4.png)

## Steps to reproduce

Create group conversation, make window width small.

#### Expected behavior

Undefined. It's the subject of that ticket.

#### Actual behavior

When width is limited buttons are located over text, with semi-transparent background.

**Comment by iurimatias** [comment]
cannot replicate this anymore
