### ISSUE TITLE
StatusCommunityTags: Improper size of the tags list

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7870]
# Bug Report

## Description

StatusCommunityTags has improper size in some cases when creating/editing community. Additionally size is improperly calculated when the component is created dynamically - https://github.com/status-im/status-desktop/pull/7869.

## Steps to reproduce

Create community popup: select four tags with the longest names
Edit community: select four tags with the longest names, set minimal window size

![Screenshot from 2022-10-12 12-24-31](https://user-images.githubusercontent.com/20650004/195332881-652b1eb2-d6e7-4047-ac23-395f6491172e.png)

![Screenshot from 2022-10-12 12-21-41](https://user-images.githubusercontent.com/20650004/195332934-cb618103-6e26-45c1-9e8f-8ab00ffed212.png)

[Kazam_screencast_00049.webm](https://user-images.githubusercontent.com/20650004/195333102-bf853b75-338d-4e01-a06d-3e3c88a51eb5.webm)

#### Expected behavior

Component size should be adequate to the content

#### Actual behavior

Width/height are improper

**Comment by iurimatias** [comment]
this has been fixed
