### ISSUE TITLE
Onboarding->Keycard: some pictures are not modified for Dark mode

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7897]
# Bug Report

## Steps to reproduce
1. In the Dark mode go to 'I am new to Status' - 'Generate keys for a new Keycard' (don't plug in the Keycard reader)
2. Plug in the Keycard reader
3. Plug in the Keycard
4. Enter some pin

#### Expected behavior
The pictures should be modified for the dark mode (the background should be dark)
#### Actual behavior
<img width="470" alt="image" src="https://user-images.githubusercontent.com/14942081/195746840-02ee3d99-b77a-4d3d-944b-42be80c6e3ba.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/14942081/195746880-042d028c-5802-4966-b662-c96e7a1c2698.png">
<img width="444" alt="image" src="https://user-images.githubusercontent.com/14942081/195747042-dca212bb-2a60-456b-8fbb-2d93550a2a98.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/14942081/195747071-6f353ac4-bf89-46ee-8ba8-50b2befd05f8.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/7646
- Operating System: macOS Monterey

**Comment by saledjenic** [comment]
@pedro-et for the keycard part I need the following images (to simulate animations) for the dark theme, here you can see what we have so far for the light theme:
https://github.com/status-im/status-desktop/tree/master/ui/imports/assets/png/keycard

**Comment by saledjenic** [comment]
@xAlisher @benjthayer could you check my previous message?

**Comment by benjthayer** [comment]
@saledjenic a quick fix would be to export all of the assets in the Figma file as PNGs - that will preserve the transparent background of the image, removing the white backing. Let me know if you'd like a hand with that.

@John-44 do you know if a set of the keycard 3D renders were ever done for dark theme? Even with the backing removed the contrast of the card won't be the best on the dark theme background (see attached)?

cc @xAlisher 

<img width="283" alt="Screenshot 2022-12-07 at 12 08 45" src="https://user-images.githubusercontent.com/110033914/206175913-20c8c986-168e-42b7-b933-3e3c1d63eb65.png">

**Comment by saledjenic** [comment]
@benjthayer as far as I see form the link above, the only images which do not have transparent background are those placed in `Card-insert-step-1` and `PIN`, for the `480px` size. So would be good if you could provide them transparent with the same size (as it's done for other images from there), that would be it, at least for now.

**Comment by caybro** [comment]
@saledjenic @benjthayer just export them with transparency on; we already have too many PNGs, no need to have 2 variants (light/dark) here
