### ISSUE TITLE
[Windows Only] Status does not launch, or it's not working properly.

### ISSUE THREAD

**Issue by Zliced13** [status-im/status-desktop#7906]
# Bug Report

## Description
When trying to open Status from the Start Menu, and from the installation folder **("$env:LOCALAPPDATA\Local\StatusApp\Status.exe")**, it does not launch at all.

## Steps to reproduce
1. Download this [installer ](https://github.com/status-im/status-desktop/releases/download/0.7.0/StatusIm-Desktop-v0.7.0-509490.exe) and run it.
2. After the installation setup is done, open your Start Menu and click on the icon called, **Status**.
3. Expect it to run, even though it does not.

#### Expected behaviour
For Status to function properly

#### Actual behaviour
Status does not launch at all.

### Additional Information
_I'll add some more information here if the devs request it from me._

— Status desktop version: 0.7.0-509490
— Operating System: Windows 10 Pro (64bit)

**Comment by du64** [comment]
Can confirm, this has happened to me on multiple Windows 10 and 11 machines and VMs

**Comment by Zliced13** [comment]
Thank you. I thought I was the only one with this problem

**Comment by du64** [comment]
> Thank you. I thought I was the only one with this problem.
> 
> The version released on the website is usable on Windows.

@Zliced13  The one on the website is quite an old build from likely a year ago or so, it's Version 0.3 while we're headed towards Version 0.8 in PRs

**Comment by Zliced13** [comment]
I'm going to try an old build from the releases page to see if one of those old builds work on Windows.

**Comment by Zliced13** [comment]
After some testing, it appears only **0.6.0-beta** , and **0.3.0-beta** actually work. **0.70** and above does not work at all.

For the Scoop app manifest file, I will have to remove autoupdate and checkver until the Status Dev's can patch this bug for Windows.

**Comment by caybro** [comment]
CC @iurimatias

**Comment by anastasiyaig** [comment]
it is still not working in RC-2 0.8.0 @iurimatias @jrainville

**Comment by elina2015** [comment]
Tested on Win 10 (VM Parallels) and it (RC-2 0.8.0) still doesn't work

**Comment by Zliced13** [comment]
Can anyone confirm if it works on Windows 11?

**Comment by Zliced13** [comment]
Oh, good to know. Thanks, @jrainville.

**Comment by iurimatias** [comment]
fixed in the next rc release

**Comment by Zliced13** [comment]
@iurimatias Thank you so much, the Status app works now when I launch it.

**Comment by Zliced13** [comment]
Proof:
![(firefox)c5I1x4_11-22-2022](https://user-images.githubusercontent.com/101912712/203425423-00a04ddb-8eb4-40a5-a01e-46d4fa6172c7.jpg)
