### ISSUE TITLE
[suite_messaging / tst_ChatFlow] - "The user can reply to the last message" scenario needs some fixes

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7909]
### Description
1. `The user can reply to the last message` scenario works **standalone** but when it runs as part of the sequence, the action of reply is not done always (sometimes yes, so check it multiple times). The popup option to reply seems to not appear sometimes.

2. Add validation to ensure the last message is really a reply, now just checking the last message is the expected one but could not be a reply. It needs a new verification method in `StatusChatScreen`.

3. Once it is updated, remove `mayfail` tag.

**IMPORTANT**: Ensure it works standalone and also as part of the sequence.

### Additional information
Master commit `80dfe2a4eaefcc1899c331185bc977a2e8a2dfe0`

**Comment by PascalPrecht** [comment]
Created #8308 for tests being flaky at times.
