### ISSUE TITLE
[suite_messaging / tst_ChatFlow] - "The user can activate image unfurling" scenario fails

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7913]
### Description
1. `The user can activate image unfurling` scenario works **standalone** but when it runs as part of the sequence, the action to **activate link preview** doesn't work.

2. Once it is updated, remove `mayfail` tag.

**IMPORTANT**: Ensure it works standalone and also as part of the sequence.

### Additional information
Master commit `80dfe2a4eaefcc1899c331185bc977a2e8a2dfe0`

**Comment by 0x-r4bbit** [comment]
This seems to work just fine as of latest master, also the `@mayfail` tag does not exists on that test anymore
Closing as solved.
