### ISSUE TITLE
Dialogs are blurry at some specific window heights

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7914]
# Bug Report

## Description

Some dialog, e.g `ProfileDialog` tends to be blurry when window is maximized and dialog has more space than required:

![Screenshot from 2022-10-14 13-54-41](https://user-images.githubusercontent.com/20650004/195841155-097d09ed-bde4-40aa-b179-b5a47cb52abe.png)

Dialog is not blurry when window height is limited and dialog is squeezed: 
![Screenshot from 2022-10-14 13-54-50](https://user-images.githubusercontent.com/20650004/195841158-bff8f8d1-b382-4f76-ae0c-6418ee8300ec.png)

When printing dialog's `y` property it shows:
```
qml: y: 64 <-- here dialog is squeezed, y pos is fixed and is integral, looks ok
qml: y: 65.5 <-- y pos is fractional, looks blury
qml: y: 66.5
qml: y: 68.5
qml: y: 70.5
qml: y: 72.5
```
It's seems to be general problem, I observed it for another dialogs as well. It may be even Qt bug, because `y` pos relies on that in `StatusDialog.qml`:
```
    anchors.centerIn: Overlay.overlay
    margins: 64
```
In `Item` it's resolved by property `anchors.alignWhenCentered` which is false by default preventing fractional positioning. It's not present in `Dialog`. Generally, probably subject of a separate issue.

## Steps to reproduce

Open popup, e.g. ProfilePopup when window is maximized.

#### Expected behavior

Fonts, edges, icons are "sharp".

#### Actual behavior

Fonts, edges, icons are "blurry".

### Additional Information

- Operating System: Ubuntu 20.04
- Screen resolution: 1920x1080, scalling 100%
- Qt version: 5.14.2

**Comment by micieslak** [comment]
![Screenshot from 2022-10-17 10-08-03](https://user-images.githubusercontent.com/20650004/196123544-7d1aa575-791a-4270-9f5d-493eb5bc814d.png)
![Screenshot from 2022-10-17 10-08-14](https://user-images.githubusercontent.com/20650004/196123546-88865df3-4613-4a8c-89ea-a477a0f8825b.png)
without alias - ok, with alias - blurry

**Comment by iurimatias** [comment]
cannot replicate anymore
