### ISSUE TITLE
[suite_messaging / tst_ChatFlow] - Add new test scenario  "The user can reply to his / her OWN message"

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7915]
### Description
 Add the following scenario in `suite_messaging / tst_ChatFlow`:

````
Scenario Outline: The user can reply to his / her own message
         When the user sends a chat message <message>
         And the user replies to the message at index 0 with <reply>
         Then the chat message <reply> is displayed as an own reply
         Examples:
		 | message | reply  |
		 | random chat message | This is an own reply |

````
Add validation to ensure the last message is really a reply to an **own** message. It needs a new verification method in `StatusChatScreen`.

**IMPORTANT**: Ensure it works standalone and also as part of the sequence.

**Comment by jrainville** [comment]
Closing this as we no longer support public chats and that test already exists as part of CommunityMessageFlows
