### ISSUE TITLE
Settings->Profile: ProfileDialog preview presents only saved state, not actual preview of edit tab

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7917]
# Bug Report

## Description

Preview tab should present the temporary state from edit tab, not the already persisted state.

Related to https://github.com/status-im/status-desktop/pull/7621

[Kazam_screencast_00060.webm](https://user-images.githubusercontent.com/20650004/196128291-a3400f3b-3140-400f-ab4e-f6d01047374f.webm)

## Steps to reproduce

Go to Settings->Profile, change name, description, profile picture, go to preview tab

#### Expected behavior
Preview tab serves real preview

#### Actual behavior
Preview tab show the same content as if we would click in left bottom corner (profile icon) and click "view my profile"

**Comment by caybro** [comment]
CC @John-44 please provide some insight on how this preview should ideally work
