### ISSUE TITLE
SocialLinkPreview: links are too short to display even short urls

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7918]
# Bug Report

## Description

Social links are too short to display even short links reasonably:
![Screenshot from 2022-10-14 13-17-56](https://user-images.githubusercontent.com/20650004/195837571-1a2adb8a-6a12-4847-ae05-c364bbb92849.png)

## Steps to reproduce
Settings -> Profile, add social links to the profile, save, open profile dialog

#### Expected behavior

Links are long enough to display e.g. github profile link

#### Actual behavior

Even short urls are elided

**Comment by PascalPrecht** [comment]
I could be wrong here, but common sense would be to not show the entire URL but instead render the username only.
If we know it's a github link, simply show only the github user.
If we know it's a twitter link, simply show only the twitter user name.

It would still have a complete link behind the scenes obviously. But this way you'd have a nicer UI and remove the somewhat redundant URL prefix.
