### ISSUE TITLE
Profile: input limit counting doesn't work correctly for non-standard input

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7919]
# Bug Report

## Description

It's impossible to save changes to user's profile in some cases, e.g. when using emojis:

[Kazam_screencast_00059.webm](https://user-images.githubusercontent.com/20650004/195840317-eb624b70-92f4-4c0a-af7d-4f83a37d321e.webm)

Console log:

```
ERR 2022-10-17 10:46:51.495+02:00 error setting bio                          topics="settings-service" tid=1034912 file=service.nim:822 errDesription="\nstatus-go error [methodName:settings_setBio, code:-32000, message:invalid bio length ]\n"
```

## Steps to reproduce

Settings -> Profile, copy emojis hash from profile preview to the profile description multiple time to reach input length limit

#### Expected behavior

Emojis should be counted adequately.

#### Actual behavior

Emojis are counted as a single char, resulting with error on save.

**Comment by caybro** [comment]
I assume it's because (some) emojis are actually UTF-16 which means 2 "characters" so they're not counted correctly

**Comment by micieslak** [comment]
> I assume it's because (some) emojis are actually UTF-16 which means 2 "characters" so they're not counted correctly

Yeah, probably that's the reason.

**Comment by jrainville** [comment]
Fixed here https://github.com/status-im/status-desktop/pull/8192
