### ISSUE TITLE
ProfileDialog: bio text should have maximum height defined

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#7922]
# Bug Report

## Description

The dialog doesn't look correct when bio has many new lines.

[Kazam_screencast_00063.webm](https://user-images.githubusercontent.com/20650004/196141705-1644d747-ea99-4416-8e65-dc2315ae816f.webm)

Additionally profile edit form doesn't behave properly when vertically long bio is set:

[Kazam_screencast_00064.webm](https://user-images.githubusercontent.com/20650004/196141723-386402ab-f4a6-490f-8fb3-31a69cfe9b32.webm)

## Steps to reproduce

Set bio with many new lines

#### Expected behavior

Bio text should have maximum height, when more space is required it should be scrollable.

#### Actual behavior

the whole modal content is very long

**Comment by jrainville** [comment]
@mprakhov for the maximum height, you can ask Benji or Julia from the design team as they worked on the profile.
If they don't answer fast enough, just use your best judgement and we'll update with the final height when we have it

**Comment by mprakhov** [comment]
@juliaiskandarian @benjthayer 
Could you please provide me expected maximum height?

**Comment by benjthayer** [comment]
@jrainville @mprakhov @micieslak the design team are currently discussing this and will get back to you asap

**Comment by mprakhov** [comment]
@benjthayer any updates?

**Comment by benjthayer** [comment]
@mprakhov I've worked up a few design options which I will review with the team today. There are a few related considerations that need to be resolved at the same time:

On the authoring side (here)
- Do we allow carriage returns
- If yes, do we expand the bio input as the user fills it
- Do we have a max height for the bio input 
- If using a max height for the bio input we need to consider implementing a nested scrollbar for that input so the user can review their bio before saving

On the user side (someone visiting the profile card)
- How do we present bios with extensive carriage returns
- Do we truncate/crop the bio and have an expand / collapse function for people to view the full bio OR
- Do we show the bio in full 

I'll come back to you later today either with recommendations from the design team or confirmation that we require sign off from John
