### ISSUE TITLE
Communities Portal: The tags don't change their color after clicking

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7947]
# Bug Report

## Steps to reproduce
1. Go to Communities Portal and click any tag
2. Click the same tag and don't move the cursor 

#### Expected behavior
The tag is changed its color to white because after clicking it's not selected
#### Actual behavior
The color of the tag is still the same as it is selected
### Additional Information

https://user-images.githubusercontent.com/14942081/196581722-f7a1e5dc-c1f6-44aa-b6ad-446f4a879322.mov

- Status desktop version: https://github.com/status-im/status-desktop/pull/7941
- Operating System: macOS Monterey

**Comment by PascalPrecht** [comment]
Not reproducible in latest `master` (`8062ff968b2f6a8cdabf2df480d4f219fbe18890` at the time of writing this comment)
