### ISSUE TITLE
Use https:// deep links instead of status-im:// - MacOS

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#7957]
Docs: https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app

Related discussions: https://github.com/status-im/status-web/issues/327

**Comment by jrainville** [comment]
Has this been brought up with the right people at Status (eg Jakub)?

**Comment by endulab** [comment]
This topic was discussed in a deep link channel with @John-44
Jakub maintains the old website which we do not want to improve. I checked the code and now it handles only /u link correctly.
The new website will be created by Pavel and Felicio and will be hosted at status.app and will handle status-app internal links.

**Comment by borismelnik** [comment]
waiting for feedback from web team.

**Comment by felicio** [comment]
@borismelnik did you verify the `appIDs` as per https://developer.apple.com/documentation/xcode/supporting-associated-domains?language=objc and https://github.com/status-im/universal-links-handler/blob/b1bb906857c9b134e909562bb5acfaf0d0c92747/resources/apple-app-site-association.json#L6?

**Comment by felicio** [comment]
Also, for the `status-app://` scheme the association file shouldn't be necessary.

**Comment by felicio** [comment]
@borismelnik, in the meantime, and just like https://github.com/status-im/status-desktop/issues/9549#issuecomment-1431096996 as well, were you able to at least test the query params?

**Comment by borismelnik** [comment]
> @borismelnik, deployed the association file for https://status-website-dat9ziqdi-status-im-web.vercel.app/.
> 
> Could you test `https://` now too?
> 
> After merging the related PR, it'll also be available at https://status-web-website.vercel.app.

lets try :) but which kind of link I can use? any example?

**Comment by felicio** [comment]
@borismelnik please, reference https://github.com/status-im/status-desktop/issues/8102#issuecomment-1574238326 and consider the above.

For example, https://status-website-dat9ziqdi-status-im-web.vercel.app/c#zQ3shYSHp7GoiXaauJMnDcjwU2yNjdzpXLosAWapPS4CFxc11.

**Comment by jrainville** [comment]
@borismelnik the app itself doesn't support the new format, but `urls_manager`, it should the full link anyway with  `Unsupported deep link structure`. 

As long as the https link opens the app and we get it in the app, then it means it works. We'll support the new format with the other issues you are assigned to.

**Comment by borismelnik** [comment]
@jrainville @felicio Now my tests is working fine. 

![Image](https://github.com/status-im/status-desktop/assets/82511785/55c9eccc-0cf3-4d10-b10c-5d42c72cb6fe)

I need to move to our code and investigate how we sign it for Mac OS.

**Comment by felicio** [comment]
@borismelnik since you've closed this one, what's the expected final version of `.well-known/apple-app-site-association` file?

I'd like to resolve https://github.com/status-im/status-web/pull/418#discussion_r1223330670 and merge the PR.
