### ISSUE TITLE
[suite_communities / tst_communityMessageFlows] - "The user pins and unpins messages" scenario fails

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7962]
### Description
The action step is broken and check if #6554 is already fixed to remove `mayfail` tag.

**IMPORTANT**: Ensure it works standalone and also as part of the sequence.

### Additional information
Master commit `80dfe2a4eaefcc1899c331185bc977a2e8a2dfe0`

**Comment by jrainville** [comment]
Fixed in #8275
