### ISSUE TITLE
Find better way to display deleted messages that are replies

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7982]
![Screenshot from 2022-10-20 13-40-45](https://user-images.githubusercontent.com/445106/196939197-b2f67d19-cceb-4dbe-bce6-1a7b197e8c01.png)

I wonder if we should/could come up with a better way to render reply-to-messages that have been deleted.
Don't have a concrete proposal here. Only that the blue circle thingy usually indicates that we're trying to render a reply-to-message that doesn't live in memory (yet)

How about we should more something like "this message has been deleted" instead of "<deleted>" plus the circle?

**Comment by caybro** [comment]
Problem here is that I noticed `<deleted>` gets also displayed if the original message hasn't been loaded yet

**Comment by iurimatias** [comment]
this has been fixed/improved
