### ISSUE TITLE
set nodeconfig values before login

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#8003]
There are some node config settings that would be ideal to be able to setup before login in the app, as well from within the app are:
- Port numbers (TCP and UDP for Waku, DiscV5 and History Protocol):  it would let the final user be able to switch ports to whatever they need without having to deal with environment variables. Users should be able to set a custom port number, automatically get a free port number, or reset the number to the default. IMO it's one of the most important settings to be able to control, since port config can stop you from login. Also we should probably change the port number for various protocols to be random (might require changes in status-go / go-waku).
- Cluster config: The user should be able to setup to which nodes the app would connect to, without having to login and connect to the default status nodes. The user should also have the option once they have login to manually register custom peers and connect to them (depends on https://github.com/status-im/status-go/pull/2438)
- Log level: useful for debugging, in case an user runs into an issue during login that would not let them change the log level.

Other useful settings that we should consider to let the user be able to set them up before login could be the following:
- Enabling / Disabling discovery
- Enabling / Disabling NAT: this should affect both the parts related to go-ethereum as well as go-waku and history protocol
- Fleet
- Enabling / Disabling mailserver cycle
- Full / Light node

**Comment by igor-sirotin** [comment]
Let's implement it as CLI options. But only one by one there's particular need.
