### ISSUE TITLE
[suite_communities / tst_communityFlows] - All scenarios are failling bc the background sequence is broken

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#8009]
### Description

There is an issue with the background sequence. `Community Portal` is not clicked sometimes so scenarios cannot start.

Once it is updated, remove all `mayfail` tags.

### Additional information
Master commit `80dfe2a4eaefcc1899c331185bc977a2e8a2dfe0`

**Comment by jrainville** [comment]
Gonna fix that

**Comment by noeliaSD** [comment]
Please fix it on top of this https://github.com/status-im/status-desktop/pull/7987 or wait it to be integrated!

**Comment by jrainville** [comment]
This landed in master
