### ISSUE TITLE
Extend community with active members count information

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#8016]
### Description

Community cards should display the active members count.

![image](https://user-images.githubusercontent.com/33099791/197477345-f3686ddc-e169-44c4-8eca-aa6c4b8cd790.png)

### Acceptance criteria
- [x] define what active member means
  - Active members - number of users who posted at least 1 message in the last 7 days
- [x] status-go: extend community description with active members count
  - owner node should recalculate active members once per day
  - active members count recalculation should be performant to not block the database (consider the case of 50k+ users, many channels and messages)
- [x] status-desktop(nim): extend model with active members count
- [x] status-desktop(qml): ensure active users is rendered properly on community portal cards

**Comment by anastasiyaig** [comment]
@osmaczko @jrainville is it still planned for 0.9.0?

**Comment by osmaczko** [comment]
> Active members - number of users who posted at least 1 message in the last 7 days

FYI @John-44
