### ISSUE TITLE
Community member list still shows 3-word-alias

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8022]
Haven't looked into why this happens but when I've noticed when testing communities with multiple members, sometimes a member of the community looses their display name and renders their 3 word password instead:

![Screenshot from 2022-10-24 11-27-52](https://user-images.githubusercontent.com/445106/197494931-48cfaa33-893c-48df-a16a-933e9fe7a3f9.png)

Sometimes, this happens after a, say, second member has joined the community.

Steps to reproduce (not 100% reliable, as this doesn't always happen):

1. Create desktop instance, use account A to create community
2. Run second desktop instance, use account B
3. Invite account B to the community via account A
4. Join/request access from account B
5. Log out of account B and create account C on second desktop instance
6. Repeat 3) with account C instead of B
7. Repeat 4)

Then at some point, a member might loose their display name. In the case of the screenshot, the first member no longer shows their display name

**Comment by PascalPrecht** [comment]
Turns out this is only the case for members that don't know each other. In this particular case, the screenshot was taking from the perspective of `member2` which as not seen `member1` before.

Because these two are no contacts, member2 doesn't know about member1's display name.

**Comment by zah** [comment]
I'm encountering the same issue.
A curious work-around that I've discovered is that you can send a contact request to any of the affected users in the community roster which leads to their display name being reviewed even before they accept the contact request.

**Comment by jrainville** [comment]
@igor-sirotin you can reuse the same mechanism you did for the contact request popup of fetching the contact details from mailserver. You can also reuse the loading animation **if it doesn't bump the cpu usage**. Make sure that if a few of those are loading at the same time, having the loading multiple times doesn't create a huge CPU spike.

**Comment by jrainville** [comment]
I'm gonna close this. Status-go was changed to no longer show 3 word names, but compressed pubkeys as alias

**Comment by igor-sirotin** [comment]
@jrainville maybe makes sense to rename this issue then?
We still need to request members info from mailserver. Otherwise for some members we'll see pubkeys.
