### ISSUE TITLE
[StatusAnimatedStack] Item's visibility is not changing accordingly when it's the current

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#8024]
### Description
Fix items visibility when navigating through the stack, currently visibility is confusing, see video:

https://user-images.githubusercontent.com/31625338/196982590-8daf01f8-011a-488a-835d-4c7352fe4116.mov

**Comment by noeliaSD** [comment]
As agreed with the `ui-team`, we don't see any visual issue in the reported video so this task can be closed.
