### ISSUE TITLE
Pending community membership request isn't reflected everywhere properly

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8031]
Alright here's the scenario:

1. I have two desktop instances with account A and account B respectively
2. Account A creates a community with "Request access to join" checked
3. Account A sends invite to/shares community with account B
4. Account B requests access
5. Account A receives request to join

At this point, account A should:

1. See a little badge icon in the community tab button in the app navbar, indicating that there's **something**
2. See a notification in the activity center (I believe @MishkaRogachev is working on this)
3. See a "pending" request in the members list of the community

Here's what account A sees instead:

![Screenshot from 2022-10-25 10-18-46](https://user-images.githubusercontent.com/445106/197722663-55c6b00c-3f77-4e90-a116-0a4099678a35.png)

1. There's no indicator in the community tab button that **something** is there the user should take a look at (I know, the community tab button is currently active so one might think this has just been marked as "seen", but there was no indication in the first place).

2. There's a membership requests item which probably shouldn't be there anymore, but I think this will probably be removed by the time @MishkaRogachev is done with his work

Then:
![Screenshot from 2022-10-25 10-19-05](https://user-images.githubusercontent.com/445106/197723100-a0480408-3b2f-4172-a0fd-35317f112507.png)

There's no indication in the members list of the community that there's a pending membership request. If there wasn't the deprecated membership request item in the community view, I wouldn't know that there was a pending request!

Activating the pending requests tab, does reveal the pending request:
![Screenshot from 2022-10-25 10-27-32](https://user-images.githubusercontent.com/445106/197723476-b383f584-288f-42c7-8df8-9db971167650.png)

**Comment by iurimatias** [comment]
this has changed a lot and seems to be working correctly now
