### ISSUE TITLE
User profile not in sync between contacts

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8047]
# Bug Report

## Description

User profiles are not in sync between contacts. Within a reasonable amount of time the users current profile should sync to all contacts.

## Steps to reproduce

1. User sets profile picture
2. User sets ENS
3. User logs into fresh instance of Status - *do not set profile picture or restore ENS*
4. Profile shown differently to different users - with ENS and profile picture when user is shown neither.

Profile shown to current user:
![image](https://user-images.githubusercontent.com/50769329/198010822-ed7b2b66-2d72-409b-bc9a-59cd9a00f3a4.png)

Profile shown to contact 1:
![image](https://user-images.githubusercontent.com/50769329/198010607-7dd8f510-5f64-4b22-85af-84bb6bd37c6f.png)

Profile shown to contact 2:
![image](https://user-images.githubusercontent.com/50769329/198010654-4cb3d97a-ca4f-4040-bb9e-39d8581a28d1.png)

---
#### Expected behavior

Within a reasonable amount of time the users current profile should sync to all contacts

#### Actual behavior

User and contacts see different versions of the same profile.

### Additional Information

- Status desktop version: 0.8.0 rc
- Operating System: Mac

**Comment by jrainville** [comment]
I think this is by design. We only re-share the image when the user sends a new message. It's not super intuitive, but it was to save bandwidth on the network as far as I remember. cc @cammellos @Samyoul

**Comment by iurimatias** [comment]
probaly already fixed

**Comment by jrainville** [comment]
I can't reproduce this anymore. Feel free to reopen with different steps if you do
