### ISSUE TITLE
Invite to community broken

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#8048]
# Bug Report

## Description

Impossible to send invite to community message

## Steps to reproduce

1. Create or open administered community
2. Invite user(s) to community
2a. Using invite to community button from sidebar
2b. Using invite to community button on community overview page

#### Expected behavior

Invite users to community opens

#### Actual behavior

Nothing happens. Debug output:
```
CommunitySettingsView.qml:211: Error: Insufficient arguments 
```

**Comment by caybro** [comment]
Already fixed with https://github.com/status-im/status-desktop/pull/8039
