### ISSUE TITLE
tst_wallet causes big spike in TCP TIME_WAIT sockets

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-desktop#8057]
## Description

This is an issue that sometimes shows up as the following error:
```
RuntimeError: Could not connect to Squish server at host localhost, port 44451:
Connection refused (possible reasons: 'squishserver' process not running or listening on a different port, or firewall issue)
```
The port of course changes, but the fundamental issue is that when the `tst_wallet` suite runs we can see a big spike in `TIME_WAIT` sockets:

![image](https://user-images.githubusercontent.com/2212681/198082555-f81e4426-c25b-4900-977f-1a4206fac6dd.png)
```
2022-10-26T16:16:57Z test case tst_wallet started
2022-10-26T16:22:33Z test case end
```
https://ci.status.im/job/status-desktop/job/branches/job/uitests/job/PR-7789/58/console

The biggest spike appears right before the test suite finishes.

This issue was originally identified in:

* https://github.com/status-im/status-desktop/pull/8051

You can see some more examples in https://github.com/status-im/status-desktop/pull/8051#issuecomment-1292276298.

## Additional Information

I've managed to collect some extra information when this was happening:

* [`netstat_20221026T162216Z.log`](https://github.com/status-im/status-desktop/files/9871928/netstat_20221026T162216Z.log) - Which contains 964 sockets, out of which 931 are in `TIME_WAIT` state.
* [`ps_20221026T162216Z.log`](https://github.com/status-im/status-desktop/files/9871934/ps_20221026T162216Z.log) - Which contains the process tree at the time when the `tst_wallet` test suite was running.

**Comment by jakubgs** [comment]
The majority of the 931 waiting connections - 924 specifically - appear to go to a set of hosts on port 443:
```
 > awk '/:443.*TIME_WAIT/{a[$5]++}END{for (i in a){ printf "%5s %s\n", a[i], i}}' netstat_20221026T162216Z.log | sort -n   
    1 40.115.22.134:443
    1 52.86.9.69:443
    2 140.82.121.3:443
    2 2a06:98c1:3123:e000:443
    2 34.238.6.113:443
    3 54.173.154.254:443
    4 3.232.1.102:443
    6 2600:9000:2436:a200:443
    6 34.200.194.21:443
    6 54.172.96.17:443
    6 54.221.95.219:443
    8 18.214.252.96:443
    8 44.193.148.201:443
    9 34.192.34.171:443
   10 107.20.222.254:443
   11 18.209.201.173:443
   11 3.233.248.118:443
   11 35.168.85.49:443
   14 35.153.115.211:443
   17 44.205.150.96:443
   20 3.225.79.167:443
   22 3.220.87.117:443
   33 54.145.81.193:443
   34 3.214.39.19:443
   36 54.225.175.245:443
   37 52.204.65.9:443
   40 34.193.120.156:443
   50 34.198.248.229:443
   62 52.201.176.35:443
   62 52.71.227.115:443
   68 34.224.147.8:443
   73 54.146.140.238:443
  109 34.199.52.146:443
  140 35.171.65.55:443
```
And they all appear to go to Infura:
```
 > awk '/:443.*TIME_WAIT/{a[$5]++}END{for (i in a){ printf "%5s\t%s\n", a[i], i}}' netstat_20221026T162216Z.log | sort -n | tail -n 8 | cut -f2 | xargs -I{} curl -svk https://{} 2>&1 | grep subject:
*  subject: CN=*.infura.io
*  subject: CN=*.infura.io
*  subject: CN=*.infura.io
*  subject: CN=*.infura.io
*  subject: CN=*.infura.io
*  subject: CN=*.infura.io
*  subject: CN=*.infura.io
*  subject: CN=*.infura.io
```
But why so many?

**Comment by alaibe** [comment]
A possible reason: we reach the max number of call we can make with this infura api key

In the wallet we are currently working on reducing the number of call we do to infura but clearly not there yet.

We have ganache in place but we need to look at why it is not working

**Comment by jakubgs** [comment]
Most connections appear to be aborted via `userclosed` or `baddata` states:

![image](https://user-images.githubusercontent.com/2212681/198089836-182a55e6-535a-4363-88a3-65a0d06cefb8.png)

According to Netdata docs:

* `BadData` - happens while the connection is on FIN_WAIT1 and the kernel receives a packet with a sequence number beyond the last one for this connection - the kernel responds with RST (closes the connection).
* `UserClosed` - happens when the kernel receives data on an already closed connection and responds with RST.

**Comment by jakubgs** [comment]
Looks like this is still a problem:

![image](https://user-images.githubusercontent.com/2212681/203031453-b2538f2a-99ea-4cbc-8e8a-f6902ec69e33.png)
```
RuntimeError: Could not connect to Squish server at host localhost, port 33651: Connection refused (possible reasons: 'squishserver' process not running or listening on a different port, or firewall issue)
```
https://ci.status.im/job/status-desktop/job/branches/job/uitests/job/PR-8322/2/squishResults_221121_080809.928/webreport_221121_080809.928_linux-01/index.html

Although in this case the wallet case ran at `09:10:21`:
```
09:10:21  2022-11-21T08:10:21Z test case tst_wallet started
09:10:24  2022-11-21T08:10:24Z test case ended
```
Bu the graph shows a spike much later:

![image](https://user-images.githubusercontent.com/2212681/203032158-3ca5e11f-2a07-4b5c-b7ae-754ea1e7bcde.png)

So seems unrelated in this case.

**Comment by iurimatias** [comment]
@jakubgs is this still an issue?

**Comment by jakubgs** [comment]
I have not heard about it in a while. Maybe not?

**Comment by jakubgs** [comment]
Apparently this is still an issue:
```
RuntimeError: Could not connect to Squish server at host localhost, port 33913: Connection refused (Screenshot taken from the desktop is invalid)
```
```
RuntimeError: Could not connect to Squish server at host localhost, port 44591: Connection refused (Screenshot taken from the desktop is invalid)
```
https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-e2e/job/PR-10434/12/squishResults_230505_155319.783/webreport_230505_155319.783_linux-05/index.html

What's worth noting in this case is that different tests suits get a different Squish server process listening on a different port.
In this case those ports are `33913` and `44591`, and the error is `Connection refused`, which suggests that the process is active, but it's actively rejecting connections, which might indicate that it's either broken, or shutting down.

**Comment by jakubgs** [comment]
If we check the process limits of a `squishserver` process on a CI host while it runs we can see those are very high:
```
admin@linux-05.he-eu-hel1.ci.devel:~ % cat /proc/$(pgrep squishserver)/limits | grep files
Max open files            1048576              1048576              files 
```
And even if we were hitting a max open files limit, we would not see a `connection refused`, but something different.

**Comment by jakubgs** [comment]
If we look at an example process of a Squish server and runner we can see the port is specified as a flag:
```
admin@linux-05.he-eu-hel1.ci.devel:~ % ps faux | grep squish
jenkins  2405576  0.1  0.0 242036 10336 ?        Sl   16:31   0:00  |           \_ /opt/squish-runner-7.1-20230222-1555/lib/_squishserver --local
jenkins  2405580  0.0  0.0 284100 15504 ?        Sl   16:31   0:00  |           \_ /opt/squish-runner-7.1-20230222-1555/lib/_squishrunner --host localhost --port 39723 --debugLog pawl --testsuite /home/jenkins/workspace/_linux_x86_64_tests-e2e_PR-10567/test/ui-test/testSuites/suite_settings --reportgen html,/home/jenkins/workspace/_linux_x86_64_tests-e2e_PR-10567/squish_2_737/webreport_230505_162619.667_linux-05 --reportgen xml2.2,/home/jenkins/workspace/_linux_x86_64_tests-e2e_PR-10567/squish_2_737/result_230505_163154.098.xml --snoozeFactor 1.0 --retry 2 --tags ~mayfail --tags ~merge --tags ~relyon-mailserver --exitCodeOnFail 188
jenkins  2405587  1.5  0.0 449816 58992 ?        Sl   16:31   0:01  |           |   \_ /opt/squish-runner-7.1-20230222-1555/lib/_squishrunner --host localhost --port 39723 --testcase tst_mainSettingsSection --reportgen raw,/tmp/squishrunner_report_2405580 --wrapper Qt --objectmap /home/jenkins/workspace/_linux_x86_64_tests-e2e_PR-10567/test/ui-test/testSuites/suite_settings/objects.map --snoozeFactor 1 --resultdir /home/jenkins/workspace/_linux_x86_64_tests-e2e_PR-10567/squish_2_737/webreport_230505_162619.667_linux-05/data --suiteVersion 3 --tags=~mayfail --tags=~merge --tags=~relyon-mailserver --retry 2
```
In this case the port is `39723`, and is managed by the Squish Jenkins plugin.

My best bet is those rejected connections are either a bug in either the `squishserver` binary or the Jenkins Squish plugin.
