### ISSUE TITLE
crash when blocking a contact

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8068]
# Bug Report

Try to Block any contact, Confirm in the dialog and 100% crash in status-go. Started happening recently; current version: `v0.97.3-323-g993c236c0`, last known good version: `v0.97.3-306-g7eb66d09e`

## Description

Block a contact, crash with the following backtrace:
```
DBG 2022-10-27 12:45:13.965+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=426515 file=core.nim:20 rpc_method=wakuext_blockContactDesktop
ERR 2022-10-27 12:45:14.098+02:00 rpc response error                         topics="rpc" tid=426515 file=core.nim:29 err="\nstatus-go error [methodName:wakuext_blockContactDesktop, code:-32000, message:no such column: a.community_id ]\n"
INF 2022-10-27 12:45:14.098+02:00 shutting down...                           topics="status-app" tid=426515 file=nim_status_client.nim:145
Traceback (most recent call last)
/home/michalc/workspace/status-desktop/src/nim_status_client.nim(181) nim_status_client
/home/michalc/workspace/status-desktop/src/nim_status_client.nim(155) mainProc
/home/michalc/workspace/status-desktop/src/app/boot/app_controller.nim(243) delete
/home/michalc/workspace/status-desktop/src/app/global/global_singleton.nim(67) delete
/home/michalc/workspace/status-desktop/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:622: run-linux] Error 1
```

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by caybro** [comment]
CC @iurimatias

**Comment by osmaczko** [comment]
I can't reproduce it on the latest master(8062ff968b2f6a8cdabf2df480d4f219fbe18890) . @caybro could you please verify?

https://user-images.githubusercontent.com/33099791/200333706-5db3467e-6038-4378-abf7-0eda17903ce6.mp4

**Comment by caybro** [comment]
> I can't reproduce it on the latest master([8062ff9](https://github.com/status-im/status-desktop/commit/8062ff968b2f6a8cdabf2df480d4f219fbe18890)) . @caybro could you please verify?
> 
>  block-contact-2022-11-07_15.21.29.mp4

Yeah I can still reproduce but as we discussed with @richard-ramos, it's due to a broken DB :/ Feel free to close at will; the only solution for this is apparently wiping the account and start from scratch (restoring from a seed phrase)
