### ISSUE TITLE
Status desktop looks nothing like the mobile app redesign

### ISSUE THREAD

**Issue by du64** [status-im/status-desktop#8078]
I'm just curious, why doesn't Status Desktop look like the mobile app? 
I thought the goal was to create consistency, just like what Discord did with their apps.

The icons, navigation, border radius, button styling, and other things look completely different.

Any plans to consolidate the designs into something coherent across all platforms?

**Comment by iurimatias** [comment]
hey @du64 , there are new designs on the pipeline that will make the designs consistent
