### ISSUE TITLE
Import tool: Handle message formatting

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#8086]
@caybro has noticed that imported messages that contain, say, code snippets, are not properly interpreted.

I believe this applies to any kind of formatting but have to verify.
If I'm not mistaken, there's a "parsedText" and "text" property in status messages. So one thing we might need to do is properly parse the message contents first so they get translated properly.

**Comment by caybro** [comment]
Yes, it applies to all (markdown) formatting

**Comment by PascalPrecht** [comment]
This will be handled by https://github.com/status-im/status-go/pull/2933
