### ISSUE TITLE
Fix `enum CommunityChat` value. Rename `MessageType` to `ChatType` in message structure.

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8092]
# Bug Report

1. We have `enum ChatType` copied several types with a type for `CommunityChat = 6`.
According to `enums.proto`, it should be `5`.

2. Another thing is that we have `messageType` property, which should be `ChatType`.
It's coming from `enums.proto` and is propagated everywhere, ending in QML components.

![image](https://user-images.githubusercontent.com/25482501/198668047-5b5388e6-96c4-403a-99e7-a3eb59dec97d.png)

**Comment by caybro** [comment]
Wow... same enum duplicated in 4 different places (and 4 different languages)? Can't wait for the CPP port :smiling_imp:

**Comment by caybro** [comment]
What I meant in general with enum values; here an enum is exposed directly from C++ to QML, no duplication:

![image](https://user-images.githubusercontent.com/5377645/198673194-37f8c6d3-0def-4aab-a104-0fe0e592985b.png)

**Comment by caybro** [comment]
> @caybro And it's already wrong it C++ smile

I kinda expected it... but I have to wonder then whether exporting such enum values from `golang` directly to `C++` is feasible

**Comment by igor-sirotin** [comment]
Nevermind, all values are correct. Here's the correct `enum` to reference to:
https://github.com/status-im/status-go/blob/31144ed5a38589fd129945b634f54e800b39645a/protocol/chat.go#L29-L38
