### ISSUE TITLE
 status-desktop doesn't work on Windows 11

### ISSUE THREAD

**Issue by arnewc** [status-im/status-desktop#8098]
# Bug Report

## Description

<Nothing happens after clicking run
Has anyone else found a similar problem?
- Status desktop version:StatusIm-Desktop-v0.7.0-509490
- Operating System: Windows 11 21H2 （22000.1165）

**Comment by du64** [comment]
tested in a VM, works just fine for me

**Comment by jrainville** [comment]
Duplicate of https://github.com/status-im/status-desktop/issues/7906
