### ISSUE TITLE
Communities-> Import: The community name, members and community image are not shown after import

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8100]
# Bug Report

## Steps to reproduce
1. Go to Communities Portal and import the community by the key: 0x7802b9bedb10d100df66daf3bdf9054baad252f67eefc0ef93a3fb99c443354e
2. Check the name of the imported community, the members, and the community's image

#### Expected behavior
The community is imported correctly with all data (name, members, and image)
#### Actual behavior
The name of the community, the image, and the members are not shown
<img width="651" alt="image" src="https://user-images.githubusercontent.com/14942081/199362399-a68fa9a1-3444-4ced-816f-2c85fc0483bf.png">

### Additional Information

- Status desktop version:  https://ci.infra.status.im/job/status-desktop/job/master/497/
- Operating System: macOS Monterey

**Comment by endulab** [comment]
Related to https://github.com/status-im/status-desktop/issues/7413.
Blocked by: https://github.com/status-im/status-go/issues/2878

**Comment by anastasiyaig** [comment]
it is happening the same way in the 0.7.0, moving to next release

**Comment by endulab** [comment]
Will be fixed in #7414

**Comment by elina2015** [comment]
Tested and approved

**Comment by jrainville** [comment]
Merged in https://github.com/status-im/status-desktop/issues/7414
