### ISSUE TITLE
Chat: the community invitation link doesn't look good in the Chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8101]
# Bug Report

## Steps to reproduce
0. Create a community with a long description
1. Go to the test chat and send there an invitation community link
2. Send a few simple messages
3. Check the view of the invitation community link

#### Expected behavior
The link looks good and it's not overlapped by other messages
#### Actual behavior
The link is overlapped with the other messages
<img width="652" alt="image" src="https://user-images.githubusercontent.com/14942081/199363991-7d2b37d9-af3f-4dd1-aaec-6840bf65f712.png">

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/master/497/
- Operating System: macOS Monterey

**Comment by endulab** [comment]
I think it is already fixed. @elina2015 can you recheck ?

![image](https://user-images.githubusercontent.com/61889657/200620294-8d14d759-c2e1-4aa6-9acb-ff08286c19c9.png)

**Comment by anastasiyaig** [comment]
happens in 0.7.0 as well

**Comment by endulab** [comment]
Duplicated by https://github.com/status-im/status-desktop/pull/8502

**Comment by jrainville** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/8502
