### ISSUE TITLE
Communities: the link to community doesn't work in Status browser or other browsers

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8102]
# Bug Report

## Steps to reproduce
1. Create a community and copy a public link to it (for example, https://join.status.im/c/0x030bb0ac1115f2741c25b641940787659ead1d4e1e2d1127a2d5aac8bb5acd742e)
2. Enter the link in the Status browser or in Chrome  (or any other browser)

#### Expected behavior
The link leads to the community
#### Actual behavior
The link leads to https://status.im/get/
### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/master/497/
- Operating System: macOS Monterey

**Comment by elina2015** [comment]
Caused by the pr https://github.com/status-im/status-desktop/pull/8054

**Comment by anastasiyaig** [comment]
same for 0.7.0

**Comment by iurimatias** [comment]
still an issue

**Comment by jrainville** [comment]
@felicio could you get @borismelnik a link to the website where he can test, or a something local he can use? Thanks

**Comment by felicio** [comment]
Those links should be in majority cases automatically handled, so unless testing e2e without status app installed, you as a user technically don't need or shouldn't see the website at all.
