### ISSUE TITLE
Activity Center: Mentions and Replies are not shown in the Activity Center

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8103]
# Bug Report

## Steps to reproduce
1. Go to some chat and add some mentions and replies for user A
2. Sign out and sign in with a mentioned user A
3. Check the Activity Center

#### Expected behavior
Mentions and Replies are shown in the AC

#### Actual behavior
Mentions and Replies are not shown in the AC
### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/master/497/
- Operating System: macOS Monterey

**Comment by MishkaRogachev** [comment]
@elina2015 mentions & replies works only for communities and private group chats. Read AC notifications also removed from db and should not be shown after restart. 
<img width="544" alt="Screenshot 2022-11-04 at 17 10 47" src="https://user-images.githubusercontent.com/2522130/199995548-da065bed-fb40-4171-b443-55aac7feed73.png">
