### ISSUE TITLE
Keycard not working on M1 iMac

### ISSUE THREAD

**Issue by michelleplur** [status-im/status-desktop#8104]
# Bug Report

## Description

Enter pincode, pincode input fades in and out animation but nothing happens.

## Steps to reproduce

Download Status Desktop beta 0.7.0
Use an iMac M1 with Ventura
Insert keycard 
enter pincode 
see nothing happening. 

#### Expected behavior
Log in and show my account

#### Actual behavior
Halt...

### Additional Information

- Status desktop version: 0.7.0 Beta
- Operating System: Ventura, iMac M1

**Comment by saledjenic** [comment]
@anastasiyaig @glitchminer please confirm and let's close it if this is not reproducible any more?

**Comment by anastasiyaig** [comment]
sadly i dont have iMac, however on my mac with macOS Ventura it works fine. Lets keep it in backlog for now
