### ISSUE TITLE
Messages that contain blockquotes don't look good

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8109]
Here's a screenshot of an (imported) message that happens to quote some other message:

![Screenshot from 2022-11-03 11-04-32](https://user-images.githubusercontent.com/445106/199693588-e37b05b5-36bd-4e32-a500-93a0d5e14cbc.png)

Notice the small vertical line next to the message. Not sure if that's intended, but it looks like this style needs some polishing.

**Comment by caybro** [comment]
I guess the vertical line should just span the whole quoted msg height

**Comment by 0x-r4bbit** [comment]
@alexandraB99 That I do not know to be honest. But I'd also go with some common sense like @caybro suggested.

I think discord handles it the same way.

**Comment by 0x-r4bbit** [comment]
Can also consult our designers: @pedro-et

**Comment by alexandraB99** [comment]
<img width="133" alt="j" src="https://user-images.githubusercontent.com/31625338/206704689-a22664e5-c793-4b2c-b445-8c38758a5790.png">
on a non discord imported message looks good - where can I find this message you're showing @0x-r4bbit ?

**Comment by caybro** [comment]
> <img alt="j" width="133" src="https://user-images.githubusercontent.com/31625338/206704689-a22664e5-c793-4b2c-b445-8c38758a5790.png">
> 
> on a non discord imported message looks good - where can I find this message you're showing @0x-r4bbit ?

That's a single line message :) Try with multiple lines/long text

**Comment by alexandraB99** [comment]
<img width="683" alt="h" src="https://user-images.githubusercontent.com/31625338/206705241-a8ccc0fa-9866-4c35-9a38-924464557dbf.png">
still looks good besides the line that it's short

**Comment by caybro** [comment]
> <img width="683" alt="h" src="https://user-images.githubusercontent.com/31625338/206705241-a8ccc0fa-9866-4c35-9a38-924464557dbf.png">
> still looks good besides the line that it's short

And that's exactly the bug here 🙂

**Comment by alexandraB99** [comment]
right,m "Messages that contain blockquotes don't look good" was so general so I didn't know what to look for exactly :D

**Comment by 0x-r4bbit** [comment]
Ah sorry.

I mentioned it in the issue description though:

> Notice the small vertical line next to the message. Not sure if that's intended, but it looks like this style needs some polishing.

Will try to make it more visible next time. Maybe with some emojis or something :D

**Comment by alexandraB99** [comment]
@0x-r4bbit check it out! https://user-images.githubusercontent.com/31625338/206764009-e192b501-d378-4f95-8a8a-30f10f5e8979.mov

**Comment by 0x-r4bbit** [comment]
Looks good!
Maybe on more check with Emojis because think we do some fade-out stuff with longer messages. Not sure if that will affect this,
