### ISSUE TITLE
Community hover shadow cropped

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8111]
# Bug Report

## Description

<img width="1328" alt="Снимок экрана 2022-11-03 в 15 37 29" src="https://user-images.githubusercontent.com/25482501/199722249-30dca087-8865-4bf5-9d5a-0585adf4d466.png">

**Comment by mprakhov** [comment]
Issue is not reproducible, closing
cc @iurimatias , @igor-sirotin
