### ISSUE TITLE
Can't copy message neither via shortcut or context menu

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#8113]
# Bug Report
I cannot copy the message as a shortcut CMD+C is not working and there is no option to copy the message from menu
## Steps to reproduce
- open Status, log in
- join community
- try to copy via CMD+C or via context menu

#### Expected behavior
can copy text from the message

https://user-images.githubusercontent.com/4557972/199728756-52b571d9-2b8a-4b31-8512-51774184504a.mp4

#### Actual behavior
nothing is copied

### Additional Information

- Status desktop version: 0.7.0
- Operating System: OS Ventura 13.0 (22A380)
- Device: MacBook Pro, Apple M1 Pro

**Comment by caybro** [comment]
Can't reproduce on latest master

**Comment by caybro** [comment]
@churik can you try to paste the text somewhere else (just to confirm that the problem is not about pasting not working)

**Comment by churik** [comment]
Ofc. It is reproducible for me on  MacBook Pro, Apple M1 Pro, OS Ventura 13.0 (build 0.7.) and it is not about pasting:

https://user-images.githubusercontent.com/4557972/199748474-3e5a95df-713d-49d8-9d69-5ca7e75c8ec3.mp4

**Comment by PascalPrecht** [comment]
So this seems to be indeed an issue with 0.7.0. We have another issue that reports the same: #8152 
This is not reproducible on latest master for me.

**Comment by churik** [comment]
can not reproduce on nightly 08/11/22
