### ISSUE TITLE
Link is not clickable in a long message while it's collapsed

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-desktop#8116]
# Bug Report

## Description

Unable to follow a link from a collapsed message, you need to expand the message to make it clickable.

<img width="721" alt="Screenshot 2022-11-03 at 15 38 01" src="https://user-images.githubusercontent.com/67952253/199731100-508a1f40-f4db-469e-a39e-1026feaa8228.png">

## Steps to reproduce

1. Send a long message containing a link somewhere at the beginning (to keep it visible)
2. Try to click the link

#### Expected behavior

Can open the link without expanding the message

#### Actual behavior

Need to expand the message

### Additional Information

- Status desktop version: 0.7.0
- Operating System: Monterey 12.3.1

**Comment by caybro** [comment]
Unrelated in the end, should get fixed via PR https://github.com/status-im/status-desktop/pull/7770

**Comment by caybro** [comment]
It's actually the LinearGradient put above the whole text message that makes the whole thing unclickable :) Separate issue
