### ISSUE TITLE
The Windows app cannot be launched

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8119]
# Bug Report

## Steps to reproduce
1. Get the latest build from https://ci.infra.status.im/job/status-desktop/job/master/
2. Instal on your Windows 10
3. Launch the app and check the Task manager and CPU consumption

#### Expected behavior
The app is launched successfully
#### Actual behavior
1. The app appeared as 'running' in the Task manager
2. CPU is skyrocketed
3. Status.exe process is marked as Terminated and disappeared from the Task manager
### Additional Information
<img width="497" alt="image" src="https://user-images.githubusercontent.com/14942081/199824472-6780d37f-ce95-47b9-a323-02eddf4a8a58.png">

- Status desktop version: #513
- Operating System: Win 10

**Comment by glitchminer** [comment]
Potential dup. of #8098
