### ISSUE TITLE
Communities: 'Go to Community' is not shown if the community description is long

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8120]
# Bug Report

## Steps to reproduce
1. Create a new community (public or private) with a very long Description
2. Cope and paste the public invite link to the #test chat

#### Expected behavior
The button 'Go to Community' is shown
#### Actual behavior
The button f'Go to Community' is not shown under the long description
<img width="460" alt="image" src="https://user-images.githubusercontent.com/14942081/199886200-ee1e723d-5001-45e6-b264-353c7e5683cf.png">

### Additional Information

- Status desktop version: Build #514 (Nov 3, 2022, 5:00:59 PM)
- Operating System: macOS Monterey

**Comment by elina2015** [comment]
Tested in https://github.com/status-im/status-desktop/pull/8198

**Comment by borismelnik** [comment]
I reassign it to @endulab cos his PR should fix the problem

**Comment by caybro** [comment]
It has been fixed already in master by this PR: https://github.com/status-im/status-desktop/pull/8502
