### ISSUE TITLE
clicking on a reply should jump to that message

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#8121]
### Description

1. reply to a message
2. click on the reply

expected: it should jump to that message

**Acceptance criteria:**

1. clicking a message card from **Reply** section in **Activity center** should open the channel and scroll history to that channel
2. hovering over the message card should show `finger` indicator which helps to understand the clicking area
3. clicking a message card from **Mentions** section in **Activity center** should open the channel and scroll history to that message
4. clicking Community name from message card in Mentions section opens community
5. clicking Channel name from message card in Mentions section opens channel
6. Reply should have a message shown , which was replied

**Mentions:** https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1440%3A329186&t=hAb5U1o5ke0hJ6r3-4

<img width="757" alt="image" src="https://user-images.githubusercontent.com/82375995/203248473-9802321d-e384-460c-9b4f-c582d5924a80.png">

**Replies** https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop-(rolled-back-version-to-recover-a-screen%2C-ignore)?node-id=1493%3A372975&t=vKTnATQWY09t23mV-4

<img width="452" alt="image" src="https://user-images.githubusercontent.com/82375995/203250007-0745f2d8-76a1-49ee-9d75-420173633c19.png">

**Comment by borismelnik** [comment]
@iurimatias it works in current master (but not working for 0.7.0).

**Comment by borismelnik** [comment]
it's not only timestamp, but maybe we should show `finger` when mouse above the reply message?
