### ISSUE TITLE
change tooltip from 'Activity' to 'Notifications'

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#8124]
### Description

<img width="97" alt="Screen Shot 2022-11-04 at 10 28 49 AM" src="https://user-images.githubusercontent.com/176720/199917067-3094ed47-cdcd-45ff-a5a8-0f3b2ed26de0.png">

**Comment by MishkaRogachev** [comment]
Closed here: https://github.com/status-im/status-desktop/pull/8133
