### ISSUE TITLE
[dogfooding] App uses constantly 50% CPU on mac m1 even in the background

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8139]
App uses constantly 50% CPU on mac m1 even in the background

**Comment by churik** [comment]
Confirming
https://user-images.githubusercontent.com/4557972/200272220-01fff674-70b7-4682-ac52-106e7f697b26.mp4

**Comment by caybro** [comment]
I also noticed quite high spikes of CPU usage on Linux but it was never "constant". I observed 2 patterns: GIF animations and background fetching of message history

**Comment by John-44** [comment]
On my Windows laptop (a nice laptop, but 3 years old), using hte 0.9 release CPU usage hovers around a very reasonable 1.5% to 2% most of the time.    Sometimes it goes down to 0.9%, and sometimes up as high as 2.8% (window visible but not in focus) which is very reasonable and absolutely fine.

**Comment by caybro** [comment]
@alexjba to the rescue :) he found a nice trick to limit the RAM usage drastically

**Comment by alexjba** [comment]
@John-44 @iurimatias The high CPU consumption is reproducible when using an account with Status community. But I think we can lower the priority and not sure it's a blocker. The MacOs Activity monitor will show the CPU usage/Core. This is different than Windows Task Manager where it will show the overall CPU usage. A 50% CPU usage reported on an 8 core Mac is equivalent to 6.25% overall CPU consumption reported on 8 core Windows. It a bit is higher than on Windows, but pretty close (the average I've been experiencing is around 35%/core).

I've been profiling the CPU usage while the app is in the background and about 90% of the app CPU usage is used by `status-go`. @richard-ramos @0x-r4bbit Do you think it's normal for status-go to constantly use CPU on the following call stack?
<img width="1449" alt="Screenshot 2023-03-02 at 11 49 08" src="https://user-images.githubusercontent.com/47811206/222393324-2d55ce5b-ae59-4bd8-b410-f1ecf20fd002.png">

This is the profiling data reported by `Instruments`, but I think a Mac is needed to open it:
https://drive.google.com/file/d/1rBLe1zAteGHYIBNiIGdqtzYxz2YrmP9E/view?usp=sharing

**Comment by caybro** [comment]
Ouch, this looks like an (almost) endless loop in `watchExpiredMessages`

**Comment by 0x-r4bbit** [comment]
@caybro trying to interpret that stack. Where do you see that it's an endless loop?

**Comment by caybro** [comment]
> @caybro trying to interpret that stack. Where do you see that it's an endless loop?

Well, I meant sth that gets called way too often

**Comment by richard-ramos** [comment]
Let's see what up. `resendExpiredMessages` is executed every 1s according to this. 
https://github.com/status-im/status-go/blob/develop/protocol/messenger.go#L1320-L1338 and what the function does is attempt to retrieve the expired messages from the DB. (https://github.com/status-im/status-go/blob/develop/protocol/messenger.go#L571-L614)
Perhaps we're in dire need of adding an index to speed up this query: https://github.com/status-im/status-go/blob/develop/protocol/persistence.go#L822-L831

**Comment by richard-ramos** [comment]
@alexjba could you execute this in your DB and see if the performance improves? 
```
CREATE INDEX raw_messages_expired_idx ON raw_messages (message_type, sent, send_count);
```

**Comment by alexjba** [comment]
> @alexjba could you execute this in your DB and see if the performance improves?
> 
> ```
> CREATE INDEX raw_messages_expired_idx ON raw_messages (message_type, sent, send_count);
> ```

Sure, I'll give it a try later today.

Meanwhile I've been busy compiling the app for M1. And I've been able to run it and get some data out of it. The CPU consumption looks much better. I've seen numbers as low as 7% CPU usage while using the app which was a first for me. Usually it roams around 15-20%, with around 10% while the app is in the background.

One drawback I have now it that I use [Address Sanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) on the nim build in order to call status-go API without freezing. It's consuming both CPU and memory.
@richard-ramos I've seen you logged in a go issue on it (https://github.com/golang/go/issues/48437). Do you have more insights on it?
The arm build looks really promising in terms of CPU performance and I would love to see it working!

**Comment by flexsurfer** [comment]
i can confirm that on 0.10 it roams around 15-20%, but its the same for me in the background, no changes

**Comment by John-44** [comment]
@alexjba those perf improvements from native compilation are exciting! :-)

Very interested to see what @richard-ramos says as from the issue you posted it seems he ran into the same issue back in 2021.   

cc @iurimatias

**Comment by jrainville** [comment]
@richard-ramos doesn't have his laptop, so he can't comment here, so here is his answer:

> So, regarding this,
I think this was a problem in go1. 17
And Stefan did try in newer go versions
And things were working
I remember jakub also changing the makefile to remove the code that transpiled statusgo to amd64, so builds on m1 would build for arm
But dunno the status of that. Its been a while

**Comment by alexjba** [comment]
> @alexjba could you execute this in your DB and see if the performance improves?
> 
> ```
> CREATE INDEX raw_messages_expired_idx ON raw_messages (message_type, sent, send_count);
> ```

Very good finding @richard-ramos! The CPU usage improvement I see is impressive. Without index I get about 45% CPU usage, with the index I get about 15% CPU. Can you add it to `status-go`?

**Comment by John-44** [comment]
> > @alexjba could you execute this in your DB and see if the performance improves?
> > ```
> > CREATE INDEX raw_messages_expired_idx ON raw_messages (message_type, sent, send_count);
> > ```
> 
> Very good finding @richard-ramos! The CPU usage improvement I see is impressive. Without index I get about 45% CPU usage, with the index I get about 15% CPU. Can you add it to `status-go`?

@jrainville @alexjba - @richard-ramos has just started his parental leave (congrats @richard-ramos :-) ), would anybody else be able to add this to `status-go` so we can get this improvement into 0.11 ?

**Comment by cammellos** [comment]
Nice find @richard-ramos @alexjba , here's a PR adding the index https://github.com/status-im/status-go/pull/3285

**Comment by iurimatias** [comment]
Can confirm this has massively decreased my CPU usage, there is still work to do but this definitely makes a big difference.

**Comment by cammellos** [comment]
Interesting that we don't see that on mobile, I wonder if it's possible that how things are compiled for desktop (sqlite/cipher) make it somehow slower? I'd expect to be even worse on mobile, but odd that we don't see this

**Comment by flexsurfer** [comment]
i don't think we tested CPU on mobile for latest builds with waku2 and communities
im wondering why the index in  raw_messages has an effect even if there are no new messages? so we see CPU when app is IDLE right ?

**Comment by cammellos** [comment]
> 

It's true, though that code has been there for a while, but maybe it's possible that we are storing much more raw messages if you joined a community? Worth having a look

**Comment by flexsurfer** [comment]
yeah would be great to monitor write/read operations for raw_messsages, probably there is a bug/mistake which causes hight CPU usage ,and adding index we just hide the root cause

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-go/pull/3285
