### ISSUE TITLE
Chat: quick action buttons overlap with scroll down button

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8149]
# Bug Report

![image](https://user-images.githubusercontent.com/5377645/200344626-5904c6b9-acfb-489f-9325-32e580815d63.png)

#### Expected behavior

The whole quick actions popup should move to the left in order to not overlap with the scroll button

#### Actual behavior

Impossible to reach the "pin" action

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by caybro** [comment]
@benjthayer I could use some UI/UX guidance here

**Comment by benjthayer** [comment]
Hey @caybro - have discussed with the design team - the consensus is not to address this at this point but we will of course consider it for the redesign. 

The rationale for that is that the user can see very little of the message in this scenario, so they are unlikely to want to access the message contextual controls. If they have an interest in performing an action on the message they are likely to scroll up until it is more visible so they can ensure they are performing the action on the correct message. By that point, the flyout will be fully visible given the flyout is anchored to the top of the message.

Hope that works for you! Any issues just shout.

**Comment by caybro** [comment]
This has been fixed in the meantime
