### ISSUE TITLE
[dogfooding] Not able to copy text from a message

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-desktop#8152]
# Bug Report

## Description

Not able to copy text from a message

## Steps to reproduce

1. Open a channel in community
2. Select text and press Ctrl - C (for linux)
3. Try pasting

#### Expected behavior
text should be copyable

#### Actual behavior
not able to copy

### Additional Information

- Status desktop version: 0.7.0-beta
- Operating System: Arch Linux (6.0.2-arch1-1)

**Comment by PascalPrecht** [comment]
Yes this seems to be fixed in latest `master`

**Comment by Parveshdhull** [comment]
@PascalPrecht @caybro should I close this issue then?
