### ISSUE TITLE
Message order is sometimes messed up

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8153]
# Bug Report

## Description

If we are using `timestamp` to order the messages, that's what is causing the issue, we should be using `clock` instead. If there is a tie, use message ID.

![image](https://user-images.githubusercontent.com/11926403/200375603-7b460aaa-b8b8-4e26-9fcd-0dab774df8d7.png)

## Steps to reproduce

Not sure. I replied to Andrea who had replied to himself and then our conversation had a weird order.
Probably just talking in close succession from different devices does it? Maybe difference in timezone also?

**Comment by flexsurfer** [comment]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/11790366/200488435-2131f654-0233-4689-a41c-dd7d8d03821d.png">

**Comment by flexsurfer** [comment]
first the order was incorrect but after some time message jumped to its place but timestamp is wrong

**Comment by glitchminer** [comment]
Potentially related previous issue for message order - notes in linked PR https://github.com/status-im/status-desktop/issues/7058

**Comment by osmaczko** [comment]
> <img alt="image" width="368" src="https://user-images.githubusercontent.com/11790366/200488435-2131f654-0233-4689-a41c-dd7d8d03821d.png">

I can confirm. Sorting by whisper timestamp was the issue in this case. 

See `whisper_timestamp` vs `cock_value`:
|message|whisper_timestamp|clock_value|
|------------|--------------------------|----------------|
|A) how is it on a new account?|1667826841000|1667826841740|
|B) its on the new account|1667826821000|1667826841741|

if sorted by clock A) is first, if sorted by timestamp B) is first

![image](https://user-images.githubusercontent.com/33099791/201158622-563f8247-420e-4a6b-a726-86207d7a55e5.png)

**Comment by osmaczko** [comment]
> first the order was incorrect but after some time message jumped to its place but timestamp is wrong

@flexsurfer messages get ordered correctly by status-go when they are fetched from db on app start, that would explain why messages jumped to the correct place after some time. Can you remember if you restarted the app at that time?
