### ISSUE TITLE
[dogfooding] after dissmissing contact request they showed again each time after relogin

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8156]
after dissmissing contact request they showed again each time after relogin

**Comment by PascalPrecht** [comment]
@flexsurfer can you elaborate what you mean by "they showed again" ?
Ideally, can you give us a list of steps to reproduce?
Bonus points if you attach screenshots.

**Comment by flexsurfer** [comment]
sure
1) open the app
2) see new requests
<img width="374" alt="image" src="https://user-images.githubusercontent.com/11790366/200530861-cce8bf32-3d7c-42c3-af3e-75cf62972b85.png">
3) press "Decline all"
4) there is no requests anymore
<img width="366" alt="image" src="https://user-images.githubusercontent.com/11790366/200530975-61fe3a75-4ccf-4d0f-93e4-7e23455f1c37.png">
5) relogin
6) they are here again
<img width="374" alt="image" src="https://user-images.githubusercontent.com/11790366/200530861-cce8bf32-3d7c-42c3-af3e-75cf62972b85.png">

**Comment by PascalPrecht** [comment]
@flexsurfer thank you!

**Comment by caybro** [comment]
Might be related to https://github.com/status-im/status-go/issues/2940

**Comment by PascalPrecht** [comment]
Looking into this now. Trying to reproduce this with latest master of desktop and latest develop of status-go

**Comment by PascalPrecht** [comment]
Alright, great. I can reproduce this.
