### ISSUE TITLE
[dogfooding] once sent message disappeared

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8157]
once i typed a reply message and pressed send and it disappeared, never appeared in the messages list

**Comment by PascalPrecht** [comment]
Experienced the same.
Not 100% reproducible though

**Comment by PascalPrecht** [comment]
@flexsurfer do you remember if this happened with any kind of message, or was it a reply to some other message by any chance?

Cause there's also https://github.com/status-im/status-desktop/issues/8216

**Comment by flexsurfer** [comment]
it happened only once or twice when replying to another message

**Comment by PascalPrecht** [comment]
Thank you @flexsurfer 
I"m going to close this one then in favour of #8216 as this has a bit more descriptive issue.
