### ISSUE TITLE
Can't edit my own message

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#8164]
# Bug Report

## Description

After the app restarted, I can't edit my own message. This happens probably only for messages edited before. May be related to #8163 

![image](https://user-images.githubusercontent.com/33099791/200562682-cdae15c7-0b07-474b-8e90-8cde0dad61d9.png)

**Comment by PascalPrecht** [comment]
This seems to be a dupe of #7879 and will likely be fixed with https://github.com/status-im/status-desktop/pull/8168

**Comment by PascalPrecht** [comment]
Unassigning myself

**Comment by borismelnik** [comment]
Yes it fixed. It happens cos edit request was sent without contentType and contentType was changed to `UKNOWN`. By current logic, you can edit just text and emoji messages. I will close it.
