### ISSUE TITLE
[Dogfooding] Messages receiving can last up to 40 mins (contact requests, membership requests) on status.prod fleet

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#8184]
# Bug Report
## Description

In order to investigate the issue of the missing messages that was experienced by a lot of people in 'Status CC' community  ( more info in #mobile channel) it was decided to create fresh users and try to reproduce it from scratch.
**Important note: the whole history is loading fine on eth.prod fleet in Status mobile 1.20**

The whole flow after creating a new account and to a point, when I was able to receive a Membership request took about 1,5 hours. At this point, I do not think that it makes any sense to investigate it further with this level of message reliability on  `status.prod` fleet (desktop <-> desktop, fresh multiaccounts)

## Steps to reproduce
1) UserA: create new multiaccount
2) UserB: create new multiaccount
3) UserA: send a contact request to UserB, UserC (used Chat > Start Chat > paste the public key) 

**Expected result:** UserB receives contact request immediately
**Actual result:** UserB receives contact request in ~40 minutes. During that time tried to re-login several times, eventually, CR went through.

4) UserA: create a community, Invite UserB
5) UserB: go to the community, join the community
6) UserA: receive membership request 

**Expected result:** UserA can see membership request immediately
**Actual result:**  UserA receives  membership request in ~10 minutes

7) UserA: Accept pending membership request (via Community>Members>Pending requests)

**Expected result:** accepted membership request is not pending anymore
**Actual result:**   accepted membership request is still pending, but the member has been accepted to the community

https://user-images.githubusercontent.com/4557972/200845366-6610482f-007e-45ee-a401-5be18a74bedb.mp4

### Additional Information
User A: 
- Status desktop version: [master 07/11/22](https://ci.infra.status.im/job/status-desktop/job/master/567/)
- Operating System: OS Ventura 13.0 (22A380)
- Device: MacBook Pro, Apple M1 Pro
- Geth: [geth copy.log](https://github.com/status-im/status-desktop/files/9971650/geth.copy.log)

User B: 
- Status desktop version: [master 07/11/22](https://ci.infra.status.im/job/status-desktop/job/master/567/)
- OS: macOS Monterey 12.3.1
- Device: MacBook 
- Geth: https://drive.google.com/file/d/1hofukYwsugu0kOEuLlyQVwF6AbN_VOqo/view?usp=sharing

**Comment by churik** [comment]
cc @anastasiyaig @qoqobolo

**Comment by PascalPrecht** [comment]
@churik can you do us a favour and do the following:

1. Go to settings -> Advanced Settings
2. Enable node management tab
3. Go to node management tab (a new icon appears on your app nav bar on the left)
4. Post a screenshot of it here, or tell us how many peers you're connected to

**Comment by churik** [comment]
Sure! Sorry for a long response @PascalPrecht 
![image](https://user-images.githubusercontent.com/4557972/202186210-5faa3913-7d83-4f76-b056-3add13cb72dc.png)

**Comment by qoqobolo** [comment]
@anastasiyaig just retested this with new accounts on 0.9 rc. Contact request came immediately, so confirming that the issue can be closed.
Thank you!

**Comment by anastasiyaig** [comment]
closing as done
