### ISSUE TITLE
Chat: quick actions should be disabled when editing a message

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8185]
# Bug Report

![image](https://user-images.githubusercontent.com/5377645/200850005-abfe3c4b-a76d-4dc6-83f0-13a1f170b277.png)

- Status desktop version: master
- Operating System: Linux

**Comment by caybro** [comment]
@benjthayer do you think it makes sense to show or hide these quick actions when editing a message?

**Comment by benjthayer** [comment]
@caybro I see this as the user being in an edit 'mode'. As we're in a semi-modal state, it makes sense from my perspective to focus the user in on what they intended to do when activating the mode - i.e. editing the message. For that reason, I would hide the hover controls (edit, pin etc). The user is only 1 click/key entry away from getting access to those back anyway. This is also consistent with Discord.

One thing we might want to consider for the redesign of the Desktop app is distinguishing between hover and selected states for messages. Editing a previous message should arguably put the message in a selected state. Changing the visual treatment of the message boundary/fill while in a selected state will help justify the removal of the hover controls and also bring attention to the message that is in edit mode should they go away and come back to the screen some time later. 

cc @John-44
