### ISSUE TITLE
Chat: Unable to type Unicode characters in input box

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-desktop#8203]
# Bug Report

## Description

Emoji can be mapped to keyboard keys, for fast emoji typing, like
`xmodmap -e "keycode 49 = U1F44D U1F64F"` ([example](https://github.com/Parveshdhull/emoji-keyboard/blob/main/emoji_keyboard.sh))
But pressing those keys in the status-desktop is not working after mapping.

This is a known issue:https://bugreports.qt.io/browse/QTBUG-89184
and fixed in QT versions [5.15.9](https://bugreports.qt.io/issues/?jql=project+%3D+QTBUG+AND+fixVersion+%3D+5.15.9), [6.0.1](https://bugreports.qt.io/issues/?jql=project+%3D+QTBUG+AND+fixVersion+%3D+6.0.1), [6.1.0 Alpha](https://bugreports.qt.io/issues/?jql=project+%3D+QTBUG+AND+fixVersion+%3D+%226.1.0+Alpha%22), So upgrade should fix the bug

### Additional Information

- Status desktop version: 0.7.0-beta
- Operating System: Arch Linux (6.0.2-arch1-1)

**Comment by anastasiyaig** [comment]
well , it is not a desktop bug but QT related one, not sure we have to adjust the client to make a workaround

**Comment by caybro** [comment]
Should get fixes as we move CI over to a newer Qt version; meanwhile you can build yourself from the sources against a local Qt version that's known to work
