### ISSUE TITLE
Can't cancel contact request from context menu

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#8206]
Here's the view of my pending contact requests:

![Screenshot from 2022-11-11 13-09-55](https://user-images.githubusercontent.com/445106/201337821-c0b9ea09-e503-4577-80b9-0292e53220da.png)

I'd like to cancel this one, however there's no way for me to do that from here. I have to open the contact's profile first to get an option to cancel the request.

It'd be great I could cancel a contact request from the context menu as well.

**Comment by caybro** [comment]
I believe this view should eventually go away and be fully replaced by the AC

**Comment by PascalPrecht** [comment]
@MishkaRogachev can you confirm this?

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev can you confirm this?

Yes, i asked John about that: it will be replaced with AC contact requests

**Comment by PascalPrecht** [comment]
Closing this!
