### ISSUE TITLE
Wallet: can't change color of a wallet account

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8211]
# Bug Report

![image](https://user-images.githubusercontent.com/5377645/201355115-43472a8c-3df7-465c-9b96-3d319da7ef93.png)

Notice the color (black) inside the popup is different from the actual color (blue). Anyways, if I just want to change the color or the emoji of the wallet account, I can't since the "Change name" button is disabled

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by anastasiyaig** [comment]
@caybro it is actually by design, other words - it was implemented like that. U may change the color when changing name
