### ISSUE TITLE
Mark all read button is not working

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-desktop#8215]
# Bug Report

## Description

Pressing on mark all read button is not working and giving this error
![error](https://user-images.githubusercontent.com/17097240/201618000-ab086b03-6b5a-4222-9615-7bbc155385cb.png)

### Additional Information

- Status desktop version: 0.7.0-beta
- Operating System: Arch Linux (6.0.2-arch1-1)

**Comment by anastasiyaig** [comment]
it is fixed in master commit e8b9760c4ffcad99cf4df7e4e278ef732332ad48 and will be provided in beta 0.8.0 soon
