### ISSUE TITLE
No (visual) notification about new messages in community channels

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#8217]
Here's what the app nav bar looks like when you're part of a community:

![Screenshot from 2022-11-14 10-50-01](https://user-images.githubusercontent.com/445106/201629004-4fa2140d-450b-4f6e-bc69-42bcf2ee3649.png)

When there's a message in any given community channel, the community item in the app nav bar should show a notification badge (a little blue dot attached to the community tab button).

This used to work but for some reason I don't have it anymore.

The result of that is that I don't know/see if there's new messages in a community (because I also don't get any other notification about new messages in a community), until I actually enter the community and then get surprised that there's many new messages I've missed in the meantime.

**Comment by caybro** [comment]
I notice the same; but sometimes that blue dot badge appears but with a huge delay

**Comment by PascalPrecht** [comment]
Interesting that you're getting it at all

**Comment by caybro** [comment]
@PascalPrecht yeah seeing the same, it appears out of nowhere and very seldom

**Comment by John-44** [comment]
@mprakhov @jrainville @PascalPrecht - when fixing this issue, remember that the blue dot should be displayed if a Community contains new unread messages AND no @ mentions for the user.

If a community contains new unread @ mentions then a circle with the number of unread @ mentions should be displayed as an emblem over the community icon, and no dot is required.

**Comment by mprakhov** [comment]
@John-44 Fixed is done and UI follows the pattern you have been described
Attaching the video

https://user-images.githubusercontent.com/117639195/203616744-493c4640-876c-4e21-be58-79db07ce7da2.mov

**Comment by elina2015** [comment]
Tested and approved
