### ISSUE TITLE
Channel names in community messages are no longer clickable

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#8218]
Here's what the channel list of my community looks like:

![Screenshot from 2022-11-14 10-54-14](https://user-images.githubusercontent.com/445106/201630106-7a6f8101-13a6-4b7c-8248-0b98dcd349ab.png)

Here's a message I sent in some channel (`#ui` channel) that is part of that community:

![Screenshot from 2022-11-14 10-54-21](https://user-images.githubusercontent.com/445106/201630230-827d9b8a-2d67-4a01-88cd-0b5fd1a62e02.png)

Notice how `#messenger` is not turned into a clickable item (which used to be the case before so one can easily jump to other channels if they are mentioned)

This seems to be a regression.

**Comment by borismelnik** [comment]
@PascalPrecht I can't reproduce it in latest `master`. Do you have any suggestions about it?

**Comment by PascalPrecht** [comment]
Oh sorry, I thought I did reply here already. I didn't see this happening all of a sudden anymore. The same day, same version it worked the next moment. No idea what happened there. Gonna close this for now.

Feel free to reopen if this ever occurs again.
