### ISSUE TITLE
Chat: pasting a full size screenshot results in black background

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8220]
### Description

1. on mac, do a screenshot of the app window
2. paste it in the community channel

<img width="703" alt="Screenshot 2022-11-14 at 13 10 00" src="https://user-images.githubusercontent.com/82375995/201633445-5b0713db-dc22-4a60-858c-e5904b1d418a.png">

**Comment by PascalPrecht** [comment]
Turns out this is because desktop turns every image it tries to send into a jpeg.
Will create an issue for that.

**Comment by anastasiyaig** [comment]
@PascalPrecht just wondering, why this requires another issue? I mean can't we track it in this ticket?

**Comment by PascalPrecht** [comment]
Ah, yes that's very fair.

**Comment by iurimatias** [comment]
can no longer replicate
