### ISSUE TITLE
No notification/indication of verification requests whatsoever

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8222]
As I'm looking into #8205 I noticed that, when a verification request is sent, there's no notification about such request.
If I receive such a request, I wouldn't know about it at all, unless I **accidentally** check either:

1. The profile view of the contact that might have sent me such a request
![Screenshot from 2022-11-14 11-25-28](https://user-images.githubusercontent.com/445106/201636733-36192e92-969a-4f61-b8e7-beebdc33d13b.png)

2. Or go to Settings -> Messaging -> Contacts and just notice by accident that there's a "respond to ID request" deep in the context menu:
![Screenshot from 2022-11-14 11-26-16](https://user-images.githubusercontent.com/445106/201636943-6aef2961-3d51-4c3b-9532-92abb39e71f1.png)

This needs to be improved by a big margin.

@MishkaRogachev are you aware if this is somehow covered by your work on the notification center?

**Comment by MishkaRogachev** [comment]
Yep, working on it here: https://github.com/status-im/status-desktop/issues/7373

**Comment by elina2015** [comment]
Now the notifications about Verification requests are shown in AC
