### ISSUE TITLE
Send transaction USDC error

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#8224]
![image](https://user-images.githubusercontent.com/491074/201640856-3106d037-90be-460c-9fb4-18c301384866.png)

Step to reproduce:
1 - send 1 USDC
2 - disable network/enable networks

I arrive to a view where I cannot do anything

On top of it:
![image](https://user-images.githubusercontent.com/491074/201641180-cd7efac6-75ef-40e4-851b-f8b7b2174cc6.png)

USDC decimals seems wrong

**Comment by anastasiyaig** [comment]
perhaps this is related to the issue i logged too https://github.com/status-im/status-desktop/issues/8117 ?

**Comment by alaibe** [comment]
Possibly, as decimals are incorrect we may end up in weird situation
