### ISSUE TITLE
DB caching and improved cache hit

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#8226]
Acceptance criteria:
- Fetching of balance history for enabled chains is triggered at the application start and every 12 hours afterwards for the missing entries only
  - After the first start, check the Infura dashboard for a high count of `eth_getBlockByNumber` and a much higher of `eth_getBalance`
  - This process might be slow on a slow connection and high count of accounts and enabled networks
- After the initial fetching is complete, visualizing a balanced history graph for any chain and any account's native token should be instant.

**Comment by anastasiyaig** [comment]
@stefandunca @alaibe should it be labeled with `feature` then? Not seeing it on the board because of missing (?) label

**Comment by stefandunca** [comment]
https://github.com/status-im/status-go/pull/3071
