### ISSUE TITLE
CI: master builds are broken for all 3 platforms

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8227]
### Description

https://ci.infra.status.im/job/status-desktop/job/platforms/

![image](https://user-images.githubusercontent.com/82375995/201655296-1ca4d61b-2d72-497d-af43-d5446525e292.png)

**Comment by jakubgs** [comment]
Those failures are not related to the `Makefile`, the error is clearly in the logs:
```
13:12:04  /home/jenkins/workspace/status-desktop/platforms/linux/src/app_service/service/saved_address/dto.nim(1, 24) Warning: imported and not used: 'sugar' [UnusedImport]
13:12:04  /home/jenkins/workspace/status-desktop/platforms/linux/src/app_service/service/saved_address/dto.nim(1, 14) Warning: imported and not used: 'sequtils' [UnusedImport]
13:12:04  /home/jenkins/workspace/status-desktop/platforms/linux/src/backend/accounts.nim(95, 28) Error: undeclared identifier: 'decompressPublicKey'
```

**Comment by alaibe** [comment]
The commit of nim-status-go correspond to the latest one and this error only happens on CI, could it be that the dependencies are not re built/fetch?

**Comment by jakubgs** [comment]
The symptoms relayed to me by @caybro were that things were built more times than necessary, so assume no, but it's not impossible for that to be the case.

**Comment by jakubgs** [comment]
Not 100% sure but these might be the correct fix:

* https://github.com/status-im/status-desktop/pull/8233
* https://github.com/status-im/status-desktop/pull/8239
