### ISSUE TITLE
Fix versions for release and master

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8249]
### Description

**For release** candidate: the version is `0.8.0-rc.1` which is not a number. Should be sth like `0.7.9x`
**For master:** master version should be bumped

<img width="1512" alt="Screenshot 2022-11-15 at 14 48 32" src="https://user-images.githubusercontent.com/82375995/201912364-1237fbb2-0dfa-4ec8-b264-1b5a0ee2bbc9.png">

**Comment by iurimatias** [comment]
will close as it's unrelated to the RC itself
