### ISSUE TITLE
Chat: 'Fetch more messages' CTA should not show if there are no previous messages to fetch

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#8257]
**Issue:**
The CTA to 'Fetch more messages' should not be shown at the start of the chat history when there are no previous chats to fetch.

<img width="1229" alt="Screenshot 2022-11-15 at 15 21 50" src="https://user-images.githubusercontent.com/110033914/201957525-7934018c-146b-42dc-99ae-f803ce95a62f.png">

**Comment by iurimatias** [comment]
moved to 0.14

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in the current milestone

**Comment by iurimatias** [comment]
duplicate of https://github.com/status-im/status-desktop/issues/9445
