### ISSUE TITLE
Chat: Editing messages: 'Escape' and 'Enter' key shortcuts not implemented

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#8260]
Issue:
In the Kuba designs, there is a note clarifying that, when a user is editing their message, they should be able to use the Escape and Enter keys as shortcuts for the implemented Cancel and Save buttons respectively. 

- Escape should close the edit mode without committing any changes
- Save should commit the changes to the posted message and close the edit mode

Figma:
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5395%3A43722

<img width="1106" alt="Screenshot 2022-11-15 at 15 53 54" src="https://user-images.githubusercontent.com/110033914/201965439-172fe981-8e23-4034-be5e-461b91d10a61.png">

**Comment by caybro** [comment]
@benjthayer this is already implemented (works for me in master)

**Comment by caybro** [comment]
@benjthayer what doesn't work though is these shortcuts when replying to someone but that'd be a different issue I guess :)
