### ISSUE TITLE
Investigate why community requests to join are often not received

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8264]
### Description

@iurimatias has found that with the multitude of requests he receives for the Status CC community, a lot of people say they sent a request and he never received it.

I know it happened to me as well and it took one or two days before he finally received it.

We need to investigate if the issue is in sending, the peer to peer network or in receiving.

This might be related to message reliability, so one way to debug it would be to first reproduce the issue, get that message ID and/or envelope ID and then track it through all the layers. @richard-ramos added logs everywhere to help debug this.

Maybe @iurimatias can share his DB if needed to see if we can see something on the receiving end.

**Comment by richard-ramos** [comment]
@iurimatias with latest fixes included in nwaku,  you should be able to retrieve historic messages that contain community requests, improving the experience.

I did some experiments and code review of sections related to building the community request and also receiving them and found no apparent problems there. Lack of connectivity to peers might be causing these messages to not be broadcasted succesfully, so we might have to wait until NAT hole punching solutions are deployed.

**Comment by jrainville** [comment]
More info:
We discovered that the issue seems to be on the status-go side. I had a request that was sent from one account, and the other didn't receive it. I tracked the envelope ID and the message ID, and it **did** receive the envelope, but not the message id.

Here are the logs for that envelope hash:
```
geth-2022-12-12T20-33-11.382.log:t=2022-12-12T15:08:03-0500 lvl=info msg="received waku2 store message" envelopeHash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7
geth-2022-12-12T20-33-11.382.log:t=2022-12-12T15:08:03-0500 lvl=dbug msg="received new envelope" hash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7
geth-2022-12-12T20-33-11.382.log:t=2022-12-12T15:08:03-0500 lvl=dbug msg="cached w envelope" envelopeHash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7
geth.log:t=2022-12-12T15:57:24-0500 lvl=info msg="received waku2 store message" envelopeHash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7
geth.log:t=2022-12-12T15:57:24-0500 lvl=dbug msg="received new envelope" hash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7
geth.log:t=2022-12-12T15:57:24-0500 lvl=dbug msg="cached w envelope" envelopeHash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7
geth.log:t=2022-12-12T15:57:24-0500 lvl=dbug msg="message not cached" namespace=Transport site=retrieveRawAll hash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7
geth.log:t=2022-12-12T15:57:24-0500 lvl=dbug msg="calculated ID for envelope" envelopeHash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7 messageId=0x764d1bfbdedcabaef60150c6e5efcab9d5a20efe7522b84d247011ebf13a42fe
geth.log:t=2022-12-12T15:57:24-0500 lvl=dbug msg="processing messages further" site=RetrieveAll hash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7 count=1
geth.log:t=2022-12-12T15:57:24-0500 lvl=info msg="processing message" site=RetrieveAll hash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7 message-id=0x764d1bfbdedcabaef60150c6e5efcab9d5a20efe7522b84d247011ebf13a42fe
geth.log:t=2022-12-12T15:57:24-0500 lvl=dbug msg="Handling parsed message" site=RetrieveAll hash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7 message-id=0x764d1bfbdedcabaef60150c6e5efcab9d5a20efe7522b84d247011ebf13a42fe
geth.log:t=2022-12-12T15:57:24-0500 lvl=dbug msg="Handling CommunityRequestToJoin" site=RetrieveAll hash=0x67a8ccfd1b2c17ee9d655ee0963bfb06df1455af3d369a974cc9277808acf9c7 message-id=0x764d1bfbdedcabaef60150c6e5efcab9d5a20efe7522b84d247011ebf13a42fe
```

**Comment by jrainville** [comment]
Some more recent logs we got
```
t=2023-01-10T08:49:50-0500 lvl=dbug msg="cached w envelope" envelopeHash=0x251ae7b5bcbeeb9c19e4c2a46af4a6bfb5013356e15126a039dab96f018dffbf
t=2023-01-10T08:49:50-0500 lvl=dbug msg="processing message: decrypted" hash=0x251ae7b5bcbeeb9c19e4c2a46af4a6bfb5013356e15126a039dab96f018dffbf
t=2023-01-10T08:49:50-0500 lvl=dbug msg="processing message: decrypted" hash=0x36a08e7ce17c7510d285b9c6259645dee1a11ae5dccd1d79a11bf6fb32a72e4e
t=2023-01-10T08:49:50-0500 lvl=dbug msg="filters did not match" hash=0x36a08e7ce17c7510d285b9c6259645dee1a11ae5dccd1d79a11bf6fb32a72e4e contentTopic=/waku/1/0x6a4860f5/rfc26
t=2023-01-10T08:49:50-0500 lvl=dbug msg="processing message: decrypted" hash=0xf38bc40db5441e2931a72aaa3d420b29ebe341a5f4f0d9a6ca0fc8c1539d742a
t=2023-01-10T08:49:50-0500 lvl=dbug msg="Epoch processing" namespace=mvds node=04f2e7b3 epoch=4,129,264
t=2023-01-10T08:49:50-0500 lvl=dbug msg="Epoch processing" namespace=mvds node=04f2e7b3 epoch=4,129,265
```
Interesting line: `t=2023-01-10T08:49:50-0500 lvl=dbug msg="filters did not match" hash=0x36a08e7ce17c7510d285b9c6259645dee1a11ae5dccd1d79a11bf6fb32a72e4e contentTopic=/waku/1/0x6a4860f5/rfc26`

**Comment by jrainville** [comment]
Some discussion I had with Richard 

Jo — 06/01/2023 10:37
hashes:
```
t=2023-01-06T10:34:23-0500 lvl=dbug msg="SENDING message" namespace=Transport topic="[121 109 30 135]"
t=2023-01-06T10:34:23-0500 lvl=dbug msg="sent community message " messageID=0x5ef7489796fc2a07e2337b4439f124e090e831d5ff2993b219b9dd26271f2583 hash=0x708edf79c81ef821036638bc9bf5a422674ea0c5307f8e76b5e3a582d60fe193
t=2023-01-06T10:34:23-0500 lvl=info msg="publishing message via relay" envelopeHash=0x708edf79c81ef821036638bc9bf5a422674ea0c5307f8e76b5e3a582d60fe193
t=2023-01-06T10:34:23-0500 lvl=info msg="waku.relay published" hash=708edf79c81ef821036638bc9bf5a422674ea0c5307f8e76b5e3a582d60fe193
```
rramos.eth | ラモス — 06/01/2023 10:38
the sending message topic should be  [121 109 30 135]  -----> 796D1E87 
Jo — 06/01/2023 10:38
you're saying it's using a wrong topic?
rramos.eth | ラモス — 06/01/2023 10:39
no, i'm translating it from decimal to hex
Jo — 06/01/2023 10:39
kk
ah crap, I forgot that my second dekstop app is not up to date with master
updating now
rramos.eth | ラモス — 06/01/2023 10:42
accordign to the code, when sending a request to join message, it's sent to a public chat.
With a topic calculated from the public key from the community
    filter, err := t.filters.LoadPublic(PubkeyToHex(publicKey)[2:])
so the type "public" is okay
Jo — 06/01/2023 10:42
ah ok
rramos.eth | ラモス — 06/01/2023 10:43
what we need to figure out is if we have the filter registered for the receiver.
there should be a     filter, err := t.filters.LoadPublic(PubkeyToHex(publicKey)[2:])   too, for same public key
Jo — 06/01/2023 10:45
Ok I'll check it out
rramos.eth | ラモス — 06/01/2023 10:46
what i do see is this:
```
t=2023-01-05T13:41:04-0500 lvl=dbug msg="registering filter for" namespace=filtersManager chatID=0x03046e24607c7e8c858034705637e9a9c405bd55f45772684e5eebbd3550216750 type=public topic=0xf73734f1
```
notice the chatID there is a compressed key
Jo — 06/01/2023 10:47
indeed
rramos.eth | ラモス — 06/01/2023 10:47
i wonder if that's the problem
will keep digging
because when the message was sent, i think it was sent to a expanded public key (0x04....) 
rramos.eth | ラモス — 06/01/2023 10:48
in here
:Peepo_MathsConfusedThink:
Jo — 06/01/2023 10:49
I did another repro on my two dev accounts. It failed again, but this time, I don't see the topic being registered at all
Ah, if I search /waku/1/0x59f6102d/rfc26 I don't find it, but I find it just with 0x59f6102d
Hmm
```
t=2023-01-05T13:41:04-0500 lvl=dbug msg="registering filter for" namespace=filtersManager chatID=043900e2a9c7b4bf7146a4a31e4b768ca764f67ebbc9701fa9c809f832398500eb045c13489c089e75049bda10a512da05b94083ae09bb71fa5f00308344f686b4-admin type=community topic=0x59f6102d
```
this time it says type community
rramos.eth | ラモス — 06/01/2023 10:52
but that chatID is different
Jo — 06/01/2023 10:52
and that was a fail
rramos.eth | ラモス — 06/01/2023 10:52
ends in "-admin"
Jo — 06/01/2023 10:52
right
restarted and got the request, let's see the diff
rramos.eth | ラモス — 06/01/2023 10:55
I have the suspicion that the problem is inside messenger_communities
wherever we call InitPublicFilters
i think that we are not being consistent with the communityID there
we're passing the compressed public key in some ocassions,
and in others the full public key
Jo — 06/01/2023 10:56
weird thing
Can the message coming from mailserver have a different envelope ID than the direct one?
rramos.eth | ラモス — 06/01/2023 10:57
yes, sadly
Jo — 06/01/2023 10:57
ah ok
rramos.eth | ラモス — 06/01/2023 10:57
it's due to an issue i described in nwaku's repo
Jo — 06/01/2023 10:57
that explains what I'm seeing
rramos.eth | ラモス — 06/01/2023 10:57
about the ids not being deterministic
Jo — 06/01/2023 10:57
right
at least I had the message ID
lol sadly, I don't have the topic id/name when the reception is a success

**Comment by cammellos** [comment]
thanks, taking a look at this

**Comment by jrainville** [comment]
@cammellos have you found anything? Do you need more info to help you?

**Comment by cammellos** [comment]
@jrainville sorry, got distracted :) more logs are always helpful, I had a look at the code and there's nothing obvious, but I'll have more time on Friday to investigate, apologies for the delay

**Comment by jrainville** [comment]
I've tried investigating again. I added a lot of new logs that will make it easier to know which ID a message has and which topic it is sent to. You can find it here: https://github.com/status-im/status-go/compare/develop...fix/community-lost-requests

I then tried sending requests until one of them wouldn't be received.

I have not been able to reproduce once.

Here are the different scenarios I tried:

1. Normal on request community
2. On request community with a join permission
3. On request community but the owner is the shared account (huge DB)
4. On request community but the community has not been set active
5. No Internet connection, reconnect then send (force low peers)
6. Only Wifi instead of cable
7. Sending the request when the control node is closed

The steps I did were as follow:
0. Have two instances on the same branch
1. Alice is an owner of the community and sends the community invite to Bob
2. Bob sends a request
3. If Alice receives, kill Alice and restart
4. Bob cancels the request
5. If Alice receives the cancellation, kill Alice and restart
6. retry from 2

I did those steps on the different scenarios at least 50 times.

I think maybe the issue is fixed? I know I haven't experienced it in months, where before I would get it from time to time.

@iurimatias we'll have to try to reproduce with your control node when you're back, in case your community is the only one that experiences it still.
