### ISSUE TITLE
Make channels with unread messages clearer

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8265]
### Description

Currently, when we have a channel (community or not) with unread messages, the chat name is in bold and that's it.
In the screenshot below, the channel that has a new message is `#testjo`, but it's almosy undistinguishable from the one that's active:
![image](https://user-images.githubusercontent.com/11926403/201999197-a4bd07b5-7d8a-4a8e-beea-48371f7c6fb0.png)
 
I suggest doing the same as in mobile and add a blue dot next to channels with a new message

**Comment by benjthayer** [comment]
@alexandraB99 Thanks - this came up on a call last week - I'll be exploring implementing the grey dot which we have on the mobile app which is aligned to the right of the channel/chat to tell the user they have new messages (that are not mentions). Will update here when it is ready.

**Comment by benjthayer** [comment]
Hey @alexandraB99 @jrainville I've created some designs for this which have been signed off by @John-44 

To echo mobile, we can use the grey dot to the right of any channel that has unread messages. If the unread messages contain a mention, the grey dot would be replaced with the blue notification badge. Both should be replaced with the mute icon if the channel is muted. 

The grey unread messages marker dot should only be removed when the user has read all of the messages in that channel. Not simply by clicking on the channel as we have now. The unread messages dot and the accompanying semibold treatment for the channel label would only be removed if the user either manually scrolled to the latest message in the channel or used the 'jump to' latest message button as shown in the video below:

https://user-images.githubusercontent.com/110033914/218825926-4d597a30-443d-4e7d-a460-c642b5f17c74.mov

The user should also be able to right-click the channel and select `Mark as Read` - this would have the same effect as viewing all messages.

https://user-images.githubusercontent.com/110033914/218826564-d29b0f3c-937d-49e5-9f76-3c323a5a808b.mov

Figma designs:
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=21556%3A681150&t=umUsHzhThBLH3NTa-4

If whoever is developing this could set up a call with myself before implementing that would be great - just so we can chat through all of the interactions!
Thanks!

**Comment by benjthayer** [comment]
Just to note - the skeleton loading animations, new messages marker bar seen in the body of the channel message feed and jump to latest message buttons featured in the above recordings are being/have been handled via independent issues. :)
