### ISSUE TITLE
Build Flatpak release (AppImage is terrible for everyday usage)

### ISSUE THREAD

**Issue by du64** [status-im/status-desktop#8266]
As a developer / user I want to be able to download a Flatpak or .deb version of Status Desktop, so I don't need to hunt for an AppImage every single time I want to use the app.

### Problems with AppImage:
* Cannot search for Status in the global search
* AppImage cannot actually be installed, which means users can't pin Status to the dock, or interact with it like a normal app
* They are resource restricted and containerized, which means there's stability issues for long-term usage
* Updates don't apply properly, and I must often delete the database and reinstall it before opening the AppImage

Flatpak, .deb, and snap packages all solve these four major problems on Linux

**Comment by iurimatias** [comment]
added to https://github.com/status-im/status-desktop/issues/5747
