### ISSUE TITLE
Chat: it's possible to send an empty message

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8268]
# Bug Report

## Steps to reproduce
1. Go to any chat or community
2. Enter a space in the Message field and click Enter

#### Expected behavior
The empty messages are not sent to the chat
#### Actual behavior
The empty messages are shown in the chat
### Additional Information
<img width="259" alt="image" src="https://user-images.githubusercontent.com/14942081/202093097-b29919a2-5b06-4ed5-acf2-2421f26dc8bd.png">

- Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.1
- Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
0.7.0 behaves the same
