### ISSUE TITLE
Communities: Require approval flow is allowing to join community before sending the request to join

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8269]
### Description

1. as user A, add user B to contacts
2. as user A, create community that requires approval to join
3. as user A, add user B to that community
4. as user B, observe the 1x1 chat with user A

**As result:**

- a community invitation bubble present, saying Go to the community
- user is able to join the community by clicking it
- Request to join button is shown at the top of channels list

<img width="1512" alt="Screenshot 2022-11-16 at 10 51 42" src="https://user-images.githubusercontent.com/82375995/202120857-1e2aeff2-9a52-4c0b-b60d-80b6a9ad9ec5.png">

<img width="1512" alt="Screenshot 2022-11-16 at 10 51 51" src="https://user-images.githubusercontent.com/82375995/202120899-d2596726-4f9e-42fa-acaf-33ac7ce9e042.png">

**Expected**:
- community invitation should say "Request to join"
- when clicked, the prompt to approve the memeber is sent to community owner
- once approved, the joiner should see the "go to community button" in 1x1 chat

**Version**: `0.8.0-rc.1`

**Comment by PascalPrecht** [comment]
I actually think this is by design.
When a community is shared, one should always "go to community" and then determine whether or not to join by "request to join".

**Comment by anastasiyaig** [comment]
@PascalPrecht lol indeed i forgot about the new design which is UX confusing , sorey
