### ISSUE TITLE
Highlight color of jump-to-message has too little contrast

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8271]
We have this cool feature where we can jump to a reply-to-message by clicking on it.
This seems to work great however, visually it's not very clear which message is the one I've jumped to.
Below is a screenshot of a message I've jumped to but it's barely noticable:

![Screenshot from 2022-11-16 10-48-43](https://user-images.githubusercontent.com/445106/202147127-f8ba820d-4a48-4358-9fab-2086c85fd289.png)

It's too subtle. I'd propose we use the same color we use for pinned messages.
Keep in mind that the highlight disappears after a few seconds. So the highlight color better jumps straight into my eyes.

**Comment by pedro-et** [comment]
@PascalPrecht this seems like a good proposal :) press it, colour highlight, colour disappears. Always same margin from the top unless we're in frame.

**Comment by caybro** [comment]
@benjthayer would love to hear some design feedback on this; so far I've been using `Theme.palette.primaryColor2` (which translates to `#4360DF` and `#88B0FF` in light and dark theme respectively) and it works much better; wdyt?

**Comment by benjthayer** [comment]
Hey @caybro - whats the best way for me to check that? Are you able to post a screenshot for both themes here?

FYI I'm currently looking into this today. I'm starting with exploring what the convention will be for the mobile app first to see if we can be consistent in desktop also. I'll let you know as soon as my explorations are ready.

**Comment by caybro** [comment]
@benjthayer alright :)

![image](https://user-images.githubusercontent.com/5377645/207364763-94efde01-9e48-47e9-88db-1a51400d3273.png)

![image](https://user-images.githubusercontent.com/5377645/207364896-ceb85b7f-b42d-49dc-ba5c-e578a3ad6a65.png)

Not too accurate, as the colors are "pulsing"

**Comment by 0x-r4bbit** [comment]
Definitely an improvement. I still think we should use something that jumps more into the eyes like the color we use for pinned messages.

**Comment by alexandraB99** [comment]
@benjthayer any input here? should we use the ordinary message highlight colors?

**Comment by caybro** [comment]
@benjthayer any update here, do we have some better colors? :)

**Comment by benjthayer** [comment]
Hey @caybro finalised the mobile designs - just needing to find some time with John to review / sign off - hopefully tomorrow

**Comment by benjthayer** [comment]
Hi @caybro @John-44 attaching the proposed highlight colour to use when transitioning to the original message of a reply.

As discussed with the design team, the highlight value re-uses an opacity of the primary blue colour from the light and dark design system.

This is consistent with the design for mobile which also uses an existing opacity of the primary blue.

The blue opacity wash is intended to differentiate the highlighted message from a hover state and also 'mix' with other pre-existing message highlight colours such as those used for mentions and pinned messages.

Light theme: Light Desktop / Blue 20% (4360DF 20%) above any existing message wash
Dark theme: Dark Desktop / Blue 20% (869EFF 20%) above any existing message wash

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=21265%3A511905&t=mwtupLfn99uaQFQJ-4

Just needs a final thumbs up from @John-44 

https://user-images.githubusercontent.com/110033914/212734426-c6572b08-c825-430c-b8e3-83596f1f8bef.mov

https://user-images.githubusercontent.com/110033914/212734432-9b8f8597-7d99-454d-99dc-2c31a3f9cadc.mov

https://user-images.githubusercontent.com/110033914/212734414-7b6be6df-738e-4524-a553-62aaa50b420b.mov

https://user-images.githubusercontent.com/110033914/212734419-dc7f6076-bcf7-45a7-b545-83c7f3596c21.mov

https://user-images.githubusercontent.com/110033914/212734405-144e813c-aad1-49e6-98ea-71afad3f40c7.mov

https://user-images.githubusercontent.com/110033914/212734376-1a7dd245-f2da-49bd-8bf2-5d807de0f771.mov

Mobile app for reference:

https://user-images.githubusercontent.com/110033914/212734639-c705906a-887a-496f-9b95-40f7ed9dc674.mov
