### ISSUE TITLE
[dogfooding] Can't fetch previous history for certain community channels after relaunch

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#8280]
# Bug Report
## Description

After several re-launch desktop app can't see the previous history for the community channel (in this particular case it is Status > #mobile). Got this issue from several ppl who also are using the `Status` community, that they can't see history for several weeks while they have been communities members from the start of the chat history (Nov 3)

## Steps to reproduce
**Prerequisites:** member of Status Community from Nov3, active in this channel (sending/receiving messages) 
- relaunch Status several times
- check the start of history in Status > mobile channel
- if "Fetch messages" button is available, click on it until it gets disappeared

#### Expected behavior
can see messages from the start of the channel (Nov3)

#### Actual behavior
can see history only for 2 days
Screenshots from different ppl that experience this issue:
![Status Desktop 2022-11-16 13-16-56](https://user-images.githubusercontent.com/4557972/202178553-b5f5995f-c3dd-4352-afc4-a26381ad2487.png)

https://user-images.githubusercontent.com/4557972/202178573-ef8c0f9d-9105-4a35-bf58-69b6d83bf5ea.mov

![andr](https://user-images.githubusercontent.com/4557972/202178587-a497ce0d-586e-49d3-ae49-d0406c003424.png)
In all cases fetching history before Nov15 is not possible.

### Additional Information

- Status desktop version: 0.8.0 RC1
- Operating System: OS Ventura 13.0 (22A380)
- Device: MacBook Pro, Apple M1 Pro

**Comment by flexsurfer** [comment]
it's not only messages for communities, also notifications disappear

**Comment by iurimatias** [comment]
checked with new recent joiners and it seems this has been fixed
