### ISSUE TITLE
Can't use unicode characters as own DisplayName

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8283]
# Bug Report

A followup to issue #8115, a user should be able to use Unicode characters for their display name (for the record, Discord and other messengers support this)

Currently this is restricted in 2 places using a regular expression:

status-desktop, Constants.qml:
```qml
StatusRegularExpressionValidator {
  regularExpression: /^[a-zA-Z0-9\-_]+$/
  errorMessage: qsTr("Only letters, numbers, underscores and hyphens allowed")
}
```

but also in status-go, messenger-identity.go:
```go
func ValidateDisplayName(displayName *string) error {
...
  // ^[\\w-\\s]{5,24}$ to allow spaces
  if match, _ := regexp.MatchString("^[\\w-\\s]{5,24}$", name); !match {
    return ErrInvalidDisplayNameRegExp
  }
...
```

The former is easy to fix, using the newly introduced StatusRegularExpressionValidator, but the status-go counterpart's regex has to be also adjusted accordingly (e.g. using the unicode "Character class elements": https://unicode.org/reports/tr18/#General_Category_Property)

Also notice the frontend doesn't allow spaces, while backend does

#### Expected behavior
User is able to set their own DisplayName using Unicode characters

#### Actual behavior
User is unable to set their own DisplayName using Unicode characters

### Additional Information

- Status desktop version: master
- Operating System: all

**Comment by caybro** [comment]
@PascalPrecht @richard-ramos opinions pls, especially on the status-go part

**Comment by PascalPrecht** [comment]
If the above is correct and desired, then status-go needs to update its validation.
re: spaces not allowed in frontend: this is by design AFAIK

**Comment by caybro** [comment]
Well actually both sides need an update; I was just curious whether there isn't any other serious restrictions on status-go side for the DisplayName format

**Comment by PascalPrecht** [comment]
Looping in @cammellos to be sure.

**Comment by cammellos** [comment]
> Looping in @cammellos to be sure.

Concerns should be mostly UX concerns, so we can do anything that makes sense with that respect, status-go should be able to handle anything ok I suppose

**Comment by iurimatias** [comment]
the spec is here https://github.com/status-im/feature-specs/pull/42/files#diff-be3d528e707e2e0b06d2d9bc89a375b4634c43c81cbb5809244a4c263e2883ffR73

it seems it cant accept just any characters, I believe this is for security reasons. If we are to update this needs to be discussed and analyzed
