### ISSUE TITLE
Profile showcase

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#8284]
TODO: expand this issue

showcase feature for the profile to select what tokens, accounts, communities, etc.. are visible

- [x] #9664

**Comment by caybro** [comment]
@John-44 any details here? if we still want to target 0.11, this needs further specifications/design/etc

Also, this will likely need quite some backend work; atm we only publish things like avatar, display name or bio/social links

**Comment by caybro** [comment]
As a first step, we (@benjthayer & me) thought it might be good to extend _own_ profile with the assets/tokens/communities/accounts information, instead of showing the "More content to appear here soon..." placeholder

**Comment by caybro** [comment]
Further tracked with all the other changes in: https://github.com/status-im/status-desktop/issues/9750
