### ISSUE TITLE
Remove MessageView from Activity Center notifications

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#8285]
AC notifications currently use MessageView.qml from the chat. That should be changed for new component according UI requirements for activity center.

**Comment by MishkaRogachev** [comment]
@iurimatias @jrainville i want implement this issue in one PR with identity verification notifications in AC

**Comment by MishkaRogachev** [comment]
<img width="575" alt="Screenshot 2022-11-16 at 17 54 11" src="https://user-images.githubusercontent.com/2522130/202199648-c6443cbf-93ae-47d5-9006-007dfc60725f.png">
Basically I need this component without any message contents, menus and etc

**Comment by caybro** [comment]
> <img alt="Screenshot 2022-11-16 at 17 54 11" width="575" src="https://user-images.githubusercontent.com/2522130/202199648-c6443cbf-93ae-47d5-9006-007dfc60725f.png">
> 
> Basically I need this component without any message contents, menus and etc

StatusSmartIdenticon.qml + StatusMessageHeader.qml

**Comment by MishkaRogachev** [comment]
> > <img alt="Screenshot 2022-11-16 at 17 54 11" width="575" src="https://user-images.githubusercontent.com/2522130/202199648-c6443cbf-93ae-47d5-9006-007dfc60725f.png">
> > Basically I need this component without any message contents, menus and etc
> 
> StatusSmartIdenticon.qml + StatusMessageHeader.qml

Yep, that should be much better than using whole MessageView

**Comment by jrainville** [comment]
> @iurimatias @jrainville i want implement this issue in one PR with identity verification notifications in AC

Is there a way to split it in two PRs anyway? It would make the testing and review process much simpler.
I'm asking because having two somewhat big changes at once might lead to a long and slow process that might accumulate conflicts

**Comment by MishkaRogachev** [comment]
> > @iurimatias @jrainville i want implement this issue in one PR with identity verification notifications in AC
> 
> Is there a way to split it in two PRs anyway? It would make the testing and review process much simpler. I'm asking because having two somewhat big changes at once might lead to a long and slow process that might accumulate conflicts

Ok, when I start from this refactor
