### ISSUE TITLE
Communities->Import: the notification 'Importing community is in progress' appears for already imported community

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8292]
# Bug Report

## Steps to reproduce
1. Import the community by the private key: 0x934a552a94603382f5fc6bd62fad2556eda326731068ae2ed43ac7d4571b453f
2. Import it again

#### Expected behavior
The notification 'Importing community is in progress' doesn't appear for alreadyimported community
#### Actual behavior
The notification 'Importing community is in progress' appears for alreadyimported community
### Additional Information
<img width="189" alt="image" src="https://user-images.githubusercontent.com/14942081/202095163-991b4439-a65d-4f67-bd64-462c4fc634e8.png">

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.1
Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
@0x-r4bbit do u know why it is happening? I mean i saw that too, perhaps the notification text is misleading, so maybe it is shown because community data is being fetched still and it should say so?

**Comment by jrainville** [comment]
We removed the option to import a community by private key. Closing as won't fix.
