### ISSUE TITLE
Chat: reactions distance to message content is inconsistent

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8295]
# Bug Report

## Steps to reproduce
1. Post a GIF image in the test chat
3. Add to the posted GIF any reaction

#### Expected behavior
The reactions are shown not very close to the posted GIF
The reactions are shown very close to the posted GIF

### Additional Information
<img width="257" alt="image" src="https://user-images.githubusercontent.com/14942081/202276473-5fd07723-c3a4-4933-abcf-7952bc3edeea.png">

- Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.1
- Operating System: macOS Monterey

**Comment by caybro** [comment]
@elina2015 pls checkout https://github.com/status-im/status-desktop/pull/8270 and tell me if it fixes this problem too :)

**Comment by elina2015** [comment]
@caybro hey, now we have the different distances between reactions and:
1. Text
2. Emoji
3. Sticker
4. GIF
5. Community

<img width="530" alt="image" src="https://user-images.githubusercontent.com/14942081/203149266-4900526c-a6a0-4c9b-ac82-9aa5505cafd1.png">

Could we have it the same for all these cases?
p.s: for text, we have now the optimal distance, as I see.

I've added this comment to the task about community too: https://github.com/status-im/status-desktop/pull/8270

**Comment by caybro** [comment]
Ok, I'll do a new PR to address this
