### ISSUE TITLE
[Profile] The '6 characters' requirement is shown for password instead of '10 characters' requirement

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8298]
# Bug Report

## Steps to reproduce
1. Sign in with a user without a profile image and without Biometric authentification
2. Go to Profile and change the toggle 'Biometric login' to 'on' position and click 'Save changes'
3. In the appeared Password modal enter a character and check the red notification
#### Expected behavior
The notification about '10 characters password' appeared

#### Actual behavior
The notification about '6 characters password' appeared
### Additional Information
<img width="449" alt="image" src="https://user-images.githubusercontent.com/14942081/202292857-4f1d2ba5-2e67-4aa6-b274-3661e12185a1.png">

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.1
Operating System: macOS Monterey

**Comment by caybro** [comment]
It uses the PIN length for checking:
```qml
readonly property int keycardPinLength: 6
```

**Comment by anastasiyaig** [comment]
it is like that in 0.7.0
