### ISSUE TITLE
[Windows Only] Status Does not launch at all

### ISSUE THREAD

**Issue by Zliced13** [status-im/status-desktop#8299]
# Bug Report

## Description
The **Status** app does not launch at all, even with administrator privileges.

## Steps to reproduce

1. Download this [file](https://github.com/status-im/status-desktop/releases/download/0.8.0-rc.2/StatusIm-Desktop-v0.8.0-rc.2-570a54.7z) from the latest release page.
2. Extract the archive file into a new folder, and then navigate to the app inside the newly created folder.
    ![(explorer)S6R6I6_11-16-2022](https://user-images.githubusercontent.com/101912712/202300651-abcf773d-a381-4819-9d19-394404123e92.gif)
3. Open the application inside the folder
![(explorer)x7J3R6_11-16-2022](https://user-images.githubusercontent.com/101912712/202303723-6271bf07-437a-4213-b130-19547a4398a8.gif)
4. Expect it to launch.

#### Expected behaviour
The **Status** app should launch, with or without administrator privileges.

#### Actual behaviour
The **Status** app does not launch at all, even with administrator privileges.

### Additional Information
![(WindowsTerminal)w0t9d8_11-16-2022](https://user-images.githubusercontent.com/101912712/202303656-30ce04b0-6b51-4cf0-812f-b18b18d09264.jpg)

krist@DESKTOP-7E5L82P
OS: Windows 10 Pro [64-bit]
Host: Micro-Star International Co., Ltd. Modern 15 A11M
Kernel: 10.0.19044.0
Motherboard: Micro-Star International Co., Ltd. MS-1552
Uptime: 3 days 23 hours 48 minutes
Packages: 133 (scoop)
Shell: PowerShell v7.3.0
Resolution: 1920x1080
Terminal: Windows Terminal
Theme: System - Dark, Apps - Dark
CPU: 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
GPU: Intel(R) Iris(R) Xe Graphics
CPU Usage: 60% (212 processes)
Memory: 7.48 GiB / 15.71 GiB (47%)
Disk (C:): 90 GiB / 458 GiB (19%)
Battery: 98% (Plugged in)
Weather: -1°C - Overcast (Calgary, Canada)

- Status desktop version: 0.8.0-rc.2
- Operating System: Windows 10 Pro [64-bit]

**Comment by iurimatias** [comment]
hi @Zliced13 

- did you have status installed in this machine before?
- if you go here, are there any files? `Press the Start button, select Run (or Windows Key + R) and type: %LOCALAPPDATA%\Status`

**Comment by caybro** [comment]
I was able to reproduce, Windows 11

**Comment by jrainville** [comment]
Closing this one as we already have https://github.com/status-im/status-desktop/issues/7906

**Comment by Zliced13** [comment]
> hi @Zliced13 
> 
> 
> 
> - did you have status installed in this machine before?
> 
> - if you go here, are there any files? `Press the Start button, select Run (or Windows Key + R) and type: %LOCALAPPDATA%\Status`

No I have never installed Status before.
