### ISSUE TITLE
[Communities]: “Transfer ownership” button for community is missing

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8300]
# Bug Report

## Description
The bug was fixed in https://github.com/status-im/status-desktop/pull/7466, but appeared again
## Steps to reproduce
1. Create a community
2. Open it for editing
3. Try to find the button 'Transfer Owner Node'

#### Expected behavior
The button 'Transfer Owner Node' is available for clicking
#### Actual behavior
There is no button 'Transfer Owner Node'
### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.1
Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
<img width="1425" alt="Screenshot 2022-11-17 at 15 51 44" src="https://user-images.githubusercontent.com/82375995/202451397-bddea34d-2447-47d1-b208-4facbd8b848f.png">

transfer ownership is still living in old pop up
