### ISSUE TITLE
Hitting enter should submit form when confirming seedphrase

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8309]
Look here:

![Screenshot from 2022-11-17 14-48-26](https://user-images.githubusercontent.com/445106/202463362-f3bbf0f2-4cc6-41b6-bdf9-fe1464a44913.png)

I'm hitting <Enter> but nothing happens. I'd expect this to confirm and send me to the next step.

**Comment by alexandraB99** [comment]
this was never a requirement plus see comment [here](https://github.com/status-im/status-desktop/issues/10186#issuecomment-1497404320)

**Comment by 0x-r4bbit** [comment]
> this was never a requirement plus see comment https://github.com/status-im/status-desktop/issues/10186#issuecomment-1497404320

It might have never been an explicit requirement (but common sense), but as there are now two people that have reported the same unexpected behavior, this just confirms that this should likely be tackled.

I think the fact that we don't support rudimentary keyboard support, like submitting a form by hitting enter, is rather a bug than a design decision. The comment you've linked merely states that this is working for some component but not for all. Again, nothing that was deliberately decided, just lack of time/priority I'd say.

So instead of closing this issue as non-actionable, I'd rather have us keep this open and slowly start to tackle it.
We don't have to fix this for all forms all at ones, but at least take care of the ones that have been reported by users and clearly would improve UX for many others.

Please reconsider your action here.

**Comment by alexandraB99** [comment]
> > this was never a requirement plus see comment [#10186 (comment)](https://github.com/status-im/status-desktop/issues/10186#issuecomment-1497404320)
> 
> It might have never been an explicit requirement (but common sense), but as there are now two people that have reported the same unexpected behavior, this just confirms that this should likely be tackled.
> 
> I think the fact that we don't support rudimentary keyboard support, like submitting a form by hitting enter, is rather a bug than a design decision. The comment you've linked merely states that this is working for some component but not for all. Again, nothing that was deliberately decided, just lack of time/priority I'd say.
> 
> So instead of closing this issue as non-actionable, I'd rather have us keep this open and slowly start to tackle it. We don't have to fix this for all forms all at ones, but at least take care of the ones that have been reported by users and clearly would improve UX for many others.
> 
> Please reconsider your action here.

Generally I just prefer adding stuff here and there without design spec in place but sure, if it's common sense, there you go https://github.com/status-im/status-desktop/pull/11871
