### ISSUE TITLE
Implement @everyone functionality

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#8311]
Add the ability to @everyone in messages.

When @everyone used in a message, all Community members will effectively receive a mention and all associated notifications/treatments.

<img width="1411" alt="everyone" src="https://user-images.githubusercontent.com/110033914/202469987-7d17a169-7e51-4a20-a7d0-6088e3bbaa4e.png">

@John-44

**Comment by jrainville** [comment]
Re-opened as https://github.com/status-im/status-desktop/issues/8479
