### ISSUE TITLE
Support declining community join requests

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#8316]
### Description

part of of epic https://github.com/status-im/status-desktop/issues/7072

Acceptance Criteria
- After receiving a Community Join Request, one should be able to go the activity center and reject it

**Comment by anastasiyaig** [comment]
@iurimatias @jrainville please revisit this - if we still need this to be implemented? The corresponding PR is really outdated. I put 0.10.0 for milestone in this ticket, but please take a look

**Comment by jrainville** [comment]
No longer desired. See discussion on status-go PR https://github.com/status-im/status-go/pull/2925
