### ISSUE TITLE
[Communities] The Reply form appears for a user, who is not joined to a private community

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8321]
# Bug Report

## Steps to reproduce
1. User A created a private community 'TEST", added a message there, and posted the public link to the community in the test chat
2. User B clicked on the link and opened the 'TEST' community and clicked on the Reply icon for a message in the TEST community

#### Expected behavior
The Reply icon is not shown for a community message, while the user is not joined to the community
#### Actual behavior
The form for replying appeared
### Additional Information
<img width="718" alt="image" src="https://user-images.githubusercontent.com/14942081/202596397-af3c4f79-1960-44ab-886a-c1cd60067b41.png">

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.1
Operating System: macOS Monterey

**Comment by jrainville** [comment]
This was fixed
