### ISSUE TITLE
Messaging: app nodes connection shows 5 peers when fleet nodes are already connected to > 20 nodes

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8323]
### Description

<img width="1512" alt="Screenshot 2022-11-18 at 13 48 34" src="https://user-images.githubusercontent.com/82375995/202694257-2b3225b5-accf-4b9d-999a-3153fafae9f4.png">

per discussion in discord: https://discord.com/channels/624205794384281629/1042475751783542884/1043117237764116480

```
Yeah, 5 won't be enough, as the fleet nodes are already connected to > 20 nodes. Which means it will be a lottery whether you receive a message or not. Also the likely explanation of why so many messages aren't stored (mesh is unhealthy). This is an indication that discovery methods may not be working well enough
```

**Comment by anastasiyaig** [comment]
@churik @iurimatias @glitchminer @qoqobolo

**Comment by richard-ramos** [comment]
This is currently on progress:
Changes have been made in status-go/go-waku to make your node discoverable when NAT is enabled, and experiments are currently being done on enabling hole punching for peers that are behind firewalls / routers.  (Discussions are available in #waku-e2e channels as well as meetings done every 2 days for reporting progress

**Comment by anastasiyaig** [comment]
@richard-ramos are u working on this still? How things are going? Can u please provide some info just to refresh my memory?

**Comment by richard-ramos** [comment]
This issue's been fixed already, it was a problem with DiscoveryV5 in go-waku, which was not advertising the correct IP address for the nodes, so they were not discoverable. Users should be able to see more than 5 connections now

**Comment by anastasiyaig** [comment]
thanks for confirming! I also see more than 5 nodes recently these days. @glitchminer @churik please feel free to re-open / create another ticket if u still see the problem
