### ISSUE TITLE
Replies to messages are not counted in channel "mentions" badge

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8324]
# Bug Report

When there is a channel with unread messages, which contain replies to current user's messages, 
the blue badge next to channel name should count replies as mentions.

## Description

<img width="1539" alt="Снимок экрана 2022-11-18 в 14 50 07" src="https://user-images.githubusercontent.com/25482501/202699215-646bed34-48e7-4c28-ad7e-1750cd3ae42f.png">

This is what we should see. Just as it works for mentions.

<img width="1539" alt="Снимок экрана 2022-11-18 в 14 49 13" src="https://user-images.githubusercontent.com/25482501/202699194-d1a1b9e0-5d9c-45be-a715-30fb92465479.png">

#### Expected behavior

There should be a badge next to channel name, just as if it there's an unread message with mention in the channel.

#### Actual behavior

No badge 🙁

**Comment by jrainville** [comment]
The current behaviour is actually the wanted behaviour as of now, but I agree that replies should behave like mentions.

Waiting for a response from @John-44 to see if agrees changing it to that replies are also considered mentions

**Comment by jrainville** [comment]
Haha ok then. I'll start modifying status-go in this case
