### ISSUE TITLE
Invite contacts to community - big gaps between search results

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#8333]
# Bug Report

## Description

When contacts list is filtered via search field, there are some unintended gaps between rows in contacts list.

May be related to https://github.com/status-im/status-desktop/issues/7707

![Screenshot from 2022-11-18 17-13-00](https://user-images.githubusercontent.com/20650004/202752027-213ec908-ff7a-45e6-9409-92af7686c963.png)

## Steps to reproduce
Go to community, invite users, use search field to filter the contacts list
Can be also easily reproduced in Storybook (`InviteFriendsToCommunityPopup`).

#### Expected behavior
Result list should be consistent, no gaps

#### Actual behavior
There are gaps between results (of various size)

### Additional Information

- Status desktop version:
- Operating System:

**Comment by iurimatias** [comment]
seems fixed in latest master
