### ISSUE TITLE
Profile settings - cannot scroll if the cursor is placed over text areas

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#8338]
# Bug Report

## Description

User is unable to scroll in settings page if the cursor is placed over text area

## Steps to reproduce

1. Go to Settings -> Profile
2. Scroll down
3. Make sure the mouse is over a text area
4. Scroll up

#### Expected behavior
User is able to scroll up if the active focus in not on a scrollable text area
#### Actual behavior
User is unable to scroll up
### Additional Information

- Status desktop version: v0.8.0-rc2
- Operating System:MacOs

**Comment by iurimatias** [comment]
can't replicate

**Comment by caybro** [comment]
This is reproducible with touchpad scrolling only (at least on Linux and macOS afaik)
