### ISSUE TITLE
Wallet: Transaction on Goreli Optimism are not seen in History view

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#8351]
# Bug Report

## Description

Goreli-Optimism transactions are not listed in the history view

## Steps to reproduce

1. Send a Tx over the Goreli-Opt network chain
2. Wait to see if the Tx is complete don etherscan and restart the app 
3.  view history view

#### Expected behavior
The completed Tx should be listed after a restart or refresh of the history view

#### Actual behavior
the Tx is never seen

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by alaibe** [comment]
we need to double check if this is still happening, I fixed the commands

**Comment by Khushboo-dev-cpp** [comment]
Will put this on hold till @alaibe fixes the issue with checkRecentHistory  for optimism chain

**Comment by anastasiyaig** [comment]
it seems to be already fixed in master
