### ISSUE TITLE
Long group chat names should also be blurry behind `Notification` icon

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#8359]
## Steps to reproduce
1. Create a group chat with long name

### Expected result:
If group chat name exceeds the blanck area, it will be shown blurry behind all icons.

### Actual result:
If group chat name exceeds the blanck area, it is shown blurry behind all icons less the notification one.
![Screenshot 2022-11-21 at 08 52 21](https://user-images.githubusercontent.com/97019400/203076571-87e9e998-e715-432a-8dcf-7c10f6c639c6.png)

### Additional information
Reproduced on `0.8.0-rc.2`

**Comment by micieslak** [comment]
It's a regression or faulty fix in https://github.com/status-im/status-desktop/pull/7783.

**Comment by caybro** [comment]
Yeah... this chat info header button needs some serious love...

**Comment by iurimatias** [comment]
no longer happens
