### ISSUE TITLE
Community view data is missing when hitting a "Go to community" button

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8361]
After receiving a link to a community and hitting the "Go to community" button I see something like this:

![Screenshot from 2022-11-21 16-19-12](https://user-images.githubusercontent.com/445106/203091999-52194b42-4030-4581-933b-e81c507e4dcb.png)

Probably missing data from mailserver? After a few moments the data was available

**Comment by 0x-r4bbit** [comment]
@iurimatias please don't close this issue without any reference if and how this was fixed.
This is still happening as of latest master from time to time.

**Comment by anastasiyaig** [comment]
it is reproducible now in master in 3 out of 3 attempts for encrypted and non-encrypted communities. Please include it in nearest possible iteration to fix @jrainville
