### ISSUE TITLE
App is unresponsive when sending a message in encrypted community

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8375]
When i'm trying to post new message in new status encrypted community on mac m1, app hangs , unresponsive with 100% CPU usage

edited: not reproduced anymore

**Comment by anastasiyaig** [comment]
I cant reproduce it, i sent messages in encrypted community yesterday and today , they were just fine. I am on M1 Ventura

**Comment by flexsurfer** [comment]
hm , same version of the app, but now i can see messages in new community and can post without issues

**Comment by anastasiyaig** [comment]
@flexsurfer is it still a blocker?

**Comment by flexsurfer** [comment]
idk, because i can't replicate it anymore

**Comment by anastasiyaig** [comment]
i will keep it in GH but will remove the blocker indicator

**Comment by flexsurfer** [comment]
i believe @alwx just experienced the same behavior

**Comment by alwx** [comment]
Yep, I had the same issue but after a couple of days of waiting it got gone somehow without me even doing anything.

**Comment by flexsurfer** [comment]
@anastasiyaig @iurimatias so the issue is still here

**Comment by anastasiyaig** [comment]
@flexsurfer @alwx just to be sure, which version of status u are today seeing this issue?

**Comment by alwx** [comment]
@anastasiyaig 0.8.1, macOS Ventura

**Comment by anastasiyaig** [comment]
aha interesting, thanks for sharing

**Comment by anastasiyaig** [comment]
@MishkaRogachev ^

**Comment by iurimatias** [comment]
talked to @flexsurfer , issues is not happening anymore
