### ISSUE TITLE
Message gaps are not renewed without restart

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8377]
### Description

When the app is not restarted , TODAY message gap is not renewed and shows all messages under Today, even they were sent yesterday. As result, when new messages are coming in - there will be 2 Today labels.

<img width="1396" alt="Screenshot 2022-11-22 at 12 35 48" src="https://user-images.githubusercontent.com/82375995/203279166-52dc5576-79da-49e5-b97a-903e2da3a115.png">

**Comment by 0x-r4bbit** [comment]
Created https://github.com/status-im/status-desktop/pull/8957 which removes "today" and "yesterday" entirely.
Lemme know if this is rather undesired.
