### ISSUE TITLE
OS notifications showing Contact Request message from myself

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#8381]
Issue:
Random delivery of OS notifications which show my own Contact Request messages.

<img width="368" alt="OS-notification" src="https://user-images.githubusercontent.com/110033914/203295872-3f75ec68-dce8-499c-9916-c5a87101fd79.png">

Tapping the notification does not appear to show any state in the app relating to the Contact Request or anything else.
<img width="1128" alt="Screenshot 2022-11-22 at 10 53 01" src="https://user-images.githubusercontent.com/110033914/203296115-267f752a-bb9f-485d-9f6c-a2a95b84e022.png">

**Comment by anastasiyaig** [comment]
Known already

**Comment by anastasiyaig** [comment]
but can't find the ticket :D so lets keep this one

**Comment by John-44** [comment]
what a user should see is defined in this Figma https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18681&t=PwuUK2tTs7kgO4TG-0  see image ("Contact request accpeted") line
![2022-11-22 16_27_48-Shell for Mobile – Figma](https://user-images.githubusercontent.com/22846356/203326228-312cd11a-dce3-49d9-8d33-eb86acf7525c.png)

**Comment by jrainville** [comment]
More detail for @mprakhov : Any type of message coming from ourselves should never be shown as an OS notification, not just contact requests.
