### ISSUE TITLE
After logout/login community icons are duplicated

### ISSUE THREAD

**Issue by siphiuel** [status-im/status-desktop#8382]
# Bug Report

## Description

Logged out, logged in again. Community icons `(old) Status CCs` and `Status CCs v2` are duplicated.

## Steps to reproduce

1. Join 2 communities `(old) Status CCs` and `Status CCs v2`.
2. Logout from Desktop app.
3. Login again
4. Result: icons are duplicated. Selection of active community is duplicated too.

#### Expected behavior
No duplication

#### Actual behavior
Duplicate community icons

### Additional Information

- Status desktop version: 0.8.0-rc2
- Operating System: Ubuntu 22.04

![Screenshot from 2022-11-22 13-07-43](https://user-images.githubusercontent.com/1019573/203300203-1db9b22f-5988-4c54-b44a-fcf7c0960f90.png)

**Comment by jrainville** [comment]
Thanks for logging. This was already logged here: https://github.com/status-im/status-desktop/issues/7167
