### ISSUE TITLE
[dogfooding] [0.8.0]  Space is not allowed in password

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-desktop#8385]
# Bug Report

## Description

Space is not allowed in passwords while generating keys or recovering using seed phrases.
But it is allowed while logging in. So while creating an account I thought I entered space, but it got ignored. And I kept entering the wrong password while login in.

**Comment by anastasiyaig** [comment]
@John-44 @benjthayer i need your input on this but i think it is not a bug. we dont have any control over the chars user uses for passwords

**Comment by benjthayer** [comment]
Good catch @Parveshdhull 

@John-44 I wonder if we need some validation or a tooltip near the password input at the point when the user tries to enter a space or other invalid character? This would at least clarify to them that spaces are not allowed **before** they go ahead and confirm the password by writing it again. This would mitigate the likelyhood they would leave the password creation flow thinking that they have successfully created a password with t a space. 

As an aside, if we are able to block the user from using passwords at the password generation step, can we also stop them from entering them at the login step for consistency?

<img width="603" alt="Screenshot 2022-11-23 at 14 00 16" src="https://user-images.githubusercontent.com/110033914/203565575-52086018-b50d-43f9-a752-960f62a4ef07.png">

**Comment by benjthayer** [comment]
We actually do something similar with the display name validation:

<img width="481" alt="Screenshot 2022-11-23 at 14 05 05" src="https://user-images.githubusercontent.com/110033914/203566619-2d5b9656-4501-4ebf-951b-4f8c83684fd5.png">
