### ISSUE TITLE
AC notification text formatting issues

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#8387]
- AC Notification plain text should support unicode tags
<img width="548" alt="image" src="https://user-images.githubusercontent.com/2522130/203334436-6d2e72d1-becd-4ed6-981e-b90f619947cc.png">

**Comment by caybro** [comment]
It happens in Utils.qml:

```qml
    function escapeHtml(unsafeStr)
    {
        return unsafeStr
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#039;");
    }
```

**Comment by MishkaRogachev** [comment]
Closed here: https://github.com/status-im/status-desktop/pull/8896
