### ISSUE TITLE
Allow spacing in usernames and nickname

### ISSUE THREAD

**Issue by pedro-et** [status-im/status-desktop#8391]
We need to allow the user to create a name using spaces. The same should apply when giving someone a nickname.
Examples:
John Doe
Super Mario
Frodo Baggins
<img width="857" alt="Screenshot 2022-11-22 at 15 56 11" src="https://user-images.githubusercontent.com/97039678/203373603-5ec78bcf-c8e7-49b8-9d07-75237c5263ae.png">

**Comment by anastasiyaig** [comment]
@John-44 please confirm this is a feature we want

**Comment by caybro** [comment]
@John-44 and while we're at it (the implementation will be orthogonal), whether we also want to allow users using Unicode characters for their DisplayName (already done for local Nickname). TIA :)

**Comment by John-44** [comment]
> @John-44 please confirm this is a feature we want

Yes! :-)

**Comment by John-44** [comment]
> 



> @John-44 and while we're at it (the implementation will be orthogonal), whether we also want to allow users using Unicode characters for their DisplayName (already done for local Nickname). TIA :)

Probably not.  We purposefully only allow users to use A-Z (uppercase and lowercase), 0-9 and "-" and "_" in their usernames (and nothing else, see https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=854%3A277243&t=NvalKX7lJy9Pdd1Z-1 ) to prevent users using weird characters to pretend they have an ENS name, or to create a name that looks very similar to another name but uses different characters.
