### ISSUE TITLE
How can i Login to my Desktop app while i have 12 words seed phrase 

### ISSUE THREAD

**Issue by mzaeemnasir** [status-im/status-desktop#8395]
### Description

I have 12 words seed phrase but when I click import then its asking 24th word ??

**Comment by iurimatias** [comment]
hey @mzaeemnasir , could you post a screenshot of what you are seeing, and what desktop version are you using.

This is what I see

![Screen Shot 2022-11-22 at 4 06 43 PM](https://user-images.githubusercontent.com/176720/203421268-9165fb0a-12bf-411a-9d1a-07d2309092c5.png)

**Comment by iurimatias** [comment]
seems this has been answered here https://github.com/status-im/status-desktop/discussions/8394
