### ISSUE TITLE
Settings -> Backup seed phrase: warning text background is not resized when using large text size

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#8402]
# Bug Report

After setting XXL text size from Appearance settings, the red warning background from Backup seed phrase popup is not resized based on the new text size

<img width="1512" alt="Screenshot 2022-11-23 at 12 06 44" src="https://user-images.githubusercontent.com/47811206/203520687-4c731299-883c-4825-943c-c90a4675c1a1.png">

## Steps to reproduce
1. Go to Settings -> Appearance
2. Set font size to XXL
3. Go to Settings -> Back up seed phrase

#### Expected behavior
The textbox with red background should be resized to cover the new text size
#### Actual behavior
The textbox with red background is not resized and the text is overflowing
### Additional Information

- Status desktop version:
- Operating System: MacOs

**Comment by iurimatias** [comment]
confirmed, still an issue
