### ISSUE TITLE
In full-screen mode, the app closes on clicking 'X' on the window, instead of being minimized

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-desktop#8415]
# Bug Report

## Description

https://user-images.githubusercontent.com/67952253/203586130-d987a81f-9317-4e77-8bd0-380798a09342.mov

## Steps to reproduce

1. Enable `Minimize on close` in settings
2. Expand the window to full screen
3. Click the `X` button on the window

#### Expected behavior
The app is minimized

#### Actual behavior
The app is closed, need to log in

### Additional Information

- Status desktop version: 0.8.0 rc2
- Operating System: macOS 13.0.1

**Comment by iurimatias** [comment]
fixed in the meanwhile
