### ISSUE TITLE
Community: Add CAPTCHA before sending a community request

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8416]
### Description

To reduce spam and DDOS attacks on a community, we need to add a CAPTCHA before the community request is sent.

~~This will need some new design before development can be started.~~
edit: Designs here: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2457%3A331542&t=Aj04X1c3THOVvoQg-0

Using https://www.hcaptcha.com/ is a good option

**Comment by John-44** [comment]
Designs for how the CAPTCHA integrates into the UI are here https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2090%3A245814&t=qKNFIlk6LX7fUIlh-0

**Comment by John-44** [comment]
This issue should be closed, as the CAPTCHA before sending a community request has been descoped from MVP
