### ISSUE TITLE
Community Join button should say  "Join community" if auto accept + owner is online

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8417]
### Description

Here are the conditions: 
"Join community" is shown if:
- the user hasn't joined the community
- AND  'auto accept requests to join'
- AND  the Owner Node is online

Otherwise, if one of the two points above is false, we show "Request to join"  (ie 'manually accept requests to join' is switched on OR the Owner node is offline)

See the "Manual Membership approval needed?" switcher here: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2365%3A295996&t=Aj04X1c3THOVvoQg-0

**Comment by osmaczko** [comment]
I think the last point doesn't make sense with our statuses. "Always online" means online for two weeks, in the worst-case scenario admin may not be up for two weeks and users may still see "Join community" :thinking:

**Comment by borismelnik** [comment]
@jrainville based on last discussion I need to implement some "ping" mechanism in status-go

**Comment by borismelnik** [comment]
@jrainville I moved it to this column cos @cammellos has another opinion about 3th point

**Comment by PascalPrecht** [comment]
> I think the last point doesn't make sense with our statuses. "Always online" means online for two weeks, 

This is unrelated to the "online status" of users.
A owner node being online just means the node is connected to the network and sends/receives signals (like automatically approving community member requests to join)

**Comment by PascalPrecht** [comment]
Given that there's some push back on the PR that implements this (#2999), how would everyone feel about just having 1) and 2) as a requirement for a "Join community" label?

We shouldn't forget that, even if some node receives a signal that the owner node is online, and we change the label to "Join community", there's no guarantee that the owner node is still online by the time the user this that button.

**Comment by osmaczko** [comment]
> Given that there's some push back on the PR that implements this (https://github.com/status-im/status-go/pull/2999), how would everyone feel about just having 1) and 2) as a requirement for a "Join community" label?

I don't know. IMO it may still be confusing to the user to see "Join community".

I would opt to always have "Request to join" instead. We should probably adapt our community settings to show "Auto accept requests" rather than "Request to join required". It will align better with what we really do and we will avoid confusion and edge cases.

> We shouldn't forget that, even if some node receives a signal that the owner node is online, and we change the label to "Join community", there's no guarantee that the owner node is still online by the time the user this that button.

Exactly.

**Comment by cammellos** [comment]
I'll ask @John-44 when he's back, I'd suggest to put this on halt until there's a decision.

**Comment by jrainville** [comment]
I think always showing `Request to join` is fine. The issue is on hold for now pending the decision
