### ISSUE TITLE
Chat: the date of message is shown while sending a contact request

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8423]
# Bug Report

## Steps to reproduce
1. Go to the test chat and post there:  https://join.status.im/u/zQ3shrzbTyj9RAqnysghYthb95T52dmzX9ofjuKYZZu28CAjV
2. Click on the posted link
3. Click 'Send contact request'
4. Start to write some messages in the appeared modal

#### Expected behavior
The date of a message from the chat does not appear
#### Actual behavior
The date of a message from the chat appeared
<img width="502" alt="image" src="https://user-images.githubusercontent.com/14942081/203684219-55c49702-bab2-43cf-9c54-72bd682781ed.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.5
Operating System: macOS Monterey

**Comment by caybro** [comment]
It's the tooltip leaking from the chat messages view underneath

**Comment by iurimatias** [comment]
cant replicate anymore
