### ISSUE TITLE
Crashed right away at start

### ISSUE THREAD

**Issue by qfrank** [status-im/status-desktop#8424]
With a fresh installation (removed old Status.app from Applications, removed old data dir `~/Library/Application Support/Status`), when i start Status.app, it crashed right away.

![screenshot](https://cdn.discordapp.com/attachments/1045004628649062412/1045162629645217853/image.png)

#### Expected behavior
start up normally

#### Actual behavior
crashed

### Additional Information

- Status desktop version: v0.8.0-rc.5-7e6ec2
- Operating System: mac os big sur 11.0.1 

[detail.log](https://github.com/status-im/status-desktop/files/10080531/detail.log)

**Comment by caybro** [comment]
Again looks like a too old version of macOS (there's a symbol missing from libc), try updating pls.

**Comment by qfrank** [comment]
emm, if i can't update my version of macOS for some reason, is there any working method? @caybro

**Comment by caybro** [comment]
I didn't mean necessarily upgrading to a newer major version, a mere update of the current one should do. The problem is that our packages are built against a much newer macOS version that's binary incompatible with yours (blame Apple for breaking backwards binary compatibility)

**Comment by qfrank** [comment]
i can't even update to 11.7 for some reason  🥲

**Comment by caybro** [comment]
> i can't even update to 11.7 for some reason  🥲 , can we built against a much lower macOS version? @caybro 

I'm afraid not unless you persuade GitHub 😬 @jakubgs ?

**Comment by qfrank** [comment]
I'll try.. Hi @jakubgs , we can't expect every normal user use the latest or almost latest version of mac os right? that sounds not cool, and i think it's not a good user experience..

**Comment by jakubgs** [comment]
We need resonably recent MacOS on CI to be able to use up-to-date XCode. If we need this for release builds then we'd need to purchases a dedicated MacOS machine that will do nothing most of the time other than build a desktop release once in a blue moon on an older OS version.

Considering almost nobody uses this unstable software other than internal contributors I see no value in this currently.
Once we have a stable release that actually is supposed to be targeting a wider audience then maybe this would make sense, but as it stands if it's only for internal use it seems like an unnecessary extra work and cost.

**Comment by jakubgs** [comment]
@qfrank why can't you upgrade? Is it a hardware issue?

**Comment by qfrank** [comment]
@jakubgs hackintosh

**Comment by jakubgs** [comment]
Ugh, that's a pain in the ass. Especially since for the sake of Mobile we need to keep Xcode updated, and for example newest 14.1 release requires macOS 12.5+:
https://xcodereleases.com/?q=14&scope=release

![image](https://user-images.githubusercontent.com/2212681/203957403-e9000e6a-cb49-4b95-aeef-ad90d2284f72.png)

**Comment by qfrank** [comment]
sounds not good... i may shift to android instead, but i will try to get a laptop finally

> Ugh, that's a pain in the ass. Especially since for the sake of Mobile we need to keep Xcode updated, and for example newest 14.1 release requires macOS 12.5+: https://xcodereleases.com/?q=14&scope=release
> 
> ![image](https://user-images.githubusercontent.com/2212681/203957403-e9000e6a-cb49-4b95-aeef-ad90d2284f72.png)

**Comment by qfrank** [comment]
thanks to @borismelnik , this [PR](https://github.com/status-im/status-desktop/pull/8442) just fixed this issue 🚀
