### ISSUE TITLE
Notifications: The sound of notifications is harsh and annoying

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8426]
# Bug Report

## Steps to reproduce
1. Join some chat or community
2. Got some messages mentioning there

#### Expected behavior
The sound is pleasant and not harsh
#### Actual behavior
The notifications appeared with an annoying and harsh sound
### Additional Information
- Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.5
- Operating System: macOS Monterey

**Comment by caybro** [comment]
@elina2015 just wondering, is this happening with in-app notifications or OS/system notifications, or both the same? Asking because we have different code paths there
