### ISSUE TITLE
Community: in Windows, it's impossible to create a community with a community logo or banner

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8427]
# Bug Report

## Steps to reproduce
1. In Windows 10
2. Go to create a community with a logo, or banner, or banner and logo
3. Fill out all the required fields, Save the community

#### Expected behavior
The community is saved correctly
#### Actual behavior
The community is not saved
### Additional Information

https://user-images.githubusercontent.com/14942081/203700485-a54d5707-104f-4e22-8b99-9ee4194d21af.mov

- Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.5
- Operating System: Win 10

**Comment by iurimatias** [comment]
this has been fixed
