### ISSUE TITLE
Community: in Win 10, the app crashed if user is sending a big image

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8428]
# Bug Report

## Steps to reproduce
1. Go to any community and send there the image from this link(22Mb): https://drive.google.com/file/d/13wvN1UTVycMoDXxSS28FilLRgFdm2kRC/view?usp=sharing

#### Expected behavior
The app is not crashed and the proper notification about image size limit appeared
#### Actual behavior
The app crashed and the error is shown
### Additional Information
<img width="447" alt="image" src="https://user-images.githubusercontent.com/14942081/203701892-196914ed-8fff-4992-93d6-32603c768035.png">

- Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.5
- Operating System: Win 10

**Comment by caybro** [comment]
Can't reproduce on Linux (I get the warning about max image size):

![image](https://user-images.githubusercontent.com/5377645/203749077-f6a7cda9-4e6f-4ac5-aad6-8481e65869c5.png)

**Comment by elina2015** [comment]
> Can't reproduce on Linux (I get the warning about max image size, the file is ~22MB):
> 
> ![image](https://user-images.githubusercontent.com/5377645/203749077-f6a7cda9-4e6f-4ac5-aad6-8481e65869c5.png)

@caybro yeah, it's not reproduced for Linux and mac, only Windows.

**Comment by jrainville** [comment]
I tested in Windows 10 and I got the normal error message like Lukas showed.

Can you try again @elina2015 ? Do note, in the current master, sending images is broken. Use this PR to test: https://github.com/status-im/status-desktop/pull/8752

**Comment by elina2015** [comment]
> I tested in Windows 10 and I got the normal error message like Lukas showed.
> 
> Can you try again @elina2015 ? Do note, in the current master, sending images is broken. Use this PR to test: #8752

Hey @jrainville, I tested on Win 11 and used RC1 0.9. 0 and #8752 - and the bug is stable reproduced.

**Comment by elina2015** [comment]
https://user-images.githubusercontent.com/14942081/211444737-2eaf8046-39ce-4f26-9641-4661fa5789d0.mov

**Comment by caybro** [comment]
That's still inside a VM/sandbox; can we test this under _real_ Windows? :)

**Comment by anastasiyaig** [comment]
@glitchminer could u please be so kind to assist here? Since i forced u to own windows :D

**Comment by glitchminer** [comment]
@anastasiyaig - *real* Win11 is showing the regular file size error in 0.9RC1: 
![image](https://user-images.githubusercontent.com/50769329/212040440-e7f696a9-5e60-42cc-a235-761eeaf6e428.png)

**Comment by anastasiyaig** [comment]
so no issue for real windows 11, right? @glitchminer sorry for dumb clarification here, lost in comments :D

**Comment by glitchminer** [comment]
> so no issue for real windows 11, right? @glitchminer sorry for dumb clarification here, lost in comments :D

That's right. OK to close I think but it would also be nice to know why it fails on the vm.
