### ISSUE TITLE
App freezes after attempt to send a message

### ISSUE THREAD

**Issue by xAlisher** [status-im/status-desktop#8430]
https://user-images.githubusercontent.com/7700914/203747018-a96d86f3-4742-45db-a65e-d23bf8a0268a.mov

Status desktop version:
0.8.0 - rc.4

Operating System:
MacOS 12.0.1

**Comment by jrainville** [comment]
I think this might be fixed by Andrea's fix on encryption. We'll need Alisher to try to reproduce one 0.9 is out

**Comment by jrainville** [comment]
@xAlisher could you try to reproduce this issue again with 0.9.0? Thanks
