### ISSUE TITLE
Storybook: Prevent building `Storybook` for desktop using `Storybook.pro` (for `wasm` only)

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#8451]
# Improvement proposal

## Description

`Storybook.pro` is created only for `WebAssembly` build. For desktop `CMakeLists.txt` should be used. However it's easy to set-up Storybook for desktop using `Storybook.pro` by mistake. App is compiling and running but some changes in files are not reflected property between app re-runs. Also hot reloading is not working.

#### Expected behavior
Some error should be reported when trying to use `Storybook.pro` for desktop build.

#### Actual behavior
Desktop version can be configured using `Storybook.pro`.

**Comment by alexjba** [comment]
The storyBook.pro uses precompiled qml files. We need to disable the hot reload if the qml files are precompiled.
Regarding file changes not being reflected between re-runs, might be worth investigating on wasm builds also because the project configuration is the same.

**Comment by caybro** [comment]
Somwewhere at the top of the .pro file, something like:

`!wasm: error("This .pro file is meant for WASM only")`
