### ISSUE TITLE
[StatusChatInput] refactoring: Extract emoji logic from StatusChatInput.qml

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#8465]
### Description

Extract emoji logic from StatusChatInput.qml. The code is tightly coupled with mentions logic.

Also define/implement the emojis overall behavior, currently emojis in the chat input are inserted only if typing the ascii alias and not the short name.
The Discord approach:

- Detect emoji short name in chat input by showing a "emoji suggestions" popup on the second typed character after :
- Detect both short name and ascii alias in chat history

See #7686 , #8464

**Comment by alexandraB99** [comment]
maybe it would make sense to also upgrade the emoji library while extracting the logic, linking here https://github.com/status-im/status-desktop/issues/8979

**Comment by alexandraB99** [comment]
@benjthayer we would need input from design here when it comes to the overall emoji behavior in the chat input, currently emojis in the chat input are inserted only if typing the ascii alias and not the short name. However this is not in line with other messengers we're used to like eg:
The Discord approach:

    Detect emoji short name in chat input by showing a "emoji suggestions" popup on the second typed character after :
    Detect both short name and ascii alias in chat history

Could you please provide us specs on how should emojis work considering also white spaces (eg if user types _:)_ ,where _ is a white space, then an emoji should appear, instead if they type :):):):) then no emoji should appear etc).

**Comment by caybro** [comment]
> * Detect emoji short name in chat input by showing a "emoji suggestions" popup on the second typed character after :
> * Detect both short name and ascii alias in chat history

I think we pretty much already support these 2 usecase scenarios; the code refactoring part is probably still valid though
