### ISSUE TITLE
Messages not in order post application restart

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#8466]
# Bug Report

## Description

Messages are not in order post application restart

![image](https://user-images.githubusercontent.com/33099791/204240507-aad8371b-f493-4c7b-905a-f12b9ea76d72.png)

## Steps to reproduce

Not sure if this is easily reproducible:
1) Reply to the message
2) Restart the app

### Additional Information

- Status desktop version: v0.8.0-rc.2-570a54

#### Notes
May be a status-go issue, IIRC when we start the app we load messages already sorted by status-go.

**Comment by PascalPrecht** [comment]
It's not easily reproducible. Here's what the same chat looks like for me:

![Screenshot from 2022-11-28 10-31-44](https://user-images.githubusercontent.com/445106/204242833-87e9aa12-1187-440d-9e84-40bf7dabc243.png)

**Comment by PascalPrecht** [comment]
Using version : `d0725d451`

**Comment by anastasiyaig** [comment]
i've seen the opposite https://github.com/status-im/status-desktop/issues/8377

**Comment by jrainville** [comment]
I see the same as Patryk on master's `d0725d451efedb12c205c127f4e08ae1ca9b155f`

**Comment by osmaczko** [comment]
I have it even stranger now. The last message is the contact request message and should be the first one.

![image](https://user-images.githubusercontent.com/33099791/205255114-d6aab700-37d6-4fcb-a7bf-becb6f21a1e0.png)

version: v0.8.0-rc.5-7e6ec2
