### ISSUE TITLE
Community: Go to Community button is off when hovering in dark theme

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8474]
### Description

1. paste a link to the community in a chat (u should be a member of the community)
2. hover over the invitation

<img width="846" alt="Screenshot 2022-11-28 at 13 27 09" src="https://user-images.githubusercontent.com/82375995/204265497-9e4074cb-5443-48bd-b500-74bf7c8b7712.png">

**Comment by PascalPrecht** [comment]
Duplicate of https://github.com/status-im/status-desktop/issues/8360

**Comment by anastasiyaig** [comment]
@PascalPrecht thank you! That was the one i never found by its title
