### ISSUE TITLE
Chat: contact's picture is missing in the 1x1 chat header

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8476]
### Description

1. i have added Pascal to contacts
2. the contact request was accepted
3. i opened the 1x1 chat with Pascal

As result, the avatar at the top in 1x1 chat is default, when everywhere else Pascal's custom pic is present

<img width="1596" alt="Screenshot 2022-11-28 at 13 29 39" src="https://user-images.githubusercontent.com/82375995/204268350-b2c58300-8815-4905-8f91-b5752842bfe6.png">

**Comment by jrainville** [comment]
Duplicate of https://github.com/status-im/status-desktop/issues/8273

**Comment by anastasiyaig** [comment]
ah sorry , the mentioned one was hard to find :D
