### ISSUE TITLE
symbols in the pasted url link are replaced by emoji

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8478]
when inserting URL in the chat, some symbols might be replaced by emoji so the link is invalid, and its not possible to open it

**Comment by jrainville** [comment]
Do you have an example so we can test with it?

**Comment by flexsurfer** [comment]
https://miro.com/app/board/uXjVP_uv9SE=/

**Comment by caybro** [comment]
Something to add to the list of StatusChatInput (cc @alexjba)
