### ISSUE TITLE
Rename "Communities Portal" button tooltip to "Communities"

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#8480]
## Description

On the Status desktop app, the Communities icon in the left-hand navigation bar is called "Communities Portal." However, the same icon is called "Communities" in the mobile desktop design. 

## Steps to reproduce

1. Open the Status desktop app
2. On the left-hand navigation bar, hover over the Communities icon
3. The icon tooltip is "Communities Portal"

#### Expected behavior

Hovering the mouse over the icon should show the "Communities" tooltip. 

#### Actual behavior

Hovering the mouse over the icon shows the "Communities Portal" tooltip

### Additional Information

- Status desktop version: 0.8.0-rc2
- Operating System: macOS 13.0.1 "Ventura"

**Comment by caybro** [comment]
@John-44 @benjthayer just checking (even though this is a trivial change), is this still desired?

**Comment by jorge-campo** [comment]
Thank you, @caybro – To clarify things with the terminology:

- There is no "Communities Portal".
- From the "Communities" button, users access the "Community Directory", a curated-by-members list of the public communities.
- This list is maintained in the "Community Directory Curation dApp", the code Patryk is working on.

**Comment by benjthayer** [comment]
@jorge-campo @caybro good spot. Considering the slightly different IA for desktop, it might be more on point to rename the tooltip `Discover Communities`. This is the title of the page the user is navigated to on clicking the icon / is the core function of the page. `Communities` may suggest to the user the can also view a list of joined/spectated Communities from here which in Desktop will not be the case - they can see the Communities the have joined in this list page but only by searching or browsing through all other Directory content

**Comment by caybro** [comment]
> @jorge-campo @caybro good spot. Considering the slightly different IA for desktop, it might be more on point to rename the tooltip `Discover Communities`. This is the title of the page the user is navigated to on clicking the icon / is the core function of the page. `Communities` may suggest to the user the can also view a list of joined/spectated Communities from here which in Desktop will not be the case - they can see the Communities the have joined in this list page but only by searching or browsing through all other Directory content

Up to you guys :)

**Comment by jorge-campo** [comment]
I agree with @benjthayer; let's use `Discover Communities` for the tooltip. This screen on the desktop app doesn't work 1:1 with mobile.

Apologies for the back-and-forward, @caybro!
