### ISSUE TITLE
Rename "Create New Community" button tooltip to "Create community"

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#8481]
## Description

On the Status desktop app, the CTA label to create a community is "Create New Community." This label should be renamed to "Create community" (observer uppercase and lowercase). 

## Steps to reproduce

1. Open the Status desktop app
2. From the sidebar, click Communities
3. The button to create a community is named "Create New Community"

#### Expected behavior

The button label to create a community is "Create community."

#### Actual behavior

The button label to create a community is "Create New Community."

### Additional Information

- This note was included as well in the [Desktop Figma designs](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=13514%3A418986&t=tmRG5BDJ0Qnayxtg-1)
- Status desktop version: 0.8.0-rc2
- Operating System: macOS 13.0.1 "Ventura"

**Comment by PascalPrecht** [comment]
I **believe** we've decided to go with "C"ommunity everywhere /cc @John-44

**Comment by anastasiyaig** [comment]
I am agree with Pascal here. @John-44 please confirm

**Comment by caybro** [comment]
Buttons usually use the title case, so I believe "Create Community" would be correct here

**Comment by jorge-campo** [comment]
> I believe we've decided to go with "C"ommunity everywhere /cc @John-44

If we're writing "Status Communities" or "Status Community" yes, that's uppercase "C" because that's a product name. But if we're talking about "communities" in general, that's not a product name and should not be capitalized.

I add here some examples from WhatsApp documentation to illustrate the idea:

![Screenshot 2022-11-29 at 3 45 10@2x](https://user-images.githubusercontent.com/62282406/204560372-ec2848b7-3827-46bb-88f0-f20d2f54ac75.png)
![Screenshot 2022-11-29 at 3 43 52@2x](https://user-images.githubusercontent.com/62282406/204560385-4b91d775-735a-4814-b9af-2dbace1a1cee.png)

**Comment by caybro** [comment]
That's not the same thing :) Here the term is used as part of a full sentence, not as a button caption. 

Quoting the same Apple HIG:
![image](https://user-images.githubusercontent.com/5377645/204562020-de49f526-6e6d-4d7f-8b7d-acf6ec91d67e.png)
