### ISSUE TITLE
Move history fetching timer to status-go

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8486]
This issue https://github.com/status-im/status-desktop/pull/8348 found that something made closing the app hang.

It turns out, it was the  `FetchingHistoryTimer`, because it lasts 20 minutes and threads in Nim suck. You can find more information on the problem and the lines causing issue here: https://github.com/status-im/status-desktop/pull/8485

That code should be moved to status-go. In theory, it should be simple, it's a timer. The code that the timer calls can also be moved to status-go, since it just calls `checkRecentHistory` (with some conditions). The rest is handled by signals already.

**Comment by alaibe** [comment]
Proposed solution:
on wallet start create 2 timers, which sends two event:
* fetch balance
* fetch history
both timer send an event

on nim when we receive the event we trigger the call to refetch history or balance

**Comment by jrainville** [comment]
I would propose that you don't need to send a signal just for the timer end. You could just do the processing/fetching that we call on the Nim side, then those send their own signals that Nim already knows how to process.

pro: it's cleaner and we have less signal handling to do. Nim doesn't even have to know about the timer

con: it's a semi-breaking change. Mobile would then be "double" fetching the history for example. Also, maybe mobile doesn't want to fetch as often?
  - One solution for that would be to add a new setting (or similar) that you can send the amount of time you want to set the timer, so basically the fetching interval. That solves both issues. Mobile can set a higher interval if they want. Also, we make that setting `null` or `undefined` by default, so we only perform the timer/interval when it is not null. That way, the status-go timer would only work on desktop until mobile updates their own wallet code.
