### ISSUE TITLE
Contact request: accepted contact requests are shown after relogin

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8488]
it is a really annoying bug, time from the time I receive random notifications with weird messages from myself

it can be like 3-5 in a row

in a random time

they are inside the app right bottom corner

**Comment by anastasiyaig** [comment]
normally what u are seeing at the bottom right are in-app notifications for channels . First thing is that u are not now mute the channel in community (the mute setting is not applied) so u will receive all the notifications if enabled in settings.

Second part, notifications from yourself - that could be a bug about contact request messages, so when u send a contact request  and it is accepted - there is a notification with your initial message, not with the confirmation of the contact request is accepted.

So far it is hard to debug, any screenshot or any more information would be nice to have to understand what u are receiving and when (even it looks like random thing) @flexsurfer

**Comment by flexsurfer** [comment]
but for 2, for sure it always happens after i relogin, i receive them a bunch

**Comment by anastasiyaig** [comment]
so for the 1st problem - there is existing issue https://github.com/status-im/status-desktop/issues/8381
for second problem - i will try to reproduce and add details here

**Comment by anastasiyaig** [comment]
**Example:** 

i removed this account from contacts a while ago. today i launched status being on status.prod fleet and received an incoming contact request.  I checked logs in the app and i dont see anything that can be helpful:
```
DBG 2022-11-30 11:40:14.951+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=1673575 file=core.nim:20 rpc_method=wakuext_getLatestVerificationRequestFrom
```

<img width="1698" alt="Screenshot 2022-11-30 at 11 45 52" src="https://user-images.githubusercontent.com/82375995/204751268-33c972d3-5f30-4a07-8178-f154b6fe1cb5.png">

**Comment by cammellos** [comment]
@anastasiyaig we can have a look at status-go, yes, but it would be handy if someone from desktop would tell us exactly how these notifications are displayed (i.e, do you have any custom logic, which fields from status-go do you use etc)

**Comment by anastasiyaig** [comment]
@richard-ramos please-please-please

**Comment by richard-ramos** [comment]
Based on what I could see in code, contact requests are shown if there is at least one contact that has all these conditions:
- You have received a contact request from them  (`hasAddedUs == true`)
- We didnt sent a contact request to them (`added == false`)
- It's not a removed contact (`removed == false`)
- Their contact request has not been rejected (`contactRequestState != ContactRequestStateDismissed`) 
-  It's not blocked (`blocked == false`)

**Comment by cammellos** [comment]
> Based on what I could see in code, contact requests are shown if there is at least one contact that has all these conditions:
> 
> * You have received a contact request from them  (`hasAddedUs == true`)
> * We didnt sent a contact request to them (`added == false`)
> * It's not a removed contact (`removed == false`)
> * Their contact request has not been rejected (`contactRequestState != ContactRequestStateDismissed`)
> * It's not blocked (`blocked == false`)

is that logic in status-go or in desktop?

**Comment by richard-ramos** [comment]
Desktop

**Comment by cammellos** [comment]
> Desktop

ah ok, all of these checks probably should be done in status-go, so that the behavior is consistent, do you have a link to the desktop code?

**Comment by richard-ramos** [comment]
https://github.com/status-im/status-desktop/blob/master/src/app_service/service/contacts/service.nim#L231-L237
