### ISSUE TITLE
"Key for this account already exist" when creating new account

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#8489]
# Bug Report

## Description

Sometimes when creating a new account I face "Keys for this account already exits" dialog error.

![image](https://user-images.githubusercontent.com/33099791/204464797-478e6e76-a955-4f15-b987-7c801679b18b.png)

Console logs:
```
DBG 2022-11-29 08:27:09.932+01:00 primary_action                             topics="app-controller" tid=1335565 file=module.nim:145 currFlow=FirstRunNewUserNewKeys currState=UserProfileConfirmPassword
ERR 2022-11-29 08:27:09.932+01:00 There was some issue initiating account service topics="accounts-service" tid=1335565 file=service.nim:124
ERR 2022-11-29 08:27:09.932+01:00 list of generated accounts is empty        topics="startup-controller" tid=1335565 file=controller.nim:315
```

## Steps to reproduce

Don't know what are the exact steps. Most likely:

- have a second instance running on the same port?
- create a new account

### Additional Information

- Status desktop version: master (d0725d451efedb12c205c127f4e08ae1ca9b155f)
- Operating System: Ubuntu 22.04

**Comment by anastasiyaig** [comment]
@osmaczko are u sure u are running desktop instances with different ports?

**Comment by osmaczko** [comment]
> @osmaczko are u sure u are running desktop instances with different ports?

@anastasiyaig I've mentioned in the issue that I run two desktop instances with the same port. Not sure how it relates to "Keys for this account already exits" though, the message is misleading a bit.

**Comment by anastasiyaig** [comment]
@osmaczko it is indeed, however running 2 instances is not really something we can provide as working and tested. It works like that but in terms of feature definition it was never planned. Also, having 2 instances on the same port wont work regardless the message displayed. I am not really sure this is a bug and how it impacts onboarding

**Comment by osmaczko** [comment]
You are right, I'll close it.
