### ISSUE TITLE
Chat: adding extra text before mention in a message adds extra markup

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8495]
### Description

1. enter @ and mention someone
2. do not send the message yet
3. go to the very beginning in the chat input (before `@`)
4. enter some text here
5. send the message

As result, the message is sent with extra markup

<img width="846" alt="Screenshot 2022-11-29 at 15 03 41" src="https://user-images.githubusercontent.com/82375995/204524305-4b8d50a4-84bc-49f1-9469-9b341957fe1e.png">

**Comment by caybro** [comment]
We had this bug before and I could swear I haven't seen this for a long time

**Comment by anastasiyaig** [comment]
i was able to reproduce it within mentioned steps 3 times out of 3 in RC 5

**Comment by mprakhov** [comment]
Reproduced when we change cursor position by mouse.
Keys.onKeyPressed always returns the previous cursor position
