### ISSUE TITLE
[Community Permissions] Add new switch to enable / disable `Who holds` option

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#8498]
### Description
Add switch to enable / disable `Who holds` option:

![Screenshot 2022-11-29 at 13 45 51](https://user-images.githubusercontent.com/97019400/204532821-f8dfeea4-6cab-4f09-b510-fbafc353f5b0.png)

And, when disabled:
![Screenshot 2022-12-12 at 13 58 21](https://user-images.githubusercontent.com/97019400/207050986-40816dd9-c133-49e9-903e-a6bbe666e30b.png)

And if it is disabled, the `Is allowed to` and `In` sections behavior will be the following:
![Screenshot 2023-01-11 at 10 16 04](https://user-images.githubusercontent.com/97019400/211766157-78860f19-5e1e-4e3b-bdbf-9233b98080c5.png)

The design here: 
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A480020&t=tBWgno87dJA66V1N-0

**Comment by noeliaSD** [comment]
@pedro-et @xAlisher could you provide the design for this component when it is disabled? Thanks!

**Comment by noeliaSD** [comment]
As agreed in the last `Community Permissions` meeting, this feature will be post MVP so we can postpone the development and remove it from `0.10.0` @iurimatias !

**Comment by John-44** [comment]
> As agreed in the last `Community Permissions` meeting, this feature will be post MVP so we can postpone the development and remove it from `0.10.0` @iurimatias !

A small clarification - this feature *is* a must-have for the MVP, but it is only related to channel permissions (not community level permissions) and therefor shouldn't be worked on until community level permissions are implemented, which will hopefully happen with the 0.11 release.  So this item should be moved to the 0.12 milestone.
