### ISSUE TITLE
Import tool: figure out a way to handle bot message authors

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8522]
Part of https://github.com/status-im/status-desktop/issues/12018

Something that has come up while testing the import tool for the final switch.
@iurimatias has imported a channel which in discord looks like this:

![Screenshot from 2022-11-30 16-32-18](https://user-images.githubusercontent.com/445106/204840204-14ca4c87-7441-4426-8c7b-bc3cb57de003.png)

After importing the messages into Status, the message looks like this:

![Screenshot from 2022-11-30 16-33-03](https://user-images.githubusercontent.com/445106/204840395-456aca1d-fe98-4922-b905-0b1b20ecaf68.png)

Here's what the data looks like:

```json
      {
        "id": "SOME_ID"
        "name": "Loud Mountainous Macropod@bridge",
        "discriminator": "0000",
        "nickname": "jakubgs@gitter",
        "color": null,
        "isBot": true,
        "avatarUrl": "https://cdn.discordapp.com/embed/avatars/0.png"
      },
```
We're using the author's `name` property so this should not be causing this. 
However it turns out that there's more message author data with the same `id` that looks like this (in fact, it's the first message of the channel that has this data):

```json
    {
        "id": "SOME_ID",
        "name": "jakubgs@gitter",
        "discriminator": "0000",
        "nickname": "jakubgs@gitter",
        "color": null,
        "isBot": true,
        "avatarUrl": "https://cdn.discordapp.com/avatars/633669913697058816/c367bdc0b5f5593254719b07526e3d93.png?size=512"
      },
```

So what happens here is that, when the import tool runs into the first message, it'll save the author data (where `name` and `nickname` happen to be the same), then later when it runs into the message where the author data has the same ID but different `name`, it will just associate the already stored author data with that message (which is correct cause it's the same author ID).

This is a special case for messages that originate from bots (see `isBot: true`).

We need to handle cases where discord messages can have author data where the ID is the same, but the `name` is different (in which case `isBot: true`).

### Possible solution

During the import, when processing author data, check if `isBot: true` and create a custom author `id` and update the message author id accordingly, such that for every bot message there's a distinct author entry in the database as well.

**Comment by iurimatias** [comment]
moving to 2.39 due to lack of space in the milestone

**Comment by iurimatias** [comment]
descoped for now
