### ISSUE TITLE
Start chat view shows "no results found" when entering chatkey 

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8541]
One way to send a contact request is by trying to start an adhoc chat with a chatkey that isn't a contact yet.
This can be done by entering the chatkey (or even complete status link) in the "Start chat" input:

![Screenshot from 2022-12-01 11-14-01](https://user-images.githubusercontent.com/445106/205026983-5e88fcb5-f6bd-4694-bf98-5ac62ca1bc8d.png)

A contact request modal opens immediately in case Status recognizes the key.

However, notice in the screenshot how there's also a "No results found" popup. This is most likely because of the contact suggestion popup which typically comes into play here.

I think when we enter a chatkey (or status link) we should not show the "No results found" popup, because we know we're trying to chat with someone who isn't a contact yet.

**Comment by PascalPrecht** [comment]
We do. What you don't see in the screenshot is that this actually opens a contact request modal

**Comment by mprakhov** [comment]
@PascalPrecht 
I can't figure out the test scenario. Every time I put the contact key in the contact list - I see `Send contact request `popup (and no `No results found` msg)
Only if I'll decide to put a contact, which is already in my contact list - I'll get no action.

On the screenshot I see contact key and it can already be in you contact list or it can not exist at all

**Comment by PascalPrecht** [comment]
> I can't figure out the test scenario and what the problem is.

@mprakhov putting in the profile link should open the contact request modal (in case it's a profile link of a contact that isn't a contact yet). <-- This works.

However, it will also open that "No results found" menu that's attached to the input. That should not happen, given that we know we've entered a profile link of someone who isn't a contact yet.

> Only if I'll decide to put a contact, which is already in my contact list - I'll get no action.

This seems correct. Although that should probably open the 1-on-1 chat right away. 

> On the screenshot, I see the contact key and it can already be in your contact list or it can not exist at all

It's a profile link of a user that is **not** a contact yet.
