### ISSUE TITLE
UI is distorted after sleep/suspend

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-desktop#8544]
# Bug Report

## Description

After suspending UI gets distorted. Sometimes only user avatars, but sometimes the whole UI. So every time after suspending I have to kill the app and restart it.

![shot](https://user-images.githubusercontent.com/17097240/205058000-967ff97f-177c-4840-aacf-3fd1826af4a5.png)

Related Issue: https://github.com/status-im/status-desktop/issues/7486

### Additional Information

Status desktop version: 0.8.0-rc.5
Operating System: Arch Linux (6.0.10-arch2-1)

**Comment by caybro** [comment]
Let me guess, NVidia gfx card? ;)

**Comment by caybro** [comment]
NVidia drivers are known to have this kind of problems on suspend/resume. We can't really do anything about this :/

**Comment by Parveshdhull** [comment]
> NVidia drivers are known to have this kind of problems on suspend/resume.

Hi, please can you elaborate on this?
I don't face these issues with any other app on my pc.

**Comment by Parveshdhull** [comment]
even on vlc, used is QT app

**Comment by caybro** [comment]
> even on vlc, which is QT app

VLC is not a QtQuick/QML app

**Comment by Parveshdhull** [comment]
> We can't really do anything about this :/

can we force re-render of UI or something?

**Comment by Parveshdhull** [comment]
because this issue is very annoying, have to kill app and restart after every suspend. (which I do alot)
