### ISSUE TITLE
No identicon ring on new profile setup

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8551]
# Bug Report

## Description

<img width="1512" alt="Снимок экрана 2022-12-01 в 23 18 04" src="https://user-images.githubusercontent.com/25482501/205151345-1604c13a-f62e-48ae-ab2a-6f8539943bf3.png">

<img width="1512" alt="Снимок экрана 2022-12-01 в 23 18 12" src="https://user-images.githubusercontent.com/25482501/205151359-d638d389-33fb-44f4-96d6-c8042b0516b3.png">

**Comment by caybro** [comment]
@igor-sirotin actually I _think_ this should have been fixed with (now merged) https://github.com/status-im/status-desktop/pull/8543; can you pls retry in master?

**Comment by anastasiyaig** [comment]
please fix it :D
