### ISSUE TITLE
Communities: It's impossible to join a community with a long description

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8558]
# Bug Report

## Description
1. Create a community with a long description
2. Post the public link to the community in the test chat

#### Expected behavior
The button for joining is shown 
#### Actual behavior
The button for joining is not shown
<img width="493" alt="image" src="https://user-images.githubusercontent.com/14942081/205186539-e3b9c6e5-fad5-40ba-9a75-9e5b5831ae90.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.9
Operating System: macOS Monterey

**Comment by caybro** [comment]
@iurimatias should be fixed with https://github.com/status-im/status-desktop/pull/8502; can you pls try to test that PR @elina2015 ?

**Comment by elina2015** [comment]
> @iurimatias should be fixed with #8502; can you pls try to test that PR @elina2015 ?

Thank you, @caybro , I will check now.

**Comment by jrainville** [comment]
Closing as fixed. Reopen if you can reproduce in master
