### ISSUE TITLE
Chat: The community's owner icon is shown not complete

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8561]
# Bug Report

## Steps to reproduce
1. Open the app, open a community with the member's list shown
2. Make the size of the app's window as small as possible

#### Expected behavior
The icon is shown completely
#### Actual behavior
The right edge of the icon is not shown
<img width="451" alt="image" src="https://user-images.githubusercontent.com/14942081/205189270-a474b748-7a8d-42b4-8b93-1db3d17e82c2.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.9
Operating System: macOS Monterey

**Comment by caybro** [comment]
It's pretty clear we need do increase the minimum app's window size; there are other such deficiencies, mainly in Settings

**Comment by iurimatias** [comment]
this has been fixed in the meanwhile
