### ISSUE TITLE
Chat: the message 'No results found' is going outside of the app

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8562]
# Bug Report

## Steps to reproduce
1. Go to create a new chat
2. In the field 'To:' enter some long text
3. Check the position of appeared 'No results found'

#### Expected behavior
The message 'No results found' is NOT going outside of the app
#### Actual behavior
The message 'No results found' is going outside of the app
<img width="720" alt="image" src="https://user-images.githubusercontent.com/14942081/205189650-a844a383-2b58-420f-8de9-962413a3b6fb.png">

### Additional Information
Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.9
Operating System: macOS Monterey

**Comment by iurimatias** [comment]
this has been fixed
