### ISSUE TITLE
Cannot see/read a message if it's hovered

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#8567]
If a long message is not the first, but the second one sent in a row and if I am hovering it I am not able to read it because of quick actions menu displayed on the right. 

In that case we should move the menu a bit up, the same as we do if the message is the first one.

Example: on the image below I cannot see text which is under red rectangle on the right. 

![reading-msg-issue](https://user-images.githubusercontent.com/86303051/205262073-cd17adb2-06a4-43eb-99db-42de0f08aa5f.png)

**Comment by iurimatias** [comment]
this has been fixed
