### ISSUE TITLE
Error in "Finalise Status Password Creation"

### ISSUE THREAD

**Issue by AlbertoSoutullo** [status-im/status-desktop#8574]
# Bug Report

When installing Status Desktop, a "Login failed" error pops up once reaching "Finalise Status Password Creation" part.

## Description

I am trying to create a new account, but can not confirm the password.

## Steps to reproduce

Step1. Open installer `StatusIm-Desktop-v0.8.0-7be712` on `Microsoft Windows 11 Pro, 10.0.22621 Build 22621`.

Step2. Click `OK` as English is fine as default language.

![Step_2](https://user-images.githubusercontent.com/23367096/205275740-de1041a6-6719-4dc4-9481-61ce0f777e92.png)

Step3. Click `Browse` and change hard drive to D, click `next`:

![Step_3](https://user-images.githubusercontent.com/23367096/205272730-294b52f3-4a6a-4d31-8453-f54226f7cf53.png)

Step4. Click `Next` on Start Menu Folder:

![Step_4](https://user-images.githubusercontent.com/23367096/205272980-06754966-b83d-4736-94ad-3d01c19ccbf6.png)

Step5. Click `Next` on Select Aditional Tasks:

![Step_5](https://user-images.githubusercontent.com/23367096/205273144-6eb7875c-e13d-4623-93d8-9bfe818bfe0c.png)

Step6. Click `Install` on Ready to Install:

![Step_6](https://user-images.githubusercontent.com/23367096/205273291-12ec20ed-d0be-4ebd-a92d-935e7a6eec6c.png)

Step7. Click `Finish` with default checkbox Launch Status selected and wait Status Desktop to run.

![Step_7](https://user-images.githubusercontent.com/23367096/205273503-6b0c9bb4-93f0-4ba5-a144-1e6cb35d8b35.png)

Step8. Mark both checkboxes in "Before you get started..." and click `Get Started`.

![Step_8](https://user-images.githubusercontent.com/23367096/205273959-f93b0c83-a6d0-446b-a4d2-bbff7590a685.png)

Step9. Click on `I am new to Status`.

![Step_9](https://user-images.githubusercontent.com/23367096/205274143-de3feacb-38fa-43b4-92e1-10e194ab3b78.png)

Step10. Click on `Generate new keys`

![Step_10](https://user-images.githubusercontent.com/23367096/205274282-132ce3ff-5c88-4d2e-92a7-6c02f6994414.png)

Step11. Set my name and put my picture, then click on `Next`.

![Step_11](https://user-images.githubusercontent.com/23367096/205274462-bd93cccb-8d88-4b2b-8f1c-33822189441f.png)

Step12. Click on `Next`.

![Step_12](https://user-images.githubusercontent.com/23367096/205274587-3e4e97d4-ee7c-47aa-9c07-e04de2110958.png)

Step13. Generate a password with my password manager (Bitwarden), click on button "Copy Password", and set that password in Status Desktop with ctrl+v. This password is length 18 characters, it has Upper and Lower case letters, Numbers and Symbols. Click on `Create Password`.

![Step_13](https://user-images.githubusercontent.com/23367096/205274939-19fb0bac-f501-466c-9567-d3994e0fa63a.png)

Step14. Paste the password again with ctrl+v. *Somehow the clipboard is empty*. Have to copy again the password. Then click on `Finalise Status Password Creation`. The error pops up.

![Step_14](https://user-images.githubusercontent.com/23367096/205275483-45446a40-821b-456c-b9ae-ceb81d6e533f.png)

Now if I click on ok and I click again on `Finalise Status Password Creation`, nothing happens.

#### Expected behavior

Going to the next step in the set up phase.

#### Actual behavior

Error. Can not continue.

### Additional Information

- Status desktop version: StatusIm-Desktop-v0.8.0-7be712
- Operating System: Microsoft Windows 11 Pro, 10.0.22621 Build 22621

**Comment by jrainville** [comment]
The problem was that the Waku port was already in use.

Status wasn't already opened (no zombies), so we're not sure what was clashing. Might have been a sad accident.

Anyway, by setting the `WAKUV2_PORT` env var, we were able to remediate the issue.
