### ISSUE TITLE
Editing a message with a code block loses information about the code block

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8576]
## Steps to reproduce

1) Author a message with a code block. For example:

  --- Status message: ---

  Here is a code block:

  \```
  proc main = 
  &nbsp; &nbsp; echo "hello world"
  \```

--- Status message end ---

2) Click "Edit" on the message

3) Notice how the code block is flattened not a single line, not containing any of the backtick characters.

#### Expected behavior

I expect the Edit operation to allow me to tweak the original input text of the message, containing the backtick characters exactly as I entered them before sending it in step 1). This makes it easy to introduce small tweaks to the message.

### Additional Information

Status Desktop 0.8 on macOS

**Comment by caybro** [comment]
I think the edit operation discards _any_ markup we currently have :/

**Comment by alexandraB99** [comment]
closing as duplicate https://github.com/status-im/status-desktop/issues/7804
