### ISSUE TITLE
AC: contact requests not grouped correctly

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8585]
# Bug Report

## Description

These 2 contact requests came on the same day and they had been grouped together under a single "Today" header until I've accepted them

![image](https://user-images.githubusercontent.com/5377645/205307584-8b4e1b55-884d-4f17-9df4-9a88a241cf1e.png)

### Additional Information

- Status desktop version: master (post 0.8)
- Operating System: linux

**Comment by MishkaRogachev** [comment]
Can be solved here: https://github.com/status-im/status-desktop/issues/8510

**Comment by MishkaRogachev** [comment]
@caybro that supposed to be fixed
