### ISSUE TITLE
AC: profile image change not reflected

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8586]
# Bug Report

## Description

For some time during one day, I haven't had a profile image (I unset it temporarily); however I think the Activity Center should always reflect the last known state and display the image nevertheless, even for older notifications:

![image](https://user-images.githubusercontent.com/5377645/205308035-ae43d691-40e2-4f6b-bb60-06647b3b86bc.png)

### Additional Information

- Status desktop version: master (post 0.8)
- Operating System: linux

**Comment by MishkaRogachev** [comment]
waiting for https://github.com/status-im/status-desktop/pull/8246 merged
