### ISSUE TITLE
No Back Button Navigation from "Keycard is Empty" Error Screen

### ISSUE THREAD

**Issue by jessiebroke** [status-im/status-desktop#8596]
# Bug Report

## Description

Tried to use my Keycard to login (at my own risk, I am aware) and there is no back button after failure to key pair from Keycard.

## Steps to reproduce

Step 1. Open Status Desktop App v0.8.0
Step 2. Go through "Before you get started..." and check both checkboxes acknowledging Beta status and Privacy Policy and click "Get Started"
Step 3. Click "I already use Status"
Step 4. Click "Login with Keycard" after inserting Keycard into card reader connected to computer via USB 2.0
Step 5. Profit w/ "Keycard is empty" screen with no way to go back to previous menu options

#### Expected behavior
Back navigation button exists to take you back to previous menu options

#### Actual behavior
No back navigation button exists

### Additional Information

- Status desktop version: v0.8.0
- Operating System: Windows 10

Actual behavior screenshot below:
![image](https://user-images.githubusercontent.com/18238304/205332954-8359348f-ed36-4879-b9a7-61fe8e384316.png)

**Comment by glitchminer** [comment]
Hi @alaibe, this was moved to QA earlier, please can you link a PR or specify a version with the fix?

**Comment by saledjenic** [comment]
@glitchminer this is an outdated issue, I am not sure which PR exactly fixed this, most likely fixed via some other issue.

We just need you to verify this and close with "not reproducible any more" comment.

**Comment by glitchminer** [comment]
> @glitchminer this is an outdated issue, I am not sure which PR exactly fixed this, most likely fixed via some other issue.
> 
> We just need you to verify this and close with "not reproducible any more" comment.

This appears to be resolved in the current RC (0.10 rc7). A back button is now available to return to the previous screens. Setting to closed.

![image](https://user-images.githubusercontent.com/50769329/218832134-cad769c8-f96a-4c85-bfb6-ed878e4da8b1.png)
