### ISSUE TITLE
No UI alert when failing to rps limit is reached

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8597]
# Bug Report

The following report is mostly about ENS getting process.
But this also applies to getting wallet balance, e.g.

## Description

There's infura limit on RPS, but UI doesn't reflect this in anyway.
I can see the following error in logs, but no reaction from UI. 

`
ERR 2022-12-02 19:12:31.081+03:00 error doing rpc request                    topics="rpc" tid=7899216 file=core.nim:33 methodName=ens_ownerOf exception="\nstatus-go error [methodName:ens_ownerOf, code:-32000, message:429 Too Many Requests: {\"jsonrpc\":\"2.0\",\"id\":63,\"error\":{\"code\":-32005,\"message\":\"daily request count exceeded, request rate limited\",\"data\":{\"rate\":{\"allowed_rps\":1,\"backoff_seconds\":30,\"current_rps\":224},\"see\":\"https://infura.io/dashboard\"}}} ]\n"
`

## Steps to reproduce

1. Open Settings
2. Go to "ENS Usernames"
3. input some name, wait for UI response
4. repeat clause 3 until the error occurs in the logs
5. Note no alert in UI

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/25482501/205339482-ac2cd8f1-ae17-4144-9285-2a0a013ef741.png">

#### Expected behavior

Some UI alert/text/notification/reaction would be great.

Some loading animation would also be great.

#### Actual behavior

Nothing in UI 🙁

**Comment by John-44** [comment]
@Khushboo-dev-cpp thanks for tagging me, yes this does need a bit of design work, we will get on to this on Monday :-)

**Comment by Khushboo-dev-cpp** [comment]
@alaibe @igor-sirotin please not we've confirmed with John that this entire feature needs redesign but is not in priority right now, so if basic functionality works, its enough till this is redesigned. This can be moved out and pushed back in terms of priority.

**Comment by igor-sirotin** [comment]
@Khushboo-dev-cpp, I'm ok with that 🙂

**Comment by Khushboo-dev-cpp** [comment]
we need to de prioritise this task as per the discussion above
