### ISSUE TITLE
Update wallet navigation

### ISSUE THREAD

**Issue by mariocnovoa** [status-im/status-desktop#8598]
### Description
Update the position of "Saved addresses" as an additional navigation element.
Also update the position of the new wallet button now at the top, next to the title.

Add icon next to account when watch account or keycard

**Link to Figma**
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=3014%3A155152&t=6vJfxncv0mo8YA4B-1

**Comment by alaibe** [comment]
The eye is for watch only account type
The key is for kecard account

The users: don't know
