### ISSUE TITLE
group is not highlighted in a community, when there is new message in one of the chats in the group

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8604]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/11790366/205452039-24e8fe83-916a-4a1d-b922-6ab254635d62.png">

whatever should be highlighted

**Comment by stefandunca** [comment]
On the same note, if the group is collapsed and the user is viewing a channel inside the group, the corresponding group is not highlighted and the user has to remember/search which group contains the selected channel

![cant_see_group](https://user-images.githubusercontent.com/47554641/205947498-60f1bd94-0260-47bc-80b7-a1ede3494d7a.png)

**Comment by jrainville** [comment]
I'll ask for actual designs, but in the meantime, we can just make the category name bold when there are unread messages in it
