### ISSUE TITLE
The Touch ID login flow always requires me to enter a password

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8605]
I have enabled "Login trough Touch ID" on my mac. When I start the client, it correctly launches the Touch ID login prompt, but placing my finger on the sensor produces no effect. I'm still able to click on the "Use password" button within the Touch ID dialog to login successfully. I have no troubles using Touch ID in other apps.

**Comment by mprakhov** [comment]
@zah is it still actual for you on the latest rc or master build?

**Comment by mprakhov** [comment]
Closing as non-reproducible.
I did not see any TouchID issues.
There could be additional keychain requests, but they will be done only:
1. You do use not official Status build/app
2. Official build - first login after installation (mark it as "Allow always" to skip keychain access request)
