### ISSUE TITLE
Wallet balance is empty from Turkey (works with Estonia VPN) [http: server gave HTTP response to HTTPS client]

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8610]
# Bug Report

## Description

When I start Status app and open wallet, the balance is not loaded.
There's a bunch of `http: server gave HTTP response to HTTPS client` errors in log.

And there's also no UI alert/reaction to this 🙁 
Same as for https://github.com/status-im/status-desktop/issues/8597

<details>
<summary>
Log errors
</summary>
<pre>
<code class="language-javascript">
DBG 2022-12-05 11:12:01.909+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.107+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.107+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.108+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.110+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.187+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.187+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.188+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.199+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.277+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.278+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.279+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.280+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.367+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.368+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.369+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.376+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.454+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.454+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.455+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.456+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.537+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.539+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.539+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.548+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.661+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.662+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.663+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.664+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.773+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.775+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.775+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.782+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.862+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.862+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.863+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=ETH&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
DBG 2022-12-05 11:12:02.864+03:00 NewBE_callPrivateRPC                       topics="rpc" tid=10201049 file=core.nim:20 rpc_method=wallet_fetchPrices
ERR 2022-12-05 11:12:02.944+03:00 rpc response error                         topics="rpc" tid=10201049 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.944+03:00 error doing rpc request                    topics="rpc" tid=10201049 file=core.nim:33 methodName=wallet_fetchPrices exception="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
ERR 2022-12-05 11:12:02.945+03:00 error:                                     topics="wallet-account-service" tid=10201049 file=service.nim:169 errDesription="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=SNT&tsyms=usd&extraParams=Status.im\": http: server gave HTTP response to HTTPS client ]\n"
</code>
</pre>
</details>

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/25482501/205586873-2d031363-9061-43e4-b4ef-c0be0d45e8ba.png">

After restarting the app with Estonia VPN connected the balances are loaded with no problem:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/25482501/205587100-bb38f69e-a262-4ca2-8c8f-fd204ddf1a4e.png">

### Additional Information

- Status desktop version:
- Operating System:

**Comment by alaibe** [comment]
@igor-sirotin could u verify that u have no problem connecting to infura API?

**Comment by anastasiyaig** [comment]
@igor-sirotin i doubt we have it related to the app itself. Please check it with Infura api as @alaibe suggested
