### ISSUE TITLE
Twitter handle field emptied upon saving

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8614]
# Bug Report

## Description

On the Profile page. I entered a text for Bio and then a twitter a twitter handle. When I clicked "save" the bio text remained but the twitter handle did not.

## Steps to reproduce

Go to profile.

Enter Bio
Enter twitter handle (one word)
Click "save changes"

#### Expected behavior

Twitter handle field contains entered value

#### Actual behavior

Twitter handle field is emptied

### Additional Information

- Status desktop version: 0.8.0
- Operating System: Linux Fedora

![image](https://user-images.githubusercontent.com/110212804/205625629-18fd8e95-ae7c-416d-b979-2ac280b4bf09.png)

**Comment by caybro** [comment]
Already working on this as part of https://github.com/status-im/status-desktop/issues/7918
