### ISSUE TITLE
The "switch to chat" dialog launched with Command+K should offer fuzzy matching

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8616]
The current dialog requires an exact case-sensitive substring matching which is too inconvenient to use.

At a bare minimum, the matching should be done in case-insensitive fashion, but competing products such as Discord and Slack offer even fuzzier matching where for example typing "jms" will successfully match for a contact named "James".

**Comment by jrainville** [comment]
duplicate of https://github.com/status-im/status-desktop/issues/8460

**Comment by zah** [comment]
@jrainville, I could argue that my suggestion here is about supporting fuzzy matching while the other issue is focusing only on case insensitivity.

**Comment by zah** [comment]
Done:
https://status-desktop.featureupvote.com/suggestions/347077/switch-to-chat-cmdk-should-offer-fuzzy-matching
