### ISSUE TITLE
fix: Key text field does not work in 0.8.0 Linux

### ISSUE THREAD

**Issue by kaiserd** [status-im/status-desktop#8619]
### Version

Linux AppImage 0.8.0, downloaded [here](https://github.com/status-im/status-desktop/releases/tag/0.8.0).

### Issue

Entering a key like so
![status_error](https://user-images.githubusercontent.com/1684595/205629282-927817e7-78c5-4b87-968e-a21754d5a004.jpg)

does not show the expected contact request dialog.

Pressing enter yields: `qrc:/app/AppLayouts/Chat/views/MembersSelectorView.qml:25: TypeError: Cannot read property '_pubKey' of null`

**Comment by PascalPrecht** [comment]
I personally have trouble reproducing this in 0.8.0 and in latest master.
Can anyone reproduce this?

**Comment by caybro** [comment]
It doesn't work for me but in a slightly different way; I see "No results found" for a split second and then both the input field and view resets to initial state. Console warning:

```
Warning: <Unknown File>: localNickname is undefined. Adding an object with a undefined member does not create a role for it. (:4294967295, )
```

**Comment by PascalPrecht** [comment]
@caybro ah, that was reported in https://github.com/status-im/status-desktop/issues/8591

**Comment by caybro** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/8659
