### ISSUE TITLE
Default browser is in app

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8627]
# Bug Report

## Description

By default, links are opened in the in app browser instead of system one

https://discord.com/channels/624205794384281629/624205794384281631/1048170960580263967

## Steps to reproduce

Check settings

#### Expected behavior

In app browser "isn't ready" so default setting should be using system browsee

### Additional Information

- Status desktop version: 0.8.0
- Operating System: linux fedora

**Comment by PascalPrecht** [comment]
@caybro haven't you recently introduced a change that ignores the status browser?

**Comment by caybro** [comment]
@PascalPrecht yes that would be https://github.com/status-im/status-desktop/pull/8579 but it hasn't made it into 0.8 release :/ still needs to be backported to the 0.8 branch (if we ever release an 0.8.1)

**Comment by PascalPrecht** [comment]
Well, good to know and having it tracked here so we can potentially close this issue once the next release is out.

**Comment by jrainville** [comment]
I'll still close it, since it was fixed in master. Otherwise, tracking what is still an issue is harder
