### ISSUE TITLE
Import tool: track which archives have been imported after download

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8628]
There's an issue that will become more apparent the more users run the archive protocol with lots of data.
From a community member perspective the archive protocol works as follows:

1. Member node receives magnet link message from owner node
2. Member node parses magnet link into torrent metadata and tries to fetch torrent info
3. Once torrent info has been received, member node determines which archives to download based on archive hashes
3.1. It will only download archives that aren't tracked as already downloaded
4. Once download of all missing archives is done, it will extract messages from archives and import them into the database

Step 3) and 4) can take a while and there's a chance users will close the app while this is in progress.
For 3) this is not to critical. The next time a magnet link message is received, the member node will again check which archives to download based on the hashes and then import the messages afterwards.

There's a problem though if 3) was finished, but 4) was not. We're then in a state of downloaded archives that are not imported into the database and also won't be anymore because they are marked as downloaded.

To account for that, we should also check if an archive has finished importing into the database and if it hasn't, messages should be picked up in the next cycle.

**Comment by 0x-r4bbit** [comment]
This will be addressed in: https://github.com/status-im/status-go/pull/3012

**Comment by caybro** [comment]
Just wondering, is it still feasible to initiate 4) (ie the import part) post-mortem?

**Comment by 0x-r4bbit** [comment]
Not sure what you mean. 
If you're referring to the memory inefficiency we're running into atm, that's still a thing to address.

But import of data has to happen regardless.

**Comment by caybro** [comment]
No, I mean fixing this retroactively for existing users (like me) who are already in this failed/limbo state

**Comment by 0x-r4bbit** [comment]
That's what I'm aiming to do with https://github.com/status-im/status-go/pull/3012
In there is a migration that introduces a new field in the database table that tracks which archives have been imported (not just downloaded).

In your case, most likely all archives will be marked as downloaded, but not all will be marked as imported.

To ensure we don't leave stuff out, the migration will set all archive markers to "not imported".
So the next time the archive protocol kicks in, it will extract the messages from the archive data again and import them into the database (even if some were already in there)

**Comment by caybro** [comment]
> To ensure we don't leave stuff out, the migration will set all archive markers to "not imported".
> So the next time the archive protocol kicks in, it will extract the messages from the archive data again and import them into the database (even if some were already in there)

Great to hear! Thanks for all the effort you're putting into this

**Comment by 0x-r4bbit** [comment]
This has landed
