### ISSUE TITLE
An incoming message sent in a community channel was delivered with more than 30 minutes of delay

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8629]
# Bug Report

## Description

For more than 30 minutes, the history of the #dogfooding channel appeared to be the following for me:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/175462/205632397-35d1a010-f2e1-45b1-ab40-6e2e51c2b023.png">

Then, without an apparent reason, the history changed to the following (full?) message log:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/175462/205640351-89196404-2d96-4e58-89de-8bb748141bd5.png">

### Additional Information

- Status desktop version: Status Desktop 0.8
- Operating System: macOS

**Comment by zah** [comment]
A similar report from another user, not seeing messages sent by me (I was chatting with Iuri in the conversation below):

![image](https://user-images.githubusercontent.com/175462/205660507-04ceafee-66ba-43e3-aa57-c46d183033e2.png)

**Comment by PascalPrecht** [comment]
This looks like some messages were delivered later (by store nodes?)
