### ISSUE TITLE
The suggestion to enable link previews in chats is displayed even when the option is already enabled

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8631]
# Bug Report

## Steps to reproduce

1) Navigate to the application settings and enable "Display Message Link Previews" on a fresh Status Desktop installation.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/175462/205652277-fb046e2f-bd4d-4bd4-8243-5a9b42acf568.png">

2) Restart Status and observe that the widget, suggesting that link previews should be enabled is still displayed in the chats:

<img width="921" alt="image" src="https://user-images.githubusercontent.com/175462/205652123-48f28737-bab8-4ce4-bd20-b4bf31dfe16c.png">

3) Clicking "Don't display this message again" is enough to resolve the issue (the widget is no longer displayed after a restart).

#### Expected behavior

As a  user, I find it surprising that the app is suggesting that I should do something that I've already done. I expect the widget to go away as soon as I enable the suggested setting.

### Additional Information

- Status desktop version: Status 0.8
- Operating System: macOS

**Comment by jrainville** [comment]
@zah in your screenshot, we only see Status and Youtube being enabled. Was Github also enbaled?

**Comment by mprakhov** [comment]
Checked on the latest master build `784b9acd4f73e47e0403a1b6240369b34ec1840b`, and everything works as expected.
Closing as non-reproducible
