### ISSUE TITLE
The Number of community members is not dynamically updated

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8632]
# Bug Report

## Steps to reproduce

1. Create a new community and send out invites to a bunch of users.
2. Observe the number of community members slowly increasing as people accept your invite.
3. Restart the client and observe the number of members rapidly increasing once the client has loaded the community again.

#### Expected behavior

I expect all community joiners to be tracked in real time, without having to restart the client.

### Additional Information

- Status desktop version: Status Desktop 0.8
- Operating System: macOS

**Comment by PascalPrecht** [comment]
Alright, so just to add some color to this, what's actually happening behind the scenes is that a community owner really only shares a link to a community (there's no such thing as an invite, even though it might look like it).

Anyone who has that link can then request access to that community. This request has to be initiated by whoever wants to join that community. Also, every such request has to be accepted by the owner (this either happens automatically when the owner node is online, or manually, via approval of owner. Depends on the community configuration).

So if you see a slow increase in member count, then after restart a faster increase, it really means that your node has received all the other requests after restart (but should've probably received/processed them earlier, but that really depends on when a request to join was sent by a future member of the community)
