### ISSUE TITLE
Community invite is overlapping with the next messages

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#8634]
The invite box is overlapping with messages which makes clicking for the link very hard
 
![Untitled](https://user-images.githubusercontent.com/47554641/205662144-83101ade-e6ae-4245-8455-69a3af8e1b60.png)

## Steps to reproduce

Receive a community invite and a message afterwards

#### Expected behavior

User can clock on the join community link

#### Actual behavior

The join community link is obscured by the next message

### Additional Information

- Status desktop version: 0.8.0
- Operating System: macOS

**Comment by caybro** [comment]
Already fixed in master with https://github.com/status-im/status-desktop/pull/8502; didn't make it into 0.8 and not cherry-picked/backported yet (if we ever release an 0.8.1 :/ cc @iurimatias
