### ISSUE TITLE
Mouse click seems to stay attached to individual chat list item

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8636]
This is something that was already reported somewhere but I can't seem to find the issue. Feel free to close this one if the other one shows up again.

Alright so here's the problem:

When there's a community with many channels (so, a long list of items in the chat list), or, in the chat view, when there's many 1-on-1 chats (or group chats), it happens that, when I click an item of that list, the clickhandler seems to somehow stay attached to that item.

The result of that is that when I keep moving my mouse/cursor, the list drags along with it (as if I did something like a press-and-hold).
This make scrolling through a long list of chats and channels very very hard.

The member list of a community does not seem to have this problem...

Additional info:
OS: Ubuntu
Devices: Touchpad + Mouse

**Comment by 0x-r4bbit** [comment]
@noeliaSD @caybro didn't any of you run into this as well?

@alexandraB99 I'd be cool if this one could get some priority as it makes using Status really hard.

**Comment by caybro** [comment]
@0x-r4bbit never happened to me... so I can only speculate about the reasons. The user list doesn't have this DND feature to reorder the items so I _think_ it could be that (under certain conditions, like high load), the MouseArea grabs the mouse and never releases it

**Comment by 0x-r4bbit** [comment]
@caybro do you recommend anything for me to quickly verify if that causes the issue?

**Comment by caybro** [comment]
StatusChatList.qml:
```qml
DropArea {
    id: dropArea
    width: dragSensor.active ? 0 : parent.width
    height: dragSensor.active ? 0 : parent.height
    keys: ["chat-item-category-" + statusChatListItem.categoryId]
    onEntered: reorderDelay.start()
    Timer {
        id: reorderDelay
        interval: 100
        repeat: false
        onTriggered: {
            if (dropArea.containsDrag) {
                d.destinationPosition = delegateModel.model.get(draggable.DelegateModel.itemsIndex).position
                delegateModel.items.move(dropArea.drag.source.DelegateModel.itemsIndex, draggable.DelegateModel.itemsIndex)
            }
        }
    }
}
```

I'd try commenting it out completely... that Timer there sounds fishy...

**Comment by 0x-r4bbit** [comment]
Alright, so I've removed the `DropArea` in both `StatusChatList` and `StatusChatListAndCategories`.
I've also removed all `Drag` properties from the `MouseArea` that attaches them to a `StatusChatListItem`.

The issue still persists..

**Comment by 0x-r4bbit** [comment]
No this is something I've experienced a long time ago as well, even on macOS. So I'm surprised no one else is running into this...

**Comment by 0x-r4bbit** [comment]
This happens for the chatlog as well btw. When clicking on a message, the mouse click seems to "stick" to a message

**Comment by 0x-r4bbit** [comment]
I can no longer reproduce this. This has stopped occuring at some point without changing the app version.
Now I've also updated to 8.1 and there's no such issue atm.

Will close this for now.

**Comment by 0x-r4bbit** [comment]
Reopening this as @iurimatias now runs into this

**Comment by 0x-r4bbit** [comment]
This happened to me again. After restarting my machine, this was gone (so far)

**Comment by 0x-r4bbit** [comment]
This is happening to me more often in the latest release (0.10.0-rc.7)

**Comment by iurimatias** [comment]
clsoing due to new work on the drag & drop sorting. we should re-open if it happens again
