### ISSUE TITLE
[StatusChatInput] Navigate to the beginning and end of the message using the arrow keys on the keyboard

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8637]
When I'm authoring or editing a message, I'm able to use the UP and DOWN arrow keys on my keyboard to move to the previous or the next line in the word-wrapped text. When I'm already at the top-most line (but in the middle of it), I expect that pressing the UP arrow again will position my cursor at the beginning of the message (thus, pressing UP multiple times in succession is a convenient way to simulate the behavior of the HOME button on keyboards lacking a dedicated HOME button). The same is true for the DOWN arrow which can be used to produce the effect of a dedicated END button.

This convenient behavior is currently not present in Status Desktop (version 0.8 on macOS)

**Comment by caybro** [comment]
I'd argue this is clearly a bug :)

**Comment by alexandraB99** [comment]
@benjthayer could you give some input on if such behavior is needed here?

**Comment by benjthayer** [comment]
@alexandraB99 the functionality described by @zah is fairly common across messaging apps including Discord and WhatsApp so it would be great to support if we can.

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
