### ISSUE TITLE
Upgrade QT to 5.15

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8642]
### Description

We currently use QT 5.14

5.15 doesn't have breaking changes and yet fixes a couple of issues we've had. Also, it adds new features.

The task is to upgrade the CI, upgrade imports if needed, fix warnings about deprecated stuff and any other changes needed for 5.15 to be usable in builds and locally (without having a ton of warnings in the logs).

See this old PR for inspiration https://github.com/status-im/status-desktop/pull/2712

**Comment by caybro** [comment]
YES!!!

**Comment by jrainville** [comment]
I like the enthusiasm. It will for sure be in 0.10.0
If my team has bandwidth, we'll pick it up for 0.9.0, but feel free to do it beforehand if you guys have the time. (I have Iuri's approval for whichever milestone, as long as we complete the current 0.9 tasks)

**Comment by jakubgs** [comment]
Squish license and runner server upgrade to 7.1 issue is on-hold until the Qt upgrade to 5.15 is in effect to avoid doubling work:

* https://github.com/status-im/infra-ci/issues/70
