### ISSUE TITLE
Chat: pasting and removing image results in error message

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8644]
# Bug Report

![image](https://user-images.githubusercontent.com/5377645/205735238-d75db166-9451-4bca-ba68-de640852c6a2.png)

## Steps to reproduce

1. copy an image to clipboard
2. paste it using Ctrl+V
3. hover over its "close" button to remove it
4. error msg appears which cannot be gotten rid of

- Status desktop version: master
- Operating System: linux

**Comment by caybro** [comment]
cc @PascalPrecht: should probably re-trigger validation also when we remove images

**Comment by 0x-r4bbit** [comment]
Thank you for reporting this.
I'll  get back to it once I have some spare cycles

Otherwise, feel free to assign this in UI team

**Comment by 0x-r4bbit** [comment]
I can no longer reproduce this in latest master
