### ISSUE TITLE
Emoji completion not present in contact request text box

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8648]
# Bug Report

## Description

The emoji auto-completion `:abc` is not present in the contact request text box

## Steps to reproduce

- Select contact
- Click "send contact request"
- In the text field, type `:`

#### Expected behavior

- Emoji completion drop list appears

#### Actual behavior

- No drop list

![image](https://user-images.githubusercontent.com/110212804/205776388-036a4a8f-5cc6-429f-95ee-1c25e45a6642.png)

### Additional Information

- Status desktop version: 0.8.0
- Operating System: Fedora Linux

**Comment by jrainville** [comment]
This is a feature request, like Lukas showed by changing the labels.
Can you open it as a suggestion in https://status-desktop.featureupvote.com/ ?
The reason why is that we never supported any markup in that field. It would require a new feature.
Closing for now to see if enough people upvote it
