### ISSUE TITLE
Code block formatting in input field hurts my eyes in Dark mode

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8649]
# Bug Report

## Description

I have sensitive eyes :)

The block format in the input field is not great as it's white on grey so not readable.
It's fine once the message is sent.

## Steps to reproduce

- Set dark mode
- Type `backtick something`

#### Expected behavior

- Easy to read

#### Actual behavior

- Can't see nothing

### Additional Information

![image](https://user-images.githubusercontent.com/110212804/205776908-2eedd6b4-287c-4599-99a5-7adc4ad77f96.png)

- Status desktop version: 0.8.0
- Operating System: Fedora Linux

**Comment by caybro** [comment]
Need some design input here @benjthayer @John-44, thx :)

**Comment by benjthayer** [comment]
@caybro I can take a look at this. The light theme treatment in the input isn't great either. Out of interest, are you able to use opacities for the block fill colour?

**Comment by caybro** [comment]
> @caybro I can take a look at this. The light theme treatment in the input isn't great either. Out of interest, are you able to use opacities for the block fill colour?

Sure :)

**Comment by benjthayer** [comment]
Hi @caybro it looks as if the wash used for code block formatting just hasn't been implemented to be inline with the designs.

Both light and dark theme input and message feed washes are outlined in the Kuba file here:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=232%3A73047&t=NlFVcmmDVed1ts2O-4

These colours are much more usable and inline with the design so I think we will be fine if we follow these.

The only thing we need to ensure is that the wash of the code snippet is visible on hover. If easy enough to do, perhaps we can implement the Kuba colours and see how well differentiated the code block wash is from the hover wash and tweak values from there if needed.

<img width="1440" alt="Compact mode-4" src="https://user-images.githubusercontent.com/110033914/207280761-e813e6fa-535d-4c3a-a956-4c0d0a8a5773.png">
<img width="1440" alt="Compact mode-5" src="https://user-images.githubusercontent.com/110033914/207280769-a5894066-92fa-4de4-914c-ef979514c4d6.png">

<img width="1440" alt="Compact mode-2" src="https://user-images.githubusercontent.com/110033914/207280841-42871b9d-cbc7-4c34-b5cb-025c38c5b82b.png">
<img width="1440" alt="Compact mode-3" src="https://user-images.githubusercontent.com/110033914/207280845-acb77a14-cb16-4577-90e8-dcd58ec4cf56.png">

**Comment by caybro** [comment]
> Hi @caybro it looks as if the wash used for code block formatting just hasn't been implemented to be inline with the designs.
> 
> Both light and dark theme input and message feed washes are outlined in the Kuba file here: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=232%3A73047&t=NlFVcmmDVed1ts2O-4
> 
> These colours are much more usable and inline with the design so I think we will be fine if we follow these.
> 
> The only thing we need to ensure is that the wash of the code snippet is visible on hover. If easy enough to do, perhaps we can implement the Kuba colours and see how well differentiated the code block wash is from the hover wash and tweak values from there if needed.
> 
> <img alt="Compact mode-4" width="1440" src="https://user-images.githubusercontent.com/110033914/207280761-e813e6fa-535d-4c3a-a956-4c0d0a8a5773.png">
> 
> <img alt="Compact mode-5" width="1440" src="https://user-images.githubusercontent.com/110033914/207280769-a5894066-92fa-4de4-914c-ef979514c4d6.png">
> 
> <img alt="Compact mode-2" width="1440" src="https://user-images.githubusercontent.com/110033914/207280841-42871b9d-cbc7-4c34-b5cb-025c38c5b82b.png">
> 
> <img alt="Compact mode-3" width="1440" src="https://user-images.githubusercontent.com/110033914/207280845-acb77a14-cb16-4577-90e8-dcd58ec4cf56.png">

Hi @benjthayer, thanks for the feedback! Although we don't implement full syntax highlighting, the colors mentioned there ^^ even for simple backticks (`) will definitely improve the situation.
