### ISSUE TITLE
categories state are not persistent between login sessions 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8650]
categories state (opened/closed) should be persistent between login sessions

**Comment by anastasiyaig** [comment]
there is a feature request for this , please vote https://status-desktop.featureupvote.com/suggestions/346661/keep-categories-closed-on-restart-and-just-show-channels-that-have-new-messages

also, please be wise when marking tickets with labels, not everything is bug :)

**Comment by flexsurfer** [comment]
hey @anastasiyaig thanks, this is the bug, because we should have this functionality, and its different from feature request

**Comment by anastasiyaig** [comment]
@flexsurfer it was never implemented and bug is a definition of something that was working and stopped working. We never had it

**Comment by flexsurfer** [comment]
ok. cool, thanks
