### ISSUE TITLE
I cannot backup my seed phrase after setting up a new account, new install of Status App

### ISSUE THREAD

**Issue by harmeet-status** [status-im/status-desktop#8651]
# Bug Report

## Description

I cannot backup my Seed Phrase, after setting up a clean install of Status App and also setting up a brand new account.

## Steps to reproduce

1. Install Status App 
2. Create a new account
3. Once you are finished, click the Backup seed phrase banner.
4. Select all of the checkboxes, Confirm Seed Phrase is still greyed out

#### Expected behavior
Show me the seed phrase.

#### Actual behavior
Cannot go to next step to see seed phrase.

### Additional Information

- Status desktop version: 0.8.0
- Operating System: Mac 12.6

<img width="1410" alt="Screen Shot 2022-12-06 at 5 08 16 pm" src="https://user-images.githubusercontent.com/104047049/205835386-34cb563d-e2cb-4183-8911-a1bd4f69d2ba.png">

**Comment by anastasiyaig** [comment]
@harmeet-status please scroll the modal a bit, there is one more checkbox u have to accept :)

**Comment by 0x-r4bbit** [comment]
@harmeet-status can confirm that you'll have to scroll down in the modal.

@jrainville I propose we should either make the red box part of the scrollable area, or move it above the checkboxes. to solve this

**Comment by jrainville** [comment]
@0x-r4bbit I guess the design wants the red box at the bottom, so try putting it in the scrollable area. Maybe also make the scrollbar always show when there is something to scroll (something like `ScrollBar.AsNeeded` from the policy https://doc.qt.io/qt-6/qml-qtquick-controls2-scrollbar.html#policy-prop)

**Comment by 0x-r4bbit** [comment]
Okay I can do that w.r.t. scrollbar but I think ideally we have a proper solution with an indication that there's more content in the scroll area.

I've discussed this many times with @benjthayer and if I remember correctly, there's already designs for it for the discord import tool modal, which suffers from the same problem.

I think if we implement this design for all scrollable areas in our app, this would greatly improve the UX.
But I think this still needs to get green light, no? @benjthayer

**Comment by jrainville** [comment]
Ah yes that would be great. Obviously, this would need its own ticket and is out of the scope of this one for now

**Comment by 0x-r4bbit** [comment]
Actually, it turns out that `StatusScrollView` (which is a `Flickable`) already comes with `StatusScrollBar.vertical.policy: ScrollBar.AsNeeded`

```qml

    ScrollBar.horizontal: StatusScrollBar {
        policy: ScrollBar.AsNeeded
        visible: resolveVisibility(policy, root.width, root.contentWidth)
    }

    ScrollBar.vertical: StatusScrollBar {
        policy: ScrollBar.AsNeeded
        visible: resolveVisibility(policy, root.height, root.contentHeight)
    }

    function ensureVisible(rect) {
        Utils.ensureVisible(this, rect)
    }
```

However, even if this is `visible: true` it's still not shown. Now sure if that is somehow OS dependent?
Maybe some QML wizards can shed some light into darkness here? 
/cc @caybro @MishkaRogachev

**Comment by benjthayer** [comment]
@0x-r4bbit correct! :) 

We explored this for the import tool - I added a subtle hard shadow along the top edge of the toolbar to indicate there was content below it. This hasn't been given the green light globally for the rest of the dialogs in the app though. Ideally, we  would take some time to review all types of dialog to ensure a consistent treatment can be applied. 

@John-44 I'm happy to extend on this work to review all desktop dialog types and propose a uniform solution?
 
<img width="599" alt="Screenshot 2023-01-11 at 15 54 36" src="https://user-images.githubusercontent.com/110033914/211853387-204d5629-2cb1-44c5-8faf-b631504e5937.png">

**Comment by caybro** [comment]
> @caybro do you have any with regards to [#8651 (comment)](https://github.com/status-im/status-desktop/issues/8651#issuecomment-1378980079) ?

Uhm I don't understand :)

**Comment by 0x-r4bbit** [comment]
The vertical scrollbar of this modal does not show, even though the content of the scrollbar is bigger than the scrollview and it's visibility is set to `true`.

We want to ensure users know that the modal has more content (there's a scrollable area) but right now they can't see it even though the policiy of the scrollbar is set as such.

**Comment by caybro** [comment]
> The vertical scrollbar of this modal does not show, even though the content of the scrollbar is bigger than the scrollview and it's visibility is set to `true`.
> 
> We want to ensure users know that the modal has more content (there's a scrollable area) but right now they can't see it even though the policiy of the scrollbar is set as such.

I understand that; but what is it that you wanted to ask me? :)

> @caybro do you have any with regards to https://github.com/status-im/status-desktop/issues/8651#issuecomment-1378980079 ?

**Comment by 0x-r4bbit** [comment]
Ah lol "any **deas** with regards to"

I wonder if I miss anything to make this scrollbar show up. Seems like this needs to be fixed in the ScrollView.
I can take another look and see if I can figure anything out, but I was hoping you had some for wizard ideas/pointers that fix things instantly haha

**Comment by caybro** [comment]
> Ah lol "any **deas** with regards to"
> 
> I wonder if I miss anything to make this scrollbar show up. Seems like this needs to be fixed in the ScrollView. I can take another look and see if I can figure anything out, but I was hoping you had some for wizard ideas/pointers that fix things instantly haha

Ok, so actually 2 ideas:
- try with a vanilla `ScrollView`, not `StatusScrollView`
- force the vertical scrollbar to be `AlwaysOn`

**Comment by MishkaRogachev** [comment]
I've just tested StatusScollView in very simple approach:
```
StatusModal {
...
    contentItem: StatusScrollView {
        padding: Style.current.padding

        ColumnLayout {
            id: contentColumn
            spacing: Style.current.padding

```
And when StatusModal's content becomes less than implicitHeight of ColumnLayout - StatusScrollBar appears. And it's still working in backup seed phrase dialog:

https://user-images.githubusercontent.com/2522130/212127674-0a0fa2c0-a174-40f3-a84c-23f90074d29c.mov

**Comment by 0x-r4bbit** [comment]
@MishkaRogachev you're right, I was misinterpreting the property. I though that `AsNeeded` would render it as soon as the viewport becomes too small, but it only renders once you start scrolling.

After changing this to `AlwaysOn` as per @caybro 's suggestion, this is now much more apparent.
Sent #9153 accordingly
