### ISSUE TITLE
Start chat overlay remains on screen when you click the communities button

### ISSUE THREAD

**Issue by harmeet-status** [status-im/status-desktop#8655]
# Bug Report

## Description

Add new user overlay remains on screen when you click the communities button

## Steps to reproduce

1. Click start chat
2. Then click communities, you can see that the start chat overlay remains which should go away as soon as you click communities
3. This issue also there if you click settings

### Additional Information

- Status desktop version: 0.8.0
- Operating System: Mac 12.6

<img width="1680" alt="Screen Shot 2022-12-06 at 7 02 34 pm" src="https://user-images.githubusercontent.com/104047049/205867069-b6ff50af-06da-4429-a83a-a120d9d42ee4.png">

**Comment by jrainville** [comment]
Already fixed here https://github.com/status-im/status-desktop/issues/7675
