### ISSUE TITLE
Build fails on MacOS 11.6.1

### ISSUE THREAD

**Issue by cskiraly** [status-im/status-desktop#8663]
# Bug Report

## Description

As the current binary fails on 11.6.1, I was trying to build from source, but that fails as well

## Steps to reproduce

Try to build on macOS 11.6.1

#### Expected behavior

builds

#### Actual behavior

Fails when trying to link.

It seems it tried to link agains some downloaded binaries build for newer version.

```bash
> clang  @nim_status_client_linkerArgs.txt
ld: warning: object file (bottles/openssl@1.1/lib/libcrypto.a(bio_err.o)) was built for newer macOS version (13.0) than being linked (11.0)
ld: warning: object file (bottles/openssl@1.1/lib/libssl.a(ssl_init.o)) was built for newer macOS version (13.0) than being linked (11.0)
ld: warning: object file (bottles/pcre/lib/libpcre.a(libpcre_la-pcre_compile.o)) was built for newer macOS version (13.0) than being linked (11.0)
ld: warning: object file (bottles/pcre/lib/libpcre.a(libpcre_la-pcre_config.o)) was built for newer macOS version (13.0) than being linked (11.0)
ld: warning: object file (bottles/pcre/lib/libpcre.a(libpcre_la-pcre_exec.o)) was built for newer macOS version (13.0) than being linked (11.0)
ld: warning: object file (bottles/pcre/lib/libpcre.a(libpcre_la-pcre_study.o)) was built for newer macOS version (13.0) than being linked (11.0)
...
```

### Additional Information

- Status desktop version:
- Operating System:

**Comment by anastasiyaig** [comment]
@jrainville @iurimatias i remember we had something like that , how to fix this?

**Comment by jrainville** [comment]
I am Mac noob. No idea

**Comment by jrainville** [comment]
I know @borismelnik helped someone lately with Mac issues

**Comment by caybro** [comment]
Update macOS

**Comment by cskiraly** [comment]
Updating macOS is IMHO not the right solution to propose, at least if there is something better we can have.

I've managed to build by using `brew install` instead of the bottle download which is IMHO a weak point of the build process. In particular:
- build using qt5 from brew works (no need for the manual install as per instructions)
- build using other dependencies from brew works (no need for GH credentials and manual bottle download)
I did not test the build extensively, but it seems to work.

I've also checked and the same process also works to build a native arm64 version for M1. It builds, it starts, then it hangs at one point, so still not perfect.

**Comment by anastasiyaig** [comment]
@cskiraly i dont think this problem is really related to the client itself (the desktop application).

Also, I am building the app on M1 arm64 each day, it works. I dont deny you have issues, but i doubt it is a bug in the product itself.

**Comment by cskiraly** [comment]
@anastasiyaig I agree, no problem with the product. I had issues with the binary distributed and the build process:
- the distributed binary is macOS 13+ only, as I see
-  the build process downloads brew binary packages that are only compatible with macOS 13+.

What macOS are you building on? Are you doing native arm64 build, or x86_64 with Rosetta? Because I was saying the native arm64 build (which is not yet ready as I understand) did build, even if not yet working perfectly.

**Comment by iurimatias** [comment]
Latest release have new builds and better building process, including apple silicon builds.
