### ISSUE TITLE
Settings: cant switch off sounds for notifications 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8668]
### Description

Having toggle off and sound lowered to 0 i am still receiving sounds

<img width="1652" alt="Screenshot 2022-12-06 at 18 52 01" src="https://user-images.githubusercontent.com/82375995/205959320-74387e8c-0f8b-4b92-9a86-d70fd8eb85c1.png">

**Comment by caybro** [comment]
Any warnings in the console that might be related? Also, version?
