### ISSUE TITLE
Design / dev discrepancies found during implementation of "Create a copy of Keycard" flow 

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8674]
# Bug Report

## Description

Design issues found during: https://github.com/status-im/status-desktop/issues/8671 / https://github.com/status-im/status-desktop/issues/7035

---
### 1. OPEN Figma suggests that in some scenarios user is directed back to "Insert this keycard…" modal 

A way for the user to be returned to the "insert this keycard" modal was not found. It has been confirmed during development that this cannot be implemented. This inconsistency may need resolved.

From @saledjenic : 
> There are no technical feasibilities to support that. Our keycard library doesn't recognize a moment when user removes a card. This further means that connection/arrow in Figma should be removed. 

![image](https://user-images.githubusercontent.com/50769329/205999893-3d5d4787-57e0-4c8e-af0c-7ad2822a757d.png)

---
### 2. OPEN Keycard locked and already stores keys does not match Figma

Currently implementation does not match design. @saledjenic highlighted differences in the design.

> That is just one of examples I faced with inconsistency between the same states for different flows, see how it's handled here:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=7258%3A187151&t=xQGc6EBwae0yJDPg-0
> and you pointed to this:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=7258%3A187459&t=fT7INtOJGMypfzuz-4

---
### 3. OPEN Keycard registered with account after factory reset

If a user factory resets a recognised Keycard as part of the flow then the user may end up with Keycards listed in the app that are not useable. For example, a keycard is locked and then factory reset will still be listed in the app.

---
### 4.  OPEN Wording on This keycard already stores keys modal
Figma reads "To migrate..." instead of "To copy..."

![image](https://user-images.githubusercontent.com/50769329/206004005-d39a5921-4c2d-4278-8490-47d22dddd7a1.png)

@saledjenic 
> Yes, I deliberately wrote "To copy..." cause it's a Create a backup copy of this Keycard flow, so we're copying a keycard, not migrating a keypair. Keypair was already migrated to the keycard we're copying from. But it's a good point to notify @xAlisher about that. 

---
### 5. OPEN Main keycard screen may make it difficult to find copies
Found during: https://github.com/status-im/status-desktop/issues/8136

Users have to click on the original keycard to view or manage copied keycards. This doesn't seem particularly intuitive. It's also not clear how this would work in the event that the original keycard is repurposed for another account. 
![image](https://user-images.githubusercontent.com/50769329/207290086-c7f8da53-3d62-4274-aa5a-18b46605dbed.png)

---
### 6. OPEN Keycard flows could better identify what card is in use
Found during: https://github.com/status-im/status-desktop/issues/8136

Flows available when there are multiple keycards, such as for changing PIN or setting PUK, could better identify what card is in use. This may be important given physical keycards look the same and, by default, the account and every keycard linked to it will have the same name in the UI.
![image](https://user-images.githubusercontent.com/50769329/207288980-d51deb33-ce1f-40ec-9554-fd18b4bc34af.png)

**Comment by saledjenic** [comment]
@xAlisher @benjthayer could you check the details from the issue description above?

**Comment by saledjenic** [comment]
All keycard flows will be checked and aligned comparing the real app state with the fgma design. 
Depends on a case to case, an update will be either on the app or the figma side.
