### ISSUE TITLE
Increase spacing between chat messages 

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8675]
# Bug Report

## Description

When 2 message are sent from different users, the distance between the bottom of a message and the top of of the next is greater in Figma.

## Steps to reproduce

App:
![image](https://user-images.githubusercontent.com/50769329/206006007-e64e6b78-3157-4d3b-a291-b14cd773bb74.png)

Figma:
![image](https://user-images.githubusercontent.com/50769329/206005572-f8ff07ce-432c-4a63-911a-20c96941cdc5.png)

#### Expected behavior

App and Figma match

#### Actual behavior

Figma distance between messages from different users (or same user when sent more than 2 mins from each other) is greater.

### Additional Information

- Status desktop version: 0.8
- Operating System: Mac

**Comment by alexandraB99** [comment]
@benjthayer could you please give some input here, how much should be the spacing between separate messages?
