### ISSUE TITLE
Can't see emoji reactions from other members in community channels

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-desktop#8689]
# Bug Report

## Description

Noticed that people don't use reactions in community channels.
It turned out that you do not see reactions other than your own (thanks Desktop and Mobile QAs for confirmation). 
For example, this message in the #mobile channel has at least 4 `thumbs-up`'s, but Jamie will never find out about this.

<img width="469" alt="Screenshot 2022-12-07 at 17 54 02" src="https://user-images.githubusercontent.com/67952253/206241364-8697462e-9745-4255-9867-3aa9c43994d9.png">

Restarting the app doesn't help.
It works fine in group chats.

## Steps to reproduce

1. Open any community channel
2. Set a reaction on someone's message and ask if they can see it (or vise versa) 

#### Expected behavior
Can see reactions from other members
#### Actual behavior
Can only see my own reactions
### Additional Information

- Status desktop version: 0.8
- Operating System: macOS Ventura 13.0.1 Intel Core i5, Ventura 13 Apple M1 Pro, macOS Monterey 12.0 M1 Pro

**Comment by jrainville** [comment]
I tested a couple of times both in master and in 0.8.1 and I can't reproduce. I see and receive reactions correctly.

Can you try again? And if you do reproduce, can you check how many peers you have in the Node management? Check also if when you don't receive reactions, if you do receive messages.

**Comment by qoqobolo** [comment]
Hey @jrainville! Thanks for taking a look at this!

Yeah, it is still reproducible for me and a couple of other people I asked to confirm (we all are using 0.8.1). 
We don't see any reactions from each other in community channels, in private chats it works fine. 
I have 31 peers atm. 

Can you check the mobile channel btw, please? Can you see our reactions (screenshots below)?

This is how I see reactions there
<img width="666" alt="Screenshot 2022-12-13 at 17 03 49" src="https://user-images.githubusercontent.com/67952253/207383344-f4c931e2-3dc6-4b1d-9670-3f512a7a5e09.png">

---

And these are from other guys (we can only see our own reactions). They have 26 and 35 peers.
<img width="963" alt="Screenshot 2022-12-13 at 17 04 19" src="https://user-images.githubusercontent.com/67952253/207383465-3921dcf4-6768-42a5-8f11-0aff30283b7e.png">

<img width="569" alt="Screenshot 2022-12-13 at 17 01 50" src="https://user-images.githubusercontent.com/67952253/207382851-9e6fa88b-de7a-4fba-92a6-88d2c7af6b98.png">

**Comment by jrainville** [comment]
I don't see your reactions as well in #mobile. 
Now I have something to reproduce on, I'll try to figure out the issue.
Thanks for the detailed reply.

**Comment by jrainville** [comment]
I finally figured it out with the help of @richard-ramos .
Turns out it **only** happens in enrypted communities, that's why it was hard to find. Also, not only emoji reactions were broken, deletes, edits and pins were not working either.

The PR that fixes it is here https://github.com/status-im/status-desktop/pull/8804

**Comment by qoqobolo** [comment]
> Also, not only emoji reactions were broken, deletes, edits and pins were not working either.

Yes, noticed the deletion issue as well, but I was told that this is a known issue and will be fixed in 0.9, so I didn't report it in GH.

> Turns out it only happens in enrypted communities, that's why it was hard to find.

Ahhh, sorry you had to deal with it! And thanks for a great job, Jo!
