### ISSUE TITLE
Wrong name "Tokens" in Profile preview

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#8716]
## Description

Was discussed during Istanbul offsite, the name on the Profile sections should be assets and not tokens

#### Expected behavior
The name should be Assets like in wallet view 

#### Actual behavior

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/60327365/206710726-0e80c54e-a41e-4d2f-be89-5c783af882c7.png">

### Additional Information

- Status desktop version:
- Operating System:

**Comment by caybro** [comment]
@benjthayer need some input here

**Comment by benjthayer** [comment]
@caybro confirming with the design team.
