### ISSUE TITLE
Message height should be adjusted when dismissing link previews

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8720]
Here you see a message that takes a lot of blank space:

![Screenshot from 2022-12-09 16-04-08](https://user-images.githubusercontent.com/445106/206731756-6598cdbd-1b58-4dbe-a058-4e792ce06ae4.png)

The reason it does that is because there's three links in the message and for every link I got the "enable link preview" bubble, which I then dismissed for all of them.

The message then however didn't adjust its height.

**Comment by alexandraB99** [comment]
can't reproduce this one, @anastasiyaig could you please have a look?

**Comment by caybro** [comment]
> can't reproduce this one, @anastasiyaig could you please have a look?

Well it's probably because in current master, we do not display previews for Github URLs (among others)

**Comment by lukaszso** [comment]
Cannot reproduce in the latest master. The message height adjusts correctly when dismissing the preview.
