### ISSUE TITLE
Notifications: I can see many of 'Hi' from myself as the mutual contact notifications

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8727]
# Bug Report

## Steps to reproduce
1. I sent 20 contact requests to different accounts with the message 'Hi!'
2. When I was offline, these accounts added me to their Contacts
3. I'm launching the app

#### Expected behavior
As a user, I'm expecting to see the notifications with the name of the contact and information that they added me t their Contacts and I can chat with them now.
#### Actual behavior
The notification with my name and 'Hi!' is shown many times
### Additional Information
<img width="241" alt="hi_again" src="https://user-images.githubusercontent.com/14942081/206977234-c5d42af6-c647-46c2-ba38-93ca50180126.png">

<img width="182" alt="many_hi" src="https://user-images.githubusercontent.com/14942081/206977224-c543cca1-771a-4cf9-ae4b-19346d64cea1.png">

- Status desktop version: 0.8.1.
- Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
it is known bug and already is being worked on https://github.com/status-im/status-desktop/issues/7851
