### ISSUE TITLE
Chat input: mentions drop selected area

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8731]
# Bug Report

## Description

When the user selects text by keyboard, if there are mentions, all selected text before are canceled when we try to select the mention

## Steps to reproduce

1. Add simple text and mention in the middle of the text
2. Try to select my keyboard text using arrows

#### Expected behavior

All text is selected by keyboard, including the mention

#### Actual behavior

Mention canceling the selected

https://user-images.githubusercontent.com/117639195/207027692-98fe126f-d167-4fc1-b1eb-52998140f0ff.mov

### Additional Information

- Status desktop version: 0.8.0
- Operating System: macos

**Comment by alexjba** [comment]
Closed by #8842
