### ISSUE TITLE
[StatusChatInput] During inserting letter before mention - this letter is adding at the end of the mention

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8741]
# Bug Report

## Description

When you change the cursor position by mouse to the beginning of the mention and try to insert any letter - it will be added at the end of the mention (plus mention will be selected)

## Steps to reproduce

Input mention, move the cursor by mouse click to the beginning of the mention, try to add any letter

https://user-images.githubusercontent.com/117639195/207059853-19a09c43-a8c6-4718-b0ed-69763d3c55a6.mov

#### Expected behavior

the letter is added before the mention

#### Actual behavior

the letter is added after the mention and the mention is selecting

### Additional Information

- Status desktop version: 0.8.0
- Operating System: macos

**Comment by noeliaSD** [comment]
Similar use case failure commented here: https://github.com/status-im/status-desktop/pull/8842#pullrequestreview-1224344614

**Comment by alexjba** [comment]
This is the new behaviour

https://github.com/status-im/status-desktop/assets/47811206/1853ed05-27b0-447d-9100-8b82a887412d

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
