### ISSUE TITLE
Chat input: removing mention after mouse action leave pubkey

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8742]
# Bug Report

## Description

If you remove mention after:
- mouse click on the mention
- selecting the cursor in the mention
- selecting mention

pubkey is not removing

## Steps to reproduce

https://user-images.githubusercontent.com/117639195/207062727-bbd79bcc-de6b-4640-9248-8d845b93165f.mov

#### Expected behavior

Mention removed, after sending the message - no pubkey is visible

#### Actual behavior

Mention removed, after sending the message - pubkey is visible

### Additional Information

- Status desktop version: 0.8.0
- Operating System: macos

**Comment by alexjba** [comment]
Closed by #8842
