### ISSUE TITLE
[StatusMessage] Refactor/improve/optimize

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#8744]
### Description

Currently scrolling in messages is slow, this task is to optimize the StatusMessage component & friends (eg. StatusTextMessage) 

* EDIT MESSAGE MODE: In the past it seemed that the StatusChatInput which is loaded when the user pressed to edit the message was impacting performance, make sure things are loaded only on demand

**Comment by alexjba** [comment]
related to #3067
