### ISSUE TITLE
[StatusChatInput] Reply message input: Navigating emoji suggestions with up/down keys will navigate the messages view

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#8748]
### Description

Might be same root cause/fix as #8746. The behaviour is the same.

Repro steps:
Send a message in community
Edit the message,
Add :sm to trigger the emoji suggestion
Navigate using up/down.

Expected:
Key navigation is limited to emoji suggestions

Actual:
Key navigation is processed by the messages view

**Comment by alexjba** [comment]
Found in 7686

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
