### ISSUE TITLE
Chat input: Cannot add mentions in the create chat view

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#8749]
### Description
Repro steps:
Create chat
Add some contacts
Write the first message with mention

Expected:
Mentions are available

Actual:
Cannot add mentions

https://user-images.githubusercontent.com/47811206/207101729-c2c52f04-99bb-45fe-9bd3-b319796cc1a2.mov

**Comment by alexjba** [comment]
Found in #7686

**Comment by alexandraB99** [comment]
@benjthayer could you please add some input here, should mentions be present when creating a new 1-1 or group chat? (see video for details)

**Comment by benjthayer** [comment]
Hi @alexandraB99 it seems logical that they should be present - confirming with the design team - will get back to you asap

**Comment by John-44** [comment]
@alexandraB99 @benjthayer yes when creating an ad-hoc group chat, a user should be able to @ mention the members of the ad-hoc group chat that are present in the "To:" field.

**Comment by John-44** [comment]
@alexandraB99 @benjthayer also @ mentions don't need to be present in 1-1 chats, because every message in a 1-1 chat is an @ mention

**Comment by alexandraB99** [comment]
@benjthayer @John-44 but even before the group is actually created? so before the "Confirm" button is pressed to actually create the group? in the video if you notice, it's before creating the group, so does is make sense to mention someone in a group that is not yet created?

**Comment by benjthayer** [comment]
That is an interesting point. If the user is mentioned then subsequently removed from the final group members they will not receive the message or associated mention notification. 

However, that feels like an edge case as in most cases a user mentioned in the initial message of a group chat will also be added to the initial member list. 

Although there is a chance the user may accidentally delete the user from the group membership when they have mentioned them, it feels like worse UX to remove an expected feature like the mention suggestions.

What do you think @John-44 ?

**Comment by jrainville** [comment]
I agree with @benjthayer and @John-44 that we should be able to mention the contacts we selected for the group even if confirm was not clicked.

Even if one of the contacts is removed and we mentioned them, it will not actually mention that person, since they will not be added. The name will be blue, but there will be no notification, so it's not a big deal.

This is more of a messenger issue, I'll take it.
