### ISSUE TITLE
Image Download doesn't work

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8755]
# Bug Report

## Description

When you right click an image in a channel and select "Download", the dialog opens, but when you select the folder, nothing happens. The image is not downloaded in that folder.

Also, it would be way better if the location dialog enabled to select the name of the file you want to download as. Right now, it only lets you choose the folder.

#### Expected behavior

Once you select the location to download, the image should be downloaded to that location. 

Bonus points if there is a loader or progress bar, but that can be done if we add a design later.

Also, changing the dialog to a file location dialog instead of a folder one would be better.

### Additional Information

- Status desktop version: master (`59a05243aff598f4b031df9a7ba5687eb06ec51d`)
- Operating System: Windows 10

**Comment by jrainville** [comment]
As far as I could see, there was nothing. I'll try again later to see if I get something. It might be a weird Windows bug. I tested on Linux as well and indeed it worked.

**Comment by caybro** [comment]
> Seems like a Windows issue. I tested again and it doesn't work on Windows. No logs sadly.

Try printing out the destination folder path
