### ISSUE TITLE
When clicking on an item (reply) in notification, behaviour is erratic, no feedback shown

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8758]
# Bug Report

## Description

When clicking on an item in the notification bar:

- Behaviour is erratic/slow:
  - it does not jump to the channel if the message is in a community but community is not selected in the left hand sidebar
  - When it finally jumps after several seconds, it does not always get to the message
- Poor feedback:
	-  There is no feedback on whether the item is clickable or what should be clicked
	- no feedback on whether the item is indeed clicked
	- no visual aid to highlight the message once jump to channel is done

## Steps to reproduce

1. Get someone to reply to you
2. open notification menu
3. click on message

#### Expected behavior

- Visual aid to understand that the item is clickable
- Visual aid to understand where we should click (sometime clicking on a word and not sure if it's clickable or I am just selecting text)
- Visual aid to understand that it has been clicked
- Faster experience to jump to the right channel/message
- Open the right community if message is from a community channel
- Better location to the message: ie, open the channel with clicked message on top but with some top margin
- Visual aid to locate the message (eg, temporary highlight of said message in channel),

#### Actual behavior

See description

### Additional Information

- Status desktop version: 0.8.0 & 0.8.1
- Operating System: Fedora Linux

https://user-images.githubusercontent.com/110212804/207182816-fd9471a8-aa23-486d-89fe-b1e104d8300e.mp4

**Comment by MishkaRogachev** [comment]
@benjthayer @John-44 i need here some advices how we can animate jumping to a specific chat or message

**Comment by caybro** [comment]
> @benjthayer @John-44 i need here some advices how we can animate jumping to a specific chat or message

The animation is there already; you just need to call `messageStore.messageModule.jumpToMessage(model.id)` (see e.g. the PinnedMessagesPopup.qml)
