### ISSUE TITLE
fix: generated account balances not updated after transaction

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#876]
1. Enable wallet
2. Generate new account
3. Send eth/stt from original account to the newly generated account.
4. Expected result: upon tx success, sent funds should appear in the generated account.
5. Actual result: funds are not appearing in the generated account, but they are being deducted from the sending account.

**Comment by iurimatias** [comment]
note: possible that PRs #2315 and #2321 fix or help with this

**Comment by anastasiyaig** [comment]
fixed in Version: 0.1.0-beta.9
