### ISSUE TITLE
[Community Permissions] Backend

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#8764]
### Description

EPIC https://github.com/status-im/status-desktop/issues/5981 is almost done, so **UI part for community permissions** is ready and now working with _mocked data._

Here a high level list of backend needs ([figma design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2992%3A367890&t=MvpCZX7pPOMCYkn8-0)):

#### General:
- [x] Define / create new NIM module that contains a **permissions list object model** and make it a visible module for the UI. Use the `AppLayout/Chat/stores/CommunitiesStore.qml` as a base file to understand which are the model roles the UI is expecting (in `createPermission` a mock permissions object is created).
- [x] API method to validate a permission before it is created to cover the following use case (agree with design team which are the expected validation rules): https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22253%3A486103&t=2kdi9XnmFFXnsQfU-0
- [x] API method to create a new permission 
- [ ] API method to duplicate a permission
- [x] API method to remove a permission
- [x] API method to edit an existing permission
- [ ] API method to determine the % of community members that fulfill the requirements to cover the following use case: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22772%3A496682&t=Q7sGGTFUmcOTI1oq-0

#### Holdings
- [x] API method/object model to get `Community collectible / tokens` and `Listed collectibles / tokens` dropdown data. 
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A482819&t=2kdi9XnmFFXnsQfU-0
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A484524&t=k9Rsiro7S7LLW2to-0
- [ ]  API method to get following filtering options for collectibles:  `most viewed`, `newest first` and `oldest first`.
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A484608&t=YvTezgDekHc7O9d8-0
- [ ]  API method to get ENS custom subdomain validation
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=15471%3A461262&t=2kdi9XnmFFXnsQfU-0
- [x] Do the integration of getting the real data (assets and collectibles in the user's wallet) to be displayed in the corresponding holdings dropdown lists.

#### Permissions (is alowed to):
- [ ] API method/object model to get the list of possible permissions (now hardcoded in ui)
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481728&t=2kdi9XnmFFXnsQfU-0

#### Permissions management
- [ ] How this permissions will be applied?

**Comment by 0x-r4bbit** [comment]
>  API method to duplicate a permission

@noeliaSD AFAIK duplicating will be removed, right?

**Comment by noeliaSD** [comment]
> > API method to duplicate a permission
> 
> @noeliaSD AFAIK duplicating will be removed, right?

Yes! The design flow changed so now, when user clicks on `duplicate` it navigates to the "create new permission" page and the call to the backend will be the regular one done when a new permission is created!

**Comment by jrainville** [comment]
Closing as it is outdated and stuff is tracked elsewhere
