### ISSUE TITLE
Chat: Unable to paste images (macos)

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8771]
# Bug Report

## Description

On MacOS it is not possible to paste and send chat messages. Confirmed that this is currently OK in Linux.

## Steps to reproduce

Copy and image to the clipboard
Have the chat input in focus
Command-V to paste

#### Expected behavior

Image is pasted into message

#### Actual behavior

Image is not pasted, nothing is added to input

### Additional Information

- Status desktop version: 0.8.1
- Operating System: MacOS

**Comment by iurimatias** [comment]
Deja Vu, this might be a duplicate

**Comment by mprakhov** [comment]
was fixed in #8459

on 0.9.0 is not reproducible

closing as fixed
