### ISSUE TITLE
Liking a message, does not auto hide the popup after selecting reaction

### ISSUE THREAD

**Issue by harmeet-status** [status-im/status-desktop#8776]
# Bug Report

## Description

In discord, when you want to like a MSG, you are shows a little popup and once you select a reaction, it goes away automatically. In Status app, this stays there, and you have to click elsewhere to get rid of it.

It should go away automatically once you have selected a reaction.

## Steps to reproduce

1. Select a msg
2. Click the reaction button
3. Select a reaction
4. The popup should disappear automatically since you are done

### Additional Information

- Status desktop version:
- Operating System:

<img width="1677" alt="Screen Shot 2022-12-14 at 8 24 25 pm" src="https://user-images.githubusercontent.com/104047049/207557923-648eda16-d716-4fb0-97c6-4f943aee7f0d.png">

**Comment by caybro** [comment]
Already fixed in master by https://github.com/status-im/status-desktop/pull/8672
