### ISSUE TITLE
chore(QML): reduce memory usage, improve startup time

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8779]
### Description

Currently the app's memory (RAM) usage is abysmal; potential areas for improvement: 
(this bug serves as a tracking collection)

- [x] #8782
- [x] #8781 (PR https://github.com/status-im/status-desktop/pull/8794)
- [x] #8744
- [x] #9016
- [x] Refactor DOtherSideStatusSyntaxHighlighter to be a singleton internally on work on a given QTextDocument (https://github.com/status-im/dotherside/blob/master/lib/src/DOtherSideStatusSyntaxHighlighter.cpp#L69)
- [x] #8792

**Comment by micieslak** [comment]
> also in order to improve scroll performance

I think that's big topic that should be carefully discussed before starting any work here. We need to decide what should be the new approach here, bc currently used ListView  will probably never be the proper option. Maybe we should create custom c++ component for controlling the messages list in a performant way. Or some other approach.

**Comment by caybro** [comment]
> > also in order to improve scroll performance
> 
> I think that's big topic that should be carefully discussed before starting any work here. We need to decide what should be the new approach here, bc currently used ListView will probably never be the proper option. Maybe we should create custom c++ component for controlling the messages list in a performant way. Or some other approach.

Ye, for a long term solution... I agree; however we need to do something about it asap, we can always improve iteratively
