### ISSUE TITLE
Notifications pop-up for messages sent

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8784]
# Bug Report

## Description

When starting the app, I usually have a bunch of notifications popping up for messages **I** sent.

## Steps to reproduce

- Send 1:1 messages to people
- Close/open app

#### Expected behavior

- Notification only for incoming messages

#### Actual behavior

- Notifications for outgoing messages

### Additional Information

- Status desktop version: 0.8.0 & 0.8.1
- Operating System: Fedora Linux Wayland

I was able to get a screenshot but they go fast.
![image](https://user-images.githubusercontent.com/110212804/207577676-bf450bb8-551c-4422-bb20-1e8583f18cdb.png)

**Comment by caybro** [comment]
cc @MishkaRogachev

**Comment by MishkaRogachev** [comment]
@caybro that's not AC notifications, it's notifications manager. WE should already have issue to remove it and promote AC notifications to system notification when app is not visible

**Comment by jrainville** [comment]
This is getting fixed here https://github.com/status-im/status-desktop/pull/8808
