### ISSUE TITLE
[Chore] Improve error logging for OpenSea errors / generic json unmarshalling errors

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#8798]
Due to an expired API key, we got a very cryptic error when trying to fetch collectibles:

`
ERR 2022-12-06 21:00:46.163+00:00 rpc response error                         topics="rpc" tid=4250323 file=core.nim:29 err="\nstatus-go error [methodName:wallet_getOpenseaCollectionsByOwner, code:-32000, message:invalid character \'E\' looking for beginning of value ]\n"
ERR 2022-12-06 21:00:46.164+00:00 error doing rpc request                    topics="rpc" tid=4250323 file=core.nim:33 methodName=wallet_getOpenseaCollectionsByOwner exception="\nstatus-go error [methodName:wallet_getOpenseaCollectionsByOwner, code:-32000, message:invalid character \'E\' looking for beginning of value ]\n"
ERR 2022-12-06 21:00:46.164+00:00 error:                                     tid=4250323 file=async_tasks.nim:14 errDesription="\nstatus-go error [methodName:wallet_getOpenseaCollectionsByOwner, code:-32000, message:invalid character \'E\' looking for beginning of value ]\n"
`

Running the API request command manually, I could see this was because the API was not returning valid JSON. Instead, it returned:

`Expired API key`

Having this string in the log would've saved me a lot of time. Improve error logging when json unmarshalling fails in status-go.

Also, possibly use `json.Valid()` before?

**Comment by Khushboo-dev-cpp** [comment]
Fixed under https://github.com/status-im/status-desktop/pull/9710
