### ISSUE TITLE
Clicking "Go to Community" on a big community calls `chat_getMembers` a ton

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8801]
# Bug Report

## Description

For example, posting the link to the Status community, then clicking the button to see the community, calls `chat_getMembers` a ton. It makes the app completely unresponsive.

## Steps to reproduce

1. Post this link in a channel https://join.status.im/c/zQ3shf8EvhRKHSc3skgtupULuLdWh59S5czZkvS69P6rJ7aed
2. Wait for the link to unfurl
3. Click the button

See the console all the logs.
If it doesn't work, leave the community and try again after a reopening

The stack trace seems to be the following:

```
/home/richard/status/status-desktop/src/app/core/signals/signals_manager.nim(53) processSignal 
/home/richard/status/status-desktop/src/app/core/eventemitter.nim(57) emit 
/home/richard/status/status-desktop/src/app_service/service/community/service.nim(199) :anonymous 
/home/richard/status/status-desktop/src/app_service/service/community/service.nim(435) handleCommunityUpdates 
/home/richard/status/status-desktop/src/app/core/eventemitter.nim(57) emit 
/home/richard/status/status-desktop/src/app/modules/main/chat_section/chat_content/users/controller.nim(61) :anonymous 
/home/richard/status/status-desktop/src/app/modules/main/chat_section/chat_content/users/io_interface.nim(40) onChatMembersAddedOrRemoved 
/home/richard/status/status-desktop/src/app/modules/main/chat_section/chat_content/users/module.nim(188) onChatMembersAddedOrRemoved 
/home/richard/status/status-desktop/src/app/modules/main/chat_section/chat_content/users/io_interface.nim(43) onChatMembersAdded 
/home/richard/status/status-desktop/src/app/modules/main/chat_section/chat_content/users/module.nim(163) onChatMembersAdded 
/home/richard/status/status-desktop/src/app/modules/main/chat_section/chat_content/users/controller.nim(162) getChatMember 
/home/richard/status/status-desktop/src/app/modules/main/chat_section/chat_content/users/controller.nim(159) getChatMembers 
/home/richard/status/status-desktop/src/app_service/service/chat/service.nim(600) getMembers 
/home/richard/status/status-desktop/src/backend/chat.nim(136) getMembers 
/home/richard/status/status-desktop/src/backend/core.nim(55) callPrivateRPC 
/home/richard/status/status-desktop/src/backend/core.nim(21) makePrivateRpcCall 
```

### Additional Information

- Status desktop version: master (`3f01af4446661f77cf523588ae8ab22ec136723e`)
- Operating System: Ubuntu 20

**Comment by mprakhov** [comment]
There are 2 problems:
1. Minor: code issue, unnecessary loop, and increased algorithm complexity from n2 to n3 (where we additionally request `chat_getMembers`)
2. Priority: If we view the community, but do not join it - we don't see the members of the community. This is because on status go all members have our `join` community status during the `get_chatMembers` request (which is false). 
The question is: Should we see the members list when we view the community (we are not joined)? @pedro-et 
Depending on the answer, there will be appropriate fix:
1. If yes - status go must return the correct members' join status
2. If no - we shouldn't try to add users, because due to member states `join=false` they won't be added anyway.

**Comment by jrainville** [comment]
@mprakhov If it is possible to do it easily, I would say go ahead and remove the members list during the spectate mode. The UX gain of knowing who is in a community is not greater than the decrease in performance we get right now.

If we later want to see it during spectate, we can do it correctly in another issue, because it seems to be broken as you've pointed out.
