### ISSUE TITLE
Chat input: editing a message removes spaces between lines

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8814]
# Bug Report

## Description

When send a message and then edit it, spaces between new lines are removed

## Steps to reproduce

1. Send a message with additional spaces between the lines
2. Edit the message
3. Save changes

#### Expected behavior

Changes were applied, and spaces between the new lines are not removed

#### Actual behavior

Changes were applied, and spaces between the new lines removed

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macos

https://user-images.githubusercontent.com/117639195/207873179-d026fc25-afe1-42a6-b271-aa53eb6a133f.mov

**Comment by iurimatias** [comment]
can no longer replicate
