### ISSUE TITLE
[StatusChatInput] cursor position jumps through 2 emoji during the keyboard navigation

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8815]
# Bug Report

## Description

If I'll try to navigate via keyboard through the input emoji, the cursor position sometimes navigates through 2 emoji

## Steps to reproduce

1. Input 🧑🏿‍🎓👮‍♀️😛🔥🧁🅾️🤰🏾🫕🧍🏼🚞👨🏼‍🎤🚵🏻‍♂️🈸✖️ emoji
2. Navigate from the end to the beginning

#### Expected behavior

The cursor position is jumping through 1 emoji

#### Actual behavior

The cursor position can jump through 2 emoji

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macos

https://user-images.githubusercontent.com/117639195/207880732-cbed80ba-3f36-4551-bc2f-c73e19acf920.mov

**Comment by caybro** [comment]
The problem here (as in another place where we count the character/glyph limit) is with some emoticons which are in fact UTF-16 (therefore taking 2 bytes).

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
