### ISSUE TITLE
[Community Permissions] Update `tokens` names to `assets`

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#8816]
## Description

The design is going to change and then `Tokens` will be renamed to `Assets`. The UI should be updated accordingly.

Example figma element (not all places are already refactored when creating this ticket): https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481644&t=wgtolxqQkOw6sxsg-0

**Comment by noeliaSD** [comment]
Design updated. Use the following flow: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22721%3A499660&t=w0VWfIEyU5IqdPWz-0 to resolve the task.
