### ISSUE TITLE
[Community Permissions] Prevent adding assets or collectibles that are already chosen

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#8817]
## Description

Currently it's possible to add the same assets/collectibles multiple times:

![Screenshot from 2022-12-15 15-24-04](https://user-images.githubusercontent.com/20650004/207885619-c53d86b4-fa85-4657-8d3a-78ebde555daf.png)

It should be forbidden via disabling already used asset/collectible in the dropdown's list.

**Comment by noeliaSD** [comment]
Here the [design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22827%3A502217&t=VoLqt3AMnlHTRG38-0) to exclude already used items: 

![Screenshot 2023-01-11 at 10 41 34](https://user-images.githubusercontent.com/97019400/211771869-57b7a594-fe2f-4fc3-a86e-923d10faaa16.png)
