### ISSUE TITLE
Activity Center: message that was read in chat, should be marked as read in activity center

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8820]
### Description

1. join a community
2. send some messages
3. get some replies to your messages
4. note there is a counter in AC for that
5. open the chat where the mention was and scroll to it (_read_ it)

As result, the read message is not marked as such in AC

<img width="1552" alt="Screenshot 2022-12-15 at 12 31 54" src="https://user-images.githubusercontent.com/82375995/207891552-d596ad52-5e61-434d-bb89-0d69017b2272.png">

**Comment by MishkaRogachev** [comment]
Should be fixed here: https://github.com/status-im/status-desktop/issues/9349

**Comment by iurimatias** [comment]
closing in favour of https://github.com/status-im/status-desktop/issues/9349
