### ISSUE TITLE
Chat: adding emoji to a message should close the reactions panel

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8821]
### Description

This is a common pattern for many messages - adding a reaction to the message closes the reactions panel.

https://user-images.githubusercontent.com/82375995/207892208-372e2239-3a0d-4333-ac38-4dbb90e607f5.mov

**Comment by jrainville** [comment]
Fixed here https://github.com/status-im/status-desktop/issues/8425
