### ISSUE TITLE
Encoding issue in contact requests

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8826]
# Bug Report

## Description

Message sent by a contact to me show HTML code.

## Steps to reproduce

1. Alice sends a contact request with special character in text to Bob
2. Bob accepts request
3. Bob checks DM

#### Expected behavior

Special character renders correctly

#### Actual behavior

Special character renders as html code

### Additional Information

- Status desktop version: 0.8.1
- Operating System: Fedora Linux

![image](https://user-images.githubusercontent.com/110212804/207995478-78047521-a51a-45cf-8e28-952dd1ccb8ad.png)

**Comment by iurimatias** [comment]
can no longer replicate
