### ISSUE TITLE
[Community Permissions] Create C++ reusable model wrapper that manages dirty state of a list model

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#8830]
### Description
We have a few use cases, particularly in `Community Permission`, but there may be more in the future, where we have a list model data and want to detect if a form is changed from the initial list model data.

### What to do
Create C++ model wrapping the original model:
````
IntermediateModel /*Or thing a better appropiate naming*/ {
   id: intermediateModel
   sourceModel: hodlingsModel
}
````
Such model would have the same roles of the provided `sourceModel` + additional `dirty` role. Moreover it could expose additional `dirty` property for the whole model set to true when there is any change. It could be used as follows:
````
Button {
  text: "Close"
  onClicked: {
     if (intermediateModel.dirty)
        // open confirm exit modal
     else
        closeView()
   }
}
````

**NOTE:** Once it is done, remove all js edit logic here `ui/app/AppLayouts/Chat/views/communities/CommunityNewPermissionView.qml` and use the new object type instead.

**Comment by micieslak** [comment]
Thank you @noeliaSD for creating ticket for that idea.

Some additional clarification:

It's quite significant effort to create such model, provide some potentially needed configuration possibilities and write tests. But it has big potential to be reused in many places, reducing js code bloat in qml part.

Of course such `IntermediateModel` could be modified freely, without affecting the source. In more advanced version it could also track changes in the original model and react to them accordingly to the chosen strategy.
