### ISSUE TITLE
Old messages fetched from the store node or import should not go to the front-end

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8838]
One of the big reasons why the app feels slow and unresponsive on re-sync or opening, especially after having it closed for a while, is that the messages fetched from the store node all make it to the front-end (Nim).

IMO, they should be added to the DB, but if they are old, they should stay on the status-go side and not emit a signal.

What happens is we get hundreds of messages that come in to the front end that call the emojiReactions, contact details, getLatestVerificationRequestFrom and other backend functions for each message. Some of those calls should be fixed on the Nim side, because there is probably no reason to call getLatestVerificationRequestFrom for each messages, but still.
Also, those messages go up to the QML. In theory, if they are not in the current view, they shouldn't render, but we never know.

The way to determine what is an old message is up to debate.
I think it should come down to "is the fetched message newer or older than the oldest message we got from the cursor", ie would that message show in the chat view, considering the scroll ups the user did.
There is gonna be edge cases though, since the user might scroll a lot trying to load messages, then the oldest message is very old and we now load all messages fetched from the store, but that would be one channel, instead of all of them.

This might also fix this issue https://github.com/status-im/status-desktop/issues/8824

Let me know what are your ideas, questions or rebuttals for this suggestion.

**Comment by osmaczko** [comment]
I think this is a good idea. We should load messages only newer than the chat cursor. At first sight, it seems straightforward to implement, and it can be done client-side only.

> This might also fix this issue https://github.com/status-im/status-desktop/issues/8824

I don't think it will fix this particular issue. The "unread" info comes from status-go and it takes into account all messages, even those not loaded client-side, which makes a lot of sense by the way.

**Comment by osmaczko** [comment]
@jrainville see: https://github.com/status-im/status-desktop/pull/8854/

**Comment by osmaczko** [comment]
Implementation task: https://github.com/status-im/status-desktop/issues/8907
