### ISSUE TITLE
App crashed when archive retrieval started

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#8852]
# Bug Report

## Description

Opened Status app today and finally got the archive retrieval banner.
Shortly after (a minute or so). Whole computer froze while I was trying to send a 1:1 message and the app crashed at the same time than Discord. Not sure if OS just killed them due to lack of memory :shrug:.

## Steps to reproduce

Started app
Got archive banner
opened 1:1 chat message to send message
whole OS froze
then unfroze, app crashed

#### Expected behavior

no crash

#### Actual behavior

freeze and crash

### Additional Information

- Status desktop version: 0.8.1
- Operating System: Linux Fedora

Logs: 
[local bin StatusIm Desktop.txt](https://github.com/status-im/status-desktop/files/10263594/local.bin.StatusIm.Desktop.txt)

**Comment by fryorcraken** [comment]
Note that when restarting the app, no problem but the banner did not show up.

[Uploading DBG 2022 12 20 10 49 44.txt…]()

**Comment by jrainville** [comment]
The protocol uses a lot of memory, so you are probably right in your assumption.

> Note that when restarting the app, no problem but the banner did not show up.

That's normal, it only starts it when receiving a magnet link. It might try again in <7 days.

**Comment by caybro** [comment]
Maybe related: https://github.com/status-im/status-desktop/issues/8931

**Comment by 0x-r4bbit** [comment]
First improvements are happening here https://github.com/status-im/status-go/pull/3086#issuecomment-1382075395

**Comment by fryorcraken** [comment]
Please let me know when a release or RC should be tested for this bug. HAppened to me again today: whole gnome froze and then app crashed and took the terminal with it (so no logs).
