### ISSUE TITLE
Import tool: use streams instead of keeping all data in memory

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8857]
Right now the discord import tool keeps a bunch of things in memory to load and import messages:

1. Message data (discord message payloads and Status chat message equivalents)
2. Discord message attachments (images, videos etc)
3. Archives (created from the data above)

This makes the data grow in memory a lot and in fact, there's not stop to this at this point.
We should instead figure out a while how we can leverage stream buffers, such that the tool won't use more memory than what the buffer allows for

**Comment by caybro** [comment]
Might be related: https://github.com/status-im/status-desktop/issues/8931

**Comment by 0x-r4bbit** [comment]
A fix for this is happening here: https://github.com/status-im/status-go/pull/3086
Still needs testing under a lot of data tho
