### ISSUE TITLE
[Community Permissions] `Add channel` button for creating channels from `InDropdown`

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#8877]
## Description

The button is currently properly located but not interactive:

![Screenshot from 2022-12-21 21-04-17](https://user-images.githubusercontent.com/20650004/208994674-7279fc41-1bc9-442a-9bac-7b2b6afb6b78.png)

Currently there is no figma design covering this part.

**Comment by noeliaSD** [comment]
Please @micieslak review the new design since it has been updated and maybe this topic is already resolved in terms of design.

**Comment by noeliaSD** [comment]
New design doesn't include this button so we can close it.
