### ISSUE TITLE
Chat icons show PNG transparent background as black

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8881]
# Bug Report

## Steps to reproduce

1. Create a chat
2. Set a PNG with background as chat icon

Here's [the icon I used](https://cryptologos.cc/logos/ethereum-name-service-ens-logo.png)

#### Expected behavior

Transparent background, as in Discord

<img width="275" alt="image" src="https://user-images.githubusercontent.com/25482501/209077125-79c3c9dc-ced7-4be3-af3a-4606ee2b4a2d.png">

#### Actual behavior

<img width="310" alt="image" src="https://user-images.githubusercontent.com/25482501/209077218-e6517280-4413-4e02-9548-3e5468864a5c.png">

<img width="303" alt="image" src="https://user-images.githubusercontent.com/25482501/209077248-b3842da7-b491-4d09-8d7e-451d13bfc204.png">

**Comment by 0x-r4bbit** [comment]
Problem here is most likely the same that we have wirh https://github.com/status-im/status-desktop/issues/8220, which is that we turn anything into a jpeg atm

**Comment by iurimatias** [comment]
no longer happening
