### ISSUE TITLE
[Chat rooms] Transparent background on the the header's buttons looks weird

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#8884]
### Description

<img width="745" alt="tr" src="https://user-images.githubusercontent.com/31625338/209170501-2d147992-edb3-494c-8fe8-bdb5856edc1c.png">

**Comment by alexandraB99** [comment]
@benjthayer could you please have a look and let us know how this should looks like? should we just use the same background como as for the chat title and subtitle area?

**Comment by caybro** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/9602
