### ISSUE TITLE
Make `#something` clickable only if it refers to channel

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#8895]
At the moment any word in a message which starts with `#` is displayed as a clickable link, but how it should be:
- in community:
  - if a word starts with `#` and that word is the same as any channel name within that community it should be displayed as a link and click on it should point user to that channel (that's how it is now)
  - if a word starts with `#` and it doesn't match any channel name within that community it should be displayed as regular word, should not link, should not be clickable (this need to be fixed)
- in 1-1 or group chat:
  - any word starting with `#` should be displayed as a regular word (this need to be fixed)

In continuation to this here is a new feature: https://github.com/status-im/status-desktop/issues/8906

**Comment by jrainville** [comment]
Good ideas. I think we should log them (bug and feature) separately like you said.

**Comment by saledjenic** [comment]
Feature logged, description updated.
