### ISSUE TITLE
Opened community categories/channel list UI is corrupted

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8897]
# Bug Report

## Description

Opened community categories/channel list UI is corrupted

## Steps to reproduce

1. Go to any community, but do not join it (it should be on your list)
2. Create a community with channels and categories
3. Switch between non-joined community and community, there you are an admin

#### Expected behavior

Categories/channel list UI is as expected

#### Actual behavior

Categories/channel UI is corrupted

![Screenshot 2022-12-27 at 13 43 38](https://user-images.githubusercontent.com/117639195/209662797-eaf67d68-475f-4a92-9ff5-d94f15cf6319.jpg)

### Additional Information

- Status desktop version: master branch commit `d59cffd623e536d928ce8305100fc1ff956528d0`
- Operating System: macos

**Comment by alexandraB99** [comment]
@mprakhov wasn't this fixed here https://github.com/status-im/status-desktop/pull/9027 or it's fixing a different issue?

**Comment by mprakhov** [comment]
It seems it was fixed, didn't know that we have another ticket for this.
So this MR can be treated as fixing warnings, which we see when selecting community without the banner panel (non-admin)... or I can close it as duplicate

```
Warning: qrc:/app/AppLayouts/Chat/views/CommunityColumnView.qml:440: TypeError: Cannot read property 'height' of null (qrc:/app/AppLayouts/Chat/views/CommunityColumnView.qml:440, )
Warning: qrc:/app/AppLayouts/Chat/views/CommunityColumnView.qml:457: TypeError: Cannot read property 'height' of null (qrc:/app/AppLayouts/Chat/views/CommunityColumnView.qml:457, )
Warning: qrc:/app/AppLayouts/Chat/views/CommunityColumnView.qml:477: TypeError: Cannot read property 'height' of null (qrc:/app/AppLayouts/Chat/views/CommunityColumnView.qml:477, )
```

**Comment by mprakhov** [comment]
fixed in https://github.com/status-im/status-desktop/pull/9027
