### ISSUE TITLE
`chat_getMembers` should be cached to not hit the DB each time we add a member

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8901]
### Description

Right now, each time we add a member in a community, especially when we join, we do a call to `getChatMembers`, which calls `chat_getMembers` which hits the DB. 

It's slow and probably unnecessary since that list doesn't change that often.

We just need to make sure that we update that list when we receive the appropriate signals so it stays up to date.

**Comment by mprakhov** [comment]
The changes are on review.

I want to raise another question.
In status-go right now we have 3 types of members:

```
type Member struct {
	// Community Roles
	Roles []protobuf.CommunityMember_Roles `json:"roles,omitempty"`
	// Admin indicates if the member is an admin of the group chat
	Admin bool `json:"admin"`
	// Joined indicates if the member has joined the group chat
	Joined bool `json:"joined"`
}
```

/```
/ ChatMember represents a member who participates in a group chat
type ChatMember struct {
	// ID is the hex encoded public key of the member
	ID string `json:"id"`
	// Admin indicates if the member is an admin of the group chat
	Admin bool `json:"admin"`
}
```

```
type CommunityMember struct {
	Roles                []CommunityMember_Roles `protobuf:"varint,1,rep,packed,name=roles,proto3,enum=protobuf.CommunityMember_Roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}
```

Different type of structures sends as a JSON to nim code in different cases. For example, 
- during chat/channel/community creation - `Member`
- during group chat updates - `ChatMember`
- during community/channel updates - `CommunityMember`
They all are saved under one key - `members`

Can we union all of them into one structure during sending/returning data from status-go? I don't see a big difference between them, it just brings unnecessary complexity
I think we can just return one type 
```
ChatMember {
id
roles
joined
}
```

cc @jrainville @cammellos

**Comment by mprakhov** [comment]
The changes are on review.

I want to raise another question.
In status-go right now we have 3 types of members:

```
type Member struct {
	// Community Roles
	Roles []protobuf.CommunityMember_Roles `json:"roles,omitempty"`
	// Admin indicates if the member is an admin of the group chat
	Admin bool `json:"admin"`
	// Joined indicates if the member has joined the group chat
	Joined bool `json:"joined"`
}
```

/```
/ ChatMember represents a member who participates in a group chat
type ChatMember struct {
	// ID is the hex encoded public key of the member
	ID string `json:"id"`
	// Admin indicates if the member is an admin of the group chat
	Admin bool `json:"admin"`
}
```

```
type CommunityMember struct {
	Roles                []CommunityMember_Roles `protobuf:"varint,1,rep,packed,name=roles,proto3,enum=protobuf.CommunityMember_Roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}
```

Different type of structures sends as a JSON to nim code in different cases. For example, 
- during chat/channel/community creation - `Member`
- during group chat updates - `ChatMember`
- during community/channel updates - `CommunityMember`
They all are saved under one key - `members`

Can we union all of them into one structure during sending/returning data from status-go? I don't see a big difference between them, it just brings unnecessary complexity
I think we can just return one type 
```
ChatMember {
id
roles
joined
}
```

cc @jrainville , @cammellos

**Comment by mprakhov** [comment]
The changes are on review.

I want to raise another question.
In status-go right now we have 3 types of members:

```
type Member struct {
	// Community Roles
	Roles []protobuf.CommunityMember_Roles `json:"roles,omitempty"`
	// Admin indicates if the member is an admin of the group chat
	Admin bool `json:"admin"`
	// Joined indicates if the member has joined the group chat
	Joined bool `json:"joined"`
}
```

```
// ChatMember represents a member who participates in a group chat
type ChatMember struct {
	// ID is the hex encoded public key of the member
	ID string `json:"id"`
	// Admin indicates if the member is an admin of the group chat
	Admin bool `json:"admin"`
}
```

```
type CommunityMember struct {
	Roles                []CommunityMember_Roles `protobuf:"varint,1,rep,packed,name=roles,proto3,enum=protobuf.CommunityMember_Roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}
```

Different type of structures sends as a JSON to nim code in different cases. For example, 
- during chat/channel/community creation - `Member`
- during group chat updates - `ChatMember`
- during community/channel updates - `CommunityMember`
They all are saved under one key - `members`

Can we union all of them into one structure during sending/returning data from status-go? I don't see a big difference between them, it just brings unnecessary complexity
I think we can just return one type 
```
ChatMember {
id
roles
joined
}
```

cc @jrainville @cammellos

**Comment by cammellos** [comment]
> Can we union all of them into one structure during sending/returning data from status-go? I don't see a big difference between them, it just brings unnecessary complexity
I think we can just return one type

I would keep things separate in terms of community vs private chats, at least at the struct level. 
I agree without you that are similar, but they will change for different reasons and product requirements (they already have 1 out of 3 fields different), though it's fine to make it consistent in terms of how to serialize them and/or re-use an embedded type if we want to.
If we add roles to private group chats, then probably it might be a good time to think about it.


In mobile we don't use `type Member struct {`, so that could be consolidated from our side. 
`CommunityMember` is also a protobuf definition, in theory we should not expose those to the client, since they are protocol specific.
