### ISSUE TITLE
Broken account issues

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#8902]
# Bug Report

Account broke after it got restored:
 - Work only 1-to-1 chats
 - Group chat does not receive messages from broken account. (nothing interesting in the logs)
 - App hangs on attempt to send message to community (also nothing interesting in the logs)
 - No history visible

## Steps to reproduce

1. Suspended dogfooding app to have only one instance running
2. Restored dogfooding account with current master status-desktop to test some stuff with AC notifications. 
3. Switched back to dogfooding app and after a while noticed that no one respond my messages
4. Restored dogfooding account with dogfooding app and got my acc finally broken

### Additional Information

- Operating System: Mac OS
- Ping me to get recovery phrase

**Comment by jrainville** [comment]
This was fixed by Andrea. Mishka's account works now
