### ISSUE TITLE
Chat: reactions are shown very close to the message if it ends with emojis

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8904]
# Bug Report

## Steps to reproduce
1. Go to any chat and write a message with the last line containing only emoji, send it
2. Add a reaction to your message
3. Check how far the reaction from the emoji

#### Expected behavior
The reaction is shown not very close to the emoji (as it works for a text)
#### Actual behavior
The reaction is shown very close to the emoji
<img width="500" alt="image" src="https://user-images.githubusercontent.com/14942081/209706313-7c1df1f6-c8c8-4ad3-af03-e7208a58ae21.png">

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macOS Monterey

**Comment by caybro** [comment]
I believe this has been fixed already; can you try in master pls @elina2015 ?

**Comment by elina2015** [comment]
Tested and it's not reproduced (0.9.0-beta)
