### ISSUE TITLE
The app icons are different for Mac and Windows

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8905]
# Bug Report

## Steps to reproduce
1. Instal the Desktop app on the mac
2. Install the Desktop app on Win 11
3. Compare the icons and their names

#### Expected behavior
The icons look similar and have the name 'Status'
#### Actual behavior
<img width="639" alt="image" src="https://user-images.githubusercontent.com/14942081/209729182-1ed01579-fe14-46d2-9c3e-01edb9895128.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/14942081/209729340-39a1dc95-9405-4125-b117-3cbf9c967982.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/8246
- Operating System: macOS Monterey, Win 11

**Comment by caybro** [comment]
How do you get the "Status.exe" tooltip on a mac? :D

**Comment by iurimatias** [comment]
@caybro seems like it's using https://www.parallels.com/ca/

**Comment by elina2015** [comment]
yep, I'm using Parallels for getting Win 11 on my macOS laptop
