### ISSUE TITLE
Windows: Cannot save a profile picture while onboarding

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8908]
# Bug Report

## Steps to reproduce
In Windows 11:
1. Go to register a new account
2. Upload an image as your profile picture
3. Go further and after completing the onboarding process check the profile picture

#### Expected behavior
The profile picture is saved
#### Actual behavior
The profile picture is not saved
### Additional Information

- Status desktop version: 0.8.1 and RC1 0.9.0
- Operating System: Windows 11

**Comment by jrainville** [comment]
I just tested on Windows 10 with latest master and it worked for me. Can you try again with the latest @elina2015 . Maybe it only happens in Windows 11?

**Comment by elina2015** [comment]
> I just tested on Windows 10 with the latest master and it worked for me. Can you try again with the latest @elina2015 . Maybe it only happens in Windows 11?

Hey Jo, I tested on Win 11 again and the bug is stably reproduced. Also, I found other places where the issue with storage access appeared. For example: https://github.com/status-im/status-desktop/issues/9020

**Comment by jrainville** [comment]
I tested again on Windows 10 with the latest master and it works as expected. I tested jpgs and pngs.

I think your VM doesn't handle image fetching correctly @elina2015 . @glitchminer can you test this issue as well to validate this theory?

**Comment by glitchminer** [comment]
Hi @jrainville @elina2015, I was not able to reproduce this with a jpg when running 0.9rc1 on Win 11 directly. Setting to closed.
