### ISSUE TITLE
No padding for input fields

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#8910]
# Bug Report

<img width="642" alt="Screenshot 2022-12-29 at 19 48 37" src="https://user-images.githubusercontent.com/2522130/209979480-7471ad25-cdd1-4bda-95a7-3a8d1aba489c.png">

## Description

No padding for input fields. By [designs](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2636%3A359221&t=EnSRibx9J7U1Yxlt-0) they should be 14 horizontal and 10 vertical

**Comment by caybro** [comment]
Bisected to 17aaec2d536f496c9defa54f020afddc55cadd66
