### ISSUE TITLE
Cannot return CurrencyAmount item from CurrentAccount view proc exposed to QML

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#8913]
# Bug Report

## Description

See https://github.com/status-im/status-desktop/pull/8911

For some reason, you cannot return a QVariant in a proc exposed to QML if the proc takes parameters (other than self). A compilation error occurs. 

This prevented me from passing the CurrencyAmount item to `[NetworkCardsComponent.qml](https://github.com/status-im/status-desktop/pull/8911/files#diff-2e942cade3306afbdf634f1872a19f214ebec38983d2caafa2cd589277619b9c) and [NetworksSimpleRoutingView.qml](https://github.com/status-im/status-desktop/pull/8911/files#diff-e9b9caee0b5901cce7d121099d6d7ca6cf2dc106999fccafd8f1ae692d6c8842). 

Similar problem in `src/app/modules/main/chat_section/view.nim`

Will need to investigate the root cause.

Fix the root cause, and remove the workarounds

**Comment by caybro** [comment]
Yeah this sucks... we have a similar thing here as well:

```nim
  # Since we cannot return QVariant from the proc which has arguments, so cannot have proc like this:
  # prepareChatContentModuleForChatId(self: View, chatId: string): QVariant {.slot.}
  # we're using combinaiton of
  # prepareChatContentModuleForChatId/getChatContentModule procs
  proc prepareChatContentModuleForChatId*(self: View, chatId: string) {.slot.} =
    self.tmpChatId = chatId

  proc getChatContentModule*(self: View): QVariant {.slot.} =
    var chatContentVariant = self.delegate.getChatContentModule(self.tmpChatId)
    self.tmpChatId = ""
    if(chatContentVariant.isNil):
      return newQVariant()

    return chatContentVariant
```

**Comment by dlipicar** [comment]
Ohh I couldn't find references to this problem in the code, thanks!
I'll replicate that workaround for now, and remove the hack when this (hopefully) gets fixed.

**Comment by caybro** [comment]
Well it won't be magically fixed unless someone with more nim-fu invests some time into making this work :)

**Comment by dlipicar** [comment]
I've seen a couple of instances where people have used JSON ser/des to pass objects to QML in such cases (see `getReplyMessageByIdAsJson`)

**Comment by caybro** [comment]
> I've seen a couple of instances where people have used JSON ser/des to pass objects to QML in such cases (see `getReplyMessageByIdAsJson`)

This has a major disadvantage: in such case it's not a regular property but a plain function call -> can't turn this into a QML binding
