### ISSUE TITLE
Chat input: can't send html text from the clipboard

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8919]
# Bug Report

## Description

As a user, I want to send any text from the clipboard  as it was copied (as a plain text)

## Steps to reproduce

1. Copy HTML text to the clipboard. Example
```
Hello, could you help me with understanding the problem
<Html>
<Head></Head><Body>test text
</Body></Html>
```
2. Paste to chat

#### Expected behavior

All paste text is displayed and visible after the send

#### Actual behavior

Text formatted and not displayed as it is

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macOS

**Comment by caybro** [comment]
Pretty sad... we already have the ClipboardProxy method to paste HTML :/ Or is this about pasting richtext as plain text?

**Comment by mprakhov** [comment]
> Pretty sad... we already have the ClipboardProxy method to paste HTML :/ Or is this about pasting richtext as plain text?

Pasting text as it is.
For example, you copy part of your HTML code and want to send it to someone, but it will be converted to rich text on the input

**Comment by caybro** [comment]
I see; I know it won't help on Windows, but I can do exactly this by pasting via the middle-mouse click :)

**Comment by caybro** [comment]
That bypasses our key press handlers, and uses the QML's component builtin handler

**Comment by jrainville** [comment]
In theory, we don't want to have to rely on a special shortcut or button, the normal paste should just work. If I copy the snippet above and paste in Discord normally, it appears as code and isn't parsed.

Any way we can do it as well? Maybe we need to convert to entities?

**Comment by caybro** [comment]
> In theory, we don't want to have to rely on a special shortcut or button, the normal paste should just work. If I copy the snippet above and paste in Discord normally, it appears as code and isn't parsed.
> 
> Any way we can do it as well? Maybe we need to convert to entities?

You really _do_ need a special shortcut. The way the clipboard works is that it may contain the same "contents" in multiple MIME formats (in this case `text/plain` and `text/html`). How do you tell the app which format to grab? We just happen to prefer HTML (rich text) but in this case we want a different format. Nothing to do with entities either

**Comment by jrainville** [comment]
> The way the clipboard works is that it may contain the same "contents" in multiple MIME formats (in this case text/plain and text/html). How do you tell the app which format to grab? We just happen to prefer HTML (rich text) but in this case we want a different format. 

Can we just always grab `text/plain` instead? I don,t think we want the html most of the time. When pasting a link, we format it ourselves for example

**Comment by caybro** [comment]
Hmm, it seems we're already doing this but it's probably broken :)

KeyPress:
```qml
        if (event.matches(StandardKey.Paste)) {
            if (QClipboardProxy.hasImage) {
                const clipboardImage = QClipboardProxy.imageBase64
                showImageArea([clipboardImage])
                event.accepted = true
            } else {
                messageInputField.remove(messageInputField.selectionStart, messageInputField.selectionEnd)

                // cursor position must be stored in a helper property because setting readonly to true causes change
                // of the cursor position to the end of the input
                d.copyTextStart = messageInputField.cursorPosition
                messageInputField.readOnly = true

                const clipboardText = globalUtils.plainText(QClipboardProxy.text)
                const copiedText = globalUtils.plainText(d.copiedTextPlain)
                if (copiedText === clipboardText) {
                    d.internalPaste = true
                } else {
                    d.copiedTextPlain = ""
                    d.copiedTextFormatted = ""
                    d.copiedMentionsPos = []
                }
            }
        }
```

and then KeyRelease:
``` qml
        if (d.internalPaste) {
            if (d.copiedTextPlain.includes("@")) {
                d.copiedTextFormatted = d.copiedTextFormatted.replace(/span style="/g, "span style=\" text-decoration:none;")

                let lastFoundIndex = -1
                for (let j = 0; j < d.copiedMentionsPos.length; j++) {
                    const name = d.copiedMentionsPos[j].name
                    const indexOfName = d.copiedTextPlain.indexOf(name, lastFoundIndex)
                    lastFoundIndex += name.length

                    if (indexOfName === d.copiedMentionsPos[j].leftIndex + 1) {
                        const mention = {
                            name: name,
                            pubKey: d.copiedMentionsPos[j].pubKey,
                            leftIndex: (d.copiedMentionsPos[j].leftIndex + d.copyTextStart - 1),
                            rightIndex: (d.copiedMentionsPos[j].leftIndex + d.copyTextStart + name.length)
                        }
                        mentionsPos.push(mention)
                        d.sortMentions()
                    }
                }
            }

            const prevLength = messageInputField.length
            insertInTextInput(d.copyTextStart, d.copiedTextFormatted)
            messageInputField.cursorPosition = d.copyTextStart + messageInputField.length - prevLength
            d.internalPaste = false
        } else if (event.matches(StandardKey.Paste)) {
            insertInTextInput(d.copyTextStart, QClipboardProxy.text)
            messageInputField.cursorPosition = d.copyTextStart + QClipboardProxy.text.length
        }
```

@alexjba has been working on this recently; any idea? :)

**Comment by caybro** [comment]
I did some more digging, and here's the TextEdit's paste() method:

```cpp
    if (source->hasFormat(QLatin1String("application/x-qrichtext")) && d->acceptRichText) {
        // x-qrichtext is always UTF-8 (taken from Qt3 since we don't use it anymore).
        const QString richtext = QLatin1String("<meta name=\"qrichtext\" content=\"1\" />")
                + QString::fromUtf8(source->data(QLatin1String("application/x-qrichtext")));
        fragment = QTextDocumentFragment::fromHtml(richtext, d->doc);
        hasData = true;
    } else if (source->hasHtml() && d->acceptRichText) {
        fragment = QTextDocumentFragment::fromHtml(source->html(), d->doc);
        hasData = true;
    } else {
        QString text = source->text();
        if (!text.isNull()) {
            fragment = QTextDocumentFragment::fromPlainText(text);
            hasData = true;
        }
    }
```

It's obvious that it prefers rich text over plain text
