### ISSUE TITLE
Contact request view doesn't show account's meta information

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8924]
Take a look at the screenshot below, where you can see a contact request popup that has opened after I've pasted a profile link into the start-chat input:

![Screenshot from 2023-01-02 13-39-24](https://user-images.githubusercontent.com/445106/210232687-abb42900-f075-4e36-8566-7997cd4d8526.png)

Notice how the popup does not render the letters inside the letter identicon and also doesn't show a display name.

My assumption is that this is happening because the account I've looked up hasn't been advertised to my node yet, so all contact related data (apart from the chatkey) isn't available yet.

We should probably, temporarily subscribe to the contact's channel and request contact info to be shown in the popup.

**Comment by jrainville** [comment]
Yeah. Maybe we need a loading state for when we are fetching the data too cc @benjthayer @juliaiskandarian

**Comment by imagiMary** [comment]
@jrainville and @0x-r4bbit - Please find below the skeleton loading state design and figma link for when the Send Contact Request dialog is opened for a user whose username and avatar image are not yet cached (which happens most frequently when a chat key or URL containing a chat key is directly pasted into the ‘start new chat’ field). 

[Figma Link](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=26972-518628&t=LNBc5i9pzU8cJFDw-4)

See design and what currently incorrectly happens below.  As soon as the ‘Send contact request’ dialogue appears, the identicon ring, chat key and emojihash should be immediately displayed.

| Design	       | Current Incorrect           |
| ------------- |:-------------:|
|  ![D0301 screenshot](https://user-images.githubusercontent.com/124154641/224391681-4e98daaf-7bc2-4db4-b431-f869c5717ddb.png) | ![D0301 current screenshot](https://user-images.githubusercontent.com/124154641/224391844-f362744e-a6c5-488d-89cd-ba7d26f84516.png) | 

&nbsp;
Once the user’s name and avatar image has been successfully fetched, the Contact Request dialog should look like the correct example below.

| Correct (for a user who hasn’t set an avatar) | Correct for a user that has set an avatar        |  Current Incorrect          |
| ------------------------------------------------ |:------------------------------------------------:|:--------------------------:|
| ![D0301 Correct Contact request dialog screenshot](https://user-images.githubusercontent.com/124154641/224392910-a1f8b05c-33ce-48ec-87f5-8eb199b415f4.png) | ![D0301 correct with avatar screenshot](https://user-images.githubusercontent.com/124154641/224392884-5794d744-9518-4722-ae99-56194812f2dc.png) | ![D0301 current screenshot](https://user-images.githubusercontent.com/124154641/224392808-3152686f-b949-4f6f-9c06-d1ff12a38496.png) |
