### ISSUE TITLE
Contacts list in create chat view automatically marks first item as selected

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8926]
I have two contacts and I want to start a new chat. So I enter the start-chat view. What I then see is this:

![Screenshot from 2023-01-02 15-20-41](https://user-images.githubusercontent.com/445106/210244093-4125f17c-045e-4966-a23f-f6004f9a4df8.png)

There's a list of my contacts, which is great, however, for some reason the first item is visually hovered/selected, which is unexpected.
It's feels especially weird when there's only one contact in the list.

**Comment by jrainville** [comment]
I don't see this as being a problem. It makes it possible to navigate the list using the up and down arrows. It's similar to the mentions list.

**Comment by 0x-r4bbit** [comment]
That's fair! I was not expecting this. Probably because this UI does not actually look like a suggestion box but simply the list of contacts (in which case there would be no reason to favour the first element over the others.

Feel free to close this if you think this doesn't need to be revisited.

**Comment by jrainville** [comment]
Closing as I don't feel this is a problem. If designers want this fix to be done, we can reopen
