### ISSUE TITLE
discord: crash when downloading discord history

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#8931]
# Bug Report

## Description

Went afk for a few, status-desktop seems to have caught the magnet link and started downloading the discord messages history. Segfaulted in the end :/

Backtrace: https://pastebin.com/raw/kRsDJxnV

### Additional Information

- Status desktop version: master (542a0b11f2708013ff9605d84936046ab967f3e4)
- Operating System: Linux

**Comment by caybro** [comment]
Happening quite frequently and while I'm at the computer, it makes it completely unusable after a really short time. The whole PC freezes and becomes unusuable for several minutes, resulting in status-desktop being killed by the OOM killer in the end:

dmesg:
```
[16828.253164] Out of memory: Killed process 74456 (nim_status_clie) total-vm:21708220kB, anon-rss:3005344kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:17120kB oom_score_adj:200
```

**Comment by 0x-r4bbit** [comment]
Really sorry for the pain.
As you know, there's an issue related to this here: https://github.com/status-im/status-desktop/issues/8857
I'll discuss next steps with @cammellos tomorrow

**Comment by anastasiyaig** [comment]
@caybro i was not able to search for this issue just because i tried to use some keywords from stacktrace and it did not show up in search results. U can close any of those 2 if they are the same :)
