### ISSUE TITLE
Cannot expose a float QtProperty, QML gets garbage values

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#8936]
# Bug Report

Trying to expose a `QtProperty[float]` results in the QML side getting garbage values. See https://github.com/status-im/status-desktop/blob/master/src/app/modules/main/communities/module.nim#L349
Investigate why this occurs, fix it if possible.

**Comment by caybro** [comment]
@dlipicar try with `float32`, I guess the QML's `real` type just overflows

**Comment by dlipicar** [comment]
> @dlipicar try with `float32`, I guess the QML's `real` type just overflows

I'll try, but it doesn't happen only with large values. There seems to be some problem with how the bits are interpreted, anything other than 0 gives you a weird value on the QML side.

**Comment by dlipicar** [comment]
It doesn't seem to like anything other than `float`

`/Users/dlipicar/repos/status-desktop/vendor/nimqml/src/nimqml/private/nimqmlmacros.nim(114, 14) Error: Unsupported conversion of float32 to metatype`

`/Users/dlipicar/repos/status-desktop/vendor/nimqml/src/nimqml/private/nimqmlmacros.nim(114, 14) Error: Unsupported conversion of float64 to metatype`

**Comment by caybro** [comment]
@dlipicar finally found it: there's an upstream bug (https://github.com/filcuc/nimqml/issues/42) and we need to backport/apply this upstream fix: https://github.com/filcuc/nimqml/commit/a8ae9cd4a5bb3b62c10cb4ce5dd6600fc3b9dcaf

**Comment by dlipicar** [comment]
@caybro cherrypicked here https://github.com/status-im/nimqml/pull/45

**Comment by caybro** [comment]
You still need to pull this fix into status-desktop

**Comment by dlipicar** [comment]
Yeah it autoclosed this issue with the nimqml PR.
Here's the one for this issue: https://github.com/status-im/status-desktop/pull/8963
