### ISSUE TITLE
Community: Cannot change the title, icon and description of general channel

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8938]
# Bug Report

## Steps to reproduce
1. Create a new community (public or private)
2. Open the 'general' channel for editing and change its title, icon, and description
3. Save and check the updates for the 'general' channel

#### Expected behavior
The updates are saved
#### Actual behavior
The updates are not saved
### Additional Information

https://user-images.githubusercontent.com/14942081/210434846-99ef4203-77ca-4583-a28b-aaaad18993f9.mov

- Status desktop version: 0.8.1
- Operating System: macOS Monterey

**Comment by borismelnik** [comment]
@elina2015 @jrainville fixed in current master

**Comment by jrainville** [comment]
I confirm
