### ISSUE TITLE
Community: Cannot open the link in the channel's description

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8939]
# Bug Report

## Steps to reproduce
1. Create a community
2. Create a new channel
3. Open the new channel for editing and add 'http://www.google.com' in the description
4. Save the updates and click on the link in the new channel description

#### Expected behavior
The modal suggesting the Status browser or system browser should appear and the user will be able to open the link
#### Actual behavior
Nothing happens (the cursor changed its view to a hand, but nothing is happening after the click on the link)
### Additional Information

https://user-images.githubusercontent.com/14942081/210435743-eca33251-57ce-43b9-b064-e567e6621800.mov

- Status desktop version: 0.8.1
- Operating System: macOS Monterey

**Comment by caybro** [comment]
> #### Expected behavior
> The modal suggesting the Status browser or system browser should appear and the user will be able to open the link

That modal for choosing the browser is already gone; nonetheless, the app should still open the link in an external browser. Need more logs/debug to be able to fix this

**Comment by caybro** [comment]
OK, I can reproduce that as well even in master
