### ISSUE TITLE
Community: Reactions are shown very close to the Github link preview

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8942]
# Bug Report

## Steps to reproduce
1. Go to any community and post a Github link
2. Add some reactions to the message

#### Expected behavior
Reactions are shown NOT very close to the Github link preview
#### Actual behavior
Reactions are shown very close to the Github link preview
<img width="389" alt="image" src="https://user-images.githubusercontent.com/14942081/210439417-21a7f5fe-371b-4e6a-8879-3398147437e8.png">

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macOS Monterey

**Comment by caybro** [comment]
@elina2015:
![image](https://user-images.githubusercontent.com/5377645/210440991-af7aece3-1732-4d07-ba61-5eaaa8937767.png)

One could argue the space could be bigger but it's there :) (aka works for me in master)

**Comment by alexandraB99** [comment]
@elina2015 could you please verify if it still happens in master?

**Comment by elina2015** [comment]
@caybro and @alexandraB99, thank you, I checked on the latest master and the bug is fixed.
