### ISSUE TITLE
Community: Stickers are not aligned in height

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8944]
# Bug Report

## Steps to reproduce
1. Open any chat or community and send different stickers there
2. Check how different stickers are centered by hight

#### Expected behavior
All stickers are centered by hight
#### Actual behavior
Stickers are not aligned in height
<img width="529" alt="image" src="https://user-images.githubusercontent.com/14942081/210453890-950c2ec2-fbba-4db5-a76a-28af8d765a73.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/14942081/210453953-e5f522b2-1404-4913-9907-3b9f7f036fd6.png">
<img width="257" alt="image" src="https://user-images.githubusercontent.com/14942081/210462689-af234b57-0bc0-4168-9347-206a3a840c35.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/14942081/210462861-4ddd21ba-2c07-40b9-ba8c-056676acdc04.png">

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macOS Monterey

**Comment by caybro** [comment]
Regression in master:

https://github.com/status-im/status-desktop/pull/9079#issuecomment-1404078695

**Comment by jrainville** [comment]
See message above by Lukas. To reproduce, post a github link and put text after.

If it doesn't work, try by setting the unfurl setting to false, post a link, post messages, then set the unfurl setting to true.

@alexandraB99

**Comment by alexandraB99** [comment]
probably not because of this PR but I'm looking into this

https://user-images.githubusercontent.com/31625338/214809383-56ee8627-69bd-46ef-bc19-7f2519663f08.mov

**Comment by caybro** [comment]
It's definitely this PR 😁 reverted locally and it fixed the issue

**Comment by alexandraB99** [comment]
what I'm saying is that it seems weird that [these changes ](https://github.com/status-im/status-desktop/pull/9308)break the message height, it seems the whole message layout sizing is broken. reverted respective changes, it should work now as before, PR: https://github.com/status-im/status-desktop/pull/9308
