### ISSUE TITLE
Contact Verification: the answer overlaps another text

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8950]
# Bug Report

## Steps to reproduce

1. Get a contact Verification request
2. Open the modal for answering
3. Answer the request with a long text
4. Check the saved text of the answer

#### Expected behavior
The answer doesn't overlap another text
#### Actual behavior
<img width="240" alt="image" src="https://user-images.githubusercontent.com/14942081/210483987-d1cc14b6-0c24-4d2b-9487-fc0b3f906e0a.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/releases/0.9.0-rc.1
- Operating System: macOS Monterey

**Comment by elina2015** [comment]
@MishkaRogachev the bug is still reproduced and the date became incorrect. Could you kindly check? 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/14942081/211455113-57abaed8-3e6d-405f-9a39-1bc6b3cd9a92.png">
Also, after changing the answer, the button is ovelapped with the text:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/14942081/211455301-e46bd0f9-025b-4883-ba03-b27719cabc80.png">

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev the bug is still reproduced and the date became incorrect. Could you kindly check? <img alt="image" width="501" src="https://user-images.githubusercontent.com/14942081/211455113-57abaed8-3e6d-405f-9a39-1bc6b3cd9a92.png"> Also, after changing the answer, the button is ovelapped with the text: <img alt="image" width="508" src="https://user-images.githubusercontent.com/14942081/211455301-e46bd0f9-025b-4883-ba03-b27719cabc80.png">

Oh, i messed up. I was expecting that it's inside notification, i'll create new PR for that
