### ISSUE TITLE
Chat: Messages sent earlier have disappeared

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8965]
# Bug Report

## Description

Sent messages earlier today. Some hours of usage later navigated to view chat history but the messages were not available. The messages still exist in the database. 

The messages reappeared after restarting the app but then some from a different chat appeared missing.

![image](https://user-images.githubusercontent.com/50769329/210610848-8e8b72ae-58bc-43bb-8162-14c1c916adc8.png)

@0x-r4bbit also reported that previously sent messages disappeared after upgrading to 0.9 and appeared again after restart. 

## Steps to reproduce

Unknown. After some time, previously sent messages disappeared.

#### Expected behavior

Messages in the database remain visible in the app.

#### Actual behavior

Messages are disappearing.

### Additional Information

- Status desktop version: 0.9
- Operating System: Mac

**Comment by jrainville** [comment]
@osmaczko hopefully this one is fixed by the other order and cursor fixes you're already working on

**Comment by osmaczko** [comment]
early observations: it happens for the channels with unread messages only
