### ISSUE TITLE
Notifications: The double notification 'Community imported' appeared

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8970]
# Bug Report

## Steps to reproduce
1. Register a new account
2. Open the 'test' chat
3. Check the appeared notifications
#### Expected behavior
The notification is not shown because the user didn't import a community
#### Actual behavior
The multiple notification 'Community imported' appeared
<img width="720" alt="image" src="https://user-images.githubusercontent.com/14942081/210704583-95183287-df61-4a4f-8d45-ebc8c8c92187.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/14942081/210695487-91c4538a-71a2-418b-a039-1e3e7615f98c.png">

### Additional Information

- Status desktop version: RC 1 0.9
- Operating System: macOS Monterey

**Comment by jrainville** [comment]
I think that's intentional from a previous feature, but it's very confusing.

IMO, we should only show this for communities the user intentionally wanted to import. So only when doing the import from key. cc @John-44 

Also, to whoever ends up doing this task, make sure we only import the communities once. Maybe use an array to store which communities we are importing to not do it twice or more.

**Comment by John-44** [comment]
> I think that's intentional from a previous feature, but it's very confusing.
> 
> IMO, we should only show this for communities the user intentionally wanted to import. So only when doing the import from key. cc @John-44
> 
> Also, to whoever ends up doing this task, make sure we only import the communities once. Maybe use an array to store which communities we are importing to not do it twice or more.

@jrainville yes correct, the "Community imported" notification should only appear when a user successfully imports a community manually by clicking "Import using key" and then pasting a community key into this dialogue.  And of course there should only be a single success notification when a user performs this action a single time.
