### ISSUE TITLE
Community Portal: the inactive communities are shown in the Community Portal

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8971]
# Bug Report

## Steps to reproduce
1. Go to the Communities Portal
2. Check the communities there

#### Expected behavior
All the communities in the Communities Portal are active and clickable
#### Actual behavior
Part of the communities are grey and not clickable
### Additional Information

- Status desktop version: RC 1 0.9
- Operating System: macOS Monterey

**Comment by jrainville** [comment]
This will be fixed with https://github.com/status-im/status-desktop/issues/7534. 
Closing as duplicate
