### ISSUE TITLE
[automation]: edit community test sometimes fails

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#8977]
# Bug Report

## Description

See this run: https://ci.status.im/job/status-desktop/job/branches/job/e2e/job/PR-8894/5/squishResults_230105_183641.585/webreport_230105_183641.585_linux-02/index.html

Fails at the step: Then the community overview name is "myCommunityNamedChanged" 

Error: Found the following text myCommunity Wanted: myCommunityNamedChanged

**Comment by noeliaSD** [comment]
I think it is a real bug in the app since in master when I try to edit the community name, it is not modifed:

https://user-images.githubusercontent.com/97019400/211762005-e044fbf8-14a2-4335-9585-999ee6b9e8f3.mov

**Comment by mprakhov** [comment]
@noeliaSD do you have a stable reproduce? Which version do you use?
I noticed, that when you click save - you have a micro scroll which I do not observe when I try to do the same

**Comment by mprakhov** [comment]
ok, this is a regression, on 0.9.0 everything works fine
cc @jrainville

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/status-desktop/pull/9108
