### ISSUE TITLE
Activity Center: the incorrect text appears if reply to @everyone mention

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8980]
# Bug Report

## Steps to reproduce
1. User A goes to the public chat and mentions @everyone
2. User B goes to the same public chat and replies to this message
3. User A check their Activity Center mentions

#### Expected behavior
The mention looks good (with the link to the public chat)
#### Actual behavior
The mention looks incorrect
<img width="298" alt="image" src="https://user-images.githubusercontent.com/14942081/210927161-ad9e4653-de01-43c6-b49b-ee53a63c9bb7.png">

### Additional Information

- Status desktop version: RC 1  0.9.
- Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
no public chats anymore in master
