### ISSUE TITLE
Activity Center: The public chat mentions are not shown in AC

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8981]
# Bug Report

## Steps to reproduce
1. User A and User B are mutual contacts
2. User A mention User B in the test public chat
3. User B opens Activity Center and check mentions

#### Expected behavior
There is a mention from a public chat from User A
#### Actual behavior
There is no mention from a public chat
<img width="527" alt="image" src="https://user-images.githubusercontent.com/14942081/210927644-c82786f8-3e67-4931-91d8-a26979771296.png">

### Additional Information

- Status desktop version: RC1 0.9.0
- Operating System: macOS Monterey

**Comment by jrainville** [comment]
This is by design. Also, public chats are going away in 0.10 or 0.11
