### ISSUE TITLE
Activity Center: The public chat replies are not shown in AC

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8982]
# Bug Report

## Steps to reproduce

1. User A replies to User B in the test public chat
3. User B opens the Activity Center and checks Replies

#### Expected behavior
There is a reply from the test public chat
#### Actual behavior
There are no replies from the test public chat
<img width="534" alt="image" src="https://user-images.githubusercontent.com/14942081/210930786-217b5fc2-d736-4d1f-bc29-b17372f3542b.png">

### Additional Information

- Status desktop version: RC 1 0.9.0
- Operating System: macOS Monterey

**Comment by jrainville** [comment]
This is by design. Also, public chats are going away in 0.10 or 0.11

**Comment by John-44** [comment]
Yes, all public chat functionality is scheduled to be removed in 0.10 https://github.com/status-im/status-desktop/issues/8504
