### ISSUE TITLE
Community: Cannot re-order community categories within drag & drop

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8983]
# Bug Report

## Steps to reproduce
1. Create a community with a few categories
2. Try to re-order them by drag & drop

#### Expected behavior
Can re-order community categories within drag & drop
#### Actual behavior
Cannot re-order community categories within drag & drop
### Additional Information

- Status desktop version: RC1 0.9.0
- Operating System: macOS Monterey

**Comment by jrainville** [comment]
Dplicate of https://github.com/status-im/status-desktop/issues/3364
