### ISSUE TITLE
By default, links in messages should be opened by the System Default Browser

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#8993]
When a user with a fresh install of Status Desktop clicks on a URL in a message, by default the URL should open in the system default browser. 

No dialogue asking the user if the URL should be opened in Status or in the system default browser should be displayed.

In a fresh install of Status desktop, this default setting should be reflected in the Settings/Messaging screen (the 'Open message links with:' setting)

This is because the MVP release of Status Desktop won't include the browser.

**Comment by caybro** [comment]
@John-44 this should be already the case in master (0.9 too); is it not the case?
