### ISSUE TITLE
Chat: members list is 0 in group chats, mentions selector is not working

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8998]
### Description

<img width="968" alt="Screenshot 2023-01-09 at 12 02 02" src="https://user-images.githubusercontent.com/82375995/211272157-02a6b0d4-627e-494e-8650-68bb2d9ec07b.png">

1. install 0.8.1 and have some data folder (be added to some groups )
2. upgrade to 0.9.0 RC 1
3. check the groups

As result the members list is empty. mentions are not working

**Version**: 0.9.0 RC1 for mac https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.9.x/1/
**OS**: macOS Ventura 13.0 (22A380)

**Comment by caybro** [comment]
Also seeing this in our UI Team group chat but it's kinda random; sometimes the Members list is empty, sometimes it works on app restart. Communities are not affected

**Comment by jrainville** [comment]
This has been fixed by @mprakhov already (https://github.com/status-im/status-desktop/pull/8959). If you experience it on master, do reopen
