### ISSUE TITLE
Chat: can't send a standalone picture as a message, a corresponding text is required

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8999]
### Description

1. Open a chat (community chat for ex)
2. Click image button and select a picture to be send
3. Try sending the picture without text

As result, sending standalone pic is not really possible

<img width="744" alt="Screenshot 2023-01-09 at 12 53 00" src="https://user-images.githubusercontent.com/82375995/211281513-b3290f7f-55c2-41bc-8ee5-10c41701eb11.png">

**Comment by caybro** [comment]
cc @mprakhov
