### ISSUE TITLE
Windows: The error 'Illegal storage access' appeared and app crashed when searching a public chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9020]
# Bug Report

## Steps to reproduce
1. Sign up a new user
2. Go to search a public chat 'test' in the chat search field
#### Expected behavior
The chat is found correctly
#### Actual behavior
The error about storage  is shown and after click on 'x' for closing the error message the app is closed:
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/14942081/211439378-8b8e7717-ef77-4d5a-897f-57d02c7d40d5.png">

### Additional Information

- Status desktop version: RC1 0.9.0
- Operating System: Win 11

**Comment by anastasiyaig** [comment]
no public chats in master anymore
