### ISSUE TITLE
Wallet: Wallet back button disappears when switching between settings sections

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9033]
### Description

<img width="1626" alt="Screenshot 2023-01-10 at 17 34 52" src="https://user-images.githubusercontent.com/82375995/211581652-a8840196-5674-4cbf-bd5a-af118bbc3c70.png">

<img width="1626" alt="Screenshot 2023-01-10 at 17 42 10" src="https://user-images.githubusercontent.com/82375995/211581760-0976e5e0-00cd-48c6-b7d5-30c3adade4d1.png">

Steps:

1. create account in status
2. enable wallet
3. go to wallet and generate new account
4. go to settings -> wallet and select your status account
5. click Communities section in Settings
6. click Wallet section in settings

**As result:**
- previously selected wallet account is still shown as selected
- Wallet back button at the top left is gone

**Comment by caybro** [comment]
Ah yes, I fixed this with https://github.com/status-im/status-desktop/pull/8794 :)
