### ISSUE TITLE
Preferred ENS usernames should depend on the network

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#9035]
This is a continuation of https://github.com/status-im/status-desktop/issues/3234.

Now, when we store the network of each ENS username, we should also store preferred ENS username on each network.
This could be done with a separate database table or a `pending` column in newly created `ens_usernames` table.

**Comment by igor-sirotin** [comment]
To update, not sure if this is an important feature. 
@John-44, what do you think of this?

**Comment by John-44** [comment]
> To update, not sure if this is an important feature. @John-44, what do you think of this?

I think this should be placed on hold until we start work on the big ENS integration redesign/rebuild, which will only start after all design items for both Mobile and Desktop MVP are complete

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/10439
