### ISSUE TITLE
Chat: Message time no longer shown in group / 1x1 chat

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9037]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/11926403/211630620-00422570-16d1-460c-9f51-2a2bd54181c5.png)

Next to the dot, there should be the time of the message, but it no longer shows.

### Additional Information

- Status desktop version: master (321496c80732eefe41f982d5dfd791e7bf119cae)

**Comment by caybro** [comment]
Weird, I and @alexjba did some changes there recently; however I can't reproduce in master. I can have a look if you want @jrainville

**Comment by jrainville** [comment]
I just rebuilt everything from scratch just to be sure and I can still reproduce.

Here are the culprit logs:
```
Warning: qrc:/StatusQ/src/StatusQ/Components/StatusMessage.qml:67: Error: Qt.formatDateTime(): Invalid arguments (qrc:/StatusQ/src/StatusQ/Components/StatusMessage.qml:67, )
Warning: qrc:/StatusQ/src/StatusQ/Components/StatusMessage.qml:66: Error: Qt.formatTime(): Invalid arguments (qrc:/StatusQ/src/StatusQ/Components/StatusMessage.qml:66, )
```

@caybro thanks for the proposition. If you have nothing else, feel free, but otherwise, it's ok to let Boris do it since he doesn't have much on his plate so far.

**Comment by anastasiyaig** [comment]
@jrainville i am able to see the timestamp in community channels but it is indeed missing in the group chats / private chats

<img width="1444" alt="Screenshot 2023-01-11 at 10 05 49" src="https://user-images.githubusercontent.com/82375995/211739937-550a3750-7f21-429c-8a83-6c134173be9b.png">

**Comment by caybro** [comment]
OK, my bad (also Qt BAD!) The method changed signature between 5.14 and 5.15, will fix :) https://doc.qt.io/archives/qt-5.14/qml-qtqml-qt.html#formatDateTime-method vs. https://doc.qt.io/qt-5/qml-qtqml-qt.html#formatDateTime-method
