### ISSUE TITLE
Chat - Is it possible to paste images larger than 10MB

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#9053]
# Bug Report

## Description

Found during https://github.com/status-im/status-desktop/pull/8974

## Steps to reproduce

Add large image to clipboard (over 10MB), paste into chat. Example image: https://upload.wikimedia.org/wikipedia/commons/e/e6/Clocktower_Panorama_20080622_20mb.jpg

#### Expected behavior

Message cannot be sent as image is too large (same as adding image using image button)

#### Actual behavior

Message can be sent

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-8974/4/
- Operating System: Mac

**Comment by iurimatias** [comment]
@glitchminer this works because the app compresses the image

**Comment by glitchminer** [comment]
@iurimatias, in that case is it a bug that the same image cannot be sent using the add image button, perhaps because it's not compressed?
