### ISSUE TITLE
Chat description bleeds into chat toolbar action buttons

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#9056]
See here:

![Screenshot from 2023-01-11 14-38-00](https://user-images.githubusercontent.com/445106/211820576-2e79621e-ab9d-4b65-8137-8b25afe5bc06.png)

**Comment by iurimatias** [comment]
note: deja vu, this might be a duplicate or already fixed

**Comment by caybro** [comment]
Yeah, there's another BR about this, can't find it now :/

**Comment by 0x-r4bbit** [comment]
This is on top of 0.9.0rc-1
I think we should really stop cherry-picking commits into releases.
We've been creating too many duplicates of issues that are already fixed in master, simply because those fixes didn't make it into the release (but were in master already)

**Comment by caybro** [comment]
> This is on top of 0.9.0rc-1 I think we should really stop cherry-picking commits into releases. We've been creating too many duplicates of issues that are already fixed in master, simply because those fixes didn't make it into the release (but were in master already)

I agree but this has been a long standing issue, even before 0.9 or 0.8

**Comment by alexandraB99** [comment]
Could this https://github.com/status-im/status-desktop/issues/8884 be related?

**Comment by caybro** [comment]
> @0x-r4bbit Could this #8884 be related? it looks like a duplicate, if you agree feel free to close this issue

yeah, that's the one! :)

**Comment by 0x-r4bbit** [comment]
@alexandraB99 I guess it depends. #8884 refers to actions buttons having a transparent background. But even if that was fixed, channel descriptions would still bleed into them.

We should restrict the description area. Something like:

```
[    DESCRIPTION AREA     ] [ ACTION BUTTONS]
```

Regardless of what's the background color of those buttons.

**Comment by alexandraB99** [comment]
@0x-r4bbit correct, so this task could fix both things, in theory

**Comment by alexandraB99** [comment]
@caybro please align with @benjthayer regarding background color and text truncation

**Comment by caybro** [comment]
@benjthayer any design guidelines what the behavior should be here?

**Comment by benjthayer** [comment]
@caybro I believe the behaviour we're seeing there was intended to be an interim fix by @micieslak to address the issue of the channel description going over the top of the icon buttons and making them non-interactive:
https://github.com/status-im/status-desktop/pull/7783#pullrequestreview-1135566048

As per @0x-r4bbit's comment above, we should perhaps explore truncating or wrapping the channel description so that when we reach the app's min width, the description is either still visible or accessible via a tooltip/other mechanism.

Something we can explore for sure. Will update when I have something to review.

**Comment by caybro** [comment]
> @caybro I believe the behaviour we're seeing there was intended to be an interim fix by @micieslak to address the issue of the channel description going over the top of the icon buttons and making them non-interactive: [#7783 (review)](https://github.com/status-im/status-desktop/pull/7783#pullrequestreview-1135566048)
> 
> As per @0x-r4bbit's comment above, we should perhaps explore truncating or wrapping the channel description so that when we reach the app's min width, the description is either still visible or accessible via a tooltip/other mechanism.
> 
> Something we can explore for sure. Will update when I have something to review.

@benjthayer cool, thanks for the heads up; I also think @0x-r4bbit suggestion is sensible and imo we could just elide the channel title/subtitle to fit the available width
