### ISSUE TITLE
Implement mentions anchor button

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#9069]
implement: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=14632%3A460085&t=TutNfrQjOOp9nIUF-0

**Comment by iurimatias** [comment]
@osmaczko removing this from 0.10.0

**Comment by osmaczko** [comment]
@iurimatias FYI: https://github.com/status-im/status-desktop/issues/7488#issuecomment-1378876678

**Comment by jrainville** [comment]
Iuri hast he last say on this lol.
We want to focus performance in 0.10
