### ISSUE TITLE
Seeing a new community link in a channel shouldn't fetch anything from it apart from the metadata

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9073]
# Bug Report

## Description

Iuri just experienced a case where he joined `#test` and there were a lot of community links and then he got a lot of those calls:

```
DBG 2023-01-11 15:38:02.780-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=8361757 file=core.nim:20 rpc_method=wakuext_messageByMessageID
DBG 2023-01-11 15:38:02.781-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=8361757 file=core.nim:20 rpc_method=wakuext_emojiReactionsByChatIDMessageID

DBG 2023-01-11 15:38:07.065-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=8361757 file=core.nim:20 rpc_method=chat_getMember
```

If this is indeed what happened, we need to fix it.

We should only fetch the metadata of the community, ie name, description and member count.

Only when the community is spectated do we want to get more details like the messages.

**Comment by 0x-r4bbit** [comment]
I've just tried this and I experience the same. **However** judging by the logs, I don't think what you guys describe here is really what's happening.

This
```
DBG 2023-01-11 15:38:02.780-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=8361757 file=core.nim:20 rpc_method=wakuext_messageByMessageID
DBG 2023-01-11 15:38:02.781-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=8361757 file=core.nim:20 rpc_method=wakuext_emojiReactionsByChatIDMessageID
```
Seems to be happening for every message in the channel.

And this one:
```
DBG 2023-01-11 15:38:07.065-05:00 NewBE_callPrivateRPC                       topics="rpc" tid=8361757 file=core.nim:20 rpc_method=chat_getMembers
```

Seems to be called once upon joining the channel as well. I also see it a second time after all emoji reactions where requested.
This seems unrelated yet to whether the messages contain community invites.

Then, I do see a bunch of

```
DBG 2023-01-17 14:46:07.293+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=2683851 file=core.nim:20 rpc_method=wakuext_requestCommunityInfoFromMailserver                   
DBG 2023-01-17 14:46:07.327+01:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=2683852 file=threadpool.nim:92 messageType=AsyncRequestCommunityInfoTaskArg:ObjectTyp
e threadid=11 task="{\"$type\":\"AsyncRequestCommunityInfoTaskArg:ObjectType\",\"communityId\":\"0x03ec4ee5fe1684254bb3486df8176eeae9ae847ce66067bfd9337129cef0328bfe\",\"vptr\":94332371200128
,\"slot\":\"asyncCommunityInfoLoaded\",\"tptr\":94332345954896}"    
```

Which we get once per shared community ^ This seems correct so far

There's no new `chat_getMembers` call after that.
So It seems this was a misinterpretation.

I assume the `chat_getMembers` call is just a standard procedure for every channel we join. We could probably remove that call if the chat is a public channel ( we want to get rid of those inside Status anyways), but other than that, it doesn't look like we're fetching more information than needed. 

The community info requested from mailservers are also just community description, so it's just metadata.

**Comment by jrainville** [comment]
According to Pascal's findings, only the members call is not ok for a public chat, and public chats are going away as part of https://github.com/status-im/status-desktop/issues/8504, so we should be ok.

Closing for now. Reopen if we experience something similar again
