### ISSUE TITLE
Define possible data load failure scenarios for wallet 

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#9077]
Skeleton loading states are currently being developed for wallet via the following issue:
https://github.com/status-im/status-desktop/issues/7661#issuecomment-1378622237

In order to design the counterpart load failure states for these, we need to first define the potential load failure scenarios we wish to support for wallet.

Once we have a comprehensive list of ways in which a page, tab or list item may fail to load, we can design a solution that is extensible to all scenarios and considered for all platforms.

The below questions are the kinds of things it would be great to know but as much detail as possible would be ideal: 

- Can there be an entire page load failure? Eg you tap on wallet and nothing loads
- Can the contents of an entire tab fail to load? Eg you tap on Assets, Collectibles or Activity and nothing loads.
- What matrix of load failures do we need to support for each asset, collectible and activity item? If some of the data fails to load do we show the entire item as failing to load or should we show what has loaded and present an error for each of the data points that has failed to load? Eg could the collectible name load but not the thumbnail or vice vera? For assets, could the token name and logo load but none of the data or vice versa?. Or could the asset name, logo and quantity load but not the % change? Is it possible for us to know the user has a certain number of assets but no data for any of them load?

Also, should the user encounter a data load failure, what are the actions we can invite them to take? Is it possible/worthwhile providing a 'Retry' / 'Reload' action. What other things should they check/try before they do: that they are connected to the network/check peers/ restart app etc?

@alaibe 
@Khushboo-dev-cpp 
@stefandunca 
@dlipicar

**Comment by Khushboo-dev-cpp** [comment]
@benjthayer thanks for creating this. I am adding all the scenarios I can think for wallet load failures below -

Reasons for failure in loading:
1. Calls to Infura exhausted for the day
2. Infura is down
-  No assets values for an account
-  No new history fetches ?
-  Send/Bridge not possible
4. Opensea is down
- No collectibles listed at all
5. Crypto compare is down
- Market values will not be loaded on main page and details page
6. Any if the above are not available in current location of user we have seen this with opensea. 
I am sure I may be missing some more scenarios. Please add more @alaibe ?

**Comment by alaibe** [comment]
I think @Khushboo-dev-cpp covered all the possible cases

* Can there be an entire page load failure? Eg you tap on wallet and nothing loads

No, but the data won't be meaningful, like all the balance being empty, I believe better to not display something if it is wrong value

* Can the contents of an entire tab fail to load? Eg you tap on Assets, Collectibles or Activity and nothing loads.

Yes, they can except Assets but we currently display wrong values

* What matrix of load failures do we need to support for each asset, collectible and activity item? If some of the data fails to load do we show the entire item as failing to load or should we show what has loaded and present an error for each of the data points that has failed to load? Eg could the collectible name load but not the thumbnail or vice vera? For assets, could the token name and logo load but none of the data or vice versa?. Or could the asset name, logo and quantity load but not the % change? Is it possible for us to know the user has a certain number of assets but no data for any of them load?

For the assets, it can be from two sides: either the balance or the price
For the collectible: only opensea
For the activity: I think it can be impacted only by infura

**Comment by alaibe** [comment]
Also we can define error per network. e.g optimism up but arbitrum down, in that case we will have partial information

**Comment by benjthayer** [comment]
Hi @alaibe @Khushboo-dev-cpp @John-44 the load fail states for the wallet are now complete in the Kuba file. Thanks for your help! :)

Do let me know if you feel there are any other load fail states we should cover off.

https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=11239%3A151730&t=vH9NZuOTnhrDwGeT-4
