### ISSUE TITLE
[Community Permissions] Implement basic SNT Permission backend

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9086]
### Description

Start of the backend work for the permissions.

Here is the Figma design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A480020&t=vSq2M0qiqm2EG3Qh-0

**Important**: the goal of this task is **not** to implement the Figma above, but rather to prepare the backend that will hook into that front-end.

To this end, you can use a placeholder front-end with only a button saying "Add Basic SNT Permission" that will add that permission to the community in the backend and propagate it.

Basically, the backend should have the new properties to accept permissions, but we can start with only SNT. 
So it would require that users must have 1 SNT (on testnet to start) to be able to join.
No need to implement the periodic checking of the users on the admin side yet.
Only add the permission and make sure it is propagated to users. No need to implement the blocking on the user side yet, it will be done in another task.

When doing the backend, make sure to make the API and Permission Objects extendable so they can later support all the customization seen in the Figma above. Feel free to talk to Alisher and Andrea for more info on the feature design (Alisher) and on the best way to implement it (Andrea).
For questions about contracts, you can ask Michal and Andrea Franz.

Better to make small increments so we can have people look at it fast and soon, so no work is wasted. Feel free to add TODOs for anything that is out of scope of the basic feature, but will be extended.

### Acceptance Criteria

1. Admin has a button that can be clicked that adds the "Needs to have 1 SNT to join this community"
2. Once that button is clicked, that permission is saved in the community (DB) and shared to other users who also save it
    - The other users will not yet have the UI for that, but we can do a log with a TODO to prove that it works
3. When the permission is there, the Admin has access to the opposite button to remove the permission
4. Once the Remove  button is clicked, the same happens as in step 2, but the permission is removed

**Comment by noeliaSD** [comment]
You can take a look at  `AppLayout/Chat/stores/CommunitiesStore.qml` as a base file to understand which are the model roles the UI is expecting. It will also help with the integration with the ui.

**Comment by 0x-r4bbit** [comment]
This issue can be closed as creating/editing and removing permissions works.
