### ISSUE TITLE
Refactor Members list to only have one list per community

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9090]
### Description

Right now, we create a `users` module for each `chat_content`, ie each Channel.
It makes sense for personal chats (group, 1-1, public), but for communities, it creates a lot of duplication of data in memory.

Do note however, having an individual list of members for community private channels will be needed in the future.
With the new Permissions, some channels will only accept users with certain conditions, so **those** particular channels will need a per chat users module.

Still, most communities and most channels in a community will be "normal" and share the exact same members, so we can easily do a performance and memory improvement here.

It's just not straightforward, because we'd need to maybe share a reference to the main users module to the different chat ones, so as not to create a brand new user module each time.

To the person working on it, please share ideas and designs before working on it so some of us can look at them and see if they are feasible.

**Comment by mprakhov** [comment]
So right now I see 2 solutions:

1. Make the user module shared between all the channels in the community (as I understood, we can reach it in min via new() + ref). In this case, the user's module will be kept on the heap, not the stack. 
Cons: Using a heap always has a risk of crashes

2. Community channels can contain or not contain a users module and the users module should live in the community channel too. 
- If the community channel does not have a users module - a community users module is used
- If the community channel has a users module - UI is using a chat users module, if not - channel users module (for community  private channels)

Current qml code for detecting if we should display the member's list:
qml code
```
usersModel: {
                let chatContentModule = root.rootStore.currentChatContentModule()
                if (!chatContentModule || !chatContentModule.usersModule) {
                    // New communities have no chats, so no chatContentModule
                    return null
                }
                return chatContentModule.usersModule.model
            }
```

**Comment by endulab** [comment]
Adding the logic of choosing modules in qml seems to be wrong for me. We should do this in nim code.
I checked briefly the code and it seems that:
- in main module for each channel group we create chat_section_module, that means that every community has its own chat_section_module
- every chat_section_module has some submodules (channels) and for every submodule chat_section_module creates chat_content_module
- every chat_content module creates users_module
- users module is exposed to qml via QProperty by chat_content view (channel).

It means that chat_section_module (community) should contains its own 1 instance of users_module which should be passed down to submodules (channels). In case of very specific channels we can create more users modules.

![image](https://user-images.githubusercontent.com/61889657/213125419-f11d32d7-27e9-430a-a689-57315187c47a.png)

**Comment by holiday-coder** [comment]
@endulab does it mean that you propose to use the first solution - share the community users_module between it's chat_content modules?

**Comment by mprakhov** [comment]
@endulab does it mean that you propose to use the first solution - share the community users_module between it's chat_content modules?

**Comment by jrainville** [comment]
Michal's solution makes sense as well. I wouldn't mind going with that one either

**Comment by endulab** [comment]
> @endulab does it mean that you propose to use the first solution - share the community users_module between it's chat_content modules?

Yes, This way we do not have to change QML.
