### ISSUE TITLE
Chat: Message shown as "Sending" even after being replied to

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#9095]
# Bug Report

## Description

A message sent in the desktop channel was shown as "Sending" even after it had been replied to.

![image](https://user-images.githubusercontent.com/50769329/212178650-8322282d-9716-49df-a1af-f5d3f6440b8f.png)

## Steps to reproduce

Unknown. Have only seen this once after sending a message in a channel

#### Expected behavior

"Sending" only appears when actually sending

#### Actual behavior

See description.

### Additional Information

- Status desktop version: Master or recent CI build (12/01)
- Operating System: Mac

**Comment by jrainville** [comment]
I'll close this. I don't think it was experienced lately, plus it's mostly connection dependent. I think we show this is the store node doesn't ack our message, but we cannot know if actual peers received them.

Feel free to reopen this if it ever happens again
