### ISSUE TITLE
Advanced setting to enable features on testnet

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#911]
In status-react, you can't buy stickers or register ens usernames in ropsten. In the desktop app ENS are currently disabled on testnet, but you can still buy stickers. It would be nice to have the same behavior as status-react to not allow buying stickers in ropsten either, but also have a toggle button in the advanced settings that would allow buying stickers / registering ens usernames while being on ropsten

**Comment by alaibe** [comment]
Sync with Richard: 
Stickers: we just need to work on the front end
ENS: Find the address
