### ISSUE TITLE
[Performance] Improve Reply message author detail fetch

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9112]
### Description

Right now, when there is a reply message, we get the details for the author of the replied message using the pubkey only and calling the backend to get JSON. That's very inefficient, as we need to do a back and forth and then parse the data.
Plus, I needed to do a iterator property just to tell the frontend to call the JSON again.

One way I realized that will improve that a lot is to just populate it all in the backend (in the module most likely).
We just need to use the new properties Pascal added here: https://github.com/status-im/status-desktop/pull/9111/files#diff-4f86d004be69cc9b51a70273a5ec7ab80e851a4231773dad079e8c01afa753b5R53-R54

When we detect that the author was updated (the model already has `modelContactUpdateIterator` taht is called in those situations), we just update the details directly instead of relying on the iterator.

**Comment by jrainville** [comment]
This is probably already done by @0x-r4bbit and @alexjba 's PRs, but make sure it is.

**Comment by 0x-r4bbit** [comment]
Correct, this seems to be done already.
