### ISSUE TITLE
App crash fixed, but maybe worth giving another round of investigation

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#9115]
This issue https://github.com/status-im/status-desktop/issues/9065 should be fixed in this PR [commit](https://github.com/status-im/status-desktop/pull/9023/commits/9eb02ac7daae26a446995604a7e59270e8653f2b). 

What's done there is locking the table and guard it if multiple wallet accounts are added in a row, what causes `buildAllTokens` proc to be called multiple times with the time diff of few ms. That fix fixed the issue I was able to reproduce, not always, but many times. After it I haven't reproduce it ever.

Why I am opening this issue is that my understanding is that async jobs on the Nim side are done in a separate thread, when the job is done, corresponding slots should be called with the affinity of the main thread. Because of that this fix works, but maybe it's worth having another look and maybe search for the real origin of that crahs.

**Comment by alaibe** [comment]
Working as expected now, the fixed work
