### ISSUE TITLE
Add account modal - generate address button update

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#9119]
In the add account modal button for generating address based on the derivation path (enter password/pin) should not have an icon on the left and the text of it should be "Preview address"

![AddAccount1](https://user-images.githubusercontent.com/86303051/212417767-492d1bf5-9fb9-4e8e-a9e5-5906ae67a8cf.png)

**Comment by anastasiyaig** [comment]
the title of the ticket is barely understandable @alaibe @saledjenic can u guys adjust to reflect the true goal of the task?

**Comment by saledjenic** [comment]
@anastasiyaig please check now, if you don't like it, please update/name it as you would like to see it.

**Comment by anastasiyaig** [comment]
It is amazing now , thanks! It is not a matter of my personal preference, i was just confused reading the title initially (and i assume it was not clear to everyone else without opening the ticket and reading it )

**Comment by saledjenic** [comment]
I agree it was confusing to me as well when I read it now. 😄
