### ISSUE TITLE
UI: window titlebar added instead of frameless window

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9126]
### Description

at the top left there are exapand collapse buttons for left pane

<img width="1512" alt="Screenshot 2023-01-16 at 12 33 37" src="https://user-images.githubusercontent.com/82375995/212654422-4a617040-fb87-4bd8-80da-1c5a89d5b4ea.png">

**Comment by anastasiyaig** [comment]
@alexandraB99 ^ please prioritise

**Comment by anastasiyaig** [comment]
@caybro actually no, it happens on login screen too and for recovered account as well

<img width="1512" alt="Screenshot 2023-01-16 at 13 30 47" src="https://user-images.githubusercontent.com/82375995/212657232-1ebf8887-a3c6-443e-9fe3-90a20a943ada.png">

**Comment by MishkaRogachev** [comment]
<img width="433" alt="Screenshot 2023-01-17 at 12 41 33" src="https://user-images.githubusercontent.com/2522130/212850521-fa8c79a2-fe8b-4a28-aefb-102ddfaa2025.png">
for me it also always visible as well
