### ISSUE TITLE
Messaging: Can not connect to mailserver error is appearing constantly when recovering a seed 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9131]
### Description

1. in latest master for example commit f8c4682885c0165799ce1796ecf8fb31a1f38992 recover account with any seed u know
2. wait a bit

As result, there is a constantly appearing mailserver error

<img width="1512" alt="Screenshot 2023-01-16 at 13 21 38" src="https://user-images.githubusercontent.com/82375995/212678475-e0652e5d-71c8-4bd4-9b09-b7d159f013b6.png">

**Comment by anastasiyaig** [comment]
@glitchminer if u have any other details, please share

**Comment by anastasiyaig** [comment]
@jrainville @richard-ramos

**Comment by igor-sirotin** [comment]
Maybe it's time to (at least) move this to a top banner?
https://github.com/status-im/status-desktop/issues/6213

**Comment by caybro** [comment]
> Maybe it's time to (at least) move this to a top banner?
> 
> * [Move mailserver disconnect notification to app's banner line #6213](https://github.com/status-im/status-desktop/issues/6213)

Fully agree; the shortcoming with the current "modal dialog" approach is that it gets duplicated ad infinitum
