### ISSUE TITLE
Pressing the Up arrow when editing a message loses the cursor 

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9139]
# Bug Report

## Description

If you're in edit mode of a message and press the up arrow, the field loses focus and you need to re-click on it.

The same goes for going in edit mode using the up arrow when you're in the normal chat input. So doing up arrow twice loses the focus.

### Additional Information

- Status desktop version: Master (`93c90b84362c6a1baaeb6d24cdc25d200a148bae`)

**Comment by jrainville** [comment]
@caybro I tested again on latest master and I can reproduce.

This bug is not when ending the edit, it's when you are in the process of or at the start. try pressing up arrow when editing, the cursor just disappears (the edit field loses focus)

**Comment by caybro** [comment]
> @caybro I tested again on latest master and I can reproduce.
> 
> This bug is not when ending the edit, it's when you are in the process of or at the start. try pressing up arrow when editing, the cursor just disappears (the edit field loses focus)

Ah right, so that's a different code path

**Comment by 0x-r4bbit** [comment]
So, I think what's happening here is something different. The input doesn't seem to really lose focus.
Because of you hit arrow-down after arrow-up, you'll see the cursor again.
It's as if you moved the cursor up a line and then moved it down a line again. The upper line then however isn't visible.

**Comment by alexandraB99** [comment]
@jrainville I cannot reproduce this on master, could you please check again?

**Comment by jrainville** [comment]
I can reproduce still. See the video attached. I pressed up arrow, then played some more with the arrows and the focus was lost and the window scrolled for no reason
[Screencast 2023-02-20 12:27:55edit.webm](https://user-images.githubusercontent.com/11926403/220169901-38b9a29f-9967-4b58-ab61-4b86ea151620.webm)
