### ISSUE TITLE
Check Windows packaged build's resistance to tampering

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/status-desktop#914]
This is a bit difficult or maybe impossible without a real code signing certificate and signed builds in CI.

Try swapping an unsigned `.dll` / `.exe` inside the `bin/` folder of a signed packaged build (the `.exe` and `.dll` files are all signed, and those are the only file types that are signed).

The expected result is that Windows will report the app is damaged or tampered with and won't run it. This may involve using additional compiler flags, I'm not certain at present, see: https://docs.microsoft.com/en-us/cpp/build/reference/integritycheck-require-signature-check?view=vs-2019

**Comment by iurimatias** [comment]
https://github.com/status-im/status-desktop/issues/914
