### ISSUE TITLE
Reactions popup misbehaves 

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#9144]
# Bug Report

The reactions popup appears on the top left corner of the app and disappears immediately.

https://user-images.githubusercontent.com/33099791/212743058-7e6b5b9c-dcdf-4eb1-80b8-37461fdad3fa.mp4

- Status desktop version: 0.9.0 RC2
- Operating System: Ubuntu

**Comment by caybro** [comment]
PR: https://github.com/status-im/status-desktop/pull/9129
