### ISSUE TITLE
Active chat is changing after leaving non-opened group chat

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#9147]
# Bug Report

## Description

If you have few group chats and you are on group chat A and closing group chat B - your active chat is changing to a random one

## Steps to reproduce

1. Create a few group chats
2. Select one of them
3. Leave non-opened group chat

#### Expected behavior

You stay on the active chat after the leave

#### Actual behavior

Your active chat is switched randomly

https://user-images.githubusercontent.com/117639195/212746141-280df6b1-acc1-4c5a-88a9-885560e923b4.mov

### Additional Information

- Status desktop version: 0.9.0-rc2
- Operating System: macOS

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone
