### ISSUE TITLE
Chat section badge shows 1 unread msg if user receives contact request

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#9152]
# Bug Report

## Description

Showing contact requests in the chat section was removed, but if the user receives a contact request, the section icon shows 1 unread message, while there are no unread messages inside the chat section

## Steps to reproduce

Send a contact request to the user, who uses 0.9.0-rc2

#### Expected behavior

The chat section badge didn't show an unread msg if a contact request received

#### Actual behavior

The chat section badge shows 1 unread message if a contact request is received, while there are no unread messages in the section

![image](https://user-images.githubusercontent.com/117639195/212868181-ccda2fbd-dee5-47e6-9366-2de55868fbed.png)

### Additional Information

- Status desktop version: 0.9.0-rc2
- Operating System: macOS

**Comment by jrainville** [comment]
Good catch. I forgot about that when I removed the  Contact request button and popup
