### ISSUE TITLE
'Pick another' for changing mailserver doesn't lead to mailserver settings

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9165]
# Bug Report

## Steps to reproduce
1. In the appeared 'Can not connect to mailserver' modal click 'Pick another'

#### Expected behavior
The messaging settings appeared and the page is not scrolled to the mail server settings

#### Actual behavior
The messaging settings appeared, but the page is not scrolled to the mail server settings

https://user-images.githubusercontent.com/14942081/213067564-71b4c6ff-aee8-4f89-92c7-96fd41ac2604.mov

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.9.x/3/
- Operating System: macOS Monterey

**Comment by jrainville** [comment]
Closing as we no longer have that popup
