### ISSUE TITLE
It's possible to save the empty Twitter field for Profile 

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9166]
# Bug Report

## Steps to reproduce
1. Go to Settings - Profile - Edit
2. In the Twitter field enter a few spaces and save changes
3. Go to Profile Preview

#### Expected behavior
It's impossible to save the empty Twitter field for Profile 
#### Actual behavior
The empty Twitter field is shown
<img width="274" alt="image" src="https://user-images.githubusercontent.com/14942081/213067995-db7aaf28-0533-4bb3-aeb7-bacefd114b6c.png">

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.9.x/3/
- Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
no longer relevant
