### ISSUE TITLE
Chat: '@0x00001' is shown instead of '@everyone'

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9168]
# Bug Report

## Steps to reproduce
1. Go to public chat and send a message '@everyone'
2. Right-click on this message and click 'Copy'
3. In the message field paste the copied text

#### Expected behavior
The pasted text is '@everyone'
#### Actual behavior
The pasted text is '@0x00001' 
### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.9.x/3/
- Operating System: macOS Monterey

**Comment by anastasiyaig** [comment]
@jrainville i doubt it is that critical to fix right now, we might move it to the 0.10.0

**Comment by 0x-r4bbit** [comment]
@anastasiyaig I have a fix in place

**Comment by jrainville** [comment]
Ah you're right. I misread the issue. I thought we showed `0x00001` in the messages themselves.

It's indeed not as important, but if Pascal already has a fix, might as well put it in

**Comment by 0x-r4bbit** [comment]
Actually, turned out this was broken for all mentions<->pubkeys and not specific to `@everyone`
