### ISSUE TITLE
Enforce Alphanumerical characters in community items

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#9180]
## Description

According to the specs and for security reasons, various items can allow alphanumerical characters and can't accept characters outside this set. This is to avoid impersonations by using characters that look like others.

The following items need to be updated to support this:
- community name
- community description
- community channel name

**Comment by mprakhov** [comment]
just to clarify
alphanumerical characters are: 0-9 and letters A-Z (both uppercase and lowercase) ([wiki](https://en.wikipedia.org/wiki/Alphanumericals))
Are we sure, that for community description we want to restrict such symbols as 'space' , . ' etc
cc @jrainville

**Comment by jrainville** [comment]
I think we accept spaces yes. The others, I don't think so. Also, for sure not any accents or Ñ.
cc @John-44

**Comment by caybro** [comment]
> I think we accept spaces yes. The others, I don't think so. Also, for sure not any accents or Ñ. cc @John-44

While I see this restriction as plausible (for the security reasons), how are we going to explain to international communities? How do you type English (ASCII) only letters on a Chinese keyboard? ;)

**Comment by mprakhov** [comment]
Just a heads up, in the scope of this ticket I'll allow in community name/description and channel name numbers, ANSII letters A-Z, a-z, underscores, whitespaces and hyphens. These restrictions are the same as for a profile name
cc @iurimatias , @jrainville , @John-44
