### ISSUE TITLE
Investigate bootstrap performance

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#9193]
### Description

It's a known issue that Status desktop starts up quite slowly, or rather seems unresponsive after logging into the app.
This is very apparent by the loading animation which even gets stuck and doesn't continue rendering frames.

The reason for that is that there's a bunch of synchronous work/calls happening upon login.

In addition, this startup time gets worse the more messages are in the database, which is especially a problem when there's a message history imported from discord (you can easily end up with tens of thousands of message).

When I was working on the import too I've investigated this a bit and noticed that, after login we try to fetch chat data for all communities and every single chat for every community.
Not only do we unnecessarily load all of that data, we also do that sequentially. If there's 10 channels then it likely takes 10x as long.
After further digging I noticed that most costly function in terms of perf is the `pinnedMessages` call for every chat.

Just removing that call when we're fetching chats, greatly improves performance. It also turned out that the app kept functioning without this data. Pinned message data seems to be fetched at a later stage anyways.

So here are the thing we could do and should look into **assuming that the slowness/blockage is caused by the same API calls as back then**:

1. First of all I don't think we need to query pinned messages per channel upfront. I tested it back then, and even if we don't load them upfront. they'll be available/fetched when you enter a channel, so no missing data in the view. Removing that query improves bootstrap speed by a lot
2. I don't think we have to load all communities + all chats from the get go. We should know what the last visited view was (default to one-on-view) and should onlyh query the data we need, based on that. This should reduce the blocking call as well
3. Instead of making this stuff synchronous, we should rather have an async API for that, this would unblock the UI immediately (and most likely keeps the animation spinning instead of getting it stuck), however we then need to ensure we introduce loading states/animations in chat view as data is being fetched in the background (we already have some UI components that do that)

For starters, I think doing 1) will already greatly improve the startup time and is a pretty low hanging fruit.

Another thing we can improve here:
Right now the getchats calls are done sequentially for every community.
We could probably spin up multiple goroutines to get the data concurently in status-go instead.
Should speed things up as well as we don't have to wait for every item to finsih one by one

**Comment by caybro** [comment]
Nice analysis!

> After further digging I noticed that most costly function in terms of perf is the pinnedMessages call for every chat.

> Just removing that call when we're fetching chats, greatly improves performance. It also turned out that the app kept functioning without this data. Pinned message data seems to be fetched at a later stage anyways.

One thing I realized... we don't need to build that "pinnedMessages" model in the backend/model at _all_ imho; we already have all the messages at hand and we could just filter those having `model.pinned` role set to `true` in QML using `SortFilterProxyModel`. Wdyt?

**Comment by jrainville** [comment]
@caybro that's a good idea in theory, but in practice the message model the Nim backend has is very limited.

It contains 20 messages on app start. So if you had a pin from the 21st oldest message, you wouldn't be able to show it.

Using a special API to get pinned messages and creating a specific model for it is the only way we have right now, as far as I can tell.

Pascal's idea of not fetching that on app start is a good one and easily feasible.

**Comment by caybro** [comment]
> @caybro that's a good idea in theory, but in practice the message model the Nim backend has is very limited.
> 
> It contains 20 messages on app start. So if you had a pin from the 21st oldest message, you wouldn't be able to show it.

I see, too bad :)

> Using a special API to get pinned messages and creating a specific model for it is the only way we have right now, as far as I can tell.
> 
> Pascal's idea of not fetching that on app start is a good one and easily feasible.

:+1:

**Comment by 0x-r4bbit** [comment]
Here's another thing I found out:

Because we have this rather unfortunate architecture to instantiated a `chat_content` module **per chat** (as opposed to having just one and swapping out its data), the `viewDidLoad` lifecycle callback is called many times:

https://github.com/status-im/status-desktop/blob/ae4d59de9a213a601b7d1afc06b13890edfff268/src/app/modules/main/chat_section/chat_content/users/module.nim#L57-L63

One of the things we do here is fetching members every time this module has finished loading it's view.
Because there are many chats in a single community, this his happening as many times after login, which is essentially a series of blocking RPC calls that make our app stall.

There are a few more of these related to message reactions. Will check where those exactly come from.

**Comment by 0x-r4bbit** [comment]
Alright, so another thing we seem to be doing after login (and messages being loaded), is we seem to request contact details from individual contacts many many times, which also results in a series of blocking calls.

There are various places from which this happens, but most of them seem to origin from `chat_content/messages/controller` and `chat_content/controller`.

We should re-evaluate how often we want to call `getContactDetails`. Need to dig further, but the first thing that comes to mind is maybe doing a single `getContactDetailsForAllContacts` call, load the data into memory, and any subsequent call originating from messages controller ensures that it relies on cached contacts instead of reaching out to status-go.

Of course, the question then is when that cache is invalidated. But I think we should for sure avoid to do so many contact detail calls right out of the bat.

**Comment by 0x-r4bbit** [comment]
> Of course, the question then is when that cache is invalidated. But I think we should for sure avoid to do so many contact detail calls right out of the bat.

Turns out there's already caching in place, but we still do many RPC calls because we request contact details for contact individually (at which point they aren't in cache **yet*)

**Comment by jrainville** [comment]
> It's just still the nature of the thing that, there are many users/contacts in a community we need to fetch individually (probably because they aren't added contacts yet).

**Comment by 0x-r4bbit** [comment]
> Anyway, if you do find that we hit the DB each time we want to get info about a user from a community, that's an issue we need to fix. It should all be cached.

Stuff is cached for sure. I do see calls to status-go still originating from the community module controller. Not sure yet why those make it all the way through to status-go yet

**Comment by jrainville** [comment]
@0x-r4bbit have you figure out if we do hit the DB for the contacts? If so, are you working on fixing it or don't have time? If the latter, I'll assign that fix to someone else.

**Comment by 0x-r4bbit** [comment]
@jrainville I didn't get to following up on it here as I was busy with import tool stuff.
Will look into it again today and see what I can do

**Comment by 0x-r4bbit** [comment]
Will also test with https://github.com/status-im/status-desktop/pull/9306 as I think this will improve things as well.

**Comment by 0x-r4bbit** [comment]
Okay so quick update here: #9306 removes a lot of the chatMember calls, which is good, but it doesn' tmake for the bulk of the bootstrap time.

OTOH if I remove collecting pinned messages from chat/service APIs while having a community roughly the size of Status' one, I safe about ~10 secs of processing time.

However, there is still a lot of other stuff / RPC calls shortly after login that cause a lot of processing and slow down the app.
Digging deeper...

**Comment by 0x-r4bbit** [comment]
Okay so.. I've been measuring a couple of RPC calls we're doing during startup that feel like they are taking a lot of time.
Most of them hour take only about a second. 
However, as mentioned above, we do many different things after startup. So at this point I think it's really the combination of all of these RPC calls that make desktop stall because we're a) blocking the app while doing these calls and for any other calls we b) have to process many signals.

It seems like the solution here is to "simply" do less work. Just to give an idea, here's the amount of RPC calls we do right after login (**and this is excluding the `getContactByID` calls for each unknown member of a community**):

```
DBG 2023-01-27 14:01:27.473+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_startMessenger
DBG 2023-01-27 14:01:27.483+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_getSettings                                          
DBG 2023-01-27 14:01:27.484+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_getSocialLinks                                       
DBG 2023-01-27 14:01:27.489+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=mailservers_getMailservers 
DBG 2023-01-27 14:01:27.489+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_imageServerURL                                        
DBG 2023-01-27 14:01:27.490+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_contacts                                              
DBG 2023-01-27 14:01:27.490+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getReceivedVerificationRequests  

# -------------- THIS ONE TOOK ABOUT 10 SECs ----------------------- #
DBG 2023-01-27 14:01:27.491+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=chat_getChats  
#--------------------------------------------------------------------------------------#

DBG 2023-01-27 14:01:27.502+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_communityTags
DBG 2023-01-27 14:01:27.502+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_joinedCommunities
DBG 2023-01-27 14:01:27.507+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_pendingRequestsToJoinForCommunity
DBG 2023-01-27 14:01:27.507+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_declinedRequestsToJoinForCommunity
DBG 2023-01-27 14:01:27.508+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_canceledRequestsToJoinForCommunity
DBG 2023-01-27 14:01:27.508+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_communities

# ------------------- THIS ONE TAKES ABOUT 6 SECS --------------------- #
DBG 2023-01-27 14:01:27.515+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_curatedCommunities
# -----------------------------------------------------------------------------------------#

DBG 2023-01-27 14:01:28.475+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getCommunitiesSettings
DBG 2023-01-27 14:01:28.476+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_myPendingRequestsToJoin
DBG 2023-01-27 14:01:28.477+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=browsers_getBookmarks
DBG 2023-01-27 14:01:28.478+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=permissions_getDappPermissions
DBG 2023-01-27 14:01:28.479+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_getEthereumChains
DBG 2023-01-27 14:01:28.480+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_getSavedAddresses
DBG 2023-01-27 14:01:28.480+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419753 file=core.nim:27 rpc_method=wakuext_activityCenterNotifications
DBG 2023-01-27 14:01:28.480+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=updates_check
DBG 2023-01-27 14:01:28.480+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419752 file=core.nim:27 rpc_method=stickers_market
DBG 2023-01-27 14:01:28.481+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_getPendingTransactionsByChainIDs
DBG 2023-01-27 14:01:28.481+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=gif_setTenorAPIKey
DBG 2023-01-27 14:01:28.490+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=gif_getRecentGifs
DBG 2023-01-27 14:01:28.493+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_getCachedPrices
DBG 2023-01-27 14:01:28.493+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=accounts_getAccounts
DBG 2023-01-27 14:01:28.495+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=ens_getName
DBG 2023-01-27 14:01:30.787+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_firstUnseenMessageID
DBG 2023-01-27 14:01:31.849+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=accounts_getAllMigratedKeyPairs
DBG 2023-01-27 14:01:32.016+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_isCurrencyFiat
DBG 2023-01-27 14:01:32.016+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_getFiatCurrencyMinorUnit
DBG 2023-01-27 14:01:32.018+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getOurInstallations
DBG 2023-01-27 14:01:32.019+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetExMuteAllMessages
DBG 2023-01-27 14:01:32.220+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetExPersonalMentions
DBG 2023-01-27 14:01:32.221+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetExGlobalMentions
DBG 2023-01-27 14:01:32.223+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetExOtherMessages
DBG 2023-01-27 14:01:32.223+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=accounts_getAccounts
DBG 2023-01-27 14:01:32.225+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=accounts_getAllMigratedKeyPairs
DBG 2023-01-27 14:01:32.226+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=stickers_recent
DBG 2023-01-27 14:01:32.242+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419754 file=core.nim:27 rpc_method=wakuext_chatPinnedMessages
DBG 2023-01-27 14:01:32.227+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=stickers_installed
DBG 2023-01-27 14:01:33.149+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419754 file=core.nim:27 rpc_method=wakuext_emojiReactionsByChatID
DBG 2023-01-27 14:01:33.154+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=stickers_stickerMarketAddress
DBG 2023-01-27 14:01:33.158+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_peers
DBG 2023-01-27 14:01:33.161+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=accounts_getAllMigratedKeyPairs
DBG 2023-01-27 14:01:33.164+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_getPendingTransactionsByChainIDs
DBG 2023-01-27 14:01:33.164+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_isCurrencyFiat
DBG 2023-01-27 14:01:33.165+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_fetchPrices
DBG 2023-01-27 14:01:33.835+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_isCurrencyFiat
DBG 2023-01-27 14:01:33.841+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wallet_getCryptoOnRamps
DBG 2023-01-27 14:01:33.846+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=accounts_getAllMigratedKeyPairs
DBG 2023-01-27 14:01:34.088+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getOurInstallations
DBG 2023-01-27 14:01:34.089+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getLatestVerificationRequestFrom
DBG 2023-01-27 14:01:34.098+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetVolume
DBG 2023-01-27 14:01:34.098+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetSoundEnabled
DBG 2023-01-27 14:01:34.100+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getOurInstallations
DBG 2023-01-27 14:01:34.100+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getLatestVerificationRequestFrom
DBG 2023-01-27 14:01:34.108+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=stickers_installed
DBG 2023-01-27 14:01:34.111+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetVolume
DBG 2023-01-27 14:01:34.112+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=settings_notificationsGetSoundEnabled
DBG 2023-01-27 14:01:34.112+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getOurInstallations
DBG 2023-01-27 14:01:34.113+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getLatestVerificationRequestFrom
DBG 2023-01-27 14:01:34.635+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getLinkPreviewWhitelist
DBG 2023-01-27 14:01:34.706+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getOurInstallations
DBG 2023-01-27 14:01:34.707+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getLatestVerificationRequestFrom
DBG 2023-01-27 14:01:35.483+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getContactByID   
DBG 2023-01-27 14:01:35.782+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=stickers_pending
DBG 2023-01-27 14:01:35.784+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=stickers_installed
DBG 2023-01-27 14:01:35.794+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_messageByMessageID
DBG 2023-01-27 14:01:35.798+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_emojiReactionsByChatIDMessageID
DBG 2023-01-27 14:01:35.802+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_getContactByID
DBG 2023-01-27 14:01:35.803+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_messageByMessageID
DBG 2023-01-27 14:01:35.806+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_emojiReactionsByChatIDMessageID
DBG 2023-01-27 14:01:35.808+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_messageByMessageID
DBG 2023-01-27 14:01:35.811+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=419738 file=core.nim:27 rpc_method=wakuext_emojiReactionsByChatIDMessageID
```

Remember that, at the same time there's also plenty of async stuff happening like, fetching messages etc, which all result in signal that have to be processed/rendered as well.

I suggest we go through the RPC calls evaluate whether they are really needed to render a particular screen.

The logs above were the result of logging in and being brought straight to a channel of a community.

**Comment by jrainville** [comment]
I did some investigation on a test account and create a sheet with the times it took for each call.

It was a small account, so the times elapsed are small, but it still gives an idea.

excerpt (sorted by longest to shortest, only the 22 biggest ones):
```
10:13:01.550-05:00 | rpc_method=stickers_market | 0.003326919
10:13:00.697-05:00 | rpc_method=chat_getChats | 0.001576816
10:13:01.277-05:00 | rpc_method=wallet_getTokens | 0.001194669
10:13:00.693-05:00 | rpc_method=wakuext_contacts | 0.000800495
10:13:01.436-05:00 | rpc_method=wallet_getCryptoOnRamps | 0.000730845
10:13:01.410-05:00 | rpc_method=wakuext_chatMessages | 0.000532044
10:13:00.700-05:00 | rpc_method=wakuext_communities | 0.000424091
10:13:01.485-05:00 | rpc_method=wakuext_unreadActivityCenterNotificationsCount | 0.000380977
10:13:01.499-05:00 | rpc_method=wakuext_getOurInstallations | 0.000285804
10:13:00.699-05:00 | rpc_method=wakuext_joinedCommunities | 0.000274918
10:13:01.505-05:00 | rpc_method=stickers_installed | 0.000274276
10:13:01.500-05:00 | rpc_method=wakuext_getLatestVerificationRequestFrom | 0.000261821
10:13:01.433-05:00 | rpc_method=wakuext_peers | 0.000250449
10:13:01.415-05:00 | rpc_method=wakuext_chatMessages | 0.000247965
10:13:01.268-05:00 | rpc_method=wallet_getEthereumChains | 0.000244767
10:13:01.428-05:00 | rpc_method=wakuext_getTrustStatus | 0.00023874
10:13:01.508-05:00 | rpc_method=wakuext_getLatestVerificationRequestFrom | 0.00023427
10:13:01.269-05:00 | rpc_method=wakuext_activityCenterNotifications | 0.000230708
10:13:01.507-05:00 | rpc_method=settings_notificationsGetSoundEnabled | 0.000227151
10:13:01.414-05:00 | rpc_method=wakuext_firstUnseenMessageID | 0.000220947
10:13:01.267-05:00 | rpc_method=wakuext_getCommunitiesSettings | 0.000219591
10:13:01.412-05:00 | rpc_method=wakuext_firstUnseenMessageID | 0.000201931
```

@alaibe I see a couple of wallet calls take a lot of time. Can we make them lazy load instead? ie only call them when we open the Wallet? In my case, the wallet wasn't even activated in settings.

Full file here: 
[timeEval.ods](https://github.com/status-im/status-desktop/files/10580281/timeEval.ods)

**Comment by jrainville** [comment]
I started doing some investigation as well. It seems like starting the waku v2 service is pretty slow by itself. I'll later do some more investigation with a big account
https://hackmd.io/@status-desktop/r1vOxEr0o
