### ISSUE TITLE
When changing amount on send modal, the send button disapear

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#9207]
![image](https://user-images.githubusercontent.com/491074/213659501-c30aa4aa-6f69-4a6d-a225-7f6b3fc06d1c.png)

**Comment by alaibe** [comment]
Also, updating the amount is not working

**Comment by Khushboo-dev-cpp** [comment]
https://user-images.githubusercontent.com/60327365/214558794-a628ad6b-7649-4ca6-b268-9ca1d601792f.mov

not able to reproduce on master

**Comment by Khushboo-dev-cpp** [comment]
https://user-images.githubusercontent.com/60327365/214561352-8d734a19-9ce2-4b81-9a10-12a8d81412c1.mov
