### ISSUE TITLE
AddressInput.qml does not validate ENS

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#9225]
# Bug Report
_AddressInput.qml_ expects only address to be entered and prematurely ignores ENS.
    
## Description

ENS is considered invalid input:

```
        chatKey.onTextChanged: {
            metrics.text = chatKey.text
            if (Utils.isValidAddress(chatKey.text)) { // THIS LINE VALIDATES ADDRESS ONLY, no further validation
                root.selectedAddress = chatKey.text
            } else {
                root.selectedAddress = ""
            }
        }
```
As a result, it is impossible to add a saved address via ENS, as button is not active: 
![Add_saved_address_popup_notvalidates_ens](https://user-images.githubusercontent.com/15627093/213994114-ce381ac1-3a98-497b-8631-610651d74f49.png)

## Steps to reproduce
Wallet -> "Saved addresses" button -> "Add new address" -> enter a valid ENS into proper field
#### Expected behavior
ENS is considered valid, "Add address" button is activated
#### Actual behavior
ENS is not reported as invalid, but "Add address" button is not activated
### Additional Information

There is an issue with focus of address field, as it does not seem to ever receive focus and its `onFocusChanged` handler is never called. validation never happens as well.

- Status desktop version: 0.9.x
- Operating System: Ubuntu 20.04

**Comment by alexjba** [comment]
@IvanBelyakoff Looks like it's working on master. Am I missing something?

https://user-images.githubusercontent.com/47811206/218996441-56464105-768a-4abd-85ea-88ec2429d1f1.mov

**Comment by alexjba** [comment]
> Please try to enter some ENS name that you don't have in contacts, for example:

The test above is done on a clean account with no contacts/activity.

**Comment by alexjba** [comment]
> I think that ENS resolving might be involved. I am not sure if we have it in requirements that only resolved ENS names can be entered in the field.
> Have you tried with some ENS name that is not resolved? Is it still a valid input for you?

True. Looks like it searches the entire namespace to validate the ENS name. I've tried with `test.some.ens` that is not registered and it is not valid.

> I see that it is resolved for me as well.

Can we close it in this case? 😄

**Comment by alexjba** [comment]
Considering the discussions on Status chat, we should allow only ENS resolved addresses to be saved. This means it works as expected.
Closing this issue.
