### ISSUE TITLE
Unknown image displayed if user replies to the message containing an image

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#9266]
If user replies to the message which contains only an image, that image is rendered well in the section where message one hase replied to should be displayed, but from some reason another image/icon is added there as well which should not be there.

![aa](https://user-images.githubusercontent.com/86303051/214335487-6ed6ca95-eaa8-4a02-b87b-83a78b24a67f.png)

**Comment by jrainville** [comment]
Clarification: that small image is the `emoji` we hardcoded in the `text` field.

**Comment by iurimatias** [comment]
has been fixed in the meantime
