### ISSUE TITLE
[Community Permissions] Create captcha popup

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9269]
### Description

[Captcha popup design:](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2457%3A338492&t=ko7tHNQ2rO8j35Uc-0)

![Screenshot 2023-01-24 at 17 13 22](https://user-images.githubusercontent.com/97019400/214346908-28e1ddf6-666d-4a68-8e75-2f697352cca5.png)

**Comment by micieslak** [comment]
Catcha is out of scope for MVP.
