### ISSUE TITLE
[suite_settings] Review and enable broken / skiped tests 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9284]
### Description

The following scenarios are unestable:
1. tst_contactsFlow --> The user can add a contact with a chat key
2. tst_mainSettingsSection --> The user can switch state to online 
3. tst_mainSettingsSection --> The user can switch state to offline 
4. tst_mainSettingsSection --> The user can switch state to automatic
5. tst_mainSettingsSection --> The user can change the password and login with new password

Update them properly and remove `@mayfail` tag. Make sure they pass successfully in both cases, standalone and as part of a sequence.

**NOTE:** Related PR: https://github.com/status-im/status-desktop/pull/9265

**Comment by noeliaSD** [comment]
I suggest to split this task in different ones. I.e. one task per scenario broken.

Also it would be nice to review the requirements / user stories with @glitchminer and add/update them in notion.

**Comment by StateOf-Vlado** [comment]
All tests are fixed, except Scenario: The user can add a contact from the chat, looks like it will be rewritten
Regarding scenarios updating:
- we moved all scenarios in the TestRail: https://ethstatus.testrail.net/index.php?/projects/overview/17
- next step will be to adopt them to e2e test cases
- then I will update test scenario according to the test case changes
@anastasiyaig do we have a task on test case rewriting?
I would like to split these tasks @noguerantees can we split them?

**Comment by anastasiyaig** [comment]
@StateOf-Vlado sure, i will add a task to re-work scenarios (i think it will be multiple tasks ).
