### ISSUE TITLE
Biometrics prompt is showing up after application is restarted

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9286]
### Description

1. install recent master
2. create account
3. do not enable biomtrics
4. close the app
5. start it again

As result, user is prompted to bypass biometrics even it was not enabled yet

<img width="370" alt="Screenshot 2023-01-25 at 12 49 58" src="https://user-images.githubusercontent.com/82375995/214549017-251049af-0418-4b5b-9420-8b33bf4cdd17.png">

**Comment by iurimatias** [comment]
closed in favour of #10424
