### ISSUE TITLE
Communities: the New or Edit Category modal look incorrect if the app  is not maximized

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9299]
# Bug Report

## Steps to reproduce
Case 1: **The button 'Save' is not shown while editing a category**
1. Create a new community with 3 channels and one category with one channel
2. Go to change the category, select a few channels, and check the button 'Save'
Actual Result:
There is no Save button
<img width="398" alt="image" src="https://user-images.githubusercontent.com/14942081/214755217-411561fe-4907-4df6-b84e-08c498752e57.png">

**Case 2: The 'Save' button is overlapped by the 'Delete category' area while editing a category**
Steps:
1. Create a new community with 3 channels and one category with one channel
2. Go to change the category, select a few channels, and hover over the 'Delete Category' area
Actual Result: The 'Save' button is overlapped by the 'Delete category' area while editing a category
<img width="356" alt="image" src="https://user-images.githubusercontent.com/14942081/214755727-76d85d04-8984-4b14-a8dd-7e84f9e6c003.png">

**Case 3: The 'Edit category' looks incorrect if there are some channels and the empty Category title**
<img width="252" alt="image" src="https://user-images.githubusercontent.com/14942081/214755963-9ac2540f-b0d4-4ffb-bdf6-9b20a89befe1.png">

**Case 4: The grey line disappears if channels are scrolled**
1. Create a new community with  four channels and go to create a new category,
2. Enter a space in the Category Name field
<img width="249" alt="image" src="https://user-images.githubusercontent.com/14942081/214756583-fd4f1237-5583-458a-aae7-58bc090c272b.png">

#### Expected behavior
The modal looks correct

### Additional Information

- Status desktop version: master
- Operating System: macOS Monterey

**Comment by iurimatias** [comment]
fixed in the meantime
