### ISSUE TITLE
Chat input: chat bar input is erased (deleted) when switching between chats

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9304]
### Description

1. open 1x1 chat
2. in a chat bar, start typing some text
3. do not send the text
4. open another chat
5. go back to previous chat

As result, the text left in chat input is gone

**Comment by anastasiyaig** [comment]
@jrainville sorry i missed your reply in community regarding this ticket, tagging you now

**Comment by imagiMary** [comment]
Hi @anastasiyaig and @jrainville, I did a more detailed write up before I realised

**Comment by jrainville** [comment]
Closing as it is superseded by https://github.com/status-im/status-desktop/issues/9709
