### ISSUE TITLE
Chat: mentions become inactive when adding [?] and whitespace after

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9305]
### Description

1. open community
2. enter @ symbol and start typing a known name to mention a person
3. select from suggestions
4. type `?` 
5. hit space button

https://user-images.githubusercontent.com/82375995/214787298-f75c4ff8-34d8-4a20-bbb5-234fd43dd673.mov

**Comment by caybro** [comment]
Similar prob to https://github.com/status-im/status-desktop/issues/7685
