### ISSUE TITLE
Send boxes low amount of STT shows error incorrectly

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#9324]
# Bug Report

Send modal: try to send 0.9 STT, it shows a red boxes

![image](https://user-images.githubusercontent.com/491074/215056262-b4160ee6-e494-4eab-a35a-b77103173d23.png)

**Comment by Khushboo-dev-cpp** [comment]
Not reproducible on latest master @alaibe  please reconfirm when you can?



![Image](https://user-images.githubusercontent.com/60327365/216254915-2c7f3356-ee39-4669-9b8c-84b1e97e2fbe.png)

**Comment by alaibe** [comment]
Also second problem is the display of <1STT

To be discussed during next monday meeting

**Comment by dlipicar** [comment]
> Also second problem is the display of <1STT
> 
> To be discussed during next monday meeting

Hmm yeah, I asked John if there were places where we wanted not to use the currency rounding logic and display full precision instead. He said amounts with a value lower than a US cent should be considered "noise" so we should always use that logic, but perhaps we could show him how it currently looks to see if he wants any change there.

**Comment by dlipicar** [comment]
`StatusFloatValidator` is not handling locale properly, need to fix it
