### ISSUE TITLE
Sync all devices button in the Device Settings is not fully visible

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#9325]
# Bug Report

## Description

The sync all devices button in the Device Settings is not fully visible if there are a lot of devices in the list

## Steps to reproduce

1. Fill paired devices list with data to make the scroll bar visible
2. Go to Settings -> Device Settings

#### Expected behavior

Sync all devices button fully visible

#### Actual behavior

Button is partially visible

![Screenshot 2023-01-27 at 13 19 58](https://user-images.githubusercontent.com/117639195/215074459-ab11a57b-7862-42e7-9ac1-968454c83a8a.jpg)

### Additional Information

- Status desktop version: 0.9.0-rc.8
- Operating System: macOS

**Comment by alexandraB99** [comment]
Closing as invalid, this is very old screen which has been replaced with new Syncing UI. cc @anastasiyaig
