### ISSUE TITLE
View Profile does not have close button

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#9327]
# Bug Report

## Description

View Profile does not have a close button and the user must click on non-profile area which is not user friendly

## Steps to reproduce

1. Open the context menu on any user
2. Select View Profile

#### Expected behavior

View Profile has a close button

#### Actual behavior

View Profile does not have a close button

![Screenshot 2023-01-27 at 14 05 45](https://user-images.githubusercontent.com/117639195/215083669-d0f04dfc-14d1-4181-b4f6-06aebac36331.jpg)

### Additional Information

- Status desktop version: 0.9.0-rc8
- Operating System: macOS

**Comment by caybro** [comment]
This is/was a design decision

CC @benjthayer

**Comment by benjthayer** [comment]
I've taken a look and this does seem to be the only place where we don't have the close cross on a dialog/modal. I agree, from the user's perspective, this is something that they would expect to see and having it elsewhere in the app reinforces this expectation. 

@John-44 do you recall if there were any specific design decisions made around omitting the X here? It certainly makes more room for the top right controls but I wonder if we could reinstate it if we used a vertical pipe to segregate it out from those controls? It wouldn't be in the exact same location as in the other dialogs but given this is a fairly custom designed dialog it might be ok?

<img width="672" alt="Contact" src="https://user-images.githubusercontent.com/110033914/215099486-af576e78-45b0-4b82-9f6f-b693e0d2f09f.png">

**Comment by John-44** [comment]
@benjthayer let's do a quick call to discuss.  This same issue applies to all the Wallet dialogues, so we shouldn't just have a solution here in isolation - any solution needs to work for all the wallet dialogues as well.

**Comment by alexandraB99** [comment]
@benjthayer @John-44 is this still an issue?

**Comment by caybro** [comment]
It was designed like that so unless the design has changed, we can close this? :)

**Comment by John-44** [comment]
Let's close for now, and we will fix when we do the big redesign and move to QT6.
