### ISSUE TITLE
The text on Advanced and custom view for recipient column is wrong

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#9331]
### Description

expected:

![image](https://user-images.githubusercontent.com/60327365/215086420-fc60c77f-d781-4913-b1d2-b359f17e79f8.png)

https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9707%3A112166&t=jih74aamRwsCSe8c-4

current:

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/60327365/215086543-f15ea1f9-bccc-4db1-a7d8-70d9550be96e.png">

**Comment by stefandunca** [comment]
@Khushboo-dev-cpp while working on the fix [here](https://github.com/status-im/status-desktop/pull/9391) i encountered the following questions not described by the requirements in the ticket here

- Should it be capitalized as in the screen snippet?
- What should be the intermediate text - when the user still enters the address and the recipient is invalid?
- Should it only show the address or the ENS, in case it is available?
  - Showing ENS will need some reflow in case of long ENS names (short address fits well)
- In the case of renaming the recipient and making it invalid, I hide the text; however, the amount received is not hidden. Shouldn't it be?

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp while working on the fix [here](https://github.com/status-im/status-desktop/pull/9391) i encountered the following questions not described by the requirements in the ticket here
> 
> * Should it be capitalized as in the screen snippet?
Yes that how its designed.
> * What should be the intermediate text - when the user still enters the address and the recipient is invalid?
this ccould be good question for @xAlisher ?
> * Should it only show the address or the ENS, in case it is available?
>   
>   * Showing ENS will need some reflow in case of long ENS names (short address fits well)
ENS name should be shown if available, how to handle long names again a question for @xAlisher 
> * In the case of renaming the recipient and making it invalid, I hide the text; however, the amount received is not hidden. Shouldn't it be?
-> Amount receieved could stay but again a question for @xAlisher :D

**Comment by stefandunca** [comment]
@xAlisher i took the liberty to implement ENS and elide in the middle if too long. Please have a look at the result in the PR description here https://user-images.githubusercontent.com/47554641/216108047-46010660-d068-4fb7-b103-1e7781c1d16e.png

@xAlisher let me know if this is acceptable until further notice and can be merged like this
