### ISSUE TITLE
Dev app sometimes doesn't start and hangs

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9336]
# Bug Report

## Description

From time to time, the app (in dev mode) just hangs when starting using `make run`. Nothing shows. It gets stuck on :
```
INF 2023-01-27 10:40:06.819-05:00 starting application...                    topics="status-app" tid=32101 file=nim_status_client.nim:176
```

## Steps to reproduce

No idea. It is very unpredictable. It seems to happen maybe 1/20 times?

#### Expected behavior

App starts all the time normally

**Comment by jrainville** [comment]
This is also part of what makes the e2e tests fail from time to time. This error:
```
Object '{checkable='true' container={container={name='mainWindow' type='StatusWindow' visible='true'} type='Overlay' unnamed='1' visible='true'} objectName='acknowledgeCheckBox' type='StatusCheckBox' visible='true'}' not found. Could not match properties:
```

**Comment by micieslak** [comment]
It happens it to me as well. I noticed it ~yesterday, but mainly using Storybook, so it could exist earlier ofc. I would estimate it as 1/10 runs.

**Comment by alexandraB99** [comment]
> It happens it to me as well. I noticed it ~yesterday, but mainly using Storybook, so it could exist earlier ofc. I would estimate it as 1/10 runs.

@micieslak isn't storybook a separate project?

**Comment by jrainville** [comment]
I can no longer reproduce this in latest master. I just ran and closed the app tens of times. Can someone else say if they experienced it lately?

**Comment by jrainville** [comment]
Seems like no one else experienced it in the last days. Closing for now
