### ISSUE TITLE
Profile -> ENS names list: long ens name leads to preview overlap

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9351]
### Description

1. enable wallet
2. switch to test net
3. buy ENS name having 10-12 chars (or longer)
4. complete the flow
5. review the list of names u own

<img width="1512" alt="Screenshot 2023-01-30 at 11 49 00" src="https://user-images.githubusercontent.com/82375995/215436909-128fda01-42dc-49cc-811c-aab99dcd26b9.png">

**Comment by anastasiyaig** [comment]
**NOTE:** it was spotted in https://github.com/status-im/status-desktop/pull/9330, and will be visible in master once this branch is merged

**Comment by igor-sirotin** [comment]
Probably better check it after merging https://github.com/status-im/status-desktop/pull/9036

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/10439
