### ISSUE TITLE
Profile -> ENS name details: ens release name is shown in the past

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9352]
### Description

1. enable wallet
2. switch to test net
3. proceed with buying ens name
4. wait for transaction to be completed (mined)
5. click the ens name to reveal the details

<img width="1512" alt="Screenshot 2023-01-30 at 11 49 48" src="https://user-images.githubusercontent.com/82375995/215440334-03acd345-6d36-4d8d-b19e-95af20da47d2.png">

**Comment by anastasiyaig** [comment]
**NOTE:** it was spotted in https://github.com/status-im/status-desktop/pull/9330, and will be visible in master once this branch is merged

**Comment by igor-sirotin** [comment]
Probably better check it after merging https://github.com/status-im/status-desktop/pull/9036
