### ISSUE TITLE
Community: '@everyone' in the pinned messages leads to 'qrc:/app/mainui/1'

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9364]
# Bug Report

## Steps to reproduce
1. In the community send a message '@everyone'
2. Pin the added message
3. Open the pinned messages and click on '@everyone'

#### Expected behavior
The community channel history is scrolled to the pinned message
#### Actual behavior
'@everyone' in the pinned messages leads to 'qrc:/app/mainui/1'
'@everyone' in the pinned messages leads to '
<img width="407" alt="image" src="https://user-images.githubusercontent.com/14942081/215631095-2cf24fa7-5d29-4da9-8671-bda477810b2b.png">

### Additional Information

- Status desktop version: 0.9.0.- beta
- Operating System: macOS Monterey

**Comment by caybro** [comment]
@0x-r4bbit any idea?

**Comment by 0x-r4bbit** [comment]
I doubt this is related to the`@everyone` in the message specifically.
Try reproducing this with any other mention in the pinned message.

Only thing that comes to mind is that there's still some sort of "linkActivated" handler on the mention (which happens to be `@everyone` in this case) but I'd assume this would cause the error for any mentions.

**Comment by caybro** [comment]
OK, I'll take this and investigate some more

**Comment by caybro** [comment]
I can reproduce this too (linux/master)

**Comment by 0x-r4bbit** [comment]
@caybro can you reproduce this with any mention? 

> Only thing that comes to mind is that there's still some sort of "linkActivated" handler on the mention (which happens to be @everyone in this case) but I'd assume this would cause the error for any mentions.

Does this assumption apply?

**Comment by caybro** [comment]
Nope and clicking a regular mention leads to opening the respective profile dialog; but see this screenshot:

![image](https://user-images.githubusercontent.com/5377645/216021584-dd01b2f3-b107-4660-9184-8fa37cfeea95.png)

I wonder why "@everyone" here contains the "@" sign, unlike the other normal mention

**Comment by 0x-r4bbit** [comment]
> I wonder why "https://github.com/everyone" here contains the "@" sign, unlike the other normal mention

This is because we replace `@0x00001` with `@everyone`. didn't look right to be to cut the `@` from `@everyone` in messages.
In fact, I think we should reintroduce the @-prefix for all other mention types as well.

**Comment by caybro** [comment]
> > I wonder why "https://github.com/everyone" here contains the "@" sign, unlike the other normal mention
> 
> This is because we replace `@0x00001` with `@everyone`. didn't look right to be to cut the `@` from `@everyone` in messages. In fact, I think we should reintroduce the @-prefix for all other mention types as well.

I agree; @alexjba would you happen to have an idea why we have this distinction in StatusMessage?

**Comment by 0x-r4bbit** [comment]
It's actually a matter of replacement in our message model when we `renderInline`. See here

https://github.com/status-im/status-desktop/blob/master/src/app_service/service/message/service.nim#L704-L717

We just need to prepend a `@` in L 717

**Comment by caybro** [comment]
> It's actually a matter of replacement in our message model when we `renderInline`. See here
> 
> https://github.com/status-im/status-desktop/blob/6c1e16b72e65d60679bb801df9e41aacc6d937e4/src/app_service/service/message/service.nim#L704-L717
> 
> We just need to prepend a `@` in L 717

Yup, just found it too :)

And the empty href here:
```nim
result = fmt("<a href=\"\" class=\"mention\">{tag}</a>") 
```

leads to the actual bug here; Qt thinks it's a relative URL, tries to resolve it against the current location, and produces the "qrc:/foo/bar" absolute URL

**Comment by 0x-r4bbit** [comment]
Ah nice find, Then I guess adding a `#` will fix it?

**Comment by caybro** [comment]
> Ah nice find, Then I guess adding a `#` will fix it?

Yup, that fixes it; PR incoming
