### ISSUE TITLE
Community: Nothing happens after clicking on a pinned message

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9365]
# Bug Report

## Steps to reproduce
1. Go to a community and pin any message
2. Go to pinned messages and click on any pinned message

#### Expected behavior
The pinned messages modal closed, and the messages' history is scrolled to the pinned message that was clicked
#### Actual behavior
Nothing happens
### Additional Information

- Status desktop version: 0.9.0.-beta
- Operating System: macOS Monterey

**Comment by benjthayer** [comment]
Hey @caybro @John-44 confirmed that the user should be able to left-click a pinned message to close the modal and travel to the pinned message in-situ of the message history. The message highlight when the user arrives at that pinned message would be the same as that used for highlighting an original message that is clicked on as part of a reply per this issue:
https://github.com/status-im/status-desktop/issues/8271#issuecomment-1348622882

There are a number of other design-alignment items in relation message pinning that it would be great to do - I'll raise another issue for those. Thanks!
