### ISSUE TITLE
Right-clicking Communities, Categories, Direct Messages and Chats should reveal the ability to mute and set mute duration

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#9369]
The designs show the ability to to set a mute duration via right-clicking on the following:

1) Community icon in the navigation bar
2) Category within category/channel list within a Community
3) Group chats
4) Direct messages (1:1 chats)

**Implemented**
The current desktop app features the ability to mute for channels, group chats and direct messages only.

**Required**
1) Implementation of mute duration options wherever there is a mute option
2) Implementation of mute option by right-clicking a Community icon and a category

**Community muting via right-click on Community icon**
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5197%3A46133&t=uM8vLZmtGjPva6cj-4

<img width="1440" alt="CommunityMute" src="https://user-images.githubusercontent.com/110033914/215722037-22270a9a-ac3a-4854-8eef-b254473f8124.png">

**Category muting via right-click on category**
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5203%3A44147&t=uM8vLZmtGjPva6cj-4

<img width="1440" alt="CategoryMute" src="https://user-images.githubusercontent.com/110033914/215722813-944f6ae0-5ce2-4aa7-a873-a6e585684cdd.png">

**Channel muting via right-click on channel**
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2817%3A381112&t=cOhqrNlv7fU5vjwF-4

<img width="1440" alt="ChannelMute" src="https://user-images.githubusercontent.com/110033914/215722336-12376d7d-d712-4a81-93c7-b6299e63d73d.png">

**Chat muting via right-click on chat**
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=9048%3A187944&t=uM8vLZmtGjPva6cj-4
<img width="1440" alt="ChatMute" src="https://user-images.githubusercontent.com/110033914/215722557-5a652683-83e3-46cb-b14d-28e959a91eeb.png">

**Muting duration options show here (pan right)**
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=9048%3A187944&t=uM8vLZmtGjPva6cj-4

<img width="477" alt="MuteMenu" src="https://user-images.githubusercontent.com/110033914/215723436-cdc42338-f8c6-4d81-95af-6f51c369f26f.png">

**Comment by benjthayer** [comment]
@John-44 just tagging you incase you want to add any comments about Category muting :)

**Comment by benjthayer** [comment]
Hey @borismelnik @John-44 here's my proposal for handling the mute interaction for Communities within Settings:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15926-367827&t=D6KInQMptqjp9xYs-4

It involves a slight re-org in the IA, moving `Settings` (if Community owner/admin), `Mute Community`, `Share Community` and `Leave Community` options into a context menu. This proposal is fairly future proof as it aligns with the work we are doing for sharing addresses at the point of joining a Community where we are planning on introducing a context menu for each Community within settings to house the `Edit shared addresses` action.

It also feels more natural for the user to select from mute duration options from a child level of a menu as opposed to having the mute icon button spawn a menu with the mute durations when clicked. It also allows us to clean up the UI considerably, only showing the bell icon in the mute state instead of showing it on every Community in the non-muted state (this can be implied by the removal of the mute status bell icon).

Would be great to get your thoughts both! :)

<img width="1308" alt="Screenshot 2023-05-31 at 11 43 50" src="https://github.com/status-im/status-desktop/assets/110033914/70e271c2-1042-438f-af00-298cdd39005f">

<img width="928" alt="Screenshot 2023-05-31 at 11 44 06" src="https://github.com/status-im/status-desktop/assets/110033914/03f24861-d7f9-4cf0-a969-e39164c8aad4">

<img width="1341" alt="Screenshot 2023-05-31 at 11 44 22" src="https://github.com/status-im/status-desktop/assets/110033914/bac837e7-26b4-4e32-bf02-32f0fde962d3">

<img width="1320" alt="Screenshot 2023-05-31 at 11 44 36" src="https://github.com/status-im/status-desktop/assets/110033914/cd60e089-05bf-4ac1-8710-63651da37774">

**Comment by John-44** [comment]
@benjthayer @borismelnik @jrainville re. "mute whole community for a time period", if this is easy to do from a dev point of view then go for it :-) but if it's going to take more than a small amount of work to do we should push the ability to "mute whole community for a time period" to a future milestone, no earlier than 0.15

**Comment by borismelnik** [comment]
@John-44 its almost done :) in the middle of testing
