### ISSUE TITLE
Wallet: follow up improvements for Balance History implementation

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#9379]
Leftovers worth considering after Balance History [initial implementation](https://github.com/status-im/status-desktop/issues/8175)

Issues

- [x] #9582
  - Noticed on L2 a lot of requests. At a quick investigation, I found that L2 doesn't follow the block length of the main chain but has different strategies to generate block numbers
- [x] #9624
- [x] ~~What happens if `startWallet` is called again? Stop the previous and execute again!~~
  - multiple `startWallet` is not supported

**Comment by glitchminer** [comment]
Hi @stefandunca , this is in the QA column but has no PRs linked to it. Is there anything more needing done before closing it?

**Comment by stefandunca** [comment]
I added it to notify the team of changes in fetching balance history. Mainly the request count should be reduced. The changes were merged under the issues in the description.
