### ISSUE TITLE
`@everyone` mention broken in latest stable version

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#9382]
Using version 0.9.0-stable I've seen this:

![Screenshot from 2023-02-01 10-55-26](https://user-images.githubusercontent.com/445106/216010502-a90036a7-3351-4df3-872f-c3d267086a17.png)

This indicates that the system tag isn't properly replaced with its label.
It used to work in previous RCs so something broke along the way

**Comment by 0x-r4bbit** [comment]
Tried this again and now `@everyone` system tags work just fine. Not sure what went sideways with Alex's original message..

**Comment by caybro** [comment]
master works fine for me; it looks like it has been just that particular message
