### ISSUE TITLE
Pinning messages - tweaks to UI and interactions to help align with original design intent

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#9396]
There are a couple of opportunities to align more closely with the designs in relation to pinned messages:

**Pinned messages modal**

1) Showing who pinned the message:
<img width="1440" alt="PinnedMessages-01" src="https://user-images.githubusercontent.com/110033914/216099107-41106213-39c9-4df0-9023-8d1768caf919.png">

2) Removing any date breaks between messages (the date should be added to the timestamp of the message instead):
<img width="815" alt="PinnedMessages-02" src="https://user-images.githubusercontent.com/110033914/216099599-77902930-ca38-4574-b300-e1624f01f663.png">

The time format should follow the new mobile app time formatting which uses relative and absolute formats depending on the proximity of the date:
Today 09:41
Yesterday 09:41
Mon 09:41
Sun 09:41
Sat 09:41
Fri 09:41
Thu 09:41
25 Jan 09:41
Etc
31 Dec 2022 09:41

3) Unpin icon button should be shown on hover of pinned message (admin/owner only) as opposed to within a right-click context menu:
<img width="1440" alt="PinnedMessages-03" src="https://user-images.githubusercontent.com/110033914/216099901-7479838f-90ee-4811-8657-726faa38ce72.png">

4) A related issue is focused on implementing left-click on pinned message to close the pinned messages modal and take the user to the pinned message in situ of the message history. For this reason, we can remove the right-click context menu:
https://github.com/status-im/status-desktop/issues/9365#issuecomment-1411964541
<img width="1006" alt="PinnedMessageContextMenu" src="https://user-images.githubusercontent.com/110033914/216100736-b1d3f32b-f812-4096-81ec-96c3ddc464d7.png">

5) There should be no padding between pinned messages per the designs and the padding at the top and base of the pinned message should be extended to match the designs:
<img width="1440" alt="PinnedMessages-04" src="https://user-images.githubusercontent.com/110033914/216100997-518f4f9b-8582-4cb8-bd9d-f22088468d7c.png">

6) The format of the number of messages should be `1 message`, `2 messages` - adding an `s` where pinned messages >1.
<img width="1440" alt="PinnedMessages-05" src="https://user-images.githubusercontent.com/110033914/216101737-115608ff-3fb7-4bfc-b784-70cb697c3613.png">

**Pinned messages CTA in chat top bar**

1) The CTA in the chat top bar to launch the pinned messages should read `n pinned messages`
<img width="1440" alt="PinnedMessages-06" src="https://user-images.githubusercontent.com/110033914/216102421-fc04e92a-48e7-46e7-9361-2c73cb0df745.png">

Figma designs for reference:
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=21394%3A549710&t=E1Y5xnuipYdAWvbV-4

cc @John-44 
cc @caybro

**Comment by John-44** [comment]
> @benjthayer cool, some of them are already implemented; let's go through these briefly in person when @John-44 approves

@caybro Everything here has +1 from me to proceed with implementation.

Thanks for this @benjthayer :-)
