### ISSUE TITLE
Don't perform history archive download if there isn't enough disk space

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#9404]
@0xc1c4da has reported this:

![Screenshot from 2023-02-02 12-01-04](https://user-images.githubusercontent.com/445106/216307417-c7cb0091-a51c-40d7-8d20-68f09426925a.png)

Turns out his hard drive ran out of space so the download has been cancelled.
We should see if there's a way to figure out the available disk space and archive sizes before requesting data pieces from the torrent.

If there isn't enough space, we could signal it to the client and have the user see a message or something.

**Comment by 0x-r4bbit** [comment]
@0xc1c4da did your machine crash by the way? Or how came you paid attention to the logs

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone

**Comment by jrainville** [comment]
FYI to anyone working on this: there is a PR that was created alreayd that can be reused https://github.com/status-im/status-desktop/pull/12995

**Comment by jrainville** [comment]
There was a PR for it a while ago. Closing https://github.com/status-im/status-go/pull/4449
