### ISSUE TITLE
Empty notification reply badge for image or sticker message

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#9416]
<img width="1059" alt="Screenshot 2023-02-03 at 13 05 49" src="https://user-images.githubusercontent.com/2522130/216558371-aa4a1e8b-155f-425a-a838-a888c0cef448.png">

**Comment by John-44** [comment]
Hi @MishkaRogachev in this case (where the user is replying to a message that only contains an image or images), in the lozinge in the activity center after the icon is should say "1 image" or "3 images" (plural in the case of more than one image), etc...

Basically the same as we are handling this case in the new mobile designs as shown below:

![2023-02-17 11_43_36-Design System for Mobile – Figma](https://user-images.githubusercontent.com/22846356/219645503-be74d96b-7f6b-4622-b73c-091c3b2a0d6c.png)

Does this answer your question?
