### ISSUE TITLE
MacOs - change key for the Keychain

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#9429]
A key under which we're storing pin/password in the Keychain for an account is account's display name. That can be misleading in case there are more than one account with the same display name, but different passwords or the same display name but one is a keycard account, another regular account.

Because of that we should think of changing that and use compressed public key instead.

Within this issue, we can do the following improvement:
The same as we have this constant [here](https://github.com/status-im/status-desktop/blob/master/src/constants.nim#L8) we can add `SUPPORTS_FINGERPRINT` const there as well, like `const SUPPORTS_FINGERPRINT = if IS_MACOS: return true else: return false` and replace usage of `IS_MACOS` in necessary places. Benefit of this change is that once we support biometric for linux/windows, we will just need to update `SUPPORTS_FINGERPRINT` constant.

**Comment by iurimatias** [comment]
closed in favour of #10424
