### ISSUE TITLE
The RPC call `firstUnseenMessageID` is called a lot on app start

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9438]
### Description

The RPC call `firstUnseenMessageID` is called a lot on app start, even though it should only be called once for the current active channel.

Looking at the code, I think we call it for each new message even if the channel is not active.

We only need to call it for the active channel and when changing channel as far as I know @osmaczko

**Comment by osmaczko** [comment]
> We only need to call it for the active channel and when changing channel as far as I know @osmaczko

Yes, that should be the case, unless something has recently changed.

**Comment by jrainville** [comment]
Ok thanks for the  info. I haven't dug into it yet, so I don't know if we just call it a lot for the same channel, or if we call it for multiple ones.
We need to investigate a bit before making changes

**Comment by osmaczko** [comment]
[This](https://github.com/status-im/status-desktop/pull/9432) change will most likely make it spam.

**Comment by jrainville** [comment]
Weird, the PR and the commit both link to this issue. Maybe Github bugged. I'll re-link manually
