### ISSUE TITLE
Onboarding: the message for the imported seed phrase is not user-friendly

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9446]
# Bug Report

## Steps to reproduce
in Dark Mode
1. Import a seed phrase, sign out
2. Try to import the seed phrase again

#### Expected behavior
The modal with message looks good and the Control buttons look correct
#### Actual behavior
1. The black colored text appeared on the dark background
2. The Control buttons of the window don't look good
3. the modal with message doesn't look user-friendly and needs a redesign
<img width="453" alt="image" src="https://user-images.githubusercontent.com/14942081/216878969-20c3125a-426f-4504-a6c0-28c4f6dab517.png">

### Additional Information

- Status desktop version: 0.9.0 beta
- Operating System: macOS Monterey

**Comment by friofry** [comment]
Cannot reproduce on 2.27.x branch (a6513e4c9)

![Image](https://github.com/status-im/status-desktop/assets/1083341/04a77869-668d-4177-ae5a-760c377df713)
