### ISSUE TITLE
Windows: crash during creating a new community

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#9449]
# Bug Report

## Description

Installed the Status app first time on a new PC. After attempting to create a new community, got a crash. After relaunch - everything was ok. (was observing on 2 PC's which did not have Status app before)

![image](https://user-images.githubusercontent.com/117639195/216923050-9d5b4f78-8a2e-4361-9580-17436603de84.png)

## Steps to reproduce

1. System did not have the Status app installed before
2. Open the Status app
3. Create a new account (without seed phrase)
4. Create a new community
5. Fill all necessary fields
6. Click "Create community"

#### Expected behavior

Community created

#### Actual behavior

Crash

### Additional Information

- Status desktop version: Status 0.9.0-beta
- Operating System: Windows 10

**Comment by iurimatias** [comment]
ca no longer replicate
