### ISSUE TITLE
Send modal shows "No balance" if left open for a long time

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#9458]
# Bug Report

## Description

It seems the Send modal is not handling background balance updates correctly. If left open for some time after entering an amount and a recipient address, it will eventually show "No Balances Active".

![Screenshot 2023-02-06 at 11 01 09 AM](https://user-images.githubusercontent.com/11161531/216992854-fc546007-55f4-4b99-a65c-279d24a88d2a.png)

![Screenshot 2023-02-06 at 11 07 09 AM](https://user-images.githubusercontent.com/11161531/216992878-63dfbfea-b388-4896-af06-4b39f76e4e99.png)

## Steps to reproduce

1. Open the Wallet's Send modal.
2. Enter a valid recipient address and amount. You should get proper fees calculation
3. Wait for a couple of minutes on that state. Eventually, the "No balances active" error message will be shown.

**Comment by Khushboo-dev-cpp** [comment]
as this will be fixed under Darios fix , reassign it to him https://github.com/status-im/status-desktop/pull/9578
