### ISSUE TITLE
Community -> Channels list: can't scroll list of channels with touchpad

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9460]
### Description

1. join a community with a lot of channels (dogfooding ideally)
2. try to scroll with touchpad across the channels list
3. try to hover over the scrolling indicator and drag it to scroll

As result, the scrolling of channels is not possible with touchpad

https://user-images.githubusercontent.com/82375995/217000717-5b39f186-75fb-4fc8-a7eb-47b1e0130447.mov

**Comment by anastasiyaig** [comment]
@jrainville please assign to someone to fix this for 0.10.0 if possible

**Comment by jrainville** [comment]
#9187 is not part of 0.10.

This is a UI issue, I'll let @alexandraB99 asign
