### ISSUE TITLE
Chat: Message history in db not displayed in UI after restart

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#9462]
# Bug Report

## Description

Occasionally on restart 1 or more chats will load without history. For example, for the UI Team chat 1717 messages are shown in the database but only the last one loaded in the UI.

![image](https://user-images.githubusercontent.com/50769329/217005550-8400ab9e-839d-42a9-96ea-853db4d0b066.png)

## Steps to reproduce

Restart 0.10.0 RC3 and evaluate chats known to have history.

#### Expected behavior

Message history available in the db loads

#### Actual behavior

Message history does not load and 1 or more restarts is required to access it.

### Additional Information

- Status desktop version: 0.10RC3
- Operating System: Mac

**Comment by caybro** [comment]
@glitchminer @0x-r4bbit looks like a dupe of https://github.com/status-im/status-desktop/issues/9361

**Comment by glitchminer** [comment]
> @glitchminer @0x-r4bbit looks like a dupe of #9361

Closing as dup.
