### ISSUE TITLE
Chat: Add contact prompt shown in chat with existing contact

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#9466]
# Bug Report

## Description

A prompt to add the user to contacts is shown overlayed on a chat with an existing contact.

![image](https://user-images.githubusercontent.com/50769329/217042472-4a69a0bc-fac1-4e83-9ab4-2cf3dc3cd1ee.png)

## Steps to reproduce

Restarted, navigated to chat, found add to contact message.

#### Expected behavior

Prompt is not shown for existing contacts and is not overlayed on top of the whole chat.

#### Actual behavior

A prompt to add the user to contacts is shown overlayed on a chat with an existing contact.

### Additional Information

- Status desktop version: 0.10 RC3
- Operating System: Mac

**Comment by jrainville** [comment]
Fixed on master. Need to update RC
