### ISSUE TITLE
Contacts: Contacts are missing and requests are inconsistent

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#9468]
# Bug Report

## Description

After restarting today my contacts list is empty. Additionally, the pending contacts has 3 requests for contacts that were previously already accepted. Clicking on accept again does nothing for the first contact, r4bbit. Accepting Patryk again add to the contact list but with large spacing - even after accepting the chat still shows as unaccepted.

![image](https://user-images.githubusercontent.com/50769329/217045646-6f7472ac-24ba-4c95-b442-bbd3052b8490.png)
![image](https://user-images.githubusercontent.com/50769329/217045675-29dc6428-604b-4bfa-a915-3fd58f9127ba.png)
![image](https://user-images.githubusercontent.com/50769329/217046790-fc9e1665-3542-46e7-85c9-1edbe9be9d16.png)

## Steps to reproduce

Noticed contact list was empty during daily use, restarted and list is still empty

#### Expected behavior

Contacts are shown and accepted as expected

#### Actual behavior

Contact list and requests appear to be broken.

### Additional Information

- Status desktop version: 0.10 RC3
- Operating System: Mac

**Comment by jrainville** [comment]
This is fixed on latest master. We need to update the version of status-go on 0.10
