### ISSUE TITLE
App loading bar featuring 'Did you know?' content

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#9470]
Currently, when logging into Status, the Status logo animation loops a couple of times before freezing with no further indication to the user that any loading/readying of the app is taking place. The app looks like it has become unresponsive which may prompt users to force quit and relaunch the app to try again.

**Current behaviour:**

https://user-images.githubusercontent.com/110033914/217079789-89405af6-4736-4420-bede-680b6a2f4a22.mov

To clarify to the user that the app is still 'loading'/being prepared during this time, the recommendation is to present a 'dummy'/fake loading bar. The loading bar will gradually fill during the c.30secs it takes between the user inputting their credentials and the content of the app loading. 

While the loading bar is filling, there is an opportunity to present the user with some messaging that will make the loading state a little more interesting and help us market the core features of the app / what we are currently working on. 

Above the loading bar, we have a constant header; 'Did you know?' (as shown in the below recording) followed by messaging randomly selected from the below notion doc. The loading bar should show a random message from category one ('Features'), then a random message from category 2 ('Principles'), then a random message from category 3 ('Organisation') and so on until the message from the last category is presented. We should aim for the 'Did you know?' items to be fairly different with each log in.So a user sees different messaging from each category each time they log in (there will obviously be some unavoidable repetition between sessions). 

https://www.notion.so/Loading-screen-messaging-be82db41dac746f9b203ac82eb6be0b3

**Proposed behaviour:**
(Please refer to the Notion doc above for the final text to be used above the notification bar)

https://user-images.githubusercontent.com/110033914/217079670-963ea439-2392-400b-a2b1-754564b6c7f0.mov

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=25878%3A518438&t=C7xTpNib38t7s7XU-4

cc @John-44 @iurimatias

**Comment by John-44** [comment]
@iurimatias @jrainville @alexandraB99 One thing to note - the animation shown in this video is supposed to be shown **after** all the other loading animations are completed e.g. at the point today where the user would be landed into the app.  Instead of landing the user into the app, we add an additional 30second delay (during which we show this loading bar and fun info messages) to let things load from waku in the background.  Then when the user is landed in the app, the app has already been running for 30 seconds post-user login.  This means things won't be jumping around and loading in for the first 20 or so seconds after the user initially lands in the app

**Comment by John-44** [comment]
@alexjba @alexandraB99 see comment I left on issue https://github.com/status-im/status-desktop/issues/9524#issuecomment-1427562377 as it is relevant for this issue (tldr; we should use @caybro's gpu status logo spinner) and hopefully @caybro will be able to make the size of the gpu spun Status logo larger.

**Comment by saledjenic** [comment]
> Instead of landing the user into the app, we add an additional 30second delay (during which we show this loading bar and fun info messages) to let things load from waku in the background. Then when the user is landed in the app, the app has already been running for 30 seconds post-user login.

An update to whoever is going to work on this, we already have this on the backend side and use it for recovering an existing account (via seed phrase or keycard) so what would we need in this case is to move all onboarding flows to that backend logic and add on the UI side loading bar and fun info messages. (Once this is done, please check all possible onboarding flows before merging this.)

But personally I don't like at all that kind of faking/masking the things. We set it up to 30secs, but what would happen to those who has weak pc configuration or a slow internet connection and need more time? They will still see loading animation freeze.

**Comment by alexjba** [comment]
> > Instead of landing the user into the app, we add an additional 30second delay (during which we show this loading bar and fun info messages) to let things load from waku in the background. Then when the user is landed in the app, the app has already been running for 30 seconds post-user login.
> 
> An update to whoever is going to work on this, we already have this on the backend side and use it for recovering an existing account (via seed phrase or keycard) so what would we need in this case is to move all onboarding flows to that backend logic and add on the UI side loading bar and fun info messages. (Once this is done, please check all possible onboarding flows before merging this.)
> 
> But personally I don't like at all that kind of faking/masking the things. We set it up to 30secs, but what would happen to those who has weak pc configuration or a slow internet connection and need more time? They will still see loading animation freeze.

The freezing loading animation should be fixed here: #9524
@saledjenic I know we have the profile fetching progress implemented in the backend, do you think we need it for this new loading view?
Please consider that this new loading view will be shown after the current Splash Screen (it will not replace it). The rationale being to avoid jumpy UI components being showed on the screen. Since it will be used to hide the current main view until it's stable, I fail to see the connection with onboarding flows.

**Comment by caybro** [comment]
Sounds reasonable; let's make this configurable, defaulting to `true` on a release build, and `false` for a debug/development build?

**Comment by John-44** [comment]
> Sounds reasonable; let's make this configurable, defaulting to `true` on a release build, and `false` for a debug/development build?

Sounds good to me :-)

**Comment by saledjenic** [comment]
> @saledjenic I know we have the profile fetching progress implemented in the backend, do you think we need it for this new loading view?

@alexjba it doesn't have anything to profile fetching and so, was talking about delayed login for recovering account flow. Should be similar to what's discussed above.

I just wanted to say that the similar/same behaviour is implemented for recovering an account (logic is already developed and may be used in above discussed case as well). At the moment when everything is ready to move to the app, we are displaying the loading animation for 30 seconds just to be sure that the latest backed up messages are received and then move to another state.
