### ISSUE TITLE
Migrate to lower-case password hash

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#9492]
## Description

Mobile is using lower-case password hashing.
Sine we're about to sync devices, we should make it same on both platforms.

@Samyoul said that lower-case is standard, so we should keep to that one.

**Comment by alaibe** [comment]
From Sam:
`
Ok, I think that there is already a password change flow, so we could just wrap that in the login flow. so the users enters the password, auths, triggers password change behind the scenes. Noone needs to be asked to enter their password at some other random point
And maybe a flag of some kind that could identify if the password is upper or lower. Just to skip any redundant noop.
Hmm, that's the tricky part. How do we know what case the encoded password is in before we attempt to migrate?
`

Maybe we can add a setting property to say "passwordMigrated" and set it to true, so we do that only once

**Comment by igor-sirotin** [comment]
@alaibe in case of further password migrations, I'd propose to create `passwordVersion` property.
Hopefully there won't be any, but it wouldn't hurt now to do that instead of simple `bool`.
wdyt?

**Comment by jrainville** [comment]
Good idea

**Comment by Samyoul** [comment]
We have a pre-existing process flow for password change, please see this function.

https://github.com/status-im/status-go/blob/7e1a894ab824904f0c90acbc307955940ef17800/mobile/status.go#L833-L839

My formalised recommendation for the implementation of this functionality is as follows:

> We could encode in lower case first. If that validates then all is good. Else encode in uppercase, if that validates, auth, then change password. Else login fails

I'd imagine the code to look something like below:

```go

	// normalise the hex encoding prefix
	if password[:2] != "0x" {
		password = "0x" + password
	}

	// parse the password string to lowercase
	password = strings.ToLower(password)

	// authentication

	// If auth is fine, return

	// Else parse password string to uppercase
	password = "0x" + strings.ToUpper(password[2:])
	
	// reattempt authentication
	
	// if success 

	err := statusBackend.ChangeDatabasePassword(KeyUID, password, newPassword)
	
	// else fail authentication
```

In this case you don't need to version your passwords, you just normalise the password and rekey only if normalisation fails.

What do you think?

**Comment by jrainville** [comment]
That's a sound suggestion as well. It's simpler since we don't have to keep a version

**Comment by alaibe** [comment]
simpler, I like it that way
