### ISSUE TITLE
Improve channel list model to have Categories as Items to simplify code

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9494]
### Description

The chat model flattening was completed, but using the section delegate property of ListView for the Categories creates a lot of complex cases, since categories are way more than just one property.

To fix it, we should add the categories themselves in the model as Items, with a special type. We would no longer need the empty chat Items. To show the category Header, we'd use a Loader with a switch case on the type to choose the right delegate.
The chat Items would still have the same properties for the position, we'd just need to set the category's `position` to `-1` so it appears above its chats.

**Comment by caybro** [comment]
@jrainville to get an inspiration, have a look at our own, very similar model for StoryBook: https://github.com/status-im/status-desktop/blob/master/storybook/sectionsdecoratormodel.h
