### ISSUE TITLE
[Automation] The test `user sets display name, bio and social links` is broken

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9499]
### Description

See this report: https://ci.status.im/job/status-desktop/job/branches/job/e2e/job/PR-9495/4/squishResults_230208_193142.304/webreport_230208_193142.304_linux-04/index.html

The test `user sets display name, bio and social links` fails on step `the user's social links are empty`

Tests must pass individually and in sequence.

Remove mayfail tag once it's done.

**Comment by noeliaSD** [comment]
This is, in fact, an application bug, not a squish test issue! Popup is malformed if you see the screenshot on failure from the report shared.

**Comment by caybro** [comment]
Fixed in https://github.com/status-im/status-desktop/compare/0d659aaac7322d41f0e63c4dcbce1c9be7b18cdf..91cf50ec218fffa8ae4559300d87e1cd34efcaa4 as part of https://github.com/status-im/status-desktop/pull/9478
