### ISSUE TITLE
Broken communities tests

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#9501]
# Bug Report

Failing on master
- Scenario Outline: `The user can edit a message`
  - Fails on master, also
- Scenario Outline: `The admin edits a community name, description and color`
  - fails on master: broken scroll, and button press miss

**Comment by jrainville** [comment]
Maybe you were not on top of latest master? Those tests work fine for me and even passed on this PR: https://github.com/status-im/status-desktop/pull/9500

**Comment by stefandunca** [comment]
> Maybe you were not on top of latest master? Those tests work fine for me and even passed on this PR: #9500

Closing due to the latest master fixing the issues I faced.
