### ISSUE TITLE
Pasting a user's profile link in the ad-hoc chat search doesn't work in the community section

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9513]
# Bug Report

## Description

When you paste the chat key or profile link of another user in the chat section, it opens the contact request popup as expected, but in the community section, it doesn't do anything.

## Steps to reproduce

1. go in a community
2. Open ad hoc chat section (Start chat)
3. Enter a profile link eg: `https://join.status.im/u/zQ3shY58UcvyLbNJDePCE3CQ8hvMFFfsB9V1fLMatne4RgUtF`
4. Nothing happens

#### Expected behavior

The contact request popup should open

### Additional Information

- Status desktop version: master (`2004adafba816042752af204b1a5bfac8027e731`)
- Operating System: Linux

**Comment by caybro** [comment]
Because:

```
Warning: qrc:/app/AppLayouts/Chat/views/CreateChatView.qml:184: TypeError: Cannot read property 'contactsModel' of undefined (qrc:/app/AppLayouts/Chat/views/CreateChatView.qml:184, )
Warning: qrc:/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml:37: TypeError: Cannot read property 'contactsModel' of undefined (qrc:/app/AppLayouts/Chat/views/private/MembersSelectorBase.qml:37, )
Warning: qrc:/app/AppLayouts/Chat/views/MembersSelectorView.qml:90: TypeError: Cannot read property 'contactsStore' of undefined (qrc:/app/AppLayouts/Chat/views/MembersSelectorView.qml:90, )
Warning: qrc:/app/mainui/AppMain.qml:902: TypeError: Cannot read property 'rootStore' of null (qrc:/app/mainui/AppMain.qml:902, )
Warning: qrc:/app/AppLayouts/Chat/views/MembersSelectorView.qml:60: TypeError: Cannot read property 'contactsStore' of undefined (qrc:/app/AppLayouts/Chat/views/MembersSelectorView.qml:60, )
```

**Comment by caybro** [comment]
There are other such problems, with the stickers popup or the activity center, coming from the fact the ChatLayout is now inside the Loader
