### ISSUE TITLE
App for Windows doesn't work

### ISSUE THREAD

**Issue by Revelation14712** [status-im/status-desktop#9527]
I installed status app for desktop, my computer is Win11, but it always show many error messages while I was opening it.

First, this app popped up many error messages while I set up new password as it asked; second, it cannot be sync with my account on my cell phone; third, even I use the keywords to login my account, it always show empty there, cannot show people are in my friend's list or group. I don't understand this.

Third, if I created a new account, still shows many errors while I was trying to login.

So is there any possible to fix this? By the way, I was trying to attach screenshots here, but none got through.

Thanks a lot.

Ruth

**Comment by anastasiyaig** [comment]
hi @Revelation14712 ! Thank you for reporting this. Is there any way to know which version of status app u are on?

**Comment by Revelation14712** [comment]
Hi,

Thank you for the reply.

I have uninstalled the app for windows, but here is the screenshot of this app.
[Snipaste_2023-02-13_21-01-38.png]

Looking forward to see this app can be used well for PC.

Thanks a lot!

May God richly bless you,

Ruth

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2023年2月13日 星期一 下午 8:39，Anastasiya Semenkevich ***@***.***> 来信：

**Comment by Revelation14712** [comment]
[Snipaste_2023-02-13_21-01-38.png]

May God richly bless you,

Ruth

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2023年2月14日 星期二 上午 12:08，Iuri Matias ***@***.***> 来信：

**Comment by jrainville** [comment]
@Revelation14712 it still didn't work. Could you try to paste the image in Github directly? I think by email it fails.

**Comment by Revelation14712** [comment]
StatusIm-Desktop-v0.3.0-beta-a8c37d

This is the name of the app for windows

Thanks!

May God richly bless you,

Ruth

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2023年2月21日 星期二 上午 1:09，Jonathan Rainville ***@***.***> 来信：

**Comment by jrainville** [comment]
@Revelation14712 that is a very old version. Our website is not updated sadly. The newest versions can be found on Github. The latest is 0.9.0 https://github.com/status-im/status-desktop/releases/tag/0.9.0. 0.10.0 is gonna release soon too.

**Comment by Revelation14712** [comment]
Thank you!

Appreciate your help!

May God richly bless you,

Ruth

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2023年2月21日 星期二 上午 2:00，Jonathan Rainville ***@***.***> 来信：

**Comment by jrainville** [comment]
Closing as this was using a very old version. Feel free to reopen if you experience the same with a newer version (0.10 just released)
