### ISSUE TITLE
[Community Permissions]: Disable/hide permissions other than `become admin` and `become member` for the first version

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#9537]
## Description

In order to implement permissions functionality step by step, first only two types (community-wise) permissions should be available for the end user.

**Comment by noeliaSD** [comment]
We need to reenable all [categories](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22721%3A500591&t=fMY6WYccLEDhAffn-1) again and allow the [channels](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22734%3A503657&t=fMY6WYccLEDhAffn-1) selectios:

![Screenshot 2023-05-24 at 11 04 48](https://github.com/status-im/status-desktop/assets/97019400/1f46cd8a-7d36-4926-bfb8-26ea14e93e7a)

![Screenshot 2023-05-24 at 11 04 56](https://github.com/status-im/status-desktop/assets/97019400/19931842-24b2-4c92-92b7-f10bcaf67c09)

**Comment by 0x-r4bbit** [comment]
@noeliaSD can you point me to where `categories` have been disabled?

**Comment by micieslak** [comment]
> @noeliaSD can you point me to where `categories` have been disabled?

@0x-r4bbit Categories have been disabled in `ui/app/AppLayouts/Chat/controls/community/PermissionsDropdown.qml`.

**Comment by 0x-r4bbit** [comment]
@micieslak I only see `channels` in there, but no mentions of categories. Can you point me to some sample model that shows what data is expected where so that categories are rendered in the dropdown?

**Comment by micieslak** [comment]
> @micieslak I only see `channels` in there, but no mentions of categories. Can you point me to some sample model that shows what data is expected where so that categories are rendered in the dropdown?

Sorry @0x-r4bbit for late reply, I've missed your post. You mean channel categories, right?

I created channel category on current master and I see it in the new permission view. But there is a problem with scrolling, the popup has improper height.

![Screenshot from 2023-06-19 13-49-36](https://github.com/status-im/status-desktop/assets/20650004/c25a116c-90c1-49bb-a5fb-53eb335c7b2b)

![Screenshot from 2023-06-19 13-49-22](https://github.com/status-im/status-desktop/assets/20650004/4eb90052-dfbf-49c9-8089-d8483a3f5f16)

The categories themselves are there. So I'm not sure where the problem can be. Could you share some screens depicting your problem?
