### ISSUE TITLE
Use https:// deep links instead of status-im:// - Windows

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#9549]
Related to #7957

Discussions in https://github.com/status-im/status-web/issues/327

**Comment by felicio** [comment]
@endulab please, could you add the following to description as one of acceptance criteria

- when passed `https://myphotoapp.example.com/albums?albumname=vacation&index=1#secret` platform can access both query parameters after `?` as well as value after `#`

of

- this issue
- https://github.com/status-im/status-desktop/issues/7957
- https://github.com/status-im/status-desktop/issues/8027

**Comment by jrainville** [comment]
I tried using `https://status-whetever` in the registry and it doesn't work.
`http` and `https` are both already handled by Windows.

Unless I misunderstood the task, I don't think it's possible to make a deep link start with `http(s)` on Windows.

We can have `status-im://` or `status-app://` or anything like that though.

@felicio @endulab

**Comment by felicio** [comment]
@jrainville thanks,

> I don't think it's possible to make a deep link start with http(s) on Windows.

I'd say following supports your conclusion.

> More than one app can register to handle the same URI scheme. The exception to this is for reserved URI schemes. Registrations of reserved URI schemes are ignored. – https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app?source=recommendations

>Reserved URI scheme names – https://learn.microsoft.com/en-us/windows/uwp/launch-resume/reserved-uri-scheme-names#reserved-uri-scheme-names

<img width="826" alt="image" src="https://github.com/status-im/status-desktop/assets/13265126/3aeddeb9-62fa-4e9f-9ea9-f7e2155dcec4">

And about,

> test if passed https://myphotoapp.example.com/albums?albumname=vacation&index=1#secret, platform can access both query parameters after ? as well as value after #

were you able to test that with `status-im://` then?

**Comment by jrainville** [comment]
> were you able to test that with status-im:// then?

I'll test it, but it should be supported

**Comment by felicio** [comment]
> > were you able to test that with status-im:// then?
> 
> I'll test it, but it should be supported

Right.

And just to make sure, I was referring to

> platform can access both query parameters after ? as well as value after #

**Comment by felicio** [comment]
> @felicio I just tested and it works.
> In the app I receive the full URL `status-im://albums/?albumname=vacation&index=1#secret`, so we can easily use a lib or regex to parse it as we want

thank you @jrainville.

Going forward, do you favor `status-app://` over `status-im://`?

@John-44 given the discussion here, Windows app won't automatically open on clicking `https://` links. That aside, for redirects like "Open in...", do you prefer to keep `status-im://` link or deprecate them  in favor of `status-app://`?

Cc @jakubgs

**Comment by John-44** [comment]
> > @felicio I just tested and it works.
> > In the app I receive the full URL `status-im://albums/?albumname=vacation&index=1#secret`, so we can easily use a lib or regex to parse it as we want
> 
> thank you @jrainville.
> 
> Going forward, do you favor `status-app://` over `status-im://`?
> 
> @John-44 given the discussion here, Windows app won't automatically open on clicking `https://` links. That aside, for redirects like "Open in...", do you prefer to keep `status-im://` link or deprecate them in favor of `status-app://`?
> 
> Cc @jakubgs

We should use status-app:// as it's more in-line with the status.app domain we will be using for the new websites going forward

**Comment by John-44** [comment]
Could packaging Status as a UWP app for windows could be an option?  Probably not, but from a quick google: it seems that they can be directly installed without going through the windows app store ( https://stackoverflow.com/questions/71800494/digitally-sign-a-uwp-standalone-app-package ) and building UWP apps is supported by QT5 ( https://doc.qt.io/qt-5/winrt-support.html )

**Comment by jrainville** [comment]
Reading the documentation, I have a couple of doubts/questions.

In the Microsoft docs, they say:

> Starting with the Windows 10 Creators update, supported links clicked in Microsoft Edge Legacy will launch the corresponding app. Supported links clicked in other browsers (for example, Microsoft Edge Chromium, Internet Explorer, etc.), will keep you in the browsing experience.

Does that mean that only Edge Legacy supports that linking feature, or they are just explaining badly?

Then, they go on to show how to handle the link activation in the app... in C#.
I did find in another page there is also a C++ example, but it's still different from what we have right now, which is to pass the URL to the app as options eg: `status.exe --url="status-im://c/0x...`
We can maybe do the `OnActivated` in DOtherSide, but it needs investigation.

Another thing that concerned me from the QT docs is this: 

> The UWP clipboard is local to the application; it cannot be retrieved by a desktop application.

If it is really that we cannot share the clipboard from our app with other apps, then that's big hit on UX and not worth it IMO.

---

In sum, it seems like a big endeavor to switch from what we have right now to UWP, with such a small deadline.

Can we do that switch after the MVP and support `status-app://` instead in the meantime?

The switch to `status-app://` is gonna take 5 minutes BTW, compared to the whole adventure that is a switch to UWP :laughing:

**Comment by John-44** [comment]
> Reading the documentation, I have a couple of doubts/questions.
> 
> In the Microsoft docs, they say:
> 
> > Starting with the Windows 10 Creators update, supported links clicked in Microsoft Edge Legacy will launch the corresponding app. Supported links clicked in other browsers (for example, Microsoft Edge Chromium, Internet Explorer, etc.), will keep you in the browsing experience.
> 
> Does that mean that only Edge Legacy supports that linking feature, or they are just explaining badly?
> 
> Then, they go on to show how to handle the link activation in the app... in C#. I did find in another page there is also a C++ example, but it's still different from what we have right now, which is to pass the URL to the app as options eg: `status.exe --url="status-im://c/0x...` We can maybe do the `OnActivated` in DOtherSide, but it needs investigation.
> 
> Another thing that concerned me from the QT docs is this:
> 
> > The UWP clipboard is local to the application; it cannot be retrieved by a desktop application.
> 
> If it is really that we cannot share the clipboard from our app with other apps, then that's big hit on UX and not worth it IMO.
> 
> In sum, it seems like a big endeavor to switch from what we have right now to UWP, with such a small deadline.
> 
> Can we do that switch after the MVP and support `status-app://` instead in the meantime?
> 
> The switch to `status-app://` is gonna take 5 minutes BTW, compared to the whole adventure that is a switch to UWP 😆

Agreed, I don't think changing to being a UWP app is a good idea for several reasons.  Shared because I found that and thought it might be interesting in the conversation, but it's not something we should do.
