### ISSUE TITLE
After archive download, notification dot on Community remains

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#9566]
# Bug Report

## Description

Since the archive download was successful, the notification dot on Status Community has remained despite no channel showing up as unread

## Steps to reproduce

1. Wait for app to download archive
2. Bunch of channels with archive messages will show as unread
3. Go through all channel til no channel is marked as unread
4. Enjoy the permanent unread dot on the Status Community logo	

#### Expected behavior

Dot goes away

#### Actual behavior

Dot remains

### Additional Information

- Status desktop version: 0.9.0
- Operating System: Linux Fedora App Image

**Comment by jrainville** [comment]
This has been fixed. Please reopen if it happens again
