### ISSUE TITLE
Saved addresses are not in sync between devices

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#9567]
# Bug Report
Addresses are not synced between paired devices, though sync switches are enabled in settings next to each of the paired devices.

## Description

Addresses are not in sync after  "Sync all devices" button clicked

## Steps to reproduce

- Launch 2 instances of Status desktop app
- Click "Advertise" button on each of them
- Enable syncing when they are paired

#### Expected behavior
When saved address is added or modified, the changes must be visible for the second instance
#### Actual behavior
No syncing happens, no changes visible
### Additional Information

- Status desktop version: master bc353a1cc
- Operating System: Ubuntu 20.04

**Comment by anastasiyaig** [comment]
it sounds like a regerssion btw, @stefandunca i think u implemented this functionality and it was working 100%, can u please check where it got broken?

**Comment by anastasiyaig** [comment]
sure sure @IvanBelyakoff i was just trying to help u

**Comment by stefandunca** [comment]
@anastasiyaig appreciations for the heads up. @IvanBelyakoff ping me if you think I can land a hand.

I reviewed the PR but didn't see anything suspicious. I would try first with a cleanup state to exclude a data corruption issue, check the DB and if the data is all right check the notification change for the UI.
