### ISSUE TITLE
Truncation of channel description and pinned message text on smaller viewports

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#9583]
Following on from the UI enhancements from @caybro on the pinned messages modal [here](https://github.com/status-im/status-desktop/issues/9396), the below are suggestions for how we can implement truncation to the channel description and any pinned messages link that is present when the app is reduced in width by the user.

cc @John-44 

1. On both Group Chats and Communities, the pinned messages icon and link should come last. (i.e. following the number of members for Group Chats and after the channel description (if there is one) for Communities).

<img width="1440" alt="00-pinned" src="https://user-images.githubusercontent.com/110033914/219738568-40d5a95d-b872-4372-8c02-8f736fc1e97c.png">

2. Where there is only 1 pinned message, the link should read `1 Pinned message` with no pluralisation 

<img width="1440" alt="01-pinned" src="https://user-images.githubusercontent.com/110033914/220060038-21b9066c-c00d-4604-ab9f-9ae9bbd19b9b.png">

3. Example of a single pinned message link following on from a standard length channel description 

<img width="1440" alt="02-pinned" src="https://user-images.githubusercontent.com/110033914/220060091-bd0974b0-c515-44fe-9c44-4dc8e34c9477.png">

4. Only when there is more than 1 pinned message do we show the number - i.e. `2 pinned messages`, `3 pinned messages`

<img width="1440" alt="03-pinned" src="https://user-images.githubusercontent.com/110033914/219740117-c7236d15-9eb3-4060-8e16-c25fd2cd0807.png">

5. We should observe a minimum padding of 40px between the top right UI icon buttons and the channel description/pinned messages link. To do this, we should truncate the channel description and pinned messages link at the same time. The pinned messages link should become `[n] pinned...`. Where further reductions in app width are made, the pinned messages link would retain this truncated format and any further truncation is applied to the channel description only

<img width="1440" alt="04-pinned" src="https://user-images.githubusercontent.com/110033914/219740322-0d7947b4-6ea0-499a-b1c3-a353338898c9.png">

<img width="1216" alt="05-pinned" src="https://user-images.githubusercontent.com/110033914/219741621-71ee8a8b-6dd7-4693-b946-22eaef9a4f56.png">

<img width="1004" alt="06-pinned" src="https://user-images.githubusercontent.com/110033914/219741699-06206921-43e2-47af-80e3-52c9a3676066.png">

6. The channel description and pinned message link could be revealed in full via a tooltip. We could perhaps set this to be a prolonged hover of 1sec+ to avoid the tooltip getting in the way of the UI if the user hovers it by accident.

<img width="1004" alt="07-pinned" src="https://user-images.githubusercontent.com/110033914/219742256-5ed7d6bb-e395-43d0-9a0d-ba68d4a946eb.png">

<img width="1004" alt="08-pinned" src="https://user-images.githubusercontent.com/110033914/219742295-f0347841-c930-4de3-b298-fcd4312885ad.png">

7. An additional, related recommendation for the absolute minimum body area for the app (i.e. the min width of the message feed area) would be to ensure 40px min padding between the top right UI icons and the longest possible channel title (24 characters) as shown below. This preserves the channel name and access to the tooltips to show the full channel description and pinned messages link as discussed in point 6.

<img width="854" alt="09-pinned" src="https://user-images.githubusercontent.com/110033914/219743595-2ee00279-991a-4640-88c8-26488e1fdd99.png">

These are just suggestions at this point and should await John's sign off / comments before implementing

**Comment by John-44** [comment]
@benjthayer I think in the case of one pinned message it should say "1 pinned message" (instead of "pinned message").  Sorry, I may have described this incorrectly to you, I meant to say that if there is only one pinned message the words "pinned message" should not be pluralised.

Otherwise looks great :-)

**Comment by benjthayer** [comment]
Done - @caybro this should be ready for implementation now :) Any questions or issues just shout. Thanks!

**Comment by alexandraB99** [comment]
closes https://github.com/status-im/status-desktop/issues/9056
