### ISSUE TITLE
fix(StatusQ): remove non-existing `Sandbox` import in sandbox's pages and adjust build script

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#9594]
# Bug Report

## Description

Sanbox pages had unused `import Sanbox`, which has been removed. Now it's causing runtime errors, and needs to be just removed.

The build script is outdated. Some little change is needed to make it working again. Anyway it works nicely from QtCreator.

**Comment by caybro** [comment]
@micieslak got it fixed locally already; so I can take it

**Comment by micieslak** [comment]
> @micieslak got it fixed locally already; so I can take it

Ops, sorry, I haven't noticed your comment... :(

**Comment by caybro** [comment]
> > @micieslak got it fixed locally already; so I can take it
> 
> Ops, sorry, I haven't noticed your comment... :(

No prob, you were faster with the PR anyway :)
