### ISSUE TITLE
Mentions and replies don't appear until app restart

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9598]
# Bug Report

## Description

Big issue. If you mention or reply to someone, that person will **not** receive that before they restart the app.

Something is broken with how we handle the signal.

## Steps to reproduce

1. Have both apps open
2. send a mention or reply to account B
3. account B doesn't receive it. They will only see it if they restart

[Screencast 2023-02-20 13:43:48mention.webm](https://user-images.githubusercontent.com/11926403/220180251-fdeaebed-590f-4573-b260-f6757503b34a.webm)

### Additional Information

- Status desktop version: master `c23f4e173e22e468f32a46322da004e84f844106`
- Operating System: Ubuntu 20

**Comment by caybro** [comment]
Does this have some PR, it's "Under review"?
