### ISSUE TITLE
[Community Permissions] Fix tooltip offset for notification bell icon in `JoinCommunityView`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9615]
### Description
The notification tooltip is placed slightly to the left so add the proper offset to display it in the center.

![image](https://user-images.githubusercontent.com/97019400/220631250-d7943ca4-4dbd-4a86-8daf-cbfff9facda3.png)

**Comment by caybro** [comment]
It happens when the member list is hidden (or anywhere when the bell icon is on the right edge of the window)

**Comment by noeliaSD** [comment]
To clarify, this is the normal behavior when the memberlist is closed so comparing with the `JoinCommunityView`, it is slightly placed to the left: 
![Screenshot 2023-02-23 at 09 54 10](https://user-images.githubusercontent.com/97019400/220861227-ec2593ae-2cd9-4f6b-902b-45b8c9877915.png)
