### ISSUE TITLE
Wallet: sending 0 transaction is not possible, Send button is not displayed

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9623]
### Description

_Switch to testnet_

1. enable wallet
2. generate account
3. click Send
4. put 0 into amount field
5. select Eth 
6. wait for calculations

As result, having 0 in amount field does not allow the send button to show up

<img width="1943" alt="Screenshot 2023-02-23 at 13 25 34" src="https://user-images.githubusercontent.com/82375995/220881417-a28477c6-9836-4e1e-8f67-5fce770b2180.png">

**Comment by anastasiyaig** [comment]
@alaibe @Khushboo-dev-cpp please take a look guys , it is recent master

**Comment by alaibe** [comment]
On it
