### ISSUE TITLE
Balance History fetches only few entries for short lived chains

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#9624]
## Bug Report (Limitation)

Investigations for https://github.com/status-im/status-desktop/issues/9582 revealed that the fixed hard coded stride length would only fetch `5` entries for `Arbitrum` and `3` for `Optimism` in the case of All time. Root cause:

- Hardcoded fixed stride length (every 4 months) optimises for the L1 chain, where `22` points are fetched (30.07.2015 is the first block)
- Short life of the chains. First blocks
  - Optimism: 11.11.2021
  - Arbitrum: 29.05.2021

### Validation

- On a clean balance-history fetching (restore or new account), the all-time graph for L1 should have more than 4-5 entries (at least double, depending on the token time deployment)

**Comment by alaibe** [comment]
Is that really a "limitation" or a design decision, as we only fetch data points every 4 months?

**Comment by stefandunca** [comment]
Improve by fetching at a higher interval for all time (every month instead of every four months). The new interval change will increase three times the all-time request count and only for the first fetch (except the last year when we reuse from other time intervals). Later on, it will recycle from different time intervals.
