### ISSUE TITLE
Crash when canceling a contact request

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#9625]
# Bug Report
In an attempt to cancel/withdraw outgoing contact request, the app crashes with:
```
ERR 2023-02-23 14:12:28.512+01:00 rpc response error                         topics="rpc" tid=39036 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_retractContactRequest, code:-32000, message:retract-contact-request: invalid id ]\n"
ERR 2023-02-23 14:12:28.512+01:00 error doing rpc request                    topics="rpc" tid=39036 file=core.nim:40 methodName=wakuext_retractContactRequest exception="\nstatus-go error [methodName:wakuext_retractContactRequest, code:-32000, message:retract-contact-request: invalid id ]\n"
INF 2023-02-23 14:12:28.513+01:00 shutting down...                           topics="status-app" tid=39036 file=nim_status_client.nim:144
INF 2023-02-23 14:12:28.517+01:00 logging out...                             topics="app-controller" tid=39036 file=app_controller.nim:273
Traceback (most recent call last)
/home/ltinkl/git/status/status-desktop/src/nim_status_client.nim(180) nim_status_client
/home/ltinkl/git/status/status-desktop/src/nim_status_client.nim(154) mainProc
/home/ltinkl/git/status/status-desktop/src/app/boot/app_controller.nim(276) delete
/home/ltinkl/git/status/status-desktop/src/app/global/global_singleton.nim(67) delete
/home/ltinkl/git/status/status-desktop/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by MishkaRogachev** [comment]
confirmed

**Comment by caybro** [comment]
@MishkaRogachev there's a similar one (albeit without a crash) when trying to cancel _ID_ request:

```
DBG 2023-02-27 13:48:07.468+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=40419 file=core.nim:27 rpc_method=wakuext_getVerificationRequestSentTo
DBG 2023-02-27 13:48:07.469+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=40419 file=core.nim:27 rpc_method=wakuext_cancelVerificationRequest
ERR 2023-02-27 13:48:07.471+01:00 rpc response error                         topics="rpc" tid=40419 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_cancelVerificationRequest, code:-32000, message:verification request not found ]\n"
ERR 2023-02-27 13:48:07.471+01:00 error doing rpc request                    topics="rpc" tid=40419 file=core.nim:40 methodName=wakuext_cancelVerificationRequest exception="\nstatus-go error [methodName:wakuext_cancelVerificationRequest, code:-32000, message:verification request not found ]\n"
ERR 2023-02-27 13:48:07.471+01:00 Error canceling verification request       topics="contacts-service" tid=40419 file=service.nim:722 msg="\nstatus-go error [methodName:wakuext_cancelVerificationRequest, code:-32000, message:verification request not found ]\n"
```

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev there's a similar one (albeit without a crash) when trying to cancel _ID_ request:
> 
> ```
> DBG 2023-02-27 13:48:07.468+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=40419 file=core.nim:27 rpc_method=wakuext_getVerificationRequestSentTo
> DBG 2023-02-27 13:48:07.469+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=40419 file=core.nim:27 rpc_method=wakuext_cancelVerificationRequest
> ERR 2023-02-27 13:48:07.471+01:00 rpc response error                         topics="rpc" tid=40419 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_cancelVerificationRequest, code:-32000, message:verification request not found ]\n"
> ERR 2023-02-27 13:48:07.471+01:00 error doing rpc request                    topics="rpc" tid=40419 file=core.nim:40 methodName=wakuext_cancelVerificationRequest exception="\nstatus-go error [methodName:wakuext_cancelVerificationRequest, code:-32000, message:verification request not found ]\n"
> ERR 2023-02-27 13:48:07.471+01:00 Error canceling verification request       topics="contacts-service" tid=40419 file=service.nim:722 msg="\nstatus-go error [methodName:wakuext_cancelVerificationRequest, code:-32000, message:verification request not found ]\n"
> ```
@caybro tested with last master: cancelling verification request works fine: 
`DBG 2023-02-27 17:42:26.511+04:00 NewBE_callPrivateRPC                       topics="rpc" tid=308430 file=core.nim:27 rpc_method=wakuext_cancelVerificationRequest`
