### ISSUE TITLE
Loading screen after adding account

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#9648]
In wallet, add a new account
While no data is being show there should be a loading screen

Currently: blank screen

**Comment by Khushboo-dev-cpp** [comment]
Loading is present currently when adding a new account

https://user-images.githubusercontent.com/60327365/225900279-d67ec910-070c-4da9-a54e-1eddc6a24cd4.mov

will use this tickets to improve the code, as currently even though the other accounts are not refreshed, the loading state is shown for all, also move logic of loading from ui to nim
