### ISSUE TITLE
Community link unfurling looks bad when the community data is not loaded yet

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9653]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/11926403/221612878-c251c55e-4737-4d1e-a595-c9a34a0d7380.png)

As you can see here, there are 2 link unfurlings that look very bad. They unfurled, but with not data and they don't have a height.

The one at the bottom looks good because it has the right data.

## Steps to reproduce

Paste a link to a community that's hard to get data from I guess? try `https://join.status.im/c/zQ3shqrjCCKMkGqaLTWuPECqkHNNUVy5FVQtBMoQ6yVLsfE5j` or `https://join.status.im/c/zQ3shewQAiWGQ8i2fsqNKoPFdjn5iL254UEGLWpLe7WkCsW87`

#### Expected behavior

Link doesn't unfurl until the data is loaded **correctly**. 

#### Actual behavior

It unfurls even with no data, or maybe there was an error, still we shouldn't unfurl.

### Additional Information

- Status desktop version: master (`cf5271cfea1cf95a3eb434d75e728fea1dc39061`)
- Operating System: Ubuntu 20

**Comment by caybro** [comment]
cc @alexjba does it ring a bell? probably result from the recent async LinksMessageView refactoring

**Comment by alexjba** [comment]
> cc @alexjba does it ring a bell? probably result from the recent async LinksMessageView refactoring

True, looks like a regression. I'll have a look
