### ISSUE TITLE
Activity center: Notification for the membership request is not shown in AC

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9656]
### Description

<img width="1380" alt="Screenshot 2023-02-27 at 19 43 16" src="https://user-images.githubusercontent.com/82375995/221627497-fdb78aab-6d14-4fbb-bcab-e618c5f9e3ab.png">

**Comment by MishkaRogachev** [comment]
<img width="571" alt="Screenshot 2023-03-01 at 16 20 10" src="https://user-images.githubusercontent.com/2522130/222137860-e1a95647-a61e-4b12-9020-5fce37c6a268.png">
Confirmed
