### ISSUE TITLE
Missing space between channels in StatusChatList

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9657]
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/11926403/221628715-de8f424f-d145-488c-b30e-2ffcf5fd6811.png)

As seen in the image, there is not space between the channels in the list

### Additional Information

- Status desktop version: master (`cf5271cfea1cf95a3eb434d75e728fea1dc39061`)
- Operating System: Ubuntu 22

**Comment by caybro** [comment]
```
4cefd4af2a (Lukáš Tinkl        2023-02-08 20:34:41 +0100)         spacing: 0
```

on purpose because of the (collapsed) category height; will fix (somehow :grin:)
