### ISSUE TITLE
[Community Permissions] Review create new/edit permission view dark mode design

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9668]
### Description
1. Review with design team if dark boxes should be like here:
![image](https://user-images.githubusercontent.com/97019400/221895798-4b913a95-3b43-460e-a2c7-4450785c2531.png)

2. Dropdown items should have the same color than background. Also review the items margin.
![image](https://user-images.githubusercontent.com/97019400/221896366-d8300533-b4c3-4173-993d-836cb47f71d0.png)

**Comment by micieslak** [comment]
I reviewed the communities-related design and current implementation and pointed several issues there:

1. Settings lists for community has no spacing therefore it's not consistent with the general settings:

![Screenshot from 2023-04-05 11-48-48](https://user-images.githubusercontent.com/20650004/230046277-98c4ca99-fe8d-4d7e-a585-ae12b079a554.png)
![Screenshot from 2023-04-05 11-49-08](https://user-images.githubusercontent.com/20650004/230046290-6a1f9112-da82-452b-9538-6b48a4ea41dd.png)

2.  The color of the rounded line starting from "Anyone" is not updated properly.

https://user-images.githubusercontent.com/20650004/230072905-a9f771e5-2c6a-4f20-a754-2adf9240f4cf.mp4
