### ISSUE TITLE
Creating a new community fails when logo and banner images are included

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9678]
Version: 0.9
OS: Windows 10

<ins>Steps to reproduce:</ins>

1. Navigate to Discover Communities

2. Click ‘Create New Community’

3. Under ‘Create new community’ click the ‘Create new’ button

4. Go through the create new community form, filling out **all** fields **including adding a community logo and community banner image**

5. At the end of the process, click the ‘Create Community’ button.

<ins>What currently incorrectly happens</ins>

6. The dialogue closes and nothing happens, the community is not created and doesn’t appear in the UI

<ins>What is supposed to happen</ins>

6. The dialog closes, the community is created, and its icon should appear in the primary nav.

<ins>Other information</ins>

This bug seems to be related to adding ‘Community logo’ and ‘Community banner’ images.  A new community is successfully created if the user **does not** upload a ‘Community logo’ and ‘Community banner’ image at the time they are creating the community.

Screencast demonstrating how creating a community fails when ‘Community logo’ and ‘Community banner’ images are included.

https://user-images.githubusercontent.com/124154641/222122302-b78af1be-51a5-4bd2-ab29-7661172f3419.mp4

&nbsp;

Screencast demonstrating how creating a community succeeds when ‘Community logo’ and ‘Community banner’ images are not added during initial community creation..

https://user-images.githubusercontent.com/124154641/222122479-49478e9b-ab70-4f46-8b5e-29e61d36b03a.mp4

&nbsp;

<ins>Other information</ins>

This issue is similar to issue #8427 but is more detailed so perhaps #8427 should be marked as a dupe of this issue?

**Comment by jrainville** [comment]
This works fine on master on Linux, but I know we've had issue with images on Windows. I'm updating my Qt version, then I'll test there too.

**Comment by jrainville** [comment]
I can confirm that the bug happens on Windows. It's a path issue as always
