### ISSUE TITLE
Incorrect label in Settings/Profile/avatar field FAB contextual menu

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9682]
Version: 0.9
OS: Windows 10

In Settings/Profile, when a user left clicks the profile avatar fields floating action button (FAB) a contextual menu is displayed. The copy in the menus first option label needs to be updated from “Upload a file” to “Select a different image”.

**Related issue**
See issue #9680 that should probably be worked on at the same time as working on this issue.

***

<ins>Steps to reproduce:</ins>

1. Navigate to Settings/Profile. 

2. Go to the profile avatar field and click on the FAB.

<ins>What currently incorrectly happens</ins>

3. The first option in the FAB contextual menu is incorrectly labelled ‘Upload a file’

<ins>What is supposed to happen</ins>

3. The first option in the FAB contextual menu should be labelled “Select a different image”.  The functionality remains the same.  

<ins>Other information</ins>

The FAB context menu copy needs to be updated in the ‘Create Community’, ‘Edit Community’, ‘Edit Profile’ and ‘Onboarding Create Profile’ screens.

![5 copy change within user profile](https://user-images.githubusercontent.com/124154641/222131489-44fdf8f0-dc6d-4a8c-9617-3712198b8f07.png)

**Comment by caybro** [comment]
@imagiMary just checking, where did you take that new text from? Any Figma design that I could find is showing "Upload a file" here

**Comment by imagiMary** [comment]
@caybro you are correct, the Figmas really should be updated. But sorry, no, the Figma hasn't been updated. I hope this is okay as it is just a copy change, and soon we will be moving to the new Status desktop redesign Figmas (these Figmas are nearing the end of their life).  

Copy should be "Select different image" (I just checked with @John-44 and have +1 from him)

**Comment by caybro** [comment]
Alright then, will change
