### ISSUE TITLE
Capitals don’t work in channel names

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9689]
Version: 0.9
OS: Windows 10

***

<ins>Steps to reproduce:</ins>

1. Navigate to a Community you are the Owner of

2. Click ‘Create channel or category’ 

3. Click ‘# Create channel’

4. Try typing a ‘Channel name’ that contains one or more capital letters.  

<ins>What currently incorrectly happens:</ins>

5. Only lowercase letters are shown, this is incorrect

<ins>What is supposed to happen:</ins>

5. Both uppercase and lowercase letters should be shown

<ins>Other information</ins>

https://user-images.githubusercontent.com/124154641/222142181-0fa10647-9d61-4e33-a5de-3eac8762297b.mp4

**Comment by mprakhov** [comment]
This looks as designed
Found such a line of code
`Utils.convertSpacesToDashesAndUpperToLowerCase(input.text)`
Need to clarify the designer expected behavior

**Comment by imagiMary** [comment]
@mprakhov have confirmed with design that both channel and category titles are supposed to contain both upper and lower case letters.  

The lack of capitals in the designs was just a coincidence :) Apologies from the design team!

**Comment by mprakhov** [comment]
@imagiMary what about spaces? Right now spaces for the channel names automatically replaced by '-'

**Comment by imagiMary** [comment]
@mprakhov the current '-' for spaces is correct :)

**Comment by mprakhov** [comment]
@imagiMary thank you for the help 👍
