### ISSUE TITLE
When the name, emoji, colour or description of a community channel that is inside a category is changed, the changes are not reflected until the app is restarted. After restart the edited channel has been moved outside of its category.

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9695]
Version: 0.9
OS: Windows 10

After the name, emoji, colour or description of a community channel *that is inside a category* is updated using the Edit Channel dialog:

- the changes are not reflected in the secondary nav (channel icon and name are not updated).

- if the Edit Channel dialog is re-opened, the previous changes are not shown (it shows the channel's original name, emoji, colour and description from before the edit was made).

- If a user then restarts Status Desktop, the changes that were made earlier are applied in the secondary navigation bar and saved in the Edit Channel dialog. 

- However at this point the channel has also been removed from the category it was in.
&nbsp;

**Desired behaviour:** When a user edits a channel, all changes are saved and immediately applied. The category the channel sits in should be unaffected.  

***

## Scenario 1

<ins>Steps to reproduce:</ins>

1. Navigate to a community that you are the owner of.

2. In the secondary navigation bar create a new channel inside a category _or_ go to a channel that is inside an existing category

3. Right click on the channel icon to open the Edit Channel dialog

4. In the Edit Channel dialog change the channel name, emoji, colour and description. Save changes.

<ins>What currently incorrectly happens:</ins>

5. The changes to the channel name/emoji/colour/description are immediately visible in the Channels main message body header and body area (which is correct), but the channel icon and name in the secondary navigation bar **does not** update (which is incorrect)..  

_Note:_ Not only are the changes made in step 4. not visible in the secondary nav bar but if the user subsequently re-opens the Edit Channel dialog, the changes made in step 4. appear to not have been saved. The information in the Edit Channel dialog has reverted back to the channel's original name, emoji, colour and description. 

<ins>What is supposed to happen:</ins>

5. The changes made to a channel using the Edit Channel dialog should be immediately visible in both the channel message body header and body area, as well as in the secondary navigation bar.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The information displayed in the Edit Channel dialog should reflect the user's changes.

&nbsp;
## Scenario 2 _(continuing from step 5. in the previous scenario)_

<ins>Steps to reproduce:</ins>

7. Force quit and relaunch Status Desktop

<ins>What currently incorrectly happens:</ins>

8. The channels that were edited in step 4 have been removed from the categories they were in (which is incorrect) but the changes to the channel name/emoji/colour/description made in step 4. are now applied. 

<ins>What is supposed to happen:</ins>

7. The changes made in step 4. should be immediately visible in both the channel message body header and body area, as well as in the secondary navigation bar. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Relaunching Status should not be necessary to make the above changes nor should it affect the categorisation of the &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;community channels.

<ins>Other information</ins>

This bug does not occur with uncategorised channel icons. The decategorisation of channels only happens once a user has tried to edit them. 

https://user-images.githubusercontent.com/124154641/222162759-11e15eee-81a7-43ed-8d09-1ce8d4b4ff38.mp4

**Comment by jrainville** [comment]
I just tested in master and this is fixed. We did a lot of fixes and refactors on that part of the code lately.
Closing as completed
