### ISSUE TITLE
Basic markdown text styling functionality broken in messaging

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9700]
Version: 0.9
OS: Windows 10

When a user writes a message they can only preview the ‘\_italics_’, ‘\*italics*’ and ‘\~~Strikethrough~~’ markdown styling in the message input field. Other combinations of markdown styling is not correctly previewed in the message input field and is not correctly rendered when the message is posted.   

**Related issue**
Although this issue is different, editing messages that contain markdown characters effects the rendering of said markdown characters. So the same issue seen here - #7804 - applies to the markdown mentioned below.     

***

<ins>Steps to reproduce:</ins>

1. Navigate to any messaging or communities screen that contains an active message input field.

2. In the message input field write a message that uses all of the markdown styling that should be supported in the message body area. 

*Note:* Status should aim to support the markdown syntax that Discord supports today.

As a first step in this direction, Status should support:

- Strikethrough \~~Strikethrough~~ **Status currently supports this** 
- Italics \*italics* or \_italics_ **Status currently supports this** 
- Underline italics \_\_\*underline italics*__
- Bold \*\*bold**
- Underline bold \_\_\**underline bold**__
- Bold Italics \*\*\*bold italics***
- Underline bold italics \_\_\*\*\*underline bold italics***__
- Underline \_\_underline__

<ins>What currently incorrectly happens:</ins>
 
3. The markdown syntax are:

a) not previewed correctly in the message input field (except for‘\_italics_’, ‘\*italics*’ and ‘\~~Strikethrough~~’). 

b) not rendered correctly when the message is posted (except for ‘\_italics_’, ‘\*italics*’ and ‘\~~Strikethrough~~’). Where the markdown syntax has not been rendered they are visible in the message posted in the message body area. 
 

<ins>What is supposed to happen:</ins>

3. All markdown styling should be previewed in the message input field. All previewed markdown styling should be rendered and visible in the message body area after the message is posted. 
None of the rendered markdown syntax should be visible in the message body area after the message is posted. 

<ins>Other information</ins>

![33 Basci markdown stext styling functionality broken in messaging](https://user-images.githubusercontent.com/124154641/222183463-ea6ae504-acb9-48ad-9b3c-d69f39c37311.png)

**Comment by iurimatias** [comment]
needs status input refactor, will be moved to next milestone

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
