### ISSUE TITLE
In Settings / Wallet, sub-headings “Imported” and “Watch-only” should not be displayed if the user doesn’t have any accounts of these types in their wallet.

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9704]
Version: 0.9
OS: Windows 10

***

<ins>Steps to reproduce:</ins>

Precondition: the user does not have any master keys (other than their default master key) or watch only accounts in their wallet.

1. Navigate to Settings / Wallet. 

<ins>What currently incorrectly happens:</ins>

2. In the middle of the Wallet body area under the “Accounts” header there are two sub-headings displayed; “Imported” and “Watch-Only”

<ins>What is supposed to happen:</ins>

2. In the middle of the Wallet body area under the “Accounts” header, no subheadings without items under them should be displayed.  Subheadings should only be displayed if there is one or more items under the subheading.

<ins>Other information</ins>

![36 Wallet Sub-headings](https://user-images.githubusercontent.com/124154641/222200185-ae5ebafa-2607-43ef-970a-f3fad4c91c89.png)

**Comment by John-44** [comment]
Let's wait for the updated Settings/Wallet designs before working on this one, as this issue might be superseded by the new designs

**Comment by alaibe** [comment]
took me 5min, done
