### ISSUE TITLE
draft/unposted messages are deleted from the message input field when a user navigates away from the messaging screen

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9709]
Version: 0.9
OS: Windows 10

**Related issue:** This issue is expanding on issue #9304 

When a user writes a message in the message input field and then navigates away from that screen, upon returning, the unposted message is no longer in the input field and has been lost. 

**Desired behaviour:** Anything that has been entered into the message input field should remain in that field until it is posted or for the duration of that session. So if a user starts writing a message, navigates somewhere else and later returns to where they were writing the message, the un-posted message should still be in the message input field. 

***

## Scenario 1 - message input box persistence in community channels

<ins>Steps to reproduce:</ins>

1. Navigate to any community channel screen that contains a message input field. 

2. Type a message into the message input field, but do not post the message 

3. Navigate away from that messaging screen to anywhere else in the app 

4. Return to the community channel you were in in step 2.  

<ins>What currently incorrectly happens:</ins>

5. The message copy written in the message input field in step 2. has disappeared

<ins>What is supposed to happen:</ins>

5. The message copy written in the message input field in step 2. should stay in the message input field until the user either posts the message, deletes the message, or exits the status app (current session ends)

<ins>Other information</ins>

https://user-images.githubusercontent.com/124154641/222219042-afb1f43f-c5dc-472a-9be3-4219558e93e5.mp4

&nbsp;

## Scenario 2 - message input box persistence in 1on1 and ad-hoc group chat threads

<ins>Steps to reproduce:</ins>

1. Navigate to a 1on1 or ad-hoc group chat message thread

2. Type a message into the message input field, but do not post the message 

3. Navigate away from this messaging screen to a different **1on1 or ad-hoc group chat thread**.

4. Return to the messaging thread that you were in in step 2.

<ins>What currently incorrectly happens:</ins>

5.  The message copy written in the message input field in step 2. has disappeared.

<ins>What is supposed to happen:</ins>
 
5. The message copy written in the message input field in step 2. should stay in the message input field until the user either posts the message, deletes the message, or exits the status app (current session ends)

<ins>Other information</ins>

If in step 3. if a user navigates to anywhere else in the app **other than to a different 1on1 or ad-hoc message**, when the user returns to the original message thread, the message copy  correctly remains persisted in the message input field.

&nbsp;

https://user-images.githubusercontent.com/124154641/222218270-2d5a8b0b-788c-4cb3-9ca6-0e63fbe6c9a4.mp4

**Comment by jrainville** [comment]
Related to https://github.com/status-im/status-desktop/issues/9235
@mprakhov I think the keeping active of channels is completely broken, so if you fix this issue above, then you can make it that we only keep 5 at a time.

**Comment by mprakhov** [comment]
Regression. I have been fixed it before 😢

**Comment by jrainville** [comment]
It's possible that it's still fixed. This issue was tested on 0.9

**Comment by mprakhov** [comment]
0.10.0 rc.13 the problem exists
The latest main - text is resetting during switching between the sections, but switching between the chat's/channels in one section does not drop the text.

Need expectation clarification:
Text resetting after switching between sections is expected behavior or a bug?
cc: @imagiMary , @jrainville

**Comment by jrainville** [comment]
The best would be that whatever the community, we keep the last 5 channels in memory (so we keep chat scroll, text input, etc).
However, if you find that for that we need to keep the whole section (community) in memory and it's too heavy, then we can change it to only keep 5 channels in memory in the current section as per https://github.com/status-im/status-desktop/issues/9235.
The 5 should be configurable easily too.

**Comment by mprakhov** [comment]
found the breaking commit for scenario 2: `f5d6c538c2918faecb3affd6a1b264f4efe7f795`
Looking for a potential fix (there was a huge refactoring)

**Comment by caybro** [comment]
> @caybro could you lend a hand to @mprakhov . He's a bit stuck on figuring out why when commenting out unloading the Loaders, there is a weird behaviour where the wrong chat section appears or not everything changes. Maybe you guys could pair on this?

There's 2 things in AppMain.qml if I remember correctly;
- around line 870:

```qml
delegate: Loader {
  readonly property string sectionId: model.id
  active: sectionId === appMain.rootStore.mainModuleInst.activeSection.id
  ...
```

- which has to match the "active section id" further up in the stack layout (around line 690):
```qml
                    currentIndex: {
                        const activeSectionType = appMain.rootStore.mainModuleInst.activeSection.sectionType

                        if (activeSectionType === Constants.appSection.chat)
                            return Constants.appViewStackIndex.chat
                        if (activeSectionType === Constants.appSection.community) {
                            for (let i = this.children.length - 1; i >=0; i--) {
                                var obj = this.children[i]
                                if (obj && obj.sectionId && obj.sectionId === appMain.rootStore.mainModuleInst.activeSection.id) {
                                    return i
                                }
                            }
```

@mprakhov does that help?

**Comment by mprakhov** [comment]
@caybro Not much.
For the fix - we need to disable unloading the ChatLayout from the loader when we switch between the sections. For this purposes, we remove changing `active` for Chat section and for Community section... and here is where the magic comes:
If you'll start switching between Chat or community sections - ChatLayout does not update its content, while StackLayout index is changing


But appeared another issue

**Comment by caybro** [comment]
> @caybro Not much.
> For the fix - we need to disable unloading the ChatLayout from the loader when we switch between the sections. For this purposes, we remove changing `active` for Chat section and for Community section... and here is where the magic comes:
> If you'll start switching between Chat or community sections - ChatLayout does not update its content, while StackLayout index is changing
> 

Then you have to activate it manually, not via the binding. Look at the git history how it used to be done before

**Comment by mprakhov** [comment]
@caybro I did it. 
Let me show you a small example:
For minimizing the test, commented chat section + I have 3 communities with different channel names and members. Community is created and not unloading on an application startup... look at switching between the section - title, and members count is changing, all other - no. So stack layout is switching but the content is showing from the previous community section. That's the main problem I have not solved.

https://user-images.githubusercontent.com/117639195/224801853-3c9290da-a759-483b-a34c-27a0063e3f0e.mov

**Comment by caybro** [comment]
@mprakhov you have to make sure this part gets re-executed everytime the section becomes active:

```qml
Component.onCompleted: {
  // we cannot return QVariant if we pass another parameter in a function call
  // that's why we're using it this way                                          
  appMain.rootStore.mainModuleInst.prepareCommunitySectionModuleForCommunityId(model.id)
                                            rootStore.chatCommunitySectionModule = 
  appMain.rootStore.mainModuleInst.getCommunitySectionModule()
}
```

**Comment by anastasiyaig** [comment]
@John-44 could u please clarify how many chats/channels we want to 'remember' having these drafts? Unlimited? For some reason there is number 5 in my head, but please confirm :)

**Comment by anastasiyaig** [comment]
@mprakhov thanks for confirming! this task (current one) i am aiming to test today :)

**Comment by John-44** [comment]
> @anastasiyaig Five. I have a task for this #9235 But I need to be sure, that this change is ok before moving to do a limitation

We *might* want to raise this number in the future, say to 10, but five is a good for now, because getting our performance issues solved is one of our top priorities

**Comment by anastasiyaig** [comment]
thank you for immediate response @John-44 , appreciate that

**Comment by imagiMary** [comment]
Hi @mprakhov, it looks like there has been a regression on draft messages being deleted when a user switches between 1on1 chats only. 

Version: 0.12.0-rc.1
OS: Windows 10 / Ubuntu 22.10


https://github.com/status-im/status-desktop/assets/124154641/e27965df-b1f1-4432-a95b-774d5590255d

LOG: doesn't show in the log

**Comment by mprakhov** [comment]
@imagiMary We keep 5 chats in memory only, so I think it was dropped because you opened 5 channels/chats
P.S. But need to check :)

**Comment by jrainville** [comment]
> @imagiMary We keep 5 chats in memory only, so I think it was dropped because you opened 5 channels/chats P.S. But need to check :)

I thought about that too, but in the video, we can see that she goes back to the last chat directly

**Comment by imagiMary** [comment]
> > @imagiMary We keep 5 chats in memory only, so I think it was dropped because you opened 5 channels/chats P.S. But need to check :)
> 
> I thought about that too, but in the video, we can see that she goes back to the last chat directly

Correct, I am only switching between three chats in the screencast, where two of the chats are 1on1 chats and the other is an ad-hoc group chat. As shown in the screencast, when doing this the draft message is lost.  

The specific scenario is when switching from a 1on1 chat to an ad-hoc group chat and then back to the 1on1 chat, the draft 1on1 chat message is lost. :)

**Comment by iurimatias** [comment]
so while this is not ideal it's not high priority vs others things and it shouldn't be in 0.13 and will be moved to 0.14

**Comment by jrainville** [comment]
I re-tested on 0.13.0 and I can no longer reproduce. I thin Igor's change fixed it.

Feel free to reopen if it happens again
