### ISSUE TITLE
Communities portal: use proper section names

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#9728]
In the Desktop UI there are "Popular Communities" and "Featured communities". "Popular communities" are simply all communities included in the community directory. 'Popular Communities' should be renamed to 'All Communities' to avoid confusion.

**Comment by osmaczko** [comment]
1) Popular
![popular](https://user-images.githubusercontent.com/33099791/222711403-199a3dba-f1dc-4744-ba52-89f38ed55579.png)

2) All
![all](https://user-images.githubusercontent.com/33099791/222711406-e418ccd0-45f9-41e3-94ae-3f23370db96b.png)

3) Spacer
![spacer](https://user-images.githubusercontent.com/33099791/222711400-6db3c3ee-a374-4de8-a3b9-42a32f772c8c.png)

@John-44 @benjthayer which option to choose?

**Comment by John-44** [comment]
@osmaczko thanks for opening this issue, I think "Featured" and "All" works best :-)
