### ISSUE TITLE
My sent messages are not synced across two Status instances

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#9729]
# Bug Report

## Description

My sent messages are not synced on a second opened app.
## Steps to reproduce
1. Open two clients 
2. Login with the same account on both
3. Send a message from either one

https://user-images.githubusercontent.com/47811206/222527828-9ae5f3b0-0bdd-4974-8d6c-d9ded35e5903.mov

#### Expected behavior
The sent message is synced on the other client
#### Actual behavior
The sent message is not synced on the other client
### Additional Information

- Status desktop version: 0.9
- Operating System: MacOs

**Comment by alexjba** [comment]
> @alexjba In general, you need to pair instances. Did you do that?
> 
> In short, if you just run to instances which is not synchronized - you can't receive any message. And if you did it, its may be an old issue :) Cos now it works.
> 
> 
> CC: @jrainville

Thank you @borismelnik! And sorry about the false alarm. I had no idea the instances needs to be paired.

**Comment by borismelnik** [comment]
as most of users I guess :D me either, actually.

**Comment by borismelnik** [comment]
I think its a good idea to raise some notification in AC about connecting new devices and ask user to sync it or not

**Comment by jrainville** [comment]
> In general, you need to pair instances. Did you do that?
>
> In short, if you just run to instances which is not synchronized - you can't receive any message. And if you did it, its may be an old issue :) Cos now it works.

Wait even I didn't know that. That's weird. I wonder if that's intentional cc @cammellos @John-44

**Comment by cammellos** [comment]
Depends on what we mean,
if you have 2 unpaired instances, you will not receive messages from the other instance, that's expected.
But you should receive messages from other peers, that's for sure (we are pretty sure that works as expected, otherwise there's some bug somewhere or a misconfiguration)

**Comment by jrainville** [comment]
> But you should receive messages from other peers, that's for sure (we are pretty sure that works as expected, otherwise there's some bug somewhere or a misconfiguration)

Yeah that works. So all good.

> if you have 2 unpaired instances, you will not receive messages from the other instance, that's expected.

I didn't know about that. Why is that the case if you can explain real quic?

**Comment by cammellos** [comment]
> > But you should receive messages from other peers, that's for sure (we are pretty sure that works as expected, otherwise there's some bug somewhere or a misconfiguration)
> 
> Yeah that works. So all good.
> 
> > if you have 2 unpaired instances, you will not receive messages from the other instance, that's expected.
> 
> I didn't know about that. Why is that the case if you can explain real quick?

it's to preserver PFS, otherwise someone would be able to recover your account and get access to all the historical data, also we want to prevent "ghost" devices, i.e someone recovers your key, and just listen passively to your messages without you noticing.

**Comment by jrainville** [comment]
Thanks for the explanation. Maybe we need to document that for the users somewhere, but the issue here is a non-issue then.
