### ISSUE TITLE
Chat: suggestions list displayed when mentioning, still searches by alias

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9738]
### Description

<img width="436" alt="Screenshot 2023-03-03 at 15 49 40" src="https://user-images.githubusercontent.com/82375995/222728393-f1bd96e3-bb52-4def-866e-35dcee34146d.png">

1. in community for dogfooding, open a channel, lets say `ask-finance`
2. enter `@rus` as search criteria

As result. it seeks through ["nickname", "ensName", "name", "alias"], seems alias is a three word name

This makes the suggestion list being looked awkward

**Comment by anastasiyaig** [comment]
@osmaczko @jrainville please take a look

**Comment by caybro** [comment]
I recently worked on this; easy to remove

**Comment by jrainville** [comment]
IMO, having the search on   ["nickname", "ensName", "name"] makes sense. I think it's only the 3 word name that makes it weird, because the user never sees that. Make sure we still support searching for mobile names that still use the 3 word name as display name however (it should be automatic, but better safe than sorry)

**Comment by caybro** [comment]
I agree but at the same time I can see why this is confusing, typing something that is not then directly visible in the suggestions popup

**Comment by anastasiyaig** [comment]
> I agree but at the same time I can see why this is confusing, typing something that is not then directly visible in the suggestions popup

this is the main driver to log the issue initially , for user the list of suggestions is just wrong (looks like that)

**Comment by caybro** [comment]
I think about something; imho we should search by the (3 word) "name" only if there's nothing else available

**Comment by jrainville** [comment]
> I'll think about something; imho we should search by the (3 word) "name" only if there's nothing else available

Yup, that is what I meant here
> Make sure we still support searching for mobile names that still use the 3 word name as display name however (it should be automatic, but better safe than sorry)

> I agree but at the same time I can see why this is confusing, typing something that is not then directly visible in the suggestions popup
