### ISSUE TITLE
Compile and analyse the performance of native M1 builds

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#9741]
### Description

Compile and analyse the performance of native arm64 build.

**Comment by alexjba** [comment]
The app is building fine on M1, but is freezing on status-go calls after Qt starts the main loop.
We have the same issue reported here: https://github.com/golang/go/issues/48437

It cannot be reproduced on a dummy c++ app that links with status-go.
It cannot be reproduced when calling status-go from another thread in Status app.

**Comment by alexjba** [comment]
Looks like this bug is related to how Qt handled SVG images. The app works if I'm not using SVG images.

**Comment by caybro** [comment]
> Looks like this bug is related to how Qt handled SVG images. The app works if I'm not using SVG images.

wow
