### ISSUE TITLE
When a user collapses a community category, the channel names disappear but the category title does not move

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9742]
Version: 0.10
OS: Windows 10

See screencast of issue, steps to reproduce the issue described below. 
&nbsp;

https://user-images.githubusercontent.com/124154641/222782412-82aa19a4-dafb-4df4-8331-8181ab2f8045.mp4

***

<ins>Steps to reproduce:</ins>
1. Navigate to a community that contains multiple channels within several categories e.g. Status CCs Community (the internal dogfooding community).

2. Click on all the categories expand and collapse chevron to collapse the channels within the various categories.  

<ins>What currently incorrectly happens:</ins>
 
3. When a user collapses a category the channel names disappear. However, the category titles do not move and therefore they are no longer correctly vertically padded. There is now excess padding between the collapsed category titles  

<ins>What is supposed to happen:</ins>

3. The collapsed category titles should be vertically padded so they are next to each other with the correct amount of padding between category titles.  

Continuing on… 

<ins>Steps to reproduce:</ins>
4. Navigate away from the community screen and then return to it.

<ins>What currently incorrectly happens:</ins>
 
5. Although the padding between the collapsed category titles is reduced the collapse category titles are not all consistently placed, with varying excess padding between category titles. 

<ins>What is supposed to happen:</ins>

5. The collapsed category titles should all be vertically organised next to each other and consistently placed, with the correct amount of padding. 

<ins>Other information</ins>
If a user repeats the scenario above with a community they are the owner of, the same bug occurs up until step 4. But when the user returns to the their community, the channel titles are *correctly* vertically padded.

**Comment by caybro** [comment]
It's definitely more than a few lines; I'd postpone it for 0.10

**Comment by caybro** [comment]
Just for the record, this is fixed already in master

**Comment by jrainville** [comment]
Gonna close since it's fixed in master
