### ISSUE TITLE
Authentication modal stuck after 2 fails attempt

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#9747]
# Bug Report
Authentication modal, don't allow me to do anything after I fails 2 times at entering the password

![image](https://user-images.githubusercontent.com/491074/223101494-3bf66dc9-9022-4a1f-bd74-e4f873b19ed7.png)

**Comment by saledjenic** [comment]
@alaibe I've noticed that, it's fixed in this PR https://github.com/status-im/status-desktop/pull/9820
