### ISSUE TITLE
Merge curatedCommunities into communities in the community service

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9752]
### Description

Additional step to https://github.com/status-im/status-desktop/issues/9570

We merged `allCommunities` and `joinedCommunities` into `communities`, now we can probably remove `curatedCommuntiies` as well and merge into `communities`. It seems like the only thing missing is the `available` prop and another flag to say `isCuratedCommunty`, since only some of the communities we know are considered curated.

**Comment by jrainville** [comment]
I just thought, @osmaczko do you think the `curatedCommunities` object will change a lot with your changes? Right now, it's basically the same as a normal community with the added `available` prop, so it makes sense to merge them, but if you think it will have a lot more props, it's probably worth it to not refactor

**Comment by caybro** [comment]
Why not simply inherit the `curatedCommunities` model from the base `communities` model to add the extra stuff?

**Comment by osmaczko** [comment]
> I just thought, @osmaczko do you think the `curatedCommunities` object will change a lot with your changes? Right now, it's basically the same as a normal community with the added `available` prop, so it makes sense to merge them, but if you think it will have a lot more props, it's probably worth it to not refactor

`curatedCommunities` is just a list of public keys we retrieve from a contract, the rest of the data we fetch from waku network. It means the curated community is represented the same as other communities, that is: `CommunityDto`.

> It seems like the only thing missing is the `available` prop and another flag to say `isCuratedCommunty`, since only some of the communities we know are considered curated.

Yes, exactly. We will also need `isCuratedFeaturedCommunity` in the future but that can be added later.

**Comment by anastasiyaig** [comment]
@jrainville added milestone 0.11.0 for this nice change, if that is correct

**Comment by jrainville** [comment]
Ah yes, my bad I forgot
