### ISSUE TITLE
Saved addresses list issues

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#9762]
## Description

- Add address modal is closed on click outside, which is not convenient https://github.com/status-im/status-desktop/issues/9773
- New saved address must appear on top of the list https://github.com/status-im/status-desktop/issues/9772
- Open on Etherscan always opens the etherscan , no matter for which network i added the address (should chain be considered?) https://github.com/status-im/status-desktop/issues/9771
- Placeholder picture is missing when no addresses were added https://github.com/status-im/status-desktop/issues/9770
- rename `Address owner` https://github.com/status-im/status-desktop/issues/9769
- investigate the Star functionality for Saved addresses: https://github.com/status-im/status-desktop/issues/9774

**Comment by anastasiyaig** [comment]
@IvanBelyakoff i will close this issue (because i opened separate tickets for each point)
