### ISSUE TITLE
[Community Mint Collectibles] Total supply number in `Create New Token` form is not localized

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9763]
### Steps to reproduce
1. Settings / Advanced / Switch Community Tokens
2. In an own community / Settings / Mint Token / Create new  token
3. Uncheck `unlimited supply` option and add value (see localized input is not accepted)
4. Press `Preview` and see supply value displayed is not localized

Total supply number seem to be not localized:
> ![Screenshot from 2023-03-07 11-06-08](https://user-images.githubusercontent.com/20650004/223391253-5eb1ad24-61a9-4535-8cad-2ac335cb569e.png)
> 
> Also localized input is not accepted:
> 
> ![Screenshot from 2023-03-07 11-11-25](https://user-images.githubusercontent.com/20650004/223391623-c4ec0220-7076-4a0d-b57f-3dadddb6b521.png)

**Comment by caybro** [comment]
It is localized, the problem is that the input doesn't accept the localized form

**Comment by caybro** [comment]
You have to use `Number.fromLocaleString()` to read it; or adjust/fix the validator (if any)
