### ISSUE TITLE
Activity Center -> Can't decline / accept the request to community from activity center

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9767]
### Description

```
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:309: TypeError: Cannot call method 'declineRequestToJoinCommunity' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:309, )
```

```
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:305: TypeError: Cannot call method 'acceptRequestToJoinCommunity' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:305, )
```

<img width="569" alt="Screenshot 2023-03-07 at 14 51 51" src="https://user-images.githubusercontent.com/82375995/223414641-4fd00513-2d5b-4c5f-9bc9-295aa94db80d.png">

**Comment by caybro** [comment]
CC @MishkaRogachev

**Comment by MishkaRogachev** [comment]
@anastasiyaig just checked latest master and it seems to be fixed
<img width="571" alt="Screenshot 2023-03-13 at 12 28 05" src="https://user-images.githubusercontent.com/2522130/224629552-d5181c5c-9436-4033-a920-11dd88a5a414.png">

**Comment by anastasiyaig** [comment]
ya it works to me in master too, thanks for checking @MishkaRogachev :)
