### ISSUE TITLE
Wallet -> Saved addresses: add placeholder for empty state

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9770]
### Description

We are missing the picture itself as well, it needs to be added and implemented

![image](https://user-images.githubusercontent.com/82375995/223428886-f57e8089-bca9-4f1c-9cae-d0d43d9d6d16.png)

**Comment by anastasiyaig** [comment]
@benjthayer i need your help over here

**Comment by benjthayer** [comment]
Thanks @IvanBelyakoff! I'll discuss this with John - feels like we need a generalised empty state for a number of places - will get back you :)

**Comment by John-44** [comment]
@benjthayer we probably have new designs for this now.  Do you want to post here, or close this issue and tackle this as part of the saved addresses update?

**Comment by benjthayer** [comment]
> @benjthayer we probably have new designs for this now. Do you want to post here, or close this issue and tackle this as part of the saved addresses update?

I think we could probably close this and I can setup a new issue for the saved address work that encompasses this requirement.

**Comment by alaibe** [comment]
closing
