### ISSUE TITLE
Settings -> Messaging: having unread count badge for Messaging section does not display the same unread badge for settings

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9779]
### Description

1. open app
2. send someone your chatkey to receive a contact request for example
3. receive the request (should come to AC)
4. do not accept it
5. check settings gear icon
6. open settings -> messaging

As result, messaging section has unread badge which is not visible until u specifically open settings

https://user-images.githubusercontent.com/82375995/223445762-2fd41638-4dd9-4a22-91aa-784d5fc184d6.mov

**Comment by anastasiyaig** [comment]
@benjthayer @alexandraB99 what do u think guys? I feel like it is incorrect, but it might be by design. Please check this out

**Comment by caybro** [comment]
It looks like the message of type "contact request" triggers the notification badge

**Comment by benjthayer** [comment]
Thanks @anastasiyaig I'd say it would make sense to have a blue notification dot for the settings icon in this instance. Despite the fact you can action the request from the AC, it feels odd to have notification badges inside the Settings area but not flag their presence at the parent nav item (the settings cog). 

What do you think @John-44 ?

**Comment by alexandraB99** [comment]
@benjthayer could you please confirm whether we should move on as suggested?

**Comment by John-44** [comment]
> Thanks @anastasiyaig I'd say it would make sense to have a blue notification dot for the settings icon in this instance. Despite the fact you can action the request from the AC, it feels odd to have notification badges inside the Settings area but not flag their presence at the parent nav item (the settings cog).
> 
> What do you think @John-44 ?

@benjthayer yes I agree, what you've said above is correct (there should be a small blue dot on the cog in this instance)
