### ISSUE TITLE
Update incoming Contact request copy in Activity Centre 

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9788]
Version: 0.10
OS: Windows 10

***

In the Activity Centre, under an incoming contact request, the grey copy that currently says “_Sent contact request:_” (incorrect) should instead say "_Contact request:_" (correct). 

&nbsp;
![03 17 Activity centre copy update](https://user-images.githubusercontent.com/124154641/223505553-c5075de8-8c91-42ff-96d1-c9221001f432.png)

<ins>Other information</ins>

See figma design posted below.  

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1267%3A320353&t=ciJBetR6GhnOu3Gc-0 

![03 17 Activity centre copy Figma](https://user-images.githubusercontent.com/124154641/223505416-f7f7ea89-2365-4575-84d7-d1c38b76b538.png)

The grey text copy for *outgoing* contact requests in the activity centre should stay the same as it is today (e.g. “Sent contact request” if fine for outgoing contact requests, it’s just the wrong copy of incoming contact requests)

**Comment by MishkaRogachev** [comment]
@imagiMary thanks for bug! Just one question: there are two notifications, for incoming and for outgoing contact requests. My proposition is to change "Sent contact request:" to "Contact request sent to @username" and remove CR text for outgoing notification

<img width="686" alt="Screenshot 2023-03-14 at 12 41 02" src="https://user-images.githubusercontent.com/2522130/224923051-6965e9cd-765f-47a6-b498-e76366985ac2.png">

<img width="689" alt="Screenshot 2023-03-14 at 12 41 17" src="https://user-images.githubusercontent.com/2522130/224923091-a731018e-d5e7-4336-b80b-84ee0e7f120a.png">

**Comment by MishkaRogachev** [comment]
UPD: incoming CR are broken because of wrong state on backend, [fixing](https://github.com/status-im/status-desktop/issues/9505) here

**Comment by imagiMary** [comment]
Hi @MishkaRogachev, does the the design shown below match what you are proposing?

![#9871 Figma](https://user-images.githubusercontent.com/124154641/225049055-c85253cc-b8bb-4591-ba20-6feb4d57aa87.png)

**Comment by MishkaRogachev** [comment]
> Hi @MishkaRogachev, does the design shown below match what you are proposing?
> 
> ![#9871 Figma](https://user-images.githubusercontent.com/124154641/225049055-c85253cc-b8bb-4591-ba20-6feb4d57aa87.png)

Yes, i'm planning to fix implementation it soon
