### ISSUE TITLE
Set min window width of 1200px - this is a quick fix as many layouts break if they are smaller

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9789]
Version: 0.10
OS: Windows 10

***

Many screen layouts break when Status Desktop’s window width is less than 1200px. A quick fix solution to this issue (for the MVP release) is to set the minimum window width to 1200px. 

The desktop app redesign will make Status Desktop fully responsive, so this will be a non-issue in the future.

Once this change is applied, there will still be a few screens in Status desktop that don’t work correctly at a 1200px minimum width.  These bugs will be raised in separate github issues.

**Comment by caybro** [comment]
Can we discuss this @alexandraB99 tomorrow?
