### ISSUE TITLE
The Status taskbar button and the Status window title bar are missing the Status icon in OS Windows 10 (new regression in 0.10)

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9791]
Version: 0.10
OS: Windows 10

***
<ins>Steps to reproduce:</ins>

1. Launch the Status app in Windows 10 

<ins>What currently incorrectly happens:</ins>
 
2. The Status taskbar button and the Status window title bar are missing the Status icon. 

<ins>What is supposed to happen:</ins>

2. The Status taskbar button and the Status window title bar should contain the Status icon. 

<ins>Other information</ins>

The Status taskbar icon was present on Windows in the 0.9 release, this issue is a new 0.10 regression. 
 
![03 04 screenshot Taskbar](https://user-images.githubusercontent.com/124154641/223513196-f651a897-5b3e-493d-b579-ff09bdc9f2d4.png)

**Comment by caybro** [comment]
I doubt we've ever had those custom window decoration buttons (like we do on macOS); the missing window icon is definitely a regression though

**Comment by imagiMary** [comment]
Morning @caybro, yes we definitely did :D Here are some screen shots I just took from 0.09 on Windows 10 :) 

![03 04 V0 09 Taskbar button](https://user-images.githubusercontent.com/124154641/223695503-a117b100-87db-45d0-b927-e0aac9e5b8ce.png)

![03 04 V0 09 Window icon](https://user-images.githubusercontent.com/124154641/223695565-8f839104-163c-4db1-b62d-440deab74a54.png)
