### ISSUE TITLE
Communities: Invite text is not sent in the 1-1 chat

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#9812]
# Bug Report

## Description

When adding members to communities the text that the owner includes in the invite does not appear in the 1-1 chat message that is created. The text has been seen to appear in the in-app toast message only.

## Steps to reproduce

Create a community and invite another user with some invite text included. The invite text will not be delivered to the user.

#### Expected behavior

The text that is included during the creation of the community invite should be delivered to the user.

#### Actual behavior

The text that is included during the creation of the community invite is not delivered to the user in 1-1 chat. 

### Additional Information

- Status desktop version: Master/0.10
- Operating System: Mac

**Comment by MishkaRogachev** [comment]
<img width="1067" alt="Screenshot 2023-03-13 at 12 24 17" src="https://user-images.githubusercontent.com/2522130/224628729-fdaf769b-c305-4ec1-b025-feb6f8b685b5.png">
works in 0.10, but fresh master does not show same message
