### ISSUE TITLE
Investigate OpenSea publishing for our Minting process

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9824]
Mish mash of questions and discussions we've had in a group chat:

- Initial message from John:
  - Hyia jonathan-new Iuri , I was just having a conversation with anthony and MichalC (MichalC had a couple of questions about fetching assets for the token permissions setup screen), and one question came up that I didn't know the answer to, so wanted to ask if anybody else knows the answer.
The question is: when a community owner mints a collectable, how is all the metadata related to the collectable (Name, Description, Image, etc...) fetched by other Status users who have that token airdropped into their wallet?  A token minted by a community owner will in many cases be airdropped into the wallets of Status users who are not yet members of that community, and we need these tokens to be correctly displayed.
I was wondering how is this functionality currently being implemented?  I can think of one way it could be implemented, and anthony suggested another totally different implementation option that might be better than what I had in mind, but I wanted to ask what the folks currently working on building this functionality have implemented (or are planning to do)?

- Open Sea idea:
  - jonathan-new Michal Pascal when I was speaking with anthony earlier today, he had a completly different suggestion that in hindsight seems completly obvious and could (if it works) be a massive simplification, better for scaling and a reliability improvement as well.
  The idea is as follows:
     - When a new Collectable is minted, it is published to OpenSea.   OpenSea might (???) watch the blockchain and automatically publish NFTs when they are detected.  However we would need to ensure the Collectable image is somehow uploaded to OpenSea as well.  There might be a delay between an NFT being published to OpenSea and its metadata inc. image being retrievable via the OpenSea API, if this is the case this delay can be handled in the UI/
OpenSea does support Ethereum Mainnet, Optimism and Arbitrum, so we are all good in terms of OpenSea blockchain support.
    - No need to worry about peridocially publishing to waku, no need to worry about waku scaling, no need to worry about waku reliability, no need to add additional code to the wallet to do something else in addition to the already supported usage of OpenSea.
WDYT?  Worth of investigation?  I'm a bit embarrassed about not thinking about this idea before, if this works it could be a much simplier way of doing things

- Some questions by Michal:
  - OpenSea solution sounds reasonable. I understand that we can deploy the contract in the way we are doing this now and then just register this contract in OpenSea, am I correct ? Or the deployment will be done completely via OpenSea ?
Our NFT has got an empty tokenUri, because we publish metadata to waku. Probably we will have to do this according to OpenSea standards: create metadata file and fill uri correctly.
Regarding delays.. If we keep our current way of deployment (can we ?) and additionally register NFT in OpenSea, then this is not a problem. The wallet can display a default icon and then reload it when notified from OpenSea.

- Other questions by Anthony:
  - Sorry catching up here... before making big plan indeed, we need to understand opensea aggregator. Are they listening on chain event, in that case it would be immediate, are they running the aggregator daily, that would mean a delay. So it depends on this. Here we are only talking about erc721, not erc20. As those tokens are not in opensea but they are more "standard"

Find anything you can about it and report here so we know if it's a good solution for our problems.

**Comment by dlipicar** [comment]
OpenSea recommends using the OpenZeppelin implementation (https://docs.opensea.io/docs/getting-started).
```To be listed on OpenSea, it's best if your items adhere to the latest [Open Zeppelin](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/token/ERC721) implementation of ERC721.
```

After deploying the contract and minting the collectibles, you apparently don't need to register them in OpenSea for them to be listed there. There's no mention of any sort of delay, you should be able to immediately access it using link `https://<net>.opensea.io/assets/<asset_contract_address>/<token_id>`

If one adheres to the ERC721Metadata standard (https://docs.opensea.io/docs/2-adding-metadata) and provides metadata following their structure (https://docs.opensea.io/docs/metadata-standards), everything will be picked up automatically. If the `tokenURI` method is not implemented, you can contact the help center and give them any link with format `<your-api.com/any_path>/{token_id}` that returns the metadata in the mentioned format, but they will have to process that manually so there's a delay.

They apparently store a local cache of the metadata, and they update it under a couple conditions
```
To refresh token metadata on OpenSea, you can emit on-chain events as defined in [EIP-4906](https://eips.ethereum.org/EIPS/eip-4906):

event MetadataUpdate(uint256 _tokenId);
event BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId);

To refresh a whole collection, emit _toTokenId with type(uint256).max

For ERC1155, metadata updates are supported via the [specification](https://eips.ethereum.org/EIPS/eip-1155#specification) for the event URI:

event URI(string _value, uint256 indexed _id);

Alternatively, you can hit the OpenSea API with the force_update param:

https://api.opensea.io/api/v1/asset/<your_contract_address>/<token_id>/?force_update=true
```

**Comment by jrainville** [comment]
Ok cool. We already use OpenZeppelin implementations iirc cc @endulab @0x-r4bbit

**Comment by endulab** [comment]
Yes @jrainville , we have OpenZeppelin impl. 

When we deploy a contract , OpenSea will know about it, so does our wallet. This is a good information.

Regarding contract metadata, the problem that we have is **storage**. Right now we keep it in waku and OpenSea does not understand waku. OpenSea requires something like this: "image": "https://storage.googleapis.com/opensea-prod.appspot.com/creature/50.png". @dlipicar does OpenSea offer some storage so we can place our metadata json and assets there ?

**Comment by dlipicar** [comment]
@endulab hmm I think they will store your image if you do the minting through their website, but I don't think they have some sort of image storage service you can freely use. Any chance we can use IPFS? [They support that](https://docs.opensea.io/docs/metadata-standards).

```
IPFS and Arweave URIs
OpenSea supports the storage of NFT metadata in decentralized file networks, so that they can’t be modified by a central party.

If you use [IPFS](https://ipfs.io/) to host your metadata, your URL should be in the format ipfs://<hash>. For example, ipfs://QmTy8w65yBXgyfG2ZBg5TrfB2hPjrDQH3RCQFJGkARStJb. If you plan to store on IPFS, we recommend [Pinata](https://pinata.cloud/) for easily storing data. Here's a tutorial by Chainlink for getting started: https://blog.chain.link/build-deploy-and-sell-your-own-dynamic-nft/.

[Arweave](https://www.arweave.org/)'s equivalent is ar://<hash>. For example, ar://jK9sR4OrYvODj7PD3czIAyNJalub0-vdV_JAg1NqQ-o.
```

**Comment by jrainville** [comment]
Closing as completed as the investigation is done
