### ISSUE TITLE
Chat input is no longer growing when input value gets longer

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#9831]
It used to be like this when entering text into the chat input that is multi line, the input would grow until a certain point.
As of 0.10 this is no longer the case

![Screenshot from 2023-03-10 11-12-00](https://user-images.githubusercontent.com/445106/224289110-c779c403-3d91-422b-ab3a-9a75bd4cb7d4.png)

**Comment by caybro** [comment]
Fixed in master already

**Comment by 0x-r4bbit** [comment]
@caybro Nice! Can you link the commit here and close this?

**Comment by caybro** [comment]
I _think_ it's this commit: bb23131f0e578d17f74e72ac3c63e8293afdfc26 

@alexandraB99 ?

**Comment by iurimatias** [comment]
this has been fixed
