### ISSUE TITLE
checkConnected API doesnt return correct values

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#9833]
### Description
the checkConnected api on go side doesnt return correct values each time

1. Market values never shows down even though internet is down
2. After turning internet on/off the values in the next tick and re till not updating correct values for the various sites

**Comment by alaibe** [comment]
1. Market values never shows down even though internet is down

I think it might be because infura is down, we never request the market values as we know we have problem

I will check that

**Comment by Khushboo-dev-cpp** [comment]
> 1. Market values never shows down even though internet is down
> 
> I think it might be because infura is down, we never request the market values as we know we have problem
> 
> I will check that
> 
> 2. u mean this still shows off values?

Yes so after internet is turned back on, I retry getting wallet tokens but still the networks show down, but I am guessing maybe that cause those networks are actually down? not sure, can we check once?

**Comment by Khushboo-dev-cpp** [comment]
I also tried turning off connection to the sites locally and data is not loading but the checkConnected api is not returning the correct values on startup

**Comment by Khushboo-dev-cpp** [comment]
Can we emit a event each time there is a change in state of these sites instead of the one-min timer on the go side?
