### ISSUE TITLE
[Community Mint toke] Add notification when minting collectible process starts

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9849]
### Description
[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A479136&t=zs22ORYUVDYpqubQ-1)

![Screenshot 2023-03-13 at 10 24 08](https://user-images.githubusercontent.com/97019400/224659888-cde0ac75-1fb5-4e46-a781-c12987626f50.png)

**Comment by 0x-r4bbit** [comment]
@endulab let me know if you need help/pointers for this

**Comment by noeliaSD** [comment]
It can be extended for notifications in general. It should have some feedback too when there is something wrong in the process.
Maybe it is necessary to talk with design team about that.
