### ISSUE TITLE
[Community Mint Collectibles] Clarify which are the requirements for description field validation

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9850]
### Description
Clarify which are the requirements for description field validation.

Once this is clarified update UI accordingly.

Here the comment that pointed it out:  (Number 7) https://github.com/status-im/status-desktop/pull/9748#pullrequestreview-1327943865

**Comment by endulab** [comment]
Total finite supply - max 999 999 999

The symbol of the token is upper case (cannot be more than 5 characters)

Smart contracts can handle diacritics.

FYI @noeliaSD

**Comment by noeliaSD** [comment]
Here we should review the existing validation criteria in the UI for each field and update it according to requirements.

**Comment by alexjba** [comment]
> Total finite supply - max 999 999 999

OK:https://github.com/status-im/status-desktop/blob/04247158102adc0fc4c4d9238404405e54154b4c/ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml#L155

> The symbol of the token is upper case (cannot be more than 5 characters)

NOK - to be implemented

> Smart contracts can handle diacritics, so we also can. This should be tested.

NOK - to be implemented

**Comment by endulab** [comment]
**Non-latin signs**
If there are any non-latin characters in the token names and symbols in this token list https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/jab416171/uniswap-pairtokens/master/uniswap_pair_tokens.json then perhaps, if there are a lot of non-latin characters in the names and symbols in that token list then yes, if there are no non-latin characters in the names and symbols in that token list then no.
A more realistic token list would be:
https://tokenlists.org/token-list?url=https://uniswap.mycryptoapi.com/
https://tokenlists.org/token-list?url=https://gateway.ipfs.io/ipns/tokens.uniswap.org

**Comment by alexjba** [comment]
> **Non-latin signs**
> If there are any non-latin characters in the token names and symbols in this token list https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/jab416171/uniswap-pairtokens/master/uniswap_pair_tokens.json then perhaps, if there are a lot of non-latin characters in the names and symbols in that token list then yes, if there are no non-latin characters in the names and symbols in that token list then no.
> A more realistic token list would be:
> https://tokenlists.org/token-list?url=https://uniswap.mycryptoapi.com/
> https://tokenlists.org/token-list?url=https://gateway.ipfs.io/ipns/tokens.uniswap.org

Thanks, Will look into it.
At a first glance only latin characters, without diacritics are used for symbols and names.

But I see symbols with both upper and lower case and larger than 5 characters (`univ2OCEANETH`). Should we stick to the max 5 upper case characters rule?

And what about the description. Should we enforce the same character set?

**Comment by endulab** [comment]
@alexjba to make it easier, let's set the same set of characters. If there is a need we can enable diacritics later.

**Comment by John-44** [comment]
> @alexjba to make it easier, let's set the same set of characters. If there is a need we can enable diacritics later.
> 
> Re: Symbol. I saw somewhere requirement that the symbol should be max 5 characters. Technically it can be longer because it is a regular string. I also found this article: https://moralis.io/erc20-exploring-the-erc-20-token-standard/. According to it symbol can be of any length, however I think we should have some restrictions. Maybe we can increase the length of the symbol to 10.
> 
> FYI @John-44

Perhaps we should increate the length of the symbol to max 7 characters?  If we go longer, it starts having design implications and hopefully there should be very few with a symbol of more than 7 characters (most are 3 or 4 characters, a few are 5 and some 6, 7 or more are very rare I think)
