### ISSUE TITLE
`StatusScrollView` implicit size

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#9864]
@alexandraB99 @saledjenic @MishkaRogachev 
What's happening with `StatusScrollView` implicit size? 
We've been adding and removing it for several times 😄 

1. Was there with first implementation by @MishkaRogachev 
2. Removed by @alexandraB99 in https://github.com/status-im/status-desktop/pull/9337
3. Added by @igor-sirotin in https://github.com/status-im/status-desktop/pull/9427
4. Added by @saledjenic in https://github.com/status-im/status-desktop/pull/9384
5. Removed again by @alexandraB99 in https://github.com/status-im/status-desktop/pull/9469

My strong opinion is: 
**All QML components must have an implicit size set internally**

**Comment by MishkaRogachev** [comment]
I'm not aware of the recent changes, but from my perspective i agree with Igor

**Comment by saledjenic** [comment]
@igor-sirotin I am not sure what else to say/add as all I had is said in https://github.com/status-im/status-desktop/pull/9384 

I added those 2 lines back, cause as you can see popup was displayed without content, just header and footer. 

I don't have anything against if anybody removes those 2 lines again as long as that removal doesn't affect all popups we have.

**Comment by caybro** [comment]
I agree... this has caused so many headaches recently

(with a small footnote; anything derived from QtQuick.Control doesn't have to specify implicitSize; those are smart enough to deduce that based on its background/contentItem)

**Comment by igor-sirotin** [comment]
As discussed with @alexandraB99, we are commonly using `available` size, there comes a binding loop: 
```
implicitWidth 
> contentWidth 
 > contentItem.childrenRect.width 
  > availableWidth 
   > width 
    > implicitWidth
```

**Comment by igor-sirotin** [comment]
@iurimatias I'd keep this open and close this in 0.12-0.13. 
This will lead to a bug sooner or later. 

I don't think it needs any further discussion. Everyone agree on the points.
There should be `implicit` size. But we should add it carefully without binding loops.
