### ISSUE TITLE
Embed QR code scanner into "Sign in by syncing" workflow

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#9865]
### Description

"Sign in by syncing" onboarding workflow is implemented here:
- https://github.com/status-im/status-desktop/pull/9482

QR Scanner QML component is implemented here: 
- https://github.com/status-im/status-desktop/pull/9464

**Comment by igor-sirotin** [comment]
About freezing on MacOS: https://bugreports.qt.io/browse/QTBUG-108530
About exception when switching cameras: https://bugreports.qt.io/browse/QTBUG-108018

**Comment by anastasiyaig** [comment]
@jrainville could u please update the milestone?

**Comment by igor-sirotin** [comment]
@jrainville could we cherry pick this to 0.11?
It's not a big change, but without this local pairing is kinda incomplete and hard to use to sync with mobile.

**Comment by jrainville** [comment]
Changed the milestone to 0.11RC.
