### ISSUE TITLE
Chat: If you change only group chat color or name - msg that color and name will be displayed

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#9877]
# Bug Report

## Description

If you change only the group chat color or group chat name, both messages that color and chat name were changed will be displayed

## Steps to reproduce

1. Create a group chat with user B
2. User B changes group color or name

#### Expected behavior
You receive the message that group color or name have been changed

#### Actual behavior
You receive the message that group color and name have been changed

![image](https://user-images.githubusercontent.com/117639195/225016399-a6de95b9-a9e5-45e0-a9a6-1beebf81ea2a.png)

### Additional Information

- Status desktop version: 0.10.0-rc13
- Operating System: macos

**Comment by friofry** [comment]
does not reproduce


<kbd>
![Image](https://github.com/status-im/status-desktop/assets/1083341/b30797f1-bdca-4eb4-a4c2-6297133cf287)

</kbd>

**Comment by jrainville** [comment]
> does not reproduce ([f3bf194](https://github.com/status-im/status-desktop/commit/f3bf194187677557a6d2c90592780bb68b1f059f)):

I doubt this is the commit that fixed it :laughing: 

However, good  if the issue doesn't exist anymore. Closing.
