### ISSUE TITLE
Saved addresses: can't open [Saved addresses] table in DB when it is not empty

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9878]
### Description

1. install master
2. enable wallet
3. open DB and open `saved addresses` table there (https://www.notion.so/How-to-browse-sqlcipher-database-3300824d1d3242ec837bf8f99adeea33#d5cc2a4589194245ba2868459f7182bd )
4. go back to the app
5. add saved address, for example `0x0c1abEa67a72e94c167F63BF5220fAa08Ec0CDdE`
6. try to open the table again

As the result, the table content can't be viewed because the SQLite app crashes

**Comment by anastasiyaig** [comment]
@IvanBelyakoff maybe u saw this? I am not sure if this is an issue with the table itself or SQLite :D But i did not see any issues with other tables, makes me feel suspicious

**Comment by stefandunca** [comment]
@anastasiyaig I suspect the `DB browser for SQLite` MacOS app has an issue displaying some fields; it happened to me, also. However, browsing using the command line tool, `sqlcipher`, and the python library worked fine.

Please use the following command line instructions to browse the DB and validate if it is an debugging app problem: https://www.notion.so/How-to-browse-sqlcipher-database-3300824d1d3242ec837bf8f99adeea33?pvs=4#d5cc2a4589194245ba2868459f7182bd

**Comment by anastasiyaig** [comment]
thank u very much @stefandunca @IvanBelyakoff !
