### ISSUE TITLE
[Identity verification] Reply to an identity verification not shown when it comes from mobile

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9879]
# Bug Report

## Description

Found here: https://github.com/status-im/status-mobile/pull/15284#issuecomment-1465769591

If you reply to an identity verification question on mobile, the reply doesn't appear on desktop.

## Steps to reproduce

A: Desktop account
B: Mobile account

1. A sends identity verification to B
2. B responds to it

Expected:A can see the identity verification response
Actual: A cannot see the reply text. It can see there was an answer, but not the text

![](https://user-images.githubusercontent.com/97245802/224655704-c7dc4bb8-67f9-458b-a392-b8e9bfd77844.png)

**Comment by jrainville** [comment]
It might not be an actual API difference, it might just be that the identity verification flow is a bit broken on desktop. @MishkaRogachev do you know if it works currently?

**Comment by MishkaRogachev** [comment]
> It might not be an actual API difference, it might just be that the identity verification flow is a bit broken on desktop. @MishkaRogachev do you know if it works currently?

I tried identity verification a few weeks ago and it was working properly. But i'll check it tomorrow

**Comment by MishkaRogachev** [comment]
![telegram-cloud-photo-size-2-5402573747879270217-y](https://github.com/status-im/status-desktop/assets/2522130/1115928f-c5a6-43b1-b88e-4b5830ff26c1)
There is an error then i'm trying to reply via mobile client

**Comment by MishkaRogachev** [comment]
upd: tried one more time, same error
![image](https://github.com/status-im/status-desktop/assets/2522130/6b1e4c4e-daeb-4bfe-83f7-7e97450bc606)

**Comment by jrainville** [comment]
Moved to 2.30 since it's still not fixed on mobile and it's also not a priority for them
