### ISSUE TITLE
Opening or creating a message using the ‘Start chat’ button in a Community does not open the 1on1 chat in Messages

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9880]
Version: 0.10
OS: Windows 10

https://user-images.githubusercontent.com/124154641/225074268-2cb0a51d-854d-491b-b028-b8e34c531cb2.mp4

***

<ins>Steps to reproduce:</ins>
1. Navigate to any Community, click on the new chat icon.

2. Start a new 1on1 chat with a mutual contact, using the ‘start chat input field’.  

<ins>What currently incorrectly happens:</ins>

3. When the ‘Start new chat’ screen closes, the user incorrectly remains in the community screen. It appears to the user like the action has failed.

<ins>What is supposed to happen:</ins>

3. Once the user clicks confirm, the user should be instantly taken to the Messaging section with the contact (they added to a 1on1 chat using the ‘start chat input field’ in step 2) selected in the secondary nav, and the related chat history open in the body area.
&nbsp;

**Comment by caybro** [comment]
Yup, this is still broken; no debug or error messages in the console though :/

**Comment by caybro** [comment]
Correction: it works (the group chat is created) but the view is not switched to the Chat section!

**Comment by John-44** [comment]
> Correction: it works (the group chat is created) but the view is not switched to the Chat section!

Yes, the view not switching to the Messaging section is what needs to be fixed :-)

**Comment by borismelnik** [comment]
Yes guys, I found a problem, trying to understand how to fix it :)
