### ISSUE TITLE
Pasting a chatkey or profile URL of a user who is a mutual contact into the Start chat input field is broken

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9881]
Version: 0.10
OS: Windows 10

When a user pastes a chatkey or Status profile URL of a **mutual contact** into the ‘Start chat input field’ in the Messaging / Start chat or in a Community / Start chat screen, the autocomplete list of contacts (that appears beneath the ‘Start chat input field’) should be updated/filtered to only display the mutual contact who has that chatkey or Status profile URL. 

***

<ins>Steps to reproduce:</ins>

1. In Messages or in a Community, click on the ‘Start chat’ button

2. Paste a chatkey or profile URL of a user who **is** a mutual contact into the ‘Start chat input field’. 

<ins>What currently incorrectly happens:</ins>

3. Nothing currently happens!

<ins>What is supposed to happen:</ins>

3.  The autocomplete list of contacts (that appears beneath the ‘Start chat input field’) should be updated/filtered to only display the mutual contact who has that chatkey or Status profile URL.

https://user-images.githubusercontent.com/124154641/225079845-ef26b909-555f-438a-9609-e89fdeb8364f.mp4

&nbsp;

**Comment by caybro** [comment]
Already fixed in master afaik too

**Comment by borismelnik** [comment]
I can prove it works in latest master, but not always :) @jrainville I'll try to find a reason why its flaky.

**Comment by jrainville** [comment]
@imagiMary tells me she is able to reproduce in 0.12.0.RC1. Seems like we have a regression

**Comment by jrainville** [comment]
It does work for completely unknown contacts though

**Comment by imagiMary** [comment]
OS: Windows 10

I installed 0.12.0.RC1 from seed phrase so lost all my existing chats, then when I tried to paste in a user chatkey / profile URL of an existing mutual contact it didn't work. 

Here is a screencast :) : 

https://github.com/status-im/status-desktop/assets/124154641/9ab54b65-6bfc-4619-9910-2379619f1bbd

LOG: ERR 2023-05-12 16:16:55.507+01:00 get - bloom level is supported only for a waku version 1 topics="node-config-service" tid=6912 file=service.nim:111
ERR 2023-05-12 16:16:56.234+01:00 chat-view unexisting item id:              topics="chat-section-module" tid=6912 file=module.nim:457 itemId=0x047388a9028237eba395f8dc27abbc730dc63b061be4d5862bfbfb644c5adab0ef2d60eec99b9d44b9d75ed5edcdeb781d2591165b1cc2ed96446f4ddbc70a72ee methodName=activeItemSet

**Comment by borismelnik** [comment]
I faced another issue: If I try to paste the link of any contacts when community open it just jump to messaging section on the last opened chat view.

**Comment by imagiMary** [comment]
Had a call with @borismelnik yesterday to go over the issues and to summarise, this is the behaviour we want. 

Pasting a chatKey of an existing mutual contact into the `Start chat input field` should have the same behaviour as if a user searches for a contact by typing in their name into the `Start chat input field`.

The various scenarios it should cover:

**Creating a 1on1 chat:** 
User pastes a chatKey/URL of a mutual contact into the `Start chat input field` 
Clicks on the contact tile
The contact name is shown in the `Start chat input field`
User clicks `confirm` 
A new 1on1 chat is created and opens. 

**Existing 1on1 chat:** 
User pastes a chatKey/URL of a mutual contact into the `Start chat input field` 
clicks on the contact tile
The contact name is shown in the `Start chat input field`
User clicks `confirm`
The user is navigated to the existing 1on1 chat.

**Ad-hoc group chat:** 
User pastes a chatKey/URL of an existing mutual contact into the `Start chat input field`  
clicks on the contact tile
The contact name is shown in the `Start chat input field`
The user is then able to enter more mutual contacts/chatKeys/URLs into the `Start chat input field` to create an ad-hoc group chat. 

If we miss the step of selecting the contact tile and navigate straight to the 1on1 chat when a chatKey/URL is pasted into the `Start chat input field`, users will be unable to create Ad-hoc group chats using chatKeys/URL’s.

&nbsp;
