### ISSUE TITLE
Regression in 0.10 - pasting a chatkey or profile URL of somebody who is not a mutual contact into the Start chat input field is broken

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9883]
Version: 0.10
OS: Windows 10

When a user pastes a chatkey or status profile URL of somebody who is not a mutual contact into the start chat input field, nothing happens.

Expected behaviour - the add Sent Contact Request dialog should open. This functionality seemed to work in 0.9.

***

<ins>Steps to reproduce:</ins>
1. In Messages or Communities, click on the ‘Start chat’ button

2. Paste a chatkey or profile URL of somebody who is not a mutual contact into the ‘Start chat input field’. 

<ins>What currently incorrectly happens:</ins>

3. Nothing currently happens!

https://user-images.githubusercontent.com/124154641/225088303-b23893e1-ca73-41b3-8e4b-4aec2ffb6d0b.mp4

&nbsp;
<ins>What is supposed to happen:</ins>

3. The Send Contact Request dialog should open. 

 

https://user-images.githubusercontent.com/124154641/225088035-0f3302b3-91fa-4c98-b9b4-4b6889cbc4fd.mp4

&nbsp;

<ins>Other information</ins>

_Note:_ The new contact user information displayed in the Send Contact Request dialog needs to be updated. See my comment on issue (https://github.com/status-im/status-desktop/issues/8924#issuecomment-1464197290)  regarding adding a loading state to the Send Contact Request dialog.
&nbsp;

**Comment by caybro** [comment]
This is fixed in master already afaik

**Comment by borismelnik** [comment]
Can approve - it fixed in latest master. But we still have a problem with method which used for checking input and sometimes the signal isn't triggered by some reason. But in fact, pasting the url or chatkey works.
