### ISSUE TITLE
Ad-hoc group chats - uploading a group image does not work

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9884]
Version: 0.10
OS: Windows 10

***

<ins>Steps to reproduce:</ins>

1. Navigate to an ad-hoc group chat

2. Right click on the group chat in the secondary nav bar and open Edit group name and image dialog

3. Add a group image and save

<ins>What currently incorrectly happens:</ins>

4. The image is not saved and is not displayed in the ad-hoc message icon in the secondary nav bar or in the message icon in the header of the message body area. 

<ins>What is supposed to happen:</ins>

4. When the user clicks save, the image should be displayed in the message icon in the secondary nav bar and in the message icon in the header of the message body area. 

<ins>Other information</ins>

https://user-images.githubusercontent.com/124154641/225090587-fc4eab87-0b70-4b8b-94ec-5142e15df571.mp4

**Comment by caybro** [comment]
Any logs, error messages? Also, it would be imho much more valuable to hunt for these regression in master. There's ton of things that changed between 0.10 and now

**Comment by anastasiyaig** [comment]
it works to me in master @caybro @imagiMary

**Comment by caybro** [comment]
Seems to be broken just on Windows

**Comment by jrainville** [comment]
I'll check master on Windows later
