### ISSUE TITLE
Start chat input field auto scroll functionality broken

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9885]
Version: 0.10
OS: Windows 10

***

<ins>Steps to reproduce:</ins>
1. In Messages or Communities, click on the ‘Start chat’ button

2. Paste a profile URL (or enter a similar amount of characters) into the ‘Start chat input field’. 

3. Try to navigate to the beginning or end of the text entered into the ‘Start chat input field’ input field by:
- Left clicking and dragging the mouse pointer over the text
- Using the keyboard left or right arrows to move the caret past the end of the input field

<ins>What currently incorrectly happens:</ins>

4. Users are unable to auto scroll the content in the ‘Start chat input field’ be either: moving the caret with keyboard arrow keys, or by clicking and dragging a text selection area.  

<ins>What is supposed to happen:</ins>

4. Users should be able to auto scroll through the ‘Start chat input field’ by: 

- clicking and dragging a text selection area with their mouse pointer to the boundary of the input field
- or using the keyboard left or right arrows to move the caret past the end of the input field

<ins>Other information</ins>

https://user-images.githubusercontent.com/124154641/225091433-880a5ff4-5d23-4976-835b-373433c89a65.mp4

&nbsp;

**Comment by John-44** [comment]
> this was never working anyway - never specified for this component. @John-44 @benjthayer are we suppose to handle any kind of text there or it's only for filtering users list? if the latter, I don't see the need of having long strings there. other than this, pasting/typing anything else than the users names will not show/filter anything in the suggestions list.

@alexandraB99 users can also paste a chat key or a "Status user profile URL" (which contains a chat key) into this field to either A) sent that user a contact request (if they are not already a contact) or B) filter the autocomplete list of contacts to only show the contact that has that chat key (if the owner of the key pasted into that field is already a contact)

That's probably not the best description, see https://github.com/status-im/status-desktop/issues/9881 and https://github.com/status-im/status-desktop/issues/9883 which show the functionality I'm referring to.

**Comment by John-44** [comment]
@alexandraB99 this functionality was originally added via this issue back in August last year https://github.com/status-im/status-desktop/issues/7176
