### ISSUE TITLE
StatusQ: implement reusable CutomDerivationPath component and integrate it with add account modal

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#9890]
## UX designs: [Figma](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=12272%3A269494&t=Azd9N7EqsqerLIHx-0)

- Derivation path format: `m / <purpose>' / <coin_type>' / <account>' / <change> / <address_index>`
  - "Base"  contains: purpose, count type, account and change

## Validation steps

- Users can enter a maximum of 5 slashes
- The selected base path can't be edited
- In the `Custom` case, the control follows ETH standard and user can't alter the separators

#### Predefined derivation path

The user selects one of the available predefined bases

- Selection of predefined bases or switching to a custom derivation path is made by pressing the chevron that extends into a list (done externally)
- Have the base locked on selected blockchain from the [supported lists of blockchains](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=12272%3A266330&t=Azd9N7EqsqerLIHx-0)
  - The [address index part](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=12272%3A269494&t=Azd9N7EqsqerLIHx-0) should be editable
- The user can extend to more elements by pressing "space" and deleting using "backspace"
  - After every number (as long as the user hasn't already reached the 5 slash limit), if they press space, we will automatically add the apostrophe to the previous entered digit and add a slash. Good idea - if the user enters a number and then hits any slash instead of the space, we should add the apostrophe and slash.
- The user is not allowed to edit the hardened part (we're following `BIP-44`)
- The path should be selectable
- Allow editing any level as it's own input but process cursor moves to sides if allowed
  - the user should be able to use the arrow key to move the cursor to the beginning or end of any digit (and the middle of 2 numbers if a double digit number has been entered). If a user hits the left arrow when they are the start of a number, eg `22'/|23|` the cursor should hop over the apostrophe and slash and rest at the end of the preceding number (so after the second 2 in this example). The same behavior in reverse should be true if the user presses the right arrow.
- Deleting a number completely should just remove the number and leave the preceeding slash in place.
  - If the user then hits backspace again, it should delete the preceding slash and apostrophe. So `m/44'/60'/0'/0'/0|` [backspace] --> `m/44'/60'/0'/0'/|` [backspace] --> `m/44'/60'/0'/0|` etc.
- Remove duplicate slashes if number is completely deleted
  - If a user highlights a number in the middle of the derivation path we should remove any duplicate slashes eg: `m/44'/60'/0'/0'/0` (imagine 60 is highlighted) - user hits [backspace] --> m/44'/0'/0'/0|
- the user should be able to select and delete any part of the path. When they do so, we just need to remove any duplicate slashes and apostrophes
- User is allowed to enter an invalid character, we just validate it
- More info: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=12023%3A176201&t=N1bctCHrRhKgs8MO-4
- Clipboard pasting is not required

#### Custom derivation path

The user can select a custom derivation path

- Only the `purpose` is fixed to `BIP-44` and everything else can be changed using 

### Questions

- [x] list of predefined available path bases
  - [`MyEtherWallet`](https://medium.com/myetherwallet/hd-wallets-and-derivation-paths-explained-865a643c7bf2) list was mentioned in design
  - FOR MVP, only the ones listed in the design. Those are provided outside already.
- [x] In design, it is mentioned: "For MVP, we support a maximum of 5 slashes in the derivation path" Does that mean we can't derive grandchildren addresses?
  - Was confirmed by @benjthayer that we only allow one address index so no grandchildren
- [x] In the custom case, how do we know if the user is editing the `address_index` given the support for short addresses? Or do we not support short addresses for the custom case?
  - Allow 5 levels 
- [x] In [design](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=12272%3A265118&t=Azd9N7EqsqerLIHx-0) there is an error "Account number must be <100" when user selects "address_index" bigger than 100. Shouldn't this be "Address number must be <100" instead? The account is represented by the third element and usually `0`

#### Control Interface

After further discussions with @saledjenic the control will only support string editing and base path provided from out

```qml
CutomDerivationPath {
  required property string initialDerivationPath
  required property string initialBasePath

  readonly property string derivationPath
  readonly property string basePath  // Custom, Ethereum (default) ...
  readonly property string errorMessage // Account number must be < 100, Please enter numbers only

  function resetDerivationPath(string basePath, string newDerivationPath)
}
```

#### QML control

`StatusText` based

**Comment by saledjenic** [comment]
@stefandunca just for the reference, at the end this component will be integrated into work done in https://github.com/status-im/status-desktop/pull/9820

**Comment by stefandunca** [comment]
@glitchminer I merged the corresponding PR missing that it was not tested. Can you please have a look so I will avoid reverting it?
