### ISSUE TITLE
User can send second CR after canceling the first one

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#9901]
# Bug Report

## Steps to reproduce

1. Alice sends CR request to Bob
<img width="480" alt="Screenshot 2023-03-15 at 12 19 12" src="https://user-images.githubusercontent.com/2522130/225228878-56683934-992f-45ed-8f11-cd1d8790637c.png">

3. Bob declines Alice's CR
<img width="559" alt="Screenshot 2023-03-15 at 12 17 19" src="https://user-images.githubusercontent.com/2522130/225228529-e16c7b9c-e8e6-4136-91e5-e6360d59e3f0.png">

4. Alice cancels pending CR to Bob
<img width="631" alt="Screenshot 2023-03-15 at 12 16 42" src="https://user-images.githubusercontent.com/2522130/225228418-3ecfc287-0baf-4947-a0cd-0d2fe6321cb1.png">

5. Alice sends another CR to Bob
<img width="480" alt="Screenshot 2023-03-15 at 12 19 29" src="https://user-images.githubusercontent.com/2522130/225228926-94285e21-669f-43b9-bbb8-959decbe78eb.png">

6.  Bob receives second PR from Alice
<img width="569" alt="Screenshot 2023-03-15 at 12 20 25" src="https://user-images.githubusercontent.com/2522130/225229105-1429e88f-f060-428b-a7c7-bf649db09450.png">

**Comment by MishkaRogachev** [comment]
@John-44 here we need some pam protection

**Comment by John-44** [comment]
@MishkaRogachev I've just finished discussing with @xAlisher @benjthayer, to close this spam loophole with the least amount of work, we need to remove the ability for a user to cancel a contact request they have sent.  Happy to hop on a call to discuss.  cc @ilmotta

**Comment by ilmotta** [comment]
> @MishkaRogachev I've just finished discussing with @xAlisher @benjthayer, to close this spam loophole with the least amount of work, we need to remove the ability for a user to cancel a contact request they have sent. Happy to hop on a call to discuss. cc @ilmotta
> 
> So the change request is: remove the functionality that lets a user cancel a contact request they have sent

Sounds reasonable to me @John-44. There's also some work to be done on status-go, but it shouldn't be complicated. @cammellos, any concern about the new definition John is sharing?

**Comment by John-44** [comment]
@ilmotta @MishkaRogachev I just doublechecked with @cammellos and he can't see any reason why we can't remove the 'ability for a user to cancel a contact request they have already sent' functionality :-)

**Comment by ilmotta** [comment]
> @ilmotta @MishkaRogachev I just doublechecked with @cammellos and he can't see any reason why we can't remove the 'ability for a user to cancel a contact request they have already sent' functionality :-)

Great @John-44. I'll create an issue for `status-mobile` if one doesn't exist yet.

**Comment by MishkaRogachev** [comment]
> > @ilmotta @MishkaRogachev I just doublechecked with @cammellos and he can't see any reason why we can't remove the 'ability for a user to cancel a contact request they have already sent' functionality :-)
> 
> Great @John-44. I'll create an issue for `status-mobile` if one doesn't exist yet.

Maybe we just need to hide the UI for canceling contact requests and save functionality in states-go? For later propouses

**Comment by ilmotta** [comment]
> Maybe we just need to hide the UI for canceling contact requests and save functionality in states-go? For later propouses

Yes, we could do that. I usually err on the side of deleting zombie code, unless we're really sure we'll need this functionality and that it'll be similar to the existing solution in status-go. Simply because zombie code can have a non-negligible maintenance cost and we can go back in time with git in case we want to implement CR cancelling in the future.

**Comment by cammellos** [comment]
Hiding though won't really help, I think here the concern is mostly from automatic spam (i.e from status-go), someone clicking around on desktop is not going to be really a menace in terms of spam :)
