### ISSUE TITLE
[e2e] fix and reenable social links test scenario

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#9909]
currently tagged with `@mayfail`

_Originally posted by @noeliaSD in https://github.com/status-im/status-desktop/pull/9792#discussion_r1137290130_

**Comment by noeliaSD** [comment]
@glitchminer we can take profit of that to review the requirements, add them to notion in BDD format and reformulate the needed user stories.
@VladimrLitvinenko work together with @glitchminer to write the user stories and start the automation from there!

**Comment by noeliaSD** [comment]
BTW, here there is a new feature, drag/drop items in lists, so maybe we can take profit, as well, of it, to create some generic methods and extend our driver API.
