### ISSUE TITLE
Fallback to coingecko doesnt work

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#9910]
### Description

Get this error when turning off connection to cryptocompare

.marketManager.FetchTokenMarketValues =  fallback failed with 'Get "https://api.coingecko.com/api/v3/coins/list": dial tcp 127.0.0.1:443: connect: connection refused'. run error was 'Get "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=RHOC,WIBB,UKG,WETH,NEXO,TNT,OMG,XPA,SUSD,ENJ,HEZ,CENTRA,R,RLC,TIME,LXS,CFI,REQ,UBT,SNT,APPC,VRS,STORJ,MET,MCO,BTU,EDG,CRV,GRID,LEND,WINGS,DRT,CSNO,YEENUS,WBTC,PLR,AVT,ENS,DGD,ADI,MOKSHA,ZEENUS,MFG,FUN,UBI,ETH,EVX,MOC,MLN,DTA,EDO,DLT,USDP,TRST,RCN,USDT,RAE,AKRO,KNC,MOD,ENG,ROL,TRX,UPP,ABYSS,SNX,POLY,SPN,SPIKE,SPANK,AST,BLT,XRL,USDD,WABI,GLM,DPY,MDS,SNM,AMPL,MTL,XDATA,LOOM,POE,VGX,ZRX,COB,SAI,TAUD,LRC,WTC,NMR,PRG,OTN,KIN,ICN,POWR,BAL,GRT,RARE,BNT,SNT,SALT,LPT,IOST,NPXS,AUSDC,ELF,HST,FRAX,DGX,COMP,XEENUS,ADX,STX,VERI,TAAS,QKC,BAT,CND,REP,EOS,ANT,HT,EKO,BNB,BUFF,DAI,GNO,SAN,1ST,USDS,SUB,QSP,DNT,UNI,XAUR,BRLN,BAND,OGN,QRL,PPT,FXC,DCN,VIB,GEN,USDC,LINK,MTH,LINK,DAT,ETH2X-FLI,MGO,ZSC,TUSD,GNT,AE,AMB,BLZ,MANA,STORM,BTM,SNGLS,PT,ABT,CDAI,ATM,MKR,ICOS,FUEL,TGBP,PAY,RDN,REN,PAXG,PPP,TCAD,WGN,OXT,SOCKS,MDA,TKN,TGT,HND,CDT,CVC,ST&tsyms=USD&extraParams=Status.im": dial tcp 127.0.0.1:443: connect: connection refused'

**Comment by iurimatias** [comment]
closing since this task is in the done state
