### ISSUE TITLE
Pairing devices result doesn't show Synced device info

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#9930]
Blocked by https://github.com/status-im/status-go/pull/3248

# Bug Report

## Description

After a successful pairing a new device, there's a result popup.
It's expected to see a "Synced device" info on the top, and all other synced devices under.

Currently it's impossible to implement, because during syncing no `isntallation` info is shared, so the device doesn't know which other device was synced. It should be possible to implement after https://github.com/status-im/status-go/pull/3248.

<img width="1312" alt="Снимок экрана 2023-03-17 в 15 17 47" src="https://user-images.githubusercontent.com/25482501/225823576-3037a5a8-2808-4e8b-b794-4cadc1a925ab.png">

## How it should be

Figma link:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1592%3A129653&t=7txyUMm5KE2EPQMx-4

<img width="771" alt="image" src="https://user-images.githubusercontent.com/25482501/225824426-a333dbcf-2ab3-4d6d-ad94-c2d591dfb47b.png">

**Comment by Samyoul** [comment]
> Currently it's impossible to implement, because during syncing no isntallation info is shared, so the device doesn't know which other device was synced.

@igor-sirotin what version of `status-go` are you building against? This functionality should already be present in `status-go.develop`

https://github.com/status-im/status-go/blob/fe4e079beace708bbc96c08b14aafd18e08e8163/server/pairing/server.go#L129-L138

```go
func (s *Server) startReceivingData() error {
	s.SetHandlers(server.HandlerPatternMap{
		pairingReceiveAccount:    handleReceiveAccount(s),
		pairingChallenge:         handlePairingChallenge(s),
		pairingSyncDeviceReceive: handleParingSyncDeviceReceive(s),
		// send installation data back to sender
		pairingSendInstallation: handleSendInstallation(s), // <--- Here
	})
	return s.Start()
}
```

https://github.com/status-im/status-go/blob/fe4e079beace708bbc96c08b14aafd18e08e8163/server/pairing/server.go#L140-L154

```go
func (s *Server) startSendingData() error {
	err := s.Mount()
	if err != nil {
		return err
	}

	s.SetHandlers(server.HandlerPatternMap{
		pairingSendAccount:    challengeMiddleware(s, handleSendAccount(s)),
		pairingChallenge:      handlePairingChallenge(s),
		pairingSyncDeviceSend: challengeMiddleware(s, handlePairingSyncDeviceSend(s)),
		// receive installation data from receiver
		pairingReceiveInstallation: challengeMiddleware(s, handleReceiveInstallation(s)), // <--- Here
	})
	return s.Start()
}
```
