### ISSUE TITLE
Removing a contact - impact on direct message with removed contact

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#9935]
New flows have been created to show what happens to a direct message between 2 mutual contacts when one of the contacts is removed by the other user.

This includes:

1) What each user sees in the **direct message** when the mutual contact status is broken by a user removing a contact.
2) What each user sees in **Settings --> Messaging** "".

The flows cover both sides - i.e. that of the user that is removing a contact and that of the user that is being removed as a contact.

At a top level these flows show the following. More detail shown in the Figma:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=27345%3A528266&t=Sbf403yQU7eCWl0X-4

From the perspective of the user removing a contact:
Contact is removed via the profile menu:
<img width="1440" alt="01" src="https://user-images.githubusercontent.com/110033914/225896317-ea25fe15-c3b3-4747-80ac-6811ab5d9b32.png">

Confirmation of removal dialog:
<img width="1440" alt="02" src="https://user-images.githubusercontent.com/110033914/225896467-4a643f83-9d6c-406c-bebe-edbe0e38caa0.png">

When the user has been removed as a contact, the direct message state changes to show: 
- A toast confirming the removal of the contact
- A system message at the base of the message feed confirming the removal of the contact with a CTA to send a fresh contact request
- Message input becomes disabled with updated placeholder text prompting the user to add the user as a contact in order to message them
<img width="1440" alt="03" src="https://user-images.githubusercontent.com/110033914/225896779-0ca1fdab-c6ef-4ad8-a556-921444a4e24a.png">

From the perspective of the user that has been removed:
<img width="1440" alt="04" src="https://user-images.githubusercontent.com/110033914/225900527-289f6ace-8e63-4ca2-a9de-68854b77f9f0.png">

**Comment by anastasiyaig** [comment]
@glitchminer please check this out ^

**Comment by MishkaRogachev** [comment]
partially resolved in https://github.com/status-im/status-desktop/pull/9902

**Comment by MishkaRogachev** [comment]
@benjthayer this designs requires to have a new type of messages: events when two contacts become actually mutual and when one of contacts has removed another. Would you mind if i separate those two issues?

**Comment by benjthayer** [comment]
Hey @MishkaRogachev absolutely, please do dissect the task in however way you wish and however makes sense :) Thanks for taking a look at this one!

**Comment by MishkaRogachev** [comment]
@benjthayer quick question: if we have pending CR from non-contact, should not we replace "Send Contact Request" button with "Accept Contact Request" ?
<img width="1345" alt="Screenshot 2023-04-25 at 00 27 36" src="https://user-images.githubusercontent.com/2522130/234109199-52e45ecf-eca2-4268-9706-036bcd762c57.png">

**Comment by MishkaRogachev** [comment]
@benjthayer @John-44 here is the video with my proposition of chat button states. It seemed a bit counterintuitive to me that the button available only for sending CR. But i'm not a designer, it's just a suggestion :)

Uploading Screen Recording 2023-04-26 at 10.29.42.mov…

**Comment by MishkaRogachev** [comment]
UPD: accept & reject actions: 
<img width="1015" alt="Screenshot 2023-04-26 at 13 14 45" src="https://user-images.githubusercontent.com/2522130/234530009-5bc182b3-a734-4a51-b5ec-3082a881a0c9.png">

**Comment by John-44** [comment]
> Hey @MishkaRogachev that makes sense to me - I think this is just something we didn't cover in the designs.
> 
> So basically, if I am no longer a contact with someone I have been chatting with, if I go back into the chat when that user has sent me a fresh contact request, I see an accept contact request button as opposed to the send contact request button.
> 
> I think that adds a nice level of efficiency to the flow in that instance as opposed to them having to go to the notification centre and it avoids them sending a 'duplicate' contact request to the counterparty when they have already sent a contact request their side.
> 
> What do you think @John-44 ?

Makes sense to me as well :-)
