### ISSUE TITLE
Crash on app close from login page

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#9937]
# Bug Report

## Description

Crash on app close from the login page

```
/Users/mprakhov/Work/status/status-desktop/src/nim_status_client.nim(181) nim_status_client
/Users/mprakhov/Work/status/status-desktop/src/nim_status_client.nim(154) mainProc
/Users/mprakhov/Work/status/status-desktop/src/app/boot/app_controller.nim(275) delete
/Users/mprakhov/Work/status/status-desktop/src/app_service/service/general/service.nim(43) logout
/Users/mprakhov/Work/status/status-desktop/src/backend/general.nim(27) logout
/Users/mprakhov/Work/status/status-desktop/vendor/nim-status-go/status_go.nim(138) logout
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [run-macos] Error 1
```

## Steps to reproduce

1. Open the Status app
2. Close the app from the login page
![image](https://user-images.githubusercontent.com/117639195/225903833-52401786-5189-47f7-910c-50e09b3878b9.png)

#### Expected behavior

App closes successfully

#### Actual behavior

App crashes on close

### Additional Information

- Status desktop version: master build, latest
- Operating System: macos

**Comment by iurimatias** [comment]
fixed in the meanwhile
