### ISSUE TITLE
[Airdrop] Hide `Assets` tab in `HoldingsDropdown` until we can airdrop also assets

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9938]
### Description

Only show collectibles tab, without header.

[Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22628%3A493690&t=9YYh8bbYxML7AoXu-1)

![Screenshot 2023-03-17 at 13 25 10](https://user-images.githubusercontent.com/97019400/225903981-182ed345-6d66-4656-90ca-f306a5151436.png)

**Comment by xAlisher** [comment]
@noeliaSD option for empty collectible list https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=27403%3A533014&t=mPy6Bd0kXC60vl88-1 
![image](https://user-images.githubusercontent.com/7700914/226355903-901ad1fc-f02b-49d5-b5d9-31edeb100d4f.png)
