### ISSUE TITLE
Support fetching Community collectibles

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#9941]
Collectibles used for community access do not follow the standard `tokenURI` metadata format. That means OpenSea will return empty metadata and won't provide the link.
In such cases, we need to get the `tokenURI` by interacting with the contract (see https://docs.infura.io/infura/tutorials/ethereum/retrieve-and-display-erc-721-and-erc-1155-tokens). Prefer Pokt, use Infura as fallback.
Our `tokenURI` will contain some sort of identifier for the corresponding community. We must then fetch the metadata and the image from Waku. Gonna need some help with this last part @0x-r4bbit @endulab

**Comment by 0x-r4bbit** [comment]
> Our tokenURI will contain some sort of identifier for the corresponding community. We must then fetch the metadata and the image from Waku.

Community collectibles live inside a community's `CommunityDescription` (a waku payload) as `CommunityTokensMetadata`.
We already add token metadata for community tokens to `CommunityDto`s in desktop.

So all we'd have to do is the following:

Request the tokeUri from the NFT (which is not an actual Uri but a communityId).
Use community Id to check if it already exists in `communitiesService`, if not, we fetch community data. The function for fetching community data is:

```nim
  proc requestCommunityInfo*(self: Service, communityId: string, importing = false) =

    try:
      let arg = AsyncRequestCommunityInfoTaskArg(
        tptr: cast[ByteAddress](asyncRequestCommunityInfoTask),
        vptr: cast[ByteAddress](self.vptr),
        slot: "asyncCommunityInfoLoaded",
        communityId: communityId,
        importing: importing
      )
      self.threadpool.start(arg)
    except Exception as e:
      error "Error requesting community info", msg = e.msg, communityId
```

This will cause the node to receive a community description, which then results in a community object being created and added to the service.

Once the community exists in the service, we can use its `communityTokensMetadata` to locate the token we're interested in, and access its `image` which should be a base64 encoded string.

Hope this helps!

**Comment by dlipicar** [comment]
Thanks for the info @0x-r4bbit , that should be enough to get the data I need. One question though, I was hoping I could fetch everything I needed on the status-go side before returning the list of collectibles to the client. Is it the same from your POV if I call `func (m *Messenger) RequestCommunityInfoFromMailserver(communityID string, useDatabase bool) (*communities.Community, error)` instead of doing it on the NIM side?

**Comment by 0x-r4bbit** [comment]
Yes, that'd be the same.
So essentially you'd move the entire logic a level up to status-go.

**Comment by dlipicar** [comment]
Do we have some util or some way of knowing if any string is a valid communityID?

**Comment by 0x-r4bbit** [comment]
Any ECDSA pubkey is a valid communityID. I believe the only validity function we have is 

```nim
proc isCompressedPubKey*(strPubKey: string): bool =
  return strPubKey.startsWith("zQ3") and allCharsInSet(strPubKey, CompressedKeyChars)
```

But if I remember correctly we don't process community IDs in its compressed form.
So if you want to check for uncompressed validity, I think you'll have to add a function that does similar checks (if characters are legit + key length), or you try to convert the key you have to a compressed one for, but then it should be a valid compressed one by definition

**Comment by dlipicar** [comment]
For testing purposes, do we have an account that:
- Holds one of our NFTs
- The `tokenURI` for that NFT is a valid `communityID`
- The `CommunityTokenMetadata` for that `communityID` contains metadata for said NFT
?

**Comment by endulab** [comment]
> For testing purposes, do we have an account that:
> 
> * Holds one of our NFTs
> * The `tokenURI` for that NFT is a valid `communityID`
> * The `CommunityTokenMetadata` for that `communityID` contains metadata for said NFT
> 
> ?

@dlipicar I will mint today correct contract.
