### ISSUE TITLE
Community encryption should automatically switch on/off depending on community permissions

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#9942]
**This is a feature for the 0.12 release**

-- Change request --

1. remove the "Encrypt community" toggle from the "Create community" and "Edit community" screens

2. If the community is an open community (e.g. there are no token permissions to become a member at the community level) then community encryption should automatically be Off

3. If a community is a closed community (e.g. there are token permissions to become a member at the community level) then community encryption should automatically be On

4. If an open community becomes a closed community (e.g. if a token permission to become a member at the community level is added) than community encryption should automatically be switched On

5. If a closed community becomes an open community (e.g. if all token permissions to become a member at the community level are deleted) then community encryption should automatically be switched Off 

cc'ing @iurimatias @jrainville

**Comment by mprakhov** [comment]
Have a questions
1. Communities can be marked on creation as encrypted, but I can't make the community encrypted during the edit mode or remove encryption from them if they were created
Does it mean that the encryption mode can't be changed after the community creation?

If yes, then:
- we must allow set permissions on community creation, not after (right now we create a community and only after that setting up permissions)
- switching from closed community to open and backward won't change the encryption settings (steps 4 and 5 from the ticket description)

If the encryption mode can be changed after the community creation: 
The request to join option must be set up to make the community encrypted (without the request to join option you can't make a community encrypted). 
2. If the user switches from closed community to open - should we keep the request to join option active?
3. If the user switches from open community (without request to join) to closed - the request to join option must be activated. But if we switch back? Do we restore the open community setting and disable the request to join?

cc @John-44, @imagiMary, @jrainville

**Comment by mprakhov** [comment]
@cammellos if you have a possibility, I would appreciate the help

**Comment by cammellos** [comment]
@Samyoul could you please look into this? They need an endpoint to toggle community encryption (it should be enough to set `encrypted` to `true` or `false` and republish the community)
Thank you

**Comment by Samyoul** [comment]
Np @cammellos . Presumably I can add a new API endpoint with a method doing something like below:

```go
SetCommunityEncryption(CommunityID string, usesEncryption bool) error {
   // Get Community
   // Check usesEncryption is different to Community's value
   // If not different return
   // if usesEncryption true:
   //   🪄 The magic that encrypts a community
   // Else:
   //   🧙 The magic that decrypts a community
   // Republish the community.
}
```

**Comment by mprakhov** [comment]
@Samyoul could you please give some updates on where an API will be ready and merged?

**Comment by Samyoul** [comment]
@mprakhov This is the PR https://github.com/status-im/status-go/pull/3417 . I'm adding tests and it'll be ready for review. So hopefully can be merged today / Monday

**Comment by benjthayer** [comment]
Hey @anastasiyaig I wasn't involved in the discussions around removing the checkbox so will leave for @John-44 to confirm :)
