### ISSUE TITLE
1x1 chat: removing custom picture is not reflected on contact's side

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9947]
### Description

1. open app
2. add mutual contact
3. open chat with this contact
4. set custom user picture for yourself and save
5. make sure the picture is shown for your contact
6. delete the custom picture from your profile to have default one
7. check contact's chat

As result, the contact is still seeing custom picture , even it was removed

<img width="1917" alt="Screenshot 2023-03-20 at 16 03 51" src="https://user-images.githubusercontent.com/82375995/226346959-09d5ab66-f753-41d6-a7f6-cc041d849950.png">

**Comment by kounkou** [comment]
Hi, 

I had a first look at the issue, and managed to reproduce the issue
by following the steps given in the description.
This ticket involves the following function :

```
proc deleteIdentityImage*(keyUID: string): RpcResponse[JsonNode] {.raises: [Exception].} =
  let payload = %* [keyUID]
  result = core.callPrivateRPC("multiaccounts_deleteIdentityImage", payload)

...

proc deleteIdentityImage*(self: Controller, address: string) =
  self.profileService.deleteIdentityImage(address)
```

At first glance, there is a pull or push mechanism for status clients which involves pulling the new image or if there's no new images, set the default image for the contact.
However, this action doesn't happen.

I believe, I am missing some elements to fix this ticket at optimal speed, I will take some 1 more day than expected to make sure I understand the details before starting a fix.
I communicated to @iurimatias about this proposal.

**Comment by kounkou** [comment]
From my testing, I have noticed that when I perform the image replacement of the Profile image, I receive a message that is sent that the contact code


Example : 

```bash
map[{0x04c429330e366166687319c372775b39a917352e1af7f1510bf0a7a7805f7a2597030753529f3ff5e55b5a27c1d0be154312fa924532ac2ad005ed403223a43e9b-contact-code 7692f12c2a0093997319247c6fdab3e044f078d11cb6180da1e57c04826cc670 696540e50b67789173e875e0f48e68d920d28c9c2df9b602769434ee15bc8029 false 04c429330e366166687319c372775b39a917352e1af7f1510bf0a7a7805f7a2597030753529f3ff5e55b5a27c1d0be154312fa924532ac2ad005ed403223a43e9b  [137 94 6 90] false false true false 0}:[0x1c003bb2840]]
```

But nothing is received when deleting the image on the profile. So the problem seems to be that the remove image doesn't notify anything therefore causing the issue.
I put a log in the RetrieveAll() function to observe all messages.

https://github.com/status-im/status-go/blob/a8357dceacd1b737952660272bf80251df19b8f8/protocol/messenger.go#L3255

**Comment by kounkou** [comment]
Step 1 : 
Added a code to trigger the publishing of a message when the user does the delete of the profile image. The profile image delete was merely a delete of the image inside the database, but didn't trigger anything. Now we will publish a message that should be caught in Step 2

Step 2 : 
Once Step 1 sent the message to delete the profile image, the application will reset the image.
