### ISSUE TITLE
[Chat history] Missing message header after new member announcement

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#9948]
# Bug Report

## Description
When adding a new member to a chat there will be a message like: `@username has added @newmemberusername`. 
The first message after this announcement has no header

## Steps to reproduce
1. Start a chat with user A & B. User A writes a message
2. B adds a new member
3. B sends a new message

#### Expected behavior
The message from step 3 has a message header
#### Actual behavior
The message from step 3 has no header
### Additional Information
<img width="1220" alt="Screenshot 2023-03-20 at 15 30 14" src="https://user-images.githubusercontent.com/47811206/226357155-9d987f2a-0ee1-45eb-866e-271aa52cb831.png">

- Status desktop version:0.10
- Operating System:MacOs

**Comment by mprakhov** [comment]
please, retest on the latest master branch, was fixed in scope of https://github.com/status-im/status-desktop/issues/9827 ticket
