### ISSUE TITLE
ActivityCenter: Process album of images

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#9951]
### Description

In fact of implementation album of images, need to process jump (or display albums correctly) from AC notification to source message with album.

Also, need design.

https://github.com/status-im/status-desktop/pull/9744#issuecomment-1471023835

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/10409

**Comment by borismelnik** [comment]
Works in `latest master`.

**Comment by jrainville** [comment]
I reopened this once because it doesn't work. I don't think it ever worked. Do we even have designs for images in the AC cc @benjthayer

**Comment by borismelnik** [comment]
@jrainville What do you expect there? there was an issue to jump on the message from AC. We don't have a design for it.

**Comment by jrainville** [comment]
> @jrainville What do you expect there? there was an issue to jump on the message from AC. We don't have a design for it.

We need to show images in the AC in the case where someone replies to you with an image or mentions you in a message with an image.

I checked and we don,t have a design for that yet.

**Comment by benjthayer** [comment]
Hey @jrainville @borismelnik I've done the designs for the 2 missing AC list items relating to:

1) when someone replies to you with an image 
2) when someone mentions you in a message with an image

Figma designs:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=36732-623659&mode=design&t=NZ5Je4z8k0w2miTJ-4

If you could let me know when/if you are happy with these, I can move them out of the `Testing Ground` area of the file and into `🔔 S-Activity center` and add these as notification centre component variants. Thanks :)

**Comment by jrainville** [comment]
@benjthayer looks good! If there is an image we haven't received yet, should we should the Loading component in the AC as well?

**Comment by benjthayer** [comment]
> @benjthayer looks good! If there is an image we haven't received yet, should we should the Loading component in the AC as well?

Thanks @jrainville ! Yeah that makes sense to me - I think that would be particularly important in the instance where the user has replied to a message with only an image (no text). In that scenario we need to show the fetching / loading state of the image in order to show anything at all in the notification centre item.

**Comment by benjthayer** [comment]
@jrainville @borismelnik these new notification centre items have now been added to the notification list item component in the relevant place in the Kuba file:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=1424-327656&mode=design&t=NZ5Je4z8k0w2miTJ-4
