### ISSUE TITLE
Move Gif models out of the input_area module

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9952]
### Description

Right now, the gif models are inside the `input_area` module. However, there is an `input_area` module created for each channel in the backend. That means that  we have the gif models multiple times in the backend.

This feels pretty useless, since there are few reasons to have a different state for each channel. The only thing that could differ is if you want to keep the search for the chat, but that's very minor.

On the other hand, it creates a a lot of useless memory usage, because each time you load a gif popup on  a different channel, we keep that model in memory. Also, we fetch the favorites, recents, etc. for each of them instead of reusing.

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone, however this could be done in the stabilization period with other refactors if there is room
