### ISSUE TITLE
Replies: Process album of images

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#9957]
### Description

Display albums of images correctly in replies. Also need design.

https://github.com/status-im/status-desktop/pull/9744#issuecomment-1471023835

UPDATE: [DESIGN](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=21897-652945&t=C86xzGkQu1rYGjXL-4)

**Comment by borismelnik** [comment]
@John-44 can you help with design? Do we have already have it?

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-desktop/issues/10409
