### ISSUE TITLE
An infinite number of `getTransfersAddressChainID` requests were made 

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#9960]
Open the app with few wallet accounts (I had 5 - 25 accounts added always), make wallet section as active one.

There is no rule when the app will start doing `getTransfersAddressChainID` requests in a loop, sometimes it's from the very first app start, sometimes after some time (min - few mins), sometimes it's after adding a new account. This it the log I saw (repeated an infinite number of times):

```
ERR 2023-03-17 14:06:50.634+01:00 rpc response error topics="rpc" tid=8770945 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getTransfersByAddressAndChainID, code:-32000, message:fallback failed with \'429 Too Many Requests: {\"jsonrpc\":\"2.0\",\"id\":1345,\"error\":{\"code\":-32005,\"message\":\"daily request count exceeded, request rate limited\",\"data\":{\"rate\":{\"allowed_rps\":1,\"backoff_seconds\":30,\"current_rps\":23.366666666666667},\"see\":\"https://infura.io/dashboard\"}}}\'. run error was \'hystrix: circuit open\' ]\n" 
DBG 2023-03-17 14:06:50.490+01:00 [threadpool task thread] initiating task topics="task-threadpool" tid=8770945 file=threadpool.nim:48 messageType=LoadTransactionsTaskArg:ObjectType threadid=8770945 task="{\"$type\":\"LoadTransactionsTaskArg:ObjectType\",\"chainId\":42161,\"address\":\"0x5859cf66c8f881fdbfa12a289774ea2af9df2186\",\"toBlock\":\"0\",\"limit\":20,\"collectiblesLimit\":200,\"loadMore\":true,\"allTxLoaded\":false,\"vptr\":105553125281760,\"slot\":\"onTransactionsLoaded\",\"tptr\":4516215792}" 
```

**Comment by alaibe** [comment]
Cannot reproduce: possible reason is that the new add account flow didn't have yet all feature enable

**Comment by glitchminer** [comment]
Attempted with 7 accounts. I did not see the error.

@saledjenic, given the error in the description is mentioning a daily rate limit, is it possible it's ending up in a loop when those conditions occur?
