### ISSUE TITLE
After being unbanned, a user needs to restart the app to be able to re-request access

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9975]
# Bug Report

## Description

As found here (7.) https://github.com/status-im/status-desktop/pull/9829#issuecomment-1476829198

If a user is banned, he will see a grayed out button. If he gets unbanned, he should see the normal blue button to request, but he can't until he restarts

## Steps to reproduce

1. A is owner of a community
2. Request access with user B
3. A accepts B
4. A then bans B
5. B is now banner and sees the gray button
6. A unbans B
7. B still sees the gray button
8. B restarts
9. B now sees the normal request button

#### Expected behavior

B shouldn't have to restart. A signal should be sent to say they were unbanned.

### Additional Information

- Status desktop version: master `8d955265dccaf3feec69ee675a3c3c48a05967d2`

**Comment by iurimatias** [comment]
moved to 0.14

**Comment by shinnok** [comment]
Hi @jrainville,

I cannot reproduce this bug, unless I'm taking the wrong steps. Please double-check to confirm either way.

https://github.com/status-im/status-desktop/assets/544446/6c755f9c-645b-49a8-8a79-b3ec4acf1be8

**Comment by jrainville** [comment]
I can't reproduce either. I guess it was fixed in the meantime. Probably with all the new changes to pending requests.
Closing
